### ISSUE TITLE
Rocky Linus requires docker installation

### ISSUE THREAD

**Issue by RobertMolenda** [jhipster/generator-jhipster#28141] opened 2024-12-08 14:25 UTC
As previously documented in ticket 

https://github.com/jhipster/generator-jhipster/issues/27435

I've upgraded to the latest release - 8.7.3 - and this still continues to fail with the following setup:

Create new application as mentioned in the previous ticket:

Production DB = Postgres / Development = H2 - Fails - same as before

Production DB = Oracle / Development = H2 - Fails with slightly different error of:
"No Docker Compose file found in directory <project directory>/. 

Installation instructions do not state that 'docker is required to build / run' app...

Kindly advise
Best
Robert

**Comment by mshima** [comment] 2024-12-08 16:51
https://github.com/jhipster/generator-jhipster/pull/28142 proves it's working as expected.
It may be a Spring Boot issue since main is using v3.4.0.

Closing since a reproduction was not passed in issue description.

**Closed by mshima** 2024-12-08 16:51 UTC
Labels: area: triage, theme: undefined

**Comment by atomfrede** [comment] 2024-12-08 16:58
@RobertMolenda Just to make it clear, we use the default [spring boot docker compose integration ](https://www.baeldung.com/docker-compose-support-spring-boot) to ease development. As always with boot (and jhipster) you can configure it differently in particular for production (as you mentioned it in the other issue). So if you want to step back from any docker usage, you can do so by setting  `spring.docker.compose.enabled` to `false`. This would need to configure all database urls manually afterwards.
