### ISSUE TITLE
i created  a Jhipster Application with React as frontend ,and used Keycloak ,but when i run my Application with local keycloak and accessing my entites ,it is showing "you are not authorized to access this page"t 

### ISSUE THREAD

**Issue by shanmukakondaveti** [jhipster/generator-jhipster#15343] opened 2021-06-16 02:13 UTC
``

##### **Browsers and Operating System**

- [ ] Checking this box is mandatory (this is just to show you read everything)

![Screenshot (112)](https://user-images.githubusercontent.com/83701275/122147406-76d40000-ce76-11eb-8c50-6bcab1f44f12.png)
`

**Comment by shanmukakondaveti** [comment] 2021-06-16 02:15
![Screenshot (114)](https://user-images.githubusercontent.com/83701275/122147552-c286a980-ce76-11eb-8e72-7470cdb197be.png)
![Screenshot (115)](https://user-images.githubusercontent.com/83701275/122147559-c4506d00-ce76-11eb-8ef4-74c1dd040051.png)
![Screenshot (116)](https://user-images.githubusercontent.com/83701275/122147561-c4e90380-ce76-11eb-89c5-56ee201711e1.png)

**Comment by shanmukakondaveti** [comment] 2021-06-16 02:16
![Screenshot (117)](https://user-images.githubusercontent.com/83701275/122147661-f235b180-ce76-11eb-948a-6edc3a681b2f.png)

**Comment by shanmukakondaveti** [comment] 2021-06-16 02:17
please,help me,i am running my local keycloak here...

**Comment by atomfrede** [comment] 2021-06-16 05:04
Can you please follow the issue template? Otherwise no one will be able to provide any help.

**Comment by mraible** [comment] 2021-06-16 05:14
Yes, we need your JDL to reproduce the problem. I'm guessing it's because you're using your own instance of Keycloak and not JHipster's. If you run JHipster's pre-configured Keycloak in a Docker container (with `docker-compose -f src/main/docker/keycloak.yml up -d`), it imports JHipster users, apps, and configuration. 

I'm not sure if we have a guide on how to set up Keycloak with JHipster's expected settings from scratch. Maybe you can import them as our Docker container does? You can find them at https://github.com/jhipster/generator-jhipster/tree/main/generators/docker-compose/templates/realm-config.

**Comment by shanmukakondaveti** [comment] 2021-06-16 05:25
thanks matt raible for your response ,what to do with those json file in that github, i am  begginer ,please help me here...

**Comment by mraible** [comment] 2021-06-16 05:36
If you're a beginner, I'd recommend using the Keycloak instance that JHipster ships with. No reason to complicate things if you're just learning! 🙂

**Comment by shanmukakondaveti** [comment] 2021-06-16 10:35
hii Matt raible,in my jhipster Application i am not getting UserManagement  in Administration tab,how to get it?

**Comment by vishal423** [comment] 2021-06-16 11:09
As you have selected OIDC (`Keycloak`), the `User Management` code is not generated for you as that should be managed on the IDP side.

**Comment by shanmukakondaveti** [comment] 2021-06-16 12:43
so how can we add users in jhipster using keycloak?,how to write an api in jhipster to create user with  some role(user),and that user stored in keycloak as well as jhipster user database

**Comment by vishal423** [comment] 2021-06-16 12:53
As per current logic, the user sync from `IDP` to `JHipster` happens after successful authentication on JHipster side.

**Comment by atomfrede** [comment] 2021-06-16 12:53
When using oauth/keycloak keycloak is the leading system to manage users. They are synced after first authentication.

**Comment by pascalgrimaud** [comment] 2021-06-16 13:08
@shanmukakondaveti : it's not something generated by JHipster, but you can code it yourself. It's pretty simple, I did it for my customer. You need to import:

```xml
        <dependency>
            <artifactId>keycloak-admin-client</artifactId>
            <groupId>org.keycloak</groupId>
            <version>${keycloak.version}</version>
        </dependency>
```

Then, you need to add all the logic, related to the call with Keycloak Client, provided by this library.

As there is no bug on our side, I'm closing this ticket.

**Closed by pascalgrimaud** 2021-06-16 13:08 UTC
Labels: area: triage, theme: undefined

**Comment by shanmukakondaveti** [comment] 2021-06-16 13:45
hey pascalgrimaud, can you please any reference  on how to create user(shanmuka) with admin role and access our application,how to write client for keycloak ?

**Comment by pascalgrimaud** [comment] 2021-06-17 07:18
@shanmukakondaveti : Do a search on Google, Stackoverflow, Git, related to keycloak-admin-client, you should find some code/documentation which can help you. Have a loot at https://gist.github.com/thomasdarimont/c4e739c5a319cf78a4cff3b87173a84b

**Comment by shanmukakondaveti** [comment] 2021-06-17 09:17
thank you pascalgrimaud,i am getting 400 bad request when trying to create client,here is my client code:

Logger log= LoggerFactory.getLogger("keycloakAdmin.class");
		
		String serverUrl="http://localhost:9080/auth/";
		String realm="jhipster";
		String clientId="web_app";
		String clientSecret="7c800e5b-1cf0-48dc-90c2-cf8c99ed1f93";
		String username="admin";
		String password="admin";
		
		try {
		Keycloak keycloak =KeycloakBuilder.builder()
				.serverUrl(serverUrl)
				.realm(realm)
				.grantType(OAuth2Constants.PASSWORD)
				.clientId(clientId)
				.clientSecret(clientSecret)
				.username(username)
				.password(password)
				.build();

		//Defining user
		UserRepresentation userkeycloak= new UserRepresentation();
		userkeycloak.setEnabled(true);
		userkeycloak.setUsername("shanmuka");
		userkeycloak.setFirstName("shanmuka");
		userkeycloak.setLastName("kondaveti");
		userkeycloak.setEmail("shanmuka@localhost");
		userkeycloak.setAttributes(Collections.singletonMap("orgin",Arrays.asList("demo")));

		//Get Realm
		UsersResource usersResource = realmResource.users();

		//Creating user in keycloak
		Response response= usersResource.create(userkeycloak);
		System.out.println("Reponses:"+response.getStatus()+" "+response.getStatusInfo()+" "+response.getLocation());

		String userId = response.getLocation().getPath().replaceAll(".*/([^/]+)$", "$1");
		//String userId=CreatedResponseUtil.getCreatedId(response);
		System.out.println("User Created with Id :"+userId);

		//Setting Password
		CredentialRepresentation passwordCred = new CredentialRepresentation();
		passwordCred.setTemporary(false);
		passwordCred.setType(CredentialRepresentation.PASSWORD);
		passwordCred.setValue("shanmuka");

		UserResource userResource = usersResource.get(userId);

		// Set password credential to created user
		userResource.resetPassword(passwordCred);

		// Get realm role "tester" (requires view-realm role)
		RoleRepresentation developerRole =realmResource.roles().get(AuthoritiesConstants.DEVELOPER).toRepresentation();

		// Assign realm role tester to user
		userResource.roles().realmLevel().add(Arrays.asList(developerRole));

		// Get client
		ClientRepresentation appClient=realmResource.clients().findByClientId(clientId).get(0);

		// Get client level role (requires view-clients role)
		RoleRepresentation userClientRole =realmResource.clients().get(appClient.getId()).roles().get("userkeycloak").toRepresentation();

		// Assign client level role to user
		userResource.roles().clientLevel(appClient.getId()).add(Arrays.asList(userClientRole));
		System.out.println(userResource);

		}
		catch (Exception e) {
			e.printStackTrace();
		}
	}

**Comment by shanmukakondaveti** [comment] 2021-06-17 09:19
getting following exception:
![Screenshot (122)](https://user-images.githubusercontent.com/83701275/122368688-2eead100-cf7b-11eb-9443-3c0c0fe34616.png)
![Screenshot (123)](https://user-images.githubusercontent.com/83701275/122368714-33af8500-cf7b-11eb-82c1-6f51d05e61e6.png)
![Screenshot (124)](https://user-images.githubusercontent.com/83701275/122368745-390ccf80-cf7b-11eb-8505-0f6f9517d77e.png)

**Comment by pascalgrimaud** [comment] 2021-06-17 09:24
@shanmukakondaveti : sorry, but this a bug tracker here, not a place to get help. You should go to stackoverflow, the community is bigger, to get help for what you're looking for, as there is nothing related to JHipster here.
