### ISSUE TITLE
Problem with expired oauth2 token on client side

### ISSUE THREAD

**Issue by AksuX** [jhipster/generator-jhipster#1170] opened 2015-02-19 06:31 UTC
IMHO there's a problem with the authentication when oauth2-token gets expired.
Browser needs reload after expiration - plain state change isn't enough.
 
Auth.authorize() calls Pricipal.identity() on every state change and  the problem is that when token-expires the identity() returns the old (expired) identity:
```javascript
        // check and see if we have retrieved the identity data from the server.
        // if we have, reuse it by immediately resolving
        if (angular.isDefined(_identity)) {
          deferred.resolve(_identity);

          return deferred.promise;
        }
```

I fixed this problem adding new interceptor to app.js which forces the authorization:
```javascript
  .factory('authExpiredInterceptor', function ($rootScope, $q, $injector) {
    return {
      responseError: function (response) {
        // token has expired
        if (response.status === 419 || response.status === 401) {
          var Principal = $injector.get('Principal');
          if (Principal.isAuthenticated()) {
            var Auth = $injector.get('Auth');
            Auth.authorize(true);
          }

        }
        return $q.reject(response);
      }
    };
  })
```

.. and putting parameter to Auth.authorize(force) which is passed to Principal.identity(force).

NOTE: also needs "_identity check" to Principal.isInRole:
```javascript
      isInRole: function (role) {
        if (!_authenticated || !_identity || !_identity.roles) {
          return false;
        }

        return _identity.roles.indexOf(role) !== -1;
      },
```

Not sure if this is the best way to proceed, but works in my case.. Would be also nice if the server side would answer with code 419 when the token expires.

**Comment by jdubois** [comment] 2015-02-19 09:27
We have had reports of this kind of issues, but we couldn't pinpoint the problem -> looks like you found it!!

I will have a look at it, but if you are sure you corrected the issue, and if you can test it, I would really appreciate a PR.

**Comment by AksuX** [comment] 2015-02-19 10:53
You can "simulate" the situation on client side, by just deleting all entries from "oauth_access_token" table when you're logged in.

Well my solution works but I think it's little bit of a hack.. At least it should do so that it gives some message to the login window that "token/session was expired". And in my opinnion as I said earlier the server should return different error code when token expired - then we can recognize the ses

btw. some questions rised when checking out the oauth2 server side implementation..
1. Does server side now refresh validity the token correctly per each transaction?
2. Why do we create database tables "oauth_approvals", "oauth_client_details", "oauth_client_token" and "oauth_code" ? When logging in we don't seem to put anything in to these and "ClientDetailsServiceConfigurer" is configured to inMemory.. Should we configure ClientDetailsServiceConfigurer so that we put it to the datasource ?

**Comment by ledor473** [comment] 2015-02-21 18:20
I was actually having the exact same issue and it was on my TODO list to open a issue and try to fix it. 
I was wondering why the login page was using the token and gets rejected if the token was expired...

**Comment by sjerman** [comment] 2015-03-04 15:08
Hi. I ran into this problem as well. I think the solution is to add ng-idle (http://hackedbychinese.github.io/ng-idle/) and explicitly logout... that way the client and server remain in sync. I am trying this solution out now and it seems so far to be working.

**Comment by jdubois** [comment] 2015-03-05 20:47
@AksuX concerning the tables, and the implementation: I have no idea :-)

- the implementation comes from Spring Security
- this is a contribution, I didn't code it myself

I'm having a look at this, and if your hack works I'll include it in the code

**Comment by AksuX** [comment] 2015-03-06 06:55
Ok.. I think that there should be at least task for oauth2 code refactoring/cleaning which should be done in the future. I might take a look at it later this spring, but for the next months I'm way too busy to do contributions :)

**Comment by jdubois** [comment] 2015-03-06 08:54
OK, I'm going to have a look at this now

**Comment by jdubois** [comment] 2015-03-06 09:16
Concerning the tables: only the access and refresh token tables are being used. I don't know how this implementation works in detail, but it comes from Spring Security, and:

- I checked and the tables are correctly filed up
- The tokens are then used in the HTTP headers
- Stopping the server, and closing the browser -> when you start up everything again, you are automatically logged in, so clearly the token used come from the database

So this looks all good to me, excepted the "client" tables which are not being used: we are not using that part anyway, so that looks good to me.

I'm now going to have a look at the token expiration: I can reproduce your issue, I'm checking your solution

**Closed** 2015-03-06 10:28 UTC

**Comment by dejewi** [comment] 2015-03-16 12:22
Am I right how it should work?:

If token has expire and there will be call to secured endpoint
then should be refresh_token and user will be still authenticated?
