### ISSUE TITLE
HTTP 401 error for api-docs with Token-based authentication

### ISSUE THREAD

**Issue by vw98075** [jhipster/generator-jhipster#1744] opened 2015-07-17 16:16 UTC
401 : {"timestamp":1437078467982,"status":401,"error":"Unauthorized","message":"Access Denied","path":"/v2/api-docs"}

I don't have this error when I use OAuth2 authentication configuration

**Comment by gmarziou** [comment] 2015-07-17 19:33
It seems to be a duplicate of #1731

**Comment by gmarziou** [comment] 2015-07-17 19:34
Yes it's a known issue, it was the same also before upgrading to spring-fox

**Comment by vw98075** [comment] 2015-07-17 19:39
I had scanned over those existing bug reports and didn't see the pone. Sorry for posting a duplicated report.

**Comment by gmarziou** [comment] 2015-07-17 19:45
No problem, it was mentioned in 2.18.0 release notes:

https://jhipster.github.io/2015/07/07/jhipster-release-2.18.0.html

**Comment by paivaric** [comment] 2015-08-08 20:56
+1

**Closed** 2015-08-12 12:47 UTC
Labels: bug
