### ISSUE TITLE
User Account activation

### ISSUE THREAD

**Issue by kn4ls** [jhipster/generator-jhipster#2346] opened 2015-11-15 09:47 UTC
* **Overview of the issue**

    Couldn't activate user account. Always return a 500 Internal server error

``` java
@RequestMapping(value = "/activate",
            method = RequestMethod.GET,
            produces = MediaType.APPLICATION_JSON_VALUE)
    @Timed
    public ResponseEntity<String> activateAccount(@RequestParam(value = "key") String key) {
        return userService.activateRegistration(key)
            .map(user -> new ResponseEntity<String>(HttpStatus.OK))
            .orElse(new ResponseEntity<>(HttpStatus.INTERNAL_SERVER_ERROR));
    }
```
due to UserService method:
``` java
public Optional<User> activateRegistration(String key) {
        log.debug("Activating user for activation key {}", key);
        userRepository.findOneByActivationKey(key)
            .map(user -> {
                // activate given user for the registration key.
                user.setActivated(true);
                user.setActivationKey(null);
                userRepository.save(user);
                userSearchRepository.save(user);
                log.debug("Activated user: {}", user);
                return user;
            });
        return Optional.empty();
    }
```

* **Motivation for or Use Case** 

* **JHipster Version(s)** 

    2.23.1

* **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 
``` json
{
  "generator-jhipster": {
    "baseName": "",
    "packageName": "",
    "packageFolder": "",
    "authenticationType": "xauth",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": "elasticsearch",
    "useCompass": false,
    "buildTool": "maven",
    "frontendBuilder": "grunt",
    "javaVersion": "8",
    "enableTranslation": true,
    "rememberMeKey": "",
    "useSass": false,
    "enableSocialSignIn": false,
    "testFrameworks": [
      "gatling"
    ]
  }
}
```

* **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory** 

* **Browsers and Operating System** 

* **Reproduce the error** 
Try to activate an account

* **Related issues** 

* **Suggest a Fix** 

``` java
public Optional<User> activateRegistration(String key) {
        log.debug("Activating user for activation key {}", key);
        return userRepository.findOneByActivationKey(key)
            .map(user -> {
                // activate given user for the registration key.
                user.setActivated(true);
                user.setActivationKey(null);
                userRepository.save(user);
                userSearchRepository.save(user);
                log.debug("Activated user: {}", user);
                return Optional.of(user);
            }).orElse(Optional.empty());
    }
```

**Comment by jdubois** [comment] 2015-11-15 09:49
Can you also send your stacktrace?

**Comment by kn4ls** [comment] 2015-11-15 09:59
The problem I think is in the lambda expression of activateRegistration() method in UserService. There is no exception thrown but always return Optional.empty() and activateAccount() in AccountResource always return a 500 error (HttpStatus.INTERNAL_SERVER_ERROR).

**Comment by sendilkumarn** [comment] 2015-11-26 14:38
@kn4ls :+1: 

Also @jdubois  & @deepu105  we can change this return responseEntity <> in UserResource and AccountResource similar to what we will do in EntityResources.

ResponseEntity.ok()
           .headers(HeaderUtil.createEntityUpdateAlert("user", managedUserDTO.getLogin()))
                    .body(new ManagedUserDTO(userRepository
                        .findOne(managedUserDTO.getId()))

during this fix.

**Comment by deepu105** [comment] 2015-11-27 01:56
I think @gzsombor was talking about re writing these classes

**Comment by deepu105** [comment] 2015-11-27 01:57
@sendilkumarn yes these needs to be updated for uniformity as well

**Comment by jdubois** [comment] 2015-12-02 09:59
I can't reproduce the error... How do you trigger it? I have registered a new user, clicked on the link, everything went fine.

**Comment by jdubois** [comment] 2015-12-07 14:19
I still can't reproduce so I'm closing this.
Next time can you also put a title that is more descriptive?

**Closed by jdubois** 2015-12-07 14:19 UTC
Labels: bug
