### ISSUE TITLE
File overwrite is asked twice by the generator

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#1698] opened 2015-07-08 08:10 UTC
When the generator is run a second time, and a file has changed, you can choose to overwrite this file or not.
As mentioned in #1682 if you select "no", the question is then asked a second time.
This does not seem to cause any bug, however it's really annoying for people who want to use this Yeoman feature (I am not using it personally, I manage all this process with Git, which I find more useful, that's why I didn't see this problem in the last release - I would recommend to do the same, at least until this is solved!).
If anybody can help on this, it is most welcome, as I have no idea what causes this issue.
This can be very annoying to people using this feature, so I will release a bug fixing release as soon as this is solved.

**Comment by deepu105** [comment] 2015-07-22 07:49
@jdubois I guess this might be something wrong at NPM level coz im seeing similar behavior in bower as well

![image](https://cloud.githubusercontent.com/assets/1107223/8820553/24eec766-3089-11e5-89e9-ac41afcea55a.png)

**Comment by kileniklawski** [comment] 2015-08-04 21:12
This seems to be related to a yeoman generator issue: https://github.com/yeoman/generator/issues/835

I think the best course of action is to fix the root cause in the yeoman generator. I'll be watching the issue to see if I can help.

**Comment by kileniklawski** [comment] 2015-08-24 14:13
My pull request to fix this in yeoman/generator was committed. This issue should be resolved in future builds. 

https://github.com/yeoman/generator/commit/1f5dc52b0c44322ac829234dc67d886084b16e10

**Comment by deepu105** [comment] 2015-08-24 15:49
Then we can close it here i guess

**Comment by atomfrede** [comment] 2015-08-24 17:47
Closed with https://github.com/jhipster/generator-jhipster/pull/1919

**Closed by atomfrede** 2015-08-24 17:47 UTC
Labels: bug
