### ISSUE TITLE
Elastic Search conflict for monolith application and jhipster console

### ISSUE THREAD

**Issue by ganeshkrishnan1** [jhipster/generator-jhipster#6621] opened 2017-10-31 03:14 UTC
##### **Overview of the issue**

I am attempting to use jhipster console with a monolith application. As per the docs I have to use this yml file for docker 

> If you are using the monolithic version of JHipster, you can get the JHipster Console’s Docker-Compose file from GitHub or with the following command:
> 
> curl -O https://raw.githubusercontent.com/jhipster/jhipster-console/master/bootstrap/docker-compose.yml

In a nutshell: The elastic search in jhipster-console is different from the generated app. Both of them are incompatible and either one does not worth for both applications (console and generated app)

##### **Motivation for or Use Case**

Use jhipster console with monolith application

##### **Reproduce the error**

1) Create a new project
2) Download the yml above
3) Run the yml docker
4) Run the newly created project
5) Errors in elastic search

##### **Related issues**

Not aware of any

##### **Suggest a Fix**
Use elastic search version > 5.0 but the project is using an older incompatible version

Jhipster details:
 

Using JHipster version installed locally in current project's node_modules
Executing jhipster:info
Options: 
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
ai-hello-core@0.0.0 /media/spyder/data/projects/AiHelloCore
├── generator-jhipster@4.10.2 
└── UNMET PEER DEPENDENCY popper.js@^1.11.0

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.aihello",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "4.10.2",
    "baseName": "AiHelloCore",
    "packageName": "com.aihello",
    "packageFolder": "com/aihello",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "gradle",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": true,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ]
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

</details>

##### **Environment and Tools**

java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

git version 2.14.1

node: v7.9.0

npm: 4.2.0

bower: 1.8.2

gulp:
[13:47:42] CLI version 1.3.0

yeoman: 2.0.0

yarn: 0.22.0

Docker version 17.06.0-ce, build 02c1d87

docker-compose version 1.13.0, build 1719ceb

Completed all tasks on www.aihello.com

- [ X] Checking this box is mandatory (this is just to show you read everything)

**Comment by PierreBesson** [comment] 2017-10-31 16:40
@ganeshkrishnan1 This is completely normal and not a bug at all for several reasons :

- The elasticsearch used by spring data and the one in the console are not on the same version : 2.X vs 5.X. This is changing in the latest spring data  that supports the latest elasticsearch but I'm sure compatibility will be broken again soon.
- The Elasticsearch instance used for the console is part of an independent monitoring system which should not be tied to your app. For obvious reason, you don't want that problems on your monitoring tool to crash your app ! In my experience the Elasticsearch that is part of the console will receive **a lot** of data and so requires some maintenance. I think it's much better to manage it independently from your app.
- The console is based on the ELK stack which works much better when you align versions of Elasticsearch, Logstash and Kibana.

If everything is clear for you please close the issue.

**Comment by ganeshkrishnan1** [comment] 2017-10-31 22:45
Does this mean we need to have two instances of elastic search running on our network? 
One for the app (2.x version) and one for console (5.x version)
I want to see my app logs on jhipster console and I was able to do this off the bat on the microservices architecture.  After moving to monolith version ES throws up errors every time the app sends messages to it.

I am running console and my app on docker instances with one common ES instance between them; you cannot have two ES instances listening to the same port (9200)

**Comment by PierreBesson** [comment] 2017-10-31 22:51
Yes you need 2 different Elasticsearch.
Now about the port conflict... This can be solved easily as the Console's Elasticsearch doesn't need to be exposed on the host. If you remove the `port:9200:9200` section for jhipster-elasticsearch dors it fixes your problem ?

**Comment by ganeshkrishnan1** [comment] 2017-10-31 23:00
I am sorry, I still don't get it. How will the logs from the app reach the console project if they run their own elastic search? And especially after you block the console ES from outside world.
The logstash for the app writes to the elastic search of the app. The console reads from it's own ES.

The console seems to be running on it's own without interacting with app. How will it get the logs from the app?

Anyway I will comment out the port for console and run it. Maybe there is some magic that I don't understand.

**Comment by PierreBesson** [comment] 2017-10-31 23:08
There is no magic ;-).
>The logstash for the app writes to the elastic search of the app. 
I think you misunderstand something here the elasticsearch option for apps is not the same as the ELK console, it is used to search entities. Also apps are not sending their logs to elasticsearch, they are sending them to logstash on port 8500. Also you must take into account the ”virtual networking” which is setup by docker-compose and which means that you don't actually need to expose the port on your host for other containers to access it.

**Comment by ganeshkrishnan1** [comment] 2017-10-31 23:31
I get the point of app -> logstash -> ES1.app.
I want to know how I can see these app logs from jhipster-console which is console -> ES2.console.
OR 
What's the common link between the app and console such that I can observe the app stats/logs from console?

Let me comment out the port for the jhipster-console, run the application and get back to you.

**Comment by ganeshkrishnan1** [comment] 2017-11-01 01:39
Allright, it works if you comment out the ports for ES in jhipster-console.yml. Else you would have to run both docker on two different physical machines to prevent port conflict.
I can get the app logs in jhipster console too which i assume is through common logstash instance or some black magic .

We still need to comment out the port in the yml file so I will leave it to you to close this ticket

**Closed** 2017-11-23 04:23 UTC
