### ISSUE TITLE
Mvnw and Gradlew permissions when using Gitlab and Windows

### ISSUE THREAD

**Issue by Evertude** [jhipster/generator-jhipster#9135] opened 2019-01-28 14:51 UTC
##### **Overview of the issue**

When using JHipster with Windows, the permissions of the Gradle and Maven Wrapper aren't set and when they are copied to Gitlab CI/CD, the build fails because of a lack of permissions.

##### **Motivation for or Use Case**

Users that use Windows for development and Gitlab for CI/CD.

##### **Reproduce the error**

Generate any project using Windows
Use Gitlab CI/CD

##### **Related issues**

Found this SO question which also contains the solution.
https://stackoverflow.com/questions/51752706/gradlew-permission-denied-when-deploying-a-jhipster-5-1-0-project-on-gitlab/54146609

##### **Suggest a Fix**

The generator should run
```
git update-index --chmod=+x mvnw
git update-index --chmod=+x gradlew
```

##### **JHipster Version(s)**

5.8 and earlier

##### **Browsers and Operating System**

Windows 10 (probably any Non-Unix system)

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by atomfrede** [comment] 2019-02-06 19:10
@Evertude Can you try the latest master branch? All wrappers are now marked as executable

**Comment by pascalgrimaud** [comment] 2019-02-09 10:11
let's close this.
Don't hesitate to comment if you still have the issue

**Closed by pascalgrimaud** 2019-02-09 10:11 UTC
Labels: minor, waiting for information

**Comment by naturzukunft** [comment] 2020-03-31 17:42
i currently created the .gitlab-ci.yml with:
```
jhipster --version:
INFO! Using JHipster version installed locally in current project's node_modules
6.8.0
```
and got the problem on gitlab.com 
```
$ ./mvnw -ntp com.github.eirslett:frontend-maven-plugin:install-node-and-npm -DnodeVersion=v12.16.1 -DnpmVersion=6.14.2 -Dmaven.repo.local=$MAVEN_USER_HOME  
/bin/bash: line 99: ./mvnw: Permission denied
```

**Comment by naturzukunft** [comment] 2020-03-31 17:50
git update-index --chmod=+x mvnw
solved my problem !

**Comment by govindrk** [comment] 2020-04-20 10:25
@naturzukunft,
This has been a pain using GitLab on windows. 
---> Running in e3925ef72bc4
/bin/sh: 1: ./mvnw: Permission denied

Windows Gitbash 
the build is failing.. did set the git update-index --chmod=+x mvnw

git ls-files --stage

100755 8b9da3b8b6006ed618243365e6d653d391a6b524 0       mvnw
100755 fef5a8f7f98851e698aed89b38961d160db50249 0       mvnw.cmd

The builds are failing exactly at the same point /bin/sh: ./mvnw: Permission denied even after making the changing, commit and push into git.

Thanks
Govind

**Comment by SudharakaP** [comment] 2020-04-20 16:08
@naturzukunft @govindrk : This seems to be a very old issue. I don't know if this problem has been reintroduced by some regression; but could you please open a new issue if this is still an issue for you. :smile:

**Comment by sorokinQA** [comment] 2020-07-28 14:36
**git update-index --chmod = + x mvnw** helped me, thanks a lot!
