### ISSUE TITLE
Jhipster v8.1.0 asks to generate Feign client during Monolithic app creation

### ISSUE THREAD

**Issue by cfreyer** [jhipster/generator-jhipster#24560] opened 2023-12-14 02:32 UTC
##### **Overview of the issue**

While running `jhipster` to create a new project, a user can choose both a Monolithic application, and a Feign client.  After answering remaining questions, project generation fails with the following error:

ERROR! An error occured while running jhipster:server#feignMigration
ERROR! ERROR! Feign client is only supported by microservice applications.

##### **Motivation for or Use Case**

Completing the questions to generate a new app should not lead to a failure situation.

##### **Reproduce the error**

install JHipster v8.1.0.  Answer questions as follows:
What is the base name of your application? something
? Which *type* of application would you like to create? Monolithic application (recommended for simple projects)
? Do you want to generate a feign client? Yes
? Besides Junit, which testing frameworks would you like to use? Cucumber
? Do you want to make it reactive with Spring WebFlux? No
? What is your default Java package name? com.test
? Which *type* of authentication would you like to use? JWT authentication (stateless, with a token)
? Which *type* of database would you like to use? SQL (H2, PostgreSQL, MySQL, MariaDB, Oracle, MSSQL)
? Which *production* database would you like to use? PostgreSQL
? Which *development* database would you like to use? H2 with in-memory persistence
? Which cache do you want to use? (Spring cache abstraction) No cache - Warning, when using an SQL database, this will disable the 
Hibernate 2nd level cache!
? Would you like to use Maven or Gradle for building the backend? Maven
? Which other technologies would you like to use? API first development using OpenAPI-generator

##### **Suggest a Fix**

Bypass feign client question if user selects Monolithic in previous question

##### **JHipster Version(s)**
v8.1.0

##### **JHipster configuration**

Welcome to JHipster v8.1.0
Welcome to the JHipster Information Sub-Generator
```
/home/me/code/test
└── (empty)
```
##### **Environment and Tools**

openjdk version "17.0.9" 2023-10-17
OpenJDK Runtime Environment GraalVM CE 17.0.9+9.1 (build 17.0.9+9-jvmci-23.0-b22)
OpenJDK 64-Bit Server VM GraalVM CE 17.0.9+9.1 (build 17.0.9+9-jvmci-23.0-b22, mixed mode, sharing)

git version 2.39.2

node: v18.18.2
npm: 10.2.5

Docker version 24.0.7, build afdd53b
WARNING! Current location doesn't contain a valid JHipster application

---

no jdl yet

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**
no entity file yet

##### **Browsers and Operating System**

No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 12 (bookworm)
Release:	12
Codename:	bookworm

Linux pluto 6.1.0-13-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.55-1 (2023-09-29) x86_64 GNU/Linux

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by mraible** [comment] 2023-12-14 03:32
I experienced this tonight when updating my [jhipster8-demo](https://github.com/mraible/jhipster8-demo). This has never been a question before when creating monoliths, so it's a regression.

**Comment by atomfrede** [comment] 2023-12-14 05:37
It was added via https://github.com/jhipster/generator-jhipster/pull/24457

**Comment by nil-malh** [comment] 2023-12-14 10:18
Hi there, is anyone working on this ? I will be happy to try and fix it !

**Comment by atomfrede** [comment] 2023-12-14 10:19
@nil-malh If you like go ahead. If you have any question don't hesitate to ask.

**Comment by nil-malh** [comment] 2023-12-14 10:20
Okay gonna work on it today will keep you posted !

**Comment by atomfrede** [comment] 2023-12-14 13:11
Not sure, maybe have it for microservices and gateways, by default it should be false and not shown for monolith. @mshima what do you say? Did I miss something such that we want feign clients for monolith too?

**Comment by nil-malh** [comment] 2023-12-14 14:52
> Not sure, maybe have it for microservices and gateways, by default it should be false and not shown for monolith. @mshima what do you say? Did I miss something such that we want feign clients for monolith too?

I would assume no, there is an error implemented that will throw if the app is a monolith and asked for a feign client

**Comment by nil-malh** [comment] 2023-12-14 14:52
Fixed in #24566

**Comment by cfreyer** [comment] 2023-12-14 15:01
For what it's worth:

A) I have not seen the feign client option in the past when generating a
monolithic application.

B) Technically, if the monolith's API is exposed, a developer could use the
feign client when writing another backend.  However, I think this goes
beyond the expectations of a monolith application.

**Comment by nil-malh** [comment] 2023-12-14 16:42
@mraible what do you advice should I let it for gateways or only for microservices ?

**Comment by mraible** [comment] 2023-12-14 17:03
I *think* it should only be for non-reactive microservices, but I'm not sure as I'm not familiar with when it was included in previous versions of JHipster.

**Comment by nil-malh** [comment] 2023-12-14 17:14
Noted will doing it now !

**Comment by nil-malh** [comment] 2023-12-14 17:32
Done #24566

**Closed** 2023-12-15 16:09 UTC
Labels: area: bug :bug:, $100, $$ bug-bounty $$, theme: cli

**Comment by morobah** [comment] 2024-02-08 09:56
Hi everyone, I think the problem is still not fixed
