### ISSUE TITLE
Jhipster AWS Deployment error Create S3 Bucket and missing configuration credentials

### ISSUE THREAD

**Issue by rizwanbpatel** [jhipster/generator-jhipster#3647] opened 2016-05-25 19:27 UTC
##### **Overview of the issue**

Followed AWS deployment steps mentioned @ http://jhipster.github.io/aws/

.yo-rc.json file:
{
  "generator-jhipster": {
    "jhipsterVersion": "3.1.0",
    "baseName": "zkc",
    "packageName": "y",
    "packageFolder": "y",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": "hazelcast",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": "no",
    "buildTool": "maven",
    "enableSocialSignIn": true,
    "useSass": false,
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ]
  }
}

yo jhipster:aws

Once build is complete gets below message printed on the server
[INFO] ------------------------------------------------------------------------

[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 03:43 min
[INFO] Finished at: 2016-05-26T00:51:36+05:30

[INFO] Final Memory: 64M/424M

[INFO] ------------------------------------------------------------------------

Create S3 bucket
Error jhipster:aws

**Missing credentials in config**
##### **Motivation for or Use Case** 

I have created the AWS bucket with the provided deails as per the quetionaire:

 Application name: zkc
? Environment name: prod
? Name of S3 bucket: zkc1
? Database name: 
? Database username: zkcriz
? Database password: *********
? On which EC2 instance type do you want to deploy? t2.micro
? On which RDS instance class do you want to deploy? db.t2.micro
? On which region do you want to deploy? us-west-2
##### **Browsers and Operating System** 

Operating System: Windows 10

**Comment by ruddell** [comment] 2016-05-26 04:56
I was able to successfully upload the app to AWS through the generator following the documentation you linked.  I was also able to get your error message (Missing credentials in config) to show up by deleting the credentials in my .aws/credentials file.  In the JHipster AWS documentation, it mentions setting up C:\Users\USERNAME\.aws\credentials on Windows. 

I'd recommend checking to make sure the credentials in that file for the [default] account are valid and have the correct permissions.

**Comment by deepu105** [comment] 2016-05-26 09:57
closed as @ruddell couldn't reproduce this and as he said you might be missing the credentials.

Thank you @ruddell

**Closed** 2016-05-26 09:56 UTC
Labels: aws
