### ISSUE TITLE
Webpack Build failing after upgrade to v5

### ISSUE THREAD

**Issue by pmverma** [jhipster/generator-jhipster#7828] opened 2018-06-22 05:11 UTC
##### **Overview of the issue**

`yarn webpack:build` is failing with following error after upgrade from v4 to v5.

```
ERROR in /home/ubuntu/workspace/jhup/src/main/webapp/app/admin/user-management/user-management-dialog.component.ts
(8,10): Module '"/home/ubuntu/workspace/jhup/src/main/webapp/app/shared/index"' has no exported member 'JhiLanguageHelper'.

ERROR in /home/ubuntu/workspace/jhup/src/main/webapp/app/admin/user-management/user-management-dialog.component.ts
(8,29): Module '"/home/ubuntu/workspace/jhup/src/main/webapp/app/shared/index"' has no exported member 'User'.

ERROR in /home/ubuntu/workspace/jhup/src/main/webapp/app/admin/user-management/user-management-dialog.component.ts
(8,35): Module '"/home/ubuntu/workspace/jhup/src/main/webapp/app/shared/index"' has no exported member 'UserService'.

ERROR in /home/ubuntu/workspace/jhup/src/main/webapp/app/admin/user-management/user-modal.service.ts
(5,10): Module '"/home/ubuntu/workspace/jhup/src/main/webapp/app/shared/index"' has no exported member 'User'.

ERROR in /home/ubuntu/workspace/jhup/src/main/webapp/app/admin/user-management/user-modal.service.ts
(5,16): Module '"/home/ubuntu/workspace/jhup/src/main/webapp/app/shared/index"' has no exported member 'UserService'.

ERROR in /home/ubuntu/workspace/jhup/src/test/javascript/spec/app/admin/user-management/user-management-dialog.component.spec.ts
(9,10): Module '"/home/ubuntu/workspace/jhup/src/main/webapp/app/shared/index"' has no exported member 'UserService'.

ERROR in /home/ubuntu/workspace/jhup/src/test/javascript/spec/app/admin/user-management/user-management-dialog.component.spec.ts
(9,23): Module '"/home/ubuntu/workspace/jhup/src/main/webapp/app/shared/index"' has no exported member 'User'.

ERROR in /home/ubuntu/workspace/jhup/src/test/javascript/spec/app/admin/user-management/user-management-dialog.component.spec.ts
(9,29): Module '"/home/ubuntu/workspace/jhup/src/main/webapp/app/shared/index"' has no exported member 'JhiLanguageHelper'.

ERROR in /home/ubuntu/workspace/jhup/src/test/javascript/spec/entry.ts
(1,22): File '/home/ubuntu/workspace/jhup/node_modules/@types/jasmine/index.d.ts' not found.
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```
##### **Motivation for or Use Case**

Upgrading an app(without any customization) should be work?
Or is there any migration guide?

##### **Reproduce the error**

Two cases here:

1. Fresh app created from 4.14.5 -> 5.0.0 is working perfectly without any error.
However, in my case following No.2
2. From 4.14.3 -> 5.0.0 as following steps

- Create a fresh app from v4.14.3
-Upgrade to v4.14.4 (fine)
-Upgrade to v4.14.5 (fine)
-Upgrade to v5.0.0 (failed)

For ref, I have created an online repo at [https://gitlab.com/pmverma/jhup/commits/master](https://gitlab.com/pmverma/jhup/commits/master)

##### **Related issues**
-

##### **Suggest a Fix**
-

##### **JHipster Version(s)**

v5.0.0

##### **JHipster Version(s)**

```
jhup@0.0.0 /home/ubuntu/workspace/jhup
└── generator-jhipster@5.0.0 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "4.14.5",
    "baseName": "jhup",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ]
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

git version 2.17.1

node: v8.11.2

npm: 5.6.0

yeoman: 2.0.0

yarn: 1.3.2

Docker version 18.03.1-ce, build 9ee9f40

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment] 2018-06-22 05:29
How did you upgrade ? Manually or with the upgrade sub generator ?

In v5, we did some reactoring for some files in Angular part. That would explain the errors.

**Comment by pmverma** [comment] 2018-06-22 07:57
@pascalgrimaud With upgrade sub-generator, upgrade is working fine but seems not working with manual.
As I have some customization I would like to upgrade manually.

**Comment by deepu105** [comment] 2018-06-23 09:30
@pmverma if the issue is with manula upgrades then probabaly you will need to make some changes as quite a lot changed from v4 to v5,

I'm not sure if we can help on this one. Hence i'm closing this as I dont think its a bug(as auto upgrade works)

Do ask to reopen if you still think its a bug with JHipster code

**Closed by deepu105** 2018-06-23 09:30 UTC

**Comment by ruddell** [comment] 2018-06-27 12:54
@pmverma JHipster migrated the http services to the core module in https://github.com/jhipster/generator-jhipster/pull/7110, the upgrade generator handles that but if you upgrade manually you have to change the imports throughout your project.  The upgrade generator should keep your custom changes
