### ISSUE TITLE
"sign in" links to "keycloak:9080/..." instead of "localhost:9080/..." in Docker

### ISSUE THREAD

**Issue by ThomasWilhelmUR** [jhipster/generator-jhipster#6722] opened 2017-11-23 15:34 UTC
##### **Overview of the issue**

In a microservice environment running in docker using the new Keycloak feature, the sign in links will take you here:
http://keycloak:9080/auth/realms/jhipster/protocol/openid-connect/auth?client_id=web_app&redirect_uri=http://localhost:8080/login&response_type=code&scope=openid%20profile%20email&state=2HNh2B

##### **Motivation for or Use Case**

Testing the new Keycloak integration.

##### **Reproduce the error**

How I did it / how to reproduce:

1. Create new microservice using keycloak
2. Create new gateway using keycloak
3. Create a dummy entity (like "foo") and regenerate.
4. Run the docker-compose subgenerator
5. Start all of the apps using "docker-compose up -d"

##### **Related issues**

When changing "keycloak:9080/" to "localhost:9080/" there is another error.
#6723 

##### **Suggest a Fix**

Clicking "sign in" in the gateway should take you to "localhost:9080". 

##### **JHipster Version(s)**

4.10.2

##### **JHipster configuration**

Service:
```
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "en.something",
      "nativeLanguage": "de"
    },
    "jhipsterVersion": "4.10.2",
    "baseName": "service",
    "packageName": "en.something",
    "packageFolder": "en/something",
    "serverPort": "8081",
    "authenticationType": "oauth2",
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "1372d952e81cee4ed366b7d48c803dd3904c35cd",
    "enableTranslation": true,
    "applicationType": "microservice",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "nativeLanguage": "de",
    "languages": [
      "de"
    ],
    "clientPackageManager": "yarn",
    "skipClient": true,
    "skipUserManagement": true
  }
}
```

Gateway:
```
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "en.something",
      "nativeLanguage": "de",
      "microservicePath": "../service"
    },
    "jhipsterVersion": "4.10.2",
    "baseName": "gateway",
    "packageName": "en.something",
    "packageFolder": "en/something",
    "serverPort": "8080",
    "authenticationType": "oauth2",
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": false,
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "gateway",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "de",
    "languages": [
      "de",
      "en"
    ]
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**
```
Foo.json
{
    "fluentMethods": true,
    "relationships": [],
    "fields": [
        {
            "fieldName": "fooname",
            "fieldType": "String"
        }
    ],
    "changelogDate": "20171123142052",
    "dto": "no",
    "service": "no",
    "entityTableName": "foo",
    "jpaMetamodelFiltering": false,
    "pagination": "no",
    "microserviceName": "service",
    "searchEngine": "elasticsearch"
}
```

##### **Browsers and Operating System**

Windows, Chrome/FF

**Comment by mraible** [comment] 2017-11-23 15:45
Yes, this is expected. You have to create a hosts entry for keycloak that points to 127.0.0.1 and everything will work. We tried to come up with a better solution, but failed to do so.

**Comment by ThomasWilhelmUR** [comment] 2017-11-23 15:49
Thank you. Can you point me to the disccusion? (I looked around in lots of issues but didn't see it before, thanks!)

**Comment by jdubois** [comment] 2017-11-23 16:07
Yes, what @mraible says is in the documentation -> closing this as this is not a bug.

Then I know the documentation isn't good enough, we have an opened ticket for that, but we just lack the time to write it.

**Closed by jdubois** 2017-11-23 16:07 UTC

**Comment by ThomasWilhelmUR** [comment] 2017-11-23 16:32
I did some digging and finally found it - I am glad you will be improving the documentation in this regard. Thanks.

**Comment by issamm** [comment] 2018-10-31 14:23
Hi @ThomasWilhelmUR , why don't you just put the answer and what you found ?

**Comment by sslgeorge** [comment] 2020-04-19 03:26
@ThomasWilhelmUR and @jdubois 
Really, why don't you put the answer here, I am having the exact issue and I have to dig around

**Comment by Tcharl** [comment] 2020-04-19 11:09
Hi, @sslgeorge @issamm ,

@mraible told what to do in order to make it work: edit your /etc/hosts file and add an entry like 
`127.0.0.1 keycloak`

**Comment by pascalgrimaud** [comment] 2020-04-19 14:18
@issamm @sslgeorge : just check our website -> https://www.jhipster.tech/docker-compose/#-keycloak
