### ISSUE TITLE
[Angular] Navbar not correctly updated when entity is created/updated

### ISSUE THREAD

**Issue by qmonmert** [jhipster/generator-jhipster#14388] opened 2021-03-19 19:43 UTC
When I add an entity `jhipster entity strava`, `navbar.component.html` is not updated with the link to the list of stravas

##### **Overview of the issue**

Navbar not updated

##### **Reproduce the error**

Create an Angular app
Add an entity

##### **JHipster Version(s)**

main branch

##### **JHipster configuration**

```
{
  "generator-jhipster": {
    "blueprints": [],
    "otherModules": [],
    "applicationType": "monolith",
    "baseName": "jhipster",
    "jhipsterVersion": "7.0.0-beta.1",
    "skipClient": false,
    "skipServer": false,
    "skipUserManagement": false,
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "testFrameworks": ["cypress"],
    "pages": [],
    "creationTimestamp": 1616180914846,
    "serviceDiscoveryType": false,
    "reactive": false,
    "authenticationType": "jwt",
    "packageName": "com.mycompany.myapp",
    "serverPort": "8080",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "buildTool": "maven",
    "serverSideOptions": [],
    "websocket": false,
    "searchEngine": false,
    "messageBroker": false,
    "enableSwaggerCodegen": false,
    "clientFramework": "angularX",
    "withAdminUi": true,
    "clientTheme": "none",
    "enableTranslation": true,
    "nativeLanguage": "fr",
    "packageFolder": "com/mycompany/myapp",
    "jwtSecretKey": "MTg2NmIwNDA4NzhjMGFlNzU1ZDUxMzdmMjAzYWZhZTI5MWVhNTQ1MWI3MDZjOTMxNzljNzVhMzFkNTYzMjI0Yjc1MDY0ODQwMTM2NzU2NzZjYTk5NzI0ZDY0YWYwMzFmNjQyM2FmZDllNjY5MTkwNTEyZWE1MjYxYTA2MjBkNDM=",
    "clientPackageManager": "npm",
    "clientThemeVariant": "",
    "languages": ["fr"],
    "lastLiquibaseTimestamp": 1616182403000,
    "entities": ["Strava", "Garmin", "Polar", "Suunto"]
  }
}
```

##### **Browsers and Operating System**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by qmonmert** [comment] 2021-03-19 21:05
@mshima you reproduce?

@pascalgrimaud doesn't reproduce

**Comment by mshima** [comment] 2021-03-19 21:20
Duplicated `navbar.component.html` entries yes.
```
jhipster jdl bug-tracker.jh --skip-jhipster-dependencies --skip-install
jhipster entity Label --regenerate
```

Not adding entities to `navbar.component.html` no.

**Comment by mshima** [comment] 2021-03-19 21:22
The problem is that we always test the entire needle, so a prettier change can make our regex to fail.
IMO we should start adding ids to needles and test the id.

**Comment by pascalgrimaud** [comment] 2021-03-20 08:37
I can reproduce the issue, described by @mshima 
I'm adding a bounty on this, in case of someone wants to fix it.
I'm preparing the other stuff before having a look on this ticket.

**Comment by mshima** [comment] 2021-03-20 10:13
On it.

**Comment by qmonmert** [comment] 2021-03-20 10:48
@mshima ok 👍

**Comment by mshima** [comment] 2021-03-20 11:51
Fix is implemented at https://github.com/jhipster/generator-jhipster/pull/14391.

I need to add regression tests for duplicated needles, since we always have problems with those needles.
I don't think it will be included for JHipster 7 release. It's a regression test anyway.

**Comment by pascalgrimaud** [comment] 2021-03-20 14:40
@mshima : should we keep this opened or not, as https://github.com/jhipster/generator-jhipster/pull/14391 has been merged ?

**Comment by mshima** [comment] 2021-03-20 15:27
@pascalgrimaud keep open I am writing some more tests for duplicated needles.

**Closed** 2021-03-20 18:56 UTC
Labels: $$ bug-bounty $$, $200, area: bug :bug:, theme: angular

**Comment by mshima** [comment] 2021-03-22 19:07
@pascalgrimaud bounty claimed https://opencollective.com/generator-jhipster/expenses/36635.

**Comment by pascalgrimaud** [comment] 2021-03-22 19:14
@mshima : approved
