### ISSUE TITLE
Swagger "Try it Out" Feature not working

### ISSUE THREAD

**Issue by gerbsen** [jhipster/generator-jhipster#2586] opened 2016-01-08 08:29 UTC
Hey,
First of all thank you guys for this awesome generator. I was searching for this quite a long time. It's like working on rails! 

Now to my question, I generated an app which is running smoothly, but the "try it out" feature of swagger does not work: 

![screenshot 2016-01-08 09 25 22](https://cloud.githubusercontent.com/assets/1186245/12193590/0bd7fc2a-b5ea-11e5-9516-13614553d963.png)

Browser Console:
![screenshot 2016-01-08 09 26 49](https://cloud.githubusercontent.com/assets/1186245/12193582/000c996e-b5ea-11e5-8fc8-7c6d20687d1f.png)

Eclipse Console:
```
2016-01-08 09:23:02.587 DEBUG 52969 --- [nio-8080-exec-5] n.m.a.aop.logging.LoggingAspect          : Enter: org.springframework.boot.actuate.audit.AuditEventRepository.add() with argument[s] = [AuditEvent [timestamp=Fri Jan 08 09:23:02 CET 2016, principal=anonymousUser, type=AUTHORIZATION_FAILURE, data={type=org.springframework.security.access.AccessDeniedException, message=Access is denied}]]
2016-01-08 09:23:02.587 DEBUG 52969 --- [nio-8080-exec-5] n.m.a.aop.logging.LoggingAspect          : Exit: org.springframework.boot.actuate.audit.AuditEventRepository.add() with result = null
2016-01-08 09:23:02.592 DEBUG 52969 --- [nio-8080-exec-5] n.m.a.s.Http401UnauthorizedEntryPoint    : Pre-authenticated entry point called. Rejecting access
```

Did I miss some configuration or is this a bug?
Cheers,
Daniel

Versions: 
Running with Spring Boot v1.3.1.RELEASE, Spring v4.2.4.RELEASE
generator-jhipster: 2.26.2
Eclipse Version: Mars.1 Release (4.5.1) Build id: 20150924-1200

**Comment by gmarziou** [comment] 2016-01-08 09:53
Hi Daniel,

The try-out feature does not work for all authentication schemes, what do you use?

**Comment by gerbsen** [comment] 2016-01-08 11:48
The default one, I guess it was HTTP Session Authentication

**Comment by jdubois** [comment] 2016-01-09 14:23
- I can't reproduce, this is working fine for me
- Maybe you could send us your configuration? It's impossible for us to reproduce if we don't have your exact config
- From what I see in your logs, you have an authentication or authorization problem: maybe you are not logged in, or maybe your user doesn't have the necessary rights?

**Comment by gmarziou** [comment] 2016-01-09 20:58
HTTP Session Authentication should work as it uses a cookie, the issue with swagger is about authentication mechanisms that use an HTTP header like JWT.

**Comment by jdubois** [comment] 2016-01-10 17:40
OK I'm closing this as I still can't reproduce, please provide more information!

**Closed by jdubois** 2016-01-10 17:40 UTC

**Comment by gerbsen** [comment] 2016-01-11 07:36
Sorry for the delay... could you tell me which configuration files you mean?

**Comment by moifort** [comment] 2016-01-11 07:39
@gerbsen everything is detail here:

### Submitting an Issue
Before you submit your issue search the archive, maybe your question was already answered.

If your issue appears to be a bug, and hasn't been reported, open a new issue.
Help us to maximize the effort we can spend fixing issues and adding new
features, by not reporting duplicate issues.  Providing the following information will increase the
chances of your issue being dealt with quickly:

* **Overview of the issue** - if an error is being thrown a stack trace helps
* **Motivation for or Use Case** - explain why this is a bug for you
* **JHipster Version(s)** - is it a regression?
* **JHipster configuration, a `.yo-rc.json` file generated in the root folder** - this will help us to replicate the scenario, you can remove the rememberMe key.
* **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory** - if the error is during an entity creation or associated with a specific entity
* **Browsers and Operating System** - is this a problem with all browsers or only IE8?
* **Reproduce the error** - an unambiguous set of steps to reproduce the error. If you have a JavaScript error, maybe you can provide a live example with
  [JSFiddle](http://jsfiddle.net/)?
* **Related issues** - has a similar issue been reported before?
* **Suggest a Fix** - if you can't fix the bug yourself, perhaps you can point to what might be
  causing the problem (line of code or commit)

Click [here][1] to open a bug issue with a pre-filled template.

Issues opened without any of these info will be **closed** without any explanation.
