### ISSUE TITLE
Angular-fontawesome 401

### ISSUE THREAD

**Issue by jlopezjuy** [jhipster/generator-jhipster#8103] opened 2018-08-16 01:14 UTC
##### **Overview of the issue**
Hello, i have create a new monolitic app, when run npm install i have 401 error on angular-fontawesome

##### **Reproduce the error**

1- Create new monolitic app
2- no registry
3- jwt
4- mysql
5- h2 local
6- languaje español

##### **Related issues**

i have te next error log message when i run npm install

```
3398 verbose stack Error: 401 Unauthorized: @fortawesome/free-solid-svg-icons@5.2.0
3398 verbose stack     at fetch.then.res (/home/jlopez/.npm-global/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/fetch.js:42:19)
3398 verbose stack     at tryCatcher (/home/jlopez/.npm-global/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
3398 verbose stack     at Promise._settlePromiseFromHandler (/home/jlopez/.npm-global/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
3398 verbose stack     at Promise._settlePromise (/home/jlopez/.npm-global/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
3398 verbose stack     at Promise._settlePromise0 (/home/jlopez/.npm-global/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
3398 verbose stack     at Promise._settlePromises (/home/jlopez/.npm-global/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
3398 verbose stack     at Async._drainQueue (/home/jlopez/.npm-global/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:133:16)
3398 verbose stack     at Async._drainQueues (/home/jlopez/.npm-global/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
3398 verbose stack     at Immediate.Async.drainQueues (/home/jlopez/.npm-global/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
3398 verbose stack     at runCallback (timers.js:810:20)
3398 verbose stack     at tryOnImmediate (timers.js:768:5)
3398 verbose stack     at processImmediate [as _immediateCallback] (timers.js:745:5)
3399 verbose cwd /media/jlopez/Disco D/Proyectos/España/vpanel-v2
3400 verbose Linux 4.16.0-0.bpo.2-amd64
3401 verbose argv "/usr/bin/node" "/home/jlopez/.npm-global/bin/npm" "install"
3402 verbose node v8.11.3
3403 verbose npm  v6.4.0
3404 error code E401
3405 error 401 Unauthorized: @fortawesome/free-solid-svg-icons@5.2.0
3406 verbose exit [ 1, true ]
```

##### **JHipster Version(s)**

jhipster 5.2.0

##### **JHipster configuration**

```
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.alicompritas.vpanel.app",
      "nativeLanguage": "es"
    },
    "jhipsterVersion": "5.2.0",
    "applicationType": "monolith",
    "baseName": "vpanel",
    "packageName": "com.alicompritas.vpanel.app",
    "packageFolder": "com/alicompritas/vpanel/app",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": true,
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "my-key",
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "npm",
    "testFrameworks": [
      "cucumber",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "es",
    "languages": [
      "es"
    ]
  }
}
```

##### **Browsers and Operating System**

LInux Debian stretch, Chrome WebBrowser

**Comment by jdubois** [comment] 2018-08-16 09:38
This looks like an NPM error to me - the package is available there, and you have a 401 error when trying to get it. Are you behind a proxy, or using your own NPM mirror? Or maybe your Yarn cache has an issue, you can try deleting it.

Could you try on on another machine, maybe?

For me this isn't a JHipster bug, as it's an authorization error on a public NPM package, and that's why I'm closing this.

**Closed by jdubois** 2018-08-16 09:38 UTC

**Comment by jdubois** [comment] 2018-08-16 11:38
I'm sorry but I can't reproduce... I see you are using NPM, which is not our default and which very few people use with JHipster -> could you try again, using Yarn? I did test with your exact config, but this might solve your issue

**Comment by gmarziou** [comment] 2018-08-16 16:34
Solution found on SO: https://stackoverflow.com/questions/51858405/jhipster-5-2-0-error-with-angular-fontawesome
