### ISSUE TITLE
too many space and wrap when i use yo jhipster:import-jdl generate entity

### ISSUE THREAD

**Issue by anjia0532** [jhipster/generator-jhipster#4309] opened 2016-10-11 10:10 UTC
https://jhipster.github.io/jdl/#a-namecommentingjdla-commenting--javadoc support java-doc it's so cool,but something is wrong with the `yo jhipster:import-jdl`

jdl code like this
```
/**
 * blog demo
 */
entity Blog {
   /**
     * author's name
     */
   name String required
}
```

generator Blog.java like this

```java

/**
 * blog demo                                                                          //(about 70 space)
 * 
 */
@ApiModel(description = ""
    + "Class comments.@author The JHipster team.                              "
    + "")
@Entity
@Table(name = "blog")
@Cache(usage = CacheConcurrencyStrategy.NONSTRICT_READ_WRITE)
public class Blog implements Serializable {

    private static final long serialVersionUID = 1L;

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    /**
     * deptartment's Code                                                      
     * 
     */
    @ApiModelProperty(value = ""
        + "deptartment's Code                                                 "
        + "")
    @NotNull
    @Column(name = "dept_id", nullable = false)
    private String deptId;
```

it has too many space and wrap to manual remove it

**Comment by deepu105** [comment] 2016-10-11 10:23
can you please open this in the jhipster-core project as the conversion happens there

**Comment by anjia0532** [comment] 2016-10-11 10:33
OK .sorry

**Comment by cbornet** [comment] 2016-10-11 20:59
The issue is in the main gen. See https://github.com/jhipster/jhipster-core/issues/73

**Comment by jdubois** [comment] 2016-10-12 13:06
Closing this as duplicate, then.

**Comment by deepu105** [comment] 2016-10-12 13:14
@jdubois its an issue here and not in core, the other issue is already closed

**Comment by jdubois** [comment] 2016-10-12 13:16
OK, sorry!

**Comment by cbornet** [comment] 2016-10-13 07:18
We need to fix that.

**Comment by anjia0532** [comment] 2016-10-13 15:42
@cbornet @deepu105 @jdubois 

look at [generator-base.js](https://github.com/jhipster/generator-jhipster/blob/master/generators/generator-base.js#L1632) line 1632-1638

```js
Generator.prototype.formatAsApiModel = function (text) {
    return jhipsterUtils.wordwrap(text.replace(/\\/g, '\\\\').replace(/\"/g, '\\\"'), WORD_WRAP_WIDTH - 9, '"\n    + "', true);
};

Generator.prototype.formatAsApiModelProperty = function (text) {
    return jhipsterUtils.wordwrap(text.replace(/\\/g, '\\\\').replace(/\"/g, '\\\"'), WORD_WRAP_WIDTH - 13, '"\n        + "', true);
};
```

and [jhipsterUtils.wordwrap](https://github.com/jhipster/generator-jhipster/blob/master/generators/util.js#L200)

```js
function wordwrap (text, width, seperator, keepLF) {
    var wrappedText = '';
    var rows = text.split('\n');
    for (var i = 0; i < rows.length; i++) {
        var row = rows[i];
        if (keepLF === true && i !== 0) {
            wrappedText = wrappedText + '\\n';
        }
        wrappedText = wrappedText + seperator + _.padEnd(row,width) + seperator;
    }
    return wrappedText;
}
```

loop the lines(\n),append \\n to this string,so,demo
```java
/** //line1
 * blog demo /line2
 */ //line3
```
output

```java
@ApiModel(value = ""//loop rows 1 append \\n
        + "blog demo"//loop rows 2 append \\n
        + "")//loop rows 2 append \\n
```

and many space because of _.[padEnd](https://lodash.com/docs/4.16.4#padEnd)(row,[width](https://github.com/jhipster/generator-jhipster/blob/master/generators/generator-base.js#L19))
padding width-row.length space to wrappedText

**Comment by anjia0532** [comment] 2016-10-13 15:52
about wordwrap,i think that's not good, should be like trim,remove invalid content.and auto padding space,it's not beautiful,when text length > `WORD_WRAP_WIDTH(80)` wordwrap,otherwise it will not be attended to.

**Comment by cbornet** [comment] 2016-10-13 16:05
Would you make a PR to fix that ?

**Comment by anjia0532** [comment] 2016-10-17 05:30
@cbornet i create PR to fix this bug,
bug in the [entity/index.js#L197](https://github.com/jhipster/generator-jhipster/blob/master/generators/entity/index.js#L197 )

```javascript
 try {
            this.fileData = this.fs.readJSON(this.fromPath);
        } catch (err) {
            this.error(chalk.red('\nThe entity configuration file could not be read!\n'));
        }
        this.relationships = this.fileData.relationships;
        this.fields = this.fileData.fields;
        this.changelogDate = this.fileData.changelogDate;
        this.dto = this.fileData.dto;
        this.service = this.fileData.service;
        this.fluentMethods = this.fileData.fluentMethods;
        this.pagination = this.fileData.pagination;
        this.javadoc = this.fileData.javadoc;
```
`this.fs.readJSON(this.fromPath)` when this.fs.readJSON run,it return the javadoc in one line(lose` \n`) ,and i dot't know this.fs.readJSON function body,so i cannot fix multi line javadoc -> one line javadoc bug

**Closed** 2016-10-18 09:46 UTC
Labels: bug, minor
