### ISSUE TITLE
Docker image: npm ERR! husky@1.2.0 install: `node husky install`

### ISSUE THREAD

**Issue by dkirrane** [jhipster/generator-jhipster#9107] opened 2019-01-22 09:27 UTC
##### **Overview of the issue**

I'm running jhipster with Docker Image `jhipster/jhipster:5.7.2`.
On Windows 10 with Docker for Windows `Version 2.0.0.0-win81 (29211)`

Error: *npm ERR! husky@1.2.0 install: `node husky install`*

```
I'm all done. Running npm install for you to install the required dependencies. If this fails, try running the command yourself.


npm WARN deprecated swagger-ui@2.2.10: No longer maintained, please upgrade to swagger-ui@3.
npm WARN deprecated kleur@2.0.2: Please upgrade to kleur@3 or migrate to 'ansi-colors' if you prefer the old syntax. Visit <https://github.com/lukeed/kleur/releases/tag/v3.0.0\> for migration path(s).

> husky@1.2.0 install /home/jhipster/app/node_modules/husky
> node husky install

fs.js:115
    throw err;
    ^

Error: EINVAL: invalid argument, open '/home/jhipster/app/node_modules/husky/package.json'
    at Object.openSync (fs.js:436:3)
    at Object.readFileSync (fs.js:341:35)
    at Object.Module._extensions..json (internal/modules/cjs/loader.js:705:20)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/jhipster/app/node_modules/husky/husky.js:2:13)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
npm WARN rollback Rolling back get-stdin@6.0.0 failed (this is probably harmless): ENOTEMPTY: directory not empty, rmdir '/home/jhipster/app/node_modules/get-stdin'
npm WARN rollback Rolling back p-limit@2.1.0 failed (this is probably harmless): ENOTEMPTY: directory not empty, rmdir '/home/jhipster/app/node_modules/husky/node_modules/p-limit'
npm WARN rollback Rolling back p-locate@3.0.0 failed (this is probably harmless): ENOTEMPTY: directory not empty, rmdir '/home/jhipster/app/node_modules/husky/node_modules/p-locate'
npm WARN rollback Rolling back p-try@2.0.0 failed (this is probably harmless): ENOTEMPTY: directory not empty, rmdir '/home/jhipster/app/node_modules/husky/node_modules/p-try'
npm WARN rollback Rolling back run-node@1.0.0 failed (this is probably harmless): ENOTEMPTY: directory not empty, rmdir '/home/jhipster/app/node_modules/run-node'
npm WARN rollback Rolling back pify@3.0.0 failed (this is probably harmless): ENOTEMPTY: directory not empty, rmdir '/home/jhipster/app/node_modules/husky/node_modules/pify'
npm WARN rollback Rolling back slash@2.0.0 failed (this is probably harmless): ENOTEMPTY: directory not empty, rmdir '/home/jhipster/app/node_modules/husky/node_modules/slash'
npm WARN rollback Rolling back parse-json@4.0.0 failed (this is probably harmless): ENOTEMPTY: directory not empty, rmdir '/home/jhipster/app/node_modules/husky/node_modules/parse-json'
npm WARN rollback Rolling back locate-path@3.0.0 failed (this is probably harmless): ENOTEMPTY: directory not empty, rmdir '/home/jhipster/app/node_modules/husky/node_modules/locate-path'
npm WARN rollback Rolling back pump@3.0.0 failed (this is probably harmless): ENOTEMPTY: directory not empty, rmdir '/home/jhipster/app/node_modules/husky/node_modules/pump'
npm WARN rollback Rolling back find-up@3.0.0 failed (this is probably harmless): ENOTEMPTY: directory not empty, rmdir '/home/jhipster/app/node_modules/husky/node_modules/find-up'
npm WARN rollback Rolling back nan@2.12.1 failed (this is probably harmless): ENOTEMPTY: directory not empty, rmdir '/home/jhipster/app/node_modules/nan'
npm WARN rollback Rolling back pkg-dir@3.0.0 failed (this is probably harmless): ENOTEMPTY: directory not empty, rmdir '/home/jhipster/app/node_modules/husky/node_modules/pkg-dir'
npm WARN rollback Rolling back get-stream@4.1.0 failed (this is probably harmless): ENOTEMPTY: directory not empty, rmdir '/home/jhipster/app/node_modules/husky/node_modules/get-stream'
npm WARN rollback Rolling back read-pkg@4.0.1 failed (this is probably harmless): ENOTEMPTY: directory not empty, rmdir '/home/jhipster/app/node_modules/husky/node_modules/read-pkg'
npm WARN rollback Rolling back execa@1.0.0 failed (this is probably harmless): ENOTEMPTY: directory not empty, rmdir '/home/jhipster/app/node_modules/husky/node_modules/execa'
npm WARN rollback Rolling back cross-spawn@6.0.5 failed (this is probably harmless): ENOTEMPTY: directory not empty, rmdir '/home/jhipster/app/node_modules/husky/node_modules/cross-spawn'
npm WARN rollback Rolling back husky@1.2.0 failed (this is probably harmless): ENOTEMPTY: directory not empty, rmdir '/home/jhipster/app/node_modules/husky/node_modules/cross-spawn'
npm WARN bootstrap@4.1.3 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.
npm WARN bootstrap@4.1.3 requires a peer of popper.js@^1.14.3 but none is installed. You must install peer dependencies yourself.
npm WARN ng-jhipster@0.5.6 requires a peer of @angular/core@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ng-jhipster@0.5.6 requires a peer of @angular/router@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ngx-webstorage@2.0.1 requires a peer of @angular/core@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! husky@1.2.0 install: `node husky install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the husky@1.2.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-01-22T09_10_20_483Z-debug.log
Application successfully committed to Git.
```

##### **Reproduce the error**

run Docker Image `jhipster/jhipster:latest`
run jhipster

##### **JHipster Version(s)**

Docker Image `jhipster/jhipster:5.7.2`

##### **JHipster configuration**

```
jhipster info
INFO! Using JHipster version installed locally in current project's node_modules
INFO! Executing jhipster:info
INFO! Options: from-cli: true
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
journey@0.0.0 /home/jhipster/app
`-- generator-jhipster@5.7.2

```


##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**


<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.journey",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "5.7.2",
    "applicationType": "monolith",
    "baseName": "Journey",
    "packageName": "com.mycompany.journey",
    "packageFolder": "com/mycompany/journey",
    "serverPort": "8080",
    "authenticationType": "session",
    "cacheProvider": "no",
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "mysql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "rememberMeKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "npm",
    "testFrameworks": [
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "otherModules": [],
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ]
  }
}
</pre>
</details>


##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>


##### **Environment and Tools**

openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-8u191-b12-0ubuntu0.18.04.1-b12)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)

git version 2.17.1

node: v10.14.1

npm: 6.5.0

yeoman: 2.0.5

yarn: 1.12.3

INFO! Congratulations, JHipster execution is complete!
```

##### **Browsers and Operating System**

`Windows 10 Enterprise 64-bit (10.0, Build 17134)`

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by jason1gh** [comment] 2019-01-28 16:00
I got the same error and here is the steps/commands.
  Win10 Version 1803
  Docker Desktop Community Version 2.0.0.2 (30215), Engine 18.09.1
  Docker image: jhipster/jhipster:latest   (5.7.2)

  From windows command prompt enter commands:
      docker container run --name ed -v C:\Users\john\dockerroot\ed:/home/jhipster/app -v C:\Users\john\dockerroot\.m2:/home/jhipster/.m2 -p 8080:8080 -p 9000:9000 -p 3001:3001 -d -t jhipster/jhipster
      docker container exec -it ed bash

  Upon attached to the container, the ~/app directory is empty, issue following commands under ~/app:
     jhipster        - this command run successfully
     jhipster import-jdl ed.jdl    - this command run successfully
     ./mvnw -Pprod package    - this command emit the error reported

  Here is the .yo-rc.json
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.company.ed"
    },
    "jhipsterVersion": "5.7.2",
    "applicationType": "monolith",
    "baseName": "ed",
    "packageName": "com.company.ed",
    "packageFolder": "com/company/ed",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "NWY4ZjdhMWNjYjJkNzg3NWM2ZjNiNTUyMjFmZWY3YWRlMDY5MjBkYTA1MTYxNjUyNTFiZmI1Y2ZhYWRmODRiM2ZiZmIzMDFiMzRhMTc4MzRmMmRiOWZjYTRiMDZiMmIzODFiNGEwMDgxZDA2NzE3ZjFhNTZiMWUyYjA2ZDkzNDQ=",
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "npm",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "otherModules": [],
    "enableTranslation": false
  }

**Comment by pascalgrimaud** [comment] 2019-02-05 09:35
@dkirrane : What command are you using to run jhipster from the docker image ?

@jason1gh : can you try without mounting volume ? Once you're inside the container, are you with "jhipster" user and not "root" user ?

**Comment by pascalgrimaud** [comment] 2019-02-06 12:03
Here our daily CI tests:
https://github.com/hipster-labs/jhipster-daily-builds/blob/master/test-integration/scripts/26-tests-docker.sh#L8-L23

Here the logs:
https://dev.azure.com/hipster-labs/jhipster-daily-builds/_build/results?buildId=1231

For me, everything works well.
I'm closing this because no answer from the original author, unless you provided more information to reproduce.

**Closed by pascalgrimaud** 2019-02-06 12:03 UTC
Labels: docker :whale:, waiting for information

**Comment by jason1gh** [comment] 2019-02-15 23:56
@PierreBesson: Thanks for the suggestion. 

With the latest image, without volume mounted, the command run successfully. 

With volume mounted, the mounted volume owned by root, if attach to the container as user jhipster, command jhipster won't run as it could not create any file/folder. Attach to the container as root can run commands jhipster and mvnw package successfully.

**Comment by banothurameshnaik** [comment] 2020-05-06 05:33
Facing same issue with Docker image `node:12.4.0-alpine`

```
npm ERR! prepareGitDep 1> 
npm ERR! prepareGitDep > husky@1.2.0 install /root/.npm/_cacache/tmp/git-clone-3d1c069d/node_modules/husky
npm ERR! prepareGitDep > node husky install
npm ERR! prepareGitDep 
npm ERR! prepareGitDep 
npm ERR! prepareGitDep 2> npm WARN install Usage of the `--dev` option is deprecated. Use `--only=dev` instead.
npm ERR! prepareGitDep npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm ERR! prepareGitDep npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm ERR! prepareGitDep npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm ERR! prepareGitDep internal/modules/cjs/loader.js:626
npm ERR! prepareGitDep     throw err;
npm ERR! prepareGitDep     ^
npm ERR! prepareGitDep 
npm ERR! prepareGitDep Error: Cannot find module '/root/.npm/_cacache/tmp/git-clone-3d1c069d/node_modules/husky/husky'
npm ERR! prepareGitDep     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:623:15)
npm ERR! prepareGitDep     at Function.Module._load (internal/modules/cjs/loader.js:527:27)
npm ERR! prepareGitDep     at Function.Module.runMain (internal/modules/cjs/loader.js:837:10)
npm ERR! prepareGitDep     at internal/main/run_main_module.js:17:11 {
npm ERR! prepareGitDep   code: 'MODULE_NOT_FOUND',
npm ERR! prepareGitDep   requireStack: []
npm ERR! prepareGitDep }
npm ERR! prepareGitDep npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/chokidar/node_modules/fsevents):
npm ERR! prepareGitDep npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! prepareGitDep npm WARN huddl-logger@0.0.1 No repository field.
npm ERR! prepareGitDep 
npm ERR! prepareGitDep npm ERR! code ELIFECYCLE
npm ERR! prepareGitDep npm ERR! errno 1
npm ERR! prepareGitDep npm ERR! husky@1.2.0 install: `node husky install`
npm ERR! prepareGitDep npm ERR! Exit status 1
npm ERR! prepareGitDep npm ERR! 
npm ERR! prepareGitDep npm ERR! Failed at the husky@1.2.0 install script.
npm ERR! prepareGitDep npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! prepareGitDep 
npm ERR! prepareGitDep npm ERR! A complete log of this run can be found in:
npm ERR! prepareGitDep npm ERR!     /root/.npm/_logs/2020-05-06T05_24_57_260Z-debug.log
npm ERR! prepareGitDep 
npm ERR! premature close
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-05-06T05_24_57_367Z-debug.log
```

Can someone help me out.
