### ISSUE TITLE
React: Protractor e2e entity tests are flaky

### ISSUE THREAD

**Issue by Abdull** [jhipster/generator-jhipster#8379] opened 2018-09-21 12:24 UTC
##### **Overview of the issue**
Running `npm run e2e` on JHipster-generated entities and their Protractor test specs has them sometimes/nondeterministically hang during the _should delete last {EntityName}_ test:

```
1) KEntity e2e test
       should delete last KEntity:
     Error: Timeout of 30000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (C:\Users\Abdull\git\jhipster-react-flaky-e2e-testing\src\test\javascript\e2e\entities\k-entity\k-entity.spec.ts)
```

When this happens, the automated Chrome window hangs at the following sample window until test timeout:
![flaky-test](https://user-images.githubusercontent.com/529862/45879801-19362600-bda6-11e8-86e7-588dd0b68f39.png)

##### **Motivation for or Use Case**
Tests should be reliable in order to keep test writing motivation up. 

##### **Reproduce the error**
* Clone https://github.com/jhipster/jhipster-sample-app-react/tree/v5.3.4 
* Add a bunch of entities with fields, e.g. `jhipster import-jdl jhipster-jdl.jh`:
```
/* jhipster-jdl.jh */ 
entity AEntity {
    name String required
}

entity BEntity {
    name String required
}

entity CEntity {
    name String required
}

entity DEntity {
    name String required
}

entity EEntity {
    name String required
}

entity FEntity {
    name String required
}

entity GEntity {
    name String required
}

entity HEntity {
    name String required
}

entity IEntity {
    name String required
}

entity JEntity {
    name String required
}

entity KEntity {
    name String required
}

dto * with mapstruct

service * with serviceClass
```
* Start up backend: `mvn`.
* Start Protractor E2E tests: `npm run e2e`.

As the issue is nondeterministic, it may require several test runs.

##### **Suggest a Fix**
As this behavior sometimes happens and sometimes not, it feels to me like a race condition due to not correctly awaiting some Protractor promise's resolution.

##### **JHipster Version(s)**

```
jhipster-sample-application-react@0.0.0 C:\Users\User\git\jhipster-react-flaky-e2e-testing
`-- generator-jhipster@5.3.4

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "baseName": "jhipsterSampleApplicationReact",
    "packageName": "io.github.jhipster.sample",
    "packageFolder": "io/github/jhipster/sample",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "mysql",
    "useCompass": false,
    "buildTool": "maven",
    "searchEngine": false,
    "enableTranslation": true,
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling",
      "protractor"
    ],
    "languages": [
      "en"
    ],
    "serverPort": 8080,
    "jhipsterVersion": "5.3.4",
    "enableSocialSignIn": false,
    "useSass": false,
    "jhiPrefix": "jhi",
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "clientPackageManager": "npm",
    "clientFramework": "react",
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "reactive": false
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity BankAccount {
  name String required,
  balance BigDecimal required
}
entity Label {
  label String required minlength(3)
}
entity Operation {
  date DateTime required,
  description String,
  amount BigDecimal required
}
entity AEntity {
  name String required
}
entity BEntity {
  name String required
}
entity CEntity {
  name String required
}
entity DEntity {
  name String required
}
entity EEntity {
  name String required
}
entity FEntity {
  name String required
}
entity GEntity {
  name String required
}
entity HEntity {
  name String required
}
entity IEntity {
  name String required
}
entity JEntity {
  name String required
}
entity KEntity {
  name String required
}
relationship OneToMany {
  BankAccount{operation} to Operation{bankAccount(name)}
}
relationship ManyToOne {
  BankAccount{user(login)} to User
}
relationship ManyToMany {
  Operation{label(label)} to Label{operation}
}

dto BankAccount, Label, Operation, AEntity, BEntity, CEntity, DEntity, EEntity, FEntity, GEntity, HEntity, IEntity, JEntity, KEntity with mapstruct
paginate Operation with infinite-scroll
service AEntity, BEntity, CEntity, DEntity, EEntity, FEntity, GEntity, HEntity, IEntity, JEntity, KEntity with serviceClass

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_112"
Java(TM) SE Runtime Environment (build 1.8.0_112-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.112-b15, mixed mode)

git version 2.17.0

node: v8.11.4

npm: 5.6.0

yeoman: 1.8.5

yarn: 1.10.0

Operating System: Windows 7 64 bit

Chrome: Tested in `Version 68.0.3440.106 (Offizieller Build) (64-Bit)` and `Version 69.0.3497.100 (Offizieller Build) (64-Bit)` (latest version as of this writing).

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by deepu105** [comment] 2018-09-21 13:50
Its a common issue with e2e setups, especially Protractor. If you have a
solution you are welcome to PR it

Thanks & Regards,
Deepu

**Comment by Tcharl** [comment] 2018-10-06 18:01
It's a common issue... When using protractor without using their promise wrappers, and disabling protractor Angular event listeners to have async/await...

After that migration to 5.3.4, we've lost 10 days to have no flaky tests, and I think you won't like the solution:

We've put many ugly 
```
await browser.wait(ExpectedConditions.visibilityOf(_element), this.DEFAULT_TIMEOUT);
expect(await _element.isDisplayed()).to.be.true;
```
At the lines which had flaky behaviors.

And we don't know if that's really fixed for us: we're not sure that all the checks has been done.
I can always make a PR to add our checks, but expect slower and uglier tests.

Otherwise, I would recommend to drop async/await and use protractor.promise wrappers: our old tests were never flaky when implemented well.

**Comment by jdubois** [comment] 2018-10-17 08:48
It also seems I have sometimes have the issue with Protractor + Angular.
I'm closing this as we don't have a solution here, that's probably a Protractor issue as far as I understand (and what they do isn't easy, so it's not a criticism!)

**Comment by deepu105** [comment] 2018-10-17 09:49
@jdubois This is the same issue that fails our Travis build all the time, i'll like to find a workaround or solution for this, I think we need to fix this else its very annoying in Travis, can we reopen add a bounty on this

**Comment by DanielFran** [comment] 2018-10-17 09:54
@jdubois @deepu105 Actually we see always the same e2e test for react that is failing!

**Comment by deepu105** [comment] 2018-10-17 10:01
I believe there is a solution, it's probably something that we are doing
wrong

Thanks & Regards,
Deepu

**Comment by deepu105** [comment] 2018-10-17 18:48
Ok we really have to fix this as its failing every PR and is annoying. Sorry @jdubois, I know you don't like long standing tickets but this one needs to be fixed. Lets put a bounty

**Comment by pascalgrimaud** [comment] 2018-10-17 20:36
Sorry I forgot to communicate.
When working on Azure, I got a lot lot lot of random failures with Protractor. The solution I found is to use chrome headless, with the properties : JHI_E2E_HEADLESS: true

We could try it in Travis too. 
What do you think ?

**Comment by pascalgrimaud** [comment] 2018-10-20 08:38
Although my PR against master branch, I think it is not totally resolved.
See https://travis-ci.org/hipster-labs/jhipster-travis-build/branches

All react builds seems randomly broken since 4 days

**Comment by pascalgrimaud** [comment] 2018-10-21 08:18
I spent a lot of time to understand where the problem is, and I think I found a fix.
FYI, to reproduce the problem, I used this script:
```bash
#!/bin/bash

export JHI_E2E_HEADLESS=true

status=0
start=$(date)

while [[ "$status" == 0 ]]; do
  npm run e2e
  status=$?
done

finish=$(date)

echo Start : $start
echo Finish: $finish
```

PR done: https://github.com/jhipster/generator-jhipster/pull/8621

**Closed** 2018-10-21 09:39 UTC
Labels: $100

**Comment by pascalgrimaud** [comment] 2018-10-30 15:32
bounty claimed https://opencollective.com/generator-jhipster/expenses/5502
