### ISSUE TITLE
Users are not listed in dropdown for many-to-one relationship

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#13862] opened 2021-02-06 05:23 UTC
##### **Overview of the issue**

If you create a reactive microservices architecture like the following, there are no users in the dropdown when you add a new blog.

```
jhipster jdl reactive-ms
```

<img width="697" alt="Screen Shot 2021-02-05 at 10 20 43 PM" src="https://user-images.githubusercontent.com/17892/107109800-66dd4d00-6800-11eb-8481-8985da17db08.png">

##### **Motivation for or Use Case**

You should be able to generate a microservices architecture with reactive-ms.jdl and all e2e tests pass.

##### **Reproduce the error**

```
jhipster jdl reactive-ms
cd gateway
jhkeycloakup
jhregistryup
./gradlew
# open a new terminal
cd ../blog
jhneo4jup
./gradlew
# open a new terminal
cd ../store
jhmongoup
./gradlew
# open a new terminal
cd ../gateway
npm run e2e
```

##### **Suggest a Fix**

I'm not sure if it's a Neo4j issue or something else. The users dropdown should have the currently authenticated user as an option.

##### **JHipster Version(s)**

`main` branch as of Feb 5, 2021.

**Comment by pascalgrimaud** [comment] 2021-02-06 10:00
Are you sure the JDL is correct ?
- blog is a microservice with OAuth2
- so it can't have User table, as it's microservice
- only the gateway should have the User table (sync with idp)
- doing a relationship between a table in microservice and the user table in gateway looks strange

**Comment by mraible** [comment] 2021-02-06 15:55
Yes, I'm sure. I've used a similar pattern for years for a lot of my JHipster microservice demos. I tried it with the JDL from [Java Microservices with Spring Cloud Config and JHipster](https://developer.okta.com/blog/2019/05/23/java-microservices-spring-cloud-config) (published in May 2019).

```
application {
  config {
    baseName gateway,
    packageName com.okta.developer.gateway,
    applicationType gateway,
    authenticationType oauth2,
    prodDatabaseType postgresql,
    serviceDiscoveryType eureka,
    testFrameworks [protractor]
  }
  entities Blog, Post, Tag, Product
}

application {
  config {
    baseName blog,
    packageName com.okta.developer.blog,
    applicationType microservice,
    authenticationType oauth2,
    prodDatabaseType postgresql,
    serverPort 8081,
    serviceDiscoveryType eureka
  }
  entities Blog, Post, Tag
}

application {
  config {
    baseName store,
    packageName com.okta.developer.store,
    applicationType microservice,
    authenticationType oauth2,
    databaseType mongodb,
    devDatabaseType mongodb,
    prodDatabaseType mongodb,
    enableHibernateCache false,
    serverPort 8082,
    serviceDiscoveryType eureka
  }
  entities Product
}

entity Blog {
  name String required minlength(3),
  handle String required minlength(2)
}

entity Post {
  title String required,
  content TextBlob required,
  date Instant required
}

entity Tag {
  name String required minlength(2)
}

entity Product {
  title String required,
  price BigDecimal required min(0),
  image ImageBlob
}

relationship ManyToOne {
  Blog{user(login)} to User,
  Post{blog(name)} to Blog
}

relationship ManyToMany {
  Post{tag(name)} to Tag{post}
}

paginate Post, Tag with infinite-scroll
paginate Product with pagination

microservice Product with store
microservice Blog, Post, Tag with blog

// will be created under 'docker-compose' folder
deployment {
  deploymentType docker-compose
  appsFolders [gateway, blog, store]
  dockerRepositoryName "jmicro"
}
```

I started everything and navigated to create a new blog. I logged in with `admin` and you can see my user in the dropdown.

![image](https://user-images.githubusercontent.com/17892/107123116-f7477c00-6858-11eb-9e1e-64713ab6b285.png)

**Comment by mraible** [comment] 2021-02-06 16:28
This appears to be a Vue issue. If I change my JDL to use Angular, it works.

![image](https://user-images.githubusercontent.com/17892/107123885-78087700-685d-11eb-9825-7f138f0025f5.png)

**Comment by pascalgrimaud** [comment] 2021-02-06 16:34
Indeed, you're right, @mraible as I just tried with your JDL:
- generate microservice with OAuth2 -> table jhi_user is generated
- generate microservice with JWT -> table jhi_user is not generated

It means:
- you can have relationship with User only with OAuth2
- it's possible because of `syncUserWithIdP` method
- it's not possible to generate a microservice with OAuth2 without this table jhi_user

**Comment by mraible** [comment] 2021-02-06 16:47
I removed all my Docker images and tried again with React. It works there too, so the problem seems to be isolated to Vue. 

<img width="1111" alt="Screen Shot 2021-02-06 at 9 44 34 AM" src="https://user-images.githubusercontent.com/17892/107124259-0251da80-6860-11eb-98f2-7ba0d20b27ca.png">

I reported a similar issue in #13465, but that wasn't a microservices JDL.

**Comment by slade13** [comment] 2021-02-12 21:54
I tried to run it from the main branch and it didn't worked. I checked out v7.0.0-beta.1 tag and then i tried to create the blog:
![image](https://user-images.githubusercontent.com/7571921/107825618-b208da00-6d83-11eb-8c2f-6e04295d5dea.png)
After using the current main I get this:
`{
  "type" : "https://www.jhipster.tech/problem/problem-with-message",
  "title" : "Not Found",
  "status" : 404,
  "detail" : "404 NOT_FOUND",
  "path" : "/",
  "message" : "error.http.404"
}`
On the http://localhost:8080
Log from the gateway:
`        Application 'gateway' is running! Access URLs:
        Local:          http://localhost:8080/
        External:       http://192.168.50.158:8080/
        Profile(s):     [dev]
----------------------------------------------------------
2021-02-12 22:52:06.882  INFO 11316 --- [  restartedMain] com.okta.developer.gateway.GatewayApp    :
----------------------------------------------------------
        Config Server:  Connected to the JHipster Registry running in Docker
----------------------------------------------------------
2021-02-12 22:52:13.053  WARN 11316 --- [oundedElastic-1] o.z.problem.spring.common.AdviceTraits   : Not Found: 404 NOT_FOUND
2021-02-12 22:52:16.024  INFO 11316 --- [nfoReplicator-0] com.netflix.discovery.DiscoveryClient    : Saw local status change event StatusChangeEvent [timestamp=1613166736024, current=UP, previous=DOWN]
2021-02-12 22:52:16.024  INFO 11316 --- [nfoReplicator-0] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_GATEWAY/gateway:83cac1febf31471178785c4c7b076ee9: registering service...
2021-02-12 22:52:16.039  INFO 11316 --- [nfoReplicator-0] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_GATEWAY/gateway:83cac1febf31471178785c4c7b076ee9 - registration status: 204
2021-02-12 22:52:18.838  WARN 11316 --- [oundedElastic-1] o.z.problem.spring.common.AdviceTraits   : Not Found: 404 NOT_FOUND
2021-02-12 22:53:06.654  WARN 11316 --- [oundedElastic-1] o.z.problem.spring.common.AdviceTraits   : Not Found: 404 NOT_FOUND`

**Comment by slade13** [comment] 2021-02-12 21:59
I tried to run it from the main branch and it didn't worked. I checked out v7.0.0-beta.1 tag and then i tried to create the blog:
![image](https://user-images.githubusercontent.com/7571921/107825618-b208da00-6d83-11eb-8c2f-6e04295d5dea.png)
After using the current main I get this:
```
{
  "type" : "https://www.jhipster.tech/problem/problem-with-message",
  "title" : "Not Found",
  "status" : 404,
  "detail" : "404 NOT_FOUND",
  "path" : "/",
  "message" : "error.http.404"
}
```
On the http://localhost:8080
Log from the gateway:
```
        Application 'gateway' is running! Access URLs:
        Local:          http://localhost:8080/
        External:       http://192.168.50.158:8080/
        Profile(s):     [dev]
----------------------------------------------------------
2021-02-12 22:52:06.882  INFO 11316 --- [  restartedMain] com.okta.developer.gateway.GatewayApp    :
----------------------------------------------------------
        Config Server:  Connected to the JHipster Registry running in Docker
----------------------------------------------------------
2021-02-12 22:52:13.053  WARN 11316 --- [oundedElastic-1] o.z.problem.spring.common.AdviceTraits   : Not Found: 404 NOT_FOUND
2021-02-12 22:52:16.024  INFO 11316 --- [nfoReplicator-0] com.netflix.discovery.DiscoveryClient    : Saw local status change event StatusChangeEvent [timestamp=1613166736024, current=UP, previous=DOWN]
2021-02-12 22:52:16.024  INFO 11316 --- [nfoReplicator-0] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_GATEWAY/gateway:83cac1febf31471178785c4c7b076ee9: registering service...
2021-02-12 22:52:16.039  INFO 11316 --- [nfoReplicator-0] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_GATEWAY/gateway:83cac1febf31471178785c4c7b076ee9 - registration status: 204
2021-02-12 22:52:18.838  WARN 11316 --- [oundedElastic-1] o.z.problem.spring.common.AdviceTraits   : Not Found: 404 NOT_FOUND
2021-02-12 22:53:06.654  WARN 11316 --- [oundedElastic-1] o.z.problem.spring.common.AdviceTraits   : Not Found: 404 NOT_FOUND
```

**Comment by pascalgrimaud** [comment] 2021-02-13 11:12
Adding a bounty on this, as it's a bug and we need the fix for the next release

**Comment by atomfrede** [comment] 2021-02-15 20:56
I can't reproduce it (maybe I am doing something wrong). This is what I have with current main branch:

![Screenshot-20210215214556-1880x578](https://user-images.githubusercontent.com/203401/107991612-4ae36380-6fd7-11eb-998c-0482b1bf1521.png)

Nevertheless e2e tests are failing, but it looks like a timing error in protractor while crud flow for `Post`s.

```
  Post e2e test
    ✓ should load Posts (2208ms)
    Create flow
      ✓ should load create Post page
      ✓ should create and save Posts
      Details, Update, Delete flow
        1) should load details Post page and fetch data
        2) should load edit Post page, fetch data and update
        3) "after all" hook: ret for "should load edit Post page, fetch data and update"
```

Did the following:

```
npm link generator-jhipster
jhipster jdl reactive-ms
cd gateway
jhkeycloakup
jhregistryup
./gradlew
# open a new terminal
cd ../blog
jhneo4jup
./gradlew
# open a new terminal
cd ../store
jhmongoup
./gradlew
# open a new terminal
cd ../gateway
npm run e2e
```

**Comment by slade13** [comment] 2021-02-15 21:15
I pulled current main but still the same issue after visiting http://localhost:8080/:
```
{
"type": "https://www.jhipster.tech/problem/problem-with-message",
"title": "Not Found",
"status": 404,
"detail": "404 NOT_FOUND",
"path": "/",
"message": "error.http.404"
}
```
I am using Windows, I found out that after reverting changes in commit 525b1b223b327399c907d501d8faa06f05f2a344 everything just works fine. I tried to upgrade **webpack** from v4 to v5 and I received the same problem as a result.

Can you check if you can run **gateway** in production mode?

`gradlew -Pprod`

**Comment by atomfrede** [comment] 2021-02-15 21:16
I am not running in production mode. will check.

**Comment by atomfrede** [comment] 2021-02-15 21:33
Running the gateway in production works just fine with all protractor tests being green. I am using node `14.15.4` and npm `7.5.2`.

**Comment by mshima** [comment] 2021-02-16 15:44
I was looking at https://github.com/jhipster/generator-jhipster/pull/13969 failure and I've found a webpack.common conflict with webpack.prod.
The error occurs when running production profile.

Seems to be related to this bug.

**Comment by mshima** [comment] 2021-02-16 17:53
> I think that it is far more complicated as dev environment doesn't work either. We should create the separate issue for this case. Besides that I found that inside webpack.prod.js are properties which are not compatible with webpack v5 for example HashedModuleIdsPlugin which is mentioned here: https://webpack.js.org/migrate/5/

@slade13 HashedModuleIdsPlugin was removed at https://github.com/jhipster/generator-jhipster/commit/525b1b223b327399c907d501d8faa06f05f2a344.
We are not supporting `beta.1`
See: `HashedModuleIdsPlugin → optimization.moduleIds: 'deterministic'`.

**Comment by mshima** [comment] 2021-02-16 21:30
https://github.com/jhipster/generator-jhipster/pull/13969 is not related to this issue.
So let's clarify, there are a few issues reported here:

1. Original bug report: `reactive-ms` sample fails to load user relationships.
I could not reproduce. I could reproduce when restarting the gateway server. The page loads, but the api fails due to expired token, so user list is empty.
The right approach would be redirect to the login page instead of ignoring.

2. A protractor failure reported at the original bug report at `Reproduce the error` section.
I could reproduce every time I kill the entire stack and recreate it.
The 2nd execution fails  sometimes, after 3rd protractor execution, it succeed every time.
Could not reproduce with cypress and seem related to cold start responsiveness.
Protractor support is deprecated, not sure if we should fix it.

3. A few points reported at https://github.com/jhipster/generator-jhipster/issues/13862#issuecomment-774503711.

4. An issue reported at https://github.com/jhipster/generator-jhipster/issues/13862#issuecomment-778477794.
I could not reproduce and seems unrelated to this issue.

Tasks related to this issue:
1. Force redirect to login when the token is expired.
2. Fix protractor.
3. Implement `syncUser` for jwt authentication
4. Only create `syncUserWithIdP` and `jhi_user` table for oauth2 when a relationship with User exists.

**Comment by slade13** [comment] 2021-02-17 20:09
@mshima do you use Windows or Linux/MacOS? I need this to see if the problem is only on my machine before I will create new issue.

**Comment by mshima** [comment] 2021-02-18 11:43
@slade13 MacOS.

**Comment by pascalgrimaud** [comment] 2021-03-27 10:12
keep it

**Comment by deepu105** [comment] 2023-10-16 12:47
@mshima do you know if this issue is still valid?

**Comment by deepu105** [comment] 2023-10-16 12:47
@mshima do you know if this issue is still valid?

**Comment by mshima** [comment] 2023-10-16 19:09
The original issue is not reproducible, it should be fixed.

There are other issues mentioned:

> Tasks related to this issue:
> 
> 1. Force redirect to login when the token is expired.

should be fixed.

> 2. Fix protractor.

protractor was dropped.

> 3. Implement `syncUser` for jwt authentication

not implemented.

> 4. Only create `syncUserWithIdP` and `jhi_user` table for oauth2 when a relationship with User exists.

not implemented.

Since the initial issue is not reproducible anymore, I think we should close. And open individual issues if makes sense.

**Closed** 2023-10-31 13:48 UTC
Labels: area: bug :bug:, theme: microservice, $100, theme: OIDC/OAuth2, $$ bug-bounty $$, theme: gateway, theme: vue

**Comment by mraible** [comment] 2023-11-01 01:42
I can confirm that the original reason I entered this issue is fixed on `main`.
