### ISSUE TITLE
Blueprint not found when generating an entity

### ISSUE THREAD

**Issue by danielpetisme** [jhipster/generator-jhipster#10257] opened 2019-08-22 14:01 UTC
##### **Overview of the issue**

When using the globally installed `generator-jhipster-dotnetcore` to generate an entity it fails pretenting to not found the blueprint.

Basically it's the same error message that
https://github.com/jhipster/generator-jhipster/issues/10223 and it fails on the same snippet
https://github.com/jhipster/generator-jhipster/blob/master/generators/generator-base-private.js#L837

```
Everything is configured, generating the entity...

     info Using blueprint generator-jhipster-dotnetcore for entity-server subgenerator
     info Using blueprint generator-jhipster-dotnetcore for entity-client subgenerator

Running `webpack:build` to update client app

events.js:173
      throw er; // Unhandled 'error' event
      ^

Error: The generator-jhipster-dotnetcore blueprint provided is not installed. Please install it using command npm i -g generator-jhipster-dotnetcore.
    at Environment.error (/usr/local/lib/node_modules/generator-jhipster/node_modules/yeoman-environment/lib/environment.js:176:40)
    at module.exports.error (/usr/local/lib/node_modules/generator-jhipster-dotnetcore/node_modules/generator-jhipster/generators/generator-base.js:1448:18)
    at shelljs.exec (/usr/local/lib/node_modules/generator-jhipster-dotnetcore/node_modules/generator-jhipster/generators/generator-base-private.js:839:22)
    at /usr/local/lib/node_modules/generator-jhipster-dotnetcore/node_modules/generator-jhipster/node_modules/shelljs/src/exec.js:127:9
    at ChildProcess.exithandler (child_process.js:304:5)
    at ChildProcess.emit (events.js:197:13)
    at maybeClose (internal/child_process.js:984:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
Emitted 'error' event at:
    at Environment.error (/usr/local/lib/node_modules/generator-jhipster/node_modules/yeoman-environment/lib/environment.js:178:15)
    at module.exports.error (/usr/local/lib/node_modules/generator-jhipster-dotnetcore/node_modules/generator-jhipster/generators/generator-base.js:1448:18)
    [... lines matching original stack trace ...]
    at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
````

I already tried to use the fix proposed in https://github.com/jhipster/generator-jhipster/pull/10225 but it doesn't work me.

Actually I had a look to the generated `yoInternalCliPath` and the `yo/lib/cli.js` doesn't exist in my system at this location.
```
>>>>> node /usr/local/lib/node_modules/generator-jhipster-dotnetcore/node_modules/generator-jhipster/node_modules/yo/lib/cli.js --generators
```
IMHO, the issue comes from the global/local npm strategy but I'm can't go deeper.

Currently I workaround the issue by using the `--skip-checks` flag but is not something I want to include in the dotnetcore blueprint communication...

##### **Reproduce the error**

```
npm install -g generator-jhipster
npm install -g generator-jhipster-jhipster
mkdir sampe && cd sample
//Generate an application
jhipster --blueprints dotnetcore
// Generate an entity
jhipster entity BankAccount
```
##### **Related issues**

https://github.com/jhipster/generator-jhipster/issues/10223

##### **Suggest a Fix**

 I think relying on the FS to invoke `yo` is tricky. Can't we import it as a lib and use the internal API to list the generators ? WDYT?

##### **Browsers and Operating System**

Mac

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment] 2019-09-03 19:08
I think jhipster isn't allowing installing blueprints globally.

You should install locally.

Running on Mac too.

**Comment by pascalgrimaud** [comment] 2019-09-05 06:50
it's strange because I don't see any issue with Vue.js blueprint
so probably related to Windows environment ?

**Comment by clement26695** [comment] 2019-09-05 07:40
There is some strange behaviors when the blueprint is locally installed and the generator globally installed (or the other way around, I don't remember exactly). I think that in some cases, yeoman does not find the blueprint... I didn't had time to investigate that for the moment

**Comment by clement26695** [comment] 2019-09-05 07:47
@pascalgrimaud I think this is related: jhipster/jhipster-vuejs#369

**Comment by PierreBesson** [comment] 2019-09-05 09:37
IMO we should never rely on locally installed tools rather than the globally installed ones as we can control their version. This is why I added the `yoInternalCliPath` some time ago. However I'm very surprise that the "yo script" doesn't exist at `generator-jhipster/node_modules/yo/lib/cli` for you @danielpetisme.
As always, it is very hard to debug problems linked to the global install of tools. The only way I know to test if the global install is correct is to do an actual release on NPM and reinstall it on a fresh system.

**Comment by clement26695** [comment] 2019-09-05 13:56
I think @PierreBesson introduced the yoInternalCliPath to not force the user to install yo globally. 

We investigate a bit with @avdev4j and it might come from different places. 

One of them could be that your NODE_PATH environment variable is not correctly set (see: https://stackoverflow.com/questions/15636367/nodejs-require-a-global-module-package and https://nodejs.org/api/modules.html#modules_loading_from_the_global_folders)

But in your case, the issue is that npm flatten the librairies and we arrive at the following node_modules filesystem:
```
- generator-jhipster-dotnetcore
  - node_modules
    - generator-jhipster
        - node_modules
             - no yo here
    - yo
```

We should either adapt the yoInternalCliScript, remove it and force the global install of yo, or force the user to execute the main generator-jhipster not from a dependance

**Comment by avdev4j** [comment] 2019-09-06 08:47
As @clement26695 said,
we did some tests because I got the same problem.

For sure this come from the yo dependency path resolving. NPM seems to store dependencies in at parent level if both parents and children have the same one.

So to fix I made three changes in generator-base-private.js in `findBlueprintVersion()` method.

* Resolve yo by testing two paths
```
        // Path to the yo cli script in generator-jhipster's node_modules
        const buildYoCliPath = (relativeYoCliPath) => { return path.join(__dirname, relativeYoCliPath) };
        const yoCliPathFromNodeModule = buildYoCliPath('../node_modules/yo/lib/cli.js');
        const yoCliPathFromParentDepency = buildYoCliPath('../../yo/lib/cli.js');
        const yoInternalCliPath = fs.existsSync(yoCliPathFromNodeModule) || yoCliPathFromParentDepency;

        if (!fs.existsSync(yoInternalCliPath)) {
            this.error('Yeoman not found in local dependencies.');
        }
```

* Resolve yo by using require.resolve (suggested by @clement26695)
```
        const yoInternalCliPath = require.resolve('yo/lib/cli.js');

        shelljs.exec(`${yoInternalCliPath} --generators`, { silent: true }, (err, stdout, stderr) => {
```

* Resolve yo by using require.resolve and giving path
```
        const yoInternalCliPath = require.resolve('yo/lib/cli.js', [path.join(__dirname, '../node_modules/')]);

        shelljs.exec(`${yoInternalCliPath} --generators`, { silent: true }, (err, stdout, stderr) => {
```

It seems like every case works. Could, some of you, test on your environment and give me some feedbacks?
There is how I did:
- Install my blueprint in global `npm i -g generator-jhipster-myBlueprint`
- Edit generator-base-private.js in the JHipster dependency in my blueprint `usr/local/lib/node_modules/generator-jhipster-myBlueprint/node_modules/generator-jhipster`
- run `usr/local/lib/node_modules/generator-jhipster-myBlueprint/node_modules/generator-jhipster/cli/jhipster.js --blueprints myBlueprint"

**Comment by PierreBesson** [comment] 2019-09-06 11:02
The require.resolve solution (without path) looks fine for me. It seems to be the best as it should support an arbitrary path to the yo cli in the dependency tree.

**Comment by avdev4j** [comment] 2019-09-06 11:52
I agree.

**Closed** 2019-09-06 15:11 UTC
Labels: area: needs-reproduction, theme: blueprint :paw_prints:
