### ISSUE TITLE
Errors when trying to access microservices for the first time

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#10062] opened 2019-07-08 23:30 UTC
##### **Overview of the issue**

When creating JHipster microservices using [this tutorial](https://developer.okta.com/blog/2019/05/23/java-microservices-spring-cloud-config), there's a couple errors when you first run it with Docker Compose.

1. "Request method 'POST' not supported"
2. Every API request (blog or store) throws a 504 time out the first time 

Here's the JDL I used to create everything:

```
application {
  config {
    baseName gateway,
    packageName com.okta.developer.gateway,
    applicationType gateway,
    authenticationType oauth2,
    prodDatabaseType postgresql,
    serviceDiscoveryType eureka,
    testFrameworks [protractor]
  }
  entities Blog, Post, Tag, Product
}

application {
  config {
    baseName blog,
    packageName com.okta.developer.blog,
    applicationType microservice,
    authenticationType oauth2,
    prodDatabaseType postgresql,
    serverPort 8081,
    serviceDiscoveryType eureka
  }
  entities Blog, Post, Tag
}

application {
  config {
    baseName store,
    packageName com.okta.developer.store,
    applicationType microservice,
    authenticationType oauth2,
    databaseType mongodb,
    devDatabaseType mongodb,
    prodDatabaseType mongodb,
    enableHibernateCache false,
    serverPort 8082,
    serviceDiscoveryType eureka
  }
  entities Product
}

entity Blog {
  name String required minlength(3),
  handle String required minlength(2)
}

entity Post {
  title String required,
  content TextBlob required,
  date Instant required
}

entity Tag {
  name String required minlength(2)
}

entity Product {
  title String required,
  price BigDecimal required min(0),
  image ImageBlob
}

relationship ManyToOne {
  Blog{user(login)} to User,
  Post{blog(name)} to Blog
}

relationship ManyToMany {
  Post{tag(name)} to Tag{post}
}

paginate Post, Tag with infinite-scroll
paginate Product with pagination

microservice Product with store
microservice Blog, Post, Tag with blog

// will be created under 'docker-compose' folder
deployment {
  deploymentType docker-compose
  appsFolders [gateway, blog, store]
  dockerRepositoryName "jmicro"
  consoleOptions [zipkin]
}
```

You can also see the source code at https://github.com/oktadeveloper/java-microservices-examples, in the `jhipster` directory.

##### **Motivation for or Use Case**

It's a better developer experience if everything works the first time.

##### **Reproduce the error**

Create a microservices architecture using the above JDL, build Docker images, then run everything in Docker compose. Hit http://localhost:8080 after everything is up and running. Then navigate to microservices in the Entities menu.

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by clement26695** [comment] 2019-07-11 15:41
Just tried and I was not able to reproduce with 6.1.2 and 6.0.1

**Comment by pascalgrimaud** [comment] 2019-08-16 15:48
As @clement26695, just tried too and I was not able to reproduce. The only way to reproduce, is to start one of the microservice after the gateway and tried to access to it -> normal, it is not registered yet, we need to wait at least 1min

I'm closing this as it's a known behaviour with Eureka, depending on the order when the microservice register to Eureka.
Feel free to give more element to reproduce Matt, if you still encounter this issue after waiting 1 or 2min

**Closed by pascalgrimaud** 2019-08-16 15:48 UTC
Labels: $$ bug-bounty $$, $100, area: bug :bug:, theme: microservice

**Comment by gmarziou** [comment] 2019-08-16 19:46
An additional reason for timeout on first request is lazy caching of ribbon context, check https://cloud.spring.io/spring-cloud-netflix/multi/multi_spring-cloud-ribbon.html#ribbon-child-context-eager-load
