### ISSUE TITLE
Changelogs contains "autoincrement" when using UUID as id

### ISSUE THREAD

**Issue by amatosg** [jhipster/generator-jhipster#17945] opened 2022-02-20 19:54 UTC
##### **Overview of the issue**
When creating entities with UUID as id and importing using JDL, autoincrement should not be present in the liquibase changelog as it will produce the following error:

`Caused by: liquibase.exception.UnexpectedLiquibaseException: Property [autoIncrement] was not found for object type [liquibase.datatype.core.UUIDType] `

##### **Motivation for or Use Case**
Adding autoincrement to a UUID field prevents the application from starting

##### **Reproduce the error**
Import a JDL with an entity with  `id UUID`:

```
entity Country {
  id UUID,
  name String required
}
```
And run the application

##### **Related issues**
Haven't found any

##### **Suggest a Fix**
Prevent adding autoincrement when ID is declared as UUID

##### **JHipster Version(s)**
7.6.0

##### **JHipster configuration**

INFO! Using JHipster version installed locally in current project's node_modulesay information about your current project and system)
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
reactive@0.0.1-SNAPSHOT /home/alejandro/projects/reactive
└── generator-jhipster@7.6.0

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "applicationType": "monolith",
    "authenticationType": "jwt",
    "baseName": "reactive",
    "blueprints": [],
    "buildTool": "maven",
    "cacheProvider": "no",
    "clientFramework": "angularX",
    "clientPackageManager": "npm",
    "clientTheme": "sandstone",
    "clientThemeVariant": "primary",
    "creationTimestamp": 1645371838709,
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "devServerPort": 4200,
    "dtoSuffix": "DTO",
    "enableGradleEnterprise": false,
    "enableHibernateCache": false,
    "enableSwaggerCodegen": false,
    "enableTranslation": false,
    "entities": ["Country"],
    "entitySuffix": "",
    "jhiPrefix": "fa",
    "jhipsterVersion": "7.6.0",
    "jwtSecretKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "languages": ["en", "fr"],
    "lastLiquibaseTimestamp": 1645386332000,
    "messageBroker": "kafka",
    "nativeLanguage": "es",
    "otherModules": [],
    "packageName": "com.reactive",
    "pages": [],
    "prodDatabaseType": "postgresql",
    "reactive": true,
    "searchEngine": false,
    "serverPort": "8080",
    "serverSideOptions": ["messageBroker:kafka"],
    "serviceDiscoveryType": "no",
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "skipUserManagement": false,
    "testFrameworks": ["cucumber"],
    "websocket": false,
    "withAdminUi": false
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Country {
  id UUID
  name String required
}

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.14" 2022-01-18
OpenJDK Runtime Environment Temurin-11.0.14+9 (build 11.0.14+9)
OpenJDK 64-Bit Server VM Temurin-11.0.14+9 (build 11.0.14+9, mixed mode)

git version 2.32.0

node: v12.22.5

npm: 7.5.2

Docker version 20.10.12, build e91ed57

docker-compose version 1.29.2, build 5becea4c

No change to package.json was detected. No package manager install will be executed.
Congratulations, JHipster execution is complete!
Sponsored with ❤️  by @oktadev.

##### **Browsers and Operating System**
Linux with IntelliJ

- [x] Checking this box is mandatory (this is just to show you read everything)

Love JHipster? Please consider supporting our collective:
👉  https://opencollective.com/generator-jhipster/donate

**Comment by mshima** [comment] 2022-02-20 23:45
Duplicate of https://github.com/jhipster/generator-jhipster/issues/17835

**Closed** 2022-02-20 23:45 UTC
Labels: area: triage, theme: undefined
