### ISSUE TITLE
Swagger interface not using Authorization header

### ISSUE THREAD

**Issue by nicoraynaud** [jhipster/generator-jhipster#5501] opened 2017-03-28 05:56 UTC
##### **Overview of the issue**

When generating a monolith app, building and running it, the swagger interface under Administration/API is not working as expected.

When debugging, i saw that requests made by swagger interface were not using the Authorization header of the app, thus getting some HTTP 403 Forbidden responses from the server.

I know it was working some time ago, something must have broken it recently.

##### **Motivation for or Use Case**

Be able to use the swagger interface.

##### **Reproduce the error**

Generate a monolith app with JHipster 4.1.1.

##### **Suggest a Fix**

-- no idea

##### **JHipster Version(s)**

JHipster generator-jhipster 4.1.1

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "nc.opt.sido"
    },
    "jhipsterVersion": "4.1.1",
    "baseName": "sido",
    "packageName": "nc.opt.sido",
    "packageFolder": "nc/opt/sido",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "no",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "gradle",
    "enableSocialSignIn": false,
    "jwtSecretKey": "a5fed59aa8712fe4626f200d765c63bc6b4f1356",
    "clientFramework": "angular2",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

none

##### **Browsers and Operating System**

java version "1.8.0_112"
Java(TM) SE Runtime Environment (build 1.8.0_112-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.112-b15, mixed mode)

git version 2.11.0.windows.3

node: v6.9.5

npm: 4.1.1

bower: 1.8.0

gulp:
[16:52:21] CLI version 3.9.1

yeoman: 1.8.5

yarn: 0.19.1

Docker version 1.13.0, build 49bf474

docker-compose version 1.10.0, build 4bd6f1a0

[x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment] 2017-03-28 06:39
I didn't manage to reproduce. Everything works fine for me.

Do you have additional element to reproduce?
- how do you start your application? ./gradlew? with your IDE?
- what is your profile? dev? prod,swagger?
- what is your browser? did you try in private navigation?
- some logs or screenshots?

**Comment by jdubois** [comment] 2017-03-28 07:00
Same thing here, couldn't reproduce.
Closing as we can't reproduce, until @nicoraynaud gives us more information on what he is doing.

**Comment by nicoraynaud** [comment] 2017-03-28 20:20
I am using gradle 3.4 (installed on my computer), starting the app with gradle bootRun and yarn start using default profiles for dev : dev, swagger.

I am using Google Chrome latest version as my browser, i am using private navigation (although i tried with standard nav and have the same behavior). I also tried with Firefox = same result.

Chrome Version 56.0.2924.87
FF Version 52.0.2

To do the tests today, i re generated an app from scratch again. same settings.

![2017-03-29 07_14_49-api](https://cloud.githubusercontent.com/assets/184581/24425368/b525c45a-144f-11e7-954d-18ea37535cdc.png)
![2017-03-29 07_15_23-api](https://cloud.githubusercontent.com/assets/184581/24425370/b72e8836-144f-11e7-9b10-185904e79e5a.png)
![2017-03-29 07_15_55-api](https://cloud.githubusercontent.com/assets/184581/24425372/b9468bd2-144f-11e7-8b1b-9d1a53ebcffb.png)

**Comment by jdubois** [comment] 2017-03-29 21:04
Re-opening this as I could reproduce.
The issue is, I don't know what specific thing I did.... Normally we have CORS enabled, so the BrowserSync front-end should be able to call the REST endpoints, but clearly this is not working here, under "some" situation. Maybe this is linked to hot reload of the front-end.

**Comment by jdubois** [comment] 2017-03-29 21:14
Yes, this is definitely a CORS issue -> it works when you go to port 8080
Now, 2 issues here if you want to test:

- CORS should be correctly configured, I remember this was done
- When doing hot reload, the page on port 8080 gets "corrupted", so you need to do `yarn start` again. I'm with the master branch, so this might be linked to our Angular 4 migration (I'm pretty sure it worked before)

**Comment by nicoraynaud** [comment] 2017-03-30 05:57
I confirm this behavior : 

- using  the app directly at port 8080 i have no problem.
- enabling CORS and using the app through webpack : i have no problem

so the problem seems to only be when using webpack and no CORS.

**Comment by jdubois** [comment] 2017-03-31 13:04
Now I understand, we only enabled it for Websockets! So this all makes sense to me now. Pushing the fix...

**Closed** 2017-03-31 13:05 UTC
Labels: bug
