### ISSUE TITLE
in Jenkins pipeline report error with npm install

### ISSUE THREAD

**Issue by redDevis** [jhipster/generator-jhipster#18250] opened 2022-03-31 09:00 UTC
##### **Overview of the issue**
[](http://10.4.1.51:30180/blue/organizations/jenkins/user-center-apir944p%2Fuser-center-gateway/detail/master/13/pipeline#step-37-log-42)[](http://10.4.1.51:30180/blue/organizations/jenkins/user-center-apir944p%2Fuser-center-gateway/detail/master/13/pipeline#step-37-log-43)[INFO] --- frontend-maven-plugin:1.12.1:npm (npm install) @ gw ---

[INFO] Running 'npm install' in /home/jenkins/agent/workspace/r944p_user-center-gateway_master

[INFO] npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated[](http://10.4.1.51:30180/blue/organizations/jenkins/user-center-apir944p%2Fuser-center-gateway/detail/master/13/pipeline#step-37-log-44)

[INFO] npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated[](http://10.4.1.51:30180/blue/organizations/jenkins/user-center-apir944p%2Fuser-center-gateway/detail/master/13/pipeline#step-37-log-45)

[INFO] npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated[](http://10.4.1.51:30180/blue/organizations/jenkins/user-center-apir944p%2Fuser-center-gateway/detail/master/13/pipeline#step-37-log-46)

[INFO] npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated[](http://10.4.1.51:30180/blue/organizations/jenkins/user-center-apir944p%2Fuser-center-gateway/detail/master/13/pipeline#step-37-log-47)[](http://10.4.1.51:30180/blue/organizations/jenkins/user-center-apir944p%2Fuser-center-gateway/detail/master/13/pipeline#step-37-log-48)[](http://10.4.1.51:30180/blue/organizations/jenkins/user-center-apir944p%2Fuser-center-gateway/detail/master/13/pipeline#step-37-log-49)

[INFO] npm WARN deprecated har-validator@5.1.5: this library is no longer supported

[INFO] npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.

[INFO] npm WARN deprecated @fortawesome/fontawesome-common-types@0.3.0: Please upgrade to 6.1.0. https://fontawesome.com/docs/changelog/[](http://10.4.1.51:30180/blue/organizations/jenkins/user-center-apir944p%2Fuser-center-gateway/detail/master/13/pipeline#step-37-log-50)

[INFO] npm WARN deprecated @fortawesome/fontawesome-svg-core@1.3.0: Please upgrade to 6.1.0. https://fontawesome.com/docs/changelog/[](http://10.4.1.51:30180/blue/organizations/jenkins/user-center-apir944p%2Fuser-center-gateway/detail/master/13/pipeline#step-37-log-51)

[INFO] npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random[](http://10.4.1.51:30180/blue/organizations/jenkins/user-center-apir944p%2Fuser-center-gateway/detail/master/13/pipeline#step-37-log-52) for details.

[INFO] npm WARN deprecated uuid@3.3.2: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random[](http://10.4.1.51:30180/blue/organizations/jenkins/user-center-apir944p%2Fuser-center-gateway/detail/master/13/pipeline#step-37-log-53) for details.

[INFO] npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142[](http://10.4.1.51:30180/blue/organizations/jenkins/user-center-apir944p%2Fuser-center-gateway/detail/master/13/pipeline#step-37-log-54)[](http://10.4.1.51:30180/blue/organizations/jenkins/user-center-apir944p%2Fuser-center-gateway/detail/master/13/pipeline#step-37-log-55)[](http://10.4.1.51:30180/blue/organizations/jenkins/user-center-apir944p%2Fuser-center-gateway/detail/master/13/pipeline#step-37-log-56)[](http://10.4.1.51:30180/blue/organizations/jenkins/user-center-apir944p%2Fuser-center-gateway/detail/master/13/pipeline#step-37-log-57)[](http://10.4.1.51:30180/blue/organizations/jenkins/user-center-apir944p%2Fuser-center-gateway/detail/master/13/pipeline#step-37-log-58)

[INFO] npm WARN deprecated popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1

[INFO] npm WARN deprecated core-js@2.6.12: core-js@<3.4 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.

[INFO] npm notice 

[INFO] npm notice New minor version of npm available! 8.4.1 -> 8.5.5

[INFO] npm notice Changelog: <https://github.com/npm/cli/releases/tag/v8.5.5[](http://10.4.1.51:30180/blue/organizations/jenkins/user-center-apir944p%2Fuser-center-gateway/detail/master/13/pipeline#step-37-log-59)[](http://10.4.1.51:30180/blue/organizations/jenkins/user-center-apir944p%2Fuser-center-gateway/detail/master/13/pipeline#step-37-log-60)[](http://10.4.1.51:30180/blue/organizations/jenkins/user-center-apir944p%2Fuser-center-gateway/detail/master/13/pipeline#step-37-log-61)[](http://10.4.1.51:30180/blue/organizations/jenkins/user-center-apir944p%2Fuser-center-gateway/detail/master/13/pipeline#step-37-log-62)[](http://10.4.1.51:30180/blue/organizations/jenkins/user-center-apir944p%2Fuser-center-gateway/detail/master/13/pipeline#step-37-log-63)[](http://10.4.1.51:30180/blue/organizations/jenkins/user-center-apir944p%2Fuser-center-gateway/detail/master/13/pipeline#step-37-log-64)[](http://10.4.1.51:30180/blue/organizations/jenkins/user-center-apir944p%2Fuser-center-gateway/detail/master/13/pipeline#step-37-log-65)[](http://10.4.1.51:30180/blue/organizations/jenkins/user-center-apir944p%2Fuser-center-gateway/detail/master/13/pipeline#step-37-log-66)[](http://10.4.1.51:30180/blue/organizations/jenkins/user-center-apir944p%2Fuser-center-gateway/detail/master/13/pipeline#step-37-log-67)[](http://10.4.1.51:30180/blue/organizations/jenkins/user-center-apir944p%2Fuser-center-gateway/detail/master/13/pipeline#step-37-log-68)[](http://10.4.1.51:30180/blue/organizations/jenkins/user-center-apir944p%2Fuser-center-gateway/detail/master/13/pipeline#step-37-log-69)[](http://10.4.1.51:30180/blue/organizations/jenkins/user-center-apir944p%2Fuser-center-gateway/detail/master/13/pipeline#step-37-log-70)[](http://10.4.1.51:30180/blue/organizations/jenkins/user-center-apir944p%2Fuser-center-gateway/detail/master/13/pipeline#step-37-log-71)[](http://10.4.1.51:30180/blue/organizations/jenkins/user-center-apir944p%2Fuser-center-gateway/detail/master/13/pipeline#step-37-log-72)[](http://10.4.1.51:30180/blue/organizations/jenkins/user-center-apir944p%2Fuser-center-gateway/detail/master/13/pipeline#step-37-log-73)[](http://10.4.1.51:30180/blue/organizations/jenkins/user-center-apir944p%2Fuser-center-gateway/detail/master/13/pipeline#step-37-log-74)>

[INFO] npm notice Run `npm install -g npm@8.5.5` to update!

[INFO] npm notice 

[INFO] npm ERR! code 1

[INFO] npm ERR! path /home/jenkins/agent/workspace/r944p_user-center-gateway_master/node_modules/deasync

[INFO] npm ERR! command failed

[INFO] npm ERR! command sh -c node-gyp rebuild

[INFO] npm ERR! make: Entering directory `/home/jenkins/agent/workspace/r944p_user-center-gateway_master/node_modules/deasync/build'

[INFO] npm ERR!   CXX(target) Release/obj.target/deasync/src/deasync.o

[INFO] npm ERR! make: Leaving directory `/home/jenkins/agent/workspace/r944p_user-center-gateway_master/node_modules/deasync/build'

[INFO] npm ERR! gyp info it worked if it ends with ok

[INFO] npm ERR! gyp info using node-gyp@8.4.1

[INFO] npm ERR! gyp info using node@16.14.0 | linux | x64

[INFO] npm ERR! gyp info find Python using Python version 3.7.0 found at "/usr/bin/python"

[INFO] npm ERR! gyp WARN EACCES current user does not have permission to access the dev dir "/root/.cache/node-gyp/16.14.0"

[INFO] npm ERR! gyp WARN EACCES attempting to reinstall using temporary dev dir "/tmp/.node-gyp"

[INFO] npm ERR! gyp http GET https://nodejs.org/download/release/v16.14.0/node-v16.14.0-headers.tar.gz[](http://10.4.1.51:30180/blue/organizations/jenkins/user-center-apir944p%2Fuser-center-gateway/detail/master/13/pipeline#step-37-log-75)

[INFO] npm ERR! gyp http 200 https://nodejs.org/download/release/v16.14.0/node-v16.14.0-headers.tar.gz[](http://10.4.1.51:30180/blue/organizations/jenkins/user-center-apir944p%2Fuser-center-gateway/detail/master/13/pipeline#step-37-log-76)

[INFO] npm ERR! gyp http GET https://nodejs.org/download/release/v16.14.0/SHASUMS256.txt[](http://10.4.1.51:30180/blue/organizations/jenkins/user-center-apir944p%2Fuser-center-gateway/detail/master/13/pipeline#step-37-log-77)

[INFO] npm ERR! gyp http 200 https://nodejs.org/download/release/v16.14.0/SHASUMS256.txt[](http://10.4.1.51:30180/blue/organizations/jenkins/user-center-apir944p%2Fuser-center-gateway/detail/master/13/pipeline#step-37-log-78)[](http://10.4.1.51:30180/blue/organizations/jenkins/user-center-apir944p%2Fuser-center-gateway/detail/master/13/pipeline#step-37-log-79)[](http://10.4.1.51:30180/blue/organizations/jenkins/user-center-apir944p%2Fuser-center-gateway/detail/master/13/pipeline#step-37-log-80)[](http://10.4.1.51:30180/blue/organizations/jenkins/user-center-apir944p%2Fuser-center-gateway/detail/master/13/pipeline#step-37-log-81)[](http://10.4.1.51:30180/blue/organizations/jenkins/user-center-apir944p%2Fuser-center-gateway/detail/master/13/pipeline#step-37-log-82)[](http://10.4.1.51:30180/blue/organizations/jenkins/user-center-apir944p%2Fuser-center-gateway/detail/master/13/pipeline#step-37-log-83)[](http://10.4.1.51:30180/blue/organizations/jenkins/user-center-apir944p%2Fuser-center-gateway/detail/master/13/pipeline#step-37-log-84)[](http://10.4.1.51:30180/blue/organizations/jenkins/user-center-apir944p%2Fuser-center-gateway/detail/master/13/pipeline#step-37-log-85)[](http://10.4.1.51:30180/blue/organizations/jenkins/user-center-apir944p%2Fuser-center-gateway/detail/master/13/pipeline#step-37-log-86)[](http://10.4.1.51:30180/blue/organizations/jenkins/user-center-apir944p%2Fuser-center-gateway/detail/master/13/pipeline#step-37-log-87)[](http://10.4.1.51:30180/blue/organizations/jenkins/user-center-apir944p%2Fuser-center-gateway/detail/master/13/pipeline#step-37-log-88)[](http://10.4.1.51:30180/blue/organizations/jenkins/user-center-apir944p%2Fuser-center-gateway/detail/master/13/pipeline#step-37-log-89)[](http://10.4.1.51:30180/blue/organizations/jenkins/user-center-apir944p%2Fuser-center-gateway/detail/master/13/pipeline#step-37-log-90)[](http://10.4.1.51:30180/blue/organizations/jenkins/user-center-apir944p%2Fuser-center-gateway/detail/master/13/pipeline#step-37-log-91)[](http://10.4.1.51:30180/blue/organizations/jenkins/user-center-apir944p%2Fuser-center-gateway/detail/master/13/pipeline#step-37-log-92)[](http://10.4.1.51:30180/blue/organizations/jenkins/user-center-apir944p%2Fuser-center-gateway/detail/master/13/pipeline#step-37-log-93)[](http://10.4.1.51:30180/blue/organizations/jenkins/user-center-apir944p%2Fuser-center-gateway/detail/master/13/pipeline#step-37-log-94)[](http://10.4.1.51:30180/blue/organizations/jenkins/user-center-apir944p%2Fuser-center-gateway/detail/master/13/pipeline#step-37-log-95)[](http://10.4.1.51:30180/blue/organizations/jenkins/user-center-apir944p%2Fuser-center-gateway/detail/master/13/pipeline#step-37-log-96)[](http://10.4.1.51:30180/blue/organizations/jenkins/user-center-apir944p%2Fuser-center-gateway/detail/master/13/pipeline#step-37-log-97)[](http://10.4.1.51:30180/blue/organizations/jenkins/user-center-apir944p%2Fuser-center-gateway/detail/master/13/pipeline#step-37-log-98)[](http://10.4.1.51:30180/blue/organizations/jenkins/user-center-apir944p%2Fuser-center-gateway/detail/master/13/pipeline#step-37-log-99)[](http://10.4.1.51:30180/blue/organizations/jenkins/user-center-apir944p%2Fuser-center-gateway/detail/master/13/pipeline#step-37-log-100)[](http://10.4.1.51:30180/blue/organizations/jenkins/user-center-apir944p%2Fuser-center-gateway/detail/master/13/pipeline#step-37-log-101)[](http://10.4.1.51:30180/blue/organizations/jenkins/user-center-apir944p%2Fuser-center-gateway/detail/master/13/pipeline#step-37-log-102)[](http://10.4.1.51:30180/blue/organizations/jenkins/user-center-apir944p%2Fuser-center-gateway/detail/master/13/pipeline#step-37-log-103)[](http://10.4.1.51:30180/blue/organizations/jenkins/user-center-apir944p%2Fuser-center-gateway/detail/master/13/pipeline#step-37-log-104)[](http://10.4.1.51:30180/blue/organizations/jenkins/user-center-apir944p%2Fuser-center-gateway/detail/master/13/pipeline#step-37-log-105)[](http://10.4.1.51:30180/blue/organizations/jenkins/user-center-apir944p%2Fuser-center-gateway/detail/master/13/pipeline#step-37-log-106)[](http://10.4.1.51:30180/blue/organizations/jenkins/user-center-apir944p%2Fuser-center-gateway/detail/master/13/pipeline#step-37-log-107)[](http://10.4.1.51:30180/blue/organizations/jenkins/user-center-apir944p%2Fuser-center-gateway/detail/master/13/pipeline#step-37-log-108)[](http://10.4.1.51:30180/blue/organizations/jenkins/user-center-apir944p%2Fuser-center-gateway/detail/master/13/pipeline#step-37-log-109)[](http://10.4.1.51:30180/blue/organizations/jenkins/user-center-apir944p%2Fuser-center-gateway/detail/master/13/pipeline#step-37-log-110)[](http://10.4.1.51:30180/blue/organizations/jenkins/user-center-apir944p%2Fuser-center-gateway/detail/master/13/pipeline#step-37-log-111)[](http://10.4.1.51:30180/blue/organizations/jenkins/user-center-apir944p%2Fuser-center-gateway/detail/master/13/pipeline#step-37-log-112)[](http://10.4.1.51:30180/blue/organizations/jenkins/user-center-apir944p%2Fuser-center-gateway/detail/master/13/pipeline#step-37-log-113)[](http://10.4.1.51:30180/blue/organizations/jenkins/user-center-apir944p%2Fuser-center-gateway/detail/master/13/pipeline#step-37-log-114)[](http://10.4.1.51:30180/blue/organizations/jenkins/user-center-apir944p%2Fuser-center-gateway/detail/master/13/pipeline#step-37-log-115)[](http://10.4.1.51:30180/blue/organizations/jenkins/user-center-apir944p%2Fuser-center-gateway/detail/master/13/pipeline#step-37-log-116)[](http://10.4.1.51:30180/blue/organizations/jenkins/user-center-apir944p%2Fuser-center-gateway/detail/master/13/pipeline#step-37-log-117)[](http://10.4.1.51:30180/blue/organizations/jenkins/user-center-apir944p%2Fuser-center-gateway/detail/master/13/pipeline#step-37-log-118)[](http://10.4.1.51:30180/blue/organizations/jenkins/user-center-apir944p%2Fuser-center-gateway/detail/master/13/pipeline#step-37-log-119)[](http://10.4.1.51:30180/blue/organizations/jenkins/user-center-apir944p%2Fuser-center-gateway/detail/master/13/pipeline#step-37-log-120)[](http://10.4.1.51:30180/blue/organizations/jenkins/user-center-apir944p%2Fuser-center-gateway/detail/master/13/pipeline#step-37-log-121)[](http://10.4.1.51:30180/blue/organizations/jenkins/user-center-apir944p%2Fuser-center-gateway/detail/master/13/pipeline#step-37-log-122)[](http://10.4.1.51:30180/blue/organizations/jenkins/user-center-apir944p%2Fuser-center-gateway/detail/master/13/pipeline#step-37-log-123)[](http://10.4.1.51:30180/blue/organizations/jenkins/user-center-apir944p%2Fuser-center-gateway/detail/master/13/pipeline#step-37-log-124)[](http://10.4.1.51:30180/blue/organizations/jenkins/user-center-apir944p%2Fuser-center-gateway/detail/master/13/pipeline#step-37-log-125)[](http://10.4.1.51:30180/blue/organizations/jenkins/user-center-apir944p%2Fuser-center-gateway/detail/master/13/pipeline#step-37-log-126)[](http://10.4.1.51:30180/blue/organizations/jenkins/user-center-apir944p%2Fuser-center-gateway/detail/master/13/pipeline#step-37-log-127)[](http://10.4.1.51:30180/blue/organizations/jenkins/user-center-apir944p%2Fuser-center-gateway/detail/master/13/pipeline#step-37-log-128)

[INFO] npm ERR! gyp info spawn /usr/bin/python

[INFO] npm ERR! gyp info spawn args [

[INFO] npm ERR! gyp info spawn args   '/home/jenkins/agent/workspace/r944p_user-center-gateway_master/node_modules/node-gyp/gyp/gyp_main.py',

[INFO] npm ERR! gyp info spawn args   'binding.gyp',

[INFO] npm ERR! gyp info spawn args   '-f',

[INFO] npm ERR! gyp info spawn args   'make',

[INFO] npm ERR! gyp info spawn args   '-I',

[INFO] npm ERR! gyp info spawn args   '/home/jenkins/agent/workspace/r944p_user-center-gateway_master/node_modules/deasync/build/config.gypi',

[INFO] npm ERR! gyp info spawn args   '-I',

[INFO] npm ERR! gyp info spawn args   '/home/jenkins/agent/workspace/r944p_user-center-gateway_master/node_modules/node-gyp/addon.gypi',

[INFO] npm ERR! gyp info spawn args   '-I',

[INFO] npm ERR! gyp info spawn args   '/tmp/.node-gyp/16.14.0/include/node/common.gypi',

[INFO] npm ERR! gyp info spawn args   '-Dlibrary=shared_library',

[INFO] npm ERR! gyp info spawn args   '-Dvisibility=default',

[INFO] npm ERR! gyp info spawn args   '-Dnode_root_dir=/tmp/.node-gyp/16.14.0',

[INFO] npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/home/jenkins/agent/workspace/r944p_user-center-gateway_master/node_modules/node-gyp',

[INFO] npm ERR! gyp info spawn args   '-Dnode_lib_file=/tmp/.node-gyp/16.14.0/<(target_arch)/node.lib',

[INFO] npm ERR! gyp info spawn args   '-Dmodule_root_dir=/home/jenkins/agent/workspace/r944p_user-center-gateway_master/node_modules/deasync',

[INFO] npm ERR! gyp info spawn args   '-Dnode_engine=v8',

[INFO] npm ERR! gyp info spawn args   '--depth=.',

[INFO] npm ERR! gyp info spawn args   '--no-parallel',

[INFO] npm ERR! gyp info spawn args   '--generator-output',

[INFO] npm ERR! gyp info spawn args   'build',

[INFO] npm ERR! gyp info spawn args   '-Goutput_dir=.'

[INFO] npm ERR! gyp info spawn args ]

[INFO] npm ERR! gyp info spawn make

[INFO] npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]

[INFO] npm ERR! g++: error: unrecognized command line option ‘-std=gnu++14’

[INFO] npm ERR! make: *** [Release/obj.target/deasync/src/deasync.o] Error 1

[INFO] npm ERR! gyp ERR! build error 

[INFO] npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2

[INFO] npm ERR! gyp ERR! stack     at ChildProcess.onExit (/home/jenkins/agent/workspace/r944p_user-center-gateway_master/node_modules/node-gyp/lib/build.js:194:23)

[INFO] npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:520:28)

[INFO] npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)

[INFO] npm ERR! gyp ERR! System Linux 5.4.165-1.el7.elrepo.x86_64

[INFO] npm ERR! gyp ERR! command "/home/jenkins/agent/workspace/r944p_user-center-gateway_master/target/node/node" "/home/jenkins/agent/workspace/r944p_user-center-gateway_master/node_modules/.bin/node-gyp" "rebuild"

[INFO] npm ERR! gyp ERR! cwd /home/jenkins/agent/workspace/r944p_user-center-gateway_master/node_modules/deasync

[INFO] npm ERR! gyp ERR! node -v v16.14.0

[INFO] npm ERR! gyp ERR! node-gyp -v v8.4.1

[INFO] npm ERR! gyp ERR! not ok

[INFO] 

[INFO] npm ERR! A complete log of this run can be found in:

[INFO] npm ERR!     /root/.npm/_logs/2022-03-31T08_25_12_374Z-debug-0.log

[INFO] ------------------------------------------------------------------------

[INFO] BUILD FAILURE

[INFO] ------------------------------------------------------------------------

[INFO] Total time:  06:28 min

[INFO] Finished at: 2022-03-31T16:31:31+08:00

[INFO] ------------------------------------------------------------------------

[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.12.1:npm (npm install) on project gw: Failed to run task: 'npm install' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1) -> [Help 1]

[ERROR]

##### **Browsers and Operating System**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by redDevis** [comment] 2022-03-31 09:01
it is an gateway app, when i create an docker image, it report this error ,i do not know the reason ,who can help me

**Comment by mshima** [comment] 2022-04-06 19:21
This related to the environment, looks related to permissions.
Not a bug, closing.

**Closed by mshima** 2022-04-06 19:21 UTC
Labels: area: triage, theme: undefined

**Comment by redDevis** [comment] 2022-10-11 07:38
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
