### ISSUE TITLE
Spring boot Repackage generates invalid war file

### ISSUE THREAD

**Issue by nachomezzadra** [jhipster/generator-jhipster#5439] opened 2017-03-20 03:45 UTC
##### **Overview of the issue**

This is a follow up issue from https://github.com/jhipster/generator-jhipster/issues/4326
I'm having the exact same issue as described there, except that in my case i do need the executable one.

The issue comes as AWS Elastic Beanstalk unzips the war file and the unzip command returns an exit code 1. 

You don't need to deploy the runnable war in AWS EB in order to reproduce this issue.  You could simply unzip the generated war file (*not* the .original one, but the executable one), and although all files get properly extracted, if we echo the last command exit reason we will get a 1.

It's worth mentioning that having created a Spring Boot sample app, this issue is not observed.

Attached both AWS Elastic Beanstalk eb-commandprocessor.log, as well as a custom log when unzipping a local test app.
[eb-commandprocessor.txt](https://github.com/jhipster/generator-jhipster/files/853903/eb-commandprocessor.txt)
[unzip-output.txt](https://github.com/jhipster/generator-jhipster/files/853904/unzip-output.txt)

##### **Motivation for or Use Case**

Can't deploy generated war file to AWS Beanstalk.

##### **Reproduce the error**

In order to reproduce the issue, simply create a new jhipster app (i'm currently using maven, although in linked issue its being used gradle), and after running ./mvnw clean package -Pprod, run the following command;
```
$ unzip target/app-0.0.1-SNAPSHOT.war 
$ echo $?
```

##### **Related issues**

https://github.com/jhipster/generator-jhipster/issues/4326

##### **JHipster Version(s)**

This happens with both Jhipster v3.12.1 as well as with v4.0.6.  I know Jhipster v4.0.8 updates Spring boot's to latest version, but even so i'm still getting the same behavior. 

##### **JHipster configuration**

```javascript

{
  "generator-jhipster": {
    "jhipsterVersion": "3.12.1",
    "baseName": "test",
    "packageName": "com.avaya.ept",
    "packageFolder": "com/avaya/ept",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "no",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "buildTool": "maven",
    "enableSocialSignIn": true,
    "rememberMeKey": "35a9882a9e9d9065c9fea0048ce9a31c9417f5fd",
    "useSass": false,
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}
```

##### **Browsers and Operating System**

MacOS El capitan

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment] 2017-03-20 07:42
I manage to reproduce what you described. Can you try to change, in your pom.xml:
```
<executable>true</executable>
```
to:
```
<executable>false</executable>
```

With this change, the unzip should exit with 0.
But I don't know if it's related to JHipster...

**Comment by jdubois** [comment] 2017-03-20 09:26
You should have the same issue with Spring Boot, as we are just basically using Spring Boot here. To create an executable WAR file, Spring Boot uses a trick when doing the compression - that's usually OK, but maybe there's a limitation with AWS Elastic Beanstalk.

- I know the WAR file isn't "correct", this is how Spring Boot works, and this is usually OK
- If you can't use this WAR file on you specific system, you should use a non-executable WAR file, and just do `java -jar` instead. That's not a big deal, just a little less intuitive. Have a look at the Spring Boot documentation for this.
- We have 2 supports for AWS Beanstalk: our own sub-generator at https://jhipster.github.io/aws/ and also Boxfuse at https://jhipster.github.io/boxfuse/ - you should use them, if you want to do this on your own, well, you're on your own :-)

I'm sorry, we are not sponsored by AWS so we can't test it - please note that Cloud Foundry, Heroku and Google Cloud all give us free credits, and people from those companies are very active JHipster contributors, so of course JHipster works better on those platforms.

**Comment by nachomezzadra** [comment] 2017-03-20 13:07
Hi Pascal, Julien.  Thanks for your inputs.

I understand that there's no sponsorship from AWS making it impossible to test this in AWS EB.  But we don't need AWS in order to test/reproduce it.  What's causing AWS EB to fail is that unzip command fails to unzip the executable war, as it returns an exit code 1.

This is not a Spring boot issue, as i mentioned before, if we create a "bare" spring boot app, the executable jar properly unzips.  You could try this by cloning this spring boot sample app https://github.com/spring-guides/gs-spring-boot 
Although this sample app uses Spring boot 1.5.2, updating JHipster spring boot's version to 1.5.2 doesn't make any difference.

So there must be something between Spring boot and JHipster that "corrupts" this executable war/jar file.

Having mentioned that, any chance we reopen this issue?

Thanks in advance.

**Comment by jdubois** [comment] 2017-03-20 13:17
Yes of course @nachomezzadra !
We need to find out what makes that difference, then. This is very surprising.

**Comment by pascalgrimaud** [comment] 2017-03-20 13:25
Here what I did:
- clone https://github.com/spring-guides/gs-spring-boot
- go into `initial` folder
- use `./mvnw clean package`
- go into target, `unzip gs-spring-boot-0.1.0.jar`
- echo $? -> 0
- go back to `initial` folder
- edit pom.xml with:
```xml
    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <executable>true</executable>
                </configuration>
            </plugin>
        </plugins>
    </build>
```
- use `./mvnw clean package`
- go into target, `unzip gs-spring-boot-0.1.0.jar`
- echo $? -> 1

So I reproduce your issue. So for me, it's not a JHipster issue, maybe it's a normal behavior? I don't know.

What I suggest:
- use `<executable>false</executable>`
- at the end of your build (local or some CI), manually chmod +x your war
- it should be what you expect

**Comment by gmarziou** [comment] 2017-03-20 13:41
Pascal and Julien are right, this is a normal issue with spring boot executable war. When this option is true spring boot maven plugin prepends a shell script to your war/jar, you can see it by running `head  target/*.war` and this is causing some archivers to declare this file as invalid.

So either don't use executable jars or ask AWS whether there is an option to skip this validation by unzip.

**Comment by jdubois** [comment] 2017-03-20 14:47
OK then @gmarziou did a good summary, and I'm closing this -> still I'd like to know why you don't have the issue without JHipster, but as we don't do anything here, I can only guess you have a misconfiguration somewhere

**Closed by jdubois** 2017-03-20 14:47 UTC

**Comment by nachomezzadra** [comment] 2017-03-20 21:00
My bad, thought that executable attribute was enabled by default.

You are correct, this seems to be an Spring boot thing.   
Given that i still need the executable one (as i need to deploy in both on premise and on AWS), as a workaround i can have a profile for AWS having the executable attribute disabled so i can continue having the embedded tomcat runtime in, and another one with the executable attribute enabled so that i can still run it on premise.  
I'd rather having a single artifact for both cases but for now i guess i can live with it.

Thank you all.

**Comment by martinpring** [comment] 2018-01-20 16:02
@gmarziou about Nexus. I ran in to this issue when uploading the executable war to Nexus.
A simple workaround to this is to uncheck the strict content type validation in the repositories in Nexus.

**Comment by gmarziou** [comment] 2018-01-20 18:22
Right, at work I even got the case where firewall blocked the upload ! 🙄

**Comment by setterlee** [comment] 2018-02-23 15:35
I tried with this changes in the pom.xml and works for me


```
           <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <version>${spring-boot.version}</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>build-info</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <mainClass>${start-class}</mainClass>
                    <!--<executable>true</executable>-->
                    <fork>true</fork>
                </configuration>
           </plugin> 
```
--

Reference: [https://forums.aws.amazon.com/thread.jspa?threadID=252710&tstart=0](https://forums.aws.amazon.com/thread.jspa?threadID=252710&tstart=0)

**Comment by gmarziou** [comment] 2018-02-23 20:45
Never too late, I had a close look to https://github.com/spring-guides/gs-spring-boot, I built the jar and looked at it in an editor: it does not include the executable script in header. So it confirms that the default is `executable=false` as documented in [spring-boot maven plugin doc](https://docs.spring.io/spring-boot/docs/1.5.10.RELEASE/maven-plugin/repackage-mojo.html#executable).

[Official doc](https://docs.spring.io/spring-boot/docs/current/reference/html/deployment-install.html#deployment-install) states:

> It is recommended that you only make your jar or war fully executable if you intend to execute it directly, rather than running it with java -jar or deploying it to a servlet container.

Our Dockerfile uses `java -jar`, same for [Heroku generator](https://github.com/jhipster/generator-jhipster/blob/master/generators/heroku/templates/Procfile.ejs)  and our Travis builds,  I'm not sure for CloudFoundry. [Our doc](http://www.jhipster.tech/production/#run) mentions the 2 ways but I guess the executable jar is only useful to users (like me) deploying their apps as systemd services.

I think we could change the default value and generate pom.xml with a comment:

~~~xml
               <configuration>
                    <mainClass>${start-class}</mainClass>
                    <!-- set to true if you plan to deploy your app as systemd service -->
                    <executable>false</executable>
                    <fork>true</fork>
                </configuration>
 ~~~

WDYT @jdubois ?

**Comment by jdubois** [comment] 2018-02-24 08:24
Oh interesting, because I think I got the same issue on start.jhipster.tech but I didn't understand why.

Let's move fully to JAR files, which are executables:

- Nobody does WAR files in app servers anymore. Let's move on!
- With JHipster 5 we will have reactive support -> this can't work in an app server anyway, so another good reason to do a JAR file

Then, we can document how it can be transformed into a WAR file if some big old company still want to use a WAR. It should be their problem, not ours.

**Comment by gmarziou** [comment] 2018-02-24 09:23
On stackoverflow, we have some rare questions about deploying into an app server but usually without a well documented answer.  So OK to use a JAR rather than a WAR.

I'm not sure that we should keep the executable flag set as true. I guess that the original issue with AWS or Nexus would still be present because it's due to the executable script added at the beginning of the archive file whether it's a jar or a war.
