### ISSUE TITLE
Incorrect values saved in Elasticsearch when using @EntityListeners on domain model

### ISSUE THREAD

**Issue by FireWolf2007** [jhipster/generator-jhipster#5956] opened 2017-06-20 05:19 UTC
##### **Overview of the issue**
We are using ```@EntityListeners```.
For example our OfficePhone entity:
```
@Entity
@EntityListeners(OfficePhoneExtender.class)
@Table(name = "office_phone")
@Cache(usage = CacheConcurrencyStrategy.NONSTRICT_READ_WRITE)
@Document(indexName = "officephone")
public class OfficePhone implements Serializable {
...
}
```
and OfficePhoneExtender:
```
public class OfficePhoneExtender {

    @PrePersist
    @PreUpdate
    static void calcProps(OfficePhone officePhone) {
         // changing some fields here
    }
}
```
We have broken tests with Elasticsearch.
We explore problem and found such behavior:
1. in ```OfficePhoneServiceImpl.save``` we have transaction

2. next line does not really save data in DB:
```OfficePhone result = officePhoneRepository.save(officePhone);```
it's store data in persistence context and PrePersist called immediately, but PreUpdate called at end of transaction.

3. ```officePhoneSearchRepository.save(result)``` - ```result``` did not updated yet and into Elasticsearch we save different data.

4. When ```OfficePhoneServiceImpl.save``` method ends - transaction closes and call method with ```@PreUpdate```. In DB we have right data.

So after that work with Elasticsearch may produce strange results.

##### **Reproduce the error**
Add EntityListeners annotation to domain model, fix ```updateOfficePhone``` that comparing updated data to right form and watch difference in Elasticsearch and DB results:
Run generated test OfficePhoneResourceIntTest and:
```
    @Test
    @Transactional
    public void updateOfficePhone() throws Exception {
       ...
        OfficePhone officePhoneEs = officePhoneSearchRepository.findOne(testOfficePhone.getId());
        // COMPARE ERROR BELOW
        assertThat(officePhoneEs).isEqualToComparingFieldByField(testOfficePhone);
    }
```
It's produce assert error on updated field (updated in entity listener) and if we add our example fix (below) - it will be success.

##### **Suggest a Fix**

For now we decided fix method save with using ```entityManager.flush()``` before saving data into Elasticsearch repository:
```
@Service
@Transactional
public class OfficePhoneServiceImpl implements OfficePhoneService{
...
    public OfficePhone save(OfficePhone officePhone) {
        OfficePhone result = officePhoneExtRepository.save(officePhone);
        entityManager.flush(); // flush initiate PreUpdate calls
        officePhoneSearchRepository.save(result);
        return result;
    }
...
}
```

We don't know best solution, and ask advice: what is best way to solve this problem and not call ```entityManager.flush()```  in every *Service.save method?

##### **JHipster Version(s)**

```
telestat@0.0.0 /home/volf/telestat
├── generator-jhipster@4.5.4 
└─┬ generator-jhipster-elasticsearch-reindexer@0.3.0
  └── generator-jhipster@4.5.2 

```

##### **Browsers and Operating System**

java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

git version 2.7.4

node: v6.11.0

npm: 5.0.3

bower: 1.8.0

gulp:
[16:40:05] CLI version 1.3.0
[16:40:05] Local version 3.9.1

yeoman: 2.0.0

yarn: 0.24.5

Docker version 1.12.6, build 78d1802

docker-compose version 1.11.2, build dfed245

**Comment by jdubois** [comment] 2017-06-20 05:47
Yes, have a look with the search engine and please link the existing tickets discussing this topic here.
There are no transactions with ES, and anyway it doesn't provide the same guarantees as a database, so it's common to have consistency issues.
Doing the flush will work, unless of course your transaction rolls back :-)
So you should also catch the roll back, or maybe re-sync your whole ES every night (which is what I do, when there isn't too much data of course).

**Comment by pascalgrimaud** [comment] 2017-06-20 06:18
For the re-sync, you can use this module https://github.com/geraldhumphries/generator-jhipster-elasticsearch-reindexer made by @geraldhumphries 
It works so well!

**Comment by FireWolf2007** [comment] 2017-06-20 06:38
Thanks for answers, we already use elasticsearch-reindexer.

**Comment by jdubois** [comment] 2017-06-20 06:59
OK then that's "normal" Elasticsearch questions and I'm closing this as it's not a bug.
You could ask this question on Stackoverflow and if you find good ideas, propose some changes to JHipster

**Closed by jdubois** 2017-06-20 06:59 UTC
