### ISSUE TITLE
Could not find a valid JHipster UAA server in path "uaa"

### ISSUE THREAD

**Issue by walternate** [jhipster/generator-jhipster#3566] opened 2016-05-08 08:21 UTC
Hello All,

Testing out the JHipster 3.2.0 release with the separate uaa microservice and getting the following error:

Could not find a valid JHipster UAA server in path "uaa"

1. Created a UAA folder in parent directory and ran UAA generator.

2. Created a Gateway folder under parent directory next to the UAA folder and ran JHipster choosing the Gateway with the separate UAA on step 5. Fails on step 6 with the "Could not find a valid JHipster UAA server in path "uaa" " message even though the UAA was generated. Any other path causes an "TypeError: Path must be a string. Received undefined" error.

Thanks for all you work.

**Comment by jdubois** [comment] 2016-05-08 08:33
Ping @xetys as this is related to JHipster UAA

**Comment by xetys** [comment] 2016-05-08 10:41
I will test out tonight ! Sorry for my delay, the features are out without some docs how to use...

i report as soon as i can!

**Comment by deepu105** [comment] 2016-05-08 15:18
Yes we need to add docs for this. Its good we marked it as beta :) ill also
check if i get some time today. The last time i checked it was working

**Comment by xetys** [comment] 2016-05-08 21:14
@walternate I tested two situations: first to name the app and the folder "uaa" to see, if it even works with default settings. It does. Then I renamed the uaa to "myuaa" as folder and application name. Rebuilt everything including docker-compose and it works...

**BUT** at the first time I typed "myuaa" instead of "../myuaa", which led me to the same error you report.


I pushed my [generated application](https://github.com/xetys/todo-microservice) to github, so you can checkout it is working.

**Comment by deepu105** [comment] 2016-05-09 02:15
Ill check if there is a problem with path gandling

**Comment by walternate** [comment] 2016-05-09 03:53
@xetys Thanks for taking a look into it. It isn't working for me though. This is the first case where the application and folder name are the same.

1. mkdir uaa
2. cd uaa
3. yo jhipster 

{
  "generator-jhipster": {
    "jhipsterVersion": "3.2.1",
    "baseName": "uaa",
    "packageName": "com.application.server",
    "packageFolder": "com/application/server",
    "serverPort": "9999",
    "authenticationType": "uaa",
    "hibernateCache": "no",
    "databaseType": "mongodb",
    "devDatabaseType": "mongodb",
    "prodDatabaseType": "mongodb",
    "searchEngine": "no",
    "buildTool": "gradle",
    "jwtSecretKey": "fbf2b10db6eb8e00737ee95a80175562c8523b07",
    "enableTranslation": false,
    "applicationType": "uaa",
    "testFrameworks": [
      "gatling"
    ],
    "jhiPrefix": "jhi",
    "skipClient": true
  }
}

4. cd ../

5. mkdir gateway - > cd gateway

6. yo jhipster

? (1/16) Which *type* of application would you like to create? Microservice gateway
? (2/16) What is the base name of your application? gateway
? (3/16) As you are running in a microservice architecture, on which port would like your server to run? It should be unique to avoid port conflicts. 8080
? (4/16) What is your default Java package name? com.application.server
? (5/16) Which *type* of authentication would you like to use? [BETA] Authentication with JHipster UAA server (the server must be generated separately)
? (6/16) What is the folder path of your UAA application?. (../uaa)
>> Could not find a valid JHipster UAA server in path "uaa"

And I know this is a beta feature so I am more than happy to be on the bleeding edge and help where I can as I get to know the JHipster architecture better.

Thanks again!

**Comment by deepu105** [comment] 2016-05-09 04:02
I tried exactly what you did and it works for me, see the log below. But im on windows, what os are you on??

The below code checks the path for a valid uaa, could you try with an absolute path?
```
_getUaaAppName : function (input) {
        var fromPath = '';
        if(path.isAbsolute(input)) {
            fromPath = input + '/' + '.yo-rc.json';
        } else {
            fromPath = this.destinationPath(input + '/' + '.yo-rc.json');
        }

        if (shelljs.test('-f', fromPath)) {
            var fileData = this.fs.readJSON(fromPath);
            if (fileData && fileData['generator-jhipster']) {
                return fileData['generator-jhipster'];
            } else return false;
        } else {
            return false;
        }
    },
```
```
PS D:\Projects\test\microserv\gateway> cd ..\uaa\                                                                                                                           
PS D:\Projects\test\microserv\uaa> yo jhipster                                                                                                                              
                                                                                                                                                                            
        ██  ██    ██  ████████  ███████    ██████  ████████  ████████  ███████                                                                                              
        ██  ██    ██     ██     ██    ██  ██          ██     ██        ██    ██                                                                                             
        ██  ████████     ██     ███████    █████      ██     ██████    ███████                                                                                              
  ██    ██  ██    ██     ██     ██             ██     ██     ██        ██   ██                                                                                              
   ██████   ██    ██  ████████  ██        ██████      ██     ████████  ██    ██                                                                                             
                                                                                                                                                                            
                            http://jhipster.github.io                                                                                                                       
                                                                                                                                                                            
Welcome to the JHipster Generator v3.2.1                                                                                                                                    
Application files will be generated in folder: D:\Projects\test\microserv\uaa                                                                                               
This is an existing project, using the configuration from your .yo-rc.json file                                                                                             
to re-generate the project...                                                                                                                                               
                                                                                                                                                                            
   create README.md                                                                                                                                                         
   create .gitignore                                                                                                                                                        
   create .gitattributes                                                                                                                                                    
   create .editorconfig                                                                                                                                                     
   create .travis.yml                                                                                                                                                       
   create src\main\docker\Dockerfile                                                                                                                                        
   create src\main\docker\app.yml                                                                                                                                           
   create src\main\docker\mongodb.yml                                                                                                                                       
   create src\main\docker\mongodb-cluster.yml                                                                                                                               
   create src\main\docker\mongodb\MongoDB.Dockerfile                                                                                                                        
   create src\main\docker\mongodb\scripts\init_replicaset.js                                                                                                                
   create src\main\docker\jhipster-registry.yml                                                                                                                             
   create src\main\docker\sonar.yml                                                                                                                                         
   create build.gradle                                                                                                                                                      
   create settings.gradle                                                                                                                                                   
   create gradle.properties                                                                                                                                                 
   create gradle\sonar.gradle                                                                                                                                               
   create gradle\docker.gradle                                                                                                                                              
   create gradle\profile_dev.gradle                                                                                                                                         
   create gradle\profile_prod.gradle                                                                                                                                        
   create gradle\mapstruct.gradle                                                                                                                                           
   create gradle\gatling.gradle                                                                                                                                             
   create gradlew                                                                                                                                                           
   create gradlew.bat                                                                                                                                                       
   create gradle\wrapper\gradle-wrapper.jar                                                                                                                                 
   create gradle\wrapper\gradle-wrapper.properties                                                                                                                          
   create src\main\resources\banner.txt                                                                                                                                     
   create src\main\resources\templates\error.html                                                                                                                           
   create src\main\resources\logback-spring.xml                                                                                                                             
   create src\main\resources\config\application.yml                                                                                                                         
   create src\main\resources\config\application-dev.yml                                                                                                                     
   create src\main\resources\config\application-prod.yml                                                                                                                    
   create src\main\java\com\application\server\config\dbmigrations\InitialSetupMigration.java                                                                               
   create src\main\resources\i18n\messages.properties                                                                                                                       
   create src\main\java\com\application\server\security\SpringSecurityAuditorAware.java                                                                                     
   create src\main\java\com\application\server\security\SecurityUtils.java                                                                                                  
   create src\main\java\com\application\server\security\AuthoritiesConstants.java                                                                                           
   create src\main\java\com\application\server\config\UaaWebSecurityConfiguration.java                                                                                      
   create src\main\java\com\application\server\config\UaaConfiguration.java                                                                                                 
   create src\main\java\com\application\server\security\Http401UnauthorizedEntryPoint.java                                                                                  
   create src\main\java\com\application\server\security\UserDetailsService.java                                                                                             
   create src\main\java\com\application\server\security\UserNotActivatedException.java                                                                                      
   create src\main\java\com\application\server\security\package-info.java                                                                                                   
   create src\main\resources\config\bootstrap-dev.yml                                                                                                                       
   create src\main\resources\config\bootstrap-prod.yml                                                                                                                      
   create src\main\java\com\application\server\config\metrics\SpectatorLogMetricWriter.java                                                                                 
   create src\main\java\com\application\server\UaaApp.java                                                                                                                  
   create src\main\java\com\application\server\ApplicationWebXml.java                                                                                                       
   create src\main\java\com\application\server\aop\logging\LoggingAspect.java                                                                                               
   create src\main\java\com\application\server\config\apidoc\package-info.java                                                                                              
   create src\main\java\com\application\server\config\apidoc\SwaggerConfiguration.java                                                                                      
   create src\main\java\com\application\server\async\package-info.java                                                                                                      
   create src\main\java\com\application\server\async\ExceptionHandlingAsyncTaskExecutor.java                                                                                
   create src\main\java\com\application\server\config\package-info.java                                                                                                     
   create src\main\java\com\application\server\config\AsyncConfiguration.java                                                                                               
   create src\main\java\com\application\server\config\CacheConfiguration.java                                                                                               
   create src\main\java\com\application\server\config\Constants.java                                                                                                        
   create src\main\java\com\application\server\config\LoggingConfiguration.java                                                                                             
   create src\main\java\com\application\server\config\CloudMongoDbConfiguration.java                                                                                        
   create src\main\java\com\application\server\domain\util\JSR310DateConverters.java                                                                                        
   create src\main\java\com\application\server\config\CloudDatabaseConfiguration.java                                                                                       
   create src\main\java\com\application\server\config\DatabaseConfiguration.java                                                                                            
   create src\main\java\com\application\server\config\audit\package-info.java                                                                                               
   create src\main\java\com\application\server\config\audit\AuditEventConverter.java                                                                                        
   create src\main\java\com\application\server\config\JacksonConfiguration.java                                                                                             
   create src\main\java\com\application\server\config\JHipsterProperties.java                                                                                               
   create src\main\java\com\application\server\config\LocaleConfiguration.java                                                                                              
   create src\main\java\com\application\server\config\LoggingAspectConfiguration.java                                                                                       
   create src\main\java\com\application\server\config\MetricsConfiguration.java                                                                                             
   create src\main\java\com\application\server\config\ThymeleafConfiguration.java                                                                                           
   create src\main\java\com\application\server\config\WebConfigurer.java                                                                                                    
   create src\main\java\com\application\server\config\locale\package-info.java                                                                                              
   create src\main\java\com\application\server\config\locale\AngularCookieLocaleResolver.java                                                                               
   create src\main\java\com\application\server\domain\package-info.java                                                                                                     
   create src\main\java\com\application\server\domain\util\JSR310DateTimeSerializer.java                                                                                    
   create src\main\java\com\application\server\domain\util\JSR310LocalDateDeserializer.java                                                                                 
   create src\main\java\com\application\server\domain\AbstractAuditingEntity.java                                                                                           
   create src\main\java\com\application\server\domain\PersistentAuditEvent.java                                                                                             
   create src\main\java\com\application\server\repository\package-info.java                                                                                                 
   create src\main\java\com\application\server\service\package-info.java                                                                                                    
   create src\main\java\com\application\server\service\util\RandomUtil.java                                                                                                 
   create src\main\java\com\application\server\web\rest\errors\ErrorConstants.java                                                                                          
   create src\main\java\com\application\server\web\rest\errors\CustomParameterizedException.java                                                                            
   create src\main\java\com\application\server\web\rest\errors\ErrorDTO.java                                                                                                
   create src\main\java\com\application\server\web\rest\errors\ExceptionTranslator.java                                                                                     
   create src\main\java\com\application\server\web\rest\errors\FieldErrorDTO.java                                                                                           
   create src\main\java\com\application\server\web\rest\errors\ParameterizedErrorDTO.java                                                                                   
   create src\main\java\com\application\server\web\filter\package-info.java                                                                                                 
   create src\main\java\com\application\server\web\filter\CachingHttpHeadersFilter.java                                                                                     
   create src\main\java\com\application\server\web\rest\dto\package-info.java                                                                                               
   create src\main\java\com\application\server\web\rest\dto\LoggerDTO.java                                                                                                  
   create src\main\java\com\application\server\web\rest\util\HeaderUtil.java                                                                                                
   create src\main\java\com\application\server\web\rest\util\PaginationUtil.java                                                                                            
   create src\main\java\com\application\server\web\rest\package-info.java                                                                                                   
   create src\main\java\com\application\server\web\rest\LogsResource.java                                                                                                   
   create src\test\java\com\application\server\web\rest\TestUtil.java                                                                                                       
   create src\test\resources\config\application.yml                                                                                                                         
   create src\test\resources\logback-test.xml                                                                                                                               
   create src\test\gatling\conf\gatling.conf                                                                                                                                
   create src\main\resources\mails\activationEmail.html                                                                                                                     
   create src\main\resources\mails\creationEmail.html                                                                                                                       
   create src\main\resources\mails\passwordResetEmail.html                                                                                                                  
   create src\main\java\com\application\server\domain\User.java                                                                                                             
   create src\main\java\com\application\server\domain\Authority.java                                                                                                        
   create src\main\java\com\application\server\repository\CustomAuditEventRepository.java                                                                                   
   create src\main\java\com\application\server\repository\AuthorityRepository.java                                                                                          
   create src\main\java\com\application\server\repository\PersistenceAuditEventRepository.java                                                                              
   create src\main\java\com\application\server\repository\UserRepository.java                                                                                               
   create src\main\java\com\application\server\service\UserService.java                                                                                                     
   create src\main\java\com\application\server\service\MailService.java                                                                                                     
   create src\main\java\com\application\server\service\AuditEventService.java                                                                                               
   create src\main\java\com\application\server\web\rest\dto\UserDTO.java                                                                                                    
   create src\main\java\com\application\server\web\rest\dto\ManagedUserDTO.java                                                                                             
   create src\main\java\com\application\server\web\rest\UserResource.java                                                                                                   
   create src\main\java\com\application\server\web\rest\AccountResource.java                                                                                                
   create src\main\java\com\application\server\web\rest\dto\KeyAndPasswordDTO.java                                                                                          
   create src\main\java\com\application\server\web\rest\mapper\UserMapper.java                                                                                              
   create src\main\java\com\application\server\web\rest\AuditResource.java                                                                                                  
   create src\test\java\com\application\server\service\UserServiceIntTest.java                                                                                              
   create src\test\java\com\application\server\web\rest\UserResourceIntTest.java                                                                                            
   create src\test\java\com\application\server\web\rest\AccountResourceIntTest.java                                                                                         
   create src\test\java\com\application\server\security\SecurityUtilsUnitTest.java                                                                                          
   create src\test\java\com\application\server\web\rest\AuditResourceIntTest.java                                                                                           
   create src\main\java\com\application\server\web\rest\ProfileInfoResource.java                                                                                            
                                                                                                                                                                            
Server app generated successfully.                                                                                                                                          
                                                                                                                                                                            
PS D:\Projects\test\microserv\uaa> cd ..\gateway\                                                                                                                           
PS D:\Projects\test\microserv\gateway> yo jhipster                                                                                                                          
                                                                                                                                                                            
        ██  ██    ██  ████████  ███████    ██████  ████████  ████████  ███████                                                                                              
        ██  ██    ██     ██     ██    ██  ██          ██     ██        ██    ██                                                                                             
        ██  ████████     ██     ███████    █████      ██     ██████    ███████                                                                                              
  ██    ██  ██    ██     ██     ██             ██     ██     ██        ██   ██                                                                                              
   ██████   ██    ██  ████████  ██        ██████      ██     ████████  ██    ██                                                                                             
                                                                                                                                                                            
                            http://jhipster.github.io                                                                                                                       
                                                                                                                                                                            
Welcome to the JHipster Generator v3.2.1                                                                                                                                    
Application files will be generated in folder: D:\Projects\test\microserv\gateway                                                                                           
? (1/16) Which *type* of application would you like to create? Microservice gateway                                                                                         
? (2/16) What is the base name of your application? gateway                                                                                                                 
? (3/16) As you are running in a microservice architecture, on which port would like your server to run? It should be unique to avoid port conflicts. 8080                  
? (4/16) What is your default Java package name? com.application.server                                                                                                     
? (5/16) Which *type* of authentication would you like to use? [BETA] Authentication with JHipster UAA server (the server must be generated separately)                     
? (6/16) What is the folder path of your UAA application?. uaa                                                                                                              
? (7/16) Which *type* of database would you like to use? SQL (H2, MySQL, PostgreSQL, Oracle)                                                                                
? (8/16) Which *production* database would you like to use? MySQL                                                                                                           
? (9/16) Which *development* database would you like to use? H2 with disk-based persistence                                                                                 
? (10/16) Do you want to use Hibernate 2nd level cache? Yes, with HazelCast (distributed cache, for multiple nodes)                                                         
? (11/16) Do you want to use a search engine in your application? No                                                                                                        
? (12/16) Do you want to use clustered HTTP sessions? No                                                                                                                    
? (13/16) Do you want to use WebSockets? No                                                                                                                                 
? (14/16) Would you like to use Maven or Gradle for building the backend? Maven                                                                                             
? (15/16) Would you like to use the LibSass stylesheet preprocessor for your CSS? No                                                                                        
? (16/16) Would you like to enable internationalization support? Yes                                                                                                        
? Please choose the native language of the application? English                                                                                                             
? Please choose additional languages to install                                                                                                                             
? (17/16) Which testing frameworks would you like to use?                                                                                                                   
                                                                                                                                                                            
Installing languages: en                                                                                                                                                    
   create bower.json                                                                                                                                                        
   create package.json                                                                                                                                                      
   create README.md                                                                                                                                                         
   create .gitignore                                                                                                                                                        
```

**Comment by deepu105** [comment] 2016-05-09 04:05
FYI it works with all folder name and appname combinations for me

**Comment by walternate** [comment] 2016-05-09 04:23
@deepu105 

I am on Mac El Capitan 10.11.4. I tried with absolute path and still got the "Could not find a valid JHipster UAA server in path "uaa"" error. 

If the folder name does not match the app name, I will get the "Could not find a valid JHipster UAA server in path "uaa"" error. But if the path to the folder is wrong even by a space at the end of the string I get this. I am not sure what happens on Windows but I imagine the default behavior would be more gracefu, e.g. the no uaa server at this path error:

/Users/walternate/.nvm/versions/node/v5.6.0/lib/node_modules/yo/node_modules/rx/dist/rx.js:77
    throw e;
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:8:11)
    at Object.posix.isAbsolute (path.js:470:3)
    at module.exports.JhipsterServerGenerator.extend._getUaaAppName (/Users/walternate/.nvm/versions/node/v5.6.0/lib/node_modules/generator-jhipster/generators/server/index.js:220:17)
    at null.<anonymous> (/Users/walternate/.nvm/versions/node/v5.6.0/lib/node_modules/generator-jhipster/generators/server/index.js:350:47)
    at /Users/walternate/.nvm/versions/node/v5.6.0/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/run-async/index.js:26:25
    at /Users/walternate/.nvm/versions/node/v5.6.0/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/run-async/index.js:25:19
    at /Users/walternate/.nvm/versions/node/v5.6.0/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/inquirer/lib/prompts/base.js:89:14
    at process._tickCallback (node.js:402:9)

I will have to step through the _getUaaAppName function and see where exactly it's failing. Thanks for that so I don't have to dig for it. I'll update as soon as it makes any sense.

**Comment by deepu105** [comment] 2016-05-09 07:10
Im adding an npm test case for uaa server as well. Have also fixed issues when path has trailing space. But still im unable to figure whats causing issue for you

**Comment by xetys** [comment] 2016-05-09 07:40
I tested on ubuntu 14.04 desktop....I don't have a mac with El Capitan to test this issue :tired_face:

**Comment by deepu105** [comment] 2016-05-09 13:02
@jhipster/developers can someone check this in mac?

**Comment by sdoxsee** [comment] 2016-05-09 13:11
I'm on El Capitan 10.11.4. I hadn't had a problem with this before but just ran it again and got the same error. Created 'uaa', then started 'gateway' but failed to find uaa

https://www.dropbox.com/s/wddpnqunb4xmkbp/Screenshot%202016-05-09%2009.09.14.png?dl=0

**Comment by deepu105** [comment] 2016-05-09 14:36
Im using the same method i posted above for validate and filter so it should give same output. @sdoxsee as Im unable to reproduce this could you check it?

**Comment by deepu105** [comment] 2016-05-09 14:51
I didnt see your edit, it seems like a yeoman bug, Im able to reproduce with yo 1.8.1

**Comment by deepu105** [comment] 2016-05-09 15:21
fixed via https://github.com/jhipster/generator-jhipster/commit/0cd2e6fb33ca55d517fd01a2077a3367e3829e26

**Comment by deepu105** [comment] 2016-05-09 15:22
@walternate @sdoxsee could you check

**Closed by deepu105** 2016-05-09 15:21 UTC

**Comment by sdoxsee** [comment] 2016-05-09 15:41
Works for me. Thanks @deepu105

**Comment by walternate** [comment] 2016-05-09 16:29
Success! Thanks @deepu105.

**Comment by deepu105** [comment] 2016-05-10 01:40
Inquirer changed the way filters works https://github.com/SBoudrias/Inquirer.js/issues/122

**Comment by deepu105** [comment] 2016-05-10 01:42
but i dont understand how its affecting us when our yo version changes, we didn't update yeoman-generator which we depend on @sboudrias any idea?

**Comment by SBoudrias** [comment] 2016-05-10 01:47
@deepu105 inquirer is provided by yeoman-environment so that all generators can be integrated in GUI tools.

I didn't read the issue, but it's possible some filtering/validation edge case are seen with the latest yeoman-environment that we haven't foreseen.

**Comment by deepu105** [comment] 2016-05-10 01:57
@SBoudrias ok so if I understand you correctly regardless of what `yeoman-generator` version I add as dependency the inquirer version will be determined by the global `yo` version I have? That makes sense  as the GUI behavior is not tied to the generator I assume. The issue was that we were doing some validation and filter on an input and in validation block input was not filtered in yo versions less than 1.8. but people who upgraded global yo started getting issues as the input in validation was now filtered and it was failing validation as it changed to a string from a path url (my filter was getting string from a url, my validation was checking if the url path existed)

**Comment by SBoudrias** [comment] 2016-05-10 02:05
@deepu105 yeah, this is unfortunate, but from what I've seen it's been transparent for most users. You're probably hitting in an edge cases.

If you can tell me exactly the signature you were using that is not working anymore, I can try to see if we can work it back into inquirer so it stays backward compatible.

**Comment by deepu105** [comment] 2016-05-10 02:27
@SBoudrias this is the patch I did https://github.com/jhipster/generator-jhipster/commit/0cd2e6fb33ca55d517fd01a2077a3367e3829e26 so you can see my previous signature and current. I guess the issue was that I was asking for a URL from user and then validate it to see if its a valid URL and once validated I was using the filter to read a JSON file from the url and get a value form it. So I got hit when the sequence changed. I worked around by moving what I did in filter to the promts callback

**Comment by deepu105** [comment] 2016-05-10 02:28
Anyways its not a big deal, I just wanted to let you guys know that there are such cases.

**Comment by SBoudrias** [comment] 2016-05-10 02:51
@deepu105 no worry! Thanks for the heads up. We'll monitor in case more people run into it.

**Comment by cmcruzata** [comment] 2018-04-10 17:28
Hi, I know I'm late but, I'm trying to generate an app with Microservice application and continue the same issue. Here's a snapshot of issue.

Welcome to the JHipster Generator v4.14.2
Application files will be generated in folder: N:\SRA

? Which *type* of application would you like to create? Microservice application
? What is the base name of your application? SRA
? As you are running in a microservice architecture, on which port would like your server to run? It should be unique to avo
id port conflicts. 8081
? What is your default Java package name? com.sra.server
? Which service discovery server do you want to use? No service discovery
? Which *type* of authentication would you like to use? Authentication with JHipster UAA server (the server must be generate
d separately)
? What is the folder path of your UAA application? (../uaa)
>> Could not find a valid JHipster UAA server in path "../uaa"

Folder structure:
SRA(root)
-----ClientWeb
-----uaa

**Comment by ruddell** [comment] 2018-04-10 17:40
@cmcruzata Please don't comment on an old issue.  If you think this issue still applies, please [create a new ticket](https://github.com/jhipster/generator-jhipster/issues/new) with proper details.
