### ISSUE TITLE
setDocumentRoot should not be called when running .war with java -jar

### ISSUE THREAD

**Issue by wmarques** [jhipster/generator-jhipster#3122] opened 2016-03-09 14:34 UTC
##### **Overview of the issue**
When i do `docker-compose -f app.dev.yml up` it throws me an EmbeddedServletContainerException.
StackTrace:
```
java.util.concurrent.ExecutionException: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Tomcat].StandardHost[localhost].StandardContext[]]
gateway-dev-app_1 | 	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
gateway-dev-app_1 | 	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
gateway-dev-app_1 | 	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:916)
gateway-dev-app_1 | 	at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:871)
gateway-dev-app_1 | 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147)
gateway-dev-app_1 | 	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1408)
gateway-dev-app_1 | 	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1398)
gateway-dev-app_1 | 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
gateway-dev-app_1 | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
gateway-dev-app_1 | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
gateway-dev-app_1 | 	at java.lang.Thread.run(Thread.java:745)
gateway-dev-app_1 | Caused by: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Tomcat].StandardHost[localhost].StandardContext[]]
gateway-dev-app_1 | 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:153)
gateway-dev-app_1 | 	... 6 common frames omitted
gateway-dev-app_1 | Caused by: org.apache.catalina.LifecycleException: Failed to start component [org.apache.catalina.webresources.StandardRoot@67862846]
gateway-dev-app_1 | 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:153)
gateway-dev-app_1 | 	at org.apache.catalina.core.StandardContext.resourcesStart(StandardContext.java:4928)
gateway-dev-app_1 | 	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5058)
gateway-dev-app_1 | 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147)
gateway-dev-app_1 | 	... 6 common frames omitted
gateway-dev-app_1 | Caused by: java.lang.IllegalArgumentException: The main resource set specified [/src/main/webapp] is not valid
gateway-dev-app_1 | 	at org.apache.catalina.webresources.StandardRoot.createMainResourceSet(StandardRoot.java:723)
gateway-dev-app_1 | 	at org.apache.catalina.webresources.StandardRoot.startInternal(StandardRoot.java:684)
gateway-dev-app_1 | 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147)
gateway-dev-app_1 | 	... 9 common frames omitted
gateway-dev-app_1 | 
gateway-dev-app_1 | 2016-03-09 14:26:43.972 ERROR 1 --- [           main] org.apache.catalina.core.ContainerBase   : A child container failed during start
gateway-dev-app_1 | 
gateway-dev-app_1 | java.util.concurrent.ExecutionException: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Tomcat].StandardHost[localhost]]
gateway-dev-app_1 | 	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
gateway-dev-app_1 | 	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
gateway-dev-app_1 | 	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:916)
gateway-dev-app_1 | 	at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:262)
gateway-dev-app_1 | 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147)
gateway-dev-app_1 | 	at org.apache.catalina.core.StandardService.startInternal(StandardService.java:441)
gateway-dev-app_1 | 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147)
gateway-dev-app_1 | 	at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:769)
gateway-dev-app_1 | 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147)
gateway-dev-app_1 | 	at org.apache.catalina.startup.Tomcat.start(Tomcat.java:345)
gateway-dev-app_1 | 	at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer.initialize(TomcatEmbeddedServletContainer.java:89)
gateway-dev-app_1 | 	at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer.<init>(TomcatEmbeddedServletContainer.java:76)
gateway-dev-app_1 | 	at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainerFactory.getTomcatEmbeddedServletContainer(TomcatEmbeddedServletContainerFactory.java:457)
gateway-dev-app_1 | 	at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainerFactory.getEmbeddedServletContainer(TomcatEmbeddedServletContainerFactory.java:168)
gateway-dev-app_1 | 	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.createEmbeddedServletContainer(EmbeddedWebApplicationContext.java:160)
gateway-dev-app_1 | 	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.onRefresh(EmbeddedWebApplicationContext.java:130)
gateway-dev-app_1 | 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:532)
gateway-dev-app_1 | 	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118)
gateway-dev-app_1 | 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:766)
gateway-dev-app_1 | 	at org.springframework.boot.SpringApplication.createAndRefreshContext(SpringApplication.java:361)
gateway-dev-app_1 | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
gateway-dev-app_1 | 	at com.mycompany.myapp.GatewayApp.main(GatewayApp.java:74)
gateway-dev-app_1 | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
gateway-dev-app_1 | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
gateway-dev-app_1 | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
gateway-dev-app_1 | 	at java.lang.reflect.Method.invoke(Method.java:498)
gateway-dev-app_1 | 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:54)
gateway-dev-app_1 | 	at java.lang.Thread.run(Thread.java:745)
gateway-dev-app_1 | Caused by: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Tomcat].StandardHost[localhost]]
gateway-dev-app_1 | 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:153)
gateway-dev-app_1 | 	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1408)
gateway-dev-app_1 | 	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1398)
gateway-dev-app_1 | 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
gateway-dev-app_1 | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
gateway-dev-app_1 | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
gateway-dev-app_1 | 	... 1 common frames omitted
gateway-dev-app_1 | Caused by: org.apache.catalina.LifecycleException: A child container failed during start
gateway-dev-app_1 | 	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:924)
gateway-dev-app_1 | 	at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:871)
gateway-dev-app_1 | 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147)
gateway-dev-app_1 | 	... 6 common frames omitted
gateway-dev-app_1 | 
gateway-dev-app_1 | 2016-03-09 14:26:43.973  WARN 1 --- [           main] ationConfigEmbeddedWebApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.context.ApplicationContextException: Unable to start embedded container; nested exception is org.springframework.boot.context.embedded.EmbeddedServletContainerException: Unable to start embedded Tomcat
gateway-dev-app_1 | 2016-03-09 14:26:43.985 ERROR 1 --- [           main] o.s.boot.SpringApplication               : Application startup failed
gateway-dev-app_1 | 
gateway-dev-app_1 | org.springframework.context.ApplicationContextException: Unable to start embedded container; nested exception is org.springframework.boot.context.embedded.EmbeddedServletContainerException: Unable to start embedded Tomcat
gateway-dev-app_1 | 	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.onRefresh(EmbeddedWebApplicationContext.java:133)
gateway-dev-app_1 | 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:532)
gateway-dev-app_1 | 	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118)
gateway-dev-app_1 | 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:766)
gateway-dev-app_1 | 	at org.springframework.boot.SpringApplication.createAndRefreshContext(SpringApplication.java:361)
gateway-dev-app_1 | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
gateway-dev-app_1 | 	at com.mycompany.myapp.GatewayApp.main(GatewayApp.java:74)
gateway-dev-app_1 | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
gateway-dev-app_1 | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
gateway-dev-app_1 | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
gateway-dev-app_1 | 	at java.lang.reflect.Method.invoke(Method.java:498)
gateway-dev-app_1 | 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:54)
gateway-dev-app_1 | 	at java.lang.Thread.run(Thread.java:745)
gateway-dev-app_1 | Caused by: org.springframework.boot.context.embedded.EmbeddedServletContainerException: Unable to start embedded Tomcat
gateway-dev-app_1 | 	at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer.initialize(TomcatEmbeddedServletContainer.java:99)
gateway-dev-app_1 | 	at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer.<init>(TomcatEmbeddedServletContainer.java:76)
gateway-dev-app_1 | 	at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainerFactory.getTomcatEmbeddedServletContainer(TomcatEmbeddedServletContainerFactory.java:457)
gateway-dev-app_1 | 	at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainerFactory.getEmbeddedServletContainer(TomcatEmbeddedServletContainerFactory.java:168)
gateway-dev-app_1 | 	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.createEmbeddedServletContainer(EmbeddedWebApplicationContext.java:160)
gateway-dev-app_1 | 	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.onRefresh(EmbeddedWebApplicationContext.java:130)
gateway-dev-app_1 | 	... 12 common frames omitted
gateway-dev-app_1 | Caused by: org.apache.catalina.LifecycleException: Failed to start component [StandardServer[-1]]
gateway-dev-app_1 | 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:153)
gateway-dev-app_1 | 	at org.apache.catalina.startup.Tomcat.start(Tomcat.java:345)
gateway-dev-app_1 | 	at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer.initialize(TomcatEmbeddedServletContainer.java:89)
gateway-dev-app_1 | 	... 17 common frames omitted
gateway-dev-app_1 | Caused by: org.apache.catalina.LifecycleException: Failed to start component [StandardService[Tomcat]]
gateway-dev-app_1 | 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:153)
gateway-dev-app_1 | 	at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:769)
gateway-dev-app_1 | 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147)
gateway-dev-app_1 | 	... 19 common frames omitted
gateway-dev-app_1 | Caused by: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Tomcat]]
gateway-dev-app_1 | 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:153)
gateway-dev-app_1 | 	at org.apache.catalina.core.StandardService.startInternal(StandardService.java:441)
gateway-dev-app_1 | 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147)
gateway-dev-app_1 | 	... 21 common frames omitted
gateway-dev-app_1 | Caused by: org.apache.catalina.LifecycleException: A child container failed during start
gateway-dev-app_1 | 	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:924)
gateway-dev-app_1 | 	at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:262)
gateway-dev-app_1 | 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147)
gateway-dev-app_1 | 	... 23 common frames omitted
gateway-dev-app_1 | 
gateway-dev-app_1 | Exception in thread "main" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
gateway-dev-app_1 | 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:62)
gateway-dev-app_1 | 	at java.lang.Thread.run(Thread.java:745)
gateway-dev-app_1 | Caused by: java.lang.reflect.InvocationTargetException
gateway-dev-app_1 | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
gateway-dev-app_1 | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
gateway-dev-app_1 | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
gateway-dev-app_1 | 	at java.lang.reflect.Method.invoke(Method.java:498)
gateway-dev-app_1 | 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:54)
gateway-dev-app_1 | 	... 1 more
gateway-dev-app_1 | Caused by: org.springframework.context.ApplicationContextException: Unable to start embedded container; nested exception is org.springframework.boot.context.embedded.EmbeddedServletContainerException: Unable to start embedded Tomcat
gateway-dev-app_1 | 	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.onRefresh(EmbeddedWebApplicationContext.java:133)
gateway-dev-app_1 | 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:532)
gateway-dev-app_1 | 	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118)
gateway-dev-app_1 | 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:766)
gateway-dev-app_1 | 	at org.springframework.boot.SpringApplication.createAndRefreshContext(SpringApplication.java:361)
gateway-dev-app_1 | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
gateway-dev-app_1 | 	at com.mycompany.myapp.GatewayApp.main(GatewayApp.java:74)
gateway-dev-app_1 | 	... 6 more
gateway-dev-app_1 | Caused by: org.springframework.boot.context.embedded.EmbeddedServletContainerException: Unable to start embedded Tomcat
gateway-dev-app_1 | 	at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer.initialize(TomcatEmbeddedServletContainer.java:99)
gateway-dev-app_1 | 	at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer.<init>(TomcatEmbeddedServletContainer.java:76)
gateway-dev-app_1 | 	at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainerFactory.getTomcatEmbeddedServletContainer(TomcatEmbeddedServletContainerFactory.java:457)
gateway-dev-app_1 | 	at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainerFactory.getEmbeddedServletContainer(TomcatEmbeddedServletContainerFactory.java:168)
gateway-dev-app_1 | 	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.createEmbeddedServletContainer(EmbeddedWebApplicationContext.java:160)
gateway-dev-app_1 | 	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.onRefresh(EmbeddedWebApplicationContext.java:130)
gateway-dev-app_1 | 	... 12 more
gateway-dev-app_1 | Caused by: org.apache.catalina.LifecycleException: Failed to start component [StandardServer[-1]]
gateway-dev-app_1 | 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:153)
gateway-dev-app_1 | 	at org.apache.catalina.startup.Tomcat.start(Tomcat.java:345)
gateway-dev-app_1 | 	at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer.initialize(TomcatEmbeddedServletContainer.java:89)
gateway-dev-app_1 | 	... 17 more
gateway-dev-app_1 | Caused by: org.apache.catalina.LifecycleException: Failed to start component [StandardService[Tomcat]]
gateway-dev-app_1 | 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:153)
gateway-dev-app_1 | 	at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:769)
gateway-dev-app_1 | 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147)
gateway-dev-app_1 | 	... 19 more
gateway-dev-app_1 | Caused by: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Tomcat]]
gateway-dev-app_1 | 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:153)
gateway-dev-app_1 | 	at org.apache.catalina.core.StandardService.startInternal(StandardService.java:441)
gateway-dev-app_1 | 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147)
gateway-dev-app_1 | 	... 21 more
gateway-dev-app_1 | Caused by: org.apache.catalina.LifecycleException: A child container failed during start
gateway-dev-app_1 | 	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:924)
gateway-dev-app_1 | 	at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:262)
gateway-dev-app_1 | 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147)
gateway-dev-app_1 | 	... 23 more
docker_gateway-dev-app_1 exited with code 0

```
##### **Motivation for or Use Case** 
I saw this when working on the jhipster-docker-compose generator.

##### **JHipster Version(s)** 
Master

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 
```
{
  "generator-jhipster": {
    "jhipsterVersion": "2.27.0",
    "baseName": "gateway",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": "no",
    "buildTool": "maven",
    "jwtSecretKey": "df113f1173888aeee8a5a02305f148415ee7b5a2",
    "rememberMeKey": "",
    "useSass": false,
    "applicationType": "gateway",
    "testFrameworks": [
      "gatling"
    ],
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ]
  }
}
```
##### **Browsers and Operating System** 
Ubuntu 14.04

##### **Reproduce the error** 

1. Generate a gateway
2. run `mvn package docker:build`
3. go in src/main/docker
4. run `docker-compose -f app.dev.yml up` 

##### **Suggest a Fix** 
I don't know from where this come from but I can launch a microservice app using docker without problem.

**Comment by PierreBesson** [comment] 2016-03-09 14:52
cc @pascalgrimaud

**Comment by pascalgrimaud** [comment] 2016-03-09 15:06
do you manage to start the gateway without docker ?
1) mvn package
2) java -jar target/*.war

**Comment by pascalgrimaud** [comment] 2016-03-09 15:12
The master gateway can start : https://travis-ci.org/jhipster/generator-jhipster/jobs/114780202
I will have a look as soon as I can !

**Comment by PierreBesson** [comment] 2016-03-09 15:15
It works with java -jar.

**Comment by pascalgrimaud** [comment] 2016-03-09 15:17
Can you try with the old Dockerfile ? => https://github.com/jhipster/generator-jhipster/commit/9549cd56f53ce1b014a897d1a836aae3e7f40196#diff-32b8317d0b1b30923d5bd5aaa167a0b2
The base image is FROM java:openjdk-8u72-jre
And the new Dockerfile use openjdk... I suspect the jdk version.

**Comment by wmarques** [comment] 2016-03-09 15:25
Works  with java -jar, but still having same issue when switching to the old Dockerfile

**Comment by pascalgrimaud** [comment] 2016-03-09 15:26
ok guys, I will have a look after day work

**Comment by pascalgrimaud** [comment] 2016-03-09 22:02
I made some tests, I think the cause is from : https://github.com/jhipster/generator-jhipster/commit/5eac95eb697d0d8b2e3dc1f87fd5dca4cad53553#diff-4ac12e0abae2ba3bd72788629c00c4ab

I tested on this branch: 
`git checkout -b test-issue-3122-6f101fae3 6f101fae3ce10d014eec7c7fa80eb7187424cb65`
and it works fine.

The main issue comes from the package.war
To reproduce (no need docker) :
1) generate a simple project, all options by default
2) mvn package
3) move the target/*.war to another directory
4) go into this directory: java -jar *.war

Sorry, no time to try to resolve it.
@erikkemperman : as you did the initial commit, can you have a look (if you're not so tired like me after work)

**Comment by erikkemperman** [comment] 2016-03-09 22:26
I can take a look tomorrow afternoon (CET), but my first guess is it might be the `setDocumentRoot` call in WebConfigurer.java? Does it work without that call? Or catching any exception from that?

If I remember correctly this was only needed when running in IDE, but now I guess the relative path there might be a problem when issuing the `java -jar` command from directory other than project root?

**Comment by pascalgrimaud** [comment] 2016-03-10 07:32
Yes the war file works without setDocumentRoot
I didn't test with an IDE

**Comment by pascalgrimaud** [comment] 2016-03-10 08:32
@PierreBesson @wmarques : if you confirm my tests, can you change the title to an appropriate plz ?

**Comment by erikkemperman** [comment] 2016-03-10 08:48
I can confirm that the `setDocumentRoot` call is causing this issue.

Without it, the war works independent of where it is relative to the cwd at the time of the `java -jar` command.

Unfortunately I can also confirm that without it, running the application in the IDE with prod profile doesn't work (well, it seems to work but you actually get the dev assets because those are at the default location).

The call itself doesn't throw any exception we could catch though, it just sets the value which then causes things to break later. So I guess we should somehow detect whether we're running the executable war or as regular application, and only do the `setDocumentRoot` in the latter case?

I'll try to come up with the least ugly way to do this, and make a PR.

Sorry about having introduced this problem!

**Comment by wmarques** [comment] 2016-03-10 09:02
Thanks for your feedbacks, I updated the title tell me if it's not accurate with the issue !

**Comment by erikkemperman** [comment] 2016-03-10 09:11
Well, the problem is not so much that the path is wrong, but that the war should be portable and therefore there is no right path, if you know what I mean. We should not call `setDocumentRoot` at all when running from the war-file.

I have made a PR [#3125](https://github.com/jhipster/generator-jhipster/pull/3125) which addresses this. The detection of whether it's running from the war-file or not is not very pretty, if anyone knows of a nicer way to do this...?

**Comment by erikkemperman** [comment] 2016-03-11 07:27
So the PR was merged... There might be a better way to detect running from war, I'd love to hear about it!

In the mean time though it would be good if you guys can confirm this works for your use case, and if so close the issue?

**Comment by deepu105** [comment] 2016-03-11 08:17
@wmarques @pascalgrimaud can you guys check plz?

**Comment by pascalgrimaud** [comment] 2016-03-11 08:23
I can test on linux tonight. Tests which must be done:
- Windows / OSX / Linux
    - Maven / Gradle
        - the package.war in target/ folder or build/lib/ for gradle
        - move the .war to another folder, and 
        - with IDE
        - of course, the default ./mvnw or ./gradlew should work

**Comment by deepu105** [comment] 2016-03-11 08:28
@pascalgrimaud btw what do you think of @erikkemperman suggestion to remove the setDocumentRoot as the need to run an app in prod from IDE is very rare and if done should be only for debugging purpose?

**Comment by pascalgrimaud** [comment] 2016-03-11 08:45
When developping / debugging, start the app in prod profile is optional, so IMO it's not so important.
Anyway, the user would be able to test his app in prod profile using : ./mvnw -Pprod or ./gradlew -Pprod

**Comment by PierreBesson** [comment] 2016-03-11 09:00
For me, th only way I knew to launch the app in prod profile was using the Maven IDE plugin and switch the profile there.

**Comment by erikkemperman** [comment] 2016-03-11 09:33
Maybe just to clarify, the case I was talking about (and which breaks without the `setDocumentRoot` call) is in Eclipse STS (and I imagine IntelliJ): Run/Debug as application. You can edit run/debug configurations and add VM arguments, such as `spring.profiles.active`.

But I think this might be quite a rare thing to do, and it is the only reason the `setDocumentRoot` call is in there. So if this doesn't have to be supported, we can remove that (and the ugly detection of war/not-war) entirely.

**Comment by wmarques** [comment] 2016-03-11 09:55
@deepu105 it works fine with docker and `java -jar` command in target folder and `./mvnw`.

**Comment by deepu105** [comment] 2016-03-11 10:01
may be we could add a spring.profile variable to activate this something
like -Pdebug  or -Pide

ANd we can document it so that if anyone wants to run prod profile from IDE
s/he could pass this additional environment variable along with -Pprod

Thanks & Regards,
Deepu

**Comment by deepu105** [comment] 2016-03-11 10:19
Guys Im closing this, plz reopen if there is any issue

**Closed by deepu105** 2016-03-11 10:19 UTC
Labels: bug
