### ISSUE TITLE
elasticsearch SearchPhaseExecutionException  Failed to execute phase [dfs]

### ISSUE THREAD

**Issue by MBenali** [jhipster/generator-jhipster#3616] opened 2016-05-18 17:34 UTC
Hello,

I use jhipster (JHipster Generator v3.1.0) to generate microservice and gateway application (with option : **elasticsearch**).
The search don't work and i have this exception:

##### **org.elasticsearch.action.search.SearchPhaseExecutionException: Failed to execute phase [dfs], all shards failed; shardFailures**

org.elasticsearch.action.search.SearchPhaseExecutionException: Failed to execute phase [dfs], all shards failed; shardFailures {[EVDSO7OqQ9S9plbpx_auJA][account][0]: SearchParseException[[account][0]: query[_all:11235yyy-9*],from[0],size[20]: Parse Failure [Failed to parse source [{"from":0,"size":20,"query":{"query_string":{"query":"11235yyY-9*"}},"sort":[{"_score":{"order":"desc"}},{"id":{"order":"asc"}}]}]]]; nested: SearchParseException[[account][0]: query[_all:11235yyy-9*],from[0],size[20]: Parse Failure [No mapping found for [id] in order to sort on]]; }{[EVDSO7OqQ9S9plbpx_auJA][account][1]: SearchParseException[[account][1]: query[_all:11235yyy-9*],from[0],size[20]: Parse Failure [Failed to parse source [{"from":0,"size":20,"query":{"query_string":{"query":"11235yyY-9*"}},"sort":[{"_score":{"order":"desc"}},{"id":{"order":"asc"}}]}]]]; nested: SearchParseException[[account][1]: query[_all:11235yyy-9*],from[0],size[20]: Parse Failure [No mapping found for [id] in order to sort on]]; }{[EVDSO7OqQ9S9plbpx_auJA][account][2]: SearchParseException[[account][2]: query[_all:11235yyy-9*],from[0],size[20]: Parse Failure [Failed to parse source [{"from":0,"size":20,"query":{"query_string":{"query":"11235yyY-9*"}},"sort":[{"_score":{"order":"desc"}},{"id":{"order":"asc"}}]}]]]; nested: SearchParseException[[account][2]: query[_all:11235yyy-9*],from[0],size[20]: Parse Failure [No mapping found for [id] in order to sort on]]; }{[EVDSO7OqQ9S9plbpx_auJA][account][3]: SearchParseException[[account][3]: query[_all:11235yyy-9*],from[0],size[20]: Parse Failure [Failed to parse source [{"from":0,"size":20,"query":{"query_string":{"query":"11235yyY-9*"}},"sort":[{"_score":{"order":"desc"}},{"id":{"order":"asc"}}]}]]]; nested: SearchParseException[[account][3]: query[_all:11235yyy-9*],from[0],size[20]: Parse Failure [No mapping found for [id] in order to sort on]]; }{[EVDSO7OqQ9S9plbpx_auJA][account][4]: SearchParseException[[account][4]: query[_all:11235yyy-9*],from[0],size[20]: Parse Failure [Failed to parse source [{"from":0,"size":20,"query":{"query_string":{"query":"11235yyY-9*"}},"sort":[{"_score":{"order":"desc"}},{"id":{"order":"asc"}}]}]]]; nested: SearchParseException[[account][4]: query[_all:11235yyy-9*],from[0],size[20]: Parse Failure [No mapping found for [id] in order to sort on]]; }
	at org.elasticsearch.action.search.type.TransportSearchTypeAction$BaseAsyncAction.onFirstPhaseResult(TransportSearchTypeAction.java:238)
	at org.elasticsearch.action.search.type.TransportSearchTypeAction$BaseAsyncAction$1.onFailure(TransportSearchTypeAction.java:184)
	at org.elasticsearch.search.action.SearchServiceTransportAction$23.run(SearchServiceTransportAction.java:565)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Thanks

**Comment by jdubois** [comment] 2016-05-18 17:37
Could you send us your config files? If we can't reproduce it we can't help you.

**Comment by MBenali** [comment] 2016-05-18 17:41
Which config files:
ms/application.yml and gateway/application.yml ?

**Comment by jdubois** [comment] 2016-05-18 17:44
Both. And your JSON files in the .jhipster folder.
You should of course remove sensitive information.

**Comment by MBenali** [comment] 2016-05-18 18:14
The first error was in json files, different names for entityTableName 
i change it in the gateway/ .jhipster / myEntity, and run a mvn clean install, but 


[ELASTIC_EXCEPTION.tar.gz](https://github.com/jhipster/generator-jhipster/files/271096/ELASTIC_EXCEPTION.tar.gz)

Thanks

**Comment by faycelabidi** [comment] 2016-05-18 21:26
Hi Mbenali, I have done the same test with a simple Entity with a field of type String and It is working.
I think that you have to rerun the yo jhipster:entity <yourentity> from your gateway. Let me know the news .

**Comment by MBenali** [comment] 2016-05-19 07:12
Hi all,
I think, the origin of this problem, is the fact i rename the database, and nameEntity.
the indexName in (@Document(....) also has different name / .jhipster / myEntity,

**Comment by MBenali** [comment] 2016-05-19 17:47
It work for me whith monolithic form.

I will abandon the use of ElasticSearch for my queries.

What other solution will you advise me?

Thanks

**Comment by deepu105** [comment] 2016-05-20 01:07
Can you confirm if the issue was caused by you renaming the table?  Does it
work with whatever we generate by default?

**Comment by jdubois** [comment] 2016-05-20 08:21
From my understanding @MBenali you renamed several things, so basically this is not code, and not a JHipster issue, so I'm closing this.

**Closed by jdubois** 2016-05-20 08:21 UTC
Labels: microservice

**Comment by MBenali** [comment] 2016-05-20 08:37
exact, i have rename several things, create, drop and recreate my MySql database.

i use  mvn liquibase:dropAll -Dliquibase.url=jdbc:mysql://localhost:3306/referentiel_ms -Dliquibase.username=root -Dliquibase.password=admin

and 
mvn liquibase:clearCheckSums -Dliquibase.username=root -Dliquibase.password=admin


Thanks

**Comment by mfalzetta** [comment] 2017-01-15 00:36
For that another person wate time.

My problem is because i have data in my data base saved in a application version generated from jHipster without Elasticsearch.
After update for version with Elasticsearch the old data is not found and a error "error.internalServerError"is shoed in the page.

**Comment by jdubois** [comment] 2017-01-15 00:39
Yes you need to index the old data, of course. There's a reindexer module but I have never used it.

**Comment by mfalzetta** [comment] 2017-01-15 00:56
If you can answer me, please...

My entity search, only works for one field.

Im try to understand why, because i ready this "Search superpowers are also added to the AngularJS UI, so you can search in your entity’s list screen."

You have a suggestion where to look in code/configuration?

Thanks a lot.

**Comment by mfalzetta** [comment] 2017-01-15 01:09
Sorry, works perfect!
I was looking for indexed data.
