### ISSUE TITLE
jib dockBuild throws CacheDirectoryNotOwnedException

### ISSUE THREAD

**Issue by marianfoo** [jhipster/generator-jhipster#9589] opened 2019-04-20 07:06 UTC
##### **Overview of the issue**

After creating a microservice App, i try to create a docker file with 
`./mvnw package -Pprod verify jib:dockerBuild`

```
Following error occurs:
[INFO] Containerizing application to Docker daemon as amazoncrawler...
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  07:02 min
[INFO] Finished at: 2019-04-19T22:29:10+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.google.cloud.tools:jib-maven-plugin:0.9.11:dockerBuild (default-cli) on project amazon-crawler: Build to Docker daemon failed, perhaps you should check that '/Library/Application Support/google-cloud-tools-java/jib' is not used by another application or set the `useOnlyProjectCache` configuration: CacheDirectoryNotOwnedException -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
```
same error on gateway app, so not in particular a microservice issue
##### **Reproduce the error**

Create Microservice App
```
? Which *type* of application would you like to create? Microservice application
? What is the base name of your application? amazonCrawler
? As you are running in a microservice architecture, on which port would like your server to run? It should be unique
 to avoid port conflicts. 8083
? What is your default Java package name? com.goat.crawler
? Which service discovery server do you want to use? JHipster Registry (uses Eureka, provides Spring Cloud Config sup
port and monitoring dashboards)
? Which *type* of authentication would you like to use? JWT authentication (stateless, with a token)
? Which *type* of database would you like to use? SQL (H2, MySQL, MariaDB, PostgreSQL, Oracle, MSSQL)
? Which *production* database would you like to use? PostgreSQL
? Which *development* database would you like to use? H2 with disk-based persistence
? Do you want to use the Spring cache abstraction? Yes, with the Hazelcast implementation (distributed cache, for mul
tiple nodes)
? Do you want to use Hibernate 2nd level cache? Yes
? Would you like to use Maven or Gradle for building the backend? Maven
? Which other technologies would you like to use? API first development using OpenAPI-generator
? Would you like to enable internationalization support? Yes
? Please choose the native language of the application English
? Please choose additional languages to install German
? Besides JUnit and Jest, which testing frameworks would you like to use? 
? Would you like to install other generators from the JHipster Marketplace? No
```

run
`./mvnw package -Pprod verify jib:dockerBuild`

##### **Related issues**

The only thing i found with this exception is this github issue:
[jib:dockerBuild fails: CacheDirectoryNotOwnedException](https://github.com/GoogleContainerTools/jib/issues/471)

as written there, did a clean, but error still exists
##### **Suggest a Fix**

after updating the jib maven plugin in pom.xml, it works:
`<jib-maven-plugin.version>1.1.1</jib-maven-plugin.version>`

unfortunately when i try that to run with
`docker run IMAGENAME`
i get following error:
```
The application will start in 0s...
Error: Could not find or load main class com.goat.crawler.AmazonCrawlerApp
```

##### **JHipster Version(s)**

```
amazoncrawler@0.0.0 Documents/master/amazoncrawler
└── generator-jhipster@5.8.1 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "appsFolders": [
      "jhipstergateway"
    ],
    "directoryPath": "./",
    "gatewayType": "zuul",
    "monitoring": "prometheus",
    "serviceDiscoveryType": "eureka",
    "jwtSecretKey": "",
    "promptValues": {
      "packageName": "com.goat.crawler",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "5.8.1",
    "applicationType": "microservice",
    "baseName": "amazoncrawler",
    "packageName": "com.goat.crawler",
    "packageFolder": "com/goat/crawler",
    "serverPort": "8083",
    "authenticationType": "jwt",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": true,
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": true,
    "clientPackageManager": "npm",
    "nativeLanguage": "en",
    "languages": [
      "en",
      "de"
    ],
    "skipClient": true,
    "skipUserManagement": true
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_51"
Java(TM) SE Runtime Environment (build 1.8.0_51-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.51-b03, mixed mode)

git version 2.19.1

node: v10.10.0

npm: 6.7.0

yeoman: 2.0.0

yarn: 1.13.0

Docker version 18.09.2, build 6247962

docker-compose version 1.23.2, build 1110ad01

##### **Browsers and Operating System**

macOS 10.14.4

-   [ X] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment] 2019-04-22 08:34
Just tried your configuration with JHipster 5.8.1, and it works fine. I don't have problem to build my Docker image:

```
[INFO] --- jib-maven-plugin:0.9.11:dockerBuild (default-cli) @ amazoncrawler ---
[WARNING] Setting image creation time to current time; your image may not be reproducible.
[INFO] 
[INFO] Containerizing application to Docker daemon as amazoncrawler...
[INFO] 
[INFO] Getting base image openjdk:8-jre-alpine...
[INFO] Building dependencies layer...
[INFO] Building resources layer...
[INFO] Building extra files layer...
[INFO] Building classes layer...
[INFO] The base image requires auth. Trying again for openjdk:8-jre-alpine...
[INFO] Retrieving registry credentials for registry.hub.docker.com...
[INFO] Finalizing...
[INFO] Loading to Docker daemon...
[INFO] 
[INFO] Container entrypoint set to [sh, -c, chmod +x /entrypoint.sh && sync && /entrypoint.sh]
[INFO] 
[INFO] Built image to Docker daemon as amazoncrawler
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:16 min
[INFO] Finished at: 2019-04-22T10:23:10+02:00
[INFO] ------------------------------------------------------------------------

10:26:12 in ~/tmp/39-issue-9589 on  master 
➜ docker images|grep amazoncrawler
amazoncrawler                                   latest              7e4e3ae80af1        3 minutes ago       164MB

```

The exact command is `./mvnw -Pprod verify jib:dockerBuild`. Do not put both: package and verify. It has been fixed by https://github.com/jhipster/generator-jhipster/pull/9524

Then, as you said you managed to build your image, but `docker run` doesn't work, it's normal as you need to start your PostgreSQL database and the registry, because you choose a  `gateway` application. Have a look at the generated docker-compose file `app.yml` :

```yaml
version: '2'
services:
    amazoncrawler-app:
        image: amazoncrawler
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
            - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:postgresql://amazoncrawler-postgresql:5432/amazoncrawler
            - JHIPSTER_SLEEP=30 # gives time for the JHipster Registry to boot before the application
    amazoncrawler-postgresql:
        extends:
            file: postgresql.yml
            service: amazoncrawler-postgresql
    jhipster-registry:
        extends:
            file: jhipster-registry.yml
            service: jhipster-registry
        environment:
            - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_TYPE=native
            - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_SEARCH_LOCATIONS=file:./central-config/docker-config/
```

**Comment by pascalgrimaud** [comment] 2019-04-22 08:36
So it can be:
- a problem with the command you used
- a problem with your Docker
- as you upgraded the jib version and was unable to run the app, you need to use the docker-compose

As I don't see any issue on our side, I'm closing this.
Don't hesitate to comment if you still have an issue, and provide more information to reproduce plz.

**Closed by pascalgrimaud** 2019-04-22 08:36 UTC
Labels: docker:whale:

**Comment by marianfoo** [comment] 2019-04-22 11:01
Hi @pascalgrimaud 
thank you so much for your answer.
Your build of the docker image looked different to mine, so it was definitely a problem with the building itself.
I took the command `./mvnw -Pprod verify jib:dockerBuild` from here ["Docker and Docker Compose"](https://www.jhipster.tech/docker-compose/).
The database and the registry are running anyway.
But i just found a workaround with using `sudo`. So it's an permission error on my side.
After that the build output looked like yours and i can run it with simply `docker run amazonCrawler`.
Didn't need to update jib plugin too.
Thanks again for your work

**Comment by pascalgrimaud** [comment] 2019-04-22 12:50
happy to know it works for you now ! :-) 
Thanks for your feedback @marianfoo
