### ISSUE TITLE
Filtering entities limited to two attributes

### ISSUE THREAD

**Issue by pierro72** [jhipster/generator-jhipster#6543] opened 2017-10-17 10:36 UTC
##### **Overview of the issue**
I have generated an simple Jhipster app and i create some entity with filter. 
The api-docs page only display the parameters for the two first attributes of the entities.
Exemple my entity has : 
**Long** 		id 
**String** 		nom 
**String** 		description 
**Long** 		collaborateur_id 

The EntityCriteria has :

**LongFilter** 		id 
**StringFilter** 	nom 
**StringFilter** 	description 
**LongFilter** 		collaborateur_id 
in swagger view for the route GET '/api/entities'
there is just the parameters for attribute **id** and **name** witch is diplayed.
This is the same for all my entities with criteria
##### **JHipster Version(s)**
- jhipster version 4.9.0
##### **JHipster configuration**
My jHipster app :
- "baseName": "skillex",
- "packageName": "fr.sodifrance.skillex",
- "packageFolder": "fr/sodifrance/skillex",
- "serverPort": "8080",
- "authenticationType": "jwt",
- "hibernateCache": "ehcache",
- "clusteredHttpSession": false,
- "websocket": false,
- "databaseType": "sql",
- "devDatabaseType": "mysql",
- "prodDatabaseType": "mysql",
- "searchEngine": false,
- "messageBroker": false,
- "serviceDiscoveryType": false,
- "buildTool": "maven",
- "enableSocialSignIn": false,
- "enableSwaggerCodegen": true,
- "jwtSecretKey": "replaced-by-jhipster-info",
- "clientFramework": "angularX",
- "useSass": false,
- "clientPackageManager": "yarn",
- "applicationType": "monolith"

My tools :
- java version "1.8.0_112"
- Java(TM) SE Runtime Environment (build 1.8.0_112-b15)
- Java HotSpot(TM) 64-Bit Server VM (build 25.112-b15, mixed mode)
- git version 2.11.0.windows.1
-  node: v8.6.0
- npm: 5.4.2
- yeoman: 2.0.0
- yarn: 1.2.0
- Docker version 17.07.0-ce, build 8784753
- docker-compose version 1.15.0, build e12f3b94
##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**
My entities:
- "dto": "no",
- "service": "serviceClass",
- "entityTableName": "competence",
- "jpaMetamodelFiltering": true,
- "pagination": "no",
- "microserviceName": "apiskillex",
- "searchEngine": false

**Comment by gzsombor** [comment] 2017-10-17 10:55
Could you check, that calling it from the browser works correctly?
For example: '/api/entities?description.contains=something&collaborateur_id.equals=12
If yes, it must be a swagger issue.

**Comment by pierro72** [comment] 2017-10-17 11:54
I send my request with postman and I get a good answer.

**Comment by gzsombor** [comment] 2017-10-28 20:32
It's seems to be a springfox failure, I've sent a patch, hopefully they will merge it.

**Comment by gmarziou** [comment] 2017-11-18 19:52
@gzsombor's PR has been merged. Should we wait for Springfox's next release to close this issue? Previous release was in May.

**Comment by gzsombor** [comment] 2017-11-20 20:28
I would wait for the next release, so we wont forget to upgrade

**Comment by gzsombor** [comment] 2017-11-20 20:29
There is an open question about a new release : https://github.com/springfox/springfox/issues/2079 
Unfortunately it is stalled :(

**Comment by jdubois** [comment] 2017-12-04 12:25
I'm closing this as the issue is not on our side - as soon as SpringFox corrects it, we will upgrade anyway, so no problem for us.
Sorry but we have 44 opened issues, so we need to clean up issues with less priority.

**Closed by jdubois** 2017-12-04 12:25 UTC
