### ISSUE TITLE
Runtime language change don't always translate all

### ISSUE THREAD

**Issue by Skynniman** [jhipster/generator-jhipster#1364] opened 2015-04-09 22:44 UTC
Hi,
After some tries on jHipster, without touch any lines, there is a little bug that can be very annoying with translations... and it happend on most of views.
For exemple : Metrics
If I come on the page with English language (or what ever else language) everything is correctly translate
but if I change the language on the page most (even all) the text go back to it's identifier.
if I want to see the translations I must change page and after go back to metrics or refresh the page

![en](https://cloud.githubusercontent.com/assets/8077943/7078482/cc786b34-df19-11e4-96af-23b39007b727.png)

After language change
![fr](https://cloud.githubusercontent.com/assets/8077943/7078483/cc835d64-df19-11e4-9e9b-55b450824de1.png)

Tested on Chrome 43 without any plugins on up to date linux system
Version of jHipster : 2.7.0
Project created with all default answer
app serve with mvn spring-boot:run + grunt serve (bug happend on both port)

**Comment by jdubois** [comment] 2015-04-12 19:58
It works for me...

- Is this also happening on other OSes / browsers? This is to check if the issue is specific to your system
- What other langage are you using?
- Can you tell me precisely what you do?

**Comment by wuethrich44** [comment] 2015-04-13 06:42
Can you check your global.json has a proper format? 

Maybe this bug is duplicated with #1287.

**Comment by jdubois** [comment] 2015-04-13 08:17
@wuethrich44 good catch! It's quite obviously this issue -> I'm closing this as a duplicate

The real problem is that I don't know how we could solve this cleanly. One of the problems with JSON is that you can't put comments in it, so we can't warn the user he shouldn't delete that line.

**Closed by jdubois** 2015-04-13 08:17 UTC

**Comment by tagliola** [comment] 2015-04-15 12:04
Put a clear replacement marker in the text? If the translator shouldn't
translate, make sure it's not english. Either that, or put 'DO NOT
TRANSLATE' in the line :-)

**Comment by jdubois** [comment] 2015-04-15 12:10
Yes that's what we just did! I merged this today :-)
