### ISSUE TITLE
Camel case entity names do not work properly with jdl import

### ISSUE THREAD

**Issue by dpalomar** [jhipster/generator-jhipster#4398] opened 2016-10-28 12:46 UTC
##### **Overview of the issue**
Using jdl import not generates  names of entity correctly when the name is like _NameXX_ , this does not occur when the _jhipster:entity_ generator is used.

##### **Motivation for or Use Case**

If an entity has a relationship with another one that use a name like before pattern, the code does not compile, and the test will fail.

##### **Reproduce the error**

`yo jhipster:import-jdl file.jdl`

Sample file

```js
entity EntityAN {

    name String required,
    description String
}

entity EntityBN{
    name String required,
    description String
}

relationship OneToMany {
    EntityAN{catalog} to EntityBN{products}
}


paginate EntityAN, EntityBN with infinite-scroll

```

##### **Suggest a Fix**

It appears that the .jhipster/xxx.json internal code is not correctly generated, like so:

```json
    "relationships": [
        {
            "relationshipType": "one-to-many",
            "relationshipName": "catalog",
       --> "otherEntityName": "entityBn",
            "otherEntityRelationshipName": "products"
        }
    ],
```

**NOTE:** this doesn't occur with entity generator console

##### **JHipster Version(s)**

Version 3.9.1

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**
```json
{
  "generator-jhipster": {
    "jhipsterVersion": "3.9.1",
    "baseName": "demo",
    "packageName": "com.testing.demo",
    "packageFolder": "com/testing/demo",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "rememberMeKey": "0d1e5e791ae88699b28a189d34218301f3f5b228",
    "useSass": false,
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling",
      "cucumber",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "es"
    ]
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

File **EntityAN.json**

```json
{
    "fluentMethods": true,
    "relationships": [
        {
            "relationshipType": "one-to-many",
            "relationshipName": "catalog",
            "otherEntityName": "entityBn",
            "otherEntityRelationshipName": "products"
        }
    ],
    "fields": [
        {
            "fieldName": "name",
            "fieldType": "String",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "description",
            "fieldType": "String"
        }
    ],
    "changelogDate": "20161028121407",
    "entityTableName": "entity_an",
    "dto": "no",
    "pagination": "infinite-scroll",
    "service": "no"
}
```

File **EntityBN.json**

```json
{
    "fluentMethods": true,
    "relationships": [
        {
            "relationshipType": "many-to-one",
            "relationshipName": "products",
            "otherEntityName": "entityAn",
            "otherEntityField": "id"
        }
    ],
    "fields": [
        {
            "fieldName": "name",
            "fieldType": "String",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "description",
            "fieldType": "String"
        }
    ],
    "changelogDate": "20161028121408",
    "entityTableName": "entity_bn",
    "dto": "no",
    "pagination": "infinite-scroll",
    "service": "no"
}
```

**JDL file** used

```javascript

entity EntityAN {

    name String required,
    description String
}

entity EntityBN{
    name String required,
    description String
}

relationship OneToMany {
    EntityAN{catalog} to EntityBN{products}
}


paginate EntityAN, EntityBN with infinite-scroll
```

##### **Browsers and Operating System**

Ubuntu 14.04

**Comment by jdubois** [comment] 2016-10-28 13:08
I think this should go to the jhipster/jhipster-core project, @MathieuAA what do you think?

**Comment by cbornet** [comment] 2016-10-28 13:17
:+1:  I also have the issue !
And yes, it's a jhipster-core issue.

**Comment by MathieuAA** [comment] 2016-10-28 13:30
I confirm. It will be fixed tomorrow.

**Comment by Dufgui** [comment] 2016-10-29 21:43
I think it's related to  #4320.

**Comment by deepu105** [comment] 2016-10-30 09:51
Im closing this as the issue is in jHipster-core

**Closed by deepu105** 2016-10-30 09:51 UTC
