### ISSUE TITLE
gateway monitor issue cannot use setMetricRegistry() and setMetricsTrackerFactory() together

### ISSUE THREAD

**Issue by yudar1024** [jhipster/generator-jhipster#7497] opened 2018-04-17 13:45 UTC
##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.jh5.gateway",
      "nativeLanguage": "zh-cn"
    },
    "jhipsterVersion": "5.0.0-beta.0",
    "baseName": "gateway",
    "reactive": false,
    "packageName": "com.jh5.gateway",
    "packageFolder": "com/jh5/gateway",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "gradle",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "clientFramework": "react",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "gateway",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "zh-cn",
    "languages": [
      "zh-cn",
      "en"
    ]
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)

git version 2.16.0.windows.2

node: v8.11.1

npm: 5.6.0

yeoman: 2.0.2

yarn: 1.5.1

Congratulations, JHipster execution is complete!

##### **Overview of the issue**

micro service gateway can not run. 

##### **Motivation for or Use Case**

i need to create a gateway project

##### **Reproduce the error**

step 1 jhipster
step 2 choose gateway template
step 3 use mysql
step 4 use cache enhance
step 5 hibernate cache level 2 enable
step 6 no sass
step 7 no testing framework be choosen
project create successfully

step 8 import to intellig idea

step 9 just run the application.java
##### **Suggest a Fix**

``` java
Caused by: java.lang.IllegalStateException: cannot use setMetricRegistry() and setMetricsTrackerFactory() together
	at com.zaxxer.hikari.HikariConfig.setMetricRegistry(HikariConfig.java:734)
	at com.zaxxer.hikari.HikariDataSource.setMetricRegistry(HikariDataSource.java:237)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:223)
	at org.springframework.cloud.context.scope.GenericScope$LockedScopedProxyFactoryBean.invoke(GenericScope.java:482)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)
	at com.zaxxer.hikari.HikariDataSource$$EnhancerBySpringCGLIB$$b43d8931.setMetricRegistry(<generated>)
	at com.jh5.gateway.config.MetricsConfiguration.init(MetricsConfiguration.java:78)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:369)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:312)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:135)
	... 46 common frames omitted
```

it seems MetricsConfiguration.init cause the problem
the statement is
hikariDataSource.setMetricRegistry(metricRegistry);

##### **JHipster Version(s)**

5.0.0-beta.0

##### **JHipster configuration**

{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.jh5.gateway",
      "nativeLanguage": "zh-cn"
    },
    "jhipsterVersion": "5.0.0-beta.0",
    "baseName": "gateway",
    "reactive": false,
    "packageName": "com.jh5.gateway",
    "packageFolder": "com/jh5/gateway",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "gradle",
    "enableSwaggerCodegen": false,
    "clientFramework": "react",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "gateway",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "zh-cn",
    "languages": [
      "zh-cn",
      "en"
    ]
  }
}

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

none

##### **Browsers and Operating System**
chrome 65 x64

windows 10 x64

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment] 2018-04-17 13:49
Are you using the "5.0.0-beta.0" release or did you clone the project from the master branch? Because this used to happen some time ago, and this should be fixed now

**Comment by yudar1024** [comment] 2018-04-17 13:56
yes i am using 5.0.0-beta.0. i install jhipster via nodejs by specify beta.0 version . i do not clone from master branch.

**Comment by Dufgui** [comment] 2018-04-22 19:36
I reproduce the error with current master (a023db535af263f5e0c0bf3c53d5f8c01218566d), i will take a look to find a fix.

**Comment by Dufgui** [comment] 2018-04-22 21:33
ok it's came from a new auto config from spring boot : 
https://github.com/spring-projects/spring-boot/commits/master/spring-boot-project/spring-boot-actuator-autoconfigure/src/main/java/org/springframework/boot/actuate/autoconfigure/metrics/jdbc/HikariDataSourceMetricsPostProcessor.java

I am asking myself if must migrate to meterRegistry instead of metricRegistry.  Maybe I don't well understand but spring boot seems using this now : https://github.com/micrometer-metrics

**Comment by jdubois** [comment] 2018-04-23 06:37
Yes we'll migrate to micrometer but in 6-12 months as we need to re code everything for it. And I would like to wait until it matures a bit.

**Comment by Dufgui** [comment] 2018-04-23 07:04
Ok so I will try a quick fix
Le lun. 23 avr. 2018 à 08:37, Julien Dubois <notifications@github.com> a
écrit :

**Comment by Dufgui** [comment] 2018-04-23 09:01
I can add an integration/Travis test if you want ?

**Closed** 2018-04-26 07:42 UTC
