### ISSUE TITLE
[JDL] Importing a file containing "all" as an Entity's property fails

### ISSUE THREAD

**Issue by amatosg** [jhipster/generator-jhipster#10709] opened 2019-10-30 03:41 UTC
##### **Overview of the issue**
I have a jh file with many entities. One of them has `allowLoginAfterHours` as a property. When I import that jh file with 6.4.1 it fails with following message:

```
SyntaxError: Error: MismatchedTokenException: Expecting --> '}' <-- but found --> 'all' <-- 
at line: 57, column: 5
```
Moving the property to another line will be reported on error message.

##### **Motivation for or Use Case**
I should be able to import a JDL file with entities having properties that start with `all`.

##### **Reproduce the error**
* Create a JDL file
* Add an entity
* Add a field that starts with `all`

##### **Related issues**
Unknown
##### **Suggest a Fix**
Not sure where the check happens

##### **JHipster Version(s)**
6.4.1

##### **JHipster configuration**
<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.almasoft.facturapp"
    },
    "jhipsterVersion": "6.4.1",
    "applicationType": "monolith",
    "baseName": "FacturApp",
    "packageName": "com.almasoft.facturapp",
    "packageFolder": "com/almasoft/facturapp",
    "serverPort": "8080",
    "authenticationType": "session",
    "cacheProvider": "caffeine",
    "enableHibernateCache": true,
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "rememberMeKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "embeddableLaunchScript": false,
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "angularX",
    "clientTheme": "spacelab",
    "clientThemeVariant": "primary",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": false,
    "blueprints": []
  }
}

</pre>
</details>

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**
I have no entities

##### **Browsers and Operating System**
macOs
-   [x] Checking this box is mandatory (this is just to show you read everything)

Love JHipster? Please consider supporting our collective:
👉  https://opencollective.com/generator-jhipster/donate

**Comment by ruddell** [comment] 2019-10-30 03:57
Thanks for reporting, there's already a related issue in the jhipster-core repository.

Duplicate of https://github.com/jhipster/jhipster-core/issues/389

**Closed by ruddell** 2019-10-30 03:57 UTC

**Comment by amatosg** [comment] 2019-10-30 05:02
thanks
