### ISSUE TITLE
Undefined types in minified Javascript file

### ISSUE THREAD

**Issue by seanoreillyza** [jhipster/generator-jhipster#1717] opened 2015-07-13 10:12 UTC
Hi All,

I have included the Quagga JS library in my project https://serratus.github.io/quaggaJS/ which works perfectly fine using my JHipster dev profile. 

However, when I test a production / minified version of my project, I get the following error:

Uncaught ReferenceError: glMatrixArrayType is not define (even though Quagga.js logic has been included in the resultant minified production JS file)

I only get this error in production mode, when all JS files have been minified into one file.

As an interim fix, what's the best way to exclude this file from the minification process and include it as a separate JS file in production mode?

**Comment by deepu105** [comment] 2015-07-13 10:28
Add the script outside the minification block below in the index file as interim solution, but ideally this should work out of box, I have used hell lot of additional plugins and works like a charm in prod mode.
```
        <!-- build:js scripts/vendor.js -->
        <!-- bower:js -->
        <!-- endbower -->
        <!-- endbuild -->
```
Anyways since this is not a plugin we ship with we wont be able to help much here. May be if you can dig deeper and provide some more info we might be able to help

**Comment by gmarziou** [comment] 2015-07-13 10:30
I would add that it depends also on how you integrated it: manually or using bower install.

**Comment by seanoreillyza** [comment] 2015-07-13 12:03
Hi guys,

Thanks for the prompt response. 

I was originally trying to keep the JS file outside of the build list as follows:

```
 <!-- build:js scripts/vendor.js -->
        <!-- bower:js -->
        <!-- endbower -->
        <!-- endbuild -->
<script src="scripts/app/quagga/quagga.js"></script>
```
But this resulted in a browser error, as Grunt was removing the javascript files from the scripts directory (in the minification step) and as a result the required JS file was no longer in the dist/scripts/app/quagga directory.

This kind of behaviour can be overridden using the Grunt config file, but I didn't to modify the defaults for this particular situation.

I ended up putting the required JS file in the root of the application, alongside index.html

```
<!-- endbuild -->
<script src="quagga.js"></script>
```

As an interim solution, this did solve the problem.

I then installed the library using bower
```
bower install "quagga" --save
```

And modified index.html by removing the old include and adding the following the appropriate location:
```
<script src="bower_components/quagga/dist/quagga.js"></script>
<!-- endbower -->
<!-- endbuild -->
```
This also seems to be working before and after minification.

**Comment by gmarziou** [comment] 2015-07-13 12:09
Yes scripts in bower_components are not modified because usually their distribution already include a minified version.
But you should not have to manually add '<script src="bower_components/quagga/dist/quagga.js"></script>', running 'grunt wiredep' or 'grunt serve' does it for you for all bower components.

**Comment by jdubois** [comment] 2015-07-13 12:12
Yes, this is just adding an external lib, it's documented [here](http://jhipster.github.io/development.html)

-> this is why I'm closing this, it is not a bug

@seanoreillyza if you follow the doc and have an error, can you add a comment or create a new bug? To be honest I haven't used it for a long time, and documentation can always be improved

**Closed by jdubois** 2015-07-13 12:12 UTC

**Comment by seanoreillyza** [comment] 2015-07-13 12:14
Happy to contribute where I can - thanks again for the feedback.
