### ISSUE TITLE
Application run failed -  Error creating bean with name 'feignRetryer'

### ISSUE THREAD

**Issue by depzor** [jhipster/generator-jhipster#8144] opened 2018-08-22 14:42 UTC
##### **Overview of the issue**

When running the app:

`2018-08-22 14:24:43.207  WARN 1 --- [           main] c.n.c.sources.URLConfigurationSource     : No URLs will be polled as dynamic configuration sources.
my-app_1  | 2018-08-22 14:24:44.789  WARN 1 --- [           main] s.c.a.AnnotationConfigApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'feignRetryer' defined in org.springframework.cloud.openfeign.FeignClientsConfiguration: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [feign.Retryer]: Factory method 'feignRetryer' threw exception; nested exception is java.lang.NoSuchFieldError: NEVER_RETRY
my-app_1  | 2018-08-22 14:24:44.792  WARN 1 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'myCustomResource' defined in URL [jar:file:/home/jhipster/app.war!/WEB-INF/classes!/com/mycompany/test/web/rest/MyCustomResource.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'myCustomServiceImpl' defined in URL [jar:file:/home/jhipster/app.war!/WEB-INF/classes!/com/mycompany/test/service/impl/MyCustomServiceImpl.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.mycompany.test.client.MyCustomFeignClient': FactoryBean threw exception on object creation; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'feignRetryer' defined in org.springframework.cloud.openfeign.FeignClientsConfiguration: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [feign.Retryer]: Factory method 'feignRetryer' threw exception; nested exception is java.lang.NoSuchFieldError: NEVER_RETRY
my-app_1  | 2018-08-22 14:24:44.813 ERROR 1 --- [           main] o.s.boot.SpringApplication               : Application run failed
`

##### **Motivation for or Use Case**

This error seem to occur sometimes and it seems to happen only when running the app in a docker container....

##### **Reproduce the error**
MyCustomFeignClient.java

`
@FeignClient(name = "myCustomFeignClient", url = "${application.custom.url}")
public interface MyCustomFeignClient {
    @RequestMapping(method = RequestMethod.GET, value = "/api/some-endpoint")
    CustomDoc getSomethingById(@PathVariable(value = "id") final String id);
}
`

Injecting the feign client:
`
@Service
public class MyCustomServiceImpl implements MyCustomService {
    private MyCustomFeignClient client;
    public MyCustomServiceImpl(MyCustomFeignClient client) {
        this.client = client;
    }
...
`

application.yml:
`feign:
    hystrix:
        enabled: false

    client:
        config:
            myCustomFeignClient:
                decoder: feign.gson.GsonDecoder
            default:
                loggerLevel: full
                connectTimeout: 5000
                readTimeout: 5000`

Dependency tree:
 +- io.github.jhipster:jhipster-framework:jar:2.0.14:compile
[INFO] |  +- org.springframework:spring-context-support:jar:5.0.7.RELEASE:compile
[INFO] |  +- org.springframework.boot:spring-boot-actuator-autoconfigure:jar:2.0.3.RELEASE:compile
[INFO] |  |  \- org.springframework.boot:spring-boot-actuator:jar:2.0.3.RELEASE:compile
[INFO] |  \- org.springframework.boot:spring-boot-autoconfigure:jar:2.0.3.RELEASE:compile
[INFO] +- io.dropwizard.metrics:metrics-core:jar:3.2.6:compile
[INFO] |  \- org.slf4j:slf4j-api:jar:1.7.25:compile
[INFO] +- io.dropwizard.metrics:metrics-annotation:jar:3.2.6:compile
[INFO] +- io.dropwizard.metrics:metrics-json:jar:3.2.6:compile
[INFO] |  \- com.fasterxml.jackson.core:jackson-databind:jar:2.9.6:compile
[INFO] +- io.dropwizard.metrics:metrics-jvm:jar:3.2.6:compile
[INFO] +- io.dropwizard.metrics:metrics-servlet:jar:3.2.6:compile
[INFO] +- io.dropwizard.metrics:metrics-servlets:jar:3.2.6:compile
[INFO] |  +- io.dropwizard.metrics:metrics-healthchecks:jar:3.2.6:compile
[INFO] |  \- com.papertrail:profiler:jar:1.0.2:compile
[INFO] |     \- joda-time:joda-time:jar:2.9.9:compile
[INFO] +- com.fasterxml.jackson.datatype:jackson-datatype-hppc:jar:2.9.6:compile
[INFO] |  +- com.carrotsearch:hppc:jar:0.7.1:compile
[INFO] |  \- com.fasterxml.jackson.core:jackson-core:jar:2.9.6:compile
[INFO] +- com.fasterxml.jackson.datatype:jackson-datatype-jsr310:jar:2.9.6:compile
[INFO] |  \- com.fasterxml.jackson.core:jackson-annotations:jar:2.9.0:compile
[INFO] +- com.fasterxml.jackson.datatype:jackson-datatype-json-org:jar:2.9.6:compile
[INFO] |  \- org.json:json:jar:20171018:compile
[INFO] +- com.fasterxml.jackson.module:jackson-module-afterburner:jar:2.9.6:compile
[INFO] +- com.h2database:h2:jar:1.4.197:test
[INFO] +- com.jayway.jsonpath:json-path:jar:2.4.0:test
[INFO] |  \- net.minidev:json-smart:jar:2.3:test
[INFO] |     \- net.minidev:accessors-smart:jar:1.2:test
[INFO] +- io.springfox:springfox-swagger2:jar:2.9.2:compile
[INFO] |  +- io.swagger:swagger-annotations:jar:1.5.20:compile
[INFO] |  +- io.swagger:swagger-models:jar:1.5.20:compile
[INFO] |  +- io.springfox:springfox-spi:jar:2.9.2:compile
[INFO] |  |  \- io.springfox:springfox-core:jar:2.9.2:compile
[INFO] |  +- io.springfox:springfox-schema:jar:2.9.2:compile
[INFO] |  +- io.springfox:springfox-swagger-common:jar:2.9.2:compile
[INFO] |  +- io.springfox:springfox-spring-web:jar:2.9.2:compile
[INFO] |  +- com.google.guava:guava:jar:25.1-jre:compile
[INFO] |  |  +- org.checkerframework:checker-qual:jar:2.0.0:compile
[INFO] |  |  +- com.google.errorprone:error_prone_annotations:jar:2.1.3:compile
[INFO] |  |  +- com.google.j2objc:j2objc-annotations:jar:1.1:compile
[INFO] |  |  \- org.codehaus.mojo:animal-sniffer-annotations:jar:1.14:compile
[INFO] |  +- com.fasterxml:classmate:jar:1.3.4:compile
[INFO] |  +- org.springframework.plugin:spring-plugin-core:jar:1.2.0.RELEASE:compile
[INFO] |  \- org.springframework.plugin:spring-plugin-metadata:jar:1.2.0.RELEASE:compile
[INFO] +- io.springfox:springfox-bean-validators:jar:2.9.2:compile
[INFO] +- com.ryantenney.metrics:metrics-spring:jar:3.1.3:compile
[INFO] |  +- org.springframework:spring-core:jar:5.0.7.RELEASE:compile
[INFO] |  |  \- org.springframework:spring-jcl:jar:5.0.7.RELEASE:compile
[INFO] |  +- org.springframework:spring-beans:jar:5.0.7.RELEASE:compile
[INFO] |  \- org.springframework:spring-aop:jar:5.0.7.RELEASE:compile
[INFO] +- commons-io:commons-io:jar:2.6:compile
[INFO] +- org.apache.commons:commons-lang3:jar:3.7:compile
[INFO] +- org.assertj:assertj-core:jar:3.9.1:test
[INFO] +- net.logstash.logback:logstash-logback-encoder:jar:5.1:compile
[INFO] +- org.mapstruct:mapstruct-jdk8:jar:1.2.0.Final:compile
[INFO] +- org.mapstruct:mapstruct-processor:jar:1.2.0.Final:provided
[INFO] +- org.springframework.boot:spring-boot-configuration-processor:jar:2.0.3.RELEASE:provided
[INFO] +- org.springframework.boot:spring-boot-loader-tools:jar:2.0.3.RELEASE:compile
[INFO] |  \- org.apache.commons:commons-compress:jar:1.14:compile
[INFO] +- org.springframework.boot:spring-boot-starter-actuator:jar:2.0.3.RELEASE:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter:jar:2.0.3.RELEASE:compile
[INFO] |  |  +- javax.annotation:javax.annotation-api:jar:1.3.2:compile
[INFO] |  |  \- org.yaml:snakeyaml:jar:1.19:runtime
[INFO] |  \- io.micrometer:micrometer-core:jar:1.0.5:compile
[INFO] |     +- org.hdrhistogram:HdrHistogram:jar:2.1.10:compile
[INFO] |     \- org.latencyutils:LatencyUtils:jar:2.0.3:compile
[INFO] +- org.springframework.boot:spring-boot-starter-aop:jar:2.0.3.RELEASE:compile
[INFO] |  \- org.aspectj:aspectjweaver:jar:1.8.13:compile
[INFO] +- org.springframework.boot:spring-boot-starter-logging:jar:2.0.3.RELEASE:compile
[INFO] |  +- ch.qos.logback:logback-classic:jar:1.2.3:compile
[INFO] |  |  \- ch.qos.logback:logback-core:jar:1.2.3:compile
[INFO] |  +- org.apache.logging.log4j:log4j-to-slf4j:jar:2.10.0:compile
[INFO] |  |  \- org.apache.logging.log4j:log4j-api:jar:2.10.0:compile
[INFO] |  \- org.slf4j:jul-to-slf4j:jar:1.7.25:compile
[INFO] +- org.springframework.boot:spring-boot-starter-mail:jar:2.0.3.RELEASE:compile
[INFO] |  +- org.springframework:spring-context:jar:5.0.7.RELEASE:compile
[INFO] |  |  \- org.springframework:spring-expression:jar:5.0.7.RELEASE:compile
[INFO] |  \- com.sun.mail:javax.mail:jar:1.6.1:compile
[INFO] |     \- javax.activation:activation:jar:1.1:compile
[INFO] +- org.springframework.boot:spring-boot-starter-security:jar:2.0.3.RELEASE:compile
[INFO] |  +- org.springframework.security:spring-security-config:jar:5.0.6.RELEASE:compile
[INFO] |  \- org.springframework.security:spring-security-web:jar:5.0.6.RELEASE:compile
[INFO] +- org.springframework.boot:spring-boot-starter-thymeleaf:jar:2.0.3.RELEASE:compile
[INFO] |  +- org.thymeleaf:thymeleaf-spring5:jar:3.0.9.RELEASE:compile
[INFO] |  |  \- org.thymeleaf:thymeleaf:jar:3.0.9.RELEASE:compile
[INFO] |  |     +- org.attoparser:attoparser:jar:2.0.4.RELEASE:compile
[INFO] |  |     \- org.unbescape:unbescape:jar:1.1.5.RELEASE:compile
[INFO] |  \- org.thymeleaf.extras:thymeleaf-extras-java8time:jar:3.0.1.RELEASE:compile
[INFO] +- org.springframework.boot:spring-boot-starter-web:jar:2.0.3.RELEASE:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter-json:jar:2.0.3.RELEASE:compile
[INFO] |  |  +- com.fasterxml.jackson.datatype:jackson-datatype-jdk8:jar:2.9.6:compile
[INFO] |  |  \- com.fasterxml.jackson.module:jackson-module-parameter-names:jar:2.9.6:compile
[INFO] |  +- org.hibernate.validator:hibernate-validator:jar:6.0.10.Final:compile
[INFO] |  |  \- org.jboss.logging:jboss-logging:jar:3.3.2.Final:compile
[INFO] |  +- org.springframework:spring-web:jar:5.0.7.RELEASE:compile
[INFO] |  \- org.springframework:spring-webmvc:jar:5.0.7.RELEASE:compile
[INFO] +- org.springframework.boot:spring-boot-starter-test:jar:2.0.3.RELEASE:test
[INFO] |  +- org.springframework.boot:spring-boot-test-autoconfigure:jar:2.0.3.RELEASE:test
[INFO] |  +- junit:junit:jar:4.12:test
[INFO] |  +- org.mockito:mockito-core:jar:2.15.0:test
[INFO] |  |  +- net.bytebuddy:byte-buddy:jar:1.7.11:compile
[INFO] |  |  +- net.bytebuddy:byte-buddy-agent:jar:1.7.11:test
[INFO] |  |  \- org.objenesis:objenesis:jar:2.6:test
[INFO] |  +- org.hamcrest:hamcrest-core:jar:1.3:test
[INFO] |  +- org.hamcrest:hamcrest-library:jar:1.3:test
[INFO] |  +- org.skyscreamer:jsonassert:jar:1.5.0:test
[INFO] |  +- org.springframework:spring-test:jar:5.0.7.RELEASE:test
[INFO] |  \- org.xmlunit:xmlunit-core:jar:2.5.1:test
[INFO] +- org.springframework.boot:spring-boot-test:jar:2.0.3.RELEASE:test
[INFO] |  \- org.springframework.boot:spring-boot:jar:2.0.3.RELEASE:compile
[INFO] +- org.springframework.security:spring-security-test:jar:5.0.6.RELEASE:test
[INFO] |  \- org.springframework.security:spring-security-core:jar:5.0.6.RELEASE:compile
[INFO] +- org.zalando:problem-spring-web:jar:0.23.0:compile
[INFO] |  +- org.apiguardian:apiguardian-api:jar:1.0.0:compile
[INFO] |  +- com.google.code.findbugs:jsr305:jar:3.0.2:compile
[INFO] |  +- org.zalando:problem:jar:0.20.3:compile
[INFO] |  |  \- com.google.gag:gag:jar:1.0.1:compile
[INFO] |  +- org.zalando:jackson-datatype-problem:jar:0.20.3:compile
[INFO] |  +- org.zalando:faux-pas:jar:0.7.0:compile
[INFO] |  \- javax.validation:validation-api:jar:2.0.1.Final:compile
[INFO] +- io.jsonwebtoken:jjwt:jar:0.9.0:compile
[INFO] +- org.springframework.cloud:spring-cloud-starter:jar:2.0.0.RELEASE:compile
[INFO] |  +- org.springframework.cloud:spring-cloud-context:jar:2.0.0.RELEASE:compile
[INFO] |  |  \- org.springframework.security:spring-security-crypto:jar:5.0.6.RELEASE:compile
[INFO] |  +- org.springframework.cloud:spring-cloud-commons:jar:2.0.0.RELEASE:compile
[INFO] |  \- org.springframework.security:spring-security-rsa:jar:1.0.5.RELEASE:compile
[INFO] |     \- org.bouncycastle:bcpkix-jdk15on:jar:1.56:compile
[INFO] |        \- org.bouncycastle:bcprov-jdk15on:jar:1.56:compile
[INFO] +- org.springframework.cloud:spring-cloud-starter-netflix-ribbon:jar:2.0.0.RELEASE:compile
[INFO] |  +- org.springframework.cloud:spring-cloud-netflix-ribbon:jar:2.0.0.RELEASE:compile
[INFO] |  |  \- org.springframework.cloud:spring-cloud-netflix-archaius:jar:2.0.0.RELEASE:compile
[INFO] |  +- org.springframework.cloud:spring-cloud-starter-netflix-archaius:jar:2.0.0.RELEASE:compile
[INFO] |  |  +- com.netflix.archaius:archaius-core:jar:0.7.6:compile
[INFO] |  |  \- commons-configuration:commons-configuration:jar:1.8:compile
[INFO] |  +- com.netflix.ribbon:ribbon:jar:2.2.5:compile
[INFO] |  |  +- com.netflix.ribbon:ribbon-transport:jar:2.2.5:runtime
[INFO] |  |  |  +- io.reactivex:rxnetty-contexts:jar:0.4.9:runtime
[INFO] |  |  |  \- io.reactivex:rxnetty-servo:jar:0.4.9:runtime
[INFO] |  |  +- javax.inject:javax.inject:jar:1:runtime
[INFO] |  |  \- io.reactivex:rxnetty:jar:0.4.9:runtime
[INFO] |  |     +- io.netty:netty-codec-http:jar:4.1.25.Final:runtime
[INFO] |  |     |  \- io.netty:netty-codec:jar:4.1.25.Final:runtime
[INFO] |  |     \- io.netty:netty-transport-native-epoll:jar:4.1.25.Final:runtime
[INFO] |  |        +- io.netty:netty-common:jar:4.1.25.Final:runtime
[INFO] |  |        +- io.netty:netty-buffer:jar:4.1.25.Final:runtime
[INFO] |  |        +- io.netty:netty-transport-native-unix-common:jar:4.1.25.Final:runtime
[INFO] |  |        \- io.netty:netty-transport:jar:4.1.25.Final:runtime
[INFO] |  |           \- io.netty:netty-resolver:jar:4.1.25.Final:runtime
[INFO] |  +- com.netflix.ribbon:ribbon-core:jar:2.2.5:compile
[INFO] |  |  \- commons-lang:commons-lang:jar:2.6:compile
[INFO] |  +- com.netflix.ribbon:ribbon-httpclient:jar:2.2.5:compile
[INFO] |  |  +- commons-collections:commons-collections:jar:3.2.2:runtime
[INFO] |  |  +- org.apache.httpcomponents:httpclient:jar:4.5.5:runtime
[INFO] |  |  |  +- org.apache.httpcomponents:httpcore:jar:4.4.9:runtime
[INFO] |  |  |  \- commons-codec:commons-codec:jar:1.11:runtime
[INFO] |  |  +- com.sun.jersey:jersey-client:jar:1.19.1:runtime
[INFO] |  |  |  \- com.sun.jersey:jersey-core:jar:1.19.1:runtime
[INFO] |  |  |     \- javax.ws.rs:jsr311-api:jar:1.1.1:runtime
[INFO] |  |  +- com.sun.jersey.contribs:jersey-apache-client4:jar:1.19.1:runtime
[INFO] |  |  +- com.netflix.servo:servo-core:jar:0.12.21:runtime
[INFO] |  |  \- com.netflix.netflix-commons:netflix-commons-util:jar:0.3.0:runtime
[INFO] |  +- com.netflix.ribbon:ribbon-loadbalancer:jar:2.2.5:compile
[INFO] |  |  \- com.netflix.netflix-commons:netflix-statistics:jar:0.1.1:runtime
[INFO] |  \- io.reactivex:rxjava:jar:1.3.8:compile
[INFO] +- org.springframework.cloud:spring-cloud-starter-netflix-hystrix:jar:2.0.0.RELEASE:compile
[INFO] |  +- org.springframework.cloud:spring-cloud-netflix-core:jar:2.0.0.RELEASE:compile
[INFO] |  +- com.netflix.hystrix:hystrix-core:jar:1.5.12:compile
[INFO] |  +- com.netflix.hystrix:hystrix-serialization:jar:1.5.12:compile
[INFO] |  +- com.netflix.hystrix:hystrix-metrics-event-stream:jar:1.5.12:compile
[INFO] |  +- com.netflix.hystrix:hystrix-javanica:jar:1.5.12:compile
[INFO] |  |  \- org.ow2.asm:asm:jar:5.0.4:runtime
[INFO] |  \- io.reactivex:rxjava-reactive-streams:jar:1.2.1:compile
[INFO] |     \- org.reactivestreams:reactive-streams:jar:1.0.2:runtime
[INFO] +- org.springframework.retry:spring-retry:jar:1.2.2.RELEASE:compile
[INFO] +- org.springframework.cloud:spring-cloud-starter-openfeign:jar:2.0.0.RELEASE:compile
[INFO] |  +- org.springframework.cloud:spring-cloud-openfeign-core:jar:2.0.0.RELEASE:compile
[INFO] |  +- io.github.openfeign:feign-core:jar:9.5.1:compile
[INFO] |  +- io.github.openfeign:feign-slf4j:jar:9.5.1:compile
[INFO] |  +- io.github.openfeign:feign-hystrix:jar:9.5.1:compile
[INFO] |  \- io.github.openfeign:feign-java8:jar:9.5.1:compile
[INFO] +- org.springframework.cloud:spring-cloud-spring-service-connector:jar:2.0.2.RELEASE:compile
[INFO] |  \- org.springframework.cloud:spring-cloud-connectors-core:jar:2.0.2.RELEASE:compile
[INFO] +- org.springframework.security:spring-security-data:jar:5.0.6.RELEASE:compile
[INFO] |  +- javax.xml.bind:jaxb-api:jar:2.3.0:compile
[INFO] |  \- org.springframework.data:spring-data-commons:jar:2.0.8.RELEASE:compile
[INFO] +- com.googlecode.json-simple:json-simple:jar:1.1:compile
[INFO] +- org.jsoup:jsoup:jar:1.10.2:compile
[INFO] +- com.netflix.feign:feign-gson:jar:8.11.0:compile
[INFO] |  \- com.netflix.feign:feign-core:jar:8.11.0:runtime
[INFO] +- com.google.code.gson:gson:jar:2.8.4:compile
[INFO] +- org.springframework.boot:spring-boot-starter-undertow:jar:2.0.3.RELEASE:compile
[INFO] |  +- io.undertow:undertow-core:jar:1.4.25.Final:compile
[INFO] |  |  +- org.jboss.xnio:xnio-api:jar:3.3.8.Final:compile
[INFO] |  |  \- org.jboss.xnio:xnio-nio:jar:3.3.8.Final:runtime
[INFO] |  +- io.undertow:undertow-servlet:jar:1.4.25.Final:compile
[INFO] |  |  \- org.jboss.spec.javax.annotation:jboss-annotations-api_1.2_spec:jar:1.0.2.Final:compile
[INFO] |  +- io.undertow:undertow-websockets-jsr:jar:1.4.25.Final:compile
[INFO] |  |  \- org.jboss.spec.javax.websocket:jboss-websocket-api_1.1_spec:jar:1.1.3.Final:compile
[INFO] |  +- javax.servlet:javax.servlet-api:jar:3.1.0:compile
[INFO] |  \- org.glassfish:javax.el:jar:3.0.0:compile
[INFO] \- org.springframework.boot:spring-boot-devtools:jar:2.0.3.RELEASE:compile

##### **JHipster Version(s)**

        "jhipsterVersion": "4.14.3",
        "applicationType": "microservice",

##### **Browsers and Operating System**

- [x ] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment] 2018-08-22 15:31
Please could you follow the project guidelines, so we could try to reproduce? It's not possible for us to work like that.

Anyway I did a quick Google search, as you have a `java.lang.NoSuchFieldError`, and this seems to be your issue: https://github.com/spring-cloud/spring-cloud-netflix/issues/2697

-> if you had given your `.yo-rc.json` as requested in the guidelines I could have better tested this, but I'm closing this as this seems to be your bug

**Closed by jdubois** 2018-08-22 15:31 UTC

**Comment by depzor** [comment] 2018-08-22 15:45
@jdubois I have added the .yo-rc.json

**Comment by jdubois** [comment] 2018-08-22 15:47
Thanks! And it's an old JHipster version, so you might have an old Feign release.... Let me test with the current master

**Comment by jdubois** [comment] 2018-08-22 15:50
@depzor I don't get it, `feign-httpclient` is not in the dependency tree of your application, did you add it yourself? Or maybe this changed with JHipster 5

**Comment by jdubois** [comment] 2018-08-22 15:52
I just tested with your JHispter version, `feign-httpclient` is also not there, how did you get it?

**Comment by depzor** [comment] 2018-08-22 16:01
Ah, I have found something:
I see that I have included netflix feign-gson dependency: 
<dependency>
            <groupId>com.netflix.feign</groupId>
            <artifactId>feign-gson</artifactId>
            <version>8.11.0</version>
        </dependency>

Which also has a dependency with feign-core.jar
- com.netflix.feign:feign-core:jar:8.11.0:runtime

This version seems to conflict with: 
io.github.openfeign:feign-core:jar:9.5.1:compile

I have changed my gson dependency to:
<dependency>
           <groupId>io.github.openfeign</groupId>
           <artifactId>feign-gson</artifactId>
           <version>10.0.1</version>
       </dependency>

Need to do some testing, but seems promising.
Thanks @jdubois

**Comment by jdubois** [comment] 2018-08-22 16:04
Oh OK, so that's not our fault then :-)

**Comment by depzor** [comment] 2018-08-23 10:04
Yes this fixed my problem - indeed not your fault, thanks for helping! 👍
