### ISSUE TITLE
Lazy loaded modules production failure

### ISSUE THREAD

**Issue by pawprosk** [jhipster/generator-jhipster#7926] opened 2018-07-04 09:05 UTC
##### **Overview of the issue**

In production mode (monolithic application) version 5.0.1 I found bug related to lazy loaded modules.
I have created (on newly generated application) new module (copy&paste&rename home.component) and added it to app-routing.module.ts

`RouterModule.forRoot(
            [
                ...LAYOUT_ROUTES,
                {
                    path: 'admin',
                    loadChildren: './admin/admin.module#TestappAdminModule'
                },
                {
                    path: 'test',
                    loadChildren: './test/test.module#TestappTestModule'
                }
            ],
            { useHash: true, enableTracing: DEBUG_INFO_ENABLED }`

In dev mode it works fine, in production it produces error:

> Your request cannot be processed
> Sorry, an error has occurred.
> 
> Status: Not Found (Not Found)
> Message: Not Found

As I investigated it works fine only with **one** lazy module - with other ones only in dev mode.

##### **Motivation for or Use Case**

Add more lazy modules in application to reduce time of loading.

##### **Reproduce the error**

1. Create new monolithic application
2. Add new module which will be declared as lazy module
3. Add it to app-routing.module.ts
4. compile in production mode and run 

##### **JHipster Version(s)**

Version: 5.0.1

##### **JHipster configuration**
```
generator-jhipster@5.0.1 
```
##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.example.test"
    },
    "jhipsterVersion": "5.0.1",
    "applicationType": "monolith",
    "baseName": "testapp",
    "packageName": "com.example.test",
    "packageFolder": "com/example/test",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "gradle",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "yarn",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>
<pre></pre>
</details>

##### **Environment and Tools**
openjdk version "1.8.0_111"
OpenJDK Runtime Environment (build 1.8.0_111-8u111-b14-3~14.04.1-b14)
OpenJDK 64-Bit Server VM (build 25.111-b14, mixed mode)
git version 1.9.1
node: v10.1.0
npm: 5.6.0
yarn: 1.7.0
Docker version 17.03.1-ce, build c6d412e
docker-compose version 1.14.0, build c7bdf9e

##### **Browsers and Operating System**

Chrome / FF / All

- [x ] Checking this box is mandatory (this is just to show you read everything)

**Comment by vishal423** [comment] 2018-07-04 09:37
possible duplicate of #7798

**Comment by pawprosk** [comment] 2018-07-04 10:08
Yes indeed is duplicated - sorry for duplicating - tried to find any similarities earlier but different output was described there.

**Comment by ruddell** [comment] 2018-07-04 14:37
Closing as a duplicate, thanks for reporting.

**Closed by ruddell** 2018-07-04 14:37 UTC
