### ISSUE TITLE
import JDL subgenerator updates all entity changelogdate in json files while regenerating entity

### ISSUE THREAD

**Issue by pramika** [jhipster/generator-jhipster#3675] opened 2016-06-01 13:29 UTC
##### **Overview of the issue**

import JDL subgenerator updates all entity changelogdate in **.json** files while regenerating entity(instead of only the modified entity). Because of which conflict occurs and overwrite question is asked for all the .json and <entity>.java files.

Whereas we expect the files to be overwritten only for the modified or newly added tables or entities.

This also impact the audit module where again all the .json, <entity>.java and <changelog>.xml file are updated again for all the entities.

##### **Motivation for or Use Case** 

Maintenance is becoming hectic as when the number of table increases, the number of overwrite questions are also increasing. Currently I have around 10 tables in my development. If I change one table and regenerate entity using import JDL subgenerator around 60 overwrite questions are asked even for the unaltered  tables. This includes the audit overwrite question as well. ChangeLogDate field in the .json file is getting updated irrespective of the new or modified tables due to which all the .json and <entity>.java files are updated

##### **JHipster Version(s)** 

3.4.0

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 

{
  "generator-jhipster": {
    "jhipsterVersion": "3.4.0",
    "baseName": "TEGTracker_v4",
    "packageName": "com.tcs.tegtracker",
    "packageFolder": "com/tcs/tegtracker",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "no",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": "no",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "rememberMeKey": "8af9a4f2db413e9d3629564b71520896c96e6956",
    "useSass": true,
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ]
  },
  "generator-jhipster-entity-audit": {
    "auditFramework": "custom"
  }
}

**Comment by jdubois** [comment] 2016-06-01 16:01
Very interesting. The problem is, of course, that you could have modified those tables, so it's hard to know what the correct behavior should be.

For me the current workflow is:

- Generate the first version of the app with the JDL studio
- Use the liquibase "diff" goal to update the schema

You could also add new tables by doing a new JDL file - in that case don't add the existing tables, or maybe remove them? Would that solve the problem?

This discussion should be on the JDL project at https://github.com/jhipster/jhipster-domain-language so I'm cc'ing @MathieuAA -> I'm closing this here at this is not the right place, but @pramika if you want to discuss this further can you open the discussion there?

**Closed by jdubois** 2016-06-01 16:01 UTC

**Comment by pramika** [comment] 2016-06-02 06:55
@jdubois 
Thanks for your reply. I had raised this issue in  https://github.com/jhipster/jhipster-domain-language.
Because code maintenance is getting complex with the existing behaviour. Though we can use a new jh file for regeneration the JDL subgenerator expects all the dependent entity configurations in the current jh file also. As a result almost all the files are regenerated again. This worsens especially when we have lots of custom code in the generated files.
