### ISSUE TITLE
docker development hot reload not working

### ISSUE THREAD

**Issue by minhster99** [jhipster/generator-jhipster#9553] opened 2019-04-11 15:05 UTC
##### **Overview of the issue**

When using docker development, hot reload with yarn start will not refresh the browser. If you manually refresh the browser, it will pick up the changes.

##### **Motivation for or Use Case**

This is a big hit to productivity without the automatic reload.

##### **Reproduce the error**

Follow instructions to install docker development at https://www.jhipster.tech/installation/

Exec into docker container and create an application via the jhipster command
Run ./mvnw and leave running
Exec into docker container again and now run "yarn start"

Now on your host, open up browser to http://localhost:9000
Application home page will load, edit src/main/webapp/app/home/home.component.html and change any text. The browser will not refresh. Manually refreshing it will bring up your changes.

##### **Suggest a Fix**

Looking at the browser network tab, it appears to be trying to connect to http://localhost:9060/sockjs-node/info?t=1554994594081

and getting no response. Without understanding how BrowserSync works, cant provide much more insight into this.

##### **JHipster Version(s)**

5.8.2

##### **JHipster Version(s)**

```
app@0.0.0 /home/jhipster/app
`-- generator-jhipster@5.8.2 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "5.8.2",
    "applicationType": "monolith",
    "baseName": "app",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": 
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "npm",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ]
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-8u191-b12-2ubuntu0.18.04.1-b12)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)

git version 2.17.1

node: v10.15.0

npm: 6.8.0

yeoman: 2.0.5

yarn: 1.13.0

##### **Browsers and Operating System**
Mac Mojave 10.14.4, Chrome

-   [ x] Checking this box is mandatory (this is just to show you read everything)

**Comment by ruddell** [comment] 2019-04-11 16:42
Can you try adding `-p 9060:9060` to the Docker command, in addition to the other ports?  Based on the current command, only 8080, 9000, and 3001 are exposed.

**Comment by minhster99** [comment] 2019-04-12 08:18
Sorry I forgot to mention that I tried that option, it didn't work.

**Comment by PierreBesson** [comment] 2019-04-12 08:54
@minhster99 This is a strange bug, my only guess is that the mechanism to watch files for changes doesn't work properly in docker. It seems some people have had the same issues and found a fix: https://gist.github.com/vgoma/4d33c2937447afd2fb9ae2ef781761f9

Looks like it only happens when running a docker container on Mac OS and having low default ulimits on the number of open files in the docker filesystem. So in the end it might be a "docker for mac" issue.

**Comment by pascalgrimaud** [comment] 2019-04-14 10:58
The problem is because your container Docker is inside a specific network and can't access to your local network, for refreshing your changes.

You can try to start your Docker container with network host `--network host` :

```
docker container run --name jhipster -v ~/jhipster:/home/jhipster/app -v ~/.m2:/home/jhipster/.m2 -d --network host -t jhipster/jhipster
```

I just tried this and it works fine.

I'm closing this ticket and it's not related to JHipster but related to the use of Docker.

**Closed by pascalgrimaud** 2019-04-14 10:58 UTC
Labels: docker:whale:

**Comment by PierreBesson** [comment] 2019-04-15 08:15
@pascalgrimaud It's probably not what you say it is. The docker container doesn't need access to the local network of the machine on which it refreshes the page. As everything is done by websocket/polling on the browser (remember browsersync also works from a phone or any machine on the network that can access the server on port 9000). I suspect the problem comes from the "file watching" which rely on specific libraries for mac os that would not be available from the docker container.

**Comment by PierreBesson** [comment] 2019-04-15 08:16
Anyway let's keep this issue closed but wait for @minhster99's feedback to see if my link helped him fix his problem.

**Comment by minhster99** [comment] 2019-04-15 09:53
@pascalgrimaud I tried recreating the docker container as per your instructions but I am encountering an issue when running ./mvnw inside the container afterwards

```
2019-04-15 09:38:09.088 ERROR 440 --- [  restartedMain] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'h2TCPServer' defined in class path resource [com/mycompany/myapp/config/DatabaseConfiguration.class]: Invocation of init method failed; nested exception is org.h2.jdbc.JdbcSQLException: IO Exception: "java.net.UnknownHostException: linuxkit-025000000001: linuxkit-025000000001: Name or service not known" [90028-197]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1694)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:573)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:495)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:317)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:315)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:759)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:548)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:142)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:386)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
	at com.mycompany.myapp.AppApp.main(AppApp.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49)
Caused by: org.h2.jdbc.JdbcSQLException: IO Exception: "java.net.UnknownHostException: linuxkit-025000000001: linuxkit-025000000001: Name or service not known" [90028-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.message.DbException.convert(DbException.java:299)
	at org.h2.util.NetUtils.getLocalAddress(NetUtils.java:254)
	at org.h2.server.TcpServer.getURL(TcpServer.java:198)
	at org.h2.tools.Server.start(Server.java:483)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeCustomInitMethod(AbstractAutowireCapableBeanFactory.java:1819)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1762)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1690)
	... 19 common frames omitted
Caused by: java.net.UnknownHostException: linuxkit-025000000001: linuxkit-025000000001: Name or service not known
	at java.net.InetAddress.getLocalHost(InetAddress.java:1506)
	at org.h2.util.NetUtils.getLocalAddress(NetUtils.java:252)
	... 28 common frames omitted
Caused by: java.net.UnknownHostException: linuxkit-025000000001: Name or service not known
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:929)
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1324)
	at java.net.InetAddress.getLocalHost(InetAddress.java:1501)
	... 29 common frames omitted
```

**Comment by minhster99** [comment] 2019-04-15 10:01
@PierreBesson I tried setting my ulimits to unlimited but the problem still exists.

Also I suspect it's not a file watching issue as I can see the console output from the "yarn start" command and it is picking up the changes and recompiling it successfully. Just not pushing out the changes to the browser :(
