### ISSUE TITLE
Booleans are not save against null values

### ISSUE THREAD

**Issue by amatosg** [jhipster/generator-jhipster#10891] opened 2019-12-06 18:19 UTC
##### **Overview of the issue**
If my db, for any reason, has a boolean value as `null` it will trigger a NPE.

##### **Motivation for or Use Case**
I'm getting NPEs

##### **Reproduce the error**
Set a Boolean value to null and try to access it :)

##### **Related issues**
None that I know of.

##### **Suggest a Fix**
Let's replace 
```
public Boolean isActive() {
        return active;
    }
```
with 
```
public Boolean isActive() {
        return Boolean.TRUE.equals(active);
    }
```
##### **JHipster Version(s)**
6.5.1

-   [x] Checking this box is mandatory (this is just to show you read everything)

Love JHipster? Please consider supporting our collective:
👉  https://opencollective.com/generator-jhipster/donate

**Comment by ruddell** [comment] 2019-12-06 18:48
Where does the NPE happen?  Is it when mapping the database row to the entity, or are you comparing `isActive()` to something else somewhere?

I couldn't reproduce with a default project.  I could list entities, edit, delete, and view an entity with a null Boolean field.  It may relate to your generation choices, could you please add full instructions to reproduce (a sample `.yo-rc.json` and JDL file)?

**Comment by amatosg** [comment] 2019-12-06 19:01
for instance, I have this line (it might not be optimal though):
```
result.ifPresent(partnerFaDTO -> partnerFaDTO.setAddresses(partnerFaDTO.getAddresses().stream().filter(AddressDTO::isActive).collect(Collectors.toList())));
```
if the one of the addresses has `active` as null, I get NPE. Having `Boolean.TRUE.equals(active)` will make it save on `null` values.

**Comment by amatosg** [comment] 2019-12-18 17:20
@ruddell  I've read the issue you mentioned and yes, it could mean `undefined`, but it **will** also mean NPE when accesing that value, using `Boolean.TRUE.equals(myBoolean)` will return false on null.

**Comment by vicpermir** [comment] 2019-12-20 08:32
But `null` and `false` are not the same thing, and JHipster should not make them so.

Can't you just `.filter(a -> Boolean.TRUE.equals(a.isActive())` ?

**Comment by pascalgrimaud** [comment] 2019-12-20 10:01
After reading this ticket again, I don't think we should do this, following our [Policies](https://www.jhipster.tech/policies/)
In fact, we stick to what is generated by the IDE, it's the same.

That's why I'm closing this.
But we can still discuss here if needed

**Closed by pascalgrimaud** 2019-12-20 10:01 UTC
Labels: area: enhancement :wrench:, status: needs-discussion, theme: java

**Comment by amatosg** [comment] 2020-01-04 20:01
the idea was to avoid any NPE that *will* occur on null values
