### ISSUE TITLE
[Vue] bootstrap 4 uses deprecated function abs()

### ISSUE THREAD

**Issue by vw98075** [jhipster/generator-jhipster#23770] opened 2023-10-08 21:43 UTC
##### **Overview of the issue**

This error occurs right after the client is up with "npm start".
```
Compiled with problems:
×
WARNING in ./src/main/webapp/content/scss/vendor.scss (./node_modules/css-loader/dist/cjs.js??clonedRuleSet-7.use[1]!./node_modules/postcss-loader/dist/cjs.js??clonedRuleSet-7.use[2]!./node_modules/sass-loader/dist/cjs.js??clonedRuleSet-7.use[3]!./src/main/webapp/content/scss/vendor.scss)
Module Warning (from ./node_modules/sass-loader/dist/cjs.js): Deprecation Passing percentage units to the global abs() function is deprecated. In the future, this will emit a CSS abs() function to be resolved by the browser. To preserve current behavior: math.abs(100%) To emit a CSS abs() now: abs(#{100%}) More info: https://sass-lang.com/d/abs-percent node_modules/bootstrap/scss/vendor/_rfs.scss 54:14 divide() node_modules/bootstrap/scss/mixins/_grid.scss 66:15 row-cols() node_modules/bootstrap/scss/mixins/_grid-framework.scss 43:13 @content node_modules/bootstrap/scss/mixins/_breakpoints.scss 65:5 media-breakpoint-up() node_modules/bootstrap/scss/mixins/_grid-framework.scss 32:5 make-grid-columns() node_modules/bootstrap/scss/_grid.scss 72:3 @import node_modules/bootstrap/scss/bootstrap.scss 16:9 @import src/main/webapp/content/scss/vendor.scss 10:9 root stylesheet
```

##### **JHipster Version(s)**

jhipster-release-8.0.0-beta.3

##### **JHipster configuration**
```
{
  "generator-jhipster": {
    "applicationType": "monolith",
    "authenticationType": "jwt",
    "baseName": "sample",
    "buildTool": "gradle",
    "cacheProvider": "caffeine",
    "clientFramework": "vue",
    "clientTheme": "none",
    "creationTimestamp": 1696790399863,
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "devServerPort": 9060,
    "enableGradleEnterprise": null,
    "enableHibernateCache": false,
    "enableSwaggerCodegen": true,
    "enableTranslation": false,
    "entities": ["Department", "Country", "Region", "Location", "Task", "Job", "JobHistory", "Employee"],
    "gradleEnterpriseHost": null,
    "jhipsterVersion": "8.0.0-beta.3",
    "jwtSecretKey": "MWMyYjVhYWM5N2UxY2ViMzY0OTlhNmRhMzQ0N2I2M2M5YjNmZWFkYTRhYWYzOTlmN2Y1Zjg5MWM1YTE3YzVmOTAzMzYxZDY5YzlmZDg5OTA2YTk5NGViNzZiYjQxOGM4ZjAyZGU1MzE3M2YwYzM0MzJmNjVlOTBkOTIwYjQzZGM=",
    "lastLiquibaseTimestamp": 1696790879000,
    "messageBroker": false,
    "microfrontend": false,
    "microfrontends": [],
    "nativeLanguage": "en",
    "packageName": "com.mycompany.myapp",
    "prodDatabaseType": "postgresql",
    "reactive": false,
    "searchEngine": false,
    "serverPort": null,
    "serverSideOptions": ["websocket:spring-websocket", "enableSwaggerCodegen:true"],
    "serviceDiscoveryType": false,
    "skipClient": false,
    "testFrameworks": [],
    "websocket": "spring-websocket",
    "withAdminUi": true
  }
}
```
##### **Browsers and Operating System**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by qmonmert** [comment] 2023-10-11 19:22
it is due to `bootstrap` in the file `node_modules/bootstrap/scss/vendor/_rfs.scss`

<img width="865" alt="image" src="https://github.com/jhipster/generator-jhipster/assets/9989211/315754db-ba1e-40ba-a30d-7f6bdbe62bdf">

**Comment by mshima** [comment] 2023-10-26 13:51
There are 2 workarounds https://github.com/twbs/bootstrap/issues/39028#issuecomment-1693189126 and https://github.com/twbs/bootstrap/issues/39028#issuecomment-1697758268.

But I don't think we should use them by default.

**Comment by mraible** [comment] 2023-11-03 05:31
@mshima Please merge or close at your convenience.

**Comment by mshima** [comment] 2024-03-14 17:57
Duplicate of https://github.com/jhipster/generator-jhipster/issues/23865

**Closed by mshima** 2024-03-14 17:57 UTC
Labels: theme: dependencies, theme: vue
