### ISSUE TITLE
Jhipster liquidbase data init user.csv 

### ISSUE THREAD

**Issue by direstrepo24** [jhipster/generator-jhipster#11510] opened 2020-03-26 00:37 UTC
##### **Motivation for or Use Case**

I have checked the database and it does not insert the initial user data loaded in liquidbase data.

##### **Reproduce the error**

Exception in authorize() with cause = 'NULL' and exception = 'Bad credentials'
##### **JHipster Version(s)**

```
eohelstore@0.0.1-SNAPSHOT /Users/themakers/eohel/eohelstore
└── generator-jhipster@6.8.0 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "authenticationType": "jwt",
    "cacheProvider": "hazelcast",
    "clientFramework": "angularX",
    "serverPort": "8081",
    "serviceDiscoveryType": "eureka",
    "skipUserManagement": false,
    "baseName": "eohelstore",
    "buildTool": "maven",
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "enableHibernateCache": true,
    "enableSwaggerCodegen": false,
    "enableTranslation": true,
    "jhiPrefix": "jhi",
    "languages": ["es", "en"],
    "messageBroker": false,
    "nativeLanguage": "es",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "skipClient": false,
    "testFrameworks": ["protractor"],
    "websocket": "spring-websocket",
    "applicationType": "gateway",
    "clientPackageManager": "npm",
    "clientTheme": "none",
    "creationTimestamp": 1585178820828,
    "dtoSuffix": "DTO",
    "embeddableLaunchScript": false,
    "jhipsterVersion": "6.8.0",
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "otherModules": [],
    "packageName": "com.themakers.eohelstore",
    "packageFolder": "com/themakers/eohelstore",
    "skipServer": false,
    "useSass": true,
    "entitySuffix": "",
    "blueprints": []
  },
  "entities": [
    "AbonoFactura",
    "Categoria",
    "ConfigEmpresa",
    "ElementoLista",
    "Empresa",
    "Factura",
    "FacturaDetalle",
    "FacturaEmpresa",
    "FacturaNota",
    "FacturaNotaDetalle",
    "Movimiento",
    "MovimientoDetalle",
    "NotaTipo",
    "Notification",
    "Pago",
    "PrecioProducto",
    "Producto",
    "ProductoAtributo",
    "ProductoPromocion",
    "Promocion",
    "Stock",
    "Sucursal",
    "Suscripcion",
    "Tercero",
    "TipoLista",
    "Usuario"
  ]
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity AbonoFactura {
  userId Long,
  fecha Instant required,
  codigo String required,
  valor BigDecimal required
}
entity Categoria {
  nombre String required,
  descripcion String,
  image ImageBlob,
  empresaId Long
}
entity ConfigEmpresa {
  version Integer required,
  nombre String required
}
entity ElementoLista {
  nombre String required maxlength(200),
  codigo String required maxlength(5),
  propiedades AnyBlob
}
entity Empresa {
  nit String required,
  nombre String required,
  logo String,
  numDocumento String,
  representante String,
  usuario Long required
}
/**
 * Factura sold by the Online store
 */
entity Factura {
  fecha Instant required,
  codigo String,
  sucursalId Long,
  fechaPago Instant required,
  metodoPagoId Long,
  empresaId Long required,
  userId Long,
  tipoFacturaId Long,
  valor BigDecimal required
}
entity FacturaDetalle {
  productoId Long required,
  codigoProducto String,
  nombreProducto String,
  precioUnitario BigDecimal required,
  cantidad Long required min(0)
}
entity FacturaEmpresa {
  precio BigDecimal required,
  fechaEmision Instant required,
  fechaLimite Instant required
}
entity FacturaNota {
  fechacreacion Instant required,
  motivo String
}
entity FacturaNotaDetalle {
  descripcion String required,
  cantidad Integer,
  valor BigDecimal min(0)
}
entity Movimiento {
  motivo String,
  tipoMovimientoId Long required,
  fecha Instant required,
  sucursalId Long required,
  sucursalrecibeId Long,
  empresaId Long required,
  estadoMovimientoId Long required
}
entity MovimientoDetalle {
  codigoProducto String,
  nombreProducto String,
  cantidad Long required min(0)
}
entity NotaTipo {
  nombre String required
}
entity Notification {
  date Instant required,
  details String,
  sentDate Instant required,
  format NotificationType required,
  userId Long required,
  productId Long required,
  empresaId Long required
}
entity Pago {
  fechaPago Instant required,
  correo String required,
  docIdentificacion String required,
  celular String required
}
entity PrecioProducto {
  precio BigDecimal,
  activo Boolean,
  nombre String required
}
/**
 * Product sold by the Online store
 */
entity Producto {
  nombre String required,
  descripcion String,
  precioCompra BigDecimal required min(0),
  precioVenta BigDecimal required min(0),
  codigobar String,
  imagen String,
  empresaId Long required,
  estadoId Long required,
  estadoProductoId Long required
}
entity ProductoAtributo {
  atributo String,
  valor String
}
entity ProductoPromocion {
  estado Boolean,
  fechainicio Instant required,
  fechafinal Instant required
}
entity Promocion {
  nombre String required,
  porcentaje BigDecimal min(0)
}
entity Stock {
  cantidad Long required min(0),
  sucursalId Long
}
entity Sucursal {
  nombre String required,
  direccion String required
}
entity Suscripcion {
  fechaCreacion Instant required,
  fechaInicio Instant required,
  fechaFin Instant required
}
entity Tercero {
  nombre String required,
  apellido String required,
  nit String required,
  celular String,
  email String required pattern(/^[^@\s]+@[^@\s]+\.[^@\s]+$/),
  direccion1 String required,
  direccion2 String,
  empresaId Long,
  cuidadId Long,
  paisId Long,
  tipoTerceroId Long
}
entity TipoLista {
  nombre String required,
  descripcion String maxlength(500)
}
/**
 * Usuario sold by the gateway inbuk
 */
entity Usuario {
  segundoNombre String,
  segundoApellido String,
  numDocumento String required maxlength(15),
  celular String required,
  direccion String
}
enum NotificationType {
  EMAIL,
  SMS,
  PARCEL
}

relationship OneToOne {
  Pago{factura} to FacturaEmpresa,
  Suscripcion{empresa} to Empresa,
  Usuario{user required} to User
}
relationship OneToMany {
  Factura{abonoFactura} to AbonoFactura{factura},
  Factura{facturaDetalle} to FacturaDetalle{factura},
  Movimiento{movimientoDetalle} to MovimientoDetalle{movimiento},
  Categoria{producto} to Producto{productCategoria(nombre)},
  Producto{productoAtributo} to ProductoAtributo{producto(nombre)},
  Empresa{sucursal} to Sucursal{empresa(nombre)}
}
relationship ManyToOne {
  ElementoLista{tipoLista(nombre) required} to TipoLista,
  ElementoLista{padre(nombre)} to ElementoLista,
  Empresa{cuidad(nombre) required} to ElementoLista,
  Empresa{estado(nombre) required} to ElementoLista,
  Empresa{tipoDocumento(nombre) required} to ElementoLista,
  Factura{tercero(nit)} to Tercero,
  FacturaEmpresa{metodoPago(nombre) required} to ElementoLista,
  FacturaEmpresa{estadoFactura(nombre) required} to ElementoLista,
  FacturaEmpresa{empresa(nombre)} to Empresa,
  FacturaNota{factura required} to Factura,
  FacturaNota{notaTipo(nombre) required} to NotaTipo,
  FacturaNotaDetalle{facturaNota required} to FacturaNota,
  MovimientoDetalle{producto(nombre)} to Producto,
  Pago{estado(nombre) required} to ElementoLista,
  Pago{tipoPersona(nombre) required} to ElementoLista,
  PrecioProducto{producto(nombre) required} to Producto,
  ProductoPromocion{producto(nombre) required} to Producto,
  ProductoPromocion{promocion(nombre) required} to Promocion,
  Stock{producto(nombre)} to Producto,
  Suscripcion{estado(nombre) required} to ElementoLista,
  TipoLista{padre(nombre)} to TipoLista,
  Usuario{cuidad(nombre) required} to ElementoLista,
  Usuario{categoria(nombre) required} to ElementoLista
}

dto AbonoFactura, Categoria, ConfigEmpresa, ElementoLista, Empresa, Factura, FacturaDetalle, FacturaEmpresa, FacturaNota, FacturaNotaDetalle, Movimiento, MovimientoDetalle, NotaTipo, Notification, Pago, PrecioProducto, Producto, ProductoAtributo, ProductoPromocion, Promocion, Stock, Sucursal, Suscripcion, Tercero, TipoLista, Usuario with mapstruct
paginate AbonoFactura, Categoria, ConfigEmpresa, ElementoLista, Empresa, Factura, FacturaDetalle, FacturaEmpresa, FacturaNota, FacturaNotaDetalle, Movimiento, MovimientoDetalle, NotaTipo, Notification, Pago, PrecioProducto, Producto, ProductoAtributo, ProductoPromocion, Promocion, Stock, Sucursal, Suscripcion, Tercero, TipoLista, Usuario with pagination
service AbonoFactura, Categoria, ConfigEmpresa, ElementoLista, Empresa, Factura, FacturaDetalle, FacturaEmpresa, FacturaNota, FacturaNotaDetalle, Movimiento, MovimientoDetalle, NotaTipo, Notification, Pago, PrecioProducto, Producto, ProductoAtributo, ProductoPromocion, Promocion, Stock, Sucursal, Suscripcion, Tercero, TipoLista, Usuario with serviceClass
microservice AbonoFactura, Factura, FacturaDetalle, FacturaNota, FacturaNotaDetalle, NotaTipo, Tercero with facturamicroservicio
microservice Categoria, Movimiento, MovimientoDetalle, PrecioProducto, Producto, ProductoAtributo, ProductoPromocion, Promocion, Stock with inventariomicroservicio
microservice Notification with notification
filter AbonoFactura, Categoria, ConfigEmpresa, ElementoLista, Empresa, Factura, FacturaDetalle, FacturaEmpresa, FacturaNota, FacturaNotaDetalle, Movimiento, MovimientoDetalle, NotaTipo, Notification, Pago, PrecioProducto, Producto, ProductoAtributo, ProductoPromocion, Promocion, Stock, Sucursal, Suscripcion, Tercero, TipoLista, Usuario
clientRootFolder FacturaNota, FacturaNotaDetalle, NotaTipo with facturamicroservicio
clientRootFolder PrecioProducto, ProductoPromocion, Promocion with inventariomicroservicio

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.6+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.6+10, mixed mode)

git version 2.21.1 (Apple Git-122.3)

node: v12.14.1

npm: 6.14.3

yeoman: 3.1.1

yarn: 1.21.1

Docker version 19.03.5, build 633a0ea

docker-compose version 1.25.4, build 8d51620a

##### **Browsers and Operating System**

-   [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment] 2020-06-19 09:00
I manage to reproduce the issue, with this error:

```
2020-06-19 10:41:24.911 ERROR 18530 --- [helstore-task-1] i.g.j.c.liquibase.AsyncSpringLiquibase   : Liquibase could not start correctly, your database is NOT ready: Migration failed for change set config/liquibase/changelog/20200619090100_added_entity_Usuario.xml::20200619090100-1-data::jhipster:
     Reason: liquibase.exception.DatabaseException: java.sql.BatchUpdateException: Batch entry 2 INSERT INTO public.usuario(id, segundo_nombre, segundo_apellido, num_documento, celular, direccion, user_id, cuidad_id, categoria_id) VALUES(3, 'Intelligent', 'Borders program solid state', 'open-source Aut', 'Metrics PCI Handcrafted Rubber Pants', 'morph', 2, 3, 3) was aborted: ERROR: duplicate key value violates unique constraint "ux_usuario_user_id"
  Détail : Key (user_id)=(2) already exists.  Call getNextException to see other errors in the batch.

liquibase.exception.MigrationFailedException: Migration failed for change set config/liquibase/changelog/20200619090100_added_entity_Usuario.xml::20200619090100-1-data::jhipster:
     Reason: liquibase.exception.DatabaseException: java.sql.BatchUpdateException: Batch entry 2 INSERT INTO public.usuario(id, segundo_nombre, segundo_apellido, num_documento, celular, direccion, user_id, cuidad_id, categoria_id) VALUES(3, 'Intelligent', 'Borders program solid state', 'open-source Aut', 'Metrics PCI Handcrafted Rubber Pants', 'morph', 2, 3, 3) was aborted: ERROR: duplicate key value violates unique constraint "ux_usuario_user_id"
```

The reason is your relationship:
```
relationship OneToOne {
  Usuario{user required} to User
}
```

It will generate a bad fake data:

```
1;Buckinghamshire Internal;SDD multimedia Soft;synthesize;Steel;invoice primary;1;1;1
2;maroon Internal Papua New Guinea;Path transmitting matrices;neural supply-c;Rustic Handmade;Bedfordshire user-centric;2;2;2
3;Intelligent;Borders program solid state;open-source Aut;Metrics PCI Handcrafted Rubber Pants;morph;2;3;3
```

The 3rd line is incorrect because of the one to one.

In conclusion, and there are already some issues on this in the past, not sure we can do something in the generator as the problem comes from directly in your relationship.
What I can suggest is to :
- use skipFakeData flag during generation
- edit manually your fake data (it's pretty fast)

For now, let's close this.
Hope it will help you.

**Closed by pascalgrimaud** 2020-06-19 09:00 UTC
Labels: area: needs-reproduction, theme: database
