### ISSUE TITLE
Place of DTO Mapping

### ISSUE THREAD

**Issue by adkhaila** [jhipster/generator-jhipster#3637] opened 2016-05-23 04:37 UTC
Hello
Why DTO mapping is not done just after the service layer , and just before the controllers layer.
This would allegiate the controllers from dealing with entities , and make service layer retrun DTOs and accept DTOs 
Looking forward for your explanation
Good Work

**Comment by deepu105** [comment] 2016-05-23 05:12
Read https://github.com/jhipster/generator-jhipster/issues/3175 and related PR
closing as duplicate of https://github.com/jhipster/generator-jhipster/issues/3175

**Closed by deepu105** 2016-05-23 05:12 UTC
Labels: question
