### ISSUE TITLE
Object Versioning and Comparison for Auditing

### ISSUE THREAD

**Issue by myspivey** [jhipster/generator-jhipster#1762] opened 2015-07-24 00:05 UTC
Not sure if I am the only one interested in this, but looking at a solution such as http://javers.org/ to track object changes and push those to Audit events. This is useful say if an admin changes a users role or some other property. Knowing who made that change, when, and what exactly they changed. This idea extends to any entity created during the process. If something like this is already implemented I apologize.

**Comment by myspivey** [comment] 2015-07-24 00:09
The two key features that make it look like a good fit for Jhipster:
http://javers.org/documentation/spring-integration/#auto-audit-aspect
http://javers.org/documentation/repository-configuration/#choose-javers-repository

**Comment by gzsombor** [comment] 2015-07-24 08:12
Seems interesting.

**Comment by atomfrede** [comment] 2015-07-24 20:46
Yes, looks quite nice.

**Comment by myspivey** [comment] 2015-07-24 21:00
Seems like their is interest, I've started poking around at implementation however am rather new to Java. Anyone with more experience able to offer their insights as to if this will be a good fit and complexity of implementation. I will report back anything I come up with and submit PR's as best I can.

**Comment by deepu105** [comment] 2015-07-25 04:56
I think if this is compatibel with Spring data then it will be a very good addition to JH
@myspivey thank you I was looking for such a solution and was fiddling with spring data audit features to get it done, This seems very interesting, does it support Oracle DB?

**Comment by deepu105** [comment] 2015-07-25 04:57
OK i missed it, it does support `MongoDB, H2, PostgreSQL, MySQL, Oracle and Microsoft SQL Server` just cassandra is missing

**Comment by deepu105** [comment] 2015-07-25 05:04
@jdubois @atomfrede @gzsombor @andidev @gmarziou guys do you think this will be a good addition in JH? I have this requirement in my current project so im gonna go ahead and try this in my app anyway so if you guys think its good I can collaborate with @myspivey to bring this into JH

**Comment by deepu105** [comment] 2015-07-25 05:06
even better @myspivey  if you already have something thats working with jhipster generated app plz share the repo ill use that :joy:

**Comment by andidev** [comment] 2015-07-25 06:03
:+1: 
Sounds great if it's possible to use! Guess it would be an option in the entity generator and maybe by the default the user would be Audited?

**Comment by gzsombor** [comment] 2015-07-25 07:49
I've tried to add to one of my jhipster app, and it was very easy. I've only one problem, https://github.com/javers/javers/issues/180 - will see, if the source of the problem is me, or in javers :wink: Otherwise, I think, this could be a great addition.

**Comment by jdubois** [comment] 2015-07-25 07:56
I understand that everybody looks very positive about javers, and I didn't have a close look at it yet, my main concerns are:

- I don't want to add yet another library to the project, I'm worried this is getting too heavy and complex
- I don't know Javers or its team, and it only has 90 stars: what is this project going to do in the future? I don't want to tie JHipster to a project that could die, become proprietary, etc... Once again, I don't know them, so I might be completely wrong, but I already had this issue with jOOQ: everybody wanted to use it, it was great, and then I found the [pricing page](http://www.jooq.org/download/) -> this would have been a huge mistake (no Oracle support for us, for example)

**Comment by deepu105** [comment] 2015-07-25 10:24
@jdubois it seems like Apache licensed, im gonna use it anyways coz it seems better than my triggers+spring data audit approach i was trying for my app, def saves time for me :smile:  coz my users are asking for granular audit details

@gzsombor did you use it to show the audit changes in a UI? if so will you be able to share your approach :grimacing:

**Comment by myspivey** [comment] 2015-07-25 16:51
If someone wants to share the java side (that bits taken me some time), I
can tackle the UI and share the implementation.

**Comment by bartoszwalacik** [comment] 2015-07-25 21:49
hi guys, I'm a JaVers committer, JaVers is OSS and won't become proprietary, it's rather lightway library. I've seen https://github.com/javers/javers/issues/180 and i'am going to fix it (if it is a bug).

**Comment by deepu105** [comment] 2015-07-26 04:42
@myspivey i implemented it in a sample app and its working fine i did a custom ui as well to fetch changelogs

**Comment by deepu105** [comment] 2015-07-26 05:11
![image](https://cloud.githubusercontent.com/assets/1107223/8892648/c1603c4a-3397-11e5-8415-e662605f3869.png)

**Comment by deepu105** [comment] 2015-07-26 05:12
so if @jdubois and other core dev members agree i can provide a PR

**Comment by deepu105** [comment] 2015-07-27 05:20
@bartoszwalacik I'm facing issues with Javers if I enable CGLIB proxying in spring, I have opened a ticket https://github.com/javers/javers/issues/181

**Comment by gzsombor** [comment] 2015-07-27 18:20
Have you added the HibernateUnproxyObjectAccessHook to the Javers bean ? Without it caused some issues for me, because Javers access the fields directly, without calling the getters - which is proxied by hibernate.

**Comment by bartoszwalacik** [comment] 2015-07-27 21:18
@gzsombor you can configure Javers to use getters, see http://javers.org/documentation/domain-configuration/index.html#property-mapping-style. Think it should be aligned with your Hibernate mapping style (getters vs fields)

@deepu105 ok but I need a failing test which reproduces the problem

**Comment by bartoszwalacik** [comment] 2015-07-30 21:59
I've solved https://github.com/javers/javers/issues/181
This is not a Javers issue but a Spring bug, fixed in Spring 4.2.0.RC2

**Comment by sdoxsee** [comment] 2015-08-02 12:24
Haven't looked much into javers yet. How does it compare to envers? Javers sounds promising.  Raw envers is not clean to work with and spring-data-envers is a buggy and stagnant project (see https://github.com/spring-projects/spring-data-envers/issues/33)

**Comment by jdubois** [comment] 2015-08-02 12:29
Sorry, I didn't understand it was like Envers. In that case, this is used in very specific situations, and I would not recommend it for everyone.

**Comment by jdubois** [comment] 2015-08-08 07:41
Hi all,
So I've had a closer look and this is indeed like Envers.
This is clearly not something we should have by default. I've already seen a couple of failed projets because people did not understand what Envers was meant to do, and were abusing it (not an Envers issue, but a people issue... As often with Hibernate)
The use-case for this is very specific, we can't have this by default for everyone.

**Closed by jdubois** 2015-08-08 07:41 UTC
Labels: enhancement

**Comment by myspivey** [comment] 2015-08-10 17:16
Couldn't the work around be that we set it up so its not abused or optional? Right now the default auditing abilities really do nothing, and are not useful in most terms. Seems defeatist to just close this saying it does not benefit the community when there seems to be a pretty big draw to expanding the current auditing system to actually be useful. That does not seem very use-case specific from my perspective. At the least we could look at the PR from @deepu105 and see the impacts it has and then make a decision?

**Comment by jdubois** [comment] 2015-08-10 19:09
The current auditing features are only for security:

- they work well as far as I know
- they are provided to everyone as we have a strong focus on security (I think most people will be happy to have them) and they are for a very limited scope
- they are very easy to remove and are standard in Spring

Using Javers for our entities is something entierly different.

**Comment by deepu105** [comment] 2016-01-03 05:52
guys take a look at the Jhipster module https://github.com/deepu105/generator-jhipster-entity-audit 
this should be available to users from the next Jhipster release

**Comment by deepu105** [comment] 2016-01-03 05:53
@myspivey @bartoszwalacik if required you can create a Javers module as well

**Comment by bartoszwalacik** [comment] 2016-01-03 19:52
@deepu105 @myspivey I'm not into jhipster but I can help if someone who knows jhipster wants to create Javers module

**Comment by atomfrede** [comment] 2016-01-03 20:00
A javers module would be cool. I'll try to setup javers and see how to make it into a module.

**Comment by bartoszwalacik** [comment] 2016-01-05 06:35
Ok @atomfrede, new jhipster issue for javers module?

**Comment by atomfrede** [comment] 2016-01-05 17:04
I think we could create a new repository and keep track of the progress outside the main generator project.

**Comment by deepu105** [comment] 2016-01-06 01:00
@atomfrede if you are building this module why not collaborate on the
entity auditing module and make javers an option there so we can ask user
if they want hibernate audit or javers audit, so that we can reuse the UI
etc. What do you think?

I had already setup javers once, i didn't use it as it couldn't audit data
loaded outside of javers otherwise its a good option

**Comment by atomfrede** [comment] 2016-01-06 05:09
Hi,

I didn't think about it but that is even better 😀 I'll delete my repo an
open an issue.
Am 06.01.2016 2:00 vorm. schrieb "Deepu k Sasidharan" <
notifications@github.com>:

**Comment by deepu105** [comment] 2016-01-06 06:03
@atomfrede yes plz PR and improve as you see fit :)
