### ISSUE TITLE
"Error: Cannot find module 'yeoman-generator'" during yo:upgrade from 3.5.1 to 3.11.0

### ISSUE THREAD

**Issue by lrkwz** [jhipster/generator-jhipster#4544] opened 2016-11-24 22:28 UTC
I've bumped in

```
Regenerating app with jhipster 3.11.0...
module.js:471
    throw err;
    ^

Error: Cannot find module 'yeoman-generator'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/generator-jhipster/generators/app/index.js:3:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
Error jhipster:upgrade 
```

Executing this sequence of commands:

    mkdir ~/jhipster
    docker run --name jhipster -v ~/jhipster:/home/jhipster/app -v ~/.m2:/home/jhipster/.m2 -p 8080:8080 -p 3000:3000 -p 3001:3001 -d -t jhipster/jhipster:v3.5.1
    docker exec -it jhipster yo jhipster

accept all defaults and generate a jhipster app, then clean up container

    docker stop jhipster
    docker rm -fv jhipster

and upgrade

    docker run --name jhipster -v ~/jhipster:/home/jhipster/app -v ~/.m2:/home/jhipster/.m2 -p 8080:8080 -p 3000:3000 -p 3001:3001 -d -t jhipster/jhipster:v3.11.0
    docker exec -it jhipster git config --global user.email 'username@example.com'
    docker exec -it jhipster git config --global user.name 'username'
    docker exec -it jhipster yo jhipster:upgrade

**Comment by jdubois** [comment] 2016-11-25 22:00
Maybe that's because you used the Docker image, that's a use case I didn't think of. Could you try with a "normal" installation?

**Comment by lrkwz** [comment] 2016-11-25 23:08
What did you think the docker image for? I think it is extremely useful exactly for testing different versions without bothering with dependency install when you go back a forward between different version.

Anyhow I've tested with v3.10.0 and everything runs smoothly so it is probably just matter of going step-by-step from 3.5 to 3.11 without missing versions.

**Comment by jdubois** [comment] 2016-11-25 23:17
Yes you are right, but doing an upgrade is a bit different, as behind-the-scenes it gets the original JHipster release that was used for the project, and tries to do a merge.
I'm not sure that's the issue, but at least that's not something I have thought of.

**Comment by pascalgrimaud** [comment] 2016-11-26 11:37
@lrkwz : can you try to npm link generator before upgrading ? I suspect that when using yo jhipster:upgrade, you use the one old (v3.5.1) inside node_modules instead of the global v3.11.0. And there is a lot of issues since the beginning with this sub generator so I'm not sure the v3.5.1 works fine.

```
docker run --name jhipster -v ~/jhipster:/home/jhipster/app -v ~/.m2:/home/jhipster/.m2 -p 8080:8080 -p 3000:3000 -p 3001:3001 -d -t jhipster/jhipster:v3.11.0
docker exec -it jhipster git config --global user.email 'username@example.com'
docker exec -it jhipster git config --global user.name 'username'
docker exec -it jhipster npm link generator-jhipster
docker exec -it jhipster yo jhipster:upgrade
```

**Comment by pascalgrimaud** [comment] 2016-11-26 11:41
I reproduce your issue here:
- script: https://github.com/pascalgrimaud/jhipster-travis-tester/blob/ca0caa7dd49f63558c83588cd2112eb3bb0c8bcc/app/test.sh
- travis log: https://travis-ci.org/pascalgrimaud/jhipster-travis-tester/builds/178953883

Fixing by adding npm link generator:
- script: https://github.com/pascalgrimaud/jhipster-travis-tester/blob/2d4eab3abf988b4cc4182039cc97cd54ea8eb3dd/app/test.sh
- travis log: https://travis-ci.org/pascalgrimaud/jhipster-travis-tester/builds/179024529

**Comment by jdubois** [comment] 2016-11-28 09:28
Does this need a permanent fix, or is the solution from @pascalgrimaud enough? I don't know if we should close this

**Comment by pascalgrimaud** [comment] 2016-11-28 09:41
Let's close this.
@lrkwz : don't hesitate to comment or ping me if you still have the issue

**Closed by pascalgrimaud** 2016-11-28 09:41 UTC
