### ISSUE TITLE
Can't Produce an Executable JAR

### ISSUE THREAD

**Issue by brunoborges** [jhipster/generator-jhipster#8172] opened 2018-08-27 22:01 UTC
##### **Overview of the issue**
Can't get a working executable JAR file (as in `.jar`) out of a Maven JHipster project.

##### **Motivation for or Use Case**
Due to requirements from other tools, including custom Maven plugins, we need the output of the Maven project to be an executable JAR file, not an executable WAR file.

##### **Reproduce the error**
Get an executable JAR by renaming the WAR file:
1. Create a monolithic dummy JHipster application
1. Build the application `mvn package`
1. Rename the `target/<app>.war` file to `target/<app>.jar`
1. Run it with `java -jar target/<app>.jar`
1. Application starts, but `curl -I http://localhost:8080` gives 404

Get an executable JAR by changing Maven packaging to `jar`:
1. Create a monolithic dummy JHipster application
1. Build the application `mvn package`
1. Change `<packaging>` inside `pom.xml` to `jar`
1. Run the JAR file with `java -jar target/<app>.jar`
1. Visit `http://localhost:8080` in your browser.
1. Application does not render properly (missing static content).

##### **Related issues**
See this StackOverflow thread: https://stackoverflow.com/questions/52046249/spring-boots-jhipster-war-artifact-renamed-to-jar-wont-run/52047100#52047100

See this Twitter thread: https://twitter.com/brunoborges/status/1034169585564495872

##### **JHipster Version(s)**

```
foobar@0.0.0 /Users/bruno/work/jhipster/jhipster-apps/foobar
└── generator-jhipster@5.2.1

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp"
    },
    "jhipsterVersion": "5.2.1",
    "applicationType": "monolith",
    "baseName": "foobar",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "no",
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "yarn",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_172"
Java(TM) SE Runtime Environment (build 1.8.0_172-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.172-b11, mixed mode)

git version 2.18.0

node: v10.9.0

npm: 6.2.0

yeoman: 2.0.2

yarn: 1.9.4

Docker version 18.06.0-ce, build 0ffa825

docker-compose version 1.22.0, build f46880f

Congratulations, JHipster execution is complete!

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

None

##### **Browsers and Operating System**

MacOS High Sierra 10.13.6

```sh
▶ uname -a
Darwin Brunos-MacBook-Pro.local 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64
```

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment] 2018-08-28 16:02
As the documentation is up on https://www.jhipster.tech/azure/ I think you find a work around, and as this wasn't asked by anyone else yet, I'm closing this.

I'm totally OK to modify this for JHipster 6: at some point we'll need to only do executable JAR files, and drop the old War support. But that would be a major change, so we can only do this in a major release, and it's not urgent at the moment.

**Closed by jdubois** 2018-08-28 16:02 UTC

**Comment by deepu105** [comment] 2018-08-29 09:30
@jdubois based on the discussion in twitter I think we can try to generate both jar and war so that its not a breaking change. Its easy to do with gradle but i'm not sure about maven, may be we could use the plugin suggested by @brunoborges for maven.

**Comment by jdubois** [comment] 2018-08-29 09:32
Yes I agree we should do both at the moment. And in the future, maybe just do the executable JAR files.

Not sure anybody is willing to work on this for Maven, so that's a big issue. The problem is that not a lot of people have this need.

**Comment by atomfrede** [comment] 2018-08-29 09:38
I have the code ready for gradle. Can do a PR to start with

**Comment by jdubois** [comment] 2018-08-29 09:41
thanks @atomfrede - we of course need to have both build system at the same level, but we should start by one anyway: let's do it with Gradle!
