### ISSUE TITLE
Lack of inheritance is show stopper

### ISSUE THREAD

**Issue by The-Crocop** [jhipster/generator-jhipster#2383] opened 2015-11-22 18:39 UTC
Yo jhispters,

I am really intrigued by the jhipster project and we want to implement our next project with jhipster. However because inheritance is not supported we might not be able to use jhipster. So the Problem is this: 
 we have an abstract  class subject which is the parent of  Person and multiple child classes of Person like Employee, Customer, Interpreter. Subject would be our mapped superClass. 
I know the documentation states that Composition should be favored over inheritance, however this is a clear "is-a relationship" and in my opinion should be modeled as one. So do you have any ideas how to go about implementing the model in jhipster. I have read a few posts, but they seemed to require a lot of manual changes. 

http://stackoverflow.com/questions/33334746/using-inheritance-on-jhipster-entities
http://stackoverflow.com/questions/31775243/extending-jhipster-user

I have read those posts but neither of them is really a satisfying solution

Best regards

a futute hipster

**Comment by jdubois** [comment] 2015-11-23 10:13
We don't provide inheritance for various reasons:
- It's going to have an impact on the performance on your app, depending on your inheritance strategy, and that's the main reason I would avoid it myself
- It would be really annoying to set up and configure in JHipster (both for us and for the 95% of people who don't want inheritance), when you could achieve it from normal entities with a simple refactoring

I'm closing this as this is not a bug, and not really a feature request: if that's really a show-stopper for you, then I'm really sorry but it's not in my personal roadmap.

**Comment by jdubois** [comment] 2015-11-23 10:13
By the way, this kind of question should go to StackOverflow, and not to the bug tracker.

**Closed by jdubois** 2015-11-23 10:13 UTC

**Comment by The-Crocop** [comment] 2015-11-23 13:33
Thank you for your answer. 
I will see if I can work around this.
By the way great project keep it going ;-)

**Comment by cmoine** [comment] 2018-03-09 11:20
I am in the same situation. The "performance" argument totally makes sense.
However, couldn't we use interfaces to address this feature ? The generators is very valuable for this purpose:
- Generate interfaces with getter & setters
- Generate class (with Entity annotation) with the getter & setter implementation

I agree it has huge impact on JDL editors (the one online, the one in IDEs), but the change in generators should be pretty quick I think. I think it would worth it anyway.

**Comment by khaoulaBenAtitallah** [comment] 2019-02-15 10:21
bonjour
est ce que je peut utilise jhiphser avec heritage !!!!

**Comment by jdubois** [comment] 2019-02-15 10:25
@kaidohallik English please, you should follow the project guidelines and CoC.

You can do inheritance but you need to refactor the code yourself. Once again, I would not recommend this with Hibernate, but if you have good use case then you probably know there are 3 ways to do inheritance, so that's up to you to refactor your code (and that's very easy) to use the best solution according to your data and business needs (and that's the hard part).
