### ISSUE TITLE
jhipster upgrade stuck at command prompt

### ISSUE THREAD

**Issue by kalumet** [jhipster/generator-jhipster#8465] opened 2018-10-04 21:00 UTC
##### **Overview of the issue**

I tried 2 times with the same result:
The upgrade process stucks at a command prompt, when the application is rebuilt:

```
√ Cleaned up project directory
Regenerating application with JHipster 5.4.1...
......\.bin
     info ".....\.bin/jhipster" --with-entities --force --skip-install
Using JHipster version installed globally
Running default command
Executing jhipster:app
Options: withEntities: true, force: true, skipInstall: true, from-cli: true, with-entities: true, skip-install: true
```
Then comes the following question, where I have no possibility to make the selection. There is no reaction on keyboard input.

```
Welcome to JHipster v5.4.1
Application files will be generated in folder: D:\dev\hallOfFame
 _______________________________________________________________________________________________________________

  Documentation for creating an application is at https://www.jhipster.tech/creating-an-app/
  If you find JHipster useful, consider sponsoring the project at https://opencollective.com/generator-jhipster
 _______________________________________________________________________________________________________________

? May JHipster anonymously report usage statistics to improve the tool over time
? (Y/n)
```

##### **Motivation for or Use Case**

I'm unable to make an upgrade of the jhipster version. I wanted to do it, as I was unable to build the application for prod as I get an error with webpack, following this:
https://stackoverflow.com/questions/49132552/webpack-failure-during-jhipster-prod-package

##### **Reproduce the error**

I had version 5.2.0 installed.
finished development and wanted to go into production
building with the -Pprod flag resulted in an error in webpack (see link above for a similar issue i had).
I thought upgrading jhipster would also help discarding this issue.
I tried 2 times the upgrade process with the same result.

##### **Related issues**

I haven't seen any ...

##### **JHipster Version(s)**

5.2.0 -> 5.4.1

##### **JHipster configuration**

```
##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**


<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "******",
      "nativeLanguage": "de"
    },
    "jhipsterVersion": "5.2.0",
    "applicationType": "monolith",
    "baseName": "*****",
    "packageName": "*****",
    "packageFolder": "*****",
    "serverPort": "8080",
    "authenticationType": "session",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "gradle",
    "enableSwaggerCodegen": false,
    "rememberMeKey": "*****",
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "yarn",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "de",
    "languages": [
      "de",
      "en",
      "fr"
    ],
    "appsFolders": [
      "******"
    ],
    "directoryPath": "../",
    "monitoring": "elk",
    "consoleOptions": [
      "curator"
    ],
    "jwtSecretKey": "******"
  }
}
</pre>
</details>
```

##### **Browsers and Operating System**

Windows 10
Chrome (latest)
Using Docker.

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by deepu105** [comment] 2018-10-05 06:46
This was an issue in the older version. It has been fixed now. For now just
answer the question and proceed. It won't happen once the version is updated

**Comment by jdubois** [comment] 2018-10-05 08:03
Yes indeed, that should be fixed in the new releases (otherwise please don't hesitate to comment).

Have a look in the older tickets, this is already explained (and that's why I'm closing this as "duplicate"), but the trick is to create a new project with the generator and answer the question (yes or no), then you won't have the question again (well, if you say "no", you'll get it again after doing 100 generations!)

**Closed by jdubois** 2018-10-05 08:03 UTC

**Comment by iwan933** [comment] 2018-12-06 09:40
Exact same issue occurs for me in 5.7.0. Unable to upgrade. (Windows 7 x64)

**Comment by gmarziou** [comment] 2018-12-06 15:14
@iwan933 in Windows 7 there is another reason why generator could be stuck: it's the notifier in system icon tray which blocks until you click on the icon.

**Comment by asgh** [comment] 2019-04-05 16:25
Exact same issue in version 5.8.2, on Windows 10.

@jdubois  Please reopen this.

**Comment by pascalgrimaud** [comment] 2019-04-05 16:54
@asgh : plz, open a new ticket with all details, your old version, your new version, your config etc... so we can try to reproduce.

**Comment by asgh** [comment] 2019-04-05 19:17
@pascalgrimaud I no longer have the problem because I used the workaround of creating a dummy project just in order to answer that question.

However I can tell you that I was going from 4.14.0 to 5.8.2, and the problem is identical to what is described in the first comment in this issue.

So it was not fixed in the new releases.

**Comment by jivicari** [comment] 2019-04-17 14:59
Hello, I have de same problem, going from 4.13.3 to 5.8.2 in ubuntu with jdk 1.8

.yo-rc.json

`{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.miproyecto",
      "nativeLanguage": "es"
    },
    "jhipsterVersion": "4.13.3",
    "baseName": "miproyecto",
    "packageName": "com.miproyecto",
    "packageFolder": "com/miproyecto",
    "serverPort": "8080",
    "authenticationType": "session",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "oracle",
    "prodDatabaseType": "oracle",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": false,
    "rememberMeKey": "27046b107bde273bc6abc6be4e72af85bb10ca38",
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "es",
    "languages": [
      "es"
    ]
  }
}`

thanks for the help.
