### ISSUE TITLE
*.war.original file not running on tomcat and *.war is also no running using java -jar *.war command.

### ISSUE THREAD

**Issue by hassnainali** [jhipster/generator-jhipster#6330] opened 2017-09-08 08:36 UTC
##### **Overview of the issue**
*.war.original file not running on tomcat and *.war is also no running using java -jar *.war command.
when I run jHipster using mvnw the server start just fine but what I'm trying to do is building the war file using **mvnw package -Pprod -DskipTests**, to deploy in tomcat when I start my tomcat it gives the error and the tomcat is unable to run my war file. I've read other similar issues and followed their solution but it did not work. [https://github.com/jhipster/generator-jhipster/issues/5607](#5607) , I do not want to run jHipster repository.

Note: I'm new to jHipster may be I missing some steps. 

##### **Motivation for or Use Case**

Because Non of the issue discussed of deploying war file on any server. 

##### **Reproduce the error**

1. generate jhipster project using **yo jhipster**
2. molithical application using postgres
3. build the war file using --> mvnw package -Pprod -DskipTests
4. deploy *.war.original on tomcat or  java -jar *.war in the target folder 
##### **Related issues**

 [https://github.com/jhipster/generator-jhipster/issues/5607](#5607) 

##### **Error LOG**

:: JHipster ?  :: Running Spring Boot 1.5.6.RELEASE ::
:: https://jhipster.github.io ::

2017-09-08 13:06:37.536 ERROR 6428 --- [           main] o.s.boot.SpringApplication               : Application startup failed

java.lang.IllegalStateException: Could not locate PropertySource and the fail fast property is set, failing
        at org.springframework.cloud.config.client.ConfigServicePropertySourceLocator.locate(ConfigServicePropertySourceLocator.java:132)
        at org.springframework.cloud.bootstrap.config.PropertySourceBootstrapConfiguration.initialize(PropertySourceBootstrapConfiguration.java:93)
        at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:567)
        at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:338)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:301)
        at com.abs.PostgresApp.main(PostgresApp.java:68)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.WarLauncher.main(WarLauncher.java:59)
Caused by: org.springframework.web.client.ResourceAccessException: I/O error on GET request for "http://localhost:8761/config/postgresApp/prod/master": Connection refused
: connect; nested exception is java.net.ConnectException: Connection refused: connect
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:666)
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:613)
        at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:531)
        at org.springframework.cloud.config.client.ConfigServicePropertySourceLocator.getRemoteEnvironment(ConfigServicePropertySourceLocator.java:172)
        at org.springframework.cloud.config.client.ConfigServicePropertySourceLocator.locate(ConfigServicePropertySourceLocator.java:93)
        ... 13 common frames omitted
Caused by: java.net.ConnectException: Connection refused: connect
        at java.net.DualStackPlainSocketImpl.connect0(Native Method)
        at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
        at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
        at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
        at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
        at java.net.PlainSocketImpl.connect(Unknown Source)
        at java.net.SocksSocketImpl.connect(Unknown Source)
        at java.net.Socket.connect(Unknown Source)
        at java.net.Socket.connect(Unknown Source)
        at sun.net.NetworkClient.doConnect(Unknown Source)
        at sun.net.www.http.HttpClient.openServer(Unknown Source)
        at sun.net.www.http.HttpClient.openServer(Unknown Source)
        at sun.net.www.http.HttpClient.<init>(Unknown Source)
        at sun.net.www.http.HttpClient.New(Unknown Source)
        at sun.net.www.http.HttpClient.New(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection.connect(Unknown Source)
        at org.springframework.http.client.SimpleBufferingClientHttpRequest.executeInternal(SimpleBufferingClientHttpRequest.java:78)
        at org.springframework.http.client.AbstractBufferingClientHttpRequest.executeInternal(AbstractBufferingClientHttpRequest.java:48)
        at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:53)
        at org.springframework.http.client.InterceptingClientHttpRequest$InterceptingRequestExecution.execute(InterceptingClientHttpRequest.java:99)
        at org.springframework.cloud.config.client.ConfigServicePropertySourceLocator$GenericRequestHeaderInterceptor.intercept(ConfigServicePropertySourceLocator.java:23
7)
        at org.springframework.http.client.InterceptingClientHttpRequest$InterceptingRequestExecution.execute(InterceptingClientHttpRequest.java:86)
        at org.springframework.http.client.InterceptingClientHttpRequest.executeInternal(InterceptingClientHttpRequest.java:70)
        at org.springframework.http.client.AbstractBufferingClientHttpRequest.executeInternal(AbstractBufferingClientHttpRequest.java:48)
        at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:53)
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:652)
        ... 17 common frames omitted

##### **JHipster Version(s)**
 generator-jhipster@4.7.0

##### **JHipster configuration**

Using JHipster version installed locally in current project's node_modules
Executing jhipster:info
Options:
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
postgres-app@0.0.0 D:\Hassnain\projects\JHipster\postgresApp
`-- generator-jhipster@4.7.0

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.abs",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "4.7.0",
    "baseName": "postgresApp",
    "packageName": "com.abs",
    "packageFolder": "com/abs",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": true,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "ja",
      "ko"
    ]
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster`

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Student (student) {
  name String required minlength(3) maxlength(20) pattern([a-zA-Z][a-zA-Z ]*),
  address String required minlength(10) maxlength(80),
  phoneNo String
}
entity Teacher (teacher) {
  name String required minlength(3) maxlength(20) pattern([a-zA-Z][a-zA-Z ]*),
  address String required minlength(10) maxlength(80),
  phoneNo String
}

paginate Student with pagination
service Student with serviceImpl
paginate Teacher with pagination
service Teacher with serviceImpl

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

git version 2.14.1.windows.1

node: v6.11.2

npm: 5.3.0

bower: 1.8.0

gulp:
[13:03:24] CLI version 1.4.0

yeoman: 2.0.0

yarn: 0.27.5

Execution complete

##### **Browsers and Operating System**

Windows 7 + tomcat 8.0.28
- [*] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment] 2017-09-08 08:42
Have a look at your error message: it is trying to connect to a Spring Cloud Config server (at `http://localhost:8761/config/postgresApp/prod/master`) to get its configuration, so I guess you have configured your app to use the JHipster Registry? This looks strange, because I can't see the `serviceDiscoveryType` property in your `.yo-rc.json`.

Anyway:
- This is working in `dev` mode as the registry isn't required in dev mode
- In `prod` mode it is mandatory, so if the application can't find it it won't start

You will have more information on http://www.jhipster.tech/jhipster-registry/

I'm closing this as it's not a bug, just a misconfiguration - unless you didn't configure this (and this is the weird part in your `.yo-rc.json`), and in this case I'd be happy to understand how you got that configuration, so please add comments.

**Closed by jdubois** 2017-09-08 08:42 UTC

**Comment by hassnainali** [comment] 2017-09-08 08:57
@jdubois thank you for replying. Actually, it had serviceDiscoveryType property in the .yo-rc.json file but I removed it because I was following the solution of bug 5607.

**Comment by jdubois** [comment] 2017-09-08 09:06
Oh then we have a good explanation, thanks @hassnainali . BTW, you can easily disable the service discovery, it's a standard Spring Boot property.

**Comment by hassnainali** [comment] 2017-09-08 10:16
@jdubois Thank you for your response. Problem is fixed by regenerated monolithic application and not managing through jHipster Registry. :+1:

**Comment by hassnainali** [comment] 2017-09-09 16:45
My bad! It also works with managing through jHipster Register.

**Comment by jdubois** [comment] 2017-09-10 14:39
@hassnainali no problem, I know this isn't easy at the beginning! (you are not the only one!)

**Comment by hassnainali** [comment] 2017-09-12 16:22
:+1:
