### ISSUE TITLE
Authorization problems with roles in AngularJs

### ISSUE THREAD

**Issue by Chinokao** [jhipster/generator-jhipster#1977] opened 2015-09-04 18:35 UTC
I think there is a problem in isInAnyRole Principal Service function, I found that it calls to the same service isInRole function which happens to return a promise if user is authenticated. The problem is that when calling to that function from isInAnyRole without .then() it always returns true. I was looking to the sample project and in that line it doest'n call to isInRole function so it works perfectly.
Here the diferences:
My project (Release 2.19.0)
```javascript
isInRole: function (role) {
    if (!_authenticated) {
        return false;
    }
    return this.identity().then(function (_id) {
        return _id.roles && _id.roles.indexOf(role) !== -1;
        }, function () {
            return false;
        });
},
isInAnyRole: function (roles) {
    if (!_authenticated || !_identity || !_identity.roles) {
        return false;
    }
    for (var i = 0; i < roles.length; i++) {
        if (this.isInRole(roles[i])) { // this is always true in my project
            return true;
        }
    }
    return false;
}
```
Sample project: 
```javascript
isInRole: function (role) {
    if (!_authenticated) {
        return false;
    }
    return this.identity().then(function(_id) {
        return _id.roles && _id.roles.indexOf(role) !== -1;
        }, function(err){
            return false;
        });
},
isInAnyRole: function (roles) {
    if (!_authenticated || !_identity || !_identity.roles) {
        return false;
    }
    for (var i = 0; i < roles.length; i++) {
        if (_identity.roles.indexOf(roles[i]) !== -1) { // this is only true when user role is in data.roles
            return true;
        }
    }
    return false;
}
```
The problem is that authorize function from Auth Service uses isAnyRole function and so hasAnyRole directive, so both function and directive don't work (I can't hide menus with has-any-role neither redirect to accessdenied state when user is not authorized). I fixed it using the sample isInAnyRole function, but I just wanted to tell you about this.

**Comment by jdubois** [comment] 2015-09-06 10:28
Thanks for the feedback.

We just merged https://github.com/jhipster/generator-jhipster/pull/1708 and it looks like a duplicate -> that's why I'm closing this, but can you have a look and re-open or send a comment if you disagree?

**Closed by jdubois** 2015-09-06 10:28 UTC

**Comment by Slapshot9** [comment] 2015-09-14 10:39
I think, this is not a duplicate. #1708 just ensures, that _identity has a NULL-check before accessing _identity.roles.

This issue describes, that the generated isInAnyRole-function call this.isInRole(roles[i]) for every role in the array, but this.isInRole(roles[i]) is always true, as it returns a promise.

But as Chinokao pointed out, this bug is fixed within the sample app, where the roles of the _identity are checked directly withing the for-loop.

**Comment by Chinokao** [comment] 2015-09-15 16:38
Yes, I think they are different issues. I fixed it in my code like the sample app but generated code keeps using isInRole function.

**Comment by pmadridb** [comment] 2015-10-22 21:03
I had the same problem in my project. This issue shouldn't be closed.

**Comment by jdubois** [comment] 2015-10-23 07:40
@pmadridb I'm sorry but the issue isn't clear to me here -> could you open up a new issue, explaining in detail what problem you have?

**Comment by Chinokao** [comment] 2015-10-23 10:34
Hello, 

The problem is that isInAnyRole doesn't work in some situations, because when it uses isInRole it doesn't wait for the promise to finish. 
I fixed creating a isInAnyRolePromise function so we can wait for the identity to check the roles, and changing IsInAnyRole function to work without IsInRole function. 

This is how the functions work for me:

```javascript
        function isInRoleFn(role) {
            if (!_authenticated) {
                return false;
            }
            return pExports.identity().then(function (_id) {
                return _id.roles && _id.roles.indexOf(role) !== -1;
            }, function () {
                return false;
            });
        }

        function isInAnyRoleFn(roles) {
            if (!_authenticated || !_identity || !_identity.roles) {
                return false;
            }

            for (var i = 0; i < roles.length; i++) {
                if (_identity.roles.indexOf(roles[i]) !== -1) {
                    return true;
                }
            }
            return false;
        }

        function isInAnyRolePromiseFn(roles) {

            return new Promise(promiseFn);

            function promiseFn(resolve, reject) {

                pExports.identity().then(resolveIdentityIdFn, resolveIdentityFn);

                function resolveIdentityIdFn(_id) {
                    var found = false;
                    var end = false;
                    var counter = 0;
                    while (!found && !end) {
                        var role = roles[counter];
                        if (_id.roles && _id.roles.indexOf(role) !== -1) {
                            found = true;
                        } else if (counter === roles.length) {
                            end = true;
                        }
                        counter++;
                    }
                   found ? resolve(true) : resolve(false);
                }

                function resolveIdentityFn() {
                    resolve(false);
                }
            }
        }
```

And this is how I use it in the $stateProvider:

```javascript
$stateProvider
            .state('chemist', {
                parent: 'users',
                url: '/chemist',
                data: {
                    roles: [COMMON.ROLE_ADMIN, COMMON.ROLE_CHEMIST,
                                    COMMON.ROLE_CHEMIST_DISTRIBUTOR]
                },
                views: {
                    'content@': {
                        templateUrl: 'scripts/app/users/chemist/chemist.html',
                        controller: 'ChemistController',
                        controllerAs: 'chemistCtrl'
                    }
                },
                resolve: {
                    mainTranslatePartialLoader: ['$translate', '$translatePartialLoader',
                        function ($translate, $translatePartialLoader) {
                            $translatePartialLoader.addPart('chemist');
                            return $translate.refresh();
                        }],
                    chemistPrepService: ['chemistService',
                        function (chemistService) {
                            return Principal.isInAnyRolePromise([COMMON.ROLE_CHEMIST,
                                    COMMON.ROLE_CHEMIST_DISTRIBUTOR]).then(responseFn);
                            
                            function responseFn(response) {
                               return response ? chemistService.findByUser() : chemistService.countAllChemists();
                            }
                        }]
                }
            })
```
Hope it helps

**Comment by pmadridb** [comment] 2015-10-23 12:17
I won't raise a new issue since I see that it has been already fixed in the latest code base: https://github.com/jhipster/generator-jhipster/blob/master/app/templates/src/main/webapp/scripts/components/auth/_principal.service.js
