### ISSUE TITLE
JHipster 4.0.7 with Gradle+Kafka fails with "object is not an instance of declaring class"

### ISSUE THREAD

**Issue by uboznikov** [jhipster/generator-jhipster#5350] opened 2017-03-03 09:50 UTC
##### **Overview of the issue**

```
[  restartedMain] c.l.m.gateway.config.WebConfigurer       : Web application fully configured
[  restartedMain] c.l.m.g.c.c.CassandraConfiguration       : Configuring Cassandra session
[  restartedMain] c.l.m.gateway.config.CacheConfiguration  : Starting HazelcastCacheManager
[  restartedMain] i.g.j.c.apidoc.SwaggerConfiguration      : Starting Swagger
[  restartedMain] i.g.j.c.apidoc.SwaggerConfiguration      : Started Swagger in 5 ms
[  restartedMain] c.n.c.sources.URLConfigurationSource     : No URLs will be polled as dynamic configuration sources.
[  restartedMain] c.l.gateway.GatewayApp      : The following profiles are active: swagger,dev
[  restartedMain] c.l.gateway.GatewayApp      : Started GatewayApp in 0.55 seconds (JVM running for 16.427)
[  restartedMain] ationConfigEmbeddedWebApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.context.ApplicationContextException: Failed to start bean 'outputBindingLifecycle'; nested exception is java.lang.IllegalArgumentException: object is not an instance of declaring class
[  restartedMain] c.n.c.sources.URLConfigurationSource     : No URLs will be polled as dynamic configuration sources.
[  restartedMain] com.netflix.discovery.DiscoveryClient    : Saw local status change event StatusChangeEvent [timestamp=1488532023212, current=DOWN, previous=STARTING]
[  restartedMain] com.netflix.discovery.DiscoveryClient    : Shutting down DiscoveryClient ...
[  restartedMain] com.netflix.discovery.DiscoveryClient    : Unregistering ...
[nfoReplicator-0] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_GATEWAY/gateway:9d7acdc18183881572cd3ff78020ea56: registering service...
[  restartedMain] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_GATEWAY/gateway:9d7acdc18183881572cd3ff78020ea56 - deregister  status: 404
[  restartedMain] com.netflix.discovery.DiscoveryClient    : Completed shut down of DiscoveryClient
[nfoReplicator-0] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_GATEWAY/gateway:9d7acdc18183881572cd3ff78020ea56 - registration status: 204
[  restartedMain] com.hazelcast.core.LifecycleService      : [127.0.0.1]:13781 [dev] [3.7.5] [127.0.0.1]:13781 is SHUTTING_DOWN
[  restartedMain] com.hazelcast.instance.Node              : [127.0.0.1]:13781 [dev] [3.7.5] Shutting down connection manager...
[  restartedMain] com.hazelcast.instance.Node              : [127.0.0.1]:13781 [dev] [3.7.5] Shutting down node engine...
[  restartedMain] com.hazelcast.instance.NodeExtension     : [127.0.0.1]:13781 [dev] [3.7.5] Destroying node NodeExtension.
[  restartedMain] com.hazelcast.instance.Node              : [127.0.0.1]:13781 [dev] [3.7.5] Hazelcast Shutdown is completed in 51 ms.
[  restartedMain] com.hazelcast.core.LifecycleService      : [127.0.0.1]:13781 [dev] [3.7.5] [127.0.0.1]:13781 is SHUTDOWN
[  restartedMain] c.l.m.gateway.config.CacheConfiguration  : Closing Cache Manager
[  restartedMain] o.s.boot.SpringApplication               : Application startup failed

org.springframework.context.ApplicationContextException: Failed to start bean 'outputBindingLifecycle'; nested exception is java.lang.IllegalArgumentException: object is not an instance of declaring class
        at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:176)
        at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:51)
        at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:346)
        at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:149)
        at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:112)
        at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:879)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:144)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:545)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:737)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:370)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:314)
        at com.gateway.GatewayApp.main(GatewayApp.java:74)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49)
Caused by: java.lang.IllegalArgumentException: object is not an instance of declaring class
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.cloud.stream.binder.kafka.admin.Kafka10AdminUtilsOperation.errorCodeFromTopicMetadata(Kafka10AdminUtilsOperation.java:82)
        at org.springframework.cloud.stream.binder.kafka.KafkaMessageChannelBinder.createTopicAndPartitions(KafkaMessageChannelBinder.java:443)
        at org.springframework.cloud.stream.binder.kafka.KafkaMessageChannelBinder.createTopicsIfAutoCreateEnabledAndAdminUtilsPresent(KafkaMessageChannelBinder.java:421)
        at org.springframework.cloud.stream.binder.kafka.KafkaMessageChannelBinder.createProducerDestinationIfNecessary(KafkaMessageChannelBinder.java:229)
        at org.springframework.cloud.stream.binder.kafka.KafkaMessageChannelBinder.createProducerDestinationIfNecessary(KafkaMessageChannelBinder.java:93)
        at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.doBindProducer(AbstractMessageChannelBinder.java:101)
        at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.doBindProducer(AbstractMessageChannelBinder.java:55)
        at org.springframework.cloud.stream.binder.AbstractBinder.bindProducer(AbstractBinder.java:150)
        at org.springframework.cloud.stream.binding.BindingService.bindProducer(BindingService.java:125)
        at org.springframework.cloud.stream.binding.BindableProxyFactory.bindOutputs(BindableProxyFactory.java:225)
        at org.springframework.cloud.stream.binding.OutputBindingLifecycle.start(OutputBindingLifecycle.java:57)
        at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:173)
        ... 17 common frames omitted
```

##### **Motivation for or Use Case**

My gateway and microservice would not start, be it standalone or in Docker. Both setups throw the same error. I am using Cassandra, Kafka, and JHipster Registry. My standalone setup (run via `./gradlew`) accesses services created via Docker Compose.

As a side test I also created a new gateway from scratch and ran the whole thing in Docker Compose and it too threw the same error.

##### **Reproduce the error**

Upgrade to 4.0.7 or create one from scratch. I am only using microservices.

##### **Related issues**

I am not sure...

##### **Suggest a Fix**

The erring line is this: `Environment env = app.run(args).getEnvironment();`.

It might be related to a configuration property being set to a wrong type but I can't tell which is which.

##### **JHipster Version(s)**

4.0.7

##### **JHipster configuration**

```
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

gateway@0.0.0 /home/...
└── generator-jhipster@4.0.7 

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

yaml
{
  "generator-jhipster": {
    "jhipsterVersion": "4.0.7",
    "baseName": "gateway",
    "packageName": "com.gateway",
    "packageFolder": "com/gateway",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "no",
    "clusteredHttpSession": "hazelcast",
    "websocket": "spring-websocket",
    "databaseType": "cassandra",
    "devDatabaseType": "cassandra",
    "prodDatabaseType": "cassandra",
    "searchEngine": false,
    "messageBroker": "kafka",
    "serviceDiscoveryType": "eureka",
    "buildTool": "gradle",
    "enableSocialSignIn": false,
    "jwtSecretKey": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "gateway",
    "testFrameworks": [
      "gatling",
      "cucumber",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "fr",
      "tr"
    ],
    "clientFramework": "angular2"
  }
}

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

ls: no such file or directory: .jhipster/*.json

##### **Browsers and Operating System**

java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

git version 2.9.3

node: v6.10.0

npm: 3.10.10

yeoman: 1.8.5

yarn: 0.21.3

Docker version 17.03.0-ce, build 60ccb22

docker-compose version 1.10.1, build b252738
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

None.

##### **Browsers and Operating System**

Firefox 51.0.1 (64-bit), Ubuntu 16.10 64-bit

- [x ] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment] 2017-03-03 14:50
Can you try removing the `src/main/resources/bootstrap-dev.yml`? We modified that part in the last release

**Comment by uboznikov** [comment] 2017-03-05 14:21
Hi @jdubois yes the newly created gateway didn't have that file, but still the same error. I also tried removing that file from my own project, but still the same error.

**Comment by jdubois** [comment] 2017-03-05 21:58
From you stacktrace, it looks like your error comes from Kafka - I had a quick look at your gateway, you have a very uncommon set of options, so maybe you found a combinaison that doesn't work? I'm having a quick look.

**Comment by jdubois** [comment] 2017-03-05 22:31
OK found your issue: https://github.com/spring-cloud/spring-cloud-stream/issues/789

Disabling Kafka makes it work, then of course we'll need to upgrade the library.

**Comment by jdubois** [comment] 2017-03-05 22:40
More information at http://stackoverflow.com/questions/41986162/failed-to-start-bean-inputbindinglifecycle-when-using-spring-boot1-5-1-and-sp

I'm updating the ticket title to make it more clear

**Comment by uboznikov** [comment] 2017-03-06 09:29
Thanks for the find, I have temporarily fixed the issue by upgrading the following:

`spring_cloud_version = Dalston.BUILD-SNAPSHOT`
`spring-cloud-stream-binder-kafka = 1.2.0.M2`
`wurstmeister/kafka = 0.10.1.1`

**Comment by jdubois** [comment] 2017-03-06 15:21
Great, but unfortunately we can't point to a SNAPSHOT release...

**Comment by uboznikov** [comment] 2017-03-06 15:31
Yes, this is just a temporary fix.

**Comment by jdubois** [comment] 2017-03-09 12:32
Very strange: I totally agree you have an error here, but it only occurs with our Gradle build, not the Maven build. I'm pretty sure it should fail with Maven too, as we also got the same (wrong) library versions, but strangely it doesn't.

**Comment by uboznikov** [comment] 2017-03-10 16:00
You have reproduced it with Gradle, then?

**Comment by jdubois** [comment] 2017-03-10 16:02
Yes, I reproduce it with Gradle, but not with Maven.
Please note I just started the project with Maven -> it starts up OK, but maybe it can't send/receive messages.
Anyway there's a lib issue here, we should have exactly the same result with Maven and Gradle.

**Comment by jdubois** [comment] 2017-03-22 06:16
With the new JHipster 4.1.0 we upgrade the Spring Cloud release, so this should be tested again

**Comment by kuhnroyal** [comment] 2017-03-22 11:32
I just ran into this with 4.1.0 and gradle.

**Comment by anklavez** [comment] 2017-03-22 12:46
I also have the same issue with version 4.1.0, after applying manual fix for Dalston.BUILD-SNAPSHOT I have an issue with routing to Gateway app (o.s.c.n.z.w.ZuulHandlerMapping:104 - No routes found from RouteLocator).

**Comment by JuanyongZhang** [comment] 2017-03-22 14:07
The Dalston.RC1 version works for me.

```
buildscript {
	ext {
		springBootVersion = '1.5.2.RELEASE'
	}
	repositories {
		mavenCentral()
		maven { url "https://repo.spring.io/snapshot" }
		maven { url "https://repo.spring.io/milestone" }
	}
	dependencies {
		classpath("org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}")
		classpath("org.sonarsource.scanner.gradle:sonarqube-gradle-plugin:2.2.1")
	}
}
...
dependencyManagement {
	imports {
		mavenBom "org.springframework.cloud:spring-cloud-dependencies:Dalston.RC1"
	}
}
```

**Comment by JuanyongZhang** [comment] 2017-03-22 14:08
but the Kafka dependencies will dis-color the log

`	compile("org.springframework.cloud:spring-cloud-starter-stream-kafka")
`

**Comment by Isabek** [comment] 2017-03-26 13:01
I have faced this error, also. I was using gradle, Jhipster 4.1.1. Then I changed gradle to maven and problem is gone.

**Comment by tezcane** [comment] 2017-03-26 23:11
Just want to share my suspicion from #4420

The fix was only made to _pom.xml (maven only, not gradle).  I believe it had something to do with Gatling + Kafka incompatibility and was fixed by re-arranging the pom.xml imports.  After I switched to Maven, I could get Gatling + Kafka working.

**Comment by pascalgrimaud** [comment] 2017-03-27 06:34
I had a look on this few days ago and didn't find the solution. What I have seen, is some difference in the dependency tree between maven and gradle -> it shouldn't be difference...

Maybe a quick solution. Can you try to modify your `build.gradle` file by forcing and use this version 1.2.0.RC1 ?

```groovy
    compile "org.springframework.cloud:spring-cloud-stream:1.2.0.RC1"
    compile "org.springframework.cloud:spring-cloud-stream-binder-kafka:1.2.0.RC1"
```

**Comment by Isabek** [comment] 2017-03-27 07:10
I have changed spring-kafka to
```
compile group: 'org.springframework.kafka', name: 'spring-kafka', version: '1.0.5.RELEASE'
```

spring-kafka was using `org.apache.kafka:kafka_2.11:jar:0.10.1.1` and other packages were using `org.apache.kafka:kafka_2.11:jar:0.9.0.1`. 

Now, spring-kafka uses `org.apache.kafka:kafka_2.11:jar:0.9.0.1`. Everything is okay.

**Comment by jdubois** [comment] 2017-03-27 07:44
Thanks everyone! So we have a different dependency graph between Gradle and Maven, which shouldn't happen, and which is going to be hard to solve... The solution from @Isabek looks good enough to me, shouldn't we just do that? @Isabek would you like to do a PR?

**Comment by atomfrede** [comment] 2017-03-27 12:14
Is there something we can do automate comparison of dependency trees? I did that often to align versions between gradle and maven (obviously I miss some combinations).

**Comment by Isabek** [comment] 2017-03-27 14:43
@jdubois okay will create PR.

**Comment by Isabek** [comment] 2017-03-27 14:46
@atomfrede for gradle you can use [Project Report Plugin](https://docs.gradle.org/current/userguide/userguide_single.html#project_reports_plugin), for maven [Maven Dependency Plugin](https://maven.apache.org/plugins/maven-dependency-plugin/index.html).

**Comment by atomfrede** [comment] 2017-03-27 15:20
@Isabek Yeha, It would be cool to have them compared during build phase (but I guess that would be to much for travis as the build already takes a long time). Maybe I try to write a script or somehow semi automate it when I find time.

**Closed** 2017-03-28 05:35 UTC
Labels: bug

**Comment by uboznikov** [comment] 2017-04-18 02:23
Works perfectly now, thanks all.
