### ISSUE TITLE
Deploying to Cloud Foundry using MySQL/ClearDB

### ISSUE THREAD

**Issue by jonathanba** [jhipster/generator-jhipster#8269] opened 2018-09-10 10:44 UTC
![jhcf](https://user-images.githubusercontent.com/23099115/45292458-91266580-b4f5-11e8-822b-32008992ae81.PNG)

##### **Overview of the issue**

I created a simple JH Application to test CloundFoundry (Pivotal Web Services) and used MySQL as a DB. Unfortunately, elephantsql is offered instead of ClearDB. I had to write cleardb there.

##### **Motivation for or Use Case**

It would be better to offer either a list of all database services or just appropriate services. Also, change the database plan related to the chosen database service.

##### **JHipster Version(s)**

5.0.2

##### **JHipster configuration**

`-- generator-jhipster@5.0.2

```


##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**


<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp"
    },
    "jhipsterVersion": "5.0.2",
    "applicationType": "monolith",
    "baseName": "Example",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "yarn",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}
</pre>
</details>


##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>


##### **Environment and Tools**

java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

node: v8.11.3

npm: 6.4.1

yeoman: 2.0.3

yarn: 1.3.2

Docker version 17.12.0-ce, build c97c6d6

docker-compose version 1.18.0, build 8dd22a96

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

no entities

##### **Browsers and Operating System**

Win 10 64 bit

- [x] Checking this box is mandatory (this is just to show you read everything)

<!-- Love JHipster? Please consider supporting our collective:
👉  https://opencollective.com/generator-jhipster/donate -->

**Comment by jdubois** [comment] 2018-09-10 11:04
Yes I totally agree, but that's hard to do. The issue is that unlike other clouds like Heroku or GCP, that list depends on your installation: there's the public PCF instance, but also IBM Bluemix, Atos Canopy, and companies having their own private instances.

So we can't know the list in advance... It just depends on your instance! For the record, we just put ElephantSQL because they gave us some free instances to test. So we offered them to by the default choice in exchange.

Then we could use the CloudFoundry API, but I'm not sure if that's possible or easy to do. And I guess this is quite a lot of work, for very little people using the sub-generator (our stats show very few people use CloudFoundry compared to the other clouds).

**Comment by deepu105** [comment] 2018-09-10 17:14
Agree with Julien. Though its a small annoyance it not a blocker since you can write actual value there. Closing as wontfix unless you have a nice solution

**Closed by deepu105** 2018-09-10 17:14 UTC
