### ISSUE TITLE
Many To Many recursive calls in test createEntity 

### ISSUE THREAD

**Issue by yelhouti** [jhipster/generator-jhipster#7696] opened 2018-05-28 16:20 UTC
##### **Overview of the issue**

When you generate the code that has a many to many relationship to the same class (ex: parent, child) 
the test has class createEntity that will class it self and test will get stack.

##### **Reproduce the error**

use A JDL like this:

```
entity TaskType {
    name String required
}

relationship ManyToMany {
    TaskType{parent(name)} to TaskType{child(name)}
}
```

##### **Suggest a Fix**

check when generating that the class is different, also check if it doesn't happen for manyToOne/OneToMany (don't think so)

##### **JHipster Version(s)**

4.14.4 and I understand if it's not fixed until the 2.x like the others

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

```
{
    "fluentMethods": true,
    "relationships": [
        {
            "relationshipType": "many-to-many",
            "otherEntityRelationshipName": "child",
            "relationshipName": "parent",
            "otherEntityName": "taskType",
            "otherEntityField": "name",
            "ownerSide": true
        }
    ],
    "fields": [
        {
            "fieldName": "name",
            "fieldType": "String",
            "fieldValidateRules": [
                "required"
            ]
        }
    ],
    "changelogDate": "20180519154932",
    "entityTableName": "task_type",
    "dto": "mapstruct",
    "pagination": "no",
    "service": "serviceImpl",
    "jpaMetamodelFiltering": true,
    "microserviceName": "processing"
}
```

yo-rc.json

```
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.test",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "4.14.3",
    "baseName": "processman",
    "packageName": "com.test",
    "packageFolder": "com/test",
    "serverPort": "8083",
    "authenticationType": "oauth2",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "gradle",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "seceretkey",
    "enableTranslation": true,
    "applicationType": "microservice",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "nativeLanguage": "en",
    "languages": [
      "en",
      "fr"
    ],
    "clientPackageManager": "npm",
    "skipClient": true,
    "skipUserManagement": true
  }
}
```

##### **Browsers and Operating System**

OSX
- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by ruddell** [comment] 2018-05-28 17:05
Could you add your project's `.yo-rc.json` please?  I couldn't reproduce with just your entity JDL

**Comment by jdubois** [comment] 2018-05-29 08:14
I'm closing this as it can't be reproduced -> @yelhouti please follow the guidelines and add your `.yo-rc.json` file and all required information, so we can reproduce.

**Comment by yelhouti** [comment] 2018-05-29 09:16
Sorry guys for .yo-rc I don’t think it’s relevant. I think that the problem appears when my manyToMany is required (I know doesn’t make too much sense this is why I removed it from the post) could you try that?

**Comment by jdubois** [comment] 2018-05-29 09:19
I'm sorry @yelhouti but I'm just not testing if I don't have the full information. This already happened like 10 times before, and I know it's not your fault, but each time the missing information was in fact important and we lost time testing.

**Comment by yelhouti** [comment] 2018-05-30 01:31
@jdubois no need to justify I totally understand, I wasn't near my laptop (answered using my phone), any way here is the yo-rc.json but like I says earlier I think it's because of the required.
thanks for the great lib and keep up the great work :)

**Comment by ruddell** [comment] 2018-05-30 03:10
@yelhouti It happens when the relationship is required, that's why I couldn't reproduce with the JDL (the relationship is missing the `required` keyword).  My main question is if this is a valid use-case?  You can't create entities through the Angular frontend when it requires a relationship to another of the same entity, because none of that entity exist.  Maybe we shouldn't allow required relationships to the same entity?

We could handle the test for ManyToMany by setting the relationship to itself instead of creating a new instance of the same entity.  Not sure how to handle it for OneToMany relationships which also has this issue.

**Comment by yelhouti** [comment] 2018-05-31 02:19
indeed @ruddell I think that for the OneToMany use case having the FK required is not possible as there will always be one with null. for the manyToMany the required doesn't serve any purpose as the table contains only two columns which are primary keys and therefore required.
Therefore since there is no valid use case for required when pointing to the same relashionship, we can either decide to not to handle the use case but someone could make the same mistake and waste debugging, or just prevent the generation and print a warning at the end.

**Closed** 2018-07-01 08:53 UTC
