### ISSUE TITLE
JHipster 7 beta.0 - mvn compile fails for mysql w/ reactive

### ISSUE THREAD

**Issue by saturnism** [jhipster/generator-jhipster#13480] opened 2021-01-12 19:22 UTC
##### **Overview of the issue**

app generated using mysql + reactive fails to compile.

##### **Motivation for or Use Case**

preparing for a demo

##### **Reproduce the error**

1. take https://github.com/mraible/choose-jhipster/blob/main/apps.jdl
2. for blog, change database from neo4j to mysql
3. generate the applications
4. cd blog && mvn compile

##### **JHipster Version(s)**

JHipster 7.0.0.beta.0

##### **JHipster configuration**

```
application {
  config {
    applicationType gateway
    baseName gateway
    clientFramework vue
    reactive true
    packageName com.okta.developer.gateway
    authenticationType oauth2
    prodDatabaseType postgresql
    serviceDiscoveryType eureka
    testFrameworks [cypress]
  }
  entities Blog, Post, Tag, Product
}

application {
  config {
    applicationType microservice
    baseName blog
    reactive true
    packageName com.okta.developer.blog
    authenticationType oauth2
    prodDatabaseType mysql
    serverPort 8081,
    serviceDiscoveryType eureka
  }
  entities Blog, Post, Tag
}

application {
  config {
    applicationType microservice
    baseName store
    reactive true
    packageName com.okta.developer.store
    authenticationType oauth2
    databaseType mongodb
    devDatabaseType mongodb
    prodDatabaseType mongodb
    enableHibernateCache false
    serverPort 8082
    serviceDiscoveryType eureka
  }
  entities Product
}

entity Blog {
  name String required minlength(3)
  handle String required minlength(2)
}

entity Post {
  title String required
  content TextBlob required
  date Instant required
}

entity Tag {
  name String required minlength(2)
}

entity Product {
  title String required
  price BigDecimal required min(0)
  image ImageBlob
}

relationship ManyToOne {
  Blog{user(login)} to User
  Post{blog(name)} to Blog
}

relationship ManyToMany {
  Post{tag(name)} to Tag{post}
}

paginate Post, Tag with infinite-scroll
paginate Product with pagination

microservice Product with store
microservice Blog, Post, Tag with blog

deployment {
  deploymentType docker-compose
  appsFolders [gateway, blog, store]
  dockerRepositoryName "mraible"
}

```

##### **Browsers and Operating System**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by mraible** [comment] 2021-01-12 19:24
Duplicate of https://github.com/jhipster/generator-jhipster/issues/13467.

**Closed by mraible** 2021-01-12 19:24 UTC
Labels: area: triage, theme: undefined
