### ISSUE TITLE
Microservices gateway issue: APPLICATION FAILED TO START

### ISSUE THREAD

**Issue by TonyLuo** [jhipster/generator-jhipster#8195] opened 2018-08-31 13:03 UTC
##### **Overview of the issue**
I generate the microservice gateway using the jhipster 5.2.1, change nothing but only the database configuration.
 After that compile the war file by running mvn clean -Pprod,swagger,no-liquibase package, 
and try to run java -jar gateway-0.0.1-SNAPSHOT.war, but the gateway failed to start

##### **Related issues**

> [root@VM_0_7_centos app]# java -jar gateway-0.0.1-SNAPSHOT.war
> 
>         ██╗ ██╗   ██╗ ████████╗ ███████╗   ██████╗ ████████╗ ████████╗ ███████╗
>         ██║ ██║   ██║ ╚══██╔══╝ ██╔═══██╗ ██╔════╝ ╚══██╔══╝ ██╔═════╝ ██╔═══██╗
>         ██║ ████████║    ██║    ███████╔╝ ╚█████╗     ██║    ██████╗   ███████╔╝
>   ██╗   ██║ ██╔═══██║    ██║    ██╔════╝   ╚═══██╗    ██║    ██╔═══╝   ██╔══██║
>   ╚██████╔╝ ██║   ██║ ████████╗ ██║       ██████╔╝    ██║    ████████╗ ██║  ╚██╗
>    ╚═════╝  ╚═╝   ╚═╝ ╚═══════╝ ╚═╝       ╚═════╝     ╚═╝    ╚═══════╝ ╚═╝   ╚═╝
> 
> :: JHipster 🤓  :: Running Spring Boot 2.0.4.RELEASE ::
> :: https://www.jhipster.tech ::
> 
> 2018-08-31 20:59:14.804  INFO 7069 --- [           main] com.zykj.gateway.GatewayApp              : The following profiles are active: prod,swagger,no-liquibase
> 2018-08-31 20:59:17.775  WARN 7069 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.springframework.scheduling.annotation.ProxyAsyncConfiguration': Unsatisfied dependency expressed through method 'setConfigurers' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'asyncConfiguration' defined in URL [jar:file:/data/app/gateway-0.0.1-SNAPSHOT.war!/WEB-INF/classes!/com/zykj/gateway/config/AsyncConfiguration.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.boot.context.properties.ConfigurationPropertiesBindException: Error creating bean with name 'io.github.jhipster.config.JHipsterProperties': Could not bind properties to 'JHipsterProperties' : prefix=jhipster, ignoreInvalidFields=false, ignoreUnknownFields=false; nested exception is org.springframework.boot.context.properties.bind.BindException: Failed to bind properties under 'jhipster' to io.github.jhipster.config.JHipsterProperties
> 2018-08-31 20:59:17.799 ERROR 7069 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   : 
> 
> ***************************
> APPLICATION FAILED TO START
> ***************************
> 
> Description:
> 
> Binding to target [Bindable@56febdc type = io.github.jhipster.config.JHipsterProperties, value = 'provided', annotations = array<Annotation>[@org.springframework.boot.context.properties.ConfigurationProperties(ignoreInvalidFields=false, ignoreUnknownFields=false, value=jhipster, prefix=jhipster)]] failed:
> 
>     Property: jhipster.logging.spectator-metrics.enabled
>     Value: false
>     Origin: "jhipster.logging.spectator-metrics.enabled" from property source "bootstrapProperties"
>     Reason: The elements [jhipster.logging.spectator-metrics.enabled,jhipster.metrics.graphite.enabled,jhipster.metrics.graphite.host,jhipster.metrics.graphite.port,jhipster.metrics.graphite.prefix,jhipster.metrics.prometheus.enabled,jhipster.metrics.prometheus.endpoint] were left unbound.
>     Property: jhipster.metrics.graphite.enabled
>     Value: false
>     Origin: "jhipster.metrics.graphite.enabled" from property source "bootstrapProperties"
>     Reason: The elements [jhipster.logging.spectator-metrics.enabled,jhipster.metrics.graphite.enabled,jhipster.metrics.graphite.host,jhipster.metrics.graphite.port,jhipster.metrics.graphite.prefix,jhipster.metrics.prometheus.enabled,jhipster.metrics.prometheus.endpoint] were left unbound.
>     Property: jhipster.metrics.graphite.host
>     Value: localhost
>     Origin: "jhipster.metrics.graphite.host" from property source "bootstrapProperties"
>     Reason: The elements [jhipster.logging.spectator-metrics.enabled,jhipster.metrics.graphite.enabled,jhipster.metrics.graphite.host,jhipster.metrics.graphite.port,jhipster.metrics.graphite.prefix,jhipster.metrics.prometheus.enabled,jhipster.metrics.prometheus.endpoint] were left unbound.
>     Property: jhipster.metrics.graphite.port
>     Value: 2003
>     Origin: "jhipster.metrics.graphite.port" from property source "bootstrapProperties"
>     Reason: The elements [jhipster.logging.spectator-metrics.enabled,jhipster.metrics.graphite.enabled,jhipster.metrics.graphite.host,jhipster.metrics.graphite.port,jhipster.metrics.graphite.prefix,jhipster.metrics.prometheus.enabled,jhipster.metrics.prometheus.endpoint] were left unbound.
>     Property: jhipster.metrics.graphite.prefix
>     Value: gateway
>     Origin: "jhipster.metrics.graphite.prefix" from property source "bootstrapProperties"
>     Reason: The elements [jhipster.logging.spectator-metrics.enabled,jhipster.metrics.graphite.enabled,jhipster.metrics.graphite.host,jhipster.metrics.graphite.port,jhipster.metrics.graphite.prefix,jhipster.metrics.prometheus.enabled,jhipster.metrics.prometheus.endpoint] were left unbound.
>     Property: jhipster.metrics.prometheus.enabled
>     Value: false
>     Origin: "jhipster.metrics.prometheus.enabled" from property source "bootstrapProperties"
>     Reason: The elements [jhipster.logging.spectator-metrics.enabled,jhipster.metrics.graphite.enabled,jhipster.metrics.graphite.host,jhipster.metrics.graphite.port,jhipster.metrics.graphite.prefix,jhipster.metrics.prometheus.enabled,jhipster.metrics.prometheus.endpoint] were left unbound.
>     Property: jhipster.metrics.prometheus.endpoint
>     Value: /prometheusMetrics
>     Origin: "jhipster.metrics.prometheus.endpoint" from property source "bootstrapProperties"
>     Reason: The elements [jhipster.logging.spectator-metrics.enabled,jhipster.metrics.graphite.enabled,jhipster.metrics.graphite.host,jhipster.metrics.graphite.port,jhipster.metrics.graphite.prefix,jhipster.metrics.prometheus.enabled,jhipster.metrics.prometheus.endpoint] were left unbound.
> 
> Action:
> 
> Update your application's configuration
> 
> [root@VM_0_7_centos app]# 
> 

##### **JHipster Version(s)**
JHipster 5.2.1

##### **JHipster configuration**

tonys-Air:gateway-test tony$ jhipster info
Using JHipster version installed locally in current project's node_modules
Executing jhipster:info
Options: 
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
gateway@0.0.0 /Users/tony/dev/microservice/gateway-test
└── generator-jhipster@5.2.1 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.zykj.gateway",
      "nativeLanguage": "zh-cn"
    },
    "jhipsterVersion": "5.2.1",
    "applicationType": "gateway",
    "baseName": "gateway",
    "packageName": "com.zykj.gateway",
    "packageFolder": "com/zykj/gateway",
    "serverPort": "9080",
    "authenticationType": "jwt",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": true,
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "yarn",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "zh-cn",
    "languages": [
      "zh-cn",
      "en"
    ]
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_152"
Java(TM) SE Runtime Environment (build 1.8.0_152-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.152-b16, mixed mode)

git version 2.15.1 (Apple Git-101)

node: v8.11.3

npm: 6.4.0

yeoman: 2.0.0

yarn: 1.7.0

Congratulations, JHipster execution is complete!
tonys-Air:gateway-test tony$ 
##### **Browsers and Operating System**

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment] 2018-08-31 15:45
I'm testing but at the moment I can't reproduce... It looks like those properties got deleted in your code: Spring Boot has a configuration for them, but it can't apply it. Did you change anything else in your code?

**Comment by jdubois** [comment] 2018-08-31 15:45
Oops you closed it as the same millisecond I posted my message! So I guess you found the issue :-)

**Closed** 2018-08-31 15:45 UTC

**Comment by TonyLuo** [comment] 2018-09-01 03:33
the project is upgraded from jhipster4, and using the cloud configuration, when start it , it will automatically load the old configuration from cloud....
jhipster4 old cloud configuration cause that issue.

**Comment by abhiroopghatak** [comment] 2019-04-07 05:24
***************************
APPLICATION FAILED TO START
***************************

Description:

Failed to bind properties under '' to com.zaxxer.hikari.HikariDataSource:

    Property: driverclassname
    Value: org.h2.Driver
    Origin: "driverClassName" from property source "source"
    Reason: Failed to load driver class org.h2.Driver in either of HikariConfig class loader or Thread context classloader

Action:

Update your application's configuration.


None responses are related to this ... They talk about application.properties and mvn deps ... even afetr providing necessary details , it failed . If JHipster creates so many files automatically , they shouldnt have missed such . This hampers selection of dev framework  at very initial stage .
