### ISSUE TITLE
jhi_user is not populated with new user upon logging using Keycloak

### ISSUE THREAD

**Issue by vrijmetse** [jhipster/generator-jhipster#11875] opened 2020-06-01 12:22 UTC
##### **Overview of the issue**

I enabled JHipster with Oauth2 using Keycloak. I notice upon logging in with Facebook, the new user registered is not being added into "jhi_user"

##### **Motivation for or Use Case**

I believe the expectation for this use case the new user must be added into jhi_user as well.

##### **Reproduce the error**

Generate project using oauth2

##### **Suggest a Fix**

Remove readOnly=true from `UserService.getUserFromAuthentication`

##### **JHipster Version(s)**

6.9.0

##### **JHipster configuration**

```
{
  "generator-jhipster": {
    "authenticationType": "oauth2",
    "cacheProvider": "redis",
    "clientFramework": "react",
    "serverPort": "8080",
    "serviceDiscoveryType": "eureka",
    "skipUserManagement": true,
    "baseName": "webportal",
    "buildTool": "gradle",
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "enableHibernateCache": true,
    "enableSwaggerCodegen": true,
    "enableTranslation": true,
    "jhiPrefix": "jhi",
    "languages": ["in", "en"],
    "messageBroker": false,
    "nativeLanguage": "in",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "skipClient": false,
    "testFrameworks": [],
    "websocket": false,
    "packageName": "com.dsa.portal",
    "packageFolder": "com/dsa/portal",
    "skipServer": false,
    "applicationType": "monolith",
    "clientPackageManager": "npm",
    "clientTheme": "journal",
    "clientThemeVariant": "light",
    "dtoSuffix": "DTO",
    "embeddableLaunchScript": false,
    "otherModules": [],
    "useSass": true,
    "jhipsterVersion": "6.9.0",
    "creationTimestamp": 1588422840597,
    "entitySuffix": "",
    "blueprints": []
  },
  "entities": ["News"]
}

```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

Using default User / jhi_user

##### **Browsers and Operating System**

Browser: Chrome
OS : Ubuntu 18.04

-   [v ] Checking this box is mandatory (this is just to show you read everything)

**Comment by mraible** [comment] 2020-06-01 12:24
Duplicate of https://github.com/jhipster/generator-jhipster/issues/11836.

@pascalgrimaud This seems like a bug we should do a patch release for.

**Closed by mraible** 2020-06-01 12:24 UTC
