### ISSUE TITLE
duplicate class while compiling

### ISSUE THREAD

**Issue by LaurSo** [jhipster/generator-jhipster#4427] opened 2016-11-04 13:41 UTC
##### **Overview of the issue**

I get the hipster project generated, I configure my eclipse, and when I compile the project, I get the error.
I have found other post but that not help or that are not clear. Can you help

 COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /xxx/target/generated-sources/com/camaieu/fasst/service/mapper/UserMapperImpl.java:[16,8] duplicate class: com.xxx.service.mapper.UserMapperImpl
[INFO] 1 error

##### **JHipster Version(s)**
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
fasst@0.0.0 D:\Dev\1 - Dev\02 - Camaieux\03 - Projet\fasst
`-- generator-jhipster@3.10.0

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "jhipsterVersion": "3.10.0",
    "baseName": "fasst",
    "packageName": "com.camaieu.fast",
    "packageFolder": "com/camaieu/fast",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "oracle",
    "prodDatabaseType": "oracle",
    "searchEngine": false,
    "messageBroker": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "jwtSecretKey": "49cdc2357627eed6bb22985ae96a2b5b93b543b5",
    "useSass": false,
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "fr",
    "languages": [
      "fr"
    ],
    "serviceDiscoveryType": false
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

ls: no such file or directory: .jhipster/*.json
##### **Browsers and Operating System**

java version "1.8.0_102"
Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode)

git version 2.10.1.windows.1

node: v4.6.0

npm: 3.10.8

bower: 1.7.9

gulp:
[14:39:22] CLI version 1.2.2
[14:39:22] Local version 3.9.1

yeoman: 1.8.5

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

{
  "generator-jhipster": {
    "jhipsterVersion": "3.10.0",
    "baseName": "fasst",
    "packageName": "com.camaieu.fast",
    "packageFolder": "com/camaieu/fast",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "oracle",
    "prodDatabaseType": "oracle",
    "searchEngine": false,
    "messageBroker": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "jwtSecretKey": "49cdc2357627eed6bb22985ae96a2b5b93b543b5",
    "useSass": false,
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "fr",
    "languages": [
      "fr"
    ],
    "serviceDiscoveryType": false
  }
}

##### **Browsers and Operating System**
windows xp

**Comment by jdubois** [comment] 2016-11-04 13:45
Yes that's because of MapStruct.
Did you follow our guide at https://jhipster.github.io/configuring-ide/ ?
It might need to be corrected.

**Comment by LaurSo** [comment] 2016-11-04 14:04
Yes I followed, except the part of the plugin maven "maven processor plugin" I dont know if installed or not 
but It wasnt requered during configuration of eclipse
because no corresponding errors occured

**Comment by jdubois** [comment] 2016-11-04 14:06
Well your issue is exactly with the "maven processor plugin": so it depends if the documentation is wrong or if you didn't follow it :-)
I know this isn't obvious, this is why DTOs are still in BETA after all this time. I personally don't have a clean working environnement here.

**Comment by pascalgrimaud** [comment] 2016-11-06 15:03
@LaurSo : just played with the last version of Eclipse: Neon, and I didn't manage to reproduce the issue.
But I use h2Disk / mysql instead of your config oracle/oracle:
- right click on pom.xml > run as... > maven build... > clean package
- right click on pom.xml > run as... > maven build... > spring-boot:run

Can you provide these information plz?
1) what is the version of your Eclipse ?
2) how did you compile ?
3) can you test with other settings (for example h2Disk/mysql -> so maybe it's easier for us to try to reproduce)

**Comment by jdubois** [comment] 2016-11-06 16:50
Not sure if @LaurSo you have misconfigured something or not, but as nobody else as commented this or warned us about the error, I guess I did something strange -> I'm closing this until we have more information, and we can reproduce

**Closed by jdubois** 2016-11-06 16:50 UTC
Labels: waiting for information
