### ISSUE TITLE
Migrate JHipster Registry to micrometer

### ISSUE THREAD

**Issue by sazeez** [jhipster/generator-jhipster#9122] opened 2019-01-26 18:04 UTC
##### **Overview of the issue**
After upgrading apps to https://github.com/jhipster/generator-jhipster/releases/tag/v5.8.0, JHipster Registry is not able to collect metrics from apps.

##### **Motivation for or Use Case**
Migration to Micrometer in apps must be reflected on Registry.

##### **Reproduce the error**
Create new microservice using default options + registry using generator-jhipster.
Start registry and microservice, navigate to registry console, Administration->metrics, verify metrics is not loading for microservice.

##### **Related issues**
PR #8812 

##### **JHipster Version(s)**
Generator v5.8.0
Registry v4.0.6

##### **JHipster configuration**
INFO! Using JHipster version installed locally in current project's node_modules
INFO! Executing jhipster:info
INFO! Options: from-cli: true
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
`-- generator-jhipster@5.8.0

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.example"
    },
    "jhipsterVersion": "5.8.0",
    "applicationType": "microservice",
    "baseName": "Test",
    "packageName": "com.example",
    "packageFolder": "com/example",
    "serverPort": "8081",
    "authenticationType": "jwt",
    "cacheProvider": "no",
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "oracle",
    "prodDatabaseType": "oracle",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "enableTranslation": false,
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "clientPackageManager": "npm",
    "skipClient": true,
    "skipUserManagement": true,
    "enableHibernateCache": false,
    "otherModules": [],
    "entitySuffix": "",
    "dtoSuffix": "DTO"
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_191"
Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
Java HotSpot(TM) Client VM (build 25.191-b12, mixed mode, sharing)

git version 2.16.2.windows.1

node: v10.15.0

npm: 6.5.0

yeoman: 2.0.5

yarn: 1.9.4

INFO! Congratulations, JHipster execution is complete!

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**
NA

##### **Browsers and Operating System**
Windows 10, Chrome 71

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by ruddell** [comment] 2019-01-26 18:39
Duplicate of https://github.com/jhipster/jhipster-registry/issues/324

There's a PR open https://github.com/jhipster/jhipster-registry/pull/325 that should fix it soon

**Closed by ruddell** 2019-01-26 18:39 UTC
