### ISSUE TITLE
Recommended workflow to handle two associations between two classes   with two   different owning sides

### ISSUE THREAD

**Issue by alfredorueda** [jhipster/generator-jhipster#2404] opened 2015-11-27 10:01 UTC
Hello, I would like to know the best approach to handle this situation , please . suppose we have two classes team and player , then suppose we have two kind of associations between team and player. The first one is a one-to-many association between team and player, to reflect that a team can have many players. In this case , naturally , player is the owner of the Association. The second one is a one-to-one association between team and player to register which player is the captain of the team but in this case, I have decided that team must be the owner of the association. naturally there's a problem when liquibase tries to apply these change sets due to the foreign keys . please, I would like to know the recommended workflow to implement this kind of associations . thank you very much

I have created a third change set manually. This seems to work at the database level but not sure if it is the best approach.

**Comment by jdubois** [comment] 2015-11-27 11:05
This is not a bug or a feature request -> I'm closing this according to our guidelines, as this kind of question should go to StackOverflow (please repost this on StackOverflow using the JHipster tag)

**Closed by jdubois** 2015-11-27 11:05 UTC
