### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by clp334264003** [jhipster/generator-jhipster#4374] opened 2016-10-24 13:51 UTC
##### **Overview of the issue**

An example of an angular2,
The node is started
Combined with jhipster single application login function

console
zone.js?1477316048302:1274 GET http://localhost:8080/api/account 
XMLHttpRequest cannot load http://localhost:8080/api/account. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:5555' is therefore not allowed access. The response had HTTP status code 401.

2016-10-24 21:50:24.564 DEBUG 8880 --- [  XNIO-2 task-6] c.qm.ipnaasp.aop.logging.LoggingAspect   : Enter: com.qm.ipnaasp.web.rest.UserJWTController.authorize() with argument[s] = [LoginVM{password='*****', username='admin', rememberMe=true}, com.codahale.metrics.servlet.AbstractInstrumentedFilter$StatusExposingServletResponse@72ec59b1]
2016-10-24 21:50:24.572 DEBUG 8880 --- [  XNIO-2 task-6] c.q.ipnaasp.security.UserDetailsService  : Authenticating admin
2016-10-24 21:50:24.673 DEBUG 8880 --- [  XNIO-2 task-6] c.qm.ipnaasp.aop.logging.LoggingAspect   : Enter: org.springframework.boot.actuate.audit.AuditEventRepository.add() with argument[s] = [AuditEvent [timestamp=Mon Oct 24 21:50:24 CST 2016, principal=admin, type=AUTHENTICATION_SUCCESS, data={}]]
2016-10-24 21:50:24.674 DEBUG 8880 --- [  XNIO-2 task-6] c.qm.ipnaasp.aop.logging.LoggingAspect   : Exit: org.springframework.boot.actuate.audit.AuditEventRepository.add() with result = null
2016-10-24 21:50:24.675 DEBUG 8880 --- [  XNIO-2 task-6] c.qm.ipnaasp.aop.logging.LoggingAspect   : Exit: com.qm.ipnaasp.web.rest.UserJWTController.authorize() with result = <200 OK,com.qm.ipnaasp.web.rest.JWTToken@5c5c5d47,{}>
2016-10-24 21:50:24.682 DEBUG 8880 --- [  XNIO-2 task-7] c.qm.ipnaasp.aop.logging.LoggingAspect   : Enter: org.springframework.boot.actuate.audit.AuditEventRepository.add() with argument[s] = [AuditEvent [timestamp=Mon Oct 24 21:50:24 CST 2016, principal=anonymousUser, type=AUTHORIZATION_FAILURE, data={details=org.springframework.security.web.authentication.WebAuthenticationDetails@b364: RemoteIpAddress: 0:0:0:0:0:0:0:1; SessionId: null, type=org.springframework.security.access.AccessDeniedException, message=Access is denied}]]
2016-10-24 21:50:24.682 DEBUG 8880 --- [  XNIO-2 task-7] c.qm.ipnaasp.aop.logging.LoggingAspect   : Exit: org.springframework.boot.actuate.audit.AuditEventRepository.add() with result = null
2016-10-24 21:50:24.683 DEBUG 8880 --- [  XNIO-2 task-7] c.q.i.s.Http401UnauthorizedEntryPoint    : Pre-authenticated entry point called. Rejecting access

**Comment by jdubois** [comment] 2016-10-24 14:00
AngularJS 2 is not released yet, this is in a specific dev branch.
You shouldn't have a CORS error, but it really depends on what you do, etc.

This is not a bug, you are working on unreleased code, so I'm closing it.

**Closed by jdubois** 2016-10-24 14:00 UTC
