### ISSUE TITLE
Replace domain objects in REST controllers by DTOs

### ISSUE THREAD

**Issue by ctytgat** [jhipster/generator-jhipster#1388] opened 2015-04-16 08:26 UTC
In the generated jHipster apps, domain objects are exposed as-is via the RestControllers.

They are used a input for PUT/POST requests and used as output for the GET requests.

Can we maintain this for anything bigger then a very simple CRUD based application and is it a best practice to expose domain objects like this?

Even with simple applications you can run into issues while updating a JPA entity because your REST controller will never receive valid domain objects 
Most of the time you simply want to update certain key attributes. (also important from a security standpoint)

Also, certain domain level validations don't necessarily make sense in a REST context. For example, I needed auditing on my domain so I let my domain objects extend AbstractAuditingEntity. This caused issues as the @NotNull validations on createdBy etc failed when created by the UI. 

From that perspective, using DTOs would make a lot more sense.
(I ended up using DTOs for all my resources)

**Comment by gzsombor** [comment] 2015-04-16 08:34
There is already a pull request about this feature: https://github.com/jhipster/generator-jhipster/pull/1199

**Comment by jdubois** [comment] 2015-04-16 15:54
I'm closing this as a duplicate of #1199
I agree this is important, yet this is quite complex to generate.

**Closed by jdubois** 2015-04-16 15:54 UTC
