### ISSUE TITLE
Deploy on Cloud Foundry using mongoDB (mongolab) does not create seed data

### ISSUE THREAD

**Issue by marcelinobadin** [jhipster/generator-jhipster#3582] opened 2016-05-11 20:43 UTC
##### **Overview of the issue**

I have created a Gateway (microservices architecture) which deploys seemly on heroku. But once I try to deploy it on Cloud Foundry (Pivotal) it just not create the seed data (using jhipster 3.2.1 - with mongobee).

It is important to notice that it is creating the `dbchangelog` (with zero documents) table and `jhi_persistent_audit_event` (with 1 document)

##### **.yo-rc.json**
```json
{
  "generator-jhipster": {
    "jhipsterVersion": "3.2.1",
    "baseName": "gateway",
    "packageName": "com.example.gateway",
    "packageFolder": "com/example/gateway",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "no",
    "clusteredHttpSession": "hazelcast",
    "websocket": "no",
    "databaseType": "mongodb",
    "devDatabaseType": "mongodb",
    "prodDatabaseType": "mongodb",
    "searchEngine": "no",
    "buildTool": "maven",
    "jwtSecretKey": "blablabla",
    "useSass": true,
    "applicationType": "gateway",
    "testFrameworks": [
      "gatling",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "pt-br"
    ]
  }
}
```

**Comment by jdubois** [comment] 2016-05-11 21:49
Just to be sure: you don't have a "User" table? Did you have anything in your logs?

**Comment by marcelinobadin** [comment] 2016-05-11 21:54
No, I didn't create any entity on the Gateway, only on my app. I just ran the jhipster:entity on gateway to create the front-end content for those entities in the app.

The logs shows everything is ok. Also tells that mongobee ran successfully.

**Comment by jdubois** [comment] 2016-05-11 21:58
i'm sorry I don't understand: do you have a "User" table? Can you log in the gateway and use it?

**Comment by marcelinobadin** [comment] 2016-05-11 22:10
Well, now I have created jhi_user and jhi_authority manually (using mongolab manager interface) and it is working.

**Comment by jdubois** [comment] 2016-05-12 09:02
I'm sorry I don't understand what you are doing exactly.
Anyway, I just tested with the latest "master" branch, and had no issue at all: tables where created, data was included in the tables, etc... So I'm closing this as I can't reproduce. I would need more info on what you do exactly.

**Comment by marcelinobadin** [comment] 2016-05-13 12:18
I found the problem.

On `CloudMongoDbConfiguration`, where it tells where to look for the migrations,

```java
mongobee.setChangeLogsScanPackage("io.github.jhipster.cms.config.dbmigrations");
```

it has the io.github... package. I just changed to my package and it worked fine.

**Comment by atomfrede** [comment] 2016-05-13 12:34
You're right. The package name should not be hard coded.

**Comment by jdubois** [comment] 2016-05-13 12:37
Oh, that's bad!!! Will you do a PR? I guess an emergency new release is necessary!

**Comment by atomfrede** [comment] 2016-05-13 12:56
I can do a PR today.

**Comment by jdubois** [comment] 2016-05-13 12:56
@atomfrede don't worry I'm doing it.... I'd like to go on week end not too late :-)

**Closed** 2016-05-13 13:04 UTC
Labels: bug
