### ISSUE TITLE
production packaging failure while webpack bundling  

### ISSUE THREAD

**Issue by dearnani** [jhipster/generator-jhipster#6295] opened 2017-08-27 13:16 UTC
##### **Overview of the issue**

tried to build the production ready with `mvnw -Pprod clean package`

Its failing with the following console output:

~~~
[INFO] Angular compilation done, starting webpack bundling.
[INFO]
[INFO] [at-loader] Using typescript@2.4.2 from typescript and "tsconfig.json" from C:\EmiratesGrpOnlineShop\tsconfig-aot.json.
[INFO]
[ERROR] 113340ms building modules
[ERROR] 235ms sealing
[ERROR] 0ms optimizing
[ERROR] 0ms basic module optimization
[ERROR] 1109ms module optimization
[ERROR] 1ms advanced module optimization
[ERROR] 230ms basic chunk optimization
[ERROR] 0ms chunk optimization
[ERROR] 20ms advanced chunk optimization
[ERROR] 14214ms building modules
[ERROR] 16ms module and chunk tree optimization
[ERROR] 0ms chunk modules optimization
[ERROR] 0ms advanced chunk modules optimization
[ERROR] 66ms module reviving
[ERROR] 18ms module order optimization
[ERROR] 63ms module id optimization
[ERROR] 8ms chunk reviving
[ERROR] 5ms chunk order optimization
[ERROR] 130ms chunk id optimization
[ERROR] 2134ms hashing
[ERROR] 5ms module assets processing
[ERROR] 3524ms chunk assets processing
[ERROR] 2325ms additional chunk assets processing
[ERROR] 5ms recording
~~~

Please Note: Dev profile is working fine...

##### **Reproduce the error**

can download the required package.json and rest from https://github.com/dearnani/EmiratesGrpOnlineShop

##### **JHipster Version(s)**

4.7.1
##### **JHipster configuration**

https://github.com/dearnani/EmiratesGrpOnlineShop

https://github.com/dearnani/EmiratesGrpOnlineShop/.yo-rc.json

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

https://github.com/dearnani/EmiratesGrpOnlineShop/jhipster-jdlN.jdl

##### **Browsers and Operating System**

Windows 10 , Google Chrome 

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by gmarziou** [comment] 2017-08-27 19:10
Please use `jhipster info` so that we get information about your environment that your repositories do not show.

**Comment by gmarziou** [comment] 2017-08-27 20:10
By the way your project on github does not work because of missing liquibase files:

`Caused by: java.io.FileNotFoundException: class path resource [config/liquibase/changelog/20170827010346_added_entity_ProductInfo.xml] cannot be resolved to URL because it does not exist`

**Comment by gmarziou** [comment] 2017-08-27 21:11
I regenerated your project with `jhipster --with-entities` with 4.7.0 and ran successfully `mvnw -Pprod clean package` with few warnings:

<details>
<summary>maven log file</summary>
[INFO] --- frontend-maven-plugin:1.4:yarn (webpack build test) @ emirates-grp-online-shop ---
[INFO] Running 'yarn run webpack:test' in e:\projets\issues\dearnani\EmiratesGrpOnlineShop
[INFO] yarn run v0.27.5
[INFO] $ yarn run test
[INFO] Hash: e0bdc8cc97632b01d813
[INFO] Version: webpack 3.5.4
[INFO] Time: 202ms
[INFO] webpack: Compiled successfully.
[INFO] webpack: Compiling...
[ERROR] Warning: The 'no-use-before-declare' rule requires type infomation.
[INFO]
[INFO] [at-loader] Using typescript@2.4.2 from typescript and "tsconfig.json" from e:\projets\issues\dearnani\EmiratesGrpOnlineShop/tsconfig.json.
[INFO]
[INFO]
[INFO] [at-loader] Checking started in a separate process...
[INFO]
[INFO] [at-loader] Ok, 1.172 sec.
[ERROR] Hash: 6d89ca7c6067a43e5fa3
[INFO] webpack: Compiled with warnings.
[ERROR] Version: webpack 3.5.4
[ERROR] Time: 36400ms
[ERROR]         Asset     Size  Chunks                    Chunk Names
[ERROR] spec/entry.ts  5.44 MB       0  [emitted]  [big]  spec/entry.ts
[ERROR]   [19] ./node_modules/@angular/core/@angular/core/testing.es5.js 39.7 kB {0} [built]
[ERROR]   [25] ./node_modules/rxjs/Rx.js 9.65 kB {0} [built]
[ERROR]  [266] ./node_modules/rxjs/util/TimeoutError.js 776 bytes {0} [built]
[ERROR]  [381] ./src/test/javascript/spec/entry.ts 853 bytes {0} [built]
[ERROR]  [382] ./node_modules/core-js/index.js 639 bytes {0} [built]
[ERROR]  [570] ./node_modules/zone.js/dist/zone.js 113 kB {0} [built]
[ERROR]  [571] ./node_modules/zone.js/dist/long-stack-trace-zone.js 6.22 kB {0} [built]
[ERROR]  [572] ./node_modules/zone.js/dist/async-test.js 3.23 kB {0} [built]
[ERROR]  [573] ./node_modules/zone.js/dist/fake-async-test.js 16.3 kB {0} [built]
[ERROR]  [574] ./node_modules/zone.js/dist/sync-test.js 1.41 kB {0} [built]
[ERROR]  [575] ./node_modules/zone.js/dist/proxy.js 5.6 kB {0} [built]
[ERROR]  [576] ./node_modules/zone.js/dist/jasmine-patch.js 6.36 kB {0} [built]
[ERROR]  [827] ./node_modules/intl/locale-data/jsonp/en-US.js 24 kB {0} [built]
[ERROR]  [828] ./node_modules/@angular/platform-browser-dynamic/@angular/platform-browser-dynamic/testing.es5.js 3.6 kB {0} [built]
[ERROR]  [832] ./src/test/javascript/spec \.spec 2.19 kB {0} [built]
[ERROR]     + 916 hidden modules
[ERROR]
[ERROR] WARNING in ./node_modules/@angular/core/@angular/core.es5.js
[ERROR] 5646:15-36 Critical dependency: the request of a dependency is an expression
[ERROR]
[ERROR] WARNING in ./node_modules/@angular/core/@angular/core.es5.js
[ERROR] 5662:15-102 Critical dependency: the request of a dependency is an expression
[INFO] 27 08 2017 22:21:06.922:INFO [karma]: Karma v1.7.0 server started at http://0.0.0.0:9876/
[INFO] 27 08 2017 22:21:06.929:INFO [launcher]: Launching browser PhantomJS with unlimited concurrency
[INFO] 27 08 2017 22:21:07.089:INFO [launcher]: Starting browser PhantomJS
[INFO] 27 08 2017 22:21:11.107:INFO [PhantomJS 2.1.1 (Windows 8 0.0.0)]: Connected on socket KezBfOKjsc_XIaZXAAAA with id 45668302
        PhantomJS 2.1.1 (Windows 8 0.0.0): Executed 44 of 44 SUCCESS (0 secs / 6.189 secs)
[INFO] .
       PhantomJS 2.1.1 (Windows 8 0.0.0): Executed 44 of 44 SUCCESS (6.209 secs / 6.189 secs)
[INFO]
[INFO] =============================== Coverage summary ===============================
[INFO] Statements   : 67.2% ( 1043/1552 )
[INFO] Branches     : 30.17% ( 73/242 )
[INFO] Functions    : 44.5% ( 186/418 )
[INFO] Lines        : 64.97% ( 909/1399 )
[INFO] ================================================================================
[INFO] Done in 60.92s.
[INFO]
[INFO] --- maven-war-plugin:2.6:war (default-war) @ emirates-grp-online-shop ---
[INFO] Packaging webapp
[INFO] Assembling webapp [emirates-grp-online-shop] in [e:\projets\issues\dearnani\EmiratesGrpOnlineShop\target\emirates-grp-online-shop-0.0.1-SNAPSHOT]
[INFO] Processing war project
[INFO] Copying webapp resources [e:\projets\issues\dearnani\EmiratesGrpOnlineShop\target\www]
[INFO] Webapp assembled in [2469 msecs]
[INFO] Building war: e:\projets\issues\dearnani\EmiratesGrpOnlineShop\target\emirates-grp-online-shop-0.0.1-SNAPSHOT.war
[INFO]
[INFO] --- spring-boot-maven-plugin:1.5.6.RELEASE:repackage (default) @ emirates-grp-online-shop ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 05:38 min
[INFO] Finished at: 2017-08-27T22:21:29+02:00
[INFO] Final Memory: 60M/649M
[INFO] ------------------------------------------------------------------------
</details>

Using JHipster version installed locally in current project's node_modules
Executing jhipster:info
Options: 
##### **JHipster Version(s)**

```
emirates-grp-online-shop@0.0.0 e:\projets\issues\dearnani\EmiratesGrpOnlineShop
+-- generator-jhipster@4.7.0 
`-- UNMET PEER DEPENDENCY popper.js@^1.11.0

```


##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**


<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.emrgrp.ecom.shopcart",
      "nativeLanguage": "ar-ly"
    },
    "jhipsterVersion": "4.7.0",
    "baseName": "EmiratesGrpOnlineShop",
    "packageName": "com.emrgrp.ecom.shopcart",
    "packageFolder": "com/emrgrp/ecom/shopcart",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "ar-ly",
    "languages": [
      "ar-ly",
      "en",
      "hi"
    ]
  }
}
</pre>
</details>


##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity ProductInfo (product_info) {
  prouctCode String required,
  proudctName String,
  productType ProductType required,
  productDescription String,
  productStatus ProductStatus required
}
entity DealerInfo (dealer_info) {
  dealerCode String required,
  dealerName String,
  dearLocation String,
  dealerStatus DealerStatus required
}
entity PaymentDetails (payment_details) {
  paymentMode PaymentChannel required,
  paymentStatus PaymentStatus required,
  oderNumber String required,
  oderDate ZonedDateTime,
  numberOfProducts Integer required,
  totalAmount Long required
}
/**
 * not an ignored comment
 */
entity Location (location) {
  streetAddress String,
  postalCode String required,
  city String required,
  stateProvince String,
  country String
}
/**
 * The Employee entity.
 */
entity CustomerInfo (customer_info) {
  aliasName String required,
  firstName String,
  lastName String,
  email String,
  phoneNumber String required,
  lastLogin ZonedDateTime
}
entity OrderMangement (order_mangement) {
  orderId Long,
  productCode Long,
  dealerCode String,
  assignedPrice BigDecimal,
  dearLocation String,
  orderStatus OrderStatus,
  paymentStatus PaymentStatus
}
entity DeliverManagement (deliver_management) {
  orderNumber Long,
  deliveryStatus DeliveryStatus
}

enum ProductType {
  ELECTRONICS,
  HOMEAPPLIANCES,
  FURNITURE,
  FABRICS
}

enum ProductStatus {
  AVAILABLE,
  NOT_AVAILABLE,
  BLOCKED,
  DELETED,
  EXPIRED
}

enum DealerStatus {
  ACIVE,
  INACTIVE,
  BLOKED
}

enum PaymentChannel {
  CASHON_DELIVERY,
  ONLINE_CREDITCARD,
  ONLINE_DEBITCARD
}

enum PaymentStatus {
  SUCCESS,
  FAIL
}

enum OrderStatus {
  SAVE,
  SUCESS,
  DELIVERY_FAIL,
  PAYMENT_FAIL,
  COMPLETE
}

enum DeliveryStatus {
  DISPATCHED,
  TRANSIT,
  RETURNED,
  DOORLOCKED,
  DELIVERED,
  UNDELIVERED
}

relationship OneToMany {
  ProductInfo{dealerProductInfo} to DealerInfo{productInfo},
  Location{dealerLocation} to DealerInfo{location},
  Location{custLocation} to CustomerInfo{location},
  ProductInfo{productInfo} to OrderMangement{productInfo},
  PaymentDetails{paymentDetails} to OrderMangement{paymentDetails},
  CustomerInfo{customerInfo} to OrderMangement{customerInfo},
  Location{deliveryLocation} to DeliverManagement{location}
}


</pre>
</details>


##### **Environment and Tools**

java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

git version 2.12.0.windows.1

node: v6.11.1

npm: 3.10.10

gulp:
[22:58:58] CLI version 1.4.0

yeoman: 2.0.0

yarn: 0.27.5

Docker version 17.06.0-ce, build 02c1d87

docker-compose version 1.14.0, build c7bdf9e3

Execution complete

**Comment by gmarziou** [comment] 2017-08-27 21:12
I'm closing because I'm unable to reproduce it and there's not enough info to help.

**Comment by dearnani** [comment] 2017-08-27 21:12
Thank you for your kind response, am running onno-liquibase profile

**Closed by gmarziou** 2017-08-27 21:12 UTC

**Comment by dearnani** [comment] 2017-08-27 21:21
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
emirates-grp-online-shop@0.0.0 C:\EmiratesGrpOnlineShop
`-- generator-jhipster@4.7.0

```


##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**


<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.emrgrp.ecom.shopcart",
      "nativeLanguage": "ar-ly"
    },
    "jhipsterVersion": "4.7.0",
    "baseName": "EmiratesGrpOnlineShop",
    "packageName": "com.emrgrp.ecom.shopcart",
    "packageFolder": "com/emrgrp/ecom/shopcart",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "ar-ly",
    "languages": [
      "ar-ly",
      "en",
      "hi"
    ]
  }
}
</pre>
</details>


##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity ProductInfo (product_info) {
  prouctCode String required,
  proudctName String,
  productType ProductType required,
  productDescription String,
  productStatus ProductStatus required
}
entity DealerInfo (dealer_info) {
  dealerCode String required,
  dealerName String,
  dearLocation String,
  dealerStatus DealerStatus required
}
entity PaymentDetails (payment_details) {
  paymentMode PaymentChannel required,
  paymentStatus PaymentStatus required,
  oderNumber String required,
  oderDate ZonedDateTime,
  numberOfProducts Integer required,
  totalAmount Long required
}
/**
 * not an ignored comment
 */
entity Location (location) {
  streetAddress String,
  postalCode String required,
  city String required,
  stateProvince String,
  country String
}
/**
 * The Employee entity.
 */
entity CustomerInfo (customer_info) {
  aliasName String required,
  firstName String,
  lastName String,
  email String,
  phoneNumber String required,
  lastLogin ZonedDateTime
}
entity OrderMangement (order_mangement) {
  orderId Long,
  productCode Long,
  dealerCode String,
  assignedPrice BigDecimal,
  dearLocation String,
  orderStatus OrderStatus,
  paymentStatus PaymentStatus
}
entity DeliverManagement (deliver_management) {
  orderNumber Long,
  deliveryStatus DeliveryStatus
}

enum ProductType {
  ELECTRONICS,
  HOMEAPPLIANCES,
  FURNITURE,
  FABRICS
}

enum ProductStatus {
  AVAILABLE,
  NOT_AVAILABLE,
  BLOCKED,
  DELETED,
  EXPIRED
}

enum DealerStatus {
  ACIVE,
  INACTIVE,
  BLOKED
}

enum PaymentChannel {
  CASHON_DELIVERY,
  ONLINE_CREDITCARD,
  ONLINE_DEBITCARD
}

enum PaymentStatus {
  SUCCESS,
  FAIL
}

enum OrderStatus {
  SAVE,
  SUCESS,
  DELIVERY_FAIL,
  PAYMENT_FAIL,
  COMPLETE
}

enum DeliveryStatus {
  DISPATCHED,
  TRANSIT,
  RETURNED,
  DOORLOCKED,
  DELIVERED,
  UNDELIVERED
}

relationship OneToMany {
  ProductInfo{dealerProductInfo} to DealerInfo{productInfo},
  Location{dealerLocation} to DealerInfo{location},
  Location{custLocation} to CustomerInfo{location},
  ProductInfo{productInfo} to OrderMangement{productInfo},
  PaymentDetails{paymentDetails} to OrderMangement{paymentDetails},
  CustomerInfo{customerInfo} to OrderMangement{customerInfo},
  Location{deliveryLocation} to DeliverManagement{location}
}


</pre>
</details>


##### **Environment and Tools**

java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

git version 2.12.2.windows.2

node: v6.11.2

npm: 5.3.0

yeoman: 2.0.0

yarn: 0.27.5

**Comment by dearnani** [comment] 2017-08-27 21:33
Added the missing liquibase files....

**Comment by dearnani** [comment] 2017-08-27 21:54
Issue remain same though i ran with prod, no-liquibase profiles, working fine with dev,no-liquibase profiles.

**Comment by gmarziou** [comment] 2017-08-27 22:27
Have you run webpack in debug as I suggested ?
Beside the ERROR label in output, what makes you think the build failed? 
if you looked at my build output, there is also an ERROR label but it's only warnings
Is the war/jar being built?

**Comment by gmarziou** [comment] 2017-08-27 22:43
I ran mvnw -Pprod,no-liquibase clean package  and here is my output:

<details>
<summary>build output</summary>
<pre>
Results :

Tests run: 195, Failures: 0, Errors: 0, Skipped: 0

[INFO] 
[INFO] --- jacoco-maven-plugin:0.7.9:report (post-unit-test) @ emirates-grp-online-shop ---
[INFO] Loading execution data file e:\projets\issues\dearnani\EmiratesGrpOnlineShop\target\test-results\coverage\jacoco\jacoco.exec
[INFO] Analyzed bundle 'Emirates Grp Online Shop' with 93 classes
[INFO] 
[INFO] --- frontend-maven-plugin:1.4:yarn (webpack build test) @ emirates-grp-online-shop ---
[INFO] Running 'yarn run webpack:test' in e:\projets\issues\dearnani\EmiratesGrpOnlineShop
[INFO] yarn run v0.27.5
[INFO] $ yarn run test
[INFO] Hash: e0bdc8cc97632b01d813
[INFO] Version: webpack 3.5.4
[INFO] Time: 220ms
[INFO] webpack: Compiled successfully.
[INFO] webpack: Compiling...
[ERROR] Warning: The 'no-use-before-declare' rule requires type infomation.
[INFO] 
[INFO] [at-loader] Using typescript@2.4.2 from typescript and "tsconfig.json" from e:\projets\issues\dearnani\EmiratesGrpOnlineShop/tsconfig.json.
[INFO] 
[INFO] 
[INFO] [at-loader] Checking started in a separate process...
[INFO] 
[INFO] [at-loader] Ok, 1.131 sec.
[ERROR] Hash: 6d89ca7c6067a43e5fa3
[INFO] webpack: Compiled with warnings.
[ERROR] Version: webpack 3.5.4
[ERROR] Time: 38671ms
[ERROR]         Asset     Size  Chunks                    Chunk Names
[ERROR] spec/entry.ts  5.44 MB       0  [emitted]  [big]  spec/entry.ts
[ERROR]   [19] ./node_modules/@angular/core/@angular/core/testing.es5.js 39.7 kB {0} [built]
[ERROR]   [25] ./node_modules/rxjs/Rx.js 9.65 kB {0} [built]
[ERROR]  [266] ./node_modules/rxjs/util/TimeoutError.js 776 bytes {0} [built]
[ERROR]  [381] ./src/test/javascript/spec/entry.ts 853 bytes {0} [built]
[ERROR]  [382] ./node_modules/core-js/index.js 639 bytes {0} [built]
[ERROR]  [570] ./node_modules/zone.js/dist/zone.js 113 kB {0} [built]
[ERROR]  [571] ./node_modules/zone.js/dist/long-stack-trace-zone.js 6.22 kB {0} [built]
[ERROR]  [572] ./node_modules/zone.js/dist/async-test.js 3.23 kB {0} [built]
[ERROR]  [573] ./node_modules/zone.js/dist/fake-async-test.js 16.3 kB {0} [built]
[ERROR]  [574] ./node_modules/zone.js/dist/sync-test.js 1.41 kB {0} [built]
[ERROR]  [575] ./node_modules/zone.js/dist/proxy.js 5.6 kB {0} [built]
[ERROR]  [576] ./node_modules/zone.js/dist/jasmine-patch.js 6.36 kB {0} [built]
[ERROR]  [827] ./node_modules/intl/locale-data/jsonp/en-US.js 24 kB {0} [built]
[ERROR]  [828] ./node_modules/@angular/platform-browser-dynamic/@angular/platform-browser-dynamic/testing.es5.js 3.6 kB {0} [built]
[ERROR]  [832] ./src/test/javascript/spec \.spec 2.19 kB {0} [built]
[ERROR]     + 916 hidden modules
[ERROR] 
[ERROR] WARNING in ./node_modules/@angular/core/@angular/core.es5.js
[ERROR] 5646:15-36 Critical dependency: the request of a dependency is an expression
[ERROR] 
[ERROR] WARNING in ./node_modules/@angular/core/@angular/core.es5.js
[ERROR] 5662:15-102 Critical dependency: the request of a dependency is an expression
[INFO] 28 08 2017 00:39:59.213:INFO [karma]: Karma v1.7.0 server started at http://0.0.0.0:9876/
[INFO] 28 08 2017 00:39:59.216:INFO [launcher]: Launching browser PhantomJS with unlimited concurrency
[INFO] 28 08 2017 00:39:59.226:INFO [launcher]: Starting browser PhantomJS
[INFO] 28 08 2017 00:40:03.270:INFO [PhantomJS 2.1.1 (Windows 8 0.0.0)]: Connected on socket kDm6NrfxtiN_kkLQAAAA with id 41313348
[INFO] PhantomJS 2.1.1 (Windows 8 0.0.0): Executed 0 of 44 SUCCESS (0 secs / 0 secs)
[INFO] .PhantomJS 2.1.1 (Windows 8 0.0.0): Executed 1 of 44 SUCCESS (0 secs / 0.272 secs)
[INFO] .PhantomJS 2.1.1 (Windows 8 0.0.0): Executed 2 of 44 SUCCESS (0 secs / 0.404 secs)
[INFO] .PhantomJS 2.1.1 (Windows 8 0.0.0): Executed 3 of 44 SUCCESS (0 secs / 0.578 secs)
[INFO] .PhantomJS 2.1.1 (Windows 8 0.0.0): Executed 4 of 44 SUCCESS (0 secs / 0.719 secs)
[INFO] .PhantomJS 2.1.1 (Windows 8 0.0.0): Executed 5 of 44 SUCCESS (0 secs / 0.833 secs)
[INFO] .PhantomJS 2.1.1 (Windows 8 0.0.0): Executed 6 of 44 SUCCESS (0 secs / 0.963 secs)
[INFO] .PhantomJS 2.1.1 (Windows 8 0.0.0): Executed 7 of 44 SUCCESS (0 secs / 1.091 secs)
[INFO] .PhantomJS 2.1.1 (Windows 8 0.0.0): Executed 8 of 44 SUCCESS (0 secs / 1.204 secs)
[INFO] .PhantomJS 2.1.1 (Windows 8 0.0.0): Executed 9 of 44 SUCCESS (0 secs / 1.316 secs)
[INFO] .PhantomJS 2.1.1 (Windows 8 0.0.0): Executed 10 of 44 SUCCESS (0 secs / 1.428 secs)
[INFO] .PhantomJS 2.1.1 (Windows 8 0.0.0): Executed 11 of 44 SUCCESS (0 secs / 1.542 secs)
[INFO] .PhantomJS 2.1.1 (Windows 8 0.0.0): Executed 12 of 44 SUCCESS (0 secs / 1.654 secs)
[INFO] .PhantomJS 2.1.1 (Windows 8 0.0.0): Executed 13 of 44 SUCCESS (0 secs / 1.807 secs)
[INFO] .PhantomJS 2.1.1 (Windows 8 0.0.0): Executed 14 of 44 SUCCESS (0 secs / 2.002 secs)
[INFO] .PhantomJS 2.1.1 (Windows 8 0.0.0): Executed 15 of 44 SUCCESS (0 secs / 2.131 secs)
[INFO] .PhantomJS 2.1.1 (Windows 8 0.0.0): Executed 16 of 44 SUCCESS (0 secs / 2.255 secs)
[INFO] .PhantomJS 2.1.1 (Windows 8 0.0.0): Executed 17 of 44 SUCCESS (0 secs / 2.382 secs)
[INFO] .PhantomJS 2.1.1 (Windows 8 0.0.0): Executed 18 of 44 SUCCESS (0 secs / 2.506 secs)
[INFO] .PhantomJS 2.1.1 (Windows 8 0.0.0): Executed 19 of 44 SUCCESS (0 secs / 2.644 secs)
[INFO] .PhantomJS 2.1.1 (Windows 8 0.0.0): Executed 20 of 44 SUCCESS (0 secs / 2.79 secs)
[INFO] .PhantomJS 2.1.1 (Windows 8 0.0.0): Executed 21 of 44 SUCCESS (0 secs / 2.94 secs)
[INFO] .PhantomJS 2.1.1 (Windows 8 0.0.0): Executed 22 of 44 SUCCESS (0 secs / 3.108 secs)
[INFO] .PhantomJS 2.1.1 (Windows 8 0.0.0): Executed 23 of 44 SUCCESS (0 secs / 3.306 secs)
[INFO] .PhantomJS 2.1.1 (Windows 8 0.0.0): Executed 24 of 44 SUCCESS (0 secs / 3.438 secs)
[INFO] .PhantomJS 2.1.1 (Windows 8 0.0.0): Executed 25 of 44 SUCCESS (0 secs / 3.571 secs)
[INFO] .PhantomJS 2.1.1 (Windows 8 0.0.0): Executed 26 of 44 SUCCESS (0 secs / 3.723 secs)
[INFO] .PhantomJS 2.1.1 (Windows 8 0.0.0): Executed 27 of 44 SUCCESS (0 secs / 3.871 secs)
[INFO] .PhantomJS 2.1.1 (Windows 8 0.0.0): Executed 28 of 44 SUCCESS (0 secs / 4.024 secs)
[INFO] .PhantomJS 2.1.1 (Windows 8 0.0.0): Executed 29 of 44 SUCCESS (0 secs / 4.142 secs)
[INFO] .PhantomJS 2.1.1 (Windows 8 0.0.0): Executed 30 of 44 SUCCESS (0 secs / 4.26 secs)
[INFO] .PhantomJS 2.1.1 (Windows 8 0.0.0): Executed 31 of 44 SUCCESS (0 secs / 4.422 secs)
[INFO] .PhantomJS 2.1.1 (Windows 8 0.0.0): Executed 32 of 44 SUCCESS (0 secs / 4.606 secs)
[INFO] .PhantomJS 2.1.1 (Windows 8 0.0.0): Executed 33 of 44 SUCCESS (0 secs / 4.765 secs)
[INFO] .PhantomJS 2.1.1 (Windows 8 0.0.0): Executed 34 of 44 SUCCESS (0 secs / 4.9 secs)
[INFO] .PhantomJS 2.1.1 (Windows 8 0.0.0): Executed 35 of 44 SUCCESS (0 secs / 5.04 secs)
[INFO] .PhantomJS 2.1.1 (Windows 8 0.0.0): Executed 36 of 44 SUCCESS (0 secs / 5.16 secs)
[INFO] .PhantomJS 2.1.1 (Windows 8 0.0.0): Executed 37 of 44 SUCCESS (0 secs / 5.281 secs)
[INFO] .PhantomJS 2.1.1 (Windows 8 0.0.0): Executed 38 of 44 SUCCESS (0 secs / 5.432 secs)
[INFO] .PhantomJS 2.1.1 (Windows 8 0.0.0): Executed 39 of 44 SUCCESS (0 secs / 5.57 secs)
[INFO] .PhantomJS 2.1.1 (Windows 8 0.0.0): Executed 40 of 44 SUCCESS (0 secs / 5.733 secs)
[INFO] .PhantomJS 2.1.1 (Windows 8 0.0.0): Executed 41 of 44 SUCCESS (0 secs / 5.912 secs)
[INFO] .PhantomJS 2.1.1 (Windows 8 0.0.0): Executed 42 of 44 SUCCESS (0 secs / 6.039 secs)
[INFO] .PhantomJS 2.1.1 (Windows 8 0.0.0): Executed 43 of 44 SUCCESS (0 secs / 6.169 secs)
[INFO] .PhantomJS 2.1.1 (Windows 8 0.0.0): Executed 44 of 44 SUCCESS (0 secs / 6.307 secs)
[INFO] 
[INFO] PhantomJS 2.1.1 (Windows 8 0.0.0): Executed 44 of 44 SUCCESS (6.327 secs / 6.307 secs)
[INFO] PhantomJS 2.1.1 (Windows 8 0.0.0): Executed 44 of 44 SUCCESS (6.327 secs / 6.307 secs)
[INFO] 
[INFO] =============================== Coverage summary ===============================
[INFO] Statements   : 67.2% ( 1043/1552 )
[INFO] Branches     : 30.17% ( 73/242 )
[INFO] Functions    : 44.5% ( 186/418 )
[INFO] Lines        : 64.97% ( 909/1399 )
[INFO] ================================================================================
[INFO] Done in 65.44s.
[INFO] 
[INFO] --- maven-war-plugin:2.6:war (default-war) @ emirates-grp-online-shop ---
[INFO] Packaging webapp
[INFO] Assembling webapp [emirates-grp-online-shop] in [e:\projets\issues\dearnani\EmiratesGrpOnlineShop\target\emirates-grp-online-shop-0.0.1-SNAPSHOT]
[INFO] Processing war project
[INFO] Copying webapp resources [e:\projets\issues\dearnani\EmiratesGrpOnlineShop\target\www]
[INFO] Webapp assembled in [1975 msecs]
[INFO] Building war: e:\projets\issues\dearnani\EmiratesGrpOnlineShop\target\emirates-grp-online-shop-0.0.1-SNAPSHOT.war
[INFO] 
[INFO] --- spring-boot-maven-plugin:1.5.6.RELEASE:repackage (default) @ emirates-grp-online-shop ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 06:07 min
[INFO] Finished at: 2017-08-28T00:40:21+02:00
[INFO] Final Memory: 58M/505M
[INFO] ------------------------------------------------------------------------
</pre>
</details>
