### ISSUE TITLE
The first initialization of the database (define with jdl-studio) with mvnw throw a liquibase exception

### ISSUE THREAD

**Issue by chris2338** [jhipster/generator-jhipster#3605] opened 2016-05-17 09:17 UTC
##### **Overview of the issue**

The first initialization of the database (define with jdl-studio) throw this exception :
```

2016-05-17 10:29:29.566  WARN 10420 --- [  fb-Executor-1] c.p.f.c.liquibase.AsyncSpringLiquibase   : Starting Liquibase asynchronously, your database might not be ready at startup!
2016-05-17 10:29:37.535 ERROR 10420 --- [  fb-Executor-1] liquibase                                : classpath:config/liquibase/master.xml: classpath:config/liquibase/changelog/00000000000000_initial_schema.xml::00000000000001::jhipster: Change Set classpath:config/liquibase/changelog/00000000000000_initial_schema.xml::00000000000001::jhipster failed.  Error: La cl+® est trop longue. Longueur maximale: 1000 [Failed SQL: ALTER TABLE fb.jhi_social_user_connection ADD UNIQUE (user_id, provider_id, provider_user_id)]

liquibase.exception.DatabaseException: La cl+® est trop longue. Longueur maximale: 1000 [Failed SQL: ALTER TABLE fb.jhi_social_user_connection ADD UNIQUE (user_id, provider_id, provider_user_id)]
        at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:301)
        at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:55)
        at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:107)
        at liquibase.database.AbstractJdbcDatabase.execute(AbstractJdbcDatabase.java:1251)
        at liquibase.database.AbstractJdbcDatabase.executeStatements(AbstractJdbcDatabase.java:1234)
        at liquibase.changelog.ChangeSet.execute(ChangeSet.java:554)
        at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:51)
        at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:73)
        at liquibase.Liquibase.update(Liquibase.java:212)
        at liquibase.Liquibase.update(Liquibase.java:192)
        at liquibase.integration.spring.SpringLiquibase.performUpdate(SpringLiquibase.java:434)
        at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:391)
        at com.pivacom.fb.config.liquibase.AsyncSpringLiquibase.initDb(AsyncSpringLiquibase.java:66)
        at com.pivacom.fb.config.liquibase.AsyncSpringLiquibase.lambda$afterPropertiesSet$38(AsyncSpringLiquibase.java:49)
        at com.pivacom.fb.config.liquibase.AsyncSpringLiquibase$$Lambda$35/2113909232.run(Unknown Source)
        at com.pivacom.fb.async.ExceptionHandlingAsyncTaskExecutor.lambda$createWrappedRunnable$24(ExceptionHandlingAsyncTaskExecutor.java:47)
        at com.pivacom.fb.async.ExceptionHandlingAsyncTaskExecutor$$Lambda$36/1161086484.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: La cl+® est trop longue. Longueur maximale: 1000
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
        at com.mysql.jdbc.Util.getInstance(Util.java:387)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:939)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3878)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3814)
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2478)
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2625)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2547)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2505)
        at com.mysql.jdbc.StatementImpl.executeInternal(StatementImpl.java:840)
        at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:740)
        at com.zaxxer.hikari.pool.ProxyStatement.execute(ProxyStatement.java:95)
        at com.zaxxer.hikari.pool.HikariProxyStatement.execute(HikariProxyStatement.java)
        at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:299)
        ... 19 common frames omitted

2016-05-17 10:29:37.546 ERROR 10420 --- [  fb-Executor-1] c.p.f.c.liquibase.AsyncSpringLiquibase   : Liquibase could not start correctly, your database is NOT ready: Migration failed for change set classpath:config/liquibase/changelog/00000000000000_initial_schema.xml::00000000000001::jhipster:
     Reason: liquibase.exception.DatabaseException: La cl+® est trop longue. Longueur maximale: 1000 [Failed SQL: ALTER TABLE fb.jhi_social_user_connection ADD UNIQUE (user_id, provider_id, provider_user_id)]

liquibase.exception.MigrationFailedException: Migration failed for change set classpath:config/liquibase/changelog/00000000000000_initial_schema.xml::00000000000001::jhipster:
     Reason: liquibase.exception.DatabaseException: La cl+® est trop longue. Longueur maximale: 1000 [Failed SQL: ALTER TABLE fb.jhi_social_user_connection ADD UNIQUE (user_id, provider_id, provider_user_id)]
        at liquibase.changelog.ChangeSet.execute(ChangeSet.java:590)
        at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:51)
        at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:73)
        at liquibase.Liquibase.update(Liquibase.java:212)
        at liquibase.Liquibase.update(Liquibase.java:192)
        at liquibase.integration.spring.SpringLiquibase.performUpdate(SpringLiquibase.java:434)
        at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:391)
        at com.pivacom.fb.config.liquibase.AsyncSpringLiquibase.initDb(AsyncSpringLiquibase.java:66)
        at com.pivacom.fb.config.liquibase.AsyncSpringLiquibase.lambda$afterPropertiesSet$38(AsyncSpringLiquibase.java:49)
        at com.pivacom.fb.config.liquibase.AsyncSpringLiquibase$$Lambda$35/2113909232.run(Unknown Source)
        at com.pivacom.fb.async.ExceptionHandlingAsyncTaskExecutor.lambda$createWrappedRunnable$24(ExceptionHandlingAsyncTaskExecutor.java:47)
        at com.pivacom.fb.async.ExceptionHandlingAsyncTaskExecutor$$Lambda$36/1161086484.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: liquibase.exception.DatabaseException: La cl+® est trop longue. Longueur maximale: 1000 [Failed SQL: ALTER TABLE fb.jhi_social_user_connection ADD UNIQUE (user_id, provider_id, provider_user_id)]
        at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:301)
        at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:55)
        at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:107)
        at liquibase.database.AbstractJdbcDatabase.execute(AbstractJdbcDatabase.java:1251)
        at liquibase.database.AbstractJdbcDatabase.executeStatements(AbstractJdbcDatabase.java:1234)
        at liquibase.changelog.ChangeSet.execute(ChangeSet.java:554)
        ... 14 common frames omitted
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: La cl+® est trop longue. Longueur maximale: 1000
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
        at com.mysql.jdbc.Util.getInstance(Util.java:387)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:939)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3878)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3814)
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2478)
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2625)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2547)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2505)
        at com.mysql.jdbc.StatementImpl.executeInternal(StatementImpl.java:840)
        at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:740)
        at com.zaxxer.hikari.pool.ProxyStatement.execute(ProxyStatement.java:95)
        at com.zaxxer.hikari.pool.HikariProxyStatement.execute(HikariProxyStatement.java)
        at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:299)
        ... 19 common frames omitted
```

##### **JHipster Version(s)** 

3.3.0

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 

```
{
  "generator-jhipster": {
    "jhipsterVersion": "3.3.0",
    "baseName": "fb",
    "packageName": "com.pivacom.fb",
    "packageFolder": "com/pivacom/fb",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "no",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": "no",
    "buildTool": "maven",
    "enableSocialSignIn": true,
    "jwtSecretKey": "secret",
    "useSass": false,
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling",
      "cucumber",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "fr",
    "languages": [
      "fr",
      "en"
    ]
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory** 

I think it better for you to have my file fb-jdl.jh:

```
enum FeedbackStates {
    OPENED, CLOSED, REMOVED
}

enum Roles {
    ADMIN, WRITER, READER
}

entity Feedback {	
	title String required,
    description String,
    state FeedbackStates required
}

entity Subject {
    title String required
}

entity Post {	
    text String required
}

entity Tag {	
    name String required, 
}

entity UserFeedback {
	role Roles required
}

relationship OneToMany {
	Feedback{tags} to Tag
}

relationship ManyToMany {
	Tag{subjects} to Subject{tags}
}

relationship OneToMany {
	Subject{posts} to Post
}

relationship OneToMany {
	Feedback{subjects} to Subject
}

relationship OneToMany {
	User{feedbacks} to UserFeedback
}

relationship OneToOne {
  UserFeedback{feedback} to Feedback{userFeedback}
}

paginate Feedback with pagination

paginate User with pagination

paginate Subject with pagination

paginate Post with pagination

paginate Role with pagination

paginate Tag with pagination
```

##### **Browsers and Operating System** 

Windows 7 64bits

##### **Reproduce the error** 

Very simple:
- create the jhipster project
- yo jhipster:import-jdl fb-jdl.jh
- créate the mysql database  (the version on mysql is 5.7.9)
- launch mvnw

That's all !

##### **Related issues** 

My issue is quite similar with this one: 

[max key length is 767 bytes](https://github.com/jhipster/generator-jhipster/issues/307)

##### **Suggest a Fix** 

I don't know where could be the problem in the file config/liquibase/changelog/00000000000000_initial_schema.xml:

```
<?xml version="1.0" encoding="utf-8"?>
<databaseChangeLog
    xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.4.xsd">

    <property name="now" value="now()" dbms="mysql,h2"/>
    <property name="now" value="current_timestamp" dbms="postgresql"/>
    <property name="now" value="sysdate" dbms="oracle"/>

    <property name="autoIncrement" value="true" dbms="mysql,h2,postgresql,oracle"/>

    <changeSet id="00000000000000" author="jhipster" dbms="postgresql,oracle">
        <createSequence sequenceName="hibernate_sequence" startValue="1000" incrementBy="1"/>
    </changeSet>

    <!--
        JHipster core tables.
        The initial schema has the '00000000000001' id, so that it is over-written if we re-generate it.
    -->
    <changeSet id="00000000000001" author="jhipster">
        
        <createTable tableName="jhi_user">
            <column name="id" type="bigint" autoIncrement="${autoIncrement}">
                <constraints primaryKey="true" nullable="false"/>
            </column>
            <column name="login" type="varchar(100)">
                <constraints unique="true" nullable="false"/>
            </column>
            <column name="password_hash" type="varchar(60)"/>
            <column name="first_name" type="varchar(50)"/>
            <column name="last_name" type="varchar(50)"/>
            <column name="email" type="varchar(100)">
                <constraints unique="true" nullable="true"/>
            </column>
            <column name="activated" type="boolean" valueBoolean="false">
                <constraints nullable="false" />
            </column>
            <column name="lang_key" type="varchar(5)"/>
            <column name="activation_key" type="varchar(20)"/>
            <column name="reset_key" type="varchar(20)"/>
            <column name="created_by" type="varchar(50)">
                <constraints nullable="false"/>
            </column>
            <column name="created_date" type="timestamp" defaultValueDate="${now}">
                <constraints nullable="false"/>
            </column>
            <column name="reset_date" type="timestamp">
                <constraints nullable="true"/>
            </column>
            <column name="last_modified_by" type="varchar(50)"/>
            <column name="last_modified_date" type="timestamp"/>
        </createTable>
        
        <createIndex indexName="idx_user_login"
            tableName="jhi_user"
            unique="true">
            <column name="login" type="varchar(100)"/>
        </createIndex>

        <createIndex indexName="idx_user_email"
            tableName="jhi_user"
            unique="true">
            <column name="email" type="varchar(100)"/>
        </createIndex>
        
        <createTable tableName="jhi_authority">
            <column name="name" type="varchar(50)">
                <constraints primaryKey="true" nullable="false"/>
            </column>
        </createTable>

        <createTable tableName="jhi_user_authority">
            <column name="user_id" type="bigint">
                <constraints nullable="false"/>
            </column>
            <column name="authority_name" type="varchar(50)">
                <constraints nullable="false"/>
            </column>
        </createTable>

        <addPrimaryKey columnNames="user_id, authority_name" tableName="jhi_user_authority"/>

        <addForeignKeyConstraint baseColumnNames="authority_name"
                                 baseTableName="jhi_user_authority"
                                 constraintName="fk_authority_name"
                                 referencedColumnNames="name"
                                 referencedTableName="jhi_authority"/>

        <addForeignKeyConstraint baseColumnNames="user_id"
                                 baseTableName="jhi_user_authority"
                                 constraintName="fk_user_id"
                                 referencedColumnNames="id"
                                 referencedTableName="jhi_user"/>
        <loadData encoding="UTF-8"
                  file="config/liquibase/users.csv"
                  separator=";"
                  tableName="jhi_user">
            <column name="activated" type="boolean"/>
            <column name="created_date" type="timestamp"/>
        </loadData>
        <dropDefaultValue tableName="jhi_user" columnName="created_date" columnDataType="datetime"/>

        <loadData encoding="UTF-8"
                  file="config/liquibase/authorities.csv"
                  separator=";"
                  tableName="jhi_authority"/>

        <loadData encoding="UTF-8"
                  file="config/liquibase/users_authorities.csv"
                  separator=";"
                  tableName="jhi_user_authority"/>
        
        <createTable tableName="jhi_persistent_audit_event">
            <column name="event_id" type="bigint" autoIncrement="${autoIncrement}">
                <constraints primaryKey="true" nullable="false"/>
            </column>
            <column name="principal" type="varchar(255)">
                <constraints nullable="false" />
            </column>
            <column name="event_date" type="timestamp"/>
            <column name="event_type" type="varchar(255)"/>
        </createTable>

        <createTable tableName="jhi_persistent_audit_evt_data">
            <column name="event_id" type="bigint">
                <constraints nullable="false"/>
            </column>
            <column name="name" type="varchar(255)">
                <constraints nullable="false"/>
            </column>
            <column name="value" type="varchar(255)"/>
        </createTable>
        <addPrimaryKey columnNames="event_id, name" tableName="jhi_persistent_audit_evt_data"/>

        <createIndex indexName="idx_persistent_audit_event"
                     tableName="jhi_persistent_audit_event"
                     unique="false">
            <column name="principal" type="varchar(255)"/>
            <column name="event_date" type="timestamp"/>
        </createIndex>

        <createIndex indexName="idx_persistent_audit_evt_data"
                     tableName="jhi_persistent_audit_evt_data"
                     unique="false">
            <column name="event_id" type="bigint"/>
        </createIndex>

        <addForeignKeyConstraint baseColumnNames="event_id"
                                 baseTableName="jhi_persistent_audit_evt_data"
                                 constraintName="fk_evt_pers_audit_evt_data"
                                 referencedColumnNames="event_id"
                                 referencedTableName="jhi_persistent_audit_event"/>
    
        <!-- Social -->
        <createTable tableName="jhi_social_user_connection">
            <column name="id" type="bigint" autoIncrement="${autoIncrement}">
                <constraints primaryKey="true" nullable="false"/>
            </column>
            <column name="user_id" type="varchar(255)">
                <constraints nullable="false"/>
            </column>
            <column name="provider_id" type="varchar(255)">
                <constraints nullable="false"/>
            </column>
            <column name="provider_user_id" type="varchar(255)">
                <constraints nullable="false"/>
            </column>
            <column name="rank" type="bigint">
                <constraints nullable="false"/>
            </column>
            <column name="display_name" type="varchar(255)"/>
            <column name="profile_url" type="varchar(255)"/>
            <column name="image_url" type="varchar(255)"/>
            <column name="access_token" type="varchar(255)">
                <constraints nullable="false"/>
            </column>
            <column name="secret" type="varchar(255)"/>
            <column name="refresh_token" type="varchar(255)"/>
            <column name="expire_time" type="bigint"/>
        </createTable>

        <addUniqueConstraint tableName="jhi_social_user_connection" columnNames="user_id, provider_id, provider_user_id"/>

        <addUniqueConstraint tableName="jhi_social_user_connection" columnNames="user_id, provider_id, rank"/>
    
    </changeSet>
    
</databaseChangeLog>

```

**Comment by jdubois** [comment] 2016-05-17 10:08
I just tried it without any issue.

- There is an error somewhere in your JDL, the pagination part did an error so I removed some of it
- I ran your code using the current "master" branch, and ran MySQL with Docker using the current mysql.yml file that is provided

So I'm guessing this is something related to your environnement, can you try running MySQL in Docker?
Other option would be that this has been corrected in master, of course. So maybe you could try using our "master" branch, or wait for the next version.

I'm closing this as I can't reproduce, but of course don't hesitate to add comments if you have more information, or if you can help me reproduce.

**Closed by jdubois** 2016-05-17 10:08 UTC

**Comment by chris2338** [comment] 2016-05-18 14:19
You are right. It works well with a MySQL database  in Docker. Thank you for your quick answer!
