### ISSUE TITLE
import-jdl broken because of Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by xetys** [jhipster/generator-jhipster#6347] opened 2017-09-13 21:21 UTC
##### **Overview of the issue**

when generating an entity first time with JDL it breaks with the following message: 

```
TypeError: Cannot convert undefined or null to object
```

it happens because of the changed entity fix in f3b731fcb3ddee74b54375b3c552c7849693c02d

exportToJson returns undefined, which causes the error

##### **Reproduce the error**

Place a JDL in a JHipster microservice and try to import it

##### **Suggest a Fix**

I will PR one..

##### **JHipster Version(s)**

4.8.1 and upstream

- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment] 2017-09-14 08:16
You mean all JDL is broken? This would be a huge problem!

- can you tell me how bad this is?
- yes please do a PR
- I can do a patch release tomorrow, would that be good for you?

**Comment by xetys** [comment] 2017-09-14 09:09
I actually still try to figure out what @deepu105 tried to build. The error happens after a successfully parse and placement of entities. You can 'regenerate' them after import-jdl with the entity subgen. He did an update what makes the import-jdl subgen aware of changed entities. 

My local quickfix ignores this, and then it runs without errors....but for tomorrow I'm not sure wether I can provide a version wich works with updated change, too

**Comment by jdubois** [comment] 2017-09-14 09:45
I just tested with a sample JDL and it works - could you share your JDL, to see if I can reproduce?

**Comment by xetys** [comment] 2017-09-14 11:52
I was running https://github.com/xetys/jhipster-demo-generator to test #5812 yesterday. I will try it on another machine

**Comment by deepu105** [comment] 2017-09-14 19:45
I believe I tested it extensively and it was working well. May be you found some edge case I missed. I dont have time to test now

**Comment by jdubois** [comment] 2017-09-15 08:57
Yes I believe you have an edge case @xetys - if this was fully broken I think (hope!!) we would have more bug reports on this

**Comment by xetys** [comment] 2017-09-17 10:21
Ok, that issue comes because I am still using `yo jhipster` instead of `jhipster` when using the dev edition from git...I should figure out how to config it properly

**Comment by deepu105** [comment] 2017-09-17 10:48
@xetys I don't understand ideally it should behave in the same way regardless of how you execute it

**Comment by gmarziou** [comment] 2017-09-17 13:10
Could it be related to PR #6219 ?

**Comment by pragma81** [comment] 2017-09-17 16:53
Hi,
I guess I have the same problem here.. I just created a new jhipster microservices application and tried to import the  jhipster human resource [example](https://raw.githubusercontent.com/jhipster/jhipster-core/master/lib/dsl/example.jh). However I also tried very simple jdl files with just one entity, and got the same problem.

This is the full error log:
```
Using JHipster version installed locally in current project's node_modules
Executing jhipster:import-jdl hr.jh
Options: 
The jdl is being parsed.
events.js:160
      throw er; // Unhandled 'error' event
      ^
Error: ERROR! 
Error while parsing entities from JDL

at Environment.error (/Users/davideantelmo/Code/spides-workspace/myapp/node_modules/yeoman-environment/lib/environment.js:140:40)
    at constructor.error (/Users/davideantelmo/Code/spides-workspace/myapp/node_modules/generator-jhipster/generators/generator-base.js:1686:18)
    at constructor.parseJDL (/Users/davideantelmo/Code/spides-workspace/myapp/node_modules/generator-jhipster/generators/import-jdl/index.js:108:22)
    at Object.<anonymous> (/Users/davideantelmo/Code/spides-workspace/myapp/node_modules/yeoman-generator/lib/index.js:417:23)
    at /Users/davideantelmo/Code/spides-workspace/myapp/node_modules/run-async/index.js:25:25
    at /Users/davideantelmo/Code/spides-workspace/myapp/node_modules/run-async/index.js:24:19
    at /Users/davideantelmo/Code/spides-workspace/myapp/node_modules/yeoman-generator/lib/index.js:418:9
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
`
```
**My environment:**
macOs Sierra
node 6.11.3
jhipster 4.8.1

**Comment by jdubois** [comment] 2017-09-28 08:57
I'm sorry guys but I need something I can reproduce:

- I used my own `.yo-rc.json` as you don't give me anything here (and I can't guess your config!)
- I used the "human resources" example from @pragma81 

-> no issue at all, this is all working for me

So I'm closing this as I can't reproduce.

**Comment by rmahnovetsky** [comment] 2017-09-29 11:44
I also get the same error. Just installed jhipster only 2 days ago.

`$ jhipster import-jdl ./jhipster-jdl.jh
Using JHipster version installed locally in current project's node_modules
Executing jhipster:import-jdl ./jhipster-jdl.jh
Options: 
The jdl is being parsed.
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: ERROR! 
Error while parsing entities from JDL

    at Environment.error (/Users/rafael/workspace/home-workspace/electricity/node_modules/yeoman-environment/lib/environment.js:140:40)
    at constructor.error (/Users/rafael/workspace/home-workspace/electricity/node_modules/generator-jhipster/generators/generator-base.js:1686:18)
    at constructor.parseJDL (/Users/rafael/workspace/home-workspace/electricity/node_modules/generator-jhipster/generators/import-jdl/index.js:108:22)
    at Object.<anonymous> (/Users/rafael/workspace/home-workspace/electricity/node_modules/yeoman-generator/lib/index.js:417:23)
    at /Users/rafael/workspace/home-workspace/electricity/node_modules/run-async/index.js:25:25
    at Promise (<anonymous>)
    at /Users/rafael/workspace/home-workspace/electricity/node_modules/run-async/index.js:24:19
    at /Users/rafael/workspace/home-workspace/electricity/node_modules/yeoman-generator/lib/index.js:418:9
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)`

.yo-rc.json
[yo-rc.txt](https://github.com/jhipster/generator-jhipster/files/1344195/yo-rc.txt)


anything else you need to debug?

**Comment by jdubois** [comment] 2017-09-29 11:53
Could you give me the whole `jhipster info` input so I'm sure I'm not missing anything? And your JDL file, if that's a different one

**Comment by rmahnovetsky** [comment] 2017-09-29 12:22
I just starting trying out JDL. So I was using the example from http://www.jhipster.tech/jdl-studio/. 
example jdl
[jhipster-jdl.jh.txt](https://github.com/jhipster/generator-jhipster/files/1344290/jhipster-jdl.jh.txt)

jhipster info 
[jhipster info.txt](https://github.com/jhipster/generator-jhipster/files/1344273/jhipster.info.txt)

I could get it to work with the following JDL.
[jhipster-jdl.jh.min.txt](https://github.com/jhipster/generator-jhipster/files/1344299/jhipster-jdl.jh.min.txt)

For me it seems to be a problem with the relationships. As soon as I add any of them back in I get the error. 

HTH. Let me know if you need anything else.

**Comment by deepu105** [comment] 2017-09-29 15:12
What is the node version @rmahnovetsky

**Comment by deepu105** [comment] 2017-09-29 15:23
Ok I was able to reproduce it. let me investigate

**Comment by deepu105** [comment] 2017-09-29 15:31
You are trying to create relationships on a project using mongoDB which is not possible. I will improve the error message to include useful hints

**Closed by deepu105** 2017-09-29 15:31 UTC

**Comment by deepu105** [comment] 2017-09-29 15:38
https://github.com/jhipster/generator-jhipster/commit/62e5192214a26031b0c9d1cff53ff4595f35fda9

**Comment by rmahnovetsky** [comment] 2017-09-29 20:35
thanks mate 👍

**Comment by rmahnovetsky** [comment] 2017-09-30 03:48
Just a thought, would it be worth mentioning in the documentation http://www.jhipster.tech/jdl/ that relationships are not supported for MongoDB?

**Comment by jdubois** [comment] 2017-09-30 09:19
Yes as I see many people having issue with that

**Comment by jeffgrant** [comment] 2017-10-10 17:09
FYI, I just had the same error, but for a different reason, and it was a bit of a pain to track down.

It ended up being my own stupidity due to the fact that I used "Interface" as an entity name.

Looking back at it, obviously Interface is a Java reserved word, but I never thought using it as an entity name would break the import-jdh process because it's a legal Postgres table name.

Just replying here in case someone else has the same issue, as this is one of the top Google search results.

Needless to say it would be quite handy to have more detail in the error message if at all possible.

**Comment by MathieuAA** [comment] 2017-10-10 17:30
It's not stupidity. In this case, the "stupidest" thing would be not to 
do anything. I'll try to further improve error reporting on this front.

Sorry for the inconvenience!

**Comment by jeffgrant** [comment] 2017-10-10 17:33
Not complaining at all... and no need to apologize... it was just a bit of a dive to figure it out and thought I'd share it in case someone else could learn from my experience.

**Comment by thomaschristensen** [comment] 2017-10-16 12:06
It would appear that entities named something that is already in use by the jhipster apps should be avoided. F.ex. creating an entity called "Account" caused this problem to appear. I must admit I haven't looked for the FAQ so that might already be noted there.
