### ISSUE TITLE
Idp data does not sync with local database

### ISSUE THREAD

**Issue by vinayrlimbare** [jhipster/generator-jhipster#11844] opened 2020-05-24 15:16 UTC
##### **Overview of the issue**

With the latest Jhipster code v.6.9.0 using OIDC, the user's data is not getting synced with the Idp. 

##### **Reproduce the error**

Generate Jhipter application with auth as "oauth2" (I used Keycloak). Front end as react and database like Postgres. 
->  Allow registration in the Keycloak admin console.
-> Register a new user. Logout and login back to the application using the newly created user. You see in the logs "Saving user 'Xyz' in local database" but it does not save. 
-> The Postgres data for jhi_user contains previously created 'system' and 'anonymous' entries.

##### **Suggest a Fix**

The method `com.ve.service.UserService#getUserFromAuthentication` is marked as `@Transactional(readOnly = true)`, if the readOnly is made as false or the `@Transactional` annotation is removed, then the user data is synced with Idp and stored in Postgres DB.

##### **JHipster Version(s)**

Jhipster version v6.9.0

##### **JHipster configuration**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.ve"
    },
    "jhipsterVersion": "6.9.0",
    "applicationType": "monolith",
    "baseName": "eventor",
    "packageName": "com.ve",
    "packageFolder": "com/ve",
    "serverPort": "8080",
    "authenticationType": "oauth2",
    "cacheProvider": "caffeine",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "embeddableLaunchScript": false,
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "react",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "creationTimestamp": 1590300101788,
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": false,
    "blueprints": []
  }
}

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_241"
Java(TM) SE Runtime Environment (build 1.8.0_241-b07)
Java HotSpot(TM) 64-Bit Server VM (build 25.241-b07, mixed mode)

git version 2.25.0.windows.1

node: v12.14.1

npm: 6.13.4

yeoman: 3.1.1

Docker version 19.03.1, build 74b1e89e8a

docker-compose version 1.24.1, build 4667896b

##### **Browsers and Operating System**

The browser does not matter at this time. 

-   [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by vishal423** [comment] 2020-05-24 16:17
duplicate of #11836

**Closed by vishal423** 2020-05-24 16:17 UTC
Labels: area: needs-reproduction, theme: OIDC/OAuth2
