### ISSUE TITLE
import-jdl DatabaseType is mandatory

### ISSUE THREAD

**Issue by BurningFist** [jhipster/generator-jhipster#7623] opened 2018-05-14 14:52 UTC
##### **Overview of the issue**

We want to use the application feature of JDL 2.0. We upgraded to Version 5 beta1 and  added the application section from the example on the website. 
This is our directory tree:
```
+ 
 | - gateway
 | - scenedetect
 | - demuxer
 | + model
   | - model.jdl
```

But running `jhipster import-jdl model/model.jdl --force --debug` on the root, the outputs is:
```
Using JHipster version installed globally
DEBUG!  cmd: import-jdl
DEBUG!  args: model/model.jdl, commands: Object, options: Object, _execs: Object, _allowUnknownOption: true, _args: Object, _name: import-jdl, _noHelp: false, parent: Object, _description: Create entities from the JDL file passed in argument, _events: Object, _eventsCount: 1
DEBUG!  opts: argument: Object, desc: Create entities from the JDL file passed in argument
DEBUG!  Arguments found
DEBUG!  cmdArgs: model/model.jdl
Executing jhipster:import-jdl model/model.jdl
Options: force: true, debug: true
The JDL is being parsed.
Writing application configuration files.
DEBUG! Error:
{ name: 'NullPointerException',
  message: 'The JDL object and the database type are both mandatory.',
  prototype: Error
    at new BuildException (~\AppData\Local\Yarn\Data\global\node_modules\jhipster-core\lib\exceptions\exception_factory.js:59:25)
    at Object.parse [as convertToJHipsterJSON] (~\AppData\Local\Yarn\Data\global\node_modules\jhipster-core\lib\parser\entity_parser.js:57:11)
    at module.exports.parseJDL (~\AppData\Local\Yarn\Data\global\node_modules\generator-jhipster\generators\import-jdl\index.js:120:46)
    at Object.<anonymous> (~\AppData\Local\Yarn\Data\global\node_modules\yeoman-generator\lib\index.js:399:25)
    at ~\AppData\Local\Yarn\Data\global\node_modules\run-async\index.js:25:25
    at new Promise (<anonymous>)
    at ~\AppData\Local\Yarn\Data\global\node_modules\run-async\index.js:24:19
    at self.env.runLoop.add.completed (~\AppData\Local\Yarn\Data\global\node_modules\yeoman-generator\lib\index.js:400:11)
    at runCallback (timers.js:763:18)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate (timers.js:716:5) }
NullPointerException: The JDL object and the database type are both mandatory.
events.js:165
      throw er; // Unhandled 'error' event
      ^

Error: ERROR! Error while parsing applications and entities from the JDL [object Object]
    at Environment.error (~\AppData\Local\Yarn\Data\global\node_modules\yeoman-environment\lib\environment.js:157:40)
    at module.exports.error (~\AppData\Local\Yarn\Data\global\node_modules\generator-jhipster\generators\generator-base.js:1970:18)
    at module.exports.parseJDL (~\AppData\Local\Yarn\Data\global\node_modules\generator-jhipster\generators\import-jdl\index.js:155:26)
    at Object.<anonymous> (~\AppData\Local\Yarn\Data\global\node_modules\yeoman-generator\lib\index.js:399:25)
    at ~\AppData\Local\Yarn\Data\global\node_modules\run-async\index.js:25:25
    at new Promise (<anonymous>)
    at ~\AppData\Local\Yarn\Data\global\node_modules\run-async\index.js:24:19
    at self.env.runLoop.add.completed (~\AppData\Local\Yarn\Data\global\node_modules\yeoman-generator\lib\index.js:400:11)
    at runCallback (timers.js:763:18)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate (timers.js:716:5)
Emitted 'error' event at:
    at Immediate.setImmediate (~\AppData\Local\Yarn\Data\global\node_modules\yeoman-generator\lib\index.js:406:18)
    at runCallback (timers.js:763:18)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate (timers.js:716:5)
```

Running `jhipster import-jdl ../model/model.jdl --force --debug` on the gateway, witch contains the old monolitic application, the outputs is:
```
Using JHipster version installed locally in current project's node_modules
DEBUG!  cmd: import-jdl
DEBUG!  args: ../model/model.jdl, commands: Object, options: Object, _execs: Object, _allowUnknownOption: true, _args: Object, _name: import-jdl, _noHelp: false, parent: Object, _description: Create entities from the JDL file passed in argument, _events: Object, _eventsCount: 1
DEBUG!  opts: argument: Object, desc: Create entities from the JDL file passed in argument
DEBUG!  Arguments found
DEBUG!  cmdArgs: ../model/model.jdl
Executing jhipster:import-jdl ../model/model.jdl
Options: force: true, debug: true
The JDL is being parsed.
Writing application configuration files.
Writing entity JSON files.
Updated entities are: Translatable,SpeechToTextJob.
Generating applications.
Generating application undefined.
Generating application undefined.
Generating application undefined.
Generating entities.
events.js:165
      throw er; // Unhandled 'error' event
      ^

Error: ERROR! While generating applications and entities from the parsed JDL
TypeError: Cannot read property 'forEach' of undefined
    at Environment.error (~\gateway\node_modules\yeoman-environment\lib\environment.js:157:40)
    at module.exports.error (~\gateway\node_modules\generator-jhipster\generators\generator-base.js:1970:18)
    at module.exports.generateEntities (~\gateway\node_modules\generator-jhipster\generators\import-jdl\index.js:192:26)
    at Object.<anonymous> (~\gateway\node_modules\yeoman-generator\lib\index.js:399:25)
    at ~\gateway\node_modules\run-async\index.js:25:25
    at new Promise (<anonymous>)
    at ~\gateway\node_modules\run-async\index.js:24:19
    at self.env.runLoop.add.completed (~\gateway\node_modules\yeoman-generator\lib\index.js:400:11)
    at runCallback (timers.js:763:18)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate (timers.js:716:5)
Emitted 'error' event at:
    at Immediate.setImmediate (~\gateway\node_modules\yeoman-generator\lib\index.js:406:18)
    at runCallback (timers.js:763:18)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate (timers.js:716:5)
```

##### **Motivation for or Use Case**

We can't use the version 5 Generator.

##### **Reproduce the error**

- setup the dirctory tree as descriped
- running `jhipster import-jdl model/model.jdl --force --debug`
- running `jhipster import-jdl ../model/model.jdl --force --debug` 

##### **JHipster Version(s)**
Using JHipster version installed locally in current project's node_modules
Executing jhipster:info
Options:
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
gateway@0.0.0 ~\gateway
`-- generator-jhipster@5.0.0-beta.1

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "entities": [
    "Translatable",
    "SpeechToTextJob"
  ],
  "generator-jhipster": {
    "applicationType": "gateway",
    "clientPackageManager": "yarn",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "enableHibernateCache": true,
    "enableSwaggerCodegen": false,
    "enableTranslation": true,
    "jhiPrefix": "jhi",
    "languages": [
      "en",
      "fr"
    ],
    "messageBroker": false,
    "nativeLanguage": "en",
    "packageName": "com.company",
    "packageFolder": "com/company",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "serviceDiscoveryType": false,
    "skipClient": false,
    "skipServer": false,
    "testFrameworks": [],
    "useSass": false,
    "websocket": false,
    "baseName": "gateway",
    "authenticationType": "jwt",
    "buildTool": "maven",
    "cacheProvider": "ehcache",
    "clientFramework": "angularX",
    "jwtSecretKey": "replaced-by-jhipster-info",
    "serverPort": "8080",
    "skipUserManagement": false,
    "jhipsterVersion": "5.0.0-beta.1"
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
application {
	config {
		baseName gateway,
		path "../",
		applicationType gateway
		databaseType sql
		packageName com.company
	}
	entities *
}

application {
	config {
		baseName demuxer,
		path "../",
		applicationType microservice
		prodDatabaseType no
		packageName com.company.demux
	}
	entities *
}

application {
	config {
		baseName sceneDetection,
		path "../",
		applicationType microservice
		prodDatabaseType no
		packageName com.company.scene
	}
	entities *
}

entity Translatable {
	name String required
	file Blob required
}

entity SpeechToTextJob {
	recognizedText TextBlob
	errorText String maxlength(2000)
}

relationship ManyToOne {
	 SpeechToTextJob{toRecognize(name)} to Translatable{recognizeJob(withSystem) required}
}

service SpeechToTextJob with serviceClass

paginate Translatable, SpeechToTextJob with pagination

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_162"
Java(TM) SE Runtime Environment (build 1.8.0_162-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.162-b12, mixed mode)

git version 2.16.2.windows.1

node: v9.11.1

npm: 5.6.0

yeoman: 2.0.1

yarn: 1.5.1

Docker version 18.03.1-ce, build 9ee9f40

docker-compose version 1.21.1, build 7641a569

Congratulations, JHipster execution is complete!

##### **Browsers and Operating System**
On Windows 10 Version 10.0.16299.248

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment] 2018-05-14 14:55
Sorry, I know this is broken cc @deepu105 @MathieuAA - we need to remove the documentation for the moment, this is misleading.

@BurningFist it's probably not very complicated to have this working, but we just don't have the bandwidth at the moment... Tomorrow we have 1 day to work on JHipster at my company, we'll see if we can help.

**Comment by MathieuAA** [comment] 2018-05-14 15:07
It's fixed in an unstable branch. I'll try to do a release when I have the time

**Comment by MathieuAA** [comment] 2018-05-14 18:46
@jdubois You can focus on more important tasks, this one is almost done (and I'm quite confident about this).

**Comment by jdubois** [comment] 2018-05-14 18:52
@MathieuAA yes but the issue is that I wanted to do a release tomorrow :-P
What could I do to help you release? Do you want to have lunch with the Ippon team tomorrow noon?

**Comment by MathieuAA** [comment] 2018-05-14 19:52
@jdubois I won't be available until next week, I can only work remotely this week.
As you previously said, it's better to release v5 when you want, have minor/patch versions afterwards.
As I said, I'm nearly done but not done enough for tomorrow. There's a branch on JCore ("fix-application-gen"), with a fix for application generation. Basically, the issue is this:
  - the DocumentParser (the thing that generates a JDL object) requires a database type (even if we generate applications)
  - I've removed the need for it, removed every business check done here to put it in a separate class that can handle applications, entities, everything
  - I'm working on a class that does what the subgen does so that the subgen will call the class and voilà (I'm testing the class right now).

It's better to update the doc so that I can properly assert that my solution works.

**Comment by jdubois** [comment] 2018-05-15 10:11
Thanks @MathieuAA - I'll revert the documentation temporarily and link it here.

Sorry @BurningFist I thought this was working fine, but it's not ready yet.

**Comment by jdubois** [comment] 2018-05-15 10:19
Closing as the documentation is reverted

**Closed by jdubois** 2018-05-15 10:19 UTC
