### ISSUE TITLE
JHipster 5.8.0: Language switch broken, only updates page title

### ISSUE THREAD

**Issue by ksilz** [jhipster/generator-jhipster#9121] opened 2019-01-26 07:22 UTC
##### **Overview of the issue**

I create a new monolithic SQL application (H2 file-based / PostgreSQL) with Gradle as the build system, German as the main language and English as the secondary one. When I use the language menu of the application to switch to English, only the page title changes; the main contents remains in German.

![jhipster 5 8 0 broken language switch](https://user-images.githubusercontent.com/1061209/51783874-feebca80-2140-11e9-98e0-3c38c611458d.gif)

##### **Motivation for or Use Case**

If only the page title switches the language, then the internationalization features is not working.

##### **Reproduce the error**

**Steps**
- Create a new monolithic SQL application with Gradle as the build system, German as the main language and English as the secondary one.
- Run `./gradlew` to start the application.
- Open the application at http://localhost:8080.
- In the menu bar, click on _Sprache_ and then select _English_.

**Expected Result**
The page title, menu bar and the page content all switch to English.

**Actual Result**
Only the page title switches to English, the menu bar and the page content remain in Germain.

##### **Related issues**

I couldn't find any.

##### **Suggest a Fix**

* I reproduced this with Firefox and Chrome. In Firefox, I emptied the browser cache (both cookies & files) and restarted the browser - the error still showed.
* Both Firefox and Chrome don't show an error in the browser console.

##### **JHipster Version(s)**

5.8.0

##### **JHipster Version(s)**

```
language-switch@0.0.0 /Users/karsten/workspaces/me/services/jump-start-project/test/jhipster-sample-5
└── generator-jhipster@5.8.0 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
    "generator-jhipster": {
        "promptValues": {
            "packageName": "com.mycompany.myapp",
            "nativeLanguage": "de"
        },
        "jhipsterVersion": "5.8.0",
        "applicationType": "monolith",
        "baseName": "languageSwitch",
        "packageName": "com.mycompany.myapp",
        "packageFolder": "com/mycompany/myapp",
        "serverPort": "8080",
        "authenticationType": "session",
        "cacheProvider": "ehcache",
        "enableHibernateCache": true,
        "websocket": "spring-websocket",
        "databaseType": "sql",
        "devDatabaseType": "h2Disk",
        "prodDatabaseType": "postgresql",
        "searchEngine": false,
        "messageBroker": false,
        "serviceDiscoveryType": false,
        "buildTool": "gradle",
        "enableSwaggerCodegen": false,
        "rememberMeKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
        "clientFramework": "angularX",
        "useSass": false,
        "clientPackageManager": "npm",
        "testFrameworks": [],
        "jhiPrefix": "jhi",
        "entitySuffix": "",
        "dtoSuffix": "DTO",
        "otherModules": [],
        "enableTranslation": true,
        "nativeLanguage": "de",
        "languages": ["de", "en"]
    }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

openjdk version "1.8.0_202"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_202-b08)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.202-b08, mixed mode)

git version 2.20.1

node: v10.15.0

npm: 6.4.1

Docker version 18.09.1, build 4c52b90

docker-compose version 1.23.2, build 1110ad01

##### **Browsers and Operating System**

- macOS Mojava 10.14.3
- Chrome 71.0.3578.98 (Official Build) (64-Bit) 
- Firefox 64.0.2 (64-Bit)

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by atomfrede** [comment] 2019-01-26 08:58
It also looks like the footer translation is not found.

**Comment by pascalgrimaud** [comment] 2019-01-26 12:16
I confirm the issue.
I couldn't reproduce with Vue.js or React, so it only concerns Angular.
I couldn't reproduce with v5.7.2 and Angular app, so it's probably related to the changes concerned by Translation directive.

**Comment by vishal423** [comment] 2019-01-26 12:50
I did quick check and indeed its due to recent changes in the translate directive. I think `ngOnChanges` wouldn't be called as there wouldn't be any input change.

**Comment by wmarques** [comment] 2019-01-27 20:03
I'm checking this

**Comment by wmarques** [comment] 2019-01-27 20:18
Should be fixed by https://github.com/jhipster/ng-jhipster/pull/90

**Closed** 2019-01-28 09:15 UTC
Labels: angular, bug :bug:
