### ISSUE TITLE
import-jdl forces generation of all entities irrespective of which ones actually changed

### ISSUE THREAD

**Issue by vraravam** [jhipster/generator-jhipster#9837] opened 2019-06-01 16:19 UTC
##### **Overview of the issue**
I made a change in my `.jh` file, and ran the `jhipster import-jdl` command - since I only added a single attribute to one of the entities, I expected it to figure that out and only generate the files pertaining to that one entity.

##### **Motivation for or Use Case**

I was trying to add a new attribute to an existing entity.

##### **Reproduce the error**

* Have a codebase that was previously generated with some entities.
* Add a single property to one of the existing entities
* Rerun the `import-jdl` command

##### **Browsers and Operating System**

-   [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by vraravam** [comment] 2019-06-01 16:19
What I also accidentally figured out was that the presence of the `application` config block inside the `jh` file causes this behavior.

**Comment by pascalgrimaud** [comment] 2019-06-01 18:08
Can you post your JDL file plz ? Before your modification, and after. So it will be easier to reproduce your use case.

**Comment by ruddell** [comment] 2019-06-01 18:09
Duplicate of https://github.com/jhipster/generator-jhipster/issues/8880, there's also a PR in progress to fix this

As a workaround, you can pass the `--ignore-application` flag when importing jdl.

**Closed by ruddell** 2019-06-01 18:09 UTC
Labels: area: waiting for information, theme: JDL
