### ISSUE TITLE
Console error in User management Angular 4

### ISSUE THREAD

**Issue by frank8559** [jhipster/generator-jhipster#6593] opened 2017-10-25 12:11 UTC
##### **Overview of the issue**

Hello, a console error is thrown when user create dialog is opened in gateway. Doesn’t seem to cause any issue.

##### **Reproduce the error**
Create an app with jwt, run ./mvnw and open localhost:8080 and go to user management entity. Open user create dialog and look at console.

`ERROR Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'undefined'. Current value: 'userManagement.home.createOrEditLabel` ...

I can't display the full log error and configuration to security restriction.

##### **Related issues**

#5985 

##### **JHipster Version(s)**

4.10

##### **Browsers and Operating System**

Windows 10, centos 7
Firefox and chrome

**Comment by jdubois** [comment] 2017-10-25 12:17
Thanks for the bug report - I understand it's not your fault, but that's really not nice from your company to make us have incomplete bug reports because of their security restrictions. We give them a great tool for free, and we just want to have enough information to help you (still for free).

Anyway this should be closed as you don't respect the guidelines, but once again I totally understand it's not your fault and I'm pretty sure you found something interesting -> let's try to reproduce

**Comment by frank8559** [comment] 2017-10-25 13:16
I asked for a procedure, but it takes a lot of time. (French administration requires: D)
At the Ministry of Defense, we are completely disconnected from the internet, it is not easy to respect the guideline. I can't connect a USB key to my internet station to transfer information. And updating jhipster can be complicated..so test the master branch for the moment I don't even try: D
I just submit the anomalies that I detect on a freshly generated application. I can't  use my usual github account to submit anomalies ...
I hope that eventually, I could submit all the information and make PR .. a day..perhaps
And if it does not move forward, I'll try to reproduce the anomalies at home to submit them in my name.

**Comment by jdubois** [comment] 2017-10-25 13:23
Oh I had no idea you were working for the French administration! Once again, I perfectly understand... But things are changing there, believe me :-)

**Comment by nikersch** [comment] 2017-10-30 23:53
Sorry to hijack your issue.  Have currently the same problem, I attach the console log.

Browser: Chrome
OS: Windows 10


`UserMgmtDialogComponent.html:1 ERROR Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'undefined'. Current value: 'userManagement.home.createOrEditLabel'. It seems like the view has been created after its parent and its children have been dirty checked. Has it been created in a change detection hook ?
    at viewDebugError (core.es5.js?de3d:8420)
    at expressionChangedAfterItHasBeenCheckedError (core.es5.js?de3d:8398)
    at checkBindingNoChanges (core.es5.js?de3d:8562)
    at checkNoChangesNodeInline (core.es5.js?de3d:12423)
    at checkNoChangesNode (core.es5.js?de3d:12397)
    at debugCheckNoChangesNode (core.es5.js?de3d:13174)
    at debugCheckDirectivesFn (core.es5.js?de3d:13076)
    at Object.View_UserMgmtDialogComponent_0._co [as updateDirectives] (UserMgmtDialogComponent.html:1)
    at Object.debugUpdateDirectives [as updateDirectives] (core.es5.js?de3d:13058)
    at checkNoChangesView (core.es5.js?de3d:12217)
View_UserMgmtDialogComponent_0 @ UserMgmtDialogComponent.html:1
proxyClass @ compiler.es5.js?524d:14975
DebugContext_.logError @ core.es5.js?de3d:13398
ErrorHandler.handleError @ core.es5.js?de3d:1080
(anonymous) @ core.es5.js?de3d:4814
ZoneDelegate.invoke @ zone.js?6524:391
Zone.run @ zone.js?6524:141
NgZone.runOutsideAngular @ core.es5.js?de3d:3844
ApplicationRef_.tick @ core.es5.js?de3d:4814
(anonymous) @ core.es5.js?de3d:4684
ZoneDelegate.invoke @ zone.js?6524:391
onInvoke @ core.es5.js?de3d:3890
ZoneDelegate.invoke @ zone.js?6524:390
Zone.run @ zone.js?6524:141
NgZone.run @ core.es5.js?de3d:3821
next @ core.es5.js?de3d:4684
schedulerFn @ core.es5.js?de3d:3635
SafeSubscriber.__tryOrUnsub @ Subscriber.js?9a65:238
SafeSubscriber.next @ Subscriber.js?9a65:185
Subscriber._next @ Subscriber.js?9a65:125
Subscriber.next @ Subscriber.js?9a65:89
Subject.next @ Subject.js?104a:55
EventEmitter.emit @ core.es5.js?de3d:3621
checkStable @ core.es5.js?de3d:3855
onHasTask @ core.es5.js?de3d:3903
ZoneDelegate.hasTask @ zone.js?6524:444
ZoneDelegate._updateTaskCount @ zone.js?6524:464
Zone._updateTaskCount @ zone.js?6524:288
Zone.runTask @ zone.js?6524:208
drainMicroTaskQueue @ zone.js?6524:595
ZoneTask.invokeTask @ zone.js?6524:502
invokeTask @ zone.js?6524:1370
globalZoneAwareCallback @ zone.js?6524:1388
UserMgmtDialogComponent.html:1 ERROR CONTEXT DebugContext_ {view: {…}, nodeIndex: 10, nodeDef: {…}, elDef: {…}, elView: {…}}
View_UserMgmtDialogComponent_0 @ UserMgmtDialogComponent.html:1
proxyClass @ compiler.es5.js?524d:14975
DebugContext_.logError @ core.es5.js?de3d:13398
ErrorHandler.handleError @ core.es5.js?de3d:1085
(anonymous) @ core.es5.js?de3d:4814
ZoneDelegate.invoke @ zone.js?6524:391
Zone.run @ zone.js?6524:141
NgZone.runOutsideAngular @ core.es5.js?de3d:3844
ApplicationRef_.tick @ core.es5.js?de3d:4814
(anonymous) @ core.es5.js?de3d:4684
ZoneDelegate.invoke @ zone.js?6524:391
onInvoke @ core.es5.js?de3d:3890
ZoneDelegate.invoke @ zone.js?6524:390
Zone.run @ zone.js?6524:141
NgZone.run @ core.es5.js?de3d:3821
next @ core.es5.js?de3d:4684
schedulerFn @ core.es5.js?de3d:3635
SafeSubscriber.__tryOrUnsub @ Subscriber.js?9a65:238
SafeSubscriber.next @ Subscriber.js?9a65:185
Subscriber._next @ Subscriber.js?9a65:125
Subscriber.next @ Subscriber.js?9a65:89
Subject.next @ Subject.js?104a:55
EventEmitter.emit @ core.es5.js?de3d:3621
checkStable @ core.es5.js?de3d:3855
onHasTask @ core.es5.js?de3d:3903
ZoneDelegate.hasTask @ zone.js?6524:444
ZoneDelegate._updateTaskCount @ zone.js?6524:464
Zone._updateTaskCount @ zone.js?6524:288
Zone.runTask @ zone.js?6524:208
drainMicroTaskQueue @ zone.js?6524:595
ZoneTask.invokeTask @ zone.js?6524:502
invokeTask @ zone.js?6524:1370
globalZoneAwareCallback @ zone.js?6524:1388
`

**Comment by cfaddict** [comment] 2017-11-03 01:40
Wow. This tripped me up all night tonight. Thank you so much for solving it 👍

**Closed** 2017-11-05 20:57 UTC
