### ISSUE TITLE
Default oracle jar name doesn't match oracle's distribution

### ISSUE THREAD

**Issue by cm325** [jhipster/generator-jhipster#3737] opened 2016-06-17 16:03 UTC
##### **Overview of the issue**

This is a minor issue, but during project generation, if Oracle is selected as the db, the following instructions are given:

`WARNING! You have selected Oracle database.
Please place the ojdbc-7.jar in the `lib/oracle/ojdbc/7/` folder under the project root. `

But if you go to Oracle download page, you'll see the default name for the current ojdbc 7 jar is "ojdbc7.jar" without the dash (http://www.oracle.com/technetwork/database/features/jdbc/jdbc-drivers-12c-download-1958347.html). 

##### **Motivation for or Use Case** 

This isn't a huge deal, except that as a new user, you don't discover the problem until you run the mvn clean command. Then, you go look, and see the jar is there, so you're perplexed. Then you realize the name is off a little, and you change it. But, on the first run,maven caches the fact that the wrong jar is there, and even with the right jar there, it still fails. So you have to go digging for the maven command to update jar references, and then run `mvn test -U`

##### **JHipster Version(s)** 

v3.4.1

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 

This is not a bug

##### **Suggest a Fix** 

Change default oracle jar name to match the default name from oracle downloads site

**Comment by deepu105** [comment] 2016-06-17 16:16
I kept the `-` on purpose but i couldn't recall why now. I should have
documented it my bad :(

May be it was when we had java7 support, do you see any error if you use
the default name? It would be referenced in the pom/gradle file

Thanks & regards,
Deepu
On 18 Jun 2016 00:03, "chris marx" <notifications@github.com> wrote:

*Overview of the issue*

This is a minor issue, but during project generation, if Oracle is selected
as the db, the following instructions are given:

WARNING! You have selected Oracle database.
Please place the ojdbc-7.jar in thelib/oracle/ojdbc/7/folder under the
project root.

But if you go to Oracle download page, you'll see the default name for the
current ojdbc 7 jar is "ojdbc7.jar" without the dash (
http://www.oracle.com/technetwork/database/features/jdbc/jdbc-drivers-12c-download-1958347.html).

*Motivation for or Use Case*

This isn't a huge deal, except that as a new user, you don't discover the
problem until you run the mvn clean command. Then, you go look, and see the
jar is there, so you're perplexed. Then you realize the name is off a
little, and you change it. But, on the first run,maven caches the fact that
the wrong jar is there, and even with the right jar there, it still fails.
So you have to go digging for the maven command to update jar references,
and then run mvn test -U
*JHipster Version(s)*

v3.4.1
*JHipster configuration, a .yo-rc.json file generated in the root folder*

This is not a bug
*Entity configuration(s) entityName.json files generated in the .jhipster
directory* *Browsers and Operating System* *Reproduce the error* *Related
issues* *Suggest a Fix*

Change default oracle jar name to match the default name from oracle
downloads site

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/jhipster/generator-jhipster/issues/3737>, or mute the
thread
<https://github.com/notifications/unsubscribe/ABDlF6YzbUnCIjMIxedM9NlpawYAP9Icks5qMsVAgaJpZM4I4gFB>
.

**Comment by cm325** [comment] 2016-06-17 16:29
> May be it was when we had java7 support, do you see any error if you use
the default name? It would be referenced in the pom/gradle file

Not sure what you mean, are you saying, do I see any error if I change the jar name to match the expected name with the "-"?  If so, no, once I changed the name, the build completed successfully

**Comment by deepu105** [comment] 2016-06-17 16:47
No what I meant was if you use the name without hyphen after changing the
name in build file as well does it work with maven and gradle?

Thanks & regards,
Deepu
On 18 Jun 2016 00:29, "chris marx" <notifications@github.com> wrote:

May be it was when we had java7 support, do you see any error if you use
the default name? It would be referenced in the pom/gradle file

Not sure what you mean, are you saying, do I see any error if I change the
jar name to match the expected name with the "-"? If so, no, once I changed
the name, the build completed successfully

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/jhipster/generator-jhipster/issues/3737#issuecomment-226816429>,
or mute the thread
<https://github.com/notifications/unsubscribe/ABDlF1v4we4Leunu4nJqnegWFzBHv-Nkks5qMstZgaJpZM4I4gFB>
.

**Comment by jdubois** [comment] 2016-06-17 16:59
Yes I think you need it for Maven, so this should be tested
Le 17 juin 2016 6:47 PM, "Deepu K Sasidharan" <notifications@github.com> a
écrit :

> No what I meant was if you use the name without hyphen after changing the
> name in build file as well does it work with maven and gradle?
>
> Thanks & regards,
> Deepu

**Comment by deepu105** [comment] 2016-06-17 17:10
Ya I too remember something like that. It was failing either in maven or
gradle without hyphen

Thanks & regards,
Deepu

**Comment by cm325** [comment] 2016-06-17 20:17
Hi, I just started using jhipster this morning, I'm not sure which build file I would need to modify. Anyways, if the jar name without the dash was problematic, adding a note to change the name would probably be appreciated

**Comment by pascalgrimaud** [comment] 2016-06-18 07:49
It's already documented: https://jhipster.github.io/using-oracle/

> You will need to rename your driver, from ojdbc7.jar to ojdbc-7.jar, in order to follow Maven’s naming conventions.

**Comment by cm325** [comment] 2016-06-19 17:21
Ah,
Great, thanks for being so thorough, I failed to see that and just went
with the instructions in the yeoman build. The documentation so far for
jhipster has been quite comprehensive, great job!

**Comment by deepu105** [comment] 2016-06-20 04:29
Oh yes its for the naming convention now I remember :) so closing this

**Closed by deepu105** 2016-06-20 04:29 UTC
