### ISSUE TITLE
Gulp + Production mode: bootstrap fonts are not loaded

### ISSUE THREAD

**Issue by ctranxuan** [jhipster/generator-jhipster#1010] opened 2015-01-19 09:45 UTC
Hello,
A project generated with JHipster 2.0.0 with Gulp as js build manager and maven as java build manager does not display properly with the production mode: the bootstrap fonts are not loaded.

Here are the steps to reproduce:

* create a project with jhipster-generator 2.0.0 (choose the default options except for the js build manager: choose Gulp): yo jhipster
* run: mvn -Pprod package
* run: java -jar target/jhipster-0.0.1-SNAPSHOT.war --spring.profiles.active=prod
* open a browser, you get the welcome page but the fonts are not loaded: see screenshot in attachment

When opening the js console, we get some js errors:

```
GET http://localhost:8080/assets/fonts/glyphicons-halflings-regular.woff 
localhost/:1
GET http://localhost:8080/assets/fonts/glyphicons-halflings-regular.ttf
```

![screenshot from 2015-01-19 10 37 22](https://cloud.githubusercontent.com/assets/816144/5798480/d9198134-9fc7-11e4-8216-27f223d544cf.png)

Tested on Chrome Version 39.0.2171.99 (64-bit) and Firefox 35.0 Mozilla Firefox for Ubuntu canonical - 1.0

If ever you need more details, feel free to contact me.

Cheers,

Cédric.

**Comment by andidev** [comment] 2015-01-19 12:10
I think this may be solved when merging #1007

**Comment by andidev** [comment] 2015-01-19 12:16
Though there still may be a bug in gulpfile which does not copy the assets when building the dist version. Note that my comments are just thoughts.

**Comment by andidev** [comment] 2015-01-19 14:37
The assets seems to be in place in the dist folder so it's not that.

This is a bit strange. I am having problem loading the main.html and the navbar.html when following your instructuions.
![screen shot 2015-01-15 at 14 00 57](https://cloud.githubusercontent.com/assets/571389/5801975/c94d031a-9ff0-11e4-82cc-43c634859640.png)
 
 An addition to this bug is that it seems that the Development ribbon is not removed.

**Comment by amr** [comment] 2015-01-19 21:56
@andidev make sure you are running of the latest master

**Comment by amr** [comment] 2015-01-19 23:35
I cannot reproduce the font issue. Can anyone else reproduce? @ctranxuan: can you push the code somewhere?

Btw, I can reproduce the Development ribbon issue @andidev mentioned, and will submit a PR for it.

**Comment by ctranxuan** [comment] 2015-01-20 10:19
Hi,
You can find the project at https://github.com/ctranxuan/jhipster2-sample
I've removed npm_modules and bower dependencies. 

MySQL username / pwd has been configured with root / root.

If ever you need any other feedback, feel free to contact me.

**Comment by jdubois** [comment] 2015-01-20 11:58
I have merged https://github.com/jhipster/generator-jhipster/pull/1011 this should fix the development ribbon issue

**Comment by andidev** [comment] 2015-01-22 09:48
Is your issue solved?

If not could you try the #1007 PR version by doing the following?

Install the PR version of JHipster generator by entering the following in your console
```bash
git clone https://github.com/andidev/generator-jhipster
cd generator-jhipster
git co wiredep-bootstrap
npm link
```

then try generatirng a new JHipster project and retry your test case.

**Comment by amr** [comment] 2015-01-23 22:55
@ctranxuan I was able to reproduce from your github repo, what was missing in your original steps is to indicate that you chose to use compass as well. I tested with @andidev #1007 PR and found that it resolves this issue.

**Closed** 2015-01-26 22:57 UTC
Labels: gulp.js

**Comment by ctranxuan** [comment] 2015-01-28 12:35
Sorry about compass. :( 
I was so used to generate with compass that I did not realize it was not a default option.
Apologizes.

**Comment by amr** [comment] 2015-01-28 12:42
No worries at all & thanks for reporting
