### ISSUE TITLE
Broken jhipster:upgrade in 3.12.0

### ISSUE THREAD

**Issue by ashakhov** [jhipster/generator-jhipster#4593] opened 2016-12-01 13:06 UTC
##### **Overview of the issue**

yo jhipster:upgrade fails to upgrade project. Seems like the problem is in the second stage which should update jhipster and regenerate project using its new version. In some projects it also reverts jhipster version in .yo-rc to 3.10.0.
```
Successfully regenerated app with jhipster 3.11.0
Committed with message "Generated with JHipster 3.11.0"
Checked out branch "master"
Current code recorded as generated with version 3.11.0
Updating generator-jhipster. This might take some time...
Updated generator-jhipster to version 3.12.0
Checked out branch "jhipster_upgrade"
Cleaned up directory
Regenerating app with jhipster 3.12.0...
 
        ██  ██    ██  ████████  ███████    ██████  ████████  ████████  ███████
        ██  ██    ██     ██     ██    ██  ██          ██     ██        ██    ██
        ██  ████████     ██     ███████    █████      ██     ██████    ███████
  ██    ██  ██    ██     ██     ██             ██     ██     ██        ██   ██
   ██████   ██    ██  ████████  ██        ██████      ██     ████████  ██    ██

                            http://jhipster.github.io

Welcome to the JHipster Generator v3.11.0
Documentation for creating an application: https://jhipster.github.io/creating-an-app/
Application files will be generated in folder: /home/ashakhov/jh-test
 ______________________________________________________________________________

  JHipster update available: 3.12.0 (current: 3.11.0)
  Run npm install -g generator-jhipster to update.
 ______________________________________________________________________________

This is an existing project, using the configuration from your .yo-rc.json file 
to re-generate the project...
```

##### **Reproduce the error**

yo jhipster:upgrade

##### **JHipster Version(s)**
Trying to update project generated with 3.11.0 to 3.12.0.
```
jhipster@0.0.0 /home/ashakhov/jh-test
└── generator-jhipster@3.11.0 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "jhipsterVersion": "3.11.0",
    "baseName": "jhipster",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "rememberMeKey": "e0051e23b0c3f2b739ed8aab4ccb32a87ce74969",
    "useSass": false,
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ]
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

ls: no such file or directory: .jhipster/*.json
##### **Browsers and Operating System**
ubuntu 14.04.5
java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)

git version 1.9.1
node: v4.6.2
npm: 4.0.2
bower: 1.8.0

gulp:
[15:00:51] CLI version 1.2.2
[15:00:51] Local version 3.9.1

yeoman: 1.8.5

**Comment by pascalgrimaud** [comment] 2016-12-01 13:24
@ashakhov : can you try with node v6.9.1 LTS instead of node 4.6.2 ?

**Comment by ashakhov** [comment] 2016-12-01 13:34
@pascalgrimaud : yes, tried it as well but problem persists. BTW, git log looks pretty interesting:
```
commit 4763594a8c43770c5923d2c0183e4c3b32721d4c
Merge: ad547e9 8f3e13d
Author: Andrii Shakhov
Date:   Thu Dec 1 15:27:25 2016 +0200
    Merge branch 'jhipster_upgrade'

commit 8f3e13d3ab21d9bcc6f1d85dbbdee5b3437ea0be
Author: Andrii Shakhov
Date:   Thu Dec 1 15:27:25 2016 +0200
    Generated with JHipster 3.12.0

commit ad547e907fd3c0186be48445e91b94c89a96f814
Merge: ace7a1c f3bf05e
Author: Andrii Shakhov
Date:   Thu Dec 1 15:27:10 2016 +0200
    Merge branch 'jhipster_upgrade'

commit f3bf05e8fde2caa49c05e86e282b86e9b4f33209
Author: Andrii Shakhov
Date:   Thu Dec 1 15:27:09 2016 +0200
    Generated with JHipster 3.11.0

commit ace7a1c6634718e252339324c5f20c5b9c41d476
Author: Andrii Shakhov
Date:   Thu Dec 1 14:58:26 2016 +0200
    Initial
```
It was a newly created clean project generated using 3.11.0 so there was no reason to update it to 3.11.0.

**Comment by shinusuresh** [comment] 2016-12-01 14:12
I am also seeing the same issue while upgrading to 3.12.0 from 3.11.0. 
I am on windows 8 machine with node v6.9.1

GIT - 1.9.5.msysgit.0
npm - 3.10.2
gulp
CLI version 3.9.1
Local version 3.9.1
yo - 1.8.5

**Comment by cbornet** [comment] 2016-12-01 14:19
It means some jhipster package installed somewhere was used instead of the locally installed 3.12.
Can you check in the jhipster-upgrade branch where does it find the jhipster package ? Also, are you using yarn ?

**Comment by ashakhov** [comment] 2016-12-01 14:37
```/home/ashakhov/jh-test/node_modules/generator-jhipster/package.json``` says:
```
  "_args": [
    [
      {
        "raw": "generator-jhipster@3.11.0",
        "scope": null,
        "escapedName": "generator-jhipster",
        "name": "generator-jhipster",
        "rawSpec": "3.11.0",
        "spec": "3.11.0",
        "type": "version"
      },
      "/home/ashakhov/jh-test"
    ]
```
So the local one is 3.11.0? Otherwise 
>Can you check in the jhipster-upgrade branch where does it find the jhipster package

How can I do it?

No, I don't use yarn.

**Comment by cbornet** [comment] 2016-12-01 15:49
Can you look at the same file but in the jhipster_upgrade branch ?

**Comment by ashakhov** [comment] 2016-12-01 15:51
Same version.

**Comment by cbornet** [comment] 2016-12-01 15:56
I guess `npm list --depth=0 generator-jhipster` also gives you 3.11.0 ?

**Comment by ashakhov** [comment] 2016-12-01 15:58
Yes.

**Comment by cbornet** [comment] 2016-12-01 15:59
Last question: you didn't `npm link` a clone version ?

**Comment by ashakhov** [comment] 2016-12-01 16:10
No. 
BTW, if I try to create a new project, it has 3.12.0.

**Comment by cbornet** [comment] 2016-12-01 16:25
If you do in the project folder `npm install generator-jhipster`, what is the result ?

**Comment by ashakhov** [comment] 2016-12-01 16:28
```
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
jhipster@0.0.0 /home/ashakhov/jh-test
└── generator-jhipster@3.11.0 

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.15: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
```
Both master and jhipster_upgrade branches have ```"generator-jhipster": "3.11.0",``` in ```package.json```.

**Comment by cbornet** [comment] 2016-12-01 16:39
Please paste the full log of `npm install generator-jhipster`

**Comment by ashakhov** [comment] 2016-12-01 16:41
That was the full log.

**Comment by cbornet** [comment] 2016-12-01 16:43
`install` not `list`

**Comment by ashakhov** [comment] 2016-12-01 16:46
```
~/jh-test$ npm install generator-jhipster
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
jhipster@0.0.0 /home/ashakhov/jh-test
└── generator-jhipster@3.11.0 

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.15: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
~/jh-test$ 
```

**Comment by cbornet** [comment] 2016-12-01 16:50
Oh ! That's not at all the log I get when I install with npm ! And it looks so close to the npm list result !

**Comment by cbornet** [comment] 2016-12-01 16:52
So the issue is clear: the npm install command doesn't seem to install the latest version...
Can you try with `npm install generator-jhipster@3.12.0` ?

**Comment by ashakhov** [comment] 2016-12-01 16:55
```
~/jh-test$ npm install generator-jhipster@3.12.0
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
jhipster@0.0.0 /home/ashakhov/jh-test
└─┬ generator-jhipster@3.12.0  invalid
  └─┬ jhipster-core@1.2.1 
    └── lodash@4.17.2 

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.15: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
```

**Comment by cbornet** [comment] 2016-12-01 16:56
😅 npm...

**Comment by cbornet** [comment] 2016-12-01 16:58
Are you using some proxy to the npm-registry ? Like a cache proxy ?

**Comment by ashakhov** [comment] 2016-12-01 17:29
No. And I never had any issues with connecting to npm.
Not sure if it is related but there is another weird thing. I looked through updates history and found out that update from 3.10.0 to 3.11.0 haven't changed .yo-rc.json. Code upgraded to 3.11.0 still has ```"jhipsterVersion": "3.10.0",```.

**Comment by bradrich** [comment] 2016-12-01 20:52
I was forced, as I have been every time, to update JHipster globally with `npm install -g generator-jhipster` and then on my gateway application (I'm using microservices), having to go into my `package.json` file, change the `generator-jhipster` version number, and then update JHipster locally with `npm install generator-jhipster`.

This solved my issue.

**Comment by shinusuresh** [comment] 2016-12-02 06:56
@bradrich That worked for me. :+1:

**Comment by ashakhov** [comment] 2016-12-02 12:50
Worked for me as well. But there was a new problem with gulp so I had to remove bower_components, install it again and do ```gulp inject``` before merging.

**Comment by shinusuresh** [comment] 2016-12-02 13:09
@ashakhov I Just ran gulp and app came up fine.

**Comment by fw060** [comment] 2016-12-02 16:49
@bradrich That worked for me too 👍 Thank you so much!

**Comment by jdubois** [comment] 2016-12-04 12:06
Maybe we should update our docs here... Sorry everyone, but I'm not using the tool like you, and the rest of the dev team is probably doing the same as me: we are directly working on a Git clone of the repo, so we don't do "npm install", we basically do "git pull" instead... So if you have a better workflow than the one on the website, can you help us update the documentation?

**Comment by jdubois** [comment] 2016-12-05 17:18
I'm closing this as everybody looks happy, but I have no idea what the issue was...

**Closed by jdubois** 2016-12-05 17:18 UTC

**Comment by fw060** [comment] 2016-12-09 16:04
@jdubois I am not sure what the cause is but my wild guess is that jhipster:upgrade was not considering how to upgrade different microservices independently. With the following steps, maybe a "jhipster:upgrademicroservice" can be created?

So here are the steps based on the instructions by @bradrich
1. Globally upgrade jHipster to the new version: "npm install -g generator-jhipster"
Then repeat step 2-3 for EACH microservice, including gateway, uaa, and user created ones.
2. manually modify package.json, change generator-jhipster to the NEW jhipster version
3. locally commit package.json
4. run "yo jhipster:upgrade"

**Comment by pascalgrimaud** [comment] 2016-12-09 16:28
@PierreBesson is working on this: https://github.com/jhipster/generator-jhipster/pull/4597 to include package.json in Microservices projects.
With that, I think the sub module jhipster:upgrade should work, so no need to add a new sub generator

**Comment by fw060** [comment] 2016-12-09 16:35
@pascalgrimaud @PierreBesson Awesome! Thanks!

**Comment by jdubois** [comment] 2016-12-10 07:49
Oh, for a microservice, I never thought of this, indeed!!!! So indeed #4597 from @PierreBesson is very, very important.
Then, the original issue filled here was for a monolith, so this is a different thing...

**Comment by ashakhov** [comment] 2016-12-10 13:44
Maybe [there was a mistake](https://github.com/jhipster/generator-jhipster/commit/dea5f1c6280faf35451052532f760b0beaceece4#diff-dd45b0ed9a9bcd681530aa65866a6501L217)?
Previously ```npm i -g generator-jhipster``` was automated, but it was removed so now we have to do it manually.

**Comment by cbornet** [comment] 2016-12-10 14:20
The upgrader now upgrades the generator only for the project and not globally. Upgrading globally may require root privileges on some systems.
