### ISSUE TITLE
com.boss.user.service.UserService#clearUserCaches cannot clear the redis cache

### ISSUE THREAD

**Issue by TonyLuo** [jhipster/generator-jhipster#11348] opened 2020-02-20 02:45 UTC
##### **Overview of the issue**
com.boss.user.service.UserService#clearUserCaches cannot clear the redis cache. because user.getLogin() is "admin", but the key in redis hash is "\xFCKcom.boss.user.repository.UserRepository_findOneWithAuthoritiesByLogin_admin"
```
com.boss.user.service.UserService#clearUserCaches
  private void clearUserCaches(User user) {
        Objects.requireNonNull(cacheManager.getCache(UserRepository.USERS_BY_LOGIN_CACHE)).evict(user.getLogin());
}
```
```
the key in redis hash "usersByLogin": 

\xFCKcom.boss.user.repository.UserRepository_findOneWithAuthoritiesByLogin_admin
```
![image](https://user-images.githubusercontent.com/3250305/74896087-4a1cef00-53ce-11ea-8c95-78e941e98d58.png)

##### **JHipster Version(s)**
6.7.0

##### **Browsers and Operating System**

-   [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by SudharakaP** [comment] 2020-02-20 03:18
@TonyLuo : Could you please give some more information on how to reproduce this error. Maybe fill the issue template by including the `.yo-rc.json` file and any entity configurations you've created. :smile:

**Comment by TonyLuo** [comment] 2020-02-20 03:44
@SudharakaP FYI

INFO! Using JHipster version installed locally in current project's node_modules
INFO! Executing jhipster:info
INFO! Options: from-cli: true
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
test@0.0.1-SNAPSHOT D:\dev\next\test
`-- generator-jhipster@6.7.1

```


##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**


<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "6.7.1",
    "applicationType": "monolith",
    "baseName": "test",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "redis",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",        "embeddableLaunchScript": false,
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "angularX",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "creationTimestamp": 1582169100503,
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": ["en", "zh-cn"],
    "blueprints": []
  }
}

</pre>
</details>


##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>


##### **Environment and Tools**

java version "1.8.0_241"
Java(TM) SE Runtime Environment (build 1.8.0_241-b07)
Java HotSpot(TM) 64-Bit Server VM (build 25.241-b07, mixed mode)

git version 2.23.0.windows.1

node: v10.16.3

npm: 6.13.7

yeoman: 3.1.1

yarn: 1.19.0

Docker version 19.03.5, build 633a0ea

docker-compose version 1.24.1, build 4667896b

**Comment by pascalgrimaud** [comment] 2020-02-20 06:17
cc @Shaolans as he's the one who coded initially the Redis cache

**Comment by Shaolans** [comment] 2020-02-20 07:02
I will investigate ASAP !

**Comment by Shaolans** [comment] 2020-03-02 14:23
Hello, sorry for the late reply.
I tried to reproduce your issue, however it seems to be working fine.
When I call clearUserCaches, the usersByLogin is cleared.
Have you updated the generator to the 6.7.X ? Because the method clearUserCaches is different from what I have generated.
```Java
public void clearUserCaches(User user) {
        Objects.requireNonNull(cacheManager.getCache(UserRepository.USERS_BY_LOGIN_CACHE)).evict(user.getLogin());
        if (user.getEmail() != null) {
            Objects.requireNonNull(cacheManager.getCache(UserRepository.USERS_BY_EMAIL_CACHE)).evict(user.getEmail());
        }
    }
```

**Comment by Shaolans** [comment] 2020-03-02 19:55
Since your issue does not appear with the app I generated with your .yo-rc.json, can you give me more details on how to reproduce it with minimal changes ?

**Comment by pascalgrimaud** [comment] 2020-03-05 06:11
Closing this as we can't reproduce
Feel free to provide more steps if you're sure about your issue

**Closed by pascalgrimaud** 2020-03-05 06:11 UTC
Labels: area: needs-reproduction, theme: redis
