### ISSUE TITLE
bug deploying a jhipster app on heroku

### ISSUE THREAD

**Issue by vhiguitamibi14** [jhipster/generator-jhipster#5486] opened 2017-03-25 16:06 UTC
Hi,

I'm trying to deploy a project with heroku but I'm getting the next error.

Thank you very much
![error heroku deploy](https://cloud.githubusercontent.com/assets/6797470/24323916/f0f8dde4-114a-11e7-82f9-435052b4a08d.jpg)

**Comment by jdubois** [comment] 2017-03-25 16:09
This ticket has been closed as the guidelines are not followed.

Tickets must follow our [Guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#submitting-an-issue), as mentioned in:

1. our [Readme file on the front page of the project](https://github.com/jhipster/generator-jhipster/blob/master/README.md), 
2. the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) and
3. our [Help page](http://jhipster.github.io/help/)

We have also created a template on the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) to help you follow those guidelines.

**Closed by jdubois** 2017-03-25 16:09 UTC

**Comment by gmarziou** [comment] 2017-03-25 18:34
Looks like a duplicate of #4871 but we cannot be sure as you did not use issue template to provide all required details.
