### ISSUE TITLE
The web client does not showing the error anymore

### ISSUE THREAD

**Issue by damir78** [jhipster/generator-jhipster#7137] opened 2018-02-17 22:41 UTC
##### **Overview of the issue**

The web client does not showing the error anymore, s. screenshot:

##### **Motivation for or Use Case**

n/a
##### **Reproduce the error**

1) Try to register a new user with existing login, for example user, admin, or with existing email
##### **JHipster Version(s)**

v4.14.0
##### **JHipster configuration**

simple config: mono, without any extra feature
##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**
a
![bildschirmfoto 2018-02-17 um 23 34 48](https://user-images.githubusercontent.com/12588674/36346287-14ac4eca-143c-11e8-8e00-415655ef894f.png)

##### **Browsers and Operating System**
Chrome on MacOs

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by ruddell** [comment] 2018-02-17 22:58
Duplicate of https://github.com/jhipster/generator-jhipster/issues/7085, see https://github.com/jhipster/generator-jhipster/commit/3f5c72927a544c662510bab00af30ab0d538bdf3 and https://github.com/jhipster/generator-jhipster/commit/d760e618dd2813ef40d10282d0e18061598f2c44 for the fix

Similar issue happened with the password reset page, see https://github.com/jhipster/generator-jhipster/commit/79782199771162086a1817ca1559d48961857cde for that fix

**Closed by ruddell** 2018-02-17 22:58 UTC
