### ISSUE TITLE
Tomcat 8 warning: org.apache.catalina.webresources.Cache.getResource Unable to add the resource

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#3995] opened 2016-08-17 11:54 UTC
This issue is only occurring on the current master (future JHipster 3.6.0), when running the application in production.

This is probably caused by our migration to Spring Boot 1.4, which has upgraded Tomcat.

At startup time, we have errors in the form:

    org.apache.catalina.webresources.Cache.getResource Unable to add the resource

This is for all Jar files in WEB-INF/lib which have a size >512kb.

This error is quite common to people migrating to Tomcat 8, [here is a stackoverflow question with good answers](http://stackoverflow.com/questions/26893297/tomcat-8-throwing-org-apache-catalina-webresources-cache-getresource-unable-to) for example.

This is documented [on the Tomcat 8 documentation](https://tomcat.apache.org/tomcat-8.0-doc/config/resources.html), and this is because:

- Tomcat caches `classes, JAR files, HTML, JSPs and any other files that contribute to the web application`
- The total cache size (`cacheMaxSize`) is `10240kb` and de maximum object size (`cacheObjectMaxSize`) is `512kb`
- With JHipster, we have a quite specific use of Tomcat: indeed we have those big Jar files (like any Spring Boot application), but we also have big JS and CSS files in production, and those can grow very big depending on what people put in them -> not caching them (if they are more than 512kb in size) would be a performance issue

-> this is all logical, and caused by our specific use of Spring Boot (which is why this isn't corrected in Spring Boot)

My solution is to multiply the standard values by 4:

- `cacheMaxSize=40960`
- `cacheObjectMaxSize=2048`

My only concern is that this will make our final application use more RAM - but comparing to an Hibernate 2nd level cache (which most people are using), this should be OK.

I'll submit a patch for this in a few minutes.

**Comment by ruddell** [comment] 2016-08-19 22:43
@jdubois This appears to be fixed in monoliths, but the warnings still show up in gateway/monolith apps.  I can confirm they call `customizeTomcat` is called but the warnings still appear.

**Comment by jdubois** [comment] 2016-08-21 06:51
Thanks @ruddell you are correct, I just reproduced the issue. What the hell did I do wrong??

**Comment by jdubois** [comment] 2016-08-21 07:07
From my first tests, it looks like the 40Mb cache I put might not be enough...

- I don't understand why this size is enough sometimes (for monoliths, for the registry), and sometimes not (microservices... and they are lighter than monoliths!!)
- I don't want a cache which is too big, especially for microservices, as I want the apps to run in small containers/VMs

**Comment by ruddell** [comment] 2016-08-22 07:26
The `/target/myapp-0.0.1-SNAPSHOT/WEB-INF/lib` folder  is about 20MB smaller for a monolith (~57MB) than a microservice (~75MB) and gateway (~77MB).  I'm confused why it would work for monoliths if the folder is over 40MB but it seems to be fine.

A workaround instead of increasing the cache is to add `<logger name="org.apache.catalina.webresources.Cache" level="ERROR"/>` to the logback-spring.xml.  This would basically be the behavior of Tomcat 7 according to that StackOverflow link.

**Comment by jdubois** [comment] 2016-08-22 07:31
Oh yes, that's because of all the Spring Cloud dependencies! That's logical then, and that means we should have a bigger cache for microservices & gateways if we want to keep this solution.
Then, this is eating quite a lot of RAM, and I'm not even sure it's useful - as it says in the StackOverflow link (I also found it [here in the Atlassian documentation](https://confluence.atlassian.com/confkb/excessive-warning-cache-messages-in-catalina-out-for-confluence-5-8-x-771098337.html)).
Then, as we are having pretty big JS/CSS files after minification, I'm worried those files won't get cached: and for those, I'm pretty sure that caching them is useful!!

So at the moment I'm for having a bigger cache, but this needs further study.

Might be a good time to test JHipster on Undertow again! This would solve everything!

**Comment by erikkemperman** [comment] 2016-08-24 09:25
@jdubois @ruddell  I just ran into the same warnings after having upgraded my app to JH 3.6.1 (yay!).

I am wondering if it makes sense to increase both the total cache limit and the per-object limit by the same factor... After all, that way it will have more room, but also require more room because more artifacts pass the per-object limit.

Would it make sense to look at the sorted list of jars in WEB-INF/lib and determine a per-object limit that (just) includes the most performance-critical jars? And then set the total limit take some multiple of that to account for the number of included jars and some space for web assets (HTML,JS,CSS)?

**Comment by jdubois** [comment] 2016-08-24 09:42
@erikkemperman the issue is that the per-object limit is max 5% of the total cache limit. So if you have big JARs (or probably CSS/JS but I've not seen it yet), you're going to have to increase the total limit...

**Comment by erikkemperman** [comment] 2016-08-24 09:51
Sorry, maybe I was not clear. My suggestion was to increase the per-object limit by a _smaller_ factor than the total limit (so the percentage would decrease).

**Comment by jdubois** [comment] 2016-08-24 09:52
oh sorry @erikkemperman 
But then I'm afraid some big CSS/JS would not be cached... I'm not sure what it does for JAR files, but for CSS/JS I'm pretty sure they should be cached.

**Comment by erikkemperman** [comment] 2016-08-24 10:01
@jdubois Absolutely agreed. For my own app I notice that none of the static web assets (production build) exceed 1 MB, so  that's where I've set my per-object limit for now. (There is a `.map` file which is larger but I can live with that not being cached).

I'm curious if these limits take into account compression, if so I could probably decrease it some more if I wanted.

Anyway, just thought I'd contibute my 2 cents here -- for me the most convenient remedy for these warnings -- which I was still seeing with your patch -- was increasing total limit by x4 (relative to original defaults) and per-object limit by x2.

**Comment by jdubois** [comment] 2016-08-24 10:05
Thanks @erikkemperman - indeed I'll try with your settings

**Comment by erikkemperman** [comment] 2016-08-24 10:06
Cool, thanks for the quick response like always!!

**Comment by cm325** [comment] 2016-08-26 22:10
Spring boot 1.4 says it still supports tomcat 7, but with these fixes (namely using StandardRoot), the app is now hardcoded to expect tomcat 8. For the moment, I still need to deploy to 7. Would it be possible to make these changes conditional? Also, for anyone still wanting to use 7, they would have to follow the new boot guidelines, and it took me a while to figure out I had to do this - http://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#howto-use-tomcat-7

**Comment by deepu105** [comment] 2016-08-27 04:22
I haven't checked this yet but will these changes affect the ability to
deploy the generated war to other containers?

Thanks & regards,
Deepu

**Comment by jdubois** [comment] 2016-08-27 08:00
Oh I didn't know those were Tomcat 8 - specific APIs! Are you sure about this?

**Comment by erikkemperman** [comment] 2016-08-27 08:11
@deepu105 I was wondering the same at first, haven't tested it but it looks like it's all right -- the limits are only applied if the container is an instance of `TomcatEmbeddedServletContainerFactory`. 

Maybe the `import` statement for `org.springframework.boot.context.embedded.tomcat.*` might problematic? If so the tomcat stuff should maybe go to a separate class.

I'm not sure why the javadoc for the `customize` method now looks like it's Tomcat specific, because I think it's not...

**Comment by cm325** [comment] 2016-08-29 14:47
Yeah, it's the import, this class doesn't exist as far as I can tell in tomcat 7 -

https://tomcat.apache.org/tomcat-8.0-doc/api/org/apache/catalina/webresources/StandardRoot.html

**Comment by erikkemperman** [comment] 2016-09-01 17:04
@jdubois I for one would like to be able to control these limits, on Tomcat 8. Maybe even from a setting in the yaml files. Can we somehow detect the version and do this only when appropriate?

**Comment by jdubois** [comment] 2016-09-01 20:31
Another solution would be to switch to Undertow. We tried a few months ago (see #2948 ) but we had to rollback.
I'm opening a specific issue for this, and will link it here.

**Comment by erikkemperman** [comment] 2016-09-02 07:22
All right, I am stuck with Tomcat unfortunately, but if the goal for JH is to move to Undertow as default I understand not putting energy in this :-)

**Comment by jdubois** [comment] 2016-09-02 07:30
One of the goals with Undertow is that we don't have the embbeded Tomcat
anymore, so it would be less trouble to deploy your WAR on a "real" Tomcat.
So that should be better for you.

Le 2 sept. 2016 9:22 AM, "Erik Kemperman" <notifications@github.com> a
écrit :

**Comment by pascalgrimaud** [comment] 2016-09-10 14:34
As we migrated to undertow, can it be closed?

**Comment by deepu105** [comment] 2016-09-10 15:20
yes ofcourse

**Closed by deepu105** 2016-09-10 15:20 UTC
Labels: bug
