### ISSUE TITLE
Configs are not been passed to Entity generator when using blueprints

### ISSUE THREAD

**Issue by mshima** [jhipster/generator-jhipster#10205] opened 2019-08-09 20:29 UTC
When executing jhipster for the first time, configs are not been passed correctly to the entity generator blueprint.

##### **Reproduce the error**

Created a test:
https://github.com/mshima/generator-jhipster/commit/54da517f6c8f1908022a83b478720c9985bbc38e

##### **Suggest a Fix**

Seems related to:
https://github.com/jhipster/generator-jhipster/blob/c9f4ca1aa0f865e06b3cd45f8f7a2e57f42d5cfc/generators/utils.js#L421
https://github.com/jhipster/generator-jhipster/blob/c9f4ca1aa0f865e06b3cd45f8f7a2e57f42d5cfc/generators/entity/index.js#L140

##### **JHipster Version(s)**

6.2.0
Seems this wasn't happening on 6.1.2.

##### **Browsers and Operating System**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment] 2019-08-10 19:54
it's probably related to https://github.com/jhipster/generator-jhipster/pull/9937
But to be honest, I don't clearly understand this ticket.

Maybe @pvliss you can have a quick look plz ?

**Comment by pvliss** [comment] 2019-08-12 17:29
@mshima Thanks for reporting and the test. Will check to see what the problem is.

**Comment by pvliss** [comment] 2019-08-13 05:27
So I tried the test and the problem is that in order to work properly you also need an existing `.yo-rc.json` file; otherwise it will not be able to properly load the configuration required by the entity generator.

I also modified [entity-blueprint.spec.js](https://github.com/jhipster/generator-jhipster/blob/master/test/blueprint/entity-blueprint.spec.js) and removed the used `.yo-rc.json` to include your changes and it also fails for versions 6.2.0(current master), 6.1.2 and 5.8.2. Again the main reason being that there is no config file to load all of the needed configuration properties from.

This can be solved in the unit test by simply adding a `.yo-rc.json` file like in this [example branch](https://github.com/pvliss/generator-jhipster/commit/5df8f1a95a62b443c06fd517e8650119e2686f45)(that also includes your changes, slightly modified). 

When running the generator normally this is not a problem as the app generator will take care to initialize the config file **before** composing any of the sub-generators and blueprints. I tested it by creating a new app with `jhipster --blueprints vuejs` and modified the app name at the prompt and everything worked as expected.

So I believe this is not a problem and we can certainly add your changes to enhance the test suite.

Other than the test did you have any issues using one or more blueprints? If so, please provide the details to try and reproduce.

**Comment by pascalgrimaud** [comment] 2019-08-13 05:30
Thanks for the analyze and your help @pvliss !

**Comment by mshima** [comment] 2019-08-13 14:57
> This can be solved in the unit test by simply adding a `.yo-rc.json` file like in this [example branch](https://github.com/pvliss/generator-jhipster/commit/5df8f1a95a62b443c06fd517e8650119e2686f45)(that also includes your changes, slightly modified).

Yep, the problem is that `.yo-rc.json` file isn't saved at this point.

In the last commit generator.configOptions is merged into the config, seems a workaround.
But I think jhipster should have a cleaner and unified configuration object for passing configs between the modules, instead of always reading from file.

**Comment by mshima** [comment] 2019-08-13 15:32
> Other than the test did you have any issues using one or more blueprints? If so, please provide the details to try and reproduce.

I am implementing a blueprint that customize current behavior of the original modules.

This blueprint creates a tenant (ex:Company).
https://github.com/mshima/generator-jhipster-multitenancy2/blob/13771cddb837e6b9b18b5dc7e0d92fafa530752e/generators/common/index.js#L175
https://github.com/mshima/generator-jhipster-multitenancy2/blob/13771cddb837e6b9b18b5dc7e0d92fafa530752e/generators/entity/index.js#L126

Creates an optional relationship between User and the tenant.
https://github.com/mshima/generator-jhipster-multitenancy2/blob/13771cddb837e6b9b18b5dc7e0d92fafa530752e/generators/server/partials/server/User.java.v6.js#L33

It creates an optional relationship between an registry and the tenant and limit access to this registry only by Users related to this tenant.
https://github.com/mshima/generator-jhipster-multitenancy2/blob/13771cddb837e6b9b18b5dc7e0d92fafa530752e/generators/entity/index.js#L299

I am trying to use everything 'upstream'.

Some problems that I had to create workarounds:
https://github.com/jhipster/generator-jhipster/issues/10160

The blueprint:
https://github.com/mshima/generator-jhipster-multitenancy2

Workaround for this bug:
https://github.com/mshima/generator-jhipster-multitenancy2/commit/13771cddb837e6b9b18b5dc7e0d92fafa530752e

I hoped jhipster was ready for this blueprint use case.

**Comment by pvliss** [comment] 2019-08-13 17:57
> Yep, the problem is that .yo-rc.json file isn't saved at this point.

Yes, I realize that. That is why I also tested with 5.8.2 and 6.1.2 without using a `.yo-rc.json` to check if it was a regression, but found otherwise. It did not work before either, except if my test has a mistake. Have you tested it with 6.1.2 as you mention in the description?

> In the last commit generator.configOptions is merged into the config, seems a workaround.
But I think jhipster should have a cleaner and unified configuration object for passing configs between the modules, instead of always reading from file.

First time I looked at the code I was a bit confused as welll with all the config and option obejcts going arround so I agree that there could be some cleaner way to handle that. But it is a rather complex task to take and not sure if it will create compatibility issues with existing blueprtints and modules. Ofcourse, PRs are always welcome :)

> I am implementing a blueprint that customize current behavior of the original modules.

That is great!!! 👍 

>Workaround for this bug:
mshima/generator-jhipster-multitenancy2@13771cd

Again, if you can generalize a solution then you can create a PR in the main generator as well.

**Comment by mshima** [comment] 2019-08-19 17:35
> > Yep, the problem is that .yo-rc.json file isn't saved at this point.
> 
> Yes, I realize that. That is why I also tested with 5.8.2 and 6.1.2 without using a `.yo-rc.json` to check if it was a regression, but found otherwise. It did not work before either, except if my test has a mistake. Have you tested it with 6.1.2 as you mention in the description?
> 
> > In the last commit generator.configOptions is merged into the config, seems a workaround.
> > But I think jhipster should have a cleaner and unified configuration object for passing configs between the modules, instead of always reading from file.
> 
> First time I looked at the code I was a bit confused as welll with all the config and option obejcts going arround so I agree that there could be some cleaner way to handle that. But it is a rather complex task to take and not sure if it will create compatibility issues with existing blueprtints and modules. Ofcourse, PRs are always welcome :)
> 
> > I am implementing a blueprint that customize current behavior of the original modules.
> 
> That is great!!! 👍
> 
> > Workaround for this bug:
> > [mshima/generator-jhipster-multitenancy2@13771cd](https://github.com/mshima/generator-jhipster-multitenancy2/commit/13771cd)
> 
> Again, if you can generalize a solution then you can create a PR in the main generator as well.

Ok, please take a look is this branch:
https://github.com/mshima/generator-jhipster/commits/config_refactoring

This is the start of a jhipster configuration complete refactoring.
Implemented to not cause problems to current modules and blueprints.
But with the flag --new-configuration will disable old configurations.

**Comment by pvliss** [comment] 2019-08-20 06:57
Closing in favor of #10247

**Closed by pvliss** 2019-08-20 06:57 UTC
Labels: area: needs-reproduction, theme: blueprint :paw_prints:
