### ISSUE TITLE
Issue in Hazelcast dependency. 

### ISSUE THREAD

**Issue by hassnainali** [jhipster/generator-jhipster#6579] opened 2017-10-22 11:26 UTC
##### **Overview of the issue**
Hi there, I've generate microservice gateway app successfully but I'm facing issue with the hazelcast dependency its unable to download or find required classes in CacheConfiguration.java class and in WebConfigureTest.java.  I've not added any kind of additional dependency, just generated this project and trying to run it. If I'm doing something wrong please guide me. I think I'm the only one who's facing this issue right now.

##### **Motivation for or Use Case**

These are some of the classes from hazelcast dependency which are not being found.
import com.hazelcast.config.Config;
import com.hazelcast.core.HazelcastInstance;
import com.hazelcast.core.Hazelcast;
import com.hazelcast.config.MapConfig;
import com.hazelcast.config.EvictionPolicy;
import com.hazelcast.config.MaxSizeConfig;

##### **Reproduce the error**
Just generate a Microservice gateway project. and try run it with **mvnw**

##### **Related issues**
none

##### **Suggest a Fix**
none

##### **JHipster Version(s)**
4.9.0

##### **JHipster configuration**
Executing jhipster:info
Options:
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
msgateway@0.0.0 D:\Hassnain\jHipster\10-10-2017-personal\microservices\oracle12c\base-microservice-gateway-oracle
`-- generator-jhipster@4.9.0

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.micro.gateway"
    },
    "jhipsterVersion": "4.9.0",
    "baseName": "msgateway",
    "packageName": "com.micro.gateway",
    "packageFolder": "com/micro/gateway",
    "serverPort": "8080",
    "authenticationType": "uaa",
    "uaaBaseName": "oauthserver",
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "oracle",
    "prodDatabaseType": "oracle",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": true,
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "gateway",
    "testFrameworks": [
      "gatling",
      "cucumber",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

node: v8.6.0

npm: 5.4.2

bower: 1.8.2

gulp:
[16:17:10] CLI version 1.4.0

yeoman: 2.0.0

yarn: 1.1.0

##### **Browsers and Operating System**
**windows 7**
**chrome**
**apache maven 3.5.0** 
**Please note : I've just setup this system.**

- [*] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment] 2017-10-22 11:42
As you are using Oracle, are you sure you don't have an issue downloading the Oracle JDBC drivers?

**Comment by hassnainali** [comment] 2017-10-22 11:46
@jdubois thank you for replying. I've updated the oracle12c dependency and these are the step I've followed in order to add the jdbc dependency.
Download the jdbc7 jar file which can be found here
http://www.oracle.com/technetwork/database/features/jdbc/jdbc-drivers-12c-download-1958347.html

mvn install:install-file -Dfile=C:\\OracleJDBC\\ojdbc7.jar -DgroupId=com.oracle -DartifactId=ojdbc7 -Dversion=12.1.0 -Dpackaging=jar

This is the dependency I've updated
<dependency>
    <groupId>com.oracle</groupId>
    <artifactId>ojdbc7</artifactId>
    <version>12.1.0</version>
</dependency

**Comment by jdubois** [comment] 2017-10-22 17:21
Yes did you see it in our documentation? And is your problem solved?

**Comment by hassnainali** [comment] 2017-10-22 18:33
No I've tried couple of thing but I'm unable to solve this problem. Yes I've seen the documentation as well but I followed a different website in order to add the ORACLE jdbc dependency for 12c. 
I tried to add different jar i.e hazalcast core, hazalcast-spring but it did not work as well because I think I was not adding the correct jar/dependencies. @jdubois 

please note I think its not a JDBC driver issue as I'm using this driver in the jhipster monolethical application configure with Ehcache.

**Comment by pascalgrimaud** [comment] 2017-10-22 19:08
There is the same post on stackoverflow: https://stackoverflow.com/questions/46848897/jhipster-microservice-gatway-error-for-hazelcast
Plz don't cross post.

I just tried your configuration, and I don't have any issue.
See my IDE:
![jhipster-oracle](https://user-images.githubusercontent.com/9156882/31865281-cc3de29c-b76c-11e7-8acb-49559e88366a.png)

**Comment by hassnainali** [comment] 2017-10-22 19:23
@pascalgrimaud  thank you for replying. can you please take backup of your .m2 folder and download these dependencies again? I'm using jHipster 4.9.0 and maven 3.5.0. Sorry for the cross post but if I'm doing something wrong please point it out. There is no answer at the stackower question. if you can only pinpoint where I'm wrong, it would be great.

**Comment by pascalgrimaud** [comment] 2017-10-22 19:27
it's a fresh download, as I formatted my computer and reinstalled ubuntu
17.10 tonight.
I think it's an IDE issue. Is it working with only your terminal or another
IDE ?

**Comment by jdubois** [comment] 2017-10-22 19:29
Sorry but that's really not nice to cross post. At the moment I don't see why this would be a JHipster bug, so if we cannot reproduce that's a configuration issue and should be on StackOverflow.
That's why I'm closing this.

**Closed by jdubois** 2017-10-22 19:29 UTC

**Comment by hassnainali** [comment] 2017-10-22 19:38
@pascalgrimaud thank you i'll download all of the dependencies again. Actually I'm stuck on this issue since Friday. @jdubois sorry for the cross post.

**Comment by jdubois** [comment] 2017-10-22 19:41
Yes I guess you have an IDE issue that is not trivial but can we discuss this on StackOverflow? It's nicer for other people, here it will just get lost in the tickets

**Comment by hassnainali** [comment] 2017-10-22 19:47
@jdubois  yeah sure
