### ISSUE TITLE
Generating new entity with jhipster using CLI "jhipsterVersion": "3.9.0"

### ISSUE THREAD

**Issue by sarjerav** [jhipster/generator-jhipster#4315] opened 2016-10-12 06:24 UTC
I am trying to generate CRUD using jhipster but while entity creation I got stuck .

I'm getting random exceptions like this & below are the details :-

**Stack Trace :-**
```
> 2016-10-12 11:34:30.281  WARN 6712 --- [  restartedMain] ationConfigEmbeddedWebApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'hospitalServiceImpl': Unsatisfied dependency expressed through field 'hospitalMapper'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean found for dependency [com.org.hospapp.service.mapper.HospitalMapper]: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@javax.inject.Inject()}
2016-10-12 11:34:30.325  INFO 6712 --- [  restartedMain] c.f.hospapp.config.CacheConfiguration    : Remove Cache Manager metrics
2016-10-12 11:34:30.350  INFO 6712 --- [  restartedMain] c.f.hospapp.config.CacheConfiguration    : Closing Cache Manager
2016-10-12 11:34:30.484  WARN 6712 --- [  restartedMain] .s.c.a.CommonAnnotationBeanPostProcessor : Invocation of destroy method failed on bean with name 'cacheConfiguration': java.lang.NullPointerException
2016-10-12 11:34:30.518  WARN 6712 --- [  restartedMain] o.s.boot.SpringApplication               : Error handling failed (Error creating bean with name 'delegatingApplicationListener' defined in class path resource [org/springframework/security/config/annotation/web/configuration/WebSecurityConfiguration.class]: BeanPostProcessor before instantiation of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.cache.annotation.ProxyCachingConfiguration': Initialization of bean failed; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'org.springframework.context.annotation.ConfigurationClassPostProcessor.importRegistry' is defined)
2016-10-12 11:34:30.532  WARN 6712 --- [-app-Executor-1] com.zaxxer.hikari.pool.ProxyConnection   : HikariPool-1 - Connection com.mysql.jdbc.JDBC4Connection@4c5dd618 marked as broken because of SQLSTATE(08003), ErrorCode(0)

> com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException:

>  Connection.close() has already been called. Invalid operation in this state.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
	at com.mysql.jdbc.Util.getInstance(Util.java:381)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:984)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:926)
	at com.mysql.jdbc.ConnectionImpl.getMutex(ConnectionImpl.java:3018)
	at com.mysql.jdbc.ConnectionImpl.rollback(ConnectionImpl.java:4564)
	at com.zaxxer.hikari.pool.ProxyConnection.rollback(ProxyConnection.java:360)
	at com.zaxxer.hikari.pool.HikariProxyConnection.rollback(HikariProxyConnection.java)
	at liquibase.database.jvm.JdbcConnection.rollback(JdbcConnection.java:337)
	at liquibase.database.AbstractJdbcDatabase.rollback(AbstractJdbcDatabase.java:1141)
	at liquibase.lockservice.StandardLockService.acquireLock(StandardLockService.java:197)
	at liquibase.lockservice.StandardLockService.waitForLock(StandardLockService.java:164)
	at liquibase.Liquibase.update(Liquibase.java:196)
	at liquibase.Liquibase.update(Liquibase.java:192)
	at liquibase.integration.spring.SpringLiquibase.performUpdate(SpringLiquibase.java:434)
	at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:391)
	at 

> com.org.hospapp.config.liquibase.AsyncSpringLiquibase.initDb(AsyncSpringLiquibase.java:67)

	at 

> com.org.hospapp.config.liquibase.AsyncSpringLiquibase.lambda$0(AsyncSpringLiquibase.java:50)

	at 

>com.org.hospapp.async.ExceptionHandlingAsyncTaskExecutor.lambda$1(ExceptionHandlingAsyncTaskExecutor.java:47)

	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

> 2016-10-12 11:34:30.682  WARN 6712 --- [-app-Executor-1] liquibase                                : Failed to restore the auto commit to true
2016-10-12 11:34:30.683 ERROR 6712 --- [-app-Executor-1] c.f.h.c.liquibase.AsyncSpringLiquibase   : Liquibase could not start correctly, your database is NOT ready: java.sql.SQLException: Connection is closed

> liquibase.exception.DatabaseException: java.sql.SQLException: Connection is closed
> 	at liquibase.database.jvm.JdbcConnection.setAutoCommit(JdbcConnection.java:363)
> 	at liquibase.database.AbstractJdbcDatabase.close(AbstractJdbcDatabase.java:1176)
> 	at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:400)
> 	at com.org.hospapp.config.liquibase.AsyncSpringLiquibase.initDb(AsyncSpringLiquibase.java:67)
> 	at com.org.hospapp.config.liquibase.AsyncSpringLiquibase.lambda$0(AsyncSpringLiquibase.java:50)
> 	at com.org.hospapp.async.ExceptionHandlingAsyncTaskExecutor.lambda$1(ExceptionHandlingAsyncTaskExecutor.java:47)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
> 	at java.lang.Thread.run(Unknown Source)
> Caused by: java.sql.SQLException: Connection is closed
> 	at com.zaxxer.hikari.pool.ProxyConnection$ClosedConnection$1.invoke(ProxyConnection.java:468)
> 	at com.sun.proxy.$Proxy114.setAutoCommit(Unknown Source)
> 	at com.zaxxer.hikari.pool.ProxyConnection.setAutoCommit(ProxyConnection.java:378)
> 	at com.zaxxer.hikari.pool.HikariProxyConnection.setAutoCommit(HikariProxyConnection.java)
> 	at liquibase.database.jvm.JdbcConnection.setAutoCommit(JdbcConnection.java:361)
> 	... 8 common frames omitted
> 
> 2016-10-12 11:34:32.530 ERROR 6712 --- [  restartedMain] o.s.b.d.LoggingFailureAnalysisReporter   : 
> 
> ***************************
> APPLICATION FAILED TO START
> ***************************
> 
> Description:
> 
> Field hospitalMapper in com.org.hospapp.service.impl.HospitalServiceImpl required a bean of type 'com.org.hospapp.service.mapper.HospitalMapper' that could not be found.
> 
> 
> Action:
> 
> Consider defining a bean of type 'com.org.hospapp.service.mapper.HospitalMapper' in your configuration.
```

**generator-jhipster version 3.9.0**

JHipster configuration, a .yo-rc.json file generated in the root folder
```
{
  "generator-jhipster": {
    "jhipsterVersion": "3.9.0",
    "baseName": "HospitalApp",
    "packageName": "com.org.hospapp",
    "packageFolder": "com/org/hospapp",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "buildTool": "maven",
    "enableSocialSignIn": true,
    "rememberMeKey": "262e1b4347c3d859901df4cbe85e6799650bcb79",
    "useSass": false,
    "applicationType": "monolith",
    "testFrameworks": [
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}
```
##### **Reproduce the error**

`G:\Flowian\jHipster\MedicalApp>yo jhipster:entity hospital`
```
The entity hospital is being created.
Generating field #1

? Do you want to add a field to your entity? Yes
? What is the name of your field? hospitalName
? What is the type of your field? String
? Do you want to add validation rules to your field? Yes
? Which validation rules do you want to add? Required

================= Hospital =================
Fields
hospitalName (String) required

Generating field #2
? Do you want to add a field to your entity? No
================= Hospital =================
Fields
hospitalName (String) required

Generating relationships to other entities? 
Do you want to add a relationship to another entity? No

================= Hospital =================
Fields
hospitalName (String) required

? Do you want to use a Data Transfer Object (DTO)? [BETA] Yes, generate a DTO with MapStruct
? Do you want to use separate service class for your business logic? Yes, generate a separate service interface and implementation
? Do you want pagination on your entity? Yes, with pagination links

Everything is configured, generating the entity...

   create .jhipster\Hospital.json
   create src\main\resources\config\liquibase\changelog\20161012054120_added_entity_Hospital.xml
 conflict src\main\resources\config\liquibase\master.xml
? Overwrite src\main\resources\config\liquibase\master.xml? overwrite
    force src\main\resources\config\liquibase\master.xml
   create src\main\java\com\org\hospapp\domain\Hospital.java
   create src\main\java\com\org\hospapp\repository\HospitalRepository.java
   create src\main\java\com\org\hospapp\repository\search\HospitalSearchRepository.java
   create src\main\java\com\org\hospapp\web\rest\HospitalResource.java
   create src\main\java\com\org\hospapp\service\HospitalService.java
   create src\main\java\com\org\hospapp\service\impl\HospitalServiceImpl.java
   create src\main\java\com\org\hospapp\service\dto\HospitalDTO.java
   create src\main\java\com\org\hospapp\service\mapper\HospitalMapper.java
 conflict src\main\resources\ehcache.xml
? Overwrite src\main\resources\ehcache.xml? overwrite
    force src\main\resources\ehcache.xml
   create src\main\webapp\app\entities\hospital\hospitals.html
   create src\main\webapp\app\entities\hospital\hospital-detail.html
   create src\main\webapp\app\entities\hospital\hospital-dialog.html
   create src\main\webapp\app\entities\hospital\hospital-delete-dialog.html
   create src\main\webapp\app\entities\hospital\hospital.state.js
   create src\main\webapp\app\entities\hospital\hospital.controller.js
   create src\main\webapp\app\entities\hospital\hospital-dialog.controller.js
   create src\main\webapp\app\entities\hospital\hospital-delete-dialog.controller.js
   create src\main\webapp\app\entities\hospital\hospital-detail.controller.js
   create src\main\webapp\app\entities\hospital\hospital.service.js
   create src\main\webapp\app\entities\hospital\hospital.search.service.js
identical src\test\javascript\spec\app\entities\hospital\hospital-detail.controller.spec.js
identical src\test\javascript\e2e\entities\hospital.js
   create src\test\java\com\org\hospapp\web\rest\HospitalResourceIntTest.java

Running gulp Inject to add javascript to index

Using gulpfile G:\Flowian\jHipster\MedicalApp\gulpfile.js
Starting 'inject:app'...
gulp-inject 112 files into index.html.
Finished 'inject:app' after 381 ms
```
##### ** Entity Creation Bug **
```
{
    "fluentMethods": true,
    "relationships": [],
    "fields": [
        {
            "fieldName": "hospitalName",
            "fieldType": "String",
            "fieldValidateRules": [
                "required"
            ]
        }
    ],
    "changelogDate": "20161012054120",
    "dto": "mapstruct",
    "service": "serviceImpl",
    "entityTableName": "hospital",
    "pagination": "pagination"
}
```
##### ** Browsers and Operating System
=====================
Apache Maven 3.3.9
Maven home: D:\JAVA\installation\apache-maven-3.3.9
Java version: 1.8.0_25, vendor: Oracle Corporation
Java home: C:\Program Files\Java\jdk1.8.0_25\jre
Default locale: en_IN, platform encoding: Cp1252
OS name: "windows 7", version: "6.1", arch: "amd64", family: "dos"

java version "1.8.0_92"
Java(TM) SE Runtime Environment (build 1.8.0_92-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.92-b14, mixed mode)

Please correct me if I'm wrong .

Thanks
sarjerav

**Comment by deepu105** [comment] 2016-10-12 07:39
Is your MySQL database started and accessible, have you configured its url and credentials in the `application-dev.yml`?

**Comment by jdubois** [comment] 2016-10-12 10:19
Yes the stacktrace says your database isn't running...

**Comment by sarjerav** [comment] 2016-10-17 12:21
But when i tried without any generation of entity using CLI then i can run my project without any errors.

Also MySQL database started and accessible, I configured its url and credentials in the application-dev.yml.

**Comment by sarjerav** [comment] 2016-10-17 12:28
**Below is my stack trace :-**

2016-10-17 17:54:50.153  INFO 4104 --- [  restartedMain] com.org.demoapp.demoApp      : Starting demoApp on Admin-PC with PID 4104 
2016-10-17 17:54:50.270 DEBUG 4104 --- [  restartedMain] com.org.demoapp.demoApp      : Running with Spring Boot v1.4.1.RELEASE, Spring v4.3.3.RELEASE
2016-10-17 17:54:50.270  INFO 4104 --- [  restartedMain] com.org.demoapp.demoApp      : The following profiles are active: swagger,dev
2016-10-17 17:54:50.478 DEBUG 4104 --- [kground-preinit] org.jboss.logging                        : Logging Provider: org.jboss.logging.Slf4jLoggerProvider found via system property
2016-10-17 17:54:56.269 DEBUG 4104 --- [  restartedMain] c.f.h.config.AsyncConfiguration          : Creating Async Task Executor
2016-10-17 17:54:57.671 DEBUG 4104 --- [  restartedMain] c.f.h.config.MetricsConfiguration        : Registering JVM gauges
2016-10-17 17:54:57.702 DEBUG 4104 --- [  restartedMain] c.f.h.config.MetricsConfiguration        : Monitoring the datasource
2016-10-17 17:54:57.709 DEBUG 4104 --- [  restartedMain] c.f.h.config.MetricsConfiguration        : Initializing Metrics JMX reporting
2016-10-17 17:54:58.921  WARN 4104 --- [  restartedMain] io.undertow.websockets.jsr               : UT026009: XNIO worker was not set on WebSocketDeploymentInfo, the default worker will be used
2016-10-17 17:54:58.928  WARN 4104 --- [  restartedMain] io.undertow.websockets.jsr               : UT026010: Buffer pool was not set on WebSocketDeploymentInfo, the default pool will be used
2016-10-17 17:54:59.962  INFO 4104 --- [  restartedMain] c.f.demoapp.config.WebConfigurer     : Web application configuration, using profiles: [swagger, dev]
2016-10-17 17:54:59.969 DEBUG 4104 --- [  restartedMain] c.f.demoapp.config.WebConfigurer     : Initializing Metrics registries
2016-10-17 17:54:59.981 DEBUG 4104 --- [  restartedMain] c.f.demoapp.config.WebConfigurer     : Registering Metrics Filter
2016-10-17 17:54:59.982 DEBUG 4104 --- [  restartedMain] c.f.demoapp.config.WebConfigurer     : Registering Metrics Servlet
2016-10-17 17:54:59.994  INFO 4104 --- [  restartedMain] c.f.demoapp.config.WebConfigurer     : Web application fully configured
2016-10-17 17:55:00.493 DEBUG 4104 --- [  restartedMain] c.f.h.config.DatabaseConfiguration       : Configuring Liquibase
2016-10-17 17:55:00.526  WARN 4104 --- [-app-Executor-1] c.f.h.c.liquibase.AsyncSpringLiquibase   : Starting Liquibase asynchronously, your database might not be ready at startup!
2016-10-17 17:55:03.193  WARN 4104 --- [  restartedMain] o.h.c.e.AbstractEhcacheRegionFactory     : HHH020003: Could not find a specific ehcache configuration for cache named [com.org.demoapp.domain.SocialUserConnection]; using defaults.
2016-10-17 17:55:03.583  INFO 4104 --- [  restartedMain] com.org.demoapp.demoApp      : Running with Spring profile(s) : [swagger, dev]
2016-10-17 17:55:09.679 DEBUG 4104 --- [  restartedMain] c.f.h.config.social.SocialConfiguration  : Configuring GoogleConnectionFactory
2016-10-17 17:55:09.705 DEBUG 4104 --- [  restartedMain] c.f.h.config.social.SocialConfiguration  : Configuring FacebookConnectionFactory
2016-10-17 17:55:09.713 DEBUG 4104 --- [  restartedMain] c.f.h.config.social.SocialConfiguration  : Configuring TwitterConnectionFactory
2016-10-17 17:55:10.827  WARN 4104 --- [  restartedMain] ationConfigEmbeddedWebApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'authorResource': Unsatisfied dependency expressed through field 'authorMapper'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean found for dependency [com.org.demoapp.service.mapper.AuthorMapper]: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@javax.inject.Inject()}
2016-10-17 17:55:10.870  INFO 4104 --- [  restartedMain] c.f.h.config.CacheConfiguration          : Remove Cache Manager metrics
2016-10-17 17:55:10.882  INFO 4104 --- [  restartedMain] c.f.h.config.CacheConfiguration          : Closing Cache Manager
2016-10-17 17:55:10.883  WARN 4104 --- [  restartedMain] .s.c.a.CommonAnnotationBeanPostProcessor : Invocation of destroy method failed on bean with name 'cacheConfiguration': java.lang.NullPointerException
2016-10-17 17:55:10.993  WARN 4104 --- [  restartedMain] o.s.boot.SpringApplication               : Error handling failed (Error creating bean with name 'delegatingApplicationListener' defined in class path resource [org/springframework/security/config/annotation/web/configuration/WebSecurityConfiguration.class]: BeanPostProcessor before instantiation of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.cache.annotation.ProxyCachingConfiguration': Initialization of bean failed; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'org.springframework.context.annotation.ConfigurationClassPostProcessor.importRegistry' is defined)
2016-10-17 17:55:10.996  WARN 4104 --- [-app-Executor-1] com.zaxxer.hikari.pool.ProxyConnection   : HikariPool-1 - Connection com.mysql.jdbc.JDBC4Connection@6a26ffa1 marked as broken because of SQLSTATE(08003), ErrorCode(0)

com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Connection.close() has already been called. Invalid operation in this state.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
	at com.mysql.jdbc.Util.getInstance(Util.java:381)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:984)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:926)
	at com.mysql.jdbc.ConnectionImpl.getMutex(ConnectionImpl.java:3018)
	at com.mysql.jdbc.ConnectionImpl.rollback(ConnectionImpl.java:4564)
	at com.zaxxer.hikari.pool.ProxyConnection.rollback(ProxyConnection.java:360)
	at com.zaxxer.hikari.pool.HikariProxyConnection.rollback(HikariProxyConnection.java)
	at liquibase.database.jvm.JdbcConnection.rollback(JdbcConnection.java:337)
	at liquibase.database.AbstractJdbcDatabase.rollback(AbstractJdbcDatabase.java:1141)
	at liquibase.lockservice.StandardLockService.acquireLock(StandardLockService.java:197)
	at liquibase.lockservice.StandardLockService.waitForLock(StandardLockService.java:164)
	at liquibase.Liquibase.update(Liquibase.java:196)
	at liquibase.Liquibase.update(Liquibase.java:192)
	at liquibase.integration.spring.SpringLiquibase.performUpdate(SpringLiquibase.java:434)
	at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:391)
	at com.org.demoapp.config.liquibase.AsyncSpringLiquibase.initDb(AsyncSpringLiquibase.java:67)
	at com.org.demoapp.config.liquibase.AsyncSpringLiquibase.lambda$0(AsyncSpringLiquibase.java:50)
	at com.org.demoapp.async.ExceptionHandlingAsyncTaskExecutor.lambda$1(ExceptionHandlingAsyncTaskExecutor.java:47)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

2016-10-17 17:55:11.008  WARN 4104 --- [-app-Executor-1] liquibase                                : Failed to restore the auto commit to true
2016-10-17 17:55:11.031 ERROR 4104 --- [-app-Executor-1] c.f.h.c.liquibase.AsyncSpringLiquibase   : Liquibase could not start correctly, your database is NOT ready: java.sql.SQLException: Connection is closed

liquibase.exception.DatabaseException: java.sql.SQLException: Connection is closed
	at liquibase.database.jvm.JdbcConnection.setAutoCommit(JdbcConnection.java:363)
	at liquibase.database.AbstractJdbcDatabase.close(AbstractJdbcDatabase.java:1176)
	at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:400)
	at com.org.demoapp.config.liquibase.AsyncSpringLiquibase.initDb(AsyncSpringLiquibase.java:67)
	at com.org.demoapp.config.liquibase.AsyncSpringLiquibase.lambda$0(AsyncSpringLiquibase.java:50)
	at com.org.demoapp.async.ExceptionHandlingAsyncTaskExecutor.lambda$1(ExceptionHandlingAsyncTaskExecutor.java:47)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.sql.SQLException: Connection is closed
	at com.zaxxer.hikari.pool.ProxyConnection$ClosedConnection$1.invoke(ProxyConnection.java:468)
	at com.sun.proxy.$Proxy105.setAutoCommit(Unknown Source)
	at com.zaxxer.hikari.pool.ProxyConnection.setAutoCommit(ProxyConnection.java:378)
	at com.zaxxer.hikari.pool.HikariProxyConnection.setAutoCommit(HikariProxyConnection.java)
	at liquibase.database.jvm.JdbcConnection.setAutoCommit(JdbcConnection.java:361)
	... 8 common frames omitted

2016-10-17 17:55:11.738 ERROR 4104 --- [  restartedMain] o.s.b.d.LoggingFailureAnalysisReporter   : 

***************************
APPLICATION FAILED TO START
***************************

Description:

Field authorMapper in com.org.demoapp.web.rest.AuthorResource required a bean of type 'com.org.demoapp.service.mapper.AuthorMapper' that could not be found.


Action:

Consider defining a bean of type 'com.org.demoapp.service.mapper.AuthorMapper' in your configuration.

**Comment by sarjerav** [comment] 2016-10-19 04:53
Yes I have ran maven & AuthorMapperImpl class was generated in target folder too.

But still there is issue with me.

**Comment by sarjerav** [comment] 2016-10-19 04:54
can you change **status of my issue** to **open**

**Comment by jdubois** [comment] 2016-10-19 06:42
Can you send your full configuration? Yes I'll reopen the ticket this
evening (not possible from my phone at the moment)

Le 19 oct. 2016 6:54 AM, "sarjerav" <notifications@github.com> a écrit :

can you change *status of my issue* to *open*

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/jhipster/generator-jhipster/issues/4315#issuecomment-254710212>,
or mute the thread

**Comment by sarjerav** [comment] 2016-10-19 07:00
@jdubois Yeah but I have given full config in my first post .

**Comment by sarjerav** [comment] 2016-10-19 09:07
Also **change the label** too as I have provided all configuration too.

**Comment by pascalgrimaud** [comment] 2016-10-19 10:15
You have an error with `com.org.demoapp.web.rest.AuthorResource`
Our generator doesn't generate this class, that means it's your code.

I'm using all information you provided to generate a new project:
- your `.yo-rc.json`
- your `.jhipster/Hospital.json`
- using: `yo jhipster --force --with-entities`

Then, start the app with `mvn`
I dont have any issue:

```
2016-10-19 12:13:04.636  INFO 32096 --- [  restartedMain] com.org.hospapp.HospitalApp              : Started HospitalApp in 15.686 seconds (JVM running for 15.954)
2016-10-19 12:13:04.637  INFO 32096 --- [  restartedMain] com.org.hospapp.HospitalApp              : 
----------------------------------------------------------
	Application 'HospitalApp' is running! Access URLs:
	Local: 		http://localhost:8080
	External: 	http://127.0.1.1:8080
----------------------------------------------------------
```

**Comment by deepu105** [comment] 2016-10-19 10:18
@sarjerav we cannot waste our time debugging issues with partial information. Please provide config of all the entities you generated and if you have modified any code mention details of that as well. I'll wait for your response this time, but in future please provide all info asked

**Comment by pascalgrimaud** [comment] 2016-10-25 04:48
I'm closing this, as I can't reproduce and there is no additional information.
There seems to be 2 different config here:
- 1 for HospitalApp (configuration provided)
- 1 for demoApp (2nd stacktrace)

**Closed by pascalgrimaud** 2016-10-25 04:48 UTC
Labels: waiting for information

**Comment by felipebcs** [comment] 2016-11-20 03:39
If anyone land on this page looking for a possible solution:
I had a similar problem using Maven and Eclipse. At the end I realized that I hadn't read well the bottom of the "Configuring your IDE" page, which says about MapStruct, but I also had to add the _target/generated-sources_ folder to my build path (as instructed on http://g00glen00b.be/mapstruct/ ).
