### ISSUE TITLE
Many-To-Many relationship with User

### ISSUE THREAD

**Issue by Blucky87** [jhipster/generator-jhipster#3827] opened 2016-07-12 04:49 UTC
##### **Overview of the issue**

Unable to set up a Many-To-Many relationship with User entity

##### **Motivation for or Use Case** 

Creating a Many-To-Many relationship using the User

##### **JHipster Version(s)** 

3.4.2

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 

[.yo-rc.json](https://gist.github.com/Blucky87/ed19c6eafe48842189242b22f801c02a)

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory** 

[Team.json](https://gist.github.com/Blucky87/a6046c5b3b1219b096a4fd1474ee269c)

##### **Browsers and Operating System** 

Jhipster vagrant box

##### **Reproduce the error** 

generate new project
generate entity
try and create the entity in the app selecting multiple users and save it

##### **Suggest a Fix** 

Unsure

**Comment by deepu105** [comment] 2016-07-12 07:47
We do not support many to many with User entity yet so this is not a bug

**Comment by deepu105** [comment] 2016-07-12 07:50
@jdubois what do you think?  Should we support this?

**Comment by cbornet** [comment] 2016-07-12 09:47
An easy workaround is to create an intermediate CustomUser entity that is one-to-one with User and then make your many-to-many with this entity.

**Comment by jdubois** [comment] 2016-08-10 15:53
I just tried it and it works. Of course that wasn't on purpose, it's just our code is so good :-)

There is just one limitation: the other entity must be the owner of the relationship (otherwise we would need to modify the user entity). And of course, if you want to delete a user, you will need to delete first the relationship (but that's normal, as the user isn't the owner of the relationship).

I'm documenting this (that will be quick) and close this.

**Closed** 2016-08-10 15:59 UTC
Labels: feature request

**Comment by deepu105** [comment] 2016-08-10 16:52
Btw we should also document that one-to-one with user works as well :),
basically except one-to-many everything seems to work as long as User is
not the owner :)


Thanks & Regards,
Deepu

**Comment by jdubois** [comment] 2016-08-11 07:19
Yes I'll do it, thanks for pointing this out.

Le 10 août 2016 6:52 PM, "Deepu K Sasidharan" <notifications@github.com> a
écrit :
