### ISSUE TITLE
Bug in _UserService - updateUser method

### ISSUE THREAD

**Issue by mhavrlent** [jhipster/generator-jhipster#4551] opened 2016-11-25 20:48 UTC
##### **Overview of the issue**

I think I found a bug in the following:
file: generators/server/templates/src/main/java/package/service/_UserService.java
method: updateUser
code: 
196                 <%_ } else { // Cassandra _%>
197                 u.setAuthorities(authorities);
198                 <%_ } _%>
199                 <%_ if (databaseType == 'mongodb' || databaseType == 'cassandra') { _%>
200                 userRepository.save(u);
201                 <%_ } _%>

When the databaseType is sql like for mysql, the following two lines will be excluded from the generated code. That will prevent the record from being updated in the database.
u.setAuthorities(authorities);
userRepository.save(u);

##### **Reproduce the error**

1. generate app
mkdir myapp
cd myapp
yo jhipster

Use sql database!

2. Open user management page and hit the "activated" button to deactivate user.
3. Record in the database for that user wasn't changed. Activated is 1 instead of 0.

##### **JHipster Version(s)**

```
l4-portal@0.0.0 /home/toor/git/l4-portal
└── generator-jhipster@3.10.0 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "jhipsterVersion": "3.10.0",
    "baseName": "app",
    "packageName": "com.app.gw",
    "packageFolder": "com/app/gw",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "gradle",
    "enableSocialSignIn": false,
    "jwtSecretKey": "secret",
    "useSass": false,
    "applicationType": "gateway",
    "testFrameworks": [
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}
```

##### **Browsers and Operating System**

java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)

git version 2.7.4

node: v6.9.1

npm: 3.10.6

bower: 1.8.0

gulp:
[21:44:11] CLI version 1.2.2
[21:44:11] Local version 3.9.1

yeoman: 1.8.5

Docker version 1.12.3, build 6b644ec

**Comment by jdubois** [comment] 2016-11-25 21:35
That would be a terrible bug in JPA!!! Maybe that's because of the lambda expression?
This is top priority for me, I'll have a look ASAP

**Comment by jdubois** [comment] 2016-11-25 21:41
I just tested, no problem at all....
So maybe that's because:

- I'm on the dev branch, and we upgraded to Hibernate 5 -> then that would be temporary issue in JPA? Very, very weird
- You using Hazelcast? That would be also very, very weird

I don't have more time this week-end for this, are you sure you can reproduce this issue?? That's so strange!

**Comment by jdubois** [comment] 2016-11-25 21:52
Reading your ticket again, are you sure you tested this? At the end of the ticket you say you tested this, but at the beginning it's more like you just read the code and think there's an issue, but didn't test... And what you say is wrong, unless there's a bug in Hibernate, of course.

I'm now thinking you just made a mistake, so I'm closing this.

**Comment by mhavrlent** [comment] 2016-11-25 22:01
Well my records were not updated in the database so I started looking into the code and found out that my generated method is missing userRepository.save(u); call. Then I looked at the _UserService in the generator and found out that it's calling save only for 'mongodb' and 'cassandra' but not for 'sql'. Once I've put the missing userRepository.save(u); call it's working again.

Why do you think it's a terrible bug in JPA if we're not calling the userRepository.save(u);?
I think it's expected.

To your questions:
Yes, I'm using Hazelcast.

**Comment by jdubois** [comment] 2016-11-25 22:05
You don't need to call "save", the entity is managed by JPA and this is in a transaction, so it should be saved automatically.
I'm having doubts now!!! Maybe it fails with a lambda expression? Are you sure this doesn't work?

**Comment by mhavrlent** [comment] 2016-11-25 22:07
I'm sure it doesn't work for me without the call. What I can do is generate a new application and test it out again next week.

**Comment by pascalgrimaud** [comment] 2016-11-25 22:07
Just tested with the exact 3.10.0, no problem too.
Activated -> green/red without problem

Go inside my MySQL container to make select * from jhi_user; -> everything is correct

**Comment by jdubois** [comment] 2016-11-25 22:08
Oh, reading the code again, it's "saved" in the other update method... I'm reopening this, there's something I don't understand here.

**Comment by mhavrlent** [comment] 2016-11-25 22:08
Yes, there are two methods. I put the number of lines into the ticket so check those lines.

**Comment by mhavrlent** [comment] 2016-11-25 22:11
To be precise, there are two generated methods. I'm not sure they're generated using the same code.

**Comment by jdubois** [comment] 2016-11-25 22:14
Yes and there's also a useless "save" in the "changepassword" method.

What the hell is all that???

- For me all those "save" are useless
- I'm going to test this to be really sure
- Then I can't reproduce your issue

**Comment by jdubois** [comment] 2016-11-25 22:20
- I confirm all those "save" are useless, and I have found 3 more in `activateRegistration` `completePasswordReset` `requestPasswordReset`
- I'm going to correct all those and link those to this issue
- @mhavrlent I cannot reproduce your issue, and as @pascalgrimaud also couldn't, this shouldn't be linked to Hibernate 5. So yes if you can generate a sample app, or a unit test, so I can reproduce, that would be great

**Comment by jdubois** [comment] 2016-11-25 22:41
Closing this as I can't reproduce, but if we have some working example from @mhavrlent I'll be happy to solve this

**Closed by jdubois** 2016-11-25 22:41 UTC
