### ISSUE TITLE
Angular application is broken (generated with gateway)

### ISSUE THREAD

**Issue by artem-korolev** [jhipster/generator-jhipster#11505] opened 2020-03-24 14:35 UTC
##### **Overview of the issue**

Installed JHipster just today. Fresh version. Created gateway application with Angular frontend.
Angular frontend is unable to load in browser (npm install works okay, npm start is also good).

Browser log show this error:
TypeError: clazz.decorators is undefined

React frontend is working good.

I use Jhipster Registry + oauth2. no database, no entities. just generated jhipster gateway application with Angular

##### **Motivation for or Use Case**

I cannot use Angular frontend, because its not loading at all

##### **Reproduce the error**

http://localhost:9000/

##### **JHipster Version(s)**

6.8.0

##### **JHipster configuration**

INFO! Using JHipster version installed locally in current project's node_modules
INFO! Executing jhipster:info
INFO! Options: from-cli: true
Welcome to the JHipster Information Sub-Generator

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "fitsearch.admin.gateway",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "6.8.0",
    "applicationType": "gateway",
    "baseName": "fitsearch_admin_gateway",
    "packageName": "fitsearch.admin.gateway",
    "packageFolder": "fitsearch/admin/gateway",
    "serverPort": "8080",
    "authenticationType": "oauth2",
    "cacheProvider": "no",
    "enableHibernateCache": false,
    "websocket": false,
    "databaseType": "no",
    "devDatabaseType": "no",
    "prodDatabaseType": "no",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "embeddableLaunchScript": false,
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "angularX",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "creationTimestamp": 1585058209410,
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": ["en", "et", "ru"],
    "blueprints": []
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.6+10)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.18.1, JRE 11 Windows 10 amd64-64-Bit Compressed References 20200122_442 (JIT enabled, AOT enabled)
OpenJ9   - 51a5857d2
OMR      - 7a1b0239a
JCL      - da35e0c380 based on jdk-11.0.6+10)

git version 2.25.1.windows.1

node: v12.16.1

npm: 6.13.4

yeoman: 3.1.1

Docker version 19.03.1, build 74b1e89e8a

docker-compose version 1.24.1, build 4667896b

INFO! Congratulations, JHipster execution is complete!

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

no entities. no database. its gateway with only Angular frontend

##### **Browsers and Operating System**

Windows 10, Firefox Developer Edition 75.0b7 (64-bit)

-   [+] Checking this box is mandatory (this is just to show you read everything)

**Comment by ruddell** [comment] 2020-03-24 18:38
Can you try with a regular release of a browser?  I couldn't reproduce with Firefox 74.0 (64-bit) or Chrome (on Mac), but don't have a developer edition installed.

**Comment by artem-korolev** [comment] 2020-03-24 18:48
you right. I tried it with Microsoft Edge and it also works well.
seems to be compatibility issue with firefox developer edition.
thank you

**Comment by artem-korolev** [comment] 2020-03-24 18:51
issue comes from @angular/core. seems. probably I need to raise it there to solve it

**Comment by artem-korolev** [comment] 2020-03-24 19:03
hard to say. yes. it does not work only in firefox developer edition. so I believe its minor issue. but where is the issue - hard to say. typescript, webpack, angular...

**Comment by artem-korolev** [comment] 2020-03-24 19:21
seems issue is really in angular/core:

**..__/fesm2015/core.js:**
```javascript
if (decorators !== null) {
            if (clazz.decorators !== undefined &&
                (!parentConstructor || parentConstructor.decorators !== clazz.decorators)) {
                clazz.decorators.push(...decorators); // ** TypeError: clazz.decorators is undefined **
            }
            else {
                clazz.decorators = decorators;
            }
        }
```

**Comment by artem-korolev** [comment] 2020-03-24 19:58
I published this bug to firefox bugzilla - https://bugzilla.mozilla.org/show_bug.cgi?id=1624693

**Comment by SudharakaP** [comment] 2020-03-24 20:24
@artem-korolev : The Developer Edition has [experimental features and stuff](https://www.mozilla.org/en-US/privacy/firefox/#pre-release) and I've experienced lots of small issues like this with the developer edition. 

I am closing this issue, since we cannot do much about this here; if anyone feels otherwise feel free to re-open. :smile:

**Closed by SudharakaP** 2020-03-24 20:24 UTC
Labels: area: needs-reproduction, theme: angular
