### ISSUE TITLE
OneToMany relationship not generating liquibase column

### ISSUE THREAD

**Issue by nixgadget** [jhipster/generator-jhipster#4942] opened 2017-01-24 02:37 UTC
##### **Overview of the issue**
It appears that if I include a column (`subOrganization`) for the OneToMany relationship specified as in the `jdl` below however in the corresponding  generated liquibase changeset the column is missing.

```
entity OrgDetails {
    organizationId String required
    organizationName String required maxlength(512)
    organizationType OrgType required
}

entity OrgHierarchy {
    relationshipId String required
}

// One-to-One relationship definitions
relationship OneToOne {
    OrgHierarchy{parentOrganization} to OrgDetails
}

// One-to-Many relationship definitions
relationship OneToMany {
    OrgHierarchy{subOrganization} to OrgDetails
}
```

##### **Motivation for or Use Case**
Trying to establish a OneToMany relationship for one of the columns in OrgHierarchy,
```
OrgHierarchy {parentOrganization} (1) ----------------------> (1) OrgDetails
OrgHierarchy {subOrganization}  (1) ----------------------> (*) OrgDetails
```

The generated liquibase doesnt contain the column for some reason.

```
<?xml version="1.0" encoding="utf-8"?>
<databaseChangeLog
    xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
    xmlns:ext="http://www.liquibase.org/xml/ns/dbchangelog-ext"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.4.xsd
                        http://www.liquibase.org/xml/ns/dbchangelog-ext http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-ext.xsd">

    <property name="now" value="now()" dbms="mysql,h2"/>
    <property name="now" value="current_timestamp" dbms="postgresql"/>
    <property name="now" value="sysdate" dbms="oracle"/>
    <property name="now" value="GETDATE()" dbms="mssql"/>

    <property name="autoIncrement" value="true" dbms="mysql,h2,postgresql,oracle,mssql"/>

    <property name="floatType" value="float4" dbms="postgresql, h2"/>
    <property name="floatType" value="float" dbms="mysql, oracle, mssql"/>

    <!--
        Added the entity OrgHierarchy.
    -->
    <changeSet id="20170123225316-1" author="onboarding">
        <createTable tableName="org_hierarchy">
            <column name="id" type="bigint" autoIncrement="${autoIncrement}">
                <constraints primaryKey="true" nullable="false"/>
            </column>

            <column name="relationship_id" type="varchar(256)">
                <constraints nullable="false" />
            </column>

            <column name="parent_organization_id" type="bigint">
                <constraints unique="true" nullable="true" />
            </column>
        </createTable>
    </changeSet>
</databaseChangeLog>
```

##### **Reproduce the error**
NA

##### **Related issues**
NA

##### **Suggest a Fix**
NA

##### **JHipster Version(s)**

```
onboarding@0.0.0 /Volumes/STORAGE/Projects/Test/onboarding
└── generator-jhipster@3.12.2

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "jhipsterVersion": "3.12.2",
    "baseName": "onboarding",
    "packageName": "com.orchestral.dsm.onboarding",
    "packageFolder": "com/orchestral/dsm/onboarding",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "oracle",
    "prodDatabaseType": "oracle",
    "searchEngine": false,
    "messageBroker": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "jwtSecretKey": "f8254d93b9c60283bea2efe74eef1033922e5e01",
    "useSass": true,
    "applicationType": "monolith",
    "testFrameworks": [
      "cucumber"
    ],
    "jhiPrefix": "jhi",
    "otherModules": [
      {
        "name": "generator-jhipster-entity-audit",
        "version": "2.2.2"
      }
    ],
    "enableTranslation": false
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

Metadata.json

```yaml
{
    "fluentMethods": true,
    "relationships": [],
    "fields": [
        {
            "fieldName": "medicaidProviderStatus",
            "fieldType": "MedicaidProviderStatus",
            "fieldValues": "ELIGIBLE,NON_ELIGIBLE"
        },
        {
            "fieldName": "certifiedEHR",
            "fieldType": "CertifiedEHR",
            "fieldValues": "CERTIFIED,NON_CERTIFIED"
        },
        {
            "fieldName": "medicaidParticipation",
            "fieldType": "Boolean"
        },
        {
            "fieldName": "medicaidStage",
            "fieldType": "String"
        },
        {
            "fieldName": "medicaidEnrollmentDate",
            "fieldType": "ZonedDateTime"
        }
    ],
    "changelogDate": "20170123225317",
    "javadoc": "Metadata Entity\n\n@author kasunt",
    "entityTableName": "metadata",
    "dto": "mapstruct",
    "pagination": "no",
    "service": "serviceImpl"
}
```

OrgDetails.json

```yaml
{
    "fluentMethods": true,
    "relationships": [
        {
            "relationshipType": "one-to-one",
            "relationshipName": "orgTenant",
            "otherEntityName": "orgTenants",
            "otherEntityField": "id",
            "ownerSide": true,
            "otherEntityRelationshipName": "orgDetails"
        },
        {
            "relationshipType": "one-to-one",
            "relationshipName": "metadata",
            "otherEntityName": "metadata",
            "otherEntityField": "id",
            "ownerSide": true,
            "otherEntityRelationshipName": "orgDetails"
        },
        {
            "relationshipName": "orgHierarchy",
            "otherEntityName": "orgHierarchy",
            "relationshipType": "many-to-one",
            "otherEntityField": "id"
        }
    ],
    "fields": [
        {
            "fieldName": "organizationId",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": 256
        },
        {
            "fieldName": "organizationName",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": 512
        },
        {
            "fieldName": "organizationType",
            "fieldType": "OrgType",
            "fieldValues": "CONNECT,WEBMAIL,DIRECTXDR,NONE",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "smimeSupport",
            "fieldType": "SMIMESupport",
            "fieldValues": "SERVER,CLIENT,WEBMAIL,HIE_CONVERSION,RC,NONE",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "xdrSupport",
            "fieldType": "XDRSupport",
            "fieldValues": "SUPPORTED,HIE_CONVERSION,RC,NONE",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "domain",
            "fieldType": "String",
            "fieldValidateRules": [
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": 512
        },
        {
            "fieldName": "uri",
            "fieldType": "String",
            "fieldValidateRules": [
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": 512
        },
        {
            "fieldName": "sslCertificateSerialNumber",
            "fieldType": "String",
            "fieldValidateRules": [
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": 256
        },
        {
            "fieldName": "mdn",
            "fieldType": "Boolean"
        },
        {
            "fieldName": "createdDate",
            "fieldType": "ZonedDateTime"
        },
        {
            "fieldName": "updatedDate",
            "fieldType": "ZonedDateTime"
        }
    ],
    "changelogDate": "20170123225314",
    "javadoc": "Organization Details Entity\n\n@author kasunt",
    "entityTableName": "org_details",
    "dto": "mapstruct",
    "pagination": "pagination",
    "service": "serviceImpl"
}
```

OrgHierarchy.json

```yaml
{
    "fluentMethods": true,
    "relationships": [
        {
            "relationshipType": "one-to-one",
            "relationshipName": "parentOrganization",
            "otherEntityName": "orgDetails",
            "otherEntityField": "id",
            "ownerSide": true,
            "otherEntityRelationshipName": "orgHierarchy"
        },
        {
            "relationshipType": "one-to-many",
            "relationshipName": "subOrganization",
            "otherEntityName": "orgDetails",
            "otherEntityRelationshipName": "orgHierarchy"
        }
    ],
    "fields": [
        {
            "fieldName": "relationshipId",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": 256
        }
    ],
    "changelogDate": "20170123225316",
    "javadoc": "Organization Hierarchy Entity\n\n@author kasunt",
    "entityTableName": "org_hierarchy",
    "dto": "mapstruct",
    "pagination": "pagination",
    "service": "serviceImpl"
}
```

OrgTenants.json

```yaml
{
    "fluentMethods": true,
    "relationships": [],
    "fields": [
        {
            "fieldName": "organizationId",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": 256
        },
        {
            "fieldName": "organizationName",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": 512
        },
        {
            "fieldName": "aliasName",
            "fieldType": "String",
            "fieldValidateRules": [
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": 128
        }
    ],
    "changelogDate": "20170123225315",
    "javadoc": "Tenant Entity\n\n@author kasunt",
    "entityTableName": "org_tenants",
    "dto": "mapstruct",
    "pagination": "no",
    "service": "serviceImpl"
}
```

##### **Browsers and Operating System**

java version "1.8.0_112"
Java(TM) SE Runtime Environment (build 1.8.0_112-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.112-b16, mixed mode)

git version 2.11.0

node: v6.2.2

npm: 3.9.5

bower: 1.8.0

gulp:
[15:23:40] CLI version 3.9.1
[15:23:40] Local version 3.9.1

yeoman: 1.8.5

Docker version 1.13.0, build 49bf474

docker-compose version 1.10.0, build 4bd6f1a

**Comment by nixgadget** [comment] 2017-01-24 02:42
Is this due to this issue ? https://github.com/jhipster/generator-jhipster/issues/1569

**Comment by MathieuAA** [comment] 2017-01-24 07:32
I'll take a look at this issue later today.

Le 24 janvier 2017 03:37:38 GMT+01:00, Kasun Talwatta <notifications@github.com> a écrit :
>
>
>##### **Overview of the issue**
>It appears that if I include a column (`subOrganization`) for the
>OneToMany relationship specified as in the `jdl` below, in the
>corresponding  generated liquibase migration the column is missing.
>
>```
>entity OrgDetails {
>    organizationId String required
>    organizationName String required maxlength(512)
>    organizationType OrgType required
>}
>
>entity OrgHierarchy {
>    relationshipId String required
>}
>
>// One-to-One relationship definitions
>relationship OneToOne {
>    OrgHierarchy{parentOrganization} to OrgDetails
>}
>
>// One-to-Many relationship definitions
>relationship OneToMany {
>    OrgHierarchy{subOrganization} to OrgDetails
>}
>```
>
>
>
>##### **Motivation for or Use Case**
>Trying to establish a OneToMany relationship for one of the columns in
>OrgHierarchy,
>```
>OrgHierarchy {parentOrganization} (1) ----------------------> (1)
>OrgDetails
>OrgHierarchy {subOrganization}  (1) ----------------------> (*)
>OrgDetails
>```
>
>The generated liquibase doesnt contain the column for some reason.
>
>```
><?xml version="1.0" encoding="utf-8"?>
><databaseChangeLog
>    xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
>    xmlns:ext="http://www.liquibase.org/xml/ns/dbchangelog-ext"
>    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
>xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog
>http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.4.xsd
>http://www.liquibase.org/xml/ns/dbchangelog-ext
>http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-ext.xsd">
>
>    <property name="now" value="now()" dbms="mysql,h2"/>
>    <property name="now" value="current_timestamp" dbms="postgresql"/>
>    <property name="now" value="sysdate" dbms="oracle"/>
>    <property name="now" value="GETDATE()" dbms="mssql"/>
>
><property name="autoIncrement" value="true"
>dbms="mysql,h2,postgresql,oracle,mssql"/>
>
>    <property name="floatType" value="float4" dbms="postgresql, h2"/>
> <property name="floatType" value="float" dbms="mysql, oracle, mssql"/>
>
>    
>    <changeSet id="20170123225316-1" author="onboarding">
>        <createTable tableName="org_hierarchy">
>      <column name="id" type="bigint" autoIncrement="${autoIncrement}">
>                <constraints primaryKey="true" nullable="false"/>
>            </column>
>
>            <column name="relationship_id" type="varchar(256)">
>                <constraints nullable="false" />
>            </column>
>
>            <column name="parent_organization_id" type="bigint">
>                <constraints unique="true" nullable="true" />
>            </column>
>        </createTable>
>    </changeSet>
></databaseChangeLog>
>```
>
>##### **Reproduce the error**
>NA
>
>
>##### **Related issues**
>NA
>
>
>##### **Suggest a Fix**
>NA
>
>
>##### **JHipster Version(s)**
>
>```
>onboarding@0.0.0 /Volumes/STORAGE/Projects/Test/onboarding
>└── generator-jhipster@3.12.2
>
>```
>
>
>##### **JHipster configuration, a `.yo-rc.json` file generated in the
>root folder**
>
>```yaml
>{
>  "generator-jhipster": {
>    "jhipsterVersion": "3.12.2",
>    "baseName": "onboarding",
>    "packageName": "com.orchestral.dsm.onboarding",
>    "packageFolder": "com/orchestral/dsm/onboarding",
>    "serverPort": "8080",
>    "authenticationType": "jwt",
>    "hibernateCache": "ehcache",
>    "clusteredHttpSession": false,
>    "websocket": false,
>    "databaseType": "sql",
>    "devDatabaseType": "oracle",
>    "prodDatabaseType": "oracle",
>    "searchEngine": false,
>    "messageBroker": false,
>    "buildTool": "maven",
>    "enableSocialSignIn": false,
>    "jwtSecretKey": "f8254d93b9c60283bea2efe74eef1033922e5e01",
>    "useSass": true,
>    "applicationType": "monolith",
>    "testFrameworks": [
>      "cucumber"
>    ],
>    "jhiPrefix": "jhi",
>    "otherModules": [
>      {
>        "name": "generator-jhipster-entity-audit",
>        "version": "2.2.2"
>      }
>    ],
>    "enableTranslation": false
>  }
>}
>```
>
>
>##### **Entity configuration(s) `entityName.json` files generated in
>the `.jhipster` directory**
>
>Metadata.json
>
>```yaml
>{
>    "fluentMethods": true,
>    "relationships": [],
>    "fields": [
>        {
>            "fieldName": "medicaidProviderStatus",
>            "fieldType": "MedicaidProviderStatus",
>            "fieldValues": "ELIGIBLE,NON_ELIGIBLE"
>        },
>        {
>            "fieldName": "certifiedEHR",
>            "fieldType": "CertifiedEHR",
>            "fieldValues": "CERTIFIED,NON_CERTIFIED"
>        },
>        {
>            "fieldName": "medicaidParticipation",
>            "fieldType": "Boolean"
>        },
>        {
>            "fieldName": "medicaidStage",
>            "fieldType": "String"
>        },
>        {
>            "fieldName": "medicaidEnrollmentDate",
>            "fieldType": "ZonedDateTime"
>        }
>    ],
>    "changelogDate": "20170123225317",
>    "javadoc": "Metadata Entity\n\n@author kasunt",
>    "entityTableName": "metadata",
>    "dto": "mapstruct",
>    "pagination": "no",
>    "service": "serviceImpl"
>}
>```
>
>OrgDetails.json
>
>```yaml
>{
>    "fluentMethods": true,
>    "relationships": [
>        {
>            "relationshipType": "one-to-one",
>            "relationshipName": "orgTenant",
>            "otherEntityName": "orgTenants",
>            "otherEntityField": "id",
>            "ownerSide": true,
>            "otherEntityRelationshipName": "orgDetails"
>        },
>        {
>            "relationshipType": "one-to-one",
>            "relationshipName": "metadata",
>            "otherEntityName": "metadata",
>            "otherEntityField": "id",
>            "ownerSide": true,
>            "otherEntityRelationshipName": "orgDetails"
>        },
>        {
>            "relationshipName": "orgHierarchy",
>            "otherEntityName": "orgHierarchy",
>            "relationshipType": "many-to-one",
>            "otherEntityField": "id"
>        }
>    ],
>    "fields": [
>        {
>            "fieldName": "organizationId",
>            "fieldType": "String",
>            "fieldValidateRules": [
>                "required",
>                "maxlength"
>            ],
>            "fieldValidateRulesMaxlength": 256
>        },
>        {
>            "fieldName": "organizationName",
>            "fieldType": "String",
>            "fieldValidateRules": [
>                "required",
>                "maxlength"
>            ],
>            "fieldValidateRulesMaxlength": 512
>        },
>        {
>            "fieldName": "organizationType",
>            "fieldType": "OrgType",
>            "fieldValues": "CONNECT,WEBMAIL,DIRECTXDR,NONE",
>            "fieldValidateRules": [
>                "required"
>            ]
>        },
>        {
>            "fieldName": "smimeSupport",
>            "fieldType": "SMIMESupport",
>         "fieldValues": "SERVER,CLIENT,WEBMAIL,HIE_CONVERSION,RC,NONE",
>            "fieldValidateRules": [
>                "required"
>            ]
>        },
>        {
>            "fieldName": "xdrSupport",
>            "fieldType": "XDRSupport",
>            "fieldValues": "SUPPORTED,HIE_CONVERSION,RC,NONE",
>            "fieldValidateRules": [
>                "required"
>            ]
>        },
>        {
>            "fieldName": "domain",
>            "fieldType": "String",
>            "fieldValidateRules": [
>                "maxlength"
>            ],
>            "fieldValidateRulesMaxlength": 512
>        },
>        {
>            "fieldName": "uri",
>            "fieldType": "String",
>            "fieldValidateRules": [
>                "maxlength"
>            ],
>            "fieldValidateRulesMaxlength": 512
>        },
>        {
>            "fieldName": "sslCertificateSerialNumber",
>            "fieldType": "String",
>            "fieldValidateRules": [
>                "maxlength"
>            ],
>            "fieldValidateRulesMaxlength": 256
>        },
>        {
>            "fieldName": "mdn",
>            "fieldType": "Boolean"
>        },
>        {
>            "fieldName": "createdDate",
>            "fieldType": "ZonedDateTime"
>        },
>        {
>            "fieldName": "updatedDate",
>            "fieldType": "ZonedDateTime"
>        }
>    ],
>    "changelogDate": "20170123225314",
>    "javadoc": "Organization Details Entity\n\n@author kasunt",
>    "entityTableName": "org_details",
>    "dto": "mapstruct",
>    "pagination": "pagination",
>    "service": "serviceImpl"
>}
>```
>
>OrgHierarchy.json
>
>```yaml
>{
>    "fluentMethods": true,
>    "relationships": [
>        {
>            "relationshipType": "one-to-one",
>            "relationshipName": "parentOrganization",
>            "otherEntityName": "orgDetails",
>            "otherEntityField": "id",
>            "ownerSide": true,
>            "otherEntityRelationshipName": "orgHierarchy"
>        },
>        {
>            "relationshipType": "one-to-many",
>            "relationshipName": "subOrganization",
>            "otherEntityName": "orgDetails",
>            "otherEntityRelationshipName": "orgHierarchy"
>        }
>    ],
>    "fields": [
>        {
>            "fieldName": "relationshipId",
>            "fieldType": "String",
>            "fieldValidateRules": [
>                "required",
>                "maxlength"
>            ],
>   
-- 
Mathieu ABOU-AICHI

**Comment by MathieuAA** [comment] 2017-01-24 21:07
When you have a unidirectional OtM relationship, the entity creator (the object that creates the JSON files) converts it into a bidirectional (it is the best solution for this use case). So no, the issue you mentioned isn't related. I've checked your JDL and your JSON files (by manually creating the entities), there's nothing wrong with them.
From that, I've also checked the liquibase files. You're right. You have this issue because you have two relationships from the same two entities. The second relationship is completely ignored in the liquibase file. However, the Java classes seem normal.

**Comment by nixgadget** [comment] 2017-01-24 21:23
@MathieuAA thanks. That was my suspicion too. I saw no problems with the JPA code either.

So does that mean we'l need to raise this as a liquibase bug or a bug in the JDL generation itself ?

**Comment by MathieuAA** [comment] 2017-01-24 21:27
The JDL generation is perfect as far as I'm concerned (first thing I checked, obviously :)). I've done the exact same thing as the JDL importer does, but only manually (with the Q&As) and I got the same problem as you.
@jdubois I think I've already seen this kind of issue in the past, but I don't remember how it went last time (and I can't find something similar in the issues). Do you have an idea?

**Comment by deepu105** [comment] 2017-01-24 21:41
Might be we missed a condition in the liquibase template. I havent had a
look but i'll start from there.


Thanks & Regards,
Deepu

**Comment by deepu105** [comment] 2017-01-24 21:42
but I dont have time as I'm going through ng2 stuff


Thanks & Regards,
Deepu

**Comment by MathieuAA** [comment] 2017-01-24 21:43
@deepu105 I'll look into it. Thanks for the pointer

**Comment by jdubois** [comment] 2017-01-24 21:44
I'll also have a look, @deepu105 your work on NG2 is more important

**Comment by jdubois** [comment] 2017-01-24 22:35
I'm sorry but I can't reproduce.

I modified a few things, so here's what I tested:

- I modified your `.yo-rc.json` to use "H2 Disk", so I didn't need to use Oracle
- I removed `OrgType` in your JDL as it isn't described

-> I don't think those should make any difference.

Then I generated the app with the current master branch:

- I do have 2 constraints generated
- BTW my constraint files don't look like yours, so I don't really understand the Liquibase file you give

-> I think we don't have your full configuration here, or maybe you then modified something, so it's hard to tell what the real issue is

So this all work at the database level, but this fails with Hibernate when you use the app in this way:

- Create an "org detail"
- Create an "org hierarchy" and give it the previous "org detail" as parent
- Go back to the "org detail" and edit it, and link it to the "org hierarchy"

-> you'll get a stackoverflow, which I think is normal as Hibernate is going to go into an infinite loop getting the eager relationship.

Then I don't understand why you do those 2 relationships, it looks like you just want to do a hierarchy of organizations, and in that case a one-to-many relationship of the entity on itself should be enough.

I'm closing this as I can't reproduce, and as the constraint issue isn't clear to me (as your file do looks strange).

**Closed by jdubois** 2017-01-24 22:35 UTC

**Comment by nixgadget** [comment] 2017-01-24 22:46
@jdubois Thanks for your findings. Are you able to share your entity json files or even the JDL file. So I can verify what Im trying to do is as you suggested.

At a high level all I'm trying to do is,

```
OrgHierarchy
==========
parentOrganization --------- OrgDetails (1)
subOrganization      --------- OrgDetails (*)
```

**Comment by jdubois** [comment] 2017-01-24 22:48
It should be the same JDL as you, here it is:

```yaml
entity OrgDetails {
    organizationId String required
    organizationName String required maxlength(512)
}

entity OrgHierarchy {
    relationshipId String required
}

// One-to-One relationship definitions
relationship OneToOne {
    OrgHierarchy{parentOrganization} to OrgDetails
}

// One-to-Many relationship definitions
relationship OneToMany {
    OrgHierarchy{subOrganization} to OrgDetails
}
```

But once again, for a hierarchy, I don't think you should do this kind of mapping.
