### ISSUE TITLE
Fetch type EAGER causes a NPE on OneToMany relationship during JSON deserialization

### ISSUE THREAD

**Issue by blacksmithbrew** [jhipster/generator-jhipster#10981] opened 2019-12-18 09:13 UTC
##### **Overview of the issue**

Setting fetch type eager on a One2Many relationship causes a HTTP 400 and internally a NullPointerException during JSON deserialization.

##### **Motivation for or Use Case**

Use of fetch type EAGER should not lead to an error.

##### **Reproduce the error**

- Building the application from scratch with the JDL below with **--skip-fake-data** option
- set Fetch type EAGER on OneToMany relationship in class "**Parent.childTwos**"
- start application and open in browser
- go to "Parent" entity and create an entry P1
- go to "Child" entry and create an entry C1 with reference to P1
- Result is a **HTTP 400**:
```
JSON parse error: (was java.lang.NullPointerException);
nested exception is com.fasterxml.jackson.databind.JsonMappingException: (was java.lang.NullPointerException) 
(through reference chain: jh.eager.test.domain.Child["parent"]->jh.eager.test.domain.Parent["childTwos"])
```

##### **Related issues**

NONE

##### **Suggest a Fix**

---

##### **JHipster Version(s)**

6.5.1, 6.6.0

##### **JHipster configuration**

```
application {
  config {
    databaseType sql
    devDatabaseType h2Memory
    enableHibernateCache true
    enableSwaggerCodegen false
    enableTranslation false
    jhiPrefix jhi
    languages [en]
    messageBroker false
    nativeLanguage en
    packageName jh.eager.test
    prodDatabaseType mysql
    searchEngine false
    serviceDiscoveryType false
    skipClient false
    skipServer false
    testFrameworks []
    websocket false
    applicationType monolith
    baseName jh_eager
    serverPort 8080
    authenticationType session
    cacheProvider no
    buildTool maven
    useSass true
    clientPackageManager npm
    clientFramework angularX
    clientTheme none
    clientThemeVariant
    entitySuffix
    dtoSuffix DTO
    skipUserManagement false
  }
  entities Parent, Child, ChildTwo
}
entity Parent {
  name String required
}
entity Child {
  name String required
}
entity ChildTwo {
  name String required
}
relationship OneToMany {
  Parent{child} to Child{parent}
  Parent{childTwo} to ChildTwo{parent}
}

paginate * with pagination
service * with serviceClass
filter *

```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

see above

##### **Browsers and Operating System**

- Ubuntu 18.04.3 LTS
- Firefox 71.0

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment] 2019-12-21 11:58
looks like this is duplicate of https://github.com/jhipster/generator-jhipster/issues/10984?
Can you confirm this one is fixed?

**Comment by blacksmithbrew** [comment] 2019-12-23 08:06
I **can't** confirm. Just tested it with v6.6.0.
Described error still occurs.
Moreover, generated relationship names are correct in ManyToOne.

**Comment by pmverma** [comment] 2020-02-20 16:47
@blacksmithbrew I tried with your provided info. But error did not occur.
Can you please confirm again so that we either close or further this issue?

**Comment by Shaolans** [comment] 2020-03-25 10:56
I tried on my side, unfortunately I can reproduce the error on jhipster 6.6.0, 6.8.0 and on the master version.
Based on my observation/research (I might be wrong thought), Jackson does not seem to be able to deserialize an empty array and since when we use Fetch type EAGER on a OneToMany relationship that does not hold any entity yet. It returns an empty HashSet, it might be the problem here.
Thus, when we create, in this case, a Child it sends ```{"name":"C1","parent":{"id":1,"name":"P1","children":null,"childTwos":[]}}``` causing the deserialization issue.
Adding ```@JsonInclude(JsonInclude.Include.NON_EMPTY)``` on the EAGER relationship should do the trick.
I don't know if this is the best solution or should we even fix in the generator ?

**Comment by pascalgrimaud** [comment] 2020-03-25 12:22
Thanks for the analyze @Shaolans, I think you're right.
As by default, we don't use `eager`, for me, it's not a JHipster bug. Anyway, I think it can go to a specific part in our documentation, maybe at https://www.jhipster.tech/managing-relationships/

Would you like to do a PR for that plz @Shaolans ?

**Comment by Shaolans** [comment] 2020-03-25 12:24
I will do it this afternoon !

**Comment by Shaolans** [comment] 2020-03-25 16:38
@pascalgrimaud I opened the PR

**Comment by pascalgrimaud** [comment] 2020-03-26 06:15
fixed by https://github.com/jhipster/jhipster.github.io/pull/922

**Closed by pascalgrimaud** 2020-03-26 06:15 UTC
Labels: area: documentation:books:, theme: relationships
