### ISSUE TITLE
jhipster docker composer ERROR! YAMLException

### ISSUE THREAD

**Issue by direstrepo24** [jhipster/generator-jhipster#11484] opened 2020-03-16 19:00 UTC
##### **Overview of the issue**

when I try to generate the docker composer configuration, after the questions the ERROR comes out! YAMLException
##### **Reproduce the error**
jhipster docker-compose:
Checking Docker images in applications directories...
ERROR! YAMLException: duplicated mapping key at line 21, column -172:
        environment:
        ^

##### **JHipster Version(s)**
6.7.1

##### **Browsers and Operating System**

-   [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment] 2020-03-16 19:11
you need to provide enough information about your project, just use `jhipster info` inside your project.

otherwise, we don't have information to reproduce your issue

**Comment by direstrepo24** [comment] 2020-03-16 19:53
eohelstore@0.0.1-SNAPSHOT /Users/themakers/eohel/eohelstore
├── generator-jhipster@6.7.1 
└─┬ generator-jhipster-entity-audit@3.2.0
  └── generator-jhipster@6.7.1  deduped

```


##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**


<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "enableHibernateCache": true,
    "enableSwaggerCodegen": false,
    "enableTranslation": true,
    "jhiPrefix": "jhi",
    "languages": ["es", "en"],
    "messageBroker": false,
    "nativeLanguage": "es",
    "packageName": "com.themakers.eohelstore",
    "packageFolder": "com/themakers/eohelstore",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "serviceDiscoveryType": "eureka",
    "skipClient": false,
    "skipServer": false,
    "testFrameworks": ["protractor"],
    "websocket": "spring-websocket",
    "baseName": "eohelstore",
    "applicationType": "gateway",
    "authenticationType": "jwt",
    "cacheProvider": "hazelcast",
    "buildTool": "maven",
    "serverPort": "8081",
    "clientFramework": "angularX",
    "useSass": true,
    "jhipsterVersion": "6.7.1",
    "creationTimestamp": 1583859840796,
    "skipUserManagement": false,
    "clientPackageManager": "npm",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "embeddableLaunchScript": false,
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "blueprints": [],
    "otherModules": []
  },
  "entities": [
    "Usuario",
    "Empresa",
    "Sucursal",
    "Suscripcion",
    "TipoLista",
    "ElementoLista",
    "FacturaEmpresa",
    "Pago",
    "Factura",
    "FacturaDetalle",
    "AbonoFactura",
    "Tercero",
    "Producto",
    "Stock",
    "ProductoAtributo",
    "Categoria",
    "Movimiento",
    "MovimientoDetalle",
    "Notification"
  ],
  "generator-jhipster-entity-audit": {
    "auditFramework": "custom"
  }
}

</pre>
</details>


##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
/**
 * Usuario sold by the gateway inbuk
 */
entity Usuario {
  segundoNombre String,
  segundoApellido String,
  numDocumento String required maxlength(15),
  celular String required,
  direccion String
}
entity Empresa {
  nit String required,
  nombre String required,
  logo String,
  numDocumento String,
  representante String,
  usuario Long required
}
entity Sucursal {
  nombre String required,
  direccion String required
}
entity Suscripcion {
  fechaCreacion Instant required,
  fechaInicio Instant required,
  fechaFin Instant required
}
entity TipoLista {
  nombre String required,
  descripcion String maxlength(500)
}
entity ElementoLista {
  nombre String required maxlength(200),
  codigo String required maxlength(5),
  propiedades AnyBlob
}
entity FacturaEmpresa {
  precio BigDecimal required,
  fechaEmision Instant required,
  fechaLimite Instant required
}
entity Pago {
  fechaPago Instant required,
  correo String required,
  docIdentificacion String required,
  celular String required
}
/**
 * Factura sold by the Online store
 */
entity Factura {
  fecha Instant required,
  codigo String,
  sucursalId Long,
  fechaPago Instant required,
  metodoPagoId Long,
  empresaId Long required,
  userId Long,
  tipoFacturaId Long,
  valor BigDecimal required
}
entity FacturaDetalle {
  productoId Long required,
  codigoProducto String,
  nombreProducto String,
  precioUnitario BigDecimal required,
  cantidad Long required min(0)
}
entity AbonoFactura {
  userId Long,
  fecha Instant required,
  codigo String required,
  valor BigDecimal required
}
entity Tercero {
  nombre String required,
  apellido String required,
  nit String required,
  celular String,
  email String required pattern(/^[^@\s]+@[^@\s]+\.[^@\s]+$/),
  direccion1 String required,
  direccion2 String,
  empresaId Long,
  cuidadId Long,
  paisId Long,
  tipoTerceroId Long
}
/**
 * Product sold by the Online store
 */
entity Producto {
  nombre String required,
  descripcion String,
  precioCompra BigDecimal required min(0),
  precioVenta BigDecimal required min(0),
  codigobar String,
  imagen String,
  empresaId Long required,
  estadoId Long required,
  estadoProductoId Long required
}
entity Stock {
  cantidad Long required min(0),
  sucursalId Long
}
entity ProductoAtributo {
  atributo String,
  valor String
}
entity Categoria {
  nombre String required,
  descripcion String,
  image ImageBlob,
  empresaId Long
}
entity Movimiento {
  motivo String,
  tipoMovimientoId Long required,
  fecha Instant required,
  sucursalId Long required,
  sucursalrecibeId Long,
  empresaId Long required,
  estadoMovimientoId Long required
}
entity MovimientoDetalle {
  codigoProducto String,
  nombreProducto String,
  cantidad Long required min(0)
}
entity Notification {
  date Instant required,
  details String,
  sentDate Instant required,
  format NotificationType required,
  userId Long required,
  productId Long required,
  empresaId Long required
}
enum NotificationType {
  EMAIL,
  SMS,
  PARCEL
}

relationship OneToOne {
  Usuario{user required} to User,
  Suscripcion{empresa} to Empresa,
  Pago{factura} to FacturaEmpresa
}
relationship OneToMany {
  Empresa{sucursal} to Sucursal{empresa(nombre)},
  Factura{facturaDetalle} to FacturaDetalle{factura},
  Factura{abonoFactura} to AbonoFactura{factura},
  Categoria{producto} to Producto{productCategoria},
  Producto{productoAtributo} to ProductoAtributo{producto(nombre)},
  Movimiento{movimientoDetalle} to MovimientoDetalle{movimiento}
}
relationship ManyToOne {
  Usuario{cuidad(nombre) required} to ElementoLista,
  Usuario{categoria(nombre) required} to ElementoLista,
  Empresa{cuidad(nombre) required} to ElementoLista,
  Empresa{estado(nombre) required} to ElementoLista,
  Empresa{tipoDocumento(nombre) required} to ElementoLista,
  Suscripcion{estado(nombre) required} to ElementoLista,
  TipoLista{padre(nombre)} to TipoLista,
  ElementoLista{tipoLista(nombre) required} to TipoLista,
  ElementoLista{padre(nombre)} to ElementoLista,
  FacturaEmpresa{metodoPago(nombre) required} to ElementoLista,
  FacturaEmpresa{estadoFactura(nombre) required} to ElementoLista,
  FacturaEmpresa{empresa(nombre)} to Empresa,
  Pago{estado(nombre) required} to ElementoLista,
  Pago{tipoPersona(nombre) required} to ElementoLista,
  Factura{tercero(nit)} to Tercero,
  Stock{producto(nombre)} to Producto,
  MovimientoDetalle{producto(nombre)} to Producto
}

dto Usuario, Empresa, Sucursal, Suscripcion, TipoLista, ElementoLista, FacturaEmpresa, Pago, Factura, FacturaDetalle, AbonoFactura, Tercero, Producto, Stock, ProductoAtributo, Categoria, Movimiento, MovimientoDetalle, Notification with mapstruct
paginate Usuario, Empresa, Sucursal, Suscripcion, TipoLista, ElementoLista, FacturaEmpresa, Pago, Factura, FacturaDetalle, AbonoFactura, Tercero, Producto, Stock, ProductoAtributo, Categoria, Movimiento, MovimientoDetalle, Notification with pagination
service Usuario, Empresa, Sucursal, Suscripcion, TipoLista, ElementoLista, FacturaEmpresa, Pago, Factura, FacturaDetalle, AbonoFactura, Tercero, Producto, Stock, ProductoAtributo, Categoria, Movimiento, MovimientoDetalle, Notification with serviceClass
filter Usuario, Empresa, Sucursal, Suscripcion, TipoLista, ElementoLista, FacturaEmpresa, Pago, Factura, FacturaDetalle, AbonoFactura, Tercero, Producto, Stock, ProductoAtributo, Categoria, Movimiento, MovimientoDetalle, Notification
microservice Factura, FacturaDetalle, AbonoFactura, Tercero with facturamicroservicio
microservice Producto, Stock, ProductoAtributo, Categoria, Movimiento, MovimientoDetalle with inventariomicroservicio
microservice Notification with notification

</pre>
</details>


##### **Environment and Tools**

openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.6+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.6+10, mixed mode)

git version 2.21.1 (Apple Git-122.3)

node: v12.14.1

npm: 6.13.4

yeoman: 3.1.1

yarn: 1.21.1

Docker version 19.03.5, build 633a0ea

docker-compose version 1.25.4, build 8d51620a

**Comment by gmarziou** [comment] 2020-03-16 20:28
You pasted only the configuration of your gateway not the other apps.

As [stated in doc](https://www.jhipster.tech/docker-compose/) `jhipster docker-compose` must be run in root directory of your project with all your app as sub directories. Without them, we cannot reproduce.

Please also paste the generated file that causes the YAML exception. What have you done to fix it?

**Comment by direstrepo24** [comment] 2020-03-16 20:34
yes, I did it in the root directory of the microservices that I have. When executing after error: jhipster info: get this

cat: no such file or directory: .yo-rc.json

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**


<details>
<summary>.yo-rc.json file</summary>
<pre>

</pre>
</details>


##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>


##### **Environment and Tools**

openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.6+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.6+10, mixed mode)

git version 2.21.1 (Apple Git-122.3)

node: v12.14.1

npm: 6.13.4

yeoman: 3.1.1

yarn: 1.21.1

Docker version 19.03.5, build 633a0ea

**Comment by gmarziou** [comment] 2020-03-16 23:29
I used this example which looks close to your  project:
https://github.com/jhipster/jdl-samples/blob/master/microservice-ecommerce-store.jdl

Then I tried to reproduce issue with JHipster 6.7.1 and 6.8.0 but both succeeded as shown below.

So this issue is probably specific to your project:

- either you modified some of the` src/main/docker/app.yml` files which are loaded by the docker-compose sub generator (see https://github.com/jhipster/generator-jhipster/blob/master/generators/docker-compose/index.js)
- or there's something weird in your project but we will not be able to reproduce it unless you  provide full project or full JDL like the example I used.

If you can't provide us with these then only you will be able to propose a fix.
You could run the sub  generator under debugger to get a clue about what's going on.

~~~
mkdir docker-compose
cd .\docker-compose\
jhipster docker-compose
INFO! Using JHipster version installed globally
INFO! Executing jhipster:docker-compose
INFO! Options: from-cli: true
√ Docker is installed
? Which *type* of application would you like to deploy? Microservice application
? Which *type* of gateway would you like to use? Traefik gateway (only works with Consul)
? Enter the root directory where your gateway(s) and microservices are located ../
3 applications found at D:\projets\jhipster-projects\issues\docker-composer\

? Which applications do you want to include in your configuration? (Press <space> to select, <a> to toggle all, <i> to invert selection)
>( ) invoice
 ( ) notification
 ( ) store
? Do you want to setup monitoring for your applications ? No
JHipster registry detected as the service discovery and configuration provider used by your apps
? Enter the admin password used to secure the JHipster Registry admin
🐳  Welcome to the JHipster Docker Compose Sub-Generator 🐳
Files will be generated in folder: D:\projets\jhipster-projects\issues\docker-composer\docker-compose

Checking Docker images in applications directories...
ls: no such file or directory: D:/projets/jhipster-projects/issues/docker-composer/invoice/build/jib-cache
ls: no such file or directory: D:/projets/jhipster-projects/issues/docker-composer/notification/build/jib-cache
ls: no such file or directory: D:/projets/jhipster-projects/issues/docker-composer/store/build/jib-cache
   create traefik\traefik.toml
   create docker-compose.yml
   create README-DOCKER-COMPOSE.md
   create jhipster-registry.yml
   create central-server-config\application.yml
   create traefik.yml

WARNING! Docker Compose configuration generated, but no Jib cache found
If you forgot to generate the Docker image for this application, please run:
To generate the missing Docker image(s), please run:
  ./gradlew bootJar -Pprod jibDockerBuild in D:\projets\jhipster-projects\issues\docker-composer\invoice
  ./gradlew bootJar -Pprod jibDockerBuild in D:\projets\jhipster-projects\issues\docker-composer\notification
  ./gradlew bootJar -Pprod jibDockerBuild in D:\projets\jhipster-projects\issues\docker-composer\store

You can launch all your infrastructure by running : docker-compose up -d
INFO! Congratulations, JHipster execution is complete!

~~~

**Comment by pascalgrimaud** [comment] 2020-03-18 07:55
@direstrepo24 : we need your `jhipster info` inside of each your microservices:
- eohelstore
- facturamicroservicio
- inventariomicroservicio

**Comment by direstrepo24** [comment] 2020-03-18 15:46
The problem started when I wanted to change the option of "Do you want to setup monitoring for your applications? (Use arrow keys)
❯ No ", I had already executed it well but then decided not to use monitoring. Now the problem occurs with any project that I want to carry out.
I share my app.yml docker of gateway:
version: '2'
services:
  eohelstore-app:
    image: eohelstore
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
      - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
      #- SPRING_DATASOURCE_URL=jdbc:postgresql://eohelstore-postgresql:5432/eohelstore
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8081:8081
  #eohelstore-postgresql:
  # extends:
  #  file: postgresql.yml
  # service: eohelstore-postgresql
  jhipster-registry:
    extends:
      file: jhipster-registry.yml
      service: jhipster-registry
    environment:
      - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_TYPE=native
      - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_SEARCH_LOCATIONS=file:./central-config/docker-config/

**Comment by pascalgrimaud** [comment] 2020-03-18 16:11
@direstrepo24 : still need your jhipster info inside of each your microservices:
- eohelstore
- facturamicroservicio
- inventariomicroservicio

Without these information, we can't reproduce the issue, and we can't help.

**Comment by direstrepo24** [comment] 2020-03-18 16:21
##### **JHipster Version(s)**

```
eohelstore@0.0.1-SNAPSHOT /Users/themakers/eohel/eohelstore
├── generator-jhipster@6.7.1 
└─┬ generator-jhipster-entity-audit@3.2.0
  └── generator-jhipster@6.7.1  deduped

```


##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**


<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "enableHibernateCache": true,
    "enableSwaggerCodegen": false,
    "enableTranslation": true,
    "jhiPrefix": "jhi",
    "languages": ["es", "en"],
    "messageBroker": false,
    "nativeLanguage": "es",
    "packageName": "com.themakers.eohelstore",
    "packageFolder": "com/themakers/eohelstore",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "serviceDiscoveryType": "eureka",
    "skipClient": false,
    "skipServer": false,
    "testFrameworks": ["protractor"],
    "websocket": "spring-websocket",
    "baseName": "eohelstore",
    "applicationType": "gateway",
    "authenticationType": "jwt",
    "cacheProvider": "hazelcast",
    "buildTool": "maven",
    "serverPort": "8081",
    "clientFramework": "angularX",
    "useSass": true,
    "jhipsterVersion": "6.7.1",
    "creationTimestamp": 1583859840796,
    "skipUserManagement": false,
    "clientPackageManager": "npm",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "embeddableLaunchScript": false,
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "blueprints": [],
    "otherModules": []
  },
  "entities": [
    "Usuario",
    "Empresa",
    "Sucursal",
    "Suscripcion",
    "TipoLista",
    "ElementoLista",
    "FacturaEmpresa",
    "Pago",
    "Factura",
    "FacturaDetalle",
    "AbonoFactura",
    "Tercero",
    "Producto",
    "Stock",
    "ProductoAtributo",
    "Categoria",
    "Movimiento",
    "MovimientoDetalle",
    "Notification"
  ],
  "generator-jhipster-entity-audit": {
    "auditFramework": "custom"
  }
}

</pre>
</details>


##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
/**
 * Usuario sold by the gateway inbuk
 */
entity Usuario {
  segundoNombre String,
  segundoApellido String,
  numDocumento String required maxlength(15),
  celular String required,
  direccion String
}
entity Empresa {
  nit String required,
  nombre String required,
  logo String,
  numDocumento String,
  representante String,
  usuario Long required
}
entity Sucursal {
  nombre String required,
  direccion String required
}
entity Suscripcion {
  fechaCreacion Instant required,
  fechaInicio Instant required,
  fechaFin Instant required
}
entity TipoLista {
  nombre String required,
  descripcion String maxlength(500)
}
entity ElementoLista {
  nombre String required maxlength(200),
  codigo String required maxlength(5),
  propiedades AnyBlob
}
entity FacturaEmpresa {
  precio BigDecimal required,
  fechaEmision Instant required,
  fechaLimite Instant required
}
entity Pago {
  fechaPago Instant required,
  correo String required,
  docIdentificacion String required,
  celular String required
}
/**
 * Factura sold by the Online store
 */
entity Factura {
  fecha Instant required,
  codigo String,
  sucursalId Long,
  fechaPago Instant required,
  metodoPagoId Long,
  empresaId Long required,
  userId Long,
  tipoFacturaId Long,
  valor BigDecimal required
}
entity FacturaDetalle {
  productoId Long required,
  codigoProducto String,
  nombreProducto String,
  precioUnitario BigDecimal required,
  cantidad Long required min(0)
}
entity AbonoFactura {
  userId Long,
  fecha Instant required,
  codigo String required,
  valor BigDecimal required
}
entity Tercero {
  nombre String required,
  apellido String required,
  nit String required,
  celular String,
  email String required pattern(/^[^@\s]+@[^@\s]+\.[^@\s]+$/),
  direccion1 String required,
  direccion2 String,
  empresaId Long,
  cuidadId Long,
  paisId Long,
  tipoTerceroId Long
}
/**
 * Product sold by the Online store
 */
entity Producto {
  nombre String required,
  descripcion String,
  precioCompra BigDecimal required min(0),
  precioVenta BigDecimal required min(0),
  codigobar String,
  imagen String,
  empresaId Long required,
  estadoId Long required,
  estadoProductoId Long required
}
entity Stock {
  cantidad Long required min(0),
  sucursalId Long
}
entity ProductoAtributo {
  atributo String,
  valor String
}
entity Categoria {
  nombre String required,
  descripcion String,
  image ImageBlob,
  empresaId Long
}
entity Movimiento {
  motivo String,
  tipoMovimientoId Long required,
  fecha Instant required,
  sucursalId Long required,
  sucursalrecibeId Long,
  empresaId Long required,
  estadoMovimientoId Long required
}
entity MovimientoDetalle {
  codigoProducto String,
  nombreProducto String,
  cantidad Long required min(0)
}
entity Notification {
  date Instant required,
  details String,
  sentDate Instant required,
  format NotificationType required,
  userId Long required,
  productId Long required,
  empresaId Long required
}
enum NotificationType {
  EMAIL,
  SMS,
  PARCEL
}

relationship OneToOne {
  Usuario{user required} to User,
  Suscripcion{empresa} to Empresa,
  Pago{factura} to FacturaEmpresa
}
relationship OneToMany {
  Empresa{sucursal} to Sucursal{empresa(nombre)},
  Factura{facturaDetalle} to FacturaDetalle{factura},
  Factura{abonoFactura} to AbonoFactura{factura},
  Categoria{producto} to Producto{productCategoria(nombre)},
  Producto{productoAtributo} to ProductoAtributo{producto(nombre)},
  Movimiento{movimientoDetalle} to MovimientoDetalle{movimiento}
}
relationship ManyToOne {
  Usuario{cuidad(nombre) required} to ElementoLista,
  Usuario{categoria(nombre) required} to ElementoLista,
  Empresa{cuidad(nombre) required} to ElementoLista,
  Empresa{estado(nombre) required} to ElementoLista,
  Empresa{tipoDocumento(nombre) required} to ElementoLista,
  Suscripcion{estado(nombre) required} to ElementoLista,
  TipoLista{padre(nombre)} to TipoLista,
  ElementoLista{tipoLista(nombre) required} to TipoLista,
  ElementoLista{padre(nombre)} to ElementoLista,
  FacturaEmpresa{metodoPago(nombre) required} to ElementoLista,
  FacturaEmpresa{estadoFactura(nombre) required} to ElementoLista,
  FacturaEmpresa{empresa(nombre)} to Empresa,
  Pago{estado(nombre) required} to ElementoLista,
  Pago{tipoPersona(nombre) required} to ElementoLista,
  Factura{tercero(nit)} to Tercero,
  Stock{producto(nombre)} to Producto,
  MovimientoDetalle{producto(nombre)} to Producto
}

dto Usuario, Empresa, Sucursal, Suscripcion, TipoLista, ElementoLista, FacturaEmpresa, Pago, Factura, FacturaDetalle, AbonoFactura, Tercero, Producto, Stock, ProductoAtributo, Categoria, Movimiento, MovimientoDetalle, Notification with mapstruct
paginate Usuario, Empresa, Sucursal, Suscripcion, TipoLista, ElementoLista, FacturaEmpresa, Pago, Factura, FacturaDetalle, AbonoFactura, Tercero, Producto, Stock, ProductoAtributo, Categoria, Movimiento, MovimientoDetalle, Notification with pagination
service Usuario, Empresa, Sucursal, Suscripcion, TipoLista, ElementoLista, FacturaEmpresa, Pago, Factura, FacturaDetalle, AbonoFactura, Tercero, Producto, Stock, ProductoAtributo, Categoria, Movimiento, MovimientoDetalle, Notification with serviceClass
filter Usuario, Empresa, Sucursal, Suscripcion, TipoLista, ElementoLista, FacturaEmpresa, Pago, Factura, FacturaDetalle, AbonoFactura, Tercero, Producto, Stock, ProductoAtributo, Categoria, Movimiento, MovimientoDetalle, Notification
microservice Factura, FacturaDetalle, AbonoFactura, Tercero with facturamicroservicio
microservice Producto, Stock, ProductoAtributo, Categoria, Movimiento, MovimientoDetalle with inventariomicroservicio
microservice Notification with notification

</pre>
</details>


##### **Environment and Tools**

openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.6+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.6+10, mixed mode)

git version 2.21.1 (Apple Git-122.3)

node: v12.14.1

npm: 6.13.4

yeoman: 3.1.1

yarn: 1.21.1

Docker version 19.03.5, build 633a0ea

docker-compose version 1.25.4, build 8d51620a

**Comment by direstrepo24** [comment] 2020-03-18 16:22
facturamicroservicio:
##### **JHipster Version(s)**

```
facturamicroservicio@0.0.0 /Users/themakers/eohel/facturamicroservicio
└── generator-jhipster@6.7.1 

```


##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**


<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "enableHibernateCache": true,
    "enableSwaggerCodegen": false,
    "enableTranslation": true,
    "jhiPrefix": "jhi",
    "languages": ["es", "en"],
    "messageBroker": false,
    "nativeLanguage": "en",
    "packageName": "com.themakers.facturacion",
    "packageFolder": "com/themakers/facturacion",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "serviceDiscoveryType": "eureka",
    "skipClient": true,
    "testFrameworks": [],
    "websocket": false,
    "baseName": "facturamicroservicio",
    "applicationType": "microservice",
    "authenticationType": "jwt",
    "buildTool": "maven",
    "serverPort": "8082",
    "jhipsterVersion": "6.7.1",
    "creationTimestamp": 1583859840796,
    "skipUserManagement": true,
    "clientPackageManager": "npm",
    "cacheProvider": "hazelcast",
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "embeddableLaunchScript": false,
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "blueprints": [],
    "otherModules": []
  },
  "entities": ["Factura", "FacturaDetalle", "AbonoFactura", "Tercero"]
}

</pre>
</details>


##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
/**
 * Factura sold by the Online store
 */
entity Factura {
  fecha Instant required,
  codigo String,
  sucursalId Long,
  fechaPago Instant required,
  metodoPagoId Long,
  empresaId Long required,
  userId Long,
  tipoFacturaId Long,
  valor BigDecimal required
}
entity FacturaDetalle {
  productoId Long required,
  codigoProducto String,
  nombreProducto String,
  precioUnitario BigDecimal required,
  cantidad Long required min(0)
}
entity AbonoFactura {
  userId Long,
  fecha Instant required,
  codigo String required,
  valor BigDecimal required
}
entity Tercero {
  nombre String required,
  apellido String required,
  nit String required,
  celular String,
  email String required pattern(/^[^@\s]+@[^@\s]+\.[^@\s]+$/),
  direccion1 String required,
  direccion2 String,
  empresaId Long,
  cuidadId Long,
  paisId Long,
  tipoTerceroId Long
}
relationship OneToMany {
  Factura{facturaDetalle} to FacturaDetalle{factura},
  Factura{abonoFactura} to AbonoFactura{factura}
}
relationship ManyToOne {
  Factura{tercero(nit)} to Tercero
}

dto Factura, FacturaDetalle, AbonoFactura, Tercero with mapstruct
paginate Factura, FacturaDetalle, AbonoFactura, Tercero with pagination
service Factura, FacturaDetalle, AbonoFactura, Tercero with serviceClass
microservice Factura, FacturaDetalle, AbonoFactura, Tercero with facturamicroservicio
filter Factura, FacturaDetalle, AbonoFactura, Tercero

</pre>
</details>


##### **Environment and Tools**

openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.6+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.6+10, mixed mode)

git version 2.21.1 (Apple Git-122.3)

node: v12.14.1

npm: 6.13.4

yeoman: 3.1.1

yarn: 1.21.1

Docker version 19.03.5, build 633a0ea

docker-compose version 1.25.4, build 8d51620a

**Comment by direstrepo24** [comment] 2020-03-18 16:24
inventariomicroservicio:
##### **JHipster Version(s)**

```
inventariomicroservicio@0.0.0 /Users/themakers/eohel/inventariomicroservicio
└── generator-jhipster@6.7.1 

```


##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**


<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "enableHibernateCache": true,
    "enableSwaggerCodegen": false,
    "enableTranslation": true,
    "jhiPrefix": "jhi",
    "languages": ["es", "en"],
    "messageBroker": false,
    "nativeLanguage": "en",
    "packageName": "com.themakers.inventario",
    "packageFolder": "com/themakers/inventario",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "serviceDiscoveryType": "eureka",
    "skipClient": true,
    "testFrameworks": [],
    "websocket": false,
    "baseName": "inventariomicroservicio",
    "applicationType": "microservice",
    "authenticationType": "jwt",
    "buildTool": "maven",
    "serverPort": "8083",
    "jhipsterVersion": "6.7.1",
    "creationTimestamp": 1583859840796,
    "skipUserManagement": true,
    "clientPackageManager": "npm",
    "cacheProvider": "hazelcast",
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "embeddableLaunchScript": false,
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "blueprints": [],
    "otherModules": []
  },
  "entities": ["Producto", "ProductoAtributo", "Movimiento", "MovimientoDetalle", "Categoria", "Stock"]
}

</pre>
</details>


##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
/**
 * Product sold by the Online store
 */
entity Producto {
  nombre String required,
  descripcion String,
  precioCompra BigDecimal required min(0),
  precioVenta BigDecimal required min(0),
  codigobar String,
  imagen String,
  empresaId Long required,
  estadoId Long required,
  estadoProductoId Long required
}
entity Stock {
  cantidad Long required min(0),
  sucursalId Long
}
entity ProductoAtributo {
  atributo String,
  valor String
}
entity Categoria {
  nombre String required,
  descripcion String,
  image ImageBlob,
  empresaId Long
}
entity Movimiento {
  motivo String,
  tipoMovimientoId Long required,
  fecha Instant required,
  sucursalId Long required,
  sucursalrecibeId Long,
  empresaId Long required,
  estadoMovimientoId Long required
}
entity MovimientoDetalle {
  codigoProducto String,
  nombreProducto String,
  cantidad Long required min(0)
}
entity PrecioProducto {
  precio BigDecimal,
  activo Boolean
}
relationship OneToMany {
  Categoria{producto} to Producto{productCategoria(nombre)},
  Producto{productoAtributo} to ProductoAtributo{producto(nombre)},
  Movimiento{movimientoDetalle} to MovimientoDetalle{movimiento}
}
relationship ManyToOne {
  Stock{producto(nombre)} to Producto,
  MovimientoDetalle{producto(nombre)} to Producto
}

dto Producto, Stock, ProductoAtributo, Categoria, Movimiento, MovimientoDetalle, PrecioProducto with mapstruct
paginate Producto, Stock, ProductoAtributo, Categoria, Movimiento, MovimientoDetalle, PrecioProducto with pagination
service Producto, Stock, ProductoAtributo, Categoria, Movimiento, MovimientoDetalle with serviceClass
service PrecioProducto with serviceImpl
microservice Producto, Stock, ProductoAtributo, Categoria, Movimiento, MovimientoDetalle, PrecioProducto with inventariomicroservicio
filter Producto, Stock, ProductoAtributo, Categoria, Movimiento, MovimientoDetalle, PrecioProducto
clientRootFolder PrecioProducto with inventariomicroservicio

</pre>
</details>


##### **Environment and Tools**

openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.6+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.6+10, mixed mode)

git version 2.21.1 (Apple Git-122.3)

node: v12.14.1

npm: 6.13.4

yeoman: 3.1.1

yarn: 1.21.1

Docker version 19.03.5, build 633a0ea

docker-compose version 1.25.4, build 8d51620a

**Comment by gmarziou** [comment] 2020-03-18 16:25
I doubt that we can reproduce even with all your service configurations.

You could run the sub generator under debugger or add log statements to https://github.com/jhipster/generator-jhipster/blob/master/generators/docker-compose/index.js to understand which file is  causing the error.

**Comment by direstrepo24** [comment] 2020-03-18 16:31
sorry, how to do this?

**Comment by pascalgrimaud** [comment] 2020-03-18 16:58
I think @gmarziou is right, I couldn't reproduce using your configuration.
So I think you modified your config...

If you can publish all these projects on GitHub (or a different version generated from scratch), it would helped to reproduce.

Otherwise, I think we are stuck here

**Comment by gmarziou** [comment] 2020-03-18 17:05
> sorry, how to do this?

You edit `node_modules/generator-jhipster/generators/docker-compose/index.js` file and add log statements like `this.log(`Loaded something}`);` and then you re-execute.

**Comment by pascalgrimaud** [comment] 2020-03-22 10:42
As we didn't manage to reproduce, I'm pretty sure you modified the original projects.
Feel free to provide more details, projects on GitHub if possible etc... to help us to reproduce.
For now, let' close this.

**Closed by pascalgrimaud** 2020-03-22 10:42 UTC
Labels: area: needs-reproduction, theme: docker :whale:
