### ISSUE TITLE
jhi 4.2: Images are creating yarn error if the project Path contains spaces

### ISSUE THREAD

**Issue by Tcharl** [jhipster/generator-jhipster#5596] opened 2017-04-14 14:46 UTC
##### **Overview of the issue**

On windows, images are creating yarn error if the project Path contains spaces

~~~
\node_modules\cross-spawn\lib\enoent.js:46:16)
    at ChildProcess.cp.emit (d:\Users\T0172298\Documents\Mes Outils Personnels\com.thalesgroup.ods.ecwp\com.thalesgroup.ods.ecwp.gw\node_modul
es\execa\node_modules\cross-spawn\lib\enoent.js:33:19)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
 @ ./~/css-loader!./~/sass-loader/lib/loader.js!./src/main/webapp/app/layouts/navbar/navbar.scss 6:1556-1608
 @ ./src/main/webapp/app/layouts/navbar/navbar.scss
 @ ./src/main/webapp/app/layouts/navbar/navbar.component.ts
 @ ./src/main/webapp/app/layouts/index.ts
 @ ./src/main/webapp/app/app.module.ts
 @ ./src/main/webapp/app/app.main.ts
 @ multi (webpack)-dev-server/client?http://localhost:9060 webpack/hot/dev-server ./src/main/webapp/app/app.main`
~~~
##### **Motivation for or Use Case**

My company is forcing the path of each executable to be located in a specific folder (containing space)...

##### **Reproduce the error**
Create a jhipster project in a folder where parent path contains spaces (tested on windows), launch yarn install, yarn start, and wait for it!

##### **Related issues**
I don't think
##### **Suggest a Fix**
Sry, I'm far from be a ts/node expert. When there'll be backend issues, I will be there ;)

##### **JHipster Version(s)**
4.2.0

##### **JHipster configuration**
~~~
{
  "generator-jhipster": {
    "jhipsterVersion": "4.2.0",
    "baseName": "gw",
    "packageName": "",
    "packageFolder": "",
    "serverPort": "8080",
    "authenticationType": "uaa",
    "uaaBaseName": "uaa",
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": "hazelcast",
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "clientFramework": "angular2",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "gateway",
    "testFrameworks": [
      "cucumber",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "fr"
    ]
  }
}
~~~

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

Not concerned

##### **Browsers and Operating System**

Windows 7, git bash 1.9.4 (if it is important)

- [ x] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment] 2017-04-14 17:02
- Unfortunately we can't test on Windows, so it's quite hard for us to reproduce... Are you sure it's caused by the spaces? I guess it's the case, of course...
- Another big issue to test, is that Windows 7 is EOL - I guess your company paid for the extended support, but for us that's even harder to get a machine

Maybe you could try with NPM instead of Yarn? I strongly recommend Yarn, but it's still young and probably less tested on Windows 7, so maybe it will work with NPM

**Comment by gmarziou** [comment] 2017-04-14 21:26
I used your `.yo-rc.json` to generate an app in `e:\projets\name space\test` on Windows 10 Pro and I haven't  got any error with `yarn webpack:build` or `yarn start`.

Maybe you should use [Jhipster devbox](https://github.com/jhipster/jhipster-devbox).

**Comment by jdubois** [comment] 2017-04-14 21:43
Thanks @gmarziou - indeed I think this only fails with older Windows versions, which we can't test and/or support. @Tcharl you should tell your company to use a real OS :-)
Then, indeed, I know the constraints you have at your company (I did a few gigs there!), and I created the Devbox exactly for this kind of reasons (and for a very, very similar company), so that's your best option - it's also probably faster, as you won't have your anti-virus checking your JAR and .class files!
I'm closing this as we have workarounds, and we're not going to spend time supporting an older OS.

**Closed by jdubois** 2017-04-14 21:43 UTC

**Comment by Tcharl** [comment] 2017-04-15 12:14
@gmarziou @jdubois Thank you for the tests: as long as it works on win 10 (so that every other user will be happy), It's good to me ;-).
Unfortunately, I able to tell my company DIS/RSSI to use a Real OS, neither have admin rights nor local VM due to security concerns (we also have some issue with real VMs that randomly disconnects due to some psychotic proxy configuration). So as always I'll deal with it and find a way to hack it.

Thank you and best regards,
