### ISSUE TITLE
Api not found

### ISSUE THREAD

**Issue by lindamarieb** [jhipster/generator-jhipster#3583] opened 2016-05-12 07:59 UTC
##### **Overview of the issue**

I have a Jhipster app which I have installed on 3 different hosts - 1 Windows 8 server, 1 Centos Linux server and 1 Amazon Linux server. I am using the app mainly as an api for mobile apps and it works perfectly on the Windows server and Centos server, but on the Amazon Linux server I get 404 Not Found errors for all "/api" paths - the base url works fine but the moment I try to access /api it fails. I'm running the app in Tomcat8. Access to the app is proxied by Nginx.

##### **Motivation for or Use Case** 

I would really appreciate any help with this issue.

##### **JHipster Version(s)** 

jhipster 2.17.0

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 

{
  "generator-jhipster": {
    "baseName": "boss",
    "packageName": "za.co.irontree.boss",
    "packageFolder": "za/co/irontree/boss",
    "authenticationType": "xauth",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": "no",
    "useCompass": false,
    "buildTool": "maven",
    "frontendBuilder": "grunt",
    "javaVersion": "8",
    "enableTranslation": false,
    "rememberMeKey": "xyz"
  }
}

##### **Browsers and Operating System** 

Amazon Linux. Browser irrelevant in this case.

**Comment by jdubois** [comment] 2016-05-12 08:26
This is probably an issue with NGinx -> the gateway is supposed to be the entrance to the app, so if you put something in front of it, we can't really support you. It's more a question on StackOverflow than a bug...

So I'm closing this as it's not a bug (and I couldn't reproduce it, I didn't even know there was an "Amazon Linux"!!), but here are some thoughts:

- As you seem to deploy on Tomcat, make sure you deploy to the ROOT context
- Have a look at your Tomcat logs, if you have 404 errors you should see something here
- As NGinx is the proxy server, maybe you could have a look at the Spring Boot documentation for running behind a proxy server: https://docs.spring.io/spring-boot/docs/current/reference/html/howto-embedded-servlet-containers.html#howto-use-tomcat-behind-a-proxy-server

**Closed by jdubois** 2016-05-12 08:26 UTC
