### ISSUE TITLE
Code Review: User/Account Management Bugs/Testcases/JWT concerns

### ISSUE THREAD

**Issue by RobinKamps** [jhipster/generator-jhipster#6987] opened 2018-01-15 12:55 UTC
##### **Overview of the issues**

Greetings JHipsters!

First of all thanks for your amazing work!
Just reviewed some of your code.
Here are some obvious bugs and concerns:

1.
Login of users can be changed via adminpanel.
However Login with invalid old Login is still possible, if cacheManager is enabled.
Solution: Both caches should be evicted on updateUser(UserDTO...) **also before** you update the user e.g.:

```
<%_ if (cacheManagerIsAvailable === true) { _%>
                cacheManager.getCache(UserRepository.USERS_BY_LOGIN_CACHE).evict(user.getLogin());
                cacheManager.getCache(UserRepository.USERS_BY_EMAIL_CACHE).evict(user.getEmail());
<%_` } _%>
```

2.
Email of users can be changed via adminpanel or via account by the users.
Login with old Email is still possible.
Solution: The email cache should evict on updateUser(String...) **also before** you update the user e.g.:

```
<%_ if (cacheManagerIsAvailable === true) { _%>
                cacheManager.getCache(UserRepository.USERS_BY_EMAIL_CACHE).evict(user.getEmail());
<%_` } _%>
```

Note: There are no Testcases wich cover the appropiate cache behavior - they should be added.

3.
Login via Email is messed up:
Emails can be stored with uppercases in db (on registration e.g.).
Then Login with email is not possible. Reason: the login is always converted tolowercase.
(DomainUserDetailService / String lowercaseLogin = login.toLowerCase(Locale.ENGLISH);)
Solution: emails should be stored in db tolowercase like the login - otherwise indexing and finding them etc. is just bad.

Testcases here do not cover tolower correct (no email in the testcases contains uppercase letters)

4. 
There is no need to check db everytime for email at login - its only needed if login is in email format.
Solution: check `(new EmailValidator()).isValid(lowercaseLogin,null)` first

Note:
Tests do not cover elasticsearch deletes/updates

...

Important Notes (I guess also pretty obvious for all that have jwt experience):

The overall design of how the jwt-tokens and UserDetailService/principal is currently implemented is not production ready.
Please stop people telling they can rely on SecurityUtils.getCurrentUserLogin() to get the user id or even use the login as a reference fk on microservices (Stackoverflow is full of such answers). If the user login is changed via admin panel or people imlement a feature wich enables users to change their own username, those people will be in big trouble. The login is not a reliable fk - so all references on old logins (data owned by users and logs e.g.) will fail.

For pure jwt-auth (and where you somehow "own" the users) it would be far more better to use the real PK id as sub (or at least do not allow the login to be changed and mention this in the docs). 
Otherwise it is possible to get logged in as another user, if you flip usernames (you can easily try this out) (or to login as a non existent user).
This is made worse by the long duration if "remember me" was checked.
Furthermore using the id as sub you can easily get the correct id directly in a microservice and have no "fake fk" issues.

Currently a valid token is produced for every successfull login - and the token is valid until its expiration date, regardless if the user login changed - this is normal for jwt and could be sufficient on some use cases - but this is not an optimal solution for general usage.
To secure the current  jwt configuration you should consider a "jwt revocation mechanism" - an option using uuid as jti and to store it with the user in db. In JWTToken getAuthentification etc. it has to be looked up and set to a new value etc. - this way a user who has clicked logout will stay logged out - even if he supplies one of the non-expired tokens - only one token or no token will be valid at a time.
(this will result in one db-query for each rest call with monoliths (which will happen also if you use the built in SecurityUtils.getCurrentUserLogin() method anyway - but due to the neccessary update call it will not be in the cache). In an microservice environment it could be added to the uaa. Every other microservice then will have to validate the jwt calling an uaa instance via rest so this approach will result a much higher workload of the uaas/db etc.).

The implementation of a "revocation" mechanismen will also solve the following issue:
if an admin deactivates a user the user still will be logged in / able to login via existing tokens (this also can easily be tried out right now).

I know JHipster is just a generator but it also claims that it will generate production ready features.
JHipster may be used from newbies so i guess a more reliable (fk issue) and a more secure configuration should be provided, or at least the users should be informed/aware of the downsides/caveats of the current implementation on http://www.jhipster.tech/security/.

Thank you for your attention.

**Comment by jdubois** [comment] 2018-01-15 13:14
Thanks for your feedback - lots of different things here, and the important point for me is that it's probably the first time we have someone do a complete audit of what is being generated. So thanks a lot - please keep doing this!!

For the first 4 points: we need to check each of them, nothing seems to be very bad here (the admin panel isn't normally used to modify a user's login or e-mail - but you are right, if there is the option, it should be correctly done). I'm surprised by the e-mail addresses which are not in lower-case, I remember checking this - maybe someone changed the code, or maybe I did a mistake. As you seem to have a good understanding of this @RobinKamps maybe you could do PRs for those? It shouldn't be very hard anyway.

The most important point is after, concerning the user login. Maybe people tell that on Stackoverflow, as you say - I'm not reading everything on Stackoverflow, to be honest. Anyway, we never tell people to use the login as an ID - we have an ID, which is indeed used as a FK, and which basically is the answer to all your concerns. The login can be changed (and that's why it's bad to use it as an ID), and can be used publicly (the ID is not shared, for example if you create a public "user profile" page, you'll use the login, not the ID). Basically, I think we agree here. Maybe we could improve our "security" page for this topic?
Please note this might change soon: we might totally drop off the login, to use just the email (which has the same issue, but at least that's one less issue to take care of), and we'll also move to Spring Security 5 (which might also change a couple of things here)

**Comment by RobinKamps** [comment] 2018-01-15 14:16
Yes i can do a PR but it will take one or two weeks.

Sorry - it was not a complete audit - i just refactored the current implementation to my needs (no login - just email) and tried to figure out how things are implemented in JHipster. For my own project i also implemented a prototype to use id as sub in the token. 
By the way: In JHipster the standard Spring DetailUser implementation is always used as an Adapter (even in UserDetailsService).
For the next Version/Spring 5 especially if you are going down the jti uuid "revocation" feature road you should consider to implement the Spring interface UserDetails on your "Domain"User - and use it instead of the build in Implementation, so you will be able to cast the principal to the actual user - this approach is easy in monolith but more complex in microservice settings. The authorities class should implement the corresponding Spring Security Interfaces as well...

Yes, i think we totally agree on the usage of login as fk.
Perhaps the right way for relation usage to users in a microservice should be in the docs.
Without it people maybe running in the wrong direction (just a stackoverflow example
https://stackoverflow.com/questions/43393074/missing-user-class-creating-entity-relationship-to-user-entity-in-microservice/43405851
)

**Comment by jdubois** [comment] 2018-01-15 14:20
Hold on @RobinKamps - I'm pretty sure we're working on the same thing, as I'm preparing JHipster 5:

- Migration to Spring Security 5
- Removing the login, to just use the email

-> if you have time (and 1 or 2 week is really good, my goal is for more than 1 month), could you work on our "spring-boot-2" branch? This should get merged in the master branch at some point, and will be the basis for JHipster 5.

-> if that's fine with you, please tell me, so I can work on other parts of the migration, which is big. I also think @mraible will work on the Open ID Connect part.

**Comment by ruddell** [comment] 2018-01-15 16:53
@RobinKamps While I agree with your other points, I don't think we should restrict login to one token at a time.  A common use-case for me is to be logged in via a mobile application and through a browser at the same time.

I updated the StackOverflow question to advise using the user's ID instead of login.  Is the fact that the JWT token stores the user's login (instead of the ID) an issue as well?

**Comment by RobinKamps** [comment] 2018-01-15 17:02
@jdubois Thank you for your invitation - i have doubts that i´m the right one to do the job.
Refactoring a given codebase on such things for custom needs is an easy task and i can do "smart talk" on jwt-based login etc. But after all i´m relativley new to jhipster/spring and yeoman. I have only little experience with microservices, your oauth and openid integration (okta/keycloak) as well as with social login. 
I guess you need someone who has different JHipster settings up and running in Production and is really a Spring Security Expert.

**Comment by jdubois** [comment] 2018-01-15 17:07
Don't underestimate yourself @RobinKamps - from what I see you perfectly understand our codebase and issues!
The JWT part is in separate templates, if you have a look at https://github.com/jhipster/generator-jhipster/tree/master/generators/server/templates/src/main/java/package you shouldn't have much trouble (and don't worry we have processes to validate your code, and are used to people making mistakes in the PRs, there's no issue with that at all - what's important is the security code you write, then fixing a PR is easy for me)

**Comment by RobinKamps** [comment] 2018-01-15 19:50
@ruddell - sorry for mentioning your answer as not best practice - just picked a random answer at stackoverflow mentioning saving the login from jwt as fk to the db is a good solution without mentioning it could lead to broken fks. 

Yes, you are right - "revocation" is not the best for every use case (however "jwt revocation" could easily be set up in a way, that more than one token is valid at a time and still becomes invalid, if the user/device using the token logs out and the other device stays in - you even could implement that one user can not log in from more than x devices at the same time etc.)

There is no easy answer on the question what to store in jwt - after thinking about this issue once more i would suggest the following:

Case 1 - if you own/manage the users in a database and have access to the pk.
then login/username/email etc. should be treated as possible beeing affected by changes by admins or users.
Then the pk/id should be put into the jwt and you have a "strong fk binding". 

Case 2 - you don´t own the users.
If the authorization mechanismen provides a real pk: use this as login - then you have a "strong binding", too. (Dont know how OpenID and OAuth could be set up this way..- In case of OpenID the user can decide which Information your Aplication could get/read from it - so you can´t really generally rely on this and therefore a traditional approach with a "complete your user profile"/registration process is more likely especially if your application stores sensitive data)
However if you have absolutely no chance to get the "real" pk and want to store entities for the users then you have to assume one given part of information or some informations together etc. like the login/username or email as fk - resulting in a "weak fk binding" (i just made those terms up). 

This categorisation has following effects:
If you have only a weak binding - anything could be possible. Perhaps a email/adress or Domain gets deleted and is registered by another person/company - then data stored with the "weak fk" possibly could be exposed to that person (note: this could also be a possible issue, if you have a password reset link to email adresses with traditional account management).
As this is a edge case - the alteration of username/email as a credentials is much more likely.
If you run you own Oauth/OpenId Server etc. - perhaps you could set this up to give an unique id as well to have a "strong binding" (e.g. when a person leaves a company and another person with the same name gets a equal email/username  etc.)

i just made some test with jhipsters keycloak default config to backup my suggestions. In JHipster the keycloak username is taken as login/Principal (so entites would be stored with "admin" or "user" as fk). In keycloak the alteration of the username is restricted so far so good - but not optimal.
If i just delete a user and again add a user with same username - all the entites stored with this fk will belong to the new user (with same username "user" e.g. but different uuid - keyclaok uses an uuid internally).
If you run your own Keycloak instance this should definetly be configured to expose the id- if that is possible and jhipster should pick this up as "strong fk". 

By the way keycloak.yml should use version: '2.1' docker for windows othwerwise it fails.

Summary: use real pks/ids wherever possible - if you cannot: be aware of possible side effects and try to minimize them for your use case.

PS: 
However JHipster is just a generator and cannot provide best solutions for all use cases.
Dependening on the use case you could store and synchronize the user data exposed by OpenId/etc to your own db and therefore somehow own the user - but without the need to manage the email/username/password etc.
Amongst others i manage a project with similar use case: users are authenticated by a third party via soap (and i get a "real pk" back). The project includes lots of forms/data - entities with relation created_by and updated_by those users - and all data has to be archived for several years. As users are not owned by me but i have to ensure, that fks are stable and user information can be accesss along with form/data (and exported to pdf etc.) at anytime and does not get deleted or are altered in any way i wrote a custom user/db handling for that. Because users are stored (without passwords) in my db as well, forms/data can still be identified with fks and one could view user history even if they don´t exist in the third party application anymore.

**Comment by RobinKamps** [comment] 2018-01-17 10:07
Good Morning JHipsters!

@ruddell: Just deleted my last comment. It was right, that you always should store the unique identifier (user id) in jwt.
However after fiddling around with googles oauth/openId and keycloaks interplay with jhipster at the moment, i think everybody who really cares should go "rtfm" first (including me next time) and figure out the best approach for his usecase and ecosystem - there are just too many options and different approaches all with their pros and cons.
After all my last comment was way to general, so here is one comment more specific on JHipster.

By the way JHipster has already implemented a mechanismen (Method syncUserWithIdP) to update/synchronize users, which i suggested in general as a possible solution - im just new to JHipster so thanks for not commenting my comment.

@jdubois:
You must be kidding - i have just played a few hours with jhipster/spring - just with jwt settings and now a bit with keycloak integration.

You are right that i try to understand in general what good software design looks like (for the Spring Userdetail interface/extend from it part).
And yes i hope to understand what JHipster does and what role the login/uaa plays in there and how it could evolve.
(As JHipsters main tasks are 
1. get you up and running a spring monolith with ng-frontend and additions or complex microservice stacks and 
2. provide an entity generator for the stack and hooks for third party generators,
the goals of refactoring the uaa/login should take care that the whole codebase stays with a minimal footprint (maintainability), does not get bloated with features keycloak/okta already offer and 
stick tight to Springs common interfaces, so Spring devs have minimal learning curve. 
Then developers can customize the uaa or switch to the various more advanced options 
- so nothing new for you here i guess!)

But for me it seems that this issue is not just about dropping the username and replace it by the email.

Here is why:
JHipster currently uses the login in the JWT/and Session based as internal Principal on all setups (uaa, keycloak and social) 
- this of course has to change if the login is dropped. 

The tricky part is, that what ever the solution will look like in the end, there are perhaps non resolving race conditions to a possible final design.
So this is more a political/strategic issue including the evaluation of each cons and pros - and therefore should be taken from a lead and backed up by the team.
If you want an all inclusive solution like now (without ignoring the standards for the sub) i see this thing might end up more like an adapter, 
wich has the benefit of integrating all kind of stuff but is not the best way if you want a tight integration with keycloak e.g. and devs have to decide if they drop this adapter later on or figure out how they can integrate their own stuff/use this adapter.

To replace the login there are many possible solutions - here are a few of them:

1.
The users from other sources can be still be synchronised with somehow with syncUserWithIdP and login could just be replaced with email as Principal (ignoring the standards - if you consider email is supposed to be sufficient unique in most usecases).
This would be by far the easiest way of refactoring, but no good solution at all, 
because you would still ignore standards, and you will have to look up the real user pk before storing related data. 
On the other hand the additional lookup is not as bad as it may seem, because if you are on a pure uaa/JWT setting devs should consider to lookup the user 
anyway before a critical operation and check: 
a. if the user is still active. 
b. if the user has still the granted_authorities - as JWT Tokens maybe long time valid 
(even deleted admins could use still valid tokens to mess up your data or create other admin accounts, that could be used later on, e.g.). 

2.
As 1. but with user (long) id as Principal/JWT sub/Session.
This would be better, because microservices could just read the id from the session/token without lookup (for uncritical ops!) and its standard compliant.

3.
As 2. but with uuid instead of long. Few pros (mainly for distributed services) but for most use cases perhaps even more cons (size, performance) if you just look at long vs uuid. 
But it turns out that the default Keycloak setup returns already an uuid as sub - the "real user pk" internally used in keycloak. So uuid would be indeed a good solution if JHipster should be connected more tightly to keycloak, as you can just synchronize it with the real pk (or even drop more uaa code)

However you should consider to store this uuid in conjunction with keycloak anyway, 
because its the sub and only this is intended as the unique identifier even if you do not use it and generate your own long id (flip email/removed and newly created username problem etc...).
However at the moment i believe you use "preferred_username" in `UserService` as an unique identifier, wich is not intendend for this kind of usage 
(the docs say: "The RP MUST NOT rely upon this value being unique", http://openid.net/specs/openid-connect-core-1_0.html search for preferred_username)

`
private static User getUser(Map<String, Object> details) {
        User user = new User();
        user.setLogin((String) details.get("preferred_username"));
`

4.
To not just have uuid support for the sub you could consider an Adapter pattern like this:
Two additional attributes for users - one for external reference sub (the sub you get from third parties), the other one to distinguish the auth provider who handed out the sub reference.

Reason is that other Auth Providers may have different approaches to generate their sub - and you have to get sure this references 
a. dont clash (at least if your software is made for the long run/millions of users etc.), but  still
b. users can use your service if third party subs clash - therefore distinguishing the auth provider

Google e.g. uses a google_id (seems to be non uuid) wich you should store and take this as an identifier to look up your internal JHipster id (perhaps long):
Google Docs say: "Claim: sub	Provided: always - An identifier for the user, unique among all Google accounts and never reused. 
A Google account can have multiple emails at different points in time, 
but the sub value is never changed. 
Use sub within your application as the unique-identifier key for the user."

So this adapter approach would generalize how JHipster treats different auth providers 
- internally you still use your own JHipster id as sub perhaps long or whatever.

I have not checked how you use/look up Googles sub at the moment - but after seeing how keycloak sub is not used, this should be checked, too.

5.
If you do not want to implement that much - keycloak already has setup a decent social/third party integration...

6.
Instead of using a general adapter you could provide/let yeoman generate different optimized codebases for the different use cases 
- i have zero yeoman dev experience and do not know if this is could be a valid/maintainable solution.


As mentioned i have no experience to your current facebook/okta integration, so before making a design decision this should be checked, too.
I guess other parts of JHipster are affected by this design decision as well - without looking into it:
- the current audit component
- the jhipster entitiy generator (establishing the user relations)

As this is a strategic design decision wich has effects on the whole project and
i am just about to learn spring/jhipster/yeoman - please see all this just as basic ideas - there will be definetly some serious points missing.
After all you should discuss even more possible solutions with their pros and cons in detail, so you can come up with a profound solution, which should be the best possible decision for the future of JHipster. 
Perhaps this all is too complex to archieve in your planned schedule - than you should consider to just replace login with id just to get it working with spring 5 and come up with a better solution afterwards. 
However: do not let take this over from a random guy who found a few bugs.

Thanks for your attention - i know my comment is way too long.
Happy Coding!

PS:
Personally i will have a deeper dive into integrating keycloak, as this provides most stuff i need - 
fine grained control of resources, interceptors and services can 
add themselves dynamically including their roles/permission setup etc.

**Comment by deepu105** [comment] 2018-06-04 10:03
@RobinKamps @jdubois I dont think anyone is working on this. @jhipster/developers is anyone willing to work on this else lets close it as 'wont-fix'

**Comment by jdubois** [comment] 2018-06-04 10:52
I can confirm nobody works on this - we just lack time to do everything, and there isn't much external contribution on those topics (sadly)

**Comment by jdubois** [comment] 2018-08-27 09:45
I've just checked:

- Point 1 is already done
- Point 2 is already done
- I'm doing a fix for point 3 and will link the commit here

**Comment by jdubois** [comment] 2018-08-27 09:59
- point 4 is also already done

This ticket is quite old and 3 out of 4 points where already done: the problem here is that it is too big, so people don't read it (including me). We need smaller issues, as people do this on their free time, and don't have the will to read stuff for 10 minutes.

I'll close this when point 3 is merged (I'm waiting for Travis)

**Comment by jdubois** [comment] 2018-08-27 13:15
Travis is having issues so I can't validate with the CI right now :-(
I've merged this into master, if the build fails I will correct manually

**Closed by jdubois** 2018-08-27 13:15 UTC
Labels: help wanted
