### ISSUE TITLE
JHipster 4.3.0 unable to create production build

### ISSUE THREAD

**Issue by waqas80** [jhipster/generator-jhipster#5644] opened 2017-04-23 08:26 UTC
I updated the JHipster to latest version 4.3.0. I created a simple application a monolithic one. And build the project. It works perfectly fine. But when I create a production build with the following command ./mvnw -Pprod package;   I am getting the below error

[INFO] > myblog@0.0.0 ngc /Users/waqas80/Documents/jhip-proj/myblog
[INFO] > ngc -p tsconfig-aot.json
[INFO] 
[ERROR] Warning: Can't resolve all parameters for AlertService in /Users/waqas80/Documents/jhip-proj/myblog/node_modules/ng-jhipster/src/service/alert.service.d.ts: ([object Object], ?, [object Object]). This will become an error in Angular v5.x
[ERROR] Warning: Can't resolve all parameters for InterceptableHttp in /Users/waqas80/Documents/jhip-proj/myblog/node_modules/ng-jhipster/src/interceptor/interceptable-http.d.ts: ([object Object], [object Object], ?). This will become an error in Angular v5.x
[ERROR] Template parse warnings:
[ERROR] The <template> element is deprecated. Use <ng-template> instead ("
[ERROR]   <div class="card">
[ERROR]     [WARNING ->]<template ngFor let-panel [ngForOf]="panels">
[ERROR]       <div role="tab" id="{{panel.id}}-header"
[ERROR]         "): ng:///Users/waqas80/Documents/jhip-proj/myblog/node_modules/@ng-bootstrap/ng-bootstrap/accordion/accordion.d.ts.NgbAccordion.html@2:4
[INFO] Hash: b0a3d30ef41a8b83663d
[INFO] Version: webpack 2.3.3

And the below warning messages also appear,

[INFO]     [./node_modules/html-webpack-plugin/lib/loader.js!./src/main/webapp/index.html] ./~/html-webpack-plugin/lib/loader.js!./src/main/webapp/index.html 944 bytes {0} [built]
[WARNING] npm WARN angular2-cookie@1.2.6 requires a peer of @angular/common@^2.0.0 but none was installed.
[WARNING] npm WARN angular2-cookie@1.2.6 requires a peer of @angular/core@^2.0.0 but none was installed.
[WARNING] npm WARN ng-jhipster@0.1.12 requires a peer of @angular/core@4.0.0 but none was installed.
[WARNING] npm WARN ng-jhipster@0.1.12 requires a peer of @angular/http@4.0.0 but none was installed.
[WARNING] npm WARN ng2-translate@4.2.0 requires a peer of @angular/core@^2.0.0 but none was installed.
[WARNING] npm WARN ng2-translate@4.2.0 requires a peer of @angular/http@^2.0.0 but none was installed.
[INFO] 

Below is the info generated by JHipster info command 
##### **JHipster Version(s)**

```
myblog@0.0.0 /Users/waqas80/Documents/jhip-proj/myblog
└── generator-jhipster@4.3.0 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.enfocarsoft.myblog"
    },
    "jhipsterVersion": "4.3.0",
    "baseName": "myblog",
    "packageName": "com.enfocarsoft.myblog",
    "packageFolder": "com/enfocarsoft/myblog",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "jwtSecretKey": "6786ea6f4be82863f6229cfc4ff4bd55f032536c",
    "clientFramework": "angular2",
    "useSass": true,
    "clientPackageManager": "npm",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

ls: no such file or directory: .jhipster/*.json

##### **Browsers and Operating System**

java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)

node: v6.10.0

npm: 4.6.1

yeoman: 1.8.5

Docker version 17.03.0-ce, build 60ccb22

docker-compose version 1.11.2, build dfed245

**Comment by pascalgrimaud** [comment] 2017-04-23 08:54
I confirm these messages. 
But the prod build finished successfully and the application starts and runs without problem. 
So for me, it's only warning but we should probably do something

**Comment by jdubois** [comment] 2017-04-23 10:45
Some of those come from ng bootstrap, so it's not even our fault

Le 23 avr. 2017 10:54 AM, "Pascal Grimaud" <notifications@github.com> a
écrit :

**Comment by jdubois** [comment] 2017-04-23 10:46
Some of those come from ng bootstrap, so it's not even our fault

Le 23 avr. 2017 10:54 AM, "Pascal Grimaud" <notifications@github.com> a
écrit :

I confirm these messages.
But the prod build finished successfully and the application starts and
runs without problem.
So for me, it's only warning but we should probably do something

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/jhipster/generator-jhipster/issues/5644#issuecomment-296428960>,
or mute the thread

**Comment by jdubois** [comment] 2017-04-23 11:17
Closing as this is just a warning, and not our fault

**Closed by jdubois** 2017-04-23 11:17 UTC

**Comment by waqas80** [comment] 2017-04-23 17:14
But because of these messages, the prod build not completed successfully.

**Comment by jdubois** [comment] 2017-04-23 17:16
I don't understand: those are just warning messages, and the prod build does succeed in the end (at least on my machine). Do you mean you have no executable WAR in your target directory? I don't think this is caused by those warnings, you should have some other error elsewhere - could you check this? Of course we'll reopen this if we have more information and can reproduce

**Comment by waqas80** [comment] 2017-04-23 17:30
Yes the WAR file is not getting generated. 
When I run the command (./mvnw -Pprod package) below is the complete errors generated at the end
[ERROR] 
[ERROR] npm ERR! Darwin 16.5.0
[ERROR] npm ERR! argv "/Users/waqas80/Documents/jhip-proj/myblog/node/node" "/Users/waqas80/Documents/jhip-proj/myblog/node/node_modules/npm/bin/npm-cli.js" "run" "test"
[ERROR] npm ERR! node v6.10.0
[ERROR] npm ERR! npm  v4.3.0
[ERROR] npm ERR! code ELIFECYCLE
[ERROR] npm ERR! errno 1
[ERROR] npm ERR! myblog@0.0.0 test: `npm run lint && karma start src/test/javascript/karma.conf.js`
[ERROR] npm ERR! Exit status 1
[ERROR] npm ERR! 
[ERROR] npm ERR! Failed at the myblog@0.0.0 test script 'npm run lint && karma start src/test/javascript/karma.conf.js'.
[ERROR] npm ERR! Make sure you have the latest version of node.js and npm installed.
[ERROR] npm ERR! If you do, this is most likely a problem with the myblog package,
[ERROR] npm ERR! not with npm itself.
[ERROR] npm ERR! Tell the author that this fails on your system:
[ERROR] npm ERR!     npm run lint && karma start src/test/javascript/karma.conf.js
[ERROR] npm ERR! You can get information on how to open an issue for this project with:
[ERROR] npm ERR!     npm bugs myblog
[ERROR] npm ERR! Or if that isn't available, you can get their info via:
[ERROR] npm ERR!     npm owner ls myblog
[ERROR] npm ERR! There is likely additional logging output above.
[ERROR] 
[ERROR] npm ERR! Please include the following file with any support request:
[ERROR] npm ERR!     /Users/waqas80/.npm/_logs/2017-04-23T17_27_13_350Z-debug.log
[ERROR] 
[ERROR] npm ERR! Darwin 16.5.0
[ERROR] npm ERR! argv "/Users/waqas80/Documents/jhip-proj/myblog/node/node" "/Users/waqas80/Documents/jhip-proj/myblog/node/node_modules/npm/bin/npm-cli.js" "run" "webpack:prod"
[ERROR] npm ERR! node v6.10.0
[ERROR] npm ERR! npm  v4.3.0
[ERROR] npm ERR! code ELIFECYCLE
[ERROR] npm ERR! errno 1
[ERROR] npm ERR! myblog@0.0.0 webpack:prod: `npm run ngc && npm run test && webpack -p --config webpack/webpack.vendor.js && webpack -p --config webpack/webpack.prod.js`
[ERROR] npm ERR! Exit status 1
[ERROR] npm ERR! 
[ERROR] npm ERR! Failed at the myblog@0.0.0 webpack:prod script 'npm run ngc && npm run test && webpack -p --config webpack/webpack.vendor.js && webpack -p --config webpack/webpack.prod.js'.
[ERROR] npm ERR! Make sure you have the latest version of node.js and npm installed.
[ERROR] npm ERR! If you do, this is most likely a problem with the myblog package,
[ERROR] npm ERR! not with npm itself.
[ERROR] npm ERR! Tell the author that this fails on your system:
[ERROR] npm ERR!     npm run ngc && npm run test && webpack -p --config webpack/webpack.vendor.js && webpack -p --config webpack/webpack.prod.js
[ERROR] npm ERR! You can get information on how to open an issue for this project with:
[ERROR] npm ERR!     npm bugs myblog
[ERROR] npm ERR! Or if that isn't available, you can get their info via:
[ERROR] npm ERR!     npm owner ls myblog
[ERROR] npm ERR! There is likely additional logging output above.
[ERROR] 
[ERROR] npm ERR! Please include the following file with any support request:
[ERROR] npm ERR!     /Users/waqas80/.npm/_logs/2017-04-23T17_27_13_372Z-debug.log
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:41 min
[INFO] Finished at: 2017-04-23T21:27:13+04:00
[INFO] Final Memory: 31M/354M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.3:npm (webpack build prod) on project myblog: Failed to run task: 'npm run webpack:prod' failed. (error code 1) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by jdubois** [comment] 2017-04-23 17:33
And did you try what is being said, running:

    npm run lint && karma start src/test/javascript/karma.conf.js

This might be a Karma test issue

**Comment by pascalgrimaud** [comment] 2017-04-23 18:30
@waqas80 : I tried your configuration and the build finished successfully:
```
╭─pgrimaud@xps ~/tmp/50-5644  
╰─$ ./mvnw -Pprod package
[INFO] Scanning for projects...
[INFO] 

(...)

[INFO] --- spring-boot-maven-plugin:1.5.2.RELEASE:repackage (default) @ myblog ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:56 min
[INFO] Finished at: 2017-04-23T20:27:34+02:00
[INFO] Final Memory: 65M/600M
[INFO] ------------------------------------------------------------------------
╭─pgrimaud@xps ~/tmp/50-5644  
╰─$ ls -al target 
total 107912
drwxr-xr-x 13 pgrimaud pgrimaud     4096 avril 23 20:27 .
drwxr-xr-x  9 pgrimaud pgrimaud     4096 avril 23 20:24 ..
drwxr-xr-x  4 pgrimaud pgrimaud     4096 avril 23 20:23 aot
drwxr-xr-x  8 pgrimaud pgrimaud     4096 avril 23 20:27 classes
drwxr-xr-x  3 pgrimaud pgrimaud     4096 avril 23 20:26 generated-sources
drwxr-xr-x  3 pgrimaud pgrimaud     4096 avril 23 20:27 generated-test-sources
drwxr-xr-x  2 pgrimaud pgrimaud     4096 avril 23 20:27 maven-archiver
drwxr-xr-x  3 pgrimaud pgrimaud     4096 avril 23 20:26 maven-status
drwxr-xr-x  6 pgrimaud pgrimaud     4096 avril 23 20:27 myblog-0.0.1-SNAPSHOT
-rwxr--r--  1 pgrimaud pgrimaud 57343906 avril 23 20:27 myblog-0.0.1-SNAPSHOT.war
-rw-r--r--  1 pgrimaud pgrimaud 51297771 avril 23 20:27 myblog-0.0.1-SNAPSHOT.war.original
-rw-r--r--  1 pgrimaud pgrimaud  1802672 avril 23 20:26 stats.html
drwxr-xr-x  2 pgrimaud pgrimaud     4096 avril 23 20:27 surefire-reports
drwxr-xr-x  4 pgrimaud pgrimaud     4096 avril 23 20:27 test-classes
drwxr-xr-x  4 pgrimaud pgrimaud     4096 avril 23 20:26 test-results
drwxr-xr-x  4 pgrimaud pgrimaud     4096 avril 23 20:26 www
```

As you upgrade your project, can you try to delete your `node_modules` folder and relaunch your build?

**Comment by waqas80** [comment] 2017-04-23 18:32
this command not work.
But I deleted the project folder and update npm and NodeJS package. And create a project again. Now the WAR file gets generated. But I can still the errors in log. 
Thanks Julien 
Thanks Pascal. Now next step is to host on AWS. 
Thanks alot for helping.

**Comment by jdubois** [comment] 2017-04-23 18:43
OK you probably had an issue with your `node_modules`, that's why I recommend using Yarn :-)

**Comment by amaziane** [comment] 2018-05-14 23:53
Hello Julien ,

I have the same problem as my collegues , and i don't know how i can fixe it ;
[ERROR] warning Resolution field "source-map@0.6.1" is incompatible with requested version "source-map@^0.4.2"
[INFO] [3/5] Fetching packages...
[INFO] info fsevents@1.2.3: The platform "linux" is incompatible with this module.
[INFO] info "fsevents@1.2.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[INFO] [4/5] Linking dependencies...
[ERROR] warning " > bootstrap@4.0.0" has unmet peer dependency "popper.js@^1.12.9".
[INFO] [5/5] Building fresh packages...
[INFO] success Saved lockfile.
[INFO] $ node node_modules/phantomjs-prebuilt/install.js
[INFO] Found PhantomJS at /home/jhipster/app/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs ...verifying
[INFO] PhantomJS is previously installed at /home/jhipster/app/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs
[INFO] Done in 189.36s.
[INFO]
[INFO] --- frontend-maven-plugin:1.6:yarn (webpack build prod) @ app ---
[INFO] yarn not inheriting proxy config from Maven
[INFO] Running 'yarn run webpack:prod' in /home/jhipster/app
[INFO] yarn run v1.3.2
[INFO] $ yarn run cleanup && yarn run webpack:prod:main && yarn run clean-www
[INFO] $ rimraf target/{aot,www}
[INFO] $ yarn run webpack --config webpack/webpack.prod.js --profile
[INFO] $ node --max_old_space_size=4096 node_modules/webpack/bin/webpack.js --config webpack/webpack.prod.js --profile
[ERROR] Killed
[ERROR] error Command failed with exit code 137.
[INFO] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[ERROR] error Command failed with exit code 1.
[INFO] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[ERROR] error Command failed with exit code 1.
[INFO] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 07:03 min
[INFO] Finished at: 2018-05-14T23:46:09Z
[INFO] Final Memory: 28M/68M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.6:yarn (webpack build prod) on project app: Failed to run task: 'yarn run webpack:prod' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
root@amaziane:/home/jhipster/app#

**Comment by pascalgrimaud** [comment] 2018-05-15 04:13
Hi @amaziane
We don't know how to help you if we have 0 information about your config, your options, your environment etc. 
Plz open a new issue with all required informations

**Comment by gmarziou** [comment] 2018-05-27 08:57
@amaziane 1 GB of RAM is probably too low by far and you should install node 8.x rather than 10.x
