### ISSUE TITLE
Allow to override `app` from a blueprint

### ISSUE THREAD

**Issue by danielpetisme** [jhipster/generator-jhipster#9835] opened 2019-05-31 22:02 UTC
##### **Overview of the feature request**

The purpose of this feature is to be able to override the `app` generator behavior in blueprints.

##### **Motivation for or Use Case**

As you may know, I'm working on a .Net Core JHipster blueprints and some prompts/behaviors are managed by the `app` itself (like the type of application, JHipster UAA is not applicable in a .Net context). 

IMHO, it's simply to apply the pattern already in place for the other generators (using `_` functions). Do I miss something?

##### **Related issues or PR**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by ruddell** [comment] 2019-05-31 23:31
Duplicate of https://github.com/jhipster/generator-jhipster/issues/9692

**Closed by ruddell** 2019-05-31 23:31 UTC
