### ISSUE TITLE
How to view Hazelcast cache logs?

### ISSUE THREAD

**Issue by pavankjadda** [jhipster/generator-jhipster#7300] opened 2018-03-15 14:45 UTC
##### **Overview of the issue**

I have a project with two microservices and a gateway. Both were generated through JHipster. I use Hibernate 2nd level cache for caching and implemented this with Hazelcast cache solution. Everything deployed to Docker using docker-compose. My question is "When I load the entities the second time, how do I know if microservice hitting the database or fetching from cache". Where can I see generated hibernate queries for each request? And cache provider logs? Code uploaded to [Github](https://github.com/pavankjadda/Kubernetes-SpringCloudStream-Kafka-Docker) for reference

##### **Motivation for or Use Case**

I do not know a way to view Hazelcast cache logs

##### **Reproduce the error**

Clone the [Github](https://github.com/pavankjadda/Kubernetes-SpringCloudStream-Kafka-Docker) repository and deploy it

##### **JHipster Version(s)**
JHipster release 4.14.1

##### **Browsers and Operating System**
macOS High Sierra, Chrome

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment] 2018-03-15 14:48
You can use the Hazelcast management center, we provide a Docker Compose file for this, have a look at our Hazelcast documentation

**Comment by jdubois** [comment] 2018-03-15 14:48
I'm closing this as this is not a bug, and next time please follow the guidelines

**Closed by jdubois** 2018-03-15 14:48 UTC
