### ISSUE TITLE
Application fails to render start page for a fresh React project on IE11

### ISSUE THREAD

**Issue by hirro** [jhipster/generator-jhipster#8250] opened 2018-09-07 12:57 UTC
##### **Overview of the issue**

I had some problems with my application not rendering at all in IE11. 
After some troubleshooting I generated a blank React project in jHipster but I still get this problem.
The console error in IE reads:

> SCRIPT5009: 'Symbol' is undefined
  vendors.chunk.js (84301,60)

**vendors.chunk.js**
> 	84285: /***/ "./node_modules/react-jhipster/lib/src/language/translate.js":
> 	84286: /*!*******************************************************************!*\
> 	84287:   !*** ./node_modules/react-jhipster/lib/src/language/translate.js ***!
> 	84288:   \*******************************************************************/
> 	84289: /*! no static exports found */
> 	84290: /***/ (function(module, exports, __webpack_require__) {
> 	84291: 
> 	84292: "use strict";
> 	84293: 
> 	84294: var __extends = (this && this.__extends) || (function () {
> 	84295:     var extendStatics = Object.setPrototypeOf ||
> 	84296:         ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
> 	84297:         function (d, b) { for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p]; };
> 	84298:     return function (d, b) {
> 	84299:         extendStatics(d, b);
> 	84300:         function __() { this.constructor = d; }
> 	84301:         d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
> 	84302:     };
> 	84303: })();
> 	84304: Object.defineProperty(exports, "__esModule", { value: true });
> 	84305: var React = __webpack_require__(/*! react */ "./node_modules/react/index.js");
> 	84306: var get = __webpack_require__(/*! lodash.get */ "./node_modules/lodash.get/index.js");
> 	84307: var sanitizeHtml = __webpack_require__(/*! sanitize-html */ "./node_modules/sanitize-html/dist/index.js");
> 	84308: var translator_context_1 = __webpack_require__(/*! ./translator-context */ "./node_modules/react-jhipster/lib/src/language/translator-context.js");
> 	84309: var REACT_ELEMENT = Symbol.for('react.element');

##### **Motivation for or Use Case**

According to the jHipster page IE11 is supported.

##### **Reproduce the error**

Generate project with settings in the provided .yo-rc file.
Start a browser (did it using Vagrant and https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/)

##### **Related issues**

I didn't find any React related issues.

##### **Suggest a Fix**

I have/am tried/trying but not too familiar with troubleshooting polyfills and webpack.

##### **JHipster Version(s)**

5.3.0

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

Using JHipster version installed locally in current project's node_modules
Executing jhipster:info
Options: 
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
jhipster@0.0.0 /home/jiar/tmp/jhipster-react-empty
└── generator-jhipster@5.3.0 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "5.3.0",
    "applicationType": "monolith",
    "baseName": "jhipster",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "clientFramework": "react",
    "useSass": true,
    "clientPackageManager": "npm",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ]
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

openjdk version "1.8.0_181"
OpenJDK Runtime Environment (build 1.8.0_181-8u181-b13-0ubuntu0.18.04.1-b13)
OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)

git version 2.17.1

node: v8.11.3

npm: 6.4.1

yeoman: 2.0.2

yarn: 1.6.0

Docker version 18.05.0-ce, build f150324

docker-compose version 1.17.0, build ac53b73

Congratulations, JHipster execution is complete!

##### **Browsers and Operating System**
Server on PopOS
Browser Windows 10 and IE11

- [ x ] Checking this box is mandatory (this is just to show you read everything)

**Comment by deepu105** [comment] 2018-09-07 13:18
We officially only support the evergreen browsers(Chrome, FF, Opera, Edge etc) also most of the core team is on Mac or Linux hence difficult for us to test this. If you have found a solution please do PR. Mostly issues like these can be solved by adding the required polyfill

**Comment by jdubois** [comment] 2018-09-07 13:26
Closing as we can't support IE 11 anymore, but indeed this should be solved easily with a polyfill -> if anyone can do this, a PR is much welcomed (and will probably be merged without testing, so please test before!)

**Comment by hirro** [comment] 2018-09-07 13:26
Ok! 
I don't get why anyone would like to use IE11 when Edge is around anyway.
But looking on the React document pages, IE11 is supported.

**Closed by jdubois** 2018-09-07 13:26 UTC

**Comment by jmsuhy** [comment] 2018-09-13 00:08
Government agencies are usually far behind and many are still using IE11.  Not having it work with IE11 means you may have just made it much harder for government agencies or contractors building apps for the agencies to adopt jhipster.

**Comment by mraible** [comment] 2018-09-13 00:32
IE is a dead browser with no support or security patches from Microsoft. It’s risky to use it. From https://medium.com/@burger.neal/the-end-of-life-of-internet-explorer-11-12736f9ff75f:

> As a developer, we tend to bend to the wishes of our customer. In this case, this is actually causing the problem.
> 
> It is your job to also inform your client/customer that the decision to support IE 11 is a very short-sighted one.

**Comment by jmsuhy** [comment] 2018-09-13 02:44
I completely agree with you Matt.   Also, just an FYI - a quick fix to the issue is to include babel-polyfill in you dependencies then add the following to the top of your index.tsx file.  (You can tweak it to include only what you need in the package too).
// tslint:disable-next-line
import 'babel-polyfill';

**Comment by deepu105** [comment] 2018-09-13 06:34
I would rather just document it. As we officially don't and will not
support IE. So anyone who wants to can add the code from docs. Will you be
willing to contribute the docs?

**Comment by deepu105** [comment] 2018-09-13 06:34
It can be in the generated readme file for the project

**Comment by jdubois** [comment] 2018-09-13 09:56
For me that should be a "tip" in our tips and tricks pages. That should help many people, and is quick to write.

**Comment by garajo** [comment] 2019-01-24 17:46
These polyfills resolve the baseline generated React application.
```
import 'core-js/fn/symbol';
import 'core-js/fn/promise';
import 'core-js/fn/object';
import 'core-js/fn/string';
import 'core-js/fn/array';
```
and in webpack\webpack.common.js 
`entry: ['.polyfills.ts']`

I'd be glad to do a PR, if someone can point out where to change this.

**Comment by deepu105** [comment] 2019-01-24 17:50
@garajo you are welcome to add a tip on our docs site https://github.com/jhipster/jhipster.github.io/tree/master/tips
