### ISSUE TITLE
docker_jhipster-registry_1 exited with code 1

### ISSUE THREAD

**Issue by bahadyr** [jhipster/generator-jhipster#8960] opened 2018-12-16 10:59 UTC
##### **Overview of the issue**

docker_jhipster-registry_1 exited with code 1 

##### **Motivation for or Use Case**

not working as expected and described in the documentation https://www.jhipster.tech/jhipster-registry/ 'Using Docker'.

##### **Reproduce the error**

1. Create docker machine (windows OS)
2. create folders gw, ms, docker in some folder
3. generate using jhipster gateway in gw, microservice in ms and docker compose files in docker folders
4. run 'docker-compose up -d' in docker folder

or just follow below command in docker folder (as described in documentation)
1. docker-compose -f jhipster-registry.yml up

##### **JHipster Version(s)**

v5.7.1

##### **JHipster configuration**

$ jhipster info
INFO! Using JHipster version installed globally
INFO! Executing jhipster:info
INFO! Options: from-cli: true
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
C:\dev\mscheck4\docker
`-- (empty)

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "appsFolders": [
      "gw",
      "ms",
      "ua"
    ],
    "directoryPath": "../",
    "gatewayType": "zuul",
    "clusteredDbApps": [],
    "monitoring": "no",
    "serviceDiscoveryType": "eureka",
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl"
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_191"
Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.191-b12, mixed mode)

git version 2.9.0.windows.1

node: v8.12.0

npm: 6.4.1

yeoman: 2.0.5

yarn: 1.10.1

Docker version 18.03.0-ce, build 0520e24302

docker-compose version 1.20.1, build 5d8c71b2

INFO! Congratulations, JHipster execution is complete!

##### **Browsers and Operating System**

Windows 10 Home

-   [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by bahadyr** [comment] 2018-12-16 11:05
Exception 

$ docker-compose -f jhipster-registry.yml up
Creating network "docker_default" with the default driver
Creating docker_jhipster-registry_1 ... done
Attaching to docker_jhipster-registry_1
jhipster-registry_1  | Picked up _JAVA_OPTIONS: -Xmx512m -Xms256m
jhipster-registry_1  |
jhipster-registry_1  |         ██╗ ██╗   ██╗ ████████╗ ███████╗   ██████╗ ████████╗ ████████╗ ███████╗
jhipster-registry_1  |         ██║ ██║   ██║ ╚══██╔══╝ ██╔═══██╗ ██╔════╝ ╚══██╔══╝ ██╔═════╝ ██╔═══██╗
jhipster-registry_1  |         ██║ ████████║    ██║    ███████╔╝ ╚█████╗     ██║    ██████╗   ███████╔╝
jhipster-registry_1  |   ██╗   ██║ ██╔═══██║    ██║    ██╔════╝   ╚═══██╗    ██║    ██╔═══╝   ██╔══██║
jhipster-registry_1  |   ╚██████╔╝ ██║   ██║ ████████╗ ██║       ██████╔╝    ██║    ████████╗ ██║  ╚██╗
jhipster-registry_1  |    ╚═════╝  ╚═╝   ╚═╝ ╚═══════╝ ╚═╝       ╚═════╝     ╚═╝    ╚═══════╝ ╚═╝   ╚═╝
jhipster-registry_1  |
jhipster-registry_1  | :: JHipster Registry :: Running Spring Boot 2.0.6.RELEASE ::
jhipster-registry_1  | :: https://www.jhipster.tech ::
jhipster-registry_1  |
jhipster-registry_1  | 2018-12-16 10:35:24.364  INFO 1 --- [           main] i.g.j.registry.JHipsterRegistryApp       : The following profiles are active: composite,dev,swagger,uaa
jhipster-registry_1  | 2018-12-16 10:35:34.279  WARN 1 --- [           main] c.n.c.sources.URLConfigurationSource     : No URLs will be polled as dynamic configuration sources.
jhipster-registry_1  | 2018-12-16 10:35:38.726  INFO 1 --- [           main] i.g.j.registry.config.WebConfigurer      : Web application configuration, using profiles: composite
jhipster-registry_1  | 2018-12-16 10:35:38.750  INFO 1 --- [           main] i.g.j.registry.config.WebConfigurer      : Web application fully configured
jhipster-registry_1  | 2018-12-16 10:35:39.303  INFO 1 --- [           main] i.g.j.r.security.jwt.TokenProvider       : The JWT key used is not Base64-encoded. We recommend using the `jhipster.security.authentication.jwt.base64-secret` key for optimum security.
jhipster-registry_1  | 2018-12-16 10:35:39.308 ERROR 1 --- [           main] i.g.j.r.security.jwt.TokenProvider       :
jhipster-registry_1  | ----------------------------------------------------------
jhipster-registry_1  | Your JWT secret key is not set up, you will not be able to log into the JHipster.
jhipster-registry_1  | Please read the documentation at https://www.jhipster.tech/jhipster-registry/
jhipster-registry_1  | ----------------------------------------------------------
jhipster-registry_1  | 2018-12-16 10:35:39.310  WARN 1 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'userJWTController' defined in URL [jar:file:/jhipster-registry.war!/WEB-INF/classes!/io/github/jhipster/registry/web/rest/UserJWTController.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'tokenProvider': Invocation of init method failed; nested exception is java.lang.RuntimeException: No JWT secret key is configured, the application cannot start.
jhipster-registry_1  | 2018-12-16 10:35:39.388 ERROR 1 --- [           main] o.s.boot.SpringApplication               : Application run failed
jhipster-registry_1  |
jhipster-registry_1  | org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'userJWTController' defined in URL [jar:file:/jhipster-registry.war!/WEB-INF/classes!/io/github/jhipster/registry/web/rest/UserJWTController.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'tokenProvider': Invocation of init method failed; nested exception is java.lang.RuntimeException: No JWT secret key is configured, the application cannot start.
jhipster-registry_1  |  at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:733)
jhipster-registry_1  |  at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:198)
jhipster-registry_1  |  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1266)
jhipster-registry_1  |  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1123)
jhipster-registry_1  |  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:535)
jhipster-registry_1  |  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:495)
jhipster-registry_1  |  at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:317)
jhipster-registry_1  |  at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
jhipster-registry_1  |  at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:315)
jhipster-registry_1  |  at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
jhipster-registry_1  |  at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:759)
jhipster-registry_1  |  at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867)
jhipster-registry_1  |  at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:548)
jhipster-registry_1  |  at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140)
jhipster-registry_1  |  at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754)
jhipster-registry_1  |  at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:386)
jhipster-registry_1  |  at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
jhipster-registry_1  |  at io.github.jhipster.registry.JHipsterRegistryApp.main(JHipsterRegistryApp.java:72)
jhipster-registry_1  |  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
jhipster-registry_1  |  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
jhipster-registry_1  |  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
jhipster-registry_1  |  at java.lang.reflect.Method.invoke(Method.java:498)
jhipster-registry_1  |  at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
jhipster-registry_1  |  at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
jhipster-registry_1  |  at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
jhipster-registry_1  |  at org.springframework.boot.loader.WarLauncher.main(WarLauncher.java:58)
jhipster-registry_1  | Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'tokenProvider': Invocation of init method failed; nested exception is java.lang.RuntimeException: No JWT secret key is configured, the application cannot start.
jhipster-registry_1  |  at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:139)
jhipster-registry_1  |  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:416)
jhipster-registry_1  |  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1686)
jhipster-registry_1  |  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:573)
jhipster-registry_1  |  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:495)
jhipster-registry_1  |  at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:317)
jhipster-registry_1  |  at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
jhipster-registry_1  |  at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:315)
jhipster-registry_1  |  at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
jhipster-registry_1  |  at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:251)
jhipster-registry_1  |  at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1135)
jhipster-registry_1  |  at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1062)
jhipster-registry_1  |  at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:819)
jhipster-registry_1  |  at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:725)
jhipster-registry_1  |  ... 25 common frames omitted
jhipster-registry_1  | Caused by: java.lang.RuntimeException: No JWT secret key is configured, the application cannot start.
jhipster-registry_1  |  at io.github.jhipster.registry.security.jwt.TokenProvider.init(TokenProvider.java:61)
jhipster-registry_1  |  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
jhipster-registry_1  |  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
jhipster-registry_1  |  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
jhipster-registry_1  |  at java.lang.reflect.Method.invoke(Method.java:498)
jhipster-registry_1  |  at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:366)
jhipster-registry_1  |  at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:309)
jhipster-registry_1  |  at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:136)
jhipster-registry_1  |  ... 38 common frames omitted
jhipster-registry_1  |
docker_jhipster-registry_1 exited with code 1

**Comment by ruddell** [comment] 2018-12-16 17:54
I could not reproduce the issue.  Did you customize the config that is loaded by the `jhipster-registry` docker image?  By default it should load from the volume declared in the docker-compose file, which contains the `jhipster.security.authentication.jwt.base64-secret`

On a side note, this config value should not be required for UAA architectures.

**Comment by bahadyr** [comment] 2018-12-16 18:12
I did not customize any files. Right after creating gateway, microservice and docker-compose files I run command 'docker-compose up -d'.

**Comment by ruddell** [comment] 2018-12-16 18:33
Are you sure the volumes are being mounted correctly?  Is your project under the `c:\Users` directory?  I've heard of issues with docker volumes under other paths.

You can try [changing the ENV variables](https://github.com/jhipster/jhipster-sample-app-gateway/blob/master/src/main/docker/jhipster-registry.yml#L16-L20) in `jhipster-registry.yml` to connect to the remote sample config instead of the sample config from the volume.  If that works, it's definitely an issue with your volume config.

**Comment by bahadyr** [comment] 2018-12-16 19:04
@ruddell Thanks you so much for help. Creating project inside a folder in user directory of Windows solved the issue. No any changes required anywhere else.

**Comment by ruddell** [comment] 2018-12-16 19:18
Glad to help.  This is documented in the yellow warning box so I'm closing this issue https://www.jhipster.tech/docker-compose/#-prerequisites

**Closed by ruddell** 2018-12-16 19:18 UTC
