### ISSUE TITLE
Make joda time optional

### ISSUE THREAD

**Issue by xvitcoder** [jhipster/generator-jhipster#1161] opened 2015-02-17 11:40 UTC
It would be nice to have the usage of joda-time optional, cause not everybody use it.

**Comment by rasheedamir** [comment] 2015-02-17 12:47
For Java 8 it can be made optional but what alternatives do we have for joda time before Java 8?

**Comment by gzsombor** [comment] 2015-02-17 12:52
This is a duplicate of https://github.com/jhipster/generator-jhipster/issues/1161

**Comment by jdubois** [comment] 2015-02-17 12:57
Yes this is a duplicate

**Closed by jdubois** 2015-02-17 12:57 UTC

**Comment by xvitcoder** [comment] 2015-02-17 13:31
Yes, it could be done alternatives just for Java 8, as most of us use Java 8. If Java 7 s selected then the option for using joda-time can be skipped.
