### ISSUE TITLE
Integrationtest fails with relationship OneToOne

### ISSUE THREAD

**Issue by bornf** [jhipster/generator-jhipster#9198] opened 2019-02-05 15:09 UTC
##### **Overview of the issue**

After importing this jdl to create a fresh application, the `./mnvw test` command fails

```
application {
  config {
    baseName entitytest,
    applicationType monolith,
    packageName de.jhtest,
    authenticationType jwt,
    buildTool maven,
    databaseType sql,
    devDatabaseType h2Disk,
    prodDatabaseType mysql,
    cacheProvider ehcache,
    enableHibernateCache true,
    clientFramework angularX,
    useSass true,
    clientPackageManager npm,
    enableTranslation true,
    nativeLanguage de,
    languages [en, de],
    enableSwaggerCodegen true,
    testFrameworks [protractor],
    skipUserManagement false
  }

  entities *
}

entity AEntity {
    aname String
}

entity BEntity {
    bname String unique
}
relationship OneToOne {
    AEntity to BEntity
}

service all with serviceClass
filter all
```
the stacktrace is very long....

```
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Infinite recursion (StackOverflowError) (through reference chain: de.jhtest.domain.AEntity["bentity"]->de.jhtest.domain.BEntity["aentity"]->de.jhtest.domain.AEntity["bentity"]->de.jhtest.domain.BEntity["aentity"]->de.jhtest.domain.AEntity["bentity"]->de.jhtest.domain.BEntity["aentity"]->de.jhtest.domain.AEntity["bentity"]->de.jhtest.domain.BEntity["aentity"]->de.jhtest.domain.AEntity["bentity"]->de.jhtest.domain.BEntity["aentity"]->de.jhtest.domain.AEntity["bentity"]->de.jhtest.domain.BEntity["aentity"]->de.jhtest.domain.AEntity["bentity"]->de.jhtest.domain.BEntity["aentity"]->de.jhtest.domain.AEntity["bentity"]->de.jhtest.domain.BEntity["aentity"]->de.jhtest.domain.AEntity["bentity"]->de.jhtest.domain.BEntity["aentity"]->de.jhtest.domain.AEntity["bentity"]->de.jhtest.domain.BEntity["aentity"]->de.jhtest.domain.AEntity["bentity"]->de.jhtest.domain.BEntity["aentity"]->de.jhtest.domain.AEntity["bentity"]->de.jhtest.domain.BEntity["aentity"]->de.jhtest.domain.AEntity["bentity"]->de.jhtest.domain.BEntity["aentity"]->de.jhtest.domain.AEntity["bentity"]->de.jhtest.domain.BEntity["aentity"]->de.jhtest.domain.AEntity["bentity"]->de.jhtest.domain.BEntity["aentity"]->de.jhtest.domain.AEntity["bentity"]->de.jhtest.domain.BEntity["aentity"]->de.jhtest.domain.AEntity["bentity"]->de.jhtest.domain.BEntity["ae


[ERROR] Tests run: 13, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1.397 s <<< FAILURE! - in de.jhtest.web.rest.BEntityResourceIntTest
[ERROR] getAllBEntitiesByAEntityIsEqualToSomething(de.jhtest.web.rest.BEntityResourceIntTest)  Time elapsed: 0.45 s  <<< FAILURE!
java.lang.AssertionError: Content type expected:<application/json;charset=UTF-8> but was:<application/problem+json>
	at de.jhtest.web.rest.BEntityResourceIntTest.defaultBEntityShouldBeFound(BEntityResourceIntTest.java:236)
	at de.jhtest.web.rest.BEntityResourceIntTest.getAllBEntitiesByAEntityIsEqualToSomething(BEntityResourceIntTest.java:224)

```

##### **Motivation for or Use Case**

inetgration test fails

##### **JHipster Version(s)**

5.8.1

##### **JHipster Version(s)**

```
entitytest@0.0.0 /home/alexander/programmierung/java/vsc-projects/uniqueTest
└── generator-jhipster@5.8.1 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "enableHibernateCache": true,
    "enableSwaggerCodegen": true,
    "enableTranslation": true,
    "jhiPrefix": "jhi",
    "languages": [
      "en",
      "de"
    ],
    "messageBroker": false,
    "nativeLanguage": "de",
    "packageName": "de.jhtest",
    "packageFolder": "de/jhtest",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "serviceDiscoveryType": false,
    "skipClient": false,
    "skipServer": false,
    "testFrameworks": [
      "protractor"
    ],
    "websocket": false,
    "baseName": "entitytest",
    "applicationType": "monolith",
    "authenticationType": "jwt",
    "buildTool": "maven",
    "cacheProvider": "ehcache",
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "npm",
    "skipUserManagement": false,
    "jhipsterVersion": "5.8.1",
    "serverPort": "8080",
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": []
  },
  "entities": [
    "AEntity",
    "BEntity"
  ]
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity AEntity {
  aname String
}
entity BEntity {
  bname String unique
}
relationship OneToOne {
  AEntity{bEntity} to BEntity{aEntity}
}

service AEntity, BEntity with serviceClass
filter AEntity, BEntity

</pre>
</details>

##### **Environment and Tools**

openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-8u191-b12-2ubuntu0.18.04.1-b12)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)

git version 2.17.1

node: v8.10.0

npm: 6.7.0

yeoman: 2.0.5

yarn: 1.9.4

Docker version 18.06.1-ce, build e68fc7a

docker-compose version 1.20.1, build 5d8c71b

##### **Browsers and Operating System**

-   [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment] 2019-02-06 22:40
I'm not sure it's a bug. It's probably because you didn't specify the owner of the relationship.
For example, can you try instead :
```
relationship OneToOne {
    AEntity{BEntity(bname)} to BEntity
}
```

**Comment by pascalgrimaud** [comment] 2019-02-06 22:41
Ping @MathieuAA, if you can confirm my analyze

**Comment by pascalgrimaud** [comment] 2019-02-07 05:48
Tested manually, and you need to define the owner of the relationship. Otherwise, it will result in a resursive loop during Integration tests.

I'll let give you a try.
Closing this, as it is not a bug.

**Comment by bornf** [comment] 2019-02-07 08:50
> I'm not sure it's a bug. It's probably because you didn't specify the owner of the relationship.
> For example, can you try instead :
> 
> ```
> relationship OneToOne {
>     AEntity{BEntity(bname)} to BEntity
> }
> ```

Should this mistake not be intercepted by the jdl syntax?

**Comment by bornf** [comment] 2019-02-07 09:08
for the sake of completeness - this is valid jdl syntax too:

```
entity A {
    aname String
}

entity B {
    bname String
}

relationship OneToOne {
    A{B} to B
}
```

Both the integration test and the web application do not work ...

**Comment by clement26695** [comment] 2019-02-07 09:47
I think the second syntax you mentioned is related to #8446

**Comment by pvliss** [comment] 2019-02-07 15:38
Hello @pascalgrimaud. I had a look at this one and I believe that @bornf  is right in that JDL importer should handle the missing relationship name automatically, i.e the following declarations should all produce the same code and integration tests should not fail:
```
relationship OneToOne {
    AEntity to BEntity
}
```
```
relationship OneToOne {
    AEntity{BEntity} to BEntity
}
```
```
relationship OneToOne {
    AEntity{BEntity(id)} to BEntity
}
```
Also please note that for the first sample the `@JsonIgnore` added to `BEntity` for `AEntity` seems to be ignored by Jackson hence the infinite recursion.

If you don't mind please re-open this one and I will investigate further and provide a fix PR at jhipster core if needed. Thanks

**Comment by pascalgrimaud** [comment] 2019-02-07 15:40
Thanks a lot @pvliss 
I'll follow your PR to understand better the issue.

**Comment by pvliss** [comment] 2019-02-07 19:52
@pascalgrimaud So according to the docs the following syntax is valid and declares a **bi-directional** relationship:
```
relationship OneToOne {
    AEntity to BEntity
}
```
JHipster generates the proper code but for some reason `@JsonIgnore' is not taken into account by Jackson and an infinite loop is caused.

The following are equivalent(as `id` is the default display field) and declare a **unidirectional** relationship:
```
relationship OneToOne {
    AEntity{BEntity} to BEntity
}
```
```
```

**Comment by pascalgrimaud** [comment] 2019-02-07 20:02
There are some discussion about that but I don't remember in details because I'm not expert with JDL.

If we don't find a fix, I suggest to add at least documentation.

**Comment by pvliss** [comment] 2019-02-07 22:40
OK, so in my investigation the problem is that indeed Jackson ignores the `@JsonIgnore` annotation on the field and the reason is that the default visibility for fields is set to public only. See also [here](https://github.com/FasterXML/jackson-databind/blob/74b90a4a8f5fb0655779ece94b15dafa37716ef5/src/main/java/com/fasterxml/jackson/databind/introspect/VisibilityChecker.java#L169).

It is currently very difficult to change the default settings without also completely overriding/discarding the default auto-configuration done by Spring Boot as explained in the [docs](https://docs.spring.io/spring-boot/docs/current/reference/html/howto-spring-mvc.html#howto-customize-the-jackson-objectmapper). It is not possible to do using an `Jackson2ObjectMapperBuilderCustomizer` and using a `Jackson2ObjectMapperBuilder` will discard all auto-configuration and all of it needs to be re-done.

It seems that this is now possible with SB 2.1, see [here](https://github.com/FasterXML/jackson-databind/blob/74b90a4a8f5fb0655779ece94b15dafa37716ef5/src/main/java/com/fasterxml/jackson/databind/introspect/VisibilityChecker.java#L169) and moreover can be done in the configuration.

The current workaround is to place the `@JsonIgnore` to the getter instead of the field and everything will work as expected.

As it would be too much work to fully re-configure Jackson properly I believe we can wait for SB 2.1. 
Another possible solution would be the use of [Jackson MixIn Annotations](https://github.com/FasterXML/jackson-docs/wiki/JacksonMixInAnnotations) but again not sure if it is worth since update to SB 2.1 is close.

Exploring the use of `@JsonManagedReference` and `@JsonBackReference` would probably worth the effort as it maps the use case of entity relationships more closely

**Comment by pvliss** [comment] 2019-02-09 08:33
@pascalgrimaud So I just had another look at this and did a few more tests as it will take a while for 6.x  with SB 2.1 to be released.

Any of the following solutions will work for 5.x:
1. Modify entity generator to and move Jackson annotations from fields to the getters and they will be picked up by Jackson by defaut. Actually Jackson currently works with the getters/setters instead of the the fields.
2. Modify entity generator to add a `@JsonAutoDetect` annotation at the class level of each entity, e.g:
```java
@Entity
@Table(name = "b_entity")
@Cache(usage = CacheConcurrencyStrategy.NONSTRICT_READ_WRITE)
@JsonAutoDetect( fieldVisibility = ANY, getterVisibility = NONE, setterVisibility = NONE, isGetterVisibility = NONE, creatorVisibility = NONE)
public class BEntity implements Serializable {
...
}
```
3. Use [Jackson mixins](https://github.com/FasterXML/jackson-docs/wiki/JacksonMixInAnnotations) and customize Jackson builder within `server/config/JacksonConfiguration` for each entity. e.g:
```java
@Configuration
public class JacksonConfiguration {
    ...
    @Bean
    Jackson2ObjectMapperBuilderCustomizer jhiJackson2ObjectMapperBuilderCustomizer() {
        return builder -> {
            builder.mixIn(BEntity.class, EntityMixin.class);
            builder.mixIn(AEntity.class, EntityMixin.class);
        };
    }

    @JsonAutoDetect( fieldVisibility = ANY, getterVisibility = NONE, setterVisibility = NONE, isGetterVisibility = NONE, creatorVisibility = NONE)
    public static class EntityMixin {}

}
```
**NOTE:** I tried to apply mixin on the `@Entity` annotation to avoid declaring for each entity class separately but that does not work.

Solution 1 will go against the current usage where all annotations(JPA, Validation, etc.) are on the fields and might create confusion. 
Solution 3 will be more complicated to code as we will need a needle in `JacksonConfiguration` and have the entity generator modify it for each entity(similar to what happens with `CacheConfiguration`)

I believe that solution 2 is better and simpler for now. 

For version 6.x and SB 2.1 all the solutions outlined above will also work plus we could switch to [configuration](https://github.com/spring-projects/spring-booT/wiki/Spring-Boot-2.1-Release-Notes#miscellaneous)

I can create a PR if you wish

Also I would recommend to switch from using `@JsonIgnore' to `@JsonManagedReference` and `@JsonBackReference` but that would be best done on a separate PR.

So what do you think?

**Comment by pascalgrimaud** [comment] 2019-02-09 08:39
I think we should focus on v6 with SB2.1
Don't push too much effort on code which will be outdated in few weeks. 

As you mentionned different solutions here, the end-user can already manually apply it.

**Comment by pascalgrimaud** [comment] 2019-02-09 08:40
And thanks again for all your last contributions and help to the projects, @pvliss

**Comment by pvliss** [comment] 2019-02-09 09:04
> I think we should focus on v6 with SB2.1
> Don't push too much effort on code which will be outdated in few weeks.
> 
> As you mentionned different solutions here, the end-user can already manually apply it.

OK, cool

> And thanks again for all your last contributions and help to the projects, @pvliss
You are welcome and sorry for the issues caused with jdl import

**Comment by jdubois** [comment] 2019-02-27 10:53
Closing as according to the comment this is solved.

**Closed by jdubois** 2019-02-27 10:53 UTC
Labels: JDL, needs-reproduction
