### ISSUE TITLE
Cannot update jhipster project from 2.6 to 2.9.2

### ISSUE THREAD

**Issue by uclesn** [jhipster/generator-jhipster#1437] opened 2015-05-03 20:31 UTC
I updated the jhipster generator to 2.9.2 but when I tried to update my project it does not seem to update the files. Everything stays the same basically. I noticed that the package.json file shows the 2.6 generator as a dependency so I tried to change that to 2.9.2 and ran yo jhipster again but this time it didnt recognize the project and it tried to create a new one instead. Is it no possible to upgrade a 2.6 project to the latest one?

**Comment by jdubois** [comment] 2015-05-04 07:29
Yes, did you follow the doc and do a 'npm update -g generator-jhipster'? That should update your JHipster version

**Comment by jdubois** [comment] 2015-05-04 11:36
I'm closing this because this is just a npm update issue -> this is not a JHipster issue

**Closed by jdubois** 2015-05-04 11:36 UTC

**Comment by uclesn** [comment] 2015-05-04 12:50
I did npm update but I had to specify the version. I confirmed I had the new version because when I create a new Jhipster project the Grunt file shows it was created by 2.9.2.

**Comment by uclesn** [comment] 2015-05-05 03:00
I also tried this on the lastest jhipster docker image and I get the same behaviour.

**Comment by ggtools** [comment] 2015-05-07 13:24
I think the issue is caused by the introduction of elasticsearch. As the `.yo-rc.json` file generated by jHipster 2.6.0 does not contain the `searchEngine` field, jHipster does not recognize the process as an upgrade. The workaround is to add manually the following line `.yo-rc.json`:

    "searchEngine": "no",

**Comment by jdubois** [comment] 2015-05-07 13:26
Oh yes @ggtools you are correct.
As the configuration changed, the questions are asked again.

**Comment by andidev** [comment] 2015-05-07 14:03
Would be nice if new fields added to .yo-rc.json was documented in the release notes in the future. The section describing how to update your entities would be perfect for this information.

**Comment by jdubois** [comment] 2015-05-07 14:07
yes, I agree. I will at least write it in the release notes.

**Comment by uclesn** [comment] 2015-05-07 19:15
Worked like a charm. Thank you very much @ggtools. And thank you @jdubois for such an awesome generator.
