### ISSUE TITLE
Springfox: NoClassDefFoundError: com/google/common/collect/Lists

### ISSUE THREAD

**Issue by tillias** [jhipster/generator-jhipster#12611] opened 2020-09-30 18:50 UTC
##### **Overview of the issue**

When starting sample app there is following error:
```
java.lang.NoClassDefFoundError: com/google/common/collect/Lists
	at io.github.jhipster.config.apidoc.PageableParameterBuilderPlugin.apply(PageableParameterBuilderPlugin.java:96)
	at springfox.documentation.spring.web.plugins.DocumentationPluginsManager.operation(DocumentationPluginsManager.java:144)
	at springfox.documentation.spring.web.readers.operation.ApiOperationReader.read(ApiOperationReader.java:72)
	at springfox.documentation.spring.web.scanners.CachingOperationReader.lambda$new$0(CachingOperationReader.java:43)
```

##### **Motivation for or Use Case**

I don't think this is normal behavior

##### **Reproduce the error**

Generate sample app, verify that guava 19.0 is downloaded correctly

##### **JHipster Version(s)**

6.10.3
##### **JHipster configuration**

INFO! Using JHipster version installed locally in current project's node_modules
INFO! Executing jhipster:info
##### **JHipster Version(s)**

```
micatalog@0.0.1-SNAPSHOT C:\Development\Projects\microservice-catalog
`-- generator-jhipster@6.10.3 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.tillias.mcatalog",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "6.10.3",
    "applicationType": "monolith",
    "baseName": "micatalog",
    "packageName": "com.tillias.mcatalog",
    "packageFolder": "com/tillias/mcatalog",
    "serverPort": "8080",
    "authenticationType": "session",
    "cacheProvider": "no",
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "rememberMeKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "embeddableLaunchScript": false,
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "angularX",
    "clientTheme": "solar",
    "clientThemeVariant": "dark",
    "creationTimestamp": 1601488792926,
    "testFrameworks": ["cucumber"],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": ["en", "de"],
    "blueprints": [],
    "reactive": true
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_261"
Java(TM) SE Runtime Environment (build 1.8.0_261-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.261-b12, mixed mode)

git version 2.24.1.windows.2

node: v12.18.3

npm: 6.14.6

Docker version 19.03.12, build 48a66213fe

docker-compose version 1.27.2, build 18f557f9

INFO! Congratulations, JHipster execution is complete!

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by gmarziou** [comment] 2020-09-30 20:19
I reproduced the error, it seems to be related to https://github.com/springfox/springfox/issues/3256#issuecomment-683273097

**Comment by tillias** [comment] 2020-09-30 20:54
Yes, I have chosen WebFlux when generating the project

**Comment by tillias** [comment] 2020-09-30 21:02
If I change: DocumentationType.SWAGGER_2 to DocumentationType.SWAGGER_12 then error is not reproducible. I have also noticed that @EnableSwagger2WebFlux is deprecated

```
@Primary
@Profile(JHipsterConstants.SPRING_PROFILE_SWAGGER)
@Configuration
@EnableSwagger2WebFlux
public class SwaggerConfiguration {

    @Bean
    public Docket api() {
        return new Docket(DocumentationType.SWAGGER_12)
            .select()
            .apis(RequestHandlerSelectors.any())
```

**Comment by joewhite101** [comment] 2020-10-10 12:07
This is related to https://github.com/jhipster/generator-jhipster/issues/12072 

And should be resolved by the same fix. You can assign to me.

**Comment by pascalgrimaud** [comment] 2020-10-10 12:56
closing as duplicate, and delete the bounty as there is an already one, in the other ticket

**Closed by pascalgrimaud** 2020-10-10 12:56 UTC
Labels: $$ bug-bounty $$, $100, area: bug :bug:, theme: reactive ⚛️
