### ISSUE TITLE
When I am running jhipster gateway appliaction by using ./mvnw I am unable to run

### ISSUE THREAD

**Issue by sachi7038** [jhipster/generator-jhipster#21231] opened 2023-02-25 14:06 UTC
Hi Team, I created one jhipster-gateway application,
I am using open jdk 11, spring boot 2.73, and UI angular.
when I am running mvn spring-boot: run it is working fine.
But if I am running mvnw at that time I am getting below error  

[ERROR] Failed to execute goal org.springframework.boot:spring-boot-maven-plugin:2.7.3:run (default-cli) on project smbweb: Could not exec java: Cannot run program "C:\Program Files\JAVA\jdk\bin\java.exe" (in the directory "C:\Users\SachchidaNandSingh\git\smbweb"): CreateProcess error=206, The filename or extension is too long -> [Help 1]

I am unable to run the application using "mvnw" command 

Please suggest me , how I can go ahead. 

##### **Browsers and Operating System**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by gmarziou** [comment] 2023-02-25 18:17
Well your path is too long for java on Windows, this is not due to JHipster.

You could move your project to a shorter path like "C:\Projects\smbweb

**Comment by sachi7038** [comment] 2023-02-26 15:22
Thanks for your reply, i tried but still i am facing same issue.

**Comment by gmarziou** [comment] 2023-02-26 20:18
Duplicate of #18136 and #8878, you might find some hints looking at these issues.
Maybe you could you try to move your maven local repository to another place because it impacts the length of the classpath and it's located under your home directory

**Closed by gmarziou** 2023-02-26 20:18 UTC
Labels: area: triage, theme: undefined
