### ISSUE TITLE
Swagger UI for apiFirst Issue

### ISSUE THREAD

**Issue by liseri** [jhipster/generator-jhipster#6495] opened 2017-10-09 09:18 UTC
##### **Overview of the issue**
ApiFirst Testing:
`petstore api` cannot display in frontend swagger ui when custom overide method.

##### **Related issues**

1. create a new project with feature `apiFirst`
2. as `http://www.jhipster.tech/doing-api-first-development/`, copy the yml from `http://editor.swagger.io/` to `swagger/api.yml`
3. as `http://www.jhipster.tech/doing-api-first-development/`, create a new RestController, but no any override method, like that :
```
@RestController
@RequestMapping("/api/petstore")
public class PetStore implements PetApi, StoreApi, UserApi {

//    @Override
//    public ResponseEntity<List<Pet>> findPetsByStatus(@RequestParam List<String> status) {
//        return new ResponseEntity<>(
//            status.stream()
//                .distinct()
//                .map(Pet.StatusEnum::fromValue)
//                .map(statusEnum -> new Pet().id(RandomUtils.nextLong()).status(statusEnum))
//                .collect(Collectors.toList()),
//            HttpStatus.OK);
//    }
}
```
4. start the project, in frontend `http://localhost:8080/#/docs`, the item `Pet` `store` `user` is display. 

But,
5. In new RestController , add a override method,  the item `Pet` `store` `user` is no-display, like that:
```
@RestController
@RequestMapping("/api/petstore")
public class PetStore implements PetApi, StoreApi, UserApi {

    @Override
    public ResponseEntity<List<Pet>> findPetsByStatus(@RequestParam List<String> status) {
        return new ResponseEntity<>(
            status.stream()
                .distinct()
                .map(Pet.StatusEnum::fromValue)
                .map(statusEnum -> new Pet().id(RandomUtils.nextLong()).status(statusEnum))
                .collect(Collectors.toList()),
            HttpStatus.OK);
    }
}
```
##### **JHipster Version(s)**

`jhipster 4.9.0`

##### **JHipster configuration**

```
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "4.9.0",
    "baseName": "monomvn",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": true,
    "jwtSecretKey": "b1dba33e08ec32985c9e7a33a6e390e32720f254",
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ]
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

no entities

##### **Browsers and Operating System**

`win10, chrome`, with feature `mvn` `apiFirst`

- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by cbornet** [comment] 2017-10-10 16:30
@liseri you don't have the issue anymore ?

**Comment by liseri** [comment] 2017-10-11 13:20
@cbornet  Just no one responded to me for serveral days, so ... (^.^)

**Comment by cbornet** [comment] 2017-10-11 17:14
We'll have a look. Be patient !

**Comment by liseri** [comment] 2017-10-11 20:17
@cbornet Than you.

**Comment by duderoot** [comment] 2017-10-13 15:31
I am not able to reproduce the issue. I have created a project based on your specification [here](https://github.com/duderoot/jhipster6495) Also with an override in PetStore swagger is showing the complete API.
![grafik](https://user-images.githubusercontent.com/4954023/31553851-14f36ed6-b03c-11e7-9fc8-0b8decad14e9.png)

**Comment by liseri** [comment] 2017-10-14 02:14
Thank you. @duderoot . 
- I had compare my project with [your](https://github.com/duderoot/jhipster6495). The only different is the package of PetStore Controller. My package is `package com.mycompany.myapp.web.rest;`, and your is `package com.mycompany.myapp.web;`. 
- You can try as my package, and the swagger ui will be disapper

**Comment by deepu105** [comment] 2017-10-15 12:28
@cbornet I do not understand whats wrong here do you?

**Comment by duderoot** [comment] 2017-10-16 00:50
I can confirm the last comment from @liseri:

- if I want to override methods from the generated swagger source code the it dose atter in which package I put the RestController which is overriding code from Swagger:
 
  1. if I add the controller in the  `package com.mycompany.myapp.web.rest` package where also the JHipster RestController e.g. **AccountResource** are located, then, the compiled jar will have a incomplete Swagger documentation i.e. all the generated swagger endpoints are not gone be listed; see next picture<img width="1382" alt="grafik" src="https://user-images.githubusercontent.com/4954023/31590712-4be5ce90-b215-11e7-91b1-c92be991b785.png">
   2. if I add the controller in other package then ...rest e.g. `package com.mycompany.myapp.web` then the endpoints which have been generated with swagger are gone be displayed like in the picture from the previous comment.

**Interesting founding**:

- when I run case 1. from my IDE(STS) then it dose work and the swagger documentation dose contain also the endpoints generated from swagger. There is also an [issue](https://github.com/springfox/springfox/issues/1753) on springfox which is about _Spring boot with swagger can not run when package a jar_ I can't say if this something related to our issue. 
- I was also having a look at the [SwaggerConfiguration](https://github.com/jhipster/jhipster/blob/master/src/main/java/io/github/jhipster/config/apidoc/SwaggerConfiguration.java) to see if I can get a clue of the problem from there. I tip on a problem with the order of the packages or just the packages that are scan. I was trying to add `apis( RequestHandlerSelectors.any())` and to live the restriction of the api only over the regex in paths.

`Docket docket = new Docket(DocumentationType.SWAGGER_2)
            .host(jHipsterProperties.getSwagger().getHost())
            .protocols(new HashSet<>(Arrays.asList(jHipsterProperties.getSwagger().getProtocols())))
            .apiInfo(apiInfo)
            .forCodeGeneration(true)
            .directModelSubstitute(java.nio.ByteBuffer.class, String.class)
            .genericModelSubstitutes(ResponseEntity.class)
            .select()
            .apis( RequestHandlerSelectors.any())
            .paths(regex(jHipsterProperties.getSwagger().getDefaultIncludePattern()))
            .build();
        watch.stop();`

 Unfortunately no success.

**Comment by cbornet** [comment] 2017-10-18 15:40
The issue is unrelated to swagger. Set `<logger name="org.springframework.web" level="INFO"/>` in logback's config and you'll see that it comes from Spring MVC which doesn't seem to do the mapping if the implementation is not in the same package as the interface.
I don't know if it's a bug or a limitation on Spring side but we have to document this.

**Comment by liseri** [comment] 2017-10-19 06:56
@cbornet I had done some tests. 

1. Put controller into web package , it is ok.
2. Put controller into service package, it is not ok.
3. Put controller into web.rest package, it is not ok.
4. Generat swagger code into web.rest.api, and put controller into web.rest package, it is not ok.

**Comment by deepu105** [comment] 2017-11-22 21:34
@cbornet are you gonna add the docs? or shall we close this as its not a JH bug anyway

**Comment by cbornet** [comment] 2017-11-23 14:10
I'll do the docs. Thanks for reminding :sweat_smile:

**Comment by jdubois** [comment] 2017-12-05 16:51
Ping @cbornet for the docs, do you need help?

**Comment by jdubois** [comment] 2017-12-05 18:54
Closing as documentation is merged

**Closed by jdubois** 2017-12-05 18:54 UTC
Labels: documentation

**Comment by gabrox999** [comment] 2018-01-27 19:43
Hi,
I run in the same issues as @liseri and @duderoot :

I'll dit the same tests as they did:
> Put controller into web package , it is ok.
> Put controller into service package, it is not ok.
> Put controller into web.rest package, it is not ok.
> Generat swagger code into web.rest.api, and put controller into web.rest package, it is not ok.

And I also did other tests:
- moving implementation in other package result in not working endpoint
- deleting the interface and leave implementation in the rest package seams to work...

Can have something related to this "Invoker Package Name" INFO:
```
[INFO] --- swagger-codegen-maven-plugin:2.2.3:generate (default) @ jhipster-demo ---
[...]
[INFO] Invoker Package Name, originally not set, is now dervied from api package name: io.github.jhipster.application.web

```

Someone have found a solution to the problem?

Tnx.

P.S.
Please edit the documentation, the "same package" note is misleading..

**Comment by SameerNainawat** [comment] 2018-11-16 09:40
Thank you @jdubois
