### ISSUE TITLE
Dev DB is not updated when I add a new entity field with sub-generator

### ISSUE THREAD

**Issue by WhyINeedToFillUsername** [jhipster/generator-jhipster#3510] opened 2016-05-01 15:57 UTC
##### **Overview of the issue**
When adding a field to an entity with the sub-generator, it updates the existing liquibase xml changelog of that entity (XXX_added_entity_Name.xml) instead of adding a new one. This changelog is not then executed on existing db, only when recreating it.

So the db is not updated with the field, and when trying to create the entity in the application, it reports an error.

According to [Using JHipster in development](http://jhipster.github.io/development/) `Database updates`, the changelog "will be applied the next time you run your application".

##### **JHipster Version(s)** 
`3.1.0`

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 
```
{
  "generator-jhipster": {
    "jhipsterVersion": "3.1.0",
...
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "buildTool": "maven",
    "enableSocialSignIn": true,
    "rememberMeKey": "8dab5f27baaec77194f7d482be9866580412018c",
    "useSass": true,
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "cs"
    ]
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory** 
Before "yo jhipster:entity Badge":
```
{
  "relationships": [
    {
      "relationshipId": 1,
      "relationshipType": "many-to-one",
      "relationshipName": "isOfType",
      "otherEntityName": "typeOfBadge",
      "otherEntityField": "id"
    },
    {
      "relationshipId": 2,
      "relationshipType": "many-to-one",
      "relationshipName": "ownedBy",
      "otherEntityName": "user",
      "otherEntityField": "id"
    }
  ],
  "fields": [
    {
      "fieldId": 1,
      "fieldName": "earnedAt",
      "fieldType": "ZonedDateTime"
    }
  ],
  "changelogDate": "20160427120814",
  "dto": "no",
  "pagination": "no",
  "service": "no",
  "entityTableName": "badge"
}
```
After:
```
{
    "relationships": [
        {
            "relationshipId": 1,
            "relationshipType": "many-to-one",
            "relationshipName": "isOfType",
            "otherEntityName": "typeOfBadge",
            "otherEntityField": "id"
        },
        {
            "relationshipId": 2,
            "relationshipType": "many-to-one",
            "relationshipName": "ownedBy",
            "otherEntityName": "user",
            "otherEntityField": "id"
        }
    ],
    "fields": [
        {
            "fieldId": 1,
            "fieldName": "earnedAt",
            "fieldType": "ZonedDateTime"
        },
        {
            "fieldName": "avatar",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "image",
            "fieldValidateRules": [
                "maxbytes"
            ],
            "fieldValidateRulesMaxbytes": "100000"
        }
    ],
    "changelogDate": "20160427120814",
    "dto": "no",
    "service": "no",
    "entityTableName": "badge",
    "pagination": "no"
}
```

##### **Browsers and Operating System** 
Windows 7

##### **Reproduce the error** 
Run `yo jhipster:entity EntityName` on existing entity, add a new field (I've added a Blob/image). Run the app, try creating the new entity in administration.

**Comment by deepu105** [comment] 2016-05-01 16:03
This is normal, new changelogs will be applied when you restart but if an
existing changelog is updated liquibase will not recreate it unless you
delete the table. You need to use `liquibase:diff` maven goal to get that
updated. May be we will update documentation a bit more for this.

**Comment by WhyINeedToFillUsername** [comment] 2016-05-01 16:15
Ok, thanks for the info.

I'm also confused about what to do with the changelog then. I thought I'd just run something like the `liquibase:update`, which would update the db automatically. But this fails with
`[ERROR] Failed to execute goal org.liquibase:liquibase-maven-plugin:3.4.2:update (default-cli) on project tidy-up: Error setting up or running Liquibase: liquibase.exception.SetupException: classpath:config/liquibase/changelog/00000000000000_initial_schema.xml does not exist`.

The `liquibase:diff` works, it creates a changelog.xml, but is there a way how to use the changelog? It is not an SQL script, so do I have to edit the DB by hand?

**Comment by ruddell** [comment] 2016-05-01 17:23
To use the generated changelog.xml, you need to include it manually in src/main/resources/config/liquibase/master.xml. It will then run the updates on the next start.

From http://jhipster.github.io/development/

**Comment by WhyINeedToFillUsername** [comment] 2016-05-01 21:25
Cool, thanks. Not sure if I've missed it on the site or it was added later :)

**Comment by deepu105** [comment] 2016-05-02 03:00
The documentation can be improved for this

**Comment by jdubois** [comment] 2016-05-02 09:49
It's already documented at http://jhipster.github.io/development/

Closing this as it's not a bug -> @deepu105 you can improve the documentation of course, but for me that's already documented, and it's the main "development" page, so this isn't really hidden on the website

**Closed by jdubois** 2016-05-02 09:49 UTC
Labels: documentation

**Comment by AmineJa** [comment] 2017-03-30 12:22
@jdubois 
When I add an entity or attribute to an entity, the chngelog adds successfully but the doees database does not chnage
What is the solution for updating the data base

**Comment by jdubois** [comment] 2017-03-30 12:27
I'm sorry but this issue was closed more than 1 year ago... Why do you ask me personally about it?

**Comment by jdubois** [comment] 2017-03-30 12:29
Reading again https://jhipster.github.io/development/#using-a-database it looks well documented to me, please be more specific
