### ISSUE TITLE
Compilation error when generating application using jhipster 3.1.0

### ISSUE THREAD

**Issue by billy93** [jhipster/generator-jhipster#3473] opened 2016-04-26 07:28 UTC
##### **Overview of the issue**

I have an issue when generating jhipster 3.1.0 apps with mongo, i have already attach .yo.rc.json file

##### **Motivation for or Use Case** 

Because I can't start an application, there is a compilation error in MongoDBTokenStore.java file line 88 in method removeRefreshToken

Before : 
oAuth2AccessTokenRepository.delete(refreshToken); 

##### **JHipster Version(s)** 

3.1.0

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 

{
  "generator-jhipster": {
    "jhipsterVersion": "3.1.0",
    "baseName": "blog",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "oauth2",
    "hibernateCache": "no",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "mongodb",
    "devDatabaseType": "mongodb",
    "prodDatabaseType": "mongodb",
    "searchEngine": "no",
    "buildTool": "maven",
    "useSass": false,
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ]
  }
}

##### **Browsers and Operating System** 

OS : Windows 7

##### **Suggest a Fix** 

I think in MongoDBTokenStore in line 88 should be 
oAuth2RefreshTokenRepository.delete(refreshToken);

**Comment by deepu105** [comment] 2016-04-26 07:49
This is fixed in master already. duplicate of https://github.com/jhipster/generator-jhipster/issues/3436

**Closed by deepu105** 2016-04-26 07:49 UTC
