### ISSUE TITLE
Login dialog not displayed when trying to access protected page without login.

### ISSUE THREAD

**Issue by ashishjmeshram** [jhipster/generator-jhipster#10630] opened 2019-10-16 10:07 UTC
##### **Overview of the issue**

It seems that when an user is not logged in and if he tries to access the page which requires authentication, application should ideally ask him to login. But instead a blank page is shown.

Below is the stacktrace from the console.

```
webpack-internal:///./node_modules/@angular/core/fesm2015/core.js:5621 ERROR Error: Uncaught (in promise): HttpErrorResponse: {"headers":{"normalizedNames":{},"lazyUpdate":null},"status":401,"statusText":"Unauthorized","url":"http://localhost:8080/api/account","ok":false,"name":"HttpErrorResponse","message":"Http failure response for http://localhost:8080/api/account: 401 Unauthorized","error":{"type":"https://www.jhipster.tech/problem/problem-with-message","title":"Unauthorized","status":401,"detail":"Full authentication is required to access this resource","path":"/api/account","message":"error.http.401"}}
    at resolvePromise (webpack-internal:///./node_modules/zone.js/dist/zone.js:840)
    at resolvePromise (webpack-internal:///./node_modules/zone.js/dist/zone.js:799)
    at eval (webpack-internal:///./node_modules/zone.js/dist/zone.js:901)
    at ZoneDelegate.invokeTask (webpack-internal:///./node_modules/zone.js/dist/zone.js:435)
    at Object.onInvokeTask (webpack-internal:///./node_modules/@angular/core/fesm2015/core.js:35473)
    at ZoneDelegate.invokeTask (webpack-internal:///./node_modules/zone.js/dist/zone.js:434)
    at Zone.runTask (webpack-internal:///./node_modules/zone.js/dist/zone.js:202)
    at drainMicroTaskQueue (webpack-internal:///./node_modules/zone.js/dist/zone.js:615)
    at ZoneTask.invokeTask [as invoke] (webpack-internal:///./node_modules/zone.js/dist/zone.js:521)
    at invokeTask (webpack-internal:///./node_modules/zone.js/dist/zone.js:1675)
```

##### **Motivation for or Use Case**

Better user login experience.

##### **Reproduce the error**

Do not login to the jhipster application. Try to access pages like user management by directly typing the url in the browser window, a blank page is shown to user. 

http://localhost:8080/admin/user-management

##### **Related issues**

None

##### **Suggest a Fix**

Currently not known.

##### **JHipster Version(s)**

6.4.1

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "in.gov.hssc.dvscentral",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "6.4.1",
    "applicationType": "monolith",
    "baseName": "dvsCentral",
    "packageName": "in.gov.hssc.dvscentral",
    "packageFolder": "in/gov/hssc/dvscentral",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "no",
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "gradle",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "embeddableLaunchScript": false,
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "angularX",
    "clientTheme": "cosmo",
    "clientThemeVariant": "dark",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": ["en", "hi"],
    "blueprints": []
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

git version 2.17.1

node: v8.10.0

npm: 3.5.2

yeoman: 2.0.4

yarn: 1.7.0

Docker version 18.09.7, build 2d0083d

##### **Browsers and Operating System**

Linux (Ubuntu 18.04) and Chrome

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by kaidohallik** [comment] 2019-10-17 03:22
Probably can be done by improving AuthExpiredInterceptor. I believe that resolving this issue resolves also #10551.

**Comment by ashishjmeshram** [comment] 2019-10-17 03:28
> Probably can be done by improving AuthExpiredInterceptor. I believe that resolving this issue resolves also #10551.

This used to work in jhipster version 6.3.1. Not sure, why its not working in 6.4.1.

**Comment by guerreroje** [comment] 2019-10-18 15:46
The problem occurs in user-route-access-service.ts from checkLogin that must route to accessdenied and is not doing so.

**Comment by gantispam** [comment] 2019-10-22 09:22
hi. 
Same issue on JHipster 6.4.1

I thinks is an issue due to lazy loading release.

have you found a quick patch for continue development?

![image](https://user-images.githubusercontent.com/15685552/67273107-18e2ef80-f4be-11e9-9cd2-d1472a6d66e2.png)

**Comment by kaidohallik** [comment] 2019-10-22 12:04
> This used to work in jhipster version 6.3.1. Not sure, why its not working in 6.4.1.

@ashishjmeshram, great hint, that helped to find culprit. This is regression from #10383 - in `account.service.ts.ejs`:
* before, if `Promise` was used, error was caught in `identity` function
* after, if `Observable` is used, error is not caught any more in `identity` function, code was moved to Observable error chain in `tap`, but this doesn't catch error, this just executes code and error is going on

I made PR #10672 to restore logic before #10383 - now error is caught again.

**Comment by anthony-o** [comment] 2019-10-24 14:35
Here is a simple bash script to reproduce this bug.

```bash
cd /dev/shm/
rm -rf /dev/shm/myproject
mkdir myproject
cd myproject
mkdir /dev/shm/m2cache /dev/shm/yarncache
sudo tee myproject.jdl <<EOF
application {
    config {
        baseName MyProject
        clientPackageManager yarn
        jhiPrefix mp
        packageName com.mycompany.myproject
        prodDatabaseType postgresql
    }
    entities *
}

entity MyEntity {
    label String
}
EOF
JHIPSTER_VERSION=v6.4.1
sudo chown -R 1000:1000 . /dev/shm/m2cache /dev/shm/yarncache
docker run -it --rm --name jhipster -v "$(pwd):/home/jhipster/app" -v /dev/shm/m2cache:/home/jhipster/.m2 -v /dev/shm/yarncache:/home/jhipster/.cache/yarn -v "$HOME/.gitconfig:/home/jhipster/.gitconfig:ro" jhipster/jhipster:$JHIPSTER_VERSION jhipster import-jdl ./myproject.jdl --force

docker run -it --rm --name jhipster -v "$(pwd):/home/jhipster/app" -v /dev/shm/m2cache:/home/jhipster/.m2 -v /dev/shm/yarncache:/home/jhipster/.cache/yarn -p 9000:9000 -p 8080:8080 jhipster/jhipster:$JHIPSTER_VERSION bash -c "./mvnw & yarn start"
```

**Closed** 2019-11-06 09:21 UTC
Labels: area: needs-reproduction, theme: angular
