### ISSUE TITLE
`jhipster` command with main branch stuck forever when run with Windows cmd

### ISSUE THREAD

**Issue by pmverma** [jhipster/generator-jhipster#13140] opened 2020-11-25 04:54 UTC
##### **Overview of the issue**

With main branch, `jhipster` command stuck forever when run with Windows cmd 
However with GitBash, it run fine.
![image](https://user-images.githubusercontent.com/5289123/100184358-bd303480-2f0f-11eb-9dc5-f467060d0877.png)

##### **Motivation for or Use Case**

Command should not stuck forever.

##### **Reproduce the error**

In Windows 10 (with my version 20H2),

- clone `generator-jhipster`
- npm link
- run `jhipster` using windows cmd

##### **JHipster Version(s)**

current main branch

##### **Browsers and Operating System**

Node: v12.18.4
Npm: 6.14.6

-   [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by kaidohallik** [comment] 2020-11-25 06:52
Duplicate of #13138 - solution is to update `node.js` to the latest LTS version.

**Closed by kaidohallik** 2020-11-25 06:52 UTC
Labels: area: triage, theme: undefined
