### ISSUE TITLE
Cannot setup JHipster on windows 7 x64

### ISSUE THREAD

**Issue by Coccoonx** [jhipster/generator-jhipster#6200] opened 2017-08-04 17:28 UTC
##### **Overview of the issue**

I cannot install jhipster due to a failing on tabtab. 
Here is the stacktrace error.
```
error C:\Users\Coccoonx\AppData\Local\Yarn\config\global\node_modules\generator-jhipster: Command failed.
Exit code: 1
Command: C:\Windows\system32\cmd.exe
Arguments: /d /s /c tabtab install --name jhipster --auto
Directory: C:\Users\Coccoonx\AppData\Local\Yarn\config\global\node_modules\generator-jhipster
Output:
Fri, 04 Aug 2017 16:52:28 GMT tabtab:installer Installing completion script to fish directory
fs.js:640
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'C:\Users\Coccoonx\AppData\Local\Yarn\config\global\node_modules\tabtab\scripts\C:\Program Files\Git\usr\bin\bash.sh'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at fs.readFileSync (fs.js:508:33)
    at Complete.script (C:\Users\Coccoonx\AppData\Local\Yarn\config\global\node_modules\tabtab\src\complete.js:373:14)
    at Installer.writeTo (C:\Users\Coccoonx\AppData\Local\Yarn\config\global\node_modules\tabtab\src\installer.js:91:34)
    at Installer.handle (C:\Users\Coccoonx\AppData\Local\Yarn\config\global\node_modules\tabtab\src\installer.js:80:21)
    at Commands.install (C:\Users\Coccoonx\AppData\Local\Yarn\config\global\node_modules\tabtab\src\commands\index.js:75:22)
    at Object.<anonymous> (C:\Users\Coccoonx\AppData\Local\Yarn\config\global\node_modules\tabtab\src\cli.js:33:16)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this command.
```

##### **Motivation for or Use Case**

I follow installation process from jhipster official website and at end, when running `yarn global add generator-jhipster` I have an exception from tabtab.

##### **Reproduce the error**

Just running `yarn global add generator-jhipster` produce same error.

##### **Related issues**

I read something about tabtab in #6162 and #6089 but I don't see how to solve it on windows.
I can see the same stacktrace error here [#4386](https://github.com/angular/angular-cli/issues/4386), but it still on ubuntu OS.

##### **JHipster Version(s)**

Cannot have jhipster version, since installation failed.

##### **JHipster configuration**

`jhipster info` produces the same error. Then I cannot provide configuration. Cannot see `.yo-rc.json` too.

##### **Browsers and Operating System**

Windows 7 x64

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by gmarziou** [comment] 2017-08-04 18:01
Duplicate of #6162

**Closed by gmarziou** 2017-08-04 18:01 UTC

**Comment by gmarziou** [comment] 2017-08-04 18:04
Please note that we don't support Windows 7, there are other issues like #5820

**Comment by Coccoonx** [comment] 2017-08-05 16:31
oh! 
Thanks
