### ISSUE TITLE
401 errors when session expires on the server

### ISSUE THREAD

**Issue by Kwaq** [jhipster/generator-jhipster#1291] opened 2015-03-24 13:08 UTC
After session expires on the server, and 'remember me' was not selected (or token was invalidated) every request to servers is responded with 401 Unauthorized error.

In JHipster 1.x http-auth-interceptor was supporting this case. In 2.x I can't find code which would replace its functionality.  

Configuration below.

```json
{
  "generator-jhipster": {
    "baseName": "---",
    "packageName": "---",
    "packageFolder": "---",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "postgresql",
    "useCompass": true,
    "buildTool": "maven",
    "frontendBuilder": "grunt",
    "javaVersion": "8",
    "rememberMeKey": "---"
  }
}
```

**Comment by jdubois** [comment] 2015-03-24 15:33
If your session is invalided, and if you don't have the "remember me", this looks like a normal behavior to me.
Could you elaborate?

**Comment by Kwaq** [comment] 2015-03-24 19:26
I think, that in such situation user should be redirected to login page. Now he can switch views as normal - only AJAX loaded data is not fetched because of 401 error.

**Comment by jdubois** [comment] 2015-03-25 08:50
Oh sorry, I didn't understand that, you are of course correct!
Thanks for the explanation!

**Comment by aelidrissi** [comment] 2015-03-31 15:07
I had the same annoying problem with the 401 response status. My solution/workaround  was adding  
                if(!localStorageService.get('token')){
                    Auth.logout();
                }
inside app.js. Just like this:

....
.run(function ($rootScope, $location, $window, $http, $state, $translate, Auth, Principal, Language, ENV, VERSION, localStorageService) {
        $rootScope.ENV = ENV;
        $rootScope.VERSION = VERSION;
        $rootScope.$on('$stateChangeStart', function (event, toState, toStateParams) {
            $rootScope.toState = toState;
            $rootScope.toStateParams = toStateParams;

            if (Principal.isIdentityResolved()) {
                if(!localStorageService.get('token')){
                    Auth.logout();
                }
                Auth.authorize();
            }
            // Update the language
            Language.getCurrent().then(function (language) {
                $translate.use(language);
            });
        });
        
..the rest of the code intact

I hope this help! it worked for me ;)

**Comment by aelidrissi** [comment] 2015-04-01 09:15
The "solution" above is not perfect. What the user wants is to be redirected to the right page after login. Thats what the code change below is doing:

responseError: function(response) {
                if (response.status == 401){
                    var Auth = $injector.get('Auth');
                    var $state = $injector.get('$state');
                    var $rootScope = $injector.get('$rootScope');
                    var to = $rootScope.toState;
                    var params = $rootScope.toStateParams;
                    Auth.logout();
                    $rootScope.returnToState = to;
                    $rootScope.returnToStateParams = params;
                    $state.go('login');    
                }
                
                return $q.reject(response);
            }

**Comment by kbjp** [comment] 2015-04-24 09:10
Vote +1 for this issue to be fixed.

**Comment by pmdusso** [comment] 2015-05-13 13:37
I having a 401 issue also, which I don't know if is related to this one. I made a update/merge in my Gruntfile and gradle profiles because the webapp sources were not being minified (I created my project around October from last year).

This solved the minification issue, but introduced this unauthorized problem. Now after I run bootRun and grunt server, when I try to access the localhost on port 3000 I get:

> http://localhost:3000/protected/authentication_check.gif Failed to load resource: the server responded with a status of 401 (Unauthorized)
> http://localhost:3000/directives/loginFrame/loginFrame.html Failed to load resource: the server responded with a status of 401 (Unauthorized)

This does not happen always, and it's hard to reproduce. I noticed that most of the times is when the session expires. My app configuration is as follows:

```javascript
{
  "generator-jhipster": {
    "baseName": "---",
    "packageName": "---",
    "packageFolder": "---",
    "authenticationType": "token",
    "hibernateCache": "no",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "nosql",
    "devDatabaseType": "mongodb",
    "prodDatabaseType": "mongodb",
    "useCompass": true,
    "buildTool": "gradle",
    "frontendBuilder": "grunt",
    "javaVersion": "8"
  }
}
```

I'm still running on Spring Boot v1.1.7.RELEASE and Spring v4.0.7.RELEASE. Please, help get this through.

**Comment by ddewaele** [comment] 2015-06-11 16:37
+1 to have this fixed....

I tried the solution proposed by @aelidrissi  but it got stuck in an infinite loop (the login page calls api/account that returns an HTTP 401 that redirects to the login page, that .......)

I ended up with this in app.js :

```
    .factory('authInterceptor', function ($rootScope, $injector, $q, $location, localStorageService) {
        return {
            responseError: function(response) {
                // If we have an unauthorized request we redirect to the login page
                // Don't do this check on the account API to avoid infinite loop
                if (response.status == 401 && response.data.path!="/api/account"){  
                    var Auth = $injector.get('Auth');
                    var $state = $injector.get('$state');
                    var to = $rootScope.toState;
                    var params = $rootScope.toStateParams;
                    Auth.logout();
                    $rootScope.returnToState = to;
                    $rootScope.returnToStateParams = params;
                    $state.go('login');    
                }       
                return $q.reject(response);
            }
        };
    })
```

and finally push the interceptor on the httpProvider.

```
$httpProvider.interceptors.push('authInterceptor');
```

Would this be the way to go or is there a better solution ?

**Comment by jdubois** [comment] 2015-06-11 21:26
Yes, this looks good to me, can you provide a PR?

**Comment by aelidrissi** [comment] 2015-06-12 07:40
ddewaele,
I am not experiencing any loop. A little bit strange to get a 401 status with the path "/api/account".
My generator-jhipster version is 2.7.0.

**Comment by ddewaele** [comment] 2015-06-12 07:43
I was using the latest jhipster generator (2.16.0). 

I noticed that going to the login url as an anonymous users triggers an API call to "/api/account" (haven't looked at what exactly is making the call).

**Comment by jdubois** [comment] 2015-06-22 20:28
Now that the PR is merged this should be solved.
@ddewaele yes that's normal we call this endpoint to see if you are logged in or not -> if you are not (401 error), then you have the "not logged in" page

**Closed by jdubois** 2015-06-22 20:28 UTC

**Comment by spans** [comment] 2015-09-04 21:12
I came up to same problem (infinite loop) although I have the fix in my jhipster.

Funny enough I do not have the problem on windows when runing standalone but only under linux tomcat.
I have checked and logged to js console that 'response.data.path' is 'undefined' hence the infinite loop begins from first entry to application.

/api/account?cacheBuster=1441400804327 is returning 401 and then logout is called etc.

Please suggest resolution.

Thanks,Sz

**Comment by gmarziou** [comment] 2015-09-04 21:22
Similar issue was reported on [stackoverflow](http://stackoverflow.com/questions/32258457/spring-mvc-missing-variable-from-uri-named-path/32263826#32263826) check Julien's answer.

**Comment by spans** [comment] 2015-09-04 21:54
Yeah that may be tricky bit. I do not have Apache in front as in the post you suggested.
Do you have any suggestions where  it can disappear?
It must be stripped before getting back to angular/front.

**Comment by gmarziou** [comment] 2015-09-04 23:15
The only suggestion I have is to run your app in Tomcat under debugger.

**Comment by spans** [comment] 2015-09-06 21:41
Can you give me a hint which class is setting data.path, please?
I am sure this is something to do with tomcat as embedded returns the path and standalone does not.

**Comment by gmarziou** [comment] 2015-09-06 22:31
Search for classes that use `HttpServletResponse.SC_UNAUTHORIZED`, it could be in JHipster or in Spring Security.

**Comment by spans** [comment] 2015-09-08 22:10
Http401UnauthorizedEntryPoint is setting the '''SC_UNAUTHORIZED'''

And digging into sendError I have noticed that response is wrapped differently for embedded tomcat and standalone.

Embedded:
![screen shot 09-09-15 at 12 02 am](https://cloud.githubusercontent.com/assets/1579888/9748718/04f65270-5687-11e5-8af3-d3b9bd7d15b2.PNG)

standalone:
![screen shot 09-08-15 at 11 59 pm](https://cloud.githubusercontent.com/assets/1579888/9748723/10ed4b56-5687-11e5-9ff5-82db0053731e.PNG)

Where I can check that setting for that. Why the spring boot is kicking in for the standalone tomcat?
