### ISSUE TITLE
Creating an application fails

### ISSUE THREAD

**Issue by eric-pierre** [jhipster/generator-jhipster#3493] opened 2016-04-29 00:46 UTC
##### **Overview of the issue**

Following the instructions to the letter, I cannot get a sample application to build. The build appears to process correctly, until the following happens:
````
angular-mocks#1.5.2 src/main/webapp/bower_components/angular-mocks
└── angular#1.5.2

Server app generated successfully.


Client app generated successfully.

(node:2901) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
(node) v8::ObjectTemplate::Set() with non-primitive values is deprecated
(node) and will stop working in the next major release.

==== JS stack trace =========================================

Security context: 0xb790eec9fa9 <JS Object>#0#
    1: .node [module.js:568] [pc=0x344d1a77a4] (this=0x23059fdcb009 <an Object with deprecated map 0x3da12bb17be1>#1#,module=0x103c8a539fc9 <a Module with map 0x3da12bb181b9>#2#,filename=0x103c8a539fa1 <String[102]: /Users/eric/Documents/devel/app/node_modules/fsevents/lib/binding/Release/node-v48-darwin-x64/fse.node>)
    2: load [module.js:~447] [pc=0x344ce36596] (this=0x103c8a539fc9 <a Module with map 0x3da12bb181b9>#2#,filename=0x103c8a539fa1 <String[102]: /Users/eric/Documents/devel/app/node_modules/fsevents/lib/binding/Release/node-v48-darwin-x64/fse.node>)
    3: tryModuleLoad(aka tryModuleLoad) [module.js:415] [pc=0x344cc3899d] (this=0xb790ee04189 <undefined>,module=0x103c8a539fc9 <a Module with map 0x3da12bb181b9>#2#,filename=0x103c8a539fa1 <String[102]: /Users/eric/Documents/devel/app/node_modules/fsevents/lib/binding/Release/node-v48-darwin-x64/fse.node>)
    4: _load [module.js:~38 1: v8::Template::Set(v8::Local<v8::Name>, v8::Local<v8::Data>, v8::PropertyAttribute)
 2: fse::FSEvents::Initialize(v8::Local<v8::Object>)
 3: node::DLOpen(v8::FunctionCallbackInfo<v8::Value> const&)
 4: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&))
 5: v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::(anonymous namespace)::BuiltinArguments<(v8::internal::BuiltinExtraArguments)1>)
 6: v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*)
 7: 0x344cb0961b
(node) v8::ObjectTemplate::Set() with non-primitive values is deprecated
(node) and will stop working in the next major release.

==== JS stack trace =========================================

Security context: 0xb790eec9fa9 <JS Object>#0#
    1: .node [module.js:568] [pc=0x344d1a77a4] (this=0x23059fdcb009 <an Object with deprecated map 0x3da12bb17be1>#1#,module=0x103c8a539fc9 <a Module with map 0x3da12bb181b9>#2#,filename=0x103c8a539fa1 <String[102]: /Users/eric/Documents/devel/app/node_modules/fsevents/lib/binding/Release/node-v48-darwin-x64/fse.node>)
    2: load [module.js:~447] [pc=0x344ce36596] (this=0x103c8a539fc9 <a Module with map 0x3da12bb181b9>#2#,filename=0x103c8a539fa1 <String[102]: /Users/eric/Documents/devel/app/node_modules/fsevents/lib/binding/Release/node-v48-darwin-x64/fse.node>)
    3: tryModuleLoad(aka tryModuleLoad) [module.js:415] [pc=0x344cc3899d] (this=0xb790ee04189 <undefined>,module=0x103c8a539fc9 <a Module with map 0x3da12bb181b9>#2#,filename=0x103c8a539fa1 <String[102]: /Users/eric/Documents/devel/app/node_modules/fsevents/lib/binding/Release/node-v48-darwin-x64/fse.node>)
    4: _load [module.js:~381] [pc=0x344d083c35] (this=0x23059fdcafc1 <JS Function Module (SharedFunctionInfo 0x23059fd286b9)>#3#,request=0x103c8a5332f9 <String[102]: /Users/eric/Documents/devel/app/node_modules/fsevents/lib/binding/Release/node-v48-darwin-x64/fse.node>,parent=0x103c8a3dbaa1 <a Module with map 0x3da12bb181b9>#4#,isMain=0xb790ee04299 <false>)
 map 0xcfa93707bc9>#5#,require=0x103c8a3de399 <JS Function require (SharedFunctionInfo 0x23059fd593f1)>#6#,module=0x103c8a3dbaa1 <a Module with map 0x3da12bb181b9>#4#,__filename=0x103c8a3dba79 <String[65]: /Users/eric/Documents/devel/app/node_modules/fsevents/fsevents.js>,__dirname=0x103c8a3de331 <String[53]: /Users/eric/Documents/devel/app/node_modules/fsevents>)
    8: _compile [module.js:541] [pc=0x344cc40624] (this=0x103c8a3dbaa1 <a Module with map 0x3da12bb181b9>#4#,content=0x103c8a3dc609 <Very long string[3154]>#7#,filename=0x103c8a3dba79 <String[65]: /Users/eric/Documents/devel/app/node_modules/fsevents/fsevents.js>)
    9: .js [module.js:~548] [pc=0x344ce8ecdf] (this=0x23>,parent=0x103c8a0106c9 <a Module with map 0x3da12bb181b9>#20#,isMain=0xb790ee04299 <false>)
   37: require [module.js:~463] [pc=0x344cc8414b] (this=0x103c8a0106c9 <a Module with map 0x3da12bb181b9>#20#,path=0x33acd7826649 <String[9]: ./watcher>)
   38: require(aka require) [internal/module.js:20] [pc=0x344cc41f06] (this=0xb790ee04189 <undefined>,path=0x33acd7826649 <String[9]: ./watcher>)
   39: /* anonymous */ [/Users/eric/Documents/devel/app/node_modules/karma/lib/server.js:11] [pc=0x344d0805c1] (this=0x103c8a010959 <an Object with map 0xcfa93707bc9>#21#,exports=0x103c8a010959 <an Object with map 0xcfa93707bc9>#21#,require=0x103c8a010759 <JS Function require (SharedFunctionInfo 0x23059fd593f1)>#22#,module=0x103c8a0106c9 <a Module with map 0x3da12bb181b9>#20#,__filename=0x103c8a010901 <String[64]: /Users/eric/Documents/devel/app/node_modules/karma/lib/server.js>,__dirname=0x103c8a0108d9 <String[54]: /Users/eric/Documents/devel/app/node_modules/karma/lib>)
   40: _compile [module.js:541] [pc=0x344cc40624] (this=0x103c8a0106c9 <a Module with map 0x3da12bb181b9>#20#,content=0x103c8a0109b1 <Very long string[11047]>#23#,filename=0x103c8a010901 <String[64]: /Users/eric/Documents/devel/app/node_modules/karma/lib/server.js>)
2] (this=0x23059fdcafc1 <JS Function Module (SharedFunctionInfo 0x23059fd286b9)>#3#,request=0x4a308587641 <String[8]: ./server>,parent=0x103c8a0134f1 <a Module with map 0x3da12bb181b9>#24#,isMain=0xb790ee04299 <false>)
   45: require [module.js:~463] [pc=0x344cc8414b] (this=0x103c8a0134f1 <a Module with map 0x3da12bb181b9>#24#,path=0x4a308587641 <String[8]: ./server>)
   46: require(aka require) [internal/module.js:20] [pc=0x344cc41f06] (this=0xb790ee04189 <undefined>,path=0x4a308587641 <String[8]: ./server>)
   47: /* anonymous */ [/Users/eric/Documents/devel/app/node_modules/karma/lib/index.js:4] [pc=0x344d07ef42] (this=0x103c8a013701 <an Object with map 0xcfa93707bc9>#25#,exports=0x103c8a013701 <an Object with map 0xcfa93707bc9>#25#,require=0x103c8a013581 <JS Function require (SharedFunctionInfo 0x23059fd593f1)>#26#,module=0x103c8a0134f1 <a Module with map 0x3da12bb181b9>#24#,__filename=0x103c8a0136a9 <String[63]: /Users/eric/Documents/devel/app/node_modules/karma/lib/index.js>,__dirname=0x103c8a013681 <String[54]: /Users/eric/Documents/devel/app/node_modules/karma/lib>)
   48: _compile [module.js:541] [pc=0x344cc40624] (this=0x103c8a0134f1 <a Module with map 0x3da12bb181b9>#24#,content=0x103c8a013759 <String[648]\: // index module\n\nvar constants = require('./constants')\nvar Server = require('./server')\nvar runner = require('./runner')\nvar launcher = require('./launcher')\n\n// TODO: remove in 1.0\nvar oldServer = {\n  start: function (cliOptions, done) {\n    console.error('WARN `start` method is deprecated since 0.13. It will be removed in 0.14. Please use \\n' +\n      '  server = new Server(config, [done])\\n' +\n      '  server.start()\\n' +\n      'instead.')\n    var server = new Server(cliOptions, done)\n    server.start()\n  }\n}\n\nmodule.exports = {\n  VERSION: constants.VERSION,\n  Server: Server,\n  runner: runner,\n  launcher: launcher,\n  server: oldServer\n}\n>,filename=0x103c8a0136a9 <String[63]: /Users/eric/Documents/devel/app/node_modules/karma/lib/index.js>)
 [pc=0x344ce8ecdf] (this=0x23059fdcb009 <an Object with deprecated map 0x3da12bb17be1>#1#,module=0x103c8a0134f1 <a Module with map 0x3da12bb181b9>#24#,filename=0x103c8a0136a9 <String[63]: /Users/eric/Documents/devel/app/node_modules/karma/lib/index.js>)
   50: load [module.js:~447] [pc=0x344ce36596] (this=0x103c8a0134f1 <a Module with map 0x3da12bb181b9>#24#,filename=0x103c8a0136a9 <String[63]: /Users/eric/Documents/devel/app/node_modules/karma/lib/index.js>)
   51: tryModuleLoad(aka tryModuleLoad) [module.js:415] [pc=0x344cc3899d] (this=0xb790ee04189 <undefined>,module=0x103c8a0134f1 <a Module with map 0x3da12bb181b9>#24#,filename=0x103c8a0136a9 <String[63]: /Users/eric/Documents/devel/app/node_modules/karma/lib/index.js>)
   52: _load [module.js:~381] [pc=0x344cc345e2] (this=0x23059fdcafc1 <JS Function Module (SharedFunctionInfo 0x23059fd286b9)>#3#,request=0x272f85c6f899 <String[5]: karma>,parent=0x17418a1d45d1 <a Module with map 0x3da12bb181b9>#27#,isMain=0xb790ee04299 <false>)
   53: require [module.js:~463] [pc=0x344cc8414b] (this=0x17418a1d45d1 <a Module with map 0x3da12bb181b9>#27#,path=0x272f85c6f899 <String[5]: karma>)
   54: require(aka require) [internal/module.js:20] [pc=0x344cc41f06] (this=0xb790ee04189 <undefined>,path=0x272f85c6f899 <String[5]: karma>)
   55: /* anonymous */ [/Users/eric/Documents/devel/app/gulpfile.js:17] [pc=0x344ccd4469] (this=0x17418a1d4859 <an Object with map 0xcfa93707bc9>#28#,exports=0x17418a1d4859 <an Object with map 0xcfa93707bc9>#28#,require=0x17418a1d4661 <JS Function require (SharedFunctionInfo 0x23059fd593f1)>#29#,module=0x17418a1d45d1 <a Module with map 0x3da12bb181b9>#27#,__filename=0x17418a1d4811 <String[43]: /Users/eric/Documents/devel/app/gulpfile.js>,__dirname=0x17418a1d47e9 <String[31]: /Users/eric/Documents/devel/app>)
  57: .js [module.js:~548] [pc=0x344cc3a46b] (this=0x23059fdcb009 <an Object with deprecated map 0x3da12bb17be1>#1#,module=0x17418a1d45d1 <a Module with map 0x3da12bb181b9>#27#,filename=0x17418a1d4811 <String[43]: /Users/eric/Documents/devel/app/gulpfile.js>)
   58: load [module.js:~447] [pc=0x344cc38e72] (this=0x17418a1d45d1 <a Module with map 0x3da12bb181b9>#27#,filename=0x17418a1d4811 <String[43]: /Users/eric/Documents/devel/app/gulpfile.js>)
   59: tryModuleLoad(aka tryModuleLoad) [module.js:415] [pc=0x344cc3899d] (this=0xb790ee04189 <undefined>,module=0x17418a1d45d1 <a Module with map 0x3da12bb181b9>#27#,filename=0x17418a1d4811 <String[43]: /Users/eric/Documents/devel/app/gulpfile.js>)
   60: _load [module.js:~381] [pc=0x344cc345e2] (this=0x23059fdcafc1 <JS Function Module (SharedFunctionInfo 0x23059fd286b9)>#3#,request=0x17418a1d88d1 <String[43]: /Users/eric/Documents/devel/app/gulpfile.js>,parent=0x23059fdcb809 <a Module with map 0x3da12bb181b9>#31#,isMain=0xb790ee04299 <false>)
   61: require [module.js:~463] [pc=0x344cc8414b] (this=0x23059fdcb809 <a Module with map 0x3da12bb181b9>#31#,path=0x17418a1d88d1 <String[43]: /Users/eric/Documents/devel/app/gulpfile.js>)
   62: require(aka require) [internal/module.js:20] [pc=0x344cc41f06] (this=0xb790ee04189 <undefined>,path=0x17418a1d88d1 <String[43]: /Users/eric/Documents/devel/app/gulpfile.js>)
   63: handleArguments [/usr/local/lib/node_modules/gulp/bin/gulp.js:116] [pc=0x344cccea34] (this=0x17418a1d89a9 <a Liftoff with map 0x3da12bb453f1>#32#,env=0x17418a1d8959 <an Object with map 0x3da12bb49b71>#33#)
   64: /* anonymous */ [/usr/local/lib/node_modules/gulp/node_modules/liftoff/index.js:193] [pc=0x344ccab280] (this=0x17418a1d89a9 <a Liftoff with map 0x3da12bb453f1>#32#,ready=0xb790ee04231 <true>,child=0xb790eee5b91 <a process with map 0x2f4bc9c69991>#34#)
   65: /* anonymous */ [/usr/local/lib/node_modules/gulp/node_modules/flagged-respawn/index.js:17] [pc=0x344ccab655] (this=0xb790eee99f1 <JS Global Object>#35#,flags=0x17418a1d8af1 <JS Array[389]>#36#,argv=0x3f43a1f0e169 <JS Array[3]>#37#,execute=0x17418a1d8a91 <JS BoundFunction bound  (BoundTargetFunction 0x17418a1d8a11)>#38#)

==== C stack trace ===============================

 1: v8::Template::Set(v8::Local<v8::Name>, v8::Local<v8::Data>, v8::PropertyAttribute)
 2: fse::FSEvents::Initialize(v8::Local<v8::Object>)
 3: node::DLOpen(v8::FunctionCallbackInfo<v8::Value> const&)
 4: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&))
 5: v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::(anonymous namespace)::BuiltinArguments<(v8::internal::BuiltinExtraArguments)1>)
 6: v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*)
 7: 0x344cb0961b
[20:05:50] Using gulpfile ~/Documents/devel/app/gulpfile.js
[20:05:50] Starting 'install'...
[20:05:51] Starting 'wiredep:test'...
[20:05:51] Starting 'wiredep:app'...
[20:05:51] Starting 'ngconstant:dev'...
[20:05:51] 'ngconstant:dev' errored after 74 ms
[20:05:51] Error in plugin 'gulp-tslint-log'
TypeError: Path must be a string. Received null
    at assertPath (path.js:7:11)
    at Object.dirname (path.js:1324:5)
    at getFilePath (/Users/eric/Documents/devel/app/node_modules/gulp-ng-constant-fork/index.js:95:27)
    at DestroyableTransform.objectStream [as _transform] (/Users/eric/Documents/devel/app/node_modules/gulp-ng-constant-fork/index.js:60:25)
    at DestroyableTransform.Transform._read (/Users/eric/Documents/devel/app/node_modules/gulp-ng-constant-fork/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/Users/eric/Documents/devel/app/node_modules/gulp-ng-constant-fork/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/Users/eric/Documents/devel/app/node_modules/gulp-ng-constant-fork/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/Users/eric/Documents/devel/app/node_modules/gulp-ng-constant-fork/node_modules/readable-stream/lib/_stream_writable.js:227:5)
    at DestroyableTransform.Writable.write (/Users/eric/Documents/devel/app/node_modules/gulp-ng-constant-fork/node_modules/readable-stream/lib/_stream_writable.js:194:11)
    at DestroyableTransform.Writable.end (/Users/eric/Documents/devel/app/node_modules/gulp-ng-constant-fork/node_modules/readable-stream/lib/_stream_writable.js:352:10)
    at ngConstantPlugin (/Users/eric/Documents/devel/app/node_modules/gulp-ng-constant-fork/index.js:33:16)
    at Gulp.<anonymous> (/Users/eric/Documents/devel/app/gulpfile.js:154:12)
    at module.exports (/Users/eric/Documents/devel/app/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/eric/Documents/devel/app/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/eric/Documents/devel/app/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Users/eric/Documents/devel/app/node_modules/orchestrator/index.js:134:8)
[20:05:51] Error in plugin 'run-sequence'
Message:
    An error occured in task 'ngconstant:dev'.
[20:05:51] Finished 'install' after 92 ms
[20:05:51] Finished 'wiredep:test' after 165 ms
[20:05:51] Finished 'wiredep:app' after 153 ms
````

##### **Motivation for or Use Case** 

I would assume my problem is specific to my environment. I'm happy to downgrade/upgrade anything that might night downgrading/upgrading, but I would need some guidance as to what version to use.

If I try to run Maven (mvn), the application appears to start, however it never renders in the browser. I'm getting a Javascript error in the console:
````
angular.js:4547 Uncaught Error: [$injector:modulerr] Failed to instantiate module testappApp due to:
Error: [$injector:nomod] Module 'testappApp' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.5.2/$injector/nomod?p0=testappApp
    at http://127.0.0.1:8080/bower_components/angular/angular.js:68:12
    at http://127.0.0.1:8080/bower_components/angular/angular.js:2034:17
    at ensure (http://127.0.0.1:8080/bower_components/angular/angular.js:1958:38)
    at module (http://127.0.0.1:8080/bower_components/angular/angular.js:2032:14)
    at http://127.0.0.1:8080/bower_components/angular/angular.js:4524:22
    at forEach (http://127.0.0.1:8080/bower_components/angular/angular.js:321:20)
    at loadModules (http://127.0.0.1:8080/bower_components/angular/angular.js:4508:5)
    at createInjector (http://127.0.0.1:8080/bower_components/angular/angular.js:4430:19)
    at doBootstrap (http://127.0.0.1:8080/bower_components/angular/angular.js:1710:20)
    at bootstrap (http://127.0.0.1:8080/bower_components/angular/angular.js:1731:12)
http://errors.angularjs.org/1.5.2/$injector/modulerr?p0=testappApp&p1=Error…F%2F127.0.0.1%3A8080%2Fbower_components%2Fangular%2Fangular.js%3A1731%3A12)
````

##### **JHipster Version(s)** 

I'm using the latest version of JHipster, furthermore here is my setup:
java 1.8
npm: 3.8.6
node: v6.0.0
yo: 1.7.0
bower: 1.7.9
gulp: 3.9.1

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 
````
{
  "generator-jhipster": {
    "jhipsterVersion": "3.1.0",
    "baseName": "testapp",
    "packageName": "net.eric",
    "packageFolder": "net.eric",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "no",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": "no",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "useSass": false,
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ]
  }
}
````

##### **Browsers and Operating System** 

OS X 10.11.4
Chrome version 50.0.2661.86 (64-bit)

**Comment by deepu105** [comment] 2016-04-29 01:45
I think its an issue with node v6.0 we recommend using an LTS version or
5.x as it used to work well. Im closing this as its not a jhipster issue
its caused by the environment

**Comment by deepu105** [comment] 2016-04-29 01:47
Let us know if you face issue even after downgrading node

**Closed** 2016-04-29 01:46 UTC

**Comment by eric-pierre** [comment] 2016-05-02 12:56
I've downgraded node to 4.4.3 and it now works! Thanks for the suggestion.

I think you ought to update the documentation with supported versions of node, gulp etc.

cheers,
Eric

**Comment by deepu105** [comment] 2016-05-02 14:32
Our documentation asks you to use LTS versions already.

**Comment by eric-pierre** [comment] 2016-05-02 16:52
I'm sorry I must have missed that!
Thanks for your help again,
Eric
