### ISSUE TITLE
New User row created on changing email id from Keycloak user management page

### ISSUE THREAD

**Issue by caffeinecoders** [jhipster/generator-jhipster#8990] opened 2018-12-26 05:52 UTC
##### **Overview of the issue**

Issue: When I update email id via Keycloak User Management console, and login to Jhipster app, a new user row is getting generated.

##### **Reproduce the error**

Step 1:
On keycloak set following properties via admin:
Set email as username: true
User Managemed Access (Enable User Management page for all users) true
Enable User Registeration

Step 2:
Register user and login to jhipster app
Now go to User Management console and update the user email (username will also be updated)

3.
Logout and login back to app with your new email
New User row will be generated.

##### **JHipster Version(s)**

5.7.0

##### **Browsers and Operating System**

Mac OS, Chrome Browser

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment] 2019-07-01 13:45
@caffeinecoders : sorry for taking time to anwser to you.

I tried with the last JHipster 6.1.2 and didn't manage to reproduce.
Can you try with the last release of JHipster plz ?

**Comment by pascalgrimaud** [comment] 2019-07-19 05:24
I'm closing this as I couldn't reproduce in last version of JHipster 6.1.2
Feel free to comment if there is still an issue

**Closed by pascalgrimaud** 2019-07-19 05:24 UTC
Labels: area: needs-reproduction, theme: OIDC/OAuth2
