### ISSUE TITLE
"ambiguous mapping methods" when combining several relationships

### ISSUE THREAD

**Issue by andyverbunt** [jhipster/generator-jhipster#2006] opened 2015-09-13 10:28 UTC
# Overview of the issue
I have created two entities A and B backed by DTO (mapstruct). There is a many-to-many relationship between them. They both also have a many-to-one relationship with the user.

Up until creating the last relationship, everything works fine. After creating the last many-to-one relationship, I get the following error:

```
[INFO] --- maven-processor-plugin:2.2.4:process (process) @ m2m ---
[ERROR] diagnostic: /Users/andy/jhipster-m2m/src/main/java/com/m2m/web/rest/mapper/AMapper.java:18: error: Ambiguous mapping methods found for mapping property "java.lang.Long userId" to com.m2m.domain.User: com.m2m.domain.User userFromId(java.lang.Long id), com.m2m.domain.User com.m2m.web.rest.mapper.BMapper.userFromId(java.lang.Long id).
A aDTOToA(ADTO aDTO);
  ^
[ERROR] error on execute: error during compilation
```

# Motivation for or Use Case
It's a blocking issue because the container cannot start

# JHipster Version(s)
2.20.0

# JHipster configuration
Please see http://stackoverflow.com/questions/32486490/how-to-fix-ambiguous-mapping-methods
and https://github.com/andyverbunt/jhipster-m2m.git

# Entity configuration(s)
Please see http://stackoverflow.com/questions/32486490/how-to-fix-ambiguous-mapping-methods
and https://github.com/andyverbunt/jhipster-m2m.git

```
The definitions are very straightforward: For A:

{
  "relationships": [
    {
        "relationshipId": 1,
        "relationshipName": "b",
        "otherEntityName": "b",
        "relationshipType": "many-to-many",
        "otherEntityField": "id",
        "ownerSide": true
    },
    {
        "relationshipId": 2,
        "relationshipName": "user",
        "otherEntityName": "user",
        "relationshipType": "many-to-one",
        "otherEntityField": "id"
    }
],
"fields": [
    {
        "fieldId": 1,
        "fieldName": "nameA",
        "fieldType": "String"
    }
],
"changelogDate": "20150909165353",
"dto": "mapstruct",
"pagination": "no"
}
```
```
For B:

{
"relationships": [
    {
        "relationshipId": 1,
        "relationshipName": "a",
        "otherEntityName": "a",
        "relationshipType": "many-to-many",
        "ownerSide": false,
        "otherEntityRelationshipName": "b"
    },
    {
        "relationshipId": 2,
        "relationshipName": "user",
        "otherEntityName": "user",
        "relationshipType": "many-to-one",
        "otherEntityField": "id"
    }
],
"fields": [
    {
        "fieldId": 1,
        "fieldName": "nameB",
        "fieldType": "String"
    }
],
"changelogDate": "20150909165433",
"dto": "mapstruct",
"pagination": "no"
}

```
# Browsers and Operating System
N/A

# Reproduce the error
Please see http://stackoverflow.com/questions/32486490/how-to-fix-ambiguous-mapping-methods
and https://github.com/andyverbunt/jhipster-m2m.git
Just start the container

# Related issues - has a similar issue been reported before?
No

**Comment by deepu105** [comment] 2015-09-13 11:00
wow you are the first to follow thw contribution guidelines so perfectly :joy: 
:clap: :clap:

**Comment by jdubois** [comment] 2015-09-13 11:06
I can't believe it either!! First time someone follows the guidelines!

**Comment by andyverbunt** [comment] 2015-09-13 11:13
thanks ;)

let's hope someone can shed some light on the issue.

My feeling is that there might be a very easy workaround, but I'm not familiar with mapstruct

**Comment by deepu105** [comment] 2015-09-13 11:16
looks like a bug in what we generate with mapstruct. when mapstruct is trying to map userID from DTO to id in User it is seeing two methods doing that function, one in AMapper and another in BMapper

**Comment by deepu105** [comment] 2015-09-13 11:17
@andyverbunt I have posted a workaround for now in SO question, can you try that

**Comment by andyverbunt** [comment] 2015-09-13 11:17
Haven't changed anything. It looks to me that AMapper and BMapper are unrelated, so the mapping shouldn't be ambiguous. FYI, the problem only occurs in combo with the many-to-many relationship, so that must be somehow related (no pun intented ;))

**Comment by deepu105** [comment] 2015-09-13 11:19
i dont think it has anything to do with that,if im not wrong mapstruct tries to find methods from all the mappers to map things and since we have a user relation in two entities we are generating the same method twice and causes mapstruct to throw that error. but its just my guess we need to take a look at the code to be sure

**Comment by deepu105** [comment] 2015-09-13 11:21
this seems related to https://github.com/mapstruct/mapstruct/issues/213

**Comment by deepu105** [comment] 2015-09-13 11:26
seems this can be fixed by using qualifiers see section `12. Selection based on Qualifiers` of http://mapstruct.org/documentation/

**Comment by jdubois** [comment] 2015-10-01 21:28
I'm not totally sure, but I think the issue is that you have 2 relationships to User, so you have 2 `default User userFromId(Long id)` methods.
If you remove the `default User userFromId(Long id)` from the `AMapper` then it's working fine.

So I guess we should only generate one, but I'm not sure how we could know there is already one existing

**Comment by deepu105** [comment] 2015-10-02 01:24
@jdubois yes that is the issue look at my comment above reg qualifiers, that might fix this

**Comment by andyverbunt** [comment] 2015-10-02 06:11
Hi,

I solved this by creating a UserMapper with that method. Then I reference
that mapper in the other mappers.

**Comment by jdubois** [comment] 2015-10-02 08:26
OK, so the issue is when a bean is mapped twice...

- This case is handled if it is in the same bean
- But when 2 different beans do the mapping, like here with the User entity, then we have an issue

As we generate this code for each bean separately, we have no mean of knowing if this method has already been generated once... So there's something that needs to be thought of here.

**Comment by deepu105** [comment] 2016-02-01 00:59
@andyverbunt would you like to PR this?

**Comment by andyverbunt** [comment] 2016-02-01 06:47
Unfortunately, I made the change directly in my code, not in the generator
itself. So whenever I regenerate an entity, I have to manually edit the
code again (which is not such a big job after all).Unfortunately, I did not
yet have the time to fix it in jhipster.

**Closed** 2016-02-16 07:27 UTC
Labels: bug

**Comment by andyverbunt** [comment] 2016-02-16 19:39
Not to make things more difficult, but the User mapper is just one particular case. I had to create more mappers just like this (in my code of course) for each ambiguous case.

**Comment by andidev** [comment] 2016-02-16 19:42
For what kind of relationships?

**Comment by andyverbunt** [comment] 2016-02-16 19:54
As long as two entities A & B have a many-to-one relationship with an entity C, two methods will generated with the same signature hence the "ambiguous mapping" error. The User is an example of that, but it could occur with another entity as well.

I'm not sure, but I think the same problem might occur with one-to-one relationships, or in fact any combo as well.

**Comment by andidev** [comment] 2016-02-16 19:57
Yes of course. That should not be to hard to fix i think.

**Comment by andidev** [comment] 2016-02-16 20:31
> As long as two entities A & B have a many-to-one relationship with an entity C, two methods will generated with the same signature hence the "ambiguous mapping" error.

Looks like this works. I just tried
```
entity A {}
entity B {}
entity C {}

relationship ManyToOne {
  A{cc} to C{a}
}
relationship ManyToOne {
  B{cc} to C{b}
}

dto A, B, C with mapstruct
```
