### ISSUE TITLE
Error using swagger on production environment

### ISSUE THREAD

**Issue by marcelinobadin** [jhipster/generator-jhipster#3933] opened 2016-08-04 22:44 UTC
##### **Overview of the issue**

I am running the application on a microservice architecture. My app and my gateway are running with production profile and also swagger.

The gateway swagger is Ok, but when I change the combo to see the swagger from the app I got this:

com.fasterxml.jackson.core.JsonParseException: Illegal character ((CTRL-CHAR, code 31)): only regular white space (\r, \n, \t) is allowed between tokens
@6/P���� ��w�����OO^t���w�O���cx����/#����m���ps4��Kf��|^

(with this strangers characters and then my terminal got broken)

##### **JHipster Version(s)**

generator-jhipster@3.5.1 

##### **Browsers and Operating System**

openjdk version "1.8.0_91"
OpenJDK Runtime Environment (build 1.8.0_91-8u91-b14-0ubuntu4ü16.04.1-b14)
OpenJDK 64-Bit Server VM (build 25.91-b14, mixed mode)

git version 2.7.4

node: v6.2.2

npm: 3.10.5

bower: 1.7.9

gulp:
CLI version 1.2.2
Local version 3.9.1

yeoman: 1.8.4

Docker version 1.11.2, build b9f10c9

docker-compose version 1.6.2, build 4d72027

**Comment by gmarziou** [comment] 2016-08-04 22:50
Does it work when you access swagger spec directly from your service at /v2/api-docs ?

**Comment by marcelinobadin** [comment] 2016-08-04 22:58
I am trying via postman, ip:port/app/v2/api-docs then I got 200 OK but nothing on body (using Authorization Bearer <token> authenticated as admin - authentication: jwt). If I try to get ip:port/v2/api-docs I got 200 OK with body containing the swagger of my gateway.

**Comment by marcelinobadin** [comment] 2016-08-04 23:41
If I get direct from the app port (not passing through the gateway) I got the swagger json as a return

**Comment by gmarziou** [comment] 2016-08-05 10:31
Well I don't use postman, is there a way to show exactly your request  including all headers. Reporting such problem with a curl command is much easier for us to try to reproduce.

**Comment by marcelinobadin** [comment] 2016-08-05 11:11
well, I found what it is but I need help to solve.

I removed application/json from the mime-types to be compressed on the application-prod configuration and swagger is working. But I still need the application/json content to be compressed and only swagger to not be (as we can see).

Any thoughts?

**Comment by gmarziou** [comment] 2016-08-05 12:04
Which app-prod, the one of the service or gateway, or both?
I use compression in both dev and prod on services and gateways and I haven't experienced your issue.

**Comment by marcelinobadin** [comment] 2016-08-05 12:08
I changed the application-prod in service and worked.

I am trying somethings here in the code.

I moved back the changes on the application-prod in service, then in the gateway I have changed AccessControlFilter.java and included a check if the response is Gzipped.
```java
@Override
    public Object run() {
        RequestContext ctx = RequestContext.getCurrentContext();
        ctx.setResponseStatusCode(HttpStatus.FORBIDDEN.value());
        if (ctx.getResponseBody() == null && !ctx.getResponseGZipped()) {
            ctx.setSendZuulResponse(false);
        }
        log.debug("Access Control: filtered unauthorized access on endpoint {}", ctx.getRequest().getRequestURI());
        return null;
    }
```
Now, I am trying to understand how can I change SwaggerBasePathRewritingFilter.java to make it work.

**Comment by marcelinobadin** [comment] 2016-08-05 12:22
Worked. I changed SwaggerBasePathRewritingFilter.java like this and all is functional (keeping the changes on AccessControlFilter.java

```java
@Override
    public Object run() {
        RequestContext context = RequestContext.getCurrentContext();

        if (!context.getResponseGZipped()) {
            context.getResponse().setCharacterEncoding("UTF-8");
        }

        String rewrittenResponse = rewriteBasePath(context);
        context.setResponseBody(rewrittenResponse);
        return null;
    }

    private String rewriteBasePath(RequestContext context) {
        String requestUri = RequestContext.getCurrentContext().getRequest().getRequestURI();
        try {
            InputStreamReader inputStreamReader;
            if (context.getResponseGZipped()) {
                GZIPInputStream responseGzippedDataStream = new GZIPInputStream(context.getResponseDataStream());
                inputStreamReader = new InputStreamReader(responseGzippedDataStream);
            } else {
                InputStream responseDataStream = context.getResponseDataStream();
                inputStreamReader = new InputStreamReader(responseDataStream);
            }
            String response = CharStreams.toString(inputStreamReader);
            if (response != null) {
                LinkedHashMap<String, Object> map = this.mapper.readValue(response, LinkedHashMap.class);

                String basePath = requestUri.replace(Swagger2Controller.DEFAULT_URL,"");
                map.put("basePath",basePath);
                log.debug("Swagger-docs: rewritten Base URL with correct micro-service route: {}", basePath);
                return mapper.writeValueAsString(map);
            }
        }
        catch (IOException e){
            log.error("Swagger-docs filter error", e);
        }
        return null;
    }
```

**Comment by jdubois** [comment] 2016-08-05 12:27
I'm pinging @PierreBesson as I think he coded that part.
Looks like an interesting issue @marcelinobadin -> would like to do a pull request? Shouldn't be too hard as you already have the working code, and this template should be very easy to update.

**Comment by marcelinobadin** [comment] 2016-08-05 13:01
I changed a little rewriteBasePath method to guarantee UTF-8 even on GZipped.

```java
private String rewriteBasePath(RequestContext context) {
        String requestUri = RequestContext.getCurrentContext().getRequest().getRequestURI();
        try {
            InputStream inputStream;
            if (context.getResponseGZipped()) {
                inputStream = new GZIPInputStream(context.getResponseDataStream());
            } else {
                inputStream = context.getResponseDataStream();
            }
            String response = IOUtils.toString(inputStream, Charsets.UTF_8);
            ...
```

**Comment by marcelinobadin** [comment] 2016-08-05 13:01
Yes, I will do.

**Comment by jdubois** [comment] 2016-08-05 20:30
Thanks @marcelinobadin for the PR!
Closing this as the PR is merged

**Closed by jdubois** 2016-08-05 20:30 UTC

**Comment by PierreBesson** [comment] 2016-08-08 16:38
Very nice catch @marcelinobadin :+1:.
It's working perfectly.
