### ISSUE TITLE
apifirst error under gradle build

### ISSUE THREAD

**Issue by liseri** [jhipster/generator-jhipster#6447] opened 2017-10-01 11:05 UTC
##### **Overview of the issue**

ApiFirst Swagger under Gradle is error, but under maven is ok.
1. create a new project with jhipster 4.9 with gradle and apifirst, in win10
2. build the project

The build error is :
```
PS D:\test\jhipster4\mono> .\gradlew classes

> Task :swagger
failed to read resource listing
com.fasterxml.jackson.core.JsonParseException: Unexpected character ('#' (code 35)): expected a valid value (number, Str
ing, array, object, 'true', 'false' or 'null')
 at [Source: src\main\resources\swagger\api.yml; line: 1, column: 2]
        at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1702)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:558)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:456)
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._handleUnexpectedValue(UTF8StreamJsonParser.java:2689)
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._nextTokenNotInObject(UTF8StreamJsonParser.java:878)
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:772)
        at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3850)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3799)
        at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:2447)
        at io.swagger.parser.SwaggerCompatConverter.readResourceListing(SwaggerCompatConverter.java:189)
        at io.swagger.parser.SwaggerCompatConverter.read(SwaggerCompatConverter.java:116)
        at io.swagger.parser.SwaggerParser.read(SwaggerParser.java:75)
        at io.swagger.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:431)
        at io.swagger.codegen.config.CodegenConfigurator$toClientOptInput.call(Unknown Source)
        at org.detoeuf.SwaggerCodeGenTask.swaggerCodeGen(SwaggerCodeGenTask.groovy:43)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.doExecute(DefaultTas
kClassInfoStore.java:142)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskC
lassInfoStore.java:135)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskC
lassInfoStore.java:122)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:762)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:729)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:121)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildO
perationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildO
perationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.j
ava:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.
java:92)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:70
)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachin
gStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExec
uter.java:97)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:
87)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactState
TaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.j
ava:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.j
ava:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34
)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.
java:248)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildO
perationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildO
perationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecute
r.java:241)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecute
r.java:230)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor
.java:123)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.
java:79)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.j
ava:104)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.j
ava:98)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:625)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:580)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98
)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
        at java.lang.Thread.run(Thread.java:745)
Output directory does not exist, or is inaccessible. No file (.swager-codegen-ignore) will be evaluated.


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':swagger'.
> missing swagger input or config!

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
5 actionable tasks: 4 executed, 1 up-to-date
```
##### **Reproduce the error**

1. create a new project, with gradle, apifirst.
2. build the project

##### **JHipster Version(s)**

jhipster4.9

##### **JHipster configuration**

The .yo-rc.json is 
```
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "4.9.0",
    "baseName": "mono",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "gradle",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": true,
    "jwtSecretKey": "10d00b70bc3b351c64d2b7028bc9e9fec178e68e",
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ]
  }
}
```

##### **Browsers and Operating System**

windows10 (en is the default language), powershell,

- [X ] Checking this box is mandatory (this is just to show you read everything)

**Comment by atomfrede** [comment] 2017-10-01 11:17
Will check. Sounds like something has not been replaced correctly in the `yaml` file.

**Comment by atomfrede** [comment] 2017-10-01 11:33
Have you added any entities? Using the latest master and your config works fine for me.

**Comment by liseri** [comment] 2017-10-01 12:05
@atomfrede No, It is empty project.
api.yml is:
```
# API-first development with swagger
# This file will be used at compile time to generate Spring-MVC endpoint stubs using swagger-codegen
swagger: "2.0"
info:
  version: 0.0.1
paths: {}
```

**Comment by atomfrede** [comment] 2017-10-01 12:07
Yes. My file looks the same.

**Comment by liseri** [comment] 2017-10-01 12:09
@atomfrede I will try the master.  Jhipster version 4.8.2 4.9 under gradle both error, but maven style is ok.

**Comment by atomfrede** [comment] 2017-10-01 12:12
As far as I know 4.9 and master should have no difference regarding gradle. But give it a try.

**Comment by liseri** [comment] 2017-10-01 13:23
@atomfrede I had tried the master. The error is same. So, I guess gradle environment in win10  is the problem.

**Comment by atomfrede** [comment] 2017-10-02 12:36
Have you tried to remove the two comment lines from the spec file? Maybe it has something to do with win und unix file path specifications. Will try to reproduce it with a vm.

**Comment by cbornet** [comment] 2017-10-02 13:01
It looks like the file is read as a Json instead of a Yaml.

**Comment by atomfrede** [comment] 2017-10-02 13:24
Ah yes, now you mention it. I didn't realize jackson has nothing to do with yaml files. Thats even more strange now :(

**Comment by cbornet** [comment] 2017-10-02 13:53
I think we shouldn't get to https://github.com/swagger-api/swagger-parser/blob/master/modules/swagger-parser/src/main/java/io/swagger/parser/SwaggerParser.java#L75
It seems the Swagger20Parser failed to read the file (but the IOException is catched to try the compat parser). Could it be a windows/unix file separator issue ?

**Comment by atomfrede** [comment] 2017-10-02 14:00
Looks like that. Will check later.

**Comment by liseri** [comment] 2017-10-02 18:44
@atomfrede , Yes , I had tried remove the coments, but the same error.
@cbornet , Yes, it read a yaml as a json. But I don't know why. The maven style is ok.
May be the  swaggercoden style using gradle plugin shoud be simpler. I tried to debug the plugin, but fault.

**Comment by atomfrede** [comment] 2017-10-02 19:50
@liseri Can you try this: `inputSpec = file('src/main/resources/swagger/api.yml').absolutePath` under windows?

**Comment by liseri** [comment] 2017-10-02 20:31
@atomfrede  Hahaha, You are right, It passed. Thank you.  But why, If it had not been read, the error of unexpected token XXX is impossible.

**Comment by atomfrede** [comment] 2017-10-02 20:47
The problem is, currently the inputSpec is just a String, which is not environment aware. Using the approach above will build the file path aware of the environment, therefore the path is readable in your case. I will provide a PR tomorrow.

**Comment by cbornet** [comment] 2017-10-02 20:50
@atomfrede do you think this could be fixed in the swagger-codegen gradle plugin ?

**Comment by atomfrede** [comment] 2017-10-02 21:12
Not sure it's an issue as the spec can be an URL too. So maybe it is just a matter of documentation.

**Comment by cbornet** [comment] 2017-10-03 12:05
I see that the [gradle plugin](https://github.com/thebignet/swagger-codegen-gradle-plugin) has recently been deprecated. The author seems to recommend to use a [task directly](https://github.com/thebignet/swagger-codegen-gradle-plugin-example).
@atomfrede you're the expert, WDYT ?

**Comment by atomfrede** [comment] 2017-10-03 12:35
In fact that plugin just forwarded the config to swagger codegen. For now let's stay with the plugin I would say as it helps adding dependencies. Maybe we will later have a jhipster-swagger plugin which might have more functions.

**Comment by liseri** [comment] 2017-10-03 13:22
@atomfrede  It's a good idea. Now, apifirst only can convert doc to code, but code to doc. The api driver develop and the domain or model driver develop is important. It's the things I think important:
- convert code to doc
- convert  doc to code with no-clear my logic code
While, I will also try to implement it.

**Closed** 2017-10-03 16:48 UTC
Labels: bug, gradle, needs-pr

**Comment by globtroter** [comment] 2018-07-19 18:46
I have the same issue. Usage org.gradle.daemon=false in gradle.properties helps me but I don't know why

**Comment by atomfrede** [comment] 2018-07-19 19:09
Please don't comment on sooo old issues, if you think you have found a jhipster bug, please provide a new issue following the guidelines, such we can help you.
