### ISSUE TITLE
Deploy Gateway Application on Heroku Failure - Workbox needed

### ISSUE THREAD

**Issue by glautervl** [jhipster/generator-jhipster#6948] opened 2018-01-05 13:42 UTC
##### **Overview of the issue**

I am trying to deploy a gateway application on heroku but the deploy process is breaking.

##### **Motivation for or Use Case**

Deploying Gateway Application on Heroku.

##### **Reproduce the error**

Step 1: Generating a new gateway application with: jhipster
Step 2: Deploying the app on heroku and answer the asked normal questions, point to Registry URL: jhipster heroku

CONSOLE LOG ERROR
...
`[INFO] yarn run v1.3.2
[INFO] $ yarn run cleanup && yarn run webpack:prod:main && yarn run clean-www
[INFO] $ rimraf target/{aot,www}
[INFO] $ yarn run webpack -- --config webpack/webpack.prod.js --progress --profile
[ERROR] warning From Yarn 1.0 onwards, scripts don't require "--" for options to be forwarded. In a future version, any explicit "--" will be forwarded as-is to the scripts.
[INFO] $ node --max_old_space_size=4096 node_modules/webpack/bin/webpack.js --config webpack/webpack.prod.js --progress --profile
[ERROR]  10% building modules 0/2 modules 2 active ...teway/sr/main/webapp/app/polyfills.ts
 10% building modules 5/6 modules 1 active .../main/webapp/content/scss/global.scss
 11% building modules 16/18 modules 2 active .../configurati/content/scss/global.scss
 14% building modules 40/42 modules 2 active ...e/state-dialog.component.ngfactory.js
 16% building modules 55/75 modules 20 active ...teway/src/main/webapp/ms.component.ts
 20% building modules 87/90 modules 3 active ...teway/src/main/webapp/manifest.webapp 
 22% building modules 100/125 modules 25 active ...nslate/core/src/translate.compiler.js
 25% building modules 128/144 modules 17 active ...de_modules/@angular/http/esm5/http.js
 28% building modules 155/163 modules 8 active ...s/@ng-bootstrap/ng-bootstrap/index.js 
 31% building modules 177/188 modules 11 active ...ng-bootstrap/datepicker/datepicker.js
 32% building modules 186/225 modules 39 active ...modules/@angular/common/locales/pt.js
 33% building modules 198/233 modules 35 active ...de_modules/ngx-webstorage/dist/app.js
 37% building modules 227/245 modules 18 active ...eflect.get-own-property-descriptor.js
 39% building modules 244/275 modules 31 active ...translate/core/src/translate.store.js
 42% building modules 267/299 modules 31 active ..._modules/rxjs/_esm5/operators/last.js
 44% building modules 290/322 modules 32 active ...de_modules/core-js/modules/es6.set.js
 48% building modules 317/342 modules 25 active ...ng-bootstrap/timepicker/timepicker.js
 50% building modules 334/371 modules 37 active ...r/hijri/ngb-calendar-islamic-civil.js
 52% building modules 354/398 modules 44 active ...odules/rxjs/_esm5/util/errorObject.js
 55% building modules 383/415 modules 32 active ...odules/core-js/modules/_collection.js
 59% building modules 413/432 modules 19 active ...es/core-js/modules/_ie8-dom-define.js
 61% building modules 430/461 modules 31 active ...re-js/modules/es6.regexp.to-string.js
 63% building modules 443/495 modules 52 active ...s/core-js/modules/_collection-weak.js
 65% building modules 474/510 modules 36 active ...re-js/modules/_inherit-if-required.js
 67% building modules 502/528 modules 26 active ...es/core-js/modules/es6.math.fround.js
 67% building modules 527/550 modules 23 active ...otstrap/ng-bootstrap/buttons/labox.js
 66% building modules 547/576 modules 29 active ...core-js/modules/es6.string.italics.js
 65% building modules 564/606 modules 42 active ...es/core-js/modules/es6.parse-float.js
 65% building modules 586/629 modules 43 active ...modules/core-js/modules/es6.symbol.js
 67% building modules 620/642 modules 23 active ...de_modules/core-js/modules/_invoke.js
 69% building modules 653/655 modules 2 active ...de_modules/core-js/modules/_invoke.js 
 69% building modules 676/679 modules 3 active ...locks/config/uib-pagination.config.ts
 69% building modules 700/702 modules 2 active .../src/main/webapp/app/layouts/index.ts 
 69% building modules 705/709 modules 4 active ...s/rxjs/_esm5/add/operator/mergeMap.js
34147ms building modules                                                               
[ERROR] 119ms sealing
[ERROR] 2ms optimizing 
[ERROR] 0ms basic module optimization 
[ERROR] 83ms module optimization
[ERROR] 0ms advanced module optimization 
[ERROR] 16ms basic chunk optimization       
optimization
[ERROR] 0ms chunk optimization 
[ERROR] 3ms advanced chunk optimization 
[ERROR]  69% building modules 723/724 modules 2 active .../main/webapp/content/scss/vendor.scss
3094ms building modules                                    
[ERROR] 1ms module and chunk tree optimization 
[ERROR] 0ms chunk modules optimization 
[ERROR] 0ms advanced chunk modules optimization 
[ERROR] 11ms module reviving
[ERROR] 1ms module order optimization 
[ERROR] 4ms module id optimization 
[ERROR] 4ms chunk reviving 
[ERROR] 0ms chunk order optimization 
[ERROR] 18ms chunk id optimization
[ERROR] 440ms hashing
[ERROR] 0ms module assets processing 
[ERROR] 448ms chunk assets processing
[ERROR] 7ms additional chunk assets processing 
[ERROR] 1ms recording 
[ERROR] 18057ms additional asset processing
[ERROR] 0ms chunk asset optimization 
[INFO] MergetJsonsWebpackPlugin compilation started...
[INFO] MergetJsonsWebpackPlugin compilation completed...
[ERROR] 622ms asset optimization
[INFO] MergetJsonsWebpackPlugin emit starts...
[INFO] MergetJsonsWebpackPlugin emit completed...
[INFO] MergetJsonsWebpackPlugin emit starts...
[INFO] MergetJsonsWebpackPlugin emit completed...
[INFO] MergetJsonsWebpackPlugin emit starts...
[INFO] MergetJsonsWebpackPlugin emit completed...
[ERROR]  95% emittingError: workbox-sw is needed by the service worker and could not be copied over to your new site. Error: ENOENT: no such file or directory, unlink '/Users/glauterlemos/Dropbox/DESENVOLVIMENTO/JAVA/indoorchannel/IDCGateway/target/www/wor
kbox-sw.prod.v2.1.2.js'
[ERROR]     at Promise.all.then.catch (/Users/glauterlemos/Dropbox/DESENVOLVIMENTO/JAVA/indoorchannel/IDCGateway/node_modules/workbox-build/build/lib/utils/copy-workbox-sw.js:17:13)
[ERROR]     at <anonymous>
[ERROR] error Command failed with exit code 1.
[INFO] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[ERROR] error Command failed with exit code 1.
[INFO] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[ERROR] error Command failed with exit code 1.
[INFO] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:43 min
[INFO] Finished at: 2018-01-05T10:28:22-03:00
[INFO] Final Memory: 49M/508M
[INFO] ------------------------------------------------------------------------`

##### **Related issues**
[WORKBOX ISSUE](https://github.com/jhipster/generator-jhipster/issues/6945)

##### **Suggest a Fix**

I don't still know how to fix it .

##### **JHipster Version(s)**

4.13.2

##### **JHipster configuration**

`{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.indoorchannel.gateway",
      "nativeLanguage": "pt-br",
      "microservicePath": "/Users/glauterlemos/Dropbox/DESENVOLVIMENTO/JAVA/indoorchannel/IDCBaseApi"
    },
    "jhipsterVersion": "4.13.2",
    "baseName": "IDCGateway",
    "packageName": "com.indoorchannel.gateway",
    "packageFolder": "com/indoorchannel/gateway",
    "serverPort": "8080",
    "authenticationType": "uaa",
    "uaaBaseName": "IDCAuthServer",
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": true,
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "gateway",
    "testFrameworks": [
      "gatling",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "pt-br",
    "languages": [
      "pt-br",
      "en",
      "es"
    ],
    "cacheProvider": "hazelcast",
    "enableHibernateCache": true
  }
}`

##### **Browsers and Operating System**

OS: macOS Sierra
Browsers: No browser issue.

- [X ] Checking this box is mandatory (this is just to show you read everything)

**Comment by gmarziou** [comment] 2018-01-05 17:48
Duplicate of #6945 and not specific to Heroku

**Closed by gmarziou** 2018-01-05 17:48 UTC
