### ISSUE TITLE
Liquibase checksum issues after import-jdl

### ISSUE THREAD

**Issue by richard-fairthorne** [jhipster/generator-jhipster#8114] opened 2018-08-20 00:23 UTC
##### **Overview of the issue**

I have to clean my H2 database after every database change on an existing entity. Each time I run:

```
jhipster import-jdl Acct.jdl
```

Liquibase changesets are overwritten, causing checksum failures and stopping migrations from working.

##### **Motivation for or Use Case**

I have to run ./mvnw clean, and then repopulate my database every time i change existing entities. I'm not in production yet, but I presume that the same issue would occur there.

##### **Reproduce the error**

1. Create a clean project with H2 disk in development.

2. Given the file Acct.jdl:
```
entity Acct {
}
entity Currency {
	symbol String required
    name String required
    decimalPlaces Integer required
}
entity Transaction {
    transTime Instant required
	description String required
    amount Integer required
    settled Boolean required
}
relationship ManyToOne  {
	Acct{Currency(name)} to Currency
}
relationship OneToMany {
	Acct to Transaction
}

```

3. run the command:

```
jhipster import-jdl Acct.jdl
```

4. Start the backend to run the migrations.

5. Change the file Acct.jdl:

```
entity Acct {
}
entity Currency {
	symbol String required
    name String required
    decimalPlaces Integer required
}
entity Transaction {
    transTime Instant required
	description String required
    amount Integer required
    settled Boolean required
}
relationship ManyToOne  {
	Acct{Currency(name)} to Currency
    Acct{User(email)} to User
}
relationship OneToMany {
	Acct to Transaction
}

```

6. Run the command:

```
jhipster import-jdl Acct.jdl
```

Your already executed liquibase changelog will be overwritten, breaking your upgrade/migration path.

Example: https://www.dropbox.com/s/rrl9xxpba96krzd/jhipser_corrupts_liquibase_changeset.png?dl=0

An error similar to the following will be produced when you once again restart the backend: 

```
2018-08-19 18:50:05.684 ERROR 19633 --- [bang-Executor-1] i.g.j.c.liquibase.AsyncSpringLiquibase   : Liquibase could not start correctly, your database is NOT ready: Validation Failed:
     1 change sets check sum
          config/liquibase/changelog/20180819220907_added_entity_Acct.xml::20180819220907-1::jhipster was: 7:69eedc6d349bc056dc0a221a392eb0ed but is now: 7:06826cf89397bdd0e9a0c6940384f7aa


liquibase.exception.ValidationFailedException: Validation Failed:
     1 change sets check sum
          config/liquibase/changelog/20180819220907_added_entity_Acct.xml::20180819220907-1::jhipster was: 7:69eedc6d349bc056dc0a221a392eb0ed but is now: 7:06826cf89397bdd0e9a0c6940384f7aa
```

##### **Related issues**

I am not sure if any issues I found are related. They do not seem to be.

##### **Suggest a Fix**

If i knew enough about the framework to suggest a fix, I'd have fixed it. Soon 👅 

##### **JHipster Version(s)**

Welcome to JHipster v5.2.1

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

[admin:~/src/hashbang.info] 3s 130 $ jhipster info
Using JHipster version installed locally in current project's node_modules
Executing jhipster:info
Options: 
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
hashbang@0.0.0 /Users/admin/src/hashbang.info
└── generator-jhipster@5.2.1 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "info.hashbang",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "5.2.1",
    "applicationType": "monolith",
    "baseName": "hashbang",
    "packageName": "info.hashbang",
    "packageFolder": "info/hashbang",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "yarn",
    "testFrameworks": [
      "gatling",
      "cucumber",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ]
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Acct
entity Currency {
  symbol String required,
  name String required,
  decimalPlaces Integer required
}
entity Transaction {
  transTime Instant required,
  description String required,
  amount Integer required,
  settled Boolean required
}
relationship OneToMany {
  Acct{transaction} to Transaction{acct}
}
relationship ManyToOne {
  Acct{currency(name)} to Currency,
  Acct{user(email)} to User
}

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

git version 2.17.0

node: v8.11.4

npm: 5.6.0

yeoman: 2.0.5

yarn: 1.9.4

Docker version 18.06.0-ce, build 0ffa825

docker-compose version 1.22.0, build f46880f

Congratulations, JHipster execution is complete!

My specific JDL files are shared in the bug description.

##### **Browsers and Operating System**

I'm on mac OSX 10.something. The bug occurs before I load a browser.

- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by richard-fairthorne** [comment] 2018-08-20 02:54
After a quick dig through the generator source, I believe this bug may be in jhipster-core.

```
const jhiCore = require('jhipster-core');

/* [...] A bunch of words about variables and stuff */

function importJDL() {
    this.log('The JDL is being parsed.');
    const jdlImporter = new jhiCore.JDLImporter(this.jdlFiles, {
        databaseType: this.prodDatabaseType,
        applicationType: this.applicationType,
        applicationName: this.baseName,
        generatorVersion: packagejs.version,
        forceNoFiltering: this.options.force
    });

/* [...] bla bla bla farts and poop */

    try {
        importState = jdlImporter.import();
```

**Comment by richard-fairthorne** [comment] 2018-08-20 11:16
Here's what I've figured out as it goes:

Tracking: jhipster/generator-jhipster

leads to:

- jhipster-core
- module/index.js (41)
- lib/jdl/jdl_importer.js (143 or 154)
- lib/export/jhipster_entity_exporter.js (44)
- function exportedEntitiesInApplication(passedConfiguration)

I was hoping this was just about creating a new file name, but it doesn't appear that simple. Hopefully that's helpful.. maybe there's logic under the hood somewhere for doing a DB agnostic diff and creating a new changelog.

**Comment by MathieuAA** [comment] 2018-08-20 19:05
@richard-fairthorne Hi, the smallest update causes a checksum change, and the import-jdl subgen regenerates (and overwrites) everything **by force by default**. That's why you have this issue. I've tried to reproduce your case with the standard Questions & Answers (the "normal" way of generating things), and the same things happen.

**Comment by ruddell** [comment] 2018-08-20 21:15
Similar to https://github.com/jhipster/generator-jhipster/issues/5954 and the (closed) PR https://github.com/jhipster/generator-jhipster/pull/6016, that issue never was fully solved but now only changed entities are regenerated when importing JDL.

What I recommend is reverting the changelog files and running `./mvnw liquibase:diff` to generate a new changelog.

**Comment by richard-fairthorne** [comment] 2018-08-20 23:56
I'm not sure I understand ho to "revert the changelog files". Are you suggesting that I should commit the changelogs every time before I run import-jdl, then use liquibase:diff to create a new one?

If this logic works, could it be implemented wherever the changelog files are generated in the first place?

It would be like this:

- instead of overwriting the old changelog, create a new *temporary* one.
- apply the new temporary one to the database, then delete it.
- run liquibase diff

**Comment by richard-fairthorne** [comment] 2018-08-20 23:58
If this logic in fact works, I'd be willing to write a patch for it.

**Comment by ruddell** [comment] 2018-08-21 00:10
Yes, revert means reset to before the changes.  

If we automated `liquibase:diff`, we would be making a lot of assumptions (the database is set up locally and up-to-date, the project has been compiled beforehand, and the developer chose mysql or postgresql in dev).  I think the PR I linked above does it the better way of writing the changelog during generation, which would work with all database types and not depend on `liquibase:diff`

**Comment by Blackdread** [comment] 2018-08-21 12:11
Same for issue #8086 
It is alright to revert the changes of the liquibase after upgrade, just do liquibase diff if some parts changed.
and the option 

> runOnChange="true"

is not a solution.

**Comment by jdubois** [comment] 2018-08-22 14:25
For me the process is that:

- You develop using "import-jdl" until you are happy with your code: during that time, you keep overwriting your Liquibase files because you're working on them. Otherwise you would end up with a lot of changelogs.
- Once you have commited your changelog, if you want to modify your entities, you either create a new changelog manually (no JHipster at all), or use "liquibase:diff" to generate a new changelog for you

So your changelogs are not corrupted, you are just overwriting them because you are currently testing. So that means you will need to drop your database and recreate it, but with Liquibase that's easy to recreate, so that's OK.

**Comment by jdubois** [comment] 2018-08-22 14:27
I'm not totally sure about the "revert changelog" part - if you find a good workflow, don't hesitate to propose it as a new feature request + PR.
In the meantime I'm closing this because that's not really an error.

**Closed by jdubois** 2018-08-22 14:27 UTC
