### ISSUE TITLE
Reloading an entity page causes the the menu item labels on the navbar to mysteriously change to attribute names

### ISSUE THREAD

**Issue by cleecds** [jhipster/generator-jhipster#1902] opened 2015-08-20 14:40 UTC
We have three entity pages. On one of the pages, when we refresh the page, the menu item labels on the navbar would erroneously change to attribute names. For example, items such as Home, Entities, Account, Administration, etc. would change to global.menu.home, global.menu.entities.main, global.menu.account.main, etc. Is anybody experiencing this issue? Thanks.

**Comment by andidev** [comment] 2015-08-20 14:46
Need more info on this. Could you provide a screenshot and tell us what browser you using?

**Comment by andidev** [comment] 2015-08-20 14:58
Okey it's the translation keys you are seeing. 
I think I have experienced this as well but not sure when. Do you get this issue after generating a new jhipster app without doing any modification?

**Comment by afedulov** [comment] 2015-08-20 15:03
+1. Can confirm the same behavior.

**Comment by afedulov** [comment] 2015-08-20 15:07
Ok, I've got this one. On one the generated entities this is missing in the $stateProvider configuration:
```
   resolve: {
                    translatePartialLoader: ['$translate', '$translatePartialLoader', function ($translate, $translatePartialLoader) {
                        $translatePartialLoader.addPart('reportResult');
                        return $translate.refresh();
                    }]
                }
```

**Comment by cleecds** [comment] 2015-08-20 15:08
Hello andidev and afedulov,

Thank you for your responses. We are getting this issue after the jhipster app has been customized. Also we are using Firefox as the browser.

**Comment by cleecds** [comment] 2015-08-20 17:57
afedulov,

After adding the missing codes to the entity's js file, we're not able to get to the entity page either by the navbar pulldown or by url. Is there something additional we have to do? Thanks.

**Comment by andidev** [comment] 2015-08-20 19:44
@afedulov 
Are you using the latest version of jhipster? You should have `$translatePartialLoader.addPart('global');` line in your code snippet you provided if you are so my guesses is that you are not.

@cleecds 
What version of jhipster are you using?

I can't seem to reproduce this. Are you manually refreshing the page or is it Browser Sync that does it for you?

**Comment by cleecds** [comment] 2015-08-20 19:54
@andidev 
We are using $translatePartialLoader.addPart('global'); in our codes. We upgraded to Jhipster 2.19.0 few days ago. We are manually refreshing the page.

**Comment by gmarziou** [comment] 2015-08-20 20:41
How are you running your app: `mvn spring-boot:run` or using Application.main? 
Are you using grunt serve?
Are you on Windows?

**Comment by andidev** [comment] 2015-08-20 20:51
Is it only one of the entities that causes this problem? Does the browser console show any errors?

The code snippet that afedulov provided should not be missing in the latest version of jhipster according to the source code in the generator unless it is manually removed.

**Comment by afedulov** [comment] 2015-08-21 08:51
@andidev I have generated those entities from different machines, maybe even using different jhipster versions. It is hard to say now, because I have upgraded since than. It seems to me that enableTranslation option might be the source of the problem in my case. It controls the addition of the above-mentioned block and at the same time is nowhere to be found in the .yo-rc (probably because project was generated using an older version and I did not rerun yo jhipster command for this project).

**Comment by cleecds** [comment] 2015-08-21 15:53
@gmarziou 
We are running the app with mvn spring-boot:run. I don't believe we are using Grunt. How do I verify? In the Firebug console, it's showing:

Error: Could not resolve 'the app' from state 'site'
transitionTo@http://www.companyt.com/bower_components/angular-ui-router/release/angular-ui-router.js:3074:1
go@http://www.company.com/bower_components/angular-ui-router/release/angular-ui-router.js:3007:14
$StateRefDirective/<.link/</transition<@http://www.company.com/bower_components/angular-ui-router/release/angular-ui-router.js:4057:13
timeout/timeoutId<@http://www.company.com/bower_components/angular/angular.js:17571:28
completeOutstandingRequest@http://www.company.com/bower_components/angular/angular.js:5370:7
Browser/self.defer/timeoutId<@http://www.company.com/bower_components/angular/angular.js:5642:7
consoleLog/<()angular.js (line 12221)
$ExceptionHandlerProvider/this.$get</<()angular.js (line 9055)
timeout/timeoutId<()angular.js (line 17574)
completeOutstandingRequest()angular.js (line 5370)
Browser/self.defer/timeoutId<()angular.js (line 5642)
return logFn.apply(console, args);

**Comment by gmarziou** [comment] 2015-08-21 16:33
Regarding grunt, you would know if you were using this efficient workflow top develop your app, see 'Using the Java server and Grunt together{ in http://jhipster.github.io/development.html

So the logs are pretty clear, you have a link to a state named 'the app' and it could not be resolved by angular-ui router.
So, I'm not sure it's a good idea to name a state with spaces in it, then you probably haven't inserted your js script defining this state in your index.html file. 

Where does this 'the app' state comes from?
It is the name you gave to your app at generation step?

**Comment by cleecds** [comment] 2015-08-21 16:47
@gmarziou 
I have just verified that we are using Grunt.

My mistake. I forgot the underscore in 'the_app' when I was typing my last reply. It should be the_app.

**Comment by cleecds** [comment] 2015-08-21 16:52
By the way, I got the above error after implementing the snippet below:

resolve: {
                    translatePartialLoader: ['$translate', '$translatePartialLoader', function ($translate, $translatePartialLoader) {
                        $translatePartialLoader.addPart('the_app');
                        $translatePartialLoader.addPart('global');
                        return $translate.refresh();
                    }]
                }

**Comment by gmarziou** [comment] 2015-08-21 18:34
Where and why did you do that?

**Comment by cleecds** [comment] 2015-08-21 18:51
@gmarziou
Are you referring to where and why we added the snippet? afedulov mentioned that the snippet was missing from the entity's JS file. He believed it would fix our original issue. So we went ahead and added it. Thus that's how we got to the error in the console. Our original issue is the menu item labels on the navbar would erroneously change to attribute names whenever we manually refresh the browser.

**Comment by andidev** [comment] 2015-08-21 19:04
Try regenerating that entity and see if there is any differences in the code. 
Could you also provide your .yo-rc.json file content and the entity json file content of the entity causing this. The .yo-rc.js file is located in the root while the entity json is located in the .jhipster folder.

**Comment by gmarziou** [comment] 2015-08-21 20:36
OK so it means that 'the_app' is the name of the entity, I wonder whether this underscore would break generated code somehow.

**Comment by gmarziou** [comment] 2015-08-21 20:59
I just tested `yo jhipster:entity the_app`, beside producing ugly class names or non conventional routes and url, it seems to work fine.

**Comment by deepu105** [comment] 2015-08-23 03:05
@cleecds plz follow our issue guidelines and provide your yo-rc and the entity json files else we are just wasting time here

**Comment by jdubois** [comment] 2015-08-23 15:55
You are supposed to use each underlying technology "normally", so with AngularJS you shouldn't have an underscore in the entity name anyway (see also our policy 1 at http://jhipster.github.io/policies.html ).

And I can't +1 @deepu105 enough, people need to follow the guidelines here, it's really beginning to be annoying ( @cleecds this is not really your fault, I also have 2-3 private emails a day about "bugs", and this is of course not from you!)

**Closed by jdubois** 2015-08-23 15:55 UTC
Labels: bug
