### ISSUE TITLE
7.0.0 liquibase loaddata no longer works for clob type

### ISSUE THREAD

**Issue by pfrumau** [jhipster/generator-jhipster#14463] opened 2021-03-25 21:29 UTC
##### **Overview of the issue**

After migrating to 7.0.0 (and also when generating a clean app):
Any data in loadData in liquibase changelog of type clob ( `../fake-data/blob/` ) will fail, and result in row not inserted in database. No errors are thrown, data is just not loaded.

For example:
```
id;country_name;country_details
1;vortals Car Hill;../fake-data/blob/hipster.txt
```
Will result in no rows added in database

I use postgresql for dev and prod profiles.

##### **Motivation for or Use Case**

I want to use TextBlob in my entities and load it for development test data (faker)

##### **Reproduce the error**

1. create new jhipster app v7.0.0
2. import jdl with `jhipster import-jdl jhipster-jdl.jh`
3. start postgres database with `npm run docker:db:up`
4. start app with `./mvnw`
5. app will start, but check database, no rows were created.

##### **Related issues**

Found some faker.js related stuff, but nothing for 7.0.0

##### **Suggest a Fix**

I found that upgrading liquibase in pom.xml from `4.3.1` to `4.3.2` gives me slightly better results:

Instead of empty rows, i get a row with a value equal to the string in the `.csv` file (so not yet the value in the `.txt` file).

so in `pom.xml`
```
        <liquibase.version>4.3.2</liquibase.version>
        <liquibase-hibernate5.version>4.3.2</liquibase-hibernate5.version>
```

gives me all rows in postgres, but doesnt load the file blob correctly
```
1	"vortals Car Hill"	"../fake-data/blob/hipster.txt"
```
##### **JHipster Version(s)**

7.0.0

##### **JHipster configuration**

  <details>
  <summary>.jo-rc.json</summary>
  <pre>
{
  "generator-jhipster": {
    "blueprints": [],
    "otherModules": [],
    "applicationType": "monolith",
    "baseName": "test2",
    "jhipsterVersion": "7.0.0",
    "skipClient": false,
    "skipServer": false,
    "skipUserManagement": false,
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "testFrameworks": [],
    "pages": [],
    "creationTimestamp": 1616706708953,
    "serviceDiscoveryType": false,
    "reactive": false,
    "authenticationType": "jwt",
    "packageName": "com.mycompany.myapp",
    "serverPort": "8080",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "buildTool": "maven",
    "serverSideOptions": [],
    "websocket": false,
    "searchEngine": false,
    "messageBroker": false,
    "enableSwaggerCodegen": false,
    "clientFramework": "react",
    "withAdminUi": true,
    "clientTheme": "none",
    "enableTranslation": false,
    "nativeLanguage": "en",
    "packageFolder": "com/mycompany/myapp",
    "jwtSecretKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "clientPackageManager": "npm",
    "clientThemeVariant": "",
    "languages": ["en", "fr"],
    "entities": ["Region", "Country"],
    "lastLiquibaseTimestamp": 1616706851000
  }
}

  </pre>
  </details>

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

  <details>
  <summary>JDL definitions</summary>
  <pre>
    entity Region {
	    regionName String
	    regionDetails TextBlob
    }
    
    entity Country {
	    countryName String
	    countryDetails TextBlob
    }
  </pre>
  </details>

##### **Browsers and Operating System**

ubuntu 20

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment] 2021-03-27 11:31
@pfrumau : I edit your configuration and put this value `YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons` for jwtSecret. Because it's annoying when using your configuration, the jwtSecret is not correct and it makes us to lost time when trying to reproduce, because the generated project is not correct
Better solution would be to simply use `jhipster info` for you :-)

Anyway, I confirm your issue

**Comment by DanielFran** [comment] 2021-03-27 17:39
Confirmed, also happening with Angular:

INFO! Using JHipster version installed locally in current project's node_modules
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
test-2@0.0.1-SNAPSHOT C:\Users\ip040351\workspace\jhipster\test2
`-- generator-jhipster@7.0.0

```


##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**


<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "clientFramework": "angularX",
    "serverPort": "8080",
    "serviceDiscoveryType": false,
    "skipUserManagement": false,
    "withAdminUi": true,
    "baseName": "test2",
    "buildTool": "maven",
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "enableHibernateCache": true,
    "enableSwaggerCodegen": false,
    "enableTranslation": false,
    "jhiPrefix": "jhi",
    "languages": ["en", "fr"],
    "messageBroker": false,
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "skipClient": false,
    "testFrameworks": [],
    "websocket": false,
    "applicationType": "monolith",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "clientPackageManager": "npm",
    "nativeLanguage": "en",
    "jhipsterVersion": "7.0.0",
    "skipServer": false,
    "dtoSuffix": "DTO",
    "entitySuffix": "",
    "reactive": false,
    "clientTheme": "none",
    "clientThemeVariant": "",
    "entities": ["Region", "Country"],
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "blueprints": [],
    "otherModules": [],
    "pages": [],
    "creationTimestamp": 1616865918775,
    "jwtSecretKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "lastLiquibaseTimestamp": 1616866038000
  }
}

</pre>
</details>


##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Region {
  regionName String
  regionDetails TextBlob
}
entity Country {
  countryName String
  countryDetails TextBlob
}

</pre>
</details>


##### **Environment and Tools**

java version "11.0.10" 2021-01-19 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.10+8-LTS-162)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.10+8-LTS-162, mixed mode)

git version 2.24.1.windows.2

node: v14.15.4

npm: 7.7.5

Docker version 20.10.5, build 55c4c88

docker-compose version 1.28.5, build c4eb3a1f


No change to package.json was detected. No package manager install will be executed.
Congratulations, JHipster execution is complete!
Sponsored with ❤️  by @oktadev.

**Comment by DanielFran** [comment] 2021-03-27 17:42
JDL file:

````txt
entity Region {
	regionName String
	regionDetails TextBlob
}

entity Country {
    countryName String
    countryDetails TextBlob
}

application {
  config {
      applicationType monolith
      baseName test2
      packageName com.mycompany.myapp
      buildTool maven
      clientPackageManager npm
      databaseType sql
      devDatabaseType postgresql
      prodDatabaseType postgresql
      enableTranslation false
      nativeLanguage en
      languages [en, fr]
      serverPort 8080
      authenticationType jwt
      cacheProvider ehcache
      enableHibernateCache true
      messageBroker false
      searchEngine false
      clientFramework angular
  }
  entities *
}
````

**Comment by mshima** [comment] 2021-03-27 21:47
Using H2 the issue doesn't happens.
Seems a liquibase upstream bug.

**Comment by DanielFran** [comment] 2021-03-27 22:26
Yes, seems in liquibase side.

I try to use some previous version, but did not yet found the latest version where it was working....

@nvoxland seems that it was not yet reported

**Comment by jidma** [comment] 2021-04-07 18:16
The issue is indeed a liquibase issue. 
I tried different versions of liquibase with following results:

| Liquibase version | result |
|-------|-----|
| V <= 3.10.2 | The CLOB is properly loaded 
|  3.10.3 <= V <= 4.3.1 | No row is loaded
|  4.3.2 <= V  | The filename is loaded instead of the content

I opened an [issue](https://github.com/liquibase/liquibase/issues/1790) and PR on liquibase side.

In the meantime, we can revert to liquibase 3.10.2 as it's the latest working version.

**Comment by DanielFran** [comment] 2021-05-12 07:44
Keep open

**Comment by DanielFran** [comment] 2021-06-14 07:47
Keep it open

**Comment by jidma** [comment] 2021-07-15 14:49
Keep it open. A PR is being reviewed at liquibase side.

**Comment by DanielFran** [comment] 2021-08-05 21:26
@jidma PR in liquibase project has been merged and has been included in v.4.4.3.
Waiting for official release.

**Comment by amadomaster** [comment] 2021-09-06 16:21
Keep it open.

**Closed** 2021-09-07 15:44 UTC
Labels: area: bug :bug:, $100, theme: fake-data, $$ bug-bounty $$, theme: entities, theme: postgresql, theme: liquibase

**Comment by DanielFran** [comment] 2021-09-07 16:04
@pascalgrimaud Issue is now fixed.

Since @jidma fixed the issue directly on liquibase, can we share the bug-bounty with him?

**Comment by pascalgrimaud** [comment] 2021-09-07 16:39
I updated the bounty so both can claim each one :-)

**Comment by DanielFran** [comment] 2021-09-12 10:09
@pascalgrimaud Bug bounty claimed: https://opencollective.com/generator-jhipster/expenses/49869

**Comment by pascalgrimaud** [comment] 2021-09-12 10:15
@DanielFran : approved

**Comment by jidma** [comment] 2021-09-12 11:22
@pascalgrimaud same https://opencollective.com/generator-jhipster/expenses/49872

**Comment by pascalgrimaud** [comment] 2021-09-12 11:58
@jidma : approved
