### ISSUE TITLE
problem in inserting records with Date Time field in entity to Time stamp in mySql

### ISSUE THREAD

**Issue by smart987** [jhipster/generator-jhipster#2111] opened 2015-10-08 21:09 UTC
I have added new field of type time stamp using liquibase for my existing jhipster entity and my back end is mysql.

    <changeSet author="mnkb" id="20151008151559">
           <addColumn schemaName="sample"
                tableName="invoice">       
             <column name="bill_date" type="timestamp"/>
        </addColumn>
    </changeSet>

From my angular js front end request is going as :

    {"accountNumber":"AC6434364","invoiceNumber":"IN67347643","invoiceAmount":326,"status":"open","ediNumber":"6565EDI","billDate":"2012-05-02T17:07:00.000Z","id":null}

And my REST call Debug log is as follows :

    [DEBUG] com.sample.aop.logging.LoggingAspect - Enter: com.sample.web.rest.InvoiceResource.create() with argument[s] = [Invoice{id=null, accountNumber='AC6434364', invoiceNumber='IN67347643', invoiceAmount='326.0', ediNumber='6565EDI', status='open', billDate='2012-05-02T22:37:00.000+05:30'}]
    [DEBUG] com.sample.web.rest.InvoiceResource - REST request to save Invoice : Invoice{id=null, accountNumber='AC6434364', invoiceNumber='IN67347643', invoiceAmount='326.0', ediNumber='6565EDI', status='open', billDate='2012-05-02T22:37:00.000+05:30'}
    Hibernate: insert into invoice (account_number, bill_date, edi_number, invoice_amount, invoice_number, status) values (?, ?, ?, ?, ?, ?)
    [WARN] org.hibernate.engine.jdbc.spi.SqlExceptionHelper - SQL Error: 1292, SQLState: 22001
    [ERROR] org.hibernate.engine.jdbc.spi.SqlExceptionHelper - Data truncation: Incorrect datetime value: '\xAC\xED\x00\x05sr\x00\x16org.joda.time.DateTime\xB8<xdj[\xDD\xF9\x02\x00\x00xr\x00\x1Forg.joda.time.base.BaseDateTime\xFF\xFF\x' for column 'bill_date' at row 1
    [ERROR] com.sample.aop.logging.LoggingAspect - Exception in com.sample.web.rest.InvoiceResource.create() with cause = org.hibernate.exception.DataException: could not execute statement
    org.springframework.dao.DataIntegrityViolationException: could not execute statement; SQL [n/a]; nested exception is org.hibernate.exception.DataException: could not execute statement
    	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.convertHibernateAccessException(HibernateJpaDialect.java:259) ~[spring-orm-4.1.7.RELEASE.jar:4.1.7.RELEASE]
    	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.translateExceptionIfPossible(HibernateJpaDialect.java:221) ~[spring-orm-4.1.7.RELEASE.jar:4.1.7.RELEASE]
    	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.translateExceptionIfPossible(AbstractEntityManagerFactoryBean.java:417) ~[spring-orm-4.1.7.RELEASE.jar:4.1.7.RELEASE]
    	at org.springframework.dao.support.ChainedPersistenceExceptionTranslator.translateExceptionIfPossible(ChainedPersistenceExceptionTranslator.java:59) ~[spring-tx-4.1.7.RELEASE.jar:4.1.7.RELEASE]
    	at org.springframework.dao.support.DataAccessUtils.translateIfNecessary(DataAccessUtils.java:213) ~[spring-tx-4.1.7.RELEASE.jar:4.1.7.RELEASE]
    	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:147) ~[spring-tx-4.1.7.RELEASE.jar:4.1.7.RELEASE]
    	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.1.7.RELEASE.jar:4.1.7.RELEASE]

Due to this error this particular record is not getting inserted, earlier when I don't have billDate CRUD operation is working fine. 

And in Invoce.java, I have

    import org.hibernate.annotations.Cache;
    import org.hibernate.annotations.CacheConcurrencyStrategy;
    import org.joda.time.DateTime;
    
    import javax.persistence.*;
    import java.io.Serializable;
    import java.util.HashSet;
    import java.util.Set;
    import java.util.Objects;
    
     @Column(name = "bill_date")
        private DateTime billDate;
    
    
    		public DateTime getBillDate() {
    			return billDate;
    		}
    
    		public void setBillDate(DateTime billDate) {
    			this.billDate = billDate;
    		}
    
    @Override
        public String toString() {
            return "Invoice{" +
                    "id=" + id +
                    ", accountNumber='" + accountNumber + "'" +
                    ", invoiceNumber='" + invoiceNumber + "'" +
                    ", invoiceAmount='" + invoiceAmount + "'" +
                    ", ediNumber='" + ediNumber + "'" +
                    ", status='" + status + "'" +
                    ", billDate='" + billDate + "'" +
                    '}';
        }
The following is shown in my browser console.

    POST http://localhost:8080/api/invoices?cacheBuster=1444330431628 500 (Internal Server Error)

    timestamp: 1444330431767, status: 500, error: "Internal Server Error",…}
    error: "Internal Server Error"
    exception: "org.springframework.dao.DataIntegrityViolationException"
    message: "could not execute statement; SQL [n/a]; nested exception is org.hibernate.exception.DataException: could not execute statement"
    path: "/api/invoices"
    status: 500
    timestamp: 1444330431767

I am not sure, whether it is problem with jhipster options for Date time while entity generation.

**Comment by mraible** [comment] 2015-10-08 21:12
I'd suggest modifying the unit test for your `InvoiceResource` class (it's called `InvoiceResourceTest`) to include a date. Once you've proved things worked from the Java side, it might be easier to fix the JavaScript -> Java translation.

**Comment by smart987** [comment] 2015-10-08 21:23
Yes @mraible,  Junit test InvoiceResourceTest is successful. 

[INFO] com.sample.web.rest.InvoiceResourceTest - Starting InvoiceResourceTest on kishore with PID 8333 (/home/mnkb/Development/git/sample/target/test-classes started by mnkb in /home/mnkb/Development/git/sample)
[DEBUG] com.sample.web.rest.InvoiceResourceTest - Running with Spring Boot v1.2.5.RELEASE, Spring v4.1.7.RELEASE
[DEBUG] com.sample.config.AsyncConfiguration - Creating Async Task Executor
[DEBUG] com.sample.config.MetricsConfiguration - Registering JVM gauges
[DEBUG] com.sample.config.DatabaseConfiguration - Configuring Datasource
[DEBUG] com.sample.config.DatabaseConfiguration - Configuring Liquibase
[DEBUG] com.sample.config.MailConfiguration - Configuring mail server
[WARN] com.sample.Application - No Spring profile configured, running with default configuration
[INFO] com.sample.config.WebConfigurer - Web application configuration, using profiles: []
[DEBUG] com.sample.config.WebConfigurer - Initializing Metrics registries
[DEBUG] com.sample.config.WebConfigurer - Registering Metrics Filter
[DEBUG] com.sample.config.WebConfigurer - Registering Metrics Servlet
[INFO] com.sample.config.WebConfigurer - Web application fully configured
[INFO] com.sample.config.ThymeleafConfiguration - loading non-reloadable mail messages resources
[DEBUG] com.sample.config.apidoc.SwaggerConfiguration - Starting Swagger
[DEBUG] com.sample.config.apidoc.SwaggerConfiguration - Started Swagger in 13 ms
[DEBUG] com.sample.config.CacheConfiguration - Starting Ehcache
[DEBUG] com.sample.config.CacheConfiguration - Registering Ehcache Metrics gauges
[INFO] com.sample.web.rest.InvoiceResourceTest - Started InvoiceResourceTest in 24.998 seconds (JVM running for 26.258)
Hibernate: insert into invoice (account_number, bill_date, edi_number, invoice_amount, invoice_number, status) values (?, ?, ?, ?, ?, ?)
[DEBUG] com.sample.web.rest.InvoiceResource - REST request to get Invoice : 17
[DEBUG] com.sample.web.rest.InvoiceResource - REST request to get Invoice : 9223372036854775807
Hibernate: select invoice0_.id as id1_11_0_, invoice0_.account_number as account_2_11_0_, invoice0_.bill_date as bill_dat3_11_0_, invoice0_.edi_number as edi_numb4_11_0_, invoice0_.invoice_amount as invoice_5_11_0_, invoice0_.invoice_number as invoice_6_11_0_, invoice0_.status as status7_11_0_ from invoice invoice0_ where invoice0_.id=?
Hibernate: select invoice0_.id as id1_11_, invoice0_.account_number as account_2_11_, invoice0_.bill_date as bill_dat3_11_, invoice0_.edi_number as edi_numb4_11_, invoice0_.invoice_amount as invoice_5_11_, invoice0_.invoice_number as invoice_6_11_, invoice0_.status as status7_11_ from invoice invoice0_
[DEBUG] com.sample.web.rest.InvoiceResource - REST request to save Invoice : Invoice{id=null, accountNumber='SAMPLE_TEXT', invoiceNumber='SAMPLE_TEXT', invoiceAmount='1.0', ediNumber='null', status='SAMPLE_TEXT', billDate='null'}
Hibernate: insert into invoice (account_number, bill_date, edi_number, invoice_amount, invoice_number, status) values (?, ?, ?, ?, ?, ?)
Hibernate: select invoice0_.id as id1_11_, invoice0_.account_number as account_2_11_, invoice0_.bill_date as bill_dat3_11_, invoice0_.edi_number as edi_numb4_11_, invoice0_.invoice_amount as invoice_5_11_, invoice0_.invoice_number as invoice_6_11_, invoice0_.status as status7_11_ from invoice invoice0_
Hibernate: insert into invoice (account_number, bill_date, edi_number, invoice_amount, invoice_number, status) values (?, ?, ?, ?, ?, ?)
Hibernate: select count(invoice0_.id) as col_0_0_ from invoice invoice0_
Hibernate: select invoice0_.id as id1_11_, invoice0_.account_number as account_2_11_, invoice0_.bill_date as bill_dat3_11_, invoice0_.edi_number as edi_numb4_11_, invoice0_.invoice_amount as invoice_5_11_, invoice0_.invoice_number as invoice_6_11_, invoice0_.status as status7_11_ from invoice invoice0_ limit ?
Hibernate: insert into invoice (account_number, bill_date, edi_number, invoice_amount, invoice_number, status) values (?, ?, ?, ?, ?, ?)
Hibernate: select invoice0_.id as id1_11_, invoice0_.account_number as account_2_11_, invoice0_.bill_date as bill_dat3_11_, invoice0_.edi_number as edi_numb4_11_, invoice0_.invoice_amount as invoice_5_11_, invoice0_.invoice_number as invoice_6_11_, invoice0_.status as status7_11_ from invoice invoice0_
[DEBUG] com.sample.web.rest.InvoiceResource - REST request to update Invoice : Invoice{id=20, accountNumber='UPDATED_TEXT', invoiceNumber='UPDATED_TEXT', invoiceAmount='2.0', ediNumber='null', status='UPDATED_TEXT', billDate='null'}
Hibernate: update invoice set account_number=?, bill_date=?, edi_number=?, invoice_amount=?, invoice_number=?, status=? where id=?
Hibernate: select invoice0_.id as id1_11_, invoice0_.account_number as account_2_11_, invoice0_.bill_date as bill_dat3_11_, invoice0_.edi_number as edi_numb4_11_, invoice0_.invoice_amount as invoice_5_11_, invoice0_.invoice_number as invoice_6_11_, invoice0_.status as status7_11_ from invoice invoice0_
Hibernate: insert into invoice (account_number, bill_date, edi_number, invoice_amount, invoice_number, status) values (?, ?, ?, ?, ?, ?)
Hibernate: select invoice0_.id as id1_11_, invoice0_.account_number as account_2_11_, invoice0_.bill_date as bill_dat3_11_, invoice0_.edi_number as edi_numb4_11_, invoice0_.invoice_amount as invoice_5_11_, invoice0_.invoice_number as invoice_6_11_, invoice0_.status as status7_11_ from invoice invoice0_
[DEBUG] com.sample.web.rest.InvoiceResource - REST request to delete Invoice : 21
Hibernate: delete from invoice where id=?
Hibernate: select invoice0_.id as id1_11_, invoice0_.account_number as account_2_11_, invoice0_.bill_date as bill_dat3_11_, invoice0_.edi_number as edi_numb4_11_, invoice0_.invoice_amount as invoice_5_11_, invoice0_.invoice_number as invoice_6_11_, invoice0_.status as status7_11_ from invoice invoice0_
[INFO] com.sample.config.CacheConfiguration - Remove Cache Manager metrics
[INFO] com.sample.config.CacheConfiguration - Closing Cache Manager

**Comment by mraible** [comment] 2015-10-08 21:36
Did you add this new field to your unit test before running it? When I post a timestamp from my AngularJS front-end, it looks like the following:

    timestamp: "2015-10-08T15:34:00.000Z"

**Comment by jdubois** [comment] 2015-10-08 21:38
We provide two date types: DateTime and LocalDate, which come from JodaTime -> which one are you using here, to generate this "timestamp" field in Liquibase? Can you send your JSON file (it's in the ".jhipster/" directory), so we can reproduce the error?

**Comment by smart987** [comment] 2015-10-09 01:30
The following is my liquibase entry:

<changeSet author="mnkb" id="20151008151559">
       <addColumn schemaName="sample"
            tableName="invoice">       
         <column name="bill_date" type="timestamp"/>
    </addColumn>
</changeSet>

**Comment by gmarziou** [comment] 2015-10-09 08:47
> The following is my JSON file , it contains only initially generated fields not the newly added fields.

So you mean you did not update it to add new fields and then re-generate the entity using `yo jhipster:entity` command?

If you did not know this, I think this is how you should have done it because it's the best way to know that you're forgotting something.

Here, it seems you've done your own changes and it could break for any reason as we don't see what you've done.

**Comment by deepu105** [comment] 2015-10-09 10:37
From the json it looks like you have manually done this. And the exception is dataIntegrityViolation have you put some constraints on the DB?
This doesn't look like a JH issue to me

**Comment by jdubois** [comment] 2015-10-09 10:37
There isn't a date field in your JSON file.... So of course it works...
I'm closing this ticket as it is not reproductible, please better follow our guidelines next time.

**Closed by jdubois** 2015-10-09 10:37 UTC
