### ISSUE TITLE
ngx-couchbase intermittent Test Failures

### ISSUE THREAD

**Issue by SudharakaP** [jhipster/generator-jhipster#10594] opened 2019-10-10 15:05 UTC
##### **Overview of the issue**

This issue was created from the discussion at https://github.com/jhipster/generator-jhipster/issues/10589. It seems that ngx-couchbase tests on our CI seems to hang and fail sometimes. Here are some examples;

https://github.com/jhipster/generator-jhipster/pull/10498/checks?check_run_id=254018117

https://dev.azure.com/jhipster/jhipster/_build/results?buildId=6316 

##### **Motivation for or Use Case**

Getting the CI tests in working condition without problems.

##### **Reproduce the error**

Submitting a PR or making a commit so that the CI is triggered might recreate the issue.

##### **Related issues**

#10589

##### **Suggest a Fix**

Currently not known.

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by SudharakaP** [comment] 2019-10-10 15:33
@vishal423 @pascalgrimaud : I've just noticed that couchbase runs on the [prod profile](https://github.com/jhipster/generator-jhipster/blob/1c968f569fe524703fd7173bad1be221925a513e/.github/workflows/applications.yml#L37). Is there a specific reason to do so? :smile:

**Comment by pascalgrimaud** [comment] 2019-10-10 15:43
The best would be to test both: dev and prod
But it would be too much configurations to test.

There are no specific reason, that `couchbase` is tested in `prod` profile.
It could be in `dev` and Cassandra could be in `prod`

**Comment by SudharakaP** [comment] 2019-10-10 15:48
@pascalgrimaud : That is indeed interesting; because when you run in dev it works; https://github.com/SudharakaP/generator-jhipster/runs/255327289 :thinking: 

Have to think more on why it runs correctly only in dev.

**Comment by pascalgrimaud** [comment] 2019-10-10 15:50
no idea. Never tested couchbase lol !

**Comment by SudharakaP** [comment] 2019-10-10 17:05
I can do some more tests today evening to find the root cause; but if someone wants to take this and fix it before that; please feel free to go ahead. 😄

**Comment by SudharakaP** [comment] 2019-10-11 09:33
@pascalgrimaud @vishal423 : I believe I found the problem here. It seems that the javadoc (via the maven javadoc plugin) runs on java 1.8.0_22; because we manually set JAVA_HOME in [`00-init-env.sh`](https://github.com/jhipster/generator-jhipster/blob/master/test-integration/scripts/00-init-env.sh). But notice that on Github Actions when Java 11 is installed (via the initial `setup-java@v1`) JAVA_HOME is already set to `/opt/hostedtoolcache/Java/11.0.3/x64` and this value is overwritten by our `00-init-env.sh` script and thus the javadoc ultimately uses the default java version installed in the build machine; which seems to be 1.8.0_22. 

What we need to do is for GitHub CI not change the JAVA_HOME value. I've done some tests with this and it works. I will do this modification to the current PR soon. :smile:

**Comment by vishal423** [comment] 2019-10-11 10:53
I am not very sure on this solution. However, if it solves current issue, then, there is no harm to try this out.

**Comment by SudharakaP** [comment] 2019-10-11 12:10
@pascalgrimaud : I've created a pull request for the daily builds as well to replace it with OpenJDK instead of the default [Zulu](https://www.azul.com/downloads/zulu-community/?&architecture=x86-64-bit&package=jdk). It seems to work in my [Azure builds](https://dev.azure.com/hipster-labs/jhipster-daily-builds/_build?definitionId=21).

@vishal423 : I don't think highly of this solution as well; but it does indeed seems to work; and my theory is that the JAVA_HOME needs to be set correctly when it comes to TestContainers. We shall see..... :thinking:

**Comment by vishal423** [comment] 2019-10-11 12:40
@SudharakaP, this theory doesn't explain on why it worked intermittently :smile:

**Comment by SudharakaP** [comment] 2019-10-11 12:57
@vishal423 : It does not. Then again it is also difficult to exactly predict what would happen when we set JAVA_HOME to something and use some other JDK in the CI. Therefore regardless whether the change fixes this issue completely or not; I think it should be made just so we use the same JDK for everything and JAVA_HOME is set property.

**Comment by SudharakaP** [comment] 2019-10-12 03:47
I was looking at these Couchbase issues more to find out the exact underlying problem; mainly because I felt there's something I am missing that is fundamentally common to both our daily builds problem and this one. 

I found that we handle the docker image startup differently for Couchbase. I think the main problem lies in [20-docker-compose.sh](https://github.com/jhipster/generator-jhipster/blob/972e0632bd3b0e16a3907ad2c4199e5319a069c1/test-integration/scripts/20-docker-compose.sh#L28) where we use a different logic only building the image for Couchbase not starting it. This results in the following stack trace for  both here and on the daily builds; 

![image](https://user-images.githubusercontent.com/12435965/66694239-46ca6780-ec66-11e9-85b8-aa9769ab2252.png)

As seen there's not docker container up and running. This I believe is one of the things we should address for both of these CI pipelines. 

@pascalgrimaud : Is there a specific reason that we are not able to use the CouchBase docker container like the others? I see the comment in [20-docker-compose.sh](https://github.com/jhipster/generator-jhipster/blob/972e0632bd3b0e16a3907ad2c4199e5319a069c1/test-integration/scripts/20-docker-compose.sh#L28) which suggests that the image is only built but not started due to problems with tests. However in my Github CI, I don't see any problems with running it; https://github.com/SudharakaP/generator-jhipster/runs/257408009

**Comment by pascalgrimaud** [comment] 2019-10-12 06:27
if I remember well, the problem with Couchbase was:
- if you started the Couchbase database with docker-compose file, then, launch backend tests, it will fail as testcontainer will use the same port and can't start
- it's not nice for the developer experience, but it was like this
- it was probably 1 year ago, when Couchbase support was introduced, I don't know if it has been changed or not

**Comment by SudharakaP** [comment] 2019-10-12 06:57
@pascalgrimaud : Thanks for the clarification. So as you might have seen, with [my recent change to OpenJDK](https://github.com/hipster-labs/jhipster-daily-builds/pull/20) the [Java 8 build is now successful](https://dev.azure.com/hipster-labs/jhipster-daily-builds/_build/results?buildId=6320). 

So I believe we've found a workaround without starting the Couchbase database with docker-compose. Is this good enough? Or we can also give it a try to reintroduce the docker-compose method of starting Couchbase since I don't see any failures in that method (at least in my Github CI; https://github.com/SudharakaP/generator-jhipster/runs/257408009). Maybe as you said Couchbase has changed since then. This solution would be more elegant and if we could make it work should work for both the daily build and here. However if we plan to do this we need to do some tests as I've noticed that sometimes things work on my Github CI but not in the JHipster CI pipeline.

**Comment by pascalgrimaud** [comment] 2019-10-12 07:10
My goal was to start all docker container before e2e, to speed up the builds
About Couchbase, if we can start the container before the tests, so yes, we should be consistent with other builds

**Comment by SudharakaP** [comment] 2019-10-12 07:30
@pascalgrimaud : Okay how about this. I will do a PR just putting back the code to start Couchbase database with docker-compose. I think this should work, since I don't understand why it wouldn't if it works on my [fork's Github CI pipeline](https://github.com/SudharakaP/generator-jhipster/runs/257408009). We give it some time to see if it creates any problems, and if it doesn't work we revert that commit to fall back to this one. WDYT? :smile:

**Comment by pascalgrimaud** [comment] 2019-10-12 08:06
yes, let's try !

**Comment by SudharakaP** [comment] 2019-10-12 16:58
@pascalgrimaud : I've done three PRs. In the first two I've made OpenJDK 8 the default on Azure pipelines. Given our experience with Couchbase I don't think the Azul JDK that ships with Azure can be trusted, and we should test everything with OpenJDK. 

My third PR reintroduces Couchbase docker start. We'll merge this and see how it goes. In the worst case we can just revert it back so that everything will work as usual :smile:

**Comment by SudharakaP** [comment] 2019-10-13 01:32
@pascalgrimaud : As you see the couchbase problem is reoccurring. However some of my investigation suggest that its not related to the docker container start but rather the PR,  #10608. Could you please revert #10608 ?

**Comment by SudharakaP** [comment] 2019-10-13 05:37
@pascalgrimaud : I've done the revert pull request. :smile:

**Comment by pascalgrimaud** [comment] 2019-10-13 13:14
I'm reopening this, as we don't have the real reason of the failures

See https://twitter.com/whichrich/status/1183348440803221504?s=19

I'll priorize it and will investigate.

**Comment by SudharakaP** [comment] 2019-10-13 14:08
@pascalgrimaud : Yes, it seems that #10614 gives doesn't work either I believe since the intermittent problem has reoccurred. So we'll revert this too if you don't mind; #10614

This will in my opinion give a stable build (with the workaround).

**Comment by pascalgrimaud** [comment] 2019-10-13 19:31
Just tried tonight and I manage to reproduce the issue only 1 time.
Then, in Azure Daily builds:
- with OpenJDK8, it's KO -> https://dev.azure.com/hipster-labs/jhipster-daily-builds/_build/results?buildId=6338&view=logs&j=14ecf143-eece-5d03-88de-b4dd986b4ce4
- with OpenJDK11, it's OK -> https://dev.azure.com/hipster-labs/jhipster-daily-builds/_build/results?buildId=6337&view=logs&j=14ecf143-eece-5d03-88de-b4dd986b4ce4

cc @tchlyah if you can help here
For me, I gave up, as I'm not a Couchbase user

**Comment by pascalgrimaud** [comment] 2019-10-13 19:32
If it's not fixed, another solution would be to simply remove Couchbase builds from official CI here.

**Comment by SudharakaP** [comment] 2019-10-13 19:37
@pascalgrimaud : The [one that failed yesterday (which you quoted)](https://dev.azure.com/hipster-labs/jhipster-daily-builds/_build/results?buildId=6338&view=logs&j=14ecf143-eece-5d03-88de-b4dd986b4ce4) I think doesn't count since it's caused by our testing, #10609. Just to make it absolutely clear, can we restart that build several times to see if it happens again?

**Comment by pascalgrimaud** [comment] 2019-10-13 19:39
Ok, restarting the Official.openjdk8 right now

**Comment by SudharakaP** [comment] 2019-10-14 01:46
@pascalgrimaud : So it seems my fix on the Azure pipeline with JDK 8 didn't work; it's still flaky. I will try to recreate this issue on the testcontainers couchbase module itself to see if we can find the problem. :smile:

**Comment by SudharakaP** [comment] 2019-10-16 03:36
@pascalgrimaud : I've done a number of tests with Java 8 related to Couchbase and it seems to be the Java 8 failure is due to Couchbase container not starting up correctly. 

If you aren't fed up with my requests to restart the daily build could you please merge the above change and restart it. :smile: I have a strong feeling this will work. :smile:

**Comment by SudharakaP** [comment] 2019-10-16 04:47
@pascalgrimaud : I have done a number of tests on Couchbase with JDK 8 and it seems to me that the culprit here is a Couchbase not starting due to memory for the container not being adequate. 

I've created a PR above and if you aren't too tired with my countless requests to restart the daily builds; could you please merge that and restart it. :smile: :smile_cat:

**Comment by pascalgrimaud** [comment] 2019-10-16 05:04
@SudharakaP : do you want me to merge #10628, then restart the daily builds for OpenJDK8.Official ? Am I correct ?

**Comment by SudharakaP** [comment] 2019-10-16 05:14
@pascalgrimaud : Correct. :+1:

**Comment by vishal423** [comment] 2019-10-16 06:32
@SudharakaP, I have noticed a few things while looking into this failure (maybe these can help):
1. Couchbase added Ubuntu 18.04 support in the `v6.0.1`. It would be good to try to upgrade the couchbase image (considering we already have `18.04` in our build infrastructure). I do see some couchbase image upgrade attempts by @DanielFran, but, not sure on why they were reverted.
2. Couchbase has recently released `v6.0.3`. We can try to see if that helps to improve the situation on this part.
3. Every time the build stalled, I have observed below message:

> {"app_name":"travisCouchbaseNoCache","app_port":"-1","level":"WARN","logger_name":"c.c.c.c.e.Endpoint","message":"[localhost:32775][KeyValueEndpoint]: Authentication Failure: Bucket not found on Select Bucket command","thread_name":"cb-io-1-2","timestamp":"2019-10-16T03:40:25.596Z"}

4. I believe test container support was tested with couchbase `v5.5.1`. I don't see any change on that part, so, not very sure if that code will work flawlessly with the latest couchbase images.

**Comment by pascalgrimaud** [comment] 2019-10-16 06:43
@SudharakaP : the first run failed :-(

**Comment by DanielFran** [comment] 2019-10-16 09:31
@vishal423 I try to upgrade to this version but it was not working...

**Comment by SudharakaP** [comment] 2019-10-16 11:23
@vishal423 : Thanks for the information. :smile: Let me try those; but I am baffled, because I could recreate this scenario on my CI where for Java 8 it fails intermittently. It used to fail for Java 11 as well but the JAVA_HOME seems to have fixed it. Then I increased the `memoryQuota` and it started running successfully not only just once but almost all the time (I attempted like 10 times and all were successful). As soon as I made a pull request it fails. Its quite an interesting problem. Let me try your suggestions to see if we can do something.

**Comment by SudharakaP** [comment] 2019-10-16 13:09
@pascalgrimaud : We'll do some incremental changes; 

As @vishal423 suggested. 

>     1. Couchbase added Ubuntu 18.04 support in the `v6.0.1`. It would be good to try to upgrade the couchbase image (considering we already have `18.04` in our build infrastructure). I do see some couchbase image upgrade attempts by @DanielFran, but, not sure on why they were reverted.

However I see a dependency here. On Github CI we run Couchbase on `ubuntu-latest` but on Azure Java 8 we run it on `Ubuntu 16.04`. I've created a pull request to update Azure to be the same as our Github CI. If this doesn't work I'll look into upgrading the Couchbase images.

**Comment by SudharakaP** [comment] 2019-10-16 23:21
@pascalgrimaud : I have a more refined fix after investigating thoroughly what @vishal423 mentioned in his third point; I didn't notice this before. Thanks @vishal423 ðŸ˜„ ðŸ˜„ 

>Every time the build stalled, I have observed below message:
{"app_name":"travisCouchbaseNoCache","app_port":"-1","level":"WARN","logger_name":"c.c.c.c.e.Endpoint","message":"[localhost:32775][KeyValueEndpoint]: Authentication Failure: Bucket not found on Select Bucket command","thread_name":"cb-io-1-2","timestamp":"2019-10-16T03:40:25.596Z"}

Searching through the internet I found this; https://forums.couchbase.com/t/java-sdk-can-not-access-query-node-in-couchbase-5-0/14855 which I believe seems to be our issue (or at least part of it). Now notice that [we use `com.couchbase.client` version 2.5.9](https://docs.spring.io/platform/docs/current/reference/htmlsingle/#appendix-dependency-versions) which leads to the following fix; https://issues.couchbase.com/browse/JVMCBC-564. This change went live in version 2.6.2 as per; https://docs.couchbase.com/java-sdk/current/sdk-release-notes.html#version-2-5-1-3-october-2017

Therefore I've created the above pull request updating our couchbase java-client version. 😄 

Please feel free to merge this and we can do some testing as before when you have time. 😄 😄

**Comment by DanielFran** [comment] 2019-10-16 23:51
@SudharakaP Are you downgrading the couchbase java-client version?
The dependency is already defined in jhipster bom project : see https://github.com/jhipster/jhipster/blob/master/jhipster-dependencies/pom.xml#L274
Current version defined is 2.7.9 : https://github.com/jhipster/jhipster/blob/master/jhipster-dependencies/pom.xml#L46

**Comment by SudharakaP** [comment] 2019-10-17 00:05
@DanielFran : Thanks for pointing out; you are correct. I didn't even knew we had a separate repository for the dependency versions. Closed the Pull request. 😕

**Comment by SudharakaP** [comment] 2019-10-17 04:44
Digging deeper on my [previous comment](https://github.com/jhipster/generator-jhipster/issues/10594#issuecomment-542930656); I realized that the log 

>Every time the build stalled, I have observed below message:
{"app_name":"travisCouchbaseNoCache","app_port":"-1","level":"WARN","logger_name":"c.c.c.c.e.Endpoint","message":"[localhost:32775][KeyValueEndpoint]: Authentication Failure: Bucket not found on Select Bucket command","thread_name":"cb-io-1-2","timestamp":"2019-10-16T03:40:25.596Z"}

actually doesn't come from one of our direct dependencies. In fact this seems to be a side effect of us using [`com.github.differentway:couchmove`](https://github.com/differentway/couchmove). Notice that in couchmove [`couchbase.client` version 2.5.7 is used](https://github.com/differentway/couchmove/blob/a1c8ddbe30aa09447ea03edc152f24228b565ad9/pom.xml#L12). 

This probably explains everything; whatever we do there was no consistency in either Java 11 or Java 8 couchbase working. Java 11 works fairly consistently but it still seems to break at times. 

@tchlyah : Can we upgrade to `couchbase.client` to version 2.6.2 on couchmove to get rid of [JVMCBC-564](https://docs.couchbase.com/java-sdk/current/sdk-release-notes.html#version-2-6-2-4-september-2018)? I can do a pr if you'd like. :smile:

**Comment by tchlyah** [comment] 2019-10-20 16:52
Hello, sorry guys I couldn't reproduce the problem in my end, I've updated Couchmove and Couchbase image version, but I don't think it will change anything

**Comment by SudharakaP** [comment] 2019-10-20 17:12
@tchlyah : Thanks for trying though; we'll know for sure when the [daily builds](https://dev.azure.com/hipster-labs/jhipster-daily-builds/_build?definitionId=21&_a=summary) run several times. :smile: Did you try with Java 8? This is where it fails; java 11 works almost all the time with our recent changes. 

Also have a feeling this might be related to a timeout similar to https://github.com/testcontainers/testcontainers-java/issues/715; which I've pointed out in; https://github.com/testcontainers/testcontainers-java/issues/1453#issuecomment-541930826. Do you think this might be worth trying. I could do a pull request on that repository if you think this is worthwhile. :smile:

**Comment by pascalgrimaud** [comment] 2019-10-20 18:06
I'm reopening this, and wait few days our daily builds before closing this definitely

**Comment by SudharakaP** [comment] 2019-10-21 13:53
@pascalgrimaud : I noticed that yesterday the [Official.JDK8 scheduled build](https://dev.azure.com/hipster-labs/jhipster-daily-builds/_build?definitionId=21) didn't run for some reason. :thinking: :thinking:

**Comment by pascalgrimaud** [comment] 2019-10-21 14:44
I'm restarting it, as you need to see the result, right ?

**Comment by SudharakaP** [comment] 2019-10-21 15:02
@pascalgrimaud : Thanks for restarting. I was just curious why it didn't start in the first place. :smile:

**Comment by SudharakaP** [comment] 2019-10-31 19:04
After our fixes and upgrading to Ubuntu 18, Java 8 builds are fairly stable now I believe; although I think once in a while you might see a failure (this is common to Java 11 couch-base as well). Notice that in the final 8 runs in our daily builds only 1 time the couch-base tests timed out; this is the same as our Github CI builds (which also timed out once during the last 7 or 8 runs). 

Also I am not sure about the linked issue;  https://github.com/testcontainers/testcontainers-java/issues/1453 addresses our exact issue; I think there's multiple points of failures in the test-containers couch-base module. 

Given the reasonably stable nature, maybe we should close this issue off? Or is there anything we could do more?

**Comment by pascalgrimaud** [comment] 2019-10-31 19:10
Ok, let's close this.
Plz @SudharakaP, claim the bounty, it's well deserved !

**Closed by pascalgrimaud** 2019-10-31 19:10 UTC
Labels: $$ bug-bounty $$, $100, Hacktoberfest, area: bug :bug:, theme: couchbase

**Comment by SudharakaP** [comment] 2019-11-01 06:35
@pascalgrimaud : Submitted at https://opencollective.com/generator-jhipster/expenses/11269/?createSuccess=true
