### ISSUE TITLE
command `jhipster jdl ..\order\src\main\jdl\order.jdl` would drop id column of tables

### ISSUE THREAD

**Issue by flyliu33** [jhipster/generator-jhipster#27646] opened 2024-10-22 03:31 UTC
##### **Overview of the issue**

1. command `jhipster jdl ..\order\src\main\jdl\order.jdl` would drop id column of tables

no error threw
##### **Motivation for or Use Case**

I try to use command `jhipster jdl ..\order\src\main\jdl\order.jdl` for generating liquibase. but it will create drop `id` changelog after modifying my jdl files. so I prefer to use `jhipster jdl ..\order\src\main\jdl\order.jdl   --skip-db-changelog` for generating backend code and then using `./mvnw compile liquibase:diff` for generating liquibase changelog, though it doesn't seem more reasonable.
##### **Reproduce the error**
1. generating liquibase changelog by command `jhipster jdl`
3. run the backend application and create a table
4. stop the backend application
5. modify the jdl file
6. regenerating by command `jhipster jdl`

##### **JHipster Version(s)**
8.7.1

##### **JHipster configuration**

To provide all information we need, you should run `jhipster info` in the project root folder (or workspaces root for microservices), and
copy/paste the result here.
`jhipster info` removes sentitive information like rememberKey, jwtSecretKey. Double check if there is any other sensitive info.

As alternative you can add a JDL wrapped in below structure

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "applicationType": "microservice",
    "authenticationType": "jwt",
    "baseName": "order",
    "buildTool": "maven",
    "cacheProvider": "redis",
    "clientFramework": "no",
    "clientTestFrameworks": null,
    "clientTheme": null,
    "creationTimestamp": 1726891146771,
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "enableHibernateCache": true,
    "enableSwaggerCodegen": true,
    "enableTranslation": false,
    "entities": [
      "Company",
      "Order",
      "ParkingLot"
    ],
    "feignClient": true,
    "incrementalChangelog": true,
    "jhipsterVersion": "8.7.1",
    "lastLiquibaseTimestamp": 1729478625000,
    "messageBroker": "kafka",
    "microfrontend": null,
    "microfrontends": [],
    "nativeLanguage": "zh-cn",
    "packageName": "com.pu.order",
    "prodDatabaseType": "mysql",
    "reactive": false,
    "searchEngine": false,
    "serverPort": "8082",
    "serverSideOptions": [
      "messageBroker:kafka",
      "enableSwaggerCodegen:true"
    ],
    "serviceDiscoveryType": "consul",
    "skipClient": true,
    "skipUserManagement": true,
    "syncUserWithIdp": null,
    "testFrameworks": [
      "gatling"
    ],
    "websocket": false,
    "withAdminUi": null
  }
}
</pre>
</details>

##### **Environment and Tools**

openjdk version "17.0.12" 2024-07-16 LTS
OpenJDK Runtime Environment Corretto-17.0.12.7.1 (build 17.0.12+7-LTS)
OpenJDK 64-Bit Server VM Corretto-17.0.12.7.1 (build 17.0.12+7-LTS, mixed mode, sharing)

git version 2.45.1.windows.1

node: v20.17.0
npm: 10.8.2

Docker version 27.1.1, build 6312585

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
/**
 * Company
 */
@ChangelogDate("20241018060451")
entity Company {
  id UUID
  name String
  contact String
}

/**
 * Order
 */
@ChangelogDate("20241018060452")
entity Order (jhi_order) {
  id UUID
  /**
   * Parking type, 0: Street parking, 1: Gated parking
   */
  parkType ParkType required
  /**
   * Order number
   */
  orderNo String required maxlength(32)
  /**
   * Stall number, required when parkType=0
   */
  stallNo String maxlength(32)
  /**
   * License plate number, format like [粤S12345] or new energy [粤S123456]
   */
  licensePlate String required maxlength(8)
  /**
   * Order amount in cents
   */
  orderAmount Long required min(1)
  /**
   * Multiple image files, supports jpg, jpeg and png, max 10M per file
   */
  file String
  /**
   * Entry/exit lane code, choose between this and license plate number
   */
  laneNo String maxlength(32)
  /**
   * Platform transaction order number, linking multiple merchant orders
   */
  dealNo String maxlength(32)
  /**
   * Customer number
   */
  customerNo String maxlength(32)
  /**
   * Actual amount received in cents
   */
  realAmount Long min(1)
  /**
   * Platform service fee in cents
   */
  platformFee Long min(1)
  /**
   * Assistance service fee in cents
   */
  assistFee Long min(1)
  /**
   * Payment status, 0: Unpaid, 1: Payment successful, 2: Payment failed
   */
  payState PayState required
  /**
   * Platform order number
   */
  platformNo String maxlength(15)
  /**
   * Creation time
   */
  createTime LocalDate
  /**
   * Entry time
   */
  entryTime LocalDate
  /**
   * Payment time
   */
  payTime LocalDate
  /**
   * Exit deadline
   */
  exitDeadline LocalDate
  /**
   * Exit time
   */
  exitTime LocalDate
}

/**
 * Parking Lot
 */
@ChangelogDate("20241018060453")
entity ParkingLot {
  id UUID
  parkNo String
  name String
  capacity Integer
}

enum ParkType {
  ROAD,
  ENCLOSE
}

enum PayState {
  UNPAY,
  PAYED,
  FAILED
}

relationship OneToMany {
  /**
   * Creditor company
   */
  Company{company} to Order{company}
  /**
   * Assisting company
   */
  Company{assistCompany} to Order{assistCompany}
  /**
   * Parking lot
   */
  ParkingLot{order} to Order{parkingLot}
}

paginate Company, Order, ParkingLot with infinite-scroll
search Company, Order, ParkingLot with no
microservice Company, Order, ParkingLot with Order
clientRootFolder Company, Order, ParkingLot with Order

</pre>
</details>

The information is mandatory for bug reports. This will allow us to use automated tests and genarate the broken sample using `jhipster from-issue` command.

##### **Browsers and Operating System**
Edition	Windows 11 Pro
Version	23H2
Installed on	‎8/‎19/‎2024
OS build	22631.4317
Experience	Windows Feature Experience Pack 1000.22700.1041.0

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment] 2024-10-22 14:21
You have `incrementalChangelog` enabled which generates new changelogs on jdl changes.
You can disable using `--no-incremental-changelog`.

**Comment by flyliu33** [comment] 2024-10-23 09:07
Thanks for correct, but `jhipster jdl order.jdl ` still will generate the drop id changelog after modifying `order.jdl`
```
<?xml version="1.0" encoding="utf-8"?>
<databaseChangeLog
    xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
    xmlns:ext="http://www.liquibase.org/xml/ns/dbchangelog-ext"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-latest.xsd
                        http://www.liquibase.org/xml/ns/dbchangelog-ext http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-ext.xsd">

    <!--
        Dropped columns to the entity Company.
    -->
    <changeSet id="20241023090337-1-drop-columns" author="jhipster">
        <dropColumn tableName="company">
            <column name="id"/>
        </dropColumn>
    </changeSet>

    <!-- jhipster-needle-liquibase-add-changeset - JHipster will add changesets here -->

</databaseChangeLog>
```

**Comment by mshima** [comment] 2024-10-29 22:39
`dropColumn` will only be generated if incremental changelog is enabled.
Please check if
```
"incrementalChangelog": true,
```

Has changed to false in your .yo-rc.json.

Closing since reproduction steps are missing the original jdl and the modified jdl.

**Closed by mshima** 2024-10-29 22:39 UTC
Labels: area: triage, theme: undefined

**Comment by mgcnrx11** [comment] 2025-11-11 07:35
## Root Cause

  - The incremental diff in generators/base-entity-changes/generator.ts (lines 128‑143) filters out any field whose object has field.id === true. It does not look at the field name. Your `.jhipster/XX.json` shows id as a normal field without an id flag, so it survives the filter and ends up in removedFields.
  - When JDL is imported (generators/jdl/generator.ts → lib/jdl/jdl-importer.ts), each field is created by lib/jdl/converters/parsed-jdl-to-jdl-object/field-converter.ts. That converter just lowercases the  name/type. The only way to mark a field as a primary key is via an annotation, e.g. @id, which convertAnnotationsToOptions turns into field.options.id = true.
  - During the JDL→JSON conversion (lib/jdl/converters/jdl-to-json/jdl-to-json-field-converter.ts), those options are emitted verbatim under field.options. Nothing in the importer ever sets field.id automatically for a field named "id".

## When the generator later loads entities

  - Before diffing, loadEntitiesAnnotations in generators/base-application/support/relationship.ts copies field.options onto the field object. Only if the JSON field had options.id will this step result in `field.id = true`.
  - Because your .jhipster file never contained options.id, the merge step has nothing to copy, so field.id stays undefined, and the diff logic treats the column like any other user-defined column.

## Why the JSON lacks options.id

  - prepareEntityPrimaryKeyForTemplates (generators/base-application/support/prepare-entity.ts, lines 287‑334) sets field.id = true on a field named id right before templates are rendered so the code can compile, but this derived property is not persisted back into .jhipster.
  - Therefore, unless you explicitly author the JDL as @id id String ..., the importer never records the id flag, and subsequent incremental runs keep seeing that field as a regular column.

## What to do

  - In your JDL, mark the custom identifier with @id (and any other PK-related annotations such as @autoGenerate or @dbPrimaryKey if needed):

```
    entity Credential {
      @id id String required
      ...
    }
```
 
  - After re-importing, the generated .jhipster/XX.json will contain "options": { "id": true } for that field. When loadEntitiesAnnotations runs, it sets field.id = true, so the incremental diff excludes it from addedFields/removedFields, and you won’t get the unwanted drop ..._id change set anymore.

**Comment by mshima** [comment] 2025-11-12 13:59
@mgcnrx11 thanks for the analysis, if you have a simple way to reproduce, please share.
