### ISSUE TITLE
Jhipster is not generating my entites

### ISSUE THREAD

**Issue by Meriem19** [jhipster/generator-jhipster#3533] opened 2016-05-04 16:40 UTC
##### **Overview of the issue**

I'm running the app after i've generated it, but the entities that i've created does'nt exist in mySQL database, but the jhi_user, jhi_authority, jhi_user_authority.. are there :/

##### **Motivation for or Use Case** 

I can't move on with my app without having those entities.

##### **JHipster Version(s)** 
v3.1.0

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 

` "generator-jhipster": {
    "jhipsterVersion": "3.1.0",
    "baseName": "Banking",
    "packageName": "org.isi",
    "packageFolder": "org/isi",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": "no",
    "buildTool": "maven",
    "enableSocialSignIn": true,
    "rememberMeKey": "25370fb6c1d5d2626221837a8b35cbac45fc26c4",
    "useSass": true,
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "fr"
    ]
  }
}`
##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory** 
the entities.json are all there. i've using JDL

##### **Browsers and Operating System** 
windows 7

**Comment by jdubois** [comment] 2016-05-04 18:34
Did you try `jhipster --force --with-entities` ?
Otherwise please send more information, like your error logs -> I'm closing this as I don't have enough information to reproduce

**Closed by jdubois** 2016-05-04 18:34 UTC

**Comment by Meriem19** [comment] 2016-05-05 08:35
How to force ? 
No errors while runing, in the liquibase all is there, it's seems like no probleme, but once I try to call the API of the entity from the app, this comes out 

`2016-05-05 09:32:18.561  WARN 4804 --- [nio-8080-exec-5] o.h.engine.jdbc.spi.SqlExceptionHelper   : SQL Error: 1146, SQLState: 42S02
2016-05-05 09:32:18.563 ERROR 4804 --- [nio-8080-exec-5] o.h.engine.jdbc.spi.SqlExceptionHelper   : Table 'banking.client' doesn't exist
2016-05-05 09:32:18.733 ERROR 4804 --- [nio-8080-exec-5] org.isi.aop.logging.LoggingAspect        : Exception in org.isi.service.ClientService.findAll() with cause = {} and exception {}

org.springframework.dao.InvalidDataAccessResourceUsageException: could not extract ResultSet; SQL [n/a]; nested exception is org.hibernate.exception.SQLGrammarException: could not extract ResultSet`

**Comment by Meriem19** [comment] 2016-05-05 08:45
How to force ?
No errors while runing, in the liquibase all is there, it's seems like no
probleme, but once I try to call the API of the entity from the app, this
comes out

`2016-05-05 09:32:18.561 WARN 4804 --- [nio-8080-exec-5]
o.h.engine.jdbc.spi.SqlExceptionHelper : SQL Error: 1146, SQLState: 42S02
2016-05-05 09:32:18.563 ERROR 4804 --- [nio-8080-exec-5]
o.h.engine.jdbc.spi.SqlExceptionHelper : Table 'banking.client' doesn't
exist
2016-05-05 09:32:18.733 ERROR 4804 --- [nio-8080-exec-5]
org.isi.aop.logging.LoggingAspect : Exception in
org.isi.service.ClientService.findAll() with cause = {} and exception {}

org.springframework.dao.InvalidDataAccessResourceUsageException: could not
extract ResultSet; SQL [n/a]; nested exception is
org.hibernate.exception.SQLGrammarException: could not extract ResultSet`

2016-05-04 19:34 GMT+01:00 Julien Dubois <notifications@github.com>:

**Comment by jdubois** [comment] 2016-05-05 09:09
You have the XML changelogs for your database tables? Are those tables created at startup? Did you create them using "yo jhispter:entity" or "mvn liquibase:diff"?

**Comment by Meriem19** [comment] 2016-05-05 09:26
yes i have the xml changelogs, i created them using jdl file

**Comment by jdubois** [comment] 2016-05-05 09:27
And do you have the tables in your database?

**Comment by Meriem19** [comment] 2016-05-05 09:29
I've only the jhi_tables

**Comment by jdubois** [comment] 2016-05-05 09:33
Then you had a liquibase error, it didn't say anything in your logs at startup?
Are you sure your changelogs are referenced in your master.xml file? They should have been automatically added.

**Comment by Meriem19** [comment] 2016-05-05 09:40
in my master.xml NO, there're no changelogs, but in the changelog folder, the entity_added.xml are all there.

**Comment by jdubois** [comment] 2016-05-05 09:42
Then that's where the issue is, the changelogs should have been added to your master.xml file. It does it automatically, so I guess you rollbacked this master.xml, or something similar.
You need to add the files in it, a "jhipster --force --with-entities" will do it automatically.

**Comment by deepu105** [comment] 2016-05-05 09:45
Or you removed the placeholder needle comment from master.xml

Thanks & Regards,
Deepu

**Comment by jdubois** [comment] 2016-05-05 09:46
Oh yes good catch @deepu105

**Comment by Meriem19** [comment] 2016-05-05 10:13
thanks @jdubois ;) the jhipster --force --with-entities solved my issue :+1:

**Comment by AlperMulayim** [comment] 2018-05-03 15:27
Dear  Dubois , 
I generate the jhipster  however  jhipster template cannot create the H2 database , JHI_USER not found exception on handling. When I look to the h2-console there is not a table.
I tried generation with jhipster --force --with-entities also , but it does not work for me. 
Is there any solution ? 
Regards.

**Comment by jdubois** [comment] 2018-05-03 15:31
Please don't spam us on an old ticket, please follow our guidelines at https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md

**Comment by AlperMulayim** [comment] 2018-05-03 15:44
It does not a spam i ask a question

Alper MÜLAYİM
Gebze Teknik Üniversitesi

2018-05-03 18:31 GMT+03:00 Julien Dubois <notifications@github.com>:

**Comment by deepu105** [comment] 2018-05-03 18:12
@AlperMulayim we are not discouraging you, but in order for us to help you please help us by following our process and creating issues with all the required details.

**Comment by furtivusMaj** [comment] 2018-07-18 18:15
Thank you so much for this thread @Meriem19  and @jdubois 
jhipster --force --with-entities
worked just fine with me after hours of regenerating projects and trying to find a solution. :smile:

**Comment by jdubois** [comment] 2018-07-18 19:24
@furtivusMaj may the --force be with you!
