### ISSUE TITLE
Generated liquibase file for entity constraints is referring to entity name not table name.

### ISSUE THREAD

**Issue by chegola** [jhipster/generator-jhipster#3875] opened 2016-07-22 22:56 UTC
##### **Overview of the issue**

By default JHipster will generate a table name based on your entity name, I have used option --table-name <table_name> and construct many-to-one relationship. However a generated liquibase file for entity constraints is referring to entity name not table name. Could you please review this is a bug or not?
##### **Motivation for or Use Case**

There is a requirement to use table name which is different from entity name.
##### **Reproduce the error**

1. run yo jhipster:entity testA --table-name t_testA. 
2. run yo jhipster:entity testB --table-name t_testB
3. inside testB, construct many-to-one to entity testA
Generated liquibase file 20160101_added_entity_constraints_TestB.xml will looks like this

  addForeignKeyConstraint baseColumnNames="testA_id"
                                 baseTableName="t_testB"
                                 constraintName="fk_testB_testA_id"
                                 referencedColumnNames="id"
                                 **referencedTableName="testA"**

As you can see the last bit, referencedTableName should refer to t_testA which is table name not testA.

##### **JHipster Version(s)**
3.4.2

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**
{
  "generator-jhipster": {
    "jhipsterVersion": "3.4.2",
    "baseName": "test",
    "packageName": "com.test",
    "packageFolder": "com/test",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": "no",
    "buildTool": "maven",
    "enableSocialSignIn": true,
    "jwtSecretKey": "b4d9668bee61f226723481012486a1cc5bb58d2f",
    "useSass": false,
    "applicationType": "monolith",
    "testFrameworks": [
      "cucumber",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "zh-tw"
    ]
  },
  "generator-jhipster-entity-audit": {
    "auditFramework": "custom"
  }
}

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**
{
    "relationships": [
        {
            "relationshipName": "testA",
            "otherEntityName": "testA",
            "relationshipType": "many-to-one",
            "otherEntityField": "id"
        }
    ],
    "fields": [
        {
            "fieldName": "test",
            "fieldType": "String"
        }
    ],
    "changelogDate": "20160722222546",
    "dto": "no",
    "service": "no",
    "entityTableName": "te_newtable",
    "pagination": "no",
    "enableEntityAudit": false
}

##### **Browsers and Operating System**

Windows7 and browser Chrome

**Comment by deepu105** [comment] 2016-07-23 05:50
Duplicate of #3723

**Closed by deepu105** 2016-07-23 05:50 UTC
