### ISSUE TITLE
QueryDsl + gradle not working

### ISSUE THREAD

**Issue by szabobar** [jhipster/generator-jhipster#5442] opened 2017-03-20 14:32 UTC
Dear JHipster,

I use the latest jhipster docker image (jhipster/jhipster:latest), and I would like to add QueryDsl feature in my new project.

I followed the https://jhipster.github.io/tips/003_tip_add_querydsl_support.html page about how to enable it, but this page is outdated, not worked for me, I got a class not found exception (java.lang.NoClassDefFoundError: com/querydsl/apt/AbstractQuerydslProcessor)
So I use the newer version of the plugin,

Now this is my gradle file:

> buildscript {
    ...
    dependencies {
        ...
    	classpath "gradle.plugin.com.ewerk.gradle.plugins:querydsl-plugin:1.0.8"
    }
}
apply plugin: "com.ewerk.gradle.plugins.querydsl"
querydsl {
   springDataMongo = true
}
dependencies {
...
compile "com.querydsl:querydsl-mongodb"
}

Now the compiler found the domains, and generated the Q classes, but now I got this exception:

> jhipster@c41c25d4226b:~/app$ ./gradlew clean build
:cleanQuerydslSourcesDir
:clean
:cleanResources UP-TO-DATE
:bootBuildInfo
:initQuerydslSourcesDir
:compileQuerydsl
Note: Running MongoAnnotationProcessor
Note: Running MongoAnnotationProcessor
Note: Serializing Supertypes
Note: Generating my.code.domain.QAbstractAuditingEntity for [my.code.domain.AbstractAuditingEntity]
Note: Serializing Entity types
Note: Generating my.code.domain.QAuthority for [my.code.domain.Authority]
Note: Generating my.code.domain.QUser for [my.code.domain.User]
Note: Generating my.code.domain.QPersistentAuditEvent for [my.code.domain.PersistentAuditEvent]
Note: Generating my.code.domain.QSocialUserConnection for [my.code.domain.SocialUserConnection]
Note: Running MongoAnnotationProcessor
Note: Running MongoAnnotationProcessor
:compileQuerydsl FAILED

> FAILURE: Build failed with an exception.

> What went wrong:
Cannot convert path to File. path='net.ltgt.gradle.apt.AptPlugin$_apply_closure1$_closure14@4e88f5f1' basedir='/home/jhipster/app'

Thanks for your help

**Comment by jdubois** [comment] 2017-03-20 14:44
I'm sorry but we don't support QueryDSL.

The page is written by a community member: if it is really outdated and nobody is willing to update it, we will remove it.

Did you try StackOverflow, or the QueryDSL forum/stackoverflow/whatever-they-use-for-questions ?

I'm closing this because this is not a JHipster bug, as we don't support QueryDSL.

**Closed by jdubois** 2017-03-20 14:44 UTC

**Comment by szabobar** [comment] 2017-03-20 14:47
Thanks for your help, it was very helpful, but the doc is outdated. Please remove it, or actualize it (jhipster.github.io is your domain, and I found a not working description on it):  https://jhipster.github.io/tips/003_tip_add_querydsl_support.html

Thanks

**Comment by jdubois** [comment] 2017-03-20 14:51
I'm sorry @szabobar but this is not my code or my documentation.... Yes I "own" the domain (not really, in fact it belongs to GitHub), but there are many contributions from external people, as everyone is free to add tips and tricks or correct the documentation on https://github.com/jhipster/jhipster.github.io

As you can see on https://jhipster.github.io/tips/003_tip_add_querydsl_support.html the tip was submitted by @omrzljak - he's probably the best to help you here -> @omrzljak do you confirm you tip is outdated and should be removed?

**Comment by omrzljak** [comment] 2017-03-21 08:10
@jdubois probably this should be removed. I have no time to actualize it (because I am working on other not jhipster related projects ) and it is better to have no documentation the to have documentation which is not up-to-date.

**Comment by jdubois** [comment] 2017-03-21 08:58
OK thanks @omrzljak ! I'm a bit sad to remove it, but you are right!

**Comment by arnaud-deprez** [comment] 2017-03-29 15:28
Hi @jdubois,

I saw you removed the tips for query dsl.
I don't know if you want to keep update this tips but for your information, there was a regression introduced in gradle >3.2 that forces net.ltgt.gradle:gradle-apt-plugin to create a new release 0.10.

So to fix the problem, you can either downgrade gradle to 3.2.1 or upgrade net.ltgt.gradle:gradle-apt-plugin to 0.10

**Comment by jdubois** [comment] 2017-03-29 15:30
@arnaud-deprez I would love to keep this tip, and the page is still available at https://github.com/jhipster/jhipster.github.io/blob/44dec32f348b32554b7a9625216ec6de30110b03/tips/003_tip_add_querydsl_support.md -> if you know how to make it work again, please do a PR, and I'll put it back into the index

**Comment by arnaud-deprez** [comment] 2017-03-29 15:31
Ok I will :-)
