### ISSUE TITLE
Front-end app generation typed as monolith

### ISSUE THREAD

**Issue by developpef** [jhipster/generator-jhipster#9306] opened 2019-02-20 13:47 UTC
##### **Overview of the issue**
When generating a front-end app with "jhipster --skip-server", the created app is declared as "monolith" in .yo-rc.json
This causes problem later when, for example, trying to import JDL (database check error, like in issue #5191).

##### **Motivation for or Use Case**
I had to generate separated front and back applications.

##### **Reproduce the error**
1- Run "jhipster --skip-server"
2- Open .yo-rc.json and check "applicationType"

##### **Suggest a Fix**
The front-end app should be declared as "gateway" in .yo-rc.json 

##### **JHipster configuration**

Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```

`-- generator-jhipster@5.8.1

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folde
r**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
    "generator-jhipster": {
        "promptValues": {
            "nativeLanguage": "en"
        },
        "jhipsterVersion": "5.8.1",
        "applicationType": "gateway",
        "baseName": "...",
        "clientFramework": "angularX",
        "useSass": true,
        "clientPackageManager": "npm",
        "authenticationType": "JWT",
        "cacheProvider": "no",
        "databaseType": "PostgreSQL",
        "devDatabaseType": "PostgreSQL",
        "prodDatabaseType": "PostgreSQL",
        "testFrameworks": ["protractor"],
        "jhiPrefix": "jhi",
        "entitySuffix": "",
        "dtoSuffix": "DTO",
        "otherModules": [],
        "enableTranslation": true,
        "nativeLanguage": "en",
        "languages": ["en", "fr"],
        "skipServer": true
    }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in
 the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Study {
  name String
}
entity Simulation {
  name String,
  date Instant
}
relationship OneToMany {
  Study{study} to Simulation{study}
}

dto Study, Simulation with mapstruct
service Study, Simulation with serviceImpl
paginate Simulation with infinite-scroll

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_192"
Java(TM) SE Runtime Environment (build 1.8.0_192-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.192-b12, mixed mode)

git version 2.16.1.windows.1

node: v8.11.3

npm: 6.7.0

yeoman: 2.0.5

Docker version 18.03.0-ce, build 0520e24302

docker-compose version 1.20.1, build 5d8c71b2

INFO! Congratulations, JHipster execution is complete!

##### **Browsers and Operating System**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment] 2019-02-22 14:04
I think `skip-server` only works for monoliths... For microservices it wouldn't make any sense (obviously!!), and for a gateway I'm not sure it makes sense (if you have no server part, then it's not a gateway as it's not going to route any request, so basically it's a monolith).

This is probably not documented (flags are for advanced use-cases and are less documented usually, still this should be clearer).

What exactly are you trying to do?

**Comment by developpef** [comment] 2019-02-22 16:20
I was trying to generate 2 projects to separate front an back
I followed this doc https://www.jhipster.tech/separating-front-end-and-api/
Maybe it could have been easier to generate one microservice app and one gateway app?
Because since then, I had a lot of difficulties to make the front and back work together correctly. Mainly because the back was generated without any user management capabilities (APIs, spring security, repositories for database...).

**Comment by rifatdover** [comment] 2019-02-23 17:04
@jdubois In a case where you want to separate your API infrastructure with your client infrastructure (especially when you have mobile and web clients together), this will make sense. Yes I agree in any case you can make it with different gateways but it will create duplications especially if you use some custom filters in both gateways.

**Comment by rifatdover** [comment] 2019-02-23 17:13
@jdubois In a case where you want to separate your API infrastructure with your client infrastructure (especially when you have web admin clients(which will use admin templates that are popular), web clients  and also mobile clients together), this will make sense. Yes I agree in any case you can make it with different gateways but it will create duplications especially if you use some common filters in both gateways.

**Comment by jdubois** [comment] 2019-02-24 09:16
I'm sorry but this doesn't make any sense to me: are you sure you understand what we mean by a "gateway" in JHipster? Have a look at https://www.jhipster.tech/api-gateway/

**Comment by pascalgrimaud** [comment] 2019-02-24 13:17
`--skip-client` and `--skip-server` flags are only for very advanced users who want to customize the generated application.

We can't guarantee it will work immediatly as there are so much way to use it.

**Comment by developpef** [comment] 2019-02-24 13:41
Well, we managed to make it work, mainly by integrating in the 2 separated projects some classes from a monolith sample.

As this doc (https://www.jhipster.tech/separating-front-end-and-api/) says, this is what we wanted to achieve : 

> JHipster is a “full-stack” development tool, and its goal is to make you work efficiently with your front-end code (Angular/React) and your back-end code (Spring Boot).
However, it is a **common requirement to separate the front-end and the back-end codes**, typically because they are developed by different teams and have a different lifecycle.

And it also says : 

> Please note that this isn’t the default JHipster way of working: **this isn’t complex to do, and works well,** but this is an advanced topic.

In our architecture, front web app (what I thought you named "gateway") and back-end APIs ("microservices") will be deployed on separate machines for many reasons (performance, security and so on). Also, 2 different teams with different skills (front with JS/CSS and back with Java) will work seperatly on each project.

Did we misunderstood some basics?

**Comment by gmarziou** [comment] 2019-02-24 16:26
> back-end APIs ("microservices")

Your architecture is still unclear to me, are you really talking about JHipster microservices? If so, what are the options you chose for service discovery and auth type?

**Comment by ruddell** [comment] 2019-02-24 18:15
The error message is clear.  Your database type is not a valid value.

> Error: The passed database type must either be 'sql', 'mysql', 'mariadb', 'postgresql', 'oracle', 'mssql', 'mongodb', 'couchbase', or 'cassandra'
ERROR! Error while parsing applications and entities from the JDL Error: The passed database type must either be 'sql', 'mysql', 'mariadb', 'postgresql', 'oracle', 'mssql', 'mongodb', 'couchbase', or 'cassandra'

During generation, you passed `--db PostgreSQL` while it should be `postgresql`.  Update your `.yo-rc.json` file and it will work.

**Comment by developpef** [comment] 2019-02-25 07:34
We don't use service discovery, and used JWT auth.

Well, just a last try to explain what we did : see the graphics on this page : https://micro-frontends.org/
We implemented what is called the Monolithic Frontends Microservices (3rd part of the 1st image). Maybe you are thinking about something more related to the 2nd image...

And for now, when I ask Jhipster to import an entity, I first import the JDL in the front-end project, to generate all the JS/CSS/HTML pages (and Protractor tests), and import it a second time in back-end project to generate all the Java classes for Rest API, entities, repository, Liquibase changes and unit tests.

But no matter, I think we will continue using Jhipster that way.

**Comment by jdubois** [comment] 2019-02-25 10:18
Just to be sure we all understand each other: the `gateway` is not a front-end application. It's just a monolith which has some back-end routing capabilities to microservices, thanks to Netflix Zuul. You might more see it as a monolith + router.

As the gateway works using the service discovery, if you don't have service discovery then your gateway is just a monolith (as the routing part will not work).

Then, concerning the choice of separating the front-end from the back-end, it's totally up to you of course but there's nothing that prevents it with a monolith:

- If you don't do anything specific, then it's just 2 teams working on the same project. You could even do a Git sub-module for the front-end if you really want to separate them, but that's not even needed (you won't have merge issues, both team work on different parts of the project).
- We're aiming at a "full stack" application as we think it's better to have full-stack developers and it's better to focus on business use-cases than technical use-cases, but that's just a philosophy and there's really nothing in the project preventing you from doing it the other way (and separate teams by technology).
- From a performance and security point of view, you won't gain anything from separating the front-end from the back-end. The only thing that some people sometime find is that they could put the front-end in a CDN: you can still totally do that with a monolith (you just need to configure a front-end load-balancer - for example I do this easily with CloudFlare), and there are even systems that do this automatically (Google App Engine automatically "extracts" the JHipster front-end to serve it through its CDN).

**Comment by jdubois** [comment] 2019-02-27 10:45
I'm closing this as I understand @ruddell found the root cause of your issue.

Then, for me this option should only work for monoliths as it doesn't make sense for both microservices or gateways. I'm modifying the documentation for this, and will link the change here.

**Closed by jdubois** 2019-02-27 10:45 UTC
