### ISSUE TITLE
code compilation gets stuck after running gradlew

### ISSUE THREAD

**Issue by AlienWareSumant** [jhipster/generator-jhipster#4675] opened 2016-12-14 12:41 UTC
I have done everything as the jhipster installation guide suggests. But when I try to run the code using gradlew, it works for sometime and then gets stuck at gulpconstantdev. No change was done in any file after running "yo jhipster" from cmd. Please find the image attached below and let me know what the resolution should be.
![jhipsterissue](https://cloud.githubusercontent.com/assets/13749340/21182336/876d98e0-c228-11e6-9dec-fbdb144de5c4.JPG)

**Comment by jdubois** [comment] 2016-12-14 12:45
This ticket has been closed as the guidelines are not followed.

Tickets must follow our [Guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#submitting-an-issue), as mentioned in:

1. our [Readme file on the front page of the project](https://github.com/jhipster/generator-jhipster/blob/master/README.md), 
2. the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) and
3. our [Help page](http://jhipster.github.io/help/)

We have also created a template on the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) to help you follow those guidelines.

**Closed by jdubois** 2016-12-14 12:45 UTC

**Comment by kaidohallik** [comment] 2016-12-14 13:42
I have the same issue. I have 2 workarounds:
1. if using `gradlew --info` then everything works again
2. closing current command window and opening new command window, then `gradlew` works for a while in this new command window

##### **JHipster Version(s)**

```
jhipster@0.0.0 c:\projects\jhipster-test
`-- generator-jhipster@3.12.1

```


##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "jhipsterVersion": "3.12.1",
    "baseName": "jhipster",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "buildTool": "gradle",
    "enableSocialSignIn": true,
    "rememberMeKey": "65c1391bc15928034869154f58a65c34bd70e7f5",
    "useSass": true,
    "applicationType": "monolith",
    "clientFw": "angular1",
    "testFrameworks": [
      "gatling",
      "cucumber",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "et",
    "languages": [
      "et",
      "en"
    ]
  }
}
```


##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

ls: no such file or directory: .jhipster/*.json

##### **Browsers and Operating System**

java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)

git version 2.7.0.windows.1

node: v6.9.1

npm: 3.10.9

bower: 1.8.0

gulp:
[15:40:44] CLI version 1.2.2
[15:40:44] Local version 3.9.1

yeoman: 1.8.5

**Comment by jdubois** [comment] 2016-12-14 13:44
Thanks @kaidohallik so I'm opening this again - could you also update the title? Just saying that you are "stuck" doesn't help to understand the issue

**Comment by atomfrede** [comment] 2016-12-14 13:49
@kaidohallik You are using windows too?

**Comment by kaidohallik** [comment] 2016-12-14 14:33
@jdubois seems that I don't have rights to change issue title
@atomfrede yes, I'm using windows too

**Comment by atomfrede** [comment] 2016-12-14 16:01
@kaidohallik Can you try to disable the gradle daemon by using ``gradlew --no-daemon``? And maybe stop all running daemons via ``gradlew --stop``?

**Comment by kaidohallik** [comment] 2016-12-14 23:42
@atomfrede I could'nt reproduce the problem. I have had this problem at least 3 times but currently not able to reproduce. Currently `gradlew` and `gradlew --no-daemon` both worked well.

I made some tests in Windows gradle, Windows maven and Ubuntu gradle with .yo-rc.json provided in my first comment. Console outputs near ngconstant:

**Windows gradle** `gradlew` console excerpt
```
:bower
:nodeSetup SKIPPED
:gulpConstantDev
[22:57:19] Using gulpfile C:\projects\jhipster-test\gulpfile.js
[22:57:19] Starting 'ngconstant:dev'...
[22:57:19] Finished 'ngconstant:dev' after 38 ms

urceslding 31% > :processResources
:compileJava UP-TO-DATE
:compileScala UP-TO-DATE
```
Notice that even this build worked (didn't hang after ngconstant console output) there is empty line and broken text after last ngconstant line.

**Ubuntu gradle** `./gradlew` console excerpt
```
:nodeSetup SKIPPED
:gulpConstantDev
[23:28:43] Using gulpfile ~/projects/jhipster_test/gulpfile.js
[23:28:43] Starting 'ngconstant:dev'...
[23:28:43] Finished 'ngconstant:dev' after 47 ms
:processResources
:compileJava UP-TO-DATE
:compileScala UP-TO-DATE
```
In Ubuntu no empty line and broken text in console output after ngconstant lines.

**Windows maven** `mvnw` console excerpt
```
[INFO] [23:39:20] Starting 'copy:common'...
[INFO] [23:39:20] Starting 'inject:vendor'...
[INFO] [23:39:21] Starting 'ngconstant:prod'...
[INFO] [23:39:21] Starting 'copy:languages'...
[INFO] [23:39:21] Finished 'ngconstant:prod' after 174 ms
[INFO] [23:39:21] gulp-inject 1 files into vendor.scss.
[INFO] [23:39:21] Finished 'copy:languages' after 73 ms
..........
2016-12-14 23:40:06.771  INFO 10168 --- [  restartedMain] com.mycompany.myapp.JhipsterApp          : Running with Spring profile(s) : [swagger, dev]
```
Notice that maven uses ngconstant:prod instead of ngconstant:dev from gulpfile.js

Investigating gulpfile.js there is only one difference between ngconstant:dev and ngconstant:prod
* `DEBUG_INFO_ENABLED: true` in ngconstant:dev
* `DEBUG_INFO_ENABLED: false` in ngconstant:prod

This is unimportant in current issue but maybe issue with maven build.

If I changed in gulpfile.js function ngconstant:dev to:
```
gulp.task('ngconstant:dev', function () {
    return 0;
});
```
then no change, empty line and broken text in output, so I guess that problem is not in gulp-ng-constant.

After removing
```
task gulpConstantDev(type: GulpTask) {
    args = ["ngconstant:dev", "--no-notification"]
}
```
from profile_dev.gradle there is no empty line and broken text in console output.
So conclusion is: there can be some problem in gradle gulp plugin in Windows.

**Comment by kaidohallik** [comment] 2016-12-15 01:50
I made commit in my fork. Upgrading gradle node and gulp plugins to 1.0.1 and setting gulp bufferOutput to true. This version does not produce broken texts in console output any more in my computer.

**Comment by deepu105** [comment] 2016-12-15 07:29
It could have been an environment glitch
