### ISSUE TITLE
Broker not found when launching docker-compose app.yml

### ISSUE THREAD

**Issue by fdelbrayelle** [jhipster/generator-jhipster#11846] opened 2020-05-25 14:48 UTC
##### **Overview of the issue**

When launching the docker-compose command `docker-compose -f src/main/docker/app.yml up` to run the app with Kafka the broker is not found :

```
generated_project_for_tests-app_1    | 2020-05-25 14:44:51.410  WARN 1 --- [cTaskExecutor-1] org.apache.kafka.clients.NetworkClient   : [Consumer clientId=consumer-generated-project-for-tests-1, groupId=generated-project-for-tests] Connection to node 1 (localhost/127.0.0.1:9092) could not be established. Broker may not be available.
```

##### **Reproduce the error**

See overview of the issue above.

##### **Related issues**

`app.yml` will be updated as well in the [Kafka generator](https://github.com/fdelbrayelle/generator-jhipster-kafka) but it should be fixed in the main generator as well for the projects using it without the new module.

##### **Suggest a Fix**

In kafka service env vars update the following line:

```
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
```

And bind the service to the following line in the app service env var:

```
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
```

In `application.yml`, update the bootstrap servers to this:

```
  bootstrap.servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
```

##### **JHipster Version(s)**

6.9.0

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by fdelbrayelle** [comment] 2020-05-25 15:21
This will be fixed as well in the Kafka generator: https://github.com/fdelbrayelle/generator-jhipster-kafka/issues/54

**Comment by fdelbrayelle** [comment] 2020-05-25 18:42
I don't reproduce as well on [your test project](https://github.com/pascalgrimaud/burger200525). The only difference I see at first sight: you're using pgsql and I'm using mysql.

**Comment by pascalgrimaud** [comment] 2020-05-26 04:55
@fdelbrayelle : plz, provide a sample project and I'll try to reproduce

**Comment by fdelbrayelle** [comment] 2020-05-26 06:04
Here is my sample project: https://github.com/fdelbrayelle/sample-with-kafka/

And the error I get without the fix of [this PR](https://github.com/jhipster/generator-jhipster/pull/11847/files):

```
generated_project_for_tests-app_1    | 2020-05-26 06:01:51.920  WARN 1 --- [cTaskExecutor-1] org.apache.kafka.clients.NetworkClient   : [Consumer clientId=consumer-generated-project-for-tests-1, groupId=generate
d-project-for-tests] Connection to node -1 (localhost/127.0.0.1:9092) could not be established. Broker may not be available.
```

**Comment by fdelbrayelle** [comment] 2020-05-26 07:06
I don't reproduce anymore this morning in a [JHipster sample app](https://github.com/fdelbrayelle/burger11846/commit/7ce81be2ceea1fef093b6469abe0c7fefe957d4e) (linked locally with generator-jhipster updated on master) without using the Kafka module and lauching these commands:

```
mkdir burger11846
cd burger11846
jhipster # see .yo.rc-json below
./mvnw package -Pprod verify jib:dockerBuild
docker-compose -f src/main/docker/app.yml down
docker-compose -f src/main/docker/app.yml up

```

And with this `.yo-rc.json`:

```
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp"
    },
    "jhipsterVersion": "6.9.0",
    "applicationType": "monolith",
    "baseName": "burger11846",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": "kafka",
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "ZTRlOTA5OTFmODQ0NjEwODVkOTQ5ZDA1ZGZiZDlkYzk0ODU0YzRlOGNlZWM2YjNmZTY3OTk0ODUwMzEwZjg4Yjc5NjZiZjhjYWE2ZTk4YmRmMTQxN2Q5NjUxYmM2MGJiYTg3YWJiYTdhZmM0MzNkNzI3M2Y4OWNmYjM2ZGYxZDE=",
    "embeddableLaunchScript": false,
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "angularX",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "creationTimestamp": 1590474012209,
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": false,
    "blueprints": []
  }
}
```

So Issue and PR can be closed IMO...

I wonder if it could be some services that started too fast yesterday? If it's random we could at least add `links` and `depends_on` in docker compose files. What do you think about this?

**Comment by pascalgrimaud** [comment] 2020-05-30 10:08
as we couldn't reproduce the issue, let's close this

**Closed by pascalgrimaud** 2020-05-30 10:08 UTC
Labels: area: needs-reproduction, theme: kafka
