### ISSUE TITLE
Configuring HTML 5 mode not working

### ISSUE THREAD

**Issue by hookszhang** [jhipster/generator-jhipster#4770] opened 2016-12-27 08:03 UTC
I want config AngularJS html5mode and try to follow this tip https://jhipster.github.io/tips/010_tip_configuring_html_5_mode.html. 

There are two problems with this tip.

- The first problem(I founded the solution) 

In Redirection filter part
```
@Controller
public class AngularJsForwardController {
    // problem in this line
    @RequestMapping(value = "/**/{[path:[^\\.]*}")
    public String redirect() {
        return "forward:/";
    }
}
```
I added above controller to rest package. AngularJsForward is works but web socket don't works. 

Web console print
```
Opening Web Socket...
sockjs.js:1700WebSocket connection to 'ws://localhost:8080/websocket/tracker/232/mlnbe0ht/websocket' failed: Error during WebSocket handshake: Unexpected response code: 404
WebSocketBrowserDriver @ sockjs.js:1700
WebSocketTransport @ sockjs.js:2973
SockJS._connect @ sockjs.js:828
SockJS._receiveInfo @ sockjs.js:802
g @ sockjs.js:66
EventEmitter.emit @ sockjs.js:86
(anonymous) @ sockjs.js:567
g @ sockjs.js:66
EventEmitter.emit @ sockjs.js:86
(anonymous) @ sockjs.js:374
g @ sockjs.js:66
EventEmitter.emit @ sockjs.js:86
xhr.onreadystatechange @ sockjs.js:1614
sockjs.js:1622POST http://localhost:8080/websocket/tracker/232/wko3kdlb/xhr_streaming?t=1482824958918 403 (Forbidden)

......
```  

Then, I have updated the problem that line, solved!

```
@RequestMapping(value = "/{[path:[^\\.]*}")
```

-  **The second problem(need help)**

It works fine with localhost:8080 but localhost:9000 not working. 

What should i config gulp proxy?

**JHipster Version 3.10.0**
**Latest Version Chrome**
**Mac OS Sierra**

**Comment by jdubois** [comment] 2016-12-27 08:15
This is a tip submitted by a user, this isn't something we generate or we can support. I'm not surprised it doesn't work with Websockets or Gulp, the person who wrote the tip probably just didn't use those.

This is going probably to be the standard with our Angular 2 version (JHipster 4), so what you tell here is very important for our next release: if you find solutions, please post them, or even better update the tip.

**Comment by jdubois** [comment] 2016-12-27 08:23
I'm closing this as this is not a bug in the generator... It could be seen as a feature request, but we're going to do it in JHipster 4, so this is already taken into account.

In the meantime, if you find a solution please update the tip. This could also be a good question on StackOverflow.

**Closed by jdubois** 2016-12-27 08:23 UTC

**Comment by tkman59** [comment] 2016-12-27 10:47
I have the same problem.
I just fix on the file  server.js :
var proxyRoutes = [
        '/'
    ];

**Comment by jdubois** [comment] 2016-12-27 10:49
@tkman59 can you add it as a PR to the tip? It's on https://github.com/jhipster/jhipster.github.io/tree/master/tips

**Comment by tkman59** [comment] 2016-12-27 14:19
Yes I can ;)

**Comment by hookszhang** [comment] 2016-12-27 14:27
@tkman59 It works for me! Thank you!
