### ISSUE TITLE
Release v7 

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#14178] opened 2021-03-05 09:51 UTC
##### **Overview of the feature request**

This ticket is to track the release of JHipster 7 final. Things I'm looking into:

- [x] Couchbase. The last time I checked, Spring MVC + Couchbase was working, but WebFlux was not. If that’s still the case, I think it’s a good idea to disable Couchbase as an option for reactive. https://github.com/jhipster/generator-jhipster/pull/14184 and https://github.com/jhipster/generator-jhipster/pull/14186
- [x] yeoman-generator@5 https://github.com/jhipster/generator-jhipster/issues/14064
- [x] Test and make sure the blog post I wrote on Reactive Java Microservices still works. https://github.com/jhipster/generator-jhipster/issues/14196
- [x] Deploy the result of the previous blog post to Google Cloud and make sure our k8s generator works.
- [x] Remove traefik gateway option (https://github.com/jhipster/generator-jhipster/issues/14233)

##### **Motivation for or Use Case**

Quality

**Comment by mraible** [comment] 2021-03-05 10:13
I'll update this issue with the status as I address the issues above.

- ❌ ngx-couchbase [EJS error with primary keys](https://github.com/hipster-labs/jhipster-daily-builds/runs/2036948774?check_suite_focus=true#step:11:109)
- ❌ webflux-couchbase same as above.

@mshima What are we doing wrong for `primaryKey`?

**Comment by mraible** [comment] 2021-03-05 10:15
It'd be cool if we could clean this up at the end of `jhipster jdl reactive-ms`:

```
You can launch all your infrastructure by running : docker-compose up -d
Congratulations, JHipster execution is complete!
Sponsored with ❤️  by @oktadev.
INFO! Generator docker-compose child process exited with code 0
Congratulations, JHipster execution is complete!
Congratulations, JHipster execution is complete!
```

I think the following would be better:

```
You can launch all your infrastructure by running : docker-compose up -d
Congratulations, JHipster execution is complete!
Sponsored with ❤️  by @oktadev.
```

Definitely a stretch goal.

**Comment by mraible** [comment] 2021-03-05 10:26
Added a bug bounty so y'all can expense beers on Okta after the release. 😄

**Comment by mshima** [comment] 2021-03-05 11:13
> I'll update this comment with the status as I address the issues above.
> 
> * ❌ ngx-couchbase [EJS error with primary keys](https://github.com/hipster-labs/jhipster-daily-builds/runs/2036948774?check_suite_focus=true#step:11:109)
> * ❌ webflux-couchbase same as above.
> * ❌ `jhipster jdl reactive-ms` fails with Protractor:
> 
> <img alt="Screen Shot 2021-03-05 at 3 29 37 AM" width="1529" src="https://user-images.githubusercontent.com/17892/110103631-61254980-7d63-11eb-87d4-152de8fc8775.png">
> 
> I tried changing the gateway app to use Cypress and the errors still happen. I'm not sure why. I'll dig in tomorrow (Friday).
> 
> @mshima What are we doing wrong for `primaryKey`?

Not sure. I take a look.

**Comment by mshima** [comment] 2021-03-05 11:28
@mraible fixed couchbase primaryKey reference in your mongodb branch. Realized later that mongodb branch was not couchbase 😆 .

I can setup an environment to test if there are more problems later.

**Comment by mraible** [comment] 2021-03-05 19:41
I just realized that Couchbase + Spring Boot 2.4 is still pending in [this PR](https://github.com/jhipster/generator-jhipster/pull/14184).

**Comment by pascalgrimaud** [comment] 2021-03-05 21:25
@mshima : should we add yeoman 5 in the list ?

**Comment by mshima** [comment] 2021-03-05 21:30
@pascalgrimaud added. Hopefully I can finish the PR today.

**Comment by pascalgrimaud** [comment] 2021-03-05 21:33
Just crazy!

Ok so I won't do the final v7 release this weekend, so probably the next weekend, to give time to finish the last items here.
I can only do release saturday or sunday as I'm too busy with my day work at the moment.

**Comment by gzsombor** [comment] 2021-03-05 21:54
Is it possible to create a release just from the JHipster-bom/framework? A 7.0.0-beta-2 or something like that? Currently, the generator use 7.0.0-SNAPSHOT dependency, which makes local testing a bit fragile.

**Comment by mraible** [comment] 2021-03-05 21:56
I believe @jdubois might've fixed things so the SNAPSHOT build is published nightly.

**Comment by jdubois** [comment] 2021-03-05 21:59
It should work automatically but I didn't test -> please mention/contact me if you don't see the snapshots

**Comment by pascalgrimaud** [comment] 2021-03-06 08:47
> Is it possible to create a release just from the JHipster-bom/framework? A 7.0.0-beta-2 or something like that? Currently, the generator use 7.0.0-SNAPSHOT dependency, which makes local testing a bit fragile.

@gzsombor : you need to do these steps
- go into your local jhipster-bom (which should be a fork)
- update your fork
- mvn clean install -Dgpg.skip

It can be easily done with an alias. It took less than 15sec, if you decide to skip tests:
```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  13.389 s
[INFO] Finished at: 2021-03-06T09:46:34+01:00
[INFO] ------------------------------------------------------------------------
```

**Comment by pascalgrimaud** [comment] 2021-03-06 19:04
similar to improvement suggested by Matt, after generating full microservices applications, there are some changes, which are not correctly commit with git

**Comment by mshima** [comment] 2021-03-06 21:50
@pascalgrimaud can you confirm if the changes are only json files?

**Comment by pascalgrimaud** [comment] 2021-03-06 22:00
Yes, package.json, package lock and yo rc, if I remember well

**Comment by mshima** [comment] 2021-03-06 22:38
> Yes, package.json, package lock and yo rc, if I remember well

I was digging into it to make sure it wasn't related to the generator5 update.
And saw that package.json changes is pretty big.
After a couple of hours on this, just realized the problem is `prettier-plugin-packagejson` version mismatch.
`prettier-plugin-packagejson` stopped sorting scripts due to a change at sort-package-json https://github.com/keithamus/sort-package-json/pull/206.

So the generator generates using `prettier-plugin-packagejson` from generator-jhipster node_modules.
After generated and install, husky task executes prettier using `prettier-plugin-packagejson` from destination node_modules.
`prettier-plugin-packagejson` is not added the destination package.json, so the version from generator-jhipster@7.0.0.beta.1.

Including prettier-plugin-packagejson in the destination package.json may fix this issue for the package.json, yo-rc.json is a different.

**Comment by pascalgrimaud** [comment] 2021-03-06 22:40
I'm not sure for yo-rc as I'm not with my computer right now :-p
Nice catch anyway for package json

**Comment by mshima** [comment] 2021-03-06 22:48
`yo-rc.json` is due to jdl writing it disc and generator doesn't change it, since it hasn't been changed, prettifier is not executed.
I will fix this.

**Comment by egvimo** [comment] 2021-03-07 09:34
Would you mind to release `7.0.0.beta.2` meanwhile? The [milestone](https://github.com/jhipster/generator-jhipster/milestone/193) is on 100% and there are some fixes, which I really would like to migrate from the `beta.1`.

**Comment by mshima** [comment] 2021-03-07 12:02
@pascalgrimaud even with the PR there will be a diff in .yo-rc.json. Docker-compose writes to it after it was committed to git.

**Comment by pascalgrimaud** [comment] 2021-03-07 13:28
@mshima : no worry about yo rc, it's minor

**Comment by pascalgrimaud** [comment] 2021-03-07 13:30
@egvimo : the release beta.2 should be for the next week-end but I can't promise, as it's open source and we work for JHipster during our freetime. I'll do my best, just be patient :-)

**Comment by DanielFran** [comment] 2021-03-08 20:00
Added option to remove traefik support

**Comment by mraible** [comment] 2021-03-11 05:03
Couchbase is removed so I'm only concerned with `jhipster jdl reactive-ms` and deploying it with k8s now.

**Comment by mraible** [comment] 2021-03-18 04:46
I'm trying to deploy the `reactive-ms` stack on GCP with K8s now. When I run `./kubectl-apply.sh -f`, I'm getting the following error:

```
Unable to connect to the server: dial tcp 35.233.152.164:443: i/o timeout
```

I was able to deploy my Docker images directly to my registry with commands like:

```
./gradlew bootJar -Pprod jib -Djib.to.image=gcr.io/ionic-social-286904/gateway
```

**Comment by mraible** [comment] 2021-03-18 06:38
I was finally able to make things work after creating a new project and cluster. We might want to update [our GCP docs](https://www.jhipster.tech/gcp/) with more detailed steps. 

After running `./kubectl-apply.sh -f`, things were looking good.

```
Applying default `kubectl apply -f`
configmap/application-config created
secret/registry-secret created
service/jhipster-registry created
statefulset.apps/jhipster-registry created
deployment.apps/blog created
persistentvolumeclaim/blog-neo4j-pvc created
secret/blog-neo4j created
statefulset.apps/blog-neo4j created
service/blog-neo4j created
service/blog created
deployment.apps/gateway created
persistentvolumeclaim/gateway-postgresql-pvc created
secret/gateway-postgresql created
deployment.apps/gateway-postgresql created
service/gateway-postgresql created
service/gateway created
deployment.apps/store created
configmap/store-mongodb-config created
configmap/store-mongodb-init created
statefulset.apps/store-mongodb created
service/store-mongodb created
service/store created
```

10 minutes later and it seems some containers failed to start. 

```
$ kubectl get pods
NAME                                 READY   STATUS     RESTARTS   AGE
blog-69c885659-mjfs6                 0/1     Init:0/1   0          11m
blog-neo4j-0                         0/1     Pending    0          11m
gateway-d76f7bff6-9pc2g              0/1     Pending    0          11m
gateway-postgresql-f9bbb4b65-lp75b   0/1     Pending    0          11m
jhipster-registry-0                  1/1     Running    0          11m
jhipster-registry-1                  1/1     Running    0          11m
store-79fd4f88c4-9xbw8               0/1     Pending    0          11m
store-mongodb-0                      0/1     Pending    0          11m
```

Screenshot of workloads in Kubernetes Engine on GCP:

<img width="1024" alt="Screen Shot 2021-03-18 at 12 35 15 AM" src="https://user-images.githubusercontent.com/17892/111583531-37681b80-8782-11eb-814c-792f37710925.png">

Any ideas @saturnism?

**Comment by atomfrede** [comment] 2021-03-18 06:44
Can you check how the resource limits and requests are configured for `blog-neo4j`? Looks like the nodes are to small for the requested amount of memory or cpu.

**Comment by mraible** [comment] 2021-03-18 06:59
Yes, I think that's it. I need to use better machines. Maybe I can specify the machine type when creating the cluster?

**Comment by pascalgrimaud** [comment] 2021-03-18 14:53
I was thinking we are closed to v7 but it seems a lot of things are broken - https://github.com/hipster-labs/jhipster-daily-builds
Need to wait before release v7...

**Comment by DanielFran** [comment] 2021-03-18 15:02
@pascalgrimaud I am confident the update to spring-boot 2.4.4 will fix it. It seems the issue started after I pushed the override of neo4j to 6.0.6...

**Comment by DanielFran** [comment] 2021-03-18 16:47
@pascalgrimaud In fact, looking now at the chronology of the merges, it might be that the issue started when it was merged https://github.com/jhipster/generator-jhipster/pull/14365 or https://github.com/jhipster/generator-jhipster/pull/14364

I already take a look and did not identify what could be the issue...

**Comment by mraible** [comment] 2021-03-18 17:36
I tried creating a new cluster on GCP with bigger machines.

```
$ gcloud container clusters create jhipster \
--zone us-central1-a \
--machine-type n1-standard-4 \
--enable-autorepair \
--enable-autoupgrade
```

Then, I ran `./kubectl-apply.sh -f` and deployed. For some reason, it seems there's an issue pulling my images.

```
$ kubectl get pods
NAME                                 READY   STATUS             RESTARTS   AGE
blog-69c885659-44phh                 0/1     ImagePullBackOff   0          14m
blog-neo4j-0                         1/1     Running            0          14m
gateway-d76f7bff6-jgwxb              0/1     ImagePullBackOff   0          14m
gateway-postgresql-f9bbb4b65-9r4k5   1/1     Running            0          14m
jhipster-registry-0                  1/1     Running            0          14m
jhipster-registry-1                  1/1     Running            0          14m
store-79fd4f88c4-cngjn               0/1     ImagePullBackOff   0          14m
store-mongodb-0                      1/1     Running            0          14m
store-mongodb-1                      1/1     Running            0          13m
store-mongodb-2                      1/1     Running            0          13m
```

I tried `kubectl delete pod blog-69c885659-44phh` (and others), then running `./kubectl-apply.sh -f` again, but no luck. 🤷‍♂️

**Comment by mshima** [comment] 2021-03-18 17:39
The problem is with mysql, not sure if the driver or the docker image.
Every test that I've looked at has mysql server.

**Comment by DanielFran** [comment] 2021-03-18 17:47
Image has been updated 10 days ago, so it cannot be that.
I was thinking about the driver but did not found what commit would be the origin of the issue...

**Comment by mraible** [comment] 2021-03-18 18:12
Does anyone know how to enable HTTPS on my apps that are deployed to GCP? I have everything running, but it's all over HTTP, which won't work with Okta.

**Comment by mshima** [comment] 2021-03-18 19:08
@DanielFran I've triggered an old [commit](https://github.com/jhipster/generator-jhipster/commit/ad0b6e60a84a360b6773c37aaa9112017a64416b) that succeed and if [failed](https://github.com/jhipster/generator-jhipster/runs/2142047163) with the same error.
It should be related to jhipster-bom or an outside problem.

**Comment by mraible** [comment] 2021-03-18 20:03
I figured out how to do HTTPS for my K8s cluster with @saturnism's [external load balancing guide](https://spring-gcp.saturnism.me/deployment/kubernetes/load-balancing/external-load-balancing). Now that I've deployed everything successfully, I'm 👍 for releasing JHipster 7!

Of course, I created my apps last night, so recent changes might've broken things. :)

**Comment by pascalgrimaud** [comment] 2021-03-18 20:05
Ok, I'll ask a code freeze in the mailing list so let few days for daily builds

**Comment by mraible** [comment] 2021-03-19 15:53
I was able to get HTTP -> HTTPS working on my K8s cluster using the following code.

```java
// Force HTTPS
http.redirectToHttps(redirect -> redirect
    .httpsRedirectWhen(e -> e.getRequest().getHeaders().containsKey("X-Forwarded-Proto"))
);
```

**Comment by pascalgrimaud** [comment] 2021-03-21 08:26
Closed by:
- https://www.jhipster.tech/2021/03/21/jhipster-release-7.0.0.html
- https://github.com/jhipster/generator-jhipster/releases/tag/v7.0.0

**Closed by pascalgrimaud** 2021-03-21 08:26 UTC
Labels: $$ bug-bounty $$, $500, v7

**Comment by atomfrede** [comment] 2021-03-21 10:06
Thanks @pascalgrimaud and everyone of the team. It's a pleasure to work with you! When will we have our virtual drink? 🍻 😁

**Comment by pascalgrimaud** [comment] 2021-03-21 10:07
We should organize it, and discuss about v8 :-)
