### ISSUE TITLE
JHipster i18n issue: translation-not-found in user activation page and password reset page

### ISSUE THREAD

**Issue by taizhang2018** [jhipster/generator-jhipster#8397] opened 2018-09-24 17:47 UTC
My JHipster i18n works if users access it from the login page and it works fine after the users login. However, if the user click the link in the activation email to activate the account, i18n is not working because translation-not-found is shown for all jhiTranslate elements.

##### **Motivation for or Use Case**

For example, when user receives the following email: Your bbb account has been created, please click on the URL below to access it: http://127.0.0.1:8080/#/reset/finish?key=01225838052842547789

and the user click the above link, the page is with all translation-not-found.

Then, I found this translation-not-found problem exists for all the pages open with an URL directly, except the login page. For example, if I open the "forgot password" from the login page, i18n works fine. However, if I use the same URL http://localhost:8080/#/reset/request directly in the browser, translation-not-found appears everywhere.

May I know if anyone had similar JHipster i18n issues and how to fix this? Thanks.

My JHipster version is 4.8.2

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.altavia.amp",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "4.8.2",
    "baseName": "amp",
    "packageName": "com.altavia.amp",
    "packageFolder": "com/altavia/amp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "mysql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling",
      "cucumber",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "fr"
        ]
  }
}
</pre>
</details>

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

Chrome, Explorer, Windows

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by ruddell** [comment] 2018-09-24 18:12
I couldn't reproduce your issue.  I tried generating a project with your config and using v4.8.2 and navigating to the password reset screen.  I'd recommend checking your browser console for errors.

<img width="512" alt="screen shot 2018-09-24 at 11 12 23 am" src="https://user-images.githubusercontent.com/4294623/45970207-c0a39a80-bfea-11e8-818a-1c4c01f8c964.png">

**Comment by ruddell** [comment] 2018-09-24 18:35
Yes I copied and pasted the URL into a new tab.

**Comment by taizhang2018** [comment] 2018-09-24 18:54
> Yes I copied and pasted the URL into a new tab.

Is it possible there's some settings regarding the i18n? Such as when to start it?
I don't see any error in my browser console, here's the info:

[HMR] Waiting for update signal from WDS...
webpack-internal:///./node_modules/@angular/core/@angular/core.es5.js:3129 Angular is running in the development mode. Call enableProdMode() to enable the production mode.
webpack-internal:///./src/main/webapp/app/app.main.ts:11 Application started
webpack-internal:///./node_modules/webpack-dev-server/client/index.js?http://localhost:9060:77 [WDS] Hot Module Replacement enabled.

**Comment by ruddell** [comment] 2018-09-24 19:32
When something is not reproducible on a new generated project, it's usually related to some changes or customization added by the developer.  I usually tell people to try rolling back changes via git until they can identify which part of the code causes the issue.

I still can't reproduce and it doesn't seem to affect v5 either, so I'm closing this.  Please re-open if you can provide us steps to reproduce or if you identify the issue.

**Closed by ruddell** 2018-09-24 19:32 UTC

**Comment by barrychapman** [comment] 2019-02-24 20:31
I have this same issue also, exactly.
