### ISSUE TITLE
Top navbar has rounded corners

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#5207] opened 2017-02-14 20:28 UTC
##### **Overview of the issue**

The top navbar has rounded corners. They're subtle, but they're there.

![screen shot 2017-02-14 at 11 08 53 am](https://cloud.githubusercontent.com/assets/17892/22947671/34e2dc0e-f2b9-11e6-9291-b4fd78b4e674.png)

##### **Motivation for or Use Case**

I like it when UIs are perfect. ;)

##### **Reproduce the error**

Generate an app, checkout the top nav.

##### **Suggest a Fix**

Restructure HTML or add CSS. Not sure.

##### **JHipster Version(s)**

4.0.3

##### **Browsers and Operating System**

OS name: "mac os x", version: "10.12.3", arch: "x86_64", family: "mac"
Chrome Version 56.0.2924.87 (64-bit)

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by deepu105** [comment] 2017-02-14 22:46
Ya I noticed it too but its from bootstrap but we can override that
ofcourse

Thanks & regards,
Deepu

On 14 Feb 2017 9:28 p.m., "Matt Raible" <notifications@github.com> wrote:

*Overview of the issue*

The top navbar has rounded corners. They're subtle, but they're there.

[image: screen shot 2017-02-14 at 11 08 53 am]
<https://cloud.githubusercontent.com/assets/17892/22947671/34e2dc0e-f2b9-11e6-9291-b4fd78b4e674.png>
*Motivation for or Use Case*

I like it when UIs are perfect. ;)
*Reproduce the error*

Generate an app, checkout the top nav.
*Suggest a Fix*

Restructure HTML or add CSS. Not sure.
*JHipster Version(s)*

4.0.3
*Browsers and Operating System*

OS name: "mac os x", version: "10.12.3", arch: "x86_64", family: "mac"
Chrome Version 56.0.2924.87 (64-bit)

   - Checking this box is mandatory (this is just to show you read
   everything)

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/jhipster/generator-jhipster/issues/5207>, or mute the
thread

**Comment by JulienMrgrd** [comment] 2017-02-15 09:12
We can override @deepu105.
We just have to add "! important" after each css line to override.

like this :
![capture d ecran de 2017-02-15 10-08-36](https://cloud.githubusercontent.com/assets/11616517/22967450/d23a5fa6-f366-11e6-885a-014af84905e7.png)

I commit it in a few minutes.

**Comment by deepu105** [comment] 2017-02-15 09:23
@JulienMrgrd I know we can override but normally prefer not to tweak too much of BS styles but in this specific case we can do it. 
Also we dont have to add `!important` as these styles are applied after BS styles so they will take precedence. If anyone wants to PR please go ahead else ill do it sometime this week

**Comment by jdubois** [comment] 2017-02-15 09:23
I'm not a big fan with the `!important` keyword, we doesn't our CSS have a higher priority?

**Comment by deepu105** [comment] 2017-02-15 09:29
@jdubois our css do have higher priority we do not override border radius currently

**Comment by gmarziou** [comment] 2017-02-15 09:47
Is it a design choice from Bootstrap team or is it just a bug on their side?

**Comment by gmarziou** [comment] 2017-02-15 10:27
So it seems a design choice from BS4 team, see https://v4-alpha.getbootstrap.com/getting-started/options/#global-options and this would be easier to fix globally in SCSS

**Comment by sendilkumarn** [comment] 2017-02-15 10:43
It is fixed in `alpha.6` 
![screen shot 2017-02-15 at 6 40 57 pm](https://cloud.githubusercontent.com/assets/12471122/22970778/63069670-f3ae-11e6-8975-1e30b51efccc.png)

@gmarziou I think they moved this into centralized (using variables), so upgrading to alpha.6 will solve this.

**Comment by gmarziou** [comment] 2017-02-15 12:13
But unless I'm wrong variables are only available in SCSS not in CSS.

**Comment by jdubois** [comment] 2017-02-15 19:52
Closing as the PR is merged

**Closed by jdubois** 2017-02-15 19:52 UTC
Labels: angular-2, minor
