### ISSUE TITLE
yo jhipster:heroku error cannot bind to $port 

### ISSUE THREAD

**Issue by arnogeismar** [jhipster/generator-jhipster#5122] opened 2017-02-06 13:00 UTC
@jkutner I believe the heroku deploy is broken $PORT is probably not replaced with the actual port.

- Please follow the issue template below for bug reports and feature requests.
- Tickets opened without any of these informations will be **closed** without any explanation.

##### **Overview of the issue**

yo jhipster:heroku does not deploy my app correctly to heroku and it crashes when it is started on heroku
it states "Error R10 boot timeout -> web proces failed to bind to port $PORT within 90s of launch

##### **Motivation for or Use Case**
I cannot deploy my app to production

##### **Reproduce the error**
Welcome to the JHipster Generator v4.0.1
Documentation for creating an application: https://jhipster.github.io/creating-an-app/
Application files will be generated in folder: /Users/arnog/Documents/auction
? (1/15) Which *type* of application would you like to create? Microservice application
? (2/15) What is the base name of your application? auctioneerApi
? (3/15) Would you like to install other generators from the JHipster Marketplace? No
? (4/15) As you are running in a microservice architecture, on which port would like your server to run? It should be unique to avoid port conflicts. 8070
? (5/15) What is your default Java package name? be.techninja.auctioneer
? (6/15) Which *type* of authentication would you like to use? JWT authentication (stateless, with a token)
? (7/15) Which Service Discovery and Configuration solution would you like to use? JHipster Registry (using Eureka and Spring Cloud Config)
? (8/15) Which *type* of database would you like to use? SQL (H2, MySQL, MariaDB, PostgreSQL, Oracle)
? (9/15) Which *production* database would you like to use? PostgreSQL
? (10/15) Which *development* database would you like to use? PostgreSQL
? (11/15) Do you want to use Hibernate 2nd level cache? Yes, with HazelCast (distributed cache, for multiple nodes)
? (12/15) Would you like to use Maven or Gradle for building the backend? Maven
? (13/15) Which other technologies would you like to use? Search engine using Elasticsearch
? (14/15) Would you like to enable internationalization support? Yes
? Please choose the native language of the application? Dutch
? Please choose additional languages to install English, French, German
? (15/15) Besides JUnit and Karma, which testing frameworks would you like to use? 
❯◉ Gatling
 ◯ Cucumber

hi09666:auctioneer-api arnog$ yo jhipster:heroku
Heroku configuration is starting
? Name to deploy as: auctioneerApi
? On which region do you want to deploy ? eu

Using existing Git repository

Installing Heroku CLI deployment plugin

Creating Heroku application and setting up node environment
heroku create auctioneer-api --region eu
https://auctioneer-api.herokuapp.com/ | https://git.heroku.com/auctioneer-api.git

Provisioning addons
Created heroku-postgresql --as DATABASE

? What is the URL of your JHipster Registry? https://auctioneer-registry.herokuapp.com
JHIPSTER_REGISTRY_URL: https://auctioneer-registry.herokuapp.com

Creating Heroku deployment files
   create src/main/resources/config/bootstrap-heroku.yml
   create src/main/resources/config/application-heroku.yml
   create Procfile

Building application
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Auctioneer Api 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-resources-plugin:3.0.1:copy-resources (default-resources) @ auctioneer-api ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 11 resources
[INFO] Copying 7 resources
[INFO]
[INFO] --- maven-resources-plugin:3.0.1:resources (default-resources) @ auctioneer-api ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 11 resources
[INFO] Copying 7 resources
[INFO]
[INFO] --- maven-enforcer-plugin:1.4.1:enforce (enforce-versions) @ auctioneer-api ---
[INFO]
[INFO] --- jacoco-maven-plugin:0.7.7.201606060606:prepare-agent (pre-unit-tests) @ auctioneer-api ---
[INFO] argLine set to -javaagent:/Users/arnog/.m2/repository/org/jacoco/org.jacoco.agent/0.7.7.201606060606/org.jacoco.agent-0.7.7.201606060606-runtime.jar=destfile=/Users/arnog/Documents/auction/auctioneer-api/target/test-results/coverage/jacoco/jacoco.exec -Djava.security.egd=file:/dev/./urandom -Xmx256m
[INFO] 
[INFO] --- spring-boot-maven-plugin:1.4.4.RELEASE:build-info (default) @ auctioneer-api ---
[INFO]
[INFO] --- maven-compiler-plugin:3.6.0:compile (default-compile) @ auctioneer-api ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 47 source files to /Users/arnog/Documents/auction/auctioneer-api/target/classes
[INFO]
[INFO] --- maven-resources-plugin:3.0.1:testResources (default-testResources) @ auctioneer-api ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 3 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.6.0:testCompile (default-testCompile) @ auctioneer-api ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-surefire-plugin:2.18.1:test (default-test) @ auctioneer-api ---
[INFO] Tests are skipped.
[INFO] 
[INFO] --- jacoco-maven-plugin:0.7.7.201606060606:report (post-unit-test) @ auctioneer-api ---
[INFO] Skipping JaCoCo execution due to missing execution data file.
[INFO] 
[INFO] --- maven-war-plugin:2.6:war (default-war) @ auctioneer-api ---
[INFO] Packaging webapp
[INFO] Assembling webapp [auctioneer-api] in [/Users/arnog/Documents/auction/auctioneer-api/target/auctioneer-api-0.0.1-SNAPSHOT]
[INFO] Processing war project
[INFO] Copying webapp resources [/Users/arnog/Documents/auction/auctioneer-api/src/main/webapp]
[INFO] Webapp assembled in [1094 msecs]
[INFO] Building war: /Users/arnog/Documents/auction/auctioneer-api/target/auctioneer-api-0.0.1-SNAPSHOT.war
[INFO] 
[INFO] --- spring-boot-maven-plugin:1.4.4.RELEASE:repackage (default) @ auctioneer-api ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 10.440 s
[INFO] Finished at: 2017-02-06T13:41:57+01:00
[INFO] Final Memory: 68M/387M
[INFO] ------------------------------------------------------------------------

Deploying application

Uploading your application code.
This may take several minutes depending on your connection speed...
Uploading auctioneer-api-0.0.1-SNAPSHOT.war
-----> Packaging application...
       - app: auctioneer-api
       - including: target/auctioneer-api-0.0.1-SNAPSHOT.war
-----> Creating build...
       - file: slug.tgz
       - size: 82MB
-----> Uploading build...
       - success
-----> Deploying...
remote:
remote: -----> heroku-deploy app detected
remote: -----> Installing OpenJDK 1.8... done
remote: -----> Discovering process types
remote:        Procfile declares types -> web
remote:
remote: -----> Compressing...
remote:        Done: 130.8M
remote: -----> Launching...
remote:        Released v5
remote:        https://auctioneer-api.herokuapp.com/ deployed to Heroku
remote:
-----> Done

Your app should now be live. To view it run
	heroku open
And you can view the logs with this command
	heroku logs --tail
After application modification, redeploy it with
	yo jhipster:heroku
hi09666:auctioneer-api arnog$ heroku logs --tail
2017-02-06T12:41:30.476950+00:00 app[api]: Release v1 created by user arnogeismar@gmail.com
2017-02-06T12:41:30.476950+00:00 app[api]: Initial release by user arnogeismar@gmail.com
2017-02-06T12:41:30.783960+00:00 app[api]: Release v2 created by user arnogeismar@gmail.com
2017-02-06T12:41:31.537358+00:00 app[api]: Attach DATABASE (@ref:postgresql-globular-44531) by user arnogeismar@gmail.com
2017-02-06T12:41:31.537358+00:00 app[api]: Release v3 created by user arnogeismar@gmail.com
2017-02-06T12:41:30.703552+00:00 app[api]: Release v1 created by user arnogeismar@gmail.com
2017-02-06T12:41:30.667928+00:00 app[api]: Release v2 created by user arnogeismar@gmail.com
2017-02-06T12:41:31.774675+00:00 app[api]: Release v3 created by user arnogeismar@gmail.com
2017-02-06T12:41:30.667928+00:00 app[api]: Enable Logplex by user arnogeismar@gmail.com
2017-02-06T12:41:44.443705+00:00 app[api]: Set JHIPSTER_REGISTRY_URL config vars by user arnogeismar@gmail.com
2017-02-06T12:41:44.443705+00:00 app[api]: Release v4 created by user arnogeismar@gmail.com
2017-02-06T12:41:44.931611+00:00 app[api]: Release v4 created by user arnogeismar@gmail.com
2017-02-06T12:43:01.417324+00:00 app[api]: Release v5 created by user arnogeismar@gmail.com
2017-02-06T12:43:01.429052+00:00 app[api]: Scaled to web@1:Free by user arnogeismar@gmail.com
2017-02-06T12:43:01.417324+00:00 app[api]: Deploy 586d216 by user arnogeismar@gmail.com
2017-02-06T12:43:01.700655+00:00 heroku[slug-compiler]: Slug compilation started
2017-02-06T12:43:01.700666+00:00 heroku[slug-compiler]: Slug compilation finished
2017-02-06T12:43:01.672946+00:00 app[api]: Release v5 created by user arnogeismar@gmail.com
2017-02-06T12:43:07.943079+00:00 heroku[web.1]: Starting process with command `java $JAVA_OPTS -Xmx256m -jar target/*.war --spring.profiles.active=prod,heroku --server.port=48104`
2017-02-06T12:43:10.456312+00:00 app[web.1]: Setting JAVA_TOOL_OPTIONS defaults based on dyno size. Custom settings will override them.
2017-02-06T12:43:10.460274+00:00 app[web.1]: Picked up JAVA_TOOL_OPTIONS: -Xmx350m -Xss512k -Dfile.encoding=UTF-8
2017-02-06T12:43:30.050778+00:00 app[web.1]: 
2017-02-06T12:43:30.050794+00:00 app[web.1]:         ██╗ ██╗   ██╗ ████████╗ ███████╗   ██████╗ ████████╗ ████████╗ ███████╗
2017-02-06T12:43:30.050795+00:00 app[web.1]:         ██║ ██║   ██║ ╚══██╔══╝ ██╔═══██╗ ██╔════╝ ╚══██╔══╝ ██╔═════╝ ██╔═══██╗
2017-02-06T12:43:30.050800+00:00 app[web.1]:         ██║ ████████║    ██║    ███████╔╝ ╚█████╗     ██║    ██████╗   ███████╔╝
2017-02-06T12:43:30.050801+00:00 app[web.1]:   ██╗   ██║ ██╔═══██║    ██║    ██╔════╝   ╚═══██╗    ██║    ██╔═══╝   ██╔══██║
2017-02-06T12:43:30.050802+00:00 app[web.1]:   ╚██████╔╝ ██║   ██║ ████████╗ ██║       ██████╔╝    ██║    ████████╗ ██║  ╚██╗
2017-02-06T12:43:30.050802+00:00 app[web.1]:    ╚═════╝  ╚═╝   ╚═╝ ╚═══════╝ ╚═╝       ╚═════╝     ╚═╝    ╚═══════╝ ╚═╝   ╚═╝
2017-02-06T12:43:30.050803+00:00 app[web.1]: 
2017-02-06T12:43:30.050804+00:00 app[web.1]: :: JHipster 🤓  :: Running Spring Boot 1.4.4.RELEASE ::
2017-02-06T12:43:30.050805+00:00 app[web.1]: :: http://jhipster.github.io ::
2017-02-06T12:43:30.050836+00:00 app[web.1]: 
2017-02-06T12:44:38.402275+00:00 heroku[web.1]: Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 90 seconds of launch
2017-02-06T12:44:38.402436+00:00 heroku[web.1]: Stopping process with SIGKILL
2017-02-06T12:44:38.636987+00:00 heroku[web.1]: Process exited with status 137
2017-02-06T12:44:38.669391+00:00 heroku[web.1]: State changed from starting to crashed

##### **Related issues**
None that I know of
##### **Suggest a Fix**

Possibly $PORT is not replaced with the heroku port ?

##### **JHipster Version(s)**
4.0.1
 4.0.1

##### **JHipster configuration**
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
/Users/arnog/Documents/auction/auctioneer-api
└── generator-jhipster@4.0.1 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "jhipsterVersion": "4.0.1",
    "baseName": "auctioneerApi",
    "packageName": "be.techninja.auctioneer",
    "packageFolder": "be/techninja/auctioneer",
    "serverPort": "8075",
    "authenticationType": "jwt",
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "jwtSecretKey": "",
    "enableTranslation": true,
    "applicationType": "microservice",
    "testFrameworks": [
      "gatling"
    ],
    "jhiPrefix": "jhi",
    "skipClient": true,
    "skipUserManagement": true,
    "nativeLanguage": "nl",
    "languages": [
      "nl",
      "en",
      "fr",
      "de"
    ],
    "clientPackageManager": "yarn",
    "clientFramework": "angular1"
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

ls: no such file or directory: .jhipster/*.json

##### **Browsers and Operating System**

java version "1.8.0_60"
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)

git version 2.10.1 (Apple Git-78)

node: v6.9.5

npm: 3.10.10

bower: 1.8.0

gulp:
[13:56:08] CLI version 3.9.1

yeoman: 1.8.5

yarn: 0.19.1

Docker version 1.13.0, build 49bf474

docker-compose version 1.10.0, build 4bd6f1a

##### **Browsers and Operating System**

macOS Sierra 10.12.2
- [x ] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment] 2017-02-06 13:04
Your app is just taking too long to start. Are you sure you didn't lock your database? Have a look at how Liquibase works, there is a "lock" table that might prevent you to start.

**Comment by arnogeismar** [comment] 2017-02-06 13:27
@jdubois I am sure. It is a fresh heroku install. I ran the liquibase: releaseLocks Maven plugin successfully but still the same behavior

**Comment by arnogeismar** [comment] 2017-02-06 13:29
Their are also no entities in my project it is a completely fresh microservice generated app deployed to heroku without a previous dyno

**Comment by jdubois** [comment] 2017-02-06 13:31
great, thanks @arnogeismar 
then the issue is why it is taking so long to boot. Maybe you could increase the log level?

**Comment by arnogeismar** [comment] 2017-02-06 13:56
When I increase log levels I get this:

17-02-06T13:52:28.792814+00:00 app[web.1]: 2017-02-06 13:52:28.792 DEBUG 4 --- [           main] o.s.web.client.RestTemplate              : GET request for "https://auctioneer-registry.herokuapp.com/config/auctioneerApi/prod/master" resulted in 401 (Unauthorized); invoking error handler

altough my registry is running on that url

https://auctioneer-registry.herokuapp.com/#/

and the password for the registry is set in : 

application.yml

jhipster:
    registry:
        password: ********

**Comment by jdubois** [comment] 2017-02-06 13:58
Oh you are using the registry???? Sorry I didn't see this.
Then your app just waiting that the registry is up:

- Check if the registry is running
- Check if you have the correct URL
- Check if you have the correct login/password

It's one of those

**Comment by arnogeismar** [comment] 2017-02-06 14:13
Ok so for some reason it is not sending the correct username and password.
When I do the following with postman: 

http://auctioneer-registry.herokuapp.com/config/auctioneerApi/prod/master

basic auth: username: admin
                    password: ****
it works.

I am still wondering though why this is not done by default. the only thing I changed in my yml files is that I changed password: admin to my own password and configured the registry to also use this password

**Comment by jdubois** [comment] 2017-02-06 14:28
OK, so there must be a password error somewhere -> I'm closing this as it seems you wrote the wrong password somewhere, but if you have any hints/tips don't hesitate to post them, as I'm pretty sure it's bit more complex than that...

**Comment by ruddell** [comment] 2017-02-06 18:09
You need to set up the password with the registry's password - see the section "Using security with your JHipster Registry on Heroku" in https://jhipster.github.io/heroku/

`heroku config:set JHIPSTER_REGISTRY_URL="http://user:[password]@[appname].herokuapp.com"`

**Comment by PierreBesson** [comment] 2017-02-07 08:54
Could this have to do with the jhipster.registry.password property that I have added ? I have not tested Heroku with it.

**Comment by jdubois** [comment] 2017-02-07 08:55
Yes probably... Re-opening just to remember we should check this

**Comment by arnogeismar** [comment] 2017-02-07 10:10
@jdubois I managed to deploy to heroku by setting the registry url to this: 

heroku config:set JHIPSTER_REGISTRY_URL="http://admin:mypassword@myapp.herokuapp.com"

In the documentation it states the following

heroku config:set JHIPSTER_REGISTRY_URL="http://user:[password]@[appname].herokuapp.com"

an improvement would be

heroku config:set JHIPSTER_REGISTRY_URL="http://[username]:[password]@[appname].herokuapp.com"


probably unrelated but in my local setup jhipster.registry.password in bootstrap-dev.yml is not being replaced up and the application tries to connect to 

http://${jhipster.registry.password}@auctioneer-registry.herokuapp.com/config

regards,

**Comment by jdubois** [comment] 2017-02-07 13:26
@PierreBesson I confirm the "${jhipster.registry.password}" does not work... It just blew up my app :-(
Anyway I'm not sure this is useful, this is a conf property inside another conf property, it's more complex and I don't see the gain - shouldn't we better reverse it?

**Comment by jkutner** [comment] 2017-02-07 14:33
@arnogeismar make sure you are using `https://` and not `http://` in your `JHIPSTER_REGISTRY_URL` (that's a bug in the docs) https://github.com/jhipster/jhipster.github.io/pull/385

**Comment by jdubois** [comment] 2017-02-07 16:47
@jkutner @PierreBesson and for me you need to run this as the "admin" user, not the "user" user. I'm checking this.

**Comment by jdubois** [comment] 2017-02-07 16:56
@jkutner @PierreBesson yes you need to be admin, I'm changing the text and closing this with my commit

**Comment by PierreBesson** [comment] 2017-02-07 16:58
@jdubois For me this property is super important as the registry password would otherwise be passed passed through the configserver and also this separate cleanly the "secret" (the registry password) from the config (the registry URL which can be a list of eureka server separated by commas).

**Closed** 2017-02-07 16:58 UTC

**Comment by jdubois** [comment] 2017-02-07 17:02
@PierreBesson not sure I understand... The "admin" has access to both Eureka and the Config Server, but with JHipster Registry those are both the same application. Yes we could separate them, but we don't have to. And I tried with "user" and it didn't work, as with Heroku we only set the "admin" password. Are you OK with that, or do you want to change something? I'm a bit lost here

If you want to try with Heroku it's really super-simple, just click on the button on https://jhipster.github.io/heroku/

**Comment by PierreBesson** [comment] 2017-02-07 19:13
@jdubois Sorry I'm totally OK with the docs change you did for Heroku, I was just commenting on the need to keep the jhipster.registry.password property has I thought you wanted to remove it 😃 .

**Comment by jdubois** [comment] 2017-02-07 21:19
Well @PierreBesson I finally found my issue with it: it only works if you run with Maven. If you start the application with the "main" class from the IDE, the variable is not always replaced, and that's how you get the error. So there are some tests to do here, to make it fail proof.

**Comment by nutrimax1987** [comment] 2018-03-10 15:42
Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 90 seconds of launch
2018-03-10T15:34:24.734543+00:00 heroku[web.1]: Stopping process with SIGKILL
2018-03-10T15:34:24.900327+00:00 heroku[web.1]: Process exited with status 137
2018-03-10T15:34:24.912142+00:00 heroku[web.1]: State changed from starting to crashed
2018-03-10T15:34:25.001309+00:00 heroku[router]: at=error code=H20 desc="App boot timeout" method=GET path="/config/gate/prod/master" host=stocker-gateway.herokuapp.com request_id=acfa1d5f-8b6b-4779-9002-872ab6a21de9 fwd="54.195.66.141" dyno= connect= service= status=503 bytes= protocol=https
2018-03-10T15:34:27.116171+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/config/gate/prod/master" host=stocker-gateway.herokuapp.com request_id=bbbe00bf-11e7-4a7e-b9eb-15f253f117e6 fwd="54.195.66.141" dyno= connect= service= status=503 bytes= protocol=https

After deploying my gateway ( with postgres )..

1. Heroku gave me dyno with postgresql connection  
2. i Upgraded Heroku plan to 7$/month .. 'Hobby Dynos '

1. Maybe should i update it Database Credentials  my 'pom.xml' for liquibase and in 'application.yml' ?
2. Maybe the problem in https ?

**Comment by nutrimax1987** [comment] 2018-03-10 16:34
1. Redeploying it again ..
2. heroku config:set JHIPSTER_REGISTRY_URL="https://myRegistryUser:myRegistryPass@my-gateway-app.herokuapp.com"

and then got the erorr ...

at=error code=H20 desc="App boot timeout" method=GET path="/config/gate/prod/master" host=stocker-gateway.herokuapp.com request_id=8a41dade-874a-41e7-8d26-ad3c88abd031 fwd="54.217.179.76" dyno= connect= service= status=503 bytes= protocol=http

**Comment by gmarziou** [comment] 2018-03-10 16:38
@nutrimax1987 please don't comment on a one year old closed issue, please open a new one with all required details
