### ISSUE TITLE
Autocomplete in combobox

### ISSUE THREAD

**Issue by erensimsek** [jhipster/generator-jhipster#2504] opened 2015-12-18 22:02 UTC
Hi everyone,

I use JHipster in my new project. We need an develop autocomplete feature at all combobox. 
Is it good idea add this feature to JHipster for all generated list properties?

Thank you.

**Comment by jdubois** [comment] 2015-12-19 09:21
For autocompletion you need something like Lucene (at least that's how I would do it), and each keystroke will do a new GET request -> this looks a bit overkill for a "normal" situation.
But I'm sure many people would like to have this (we just had the exact same question in my company's internal mailing list).
So we need to see how this could be an option, maybe a JHipster module (not sure this is possible).
As you are going to code it anyway: once this is coded, can you provide some code sample, so we can see how easy to would be to integrate?

**Comment by geraldhumphries** [comment] 2015-12-19 18:31
I've programmed this for my own project. It also solves the "getAll() doesn't actually get all" problem with pagination enabled! It uses Elasticsearch and an Angular module called [ui-select](https://github.com/angular-ui/ui-selecthttps://github.com/angular-ui/ui-select).

https://gist.github.com/geraldhumphries/ba159d2ea93c41d8054a

**Comment by geraldhumphries** [comment] 2015-12-19 19:32
Another thing. The search method in entity controllers has this:             
```
if(response.status === 404) {
    $scope.otherEntities = OtherEntity.query({isActive: true});
}
```
Looking at git, the intention of that code is to load entities using the normal endpoint when elasticsearch finds nothing. The issue is that the elasticsearch resource never returns 404, it only returns 200 with `[]` as the result. So as far as I can tell, that code is never used.

**Comment by deepu105** [comment] 2015-12-21 11:05
There is an auto complete provoded by angular bootstrap which we are
shipping and it is really easy to use. Another option could be ui-select

**Comment by Vaelyr** [comment] 2015-12-22 07:00
I hate seeing service logic in controllers. But anyway why not just write a directive wrapper for ui-select or any autocomplete and pass some list you obtain asnyc and done? Having Elastic Search dependency seems overkill, whu not regular findAll without pagination?

**Comment by jdubois** [comment] 2015-12-28 13:12
I think what @geraldhumphries writes is a good solution (and besides he found an issue in the current ES code), so I'm closing this.
Maybe this could be part of the generator, or be a module in the future, if people are interested by having a generic solution to this problem.

**Closed by jdubois** 2015-12-28 13:12 UTC

**Comment by geraldhumphries** [comment] 2015-12-28 15:18
@Vaelyr that's a good idea, but with pagination there's no API endpoint for findAll without pagination. Discussion in #2251. The only option I've found aside from adding another endpoint  is to specify an extremely large page size, but that is definitely not optimal. For server side searching across all fields ES is the easiest solution but there are others, like an "all columns" Specification. If you only need to search one field then that's easy but would require another generator question. Do you have suggestions for how I can improve my code regarding "service logic in controllers"?

@jdubois I can open a separate issue and PR for the ES issue if you want. I would definitely be interested myself in having this in the generator or as a module.

**Comment by jdubois** [comment] 2015-12-29 13:01
@geraldhumphries as I'm not sure of all the impacts here, I'd prefer to see a module first. Then, if this is popular, we could put it into the main generator as an option. Is it fine for you?

**Comment by geraldhumphries** [comment] 2015-12-29 14:51
@jdubois I am actually talking about the `404` block of code I mentioned above that doesn't do anything. I can look into creating a module.

**Comment by erensimsek** [comment] 2016-01-06 13:49
Hello,

@jdubois I provide a code sample.

We replaced the generated code  from

    <div class="form-group">
        <label translate="atlantisApp.customer.company" for="field_company">company</label>
        <select class="form-control" id="field_company" name="company" ng-model="customer.company" ng-options="company as company.name for company in companys | orderBy:'name' track by company.id">
            <option value=""></option>
        </select>
    </div>

to

	<div class="form-group">
	    <label translate="atlantisApp.customer.company" for="field_company">company</label>
	    <ui-select ng-model="customer.company" id="field_company"  ng-disabled="disabled" >
	        <ui-select-match placeholder="Select or search a company in the list...">{{$select.selected.name}}</ui-select-match>
	        <ui-select-choices repeat="company in companys | filter: $select.search track by company.id">
	            <span ng-bind-html="company.name | highlight: $select.search"></span>
	        </ui-select-choices>
	    </ui-select>
	</div>

It runs in modal popup too. This option can be asked in generator.

**Comment by deepu105** [comment] 2016-01-06 15:29
I have used ui select extensively in a jhipster app, look wise it is good
but the way it is done is difficult to manage and i dont think it should be
that complex in angular,  its buggy and you have to tweak it a lot to get
it working fine in all scenarios.

It might be an overkill for normal apps

**Comment by SWEnthusiast** [comment] 2016-12-22 20:56
Hi friends 

I ran into this issue, I tried @geraldhumphries steps but the values are not pre populated in the drop down list. Not sure if anything changed since this post was created. 

@jdubois or @deepu105 Please point me to the jhipster documentation if there is any. 

Thanks

**Comment by jdubois** [comment] 2016-12-22 20:58
I'm sorry this is an old issue, which is closed, I don't have the time for this.

**Comment by geraldhumphries** [comment] 2016-12-22 21:24
I've replied to his comment in my Gist, so any discussion will probably take place there.
