### ISSUE TITLE
Client bundle not rebuilt after entity generation

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#5062] opened 2017-02-02 14:13 UTC
- Please follow the issue template below for bug reports and feature requests.
- Tickets opened without any of these informations will be **closed** without any explanation.

##### **Overview of the issue**

I tried to create my [blog demo](https://github.com/mraible/jhipster4-demo/blob/master/README.adoc) from using JHipster 4.0.0 and found that no site is rendered on http://localhost:8080 after generating entities. `yarn start` still works and I can see my app on http://localhost:9000.

##### **Motivation for or Use Case**

This worked when using `npm link` from master a few weeks ago.

##### **Reproduce the error**

Create a new application with the following settings.

<img width="1082" alt="screen shot 2017-02-02 at 6 50 52 am" src="https://cloud.githubusercontent.com/assets/17892/22552433/24d90010-e916-11e6-8832-5211abb852d6.png">

Here's my `.yo-json.rc`:

```
{
  "generator-jhipster": {
    "jhipsterVersion": "4.0.0",
    "baseName": "blog",
    "packageName": "org.jhipster",
    "packageFolder": "org/jhipster",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "jwtSecretKey": "3725191ac098f3a1425059b2808301ab7c546e39",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "clientFramework": "angular2",
    "testFrameworks": [
      "gatling",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "es"
    ]
  }
}
```

Create an `jhipster-jdl.jh` with the following contents.

```
entity Blog {
	name String required minlength(3),
	handle String required minlength(2)
}

entity Entry {
	title String required,
	content TextBlob required,
	date ZonedDateTime required
}

entity Tag {
	name String required minlength(2)
}

relationship ManyToOne {
	Blog{user(login)} to User,
	Entry{blog(name)} to Blog
}

relationship ManyToMany {
	Entry{tag(name)} to Tag{entry}
}

paginate Entry, Tag with infinite-scroll
```

Generate entities using `yo jhipster:import-jdl jhipster-jdl.jh`.

I had Maven running when I did this and noticed the menu was all wonky and didn't have messages translated. I restarted and localhost:8080 results in a blank page. I ran `mvn clean` and restarted again, but it's still blank with no errors in my console. Running `yarn start` works, but there's still no app on localhost:8080.

##### **Related issues**

I noticed the `navbar.component.html` still has old UI-Router attributes.

```html
<ul class="dropdown-menu" ngbDropdownMenu>
    <li uiSrefActive="active">
        <a class="dropdown-item" routerLink="blog" (click)="collapseNavbar()">
            <i class="fa fa-fw fa-asterisk" aria-hidden="true"></i>
            <span jhiTranslate="global.menu.entities.blog">Blog</span>
        </a>
    </li>
    <li uiSrefActive="active">
        <a class="dropdown-item" routerLink="entry" (click)="collapseNavbar()">
            <i class="fa fa-fw fa-asterisk" aria-hidden="true"></i>
            <span jhiTranslate="global.menu.entities.entry">Entry</span>
        </a>
    </li>
    <li uiSrefActive="active">
        <a class="dropdown-item" routerLink="tag" (click)="collapseNavbar()">
            <i class="fa fa-fw fa-asterisk" aria-hidden="true"></i>
            <span jhiTranslate="global.menu.entities.tag">Tag</span>
        </a>
    </li>
    <!-- jhipster-needle-add-entity-to-menu - JHipster will add entities to the menu here -->
</ul>
```

##### **JHipster Version(s)**

4.0.0

##### **JHipster configuration**

```
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
blog@0.0.0 /Users/mraible/dev/blog
├── UNMET PEER DEPENDENCY @angular/compiler@2.4.4
├── UNMET PEER DEPENDENCY @angular/core@2.4.4
└── generator-jhipster@4.0.0

```


##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "jhipsterVersion": "4.0.0",
    "baseName": "blog",
    "packageName": "org.jhipster",
    "packageFolder": "org/jhipster",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "jwtSecretKey": "3725191ac098f3a1425059b2808301ab7c546e39",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "clientFramework": "angular2",
    "testFrameworks": [
      "gatling",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "es"
    ]
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

Blog.json

```yaml
{
    "fluentMethods": true,
    "relationships": [
        {
            "relationshipType": "many-to-one",
            "relationshipName": "user",
            "otherEntityName": "user",
            "otherEntityField": "login"
        }
    ],
    "fields": [
        {
            "fieldName": "name",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "minlength"
            ],
            "fieldValidateRulesMinlength": 3
        },
        {
            "fieldName": "handle",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "minlength"
            ],
            "fieldValidateRulesMinlength": 2
        }
    ],
    "changelogDate": "20170202135634",
    "entityTableName": "blog",
    "dto": "no",
    "pagination": "no",
    "service": "no"
}
```

Entry.json

```yaml
{
    "fluentMethods": true,
    "relationships": [
        {
            "relationshipType": "many-to-one",
            "relationshipName": "blog",
            "otherEntityName": "blog",
            "otherEntityField": "name"
        },
        {
            "relationshipType": "many-to-many",
            "otherEntityRelationshipName": "entry",
            "relationshipName": "tag",
            "otherEntityName": "tag",
            "otherEntityField": "name",
            "ownerSide": true
        }
    ],
    "fields": [
        {
            "fieldName": "title",
            "fieldType": "String",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "content",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "text",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "date",
            "fieldType": "ZonedDateTime",
            "fieldValidateRules": [
                "required"
            ]
        }
    ],
    "changelogDate": "20170202135635",
    "entityTableName": "entry",
    "dto": "no",
    "pagination": "infinite-scroll",
    "service": "no"
}
```

Tag.json

```yaml
{
    "fluentMethods": true,
    "relationships": [
        {
            "relationshipType": "many-to-many",
            "relationshipName": "entry",
            "otherEntityName": "entry",
            "ownerSide": false,
            "otherEntityRelationshipName": "tag"
        }
    ],
    "fields": [
        {
            "fieldName": "name",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "minlength"
            ],
            "fieldValidateRulesMinlength": 2
        }
    ],
    "changelogDate": "20170202135636",
    "entityTableName": "tag",
    "dto": "no",
    "pagination": "infinite-scroll",
    "service": "no"
}
```

##### **Browsers and Operating System**

java version "1.8.0_112"
Java(TM) SE Runtime Environment (build 1.8.0_112-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.112-b16, mixed mode)

git version 2.10.2

node: v6.9.1

npm: 3.10.8

bower: 1.8.0

gulp:
[07:11:37] CLI version 1.2.2

yeoman: 1.8.5

yarn: 0.18.1

Docker version 1.13.0, build 49bf474

docker-compose version 1.10.0, build 4bd6f1a
```

**Comment by jdubois** [comment] 2017-02-02 14:16
@mraible don't hesitate to chat with me, you wrote the book, you deserve more help than just the ticket system :-)

I'm having a look ASAP, but you could try:

- Delete your `node_modules` folder to be sure you don't have some old JHipster link there
- Delete your `src` folder -> we refactored very recently the routes, so the names have changed. So if you regenerate on top of an older project, you might have different files for the same route, and that should be pretty bad!!

**Comment by pascalgrimaud** [comment] 2017-02-02 14:20
The 1st time you generated the project, I can see some folder inside target/www
Every time you launch `mvn clean` will delete target, so there is no `www`
I think you have to run `yarn run webpack:build`, and after, `mvn`

I'm learning the new workflow with Angular2, am I correct ?

**Comment by mraible** [comment] 2017-02-02 14:21
I generated from scratch and I believe this issue was caused by the fact that I had Maven running when I generated the entities, then I ran `./mvnw` in another window after generating them. I tried again and this time, localhost:8080 loads, but there's no items in the menu.

![screen shot 2017-02-02 at 7 18 23 am](https://cloud.githubusercontent.com/assets/17892/22552912/0c444abc-e918-11e6-959f-1a66d2ca5eea.png)

I tried `yarn start` and that version has menu items. After doing this, I reloaded my localhost:8080 tab and the menu items show.

I think you're right @pascalgrimaud, you can't just run `./mvnw`, there's another step that needs to happen. I'll try again and see if I can figure out what it is.

**Comment by jdubois** [comment] 2017-02-02 14:23
Yes you should have:

- `mvn` running for the backend
- `yarn start` running for the frontend

I documented this here: https://jhipster.github.io/development/

**Comment by jdubois** [comment] 2017-02-02 14:24
OK I got it working on my laptop without any issue, this is either a config error (my first comment) or the commands not running (my second comment)

**Comment by mraible** [comment] 2017-02-02 14:28
@jdubois OK, but this is different from JHipster 3.x. I can document accordingly. With JHipster 3, `gulp` was run after the entity generation. With JHipster 4, it seems like `npm run webpack:build:dev` should be run after entity generation. If you do this, `./mvnw` works as expected.

**Comment by jdubois** [comment] 2017-02-02 14:31
Yes and no :-)

- We do run `yarn start` (== Webpack) after project generation, that's why the initial project works
- We don't run it after entity generation -> the issue is that people might already have it running (I keep it running all the time), so we can't run it at that moment. So in that case you need to run it manually. But anyway, if you are developing, this should always be running.

**Comment by deepu105** [comment] 2017-02-02 14:33
If you do a clean then you need to pass the the webpack profile switch in
order to rebuild everything (I need to update this in docs)
for maven/gradle run

   - ./mvnw -Pdev,
   ​webpack
   -
   - ./gradlew -P
   ​dev
    -P
   ​
   webpack



Thanks & Regards,
Deepu

**Comment by deepu105** [comment] 2017-02-02 14:35
​If you have webpack dev server running with `yarn start` then it should
compile the new files automatically when created. I'll test this tonight
and fix if there is any issue. I'll also update the docs with the new dev
workflow​


Thanks & Regards,
Deepu

**Comment by deepu105** [comment] 2017-02-02 14:39
For angular 2 `yarn start` must be running or you need to run `yarn run
webpack:build:dev` manually as there is no point in running them after
generation. Its like having to run mvnw if you want to run the with
typescript you have to have both process running. we should just document
this and people need to follow this there is no way around it.


Thanks & Regards,
Deepu

**Comment by mraible** [comment] 2017-02-02 14:46
This makes sense now that I know about it. We should just make sure and document this since using `./mvnw` with JHipster 3 would automatically rebuild everything w/o an additional profile.

I found another issue - the "Administration" menu doesn't disappear for non-admin users. It just doesn't render - so there's a large gap in the menu.

![screen shot 2017-02-02 at 7 44 40 am](https://cloud.githubusercontent.com/assets/17892/22553966/c0a202a8-e91b-11e6-853f-54b1bcbbff2e.png)

**Comment by jdubois** [comment] 2017-02-02 14:48
Oh this might be linked to the latest PR from @gmarziou with the "invisible" class.... Could you do a specific ticket for that?

**Comment by mraible** [comment] 2017-02-02 14:55
@jdubois Done at https://github.com/jhipster/generator-jhipster/issues/5063

**Comment by deepu105** [comment] 2017-02-04 16:44
closing this as there is nothing to do here except improving docs if possible

**Comment by mraible** [comment] 2017-02-13 20:54
I think we can do better than improve the docs. With AngularJS, the entity generator runs `gulp` after it generates the entities, both for `jhipster:entity`[1] and `jhipster:import-jdl`[2]. 

We've seen a LOT of issues related to this since we released 4.x. Why can't the entity/import-jdl generators just run `webpack:build` after generation like we do with AngularJS?

1. https://github.com/jhipster/generator-jhipster/blob/master/generators/entity/index.js#L641
2. https://github.com/jhipster/generator-jhipster/blob/master/generators/import-jdl/index.js#L85

**Comment by jdubois** [comment] 2017-02-13 21:32
It could, but the issue is that it's supposed to be already running, as you should have `yarn start` (or `npm start`) running if you follow the doc. And we can't start it twice, or we would probably have some wrong result.

**Comment by jdubois** [comment] 2017-02-13 21:33
The best we could do is add even more documentation.
Then I don't understand what people do, if `yarn start` doesn't work, then nothing works. You can't work with Angular 2 without it.

**Comment by mraible** [comment] 2017-02-13 22:11
> And we can't start it twice, or we would probably have some wrong result.

Correct, but we can build `npm run webpack:build:dev` which is what we did with AngularJS and `gulp`. 

With JHipster 3.x, if you generated entities, the UI was rebuilt for you after generation. With JHipster 4.x, it is not. Yes, if you're running 'yarn start', it will be - but in 3.x this was not a requirement. We've changed the behavior and made it difficult for people familiar with the library to use 4.x. 

I think it makes sense to fix this since even I had an issue with it initially. I'd be happy to create a PR.

**Comment by jdubois** [comment] 2017-02-13 22:17
For JHipster 3 we didn't have to rebuild anything, as it was all JavaScript. With TypeScript it's different, you need to compile the application to have something running.
I don't have a better solution than adding documentation - and anyway you will need to get used to `yarn start` if you want to develop. But if you find something better, yes please do a PR.

**Comment by mraible** [comment] 2017-02-13 22:23
We didn't have to build anything, but we did have to inject the new JS files into `index.html`, which is _similar_ to building everything.

**Comment by jdubois** [comment] 2017-02-13 22:24
Oh yes you are right. But we didn't have another server running at the same time - maybe you could try to run it, I have no idea if that would fail or not.

**Comment by mraible** [comment] 2017-02-13 22:25
OK, I'll create a PR and do some tests. Reopening this issue so I can target it with the PR.

**Closed** 2017-02-14 06:08 UTC
