### ISSUE TITLE
Could not display micro-service on UI Gateway

### ISSUE THREAD

**Issue by rainee007** [jhipster/generator-jhipster#3659] opened 2016-05-28 11:31 UTC
##### **Overview of the issue**

Could not display micro-service on UI Gateway.
<img width="1205" alt="screen shot 2016-05-28 at 7 25 49 pm" src="https://cloud.githubusercontent.com/assets/15570056/15627048/1c05beb8-250a-11e6-9605-b821c1420afb.png">
##### **Motivation for or Use Case** 

I have ever seen this worked, and also I think it should work without any other setting.

##### **JHipster Version(s)** 

3.4.0

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 

.yo-rc.json @UI Gateway:
~~~
{
  "generator-jhipster": {
    "jhipsterVersion": "3.4.0",
    "baseName": "qyboi",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": "no",
    "buildTool": "maven",
    "jwtSecretKey": "0ffc30fffb1fe3a2952d5b2ec1d16b2e90c4c1c2",
    "useSass": false,
    "applicationType": "gateway",
    "testFrameworks": [
      "gatling"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "zh-cn",
    "languages": [
      "zh-cn",
      "en"
    ]
  }
}
~~~

.yo-rc.json @ Ticket (microservice):
~~~
{
  "generator-jhipster": {
    "jhipsterVersion": "3.4.0",
    "baseName": "ticket",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8082",
    "authenticationType": "jwt",
    "hibernateCache": "no",
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": "no",
    "buildTool": "maven",
    "jwtSecretKey": "1db7d0e040bffb9651e05317fc8844ed3ecb840d",
    "enableTranslation": true,
    "applicationType": "microservice",
    "testFrameworks": [
      "gatling"
    ],
    "jhiPrefix": "jhi",
    "skipClient": true,
    "skipUserManagement": true,
    "nativeLanguage": "zh-cn",
    "languages": [
      "zh-cn",
      "en"
    ]
  }
}
~~~

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory** 

UI Gateway:
../
Country.json
Department.json
Employee.json
HelloImage.json
Item.json
Job.json
JobHistory.json
Location.json
Region.json
Task.json

Ticket:
HelloImage.json

##### **Browsers and Operating System** 

Mac, Chrome and Firefox.

##### **Reproduce the error** 

really simple steps:
1. run jhipster registry
2. yo jhipster, to generate UI gateway project (JWT token)
3. yo jhipster, to generate "Ticket" microservie project
4. regenerate entity from microservice to ui gateway
5. run both (ui, ticket)

##### **Suggest a Fix** 

looks like token passing error during access to microservice API

**Comment by rainee007** [comment] 2016-05-28 11:34
by the way, UI can CRUD HelloImage entity.

**Comment by ruddell** [comment] 2016-05-28 14:47
@rainee007 I followed the steps to reproduce the error (using your .yo-rc.json files) and the the Ticket API docs appeared correctly for me: [Screenshot](https://cloud.githubusercontent.com/assets/4294623/15627855/bd101440-24ae-11e6-8568-b2ea6afbf36e.png).  Can you view the API docs for your gateway?

It's a weird error because accessing the Swagger API page normally requires the admin role...

**Comment by gmarziou** [comment] 2016-05-28 16:41
If UI works, it cannot be a problem with token passing. I would rather think it's a problem in the swagger-ui page, you should have look at the browser console to see what headers are passed on request to get the swagger JSON spec.

**Comment by pascalgrimaud** [comment] 2016-05-28 17:10
I already encountered the same problem, when developping and using spring boot devtools to restart microservices/gateway. But I don't know the exact scenario how to reproduce it

**Comment by rainee007** [comment] 2016-05-30 04:32
I could saw local api:
![screen shot 2016-05-30 at 12 29 44 pm](https://cloud.githubusercontent.com/assets/15570056/15639778/80b8984a-2662-11e6-8aad-bdb90eb0e82c.png)

**Comment by rainee007** [comment] 2016-05-30 06:16
But could not see micro-service api from same portal same session:


![screen shot 2016-05-30 at 12 27 33 pm](https://cloud.githubusercontent.com/assets/15570056/15641082/ea1dd864-2670-11e6-8279-edc367535dbc.png)

**Comment by jdubois** [comment] 2016-05-30 07:55
What is strange is that you have that timeout on "localhost:8080" which is the server+port of your gateway. That should not be possible, it should request the microservice instead.
Did you any kind of specific configuration here?
Otherwise we might close it, as I can't reproduce it, as other people in this thread.

**Comment by rainee007** [comment] 2016-05-30 08:26
nothing specific, just changed MySQL DB password.
And I am very curios that , I could CRUD the entity in Micro-service, but not see the api.

**Comment by rainee007** [comment] 2016-05-30 08:31
Also, I really experienced TIMEOUT when I created the entity, but after I closed the creation UI, the entity had been created even the TIMEOUT was warned.

**Comment by rainee007** [comment] 2016-05-30 13:05
I deployed the project @ http://54.223.67.152:8080/, on public network. with UAA, jhipster registry, and only one micro-service 'hello' with entity 'message', I can create it, can't see its api.

**Comment by rainee007** [comment] 2016-05-30 15:19
It seemed the problem recovered itself now. (It did not work this afternoon)

**Comment by PierreBesson** [comment] 2016-05-30 15:39
I can see that it works now. I advice you don't leave your project on a publicly accessible server for too long. 
However, I'm a bit confused, because your .yo-rc.json stated that you used JWT auth but your last messages says that you use the UAA so Oauth2. Did you experience the problem only with jwt ?

**Comment by rainee007** [comment] 2016-05-31 03:07
Yes, I met the problem for both, I guess the network environment changed on my laptop, caused the problem. In office, I need to switch the subnets during work. I am not sure if this cause the issue.

**Comment by jdubois** [comment] 2016-05-31 05:36
I'm closing this as we can't reproduce and this seems like an environment issue.

**Closed by jdubois** 2016-05-31 05:36 UTC
