### ISSUE TITLE
Type 'Subscription' is not assignable to type 'Subscription'

### ISSUE THREAD

**Issue by ValoData** [jhipster/generator-jhipster#7554] opened 2018-05-01 16:22 UTC
##### **Overview of the issue**

I am getting the following message when building the app without any entity ( I tried to clear the cache from npm)

ERROR in [at-loader] ./src/main/webapp/app/admin/user-management/user-management-detail.component.ts:23:9 
    TS90010: Type 'Subscription' is not assignable to type 'Subscription'. Two different types with this name exist, but they are unrelated.
  Property '_parent' is protected but type 'Subscription' is not a class derived from 'Subscription'.

##### **Reproduce the error**

Generate a new monolithic JHipster application with latest JHipster version. 

##### **JHipster Version(s)**

```
ng-hipster-test@0.0.0 /home/ulrich/ngHipsterTest
└── generator-jhipster@4.14.3 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp"
    },
    "jhipsterVersion": "4.14.3",
    "baseName": "ngHipsterTest",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

openjdk version "1.8.0_152"
OpenJDK Runtime Environment (Zulu 8.25.0.1-linux64) (build 1.8.0_152-b16)
OpenJDK 64-Bit Server VM (Zulu 8.25.0.1-linux64) (build 25.152-b16, mixed mode)

git version 2.7.4

node: v8.11.1

npm: 5.6.0

bower: 1.8.2

gulp:
[17:13:55] CLI version 3.9.1

yeoman: 2.0.1

yarn: 1.6.0

Docker version 1.13.1, build 092cba3

##### **Browsers and Operating System**

Ubuntu 16 + Chrome

- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment] 2018-05-01 16:56
I tested both with your release and with the current master branch, I couldn't reproduce.... How did you generate your app? How did you install JHipster? Did you do anything specific? Otherwise, indeed, you could clean up your node_modules and try again, but that's very weird.

I'm closing as I can't reproduce (so other team members don't lose time here), but if you have more information please add comments and I'll re-open if possible.

**Closed by jdubois** 2018-05-01 16:56 UTC

**Comment by SidMorad** [comment] 2018-05-02 05:14
I was hit with this issue couple of times and I agree, this is hard to reproduce and being very strange. First I do have almost exact same version of everything in development and production, and production build never had this issue, it only happens in my development machine. and it happens while executing following command:
`node --max_old_space_size=4096 node_modules/webpack/bin/webpack.js --config webpack/webpack.prod.js --profile`

And as @jdubois did mention best solution I found so far is deleting `node_modules` directory and if it didn't work then I will go for next directories, including(priority from top to down):
- `./node`
- `M2_REPO/com/github/eirslett/node/8.9.4/node-8.9.4-linux-x64.tar.gz`
- `~/.npm`
And if still no luck, I again delete all mentioned directories together.
Please let us know if you know what is the root of this issue? or there is a better fix? thanks.

p.s. I also do confirm, this happens for me very rarely and is not that much annoying.

**Comment by ValoData** [comment] 2018-05-02 09:06
I was not able to determine the cause but deleting the node_modules directory from the global envt did the trick
