### ISSUE TITLE
No admin metrics and log shown

### ISSUE THREAD

**Issue by vleboulanger** [jhipster/generator-jhipster#9932] opened 2019-06-18 08:57 UTC
##### **Overview of the issue**

I upgrade my project from jhipster 5.8.2 to 6.1.0. Since this upgrade, I can not see metrics and logs  in admin interface

##### **Motivation for or Use Case**

When I want open logs screen, I have this error in chrome console : 

`{error: SyntaxError: Unexpected token < in JSON at position 0 at JSON.parse (<anonymous>) at XMLHtt…, text: "<!doctype html> <html class="no-js" lang="fr" dir=…="app/global.bundle.js"></script></body> </html> "}`

It is important to can change level logs

##### **Suggest a Fix**

I have no idea how solve it

##### **JHipster Version(s)**

JHIPSTER version : 6.1.0

##### **JHipster configuration**

file .yo-rc.json 

`{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "fr.app.my",
      "nativeLanguage": "fr"
    },
    "jhipsterVersion": "6.1.0",
    "applicationType": "monolith",
    "baseName": "yvidya",
    "packageName": "fr.app.my",
    "packageFolder": "fr/app/my",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "gradle",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "ee=",
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "npm",
    "testFrameworks": [
      "gatling",
      "cucumber"
    ],
    "jhiPrefix": "jhi",
    "otherModules": [],
    "enableTranslation": true,
    "nativeLanguage": "fr",
    "languages": [
      "fr",
      "en"
    ],
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "clientTheme": "none"
  }
}`

##### **Environment and Tools**

java version "11.0.3" 2019-04-16 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.3+12-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.3+12-LTS, mixed mode)

git version 2.19.1.windows.1

node: v10.16.0

npm: 6.9.0

yeoman: 2.0.5

yarn: 1.16.0

##### **Browsers and Operating System**

Windows 10 pro and Chrome

**Comment by clement26695** [comment] 2019-06-24 09:13
Hi @vleboulanger 

I tried to reproduce your issue but didn't manage to reproduce. Do you have a repository I could use to see if I can help you?

**Comment by vleboulanger** [comment] 2019-06-24 12:06
Sorry I have no repository

**Comment by PierreBesson** [comment] 2019-06-24 16:52
You probably also need to upgrade the frontend library which contains the metrics view. I think at some point the endpoint `/jhi-metrics` was renamed to `/jhimetrics`

**Comment by pascalgrimaud** [comment] 2019-06-30 13:37
@vleboulanger : sorry, I can't reproduce too, and I'm pretty sure it comes from your upgrade.

I'm closing the ticket as there is no issue on our side. Don't hesitate to comment or provide a fresh repo with the bug.

**Closed by pascalgrimaud** 2019-06-30 13:37 UTC
Labels: area: needs-reproduction
