### ISSUE TITLE
user-management-update.component.ts - create new user

### ISSUE THREAD

**Issue by markos3d** [jhipster/generator-jhipster#19482] opened 2022-08-19 21:34 UTC
##### **Overview of the issue**

With update to Angular 14, save method in user-management-update.component.ts is refactored and user cannot be created.

##### **Motivation for or Use Case**

Cannot create new user

##### **Reproduce the error**
1. Generate and start app
2. Login and navigate to Administration/User management
3. Click on "Create a new user"
4. Populate form and save
5. Response code from api is 500

##### **Suggest a Fix**
save(): void {
    this.isSaving = true;
    const user = this.editForm.getRawValue();
    if (user.id !== null) { // should be **user.id !== undefined** as it was in previous releases
      this.userService.update(user).subscribe({
        next: () => this.onSaveSuccess(),
        error: () => this.onSaveError(),
      });
    } else {
      this.userService.create(user).subscribe({
        next: () => this.onSaveSuccess(),
        error: () => this.onSaveError(),
      });
    }
  }

##### **JHipster Version(s)**

```
jhipster@0.0.1-SNAPSHOT /home/marko/Desktop/mongo-diff
└── generator-jhipster@7.9.2

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**
<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "applicationType": "monolith",
    "authenticationType": "jwt",
    "baseName": "jhipster",
    "blueprints": [],
    "buildTool": "maven",
    "cacheProvider": "ehcache",
    "clientFramework": "angularX",
    "clientPackageManager": "npm",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "cypressAudit": true,
    "cypressCoverage": true,
    "databaseType": "mongodb",
    "devDatabaseType": "mongodb",
    "devServerPort": 4200,
    "dtoSuffix": "DTO",
    "enableGradleEnterprise": false,
    "enableHibernateCache": false,
    "enableSwaggerCodegen": false,
    "enableTranslation": true,
    "entitySuffix": "",
    "jhiPrefix": "jhi",
    "jhipsterVersion": "7.9.2",
    "languages": ["en"],
    "messageBroker": "kafka",
    "microfrontend": false,
    "microfrontends": [],
    "nativeLanguage": "en",
    "otherModules": [],
    "pages": [],
    "prodDatabaseType": "mongodb",
    "reactive": false,
    "searchEngine": false,
    "serverPort": "8080",
    "serverSideOptions": ["websocket:spring-websocket", "messageBroker:kafka"],
    "serviceDiscoveryType": "no",
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "skipUserManagement": false,
    "testFrameworks": ["cypress"],
    "websocket": "spring-websocket",
    "withAdminUi": true
  }
}

##### **Browsers and Operating System**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment] 2022-08-20 00:59
Fixed in main. Duplicate of https://github.com/jhipster/generator-jhipster/issues/19369.

**Closed by mshima** 2022-08-20 00:59 UTC
Labels: area: triage, theme: undefined
