### ISSUE TITLE
Pattern 2 - Split generated code and custom code does not work with files indicated in .yo-resolve file

### ISSUE THREAD

**Issue by jperezdelafuente** [jhipster/generator-jhipster#24313] opened 2023-11-21 14:51 UTC
##### **Overview of the issue**

When I have model changes and regenerate the project, the files that I indicate in the .yo-resolve file are not omitted and are regenerated with changes

https://www.jhipster.tech/tips/035_tip_combine_generation_and_custom_code.html#pattern-2---split-generated-code-and-custom-code

##### **Motivation for or Use Case**

Avoid overwriting custom files using .yo-resolve file when executing jhipster jdl model.jh

##### **JHipster Version(s)**

Jhipster 8.0.0

##### **JHipster configuration**

  <details>
  <summary>model.jh</summary>
  <pre>
application {
  config {
    applicationType monolith,
    baseName foo,
    packageName com.foo,
    jhiPrefix gsr,
    authenticationType session,
    databaseType sql,
    devDatabaseType h2Disk,
    prodDatabaseType oracle,
    enableHibernateCache true,
    cacheProvider ehcache,
    buildTool maven,
    testFrameworks [cypress, gatling, cucumber],
    clientFramework angular,
    enableTranslation true,
    nativeLanguage es,
    languages [es, en]
  }
  entities *
}

/** entity foo */
entity Foo(foo) {
    foo String required maxlength(20)
}
  </pre>
  </details>

  <details>
  <summary>./yo-resolve</summary>
  <pre>
pom.xml skip
  </pre>
  </details>

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment] 2023-11-21 16:37
Duplicate of https://github.com/jhipster/generator-jhipster/issues/24244

**Closed by mshima** 2023-11-21 16:37 UTC
Labels: area: triage, theme: undefined
