### ISSUE TITLE
Unable to add new field or new entity 7.8.1

### ISSUE THREAD

**Issue by vrijmetse** [jhipster/generator-jhipster#18391] opened 2022-04-17 06:42 UTC
##### **Overview of the issue**

Unable to add new field or new entity for my monolith application as I get error as follows

```
Error: Error parsing file src/main/java/org/brix/ee/service/mapper/AccountInfoMapper.java: undefined

At: 1: package org.brix.ee.service.mapper;
2: 
3: 
4: 
5: import org.brix.ee.domain.AccountInfo;
6: import org.brix.ee.service.dto.AccountInfoDTO;
7: 
8: import undefined.domain.User;
9: import .service.dto.UserDTO;
10: 
11: import org.mapstruct.*;
12: 
13: /**
14:  * Mapper for the entity {@link AccountInfo} and its DTO {@link AccountInfoDTO}.
15:  */
16: @Mapper(componentModel = "spring")
17: public interface AccountInfoMapper extends EntityMapper<AccountInfoDTO, AccountInfo> {
18:     @Mapping(target = "user", source = "user", qualifiedByName="userLogin")
19:     AccountInfoDTO toDto(AccountInfo s);
20: 
21: 
22:     @Named("userLogin")
23:     @BeanMapping(ignoreByDefault = true)
24:     @Mapping(target = "id", source = "id")
25:     @Mapping(target = "login", source = "login")
26:     UserDTO toDtoUserLogin(User user);
27: }
28: 
    at patternSpy.dot (/Users//IdeaProjects/brixee/node_modules/generator-jhipster/generators/generator-transforms.js:79:15)
    at async PTransform.transform [as _transform] (/Users/IdeaProjects/brixee/node_modules/p-transform/index.js:127:7)
    at async PTransform.queuedTransform (/Users/IdeaProjects/brixee/node_modules/p-transform/index.js:88:26)
    at async run (/Users/IdeaProjects/brixee/node_modules/p-queue/dist/index.js:163:29)

```

##### **Motivation for or Use Case**

This is the core functionality that should be working as we need to adjust our entity from time to time

##### **Reproduce the error**

Just try to add new field using the command line or
try to add new entity using the command line

##### **Suggest a Fix**

No clue

##### **JHipster Version(s)**

7.8.1

##### **JHipster configuration**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity AccountInfo {
  type AccountType required
  url String required unique
  phoneNumber String
  countryCode String
  about String required
}
entity Appearance
entity LinkStyle {
  type LinkStyleType required
  buttonColor String required
  borderColor String required
  fontColor String required
  fontType String required
}
entity HighlightStyle {
  backgroundColor String required
  transparency Integer required
}
entity BackgroundStyle {
  imageUrl String
  videoUrl String
  color1 String
  color2 String
  activeType BackgroundType required
}
entity BioStyle {
  backgroundColor String required
  transparency Integer required
  fontColor String required
  fontType String required
}
entity CreatorLink {
  pageUrl String required
  logoUrl String required
  desription String required
  order Integer required
  activated Boolean required
  type CreatorLinkType required
}
entity Highlight {
  type HighlightType required
  activated Boolean required
  imageUrl String required
  order Integer required
}
entity Product {
  name String required
  type ProductType required
  description String
  active Boolean required
}
entity DigitalProduct {
  fileUrl String required
}
entity ProductImage {
  imageUrl String required
}
entity Currency {
  code String required unique
  symbol String required
}
entity Variant {
  name String required
  description String
  quantity Integer required
  sku String unique
  weight Integer required
}
entity ProductPrice {
  amount BigDecimal required
}
entity HeaderStyle {
  imageUrl String
}
entity NftProductPrice {
  amount BigDecimal required
}
entity Request {
  price BigDecimal required
}
entity RequestSubmission {
  fullName String required
  email String required
  receiverName String required
  occassion String required
  summary String required
  status RequestSubmissionStatus required
  mediaUrl String
}
entity Campaign {
  target BigDecimal required
  description String required
  imageUrl String required
}
entity RequestVideo {
  videoUrl String required
}
entity NftProduct {
  identifier String unique required
  imageUrl String required
}
entity Cart
entity CartItem {
  quantity Integer required
  total BigDecimal required
}
entity Order (jhi_order) {
  date Instant required
  status OrderStatus required
  shippingFee BigDecimal required
  cartAmount BigDecimal required
  fullName String required
  email String required
  mobileNumber String required
  shippingAddress String required
  postalCode String required
}
entity OrderItem {
  quantity Integer required
  total BigDecimal required
}
entity Shipping {
  activeType ShippingType required
  rate Integer
}
entity CampaignSubmission {
  fullName String
  email String required
  message String
}
entity RegularTipping {
  title String required
  amount1 BigDecimal required
  amount2 BigDecimal required
  amount3 BigDecimal required
}
entity RegularTippingSubmission {
  amount BigDecimal required
  type RegularTippingSubmissionType required
}
entity Aoo {
  texting String
}
enum AccountType {
  BASIC,
  PRO
}
enum LinkStyleType {
  SQUARE,
  SEMI_ROUNDED,
  ROUND
}
enum BackgroundType {
  COLOR,
  IMAGE,
  VIDEO
}
enum CreatorLinkType {
  SOCIAL,
  REFERRAL
}
enum HighlightType {
  SHOP,
  REQUEST,
  SUPPORT,
  NFT
}
enum ProductType {
  DIGITAL,
  PHYSICAL,
  NFT
}
enum RequestSubmissionStatus {
  AWAITING_CONFIRMATION,
  ACCEPTED,
  REJECTED
}
enum OrderStatus {
  UNFULFILLED,
  FULFILLED
}
enum ShippingType {
  FLAT_RATE,
  FREE_SHIPPING,
  DYNAMIC
}
enum RegularTippingSubmissionType {
  ONCE,
  MONTHLY
}

relationship OneToOne {
  AccountInfo{user(login) required} to User
  Appearance{user(login) required} to User
  LinkStyle{appearance required} to Appearance{linkStyle}
  HighlightStyle{appearance required} to Appearance{highlightStyle}
  BackgroundStyle{appearance required} to Appearance{background}
  BioStyle{appearance required} to Appearance{bioStyle}
  DigitalProduct{product(name) required} to Product{digitalProduct}
  HeaderStyle{appearance required} to Appearance{headerStyle}
  Request{user(login) required} to User
  Campaign{user(login) required} to User
  NftProduct{product(name) required} to Product{nftProduct}
  Cart{user(login) required} to User
  Shipping{user(login) required} to User
  RegularTipping{user(login) required} to User
}
relationship OneToMany {
  Variant{productImage} to ProductImage{variant(name) required}
  Product{variant} to Variant{product(name) required}
  Variant{productPrice} to ProductPrice{variant(name) required}
  Currency{productPrice} to ProductPrice{currency(code) required}
  NftProduct{nftProductPrice} to NftProductPrice{nftProduct required}
  Currency{nftProductPrice} to NftProductPrice{currency(code) required}
  Request{requestSubmission} to RequestSubmission{request required}
  Request{requestVideo} to RequestVideo{request required}
  Cart{cartItem} to CartItem{cart required}
  Order{orderItem} to OrderItem{order required}
  Campaign{campaignSubmission} to CampaignSubmission{campaign required}
  RegularTipping{regularTippingSubmission} to RegularTippingSubmission{regularTipping required}
}
relationship ManyToOne {
  CreatorLink{user(login) required} to User
  Highlight{user(login) required} to User
  Product{user(login) required} to User
  RequestSubmission{user(login) required} to User
  Order{cart(login) required} to User
  CampaignSubmission{user(login) required} to User
  RegularTippingSubmission{user(login) required} to User
}

dto AccountInfo, Appearance, LinkStyle, HighlightStyle, BackgroundStyle, BioStyle, CreatorLink, Highlight, Product, DigitalProduct, ProductImage, Currency, Variant, ProductPrice, HeaderStyle, NftProductPrice, Request, RequestSubmission, Campaign, RequestVideo, NftProduct, Cart, CartItem, Order, OrderItem, Shipping, CampaignSubmission, RegularTipping, RegularTippingSubmission, Aoo with mapstruct
paginate AccountInfo, Appearance, LinkStyle, HighlightStyle, BackgroundStyle, BioStyle, CreatorLink, Highlight, Product, DigitalProduct, ProductImage, Currency, Variant, ProductPrice, HeaderStyle, NftProductPrice, Request, RequestSubmission, Campaign, RequestVideo, NftProduct, Cart, CartItem, Order, OrderItem, Shipping, CampaignSubmission, RegularTipping, RegularTippingSubmission, Aoo with pagination
service AccountInfo, Appearance, LinkStyle, HighlightStyle, BackgroundStyle, BioStyle, CreatorLink, Highlight, Product, DigitalProduct, ProductImage, Currency, Variant, ProductPrice, HeaderStyle, NftProductPrice, Request, RequestSubmission, Campaign, RequestVideo, NftProduct, Cart, CartItem, Order, OrderItem, Shipping, CampaignSubmission, RegularTipping, RegularTippingSubmission, Aoo with serviceClass

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.12" 2021-07-20 LTS
OpenJDK Runtime Environment Corretto-11.0.12.7.2 (build 11.0.12+7-LTS)
OpenJDK 64-Bit Server VM Corretto-11.0.12.7.2 (build 11.0.12+7-LTS, mixed mode)

git version 2.23.0

node: v14.18.1

npm: 8.5.5

Docker version 20.10.12, build e91ed57

docker-compose version 1.29.2, build 5becea4c

##### **Browsers and Operating System**

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by atomfrede** [comment] 2022-04-19 08:06
Has line 9 in your snippet been generated by jhipster or did you change it by accident? `import .service.dto.UserDTO;` is obviously not a correct package import.

**Comment by mustafa-ula** [comment] 2022-04-19 08:08
Nice catch @atomfrede I didn't see that obvious error. But I didn't change anything there.

**Comment by vrijmetse** [comment] 2022-04-19 08:09
It was generated by Jhipster @atomfrede

**Comment by atomfrede** [comment] 2022-04-19 10:31
Looks like a jh bug indeed.

**Comment by atomfrede** [comment] 2022-04-19 10:31
@vrijmetse Can you provide the needed infomation like application configuration?

**Comment by vrijmetse** [comment] 2022-04-19 10:35
```
<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "applicationIndex": 0,
    "applicationType": "monolith",
    "authenticationType": "jwt",
    "aws": {
      "applicationName": "brixee-stg",
      "awsRegion": "ap-southeast-1",
      "bucketName": "brixee",
      "dbInstanceClass": "db.t3.micro",
      "dbName": "brixee",
      "environmentName": "staging",
      "instanceType": "t2.micro"
    },
    "baseName": "brixee",
    "blueprints": [],
    "buildTool": "gradle",
    "cacheProvider": "redis",
    "clientFramework": "react",
    "clientPackageManager": "npm",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "creationTimestamp": 1649151523357,
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "devServerPort": 9060,
    "dtoSuffix": "DTO",
    "enableGradleEnterprise": false,
    "enableHibernateCache": true,
    "enableSwaggerCodegen": true,
    "enableTranslation": true,
    "entities": [
      "AccountInfo",
      "Appearance",
      "LinkStyle",
      "HighlightStyle",
      "BackgroundStyle",
      "BioStyle",
      "CreatorLink",
      "Highlight",
      "Product",
      "DigitalProduct",
      "ProductImage",
      "Currency",
      "Variant",
      "ProductPrice",
      "HeaderStyle",
      "NftProductPrice",
      "Request",
      "RequestSubmission",
      "Campaign",
      "RequestVideo",
      "NftProduct",
      "Cart",
      "CartItem",
      "Order",
      "OrderItem",
      "Shipping",
      "CampaignSubmission",
      "RegularTipping",
      "RegularTippingSubmission"
    ],
    "entitySuffix": "",
    "gradleEnterpriseHost": "",
    "jhiPrefix": "jhi",
    "jhipsterVersion": "7.8.1",
    "jwtSecretKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "languages": ["en"],
    "lastLiquibaseTimestamp": 1650169125000,
    "messageBroker": false,
    "nativeLanguage": "en",
    "otherModules": [],
    "packageFolder": "org/brix/ee",
    "packageName": "org.brix.ee",
    "pages": [],
    "prodDatabaseType": "postgresql",
    "reactive": false,
    "searchEngine": false,
    "serverPort": "8080",
    "serviceDiscoveryType": false,
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "skipUserManagement": false,
    "testFrameworks": [],
    "websocket": false,
    "withAdminUi": true
  }
}

</pre>
</details>
```

**Comment by mshima** [comment] 2022-04-19 11:08
Should be fixed in main already.
See https://github.com/jhipster/generator-jhipster/issues/18347.
If you can reproduce using main please let us know in this issue and we reopen.

**Closed by mshima** 2022-04-19 11:08 UTC
Labels: area: bug :bug:
