### ISSUE TITLE
JsonIgnore import missing

### ISSUE THREAD

**Issue by alpoza** [jhipster/generator-jhipster#1506] opened 2015-05-22 09:24 UTC
import com.fasterxml.jackson.annotation.JsonIgnore mising. One case is then the entity generator is only whet there are a many-to-many relationship with ownerSide=false.

jhipster version: Release 2.11.1

**Comment by jdubois** [comment] 2015-05-22 10:06
Which version are you using?

**Comment by jdubois** [comment] 2015-05-22 10:21
I can't reproduce with my current version, so I'm closing this.

**Closed by jdubois** 2015-05-22 10:21 UTC
