### ISSUE TITLE
Automatic build failed to compile on OSX

### ISSUE THREAD

**Issue by RagnarLodbrok** [jhipster/generator-jhipster#2304] opened 2015-11-08 10:44 UTC
First time with JHipster.

I install all the package via 

> brew install ...
> npm install ...

I have node v5 and yo doctor looks fine.

I didn't add fancy features. Just saied yes to everything (SQL for Dev and Prod).

I follow the IntelliJ setup env on the official website.

But when I try to build the project I got a bunch of errors : 
http://imgur.com/a/txehZ

Cannot figure it out what's wrong. I reinstall all the tools 3 times.

I clone an JHipster exemple (Elasticsearch), and everything looks good.

Anyone have an idea what's wrong with my machine ?

Thanks !

**Comment by atomfrede** [comment] 2015-11-08 10:48
Is your mysql database running and correctly configured in jhipster?

**Comment by RagnarLodbrok** [comment] 2015-11-08 11:31
I just follow the how-to nothing else. So no SQL conf or anything else.

I just try with H2 instead SQL for dev and I got now java errors.

<img width="1440" alt="screen shot 2015-11-08 at 12 30 35" src="https://cloud.githubusercontent.com/assets/7879555/11020099/98b0e2e8-8614-11e5-9c4b-94c7b08d90b8.png">

**Comment by jdubois** [comment] 2015-11-08 11:46
Yes but if you don't select the default options, and use MySQL instead, then you need to configure it.
It's written in the documentation -> please tell us which how to you refer to, it looks buggy.
To start you app just run Maven or execute the Application class.
I'm closing this as this is not a bug.

**Closed by jdubois** 2015-11-08 11:46 UTC
