### ISSUE TITLE
oauth authentication broken

### ISSUE THREAD

**Issue by atomfrede** [jhipster/generator-jhipster#2291] opened 2015-11-05 21:16 UTC
Currently you can't login with oauth selected.

**Comment by jdubois** [comment] 2015-11-05 21:29
This comes from commit https://github.com/jhipster/generator-jhipster/commit/d677f9cb77272389bc291fa2471a4a40776c1ade from @andidev 

At least it's a recent issue and we have an explanation!

**Comment by andidev** [comment] 2015-11-07 06:26
I feel a bit responsible here though I don't see the issue with the commit. Does reverting this change really make oauth login work again?

This is a wild guests but maybe you ment to refer the changes in [WesocketConfiguration.java](https://github.com/jhipster/generator-jhipster/commit/b79829b12f530204b1190e4b2f20570dd4089282)? I did some changes here that you thought would not work.

**Comment by jdubois** [comment] 2015-11-07 09:06
Sorry I should have been more clear: can you clone the sample app at https://github.com/jhipster/jhipster-sample-app-oauth2 and try to log in? You'll get the JS error (sorry I can't test it right now, I'm with my phone!)

**Comment by atomfrede** [comment] 2015-11-07 15:59
I get a server side error no js error. I will provide the stacktrace tomorrow.

**Comment by jdubois** [comment] 2015-11-07 17:18
I have a JavaScript issue, when I click on "sign in", and this is the part that comes from @andidev  :

    TypeError: Cannot read property 'langKey' of null
    at auth.service.js:15
    at processQueue (angular.js:14634)
    at angular.js:14650

**Comment by jdubois** [comment] 2015-11-07 17:22
Sorry, on the server side I also get a:

    Exception in com.mycompany.myapp.service.UserService.getUserWithAuthorities() with cause = null
    java.lang.IllegalStateException: User not found!
	at com.mycompany.myapp.security.SecurityUtils.getCurrentUser(SecurityUtils.java:79)

**Comment by atomfrede** [comment] 2015-11-07 17:26
Yes. Exactly what I get.
Am 07.11.2015 6:22 nachm. schrieb "Julien Dubois" <notifications@github.com

**Comment by andidev** [comment] 2015-11-08 08:40
I just tried to revert the changes that came form my commit and still the same error since `account` is null. So it's something else causing this issue. Probably the login fails in a call before.

**Comment by atomfrede** [comment] 2015-11-08 10:39
Maybe it is somehow related to #2216 at least the stacktrace looks similar.

**Comment by andidev** [comment] 2015-11-08 12:40
I can confirm it is the same issue.

The issue is that if case `if (authentication.getPrincipal() instanceof CustomUserDetails) {` on  [line 75 in SecurityUtils.java](https://github.com/jhipster/jhipster-sample-app-oauth2/blob/master/src/main/java/com/mycompany/myapp/security/SecurityUtils.java#L75) returns a `org.springframework.security.oauth2.provider.OAuth2Authentication` is not evaluated to true.

**Comment by andidev** [comment] 2015-11-08 12:51
My world is upside down, could somebody explain this:

**Principle class is `CustomerUserDetails`**
![screen shot 2015-11-08 at 13 45 21](https://cloud.githubusercontent.com/assets/571389/11020411/7c3a73ee-861f-11e5-9d55-4089ee4ad726.png)

**...at the same time it is not true:**
![screen shot 2015-11-08 at 13 45 57](https://cloud.githubusercontent.com/assets/571389/11020409/6e5059ce-861f-11e5-8d6b-cb895d825330.png)

**Comment by jdubois** [comment] 2015-11-09 10:48
Same issue for me, looks like some interesting JVM trick!!!

**Comment by jdubois** [comment] 2015-11-09 11:02
OK, found it:

- This is because of Spring Boot devtools : those classes come from different classloaders, so the instanceof doesn't work -> we need to find another solution here!
- The JS error still occurs, so it's another ticket probably

**Comment by jdubois** [comment] 2015-11-09 11:23
Of course, the incredible thing is that this only occurs with OAuth2 -> the classloader is correct for the other types of authentication!
-> to test this, remove the Spring Boot devtools with OAuth2, it will work!

**Comment by jdubois** [comment] 2015-11-09 11:32
In the end, this is a Spring Boot devtools issue, I'm going to submit a ticket to them

-> if you use OAuth2 and have this issue, the workaround is to remove Spring Boot devtools from your Maven/Gradle build

**Comment by jdubois** [comment] 2015-11-09 11:35
After reading more about the latest Spring Boot version -> we should instead migrate to the new enhanced OAuth2 support (with @EnableAuthorizationServer etc)
I guess they have better tested those and that they work

**Comment by cbornet** [comment] 2015-11-09 11:50
@jdubois You mean to use the autoconfigured AuthorizationServerConfiguration ? I looked at it when working on #2213 but I wanted to have allowFormAuthenticationForClients() and ClientDetailsServiceConfigurer.jdbc() so I eventually didn't use it. But maybe some autoconfiguration can be overridden afterwards.

**Comment by jdubois** [comment] 2015-11-09 13:26
@cbornet I'd like to use the new configuration of course as it's new (and we need to follow the changes), but mostly because I guess they have tested it better with devtools.
As you have worked on this, didn't you have this issue?

**Comment by cbornet** [comment] 2015-11-09 17:29
@jdubois When I tested my PR, I was on Spring-boot 1.3 with dev-tools activated and Oauth login was working so this is really strange...

**Comment by cbornet** [comment] 2015-11-09 17:32
I haven't deleted the branch so I guess it can still be tested https://github.com/cbornet/generator-jhipster/tree/oauth_3_legged

**Comment by jdubois** [comment] 2015-11-09 17:49
@cbornet how do you run your app? I have the issue both with Maven and running the Application class

**Comment by jdubois** [comment] 2015-11-09 18:02
So the issue is because we have the CustomUserDetails that changes classloader. This is very strange indeed, as it only fails for OAuth2: I wonder what causes this in this specific scenario.

I didn't follow closely why we added that class (that was done by @gzsombor by the way, so let's put him in the loop), but it doesn't seem to be widely used: wouldn't it be a solution to remove this class and use the normal Spring Security class? As it would come from Spring Security, it would be in the correct classloader.

**Comment by cbornet** [comment] 2015-11-09 18:02
This is strange : I just tested again with the generated app that I used before and now I get the same bug that everybody has...

**Comment by cbornet** [comment] 2015-11-09 18:24
Oh ! My fork above didn't have the CustomUserDetails commit at the time. So this is why it was working.

**Comment by cbornet** [comment] 2015-11-09 18:32
Wondering if it is not because Oauth uses SecurityEvaluationContextExtension.

**Comment by jdubois** [comment] 2015-11-09 22:24
OK I've tried with removing CustomUserDetails and it works, as expected.

@gzsombor @deepu105 I see you have worked on #1730 -> I didn't really follow what was the point of that class, but I don't really understand. I see it's supposed to remove one trip to the database, but normally we can always get a user from his login, at least on SQL : is it only for NoSQL solutions?
Anyway it is not getting called very often, so I don't think it's a big performance issue.

Anyway I would like to correct that issue first, so I might roll back #1730 and then we'll see how we can put it back, if necessary.

**Comment by jdubois** [comment] 2015-11-09 22:55
So I've tested out removing CustomUserDetails and it solves the issue, and I don't find any big drawbacks -> I'm merging this so this specific is solved, and then of course we can discuss again this topic, but we can't stay with such an important issue opened

**Comment by deepu105** [comment] 2015-11-10 04:01
I didnt work on this but it doesn't look very trivial i guess its ok to
rollback

**Comment by gzsombor** [comment] 2015-11-10 07:59
Perhaps we should disable this devtools stuff, which broke our working session management code!
 I don't understand why the surprise, the UserDetails object is stored inside the session, and if that crappy devtools reloads the classes, there will be new UserDetails classes in the system, which won't be compatible with the rest of the code. In this case, for the devtools, the sane functionality would be to invalidate all the sessions

**Comment by jdubois** [comment] 2015-11-10 09:39
I'm mostly trying to have a bug fix version today, as we can't have OAuth2 failing like this.
Then, this is to have the time to find a better solution: we will then be able to be able to manage this in a better way.

My current opinion on the CustomUserDetails is that:

- It's a perfectly normal way of using Spring Security, so it should work.
- I remember this is not the first time I have this kind of issue (I'm not sure but I think I had a similar issue with a distributed cache), so maybe we should be careful with this
- I don't understand perfectly why it is useful: it looks like it's for performance reasons, but it's not really helping a lot, as we have indexes on the ID as well as on the login, and this is not called that often. Is it for NoSQL databases?

But once again, we are going to have the time to review and discuss this, after this bugfix release.

**Comment by gzsombor** [comment] 2015-11-10 12:20
* Yes, the problem lies inside this dev tools stuff, which does this class loading magic, I bet, when oauth is used, the code is coming from a different classloader - from the regular, system classloader - but most of the application lives in that reloading classloader, so the problem is with the dev tools. If we disable it, for oauth it works perfectly fine.
* We should open a spring ticket about to avoid reloading a couple of classes.
* The CustomUserDetails is not about NoSQL database, it's just an improved place to store inmutable user data. In our app, we need the user id in hundreds of places, and that would be waste of resources to always do the 'loginname' -> 'userid' transformations for such an immutable data.

**Comment by jdubois** [comment] 2015-11-10 13:25
Yes I think the best solution is to open up a ticket for Spring Boot -> let me do the release first, then we'll see how we can report this to them.
For the CustomUserDetails I'm not sure it's going to be a big performance gain, I need to check when it is used and what it does specifically.
BTW, I'd like to do some performance testing of the application, so this could be an interesting thing to check.

**Comment by piedrahitac** [comment] 2015-11-11 19:00
I don't know if it is related to this bug or not, but right now with version 2.23.1 and OAuth2 selected you 
can't login if you restart the application.

The first time you can login just fine as many times as you want, but restarting the app results in an authentication failure and an exception saying that there's already a duplicate client id.

Truncating the `oauth_client_details` table fixes the issue until you restart the app again.

If it is not related to this bug please let me know and I will file a proper issue about it.

**Comment by jdubois** [comment] 2015-11-11 19:03
@piedrahitac you have another issue, see #2069

**Comment by onurakman** [comment] 2015-11-12 09:42
After upgrading from 2.23.0 to 2.23.1 I have the same issue with @piedrahitac, after restarting app if oauth_client_details is insertted I cant login without deleting thing the record.

**Comment by onurakman** [comment] 2015-11-12 11:55
I think our issue is related with this

https://github.com/spring-projects/spring-security-oauth/issues/420

**Comment by flaviu-idea** [comment] 2015-12-05 06:17
One question about getCurrentLogin() in SecurityUtils, I upgraded JHipster to Release 2.24.0
Why is it that the check 
 else if (authentication.getPrincipal() instanceof String) {
                 userName = (String) authentication.getPrincipal();
was removed from this method?

Because Spring comes with Object principal =  "anonymousUser" in org.springframework.security.config.annotation.web.configurers.AnonymousConfigurer, thus jhipster for me is crashing now at least in the logs.

Same error 
[ERROR] org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/].[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.IllegalStateException: User not found!] with root cause
java.lang.IllegalStateException: User not found!
        at <myapp>.security.SecurityUtils.getCurrentUser(SecurityUtils.java:71) 

Thanks!

 public static String getCurrentLogin() {
         SecurityContext securityContext = SecurityContextHolder.getContext();
         Authentication authentication = securityContext.getAuthentication();
-        UserDetails springSecurityUser = null;
         String userName = null;
-        if(authentication != null) {
+        if (authentication != null) {
             if (authentication.getPrincipal() instanceof UserDetails) {
-                springSecurityUser = (UserDetails) authentication.getPrincipal();
+                UserDetails springSecurityUser = (UserDetails) authentication.getPrincipal();
                 userName = springSecurityUser.getUsername();
             } else if (authentication.getPrincipal() instanceof String) {
                 userName = (String) authentication.getPrincipal();

**Comment by jdubois** [comment] 2015-12-06 22:51
@onurakman you have another issue it's #2069
@flahub it's also another issue

**Comment by jdubois** [comment] 2016-01-07 11:12
This ticket is quite a mess, with people asking questions unrelated to the original issue...

- I have just tried it, no issue at all for me: I can log in again after a restart, etc.
- I'm closing this as it's a mess

For me the only issue is the one from @gzsombor concerning the devtools -> hopefully this should be solved by the Spring team, and anyway this isn't an OAuth2 issue at all. I suggest we open a new ticket for this, if we encounter this again.

**Closed by jdubois** 2016-01-07 11:12 UTC
Labels: bug

**Comment by SimonKlausLudwig** [comment] 2018-01-03 21:58
Is there a plan to reimplement CustomUserDetails ? Thanks
