### ISSUE TITLE
Use Java 8 Date Time API instead of JodaTime 

### ISSUE THREAD

**Issue by hantsy** [jhipster/generator-jhipster#1158] opened 2015-02-17 04:35 UTC
If Java 8 is selected as Java runtime, it it better to use Java 8 Date API(JSR310) instead of the joda.

There some some points needs to be aligned with Java 8 and JSR310.

1. Spring date conversion and formatting by conversion service and @DateFormat
2. Jackson JSON desearialization and serialization should be compatible with AngularJS date filter.
3. JPA  Date conversion which can be done by JPA 2.1 @Convertor

**Comment by 8cells** [comment] 2015-02-17 07:52
:+1:

**Comment by gzsombor** [comment] 2015-02-17 12:52
Until datetime is implemented in hibernate, it's not worth to migrate to it. 
 You can vote for the hibernate issue, here : https://hibernate.atlassian.net/browse/HHH-8844

**Comment by jdubois** [comment] 2015-02-17 13:01
Yes we already had that issue.
We are also stuck because we still support Java 7 -> migration will be done after April, when Java 7 is EOL

**Comment by bonhamcm** [comment] 2015-02-17 14:26
I am using [Jadira Usertype Extended](http://jadira.sourceforge.net/usertype.extended/index.html) which supports JSR 310 Date-Time types with Hibernate.

**Comment by hantsy** [comment] 2015-02-17 14:30
@bonhamcm , I have said the JPA 2.1 @Convertor can converts date type betweenJSR 310 and java.sql.Date . 

I have already use JSR 310 in stead of Joda in my projects. It worked well.

**Comment by hantsy** [comment] 2015-02-17 14:33
Have a look at this project, it provides a series of converters for JSR 310.

[https://bitbucket.org/montanajava/jpaattributeconverters](https://bitbucket.org/montanajava/jpaattributeconverters)

**Comment by howie** [comment] 2015-03-03 03:51
You can use Jadira Usertype Extended for Java8 JSR310 , For Example
@Type(type = "org.jadira.usertype.dateandtime.threeten.PersistentLocalDateTime")
private LocalDateTime

**Comment by andreabreu-me** [comment] 2015-03-26 15:30
From: https://spring.io/blog/2015/03/26/what-s-new-in-spring-data-fowler

```
To easily persist JSR-310 types - the date/time API newly introduced in JDK 8 - from
within domain objects we added converters for the relevant types in the MongoDB and
JPA module. For developers not able to upgrade to Java 8 yet, we added a similar set
of converters for the ThreeTen Backport project so that you can start using the types in
your code even if you’re still on Java 7. A switch to Java 8 will be a simple switch
in the package names going forward.
```

**Comment by ygrenzinger** [comment] 2015-05-07 14:20
Hello !
Using JHipster, I have totally removed Joda for java.time using:

JPA:
        <dependency>
            <groupId>org.jadira.usertype</groupId>
            <artifactId>usertype.extended</artifactId>
            <version>3.2.0.GA</version>
        </dependency>
@Type(type = "org.jadira.usertype.dateandtime.threeten.XXX")

Jackson:
        <dependency>
            <groupId>com.fasterxml.jackson.datatype</groupId>
            <artifactId>jackson-datatype-jsr310</artifactId>
            <version>${jackson.version}</version>
        </dependency>
https://github.com/FasterXML/jackson-datatype-jsr310

and this guide for Class type conversion
http://blog.joda.org/2014/11/converting-from-joda-time-to-javatime.html

Do you need help for the migration of JHipster generator ?

**Comment by jdubois** [comment] 2015-05-07 14:23
Oh yes! Last time I tried I couldn't make it work because of Hibernate, but I wasn't using the same Type as you, so it looks like things have changed.

Can you provide a PR? I'm reopening this ticket for you

**Comment by ygrenzinger** [comment] 2015-05-08 19:24
Ca représente pas mal de taf sur le generator en fait :)
Comment construire et tester rapidement le générateur yeoman ?

**Comment by jdubois** [comment] 2015-05-08 20:33
Yes it might be a lot of work (I haven't checked, I'm not sure in fact)
We have a complete procedure here to set up the generator: https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md

**Comment by ygrenzinger** [comment] 2015-05-13 15:53
Bon je doute finir ça dans les jours qui viennent donc ce sera fini mi/fin juin

**Comment by ygrenzinger** [comment] 2015-05-17 09:06
Sorry for the french version of my previous comment :)

I have passed some hours and I have something that seems OK for SQL / Mongodb. Cassandra is a bit more difficult for me because I have never used it and tests are failing. I will try to work on it when going back from my holidays.

For MongoDB, I had to add 4 new for Converter classes.

The whole commit patch is here https://github.com/ygrenzinger/generator-jhipster/commit/3869fea0ad7bc82cd5381e5f11b9026babe83955

Last thing, I have not done an <if java 8> templating, so this patch broke the Java 7 version. Do you want to work to add this or make a Java 8 only branch ?

**Comment by jdubois** [comment] 2015-05-18 08:47
Hi @ygrenzinger , yes this should only be for Java 8 -> unfortunately we should still have Java 7 support for a few months (as my stats show we still have 22% of people using it, but this is dropping quite fast), but this is clearly not a priority.
So if you can put it only for Java 8 it would be great!

**Comment by ygrenzinger** [comment] 2015-05-18 15:44
I take a flight to USA tomorrow so no time to finish the pull request. I want to make a few other tests before. I will do this as soon as I come back.
By the way, if you know people who want to review the code (or help the cassandra part works) the fork is here https://github.com/ygrenzinger/generator-jhipster

**Comment by cbornet** [comment] 2015-06-02 08:39
This will be the way of mapping java 8 dates in spring-data-jpa:
https://github.com/spring-projects/spring-data-jpa/blob/master/src/main/java/org/springframework/data/jpa/convert/threeten/Jsr310JpaConverters.java
Has anybody tried to use it ? If it works, I think it would prevent the need for the @Type annotations and jadira dependency.

**Comment by jdubois** [comment] 2015-06-02 08:43
@cbornet I haven't tried it, but yes that would be the way to go!

**Comment by hantsy** [comment] 2015-06-02 08:51
I have used my custom JPA 2.1 converters in before projects, it worked. The converter classes are similar with the ones in the newest *spring-data-jpa*.

**Comment by hantsy** [comment] 2015-06-02 08:55
Attached my converters here.

<pre>
@Converter(autoApply = true)
public class LocalDateTimeConverter implements AttributeConverter<LocalDateTime, Timestamp> {

    @Override
    public Timestamp convertToDatabaseColumn(LocalDateTime attribute) {

        if (attribute != null) {
           return Timestamp.valueOf(attribute);
        }

        return null;
    }

    @Override
    public LocalDateTime convertToEntityAttribute(Timestamp dbData) {

        if (dbData != null) {
            return dbData.toLocalDateTime();
        }

        return null;
    }

}
</pre>


<pre>
@Converter(autoApply = true)
public class LocalDateConverter implements AttributeConverter<LocalDate, Date> {

    @Override
    public Date convertToDatabaseColumn(LocalDate attribute) {
        
        if (attribute != null) {
            return Date.valueOf(attribute);
        }

        return null;
    }

    @Override
    public LocalDate convertToEntityAttribute(Date dbData) {
        
        if (dbData != null) {
            return dbData.toLocalDate();
        }

        return null;
    }

}

</pre>


<pre>
@Converter(autoApply = true)
public class LocalTimeConverter implements AttributeConverter<LocalTime, Time> {

    @Override
    public Time convertToDatabaseColumn(LocalTime attribute) {
        if (attribute != null) {
            return Time.valueOf(attribute);
        }

        return null;
    }

    @Override
    public LocalTime convertToEntityAttribute(Time dbData) {
        if (dbData != null) {
            return dbData.toLocalTime();
        }
        return null;
    }

}

</pre>

The difference is I was using **java.sql.XX** as target type.

**Comment by cbornet** [comment] 2015-06-02 10:16
Just copied
https://github.com/spring-projects/spring-data-jpa/blob/master/src/main/java/org/springframework/data/jpa/convert/threeten/Jsr310JpaConverters.java
and
https://github.com/spring-projects/spring-data-commons/blob/master/src/main/java/org/springframework/data/convert/Jsr310Converters.java
to my domain.util directory, added converters for ZonedDatetime and OffsetDatetime, removed jadira  and so far everything works like a charm.

For Joda users:
https://github.com/spring-projects/spring-data-commons/blob/master/src/main/java/org/springframework/data/convert/JodaTimeConverters.java
And the JPA converters can be easily written.

**Comment by Infrag** [comment] 2015-06-02 10:28
I have used 
https://github.com/spring-projects/spring-data-jpa/blob/master/src/main/java/org/springframework/data/jpa/convert/threeten/Jsr310JpaConverters.java

enabled them with annotation:

@EntityScan(basePackageClasses = {Application.class, Jsr310JpaConverters.class})

Don't need to copy anything.

**Comment by cbornet** [comment] 2015-06-02 11:56
No need to put @EntityScan, the auto-scan already detects the converters

**Comment by cbornet** [comment] 2015-06-02 15:23
Also, does anyone knows why the ser/deser are declared by annotations and not set globally when configuring the JodaModule ?

I tried:
@Bean
    public JodaModule jacksonJodaModule() {
        JodaModule module = new JodaModule();
        module.addSerializer(DateTime.class, new CustomDateTimeSerializer());
        module.addDeserializer(DateTime.class, new CustomDateTimeDeserializer());
        module.addSerializer(LocalDate.class, new CustomLocalDateSerializer());
        module.addDeserializer(LocalDate.class, new ISO8601LocalDateDeserializer());
        return module;

With that ser/deser annotations on the domain classes are not needed anymore.

**Comment by cbornet** [comment] 2015-06-03 07:40
For Jsr310 serialization without model annotation, I used the following class:

public class Jsr310IsoSerializer extends JsonSerializer<TemporalAccessor> {
	    
	private static DateTimeFormatter ISOFormatter = DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm:ss'Z'").withZone(ZoneId.of("UTC"));

	public static final Jsr310IsoSerializer INSTANCE = new Jsr310IsoSerializer();
	
	private Jsr310IsoSerializer() {}
	
    @Override
    public void serialize(TemporalAccessor value, JsonGenerator generator,
                          SerializerProvider serializerProvider)
            throws IOException {
        generator.writeString(ISOFormatter.format(value));
    }
}

For the deserializers, I use the ones from jackson-datatype-jsr310 on which I add my serializers:
@Bean
    public JSR310Module jsr310Module() {
    	JSR310Module module = new JSR310Module();
    	module.addSerializer(OffsetDateTime.class, Jsr310IsoSerializer.INSTANCE);
    	module.addSerializer(ZonedDateTime.class, Jsr310IsoSerializer.INSTANCE);
    	module.addSerializer(LocalDateTime.class, Jsr310IsoSerializer.INSTANCE);
    	module.addSerializer(Instant.class, Jsr310IsoSerializer.INSTANCE);
    	return module;
    }

For LocalDate, it is already serialized correctly by jackson-datatype-jsr310 if WRITE_DATES_AS_TIMESTAMP is set to false.

I have done some tests with the front end and everything seems to work so far.

**Comment by hantsy** [comment] 2015-06-03 10:09
@cbornet , There is a problem about the timezone display. I think it is better to format the date time according to the client local timezone, not UTC. 

For persisting the datetime into database, using UTC instead is ok, but the custom Jackson ser/deser must convert the datetime between UTC and local timezone.

**Comment by cbornet** [comment] 2015-06-03 10:25
@hantsy Outputing in UTC is the current jhipster behavior. I have no idea what would be the impact of displaying a timezone. I guess the format should be at least compatible with AngularJS and who knows what other date format. I kinda like the idea of keeping the 'Z' format as I believe any client language/framework should be able to parse it. Just an hint: jackson-datatype-jsr310 serializes timezones like "+01:00" which AFAIK is not valid in AngularJS.
As for the client timezone, only the client knows it. So it is the responsibility of the client to re-format the date to the correct timezone for final display.

**Comment by ygrenzinger** [comment] 2015-06-08 15:29
Hello,

I will read your comments and try to improve my branch in the next days but don't hesitate to help me directly here https://github.com/ygrenzinger/generator-jhipster

**Comment by dllongo** [comment] 2015-06-11 14:11
Hello!
I tried to follow the instructions on spring blog [spring-boot] (https://spring.io/blog/2014/12/02/latest-jackson-integration-improvements-in-spring) to jackson parse  java.util.LocalDateTime, but spring is ignoring my config. I tried to follow @cbornet config with the same result (failed). On the blog post there's this link [github](https://github.com/sdeleuze/spring-jackson-demo) with the same config and it works, someone can explain?

Also I tried even in a clean project generate by latest version of jhipster and the same error ocurred.

that's my exception on browser:
```
"status": 400,
"error": "Bad Request",
"exception": "org.springframework.http.converter.HttpMessageNotReadableException",
    "message": "Could not read JSON: Text '21-05-2015 17:00:30' could not be parsed at index 0 (through reference chain: com.test.TestDTO[\"date\"]); nested exception is com.fasterxml.jackson.databind.JsonMappingException: Text '21-05-2015 17:00:30' could not be parsed at index 0 (through reference chain: com.test.TestDTO[\"date\"])",
```

**Comment by cbornet** [comment] 2015-06-11 16:43
Are you serializing or deserializing ? If you are deserializing, I think there misses a 'T' between date and time. Try with "21-05-2015T17:00:30" which is the ISO notation.

**Comment by dllongo** [comment] 2015-06-11 17:35
Tks @cbornet ,

I'm trying to deserializing, now with:
   "date":"21-05-2015T17:00:30",
and 
   "date":"21-05-2015 17:00:30",

Get the same result:
```
"message": "Could not read JSON: Text '21-05-2015T17:00:30' could not be parsed at index 0 
```
that's my bean:
```
    @Bean
    public Jackson2ObjectMapperBuilder jacksonBuilder() {
        log.debug("init JACKSON");
        Jackson2ObjectMapperBuilder builder = new Jackson2ObjectMapperBuilder();
        builder.indentOutput(true).dateFormat(new SimpleDateFormat("dd-MM-yyyy HH:00:ss"));
        return builder;
    }
```
and my application.yml
```
spring:
    jackson:
        serialization:
            write_dates_as_timestamps: false
```

**Comment by gmarziou** [comment] 2015-06-11 17:48
I though that the ISO notation was  "2015-05-21T17:00:30".

**Comment by cbornet** [comment] 2015-06-12 07:17
@gmarziou Of course you're right. I should have been more careful when copy/pasting...
@dllongo The dateformat() function only concerns java.util.Date, it cannot be used (so far) with the JSR310 types.

**Comment by dllongo** [comment] 2015-06-12 13:29
@cbornet the date pattern that @gmarziou  passed works "2015-05-21T17:00:30" .
here in brazil the date pattern are "dd-MM-yyyy", the format "yyyy-MM-dd" works for me too.

tks!

**Comment by ygrenzinger** [comment] 2015-06-13 19:40
@jdubois j'ai normalement créé une Pull request à partir de mon fork. Dis moi si c'est bon. 
J'ai essayé de suivre https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#submit mais je ne peux créer de Pull request sans le fork sous Github :(

**Comment by ygrenzinger** [comment] 2015-06-13 19:51
@jdubois I have created a Pull request from my fork. Tell me if it's ok.
I have tried to follow https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#submit but I can't create a Pull request sans le fork in github screens :(

**Comment by deepu105** [comment] 2015-06-24 05:01
@ygrenzinger did you forget to give a pull request?

**Comment by ygrenzinger** [comment] 2015-06-24 14:54
I am a noob in pull request but it seems I can't create a pull request directly (the button is deactivated). However I have normally pushed a pull request from my fork.

I am open to help :)

**Comment by deepu105** [comment] 2015-06-25 01:29
@ygrenzinger I have opened a pull from your branch (dont worry commits will be credited to you)
https://github.com/jhipster/generator-jhipster/pull/1640

But seems like your branch is behind current Jhipster master a ~240 commits so it might be a good idea to rebase your branch against current master 
follow this 
```
git rebase master -i
git push -f
```

you might get merge conflicts which you have to resolve and commit then do a `git rebase -continue`

**Comment by cbornet** [comment] 2015-06-25 13:24
Just a comment : I think this PR will make Jhipster incompatible with Java 7. Although I think, dropping Java 7 support is a good thing, maybe other users will complain ?

**Comment by jdubois** [comment] 2015-06-25 17:28
@cbornet that's a blocker issue
Yes we will end Java 7 support in some time, but at the moment 20% of our users are using it, so we can't drop it now.

**Comment by ygrenzinger** [comment] 2015-06-27 09:42
@jdubois each merge has its cost and with a generator difficult to put non regression test :/

Maybe the best way before killing the Java 7 compatibility is to create a Java 8 only branch ?

**Comment by jdubois** [comment] 2015-06-27 19:17
@ygrenzinger that would be hard to maintain, as we are not going to kill Java 7 at the moment (this doesn't make me happy, but that's 20% of users and I want them to be happy).

So at the moment we do switches in the templates, and it's annoying, but I don't think we have much choice.

I haven't looked at your code yet, so let me look at it first.

**Comment by hantsy** [comment] 2015-07-12 23:47
@jdubois It seems Hibernate 5 brings native Java 8 DateTime API support, there is a `hibernate-java8` artifact in Hibernate 5.0.0CR2.

**Comment by hantsy** [comment] 2015-08-15 09:30
@cbornet  it seems the latest AngularJS 1.4.x supports ISO8601 format, and the `date` filter accept a timezone paratmer.

**Comment by cbornet** [comment] 2015-08-25 15:56
@hantsy my point is that the timezone format in Angular is '+HHmm' and in other libs/frameworks/languages such as jackson-datatype-jsr310 it is '+HH:mm'. Both are valid ISO8601 formats but the libs are not compatible.

**Comment by cbornet** [comment] 2015-08-25 16:12
@hantsy @jdubois Hibernate 5 with jsr310 support is now out but there will probably be some time before it is integrated in spring boot.

**Comment by hantsy** [comment] 2015-08-26 02:28
@cbornet I think it is no need to integrate into Spring Boot, just  add hibernate-java8 in your dependencies. It is supported by Hibernate natively, not Spring Data JPA.

**Comment by cbornet** [comment] 2015-08-26 08:12
@hantsy I talk about intergration of version 5 of hibernate into spring boot. Currently, spring boot (and thus jhipster) uses hibernate 4. Since hibernate-java8 is for a different major version of hibernate, there is no guarantee that it will be compatible with hibernate 4. That said, I checked the hibernate-java8 code and it is a really small library so it could be worth the try if the core "type" API hasn't moved between versions. Can you test it and give us your feedback ?

**Comment by cbornet** [comment] 2015-08-26 08:43
@hantsy I did a small check and hibernate-java8 makes use of org.hibernate.boot.model.TypeContributions which was added in hibernate 5 (https://hibernate.atlassian.net/browse/HHH-7998) so it is not compatible with hibernate 4.

**Comment by cbornet** [comment] 2015-09-03 14:47
@jdubois Spring-data-jpa source code is under Apache License. Can we use it or do we need to rewrite it ? Note that rewritten code will not be very different since there are not many ways to do it

**Comment by cbornet** [comment] 2015-09-04 09:08
Also it seems that spring-data-jpa maps LocalDate to java.util.Date which in turn gets mapped to a timestamp column in db which feels wrong. So for LocalDate it is better to use @hantsy mapping to java.sql.Date

**Comment by paivaric** [comment] 2015-09-27 16:51
+1

**Comment by jdubois** [comment] 2015-10-15 18:51
Closing this as the PR is merged!

**Closed by jdubois** 2015-10-15 18:51 UTC
Labels: enhancement
