### ISSUE TITLE
RateLimitFilter will not work for proxied requests

### ISSUE THREAD

**Issue by jgoldhammer** [jhipster/generator-jhipster#3362] opened 2016-04-07 10:19 UTC
##### **Overview of the issue**

The built-in Ratelimitfilter tries to limit number of requests and tries to determine the ip of the client.
https://github.com/jhipster/generator-jhipster/blob/6db557c0aab25d859dc63eae15db80d5b9783fb6/generators/server/templates/src/main/java/package/gateway/ratelimiting/_RateLimitingFilter.java#L90

This method will not work for proxies. When using a proxy, the remoteAdress will be typically the proxy adress, not the real client ip adress. In most cases, proxy will write another header with the real client ip adress.

##### **Motivation for or Use Case** 

To be able to work with proxies...

##### **JHipster Version(s)** 

3.0
##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 

no special config

##### **Browsers and Operating System** 

All

##### **Reproduce the error** 

Install and configure an nginx or apache and use it to proxy requests to the backend.

##### **Suggest a Fix** 

Using alternative methods to get the real client ip adress like here (https://gist.github.com/nioe/11477264) or provide a configuration so that users can set the header to read the client ip adress from...

**Comment by gmarziou** [comment] 2016-04-07 10:29
Good point.

However I doubt this implementation would work in all cases as X-Forwarded-For is a multiple value header, if use goes through 2 proxies, header will contain 2 Ip addresses separated by commas.

**Comment by jdubois** [comment] 2016-04-07 12:03
Yes, you are correct, but:

- The idea is that our gateway IS the gateway. It's an edge server, a proxy.... Putting another proxy on top of it is *strange* and can only cause performance and resiliency issues. I'm not saying it's bad, I have a customer doing this, I'm just saying that's not optimal.
- Then, if you want to put another proxy on top of our gateway, yes you will have that issue: but in that case it's your proxy that should do the rate limiting. If let every request go through, I don't understand what it's good for? That's what my customer is doing, they have a proxy that is better than our gateway for some cases (some specific security configuration, for instance).

One solution that would be good for everyone would be document this in our tips section.

**Comment by gmarziou** [comment] 2016-04-07 18:08
I am in same case, I use nginx to hold the virtual hosts and TLS certs.

**Comment by jdubois** [comment] 2016-04-09 15:16
I'm closing this as it's not a bug for me.

**Closed by jdubois** 2016-04-09 15:16 UTC
Labels: bug, microservice
