### ISSUE TITLE
StackOverflowError in integration tests for OneToOne relationships

### ISSUE THREAD

**Issue by sbrunecker** [jhipster/generator-jhipster#11109] opened 2020-01-12 17:20 UTC
##### **Overview of the issue**
I adapted the example jdl slightly so it looks like this:

```
entity Location {
	streetAddress String,
	postalCode String,
	city String,
	stateProvince String
}

entity Department {
	departmentName String required
}

entity JobHistory {
	startDate Instant,
	endDate Instant
}

relationship OneToOne {
	Department{location required} to Location{department required}
}

relationship OneToOne {
	JobHistory{department required} to Department{jobHistory required}
}
```

jhipster generates the entities just fine but running `DepartmentResourceIT` causes StackOverflowErrors in all tests:

```
java.lang.StackOverflowError
	at org.h2.command.Command.reuse(Command.java:366)
	at org.h2.engine.Session.prepareLocal(Session.java:650)
	at org.h2.engine.Session.prepareCommand(Session.java:595)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1235)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:76)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:352)
	at com.zaxxer.hikari.pool.ProxyConnection.prepareStatement(ProxyConnection.java:311)
	at com.zaxxer.hikari.pool.HikariProxyConnection.prepareStatement(HikariProxyConnection.java)
	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$5.doPrepare(StatementPreparerImpl.java:149)
	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$StatementPreparationTemplate.prepareStatement(StatementPreparerImpl.java:176)
	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl.prepareQueryStatement(StatementPreparerImpl.java:151)
	at org.hibernate.loader.Loader.prepareQueryStatement(Loader.java:2082)
	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:2012)
	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1990)
	at org.hibernate.loader.Loader.doQuery(Loader.java:949)
	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:351)
	at org.hibernate.loader.Loader.doList(Loader.java:2787)
	at org.hibernate.loader.Loader.doList(Loader.java:2770)
	at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2604)
	at org.hibernate.loader.Loader.list(Loader.java:2599)
	at org.hibernate.loader.hql.QueryLoader.list(QueryLoader.java:505)
	at org.hibernate.hql.internal.ast.QueryTranslatorImpl.list(QueryTranslatorImpl.java:395)
	at org.hibernate.engine.query.spi.HQLQueryPlan.performList(HQLQueryPlan.java:220)
	at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1526)
	at org.hibernate.query.internal.AbstractProducedQuery.doList(AbstractProducedQuery.java:1538)
	at org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1506)
	at org.hibernate.query.Query.getResultList(Query.java:132)
	at org.hibernate.query.criteria.internal.compile.CriteriaQueryTypeQueryAdapter.getResultList(CriteriaQueryTypeQueryAdapter.java:74)
	at com.test.jh.web.rest.TestUtil.findAll(TestUtil.java:154)
	at com.test.jh.web.rest.DepartmentResourceIT.createEntity(DepartmentResourceIT.java:86)
	at com.test.jh.web.rest.LocationResourceIT.createEntity(LocationResourceIT.java:98)
	at com.test.jh.web.rest.DepartmentResourceIT.createEntity(DepartmentResourceIT.java:87)
	at com.test.jh.web.rest.LocationResourceIT.createEntity(LocationResourceIT.java:98)
	at com.test.jh.web.rest.DepartmentResourceIT.createEntity(DepartmentResourceIT.java:87)
	at com.test.jh.web.rest.LocationResourceIT.createEntity(LocationResourceIT.java:98)
	at com.test.jh.web.rest.DepartmentResourceIT.createEntity(DepartmentResourceIT.java:87)
	at com.test.jh.web.rest.LocationResourceIT.createEntity(LocationResourceIT.java:98)
	at com.test.jh.web.rest.DepartmentResourceIT.createEntity(DepartmentResourceIT.java:87)
	at com.test.jh.web.rest.LocationResourceIT.createEntity(LocationResourceIT.java:98)
	at com.test.jh.web.rest.DepartmentResourceIT.createEntity(DepartmentResourceIT.java:87)
	at com.test.jh.web.rest.LocationResourceIT.createEntity(LocationResourceIT.java:98)
	at com.test.jh.web.rest.DepartmentResourceIT.createEntity(DepartmentResourceIT.java:87)
	at com.test.jh.web.rest.LocationResourceIT.createEntity(LocationResourceIT.java:98)
	at com.test.jh.web.rest.DepartmentResourceIT.createEntity(DepartmentResourceIT.java:87)
	at com.test.jh.web.rest.LocationResourceIT.createEntity(LocationResourceIT.java:98)
...
	at com.test.jh.web.rest.LocationResourceIT.createEntity(LocationResourceIT.java:98)
	at com.test.jh.web.rest.DepartmentResourceIT.createEntity(DepartmentResourceIT.java:87)
	at com.test.jh.web.rest.LocationResourceIT.createEntity(LocationResourceIT.java:98)
	at com.test.jh.web.rest.DepartmentResourceIT.createEntity(DepartmentResourceIT.java:87)
```

##### **JHipster Version(s)**

```
testjh@0.0.1-SNAPSHOT C:\Users\stefan\Google Drive\Java Projects\test-jh
`-- generator-jhipster@6.6.0

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.test.jh",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "6.6.0",
    "applicationType": "monolith",
    "baseName": "testjh",
    "packageName": "com.test.jh",
    "packageFolder": "com/test/jh",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "redacted",
    "clientFramework": "angularX",
    "clientTheme": "darkly",
    "clientThemeVariant": "dark",
    "useSass": true,
    "clientPackageManager": "npm",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": ["en", "de"],
    "herokuAppName": "testjh",
    "herokuDeployType": "git",
    "embeddableLaunchScript": false,
    "blueprints": [],
    "creationTimestamp": 1578829876752
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Location {
  streetAddress String,
  postalCode String,
  city String,
  stateProvince String
}
entity Department {
  departmentName String required
}
entity JobHistory {
  startDate Instant,
  endDate Instant
}
relationship OneToOne {
  Department{location required} to Location{department required},
  JobHistory{department required} to Department{jobHistory required}
}

</pre>
</details>

<details>
<summary>Department.json</summary>
<pre>
{
    "name": "Department",
    "fields": [
        {
            "fieldName": "departmentName",
            "fieldType": "String",
            "fieldValidateRules": [
                "required"
            ]
        }
    ],
    "relationships": [
        {
            "relationshipType": "one-to-one",
            "otherEntityName": "location",
            "otherEntityRelationshipName": "department",
            "relationshipValidateRules": "required",
            "relationshipName": "location",
            "otherEntityField": "id",
            "ownerSide": true
        },
        {
            "relationshipType": "one-to-one",
            "otherEntityName": "jobHistory",
            "otherEntityRelationshipName": "department",
            "relationshipValidateRules": "required",
            "relationshipName": "jobHistory",
            "ownerSide": false
        }
    ],
    "changelogDate": "20200112165431",
    "entityTableName": "department",
    "dto": "no",
    "pagination": "no",
    "service": "no",
    "jpaMetamodelFiltering": false,
    "fluentMethods": true,
    "readOnly": false,
    "clientRootFolder": "",
    "applications": "*"
}
</pre>
</details>

<details>
<summary>JobHistory.json</summary>
<pre>
{
    "name": "JobHistory",
    "fields": [
        {
            "fieldName": "startDate",
            "fieldType": "Instant"
        },
        {
            "fieldName": "endDate",
            "fieldType": "Instant"
        }
    ],
    "relationships": [
        {
            "relationshipType": "one-to-one",
            "otherEntityName": "department",
            "otherEntityRelationshipName": "jobHistory",
            "relationshipValidateRules": "required",
            "relationshipName": "department",
            "otherEntityField": "id",
            "ownerSide": true
        }
    ],
    "changelogDate": "20200112165432",
    "entityTableName": "job_history",
    "dto": "no",
    "pagination": "no",
    "service": "no",
    "jpaMetamodelFiltering": false,
    "fluentMethods": true,
    "readOnly": false,
    "clientRootFolder": "",
    "applications": "*"
}
</pre>
</details>

<details>
<summary>Location.json</summary>
<pre>
{
    "name": "Location",
    "fields": [
        {
            "fieldName": "streetAddress",
            "fieldType": "String"
        },
        {
            "fieldName": "postalCode",
            "fieldType": "String"
        },
        {
            "fieldName": "city",
            "fieldType": "String"
        },
        {
            "fieldName": "stateProvince",
            "fieldType": "String"
        }
    ],
    "relationships": [
        {
            "relationshipType": "one-to-one",
            "otherEntityName": "department",
            "otherEntityRelationshipName": "location",
            "relationshipValidateRules": "required",
            "relationshipName": "department",
            "ownerSide": false
        }
    ],
    "changelogDate": "20200112165430",
    "entityTableName": "location",
    "dto": "no",
    "pagination": "no",
    "service": "no",
    "jpaMetamodelFiltering": false,
    "fluentMethods": true,
    "readOnly": false,
    "clientRootFolder": "",
    "applications": "*"
}
</pre>
</details>

##### **Environment and Tools**

openjdk version "1.8.0_232"
OpenJDK Runtime Environment Corretto-8.232.09.1 (build 1.8.0_232-b09)
OpenJDK 64-Bit Server VM Corretto-8.232.09.1 (build 25.232-b09, mixed mode)

git version 2.21.0.windows.1

node: v10.16.3

npm: 6.12.0

yeoman: 2.0.6

Docker version 19.03.5, build 633a0ea

docker-compose version 1.24.1, build 4667896b

##### **Browsers and Operating System**

OS: Windows 10

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pmverma** [comment] 2020-01-14 08:08
The problem is defining the relations `required` on both sides.

```
JobHistory{department required} to Department{jobHistory required}
```
When IT runs, JobHistorywill try to create a `department `-> During the creation of that department , the Departmentwith try to create a `jobHistory ` -> Again JobHistory will try to create a `department ` -> And Department will too.

This loop-cycle will never end and results in `java.lang.StackOverflowError`.

Do you really need a mandatory association value on both sides?

**Comment by sbrunecker** [comment] 2020-01-20 15:50
Thanks for investigating this issue.

I don't think I'll absolutely need the `required` flag on both sides of my relationships. It would be nice if JHipster printed a warning, though.

**Comment by pmverma** [comment] 2020-01-21 03:01
Of course, printing a warning will help here.
@MathieuAA Can this kind of warning message be printed when using JDL?

**Comment by MathieuAA** [comment] 2020-01-21 08:14
Yes there can be a warning but I don't see why there should be. This is an issue regarding the generated java code to the ORM, right?

**Comment by pmverma** [comment] 2020-01-21 08:29
The generator checks and generates the code for `required` object.
Please check more.

https://github.com/jhipster/generator-jhipster/blob/5a65672bd6dd09d88ce99e4d321f3d9b382921d1/generators/entity-server/templates/src/test/java/package/web/rest/EntityResourceIT.java.ejs#L467-L473

https://github.com/jhipster/generator-jhipster/blob/5a65672bd6dd09d88ce99e4d321f3d9b382921d1/generators/entity-server/templates/src/test/java/package/web/rest/EntityResourceIT.java.ejs#L480-L484

**Comment by pascalgrimaud** [comment] 2020-01-21 09:05
IMO, I don't think we should spend time on this, to display warning.
The problem comes from the initial modelisation. If something is wrong at the beginning, it's normal that the generated is wrong.
For example, you can have a more complex use case:
- 4 entities: A, B, C, D
- A requires B
- B requires C
- C required D
- D required A
You'll have the same problem but it's more difficult to "code" the warning here.
So does it deserve this "warning" message ?
What do you think @MathieuAA @pmverma ?

**Comment by pmverma** [comment] 2020-01-22 16:12
You are correct @pascalgrimaud the problem will still exist as mentioned in your case.
This may also be rare case in real world otherwise we will many issues complained for it.

The user should be responsible for his/her modeling.

**Comment by pmverma** [comment] 2020-02-20 15:45
Closing this issue as this can't be fix and user is responsible for this.

**Closed by pmverma** 2020-02-20 15:45 UTC
Labels: area: needs-reproduction, theme: relationships
