### ISSUE TITLE
_initial_schema.xml sequence management

### ISSUE THREAD

**Issue by ctamisier** [jhipster/generator-jhipster#4690] opened 2016-12-15 20:31 UTC
Hi,
I am using postgresql as storage engine.
The first liquibase database migration (from _initial_schema.xml) creates a 'jhi_user_id_seq' sequence. 

This is due to:
<column name="id" type="bigint" **autoIncrement="${autoIncrement}"**>
(which is set to 'true' in the case of postgres)

I think this is not the expected behavior because there is **hibernate_sequence** already defined and used if I create a new user (the jhi_user_id_seq is not used).
Also the sequence 'jhi_user_id_seq' will start at 1 and we already have users in the database so it can't be used like this.

In User.java it is defined:
@GeneratedValue(strategy = GenerationType.AUTO) for the id field, and it seems that postgres will use 'hibernate_sequence' by default. (vs GenerationType.IDENTITY that would use the according sequence).

Should we just remove 'postgres' from the autoIncrement property list ?

I am using postgresql 9.5 (linux, work) and 9.6 (mac, home) and I have this same behavior.

**Comment by jdubois** [comment] 2016-12-20 15:12
- There is no problem with the sequence starting with `1`, have a look at the Hibernate hilo algorithm, and you'll see it's fine.
- Indeed, the `autoincrement` is useless with Postgresql. I don't remember were this comes from, but my guess is that it's going to help people who don't want to use the hilo algorithm: that way our tables work in both situations. As this is pretty confusing, it's probably better to remove it. I'll have a try.

**Comment by cbornet** [comment] 2016-12-20 15:43
I think some people want the auto_increment because they have non-hibernate apps also committing to the DB.

**Comment by jdubois** [comment] 2016-12-20 15:44
@cbornet yes, but then they could have the sequence generate an id that is already being used, so there is a risk of failure...

**Comment by jdubois** [comment] 2016-12-20 15:45
In fact I think we should only support sequences, with the new hilo generator, and migrate everything.

**Comment by jdubois** [comment] 2016-12-20 16:16
Oh sorry I remember now: the issue is that MySQL (which 50% of our users have), does not support sequences.... Which is why we use the "auto" Hibernate generator, so we support everything.

**Comment by jdubois** [comment] 2016-12-20 19:07
I'm closing this as I'm going to make a new ticket on this matter:

- There is no bug in this release, just a confusing configuration
- For JHipster 4, we can break stuff, so I'm going to propose to change this

I'll link the new ticket to this one, of course.

**Closed by jdubois** 2016-12-20 19:07 UTC
