### ISSUE TITLE
Microservice Gateway Entity header is null

### ISSUE THREAD

**Issue by dteleki** [jhipster/generator-jhipster#6021] opened 2017-07-03 15:46 UTC
##### **Overview of the issue**

On microservice gateway with a generated Entity page no Entity will be displayed.

##### **Reproduce the error**

Issue appears on an newly generated microservice and gateway app.

The Entity is then  generated from a  JDL file on both microservice and gateway.

After saving an entity, none is displayed on the page.

##### **Suggest a Fix**

I'm assuming it stops once it can't access the header information.

In Firefox  error in the console:

> 
> Error: header is null
> parse@http://localhost:8080/app/components/util/parse-links.service.js:17:1
> onSuccess@http://localhost:8080/app/entities/book/book.controller.js:42:28
> resourceFactory/</Resource[name]/promise<@http://localhost:8080/bower_components/angular-resource/angular-resource.js:821:18
> processQueue@http://localhost:8080/bower_components/angular/angular.js:16383:28
> scheduleProcessQueue/<@http://localhost:8080/bower_components/angular/angular.js:16399:27
> $eval@http://localhost:8080/bower_components/angular/angular.js:17682:16
> $digest@http://localhost:8080/bower_components/angular/angular.js:17495:15
> $apply@http://localhost:8080/bower_components/angular/angular.js:17790:13
> done@http://localhost:8080/bower_components/angular/angular.js:11831:36
> completeRequest@http://localhost:8080/bower_components/angular/angular.js:12033:7
> requestLoaded@http://localhost:8080/bower_components/angular/angular.js:11966:9
> Browser/self.defer/timeoutId<@http://localhost:8080/bower_components/angular/angular.js:6242:7
>   angular.js:13920:18
> 	consoleLog/< http://localhost:8080/bower_components/angular/angular.js:13920:18
> 	$ExceptionHandlerProvider/this.$get</< http://localhost:8080/bower_components/angular/angular.js:10467:7
> 	processQueue http://localhost:8080/bower_components/angular/angular.js:16391:9
> 	scheduleProcessQueue/< http://localhost:8080/bower_components/angular/angular.js:16399:27
> 	$eval http://localhost:8080/bower_components/angular/angular.js:17682:16
> 	$digest http://localhost:8080/bower_components/angular/angular.js:17495:15
> 	$apply http://localhost:8080/bower_components/angular/angular.js:17790:13
> 	done http://localhost:8080/bower_components/angular/angular.js:11831:36
> 	completeRequest http://localhost:8080/bower_components/angular/angular.js:12033:7
> 	requestLoaded http://localhost:8080/bower_components/angular/angular.js:11966:9
> 	Browser/self.defer/timeoutId< http://localhost:8080/bower_components/angular/angular.js:6242:7
> 
>         
> 

##### **JHipster Version(s)**

4.5.6

##### Contents of JDL file for entity generation

> 
> entity Book{
> 	name String,
> 	rating Integer,
> 	description String
> }
> 
>  paginate all with infinite-scroll
>  microservice all with book

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "ro.blackmesa.book",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "4.5.6",
    "baseName": "gateway",
    "packageName": "ro.blackmesa.book",
    "packageFolder": "ro/blackmesa/book",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": false,
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "mariadb",
    "prodDatabaseType": "mariadb",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "jwtSecretKey": "ad59a50cf090143da6b3d4111d39f4c99ab8c0fc",
    "clientFramework": "angular1",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "gateway",
    "testFrameworks": [
      "gatling",
      "cucumber",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "de",
      "ro"
    ],
    "appsFolders": [
      "book",
      "gateway"
    ],
    "directoryPath": "../",
    "monitoring": "no",
    "adminPassword": "admin"
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

Book.json

```yaml
{
    "fluentMethods": true,
    "relationships": [],
    "fields": [
        {
            "fieldName": "name",
            "fieldType": "String"
        },
        {
            "fieldName": "rating",
            "fieldType": "Integer"
        },
        {
            "fieldName": "description",
            "fieldType": "String"
        }
    ],
    "changelogDate": "20170703093948",
    "entityTableName": "book",
    "dto": "no",
    "pagination": "infinite-scroll",
    "service": "no",
    "microserviceName": "book"
}
```

##### **Browsers and Operating System**

openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-8u131-b11-0ubuntu1.16.04.2-b11)
OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)

git version 2.7.4

node: v6.11.0

npm: 3.10.10

bower: 1.8.0

gulp:
[18:27:08] CLI version 1.2.2
[18:27:08] Local version 3.9.1

yeoman: 1.8.5

yarn: 0.27.5

Docker version 17.05.0-ce, build 89658be

docker-compose version 1.8.0, build unknown

- [ X] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment] 2017-07-03 16:56
Can you also send your microservice's `.yo-rc.json` file? I suppose there is a difference between both apps, and there's something there that makes the pagination fails.

**Comment by dteleki** [comment] 2017-07-03 17:02
Sure, not a problem.

```
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "ro.blackmesa.book",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "4.5.6",
    "baseName": "book",
    "packageName": "ro.blackmesa.book",
    "packageFolder": "ro/blackmesa/book",
    "serverPort": "8081",
    "authenticationType": "jwt",
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "mariadb",
    "prodDatabaseType": "mariadb",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "jwtSecretKey": "854c66200671a43baf31be10ae884ac28d20d183",
    "enableTranslation": true,
    "applicationType": "microservice",
    "testFrameworks": [
      "gatling",
      "cucumber"
    ],
    "jhiPrefix": "jhi",
    "skipClient": true,
    "skipUserManagement": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "de",
      "ro"
    ],
    "clientPackageManager": "yarn"
  }
}
```

**Comment by dteleki** [comment] 2017-07-03 17:03
Sorry, about that... missclick

**Comment by gmarziou** [comment] 2017-07-03 21:38
> The Entity is then generated from a JDL file on both microservice and gateway.

What do you mean? 
The JDL can be used only on microservice, on the gateway you used entity sub generator, right?

By the way, I suppose that @jdubois rather wanted to compare the 2 `.jhipster/Book.json` files from gateway and microservice because that's where pagination type is stored.

**Comment by jdubois** [comment] 2017-07-03 21:40
Yes I didn't understand that sentence either @gmarziou !

**Comment by deepu105** [comment] 2017-07-04 06:20
@gmarziou you can use the JDL on both microservice and gateway, with microservice it will create the backend and with gateway, it will create the front end code. In JDL it should have the microservice option specified though to do this properly

**Comment by dteleki** [comment] 2017-07-04 07:22
Yes, that's exactly how I did it.

On the backend it generated all that's needed to store the Book information.
On the gateway it should have generated only the files that are needed to reach the backend and store, modify, etc the data there.

And aside from the fact that I can't see the Book  after I create one it seems to have worked quite well.
Checking the database on the microservice and testing with swagger from the gateway shows the Books are being saved correctly.

**Comment by gmarziou** [comment] 2017-07-04 09:12
@deepu105 I did not know, thanks.

**Comment by pascalgrimaud** [comment] 2017-07-23 21:27
@dteleki : I tried to understand and reproduce the issue.
Everything seems to work fine on my side.
- create gateway ng1
- create microservice
- import jdl on both: gateway and micro
- start registry, gateway, micro
- play with entity book

Do you have additional info to reproduce? Full described steps, or better GitHub projects?

**Comment by deepu105** [comment] 2017-07-29 16:18
No information provided after 6 days and not reproducible, hence closing

**Closed by deepu105** 2017-07-29 16:18 UTC
Labels: microservice, waiting for information
