### ISSUE TITLE
Plural form of entities ending with "y" are not converted correctly in angular controllers

### ISSUE THREAD

**Issue by bgiegel** [jhipster/generator-jhipster#3850] opened 2016-07-18 20:52 UTC
##### **Overview of the issue**

When an entity is terminated by the letter "y" like in "Activity" or "Community" for example the plural variable name given to the tables in angular controllers are wrong. The plural form obtained is "Activitys" and it should be "activities". It works well on the view side.

**extract of my scale-dialog.controller.js** : 
`vm.activitys = Activity.query({filter: 'scale-is-null'});
        $q.all([vm.scale.$promise, vm.activitys.$promise]).then(function() {`

**and in scale-dialog.html** : 
`<select class="form-control" id="field_activity" name="activity" ng-model="vm.scale.activity" ng-options="activity as activity.name for activity in vm.activities | orderBy:'id' track by activity.id">`

##### **Motivation for or Use Case** 

The consequence is that the drop down list of a parent entity is empty. 

##### **JHipster Version(s)** 

3.4.0q

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 

~~~
{
  "generator-jhipster": {
    "jhipsterVersion": "3.4.0",
    "baseName": "StarPointsApp",
    "packageName": "fr.softeam.starpointsapp",
    "packageFolder": "fr/softeam/starpointsapp",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": "no",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "rememberMeKey": "5f02ba65c07d8ce6badb3f7b396f7ebdd040f7c8",
    "useSass": true,
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "fr",
    "languages": [
      "fr"
    ]
  }
}
~~~

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory** 

~~~
{
  "relationships": [
    {
      "relationshipId": 1,
      "relationshipType": "one-to-one",
      "relationshipName": "activity",
      "otherEntityName": "activity",
      "otherEntityField": "name",
      "ownerSide": true,
      "otherEntityRelationshipName": "scale"
    }
  ],
  "fields": [
    {
      "fieldId": 1,
      "fieldName": "startDate",
      "javadoc": "Date de début incluse",
      "fieldType": "LocalDate"
    },
    {
      "fieldId": 2,
      "fieldName": "endDate",
      "javadoc": "Date de fin incluse",
      "fieldType": "LocalDate"
    },
    {
      "fieldId": 3,
      "fieldName": "value",
      "fieldType": "String"
    }
  ],
  "changelogDate": "20160620202521",
  "dto": "no",
  "pagination": "no",
  "service": "no",
  "entityTableName": "scale"
}
~~~

##### **Browsers and Operating System** 

Ubuntu 16.04

##### **Reproduce the error** 

Let say we have a **Scale** entity that has a oneToOne relationShip with **Activity**.
I create an Activity with the jhipster app.
When I try to create a Scale and to assign a previously created activity to it, it fails. The drop down list is empty in the edit view.

**Error in browser console :** 
_TypeError: Cannot read property 'push' of undefined
    at scale-dialog.controller.js:25_

**Comment by jdubois** [comment] 2016-07-18 20:58
Looks like a major issue to me, I'm surprised this is only discovered now.
On a side note @bgiegel you seem to work for a major JHipster competitor (Softeam is doing Modelio), so I'd be very interested by your feedback on JHipster.

**Comment by bgiegel** [comment] 2016-07-18 21:47
Glad to help !

Yes indeed I work for Softeam. I started using jhipster to create a side project for the company. It is a good opportunity to see what jHipster has to offer

And I must say that I'm not disapointed for the moment. It's a great way to learn how to do things the right way. I really like JDL studio, simple but useful. I also like the time we save when we have to modify a relation on an entity. 

It lacks one thing to me : A way to modify the configuration of a previously created project with a command line tool. Something like _yo jhipster:modify-database MySQL_
There is also one annoying bug with liquibase when I try to load data from a CSV file (if a field is empty we get an error). 

Appart from that it's a great tool.

**Comment by ruddell** [comment] 2016-07-18 22:06
This is a duplicate of #3702 and is fixed in the latest version (v3.4.2) via #3705

@bgiegel Thanks for the feedback 😄

**Comment by deepu105** [comment] 2016-07-19 02:47
I don't get this. Can you be more specific. We use pluralize library to get
plural forms and so far I have seen it working as expected. Are you seeing
incorrect plural forms in few places or every where?

Thanks & regards,
Deepu

**Comment by deepu105** [comment] 2016-07-19 02:55
Oops my mail thread was incomplete so I wrote too fast. Anyways as @ruddell said its already fixed and will be released soon.

@bgiegel thank you for the compliments. I agree that having options to modify stuff would great and we are slowly getting there. Did you notice the option to modify a generated entity? Similarly we also recently added a sub generator to upgrade jhipster version and upgrade the project along.

It might be difficult to have a sub gen to modify each options, btw you can just change the db value in the .yo-rc.json and re run yo jhipster to change it. But if we can find an intuitive way to change options we might be considering that.

For the liquibase issue may be we can report it to the project so that could help

**Closed** 2016-07-19 02:56 UTC

**Comment by bgiegel** [comment] 2016-07-19 18:19
Ok. I just upgraded to jhipster 3.4.2 using the jhipster:upgrade command so it's perfect. Yes I have noticed that we could modify a generated entity. And it's very useful. I will definitely try to modify yo-rc file next time I want to change the configuration. 

Thank you all for the fast answers.

**Comment by jdubois** [comment] 2016-07-20 12:04
Thanks for the feedback @bgiegel !! Hopefully there could be some common works someday between JHipster and Modelio :-)

Indeed I'm not totally happy with Liquibase at the moment: we are also sticking to Hibernate 4 because Liquibase doesn't support yet Hibernate 5, and that's starting to be annoying.

**Comment by deepu105** [comment] 2016-07-20 14:08
May be time to start looking at flyaway if it supports all this!

Thanks & regards,
Deepu

**Comment by atomfrede** [comment] 2016-07-20 14:23
Sadly flyway does not support diffs between classes and database tables.
Otherwise flyway would work for us (or we remove that feature)

Am 20.07.2016 16:09 schrieb "Deepu K Sasidharan" <notifications@github.com>:

> May be time to start looking at flyaway if it supports all this!
>
> Thanks & regards,
> Deepu
