### ISSUE TITLE
Outdated objects in LoggingAspect

### ISSUE THREAD

**Issue by ddamw** [jhipster/generator-jhipster#2716] opened 2016-01-28 10:18 UTC
Our jHipster 2.26.2 based application suddenly started to log large stack traces when signing in a user that signed out before:

```
SLF4J: Failed toString() invocation on an object of type [com.our.application.domain.User]
javax.persistence.EntityNotFoundException: Unable to find com.our.application.domain.PersistentToken with id xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
.....
at com.our.application.aop.logging.LoggingAspect.logAround(LoggingAspect.java:53)
.....
at com.our.application.service.UserService$$EnhancerBySpringCGLIB$$845f20dd.getUserWithAuthorities(<generated>)
at com.our.application.web.rest.AccountResource.getAccount(AccountResource.java:70)
at com.our.application.web.rest.AccountResource$$FastClassBySpringCGLIB$$f2336e5e.invoke(<generated>)
.....
at com.our.application.web.rest.AccountResource$$EnhancerBySpringCGLIB$$352ac176.getAccount(<generated>)
```

We think the following sequence of events is the cause:

1. We use a MySQL backend with local sessions.
2. Signing out removes the token from the token repository (CustomPersistentRememberMyServices:149)
3. The token does not get removed from the User explicitly
4. When signing in, the LoggerAspect is called when retrieving the user, but Hibernate has not yet had the chance to 'fix' the User object.
5. LoggerAspect calls toString on the User, which calls toString on the token set. Hibernate starts to resolve the set, but cannot find the token mentioned en throws an error.

A fix for this would be to explicitly remove the token from the user when signing out, but there is more to this issue. 
First, it didn't happen before. Second, we saw something similar in another piece of code: LoggingAspect tried to print an object that used lazy loading and no session had been started.

Our guess is that the order in which the aspects - mainly LoggingAspect and Transactional - get executed got altered. This would explain why we didn't see the errors before. Our application introduces a few new beans and even a custom UserDetailsService, but no new aspect. It is my understanding that without explicit configuration, Spring does not guarantee ordering.

Possible solutions would be:
- Change all code that could trigger the problem.
- Assume the cause is the ordering of aspects and set a specific order for LoggingAspect.
- Detect Hibernate Persistent* collections in LoggingAspect and skip these.

A big problem however is that it is very hard to reproduce this behavior. We have about 10 jHipster based applications and this is the first one to show it.

**Comment by jdubois** [comment] 2016-02-23 16:22
Indeed, calling `toString()` on an object that can do lazy-loading is a source of issue.

I don't really understand how you got the aspects working the other way around, especially as the Transactional annotation is running with the "lower precedence" (have a look at the `EnableTransactionManagement` class), but yes depending on those other beans you included, who knows what can happen.

Now in a "normal" JHipster application that shouldn't happen, as this is one of the reasons we generate the `toString` methods (note that if we didn't generate them, you would get the hashCode of the object, and that should also still be OK for this use case).
The `toString` method for the `User`object is not getting the collections, and so by default you shouldn't have this issue. That would be really bad to get the lazy-loaded collections in a toString, and that's not limited to this aspect: you can have all kind of tools doing toString() on your objects, and that would definitely be bad if that method was doing SQL requests...

So as far as I'm concerned, this is not a bug (and that's why I'm closing this), however I understand the annoyance and you clearly have a good experience of how JHipster is working (doing lots of applications and filling this complex issue), so I'm interested to have more info and insight from you.

**Closed by jdubois** 2016-02-23 16:22 UTC
Labels: bug
