### ISSUE TITLE
Bad Request: JSON parse error: No _valueDeserializer assigned; 

### ISSUE THREAD

**Issue by MInesGomes** [jhipster/generator-jhipster#10743] opened 2019-11-06 21:46 UTC
##### **Overview of the issue**
This 
```
relationship ManyToOne {
 NmsZone{tenant(name)} to NmsTenant, 
}
```
generates:

```
@ManyToOne
@JsonIgnoreProperties("nmsZones")
private NmsTenant tenant;
```
If I change to
```
@ManyToOne
@JsonIgnoreProperties(value="nmsZones", allowSetters = true)
private NmsTenant tenant;
```
as suggested here 
https://gitter.im/jhipster/generator-jhipster/archives/2018/08/26

Is not giving the error anymore

##### **Reproduce the error**
Only gives the error in production not in dev.

```
Bad Request: JSON parse error: No _valueDeserializer assigned; nested exception is com.fasterxml.jackson.databind.exc.MismatchedInputException: No _valueDeserializer assigned
 at [Source: (PushbackInputStream); line: 1, column: 125] (through reference chain: com.gotop.nms.domain.NmsZone["tenant"]->com.gotop.nms.domain.NmsTenant["id"])
```

##### **Related issues**

No issue. Just in gitter.im :
https://gitter.im/jhipster/generator-jhipster/archives/2018/08/26

##### **Suggest a Fix**
Here 
https://github.com/jhipster/generator-jhipster/blob/9c09521c8b2bc5c03b3babcf0604b036f1dcbaa4/generators/entity-server/templates/src/main/java/package/domain/Entity.java.ejs#L316

Replace
`@JsonIgnoreProperties("<%= otherEntityRelationshipNamePlural %>")
by

`@JsonIgnoreProperties(value="<%= otherEntityRelationshipNamePlural %>", allowSetters = true)`

##### **JHipster Version(s)**

```
nms@0.0.1-SNAPSHOT /Users/mirg/Workspace/nms
└── generator-jhipster@6.3.0 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.gotop.nms",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "6.3.0",
    "applicationType": "monolith",
    "baseName": "nms",
    "packageName": "com.gotop.nms",
    "packageFolder": "com/gotop/nms",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "embeddableLaunchScript": false,
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "angularX",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": ["en", "nl"],
    "blueprints": []
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
/**
 * The Domain entity.\nThe domain is the customer, and it has several tenants\nselfAdmin Boolean,\ntimeZone String,
 */
entity NmsDomain {
  name String required,
  logo ImageBlob,
  brandImg ImageBlob,
  brandLink String,
  address String,
  domainEmail String,
  description String,
  notes String,
  selfAdmin Boolean,
  timeZone String,
  loginExtension String,
  sipEnabled Boolean,
  active Boolean,
  lastModifiedDate ZonedDateTime,
  lastModifiedBy String
}
/**
 * The Emails entity.\nText for emails
 */
entity NmsEmail {
  name String required,
  lang String,
  initial String,
  mainMsg String,
  greetings String,
  attachment AnyBlob,
  active Boolean,
  lastModifiedDate ZonedDateTime,
  lastModifiedBy String
}
/**
 * The Tenant entity.\na Tenant refers to a unit in the domain.\nit is a more or less independant part of the domain, possibly a building belonging to the domain.\nselfAdmin - User Zone Self-Admin" with 2 Options - Allow or Deny\nrestrictLoginsToIP - Restrict Logins to IP Address:\ntenantEmail - Tenant General Email\nipCanLogin String, -> List of IP that can login separated by ','\n
 */
entity NmsTenant {
  name String required,
  image ImageBlob,
  latitude String,
  longitude String,
  address String,
  timeZone String,
  selfAdmin Boolean,
  restrictLoginsToIP String,
  tenantEmail String,
  ipCanLogin String,
  reportMorningHour Integer,
  active Boolean,
  review Boolean,
  lastModifiedDate ZonedDateTime,
  lastModifiedBy String
}
entity NmsIntegratorServer {
  name String,
  computerNr String maxlength(24),
  heartbeatLastDT ZonedDateTime,
  diskSpaceUsed String,
  diskSpacePerc String,
  softwareVersion String,
  nowUsing String maxlength(50),
  ipAddress String maxlength(50),
  subNetMask String maxlength(50),
  defaultGateway String,
  macAddress String,
  publicIpAddress String maxlength(50),
  wifiKnownNetworks String,
  wifiAvailableNetworks String,
  wifiCurrentNetwork String,
  wifiIpAddress String,
  wifisubNetMask String,
  wifiDefaultGateway String,
  wifiMacAddress String,
  cellIpAddress String,
  phoneNumber String,
  imei String,
  active Boolean,
  lastModifiedDate ZonedDateTime,
  lastModifiedBy String
}
/**
 * entity NmsIntServerProvider\nGSM Provider\nEE (Everything Everywhere) UK\nGiffgaff UK"080">\nHutchison 3G (Three UK)"153">\nO2 Contract UK"157">\nO2 PAYG UK"223">\nVodafone Contract UK"228">\nVodafone PAYG UK"999">\nother
 */
entity NmsIntServerProvider {
  name String,
  code String,
  apn String,
  username String,
  password String,
  port String,
  active Boolean,
  lastModifiedDate ZonedDateTime,
  lastModifiedBy String
}
entity NmsIntServerBrand {
  name String,
  baudRate Integer,
  dataBits Integer,
  stopBits Integer,
  parity String,
  flowControl String,
  other String,
  active Boolean,
  lastModifiedDate ZonedDateTime,
  lastModifiedBy String
}
/**
 * entity NmsChgNetwork\nif a device needs another network SSID, password or IP settings, enter here\nit will be forwarded to the device and confirmed\nIntServName String,\nDhcp Boolean,
 */
entity NmsChgNetwork {
  confirmedDt ZonedDateTime,
  ipAddress String maxlength(16),
  subnetmask String maxlength(32),
  defaultGateway String maxlength(32),
  ssid String,
  psk String,
  apn String,
  port String,
  username String,
  password String,
  brandParams String,
  baudrate String,
  databits String,
  stopbits String,
  parity String,
  bytesize String,
  timeout String,
  flowControl Boolean,
  xonxof Boolean,
  lastModifiedDate ZonedDateTime,
  lastModifiedBy String
}
/**
 * entity NmsChgNetworkType\nchangetypes should be DHCP-wlan, DHCP-eth, Static IP wlan, Static IP eth, wifi-credentials.\nfields String,\n- change wifi to dhcp (no other fields filled)\n- change eth to dhcp (no other fields filled)\n- change wifi to static (3 ip addresses filled)\n- change eth to static (3 ip addresses filled)\n- SSID credentials (SSID filled, password optional)\nwhere 3 fields are:\nIP Address\nSubnet Mask\nDefault Gateway
 */
entity NmsChgNetworkType {
  name String,
  fields String,
  active Boolean,
  lastModifiedDate ZonedDateTime,
  lastModifiedBy String
}
/**
 * entity NmsRpiHeartbeat\ndevice_name (just a suggested name to recognize the Rpi; will be overwritten later)\nipAddress String, (store in ip_address)\ncellIpAddress String, (store in ip_address)\nmessagetype  String, - Will not be sent by rpi, but changed here\n1 Check-in Message ->  New\n2  System Events ->        Heartbeat\n3    Network Events -> Confirmation & Info
 */
entity NmsRpiHeartbeat {
  computerNr String,
  intServerId Long,
  intServerName String,
  messagetype String,
  confirmNetChgId Long,
  softwareVersion String,
  publicIpAddress String,
  diskSpaceUsed String,
  diskSpacePerc String,
  subNetMask String,
  ipAddress String,
  defaultGateway String,
  macAddress String,
  cellIpAddress String,
  wifiKnownNetworks String,
  wifiAvailableNetworks String,
  wifiCurrentNetwork String,
  imei String,
  nowUsing String,
  creationDate ZonedDateTime
}
/**
 * entity NmsRpiHeartbeatReply\n\n- result = OK\nmessage -Inserted into Intergator Server for the first Time,\nWainting for admin to couple,\nNetWork Changes\n- int_serv_name (will be stored in the Rpi; )\n- Int_serv_id (will be stored in the Rpi)\n- unconfirmed network changes\n- from the GSM provider: apn, port, username, password\n\nWhere unconfirmed network changes can be:\n- change wifi to dhcp (no other fields filled)\n- change eth to dhcp (no other fields filled)\n- change wifi to static (3 ip addresses filled)\n- change eth to static (3 ip addresses filled)\n- SSID credentials (SSID filled, password optional)\n\nnetChgType String, -> NmsChgNetworkType.name
 */
entity NmsRpiHeartbeatReply {
  result Boolean,
  message String,
  intServId Long,
  intTenantId Long,
  intServName String,
  netChgId Long,
  netChgType String,
  ipAddress String maxlength(16),
  subnetmask String maxlength(32),
  defaultGateway String maxlength(32),
  ssid String,
  psk String,
  apn String,
  port String,
  username String,
  password String,
  createDate ZonedDateTime,
  updateDate ZonedDateTime
}
/**
 * entity NmsRpiAlert\nRPI Only sends tenantId & text\nThe API Changes all other fields and search for
 */
entity NmsRpiAlert {
  text String,
  alertId Long,
  type String,
  status String,
  statusId Integer,
  error String,
  roomNotFound String,
  solved Boolean,
  date ZonedDateTime,
  tenantId Long
}
/**
 * The Zone entity.\nA zone can have one or several employees.The name of\na zone is for instance “First floor” or “Children department”.\n\nname  ex:Ground Floor, First Floor, Second Floor\ncode ex:GF, FF, SF
 */
entity NmsZone {
  name String required,
  description String,
  active Boolean,
  lastModifiedDate ZonedDateTime,
  lastModifiedBy String
}
/**
 * The Employee entity.(1-1 with user that is  automatically generated)\nIt has a one-to-one relation to user.\nemailManager,\nring Integer,\nvibration Boolean,\nselfAdmin Boolean, - user can change zones\ntoManagerEmail Boolean - send to Manager Email inf user doesn't have an email
 */
entity NmsEmployee {
  extensionNumber String,
  photo ImageBlob,
  sex NmsSexType,
  dateOfBirth LocalDate,
  selfAdmin Boolean,
  role String,
  socketId String,
  uuid String,
  alertNotifications Boolean,
  chatNotifications Boolean,
  online Boolean,
  onlineCloud Boolean,
  force Boolean,
  toManagerEmail Boolean,
  ring Integer,
  vibration Boolean,
  lastLogin ZonedDateTime,
  activeUntil ZonedDateTime,
  active Boolean,
  lastModifiedDate ZonedDateTime,
  lastModifiedBy String
}
/**
 * entity NmsEmployeeLog
 */
entity NmsEmployeeLog {
  begin ZonedDateTime,
  end ZonedDateTime,
  deviceType String,
  make String,
  model String,
  imei String,
  serialNumber String,
  ipAddress String,
  macAddress String,
  wifiNetwork String
}
entity NmsAlert {
  alertBegin ZonedDateTime,
  alertSent ZonedDateTime,
  alertAnswered ZonedDateTime,
  alertReset ZonedDateTime,
  alertPresent ZonedDateTime,
  alertMobileAccept ZonedDateTime,
  text String,
  addition String,
  updated Integer,
  sentToZones String,
  comments String,
  lastModifiedBy String,
  lastModifiedDate ZonedDateTime
}
entity NmsResidentState {
  name String,
  active Boolean,
  lastModifiedDate ZonedDateTime,
  lastModifiedBy String
}
entity NmsAlertReason {
  name String,
  active Boolean,
  lastModifiedDate ZonedDateTime,
  lastModifiedBy String
}
/**
 * The AlertTone entity.
 */
entity NmsAlertTone {
  name String required,
  soundName String,
  sound AnyBlob
}
/**
 * The AlertType entity.\nlevel Integer required, 1,2,3,4\nname  String required, ASSIST,CALL,PRIORITY,EMERGENCY, Crash...
 */
entity NmsAlertType {
  level Integer required,
  code String,
  name String required,
  colour String,
  soundName String,
  action String,
  sendToZones String,
  active Boolean,
  lastModifiedDate ZonedDateTime,
  lastModifiedBy String
}
/**
 * The Chat entity.
 */
entity NmsMessage {
  text String,
  timeSent ZonedDateTime,
  timeReceived ZonedDateTime,
  timeRead ZonedDateTime,
  image ImageBlob,
  audio AnyBlob
}
/**
 * entity Room entity. - 1 Room, 1 Resident\ncode ex:GF Bedroom 1
 */
entity NmsRoom {
  code String,
  name String required,
  active Boolean,
  lastModifiedDate ZonedDateTime,
  lastModifiedBy String
}
/**
 * The NmsResident entity.(1-1 with user that is automatically generated)\n
 */
entity NmsResident {
  photo ImageBlob,
  name String,
  idRemoteSystem Long,
  allowInfo Boolean,
  sex NmsSexType,
  dateOfBirth LocalDate,
  notes String,
  active Boolean,
  lastModifiedDate ZonedDateTime,
  lastModifiedBy String
}
/**
 * entity NmsChatGroup
 */
entity NmsChatGroup {
  name String,
  imgage ImageBlob,
  audio AnyBlob,
  broadcast Boolean,
  active Boolean,
  lastModifiedDate ZonedDateTime,
  lastModifiedBy String
}
entity NmsChatRead {
  time ZonedDateTime
}
entity NmsChatReceived {
  time ZonedDateTime
}
entity NmsFamily {
  name String,
  telephone String,
  blocked Boolean,
  active Boolean,
  lastLogin ZonedDateTime,
  lastModifiedDate ZonedDateTime,
  lastModifiedBy String
}
entity NmsRequest {
  createdDate ZonedDateTime,
  answered ZonedDateTime,
  text String,
  reaction String,
  active Boolean,
  lastModifiedDate ZonedDateTime,
  lastModifiedBy String
}
/**
 * entity NmsBugReport
 */
entity NmsBugReport {
  app Boolean,
  title String,
  description String,
  active Boolean,
  lastModifiedDate ZonedDateTime,
  lastModifiedBy String
}
/**
 * entity NmsBugReportType\nBug, Sugestion, Language
 */
entity NmsBugReportType {
  name String,
  lastModifiedDate ZonedDateTime,
  lastModifiedBy String
}
/**
 * entity upload APk
 */
entity NmsUploadAPK {
  name String,
  urlApk String,
  version String,
  lastVersion Boolean,
  lastModifiedDate ZonedDateTime,
  lastModifiedBy String
}
/**
 * entity NmsStock
 */
entity NmsStock {
  name String maxlength(64),
  available Boolean
}
/**
 * entity NmsImpRoomZone
 */
entity NmsImpRoomZone {
  zoneId Long,
  zoneCode String,
  zoneName String,
  roomId Long,
  roomCode String,
  room String,
  resident String,
  tenantId Long
}
/**
 * entity ReportState
 */
entity NmsReportState {
  name String,
  lastModifiedDate ZonedDateTime,
  lastModifiedBy String
}
/**
 * entity NmsReportTime
 */
entity NmsReportTime {
  level Integer,
  name String,
  beginHour Integer required,
  begin ZonedDateTime,
  end ZonedDateTime,
  active Boolean,
  lastModifiedDate ZonedDateTime,
  lastModifiedBy String
}
enum NmsSexType {
  FEMALE,
  MALE
}

relationship OneToOne {
  NmsEmployee{user(firstName)} to User,
  NmsRoom{resident(name)} to NmsResident{room},
  NmsResident{user(firstName)} to User,
  NmsFamily{user(firstName)} to User
}
relationship OneToMany {
  NmsDomain{tenant} to NmsTenant{domain(name)},
  NmsTenant{intServ} to NmsIntegratorServer{tenant(name)},
  NmsDomain{empployee} to NmsEmployee{domain(name)},
  NmsTenant{employee} to NmsEmployee{tenant(name)},
  NmsEmployee{log} to NmsEmployeeLog{employee},
  NmsZone{log} to NmsEmployeeLog{zone(name)},
  NmsChatGroup{message} to NmsMessage{group},
  NmsDomain{resident} to NmsResident{domain},
  NmsDomain{chatGroup} to NmsChatGroup{domain}
}
relationship ManyToOne {
  NmsIntegratorServer{brand(name)} to NmsIntServerBrand,
  NmsIntegratorServer{provider(name)} to NmsIntServerProvider,
  NmsIntServerProvider{tenant(name)} to NmsTenant,
  NmsIntServerBrand{tenant(name)} to NmsTenant,
  NmsChgNetwork{intServer(name)} to NmsIntegratorServer,
  NmsChgNetwork{type(name)} to NmsChgNetworkType,
  NmsChgNetwork{brand(name)} to NmsIntServerBrand,
  NmsRpiAlert{ten(name)} to NmsTenant,
  NmsRpiAlert{room(name)} to NmsRoom,
  NmsZone{tenant(name)} to NmsTenant,
  NmsAlert{alertType(name)} to NmsAlertType,
  NmsAlert{userAttended(firstName)} to User,
  NmsAlert{reason(name)} to NmsAlertReason,
  NmsAlert{resident(name)} to NmsResident,
  NmsAlert{room(name)} to NmsRoom,
  NmsAlert{tenant(name)} to NmsTenant,
  NmsResidentState{domain(name)} to NmsDomain,
  NmsAlertReason{domain(name)} to NmsDomain,
  NmsAlertType{tenant(name)} to NmsTenant,
  NmsMessage{sender} to User,
  NmsMessage{receiver} to User,
  NmsRoom{tenant(name)} to NmsTenant,
  NmsChatGroup{user} to User,
  NmsChatRead{user} to User,
  NmsChatRead{msg} to NmsMessage,
  NmsChatReceived{userBr} to User,
  NmsChatReceived{msg} to NmsMessage,
  NmsFamily{domain(name)} to NmsDomain,
  NmsRequest{family(name)} to NmsFamily,
  NmsRequest{employee} to NmsEmployee,
  NmsRequest{resident} to NmsResident,
  NmsRequest{domain(name)} to NmsDomain,
  NmsBugReport{type(name)} to NmsBugReportType,
  NmsBugReport{user(firstName)} to User,
  NmsReportTime{tenant(name)} to NmsTenant
}
relationship ManyToMany {
  NmsDomain{user(firstName)} to User,
  NmsEmail{domain(name)} to NmsDomain{email(name)},
  NmsEmployee{possibleZones(name)} to NmsZone{employeePossible},
  NmsEmployee{activeZones(name)} to NmsZone{employeeActive},
  NmsEmployee{possibleTenants(name)} to NmsTenant{employeePossible},
  NmsAlert{residentState(name)} to NmsResidentState{nmsAlert},
  NmsAlert{notAttend(name)} to User,
  NmsRoom{zone(name)} to NmsZone{room(name)},
  NmsChatGroup{user(firstName)} to User,
  NmsFamily{resident(name)} to NmsResident{family}
}

paginate NmsDomain, NmsEmployee, NmsResidentState, NmsAlertReason, NmsAlertType, NmsResident, NmsFamily with infinite-scroll
paginate NmsTenant, NmsRpiHeartbeat, NmsRpiHeartbeatReply, NmsRpiAlert, NmsZone, NmsAlert, NmsMessage, NmsRoom with pager

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_191"
Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.191-b12, mixed mode)

git version 2.21.0 (Apple Git-122)

node: v10.14.2

npm: 6.12.0

yarn: 1.12.3

##### **Browsers and Operating System**

- **In development**

Mac OS Catalina, 
Safari or Chrome

java -version
java version "1.8.0_191"
Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.191-b12, mixed mode)

- **In production where is giving the error**

Linux nms-cp01-vm01 4.9.0-8-amd64 #1 SMP Debian 4.9.110-3+deb9u6 (2018-10-08) x86_64

$java -version
openjdk version "1.8.0_232"
OpenJDK Runtime Environment (build 1.8.0_232-8u232-b09-1~deb9u1-b09)
OpenJDK 64-Bit Server VM (build 25.232-b09, mixed mode)

-   [ X] Checking this box is mandatory (this is just to show you read everything)

**Comment by MInesGomes** [comment] 2019-11-11 13:05
@pascalgrimaud Do you need anything from me?
After doing the changes above **is working on dev and prod. **
When I compile give these warnings for the classes that I have made changes:

```
ARNING] Classes in bundle 'Nms' do no match with execution data. For report generation the same class files must be used as at runtime.
[WARNING] Execution data for class com/gotop/nms/domain/NmsRequest does not match.
[WARNING] Execution data for class com/gotop/nms/domain/NmsAlert does not match.
[WARNING] Execution data for class com/gotop/nms/domain/NmsRpiAlert does not match.
[WARNING] Execution data for class com/gotop/nms/domain/NmsZone does not match.
[WARNING] Execution data for class com/gotop/nms/domain/NmsIntServerProvider does not match.
[WARNING] Execution data for class com/gotop/nms/domain/NmsTenant does not match.
[WARNING] Execution data for class com/gotop/nms/domain/NmsAlertReason does not match.
[WARNING] Execution data for class com/gotop/nms/domain/NmsResident does not match.
[WARNING] Execution data for class com/gotop/nms/domain/NmsIntegratorServer does not match.
[WARNING] Execution data for class com/gotop/nms/domain/NmsChatGroup does not match.
[WARNING] Execution data for class com/gotop/nms/domain/NmsMessage does not match.
[WARNING] Execution data for class com/gotop/nms/domain/NmsIntServerBrand does not match.
[WARNING] Execution data for class com/gotop/nms/domain/NmsChatReceived does not match.
[WARNING] Execution data for class com/gotop/nms/domain/NmsEmployeeLog does not match.
[WARNING] Execution data for class com/gotop/nms/domain/NmsFamily does not match.
[WARNING] Execution data for class com/gotop/nms/domain/NmsChatRead does not match.
[WARNING] Execution data for class com/gotop/nms/domain/NmsRoom does not match.
[WARNING] Execution data for class com/gotop/nms/domain/NmsBugReport does not match.
[WARNING] Execution data for class com/gotop/nms/domain/NmsChgNetwork does not match.
[WARNING] Execution data for class com/gotop/nms/domain/NmsReportTime does not match.
[WARNING] Execution data for class com/gotop/nms/domain/NmsResidentState does not match.
[WARNING] Execution data for class com/gotop/nms/domain/NmsEmployee does not match.
[WARNING] Execution data for class com/gotop/nms/domain/NmsAlertType does not match.
```

But is working ok

**Comment by pascalgrimaud** [comment] 2019-11-11 13:08
I put this tag 'need-reproduction', waiting someone else to confirm this issue.
I don't have time right now, until the end of next week, because of a conf about JHipster at Microsoft Ignite.

So unless someone else wants to have a look, you just need to be patient...

**Comment by crerdmo** [comment] 2019-11-19 14:30
I got this issue in production with @OneToMany as well:
    @OneToMany(mappedBy = "config")
    @Cache(usage = CacheConcurrencyStrategy.NONSTRICT_READ_WRITE)
    @JsonIgnoreProperties("config")
    private Set<LocalBucket> localBuckets = new HashSet<>();

The problem got solved after restarting the application in production.

This is the error message in this case:
2019-11-19 11:54:39.661  WARN 2608 --- [ XNIO-1 task-28] o.z.problem.spring.common.AdviceTrait    : Bad Request: JSON parse error: No _valueDeserializer assigned; nested exception is com.fasterxml.jackson.databind.exc.MismatchedInputException: No _valueDeserializer assigned
 at [Source: (PushbackInputStream); line: 1, column: 332] (through reference chain: com.crearesys.storagesys.domain.BackupConfig["localBuckets"]->java.util.HashSet[0]->com.crearesys.storagesys.domain.LocalBucket["id"])

**Comment by raulrotundo** [comment] 2020-01-24 14:40
I had exactly the same issue that @MInesGomes mentioned using jhipster v6.2.0 and the fix that I applied was the one she mentioned adding the allowSetters = true to @JsonIgnoreProperties.

**Comment by poolebu** [comment] 2020-03-22 16:23
I just had the same issue and this ticket saved my sanity. Also fixed with `allowSetters = true`

**Comment by pascalgrimaud** [comment] 2020-03-22 16:33
thanks, I'm changing this to bug.
If someone wants to contribute to apply the fix plz ?

**Closed** 2020-03-26 06:18 UTC
Labels: $$ bug-bounty $$, $100, area: bug :bug:, theme: api

**Comment by Shaolans** [comment] 2020-03-26 08:57
Bug Bounty claimed https://opencollective.com/generator-jhipster/expenses/14956

**Comment by pascalgrimaud** [comment] 2020-03-26 08:58
thanks @Shaolans, just approuved
