### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by uyeliksiz** [jhipster/generator-jhipster#6490] opened 2017-10-07 20:33 UTC
##### **Overview of the issue**

- I have generated an application and running on production now. In normal times it consumes %2-3 CPU. But sometimes (1 or 2 times per day) it suddenly peak to %100 and crashes apps. I do not observe any extra traffic when problem occurred.
- My server has 4 core cpu, 12 GB RAM and 300GB Full SSD disk. MY traffic is not too much, 250-300 request per minutes and almost same in a day. And CPU usage had been reached max %3 with this traffic if we exclude times when problem occurred.
- I wonder is this issue for only me, or did someone face before?
- I did research and i'm thinking there is a configuration problem.

##### **Motivation for or Use Case**

Applications have to be stable and most of user that generated app via jhipster wants to stable apps. 

##### **Related issues**

#1938 says high CPU usage with hazelcast. But i am not using hazelcast. 
- Somebody said "use ThreadPoolTaskExecutor", jhipster already use ThreadPoolTaskExecutor. ( https://stackoverflow.com/questions/39387036/spring-boot-app-consuming-all-the-cpu-when-asynctaskexecutor-is-configured )
- Somebady said Tomcat bug for version 8.5.4. But my spring version(1.5.4) uses 8.5.15. (https://stackoverflow.com/questions/39388847/spring-boot-ssl-consuming-too-much-cpu)

##### **JHipster Version(s)**

4.6.2

##### **JHipster configuration**

{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "XXX"
    },
    "jhipsterVersion": "4.6.2",
    "baseName": "XXX",
    "packageName": "XXX",
    "packageFolder": "XXX",
    "serverPort": "8008",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": true,
    "jwtSecretKey": "XXX",
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "npm",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "oak",
    "enableTranslation": false
  }
}

##### **Browsers and Operating System**

Linux version 4.4.0-93-generic (buildd@lgw01-03) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) )

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by gmarziou** [comment] 2017-10-07 21:15
This does not look a JHipster issue, at least you don't provide enough details to assert it.
What are your jvm memory settings? 
Have you enabled garbage collector logs?

**Comment by uyeliksiz** [comment] 2017-10-08 05:55
Aha ok, 
Memory settings: `-d64 -Xms6g -Xmx10g -XX:MaxPermSize=512m` 
I used `sysstat` for logging. I am watching all system cpu usage and only my Jhipster applications CPU usage. 

An example from logs:

![usage](https://user-images.githubusercontent.com/24546039/31314304-59e59f26-ac06-11e7-893b-2f487ce64481.png)

**Comment by jdubois** [comment] 2017-10-08 07:14
- we don't use Tomcat but Undertow
- and indeed you are not using Hazelcast

I have lots of apps with the basically the same config, I don't have any issue at all - what makes you say this is related to JHipster?

**Comment by uyeliksiz** [comment] 2017-10-08 08:01
It's not exactly about jhipster. It's on the code that generated by Jhipster. But also I did not make any extra configuration on it. 
I was not sure if there was a mismatch between the libraries being used. An interesting situation for me. There are around 400 requests per minute. But I can not understand why the CPU usage is peaking at a spesific times.

**Comment by atomfrede** [comment] 2017-10-08 08:45
Maybe GC kicks in? But that would be strange pattern for GC (1 or 2 times a day)

**Comment by gmarziou** [comment] 2017-10-08 10:18
> Maybe GC kicks in?

Yes that's what I thought too, this is why I suggested enabling GC logging. 
Especially with such large memory settings (up to 10GB), this is the easiest to correlate high CU usage with "stop the world" garbage collections.

**Comment by atomfrede** [comment] 2017-10-08 11:28
👍

**Comment by gzsombor** [comment] 2017-10-08 12:02
You should - at least - try to execute jstack a couple of times, during that "high" CPU usage. If you are lucky, you will see busy threads doing something ....

**Comment by uyeliksiz** [comment] 2017-10-09 05:44
I logged GC, and also Thread dumps (jstack) with 2 minutes interval. No difference was displayed normal time, before crash and at crash time.
- Logs between :  20:30 - 06:26
- Server crash down time: 06:26
- GC Analysis: https://goo.gl/mykkEr
- Thread dump: https://goo.gl/NmwcrJ
		( Thread dump 1 (05:40) .. Thread dump 14 (06:24) )
		( Other Thread Dumps are before 05:40)
- Last errors in log file
  - `2017-10-09 06:26:19.393 ERROR 5986 --- [  XNIO-2 task-1] t.o.m.w.rest.errors.ExceptionTranslator  : An unexpected error occurred: I/O error while reading input message; nested exception is java.io.InterruptedIOException: XNIO000808: I/O operation was interrupted`
  - `2017-10-09 06:26:19.396 ERROR 5986 --- [ XNIO-2 task-25] io.undertow.request                      : UT005022: Exception generating error page /error`

There is no anything new. I can not understand the problem. I can not find the source of the problem.
Could Server be inadequate for me? Where do I need to focus?

**Comment by atomfrede** [comment] 2017-10-09 06:15
I am no GC expert, but the report looks quite cool. One thing I noticed by taking a quick look is `GC Causes` (so what was the cause for GC to kick in). 97.14% of the time it was due to `Allocation Failure` and the detail says `not enough memory to create new objects when there is not enough memory in young generation`. 

Also what looks suspicious is, that there is a long time waiting on resources (either I/O or CPU).

**Comment by uyeliksiz** [comment] 2017-10-09 06:38
@atomfrede waiting on resource problem is not related with problem. Because its time that 21:12:22 when 9 hours before crash.
But you may be right at point `Allocation Failure`. I set 10g JVM memory but only 2g left for free (process using max %30 of them). Im not sure: do GC needs to allocated memory or not-allocated memory, to create new objects? 
Let me check with small heap memory.

**Comment by cbornet** [comment] 2017-10-09 07:47
@uyeliksiz just to be sure : is it a bare JHipster app or did you bring other libraries to the party ?

**Comment by uyeliksiz** [comment] 2017-10-09 07:53
@cbornet I added only `spring-retry`, `jsoup` and `gson` libraries. And one difference: i am making some http calls in one `service` with `ScheduledTask`.

**Comment by atomfrede** [comment] 2017-10-09 09:48
What is the `ScheduledTask` doing? What happens when you disable the task or change the interval of the task?

**Comment by uyeliksiz** [comment] 2017-10-09 10:08
`ScheduledTask` makes a `HttpUrlConnection ` to get some user configuration from remote server. 
i didnt try disabling it. But its interval is rarely, and crash time is so different with it. 
Could Server be inadequate for me?

**Comment by gmarziou** [comment] 2017-10-09 11:24
Nice reports, I did not know these sites.
Now that we know it's a memory consumption issue, next step could be to run a memory profiler with an automatic rule to trigger a dump when usage reaches 90%: this way you'll see what type of objects are allocated and from which code.

**Comment by atomfrede** [comment] 2017-10-09 14:28
@uyeliksiz I guess the task closes connections properly (just guessing what can go wrong here).

**Comment by gmarziou** [comment] 2017-10-09 15:07
You're right for the max memory usage but anyway your app consumes several GB between old and young gen and it seems to me that you don't know which object types are allocated. So analyzing a memory dump whether it has been triggered by a 60% or 90% threshold or just manually should give you insights. I don't consider it is useful only for memory leak.

**Comment by uyeliksiz** [comment] 2017-10-11 13:52
i have collected new logs:
* undertow IO threads (4 of all) consumes cpu
* open connection counts suddenly increases (600 to 1500) when app crashing

**Comment by ramzimaalej** [comment] 2017-10-11 16:56
@uyeliksiz are you sure you are closing the connection after using them. I would lean towards memory leak caused by the httpclient. is it expected to have 600 open connections at the same time?

**Comment by uyeliksiz** [comment] 2017-10-13 11:10
@ramzimaalej yes, im closing.

I replaced Undertow with Tomcat, and problem solved. The system is working fine for last 24 hours. 
I am going to open an issue to Undertow group. You can close this issue.
Thanks for your helps.

**Closed** 2017-10-14 11:26 UTC

**Comment by cystek** [comment] 2018-01-22 19:37
@fgustovo Did you end up creating an issue for Undertow and if so can you provide an ID or link? Thanks

**Comment by fgustovo** [comment] 2018-01-23 08:22
@cystek no, i didn't create an issue. I'm not sure is it related with undertow. 
Because i realize that i had a certification problem. Undertow didn't warn me about this, but tomcat gave me errors. 
After fixing certificate problems, tomcat worked well, and i have not try it with undertow again.

**Comment by cystek** [comment] 2018-01-23 19:38
Ok, thanks for the info and quick reply. I saw the same errors using Undertow alone so if there were an issue with it I was interested in the progress and their comments. At this point I believe my issue was client-related, though.
