### ISSUE TITLE
JHipster can't detect NodeJS version

### ISSUE THREAD

**Issue by k1c14k** [jhipster/generator-jhipster#11925] opened 2020-06-11 07:30 UTC
##### **Overview of the issue**
JHipster fails to detect nodejs version

marek@marek-GV62-7RE:~/csdm$ ./node_modules/generator-jhipster/cli/jhipster.js 
INFO! Using JHipster version installed globally
INFO! Running default command
INFO! Executing jhipster:app
INFO! Options: from-cli: true

        ██╗ ██╗   ██╗ ████████╗ ███████╗   ██████╗ ████████╗ ████████╗ ███████╗
        ██║ ██║   ██║ ╚══██╔══╝ ██╔═══██╗ ██╔════╝ ╚══██╔══╝ ██╔═════╝ ██╔═══██╗
        ██║ ████████║    ██║    ███████╔╝ ╚█████╗     ██║    ██████╗   ███████╔╝
  ██╗   ██║ ██╔═══██║    ██║    ██╔════╝   ╚═══██╗    ██║    ██╔═══╝   ██╔══██║
  ╚██████╔╝ ██║   ██║ ████████╗ ██║       ██████╔╝    ██║    ████████╗ ██║  ╚██╗
   ╚═════╝  ╚═╝   ╚═╝ ╚═══════╝ ╚═╝       ╚═════╝     ╚═╝    ╚═══════╝ ╚═╝   ╚═╝

                            https://www.jhipster.tech

Welcome to JHipster v6.9.1
Application files will be generated in folder: /home/marek/csdm
 _______________________________________________________________________________________________________________

  Documentation for creating an application is at https://www.jhipster.tech/creating-an-app/
  If you find JHipster useful, consider sponsoring the project at https://opencollective.com/generator-jhipster
 _______________________________________________________________________________________________________________

WARNING! Your NodeJS version is too old (null). You should use at least NodeJS >=10.20.1
/home/marek/csdm/node_modules/semver/classes/semver.js:41
      throw new TypeError(`Invalid Version: ${version}`)
      ^

TypeError: Invalid Version: 
    at new SemVer (/home/marek/csdm/node_modules/semver/classes/semver.js:41:13)
    at compare (/home/marek/csdm/node_modules/semver/functions/compare.js:3:32)
    at Object.lt (/home/marek/csdm/node_modules/semver/functions/lt.js:2:29)
    at shelljs.exec (/home/marek/csdm/node_modules/generator-jhipster/generators/generator-base.js:1735:43)
    at /home/marek/csdm/node_modules/shelljs/src/exec.js:127:9
    at ChildProcess.exithandler (child_process.js:301:5)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
marek@marek-GV62-7RE:~/csdm$ node -v
v10.21.0

##### **Motivation for or Use Case**
Trying to create new jhipster project fails

##### **Reproduce the error**
As in details

##### **Related issues**
N/A

##### **Suggest a Fix**

N/A

##### **JHipster Version(s)**
marek@marek-GV62-7RE:~/csdm$ ./node_modules/generator-jhipster/cli/jhipster.js info
INFO! Using JHipster version installed globally
INFO! Executing jhipster:info
INFO! Options: from-cli: true
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**
cat: no such file or directory: .yo-rc.json

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment (build 11.0.7+10-post-Ubuntu-3ubuntu1)
OpenJDK 64-Bit Server VM (build 11.0.7+10-post-Ubuntu-3ubuntu1, mixed mode, sharing)

git version 2.25.1

node: 
npm: 
Docker version 19.03.8, build afacb8b7f0

docker-compose version 1.25.0, build unknown

##### **Browsers and Operating System**

Ubuntu 20 LTS

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by MathieuAA** [comment] 2020-06-11 10:07
> ./node_modules/generator-jhipster/cli/jhipster.js
No need to do that. If you have installed JHipster (which I believe is the case), just use `jhipster`.
Further more, can you do a `node -v` and tell us what you see?

**Comment by k1c14k** [comment] 2020-06-11 12:50
Hi, I wanted to avoid installing jhipster globally. Is it **required**?

marek@marek-GV62-7RE:~/csdm$ node -v
v10.21.0

**Comment by MathieuAA** [comment] 2020-06-11 12:59
It's the same as installing maven, npm, or even yarn globally. Why would you want to avoid that?
thanks for the info BTW, will check but I didn't notice this when I played with JHipster.

**Comment by mshima** [comment] 2020-06-11 13:04
Can you try running `npx jhipster` instead?

**Comment by k1c14k** [comment] 2020-06-11 13:08
@MathieuAA I always try to narrow down # of libraries installed globally

@mshima here you are the output:

```
marek@marek-GV62-7RE:~/csdm$ npx jhipster
INFO! Using JHipster version installed globally
INFO! Running default command
INFO! Executing jhipster:app
INFO! Options: from-cli: true


        ██╗ ██╗   ██╗ ████████╗ ███████╗   ██████╗ ████████╗ ████████╗ ███████╗
        ██║ ██║   ██║ ╚══██╔══╝ ██╔═══██╗ ██╔════╝ ╚══██╔══╝ ██╔═════╝ ██╔═══██╗
        ██║ ████████║    ██║    ███████╔╝ ╚█████╗     ██║    ██████╗   ███████╔╝
  ██╗   ██║ ██╔═══██║    ██║    ██╔════╝   ╚═══██╗    ██║    ██╔═══╝   ██╔══██║
  ╚██████╔╝ ██║   ██║ ████████╗ ██║       ██████╔╝    ██║    ████████╗ ██║  ╚██╗
   ╚═════╝  ╚═╝   ╚═╝ ╚═══════╝ ╚═╝       ╚═════╝     ╚═╝    ╚═══════╝ ╚═╝   ╚═╝

                            https://www.jhipster.tech

Welcome to JHipster v6.9.1
Application files will be generated in folder: /home/marek/csdm
 _______________________________________________________________________________________________________________

  Documentation for creating an application is at https://www.jhipster.tech/creating-an-app/
  If you find JHipster useful, consider sponsoring the project at https://opencollective.com/generator-jhipster
 _______________________________________________________________________________________________________________

WARNING! Your NodeJS version is too old (null). You should use at least NodeJS >=10.20.1
/home/marek/csdm/node_modules/semver/classes/semver.js:41
      throw new TypeError(`Invalid Version: ${version}`)
      ^

TypeError: Invalid Version: 
    at new SemVer (/home/marek/csdm/node_modules/semver/classes/semver.js:41:13)
    at compare (/home/marek/csdm/node_modules/semver/functions/compare.js:3:32)
    at Object.lt (/home/marek/csdm/node_modules/semver/functions/lt.js:2:29)
    at shelljs.exec (/home/marek/csdm/node_modules/generator-jhipster/generators/generator-base.js:1735:43)
    at /home/marek/csdm/node_modules/shelljs/src/exec.js:127:9
    at ChildProcess.exithandler (child_process.js:301:5)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
```

**Comment by MathieuAA** [comment] 2020-06-11 13:20
@mshima do you know of a similar issue?

**Comment by k1c14k** [comment] 2020-06-11 13:28
The most interesting thing for me is that jhipster lives in a denial - isn't detecting node, although being executed by node.

**Comment by mshima** [comment] 2020-06-11 13:43
@MathieuAA no, the error is been thrown at https://github.com/jhipster/generator-jhipster/blob/1e43348302c34855639d73587c3761d25a61a957/generators/generator-base.js#L1735

packagejs.version is unlikely to be the source of the error.
So looks like `npm show generator-jhipster version` is not returned correctly.
npx sets some environments that could help.

@k1c14k can you post the output for `npm show generator-jhipster version`?

**Comment by mshima** [comment] 2020-06-11 13:46
The node error is a just warning.
checkNode needs an update.
https://github.com/jhipster/generator-jhipster/blob/1e43348302c34855639d73587c3761d25a61a957/generators/generator-base-private.js#L968

**Comment by k1c14k** [comment] 2020-06-11 13:49
@mshima here:
```
marek@marek-GV62-7RE:~/csdm$ npm show generator-jhipster version
6.9.1
```

**Comment by mshima** [comment] 2020-06-11 13:58
I couldn't reproduce:
```
npm -g uninstall generator-jhipster
npm install generator-jhipster@6.9.1
npx jhipster
```
Generated the project correctly.
```
$ node -v
v12.16.1
```

**Comment by mshima** [comment] 2020-06-11 14:05
> The most interesting thing for me is that jhipster lives in a denial - isn't detecting node, although being executed by node.

checkNode tries to detect node using `node -v`, looks like there are something with your environment that makes the those commands `node -v` and `npm show generator-jhipster version` return incorrectly.

A fix would be to use process.versions.node instead of `node -v` like https://github.com/jhipster/generator-jhipster/blob/1e43348302c34855639d73587c3761d25a61a957/cli/jhipster.js#L25

and use latest-version package instead of `npm show generator-jhipster version`

**Comment by pascalgrimaud** [comment] 2020-06-19 09:47
It looks like an environment issue and we didn't manage to reproduce it.

Some suggestion to help you:
- use `jhipster --skip-checks`
- use our DevBox: https://github.com/jhipster/jhipster-devbox
- maybe try to upgrade your Node version too ?

As we didn't mange to reproduce, I'm closing this.

**Closed by pascalgrimaud** 2020-06-19 09:47 UTC
Labels: area: needs-reproduction, theme: cli

**Comment by flavio20002** [comment] 2020-08-04 10:06
Hi,
I have reproduced this issue with node installed by snap:

```
$ which node
/snap/bin/node
$ node --version
v14.7.0
```

**Comment by gmarziou** [comment] 2020-08-04 13:25
Hi @flavio20002, JHipster supports only LTS versions of nodejs, 14.7.0 is current not LTS. Are you able to reproduce with LTS?

**Comment by flavio20002** [comment] 2020-08-04 13:35
Yes. Look at this snippet:

```
node
```

```
const { exec } = require("child_process");
exec("node --version", (error, stdout, stderr) => {
    if (error) {
        console.log(`error: ${error.message}`);
        return;
    }
    if (stderr) {
        console.log(`stderr: ${stderr}`);
        return;
    }
    console.log(`stdout: ${stdout}`);
});
```
Whit snap nodejs i get null:
```
stdout: 
```

With a standard nodejs i get the version value.

**Comment by gmarziou** [comment] 2020-08-05 09:30
So it would seem to be a problem with snap, don't you think so?
Have you checked whether /snap/bin/node could be some sort of wrapper that does not behave as the original node regarding stdout handling?

**Comment by j-jeurissen** [comment] 2022-08-09 08:41
Yes I can confirm, the script doesn't detect the node version when you use the snap package manager. Snap is the official recommended installation method on Debian and Ubuntu based Linux distributions. The apt package is too old of course.
