### ISSUE TITLE
React: yarn test fails to create folder if it doesn't exist

### ISSUE THREAD

**Issue by rvanrooy** [jhipster/generator-jhipster#7834] opened 2018-06-22 10:43 UTC
##### **Overview of the issue**

Yarn test fails if the reportPath doesn't exist. The new reporting library, `jest-sonar-reporter` can't create intermediary folders.

```
Test Suites: 10 passed, 10 total
Tests:       84 passed, 84 total
Snapshots:   0 total
Time:        5.465s, estimated 6s
Ran all test suites.
Error: ENOENT: no such file or directory, mkdir 'target/test-results/jest'
    at Object.fs.mkdirSync (fs.js:885:18)
    at module.exports (/home/user/code/jhipster-test/node_modules/jest-sonar-reporter/lib/reporter.js:20:8)
    at processResults (/home/user/code/jhipster-test/node_modules/jest-cli/build/run_jest.js:125:55)
    at /home/user/code/jhipster-test/node_modules/jest-cli/build/run_jest.js:244:12
    at Generator.next (<anonymous>)
    at step (/home/user/code/jhipster-test/node_modules/jest-cli/build/run_jest.js:81:191)
    at /home/user/code/jhipster-test/node_modules/jest-cli/build/run_jest.js:81:361
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
error Command failed with exit code 1.
```
##### **Motivation for or Use Case**

CI builds fail on error produced.

##### **Reproduce the error**

Create new jhipster project using v5.0.0, then
run `yarn test`

alternatively, run ``./mvnw clean && yarn test`

##### **Related issues**

New `jest-sonar-reporter` added in commit e64862 can't create intermediary folders.

##### **Suggest a Fix**

Create the folder  `<%= BUILD_DIR %>test-results/` before running any tests

##### **JHipster Version(s)**

Problem exists in v5.0.0

v5.0.0Beta-3 used jest-junit library which did not have this issue

##### **JHipster configuration**

Using JHipster version installed globally
Executing jhipster:info
Options: 
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
jhipster@0.0.0 /home/user/code/jhipster-test
└── (empty)

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "5.0.0",
    "applicationType": "monolith",
    "baseName": "jhipster",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "clientFramework": "react",
    "useSass": false,
    "clientPackageManager": "yarn",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ]
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)

git version 2.17.1

node: v8.11.3

npm: 5.6.0

yarn: 1.7.0

Docker version 18.03.1-ce, build 9ee9f40

docker-compose version 1.17.1, build unknown

Congratulations, JHipster execution is complete!

##### **Browsers and Operating System**

Linux, 
- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment] 2018-06-22 12:08
Thanks - yes we know about this, didn't @PierreBesson already create an issue on this?

**Comment by PierreBesson** [comment] 2018-06-22 12:11
No I did not create an issue before. Thanks for doing it @rvanrooy.

**Comment by jdubois** [comment] 2018-06-22 12:15
Oh great, thanks @rvanrooy !

**Comment by jdubois** [comment] 2018-06-22 12:33
I can't reproduce, looks like somebody already fixed it!!!

**Comment by jdubois** [comment] 2018-06-22 12:36
I just don't understand how this was fixed or who did it, and that's very disturbing! But I can't reproduce on the master branch, so I'm closing this.

**Comment by pascalgrimaud** [comment] 2018-06-22 16:37
I follow closely the recent commits, nothing has been done for this and it seems not easy to reproduce.

@rvanrooy : can you try again and describe all steps reproduce plz !?

**Comment by deepu105** [comment] 2018-06-22 16:42
yes indeed I couldn't reproduce as well. May be it fails only on CI?

**Comment by pascalgrimaud** [comment] 2018-06-22 16:44
no it's ok for Travis

**Comment by pascalgrimaud** [comment] 2018-06-22 17:03
Ok, just reproduced it.
It's for React:
- generate a project with React Option
- launch `yarn test` immediatly

It will failed if the folder: `target/test-results/` doesn't exist

**Comment by deepu105** [comment] 2018-06-22 17:06
@pascalgrimaud I also did for React but couldn't reproduce. I even tried again after deleting the folder

![image](https://user-images.githubusercontent.com/1107223/41789380-613adb2e-764f-11e8-9658-d170641e70a2.png)

**Comment by pascalgrimaud** [comment] 2018-06-22 17:14
@deepu105 :
I reproduce it locally on my project.
I just pushed it on GitHub: https://github.com/pascalgrimaud/jhreact180622
Then, I added a Travis build to try to reproduce it: https://travis-ci.org/pascalgrimaud/jhreact180622/builds/395555048

So Travis failed exactly like me

**Comment by pascalgrimaud** [comment] 2018-06-22 17:27
It seems to be for React only. Angular works perfectly.
I don't understand what happens, so strange!

**Comment by jdubois** [comment] 2018-06-22 17:32
Oh sorry this is stupid of me... too tired after the JHipster Conf!
This is because we had a bug in Sonar and put our test results in /target. This directory is created by Maven so if you run Yarn first it will fail.
We must create that folder with Yarn if it doesn't exist yet.

**Comment by pascalgrimaud** [comment] 2018-06-22 17:37
With Angular, we didn't create the target folder before maven and it works

**Comment by deepu105** [comment] 2018-06-22 19:48
@pascalgrimaud yes I'm also able to reproduce after pulling the latest changes from master, I guess the change in reporter causes this. I believe originally you added a junit reporter and it was fine, may be the change to sonar reporter is causing this. Is it possible to switch back to junit reporter

**Comment by deepu105** [comment] 2018-06-22 19:51
@wmarques are you ok with switching back to "jest-junit" reporter

**Comment by jdubois** [comment] 2018-06-22 19:52
No we needed to change this with @wmarques in order to have both Jest and Junit reports in the target folder, so they can be picked up by Sonar.
Previously, the issue was we had the correct test coverage, but not the correct test result (we had the Jest test coverage but not the Jest test result), which is pretty bad.

**Comment by deepu105** [comment] 2018-06-22 20:19
But with @pascalgrimaud's old code it was still writing the report right?

```
  reporters: [
    'default',
    [ 'jest-junit', { output: './target/test-results/jest/TESTS-results.xml' } ]
  ],
```

**Comment by deepu105** [comment] 2018-06-22 20:36
Oh, ok I see that the output format is different for the result. May be we can try this https://github.com/jest-community/jest-junit#example-4

**Comment by pascalgrimaud** [comment] 2018-06-22 20:37
The report is correct for **jest-junit**, but not the format.
See the **Generic Execution** part at https://docs.sonarqube.org/display/SONAR/Generic+Test+Data

With **jest-junit**, we have:

```xml
<testsuites name="jest tests" tests="81" failures="0" time="5.53">
  <testsuite name="User management reducer tests" errors="0" failures="0" skipped="0" timestamp="2018-06-22T20:33:38" time="2.903" tests="17">
```

With **jest-sonar-reporter**, we have:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<testExecutions version="1">
  <file path="/home/pgrimaud/tmp/01-react/src/test/javascript/spec/app/modules/administration/user-management/user-management.reducer.spec.ts">
```

So the report for **jest-sonar-reporter** is the correct one.

**Comment by deepu105** [comment] 2018-06-22 20:40
@pascalgrimaud also isnt sonar suppose to understand Junit format? as per this https://docs.sonarqube.org/display/PLUG/Code+Coverage+by+Unit+Tests+for+Java+Project

**Comment by pascalgrimaud** [comment] 2018-06-22 21:12
It is supposed to... I'm a little bit confuse.

But when I look at this graph: https://sonarcloud.io/project/activity?custom_metrics=tests&graph=custom&id=io.github.jhipster.sample%3Ajhipster-sample-application

It seems like the unit tests from frontend were just added recently. Sonarcloud didn't see them since the beginning ?

**Comment by pascalgrimaud** [comment] 2018-06-22 21:17
I found the fix.
I'm doing some tests and will do a PR.

**Closed** 2018-06-23 09:43 UTC
Labels: React, bug :beetle:
