### ISSUE TITLE
While passing custom question in cli and launch.json not working in jhipster 8.5.0

### ISSUE THREAD

**Issue by VijayDev98** [jhipster/generator-jhipster#27492] opened 2024-10-03 17:31 UTC
when I'm passing custom prompts commands via cmd or launch.json getting below error :

....
Debugger attached.
Debugger attached.
INFO! No custom commands found within blueprint: generator-jhipster-sample at xyz\generator-jhipster-sample
error: unknown option '--custom-question'
Waiting for the debugger to disconnect...
Waiting for the debugger to disconnect...

I have added custom-question option in generator.js
this.option('custom-question', {
desc: 'SSO key enabled',
type: Boolean,
});

as custom-question is type boolean, with 7.9.4 it's working but with 8.5.0 giving unknown option error.

**Comment by mshima** [comment] 2024-10-03 17:57
Custom options has changed in v8.
Workaround is https://github.com/jhipster/generator-jhipster/issues/27404#issuecomment-2392000325.

**Comment by mshima** [comment] 2024-10-03 17:57
Duplicate of https://github.com/jhipster/generator-jhipster/issues/27404

**Closed by mshima** 2024-10-03 17:57 UTC
Labels: area: triage, theme: undefined
