### ISSUE TITLE
Crash on marketplace

### ISSUE THREAD

**Issue by vw98075** [jhipster/generator-jhipster#5568] opened 2017-04-10 00:28 UTC
##### **Overview of the issue**

? (3/15) Would you like to install other generators from the JHipster Marketplace? Yes

     _-----_     ╭───────────────────────╮
    |       |    │      Bye from us!     │
    |--(o)--|    │       Chat soon.      │
   `---------´   │      Yeoman team      │
    ( _´U`_ )    │    http://yeoman.io   │
    /___A___\   /╰───────────────────────╯
     |  ~  |     
   __'.___.'__   
 ´   `  |° ´ Y ` 

/home/oem/.config/yarn/global/node_modules/generator-jhipster/generators/app/prompts.js:146
                name: `(${modDef.package.name}-${modDef.package.version}) ${modDef.package.description} [${modDef.package.author.name}]`
                                                                                                                                ^

TypeError: Cannot read property 'name' of undefined
    at moduleResponse.results.forEach (/home/oem/.config/yarn/global/node_modules/generator-jhipster/generators/app/prompts.js:146:129)
    at Array.forEach (native)
    at generator.httpsGet (/home/oem/.config/yarn/global/node_modules/generator-jhipster/generators/app/prompts.js:143:32)
    at IncomingMessage.res.on (/home/oem/.config/yarn/global/node_modules/generator-jhipster/generators/generator-base.js:1994:17)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

##### **Motivation for or Use Case**

It is shown in the above screenshot.

##### **Reproduce the error**

I try the process twice with a same outcome.

##### **Suggest a Fix**

I don't know how to get it fixed

##### **JHipster Version(s)**

4.2

##### **JHipster configuration**

 $ yo jhipster:info
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
/home/oem/Workspace-dev/case-study/spring-social-study-sample-jh
└── (empty)

```

cat: no such file or directory: .yo-rc.json

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml

```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

ls: no such file or directory: .jhipster/*.json

##### **Browsers and Operating System**

openjdk version "1.8.0_121"
OpenJDK Runtime Environment (build 1.8.0_121-8u121-b13-0ubuntu1.16.04.2-b13)
OpenJDK 64-Bit Server VM (build 25.121-b13, mixed mode)

git version 2.7.4

node: v6.10.0

npm: 3.10.10

yeoman: 1.8.5

yarn: 0.22.0

Docker version 17.03.1-ce, build c6d412e

##### **Browsers and Operating System**

Linux Mint 18.1

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by ruddell** [comment] 2017-04-10 01:34
Duplicate of #5563

**Closed by ruddell** 2017-04-10 01:34 UTC
