### ISSUE TITLE
JSON format different in client side vs server side when entity name starts with two capslock

### ISSUE THREAD

**Issue by Anisorf** [jhipster/generator-jhipster#9137] opened 2019-01-28 19:47 UTC
##### **Overview of the issue**

Generating Entities with the jhipster generator with two starting capslock in the name (e.g., VGeometryData), results in different naming on client side vs server side. 

##### **Motivation for or Use Case**

The json call in the request does not corrispond to what the server is expecting.

##### **Reproduce the error**

Generate an Entity by using the the `jhipster generate VGeometryData` and not with JDL or regeneration of VGeometryData.json.
Generate the Entity Viaduct that has relation O2O with VGeometryData and it is the owner.

##### **Related issues**

A related [StackOverflow post](https://stackoverflow.com/questions/30205006/why-does-jackson-2-not-recognize-the-first-capital-letter-if-the-leading-camel-c)

##### **Suggest a Fix**

A quick workaround (suggested by @ruddell ) is to add @JsonProperty("VGeometryData") above the getVGeometryData() method in the related entity, and it works.

##### **JHipster Version(s)**

Jhipster 5.7.2

##### **JHipster configuration**

`
##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.example.ese",
      "nativeLanguage": "it"
    },
    "jhipsterVersion": "5.7.2",
    "applicationType": "monolith",
    "baseName": "prova",
    "packageName": "com.example.ese",
    "packageFolder": "com/example/ese",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "************************************************************l",
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "npm",
    "testFrameworks": [
      "gatling",
      "cucumber",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "otherModules": [],
    "enableTranslation": true,
    "nativeLanguage": "it",
    "languages": [
      "it"
    ]
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity VGeometryData (vgeometry_data) {
  numBeams Integer,
  numCaisson Integer
}
entity Viaduct {
  name String
}
relationship OneToOne {
  Viaduct{vGeometryData} to VGeometryData
}

service Viaduct with serviceClass

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_191"
Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.191-b12, mixed mode)
git version 2.19.1.windows.1
node: v10.13.0
npm: 6.4.1
yeoman: 2.0.5
yarn: 1.12.3`

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment] 2019-02-07 05:51
@Anisorf @ruddell : do you think a fix can be done in the project ? If not possible, at least some documentation ?

**Comment by ruddell** [comment] 2019-02-08 17:38
I guess it's more of a Java bean standard.  I'm not sure where I would add a small note to the docs, if someone else wants to, please do.  

I'll close this for now as we have an explanation for the cause and a workaround.

**Closed by ruddell** 2019-02-08 17:38 UTC
Labels: enhancement, java
