### ISSUE TITLE
UserServiceIntTest failure

### ISSUE THREAD

**Issue by cmyker** [jhipster/generator-jhipster#6269] opened 2017-08-21 16:45 UTC
##### **Overview of the issue**

Vanilla jHipster installation is failing integration test when you run whole integration tests package.
The reason is that another test class (AccountResourceIntTest) is running before and deleting the data that this test relies on.
##### **Reproduce the error**

I just used fresh jHipster 4.6.2 installation 
##### **Suggest a Fix**

https://github.com/jhipster/generator-jhipster/pull/6251
##### **JHipster Version(s)**

4.6.2
##### **JHipster configuration**

jhipster info
Executing jhipster:info
Options: 
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
admin@0.0.0 /home/igor/Projects/tracker/admin
└── generator-jhipster@4.6.2 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.sevensenders.tracker.admin"
    },
    "jhipsterVersion": "4.6.2",
    "baseName": "admin",
    "packageName": "com.sevensenders.tracker.admin",
    "packageFolder": "com/sevensenders/tracker/admin",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "no",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "mongodb",
    "devDatabaseType": "mongodb",
    "prodDatabaseType": "mongodb",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "gradle",
    "enableSocialSignIn": false,
    "rememberMeKey": "replaced-by-jhipster-info",
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

openjdk version "1.8.0_144"
OpenJDK Runtime Environment (IcedTea 3.5.1) (suse-10.13.3-x86_64)
OpenJDK 64-Bit Server VM (build 25.144-b01, mixed mode)

git version 2.12.3

node: v6.9.1

npm: 3.10.8

bower: 1.7.9

gulp:
[18:41:54] CLI version 3.9.1

yeoman: 2.0.0

yarn: 0.27.5

Docker version 1.12.6, build 78d1802

docker-compose version 1.8.1, build unknown

Execution complete

##### **Browsers and Operating System**

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment] 2017-08-22 08:07
We run those tests all the time (including in our CI system), so I'm pretty sure they work - how do you run them exactly? Do you do something like `./mvnw test`?

**Comment by cmyker** [comment] 2017-08-22 08:19
yes, ./gradlew test

**Comment by cmyker** [comment] 2017-08-22 08:22
```
./gradlew test

> Task :test

com.sevensenders.tracker.admin.service.UserServiceIntTest > assertThatUserMustExistToResetPassword FAILED
    org.junit.ComparisonFailure at UserServiceIntTest.java:66

com.sevensenders.tracker.admin.service.UserServiceIntTest > testRemoveOldPersistentTokens FAILED
    java.util.NoSuchElementException at UserServiceIntTest.java:50

99 tests completed, 2 failed


FAILURE: Build failed with an exception.

```

**Comment by jdubois** [comment] 2017-08-22 08:44
I just ran it without any issue.... I used your `.yo-rc.json` with the current master branch (so not exactly your version, but that shouldn't make a difference - anyway this is always run by our CI system). I'm sorry but I can't reproduce.

**Comment by cmyker** [comment] 2017-08-22 08:49
The thing is, if I run the test alone - it works fine, but running them all together breaks it.
I suspect tests order is different for me and for you. Where can I see your CI running those tests?

**Comment by jdubois** [comment] 2017-08-22 09:01
I don't understand how the order would be different - but indeed that's the only logical explanation!
The CI system is at https://travis-ci.org/jhipster/generator-jhipster

**Comment by cmyker** [comment] 2017-08-22 09:34
Yes, my assumption was correct, the order is different for you, see the screenshot
![jhipster-ci](https://user-images.githubusercontent.com/1872718/29558854-ae2b7da6-872d-11e7-82d8-75c79f7956cc.png)

**Comment by jdubois** [comment] 2017-08-22 09:36
OK, so this is indeed a bug (the order shouldn't matter), and now I should be able to find a way to reproduce this.

**Comment by jdubois** [comment] 2017-08-28 16:40
I'm sorry but I tried again to reproduce, by changing the order, and I still can't reproduce:

- Running `./gradlew test` works in both orders
- Running the tests with Intellij IDEA works in both orders

So I'm closing this as I can't reproduce - are you sure you didn't change anything to the original code?? This is so strange.

**Closed by jdubois** 2017-08-28 16:40 UTC

**Comment by gclayburg** [comment] 2017-10-04 18:16
FYI - I stumbled across this exact error today.  vanilla jhipster 4 project using mongoDB.  I'll try digging into a workaround.

**Comment by cbornet** [comment] 2017-10-04 18:30
See https://github.com/cbornet/generator-jhipster-grpc/blob/master/generators/app/templates/_UserServiceIntTest.java for a fix. I'll push it to the main gen asap.

**Comment by gclayburg** [comment] 2017-10-04 19:01
ok cool.  It looks like you are redoing the test to create the user being tested first.

I was able to at least workaround this issue and get a gradle build to work by adding `@Ignore` to this one test method:

`com.mycompany.myapp.service.UserServiceIntTest.assertThatUserMustExistToResetPassword`
