### ISSUE TITLE
When clicking on sign in the page below scrolls down to the bottom

### ISSUE THREAD

**Issue by gaberon** [jhipster/generator-jhipster#7510] opened 2018-04-20 08:28 UTC
##### **Overview of the issue**
When clicking on "sign in" in the navbar the modal opens, but the page below scrolls down to the bottom. When I close the modal the page below doesn't scroll back up.
##### **Reproduce the error**
If you write a long text for the home page and then you click sign in, the home page will scroll down. You won't notice it in the autogenerated page because the home page is short
##### **JHipster Version(s)**

I'm using jhipster 4.14.1
##### **JHipster configuration**

jhipster info
Using JHipster version installed locally in current project's node_modules
Executing jhipster:info
Options:
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
license-manager@0.0.0 C:\Users\csto1024\Desktop\myApp\prova5avio\licensemanager
`-- generator-jhipster@4.14.1

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "it.mylicensemanager",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "4.14.1",
    "baseName": "licenseManager",
    "packageName": "itmylicensemanager",
    "packageFolder": "it/mylicensemanager",
    "serverPort": "8080",
    "authenticationType": "session",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": false,
    "rememberMeKey": "replaced-by-jhipster-info",
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "it"
    ]
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Producer (producer) {
  name String,
  code String
}
entity Software (software) {
  name String,
  code String
}
entity License (license) {
  amountLicense BigDecimal,
  expiryDate LocalDate,
  costForLicense BigDecimal,
  note String,
  costout Boolean,
  gepool Boolean,
  type Type,
  totalCost BigDecimal
}
entity Vendor (vendor) {
  name String,
  code String
}
entity Oda (oda) {
  odaCode String,
  amount BigDecimal,
  odaDate LocalDate,
  file AnyBlob
}
entity Rda (rda) {
  rdaCode String,
  amount BigDecimal,
  requestDate LocalDate,
  rdaDate LocalDate,
  file AnyBlob
}
entity Site (site) {
  name String,
  code String,
  country String
}
entity OdaSite (oda_site) {
  amount BigDecimal
}
entity Invoice (invoice) {
  code String,
  amount BigDecimal,
  date LocalDate,
  file AnyBlob
}
entity PortfolioManager (portfolio_manager) {
  name String,
  surname String,
  sso String
}
entity Category (category) {
  description String
}
entity Maintenance (maintenance) {
  startingDate LocalDate,
  endingDate LocalDate,
  amountLicense BigDecimal,
  totalAmout BigDecimal
}
entity Sal (sal) {
  salDate LocalDate,
  salThreeS String,
  salSap String,
  amount BigDecimal
}
entity LicenseSite (license_site) {
  percentage BigDecimal
}

enum Type {
  PERPETUA,
   LEASING
}

relationship OneToOne {
  Oda{rda required} to Rda{oda}
}
relationship OneToMany {
  Producer{software} to Software{producer required},
  PortfolioManager{software} to Software{portfolioManager},
  Software{license} to License{software required},
  Vendor{license} to License{vendor required},
  Category{license} to License{category},
  Rda{license} to License{rda required},
  Oda{odaSite} to OdaSite{oda required},
  Site{odaSite} to OdaSite{site required},
  Oda{invoice} to Invoice{oda required},
  Oda{sal} to Sal{oda required}
}
relationship ManyToOne {
  LicenseSite{license} to License,
  LicenseSite{site} to Site
}
relationship ManyToMany {
  Maintenance{license} to License{maintenance}
}

paginate License with pagination

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

git version 2.15.1.windows.2

node: v8.10.0

npm: 5.6.0

yeoman: 2.0.1

yarn: 1.5.1

Congratulations, JHipster execution is complete!

##### **Browsers and Operating System**

- [X ] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment] 2018-04-30 10:10
I confirm your issue, and as we don't do anything specific here, this seems to caused by this issue on ng-bootstrap: https://github.com/ng-bootstrap/ng-bootstrap/issues/1776

I'm closing this as the issue is not on our side, but unfortunately the ticket as also been closed on the ng-bootrap side - @gaberon could you comment there, maybe giving them a sample as they requested, so they could fix it? Then we'll simply upgrade the lib and it will be fixed for us.

**Closed by jdubois** 2018-04-30 10:10 UTC
