### ISSUE TITLE
Cucumber Tests fail with HazelCast session replication

### ISSUE THREAD

**Issue by lukasw44** [jhipster/generator-jhipster#2502] opened 2015-12-18 20:30 UTC
Hi
there is no option to reopen a issue (#2395) but i start new project with jhipster 2.66.1 and when i typing mvn clean install this bug still exist. It's weird because the same configuration but with gradle, works fine .So that issue appear when you use maven.

my yo-rc.json
```
{
  "generator-jhipster": {
    "baseName": "admin",
    "packageName": "it.seiton.seed.admin",
    "packageFolder": "it/seiton/seed/admin",
    "authenticationType": "oauth2",
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": "hazelcast",
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "useSass": false,
    "buildTool": "maven",
    "frontendBuilder": "grunt",
    "enableTranslation": true,
    "enableSocialSignIn": false,
    "rememberMeKey": "fa1371803169d54cb05dc10ab5802a31279f80bb",
    "testFrameworks": [
      "gatling",
      "cucumber",
      "protractor"
    ]
  }
}
```

```
2015-12-18 21:08:49.286 DEBUG 12610 --- [           main] i.s.s.admin.service.UserServiceIntTest   : Running with Spring Boot v1.3.0.RELEASE, Spring v4.2.3.RELEASE
2015-12-18 21:08:49.286  INFO 12610 --- [           main] i.s.s.admin.service.UserServiceIntTest   : No profiles are active
2015-12-18 21:08:50.389 DEBUG 12610 --- [           main] i.s.s.admin.config.AsyncConfiguration    : Creating Async Task Executor
2015-12-18 21:08:50.455 DEBUG 12610 --- [           main] i.s.s.admin.config.MetricsConfiguration  : Registering JVM gauges
2015-12-18 21:08:50.456 DEBUG 12610 --- [           main] i.s.s.admin.config.MetricsConfiguration  : Initializing Metrics JMX reporting
2015-12-18 21:08:50.527 DEBUG 12610 --- [           main] i.s.s.admin.config.CacheConfiguration    : Configuring Hazelcast
2015-12-18 21:08:50.528  WARN 12610 --- [           main] ationConfigEmbeddedWebApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.context.ApplicationContextException: Unable to start embedded container; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'tomcatEmbeddedServletContainerFactory' defined in class path resource [org/springframework/boot/autoconfigure/web/EmbeddedServletContainerAutoConfiguration$EmbeddedTomcat.class]: Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'webConfigurer': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private com.hazelcast.core.HazelcastInstance it.seiton.seed.admin.config.WebConfigurer.hazelcastInstance; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'hazelcastInstance' defined in class path resource [it/seiton/seed/admin/config/CacheConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.hazelcast.core.HazelcastInstance]: Factory method 'hazelcastInstance' threw exception; nested exception is com.hazelcast.core.DuplicateInstanceNameException: HazelcastInstance with name 'admin' already exists!
2015-12-18 21:08:50.529  INFO 12610 --- [           main] i.s.s.admin.config.CacheConfiguration    : Closing Cache Manager
2015-12-18 21:08:50.561 ERROR 12610 --- [           main] o.s.boot.SpringApplication               : Application startup failed

org.springframework.context.ApplicationContextException: Unable to start embedded container; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'tomcatEmbeddedServletContainerFactory' defined in class path resource [org/springframework/boot/autoconfigure/web/EmbeddedServletContainerAutoConfiguration$EmbeddedTomcat.class]: Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'webConfigurer': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private com.hazelcast.core.HazelcastInstance it.seiton.seed.admin.config.WebConfigurer.hazelcastInstance; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'hazelcastInstance' defined in class path resource [it/seiton/seed/admin/config/CacheConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.hazelcast.core.HazelcastInstance]: Factory method 'hazelcastInstance' threw exception; nested exception is com.hazelcast.core.DuplicateInstanceNameException: HazelcastInstance with name 'admin' already exists!
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.onRefresh(EmbeddedWebApplicationContext.java:133) ~[spring-boot-1.3.0.RELEASE.jar:1.3.0.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:531) ~[spring-context-4.2.3.RELEASE.jar:4.2.3.RELEASE]
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118) ~[spring-boot-1.3.0.RELEASE.jar:1.3.0.RELEASE]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:752) ~[spring-boot-1.3.0.RELEASE.jar:1.3.0.RELEASE]
        at org.springframework.boot.SpringApplication.doRun(SpringApplication.java:347) ~[spring-boot-1.3.0.RELEASE.jar:1.3.0.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:295) ~[spring-boot-1.3.0.RELEASE.jar:1.3.0.RELEASE]
        at org.springframework.boot.test.SpringApplicationContextLoader.loadContext(SpringApplicationContextLoader.java:98) [spring-boot-1.3.0.RELEASE.jar:1.3.0.RELEASE]
        at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:98) [spring-test-4.2.3.RELEASE.jar:4.2.3.RELEASE]
        at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:116) [spring-test-4.2.3.RELEASE.jar:4.2.3.RELEASE]
        at org.springframework.test.context.support.DefaultTestContext.getApplicationContext(DefaultTestContext.java:83) [spring-test-4.2.3.RELEASE.jar:4.2.3.RELEASE]
        at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.injectDependencies(DependencyInjectionTestExecutionListener.java:117) [spring-test-4.2.3.RELEASE.jar:4.2.3.RELEASE]
        at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.prepareTestInstance(DependencyInjectionTestExecutionListener.java:83) [spring-test-4.2.3.RELEASE.jar:4.2.3.RELEASE]
        at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:228) [spring-test-4.2.3.RELEASE.jar:4.2.3.RELEASE]
        at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.createTest(SpringJUnit4ClassRunner.java:230) [spring-test-4.2.3.RELEASE.jar:4.2.3.RELEASE]
        at org.springframework.test.context.junit4.SpringJUnit4ClassRunner$1.runReflectiveCall(SpringJUnit4ClassRunner.java:289) [spring-test-4.2.3.RELEASE.jar:4.2.3.RELEASE]
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) [junit-4.12.jar:4.12]
        at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.methodBlock(SpringJUnit4ClassRunner.java:291) [spring-test-4.2.3.RELEASE.jar:4.2.3.RELEASE]
        at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:249) [spring-test-4.2.3.RELEASE.jar:4.2.3.RELEASE]
        at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:89) [spring-test-4.2.3.RELEASE.jar:4.2.3.RELEASE]
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290) [junit-4.12.jar:4.12]
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71) [junit-4.12.jar:4.12]
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288) [junit-4.12.jar:4.12]
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58) [junit-4.12.jar:4.12]
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268) [junit-4.12.jar:4.12]
        at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61) [spring-test-4.2.3.RELEASE.jar:4.2.3.RELEASE]
        at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70) [spring-test-4.2.3.RELEASE.jar:4.2.3.RELEASE]
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363) [junit-4.12.jar:4.12]
        at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:193) [spring-test-4.2.3.RELEASE.jar:4.2.3.RELEASE]
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:283) [surefire-junit4-2.18.1.jar:2.18.1]
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:173) [surefire-junit4-2.18.1.jar:2.18.1]
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153) [surefire-junit4-2.18.1.jar:2.18.1]
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:128) [surefire-junit4-2.18.1.jar:2.18.1]
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203) [surefire-booter-2.18.1.jar:2.18.1]
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155) [surefire-booter-2.18.1.jar:2.18.1]
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103) [surefire-booter-2.18.1.jar:2.18.1]
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'tomcatEmbeddedServletContainerFactory' defined in class path resource [org/springframework/boot/autoconfigure/web/EmbeddedServletContainerAutoConfiguration$EmbeddedTomcat.class]: Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'webConfigurer': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private com.hazelcast.core.HazelcastInstance it.seiton.seed.admin.config.WebConfigurer.hazelcastInstance; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'hazelcastInstance' defined in class path resource [it/seiton/seed/admin/config/CacheConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.hazelcast.core.HazelcastInstance]: Factory method 'hazelcastInstance' threw exception; nested exception is com.hazelcast.core.DuplicateInstanceNameException: HazelcastInstance with name 'admin' already exists!
```

**Comment by pascalgrimaud** [comment] 2015-12-18 21:47
@lukasw44 : can you try without cucumber ?

**Comment by lukasw44** [comment] 2015-12-19 09:32
@pascalgrimaud without cucumber its working fine.

**Comment by pascalgrimaud** [comment] 2015-12-19 09:34
Yes, same for me. After some tests,
- Hazelcast without Cucumber => OK
- Hazelcast with Cucumber => KO

As @phouverneyuff fix the gradle version https://github.com/jhipster/generator-jhipster/pull/2275/ maybe you can do the same for maven ? But it seems to be more complex than gradle.

Since modules system is out, I think the best thing would be to make Cucumber as module.
@lordlothar99 maybe you can do it, as you are the original author ?

**Comment by jdubois** [comment] 2015-12-19 09:34
OK, I was going to close this because I couldn't reproduce -> I'm going to rename the title, in fact that's only failing when you have Cucumber

**Comment by lukasw44** [comment] 2015-12-19 09:35
Yes its fails only with cucumber and maven

**Comment by lukasw44** [comment] 2015-12-19 09:58
I see that for gradle @phouverneyuff use specific order, but i am afraid that for maven correct solution is using failsawe plugin for cucumber test

**Comment by jdubois** [comment] 2015-12-30 09:43
Fixed by https://github.com/jhipster/generator-jhipster/commit/680d7060f9e7c229e99b1aa8ab54ec2d7b76638f

**Closed by jdubois** 2015-12-30 09:43 UTC
Labels: bug

**Comment by pascalgrimaud** [comment] 2015-12-30 20:30
In fact, I think there are 2 issues here :
- maven + hazelcast hibernateCache + cucumber => still KO in 2.26.2
- maven + hazelcast cluster + cucumber => OK now (KO before)
- gradle => OK

I used this `.yo-rc.json` and `mvn test` failed :
```
{
  "generator-jhipster": {
    "baseName": "jhipster",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "authenticationType": "session",
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": "no",
    "useSass": false,
    "buildTool": "maven",
    "frontendBuilder": "grunt",
    "enableTranslation": true,
    "enableSocialSignIn": false,
    "rememberMeKey": "b7247d0e101bf97a06bf1787320b8f4c4e0058f6",
    "testFrameworks": [
      "cucumber"
    ]
  }
}
```

Sorry @jdubois but it seems that this issue is not totally resolved => can you confirm ?

**Comment by jdubois** [comment] 2016-01-01 08:43
Bummer, this will never be solved!!!!!
@pascalgrimaud this is another issue (I'll open it ASAP), as this is not with session replication but with the 2nd level cache....
