### ISSUE TITLE
Translation not working on Gateway UI

### ISSUE THREAD

**Issue by sendilkumarn** [jhipster/generator-jhipster#7288] opened 2018-03-13 16:05 UTC
Translations for gateway application is not working on the current master. 

Getting Translation not found error. 

@deepu105 can you check this, probably because of the recent wp4 updates.

**Comment by pascalgrimaud** [comment] 2018-03-14 07:11
Not only for Gateway. I have the same for simple monolith, in administration's page

**Comment by deepu105** [comment] 2018-03-14 08:01
I'll take a look this weekend


Thanks & Regards,
Deepu

**Comment by deepu105** [comment] 2018-03-16 23:31
duplicate of #7307

**Closed by deepu105** 2018-03-16 23:31 UTC
Labels: bug :beetle:
