### ISSUE TITLE
Improved Cache logic in generated code

### ISSUE THREAD

**Issue by vraravam** [jhipster/generator-jhipster#9980] opened 2019-06-24 02:30 UTC
##### **Overview of the feature request**

In the generated code, for `User` entity, there is code to handle cache reads and evictions as any instance is created/updated/deleted. This pattern is not followed consistently for other entities generated via jHipster

##### **Motivation for or Use Case**

Using the generator to generate entity code, the `CacheConfiguration.java` and the respective entity files have code for cache configurations at the class and property level. *But*, the cache eviction is not generated on CUD operation. This caused a lot of problems which resulted in foreign key constraints being violated when the db-state and the incoming object state did not match - thus showing an "Internal Server Error" to the end user in the UI. Turning off the cache for some of the main transactional entities in my application solved this issue.

##### **Related issues or PR**

No duplicated issue/feature request found.

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by vraravam** [comment] 2019-06-24 02:59
For eg, look at the line: https://github.com/jhipster/generator-jhipster/blob/3a7b9a9650104a7d1165be97fe38ef09a68faeac/generators/server/templates/src/main/java/package/service/UserService.java.ejs#L866 - i would like a similar code-generation for other entities generated via yeoman.

**Comment by jdubois** [comment] 2019-06-24 10:24
The `User` entity is a special one, in fact it's probably the only specific one in JHipster, as it's both a domain object and it is used by Spring Security. It's also the only one where we use the Spring cache abstraction, so you won't have this issue anywhere else in JHipster.

So I don't really understand, you mean you also have Spring cache issues in other entites? Maybe because they are linked to the user entity?

**Comment by vraravam** [comment] 2019-06-24 10:29
@jdubois - thanks for getting back.
I agree that `User` is special in one sense. But, my confusion arises from the fact that the `CacheConfiguration` is injected with configurations for caches related to the other entities that are generated. But, those caches are not "managed" is invalidated on an update/delete action (at least looking at the generated code in the entity and the service classes).

In my case,  I was able to drill down the flakiness in production mode and isolated the cache to be the possible culprit. Thus, I am trying to ask if its possible for the caching (eviction, etc) as part of the generated code.

**Comment by PierreBesson** [comment] 2019-06-24 16:49
Managing a caching for your entities is dependent on the entities that were generated. In order to reproduce, can you please provide the JDL file of your entities or at the minimum a JDL which reproduces your issue.

**Comment by vraravam** [comment] 2019-06-24 18:02
Here's the JDL that I am using.
The entities that I am getting the errors are: Resume and CoverLetter.

[resume-builder-jdl.txt](https://github.com/jhipster/generator-jhipster/files/3322015/resume-builder-jdl.txt)

**Comment by pascalgrimaud** [comment] 2019-12-30 09:28
As there is no comment since June, I think there is a lack of interest for improving our Cache logic.

That's why I'm closing this.
Feel free to review our current code and propose directly a pull request to improve it.

**Closed by pascalgrimaud** 2019-12-30 09:28 UTC
Labels: area: enhancement :wrench:, status: needs-discussion, theme: java
