### ISSUE TITLE
Failed to deploy in a different context to root

### ISSUE THREAD

**Issue by jperezdelafuente** [jhipster/generator-jhipster#22542] opened 2023-06-13 11:42 UTC
##### **Overview of the issue**

With authenticationType session:

- When I deploy a project in Tomcat 10.1.10 it´s run OK, but when I try login with admin / admin I get 200 OK but browser show public page and don´t show private pages with admin menu.
- With ./mvnw -Pprod the login process it´s work OK

With authenticationType jwt:
- When I deploy a project in Tomcat 10.1.10 it´s run OK, but when I try login with admin / admin I get "HTTP 405 – Method Not Allowed" for "POST http://localhost:8080/geiser/api/authenticate" and this logs:
```
- 2023-06-13T11:31:17.436+02:00  WARN 238448 --- [nio-8080-exec-7] .w.s.m.s.DefaultHandlerExceptionResolver : Resolved [org.springframework.web.HttpRequestMethodNotSupportedException: Request method 'POST' is not supported]
2023-06-13T11:31:17.437+02:00 ERROR 238448 --- [nio-8080-exec-7] o.s.b.w.servlet.support.ErrorPageFilter  : Cannot forward to error page for request [/api/authenticate] as the response has already been committed. As a result, the response may have the wrong status code. If your application is running on WebSphere Application Server you may be able to resolve this problem by setting com.ibm.ws.webcontainer.invokeFlushAfterService to false
```
- With ./mvnw -Pprod the login process it´s work OK

##### **Motivation for or Use Case**

Deploy in external Tomcat 10.1.10 

##### **Reproduce the error**

1. Install Jhipster v8.0.0-beta.1
2. Generate a monolithic app
3. Convert to .war with this steps for angular: https://www.jhipster.tech/production/#building-an-executable-jar--war-file
- Modify the pom.xml to change the application packaging to war like:
```
  -    <packaging>jar</packaging>
  +    <packaging>war</packaging>

```
- Modify the pom.xml to change the scope of spring-boot-starter-undertow dependency to provided
- Update the index.html with the proper base tag. Considering jhipster as the context path, base tag value should look like:
<base href="/foo/"/>
4. Generate with ./mvnw clean package -Pprod -DskipTests
5. Copy .war with: cp foo-0.0.1-SNAPSHOT.war.original ../../apache-tomcat-10.1.10/webapps/foo.war
6. Start Tomcat
7. Acces to http://localhost:8080/foo/ it´s OK
8. Try login with admin / admin

##### **Suggest a Fix**

Maybe the code generated by jhipster is not compatible with the new versions of spring security
https://docs.spring.io/spring-security/reference/5.8/migration/servlet/config.html

##### **JHipster Version(s)**

v8.0.0-beta.1

##### **JHipster configuration**

<details>
  <summary>JDL definitions</summary>
  <pre>
application {
  config {
    applicationType monolith,
    baseName foo,
    packageName com.foo,
    jhiPrefix gsr,
    authenticationType session,
    databaseType sql,
    devDatabaseType h2Disk,
    prodDatabaseType oracle,
    enableHibernateCache true,
    cacheProvider ehcache,
    buildTool maven,
    testFrameworks [cypress, gatling, cucumber],
    clientFramework angular,
    enableTranslation true,
    nativeLanguage es,
    languages [es, en]
  }
  entities *
}
  </pre>
  </details>

##### **Browsers and Operating System**
Firefox 113.0.2 (64-bit)
Ubuntu 22.04
openjdk version "17.0.7" 2023-04-18

**Comment by mraible** [comment] 2023-07-08 19:57
Please let us know if you have figured out the cause of this issue.

**Comment by jperezdelafuente** [comment] 2023-07-08 22:26
I made several deployment attempts on Tomcat 10.1.0 and I don't know what
could cause it to not work

**Comment by jperezdelafuente** [comment] 2023-07-10 11:21
Maybe the code generated by jhipster is not compatible with the new versions of spring security
https://docs.spring.io/spring-security/reference/5.8/migration/servlet/config.html

**Comment by mraible** [comment] 2023-07-10 15:03
I just tried it, and it worked fine for me. 

<img width="1682" alt="Screenshot 2023-07-10 at 9 00 22 AM" src="https://github.com/jhipster/generator-jhipster/assets/17892/5ddfb139-bc6e-4277-a26a-64a120dc43e4">

I'm able to log in too.

<img width="1337" alt="Screenshot 2023-07-10 at 9 00 42 AM" src="https://github.com/jhipster/generator-jhipster/assets/17892/283af12c-baef-4f91-bec7-46be1a4f5c63">

One thing I did to make things easier was to copy `jhipster-0.0.1-SNAPSHOT.war` to `$CATALINA_HOME/webapps/ROOT.war`. That way, I didn't have to deal with a context path. 

I'm closing this issue since everything seems to work.

**Comment by mraible** [comment] 2023-07-11 16:19
I tried modifying `index.html` to have `<base href="/foo/" />` and I added the following to `application.yml`:

```yaml
server:
  servlet:
    context-path: /foo
```

I'm able to reproduce your problem, but I don't know how to fix it.

I thought it might be a CORS issue since no CORS registration was printed to the console. Changing the filter to a `CorsConfigurationSource` makes the registration print to the console, but it still doesn't work. I tried disabling CORS, and that doesn't work either.

I'll re-open this issue in hopes that someone else knows how to fix it.

**Comment by jperezdelafuente** [comment] 2023-07-11 19:47
I think it could be a front packaging error in Webpack due to the browser traces in the previous screenshot.

In the documentation for React and Vue, the context must be indicated in the Webpack configuration:
_Please note that when building a JAR or WAR file with a context path and you chose the React client or the Vue client, you will need to update the webpack.prod.js and/or webpack.common.js (update both files in case of Vue) with the proper base attribute value. Considering jhipster as the context path, base attribute value should look like:_
```
new HtmlWebpackPlugin({
    ...
    base: '/jhipster/'
})
```
https://www.jhipster.tech/production/#building-an-executable-jar--war-file

Maybe for Angular we have to do something similar

Since the issue has been reproduced, could it be marked as a bug?

**Comment by mraible** [comment] 2023-07-11 19:59
I'm not sure it has anything to do with the front end since the back end is the one that says POST is not allowed. If you find a fix, we'd love a PR. 

I added "feature request" instead of "bug" because we expect most people to make JAR not WAR and run their app as an executable JAR. Also, there is a provided workaround - just name your app ROOT.war.

**Comment by jperezdelafuente** [comment] 2023-07-11 22:27
Since the error traces from the screenshot above occur on the index page
before the log in is attempted, that's why I think it might be related to
packaging the front end with Webpack.

It seems that the problem occurs when deploying in its own context,
regardless of whether it is deployed in an external Tomcat with a .war, due
to the previous configuration:

server:
    port: 8080
    contextPath: /context-path

**Comment by jperezdelafuente** [comment] 2023-07-12 08:02
Checked, when I start on embedded server (without an external tomcat) with this configuration in application-prod.yml:

```
server:
    port: 8080
    contextPath: /foo
```
and this in index.html:
```
<!DOCTYPE html>
<html class="no-js" lang="es" dir="ltr">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title>foo</title>
    <meta name="description" content="Description for foo" />
    <meta name="google" content="notranslate" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="theme-color" content="#000000" />
    <base href="/foo/"/>
    <link rel="icon" href="favicon.ico" />
    <link rel="manifest" href="manifest.webapp" />
    <link rel="stylesheet" href="content/css/loading.css" />
    <!-- jhipster-needle-add-resources-to-root - JHipster will add new resources here -->
  </head>
```
when I access to http://localhost:8080/foo/ (before accessing to try to log in) then it shows:
![imagen](https://github.com/jhipster/generator-jhipster/assets/9991172/5e66fa0a-a918-4f25-88b1-56b4667c7881)

Several errors appear in the browser console:

- The images are not found (since the foo context was not added to the path)
- Http failure during parsing for http://localhost:8080/foo/management/info", error: {…} } in 5728.13d74c80b040ad70.js

Since the error traces from the screenshot above occur on the index page before the log in is attempted, that's why I think it might be related to packaging the front end with Webpack.

For this reason I change the title of this issue from "Failed to deploy in Tomcat 10.1.10" to "Failed to deploy in a different context to root"

**Comment by mraible** [comment] 2023-07-12 13:54
I'll add a bug bounty in hopes that someone can figure out how to fix this.

**Comment by mshima** [comment] 2023-08-14 18:43
After generating with https://github.com/jhipster/generator-jhipster/pull/23166.
The following configuration is required:
```diff
diff --git a/angular.json b/angular.json
index 5a4e3f0..05d639f 100644
--- a/angular.json
+++ b/angular.json
@@ -23,6 +23,7 @@
             "customWebpackConfig": {
               "path": "./webpack/webpack.custom.js"
             },
+            "baseHref": "/foo/",
             "outputPath": "target/classes/static/",
             "index": "src/main/webapp/index.html",
             "main": "src/main/webapp/main.ts",
diff --git a/src/main/resources/config/application.yml b/src/main/resources/config/application.yml
index 908582c..7fee4e1 100644
--- a/src/main/resources/config/application.yml
+++ b/src/main/resources/config/application.yml
@@ -155,6 +155,7 @@ spring:

 server:
   servlet:
+    context-path: /foo/
     session:
       cookie:
         http-only: true
diff --git a/src/main/webapp/app/app.module.ts b/src/main/webapp/app/app.module.ts
index 6823ff0..11f4499 100644
--- a/src/main/webapp/app/app.module.ts
+++ b/src/main/webapp/app/app.module.ts
@@ -1,5 +1,5 @@
 import { NgModule, LOCALE_ID } from '@angular/core';
-import { registerLocaleData } from '@angular/common';
+import { APP_BASE_HREF, PlatformLocation, registerLocaleData } from '@angular/common';
 import { HttpClientModule } from '@angular/common/http';
 import locale from '@angular/common/locales/en';
 import { BrowserModule, Title } from '@angular/platform-browser';
@@ -33,6 +33,11 @@ import { AppPageTitleStrategy } from './app-page-title-strategy';
     TranslationModule,
   ],
   providers: [
+    {
+      provide: APP_BASE_HREF,
+      useFactory: (platformLocation: PlatformLocation) => platformLocation.getBaseHrefFromDOM(),
+      deps: [PlatformLocation],
+    },
     Title,
     { provide: LOCALE_ID, useValue: 'en' },
     { provide: NgbDateAdapter, useClass: NgbDateDayjsAdapter },
diff --git a/src/main/webapp/swagger-ui/index.html b/src/main/webapp/swagger-ui/index.html
index e4ab34a..2728ed3 100644
--- a/src/main/webapp/swagger-ui/index.html
+++ b/src/main/webapp/swagger-ui/index.html
@@ -3,7 +3,7 @@
   <head>
     <meta charset="UTF-8" />
     <title>bug-context-path - Swagger UI</title>
-    <base href="/swagger-ui/" />
+    <base href="/foo/swagger-ui/" />
     <link rel="stylesheet" type="text/css" href="./swagger-ui.css" />
     <link rel="icon" type="image/png" href="./favicon-32x32.png" sizes="32x32" />
     <link rel="icon" type="image/png" href="./favicon-16x16.png" sizes="16x16" />
diff --git a/webpack/proxy.conf.js b/webpack/proxy.conf.js
index 642725d..c655c7f 100644
--- a/webpack/proxy.conf.js
+++ b/webpack/proxy.conf.js
@@ -1,8 +1,9 @@
 function setupProxy({ tls }) {
+  const contextPath = require('../angular.json').projects['bug-context-path'].architect.build.options.baseHref ?? '';
   const serverResources = ['/api', '/services', '/management', '/v3/api-docs', '/h2-console', '/auth', '/health'];
   const conf = [
     {
-      context: serverResources,
+      context: serverResources.map(res => `${contextPath}${res}`),
       target: `http${tls ? 's' : ''}://localhost:8080`,
       secure: false,
       changeOrigin: tls,
```

**Comment by mshima** [comment] 2023-08-15 01:22
Generate an application with context-path with current main and local-blueprints samples:
```
git init
git submodule add https://github.com/mshima/local-blueprints.git .blueprint
jhipster --enable-local-blueprint context-path --defaults --skip-jhipster-dependencies
```

Set the context-path at the prompt and start the server.

**Closed** 2023-08-16 22:54 UTC
Labels: area: feature request :bulb:, $$ bug-bounty $$, $200

**Comment by jperezdelafuente** [comment] 2023-08-17 07:17
@mshima I think e2e tests should use the context path

**Comment by mshima** [comment] 2023-08-17 10:53
@jperezdelafuente do you mean cypress or CI integration tests?

**Comment by jperezdelafuente** [comment] 2023-08-17 11:00
@mshima I mean maybe Cypress e2e tests should be adjusted with custom context path

**Comment by mshima** [comment] 2023-08-17 11:10
Ok, AFAIK you just need to adjust the baseUrl:
https://github.com/jhipster/generator-jhipster/blob/fc1bc30d03d1ccba459bfd904cb781b34cf1ab13/generators/cypress/templates/cypress.config.ts.ejs#L50

**Comment by mshima** [comment] 2023-08-17 23:27
The local blueprint has cypress adjusts now.

**Comment by jperezdelafuente** [comment] 2023-08-22 08:35
Additional issue: 
Browsersync not working properly with context path http://localhost:9000/geiser/
![image](https://github.com/jhipster/generator-jhipster/assets/9991172/726b7083-8797-4f14-b47d-d74f7796d17c)

**Comment by levilliard** [comment] 2023-09-18 20:36
The problem is still present in version 8.0.00beta.3

**Comment by mshima** [comment] 2023-09-28 21:43
@levilliard this feature is not officially supported.
It's documentation only https://www.jhipster.tech/production/#custom-context-path.
You can try to use the local blueprint https://github.com/mshima/local-blueprints/blob/main/app/context-path.mjs.

**Comment by mshima** [comment] 2023-09-28 21:44
@DanielFran bounty claimed https://opencollective.com/generator-jhipster/expenses/163436.

**Comment by DanielFran** [comment] 2023-09-28 21:53
@mshima approved
