### ISSUE TITLE
a suggestion of release plan

### ISSUE THREAD

**Issue by yudar1024** [jhipster/generator-jhipster#9466] opened 2019-03-22 01:39 UTC
##### **Overview of the feature request**

jhipster is greate and the release of major version can be more agile. Jhipster is consist of many subproject, and not all person need them all. for example , we just need maven and angular version. do not need gradle and react version. so we hope if maven and angluar version is ready to release , we can use new major version as soon as possible. don't need to wait gradle version ready. One step closer to agile , if possbile , only just upgrade a main dependency, can be release a version. For example , from 5.8.2,  when finish spring cloud and spring boot upgrade, can release a server side only version.  please consider the sugguestion of release plan.

thank you very much for the great work.

##### **Related issues or PR**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by PierreBesson** [comment] 2019-03-22 08:12
Hi @yudar1024,
I understand your idea, the problem is that the different parts are highly dependent from each other, for example if you update a back-end endpoint, you have to adapt the front-end client (just to give a simple example, some dependencies are more complex).

If the generated application was just a hello-world then what you say would be easy. However a typical applications is 40K lines of code. So the generator code is very monolithic in its approach which allows us to test that all components work well with each other. 

As a now, JHipster is actually a way to maintain a great variety of possible applications. The main problem is that we maintain too many options (see https://dev.azure.com/hipster-labs/jhipster-daily-builds/_dashboards/dashboard/838f7bd8-7cb5-4bad-a47d-362df39abb27).
We do a poor job of communicating what are the blockers for the current release, I'm sorry about that. Please be patient.

**Comment by pascalgrimaud** [comment] 2019-03-22 09:13
@yudar1024 :
- I'm considered by the team as the DevOps
- I'm taking the responsability for the current workflow of release
- I know a lot of people would like more frequent release, more quality, and we would like too !
- I have in mind a new release process for all of our projects which could improve a lot our current workflow, but I don't have the time to start it :-( I spoke about it, last year at the JHipster conf
- we do it during our personal free time, it's not our job, unfortunately
- hope you understand :-)

Maybe one day, we'll have the bandwitch to do this... Until this, just be patient plz

**Comment by deepu105** [comment] 2019-03-22 11:59
May be we could do more beta releases. It will make it easier for people
who wants the latest release and cant wait.

Thanks & Regards,
Deepu

**Comment by ganeshkrishnan1** [comment] 2019-03-26 01:03
@pascalgrimaud @deepu105 , I didn't know you guys did this on personal time. Do you mind sharing the release process with the community?
We are a startup the heavily uses jhipster and I would glad to contribute or even ask our devs to contribute.

**Comment by jdubois** [comment] 2019-03-26 08:33
I'm currently doing it on the Paris subway while community!
Less Candy Crush, more GitHub :-)

**Comment by pascalgrimaud** [comment] 2019-03-31 08:56
@ganeshkrishnan1 :

About the release process, done by Julien manually:
- release of ng-jhipster, react-jhipster, jhipster-core
- release of jhipster lib and wait for availability
- for generator-jhipster, tag, npm publish 
- release of all sample projects, using jhipster-automated-samples project
- release and publish new devbox image
- write release note, merge pending PR and release jhipster.github.io for jhipster.tech site
- twitter :)

There are some part which can be done by our CI.
We already use our CI for:
- all Docker images : https://hub.docker.com/u/jhipster
- Sonar analysis: https://sonarcloud.io/dashboard?id=io.github.jhipster.sample%3Ajhipster-sample-application

The main problem why we didn't release a new version is we need help to solve some important tickets.
You can see some broken configs:
- JDK11 + Infinispan
- JDK11 + UAA
You can help testing PR like Kubernetes, or improving our docs.

Help is really welcome in all forms!

**Comment by pascalgrimaud** [comment] 2019-03-31 08:59
I'm closing this ticket as it will be a continuous improvement on our side.
But we can continue to discuss here.

**Closed by pascalgrimaud** 2019-03-31 08:59 UTC
Labels: enhancement
