### ISSUE TITLE
Use enumeration for field type

### ISSUE THREAD

**Issue by leleuj** [jhipster/generator-jhipster#1376] opened 2015-04-13 14:28 UTC
Hi,

I'm trying to migrate my old CRUD webapps (in Grails) using Jhipster. I had several fields in my entities which are Java enumerations.

I can't define them using the command line: `yo jhipster:entity MyEntity`.
I guess it would be great to be able to define the type field by a custom class or at least by an enumeration.

Nonetheless, I successfully changed my `.jhipster/MyEntity.json` file to define directly this enumeration (in the `"fieldType"`) but the generation is not fully correct. Tests are not properly generated and the `myentity-detail.html` view has only a text input for my field. A list of options would be necessary.

What do you think ? I'm willing to work a PR for that.

Best regards,
Jérôme

**Comment by jdubois** [comment] 2015-04-13 14:31
Hi @leleuj we don't support enumerations, but that's just because I lack time to implement it... If you are willing to do a PR, you are more than welcome!
Be careful, as we normally also support MongoDB and Cassandra -> if you don't know how to model those, people can help here (at least I could help for Cassandra), or you can just do a switch in the template so that enumerations only work on JPA (better start with JPA, and then improve it later!).

**Comment by leleuj** [comment] 2015-04-13 14:50
I'm using MongoDB. I'll check again but I'm pretty sure that defining a field as an enumeration was sufficient for the mapping to work.

For JPA, I guess that `@Enumerated(EnumType.STRING)` is the right annotation to use, isn't it?

It seems the same annotation exists for Cassandra as well: http://www.datastax.com/drivers/java/2.1/com/datastax/driver/mapping/annotations/Enumerated.html.

**Comment by jdubois** [comment] 2015-04-13 14:53
- For Cassandra the problem is that we currently use version 2.0, as 2.1 is not ready for production (we follow Datastax Enterprise versions here, as we want our users to be able to use it - mainly because I'm a user myself!!!!) -> don't worry too much for this at the moment, let's first have it working for JPA, which is 80% of our users (MongoDB is 15%, Cassandra 5%)
- For JPA I haven't used it myself, but yes I think you are correct

**Comment by alexandrustefan** [comment] 2015-04-14 12:55
I can confirm that `@Enumerated(EnumType.STRING)` is the right one. There is also possible to use the ordinal number, but this is not a good approach as you have to add the new values at the end of your enum, in order to keep the ordinal correct for future values.

**Comment by leleuj** [comment] 2015-04-16 14:36
OK. My only concern is the fact that the yeoman generator runs in javascript and cannot know the values of the Java enum. The only option is to ask the user to define a list of pre-defined values (for the enum and maybe for a String as well).

**Comment by lokkju** [comment] 2015-05-01 23:22
It'd be great if we could be a bit more generic in this, and support any custom field type; even if it was with a warning that you needed to manually edit your tests or views.  I'm currently using MongoDB with nested documents, and entity generation is something of a pain.

**Comment by leleuj** [comment] 2015-05-05 09:22
Yes, I was thinking about this also, but it would be better to only focus this PR on enums and create an additional one to support any custom type.

**Comment by sdoxsee** [comment] 2015-05-08 16:07
Enums +1

**Comment by leleuj** [comment] 2015-05-26 11:55
I'm working on it, things were harder than expected, fixing the last details...

**Comment by leleuj** [comment] 2015-05-26 14:23
Here is the PR : https://github.com/jhipster/generator-jhipster/pull/1531
I made tests, it should be ok but of course I'm looking forward to your feedbacks...

**Comment by benkratz** [comment] 2015-06-18 17:58
Enums +1

**Comment by jdubois** [comment] 2015-06-22 20:28
Merged!

**Closed by jdubois** 2015-06-22 20:28 UTC

**Comment by leleuj** [comment] 2015-06-26 14:23
Great! Thx
