### ISSUE TITLE
Yarn not found in generated Jenkins pipeline file

### ISSUE THREAD

**Issue by terribleherbst** [jhipster/generator-jhipster#5177] opened 2017-02-12 16:09 UTC
##### **Overview of the issue**
I have used the latest JHipster 4 generator to create a simple (monolithic) app, selecting angular 2 and gradle as build system. Although JHipster is really awesome I get the following error when trying to run the generated build pipeline:
```
:npmInstall
> hippo-4@0.0.0 postinstall /var/jenkins_home/workspace/test-pipeline 
> yarn run webpack:build
sh: 1: yarn: not found
```

##### **Motivation for or Use Case**
I am running jenkins 2.32, if a Jenkinsfile is generated it should work out of the box.

##### **Reproduce the error**
To reproduce you should use latests release JHipster version, create a sample project using **gradle** as the build tool and **angular2** lib (all other options can be default). 
Now try to use the generated Jenkinsfile on a jenkins server where no yarn is installed, the build should fail.

##### **JHipster Version(s)**
4.0.2

##### **JHipster configuration**
```yaml
{
  "generator-jhipster": {
    "jhipsterVersion": "4.0.2",
    "baseName": "hippo4",
    "packageName": "de.joergherbst.hippo",
    "packageFolder": "de/joergherbst/hippo",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "buildTool": "gradle",
    "enableSocialSignIn": false,
    "rememberMeKey": "929ff6b80a3a4d1dbc6da49c965aeda3bd7ed2eb",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "clientFramework": "angular2",
    "testFrameworks": [
      "gatling"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "de"
    ]
  }
}
```
##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**
no entity configured

##### **Browsers and Operating System**

Cause this is not an UI issue there is no browser dependency.

**Comment by deepu105** [comment] 2017-02-12 16:12
I'm not sure of that. shouldnt you be installing yarn in your jenkins environment?
I'll leave this open for others to comment cc @gmarziou @pascalgrimaud @cbornet

**Comment by kaidohallik** [comment] 2017-02-12 16:58
It's introduced with my PR #5071  
I reproduced it also with gradle in machine where yarn is not installed and node/npm/yarn are installed locally with -PnodeInstall flag: `gradlew yarn_install -PnodeInstall`  
Fix is to use constant `npm` instead of `<%= clientPackageManager %>` in postInstall in this line https://github.com/jhipster/generator-jhipster/blob/master/generators/client/templates/angular/_package.json#L124  
Currently I try to narrow problem and look for a solution (I will try gradle new node plugin with version 1.1.0).  
If yarn is installed globally then I can't reproduce this problem.

**Comment by terribleherbst** [comment] 2017-02-12 18:41
I guess it should work without a installed yarn in the jenkins environment (thats the purpose of the gradle-node-plugin). 
For reproduction I created a new jenkins server based on docker image. I just push the image, jenkins does a git checkout and starts from scratch on every build. Upgrading to gradle-node-plugin 1.1.0 did not help. 
@kaidohallik Do you think there is a workaround without patching my package.json?

**Comment by kaidohallik** [comment] 2017-02-12 18:50
@terribleherbst Could you try add to build.gradle after line https://github.com/jhipster/generator-jhipster/blob/master/generators/server/templates/_build.gradle#L449 one new line:
* if install phase is executed with: `gradlew npmInstall -PnodeInstall` then:
```
npmInstall.dependsOn npm_install_yarn
```
After that yarn was found in my test machine.

**Comment by pascalgrimaud** [comment] 2017-02-12 19:39
Yes, it should work without installing yarn globally, because it is installed locally:
- maven: [frontend-maven-plugin](https://github.com/jhipster/generator-jhipster/blob/master/generators/server/templates/_pom.xml#L1148-L1150)
- gradle: [gradle-node-plugin](https://github.com/jhipster/generator-jhipster/blob/master/generators/server/templates/_build.gradle#L19)

@terribleherbst : can you test @kaidohallik 's solution?

**Comment by kaidohallik** [comment] 2017-02-12 19:46
With my solution yarn is found, but in the middle of the webpack build I'm getting errors like:
```
ERROR in ./src/main/webapp/content/images/hipster.png
Module build failed: Error: spawn /home/vagrant/projects/jhipster-gradle/node_modules/pngquant-bin/vendor/pngquant ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
 @ ./~/css-loader!./src/main/webapp/app/home/home.css 6:307-350
 @ ./src/main/webapp/app/home/home.css
 @ ./src/main/webapp/app/home/home.component.ts
 @ ./src/main/webapp/app/home/index.ts
 @ ./src/main/webapp/app/app.module.ts
 @ ./src/main/webapp/app/app.main.ts
```
both in Windows and in Ubuntu.

Seems that `yarn run webpack:build` is unstable if running with locally installed yarn.  
Doing some more tests...

**Comment by ruddell** [comment] 2017-02-12 20:29
@kaidohallik I get that every time I try to build for prod on my Mac.  I fix it by adding the following commands to my `postinstall` step:
```
node node_modules/pngquant-bin/lib/install.js && node node_modules/phantomjs-prebuilt/install.js
```
Maybe this should be part of the generated code?

**Comment by terribleherbst** [comment] 2017-02-12 22:41
The solution of @kaidohallik seems to work, it installs yarn but I get problems after that. Webpack seems to be a little bit unstable. 
Now my frontend tests fail with:
``` 
[test-pipeline] Running shell script
+ ./gradlew gulp_test -PnodeInstall
FAILURE: Build failed with an exception.
```
I guess this is unrelated and an angular 2 should not create a gulp test in the jenkins build file, but I'm not sure if I should open a separate bug.

**Comment by pascalgrimaud** [comment] 2017-02-12 22:53
@terribleherbst : in fact, I thought that the Jenkinsfile was updated for Angular2, but it's not!
Maybe keep this ticket and rename to something: Jenkinsfile pipeline for NG2 ?

**Comment by kaidohallik** [comment] 2017-02-13 04:00
@ruddell Your solution worked for me if I built in clean environment. If some previous errors occurred and breaked environment then this solution also failed. Seems that there is some yarn and/or webpack unstabilty which can break builds so hard that after changing source code and rerun error stays. Needs new build to overcome.  
I tested in:
* Jenkins 2.45
* Docker 1.12.6
* Centos 7.3

@terribleherbst To get frontend test working change `gulp_test` to `yarn_test`.
To get packaging working remove in `profile_prod.gradle` this phrase from webpack task:  
`, dependsOn: 'yarn_install'`

@pascalgrimaud Yes Jenkinsfile needs update.

**Comment by cbornet** [comment] 2017-02-14 21:39
Indeed the jenkinsfile hasn't been updated for ng2. And neither the ci-cd subgen

**Comment by jdubois** [comment] 2017-02-15 12:55
Closing this as this will be done in #5188

**Closed by jdubois** 2017-02-15 12:55 UTC

**Comment by pascalgrimaud** [comment] 2018-05-30 11:45
@rakeshnambiar : it depends on your config, how you got your Jenkinsfile. Manually or generated with JHipster? etc. As you don't provide information, it's really hard to help you.

About your Jenkinsfile: 
- Manually: if you use directly `yarn install`, you need to install it
- Generated with JHipster: it will use maven front end plugin, download a local Yarn and use it, so you don't need anything.

**Comment by rakeshnambiar** [comment] 2018-05-30 13:04
Hi, @pascalgrimaud thanks a lot for your reply. I double checked and yarn (1.7.0) is already installed in this system and that's the reason I am not getting any error while executing the bash file manually.

So in the deployment script, I mentioned just 'yarn start' as one of the steps. Do I need to explicitly mention something to execute the shell script file through Jenkins?

**Comment by AllenJol** [comment] 2019-07-12 03:04
我也遇到了Jenkins发布服务的时候提示yarn命令找不到的问题，具体如下：
+ yarn install
/tmp/jenkins9043561108664892070.sh: line 2: yarn: command not found
Build step 'Execute shell' marked build as failure

目前还没找到是因为什么问题！
Jenkins服务是root用户启动的，但是Jenkins里面我是通过ssh 插件进行推送包到远程服务器上的。
麻烦解决掉的朋友帮忙回复一下解决方法,非常感谢
联系邮箱：471733951@qq.com

**Comment by AllenJol** [comment] 2019-07-12 03:51
I have got this problem about: yarn command not find.
Specific as follows：
yarn install
/tmp/jenkins9043561108664892070.sh: line 2: yarn: command not found
Build step 'Execute shell' marked build as failure
The Jenkins service was started by root, but in Jenkins I used the SSH plug-in to push packages to remote servers.

If you have solved the problem, please reply the solution. Thank you very much

Contact email: 471733951@qq.com

**Comment by rakeshnambiar** [comment] 2019-07-12 09:44
@AllenJol I couldn't find any solution to run the `yarn` command either directly through jenkins or through the bash script. However, as a workaround I managed to use the docker commands to make the build something like below.

`docker-compose -f ./docker-compose.yml up --build -d`

**Comment by AllenJol** [comment] 2019-07-12 09:47
Thank you very much for your help. Only I don't allow docker at present, so I can't try this method. I'm looking for other solutions

**Comment by rakeshnambiar** [comment] 2019-07-12 10:01
have you installed the yarn on the machine where you makes the build and export the path to the $PATH?

**Comment by AllenJol** [comment] 2019-07-12 10:07
i hava installed the yarn on the jenkins machine and make sure i have makes the build and export the path to the $PATH
[root@localhost ~]# cat /etc/profile | grep 'yarn'
export PATH=$PATH:/usr/local/bin/yarn
[root@localhost ~]# which yarn
/usr/local/bin/yarn

**Comment by rakeshnambiar** [comment] 2019-07-12 10:13
seems you are on the right way and I hope the build process is happening on the `jenkins master` itself. Can you try something like below in the jenkins `execute shell` before the `yarn` command.

`export PATH=$PATH:/usr/local/bin/yarn`
`which yarn`

**Comment by AllenJol** [comment] 2019-07-12 10:18
ok thanks very much iwill try it later and then tell you the result of my attempt

**Comment by AllenJol** [comment] 2019-07-13 01:14
I tried to export the environment variable before executing the yarn command, but I still had this problem.

+ export PATH=/usr/lib/jvm/java-1.8.0-openjdk/bin:/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/bin/yarn
+ PATH=/usr/lib/jvm/java-1.8.0-openjdk/bin:/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/bin/yarn
+ yarn install
/tmp/jenkins3380906477631719648.sh: line 3: yarn: command not found
Build step 'Execute shell' marked build as failure

**Comment by AllenJol** [comment] 2019-07-13 01:17
I don't know if it's because of openjdk. I will try to uninstall openjdkfirst,and  install Java jdk-1.8, then try again. But I don't think it's likely that this is the case

**Comment by gmarziou** [comment] 2019-07-13 13:48
@AllenJol Could you post your Jenkinsfile here?
