### ISSUE TITLE
Cannot login as uaa/api/account return 401 code

### ISSUE THREAD

**Issue by sunyuyangg555** [jhipster/generator-jhipster#8130] opened 2018-08-21 09:36 UTC
##### **Overview of the issue**

Can not login as http://localhost:9000/uaa/api/account return 401 invalid token.
I did not modify any code after it was automatically generated.
this is my test repo [https://github.com/sunyuyangg555/jiffy](url)

1、 Gateway
##### **JHipster Version(s)**
```
 generator-jhipster@5.2.1
```
##### **JHipster configuration, a `.yo-rc.json` file generated in the root folde

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.jiffy.gateway",
      "nativeLanguage": "zh-cn"
    },
    "jhipsterVersion": "5.2.1",
    "applicationType": "gateway",
    "baseName": "gateway",
    "packageName": "com.jiffy.gateway",
    "packageFolder": "com/jiffy/gateway",
    "serverPort": "8088",
    "authenticationType": "uaa",
    "uaaBaseName": "uaa",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": false,
    "websocket": "spring-websocket",
    "databaseType": "no",
    "devDatabaseType": "no",
    "prodDatabaseType": "no",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "yarn",
    "testFrameworks": [
      "gatling",
      "cucumber"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "zh-cn",
    "languages": [
      "zh-cn",
      "en"
    ]
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in
 the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) Client VM (build 25.144-b01, mixed mode)

git version 2.9.0.windows.1

node: v8.11.1

npm: 5.6.0

yeoman: 2.0.5

yarn: 1.9.4

Docker version 18.03.0-ce, build 0520e24302

docker-compose version 1.20.1, build 5d8c71b2

2、UAA

##### **JHipster Version(s)**

```
 generator-jhipster@5.2.1
```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folde

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.jiffy.uaa",
      "nativeLanguage": "zh-cn"
    },
    "jhipsterVersion": "5.2.1",
    "applicationType": "uaa",
    "baseName": "uaa",
    "packageName": "com.jiffy.uaa",
    "packageFolder": "com/jiffy/uaa",
    "serverPort": "9999",
    "authenticationType": "uaa",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "enableTranslation": true,
    "testFrameworks": [
      "gatling",
      "cucumber"
    ],
    "jhiPrefix": "jhi",
    "clientPackageManager": "yarn",
    "nativeLanguage": "zh-cn",
    "languages": [
      "zh-cn",
      "en"
    ],
    "skipClient": true
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in
 the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) Client VM (build 25.144-b01, mixed mode, sharing)

git version 2.9.0.windows.1

node: v8.11.1

npm: 5.6.0

yeoman: 2.0.5

yarn: 1.9.4

Docker version 18.03.0-ce, build 0520e24302

docker-compose version 1.20.1, build 5d8c71b2

**Comment by jdubois** [comment] 2018-08-21 09:57
Your `.yo-rc.json` is clearly wrong, as you have no database selected -> with no database, quite obviously you won't have a users table, and nothing will work...

I'm closing this because this just doesn't make any sense, and I've just tested with the command line as well as JHipster Online and we don't provide that combination.

How did you get that `.yo-rc.json` file? Did it write it yourself? Maybe we a glitch somewhere which allowed you to have that configuration.

**Closed by jdubois** 2018-08-21 09:57 UTC

**Comment by ruddell** [comment] 2018-08-21 20:43
@jdubois There's no glitch, the gateway in a UAA setup can select `no database`, there are two `.yo-rc.json` files in the main post.

I couldn't reproduce though.  I cloned your project, ran it, and was able to log in. `http://localhost:9000/uaa/api/account` will always return 401 by default until you log in.

**Comment by jdubois** [comment] 2018-08-21 20:52
Of course, thank you so much @ruddell - I didn't notice there were 2 `.yo-rc.json`, and of course I looked at the wrong one!!
And thanks also for your analysis: yes it first returns a 401, that's normal as you are not logged already (that's a comment for readers, not you @ruddell , who obviously knows that very well).
So it's all good!

**Comment by sunyuyangg555** [comment] 2018-08-22 01:16
Thank you very much for your quick reply. I know  it first returns a 401, The problem I am having is after  successful login.
![4hz mt4rosj j7lrdk_ w25](https://user-images.githubusercontent.com/5210372/44436573-85c3d680-a5e8-11e8-86db-20af1c4228fa.png)
The following is the corresponding login success.

![123](https://user-images.githubusercontent.com/5210372/44436679-0b478680-a5e9-11e8-83cc-01db5462d9e8.png)
but failed to get account information

![456](https://user-images.githubusercontent.com/5210372/44436804-c6701f80-a5e9-11e8-8b2b-5a4ffc7bdffc.png)

![22](https://user-images.githubusercontent.com/5210372/44437262-e1439380-a5eb-11e8-8086-64001d7d9dca.png)

I have cleaned up the browser cache and cookies, failure still exists.

The order in which I started the program is: jhipster-register->uaa->gateway
at last I cd gateway dir and  run yarn start.

uaa console is no error
![789](https://user-images.githubusercontent.com/5210372/44437022-b573de00-a5ea-11e8-8765-a3d98bd187b3.png)
 but jhipster-register has a timeour error
![11](https://user-images.githubusercontent.com/5210372/44437085-fff55a80-a5ea-11e8-823a-af9594c0c43c.png)
This error appears after login, before login is ok.
Is there a problem with my environment?

**Comment by ruddell** [comment] 2018-08-22 02:35
I was able to reproduce this by setting the ENV variables for Okta ([from the docs](https://www.jhipster.tech/security/#okta) for that authentication type).  Make sure you don't have any Spring OAuth config variables defined in your environment, you can see with `printenv | grep SECURITY`

**Comment by sunyuyangg555** [comment] 2018-08-22 03:36
Yes, you are right, I do set the ENV variables for Okta! Now, I unset those variables, everything works fine, Thank you very much!
