### ISSUE TITLE
HTML Text Formatting <b> and <strong> don't work in bootswatch theme

### ISSUE THREAD

**Issue by king-il** [jhipster/generator-jhipster#14105] opened 2021-03-01 00:15 UTC
##### **Overview of the issue**

when using bootswatch theme "united "; the ```<b>``` and ```<strong>``` elements don't render bold text. and when i generate an application using the jhipster default theme everything is back to normal.

##### **Motivation for or Use Case**

----------------------------------

##### **Reproduce the error**

------------------------------------

##### **Related issues**

-----------------------------------

##### **Suggest a Fix**

-----------------------------------
##### **JHipster Version(s)**
```
generator-jhipster@6.10.5
```

##### **JHipster configuration**
```
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.filyasse"
    },
    "jhipsterVersion": "6.10.5",
    "applicationType": "monolith",
    "baseName": "jhipster",
    "packageName": "com.filyasse",
    "packageFolder": "com/filyasse",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "embeddableLaunchScript": false,
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "angularX",
    "clientTheme": "united",
    "clientThemeVariant": "dark",
    "creationTimestamp": 1614553582941,
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": false,
    "blueprints": []
  }
}
```

##### **Browsers and Operating System**

WINDOWS 10, FIrefox

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by qmonmert** [comment] 2021-03-04 12:54
@king-il this is not a bug
In the file `node_modules/bootstrap/scss/_reboot.scss` you have:
```
b,
strong {
  font-weight: $font-weight-bolder; // Add the correct font weight in Chrome, Edge, and Safari
}
```
and with your theme `$font-weight-bolder` is equal to `bolder`.
For example, you can override this behaviour adding this code to the end of `src/main/webapp/content/scss/vendor.scss`:
```
b,
strong {
  font-weight: bold;
}
```

**Comment by pascalgrimaud** [comment] 2021-03-04 22:15
as it's not a bug, I'm closing this

**Closed by pascalgrimaud** 2021-03-04 22:15 UTC
Labels: area: needs-reproduction, theme: front
