### ISSUE TITLE
Error: Cannot find module 'workbox-build/build/options/schema/webpack-generate-sw'

### ISSUE THREAD

**Issue by indiepopart** [jhipster/generator-jhipster#16901] opened 2021-11-03 12:56 UTC
##### **Overview of the issue**

I get an error when building the gateway generated by JHipster with Maven:

```
[INFO] > gateway@0.0.0 webpack
[INFO] > node --max_old_space_size=4096 node_modules/webpack/bin/webpack.js "--config" "webpack/webpack.prod.js" "--progress=profile" "--env" "stats=minimal"
[INFO] 
[INFO] [webpack-cli] Failed to load '/home/indiepopart/Documents/toptal/okta/assignments/spring-data-elastic/workspace/jhipster2/gateway/webpack/webpack.prod.js' config
[INFO] [webpack-cli] Error: Cannot find module 'workbox-build/build/options/schema/webpack-generate-sw'
[INFO] Require stack:
[INFO] - /home/indiepopart/Documents/toptal/okta/assignments/spring-data-elastic/workspace/jhipster2/gateway/node_modules/workbox-webpack-plugin/build/generate-sw.js
[INFO] - /home/indiepopart/Documents/toptal/okta/assignments/spring-data-elastic/workspace/jhipster2/gateway/node_modules/workbox-webpack-plugin/build/index.js
[INFO] - /home/indiepopart/Documents/toptal/okta/assignments/spring-data-elastic/workspace/jhipster2/gateway/webpack/webpack.prod.js
[INFO] - /home/indiepopart/Documents/toptal/okta/assignments/spring-data-elastic/workspace/jhipster2/gateway/node_modules/webpack-cli/lib/webpack-cli.js
[INFO] - /home/indiepopart/Documents/toptal/okta/assignments/spring-data-elastic/workspace/jhipster2/gateway/node_modules/webpack-cli/lib/bootstrap.js
[INFO] - /home/indiepopart/Documents/toptal/okta/assignments/spring-data-elastic/workspace/jhipster2/gateway/node_modules/webpack-cli/bin/cli.js
[INFO] - /home/indiepopart/Documents/toptal/okta/assignments/spring-data-elastic/workspace/jhipster2/gateway/node_modules/webpack/bin/webpack.js
[INFO]     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
[INFO]     at Function.Module._load (internal/modules/cjs/loader.js:725:27)
[INFO]     at Module.require (internal/modules/cjs/loader.js:952:19)
[INFO]     at require (/home/indiepopart/Documents/toptal/okta/assignments/spring-data-elastic/workspace/jhipster2/gateway/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
[INFO]     at Object.<anonymous> (/home/indiepopart/Documents/toptal/okta/assignments/spring-data-elastic/workspace/jhipster2/gateway/node_modules/workbox-webpack-plugin/build/generate-sw.js:20:33)
[INFO]     at Module._compile (/home/indiepopart/Documents/toptal/okta/assignments/spring-data-elastic/workspace/jhipster2/gateway/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
[INFO]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
[INFO]     at Module.load (internal/modules/cjs/loader.js:928:32)
[INFO]     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
[INFO]     at Module.require (internal/modules/cjs/loader.js:952:19)
[INFO]     at require (/home/indiepopart/Documents/toptal/okta/assignments/spring-data-elastic/workspace/jhipster2/gateway/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
[INFO]     at Object.<anonymous> (/home/indiepopart/Documents/toptal/okta/assignments/spring-data-elastic/workspace/jhipster2/gateway/node_modules/workbox-webpack-plugin/build/index.js:10:20)
[INFO]     at Module._compile (/home/indiepopart/Documents/toptal/okta/assignments/spring-data-elastic/workspace/jhipster2/gateway/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
[INFO]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
[INFO]     at Module.load (internal/modules/cjs/loader.js:928:32)
[INFO]     at Function.Module._load (internal/modules/cjs/loader.js:769:14) {
[INFO]   code: 'MODULE_NOT_FOUND',
[INFO]   requireStack: [
[INFO]     '/home/indiepopart/Documents/toptal/okta/assignments/spring-data-elastic/workspace/jhipster2/gateway/node_modules/workbox-webpack-plugin/build/generate-sw.js',
[INFO]     '/home/indiepopart/Documents/toptal/okta/assignments/spring-data-elastic/workspace/jhipster2/gateway/node_modules/workbox-webpack-plugin/build/index.js',
[INFO]     '/home/indiepopart/Documents/toptal/okta/assignments/spring-data-elastic/workspace/jhipster2/gateway/webpack/webpack.prod.js',
[INFO]     '/home/indiepopart/Documents/toptal/okta/assignments/spring-data-elastic/workspace/jhipster2/gateway/node_modules/webpack-cli/lib/webpack-cli.js',
[INFO]     '/home/indiepopart/Documents/toptal/okta/assignments/spring-data-elastic/workspace/jhipster2/gateway/node_modules/webpack-cli/lib/bootstrap.js',
[INFO]     '/home/indiepopart/Documents/toptal/okta/assignments/spring-data-elastic/workspace/jhipster2/gateway/node_modules/webpack-cli/bin/cli.js',
[INFO]     '/home/indiepopart/Documents/toptal/okta/assignments/spring-data-elastic/workspace/jhipster2/gateway/node_modules/webpack/bin/webpack.js'
[INFO]   ]
[INFO] }
[INFO] npm ERR! code 2
[INFO] npm ERR! path /home/indiepopart/Documents/toptal/okta/assignments/spring-data-elastic/workspace/jhipster2/gateway
[INFO] npm ERR! command failed
[INFO] npm ERR! command sh -c node --max_old_space_size=4096 node_modules/webpack/bin/webpack.js "--config" "webpack/webpack.prod.js" "--progress=profile" "--env" "stats=minimal"
[INFO] 
[INFO] npm ERR! A complete log of this run can be found in:
[INFO] npm ERR!     /home/indiepopart/.npm/_logs/2021-11-03T12_18_18_990Z-debug.log
[INFO] npm ERR! code 2
[INFO] npm ERR! path /home/indiepopart/Documents/toptal/okta/assignments/spring-data-elastic/workspace/jhipster2/gateway
[INFO] npm ERR! command failed
[INFO] npm ERR! command sh -c npm run webpack -- --config webpack/webpack.prod.js --progress=profile --env stats=minimal
[INFO] 
[INFO] npm ERR! A complete log of this run can be found in:
[INFO] npm ERR!     /home/indiepopart/.npm/_logs/2021-11-03T12_18_19_025Z-debug.log
[INFO] npm ERR! code 2
[INFO] npm ERR! path /home/indiepopart/Documents/toptal/okta/assignments/spring-data-elastic/workspace/jhipster2/gateway
[INFO] npm ERR! command failed
[INFO] npm ERR! command sh -c npm run clean-www && npm run webapp:build:prod
[INFO] 
[INFO] npm ERR! A complete log of this run can be found in:
[INFO] npm ERR!     /home/indiepopart/.npm/_logs/2021-11-03T12_18_19_043Z-debug.log
```

/home/indiepopart/.npm/_logs/2021-11-03T12_18_19_043Z-debug.log

```
0 verbose cli [
0 verbose cli   '/home/indiepopart/Documents/toptal/okta/assignments/spring-data-elastic/workspace/jhipster2/gateway/target/node/node',
0 verbose cli   '/home/indiepopart/Documents/toptal/okta/assignments/spring-data-elastic/workspace/jhipster2/gateway/target/node/node_modules/npm/bin/npm-cli.js',
0 verbose cli   'run',
0 verbose cli   'webapp:prod'
0 verbose cli ]
1 info using npm@7.6.3
2 info using node@v14.16.0
3 timing config:load:defaults Completed in 2ms
4 timing config:load:file:/home/indiepopart/Documents/toptal/okta/assignments/spring-data-elastic/workspace/jhipster2/gateway/target/node/node_modules/npm/npmrc Completed in 1ms
5 timing config:load:builtin Completed in 1ms
6 timing config:load:cli Completed in 2ms
7 timing config:load:env Completed in 2ms
8 timing config:load:file:/home/indiepopart/Documents/toptal/okta/assignments/spring-data-elastic/workspace/jhipster2/gateway/.npmrc Completed in 2ms
9 timing config:load:project Completed in 7ms
10 timing config:load:file:/home/indiepopart/.npmrc Completed in 0ms
11 timing config:load:user Completed in 0ms
12 timing config:load:file:/home/indiepopart/Documents/toptal/okta/assignments/spring-data-elastic/workspace/jhipster2/gateway/target/etc/npmrc Completed in 0ms
13 timing config:load:global Completed in 0ms
14 timing config:load:cafile Completed in 0ms
15 timing config:load:validate Completed in 1ms
16 timing config:load:setUserAgent Completed in 0ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 17ms
19 verbose npm-session 39b913aa1ed48fc5
20 timing npm:load Completed in 23ms
21 timing command:run Completed in 3727ms
22 verbose stack Error: command failed
22 verbose stack     at ChildProcess.<anonymous> (/home/indiepopart/Documents/toptal/okta/assignments/spring-data-elastic/workspace/jhipster2/gateway/target/node/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:64:27)
22 verbose stack     at ChildProcess.emit (events.js:315:20)
22 verbose stack     at maybeClose (internal/child_process.js:1048:16)
22 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
23 verbose pkgid gateway@0.0.0
24 verbose cwd /home/indiepopart/Documents/toptal/okta/assignments/spring-data-elastic/workspace/jhipster2/gateway
25 verbose Linux 4.4.0-210-generic
26 verbose argv "/home/indiepopart/Documents/toptal/okta/assignments/spring-data-elastic/workspace/jhipster2/gateway/target/node/node" "/home/indiepopart/Documents/toptal/okta/assignments/spring-data-elastic/workspace/jhipster2/gateway/target/node/node_modules/npm/bin/npm-cli.js" "run" "webapp:prod"
27 verbose node v14.16.0
28 verbose npm  v7.6.3
29 error code 2
30 error path /home/indiepopart/Documents/toptal/okta/assignments/spring-data-elastic/workspace/jhipster2/gateway
31 error command failed
32 error command sh -c npm run clean-www && npm run webapp:build:prod
33 verbose exit 2
```

##### **Reproduce the error**

JDL provided below

```shell
jhipster jdl blog-reactive-ms.jdl
cd gateway
./mvnw package -Pprod verify jib:dockerBuild
```

##### **Related issues**

[Similar issue in StackOverflow](https://stackoverflow.com/questions/68738746/i-get-an-error-when-trying-to-build-a-docker-image-for-my-jhipster-7-1-0-gateway)

##### **Suggest a Fix**

I updated the version of `workbox-webpack-plugin` as suggested in the internet

```
"workbox-webpack-plugin": "6.2.4"
```

##### **JHipster Version(s)**

```
INFO! Using JHipster version installed locally in current project's node_modules
7.0.0
```

##### **JHipster configuration**

  <details>
  <summary>JDL definitions</summary>
  <pre>
application {
  config {
    baseName gateway
    reactive true
    packageName com.okta.developer.gateway
    applicationType gateway
    authenticationType oauth2
    buildTool maven
    clientFramework vue
    prodDatabaseType postgresql
    serviceDiscoveryType eureka
    testFrameworks [cypress]
  }
  entities Blog, Post, Tag
}
application {
  config {
    baseName blog
    reactive true
    packageName com.okta.developer.blog
    applicationType microservice
    authenticationType oauth2
    buildTool maven
    databaseType mongodb
    devDatabaseType mongodb
    prodDatabaseType mongodb
    enableHibernateCache false
    serverPort 8081
    serviceDiscoveryType eureka
    searchEngine elasticsearch
  }
  entities Blog, Post, Tag
}
entity Blog {
  name String required minlength(3)
  handle String required minlength(2)
}
entity Post {
  title String required
  content TextBlob required
  date Instant required
}
entity Tag {
  name String required minlength(2)
}
relationship ManyToOne {
  Blog{user(login)} to User
  Post{blog(name)} to Blog
}
relationship ManyToMany {
  Post{tag(name)} to Tag{post}
}
paginate Post, Tag with infinite-scroll
microservice Blog, Post, Tag with blog
deployment {
  deploymentType docker-compose
  appsFolders [gateway, blog]
  dockerRepositoryName "jgarbarino"
}
  </pre>
  </details>

##### **Browsers and Operating System**

Ubuntu 16.04.7 LTS

- [ x] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment] 2021-11-12 00:47
Already fixed.
Duplicate of https://github.com/jhipster/generator-jhipster/issues/16173 and https://github.com/jhipster/generator-jhipster/issues/15884

**Closed by mshima** 2021-11-12 00:47 UTC
Labels: area: triage, theme: undefined
