### ISSUE TITLE
Running integration tests fails with Cannot cast org.h2.Driver to javax.sql.DataSource

### ISSUE THREAD

**Issue by dscowan** [jhipster/generator-jhipster#3075] opened 2016-03-04 03:52 UTC
##### **Overview of the issue**
Running integration tests via gradlew test or eclipse fails with Cannot cast org.h2.Driver to javax.sql.DataSource.

`Caused by: java.lang.RuntimeException: java.lang.ClassCastException: Cannot cast org.h2.Driver to javax.sql.DataSource
	at com.zaxxer.hikari.util.UtilityElf.createInstance(UtilityElf.java:79) ~[HikariCP-2.4.1.jar:na]
	at com.zaxxer.hikari.pool.PoolElf.initializeDataSource(PoolElf.java:153) ~[HikariCP-2.4.1.jar:na]
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:113) ~[HikariCP-2.4.1.jar:na]
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:73) ~[HikariCP-2.4.1.jar:na]
	at com.nxtgen.app.config.DatabaseConfiguration.dataSource(DatabaseConfiguration.java:79) ~[bin/:na]
	at com.nxtgen.app.config.DatabaseConfiguration$$EnhancerBySpringCGLIB$$b5ccc050.CGLIB$dataSource$1(<generated>) ~[bin/:na]
	at com.nxtgen.app.config.DatabaseConfiguration$$EnhancerBySpringCGLIB$$b5ccc050$$FastClassBySpringCGLIB$$b497485d.invoke(<generated>) ~[bin/:na]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228) ~[spring-core-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:355) ~[spring-context-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at com.nxtgen.app.config.DatabaseConfiguration$$EnhancerBySpringCGLIB$$b5ccc050.dataSource(<generated>) ~[bin/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_66]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_66]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_66]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_66]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162) ~[spring-beans-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	... 121 common frames omitted
Caused by: java.lang.ClassCastException: Cannot cast org.h2.Driver to javax.sql.DataSource
	at java.lang.Class.cast(Class.java:3369) ~[na:1.8.0_66]
	at com.zaxxer.hikari.util.UtilityElf.createInstance(UtilityElf.java:76) ~[HikariCP-2.4.1.jar:na]
	... 135 common frames omitted`

##### **Motivation for or Use Case** 
Trying to run integration tests

Tried running the integration tests via eclipse to allow debugging and noticed this.  Also ran from gradle and see the same failures.

##### **JHipster Version(s)** 
2.27.1

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 
{
  "generator-jhipster": {
    "baseName": "test",
    "packageName": "com.test.app",
    "packageFolder": "com/test/app",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": "elasticsearch",
    "useSass": false,
    "buildTool": "gradle",
    "frontendBuilder": "grunt",
    "enableTranslation": true,
    "enableSocialSignIn": true,
    "rememberMeKey": "",
    "testFrameworks": [
      "gatling"
    ]
  }
}

**Comment by deepu105** [comment] 2016-03-04 03:54
@cbornet  did you fix this in master? or did someone else work on this

**Comment by cbornet** [comment] 2016-03-04 09:04
The modifications I did on Hikari configuration are not part of v2.x branch so that must be something else.

**Comment by jdubois** [comment] 2016-03-04 15:50
I'm testing this

**Comment by jdubois** [comment] 2016-03-04 17:08
Lost one hour because your rememberme key was empty :-(
And could not reproduce, it just worked out of the box...
Can you try it on the "devbox" with a fresh project, and explain what you did? Because you obviously did something else.
I'm closing this as I could not reproduce.

**Closed by jdubois** 2016-03-04 17:08 UTC

**Comment by dscowan** [comment] 2016-03-05 03:38
Sorry about the rememberme.  That was suggested in the bug posting comments =).   I created a new project to test this and am seeing the same results. Here is the log from project creation

 
        ██  ██    ██  ████████  ███████    ██████  ████████  ████████  ███████
        ██  ██    ██     ██     ██    ██  ██          ██     ██        ██    ██
        ██  ████████     ██     ███████    █████      ██     ██████    ███████
  ██    ██  ██    ██     ██     ██             ██     ██     ██        ██   ██
   ██████   ██    ██  ████████  ██        ██████      ██     ████████  ██    ██

                            http://jhipster.github.io

Welcome to the JHipster Generator v2.27.0

? (1/15) What is the base name of your application? myapp
? (2/15) What is your default Java package name? com.test.app
? (3/15) Which *type* of authentication would you like to use? HTTP Session Authentication (stateful, default Spring 
Security mechanism)
? (4/15) Which *type* of database would you like to use? SQL (H2, MySQL, PostgreSQL, Oracle)
? (5/15) Which *production* database would you like to use? MySQL
? (6/15) Which *development* database would you like to use? MySQL
? (7/15) Do you want to use Hibernate 2nd level cache? Yes, with ehcache (local cache, for a single node)
? (8/15) Do you want to use a search engine in your application? Yes, with ElasticSearch
? (9/15) Do you want to use clustered HTTP sessions? No
? (10/15) Do you want to use WebSockets? Yes, with Spring Websocket
? (11/15) Would you like to use Maven or Gradle for building the backend? Gradle
? (12/15) Would you like to use Grunt or Gulp.js for building the frontend? Grunt (recommended)
? (13/15) Would you like to use the LibSass stylesheet preprocessor for your CSS? No
? (14/15) Would you like to enable translation support with Angular Translate? Yes
? (15/15) Which testing frameworks would you like to use? Gatling

I did this then opened the project in eclipse and tried to run the UserServiceIntTest

I see this error.

Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.sql.DataSource]: Factory method 'dataSource' threw exception; nested exception is java.lang.RuntimeException: java.lang.ClassCastException: Cannot cast org.h2.Driver to javax.sql.DataSource
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:189) ~[spring-beans-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588) ~[spring-beans-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	... 120 common frames omitted
Caused by: java.lang.RuntimeException: java.lang.ClassCastException: Cannot cast org.h2.Driver to javax.sql.DataSource
	at com.zaxxer.hikari.util.UtilityElf.createInstance(UtilityElf.java:79) ~[HikariCP-2.4.1.jar:na]
	at com.zaxxer.hikari.pool.PoolElf.initializeDataSource(PoolElf.java:153) ~[HikariCP-2.4.1.jar:na]
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:113) ~[HikariCP-2.4.1.jar:na]
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:73) ~[HikariCP-2.4.1.jar:na]
	at com.test.app.config.DatabaseConfiguration.dataSource(DatabaseConfiguration.java:79) ~[bin/:na]
	at com.test.app.config.DatabaseConfiguration$$EnhancerBySpringCGLIB$$9d4739e5.CGLIB$dataSource$0(<generated>) ~[bin/:na]
	at com.test.app.config.DatabaseConfiguration$$EnhancerBySpringCGLIB$$9d4739e5$$FastClassBySpringCGLIB$$a43465b2.invoke(<generated>) ~[bin/:na]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228) ~[spring-core-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:355) ~[spring-context-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at com.test.app.config.DatabaseConfiguration$$EnhancerBySpringCGLIB$$9d4739e5.dataSource(<generated>) ~[bin/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_66]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_66]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_66]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_66]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162) ~[spring-beans-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	... 121 common frames omitted
Caused by: java.lang.ClassCastException: Cannot cast org.h2.Driver to javax.sql.DataSource
	at java.lang.Class.cast(Class.java:3369) ~[na:1.8.0_66]
	at com.zaxxer.hikari.util.UtilityElf.createInstance(UtilityElf.java:76) ~[HikariCP-2.4.1.jar:na]
	... 135 common frames omitted

**Comment by dscowan** [comment] 2016-03-05 03:41
I also see the same doing ./gradlew test

**Comment by jdubois** [comment] 2016-03-05 08:22
Oh for the rememberme key it was me being stupid, I should have spotted this earlier!
I don't know what to do with your issue as I can't reproduce it... Are you using a specific Java version, what is your OS?

**Comment by cbornet** [comment] 2016-03-05 08:40
@dscowan are you sure that you're using the tagged generator : you say you use 2.27.1 but in your logs it's 2.27.0

**Comment by dscowan** [comment] 2016-03-08 01:43
Yes.  The original log was generated on a windows machine.  I then tried it on my mac book which still had 2.27.0 on it for this log that was generated above.  Same result on both.

**Comment by dpalita** [comment] 2016-03-08 17:22
I haven't had time to investigate, but I got this error when I tried to run my app with IntelliJ 16 EAP (it runs fine with IntelliJ 15 or via command line).
There is also a new inspection checking spring boot configuration that reports the same error : org.h2.jdbcx.JdbcDataSource is not assignable to java.sql.Driver
Last thing I noticed using the new auto-completion in spring boot configuration files is that there is a data-source-class-name property... don't know if it could be used instead.

**Comment by deepu105** [comment] 2016-03-09 00:10
@cbornet could this be related to the xhanges you made for auto identification of DB from url?

**Comment by deepu105** [comment] 2016-03-09 00:11
Oops sorry i guess you answered that already

**Comment by dscowan** [comment] 2016-03-11 13:25
I just updated jhipster to 2.27.2 and generated a new app. I am still seeing the same issue.  I am generating the app and then loading it in eclipse mars R2.   I then attempted to run UserServiceIntTest and get the same cannot cast error

Caused by: java.lang.ClassCastException: Cannot cast org.h2.Driver to javax.sql.DataSource
	at java.lang.Class.cast(Class.java:3369) ~[na:1.8.0_66]
	at com.zaxxer.hikari.util.UtilityElf.createInstance(UtilityElf.java:76) ~[HikariCP-2.4.1.jar:na]
	... 74 common frames omitted

**Comment by dscowan** [comment] 2016-03-11 18:40
I believe I might have narrowed this down.  I generated a new app using maven and had no issues.  Then went back to my gradle version and it failed.  It appears the app/src/test/resources/config/application.yml is not being loaded in the gradle version.  This causes the datasource to be incorrectly configured.  Not exactly sure why this is though yet.

**Comment by dpalita** [comment] 2016-03-18 15:43
In my case (IntelliJ 2016.1 loading an IntelliJ 15 project) it was because IntelliJ changed the way they handle gradle project and they need to be reimported (at least to get the classpath right).
It is now working fine, the problem was that build/resource/main was not on the classpath.

**Comment by SimonKlausLudwig** [comment] 2016-04-14 19:10
I had the same issue with intelliJ IDEA 16. I've opened the project in IDEA 14 and started the tests, after this run the tests works also in IntelliJIdea 16.

Sorry if this is the wrong place for this. But i think it could help some people..
