### ISSUE TITLE
Error while adding new entity with relationship

### ISSUE THREAD

**Issue by ravikalla** [jhipster/generator-jhipster#11595] opened 2020-04-19 04:19 UTC
##### **Overview of the issue**
I tried to create an entity named 'box' with below command -
`jhipster entity box`

I tried to add many-to-one relationship with another entity (names as 'fileinfo') for 'box' entity

This is the error -
`ERROR! TypeError: Cannot read property 'toLowerCase' of undefined`

Detailed Entity Generation Info:
```
================= Box =================
Fields
x1 (Integer) 

Relationships
fileinfo (Fileinfo) many-to-one 

? Do you want to use separate service class for your business logic? No, the REST controller should use the repository directly
? Is this entity read-only? No
? Do you want pagination on your entity? No

Everything is configured, generating the entity...

ERROR! TypeError: Cannot read property 'toLowerCase' of undefined
```
##### **Motivation for or Use Case**

I cant create a new Entity with relationship to other entity

##### **Reproduce the error**

Download the code from this Git link - https://github.com/ravikalla/pdf-editor-solution
Try to create a new entity (named "box") and add many-to-one relationship to "fileinfo" entity
Below is the Entity info when I tried to generate -
```
================= Box =================
Fields
x1 (Integer) 

Relationships
fileinfo (Fileinfo) many-to-one 

? Do you want to use separate service class for your business logic? No, the REST controller should use the repository directly
? Is this entity read-only? No
? Do you want pagination on your entity? No

Everything is configured, generating the entity...

ERROR! TypeError: Cannot read property 'toLowerCase' of undefined
```

##### **JHipster Version(s)**

```
pdfeditor@0.0.1-SNAPSHOT /Users/ravi_kalla/Desktop/Projects/pdf-editor-solution/pdf-editor-solution
└── generator-jhipster@6.8.0 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "in.ravikalla.pdfeditor",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "6.8.0",
    "applicationType": "monolith",
    "baseName": "pdfeditor",
    "packageName": "in.ravikalla.pdfeditor",
    "packageFolder": "in/ravikalla/pdfeditor",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSwaggerCodegen": true,
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "embeddableLaunchScript": false,
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "angularX",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "creationTimestamp": 1587261542241,
    "testFrameworks": ["gatling", "cucumber", "protractor"],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": ["en", "fr", "es", "te"],
    "blueprints": []
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Fileinfo {
  file AnyBlob required,
  uploaddate ZonedDateTime required,
  notes String,
  filetype FileType
}
enum FileType {
  PDF,
  JPEG,
  GIF
}

relationship ManyToOne {
  Fileinfo{user(login) required} to User
}

dto Fileinfo with mapstruct
paginate Fileinfo with pagination
service Fileinfo with serviceClass
filter Fileinfo

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)
git version 2.14.1
node: v12.14.1
npm: 6.13.7
yeoman: 3.1.1
yarn: 1.21.1
Docker version 19.03.5, build 633a0ea
docker-compose version 1.24.1, build 4667896b

##### **Browsers and Operating System**

OS: MacOS Catalina
Version: 10.15.3
Browser: Not Applicable for this scenario

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by SudharakaP** [comment] 2020-04-19 04:51
@ravikalla : Unfortunately I wasn't able to recreate your error. Can you give us some more information. Maybe the exact questions and answers you submitted when you ran the entity sub-generator? 

One thing I noticed is that your output has something called `x1 (Integer)`. I am not sure how this is displayed there; because the name of the entity is `box` not `x1`. Anyways the output I got is attached below. 

<details>
<summary>Console Output</summary>
<pre><font color="#8AE234"><b>INFO!</b></font> Using JHipster version installed globally
<font color="#8AE234"><b>INFO!</b></font> <font color="#C4A000">Executing jhipster:entity box</font>
<font color="#8AE234"><b>INFO!</b></font> <font color="#C4A000">Options: from-cli: true</font>

The entity box is being created.


<font color="#4E9A06">Generating field #1</font>

<font color="#4E9A06">?</font> <b>Do you want to add a field to your entity?</b> <font color="#06989A">Yes</font>
<font color="#4E9A06">?</font> <b>What is the name of your field?</b> <font color="#06989A">box</font>
<font color="#4E9A06">?</font> <b>What is the type of your field?</b> <font color="#06989A">Integer</font>
<font color="#4E9A06">?</font> <b>Do you want to add validation rules to your field?</b> <font color="#06989A">No</font>

<font color="#D3D7CF">================= </font><font color="#CC0000">Box</font><font color="#D3D7CF"> =================</font>
<font color="#D3D7CF">Fields</font>
<font color="#CC0000">box</font><font color="#D3D7CF"> (Integer) </font>


<font color="#4E9A06">Generating field #2</font>

<font color="#4E9A06">?</font> <b>Do you want to add a field to your entity?</b> <font color="#06989A">No</font>

<font color="#D3D7CF">================= </font><font color="#CC0000">Box</font><font color="#D3D7CF"> =================</font>
<font color="#D3D7CF">Fields</font>
<font color="#CC0000">box</font><font color="#D3D7CF"> (Integer) </font>


<font color="#4E9A06">Generating relationships to other entities</font>

<font color="#4E9A06">?</font> <b>Do you want to add a relationship to another entity?</b> <font color="#06989A">Yes</font>
<font color="#4E9A06">?</font> <b>What is the name of the other entity?</b> <font color="#06989A">fileinfo</font>
<font color="#4E9A06">?</font> <b>What is the name of the relationship?</b> <font color="#06989A">fileinfo</font>
<font color="#4E9A06">?</font> <b>What is the type of the relationship?</b> <font color="#06989A">many-to-one</font>
<font color="#4E9A06">?</font> <b>When you display this relationship on client-side, which field from &apos;fileinfo&apos; do you want to use? This</b>
<b> field will be displayed as a String, so it cannot be a Blob</b> <font color="#06989A">id</font>
<font color="#4E9A06">?</font> <b>Do you want to add any validation rules to this relationship?</b> <font color="#06989A">No</font>

<font color="#D3D7CF">================= </font><font color="#CC0000">Box</font><font color="#D3D7CF"> =================</font>
<font color="#D3D7CF">Fields</font>
<font color="#CC0000">box</font><font color="#D3D7CF"> (Integer) </font>

<font color="#D3D7CF">Relationships</font>
<font color="#CC0000">fileinfo</font> <font color="#D3D7CF">(Fileinfo)</font> <font color="#06989A">many-to-one</font> 


<font color="#4E9A06">Generating relationships to other entities</font>

<font color="#4E9A06">?</font> <b>Do you want to add a relationship to another entity?</b> <font color="#06989A">No</font>

<font color="#D3D7CF">================= </font><font color="#CC0000">Box</font><font color="#D3D7CF"> =================</font>
<font color="#D3D7CF">Fields</font>
<font color="#CC0000">box</font><font color="#D3D7CF"> (Integer) </font>

<font color="#D3D7CF">Relationships</font>
<font color="#CC0000">fileinfo</font> <font color="#D3D7CF">(Fileinfo)</font> <font color="#06989A">many-to-one</font> 



<font color="#4E9A06">?</font> <b>Do you want to use separate service class for your business logic?</b> <font color="#06989A">No, the REST controller should use t</font>
<font color="#06989A">he repository directly</font>
<font color="#4E9A06">?</font> <b>Is this entity read-only?</b> <font color="#06989A">No</font>
<font color="#4E9A06">?</font> <b>Do you want pagination on your entity?</b> <font color="#06989A">No</font>

<font color="#4E9A06">Everything is configured, generating the entity...</font>

<font color="#C4A000">    force</font> ../../../.yo-rc-global.json
<font color="#4E9A06">   create</font> src/main/resources/config/liquibase/changelog/20200419044205_added_entity_Box.xml
<font color="#4E9A06">   create</font> src/main/resources/config/liquibase/changelog/20200419044205_added_entity_constraints_Box.xml
<font color="#4E9A06">   create</font> src/main/resources/config/liquibase/fake-data/box.csv
<font color="#4E9A06">   create</font> src/main/java/in/ravikalla/pdfeditor/domain/Box.java
<font color="#4E9A06">   create</font> src/main/java/in/ravikalla/pdfeditor/web/rest/BoxResource.java
<font color="#4E9A06">   create</font> src/main/java/in/ravikalla/pdfeditor/repository/BoxRepository.java
<font color="#4E9A06">   create</font> src/test/java/in/ravikalla/pdfeditor/web/rest/BoxResourceIT.java
<font color="#4E9A06">   create</font> src/test/gatling/user-files/simulations/BoxGatlingTest.scala
<font color="#4E9A06">   create</font> src/test/java/in/ravikalla/pdfeditor/domain/BoxTest.java
<font color="#CC0000"> conflict</font> src/main/resources/config/liquibase/master.xml
<font color="#4E9A06">?</font> <b>Overwrite src/main/resources/config/liquibase/master.xml?</b> <font color="#06989A">overwrite this and all others</font>
<font color="#C4A000">    force</font> src/main/resources/config/liquibase/master.xml
<font color="#C4A000">    force</font> src/main/java/in/ravikalla/pdfeditor/config/CacheConfiguration.java
<font color="#4E9A06">   create</font> src/main/webapp/app/entities/box/box.component.html
<font color="#4E9A06">   create</font> src/main/webapp/app/entities/box/box-detail.component.html
<font color="#4E9A06">   create</font> src/main/webapp/app/entities/box/box-update.component.html
<font color="#4E9A06">   create</font> src/main/webapp/app/entities/box/box-delete-dialog.component.html
<font color="#C4A000">    force</font> src/main/webapp/app/layouts/navbar/navbar.component.html
<font color="#C4A000">    force</font> .yo-rc.json
<font color="#4E9A06">   create</font> .jhipster/Box.json
<font color="#4E9A06">   create</font> src/main/webapp/app/shared/model/box.model.ts
<font color="#4E9A06">   create</font> src/main/webapp/app/entities/box/box.module.ts
<font color="#4E9A06">   create</font> src/main/webapp/app/entities/box/box.route.ts
<font color="#4E9A06">   create</font> src/main/webapp/app/entities/box/box.component.ts
<font color="#4E9A06">   create</font> src/main/webapp/app/entities/box/box-detail.component.ts
<font color="#4E9A06">   create</font> src/main/webapp/app/entities/box/box.service.ts
<font color="#4E9A06">   create</font> src/main/webapp/app/entities/box/box-update.component.ts
<font color="#4E9A06">   create</font> src/main/webapp/app/entities/box/box-delete-dialog.component.ts
<font color="#4E9A06">   create</font> src/test/javascript/spec/app/entities/box/box-detail.component.spec.ts
<font color="#4E9A06">   create</font> src/test/javascript/spec/app/entities/box/box.component.spec.ts
<font color="#4E9A06">   create</font> src/test/javascript/spec/app/entities/box/box.service.spec.ts
<font color="#4E9A06">   create</font> src/test/javascript/spec/app/entities/box/box-update.component.spec.ts
<font color="#4E9A06">   create</font> src/test/javascript/spec/app/entities/box/box-delete-dialog.component.spec.ts
<font color="#4E9A06">   create</font> src/test/javascript/e2e/entities/box/box.page-object.ts
<font color="#4E9A06">   create</font> src/test/javascript/e2e/entities/box/box.spec.ts
<font color="#C4A000">    force</font> src/main/webapp/app/entities/entity.module.ts
<font color="#4E9A06">   create</font> src/main/webapp/i18n/en/box.json
<font color="#C4A000">    force</font> src/main/webapp/i18n/en/global.json
<font color="#4E9A06">   create</font> src/main/webapp/i18n/fr/box.json
<font color="#C4A000">    force</font> src/main/webapp/i18n/fr/global.json
<font color="#4E9A06">   create</font> src/main/webapp/i18n/es/box.json
<font color="#C4A000">    force</font> src/main/webapp/i18n/es/global.json
<font color="#4E9A06">   create</font> src/main/webapp/i18n/te/box.json
<font color="#C4A000">    force</font> src/main/webapp/i18n/te/global.json

<font color="#8AE234"><b>Running `webpack:build` to update client app</b></font>

<font color="#8AE234"><b>Entity Box generated successfully.</b></font>

&gt; pdfeditor@0.0.1-SNAPSHOT webpack:build /home/sudharaka/IdeaProjects/GeneratedApplications/jdl-sample-test
&gt; npm run cleanup &amp;&amp; npm run webpack:build:main


&gt; pdfeditor@0.0.1-SNAPSHOT cleanup /home/sudharaka/IdeaProjects/GeneratedApplications/jdl-sample-test
&gt; rimraf target/classes/static/ target/classes/aot


&gt; pdfeditor@0.0.1-SNAPSHOT webpack:build:main /home/sudharaka/IdeaProjects/GeneratedApplications/jdl-sample-test
&gt; npm run webpack -- --config webpack/webpack.dev.js --env.stats=minimal


&gt; pdfeditor@0.0.1-SNAPSHOT webpack /home/sudharaka/IdeaProjects/GeneratedApplications/jdl-sample-test
&gt; node --max_old_space_size=4096 node_modules/webpack/bin/webpack.js &quot;--config&quot; &quot;webpack/webpack.dev.js&quot; &quot;--env.stats=minimal&quot;

<font color="#D3D7CF">Webpack: Starting ...</font>

<font color="#4E9A06">  ✔ Compile modules</font>
<font color="#4E9A06">  ✔ Build modules</font>
<font color="#4E9A06">  ✔ Optimize modules</font>
<font color="#4E9A06">  ✔ Emit files</font>

<font color="#D3D7CF">Webpack: Finished after 17.678 seconds.</font>



<span style="background-color:#4E9A06"><font color="#2E3436"> DONE </font></span> <font color="#4E9A06">Compiled successfully in 17682ms</font>                                                        <font color="#555753">9:42:31 PM</font>

   477 modules
<font color="#8AE234"><b>INFO!</b></font> <font color="#8AE234"><b>Congratulations, JHipster execution is complete!</b></font>
</pre>
</details>

**Comment by MathieuAA** [comment] 2020-04-19 08:49
@ravikalla @SudharakaP it's a possible duplicate of #11520

**Comment by SudharakaP** [comment] 2020-04-19 14:38
@MathieuAA : Yes indeed you are right; this is a duplicate of #11520 which is the reason I cannot reproduce it since I am using the `master` branch linked when generating the project. 

@ravikalla : This was already fixed at https://github.com/jhipster/generator-jhipster/pull/11521 recently. You'll get this in the next release. 

Therefore I am closing this issue. :smile:

**Closed by SudharakaP** 2020-04-19 14:38 UTC
Labels: area: needs-reproduction, theme: JDL
