### ISSUE TITLE
connect to MYSQL in Amazon RDS failed and displayed access denial error 

### ISSUE THREAD

**Issue by zergxyz** [jhipster/generator-jhipster#1541] opened 2015-05-28 18:31 UTC
Hello, I'm right now testing our jhipster sample app at my local and I'm using AWS-RDS mysql database as my dev database. I've already configured the db security group so that it can accept traffic from everwhere in aws console and test it with phpmyadmin at local without any problems.
I also test jhipster with localhost mysql database in the dev file and it also works perfectly. But when I changed the url from local to my rds database in the cloud, I got following error:

"Access denied for user 'username'@'my local PC domain' (using password: YES)".

Any idea about this case? Thanks

**Comment by wuethrich44** [comment] 2015-05-28 18:46
Did you set the following variables correctly?

- spring.datsource.url
- spring.datasource.username
- spring.datasource.password

It seems you set the wrong database url.

**Comment by zergxyz** [comment] 2015-05-28 19:15
@wuethrich44  Thanks for your reply, wue. Actually I believe I set them right, please correct me if the following configuration is wrong. What I did is just like this:
in file named application-dev.yml, I made the datasource section like this:

        dataSourceClassName: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
        url: jdbc:mysql://my-aws-rds-endpoint-address:3306/mydbname
        databaseName: 
        serverName: 
        username: mydbusername
        password: mydbpassword
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true

The only things I changed from default setting are the url, username and password. Please advice, thanks.

**Comment by jdubois** [comment] 2015-05-29 05:50
Have a look in the log to see if you use the right profile.

This is not a bug or a feature request, so I'm closing this ticket.

**Closed by jdubois** 2015-05-29 05:50 UTC

**Comment by zergxyz** [comment] 2015-05-29 13:56
@jdubois Okay, is there a user-group for me to check with?

**Comment by jdubois** [comment] 2015-05-29 14:08
We have Stackoverflow, and the chat, for this kind of questions, please read:
http://jhipster.github.io/help.html

**Comment by svennela** [comment] 2015-05-29 16:35
Looks like it is DNS issue. run this command on your EC2.. Good luck.
 echo "127.0.0.1 $(hostname)" >> /etc/hosts
