### ISSUE TITLE
Failed to generate entity ui from microservie

### ISSUE THREAD

**Issue by rainee007** [jhipster/generator-jhipster#3599] opened 2016-05-15 16:58 UTC
##### **Overview of the issue**

I download a sample jh file from JDL Studio, and generated a microservice based on it. Later, I generated entity Region for ui gateway, it was failed.

##### **Motivation for or Use Case** 

I think it should easily work the case.

##### **JHipster Version(s)** 

3.3.0

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 

gateway's:
{
  "generator-jhipster": {
    "jhipsterVersion": "3.3.0",
    "baseName": "qyboi",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "uaa",
    "uaaBaseName": "uaa",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": "no",
    "buildTool": "maven",
    "jwtSecretKey": "95302780b4502f07e9988cf3704070633df58b4d",
    "useSass": false,
    "applicationType": "gateway",
    "testFrameworks": [
      "gatling"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "zh-cn",
    "languages": [
      "zh-cn",
      "en"
    ]
  }
}

microservice's:
{
  "generator-jhipster": {
    "jhipsterVersion": "3.3.0",
    "baseName": "testms",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8081",
    "authenticationType": "uaa",
    "hibernateCache": "ehcache",
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": "no",
    "buildTool": "maven",
    "jwtSecretKey": "1fe7cf77a21a76fed05f9c7354fc32a59dc5761c",
    "enableTranslation": true,
    "applicationType": "microservice",
    "testFrameworks": [
      "gatling"
    ],
    "jhiPrefix": "jhi",
    "skipClient": true,
    "skipUserManagement": true,
    "nativeLanguage": "zh-cn",
    "languages": [
      "zh-cn",
      "en"
    ]
  }
}

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory** 

Region.json:
{
  "relationships": [],
  "fields": [
    {
      "fieldId": 1,
      "fieldName": "regionId",
      "fieldType": "Long"
    },
    {
      "fieldId": 2,
      "fieldName": "regionName",
      "fieldType": "String"
    }
  ],
  "changelogDate": "20160515153525",
  "dto": "no",
  "pagination": "no",
  "service": "no",
  "entityTableName": "region"
}

##### **Browsers and Operating System** 

Mac OS latest

##### **Reproduce the error** 

The Registry is running.
The UAA is running.
The microservice has been generated.
The ui gateway has been generated.
After ran yo jhipster:entity Region under ui gateway, got error below:
$ yo jhipster:entity Region

The entity Region is being created.

? Do you want to generate this entity from an existing microservice? Yes
? Enter the path to the microservice root directory: ../testms

Found the .jhipster/Region.json configuration file, entity can be automatically generated!

Error jhipster:entity Region 

Microservice name for the entity is not found. Entity cannot be generated!

**Comment by deepu105** [comment] 2016-05-16 00:35
Did you use `import-jdl` sub generator or jhipster uml to generate the entity?  Also did you provide the mocroservice name in the JDL file?

**Comment by deepu105** [comment] 2016-05-16 00:37
This might be  a duplicate of https://github.com/jhipster/generator-jhipster/issues/3532

**Comment by rainee007** [comment] 2016-05-16 06:09
I used jhipster uml to generate the entities.
The JDL file is:

entity Region {
	regionId Long,
	regionName String
}

entity Country {
	countryId Long,
	countryName String
}

entity Location {
	locationId Long,
	streetAddress String,
	postalCode String,
	city String,
	stateProvince String
}

entity Department {
	departmentId Long,
	departmentName String required
}

entity Task {
	taskId Long,
	title String,
	description String
}

/**
 * The Employee entity.
 */
entity Employee {
	employeeId Long,
	/**
	* The firstname attribute.
	*/
	firstName String,
	lastName String,
	email String,
	phoneNumber String,
	hireDate ZonedDateTime,
	salary Long,
	commissionPct Long
}

entity Job {
	jobId Long,
	jobTitle String,
	minSalary Long,
	maxSalary Long
}

entity JobHistory {
	startDate ZonedDateTime,
	endDate ZonedDateTime,
	language Language
}

enum Language {
    FRENCH, ENGLISH, SPANISH
}

relationship OneToOne {
	Country{region} to Region
}

relationship OneToOne {
	Location{country} to Country
}

relationship OneToOne {
	Department{location} to Location
}

relationship ManyToMany {
	Job{task(title)} to Task{job}
}

relationship OneToMany {
	Employee{job} to Job
}

relationship OneToMany {
	/**
	* A relationship
	*/
	Department{employee} to
	/**
	* Another side of the same relationship
	*/
	Employee
}

relationship ManyToOne {
	Employee{manager} to Employee
}

relationship OneToOne {
	JobHistory{job} to Job
}

relationship OneToOne {
	JobHistory{department} to Department
}

relationship OneToOne {
	JobHistory{employee} to Employee
}

paginate JobHistory, Employee with infinite-scroll
paginate Job with pagination

dto Employee with mapstruct

service Employee with serviceClass

**Comment by rainee007** [comment] 2016-05-16 06:29
I could see all the rest apis in the running microservice, but just could not generate UI code via jhipster:entity cli following the recommended way.

**Comment by deepu105** [comment] 2016-05-17 01:19
I dont see you defining the microserviceName as per the documentation anywhere in JDL. Please check the JDL docs and define it properly and ise jhipster uml to generate the entities.

**Closed by deepu105** 2016-05-17 01:19 UTC

**Comment by deepu105** [comment] 2016-05-17 01:21
Here is the related docs https://jhipster.github.io/jdl/#microserviceoptions

**Comment by davidweianibone** [comment] 2016-10-21 10:18
Hi, I have the same issue and followed jdl docs.
Didn't quit understand if and why do I need to specify my microservice name.
I have used the jhipster uml to generate the micro services entities.

**Comment by tezcane** [comment] 2016-10-21 21:57
Same issue as @davidweianibone .   It would be nice if the JDL documentation had a simple step 1. 2. 3. guide on how to make entities on the microservice (using JDL studio) then import these entities into the gateway.  I have found, there is a lot of gray area around JDL studio.   Although an awesome tool, I wish the documentations were a little clearer.  Once I learn it I was hoping to contribute to improving some of the JHipster docs...

**Comment by tezcane** [comment] 2016-10-21 22:58
@davidweianibone got it working by deleting .yo-rc-global.json which was in my home folder.  It was pointing to generator v3.8.0, but I had upgraded to v3.9.1 today.

**Comment by davidweianibone** [comment] 2016-10-21 23:48
Don't find such file in my project. The only file I have is .yo-rc.json which looks like this
{
  "generator-jhipster": {
    "jhipsterVersion": "3.8.0",
    "baseName": "AniBoneGateWay",
    "packageName": "com.anibone",
    "packageFolder": "com/anibone",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "hazelcast",
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "jwtSecretKey": my secrete key,
    "useSass": true,
    "applicationType": "gateway",
    "testFrameworks": [
      "gatling",
      "cucumber",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}

**Comment by pascalgrimaud** [comment] 2016-10-22 08:45
Plz guys, don't camp on old tickets.
If you have an issue, plz open a new one, with :
- full configuration, projects, entities ( all .yo-rc.json, all jdl files and/or all .jhipster/*.json etc...)
- all steps precisely to reproduce quickly the bug
