### ISSUE TITLE
ClassCastException: org.apache.tomcat.websocket.server.WsServerContainer cannot be cast to javax.websocket.server.ServerContainer

### ISSUE THREAD

**Issue by zapphyre** [jhipster/generator-jhipster#8119] opened 2018-08-20 09:39 UTC
##### **Overview of the issue**

A class cast exception happens when .original war package is being deployed on the Tomcat 7.x container.
Application uses WebSockets with SockJS.
I have marked `javax.websocket-api` as a provided dependency for both profiles.

error:
```
org.springframework.web.socket.sockjs.SockJsException: Uncaught failure in SockJS request, uri=http://192.168.0.31:8080/websocket/driveme/073/xmcnsxoo/websocket?access_token=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJwcm92aWRlcjEyM0Bwcm92aWRlciIsImF1dGgiOiJST0xFX1VTRVJfRFJJVkVfUFJPVklERVIiLCJleHAiOjE1MzQ4NDMzMjh9.Uo30YivFCezQrrSF-IMmI7fAOnPg1Xri52c0GLAMyth62z4W2_gQuW7jA5NVEEDxOKY6pDkffYIqgPUI5SLZJw; nested exception is org.springframework.web.socket.sockjs.SockJsTransportFailureException: WebSocket handshake failure; nested exception is java.lang.ClassCastException: org.apache.tomcat.websocket.server.WsServerContainer cannot be cast to javax.websocket.server.ServerContainer
	at org.springframework.web.socket.sockjs.support.SockJsHttpRequestHandler.handleRequest(SockJsHttpRequestHandler.java:135)
	at org.springframework.web.servlet.mvc.HttpRequestHandlerAdapter.handle(HttpRequestHandlerAdapter.java:51)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:624)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at com.codahale.metrics.servlet.AbstractInstrumentedFilter.doFilter(AbstractInstrumentedFilter.java:111)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:101)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestTraceFilter.java:110)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:317)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:127)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:114)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:170)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.session.ConcurrentSessionFilter.doFilter(ConcurrentSessionFilter.java:155)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at com.driveme.security.jwt.JWTFilter.doFilter(JWTFilter.java:36)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:96)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:64)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:177)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:347)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:263)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:108)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.springframework.boot.web.support.ErrorPageFilter.doFilter(ErrorPageFilter.java:115)
	at org.springframework.boot.web.support.ErrorPageFilter.access$000(ErrorPageFilter.java:59)
	at org.springframework.boot.web.support.ErrorPageFilter$1.doFilterInternal(ErrorPageFilter.java:90)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.boot.web.support.ErrorPageFilter.doFilter(ErrorPageFilter.java:108)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:494)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:104)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:1025)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:445)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1136)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.springframework.web.socket.sockjs.SockJsTransportFailureException: WebSocket handshake failure; nested exception is java.lang.ClassCastException: org.apache.tomcat.websocket.server.WsServerContainer cannot be cast to javax.websocket.server.ServerContainer
	at org.springframework.web.socket.sockjs.transport.handler.WebSocketTransportHandler.handleRequest(WebSocketTransportHandler.java:127)
	at org.springframework.web.socket.sockjs.transport.TransportHandlingSockJsService.handleTransportRequest(TransportHandlingSockJsService.java:312)
	at org.springframework.web.socket.sockjs.support.AbstractSockJsService.handleRequest(AbstractSockJsService.java:434)
	at org.springframework.web.socket.sockjs.support.SockJsHttpRequestHandler.handleRequest(SockJsHttpRequestHandler.java:132)
	... 102 common frames omitted
```

##### **Motivation for or Use Case**

as per documentation:
`It can also be deployed on an application server, but as it includes runtime libraries, we recommend you use the second, .original file if you want to deploy JHipster on an application server like Tomcat, Weblogic or Websphere.`
..which is exactly what I need and need it working.

##### **Reproduce the error**

- create an application that uses web sockets
- deploy an application on the Tomcat 7.x
- try to connect to web socket broker.

##### **Related issues**

[similar to](https://github.com/jhipster/generator-jhipster/issues/2270#issue-114740468)

##### **JHipster Version(s)**

$ jhipster --version
Using JHipster version installed globally
4.14.1

##### **JHipster configuration**

$ jhipster info
Using JHipster version installed locally in current project's node_modules
Executing jhipster:info
Options: 
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
backend@0.0.0 /home/tepo/IdeaProjects/jhipster/drive-me/backend
└── generator-jhipster@4.14.1 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.driveme",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "4.14.1",
    "baseName": "backend",
    "packageName": "com.driveme",
    "packageFolder": "com/driveme",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": true,
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "npm",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "cs",
      "hu",
      "sk"
    ]
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity LatLng (lat_lng) {
  lat Float,
  lng Float
}
entity Address (address) {
  city String,
  street String,
  number String
}
entity DriveOrder (drive_order) {
  state EOrderState
}
entity AppUser (app_user)
entity DriveMeUser (drive_me_user) {
  driverRole EDriverRole,
  isRegComplete Boolean,
  phoneNumber String
}
entity Car (car) {
  color String,
  type String,
  model String,
  yearMade LocalDate,
  regNumPlate String
}
entity Offer (offer) {
  priceKm Float,
  cost Float,
  durationSec Integer,
  distanceKm Float,
  created ZonedDateTime,
  path String,
  lastStateChange ZonedDateTime,
  offerState EOfferState
}

enum EOrderState {
  SAVED,
   PENDING,
   COMPLETE,
   CANCELLED,
   IN_PROGRESS,
   DRIVER_ARRIVED
}

enum EDriverRole {
  DRIVER_CLIENT,
  DRIVER_PROVIDER
}

enum EOfferState {
  PLACED,
   TAKEN,
   COMPLETE,
   EXPIRED
}

relationship OneToOne {
  Address{latLng} to LatLng,
  DriveOrder{from} to Address,
  DriveOrder{to} to Address,
  DriveOrder{user} to DriveMeUser,
  DriveMeUser{car} to Car,
  DriveMeUser{user} to User,
  Offer{provider} to DriveMeUser
}
relationship OneToMany {
  DriveOrder{offers} to Offer{driveOrder}
}

</pre>
</details>

##### **Environment and Tools**

openjdk version "1.8.0_172"
OpenJDK Runtime Environment (build 1.8.0_172-b11)
OpenJDK 64-Bit Server VM (build 25.172-b11, mixed mode)

git version 2.18.0

node: v8.9.1

npm: 6.1.0

bower: 1.7.9

gulp:
[11:24:09] CLI version 3.9.1

yeoman: 1.8.5

Congratulations, JHipster execution is complete!

##### **Browsers and Operating System**

Archlinux
$ uname -a
Linux ux32vd 4.17.4-1-ARCH #1 SMP PREEMPT Tue Jul 3 15:45:09 UTC 2018 x86_64 GNU/Linux
this app serves mainly as a backend and the issue is always reproducable.

- [ x] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment] 2018-08-20 09:53
For Websockets it's bit more complex than normal Web apps, as you will need to use the specific Websocket implementation from the app server - I am really not sure this can work easily, and would definitely recommend not using Tomcat here.
From the Spring Websockets documentation, you need to use "Tomcat 7.0.47+", which version are you using exactly?

**Comment by zapphyre** [comment] 2018-08-20 10:16
it's Tomcat 7.0.90 and I also tried with 8.5.32 which is the same.
without Tomcat the app gets terminated because lack of memory even through I have set `JAVA_OPTS="-Xms32m -Xmx128m -XX:MaxMetaspaceSize=128m"`

**Comment by gmarziou** [comment] 2018-08-20 19:59
Well I would rather spend my time analyzing a memory dump to find the root cause of these out of memory errors. For instance, one of my colleague had such issues because of metrics for RestTemplate because he used to build URIs by concatenating parameters rather than using templated URIs.

**Comment by zapphyre** [comment] 2018-08-20 20:48
you know, I'm really not doing anything special in that backend. A few REST endpoints, SimpleMEssageBroker for SocketJS over Stomp and I even turned off L2 caching... Hosting may be the weak point here, but still... not being able to deploy on the application server that's a considerable downside.

**Comment by ruddell** [comment] 2018-08-20 21:11
I see the issue on Tomcat 7 but not Tomcat 8.  I don't think we should spend time supporting old versions of Tomcat since v9 is the latest, plus this seems to be a general Tomcat+Websocket issue and not a JHipster-specific issue.

You can set the JVM parameters to limit memory when running the regular WAR file, `JAVA_OPTS="-Xms32m -Xmx128m -XX:MaxMetaspaceSize=128m" ./target/backend-0.0.1-SNAPSHOT.war`, I didn't notice any lack of memory warnings/errors

**Comment by zapphyre** [comment] 2018-08-20 21:32
And can you confirm it's working on Tomcat 8? I have tried and it was not. 
As you can see in my previous comment I have tried that, but I exported it via `.bashrc` not directly passed into the command.

**Comment by ruddell** [comment] 2018-08-20 21:40
I confirm it works with Tomcat v8.0.53 (JRE 8), tested with their Docker image.  Just copied the `.war.original` to the webapps folder and websockets work as expected.

**Comment by jdubois** [comment] 2018-08-21 08:35
I would be very surprised that your OOM is solved by migrating to Tomcat. That would mean you have the issue in Undertow, and from my experience the odds are much more likely that the issue is in your code, and not in Undertow's code.

Now for Tomcat support: I'm trusting @ruddell that it works with Tomcat 8, and that's why I'm closing this. We're not going to support old versions anyway - nobody is interested in working on those on their free time, and I'm not going to spend [bug bounty money](https://www.jhipster.tech/bug-bounties/) on those. And anyway, it's probably a Spring issue or a Tomcat 7 issue, as this works with Tomcat 8, so this isn't in our scope.

**Closed by jdubois** 2018-08-21 08:35 UTC
