### ISSUE TITLE
UserService missing flush

### ISSUE THREAD

**Issue by tibistibi** [jhipster/generator-jhipster#8303] opened 2018-09-12 14:23 UTC
I noticed that in the UserService the method registerUser in the case of double used email address is doing a flush and in the case of double login does not.
I assume it should be on both places (although tests do not fail on it).
If agreed i can added the flush in a PR

```    public <% if (reactive) { %>Mono<User><% } else { %>User<% } %> registerUser(UserDTO userDTO, String password) {
    <%_ if (!reactive) { _%>
        userRepository.findOneByLogin(userDTO.getLogin().toLowerCase()).ifPresent(existingUser -> {
            if (!existingUser.getActivated()) {
                userRepository.delete(existingUser);
                <%_ if (cacheManagerIsAvailable === true) { _%>
                this.clearUserCaches(existingUser);
                <%_ } _%>
            } else {
                throw new LoginAlreadyUsedException();
            }
        });
        userRepository.findOneByEmailIgnoreCase(userDTO.getEmail()).ifPresent(existingUser -> {
            if (!existingUser.getActivated()) {
                userRepository.delete(existingUser);
                <%_ if (databaseType === 'sql') { _%>
                userRepository.flush();
                <%_ } _%>
                <%_ if (cacheManagerIsAvailable === true) { _%>
                this.clearUserCaches(existingUser);
                <%_ } _%>
            } else {
                throw new EmailAlreadyUsedException();
            }
        });```

**Comment by jdubois** [comment] 2018-09-12 15:39
Indeed! I'm surprised this does not fail during the tests...

Could you do the PR?

If you have the time (I know the PR is easy, and this is not), it would be awesome that you add a test for this part. I'm finding this really strange, so that would reassure me.

**Comment by tibistibi** [comment] 2018-09-14 07:18
i checked and it is hit by a test:
AccountReesourceIntTest#testRegisterDuplicateLogin

i'm not sure but i think the flush problem does not happen with tests because the transaction is not commited but rolled back when test is done.

besides that there is a bug in the AccountReesourceIntTest#testRegisterDuplicateEmail()

it try's to test casing with email address but because the login stay's the same it is already hitting the login is duplicated.
this can be fixed by changing:

    userWithUpperCaseEmail.setLogin("test-register-duplicate-email-2");
to
    userWithUpperCaseEmail.setLogin("test-register-duplicate-email-3");

In the UserService the code for removing the not activated user should be extracted so it will be the same for login and email address.

shall i do a PR for both?

**Comment by tibistibi** [comment] 2018-09-14 07:27
So i would do something like this:

```
    userRepository.findOneByLogin(userDTO.getLogin().toLowerCase()).ifPresent(existingUser -> {
      boolean removed = removeNonActivatedUser(existingUser);
      if (!removed) {
        throw new LoginAlreadyUsedException();
      }
    });
    userRepository.findOneByEmailIgnoreCase(userDTO.getEmail()).ifPresent(existingUser -> {
      boolean removed = removeNonActivatedUser(existingUser);
      if (!removed) {
        throw new EmailAlreadyUsedException();
      }
    });

  private boolean removeNonActivatedUser(User existingUser) {
    if (existingUser.getActivated()) {
      return false;
    }
    userRepository.flush();
    userRepository.delete(existingUser);
    userRepository.flush();
    this.clearUserCaches(existingUser);
    return true;
  }

````

**Comment by tibistibi** [comment] 2018-09-14 07:33
While i'm thinking about this code on a higher level why is this added? Non activated users get deleted in 3 day's so if in between someone else registers with the same login it will replace the registration.

is this what we want?

**Comment by jdubois** [comment] 2018-09-14 08:18
Thanks @tibistibi - yes can you do just one PR with everything?
Indeed, I don't like this "feature", but this was asked by many people, so yes this is what "we" want ("we" being the majority of people, not including me). What happens, typically on JHipster Online, is that people try to register with a dummy e-mail. Then they realize they don't get the email, so they want to register again, with their real email... This is sooo annoying. I don't think they understand we do that for their own good: if they authorize the app to write to their GitHub account, this is better be well-protected...

**Comment by jdubois** [comment] 2018-09-14 08:28
That's a complex question... At the moment you can also use your email address as a login, so that should already work (you just copy/paste it).
The issue is that we want to be able to look at users, exactly like we do on GitHub if we go to https://github.com/tibistibi - and for that, e-mails addresses are not good: they look ugly, they contain private information (you might not want to show it on a public site), and they can change (when you get married, for example).

**Comment by tibistibi** [comment] 2018-09-14 08:35
I agree, but product owners ask for it, in my previous project i also merged the fields. The argument was simplicity one field less and avoid problems with multiple logins used etc...

Well lets leave the discussion and i will try to find time to fix the flush

**Comment by jdubois** [comment] 2018-09-14 08:39
@tibistibi yes the more I see all those arguments (this is far from being the only one), I realize we do have some "legacy code" and we can't remove it easily.

Next major release (the only moment when we break APIs), we should do a big refactoring of all this.

**Comment by deepu105** [comment] 2018-09-15 10:01
closed via #8323

**Closed by deepu105** 2018-09-15 10:01 UTC

**Comment by cbornet** [comment] 2019-02-28 13:34
When doing this kind of fix, please consider also doing it for the `reactive` option. Or at least open an issue for this.

**Comment by cbornet** [comment] 2019-02-28 13:48
That said, SQL is currently not supported for reactive so not a big deal atm. Sorry for the noise.
