### ISSUE TITLE
API calls all return unauthorised in newly generated jhipster app using http sessions

### ISSUE THREAD

**Issue by jamesfielder** [jhipster/generator-jhipster#6916] opened 2017-12-27 14:49 UTC
##### **Overview of the issue**

After generating a fresh jhipster application using http sessions (with clustered sessions using hazelcast) api calls fail, producing a 401 error. The logs created by mvnw show the following (logging in as admin and then going to the user management page):

```
2017-12-27 14:32:19.164 DEBUG 26787 --- [  XNIO-2 task-3] c.m.m.security.DomainUserDetailsService  : Authenticating admin
2017-12-27 14:32:19.171  INFO 26787 --- [  XNIO-2 task-3] c.h.i.p.impl.PartitionStateManager       : [127.0.0.1]:5701 [dev] [3.9.1] Initializing cluster partition table arrangement...
Hibernate: select user0_.id as id1_5_0_, authority2_.name as name1_0_1_, user0_.created_by as created_2_5_0_, user0_.created_date as created_3_5_0_, user0_.last_modified_by as last_mod4_5_0_, user0_.last_modified_date as last_mod5_5_0_, user0_.activated as activate6_5_0_, user0_.activation_key as activati7_5_0_, user0_.email as email8_5_0_, user0_.first_name as first_na9_5_0_, user0_.image_url as image_u10_5_0_, user0_.lang_key as lang_ke11_5_0_, user0_.last_name as last_na12_5_0_, user0_.login as login13_5_0_, user0_.password_hash as passwor14_5_0_, user0_.reset_date as reset_d15_5_0_, user0_.reset_key as reset_k16_5_0_, authoritie1_.user_id as user_id1_6_0__, authoritie1_.authority_name as authorit2_6_0__ from jhi_user user0_ left outer join jhi_user_authority authoritie1_ on user0_.id=authoritie1_.user_id left outer join jhi_authority authority2_ on authoritie1_.authority_name=authority2_.name where user0_.email=?
Hibernate: select user0_.id as id1_5_0_, authority2_.name as name1_0_1_, user0_.created_by as created_2_5_0_, user0_.created_date as created_3_5_0_, user0_.last_modified_by as last_mod4_5_0_, user0_.last_modified_date as last_mod5_5_0_, user0_.activated as activate6_5_0_, user0_.activation_key as activati7_5_0_, user0_.email as email8_5_0_, user0_.first_name as first_na9_5_0_, user0_.image_url as image_u10_5_0_, user0_.lang_key as lang_ke11_5_0_, user0_.last_name as last_na12_5_0_, user0_.login as login13_5_0_, user0_.password_hash as passwor14_5_0_, user0_.reset_date as reset_d15_5_0_, user0_.reset_key as reset_k16_5_0_, authoritie1_.user_id as user_id1_6_0__, authoritie1_.authority_name as authorit2_6_0__ from jhi_user user0_ left outer join jhi_user_authority authoritie1_ on user0_.id=authoritie1_.user_id left outer join jhi_authority authority2_ on authoritie1_.authority_name=authority2_.name where user0_.login=?
2017-12-27 14:32:19.582 DEBUG 26787 --- [  XNIO-2 task-3] c.m.myapp.aop.logging.LoggingAspect      : Enter: org.springframework.boot.actuate.audit.AuditEventRepository.add() with argument[s] = [AuditEvent [timestamp=Wed Dec 27 14:32:19 GMT 2017, principal=admin, type=AUTHENTICATION_SUCCESS, data={details=org.springframework.security.web.authentication.WebAuthenticationDetails@957e: RemoteIpAddress: 127.0.0.1; SessionId: null}]]
Hibernate: call next value for hibernate_sequence
2017-12-27 14:32:19.614 DEBUG 26787 --- [  XNIO-2 task-3] c.m.myapp.aop.logging.LoggingAspect      : Exit: org.springframework.boot.actuate.audit.AuditEventRepository.add() with result = null
Hibernate: insert into jhi_persistent_audit_event (event_date, event_type, principal, event_id) values (?, ?, ?, ?)
Hibernate: insert into jhi_persistent_audit_evt_data (event_id, name, value) values (?, ?, ?)
2017-12-27 14:32:19.684 DEBUG 26787 --- [  XNIO-2 task-3] .m.m.s.PersistentTokenRememberMeServices : Did not send remember-me cookie (principal did not set parameter 'remember-me')
2017-12-27 14:32:19.684 DEBUG 26787 --- [  XNIO-2 task-3] .m.m.s.PersistentTokenRememberMeServices : Remember-me login not requested.
2017-12-27 14:32:19.710 DEBUG 26787 --- [  XNIO-2 task-4] c.m.myapp.aop.logging.LoggingAspect      : Enter: com.mycompany.myapp.web.rest.AccountResource.getAccount() with argument[s] = []
2017-12-27 14:32:19.723 DEBUG 26787 --- [  XNIO-2 task-4] c.m.myapp.aop.logging.LoggingAspect      : Enter: com.mycompany.myapp.service.UserService.getUserWithAuthorities() with argument[s] = []
2017-12-27 14:32:19.747 DEBUG 26787 --- [  XNIO-2 task-4] c.m.myapp.aop.logging.LoggingAspect      : Exit: com.mycompany.myapp.service.UserService.getUserWithAuthorities() with result = Optional[User{login='admin', firstName='Administrator', lastName='Administrator', email='admin@localhost', imageUrl='', activated='true', langKey='en', activationKey='null'}]
2017-12-27 14:32:19.751 DEBUG 26787 --- [  XNIO-2 task-4] c.m.myapp.aop.logging.LoggingAspect      : Exit: com.mycompany.myapp.web.rest.AccountResource.getAccount() with result = UserDTO{login='admin', firstName='Administrator', lastName='Administrator', email='admin@localhost', imageUrl='', activated=true, langKey='en', createdBy=system, createdDate=2017-12-27T14:25:05.946Z, lastModifiedBy='system', lastModifiedDate=null, authorities=[ROLE_USER, ROLE_ADMIN]}
2017-12-27 14:32:21.502 DEBUG 26787 --- [  XNIO-2 task-5] c.m.myapp.aop.logging.LoggingAspect      : Enter: org.springframework.boot.actuate.audit.AuditEventRepository.add() with argument[s] = [AuditEvent [timestamp=Wed Dec 27 14:32:21 GMT 2017, principal=anonymousUser, type=AUTHORIZATION_FAILURE, data={details=org.springframework.security.web.authentication.WebAuthenticationDetails@957e: RemoteIpAddress: 127.0.0.1; SessionId: null, type=org.springframework.security.access.AccessDeniedException, message=Access is denied}]]
2017-12-27 14:32:21.502 DEBUG 26787 --- [  XNIO-2 task-5] c.m.myapp.aop.logging.LoggingAspect      : Exit: org.springframework.boot.actuate.audit.AuditEventRepository.add() with result = null
2017-12-27 14:32:21.506  WARN 26787 --- [  XNIO-2 task-5] o.z.p.spring.web.advice.AdviceTrait      : Unauthorized: Full authentication is required to access this resource
2017-12-27 14:32:21.508  WARN 26787 --- [  XNIO-2 task-5] .m.m.a.ExceptionHandlerExceptionResolver : Resolved exception caused by Handler execution: org.springframework.security.authentication.InsufficientAuthenticationException: Full authentication is required to access this resource
```

An example app exhibiting this issue is [here](https://github.com/jamesfielder/jhipster-auth-issue/).

##### **Motivation for or Use Case**

I updated an older jhipster app to the 4.13.1 version and discovered this bug.

##### **Reproduce the error**

1. Generate a new app, selecting http sessions, hazelcast (for all hazelcast options), an SQL db and angular 5.
2. Start the application and login as admin.
3. Attempt to browse to the user management page.
4. You will have been logged out and looking in the browser console will show that the call to the API to get user accounts failed with a 401 code.

##### **Suggest a Fix**

Unsure of a fix but I will have a look through the spring code to see what has changed.

##### **JHipster Version(s)**

4.13.1 and it does seem to be a regression.

##### **JHipster configuration**

```
Executing jhipster:info
Options: 
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
jhipster@0.0.0 /Users/james/work/sample-app
└── generator-jhipster@4.13.1 

```


##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**


<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp"
    },
    "jhipsterVersion": "4.13.1",
    "baseName": "jhipster",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "session",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": true,
    "clusteredHttpSession": "hazelcast",
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": true,
    "enableSwaggerCodegen": false,
    "rememberMeKey": "replaced-by-jhipster-info",
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}
</pre>
</details>


##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>




</pre>
</details>


##### **Environment and Tools**

java version "1.8.0_152"
Java(TM) SE Runtime Environment (build 1.8.0_152-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.152-b16, mixed mode)

git version 2.15.1

node: v9.3.0

npm: 5.6.0

bower: 1.8.0

gulp:
[14:44:28] CLI version 1.4.0

yeoman: 1.8.5

yarn: 1.3.2

Docker version 17.09.1-ce, build 19e2cf6

docker-compose version 1.17.1, build 6d101fb
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

I have not generated any entities.

##### **Browsers and Operating System**

MacOS 10.12.6, chrome 63.

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by jamesfielder** [comment] 2017-12-27 14:51
Additionally, this is the .yo-rc.json for my real app which has this problem.

```
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.app"
    },
    "jhipsterVersion": "4.13.1",
    "baseName": "studypro",
    "packageName": "com.app",
    "packageFolder": "com/app",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": "hazelcast",
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": true,
    "rememberMeKey": "removed",
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": false,
    "cacheProvider": "hazelcast",
    "enableHibernateCache": true
  }
}
```

Just thought I should post this incase there are some options which I shouldn't be using together say.

**Comment by jdubois** [comment] 2017-12-27 14:51
We did change the way cache is configured in the last patch release (v4.13.1), and as very few people use session clustering (and very few people use session-based authent) we might have missed something here. I'm having a look.

**Comment by jamesfielder** [comment] 2017-12-27 14:52
I thought it might be a less well walked path nowadays. Thanks for having a look!

**Comment by jdubois** [comment] 2017-12-27 14:52
Oh and you have social login too... This is also very rarely used, so you have a very uncommon configuration

**Comment by jdubois** [comment] 2017-12-27 14:54
Oh it looks it only works if you select "remember me", can you check?

**Comment by jamesfielder** [comment] 2017-12-27 14:56
Yes that works for me as well.

**Comment by jdubois** [comment] 2017-12-27 15:06
I can confirm this is caused by the clustered http session (not the social login)

**Comment by jdubois** [comment] 2017-12-27 15:39
This is definitely the clustered http session with Hazelcast: just comment the "initClusteredHttpSessionFilter" method call in `WebConfigurer` and it will work again.

I've been willing to remove support for this for a long time, as this is a lot of maintenance for very few people - and I'm now wishing we had removed that already!

**Comment by jdubois** [comment] 2017-12-27 15:51
Testing with Hazelcast Management Center (auto-configured by JHipster as a Docker image, that's awesome!) I can see my http session, but it's empty (0 kb). So that explains why we are logged out, Hazelcast doesn't store the session data.

**Comment by jamesfielder** [comment] 2017-12-27 16:39
I will remove it from the app in that case, giving you one less user to worry about!

**Comment by jdubois** [comment] 2017-12-29 15:31
Thanks for your feedback!
Honestly Session clustering is a bad idea, and you can achieve better with our new caching support -> I will document this better in our changelog, when I remove session clustering (vote is still opened, but it looks like it's the end of session clustering)

**Comment by jdubois** [comment] 2017-12-29 15:32
Oh thanks @jamesfielder for supporting us on OpenCollective! Can you add your Twitter handle so I can mention you?

**Comment by jamesfielder** [comment] 2017-12-29 15:34
I'll keep my eye out for that in the future and will probably look at using it. My twitter is @james_fielder as well, feel free to mention me if you would like. :)

**Comment by deepu105** [comment] 2018-01-05 08:01
closing this as the option is being removed

**Closed by deepu105** 2018-01-05 08:01 UTC

**Comment by ahpearce** [comment] 2018-03-29 13:33
Encountered this issue with a newly generated app with React in 4.14.0.

Tried accessing on 9000 and 8080. Logged in as 'admin:admin' with "Remember Me?" checked.

Any Swagger request is setting
`--header 'Authorization: Bearer null'`


```
.yo-rc.json
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "..."
    },
    "jhipsterVersion": "4.14.0",
    "baseName": "...",
    "reactive": false,
    "packageName": "...",
    "packageFolder": "...",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": false,
    "websocket": false,
    "databaseType": "mongodb",
    "devDatabaseType": "mongodb",
    "prodDatabaseType": "mongodb",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "2e25c29924521204ce2061b5f94f35251c8c421d",
    "clientFramework": "react",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}
```

**Comment by janierj** [comment] 2018-04-29 14:43
Me too encountered this issue with a newly generated app with React in 5.0.0-beta.0
No matters the remember me selection

Any Swagger request is setting
`--header 'Authorization: Bearer null'`

`
yo-rc.json
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "...",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "5.0.0-beta.0",
    "baseName": "bluparty",
    "reactive": true,
    "packageName": "...",
    "packageFolder": "...",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": true,
    "jwtSecretKey": "70e1afb0c537a25df90328053df6a87e4af9ba52",
    "clientFramework": "react",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "pt-br",
      "es"
    ]
  }
}
`

**Comment by eredwan** [comment] 2018-06-06 18:46
It seems like I have an issue related to this issue number.

I upgraded my jhipster app version from 4.5.4 to 4.14.4 and now my caching or auth management seems to be broken. I am getting the following error without even trying to login (default anonymousUser)  because I can't due to my nav bar not showing because ngSwitch=isAuthenticated() fails. I looked to see if any of the problems mentioned in this issue was in my app but it does not seem like there is. I do not have "initClusteredHttpSessionFilter" anywhere in my app. I have been struggling with this one for 2 days now. Anyone have any ideas?

```
2018-06-05 17:08:23.292 DEBUG 36632 --- [  XNIO-2 task-1] c.c.theApp.aop.logging.LoggingAspect   : Enter: com.theApp.theAppslink.web.rest.ProfileInfoResource.getActiveProfiles() with argument[s] = []
2018-06-05 17:08:23.299 DEBUG 36632 --- [  XNIO-2 task-1] c.c.theApp.aop.logging.LoggingAspect   : Exit: com.theApp.theApplink.web.rest.ProfileInfoResource.getActiveProfiles() with result = com.theApp.theApp.web.rest.ProfileInfoResource$ProfileInfoVM@4f29e835
2018-06-05 17:08:23.822 DEBUG 36632 --- [  XNIO-2 task-2] c.c.theApp.aop.logging.LoggingAspect   : Enter: org.springframework.boot.actuate.audit.AuditEventRepository.add() with argument[s] = [AuditEvent [timestamp=Tue Jun 05 17:08:23 PDT 2018, principal=anonymousUser, type=AUTHORIZATION_FAILURE, data={details=org.springframework.security.web.authentication
.WebAuthenticationDetails@957e: RemoteIpAddress: 127.0.0.1; SessionId: null, type=org.springframework.security.access.AccessDeniedException, message=Access is denied}]]
2018-06-05 17:08:23.825 DEBUG 36632 --- [  XNIO-2 task-2] c.c.theApp.aop.logging.LoggingAspect   : Exit: org.springfra
mework.boot.actuate.audit.AuditEventRepository.add() with result = null
2018-06-05 17:08:23.923  WARN 36632 --- [  XNIO-2 task-2] o.z.p.spring.web.advice.AdviceTrait      : Unauthorized: Full authentication is required to access this resource
2018-06-05 17:08:24.017  WARN 36632 --- [  XNIO-2 task-2] .m.m.a.ExceptionHandlerExceptionResolver : Resolved exception caused by Handler execution: org.springframework.security.authentication.InsufficientAuthenticationException: Full authentication is required to access this resource
```
.yo-rc.json:
`
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.theApps.theAppslink"
    },
    "jhipsterVersion": "4.14.4",
    "baseName": "theAppSLink",
    "packageName": "com.theApps.theAppslink",
    "packageFolder": "com/theApps/theAppslink",
    "serverPort": "9090",
    "authenticationType": "jwt",
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": false,
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "oracle",
    "prodDatabaseType": "oracle",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "jwtSecretKey": "363b7545bee4c63099549e5c864895d2fa29545d",
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling",
      "cucumber",
      "protractor"
    ],
    "jhiPrefix": "theApps",
    "enableTranslation": false,
    "cacheProvider": "hazelcast",
    "enableHibernateCache": true
  }
}
`

**Comment by HarshitChhipa** [comment] 2019-07-20 08:11
I am not having the same issue but related to this.
My authorities array is empty for the admin.
And due to that, it has no authority to see anything else and that's why I am getting an error as follows.

"You are not authorized to access this page."
My response.
activated: true
authorities: []
createdBy: "system"
createdDate: null
email: "admin@localhost"
firstName: "Administrator"
id: 3
imageUrl: ""
langKey: "en"
lastModifiedBy: "system"
lastModifiedDate: null
lastName: "Administrator"
login: "admin"

Any help will be appreciated

**Comment by gmarziou** [comment] 2019-07-20 10:44
@HarshitChhipa please don't comment on an old issue, if you have a problem please open a new issue with all required details because here we have no idea of what you are using, this is why `jhipster info` was created. Also, please don't crosspost on stackoverflow, it's a waste of time for people trying to help you.
