### ISSUE TITLE
Hazelcast cache is not working on Docker Cloud

### ISSUE THREAD

**Issue by marcelinobadin** [jhipster/generator-jhipster#3609] opened 2016-05-18 02:19 UTC
##### **Overview of the issue**

I am trying to deploy my microservices architecture using Docker Cloud. I am facing a problem with Hazelcast. It happens using dev or prod profiles.

The connection to jhipster-registry is ok and it is getting the configuration successfully.

```
Retrying the connection!!
gateway-app-1 | 2016-05-18T02:14:58.838597831Z 2016-05-18 02:14:58.838  INFO 6 --- [.ensureInstance] com.hazelcast.config.XmlConfigLocator    : Loading 'hazelcast-default.xml' from classpath.
gateway-app-1 | 2016-05-18T02:14:58.912675934Z 2016-05-18 02:14:58.912  INFO 6 --- [.ensureInstance] c.hazelcast.web.HazelcastInstanceLoader  : getOrCreateHazelcastInstance for session replication, using name 'gateway'
gateway-app-1 | 2016-05-18T02:14:58.913717278Z 2016-05-18 02:14:58.913  INFO 6 --- [.ensureInstance] c.h.instance.DefaultAddressPicker        : [LOCAL] [dev] [3.6.1] Prefer IPv4 stack is true.
gateway-app-1 | 2016-05-18T02:14:58.916079754Z 2016-05-18 02:14:58.915  INFO 6 --- [.ensureInstance] c.h.instance.DefaultAddressPicker        : [LOCAL] [dev] [3.6.1] Picked Address[10.7.0.16]:5701, using socket ServerSocket[addr=/0:0:0:0:0:0:0:0,localport=5701], bind any local is true
gateway-app-1 | 2016-05-18T02:15:08.933194202Z 2016-05-18 02:15:08.932  INFO 6 --- [.ensureInstance] c.hazelcast.web.ClusteredSessionService  : Retrying the connection!!
```

My .yo-rc.json

```json
{
  "generator-jhipster": {
    "jhipsterVersion": "3.2.1",
    "baseName": "gateway",
    "packageName": "br.com.example.gateway",
    "packageFolder": "br/com/example/gateway",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "no",
    "clusteredHttpSession": "hazelcast",
    "websocket": "no",
    "databaseType": "mongodb",
    "devDatabaseType": "mongodb",
    "prodDatabaseType": "mongodb",
    "searchEngine": "no",
    "buildTool": "maven",
    "jwtSecretKey": "blablabla",
    "useSass": true,
    "applicationType": "gateway",
    "testFrameworks": [
      "gatling",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "pt-br"
    ],
    "enableSocialSignIn": false
  }
}
```

**Comment by PierreBesson** [comment] 2016-05-18 12:28
I think you mistakenly chose the **clusteredHttpSession** option. What you really want is to use Hazelcast for the **HibernateCache**.
Try to modify the following lines in your .yo-rc.json and generate another gateway.
```
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": "no",
```

You shouldn't choose the **clusteredHttpSession** option when doing gateways ! The gateway is supposed to be stateless and use JWT for auth. This is incompatible with Hazelcast session clustering.
My understanding is that this option concerns only monoliths and doesn't work on gateways since they use tokens and not sessions for auth.

However Hazelcast is supported for **Cache Clustering**. Which means that when you scale your app, their caches will synchronise. This is enabled by Eureka discovery and should also work in Docker Cloud.

@jdubois, @deepu105 Shouldn't the _clusteredHttpSession_ question stop being asked for JWT and OAuth2 authentication types ?

**Comment by jdubois** [comment] 2016-05-18 12:30
Sorry, but your "hibernateCache" is set to "no"....
What you have configured is the session replication using Hazelcast -> we don't have a specific configuration for this like we have for Hibernate, so it only works with multicast. Which means it doesn't work out of the box.
It would be easy to add, then I don't understand why anyone would want to use this -> I'd be very interested by what you want to do.
I'm closing this as this is not a bug. And I wonder if it should be a feature.

**Closed by jdubois** 2016-05-18 12:30 UTC
Labels: microservice

**Comment by jdubois** [comment] 2016-05-18 12:32
Oups 2 comments at the same time! Sorry I'm using my phone...

**Comment by marcelinobadin** [comment] 2016-05-18 12:36
Ok. Thanks. My bad on the configuration. My apps are configured ok, only the gateway I did this mistake. Thank you very much for help @PierreBesson and @jdubois
