### ISSUE TITLE
Model importation failing silently

### ISSUE THREAD

**Issue by Paul-Etienne** [jhipster/generator-jhipster#4840] opened 2017-01-10 16:00 UTC
##### **Overview of the issue**

When running the command `yo jhipster:import-jdl file.jh`, the only result is :

> paulo@paulo-laptop:\~/Documents/...$ yo jhipster:import-jdl file.jh 
The jdl is being imported.
paulo@paulo-laptop:\~/Documents/...$ 

So I am told that the importation is in progress and then nothing.

##### **Motivation for or Use Case**

If this is a repeatable problem to every project with the same configuration, this is a major issue preventing from updating the model. The importation used to work fine with the `jhipster-uml` command.

##### **Reproduce the error**

Create a new folder and install these versions of the modules :

- yeoman: 1.8.5
- bower: 1.8.0
- gulp-cli (last version)
- generator-jhipster@3.4.2

Then, run a `yo jhipster` inside of this folder with the following configuration :

"authenticationType": "session",
"hibernateCache": "ehcache",
"clusteredHttpSession": "no",
"websocket": "no",
"databaseType": "sql",
"devDatabaseType": "h2Disk",
"prodDatabaseType": "postgresql",
"searchEngine": "elasticsearch",
"buildTool": "maven",
"enableSocialSignIn": false,
"useSass": false,
"applicationType": "monolith",
"testFrameworks": [
  "gatling",
  "cucumber",
  "protractor"
],
"enableTranslation": true,
"nativeLanguage": "fr",
"languages": [
  "fr",
  "en"
]

After the installation is complete, create a file.jh containing a simple entity :

entity Person {
	name String,
	age Integer
}

Finally, run the importation command `yo jhipster:import-jdl file.jh`.

##### **Related issues**

The result of the command is the same as in this resolved issue : https://github.com/jhipster/generator-jhipster/issues/3724

##### **JHipster Version(s)**

Here are the versions I am using :
generator-jhipster@3.4.2
java version "1.8.0_74"
Java(TM) SE Runtime Environment (build 1.8.0_74-b02)
Java HotSpot(TM) 64-Bit Server VM (build 25.74-b02, mixed mode)
git version 2.7.4
node: v4.2.6
npm: 3.5.2
bower: 1.8.0
gulp:
[16:09:44] CLI version 3.9.1
[16:09:44] Local version 3.9.1
yeoman: 1.8.5

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

The .yo-rc.json :

{
  "generator-jhipster": {
    "jhipsterVersion": "3.4.2",
    "baseName": "vraiJhipster",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "rememberMeKey": "",
    "useSass": false,
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling",
      "cucumber",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "fr",
    "languages": [
      "fr",
      "en"
    ]
  }
}

##### **Browsers and Operating System**

I am running Ubuntu Mate and using Firefox. A colleague of mine is encountering the same problem on Windows 10 using Chrome.

**Comment by jdubois** [comment] 2017-01-10 17:28
Can you try with the latest version? We've had 8 releases since JHipster 3.4.x, so this might be corrected now.

**Comment by jdubois** [comment] 2017-01-10 17:42
I've just tested it on the master branch, using AngularJS 1 (in the master branch we have the new Angular 2 option), I couldn't reproduce.

As you have an old version, I guess this has been resolved in the mean time.

As the "import-jdl" option isn't very old, you probably have an unstable version -> can you try directly with JHipster UML? As you said, it was working fine, and in fact I've never had any issue with it.

I'm closing this as I can't reproduce, so this is now solved, but please do add comments if it works with JHipster UML, or if you upgrade to a newer release.

**Closed by jdubois** 2017-01-10 17:42 UTC

**Comment by Paul-Etienne** [comment] 2017-01-10 17:54
Le problème est que la commande jhipster-uml ne fonctionne pas non pour
l'importation d'un modèle .jh pour jhipster-uml 2.0.0, cela renvoie une
erreur comme vu sur ce report :
https://github.com/jhipster/jhipster-uml/issues/210

Je vais essayer avec une version plus récente de JHipster plus tard ce soir
ou demain. Je vous tiens au courant.
Le seul souci étant que cela freine le développement de mon équipe et moi
sur notre application, et mettre à jour notre version peut prendre quelques
temps.

2017-01-10 18:42 GMT+01:00 Julien Dubois <notifications@github.com>:

**Comment by deepu105** [comment] 2017-01-10 17:59
English please

Thanks & regards,
Deepu

**Comment by Paul-Etienne** [comment] 2017-01-10 18:07
My apologies, I thought this conversation was only between Julien Dubois
and me.

I was saying that the jhipster-uml command doesn't work either for
importing a model, as stated in this report :
https://github.com/jhipster/jhipster-uml/issues/210 the command doesn't
deal with JDL files anymore.
Which leaves me no command to import my updated model.

I am going to try to reproduce the issue with the latest version of
jhipster as suggested Julien Dubois later today, or tomorrow at the latest.
I will keep you informed.
The only problem being it slows down the development of my team and me, and
upgrading the whole application to the latest version can takes some time.

2017-01-10 18:59 GMT+01:00 Deepu K Sasidharan <notifications@github.com>:

> English please
>
> Thanks & regards,
> Deepu
>

**Comment by pascalgrimaud** [comment] 2017-01-10 18:21
@Paul-Etienne : look old tickets. There are some same issues you mentionned
https://github.com/jhipster/generator-jhipster/issues/3870

I suggest you to use latest version of jhipster.
If you cant, you can look how these old tickets has been resolved and patch your forked projects.

**Comment by Paul-Etienne** [comment] 2017-01-16 08:56
Sorry for the late answer, I've tried running the command `yo jhipster:import-jdl` on a fresh install of the latest version of JHipster (being 3.12.2) and it's working.

My problem is that it's not working on my updated project, I'm having the same issue.
The thing is, there seems to be a problem with the upgrade process as this is the result of a jhipster:info :

##### **JHipster Version(s)**

```
vrai-jhipster@0.0.0 /home/paulo/Documents/path/to/folder
└── generator-jhipster@3.4.2  invalid

```


##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "jhipsterVersion": "3.12.2",
...
```

Apparently, my project is on an invalid version of 3.4.2 and the 3.12.2 isn't fully installed.
@pascalgrimaud Thanks for linking this similar issue, after looking into this, it looks like their fix was to use jhipster-uml, which doesn't work anymore for importing a JDL model sadly.
