### ISSUE TITLE
 Swagger UI adds a :80 to the request url when used with https with Traefik as reverse proxy

### ISSUE THREAD

**Issue by RamjiVE** [jhipster/generator-jhipster#8984] opened 2018-12-24 06:46 UTC
##### **Overview of the issue**

My app is based on an microservice architecture all are running in docker containers with Traefik as a reverse proxy. when I try to request a microservice the request url appends :80 added (https://example.com:80/myService).

When I hit the Try it out! button I get an empty response body and 0 as response code.

If I request without traefik as a reverse proxy it works good for example http://hostname:8080/myService.

Can someone help me , Do I need to add some label for traefik at docker service level without modifying the code. Also if there should be changes in swagger docs what are the changes that I should do?
##### **Motivation for or Use Case**

$ curl -X GET --header 'Accept: */*' --header 'Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImF1dGgiOiJST0xFX0FETUlOLFJPTEVfVVNFUiIsImV4cCI6MTU0NjY4MzA2MH0.f2k8SzKt3vgDS8eUmpS72UyArvDSuN7L2KNz9loEGZWsME-5dDqxiPgW21oTOpW4ZI3nN_8mpzX7gVKvMRR7Ow' 'https://example.com:80/plan'
Request URL
https://example.com:80/plan
Response Body
no content
Response Code
0
Response Headers
{
  "error": "no response from server"
}
##### **Browsers and Operating System**

-   [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by gmarziou** [comment] 2018-12-25 21:20
Looks like a duplicate of  #4036

**Comment by RamjiVE** [comment] 2018-12-26 05:52
@gmarziou . I need a solution without changing the code in swagger basically. Is there a way to change with traefik and docker labels??

**Comment by lmbai** [comment] 2019-01-20 11:09
@RamjiVE hi, may I know your Jhipster version, recently I also find out this issue with the jhipster 3 , but In Jhipster4 (the last jhipster 4 at least) and jhipster 5 , there is no issue with swagger port over the traefik+https

**Comment by lmbai** [comment] 2019-01-20 11:14
@RamjiVE if you a using Jhipster 3, there a 2 solution.
1, u can add add a docker env to hard-code something variable . But I can’t recall the key. It is related to the swagger.

2, you can upgrade the swagger version, the swagger used In jhipster 3 is a bit old. but U need  to update the code a bit to cater for the new version

**Comment by lmbai** [comment] 2019-01-20 12:36
@RamjiVE  pls check 
https://github.com/springfox/springfox/issues/1634
and 
https://stackoverflow.com/questions/33117478/springfox-swagger-generating-requests-with-port-80-for-https-urls
hope it will help. 


`springfox.documentation.swagger.v2.host: hostName:443`

**Closed** 2019-04-25 05:41 UTC
