### ISSUE TITLE
Upgrade Keycloak to v.19

### ISSUE THREAD

**Issue by DanielFran** [jhipster/generator-jhipster#19247] opened 2022-07-27 13:00 UTC
##### **Overview of the feature request**

See https://www.keycloak.org/2022/07/keycloak-1900-released.html
##### **Related issues or PR**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by DanielFran** [comment] 2022-07-27 13:01
cc @vishal423

**Comment by vishal423** [comment] 2022-07-28 19:00
cc @yelhouti as he did the last upgrade

**Comment by vishal423** [comment] 2022-08-04 04:38
No response. I will take a look over weekend

**Comment by vidhya03** [comment] 2022-08-04 04:55
Hi Vishal, @vishal423  Thanks  a lot, i'm interested in this 😀.

**Comment by yelhouti** [comment] 2022-08-04 05:14
Sorry I am on "vacation" I can check it when I get back in few weeks.

**Comment by vishal423** [comment] 2022-08-04 05:28
no worries @yelhouti . @vidhya03  assigned to you

**Comment by vishal423** [comment] 2022-08-04 05:29
@pascalgrimaud, can we put some bounty ?

**Comment by pascalgrimaud** [comment] 2022-08-04 05:46
@vishal423 : sure :-)

**Comment by vidhya03** [comment] 2022-08-07 04:33
Build failure, I wish to  debug the root cause, could you please suggest to how to run these tests locally.   @pascalgrimaud @vishal423

**Comment by mraible** [comment] 2022-08-15 00:32
Increasing bounty to accelerate delivery. 😀

**Comment by yelhouti** [comment] 2022-08-15 07:35
@vidhya03 I'm back from vacation if you are not available to work on this anymore I can take the lead :)

**Comment by vishal423** [comment] 2022-08-15 09:55
@yelhouti, there is an open PR. If you can also contribute to the same, you both can divide the bounty.

**Comment by yelhouti** [comment] 2022-08-15 10:04
@vishal423 There are no change in the first PR as fare as I can tell (except version number), as you might now, there some manual work that needs to be done. ie. export/import the files, change that no changes has been made. Implement some improvement to specified here: https://www.keycloak.org/2022/07/keycloak-1900-released
ex: add the --auto-build flag / remove the optimized (change the docs to explain this...)

**Comment by vidhya03** [comment] 2022-08-15 14:14
@yelhouti  can take the bounty , i am new to this, getting to understand step by step.  i have struck up with the environments configuration.  keycloak bootup  successfully ,  however i tried to setup up the failed tests use case locally,  But stuck with npm install :( , just trying with vscode devcontainer to simulate the use case.

**Comment by yelhouti** [comment] 2022-08-15 17:01
@vidhya03 thanks I will start working on it right away

**Comment by mraible** [comment] 2022-08-17 08:06
@yelhouti I'm happy to test your PR!

**Comment by yelhouti** [comment] 2022-08-17 12:13
@mraible thanks, what I am doing right now is documenting how all this should be done, since its wastes a lot of time to merge every time:
here is some of the doc:

We first generate a new project and run keycloak using docker-compose to import the real exported with the previous version (this should work due to backward compatibility).

Then, we re-export the realm like this: 
```bash
sudo docker exec docker_keycloak_1 /opt/keycloak/bin/kc.sh export --realm jhipster --users realm_file --dir /tmp
sudo docker exec docker_keycloak_1 cat /tmp/jhipster-realm.json | xclip #
```

To easily merge the changes we sort the fields (specifically arrays) in a specific order for an easier comparison, with the help of this function:

```javascript
function sortArraysRecursivelyWithId(x) {
  if (x instanceof Array) {
    x.sort((a, b) => a.id - b.id)
    x.forEach(y => sortArraysRecursivelyWithId(y))
  } else if (x instanceof Object) {
    Object.values(x).forEach(y => sortArraysRecursivelyWithId(y))
  }
}
```
This is because keycloak serializes arrays in a random order which makes looking for changes difficult to do manually or using an idea.

Feedback is appreciated @vishal423

**Comment by vishal423** [comment] 2022-08-22 07:27
I am doubtful about the overall gain and maintenance aspect of the programmatic generation of JSON. I would rather automate the process of applying JHipster customizations on top of the default, however, that's a different aspect and could be done outside the Jhipster codebase as a standalone repository/script.

**Comment by vishal423** [comment] 2022-08-24 01:04
@yelhouti, are you interested to complete this? Otherwise, I will take a look

**Comment by yelhouti** [comment] 2022-08-24 06:36
@vishal423 sorry I forgot to answer you first message, I never talked about generating the full javascript automatically but rather have a json with all the options as the default, then clean it depending on the needs (ex: remove jhipster-registry client when not needed...) which I think is what you mean by "automate the process of applying JHipster customizations on top of the default" if we agree I could fix it today.

**Comment by vishal423** [comment] 2022-08-24 08:57
let's do the upgrade to close this ticket. automation can be done as part of a separate task

**Comment by yelhouti** [comment] 2022-08-25 03:22
I dont this we can skip the automation, exports do Not include passwords (they can't) because some are hashed. We should at least automate setting passwords or document that for the next person upgrading...

**Comment by mraible** [comment] 2022-08-25 04:01
I'd prefer to do it manually like we've done in the past so we can release JHipster 7.9.3. We can also push this upgrade to the next release since it's not necessary.

**Comment by yelhouti** [comment] 2022-08-25 04:05
They are more changes in this Release than the previous One, few fields have been added to the json... If anyone wants to finit manually Please go ahead. I ll automate in the next Release If you want.

**Comment by vishal423** [comment] 2022-08-25 10:29
I will take a look. Thanks @yelhouti

**Closed** 2022-08-27 00:44 UTC
Labels: area: enhancement :wrench:, $$ bug-bounty $$, $300, theme: keycloak
