### ISSUE TITLE
Cannot sign in with default admin:admin and user:user after generated Jhipster api gateway

### ISSUE THREAD

**Issue by patrickHub** [jhipster/generator-jhipster#9255] opened 2019-02-12 17:11 UTC
Here is all the detail on generated api gateway with the  `jhipster info`  command . Please help

`INFO! Using JHipster version installed locally in current project's node_modules
INFO! Executing jhipster:info
INFO! Options: from-cli: true
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
genevahotel@0.0.0 B:\Jhispter Build and Deploy Spring Boot Microservice\projects
`-- generator-jhipster@5.7.2

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
    "generator-jhipster": {
        "promptValues": {
            "packageName": "com.patrickhub.genevahotel"
        },
        "jhipsterVersion": "5.7.2",
        "applicationType": "gateway",
        "baseName": "genevahotel",
        "packageName": "com.patrickhub.genevahotel",
        "packageFolder": "com/patrickhub/genevahotel",
        "serverPort": "8080",
        "authenticationType": "jwt",
        "cacheProvider": "hazelcast",
        "enableHibernateCache": false,
        "websocket": false,
        "databaseType": "sql",
        "devDatabaseType": "h2Disk",
        "prodDatabaseType": "postgresql",
        "searchEngine": false,
        "messageBroker": false,
        "serviceDiscoveryType": "eureka",
        "buildTool": "gradle",
        "enableSwaggerCodegen": false,
        "jwtSecretKey": "",
        "clientFramework": "angularX",
        "useSass": false,
        "clientPackageManager": "npm",
        "testFrameworks": [],
        "jhiPrefix": "jhi",
        "otherModules": [],
        "enableTranslation": false
    }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)

git version 2.11.0.windows.1

node: v10.13.0

npm: 6.4.1

yeoman: 1.8.5

yarn: 1.13.0

Docker version 1.13.0, build 49bf474

docker-compose version 1.10.0, build 4bd6f1a0

`

**Comment by gmarziou** [comment] 2019-02-12 17:44
Few questions:

- have you started the jhipster registry?
- have you looked at server logs and browser console?
- have you tried re-generating your project with latest JHipster?

Also, "\Jhispter Build and Deploy Spring Boot Microservice\projects" is a very long path and could expose you to errors on Windows.

**Comment by patrickHub** [comment] 2019-02-12 18:35
When I started jhipster registry , it discouvert the api gateway with a `status down` I don't know why i get a status down instead of status up. I re-generated one's again but still have the same problem.

**Comment by gmarziou** [comment] 2019-02-12 20:04
What about my 2nd question?

**Comment by patrickHub** [comment] 2019-02-12 20:23
I locked at browser console and i get `not found 404` response after trying to sign in with admin: admin and notihng in server logs

**Comment by gmarziou** [comment] 2019-02-12 22:04
404 for which url and HTTP method? Please give details, copy/paste text or a screenshot.

**Comment by patrickHub** [comment] 2019-02-12 22:09
POST http://localhost:9000/api/authenticate 404 (Not Found)

**Comment by pascalgrimaud** [comment] 2019-02-12 22:12
You need to provide more information to reproduce:
- how do you start the registry
- how do you start the gateway
- logs error
- screenshot
- etc...

Like this, it is impossible to help.

**Comment by gmarziou** [comment] 2019-02-12 22:29
I took your .yo-rc.json, generated a gateway, started it with `gradlew` and did not have any problem to authenticate on http://localhost:8080

**Comment by pascalgrimaud** [comment] 2019-02-12 22:49
Let's close this as we can't reproduce

**Closed** 2019-02-12 22:48 UTC
Labels: microservice, needs-reproduction

**Comment by direstrepo24** [comment] 2020-03-26 00:18
Hi. i created new app, with jhipster 6.8, and i get error pass admin:
##### **JHipster Version(s)**

```
eohelstore@0.0.1-SNAPSHOT /Users/themakers/eohel/eohelstore
└── generator-jhipster@6.8.0 

```


##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**


<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "authenticationType": "jwt",
    "cacheProvider": "hazelcast",
    "clientFramework": "angularX",
    "serverPort": "8081",
    "serviceDiscoveryType": "eureka",
    "skipUserManagement": false,
    "baseName": "eohelstore",
    "buildTool": "maven",
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "enableHibernateCache": true,
    "enableSwaggerCodegen": false,
    "enableTranslation": true,
    "jhiPrefix": "jhi",
    "languages": ["es", "en"],
    "messageBroker": false,
    "nativeLanguage": "es",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "skipClient": false,
    "testFrameworks": ["protractor"],
    "websocket": "spring-websocket",
    "applicationType": "gateway",
    "clientPackageManager": "npm",
    "clientTheme": "none",
    "creationTimestamp": 1585178820828,
    "dtoSuffix": "DTO",
    "embeddableLaunchScript": false,
    "jhipsterVersion": "6.8.0",
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "otherModules": [],
    "packageName": "com.themakers.eohelstore",
    "packageFolder": "com/themakers/eohelstore",
    "skipServer": false,
    "useSass": true,
    "entitySuffix": "",
    "blueprints": []
  },
  "entities": [
    "AbonoFactura",
    "Categoria",
    "ConfigEmpresa",
    "ElementoLista",
    "Empresa",
    "Factura",
    "FacturaDetalle",
    "FacturaEmpresa",
    "FacturaNota",
    "FacturaNotaDetalle",
    "Movimiento",
    "MovimientoDetalle",
    "NotaTipo",
    "Notification",
    "Pago",
    "PrecioProducto",
    "Producto",
    "ProductoAtributo",
    "ProductoPromocion",
    "Promocion",
    "Stock",
    "Sucursal",
    "Suscripcion",
    "Tercero",
    "TipoLista",
    "Usuario"
  ]
}

</pre>
</details>


##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity AbonoFactura {
  userId Long,
  fecha Instant required,
  codigo String required,
  valor BigDecimal required
}
entity Categoria {
  nombre String required,
  descripcion String,
  image ImageBlob,
  empresaId Long
}
entity ConfigEmpresa {
  version Integer required,
  nombre String required
}
entity ElementoLista {
  nombre String required maxlength(200),
  codigo String required maxlength(5),
  propiedades AnyBlob
}
entity Empresa {
  nit String required,
  nombre String required,
  logo String,
  numDocumento String,
  representante String,
  usuario Long required
}
/**
 * Factura sold by the Online store
 */
entity Factura {
  fecha Instant required,
  codigo String,
  sucursalId Long,
  fechaPago Instant required,
  metodoPagoId Long,
  empresaId Long required,
  userId Long,
  tipoFacturaId Long,
  valor BigDecimal required
}
entity FacturaDetalle {
  productoId Long required,
  codigoProducto String,
  nombreProducto String,
  precioUnitario BigDecimal required,
  cantidad Long required min(0)
}
entity FacturaEmpresa {
  precio BigDecimal required,
  fechaEmision Instant required,
  fechaLimite Instant required
}
entity FacturaNota {
  fechacreacion Instant required,
  motivo String
}
entity FacturaNotaDetalle {
  descripcion String required,
  cantidad Integer,
  valor BigDecimal min(0)
}
entity Movimiento {
  motivo String,
  tipoMovimientoId Long required,
  fecha Instant required,
  sucursalId Long required,
  sucursalrecibeId Long,
  empresaId Long required,
  estadoMovimientoId Long required
}
entity MovimientoDetalle {
  codigoProducto String,
  nombreProducto String,
  cantidad Long required min(0)
}
entity NotaTipo {
  nombre String required
}
entity Notification {
  date Instant required,
  details String,
  sentDate Instant required,
  format NotificationType required,
  userId Long required,
  productId Long required,
  empresaId Long required
}
entity Pago {
  fechaPago Instant required,
  correo String required,
  docIdentificacion String required,
  celular String required
}
entity PrecioProducto {
  precio BigDecimal,
  activo Boolean,
  nombre String required
}
/**
 * Product sold by the Online store
 */
entity Producto {
  nombre String required,
  descripcion String,
  precioCompra BigDecimal required min(0),
  precioVenta BigDecimal required min(0),
  codigobar String,
  imagen String,
  empresaId Long required,
  estadoId Long required,
  estadoProductoId Long required
}
entity ProductoAtributo {
  atributo String,
  valor String
}
entity ProductoPromocion {
  estado Boolean,
  fechainicio Instant required,
  fechafinal Instant required
}
entity Promocion {
  nombre String required,
  porcentaje BigDecimal min(0)
}
entity Stock {
  cantidad Long required min(0),
  sucursalId Long
}
entity Sucursal {
  nombre String required,
  direccion String required
}
entity Suscripcion {
  fechaCreacion Instant required,
  fechaInicio Instant required,
  fechaFin Instant required
}
entity Tercero {
  nombre String required,
  apellido String required,
  nit String required,
  celular String,
  email String required pattern(/^[^@\s]+@[^@\s]+\.[^@\s]+$/),
  direccion1 String required,
  direccion2 String,
  empresaId Long,
  cuidadId Long,
  paisId Long,
  tipoTerceroId Long
}
entity TipoLista {
  nombre String required,
  descripcion String maxlength(500)
}
/**
 * Usuario sold by the gateway inbuk
 */
entity Usuario {
  segundoNombre String,
  segundoApellido String,
  numDocumento String required maxlength(15),
  celular String required,
  direccion String
}
enum NotificationType {
  EMAIL,
  SMS,
  PARCEL
}

relationship OneToOne {
  Pago{factura} to FacturaEmpresa,
  Suscripcion{empresa} to Empresa,
  Usuario{user required} to User
}
relationship OneToMany {
  Factura{abonoFactura} to AbonoFactura{factura},
  Factura{facturaDetalle} to FacturaDetalle{factura},
  Movimiento{movimientoDetalle} to MovimientoDetalle{movimiento},
  Categoria{producto} to Producto{productCategoria(nombre)},
  Producto{productoAtributo} to ProductoAtributo{producto(nombre)},
  Empresa{sucursal} to Sucursal{empresa(nombre)}
}
relationship ManyToOne {
  ElementoLista{tipoLista(nombre) required} to TipoLista,
  ElementoLista{padre(nombre)} to ElementoLista,
  Empresa{cuidad(nombre) required} to ElementoLista,
  Empresa{estado(nombre) required} to ElementoLista,
  Empresa{tipoDocumento(nombre) required} to ElementoLista,
  Factura{tercero(nit)} to Tercero,
  FacturaEmpresa{metodoPago(nombre) required} to ElementoLista,
  FacturaEmpresa{estadoFactura(nombre) required} to ElementoLista,
  FacturaEmpresa{empresa(nombre)} to Empresa,
  FacturaNota{factura required} to Factura,
  FacturaNota{notaTipo(nombre) required} to NotaTipo,
  FacturaNotaDetalle{facturaNota required} to FacturaNota,
  MovimientoDetalle{producto(nombre)} to Producto,
  Pago{estado(nombre) required} to ElementoLista,
  Pago{tipoPersona(nombre) required} to ElementoLista,
  PrecioProducto{producto(nombre) required} to Producto,
  ProductoPromocion{producto(nombre) required} to Producto,
  ProductoPromocion{promocion(nombre) required} to Promocion,
  Stock{producto(nombre)} to Producto,
  Suscripcion{estado(nombre) required} to ElementoLista,
  TipoLista{padre(nombre)} to TipoLista,
  Usuario{cuidad(nombre) required} to ElementoLista,
  Usuario{categoria(nombre) required} to ElementoLista
}

dto AbonoFactura, Categoria, ConfigEmpresa, ElementoLista, Empresa, Factura, FacturaDetalle, FacturaEmpresa, FacturaNota, FacturaNotaDetalle, Movimiento, MovimientoDetalle, NotaTipo, Notification, Pago, PrecioProducto, Producto, ProductoAtributo, ProductoPromocion, Promocion, Stock, Sucursal, Suscripcion, Tercero, TipoLista, Usuario with mapstruct
paginate AbonoFactura, Categoria, ConfigEmpresa, ElementoLista, Empresa, Factura, FacturaDetalle, FacturaEmpresa, FacturaNota, FacturaNotaDetalle, Movimiento, MovimientoDetalle, NotaTipo, Notification, Pago, PrecioProducto, Producto, ProductoAtributo, ProductoPromocion, Promocion, Stock, Sucursal, Suscripcion, Tercero, TipoLista, Usuario with pagination
service AbonoFactura, Categoria, ConfigEmpresa, ElementoLista, Empresa, Factura, FacturaDetalle, FacturaEmpresa, FacturaNota, FacturaNotaDetalle, Movimiento, MovimientoDetalle, NotaTipo, Notification, Pago, PrecioProducto, Producto, ProductoAtributo, ProductoPromocion, Promocion, Stock, Sucursal, Suscripcion, Tercero, TipoLista, Usuario with serviceClass
microservice AbonoFactura, Factura, FacturaDetalle, FacturaNota, FacturaNotaDetalle, NotaTipo, Tercero with facturamicroservicio
microservice Categoria, Movimiento, MovimientoDetalle, PrecioProducto, Producto, ProductoAtributo, ProductoPromocion, Promocion, Stock with inventariomicroservicio
microservice Notification with notification
filter AbonoFactura, Categoria, ConfigEmpresa, ElementoLista, Empresa, Factura, FacturaDetalle, FacturaEmpresa, FacturaNota, FacturaNotaDetalle, Movimiento, MovimientoDetalle, NotaTipo, Notification, Pago, PrecioProducto, Producto, ProductoAtributo, ProductoPromocion, Promocion, Stock, Sucursal, Suscripcion, Tercero, TipoLista, Usuario
clientRootFolder FacturaNota, FacturaNotaDetalle, NotaTipo with facturamicroservicio
clientRootFolder PrecioProducto, ProductoPromocion, Promocion with inventariomicroservicio

</pre>
</details>


##### **Environment and Tools**

openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.6+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.6+10, mixed mode)

git version 2.21.1 (Apple Git-122.3)

node: v12.14.1

npm: 6.14.3

yeoman: 3.1.1

yarn: 1.21.1

Docker version 19.03.5, build 633a0ea

docker-compose version 1.25.4, build 8d51620a

**Comment by direstrepo24** [comment] 2020-03-26 00:27
I have checked the database and it does not insert the initial user data loaded in liquidbase data, what can I do?

**Comment by xniti3x** [comment] 2021-11-02 20:05
you can reproduce the issue if you generate a (standard) jhipster project in gitpod.io  i get the exact same problem , cant login with default credentials admin/admin or user/user  

terminal:
2021-11-02 19:30:58.806  WARN 2212 --- [  XNIO-1 task-1] o.z.problem.spring.common.AdviceTraits   : Unauthorized: Full authentication is required to access this resource
2021-11-02 19:30:58.808  WARN 2212 --- [  XNIO-1 task-1] .m.m.a.ExceptionHandlerExceptionResolver : Resolved [org.springframework.security.authentication.InsufficientAuthenticationException: Full authentication is required to access this resource]

browser console:
GET https://8080-cyan-flamingo-user73s0aai.ws-eu17.gitpod.io/api/account 401 zone.js:2863 
GET https://8080-cyan-flamingo-user73s0aai.ws-eu17.gitpod.io/manifest.webapp 401 manifest.webapp:1


when i tried it on local environment it works fine.

**Comment by freemo** [comment] 2023-04-10 03:22
I had this same issue in 2023, happens on all my computers and on all newly generated projects.

The issue with these specific symptoms happens when you are running through docker and dont have "keycloak" in your hosts file and resolving to localhost. Once I added that everything worked.

**Comment by Rockflo** [comment] 2024-01-12 13:13
I had this same issue in 2024, after having generated a microservice application without database. I will have to customize the security config myself to make it works again.

**Comment by scarabetta** [comment] 2024-02-09 15:50
I forgot I've added keycloak to my hosts file, thus I needed to navigate to "http://keycloack:8080" instead of localhost, and it worked
