### ISSUE TITLE
No errors from import-jdl - part 2

### ISSUE THREAD

**Issue by imod** [jhipster/generator-jhipster#3870] opened 2016-07-22 13:41 UTC
trying to run `yo jhipster:import-jdl ./jhipster-jdl.jh` but nothing happens...

```
enum IssueSourceType {
    JIRA, GITHUB, BITBUCKET
}

entity IssueRepo {
  name String,
  url String required,
  sourceType IssueSourceType required
}
```

output:
```
$> yo jhipster:import-jdl jhipster-jdl.jh 
The jdl is being parsed.
$>
```

using jhipster 3.5.0

**Comment by jdubois** [comment] 2016-07-22 13:43
I confirm the issue.... And it works with JHipster UML.

With #3871 that's the second major issue with this sub-generator, shouldn't we remove it again?

**Comment by MathieuAA** [comment] 2016-07-22 13:58
@deepu105, can you add a try-catch when you use the core project in your subgen?

**Comment by MathieuAA** [comment] 2016-07-22 14:21
@jdubois, I don't think we should. Not right now anyway. Let's wait until tomorrow. If it's not fixed, then we have to remove it again.

**Comment by jdubois** [comment] 2016-07-22 15:21
@MathieuAA OK, anyway there's an easy work-around in this ticket, but still we would need to warn users

**Comment by MathieuAA** [comment] 2016-07-22 15:49
Agreed.

**Comment by deepu105** [comment] 2016-07-22 16:05
guys I dont think its an issue with the sub generator at all. please wait until i confirm

**Comment by jdubois** [comment] 2016-07-22 16:07
Can you reproduce the issue?

Le 22 juil. 2016 6:05 PM, "Deepu K Sasidharan" <notifications@github.com> a
écrit :

**Comment by deepu105** [comment] 2016-07-22 16:08
also no errors being throws seems to be some issue from yo itself. @imod what is the `yo` version and node versions you use? can you please follow the issue guidelines and give all required details.

**Comment by pascalgrimaud** [comment] 2016-07-22 16:12
Just have a very quick look

it seems the error comes from this line:
https://github.com/jhipster/jhipster-core/blob/master/lib/parser/jdl_parser.js#L111-L115

In this case, the test is true, with type=IssueSourceType, type=required
-> `The validation required isn't supported for the type IssueSourceType.`

Sorry, I'm noob with JDL/JUML... I hope it will help a little bit

**Comment by MathieuAA** [comment] 2016-07-22 16:37
Ok, what the hell is IssyeSourceType? 

Le 22 juillet 2016 18:12:25 GMT+02:00, Pascal Grimaud <notifications@github.com> a écrit :
>Just have a very quick look
>
>it seems the error comes from this line:
>https://github.com/jhipster/jhipster-core/blob/master/lib/parser/jdl_parser.js#L111-L115
>
>In this case, the test is true, with type=IssueSourceType,
>type=required
>-> `The validation required isn't supported for the type
>IssueSourceType.`
>
>Sorry, I'm noob with JDL/JUML... I hope it will help a little bit
>
>---
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/jhipster/generator-jhipster/issues/3870#issuecomment-234586834

-- 
Mathieu ABOU-AICHI

**Comment by deepu105** [comment] 2016-07-22 16:38
Actually Im noticing this behavior recently with newer yo versions. The error messages are not printed on the console at all irrespective of the generator. I thought it as some issue in my environment. @imod are you on windows?

**Comment by deepu105** [comment] 2016-07-22 16:38
@MathieuAA `IssyeSourceType` is the name of the enum @imod had in the JDL

**Comment by MathieuAA** [comment] 2016-07-22 17:07
Ok, so `required` isn't available for enums... I'll fix it and release. Thanks.

**Comment by MathieuAA** [comment] 2016-07-22 17:35
v1.1.2 is released.

**Comment by jdubois** [comment] 2016-07-22 17:41
@MathieuAA so for you all this is solved? Can you close the issues? I'll do a release during the week-end (I need time to test before)

**Comment by deepu105** [comment] 2016-07-22 17:42
I'm gonna update the lib and test. will close the issue after that


Thanks & Regards,
Deepu

**Comment by MathieuAA** [comment] 2016-07-22 17:53
For me, yes. Or my tests suck. I hope they don't... the problem was that I passed the type name EVERYTIME, even when the type is an enum. It's pretty silly, right?

**Comment by deepu105** [comment] 2016-07-22 18:02
i have added a try catch as well

**Closed** 2016-07-22 18:03 UTC
Labels: bug, JDL, major

**Comment by imod** [comment] 2016-07-24 10:23
Sorry, i'm currently only limited online...
But no, I'm not on windows but Mac
