### ISSUE TITLE
Microservice API 403 error Only with Chrome

### ISSUE THREAD

**Issue by clong365** [jhipster/generator-jhipster#3793] opened 2016-06-29 17:20 UTC
##### **Overview of the issue**

I'm using Fetch API to make requests to both gateway and a microservice.
cros request to gateway is ok. but when request to a microservice:

Fetch API cannot load http://localhost:8080/question/api/questions/. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access. The response had HTTP status code 403. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

I have tried with Chrome and IE(Edge), It is happened only in Chrome.

The gateway and microservice have the same jwt.secret key with the default value:my-secret-token-to-change-in-production.

##### **JHipster Version(s)** 

3.4.2

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 

gateway:

{
  "generator-jhipster": {
    "jhipsterVersion": "3.4.2",
    "baseName": "gateway",
    "packageName": "net.jiean.iedu",
    "packageFolder": "net/jiean/iedu",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "no",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": "no",
    "buildTool": "maven",
    "jwtSecretKey": "fcf9c09628f220d8913e4ed33e2473c7b4145104",
    "useSass": false,
    "applicationType": "gateway",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}

microservice:

{
  "generator-jhipster": {
    "jhipsterVersion": "3.4.2",
    "baseName": "question",
    "packageName": "net.jiean.iedu",
    "packageFolder": "net/jiean/iedu",
    "serverPort": "8082",
    "authenticationType": "jwt",
    "hibernateCache": "no",
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": "no",
    "buildTool": "maven",
    "jwtSecretKey": "3e87dfdbb8550dbc5db1c7d7a3c3b7e8b55a3230",
    "enableTranslation": false,
    "applicationType": "microservice",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "skipClient": true,
    "skipUserManagement": true
  }
}

##### **Browsers and Operating System** 

Chrome/51.0.2704.103

**Comment by jdubois** [comment] 2016-06-29 17:41
Yes, if you want CORS (which I wouldn't recommend) we have an out-of-the-box configuration in the application-*.yml files.

This is not a bug so I'm closing this, please use Stackoverflow.

**Comment by clong365** [comment] 2016-06-29 19:25
I certainly opened the cors config in yml files. The problem is IE can issue the cors request as expected,but Chrome not.

**Comment by cbornet** [comment] 2016-06-29 20:00
This is because the cors apply for path ```/api/**``` and the requests are made on ```/question/api/**```. The CORS filter should be adapted for the gateway. Browsers have varying behavior when it comes to GET CORS request but a POST should also fail with IE.

**Comment by cbornet** [comment] 2016-06-29 20:03
@clong365 Can you try to add the line
```
source.registerCorsConfiguration("/question/api/**", config);
```
to the CORS filter [here](https://github.com/jhipster/generator-jhipster/blob/master/generators/server/templates/src/main/java/package/config/_WebConfigurer.java#L203) and tell us if it works ?

**Comment by clong365** [comment] 2016-06-30 07:05
@cbornet 

Since my Question microservice run on port 8082, it does not serve url http://localhost:8082/question/api/questions.

My gateway run on port 8080, and it sends request from http://localhost:8080/question/api/questions to http://localhost:8082/api/question

So,  when I add the line above to WebConifgurer in gateway only, the resoponse error message:

Fetch API cannot load http://localhost:8080/question/api/questions/. The 'Access-Control-Allow-Origin' header contains **multiple values 'http://localhost:3000, http://localhost:3000'**, but only one is allowed. Origin 'http://localhost:3000' is therefore not allowed access. Have the server send the header with a valid value, or, if an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

I also tried to add the line to WebConfigurer in question service only(remove from gateway) ,and restart question service, it does not work. But when i restart gateway, the GET request successed,but POST is failed.

My client run on port 3000, it access gateway and microservice both cross domains. Why the gateway is correct, and the microservice is on the contray.

**Comment by cbornet** [comment] 2016-06-30 07:50
See #3318. You need to activate the CORS filter either on the gateway or on the micro-services but not on both. Can you try and confirm ?

**Comment by clong365** [comment] 2016-06-30 08:09
Thanks! 

It works so well now.

**Comment by cbornet** [comment] 2016-06-30 08:18
Can you try
```
source.registerCorsConfiguration("/*/api/**", config);
```
in the gateway instead of 
```
source.registerCorsConfiguration("/question/api/**", config);
```
This would make a generic solution that we can put in the template.

**Comment by clong365** [comment] 2016-06-30 09:24
Sure, I have took the advice from #3318 .

**Comment by cbornet** [comment] 2016-06-30 10:00
Just to be sure : does adding ```source.registerCorsConfiguration("/*/api/**", config);``` to the gateway cors filter solve your issue ?

**Comment by clong365** [comment] 2016-06-30 10:19
Yes

1. Open the cors config in application.yml of gateway, close cors config(keep as default untouched) of microservice.

1. Add `source.registerCorsConfiguration("/*/api/**", config)` to the gateway cors filter, and keep microservice cors filter as untouched too.

**Comment by cbornet** [comment] 2016-06-30 10:27
Thanks. Would you do a PR for this ?

**Comment by jdubois** [comment] 2016-06-30 22:08
Closing this as the PR is merged, thanks for reporting the bug, testing, and doing the PR!! I don't have anything to do anymore :-)

**Closed by jdubois** 2016-06-30 22:08 UTC
