### ISSUE TITLE
Jhipster App having Mysql DB Won't start.

### ISSUE THREAD

**Issue by selmantayyar** [jhipster/generator-jhipster#3991] opened 2016-08-16 19:54 UTC
##### **Overview of the issue**

I have jhipster application using Mysql as database. When I try to deploy it to Heroku and then i run it I get the exception below:

Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSource' defined in class path resource [com/saen/offer/config/HerokuDatabaseConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.sql.DataSource]: Factory method 'dataSource' threw exception; nested exception is org.springframework.context.ApplicationContextException: Heroku data
 base URL is not configured, you must set $JDBC_DATABASE_URL

##### **Motivation for or Use Case**

Application does not start up.

##### **Related issues**

Couldn't find one.

##### **JHipster Version(s)**

```
offer-manager@0.0.0 /Users/selmantayyar/Documents/OfferManager
└── generator-jhipster@3.5.1 

<!-- to provide all information we need, you can use: yo jhipster:info -->
<!-- which version of Jhipster are you using, is it a regression? -->

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "jhipsterVersion": "3.5.1",
    "baseName": "OfferManager",
    "packageName": "com.saen.offer",
    "packageFolder": "com/saen/offer",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "mysql",
    "searchEngine": "no",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "rememberMeKey": "ab1f155826b30dc687b5f39403c622d5e3ce93a6",
    "useSass": false,
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

OfferLead.json
{
    "relationships": [
        {
            "relationshipName": "taskType",
            "otherEntityName": "taskType",
            "relationshipType": "many-to-one",
            "relationshipValidateRules": [],
            "otherEntityField": "name"
        }
    ],
    "fields": [
        {
            "fieldName": "name",
            "fieldType": "String",
            "fieldValidateRules": []
        },
        {
            "fieldName": "surname",
            "fieldType": "String"
        },
        {
            "fieldName": "email",
            "fieldType": "String",
            "fieldValidateRules": []
        },
        {
            "fieldName": "telephoneNumber",
            "fieldType": "String",
            "fieldValidateRules": []
        },
        {
            "fieldName": "postcode",
            "fieldType": "String",
            "fieldValidateRules": []
        },
        {
            "fieldName": "houseNumber",
            "fieldType": "String"
        },
        {
            "fieldName": "street",
            "fieldType": "String"
        },
        {
            "fieldName": "city",
            "fieldType": "String"
        },
        {
            "fieldName": "ageOfBuilding",
            "fieldType": "String"
        },
        {
            "fieldName": "expectedRenovationDate",
            "fieldType": "LocalDate",
            "fieldValidateRules": []
        },
        {
            "fieldName": "wallArea",
            "fieldType": "BigDecimal",
            "fieldValidateRules": []
        },
        {
            "fieldName": "ceilingArea",
            "fieldType": "BigDecimal"
        },
        {
            "fieldName": "housePlan",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "image"
        },
        {
            "fieldName": "offerDocument",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "any"
        },
        {
            "fieldName": "description",
            "fieldType": "String"
        },
        {
            "fieldName": "source",
            "fieldType": "String"
        }
    ],
    "changelogDate": "20160802173140",
    "dto": "no",
    "service": "serviceImpl",
    "entityTableName": "offer_lead",
    "pagination": "pager"
}
TaskType.json
{
    "relationships": [],
    "fields": [
        {
            "fieldName": "name",
            "fieldType": "String",
            "fieldValidateRules": []
        },
        {
            "fieldName": "wallPrice",
            "fieldType": "BigDecimal",
            "fieldValidateRules": []
        },
        {
            "fieldName": "ceilingPrice",
            "fieldType": "BigDecimal"
        }
    ],
    "changelogDate": "20160802173755",
    "dto": "no",
    "service": "serviceImpl",
    "entityTableName": "task_type",
    "pagination": "no"
}

##### **Browsers and Operating System**

java version "1.8.0_25"
Java(TM) SE Runtime Environment (build 1.8.0_25-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.25-b02, mixed mode)

git version 2.7.4 (Apple Git-66)

node: v6.3.1

npm: 3.10.3

bower: 1.7.9

gulp:
[21:52:16] CLI version 3.9.1
[21:52:16] Local version 3.9.1

yeoman: 1.8.4

##### **Browsers and Operating System**

Mac OSx 10.11.6

**Comment by jdubois** [comment] 2016-08-16 20:45
- not sure if Node.JS 6.x works, as this is not a stable version (we always recommend LTS versions) -> this should be OK, I guess you would have other errors
- did you use the Heroku sub-generator? Did you have any errors when running it?
- in Heroku, do you see your MySQL database configured and bound to your application?
- Heroku comes with Postgresql, we can't test with MySQL as we must pay an external party for that. As the only provider I know is ClearDB, is it the one you are using?
- Besides, I think ClearDB uses an older (4.5) version of MySQL, and we had an issue with it -> once this is solved, if you get an error with a timestamp (or something like this) in the "user" table, don't hesitate to open up another ticket

cc @jkutner as he's our Heroku master!

**Comment by selmantayyar** [comment] 2016-08-16 21:01
Thanks for the quick reply.

I was somehow under the impression that Mysql was going to be provisioned automatically via jhipster:heroku subgenerator. Anyway, I have provisioned it manually using 'heroku addons:create cleardb:ignite' command and this problem is solved. Thanks again.

Now,as you have already predicted,I am getting an error about user table. _**com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'heroku_f1269695394e25b.jhi_user' doesn't exist**_

I will open a separate ticket for that. Meanwhile,I am a bit hurry to deploy my application to a public server.Do you recommend to switch to Postgre,or something else?

Cheers

**Comment by jkutner** [comment] 2016-08-16 21:04
The `yo jhipster:heroku` subgenerator should provision a [JawsDB MySQL](https://elements.heroku.com/addons/jawsdb) add-on. 

Can you try removing the cleardb add-on and running the subgenerator again, then share the subgenerator's output?

**Comment by ruddell** [comment] 2016-08-16 21:13
@selmantayyar I was able to deploy an app using your configuration and entities, along with MySQL.  It added a JawsDB MySQL like @jkutner said.

https://pacific-sierra-21802.herokuapp.com/#/

**Comment by selmantayyar** [comment] 2016-08-16 21:20
Below is the output i get. And i still get the following exception when i start the app.

```
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSource' defined in class path resource [com/saen/offer/config/HerokuDatabaseConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.sql.DataSource]: Factory method 'dataSource' threw exception; nested exception is org.springframework.context.ApplicationContextException: Heroku data
base URL is not configured, you must set $JDBC_DATABASE_URL
```

Output of heroku subgenerator:
```
selmans-iMac:OfferManager selmantayyar$ yo jhipster:heroku
Heroku configuration is starting
? Name to deploy as: OfferManager
? On which region do you want to deploy ? eu

Using existing Git repository

Installing Heroku CLI deployment plugin
Installing https://github.com/heroku/heroku-deploy... 
done


Creating Heroku application and setting up node environment
heroku create offer-manager --region eu --addons jawsdb:kitefin

? The Heroku app "offer-manager" already exists! Use it anyways? Yes, I have access to it
set git remote heroku to https://git.heroku.com/offer-manager.git


Creating Heroku deployment files
identical src/main/java/com/saen/offer/config/HerokuDatabaseConfiguration.java
identical src/main/resources/config/bootstrap-heroku.yml
identical src/main/resources/config/application-heroku.yml
 conflict Procfile
? Overwrite Procfile? overwrite
    force Procfile

Building application
[INFO] Scanning for projects...

[INFO]                                                                         

[INFO] ------------------------------------------------------------------------
[INFO] Building Offer Manager 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------

[INFO] 


[INFO] --- maven-resources-plugin:3.0.0:copy-resources (default-resources) @ offer-manager ---


[INFO] Using 'UTF-8' encoding to copy filtered resources.

[INFO] ignoreDelta true

[INFO] Copying 12 resources

[INFO] Copying file config/application-dev.yml

[INFO] Copying file config/application-heroku.yml

[INFO] Copying file config/application-prod.yml

[INFO] Copying file config/application.yml

[INFO] Copying file config/bootstrap-heroku.yml

[INFO] Copying file config/liquibase/changelog/00000000000000_initial_schema.xml

[INFO] Copying file config/liquibase/changelog/20160802173140_added_entity_constraints_OfferLead.xml

[INFO] Copying file config/liquibase/changelog/20160802173140_added_entity_OfferLead.xml

[INFO] Copying file config/liquibase/changelog/20160802173755_added_entity_TaskType.xml

[INFO] Copying file config/liquibase/master.xml

[INFO] Copying file ehcache.xml

[INFO] Copying file logback-spring.xml

[INFO] ignoreDelta true

[INFO] Copying 12 resources
[INFO] Copying file .h2.server.properties

[INFO] Copying file banner.txt


[INFO] Copying file config/liquibase/authorities.csv

[INFO] Copying file config/liquibase/users.csv


[INFO] Copying file config/liquibase/users_authorities.csv

[INFO] Copying file i18n/messages.properties

[INFO] Copying file mails/activationEmail.html

[INFO] Copying file mails/creationEmail.html
[INFO] Copying file mails/passwordResetEmail.html
[INFO] Copying file offerte_template.doc
[INFO] Copying file templates/algemene_voorwaarden.pdf
[INFO] Copying file templates/error.html

[INFO] 

[INFO] --- maven-resources-plugin:3.0.0:resources (default-resources) @ offer-manager ---

[INFO] Using 'UTF-8' encoding to copy filtered resources.

[INFO] ignoreDelta true

[INFO] Copying 12 resources


[INFO] Copying file config/application-dev.yml


[INFO] Copying file config/application-heroku.yml

[INFO] Copying file config/application-prod.yml

[INFO] Copying file config/application.yml

[INFO] Copying file config/bootstrap-heroku.yml


[INFO] Copying file config/liquibase/changelog/00000000000000_initial_schema.xml


[INFO] Copying file config/liquibase/changelog/20160802173140_added_entity_constraints_OfferLead.xml

[INFO] Copying file config/liquibase/changelog/20160802173140_added_entity_OfferLead.xml

[INFO] Copying file config/liquibase/changelog/20160802173755_added_entity_TaskType.xml

[INFO] Copying file config/liquibase/master.xml

[INFO] Copying file ehcache.xml


[INFO] Copying file logback-spring.xml

[INFO] ignoreDelta true


[INFO] Copying 12 resources


[INFO] Copying file .h2.server.properties


[INFO] Copying file banner.txt

[INFO] Copying file config/liquibase/authorities.csv
[INFO] Copying file config/liquibase/users.csv
[INFO] Copying file config/liquibase/users_authorities.csv
[INFO] Copying file i18n/messages.properties
[INFO] Copying file mails/activationEmail.html
[INFO] Copying file mails/creationEmail.html
[INFO] Copying file mails/passwordResetEmail.html
[INFO] Copying file offerte_template.doc
[INFO] Copying file templates/algemene_voorwaarden.pdf
[INFO] Copying file templates/error.html

[INFO] 

[INFO] --- maven-enforcer-plugin:1.4.1:enforce (enforce-versions) @ offer-manager ---

[INFO] 
[INFO] --- jacoco-maven-plugin:0.7.6.201602180812:prepare-agent (pre-unit-tests) @ offer-manager ---

[INFO] surefireArgLine set to -javaagent:/Users/selmantayyar/.m2/repository/org/jacoco/org.jacoco.agent/0.7.6.201602180812/org.jacoco.agent-0.7.6.201602180812-runtime.jar=destfile=/Users/selmantayyar/Documents/OfferManager/target/test-results/coverage/jacoco/jacoco.exec

[INFO] 
[INFO] --- maven-processor-plugin:2.2.4:process (process) @ offer-manager ---

[INFO] 


[INFO] --- frontend-maven-plugin:1.0:install-node-and-npm (install node and npm) @ offer-manager ---


[INFO] Node v4.4.7 is already installed.

[INFO] NPM 3.10.5 is already installed.

[INFO] 
[INFO] --- frontend-maven-plugin:1.0:npm (npm install) @ offer-manager ---

[INFO] Running 'npm install' in /Users/selmantayyar/Documents/OfferManager


[INFO] 
[INFO] --- frontend-maven-plugin:1.0:bower (bower install) @ offer-manager ---

[INFO] Running 'bower install --no-color' in /Users/selmantayyar/Documents/OfferManager

[ERROR] bower angular-cookies extra-resolution Unnecessary resolution: angular-cookies#1.5.5

[INFO] 

[INFO] --- frontend-maven-plugin:1.0:gulp (gulp build) @ offer-manager ---

[INFO] Running 'gulp.js build --no-notification' in /Users/selmantayyar/Documents/OfferManager

[INFO] [23:12:49] Using gulpfile ~/Documents/OfferManager/gulpfile.js

[INFO] [23:12:49] Starting 'clean'...

[INFO] [23:12:49] Finished 'clean' after 89 ms

[INFO] [23:12:49] Starting 'build'...

[INFO] [23:12:49] Starting 'copy'...


[INFO] [23:12:49] Starting 'inject:vendor'...


[INFO] [23:12:50] Starting 'ngconstant:prod'...

[INFO] [23:12:50] Finished 'ngconstant:prod' after 227 ms


[INFO] [23:12:50] gulp-inject 18 files into index.html.

[INFO] [23:12:50] Finished 'inject:vendor' after 553 ms


[INFO] [23:12:50] Finished 'copy' after 624 ms

[INFO] [23:12:50] Starting 'inject:app'...

[INFO] [23:12:51] gulp-inject 106 files into index.html.


[INFO] [23:12:51] Finished 'inject:app' after 447 ms

[INFO] [23:12:51] Starting 'inject:troubleshoot'...


[INFO] [23:12:51] gulp-inject Nothing to inject into index.html.

[INFO] [23:12:51] Finished 'inject:troubleshoot' after 29 ms

[INFO] [23:12:51] Starting 'images'...

[INFO] [23:12:51] Starting 'styles'...


[INFO] [23:12:51] Starting 'html'...


[INFO] [23:12:51] Starting 'swagger-ui'...

[INFO] [23:12:51] Finished 'styles' after 27 ms


[INFO] [23:12:52] Finished 'html' after 1.02 s

[INFO] [23:12:52] Finished 'swagger-ui' after 1.06 s

[INFO] [23:12:52] gulp-imagemin: Minified 6 images (saved 9.19 kB - 5.3%)

[INFO] [23:12:52] Finished 'images' after 1.67 s

[INFO] [23:12:52] Starting 'assets:prod'...

[INFO] [23:13:16] Finished 'assets:prod' after 24 s

[INFO] [23:13:16] Finished 'build' after 26 s

[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ offer-manager ---

[INFO] Changes detected - recompiling the module!

[INFO] Compiling 101 source files to /Users/selmantayyar/Documents/OfferManager/target/classes

[INFO] 

[INFO] --- maven-resources-plugin:3.0.0:testResources (default-testResources) @ offer-manager ---

[INFO] Using 'UTF-8' encoding to copy filtered resources.

[INFO] ignoreDelta true

[INFO] Copying 3 resources
[INFO] Copying file config/application.yml

[INFO] Copying file ehcache.xml


[INFO] Copying file logback-test.xml

[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ offer-manager ---

[INFO] Nothing to compile - all classes are up to date

[INFO] 
[INFO] --- maven-surefire-plugin:2.18.1:test (default-test) @ offer-manager ---

[INFO] Tests are skipped.

[INFO] 
[INFO] --- jacoco-maven-plugin:0.7.6.201602180812:report (post-unit-test) @ offer-manager ---

[INFO] Analyzed bundle 'Offer Manager' with 113 classes

[INFO] 
[INFO] --- frontend-maven-plugin:1.0:gulp (gulp test) @ offer-manager ---

[INFO] Skipping test phase.

[INFO] 
[INFO] --- maven-war-plugin:2.5:war (default-war) @ offer-manager ---

[INFO] Packaging webapp

[INFO] Assembling webapp [offer-manager] in [/Users/selmantayyar/Documents/OfferManager/target/offer-manager-0.0.1-SNAPSHOT]


[INFO] Processing war project

[INFO] Copying webapp resources [/Users/selmantayyar/Documents/OfferManager/target/www]

[INFO] Webapp assembled in [3157 msecs]


[INFO] Building war: /Users/selmantayyar/Documents/OfferManager/target/offer-manager-0.0.1-SNAPSHOT.war

[INFO] 
[INFO] --- spring-boot-maven-plugin:1.3.6.RELEASE:repackage (default) @ offer-manager ---

[INFO] ------------------------------------------------------------------------


[INFO] BUILD SUCCESS

[INFO] ------------------------------------------------------------------------

[INFO] Total time: 03:55 min


[INFO] Finished at: 2016-08-16T23:13:41+02:00

[INFO] Final Memory: 53M/369M

[INFO] ------------------------------------------------------------------------


Deploying application

Uploading your application code.
 This may take several minutes depending on your connection speed...
Uploading target/offer-manager-0.0.1-SNAPSHOT.war....

-----> Packaging application...

       - app: offer-manager

       - including: target/offer-manager-0.0.1-SNAPSHOT.war


-----> Creating build...

       - file: slug.tgz

       - size: 65MB

-----> Uploading build...

       - success
-----> Deploying...


remote: 

remote: -----> JVM Common app detected

remote: -----> Installing OpenJDK 1.8... done

remote: -----> Discovering process types

remote:        Procfile declares types -> web
remote: 

remote: -----> Compressing...

remote:        Done: 113.8M

remote: -----> Launching...

remote:        Released v9

remote:        https://offer-manager.herokuapp.com/ deployed to Heroku
remote: 

-----> Done

Uploading target/offer-manager-0.0.1-SNAPSHOT.war....
-----> Packaging application...
       - app: offer-manager
       - including: target/offer-manager-0.0.1-SNAPSHOT.war
-----> Creating build...
       - file: slug.tgz
       - size: 65MB
-----> Uploading build...
       - success
-----> Deploying...
remote: 
remote: -----> JVM Common app detected
remote: -----> Installing OpenJDK 1.8... done
remote: -----> Discovering process types
remote:        Procfile declares types -> web
remote: 
remote: -----> Compressing...
remote:        Done: 113.8M
remote: -----> Launching...
remote:        Released v9
remote:        https://offer-manager.herokuapp.com/ deployed to Heroku
remote: 
-----> Done

```

**Comment by selmantayyar** [comment] 2016-08-16 21:22
@ruddell 
I am quite surprised to see that. I can not even see jawsdb in my addons.

> selmans-iMac:OfferManager selmantayyar$ heroku addons
> No add-ons for app offer-manager.

**Comment by jkutner** [comment] 2016-08-16 21:28
@selmantayyar the problem is this question:

> ? The Heroku app "offer-manager" already exists! Use it anyways? Yes

Because you are reusing the app, it can't recreate the add-on. Try destroying the app by running `heroku destroy offer-manager`, and then run the subgenerator again.

**Comment by selmantayyar** [comment] 2016-08-16 21:55
@jkutner That one worked! 

I don't know why add-on was not provisioned first time i have run heroku sub generator.
Anyway,It is working now,thanks to all for the prompt support.

**Comment by jdubois** [comment] 2016-08-16 21:56
Great news, I'm closing this!
@selmantayyar I'm creating another issue for the MySQL 4.5 version with ClearDB

**Closed** 2016-08-16 21:56 UTC
Labels: heroku

**Comment by jdubois** [comment] 2016-08-16 21:59
Oh, reading again your comment, I'm not sure... I need to confirm that first, so I'm not opening a ticket.
It's only with a specific provider, using an older version of MySQL, so I'm not sure we should work on this without a good reason anyway.

**Comment by jkutner** [comment] 2016-08-16 22:02
@jdubois jhipster:heroku doesn't use cleardb anymore. it only uses JawsDB, which seems to be a better experience overall.

**Comment by jdubois** [comment] 2016-08-16 22:05
@jkutner agreed!

**Comment by selmantayyar** [comment] 2016-08-16 22:07
@jdubois I understand. May be it is wise to encourage people to use postgresql instead of my sql in documentation somewhere.

**Comment by jdubois** [comment] 2016-08-16 22:11
With Heroku that seems logical, as this is what the platform supports bests. With other cloud providers, like Cloud Foundry, it is different (in my opinion, Cloud Foundry has a stronger focus on MySQL than on Postgresql).
Anyway, it always depend on your cloud provider: JHipster just gives you the options, then you need to have a look at what's best for you in production.

**Comment by jkutner** [comment] 2016-08-16 22:16
The JawsDB offering has proven to be very good. So despite this fluke, I'm fine with the MySQL default. Heroku does employ Postgres committers and offers it's own add-ons. But I'm not sure how to communicate that in the generator given that DB has already been selected.

@selmantayyar if you have any issues with JawsDB feel free to open a ticket at https://help.heroku.com
