### ISSUE TITLE
406 Not Acceptable when a user has an email as his login, or something with an extension.

### ISSUE THREAD

**Issue by pblanchardie** [jhipster/generator-jhipster#5460] opened 2017-03-22 01:17 UTC
##### **Overview of the issue**

When the login of a user is ends with .foo (eg. an email), we get 406 Not Acceptable: Could not find acceptable representation in the administration.
This happens when you deploy to Tomcat, not when you use the embedded Tomcat.

##### **Reproduce the error**

Generate a monolithic AngularJS application with no particular customization
Create a user with login: foo@bar.com
Try to display or delete this user and you'll get a 406 Not Acceptable Error if the application is deployed as a way in Tomcat, but it will work with Embedded Tomcat.
The request causing the error is /api/users/foo@bar.com

##### **Suggest a Fix**

I got this problem in the past when developing spring applications, and solved it by properly handling paths that can end with an extension, with content negotiation and so on.
Here, it's weird that it works with embedded container and not with the standard tomcat - there is certainly something wrong.

Did you expect emails (and more generaly, dots) to work as logins in JHipster, or do you plan to forbid them?

##### **JHipster Version(s)**

4.0.7

##### **JHipster configuration**

no customisation

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

no customisation

##### **Browsers and Operating System**

Linux, Mac OS X, Chrome, Firefox...
Tomcat 8.0 and 8.5

- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment] 2017-03-22 06:20
- this is a well-known "bug" with Spring MVC (in fact it should be correctly setup) -> this doesn't depend on Tomcat, so what you write doesn't look correct to me (or you found something new!!)
- for me, we do this correct set up
- we also use a login, not an email, in the URL (partly because of this) -> I think you modified the way JHipster works, so in that case that's not a JHipster bug, it's your own bug
- anyway you don't give your configuration, which is against the guidelines, and I have no way to reproduce....

**Comment by jdubois** [comment] 2017-03-22 06:20
This ticket has been closed as the guidelines are not followed.

Tickets must follow our [Guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#submitting-an-issue), as mentioned in:

1. our [Readme file on the front page of the project](https://github.com/jhipster/generator-jhipster/blob/master/README.md), 
2. the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) and
3. our [Help page](http://jhipster.github.io/help/)

We have also created a template on the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) to help you follow those guidelines.

**Closed by jdubois** 2017-03-22 06:20 UTC

**Comment by pblanchardie** [comment] 2017-03-22 12:36
Hi Julien,

Your answer is a bit confusing, what is missing to reproduce the bug?
You only have to generate an application with JHipster (with NO customisation at all), then deploy it in Tomcat, and create a user with something like "foo@bar.com" as the login. Then, you'll get the error.

From my point of view, it's a JHipster bug, not a Spring bug. To handle that, you have to forbid that kind of login, or fix the bug.

Best Regards,
Patrice

**Comment by jdubois** [comment] 2017-03-22 13:12
We miss your `.yo-rc.json` file.... You also need to tell where you click, how you create the user, etc, so I can reproduce.... Just follow the guidelines, I wrote them for that.
I tested this with my current project, it works without any issue, so this is more complex than that. 
By the way, we use Undertow, not Tomcat -> if you have an issue when deploying on Tomcat, and only on Tomcat, then you either have a Spring bug or a Tomcat bug, because we shouldn't do anything specific for Tomcat
Oh, and don't recommend using the email as login, that's why we separated them. But that's a business issue, so that's different.

**Comment by pblanchardie** [comment] 2017-03-22 13:17
Thanks for your quick answer, I'll test with Undertow, as it seems to be related with the container.

I understand you don't recommend using the email in the login, but as the input is free and allows dots and @, we can be sure that some users will...

Here is my .yo-rc.json:
`{
  "generator-jhipster": {
    "jhipsterVersion": "4.0.7",
    "baseName": "jhipster",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "rememberMeKey": "526a6cd88d0d934022c9992c660acf5657edf117",
    "clientFramework": "angular1",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ]
  }
}`

**Comment by tezcane** [comment] 2017-03-22 16:25
I ran into the 406 issue too since I prefer using email as a login for my users.  Here is what my login looks like (see the comments after the ".+")
```
   /**
     * GET  /users/:login : get the "login" user.
     *
     * @param login the login of the user to find
     * @return the ResponseEntity with status 200 (OK) and with body the "login" user, or with status 404 (Not Found)
     */
    @GetMapping("/users/{login:.+}") //:.+ needed since Spring cuts .* extensions, e.g. url/en.json is url.en
    @Email
    @Timed
    public ResponseEntity<UserDTO> getUser(@PathVariable String login) {
        log.debug("REST request to get User : {}", login);
        return ResponseUtil.wrapOrNotFound(
            userService.getUserWithAuthoritiesByLogin(login)
                .map(UserDTO::new));
    }
```

**Comment by ruddell** [comment] 2017-03-22 17:05
The Social Login option [expects email addresses as the login](https://github.com/jhipster/generator-jhipster/blob/79c1c0dee09f03d8f6a71f5b624d89cd62ee4462/generators/server/templates/src/main/java/package/service/_SocialService.java#L130) for all sites except Twitter, so this would be a problem for those users.

I can confirm this is broken on Tomcat but works in other places.  You might need some type of special configuration?

**Comment by pblanchardie** [comment] 2017-03-22 18:52
@tezcane thanks for sharing. You can also disable this behaviour regarding extensions with RequestMappingHandlerMapping.useSuffixPatternMatch.
But did you only get this error when deploying the WAR in Tomcat or also in embedded mode ? That's weird.

@ruddell I'm trying to figure out why it works in embedded mode, as it should throw 406 in that case! It could be due to WebConfigurer.customize, which sets type mappings...

I'll investigate and suggest a solution, as I already solved that in other applications in an elegant way.

**Comment by ruddell** [comment] 2017-03-22 18:57
@pblanchardie The embedded server uses Undertow, deploying to Tomcat uses Tomcat.  So it looks to be related to Tomcat specifically (which is why it doesn't happen for embedded or our docker images).  Thanks for looking into it

**Comment by tezcane** [comment] 2017-03-22 18:59
I did not touch any underlying server implementation, using the default.  I believe I got this error when I was trying to do a password reset with an admin account.  Did not tinker with it too much (other priorities).

**Comment by pblanchardie** [comment] 2017-03-22 19:18
@ruddell indeed, I messed up with the embedded servlet, now it's clear that it works with Undertow and not at all in Tomcat, it will be easier to debug!
@tezcane thx!

**Comment by jdubois** [comment] 2017-03-23 07:39
thanks @tezcane - yes the `{login:.+}` in the URL is the trick I was referring too. We should be doing it, or something similar.
@pblanchardie I'm pretty sure you have something specific with Tomcat, so I'm keeping this closed as this is not supposed to be a JHipster bug, but I'm following this thread, and will reopen the ticket as necessary.
BTW, sorry for the quick answers: as you can see I'm doing this in the morning while commuting :-)

**Comment by pblanchardie** [comment] 2017-03-24 17:46
Thanks for your help, it's clearly specific to Tomcat, and you can notice that the 406 is caused with the .com extension but not with the .net... and so on.
It's related to mappings, and there is a way to make it work in all cases. I'll create a PR if I find some free time to handle that, and if you want so.

**Comment by pblanchardie** [comment] 2018-01-23 16:18
The simplest fix for Tomcat is obviously to disable the path extension strategy.
As described in  #4448, make `WebConfigurer` extend `WebMvcConfigurerAdapter`, then add the following configuration:
```
@Override
public void configureContentNegotiation(ContentNegotiationConfigurer configurer) {
      configurer.favorPathExtension(false)
}
```
