### ISSUE TITLE
Upgrade to Spring Boot 3

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#19782] opened 2022-09-19 21:58 UTC
##### **Overview of the feature request**

Start upgrading to Spring Boot 3.

##### **Motivation for or Use Case**

Selfishly, I need it for a demo at ApacheCon, but I'd also like to hack on it during the JavaOne Hackergarten. 

##### **Related issues or PR**

- https://github.com/jhipster/generator-jhipster/issues/19768
- https://github.com/jhipster/generator-jhipster/issues/19934
- https://github.com/jhipster/generator-jhipster/issues/19991
- https://github.com/jhipster/generator-jhipster/issues/20004
- https://github.com/jhipster/generator-jhipster/issues/20297

**Comment by DanielFran** [comment] 2022-09-21 13:55
@mraible We should consider to migrate from zalando ([problem](https://github.com/zalando/problem) and [problem-spring-web](https://github.com/zalando/problem-spring-web)) to [spring-framework native implementation](https://github.com/spring-projects/spring-framework/issues/27052) coming with spring-framework 6.0

**Comment by mraible** [comment] 2022-09-21 14:05
I'm looking for issues to try and fix at the JavaOne Hackergarten, so this could be a candidate. 

Does anyone know how to fix the compilation errors from Hibernate? Do we still need the fixed PostgreSQL dialects in jhipster-framework?

**Comment by DanielFran** [comment] 2022-09-21 14:09
@mraible @pascalgrimaud This might be helpful: https://github.com/rstoyanchev/sandbox-rfc7807

**Comment by DanielFran** [comment] 2022-09-21 14:12
> I'm looking for issues to try and fix at the JavaOne Hackergarten, so this could be a candidate.
> 
> Does anyone know how to fix the compilation errors from Hibernate? Do we still need the fixed PostgreSQL dialects in jhipster-framework?

@mrable The fixed PostgreSQL dialect was needed for BLOB integration: https://github.com/jhipster/jhipster-bom/blob/main/jhipster-framework/src/main/java/tech/jhipster/domain/util/FixedPostgreSQL10Dialect.java#L37-L39

We just need to confirm hibernate 6 handles it now

**Comment by mraible** [comment] 2022-09-28 08:56
> @mraible @pascalgrimaud This might be helpful: https://github.com/rstoyanchev/sandbox-rfc7807

@DanielFran This looks very helpful. Do you know if we need to extend the exception handler like 
`WebMvcExceptionHandler.java` does in this example? Or can we just declare a bean that returns the parent exception handler?

Related: do we need to register this exception handler with Spring Security?

**Comment by mraible** [comment] 2022-09-28 09:08
A fix for Spring Doc might exist in this PR:

https://github.com/springdoc/springdoc-openapi/pull/1860

**Comment by DanielFran** [comment] 2022-09-28 09:37
> > @mraible @pascalgrimaud This might be helpful: https://github.com/rstoyanchev/sandbox-rfc7807
> 
> @DanielFran This looks very helpful. Do you know if we need to extend the exception handler like `WebMvcExceptionHandler.java` does in this example? Or can we just declare a bean that returns the parent exception handler?
> 
> Related: do we need to register this exception handler with Spring Security?

Seems that `WebMvcExceptionHandler.java` example is like our current https://github.com/jhipster/generator-jhipster/blob/main/generators/server/templates/src/main/java/package/web/rest/errors/ExceptionTranslator.java.ejs
But we would need to implement those exceptions https://github.com/zalando/problem-spring-web/tree/main/problem-spring-web#configuration

**Comment by DanielFran** [comment] 2022-09-28 09:45
> A fix for Spring Doc might exist in this PR:
> 
> [springdoc/springdoc-openapi#1860](https://github.com/springdoc/springdoc-openapi/pull/1860)

We have still some spring.factories in the generator (for testing purposes with testcontainer I believe) to change also.
In the bom, I already migrated them when upgrading to [2.7.0](https://github.com/jhipster/jhipster-bom/pull/790/files)

**Comment by mraible** [comment] 2022-10-12 03:11
> Seems that `WebMvcExceptionHandler.java` example is like our current https://github.com/jhipster/generator-jhipster/blob/main/generators/server/templates/src/main/java/package/web/rest/errors/ExceptionTranslator.java.ejs But we would need to implement those exceptions https://github.com/zalando/problem-spring-web/tree/main/problem-spring-web#configuration

It looks like Spring Boot might fix this by adding problem support by default. https://github.com/spring-projects/spring-boot/issues/32634

**Comment by mraible** [comment] 2022-10-12 03:38
I added new issues with bug bounties for Elasticsearch and the Zalando migration.

**Comment by omnya-alaa-eddin** [comment] 2023-01-16 15:59
Hi [Matt Raible](https://github.com/mraible) , 
how can I pull your changes in order to generate new app that is internally using spring 3 
Thanks for your effort regarding this fixes :)

**Comment by mraible** [comment] 2023-01-16 17:12
Can you please provide the steps you used to reproduce this error. Or, better yet, copy/paste your `.yo-rc.json` as a comment?

For a quick fix, you might try changing the `base-url` value to remove the trailing colon.

**Comment by pascalgrimaud** [comment] 2023-01-16 17:33
You already provided the steps, @mraible 
The main branch is simply broken when you want to generate a project from scratch. Just tried it few minutes ago:

![image](https://user-images.githubusercontent.com/9156882/212737248-174ed8c4-1299-44e0-bb42-fd9d60d0f0fe.png)

**Comment by Tcharl** [comment] 2023-01-16 19:35
Reproduced locally, I reopen

**Comment by pascalgrimaud** [comment] 2023-01-16 19:55
It's not related to Spring Boot 3, so I think we should open a new dedicated ticket instead of reopening this one

**Comment by Tcharl** [comment] 2023-01-17 14:15
Closing in favor of the dedicated issue.

**Closed by Tcharl** 2023-01-17 14:15 UTC
Labels: changes: major :star:, theme: java, $$ bug-bounty $$, $500, v8

**Comment by mshima** [comment] 2023-07-10 01:05
Half work was done by @mraible, but since he usually don't claim, I will claim full 😄 
@DanielFran bounty claimed https://opencollective.com/generator-jhipster/expenses/148964

**Comment by DanielFran** [comment] 2023-07-10 07:43
@mshima approved
