### ISSUE TITLE
Second level cache works only with collections

### ISSUE THREAD

**Issue by delverdev** [jhipster/generator-jhipster#4764] opened 2016-12-25 01:06 UTC
##### **Overview of the issue**

Second level cache works with collections, annotated with `@Cache`, but not with classes.

##### **Motivation for or Use Case**

`@Cache` annotations on classes become useless. Furthermore, all cache option too.

##### **Reproduce the error**

Login as admin into the application. You will see that two queries have sent (select user and select his authorities). Now just flood `/api/account` and you will see that user's authorities are taken from the cache but user itself selects from a database.

##### **Related issues**

[Here](https://github.com/jhipster/generator-jhipster/pull/4470#discussion_r92772743). I think this issue is individual so I decided to open a new ticket.

##### **Suggest a Fix**

No idea.

##### **JHipster Version(s)**

```
jhipstercache@0.0.0 D:\jhipstercache
`-- generator-jhipster@3.12.2

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "jhipsterVersion": "3.12.2",
    "baseName": "jhipstercache",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "buildTool": "gradle",
    "enableSocialSignIn": false,
    "rememberMeKey": "58d442ec4f611f51e49c6e0afb67ae0ff5f26a03",
    "useSass": false,
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

ls: no such file or directory: .jhipster/*.json

##### **Browsers and Operating System**

java version "1.8.0_112"
Java(TM) SE Runtime Environment (build 1.8.0_112-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.112-b15, mixed mode)

git version 2.11.0.windows.1

node: v6.9.2

npm: 3.10.9

bower: 1.8.0

gulp:
[03:05:48] CLI version 1.2.2
[03:05:48] Local version 3.9.1

yeoman: 1.8.5

yarn: 0.17.10

**Comment by jdubois** [comment] 2016-12-25 07:46
This is because we select the user on his login, and not on his ID. 2nd level cache uses the primary key, it doesn't work on requests (or you need the SQL request cache, but that's a whole different story).
This is a design decision in JHipster: IDs are just technical keys. For example, on the user, that means you can change the login (not a technical key), but you can't change the ID.
Anyway, the cache should works, have a look at a "normal" entity.

**Comment by jdubois** [comment] 2016-12-25 14:09
Closing this as this is not a bug

**Closed by jdubois** 2016-12-25 14:09 UTC
