### ISSUE TITLE
Unit test fails on Windows 10

### ISSUE THREAD

**Issue by CGarces** [jhipster/generator-jhipster#14263] opened 2021-03-10 16:27 UTC
##### **Overview of the issue**

The following command fail on my environment  due an error with the unit test
```
mvnw -ntp -Pprod verify jib:dockerBuild

[ERROR] Failures:
[ERROR]   WebConfigurerTest.testCustomizeServletContainer:83
Expecting:
 <C:\jhipster\demo\target\classes\static>
to be equal to:
 <c:\jhipster\demo\target\classes\static>
but was not.
```

Note the "C" on upper case at the begin.

##### **Related issues**

Similar to #5805 see also #5860

##### **Suggest a Fix**

I have fixed the test by hand but I'm not sure if is good enough to send a PR.

```java
assertThat(container.getDocumentRoot().getAbsolutePath()).isEqualToIgnoringCase(new File("target/classes/static/").getAbsolutePath());
```

##### **JHipster Version(s)**

6.10.5

##### **Browsers and Operating System**

- [ x] Checking this box is mandatory (this is just to show you read everything)

**Comment by CGarces** [comment] 2021-03-10 18:05
Works for me but I can't test it on linux (I have problems with WSL2).
Original code compare two objects, my solution compare only two strings, I'm not sure if they are testing the same.

**Comment by murdos** [comment] 2021-03-11 23:47
FYI I reproduce this issue when running maven from a `cmd.exe` terminal.
But not from powershell or git-bash.

**Comment by mraible** [comment] 2021-03-12 08:22
I _feel_ like we should be able to recommend [WSL](https://docs.microsoft.com/en-us/windows/wsl/install-win10) for Windows users and call it good. Document, ship, enjoy! 🤗

**Comment by mraible** [comment] 2023-07-08 20:06
@murdos Are you able to reproduce this with v8 beta?

**Comment by murdos** [comment] 2023-07-08 20:23
Hi @mraible :) Sorry, I no longer have access to a Windows development machine, I switched to Linux.

**Comment by mshima** [comment] 2023-07-08 20:27
I think @DanielFran uses windows.
I suppose is working since it updates snapshots some times.

**Comment by DanielFran** [comment] 2023-10-31 13:49
Closing since it is not reproducible with current main

**Closed by DanielFran** 2023-10-31 13:49 UTC
Labels: area: needs-reproduction, theme: windows, theme: tests
