### ISSUE TITLE
Angular 2 Internet Explorer problem

### ISSUE THREAD

**Issue by serkaneren78** [jhipster/generator-jhipster#5186] opened 2017-02-13 11:43 UTC
- Please follow the issue template below for bug reports and feature requests.
- Tickets opened without any of these informations will be **closed** without any explanation.

##### **Overview of the issue**
Angular 2 monolithic application home page is not loading , getting error for IE 10-11.. There is no problem in chrome, edge and firefox.. 

IE 10 
------
SCRIPT5009: 'Map' is undefined
vendor.dll.js (45115,9)

IE 11
-----
SCRIPT5007: Unable to get property 'apply' of undefined or null reference
vendor.dll.js (54101,5)

##### **Reproduce the error**
 yarn start, page is not loading in IE 10-11.

##### **JHipster Version(s)**
4.0.3, 4.0.2

##### **JHipster configuration**
Angular 2 monolithic application

##### **JHipster Version(s)**

```
flow@0.0.0 D:\yeoman\jhipster\4.0.2\flow
`-- generator-jhipster@4.0.3

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "jhipsterVersion": "4.0.3",
    "baseName": "flow",
    "packageName": "com.liquidity.flow",
    "packageFolder": "com/liquidity/flow",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "jwtSecretKey": "45f8a07be79784ded6f6dc1bb868afeb9ecdf6a7",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": false,
    "serviceDiscoveryType": false,
    "clientFramework": "angular2"
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

ls: no such file or directory: .jhipster/*.json

##### **Browsers and Operating System**

java version "1.8.0_102"
Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode)

git version 2.11.1.windows.1

node: v6.9.5

npm: 4.1.2

bower: 1.7.9

gulp:
[14:40:40] CLI version 3.9.1

yeoman: 1.8.5

yarn: 0.19.1

##### **Browsers and Operating System**
Windows 10 Home 64 Bit, Internet Explorer 11 - 10

- [X ] Checking this box is mandatory (this is just to show you read everything)

**Comment by JulienMrgrd** [comment] 2017-02-14 15:41
Errors reproduced, on IE10 & 11 (on VirtualBox)
It concerns the vendor.dll.js file.

_On IE10 :_
![ie10](https://cloud.githubusercontent.com/assets/11616517/22935600/54ef1016-f2d3-11e6-97ab-41564ae768b8.png)
![ie10file](https://cloud.githubusercontent.com/assets/11616517/22935601/55086fac-f2d3-11e6-99dd-909c8b945e0a.png)

_On IE11 :_
![ie11](https://cloud.githubusercontent.com/assets/11616517/22935604/55354810-f2d3-11e6-94de-fe64c058d728.png)
![ie11file](https://cloud.githubusercontent.com/assets/11616517/22935603/5523f646-f2d3-11e6-8c58-d84d900dbd5a.png)

According to @flaviencathala, on IE11 it's a problem with @angular/common, and for IE10 @angular/core.
We're already up-to-date with angular. So, maybe the solution is to downgrade these. Not sure.
I'm on it.

**Comment by gmarziou** [comment] 2017-02-14 15:49
I would rather think it's a problem of missing polyfills.

**Comment by flaviencathala** [comment] 2017-02-14 16:01
I agree, as Angular is supposed to support IE 10 and 11, the issue comes very probably from the way we build the app.

**Comment by deepu105** [comment] 2017-02-14 16:48
I wouldnt worry about IE10 as MS stopped support for it officially lets
target only IE11


Thanks & Regards,
Deepu

**Comment by JulienMrgrd** [comment] 2017-02-16 10:32
I've tested some solutions on IE11, without results...
[http://stackoverflow.com/questions/41276692/angular2-ie11-unable-to-get-property-apply-of-undefined-or-null-reference](url)

1. The **Aldracor solution** replace the error by another.
> Object doesn't support property or method 'values'

![capture d ecran de 2017-02-16 10-51-11](https://cloud.githubusercontent.com/assets/11616517/23016467/e7385c34-f436-11e6-9f22-876e848c2e18.png)

![capture d ecran de 2017-02-16 10-52-32](https://cloud.githubusercontent.com/assets/11616517/23016466/e737604a-f436-11e6-8b32-0657bad0a361.png)
I've not found any interesting post about the resolveReflectiveProviders function.

<br/>

2. The **Stas Berkov solution**
> Can't resolve all parameters for JhiTrackerService: ([object Object], [object Object], ?, ?, [object Object]).

![capture d ecran de 2017-02-16 11-25-34](https://cloud.githubusercontent.com/assets/11616517/23017571/1b30518c-f43b-11e6-8e8a-4fac574482b9.png)
![capture d ecran de 2017-02-16 11-29-25](https://cloud.githubusercontent.com/assets/11616517/23017601/3add04bc-f43b-11e6-814b-e309db5d59ad.png)
Nothing on this too...

Any ideas ?

**Comment by serkaneren78** [comment] 2017-02-19 11:54
Problem related to Polyfills.
polyfills from angular-seed project (https://github.com/angular/angular2-seed) fixed the problem. After that there is another error while injecting the window to JhiTrackerService in the IE. 

In the tracker.service.ts , this change should be in the constructor of JhiTrackerService..
        @Inject(Document) private $document: Document,
        @Inject(Window) private $window: Window,


import 'ie-shim'; // Internet Explorer 9 support
// import 'core-js/es6';
// Added parts of es6 which are necessary for your project or your browser support requirements.
import 'core-js/es6/symbol';
import 'core-js/es6/object';
import 'core-js/es6/function';
import 'core-js/es6/parse-int';
import 'core-js/es6/parse-float';
import 'core-js/es6/number';
import 'core-js/es6/math';
import 'core-js/es6/string';
import 'core-js/es6/date';
import 'core-js/es6/array';
import 'core-js/es6/regexp';
import 'core-js/es6/map';
import 'core-js/es6/set';
import 'core-js/es6/weak-map';
import 'core-js/es6/weak-set';
import 'core-js/es6/typed';
import 'core-js/es6/reflect';
// see issue https://github.com/AngularClass/angular2-webpack-starter/issues/709
// import 'core-js/es6/promise';

import 'core-js/es7/reflect';
import 'zone.js/dist/zone';
import 'zone.js/dist/long-stack-trace-zone';

**Comment by ramzimaalej** [comment] 2017-02-21 02:15
I'm having a similar issue with vendor.dll.js
![screen shot 2017-02-20 at 9 13 32 pm](https://cloud.githubusercontent.com/assets/1727621/23148088/9713cfd0-f7b1-11e6-9bf4-f83e4fc4923d.png)

**Comment by jdubois** [comment] 2017-02-21 08:22
And did you find a solution ?

Le 21 févr. 2017 3:15 AM, "Ramzi Maalej" <notifications@github.com> a
écrit :

I'm having a similar issue with vendor.dll.js
[image: screen shot 2017-02-20 at 9 13 32 pm]
<https://cloud.githubusercontent.com/assets/1727621/23148088/9713cfd0-f7b1-11e6-9bf4-f83e4fc4923d.png>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/jhipster/generator-jhipster/issues/5186#issuecomment-281226240>,
or mute the thread

**Comment by asanzdiego** [comment] 2017-02-21 12:12
Maybe the import of polyfills could fix the problem.

See: [https://angular.io/docs/ts/latest/guide/browser-support.html](https://angular.io/docs/ts/latest/guide/browser-support.html)

**Comment by deepu105** [comment] 2017-02-21 13:03
The suggested polyfill for IE11 is this https://github.com/zloirock/core-js but
I guess we already have that


Thanks & Regards,
Deepu

**Comment by ramzimaalej** [comment] 2017-02-21 14:33
I'm not on IE, this was on Chrome after generating a fresh application using JHipster 4.0.5

**Comment by serkaneren78** [comment] 2017-02-21 19:51
Below polyfills and change in tracker.service fixed IE 10 and 11 problem..

tracker.service.ts
@Inject(Document) private $document: Document,
@Inject(Window) private $window: Window,

Polyfills.ts
import 'ie-shim'; // Internet Explorer 9 support
// import 'core-js/es6';
// Added parts of es6 which are necessary for your project or your browser support requirements.
import 'core-js/es6/symbol';
import 'core-js/es6/object';
import 'core-js/es6/function';
import 'core-js/es6/parse-int';
import 'core-js/es6/parse-float';
import 'core-js/es6/number';
import 'core-js/es6/math';
import 'core-js/es6/string';
import 'core-js/es6/date';
import 'core-js/es6/array';
import 'core-js/es6/regexp';
import 'core-js/es6/map';
import 'core-js/es6/set';
import 'core-js/es6/weak-map';
import 'core-js/es6/weak-set';
import 'core-js/es6/typed';
import 'core-js/es6/reflect';
// see issue AngularClass/angular2-webpack-starter#709
// import 'core-js/es6/promise';

import 'core-js/es7/reflect';
import 'zone.js/dist/zone';
import 'zone.js/dist/long-stack-trace-zone';

**Comment by ramzimaalej** [comment] 2017-02-21 20:14
@serkaneren78 can you create a PR for this?

**Comment by holgerdunst** [comment] 2017-03-23 20:24
Why has this issue got the minor label?

**Comment by jdubois** [comment] 2017-03-23 20:29
None of us use Windows, so if you want to help, you're most welcome. Angry comments are noise, and make everyone lose time, so they definitely do not help.

**Comment by holgerdunst** [comment] 2017-03-23 21:30
Why is this comment angry? Generated JHipster Applications don't work in IE11.

**Comment by deepu105** [comment] 2017-03-23 21:35
Hi its minor becoz we consider IE support as low priority compared to others. The user base of IE is shrinking and we wont be spending lot of time on that so if you want to help you are welcome. If you want to support IE I suggest yoi use angular 1 version which is stable.

**Comment by holgerdunst** [comment] 2017-03-23 21:40
I think you should not forget corporate users. Most companies have just switched to Windows7. That means IE11.

**Comment by jdubois** [comment] 2017-03-23 21:58
guys, can we stop the talking here? @holgerdunst if you want to help, a PR on this will be very appreciated, as we can't work on this (none of us have Windows).
If big companies really need this, they can also sponsor the feature, this happens quite often. Even better, they can buy me a Surface Pro so I can test :-)

**Comment by kaidohallik** [comment] 2017-03-24 06:50
I couldn't get working conditional loading. But after adding this to polyfills.js:
```
import 'core-js/client/shim';
```
it's working in IE 11 and seems that this didn't break other browsers.

**Comment by jdubois** [comment] 2017-03-24 08:12
Great work! Let's do this - no problem for testing on other browsers anyway

**Comment by holgerdunst** [comment] 2017-03-24 08:23
I checked the change with a fresh generated App with JHipster 4.1.1. The App does not work here. IE11 shows:
`SCRIPT5022: Error: Can't resolve all parameters for JhiTrackerService: ([object Object], [object Object], ?, ?, [object Object]).
vendor.dll.js (21030,13)`
I had to change the constructor of JhiTrackerService in tracker.service.ts than in works fine. I added inject to Document and Window:

        @Inject(Document) private $document: Document,
        @Inject(Window) private $window: Window,

**Comment by deepu105** [comment] 2017-03-24 08:36
Then could you guys plz PR those changes in? Lets have this workaround for now. I still think the core problem to investigate is why the code doesn't work as its transpiled to es5 anyway. May be it has some es5 code which stupid IE doesn't support

**Comment by jdubois** [comment] 2017-03-24 09:06
@holgerdunst if you use Websockets that's a different issue - this is a quite complex option, let's not mix things up: first we make the "normal" app work, then we fix the options

@kaidohallik please do your PR, and @holgerdunst you can then do a PR on the PR for Websockets

**Comment by kaidohallik** [comment] 2017-03-24 09:15
@deepu105 Seems that problem comes from vendor part. I tried following:
1. added this to `package.json`:
```
        "babel-core": "6.24.0",
        "babel-loader": "6.4.1",
        "babel-preset-es2015": "6.24.0",
```
2. added this to `webpack.vendor.js`:
```
            {
                test: /\.js$/,
                loaders: [
                    {
                        loader: 'babel-loader',
                        query: {
                            presets: ['es2015']
                        }
                    }
                ]
            }
```

But this didn't remove the error.

**Comment by kaidohallik** [comment] 2017-03-24 09:20
@jdubois My addition to polyfills.ts increased page download size ~600 kB. That's another bad thing with this change. I'll do PR, then you can decide, merge it or not.

**Comment by deepu105** [comment] 2017-03-24 10:49
@kaidohallik thats the exact reason why I wanted to use the polyfills from a CDN with an IE conditional something like below in `<head>` so that we dont add this for all browsers. Can you give it a try please
```
<!--[if lt IE 9]>
<script src="https://cdnjs.cloudflare.com/ajax/libs/es6-shim/0.35.3/es6-shim.min.js" />
<![endif]-->
```
https://cdnjs.com/libraries/es6-shim

**Comment by kaidohallik** [comment] 2017-03-24 11:23
@deepu105 Conditional comments are no longer supported starting from IE 10:
https://msdn.microsoft.com/en-us/library/hh801214(v=vs.85).aspx

**Comment by deepu105** [comment] 2017-03-24 12:06
Damn it. They dont support stuff properly and now this. Idiots :angry: @kaidohallik do you know which line of code exactly causes the issue? may be we can try to modify that or open a bug report on that library

**Comment by kaidohallik** [comment] 2017-03-24 12:37
In IE 11 same line as reported by @JulienMrgrd in https://github.com/jhipster/generator-jhipster/issues/5186#issuecomment-279742914  
@JulienMrgrd  posted [SO link](http://stackoverflow.com/questions/41276692/angular2-ie11-unable-to-get-property-apply-of-undefined-or-null-reference) in https://github.com/jhipster/generator-jhipster/issues/5186#issuecomment-280294143  
In that link in one comment is [link to MDN](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Object/assign#Browser_compatibility) where is information that `Object.assign()` is not supported in IE.

**Comment by gmarziou** [comment] 2017-03-24 14:35
Wow then it should probably be documented as a tip.

**Comment by deepu105** [comment] 2017-03-24 15:52
Object.assign is ES6 why isnt this transpiled to ES5 by awesome-typescript-loader?

**Comment by deepu105** [comment] 2017-03-24 15:55
Lets try to add only polyfills that are required for this
We should try https://github.com/es-shims/es5-shim as well and see if it helps

**Comment by sendilkumarn** [comment] 2017-03-24 16:00
awesome-typescript-loader is using `object-assign` lib which is supporting from edge onwards.

are you sure es5-shim supports object assign ?

**Comment by deepu105** [comment] 2017-03-24 16:22
may be we should raise a ticket to awesome typescript lib and in the mean time we can add a shim specific for Object.assign

**Comment by kaidohallik** [comment] 2017-03-25 23:42
es5-shim didn't resolve this issue in IE 11.  
I changed PR #5483 - now shim is loaded only for IE 11.

**Comment by deepu105** [comment] 2017-03-26 21:36
PR merged

**Closed by deepu105** 2017-03-26 21:36 UTC
Labels: angular-2, bug, minor

**Comment by avoliva** [comment] 2017-07-18 16:12
I'm getting a similiar issue, but Math is showing as `undefined` here.

**Comment by playground** [comment] 2017-07-27 22:27
Getting the same error.  ie11 object doesn't support property or method 'assign'

**Comment by gmarziou** [comment] 2017-07-28 08:14
@avoliva and @playground please don't comment on an old closed issue, it doesn't help at all. Please open a new issue with all required details.
