### ISSUE TITLE
Migrate to new Kafka Spring Cloud Stream support

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#20297] opened 2022-11-12 21:20 UTC
##### **Overview of the issue**

With Spring Boot 3, Spring Cloud Stream no longer ships with `@EnableBinding`, `@Input`, or `@Output` annotations. The JavaDocs for these annotations says:

> Deprecated as of 3.1 in favor of functional programming model.

##### **Motivation for or Use Case**

The `ng-mongodb-kafka-cucumber` job is failing with the following error:

```
Error:  /home/runner/work/jhipster-bom/jhipster-bom/app/src/main/java/tech/jhipster/sample/config/WebConfigurer.java:14: error: cannot find symbol
Error:  import org.springframework.cloud.stream.annotation.EnableBinding;
Error:                                                    ^
Error:    symbol:   class EnableBinding
Error:    location: package org.springframework.cloud.stream.annotation
Error:  /home/runner/work/jhipster-bom/jhipster-bom/app/src/main/java/tech/jhipster/sample/config/WebConfigurer.java:29: error: cannot find symbol
Error:  @EnableBinding({ KafkaSseConsumer.class, KafkaSseProducer.class })
Error:   ^
Error:    symbol: class EnableBinding
Error:  /home/runner/work/jhipster-bom/jhipster-bom/app/src/main/java/tech/jhipster/sample/config/KafkaSseProducer.java:3: error: cannot find symbol
Error:  import org.springframework.cloud.stream.annotation.Output;
Error:                                                    ^
Error:    symbol:   class Output
Error:    location: package org.springframework.cloud.stream.annotation
Error:  /home/runner/work/jhipster-bom/jhipster-bom/app/src/main/java/tech/jhipster/sample/config/KafkaSseConsumer.java:3: error: cannot find symbol
Error:  import org.springframework.cloud.stream.annotation.Input;
Error:                                                    ^
Error:    symbol:   class Input
Error:    location: package org.springframework.cloud.stream.annotation
Error:  /home/runner/work/jhipster-bom/jhipster-bom/app/src/main/java/tech/jhipster/sample/web/rest/SampleMongoKafkaKafkaResource.java:13: error: cannot find symbol
Error:  import org.springframework.cloud.stream.annotation.StreamListener;
Error:                                                    ^
Error:    symbol:   class StreamListener
Error:    location: package org.springframework.cloud.stream.annotation
Error:  /home/runner/work/jhipster-bom/jhipster-bom/app/src/main/java/tech/jhipster/sample/config/KafkaSseProducer.java:9: error: cannot find symbol
Error:      @Output(CHANNELNAME)
Error:       ^
Error:    symbol:   class Output
Error:    location: interface KafkaSseProducer
Error:  /home/runner/work/jhipster-bom/jhipster-bom/app/src/main/java/tech/jhipster/sample/config/KafkaSseConsumer.java:9: error: cannot find symbol
Error:      @Input(CHANNELNAME)
Error:       ^
Error:    symbol:   class Input
Error:    location: interface KafkaSseConsumer
Error:  /home/runner/work/jhipster-bom/jhipster-bom/app/src/main/java/tech/jhipster/sample/web/rest/SampleMongoKafkaKafkaResource.java:65: error: cannot find symbol
Error:      @StreamListener(value = KafkaSseConsumer.CHANNELNAME, copyHeaders = "false")
Error:       ^
Error:    symbol:   class StreamListener
Error:    location: class SampleMongoKafkaKafkaResource
```

##### **Reproduce the error**

Create a new project with [`ng-mongodb-kafka-cucumber/.yo-rc.json`](https://github.com/jhipster/generator-jhipster/tree/main/test-integration/samples/ng-mongodb-kafka-cucumber) and try to compile it.

##### **Related issues**

#19791

##### **Suggest a Fix**

Refactor to use Spring Cloud Stream's functional programming model.

**Comment by codedsun** [comment] 2022-11-13 10:12
Hi @mraible Can a beginner to this project take this issue? I have good prior experience with the spring and java though. Thanks

**Comment by mshima** [comment] 2022-11-13 14:55
@codedsun you can go ahead.

**Comment by codedsun** [comment] 2022-11-14 15:52
@mshima need help i created an application and replaced the `.yo-rc` file with the above file link provided. Am i going correctly?

**Comment by codedsun** [comment] 2022-11-14 16:40
Also when I am creating a new application without any changes and run ./mvnw

```
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'tokenProvider' defined in file [/Users/codedsun/Documents/OpenSource/suneet/target/classes/com/mycompany/myapp/security/jwt/TokenProvider.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.mycompany.myapp.security.jwt.TokenProvider]: Constructor threw exception; nested exception is java.lang.NullPointerException
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:315)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:296)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1372)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1222)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1391)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1311)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:887)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:791)
	... 22 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.mycompany.myapp.security.jwt.TokenProvider]: Constructor threw exception; nested exception is java.lang.NullPointerException
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:224)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:117)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:311)
	... 36 common frames omitted
Caused by: java.lang.NullPointerException: null
	at com.mycompany.myapp.security.jwt.TokenProvider.<init>(TokenProvider.java:54)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:211)
	... 38 common frames omitted

```

i see some errors and the backend is not able to run.

**Comment by mraible** [comment] 2022-11-14 16:49
Here are the steps to get the proper JHipster version installed:

```
git clone -b spring-boot-3.0-m4 https://github.com/jhipster/jhipster-bom.git
cd jhipster-bom
./mvnw install -Dgpg.skip=true
```

Then, clone and install the Spring Boot 3 branch for the main generator:

```
git clone -b spring-boot-3.0-m4 https://github.com/jhipster/generator-jhipster.git
cd generator-jhipster
npm install
npm link
```

Now, you should be able to create a new directory, add the above `.yo-rc.json` to it, and run `jhipster` in it.

**Comment by codedsun** [comment] 2022-11-14 16:53
@mraible this jhipster-bom has to be inside the same generator-jhipster folder?

**Comment by mraible** [comment] 2022-11-14 16:57
No, it should be a separate project. When you `mvn install`, it puts the artifacts in `~/.m2/repository` and that's where your application will get its SNAPSHOT artifacts. Here's how I have my local directory structure:

```
~/dev/
  - jhipster-bom
  - jhipster-generator
```

**Comment by codedsun** [comment] 2022-11-17 17:57
@mraible thankyou, i am able to reproduce this..let me learn about the files/project structure and I will deploy a fix soon.

**Comment by codedsun** [comment] 2022-11-18 17:49
Hi @mraible , @mshima I have also understood the files which need to be changed(might be :P , just want to understand what IDE you guys are using for the development? I can't do the imports manually for everything ..

**Comment by mraible** [comment] 2022-11-18 18:18
I'm using IntelliJ IDEA. A workflow that might be helpful:

1. Create an app with JHipster locally using the Spring Boot 3 branch. Check it into GitHub.
2. Make changes to the app to fix Kafka. Create a PR for your repo on GitHub. Iterate until all tests pass.
3. Make changes in to the files that you modify in `generator-jhipster`. Create a PR for the `generator-jhipster` repo.

We can help you with the third item if you have a PR where we can see all the changes you made to get things working.

**Comment by codedsun** [comment] 2022-11-20 14:38
Hi @mraible , I have applied the changes to fix the issue but when I am running `./mnvw` the mongodb is throwing some error, do i have to configure that also on my machine?


<img width="1509" alt="image" src="https://user-images.githubusercontent.com/20026440/202908373-581b5018-f42c-44f2-97db-d8c85802e9c6.png">

**Comment by dwarakaprasad** [comment] 2022-11-20 15:37
@codedsun looks like you have committed the generated [code](https://github.com/codedsun/generator-jhipster/tree/codedsun_spring_kafka/suneet) inside the generator code base and that is not required. Can you please only commit the necessary generator code and follow the [guidelines](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md)

You can take a look at this closed [PR](https://github.com/jhipster/generator-jhipster/pull/19959) & [bom PR](https://github.com/jhipster/jhipster-bom/pull/1003), this like yours has changes to both generator-jhipster and bom.
Hope this helps.

**Comment by codedsun** [comment] 2022-11-20 16:07
HI @dwarakaprasad, Thankyou for the detailed guidance.

this is a PR for reference to point 2 here https://github.com/jhipster/generator-jhipster/issues/20297#issuecomment-1320374960. This is just a generated app where I just made things working with my project regarding the migration, this has not be merged. I just wanted to verify with @mraible that are the changes in my project are OK and do I have to test something else as well regarding kafka spring cloud stream. If no, then I will go ahead and make the changes to generator code base and submit a new PR with the guidelines. 

Thanks.

**Comment by dwarakaprasad** [comment] 2022-11-20 17:14
> 2\. Make changes to the app to fix Kafka. Create a PR for your repo on GitHub. Iterate until all tests pass.

Ok, but I would not add the generated code to the generator code base as it will pollute your PR (the actual one I mean), I would rather have that as a separate repo (app repo).

All the generated code comes packed with lots of tests and you can use the following commands to run them,
1. Front end tests -> npm run ci:frontend:test
2. Back end tests -> npm run ci:backend:test
3. e2e
    Here you have 2 options,
    Option 1: If you have docker
    npm run ci:e2e:package
    npm run ci:e2e:prepare
    npm run ci:e2e:run
    after completion
    npm run ci:e2e:teardown

   Option 2:
   bring up all your dependencies as necessary (jhipster registry, db, cache provider, etc.)
   mvnw (windows) or ./mvnw (linux)
   npm run e2e:headless

Check the package.json and customize the above scripts as required (this is the workflow that i follow).

With your code changes if all the above goes through, you have crossed 50% (i.e. for the options that you have selected in  jhipster everything works fine).

Next steps,
1. Makes changes to the generator
2. run unit tests on the generator with your changes
3. Run a couple of integration tests - refer to [this](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md#running-integration-tests-locally)
4. Create a draft PR and make changes until all the builds/[checks](https://github.com/jhipster/generator-jhipster/pull/20400/checks) are successful
5. Flip the PR for review

I am happy to assist you with the generator changes if you need help.

**Comment by codedsun** [comment] 2022-11-20 17:31
@dwarakaprasad I am a bit confused, I just wanted to know that the changes which I did regarding kafka cloud stream on my projects are compiling and server is up, but do we need anything to test it? If yes, please let me know. And if no - I would proceed forward with making changes to generator project..With the test/commands u mentioned above - do I need to run them on my project?

**Comment by dwarakaprasad** [comment] 2022-11-20 17:37
> but do we need anything to test it?

Yes, you will have to run the following tests,
1. front end tests (may not be relevant in your case but its a good idea to run them)
2. back end tests (you seem to have got that covered with the mvnw)
3. e2e (very important) - this will make sure your application is working as expected

**Comment by codedsun** [comment] 2022-11-20 18:04
@dwarakaprasad - As this PR is related to spring boot3, are you sure these tests will work?

**Comment by dwarakaprasad** [comment] 2022-11-20 18:13
> As this PR is related to spring boot3, are you sure these tests have to be run?

Yes, the tests could fail but at the least you can make sure that its not failing due to your code.

**Comment by codedsun** [comment] 2022-11-20 18:17
@dwarakaprasad - There are 93 test in total and when I run this 83 are failing, I am not sure how will I debug what are mine but I see there are multiple other failures too.. Also will `./mvnw test` not give us the clear status for backend changes in test?

**Comment by dwarakaprasad** [comment] 2022-11-20 21:21
@codedsun the way I did it was for,
1. back end tests, to start with running the tests with debug logs enabled, and then categorize the issues as mine vs existing migration issues and then comment out the existing migration ones to make sure my code is running fine.
2. for e2e, as long as there are no context loading issues, you should be able to run them and verify. for e.g. [this](https://github.com/jhipster/generator-jhipster/actions/runs/3505612690/jobs/5872021072) job seems to be working fine, you could add kafka to this and run the tests and make sure everything is working fine. Also see [this](https://github.com/jhipster/generator-jhipster/actions/runs/3505612690/jobs/5872021182) job is failing (most of the compilation issues seem to be to related kafka) I guess your changes will fix this.

**Comment by codedsun** [comment] 2022-11-21 11:20
To comment 83 test and parts would be too hard for me as a beginner to this project. @dwarakaprasad 

@mraible @mshima What should I do?

**Comment by mshima** [comment] 2022-11-21 12:09
@codedsun you can use a basic sample to make it easier, like:
```
application {
  config {
    baseName kafkaSample
    messageBroker kafka
  }
}
```

tests should be ok for default at sb3 branch.
No need for entities.

Make sure you have reactive working too afterwards.
```
application {
  config {
    baseName kafkaSample
    messageBroker kafka
    reactive true
    cacheProvider no # don't know if it's necessary
    enableHibernateCache # don't know if it's necessary
  }
}
```

**Comment by mshima** [comment] 2022-11-21 12:10
I will see if I can modularize Kafka to make it easier.

**Comment by codedsun** [comment] 2022-11-21 12:36
@mshima where do i need to put this? 
```
application {
  config {
    baseName kafkaSample
    messageBroker kafka
  }
}
```

Got somewhat confused 🤔 plus as mentioned test are failing at my newly created project too as mentioned here https://github.com/jhipster/generator-jhipster/issues/20297#issuecomment-1321206022

**Comment by mshima** [comment] 2022-11-21 13:22
> @mshima where do i need to put this?

@codedsun this is a jdl file.
Create a app.jdl with this content and run:
```
jhipster jdl app.jdl
```

If the majority of test is falling, so the startup is broken.

**Comment by codedsun** [comment] 2022-11-21 17:10
@mshima Thanks you, can you please guide me the next steps? like this https://github.com/jhipster/generator-jhipster/issues/20297#issuecomment-1320374960 . I am a little afraid to comment multiple times here for small doubts so I pinged on gitter.

1. What do i have to do for the project that I created in which I fix the kafka?
2. I haven't changed the files to generator-hipster? Shall I do it now?
3. When i create an app with `jhipster jdl app.jdl` will I have to fix the kafka their again?

**Comment by mshima** [comment] 2022-11-21 17:33
> @mshima Thanks you, can you please guide me the next steps? like this [#20297 (comment)](https://github.com/jhipster/generator-jhipster/issues/20297#issuecomment-1320374960) . I am a little afraid to comment multiple times here for small doubts so I pinged on gitter.
> 
> 1. What do i have to do for the project that I created in which I fix the kafka?

Creating a single commit or diff will help you to know what needs to be changed.

> 2. I haven't changed the files to generator-hipster? Shall I do it now?

Your choice. In the end you will need to do.

> 3. When i create an app with `jhipster jdl app.jdl` will I have to fix the kafka there again?

If you haven't applied the change to jhipster templates then yes.

> 4. Also where do i have to run the test?

Not sure I understand.
At ci we run the following to test:
```
npm run ci:backend:test # junit tests
npm run ci:e2e:package # package the jar
npm run services:up # starts docker services
npm run ci:e2e:run # starts the jar and run cypress
```

If you publish the generated project and changes to GitHub, we will manage to assist better.

**Comment by codedsun** [comment] 2022-11-21 17:35
@mshima Already shared the project in this PR. https://github.com/jhipster/generator-jhipster/pull/20401

**Comment by mshima** [comment] 2022-11-21 17:59
@codedsun I recommend to generate a new project with the jdl:
```
application {
  config {
    baseName kafkaSample
    messageBroker kafka
  }
}
```

Apply the commit https://github.com/jhipster/generator-jhipster/commit/91e7f199c173be82b3ec5854720437a5b2d064a6.

These tests needs to pass:
```
npm run ci:backend:test # junit tests
npm run ci:e2e:package # package the jar
npm run services:up # starts docker services
npm run ci:e2e:run # starts the jar and run cypress
```

**Comment by codedsun** [comment] 2022-11-21 18:00
@mshima thanks, on it 👨‍💻

**Comment by codedsun** [comment] 2022-11-21 19:08
@mshima test are working fine
<img width="1510" alt="image" src="https://user-images.githubusercontent.com/20026440/203138329-7f4ac0f7-bf08-4f79-a891-88abea5fc23c.png">



But when i run `npm run ci:e2e:package # package the jar` - I see an error ` The requested profile "e2e" could not be activated because it does not exist.`

<img width="1510" alt="image" src="https://user-images.githubusercontent.com/20026440/203138841-29469fd2-8d2d-4a58-8151-aef4daa3598a.png">

**Comment by mshima** [comment] 2022-11-21 20:26
> But when i run `npm run ci:e2e:package # package the jar` - I see an error ` The requested profile "e2e" could not be activated because it does not exist.`

@codedsun sorry, my bad, cypress is not enabled.

In any case, if the application starts, it should be ok. We don't have cypress test for Kafka.

Now just update your sb3 branch with modularized Kafka, update the templates and create a PR agains sb3 branch.
We can continue from there.

**Comment by codedsun** [comment] 2022-11-22 18:10
@mshima opened a PR here 
https://github.com/jhipster/generator-jhipster/pull/20433

**Comment by dwarakaprasad** [comment] 2022-12-26 17:35
@codedsun are you still working on this?

**Closed** 2023-03-27 16:08 UTC
Labels: $$ bug-bounty $$, $300, theme: kafka

**Comment by mshima** [comment] 2023-08-07 22:58
@DanielFran bounty claimed https://opencollective.com/generator-jhipster/expenses/154485

**Comment by DanielFran** [comment] 2023-08-08 12:13
@mshima approved
