### ISSUE TITLE
'cjs' is not recognized as an internal or external command,

### ISSUE THREAD

**Issue by venkatnaveen7** [jhipster/generator-jhipster#20182] opened 2022-11-02 11:20 UTC
npm run build

> generator-jhipster@7.9.3 build
> npm run compile && npm run copy-files && npm run compile-types && npm run copy-types

> generator-jhipster@7.9.3 compile
> tsc

> generator-jhipster@7.9.3 copy-files
> cpy 'jdl/*.json' 'dist/jdl' && cpy 'generators/**' '!**/*.(js|cjs|mjs|ts|cts|mts|snap)' '!**/__*/*' dist/generators

'cjs' is not recognized as an internal or external command,
operable program or batch file.

**Comment by Tcharl** [comment] 2022-11-02 21:29
Works on my machine

**Comment by venkatnaveen7** [comment] 2022-11-03 05:17
node --version v16.13.2
npm --version 8.1.2
trying to install jhipster V7.9.3
using Windows 10 OS Build 19044.2130  Version 21H2

generator-jhipster@7.9.3 build
npm run compile && npm run copy-files && npm run compile-types && npm run copy-types

generator-jhipster@7.9.3 compile
tsc

generator-jhipster@7.9.3 copy-files
cpy 'jdl/.json' 'dist/jdl' && cpy 'generators/' '!/.(js|cjs|mjs|ts|cts|mts|snap)' '!**/__/' dist/generators

**Comment by petecarapetyan** [comment] 2022-11-10 16:01
same problem, different route to get there

node LTS 18.12.1

to replicate
` npm uninstall -g generator-jhipster
  npm i -g generator-jhipster
  jhipster
 `
  
  This, or any jhipster command, produces output that always looks like this
  
  `node:internal/modules/cjs/loader:535
      throw e;
      ^

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/util/namespace' is not defined by "exports" in /Users/petecarapetyan/.nvm/versions/node/v18.12.1/lib/node_modules/generator-jhipster/node_modules/yeoman-environment/package.json
    at new NodeError (node:internal/errors:393:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:358:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:668:3)
    at resolveExports (node:internal/modules/cjs/loader:529:36)
    at Module._findPath (node:internal/modules/cjs/loader:569:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:981:27)
    at Module._load (node:internal/modules/cjs/loader:841:27)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/Users/petecarapetyan/.nvm/versions/node/v18.12.1/lib/node_modules/generator-jhipster/utils/blueprint.js:19:25) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
`

**Comment by mshima** [comment] 2022-11-11 18:03
@petecarapetyan your problem I probably https://github.com/jhipster/generator-jhipster/issues/19627.

@DanielFran can you reproduce on windows?

**Comment by kaidohallik** [comment] 2022-11-14 14:08
I can reproduce.
Seems to be https://github.com/sindresorhus/cpy-cli/issues/30
So solution is to change `'` with `\"` in `copy-files` and `copy-types` scripts to work also in Windows.
In my testing this worked in Windows after this change.

**Comment by kaidohallik** [comment] 2022-11-17 08:16
Fixed by #20330

**Closed by kaidohallik** 2022-11-17 08:16 UTC
Labels: area: bug :bug:, theme: windows
