### ISSUE TITLE
Manual upgrade from 5.7.2 to 5.8.1 failing

### ISSUE THREAD

**Issue by pmverma** [jhipster/generator-jhipster#9204] opened 2019-02-06 05:58 UTC
##### **Overview of the issue**

Manual upgrade from version 5.7.2 to 5.8.1 is failing with following error while automatic upgrade is working without any issue.

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project 5732581: Compilation failure: Compilation failure: 
[ERROR] /Users/sierra/github/pmverma/5732581/src/main/java/com/company/myapp/config/MetricsConfiguration.java:[5,28] cannot find symbol
[ERROR]   symbol:   class JmxReporter
[ERROR]   location: package com.codahale.metrics
[ERROR] /Users/sierra/github/pmverma/5732581/src/main/java/com/company/myapp/config/MetricsConfiguration.java:[6,28] cannot find symbol
[ERROR]   symbol:   class JvmAttributeGaugeSet
[ERROR]   location: package com.codahale.metrics
[ERROR] /Users/sierra/github/pmverma/5732581/src/main/java/com/company/myapp/config/MetricsConfiguration.java:[9,35] package com.codahale.metrics.health does not exist
[ERROR] /Users/sierra/github/pmverma/5732581/src/main/java/com/company/myapp/config/MetricsConfiguration.java:[10,1] package com.codahale.metrics.jvm does not exist
[ERROR] /Users/sierra/github/pmverma/5732581/src/main/java/com/company/myapp/config/MetricsConfiguration.java:[11,55] package com.ryantenney.metrics.spring.config.annotation does not exist
[ERROR] /Users/sierra/github/pmverma/5732581/src/main/java/com/company/myapp/config/MetricsConfiguration.java:[12,55] package com.ryantenney.metrics.spring.config.annotation does not exist
[ERROR] /Users/sierra/github/pmverma/5732581/src/main/java/com/company/myapp/config/MetricsConfiguration.java:[14,28] package io.prometheus.client does not exist
[ERROR] /Users/sierra/github/pmverma/5732581/src/main/java/com/company/myapp/config/MetricsConfiguration.java:[15,39] package io.prometheus.client.dropwizard does not exist
[ERROR] /Users/sierra/github/pmverma/5732581/src/main/java/com/company/myapp/config/MetricsConfiguration.java:[16,37] package io.prometheus.client.exporter does not exist
[ERROR] /Users/sierra/github/pmverma/5732581/src/main/java/com/company/myapp/config/MetricsConfiguration.java:[32,43] cannot find symbol
[ERROR]   symbol: class MetricsConfigurerAdapter
[ERROR] /Users/sierra/github/pmverma/5732581/src/main/java/com/company/myapp/config/MetricsConfiguration.java:[31,2] cannot find symbol
[ERROR]   symbol: class EnableMetrics
[ERROR] /Users/sierra/github/pmverma/5732581/src/main/java/com/company/myapp/config/MetricsConfiguration.java:[45,13] cannot find symbol
[ERROR]   symbol:   class HealthCheckRegistry
[ERROR]   location: class com.company.myapp.config.MetricsConfiguration
[ERROR] /Users/sierra/github/pmverma/5732581/src/main/java/com/company/myapp/config/MetricsConfiguration.java:[68,12] cannot find symbol
[ERROR]   symbol:   class HealthCheckRegistry
[ERROR]   location: class com.company.myapp.config.MetricsConfiguration
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

```
##### **Motivation for or Use Case**

Automatic and manual upgrade should work identically.

##### **Reproduce the error**

- create a 5.7.2 app `mkdir 5722581 && cd 5722581 && npm install generator-jhipster@5.7.2 && jhipster`
- Compiling the app without any problem `./mvnw compile`
- ~~Manual upgrade to 5.8.1 `rm -fr * && npm install generator-jhipster@5.8.1 && jhipster`~~
- Manual upgrade to 5.8.1 `rm -fr node_modules && npm install generator-jhipster@5.8.1 && jhipster`
- Compiling the app will fail `./mvnw compile`

##### **Suggest a Fix**

- It seems version 5.8.1 is not generating the `MetricsConfiguration.java` anymore. Removing the corresponding file should work but not confirmed.

##### **JHipster Version(s)**

```
5732581@0.0.0 /Users/sierra/github/pmverma/5732581
└── generator-jhipster@5.8.1 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.company.myapp",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "5.8.1",
    "applicationType": "monolith",
    "baseName": "5732581",
    "packageName": "com.company.myapp",
    "packageFolder": "com/company/myapp",
    "serverPort": "8080",
    "authenticationType": "oauth2",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "npm",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "otherModules": [],
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ],
    "entitySuffix": "",
    "dtoSuffix": "DTO"
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_172"
Java(TM) SE Runtime Environment (build 1.8.0_172-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.172-b11, mixed mode)

git version 2.17.2 (Apple Git-113)

node: v10.14.2

npm: 6.4.1

yeoman: 2.0.5

Docker version 18.09.1, build 4c52b90

docker-compose version 1.23.2, build 1110ad01

**Comment by pmverma** [comment] 2019-02-06 06:03
@clement26695 @PierreBesson will know it better. This might be related to switching to micrometer from dropwizard metrics. If suggested fix can work then I can do a PR.

**Comment by jdubois** [comment] 2019-02-06 06:38
Is this a duplicate with #9200 ?

**Comment by pmverma** [comment] 2019-02-06 06:51
Titles looks similar. I checked it before creating the issue. Both are irrelevant.

**Comment by PierreBesson** [comment] 2019-02-06 06:54
@jdubois those are not the same issues.

As for this particular issue. It seems to me that MetricsConfiguration.java could ne added to the JHipster cleanup phase but there is not much more that we can do. @pmverma if you know how to do it, can you do a PR please.

**Comment by pmverma** [comment] 2019-02-06 07:17
Thanks @PierreBesson, I will check and do a PR.

**Comment by pmverma** [comment] 2019-02-06 09:09
As far as I can search, the cleanup code is already there for version 5.8.0 and working for upgrade sub-generator.

https://github.com/jhipster/generator-jhipster/blob/cb83d080a2bdf31b75ebdbaa11c6c773f69fc67c/generators/cleanup.js#L73-L77
https://github.com/jhipster/generator-jhipster/blob/cb83d080a2bdf31b75ebdbaa11c6c773f69fc67c/generators/cleanup.js#L172-L174

Need to check more deeply.

**Comment by clement26695** [comment] 2019-02-06 10:01
I tried to reproduce but everything works fine when I follow the steps you provide to reproduce. I don't undestand why MetricsConfiguration file exists, as it should be deleted by  `rm -fr *`  and it should not be generated whit 5.8.1. I indeed also add it to the cleanup.js file.

What I don't understand either is why MetricsConfiguration.java.ejs is still present in the generator (as well as some other files I deleted in the micrometer migration) : I guess there were some mixup with the change in the licences

**Comment by pmverma** [comment] 2019-02-06 11:35
Oh my mistake. Thanks @clement26695! Actually it is `rm -fr node_modules`. I have updated there.

**Comment by clement26695** [comment] 2019-02-06 13:39
Does the cleanup script run when you do the upgrade manually ?

**Comment by clement26695** [comment] 2019-02-06 13:52
It seems that when you regenerate your app, your .yo-rc.json is updated before the cleanup script run. 

It causes that the cleanup script does not detect your generated your app with a previous version, and so it does not delete the old files

**Comment by pmverma** [comment] 2019-02-06 15:53
Yes @clement26695 , I can confirm it. By the time it run the cleanup script, version number in .yo-rc.json is already updated hence returning `false` value for `generator.isJhipsterVersionLessThan('5.8.0')`

**Comment by pascalgrimaud** [comment] 2019-04-22 09:02
I think we can close this after:
- https://github.com/jhipster/generator-jhipster/pull/9360
- https://github.com/jhipster/generator-jhipster/pull/9375

Anyway, it's not a good idea to migrate from 5 to 6, because there are too much breaking changes :)

**Closed by pascalgrimaud** 2019-04-22 09:02 UTC
Labels: bug :bug:, upgrade
