### ISSUE TITLE
jdl enum section cannot have java comments

### ISSUE THREAD

**Issue by joro88** [jhipster/generator-jhipster#15185] opened 2021-06-01 20:19 UTC
##### **Overview of the issue**
Javadoc comments /** this style */ are not allowed for enum values.

Stacktrace:

```
error: Syntax error message:
        MismatchedTokenException: Found an invalid token '/** comment */', at line: 43 and column: 20.
        Please make sure your JDL content does not use invalid characters, keywords or options.
Error during import-jdl: Error: MismatchedTokenException: Found an invalid token '/** comment */', at line: 43 and column: 20.
        Please make sure your JDL content does not use invalid characters, keywords or options.
Error: MismatchedTokenException: Found an invalid token '/** comment */', at line: 43 and column: 20.
        Please make sure your JDL content does not use invalid characters, keywords or options.
    at throwErrorAboutInvalidToken (C:\Users\Joro\AppData\Local\nvs\node\14.17.0\x64\node_modules\generator-jhipster\jdl\parsing\api.js:85:9)
    at throwParserError (C:\Users\Joro\AppData\Local\nvs\node\14.17.0\x64\node_modules\generator-jhipster\jdl\parsing\api.js:72:5)
    at getCst (C:\Users\Joro\AppData\Local\nvs\node\14.17.0\x64\node_modules\generator-jhipster\jdl\parsing\api.js:57:5)
    at Object.parse (C:\Users\Joro\AppData\Local\nvs\node\14.17.0\x64\node_modules\generator-jhipster\jdl\parsing\api.js:40:15)
    at callApiMethod (C:\Users\Joro\AppData\Local\nvs\node\14.17.0\x64\node_modules\generator-jhipster\jdl\readers\jdl-reader.js:98:30)
    at parse (C:\Users\Joro\AppData\Local\nvs\node\14.17.0\x64\node_modules\generator-jhipster\jdl\readers\jdl-reader.js:84:25)
    at Object.parseFromFiles (C:\Users\Joro\AppData\Local\nvs\node\14.17.0\x64\node_modules\generator-jhipster\jdl\readers\jdl-reader.js:43:10)
    at parseFiles (C:\Users\Joro\AppData\Local\nvs\node\14.17.0\x64\node_modules\generator-jhipster\jdl\jdl-importer.js:129:20)
    at createImporterFromFiles (C:\Users\Joro\AppData\Local\nvs\node\14.17.0\x64\node_modules\generator-jhipster\jdl\jdl-importer.js:61:19)
    at JDLProcessor.importJDL (C:\Users\Joro\AppData\Local\nvs\node\14.17.0\x64\node_modules\generator-jhipster\cli\import-jdl.js:356:18)
ERROR! Error during import-jdl: MismatchedTokenException: Found an invalid token '/** comment */', at line: 43 and column: 20.
        Please make sure your JDL content does not use invalid characters, keywords or options.
Error: Error during import-jdl: MismatchedTokenException: Found an invalid token '/** comment */', at line: 43 and column: 20.
        Please make sure your JDL content does not use invalid characters, keywords or options.
    at module.exports (C:\Users\Joro\AppData\Local\nvs\node\14.17.0\x64\node_modules\generator-jhipster\cli\import-jdl.js:482:27)
    at C:\Users\Joro\AppData\Local\nvs\node\14.17.0\x64\node_modules\generator-jhipster\cli\jdl.js:61:49
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Promise.all (index 0)
```

##### **Motivation for or Use Case**

Documentation state:
"Just like relationships, entities and fields, commenting is possible for enums, with the same rules."

https://www.jhipster.tech/jdl/enums

##### **Reproduce the error**

Try to add Javadoc comment for a enum value. 

##### **JHipster Version(s)**

JHipster 7.0.1

##### **JHipster configuration**

  <details>
  <summary>JDL definitions</summary>
  <pre>
Example JDL part:
enum NonWorkingDayType2 {
  OFFICIAL_HOLIDAY /** comment */,
  COMPANY_NON_WORKING_DAY
}
  </pre>
  </details>

##### **Browsers and Operating System**

Windows 10 

- [X ] Checking this box is mandatory (this is just to show you read everything)

**Comment by nomuna** [comment] 2021-06-03 04:53
@atomfrede looks like a duplicate of the issue #14869

```sh
enum Units { 
  /** This is the */
  KG, 
  LB
}
```
works.

```sh
enum Units { 
  /** This is the */
  KG /** This is the */, 
  LB
}
```

fails. At the first glance it looks like in order to support comments next to the individual values of each enum item will probably require the whole parser/lexer infrastructure to be adjusted -- change the grammar for the enum to include 
comments between items.

Not really an issue here to write the documentation of the enums as follows and avoid the error during import. How do you see the issue. :D 

```sh
/**
* KG - Some information
* LB - some information
*/
enum Units { 
  KG, 
  LB
}
```

**Comment by nomuna** [comment] 2021-06-03 05:33
This section in _jdlparser.js_ makes me believe that as enum property content only the name pattern and name with values in quotes parsed as string allowed. Apparently a new token has to be created which allows _name /** some text */_ patterns.
or change the regex for name to include comments as well.

```sh
enumProp() {
    this.RULE('enumProp', () => {
      this.CONSUME(LexerTokens.NAME, { LABEL: 'enumPropKey' });
      this.OPTION(() => {
        this.CONSUME(LexerTokens.LPAREN);
        this.OR([
          { ALT: () => this.CONSUME2(LexerTokens.STRING, { LABEL: 'enumPropValueWithQuotes' }) },
          { ALT: () => this.CONSUME3(LexerTokens.NAME, { LABEL: 'enumPropValue' }) },
        ]);
        this.CONSUME(LexerTokens.RPAREN);
      });
    });
  }
```

**Comment by swarajsaaj** [comment] 2021-06-03 05:49
Hi @nomuna @atomfrede ,

I spent some time on this, and was able to get this working with following steps (a bit rough, but if it helps :) ):-

1. Add an option for JAVADOC in jdl-parser.js
```java
enumProp() {
    this.RULE('enumProp', () => {
      this.OPTION(() => {
        this.CONSUME(LexerTokens.JAVADOC);
      });
      this.CONSUME(LexerTokens.NAME, { LABEL: 'enumPropKey' });
      this.OPTION1(() => {
        this.CONSUME(LexerTokens.LPAREN);
        this.OR([
          { ALT: () => this.CONSUME2(LexerTokens.STRING, { LABEL: 'enumPropValueWithQuotes' }) },
          { ALT: () => this.CONSUME3(LexerTokens.NAME, { LABEL: 'enumPropValue' }) },
        ]);
        this.CONSUME(LexerTokens.RPAREN);
      });
    });
  }
```
2. Change the `enumProp` grammer in `generated-serialized-grammer.js`
3. Pass comment in `prop` by reading context in `jdl-ast-builder-visitor.js` class's `enumProp` handler 
4. Add a comment field in `JDLEnumValue` class (constructed from `JDLEnum` class) and add the same in `toString()` method for templating the javadoc correctly.
5. Adjust the `stringifyKeys` method to not give javadocs in `getValueAsString` method, because that is used for creating the frontend models too.

**Closed** 2021-06-06 09:22 UTC
Labels: $$ bug-bounty $$, $100, area: triage, theme: JDL

**Comment by jdubois** [comment] 2022-07-19 11:57
@nomuna did you submit the bug bounty at https://opencollective.com/generator-jhipster/expenses/85980 ? I'm guessing it's you so I'm approving it

**Comment by nomuna** [comment] 2022-07-19 13:18
Yeah it was me. :D Thanks.
