### ISSUE TITLE
abstract state (site) controller (navbar) instantiated twice

### ISSUE THREAD

**Issue by kbjp** [jhipster/generator-jhipster#1495] opened 2015-05-19 08:34 UTC
how to reproduce:
Put a breakpoint on the line "$scope.$state = $state;" inside navbar.controller.js

The impact of this issue is that any site-wide code put inside that controller will get executed twice (in my personal case listening to server-side events)

Any idea how to fix ?

Regards

kbjp

**Comment by kbjp** [comment] 2015-05-19 08:47
Isn't "ng-controller" superfluous in navbar.html ? 
the controller is already instantiated by ui-router, right ?
kbjp

**Comment by tomsoete** [comment] 2015-05-19 10:05
You're right!

See my previous related pull request:
https://github.com/jhipster/generator-jhipster/pull/1134

**Comment by jdubois** [comment] 2015-05-20 10:02
From my understanding this is already fixed by #1134 -> I can't reproduce it, and I can't find the ng-controller again

**Closed by jdubois** 2015-05-20 10:02 UTC
