### ISSUE TITLE
MongoDB create entities fails

### ISSUE THREAD

**Issue by lucastaehli** [jhipster/generator-jhipster#16358] opened 2021-09-20 11:15 UTC
##### **Overview of the issue**

Unhandled promise rejection at:
TypeError: /home/liferay/test/node_modules/generator-jhipster/generators/entity-client/templates/react/src/main/webapp/app/entities/entity-update.tsx.ejs:164
    162| <%_ relFieldNames.forEach(rel => { _%>
    163| <%_ if (rel.relationshipManyToOne || (rel.ownerSide && rel.relationshipOneToOne))  { _%>
 >> 164|         <%= rel.relationshipFieldName %>: <%= rel.otherEntityNamePlural %>.find(it => it.<%= rel.otherEntity.primaryKey.name %>.toString() === values.<%= rel.relationshipFieldName %>Id.toString()),
    165| <%_ } _%>
    166| <%_ }) _%>
    167|     }

Cannot read property 'name' of undefined
##### **Motivation for or Use Case**

1. Generate workspace with mongodb
2. Add entities according https://www.jhipster.tech/managing-relationships :
```
entity Country {
  countryName String
}

@embedded
entity Region {
  regionName String
}


relationship OneToOne {
  Country to Region
}
```
3. Run jhipster jdl command

##### **Suggest a Fix**

I guess embedded documents dont have a primary Key:
rel.otherEntity.primaryKey.name

##### **JHipster Version(s)**

 "jhipsterVersion": "7.1.0"

##### **JHipster configuration**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "applicationType": "monolith",
    "baseName": "test",
    "jhipsterVersion": "7.1.0",
    "skipClient": false,
    "skipServer": false,
    "skipUserManagement": false,
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "testFrameworks": [],
    "blueprints": [],
    "otherModules": [],
    "pages": [],
    "creationTimestamp": 1632134523272,
    "serviceDiscoveryType": false,
    "reactive": false,
    "authenticationType": "jwt",
    "packageName": "com.mycompany.myapp",
    "serverPort": "8080",
    "cacheProvider": "ehcache",
    "enableHibernateCache": false,
    "databaseType": "mongodb",
    "buildTool": "gradle",
    "serverSideOptions": ["enableSwaggerCodegen:true"],
    "websocket": false,
    "searchEngine": false,
    "messageBroker": false,
    "enableSwaggerCodegen": true,
    "clientFramework": "react",
    "withAdminUi": true,
    "clientTheme": "none",
    "enableTranslation": false,
    "nativeLanguage": "en",
    "packageFolder": "com/mycompany/myapp",
    "jwtSecretKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "devDatabaseType": "mongodb",
    "prodDatabaseType": "mongodb",
    "devServerPort": 9060,
    "clientPackageManager": "npm",
    "clientThemeVariant": "",
    "languages": ["en", "fr"]
  }
}

</pre>

</details>
If you have a JDL please wrap it in below structure
  <details>
  <summary>JDL definitions</summary>
  <pre>
entity Country {
  countryName String
}

@embedded
entity Region {
  regionName String
}

relationship OneToOne {
  Country to Region
}
  </pre>
  </details>

##### **Browsers and Operating System**

CentOS7

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by mraible** [comment] 2022-02-18 04:21
@lucastaehli Can you provide a GitHub repo with this issue? Please regenerate your app with 7.6.0 to confirm it's still an issue.

**Comment by mshima** [comment] 2022-02-18 11:12
Probably duplicate of https://github.com/jhipster/generator-jhipster/issues/15524#issuecomment-1044320728

**Closed** 2022-04-11 09:49 UTC
Labels: area: duplicate, theme: react, area: needs-reproduction, theme: jhipster-internals, theme: relationships, theme: mongo
