### ISSUE TITLE
Upgrade to 7.7.0: No property fetchBagRelationships found for type Entity

### ISSUE THREAD

**Issue by tschig** [jhipster/generator-jhipster#17990] opened 2022-02-27 08:47 UTC
##### **Overview of the issue**
(Name of my Entity was replaced by "Entity", Name of my Project was replaced by "Example")

Backend won't start after updating to 7.7.0 from 7.6.0. 
Repositories now have a EntityRepositoryWithBagRelationships super class.
Starting the backend results in a "No property fetchBagRelationships found for type Entity!" Error.

##### **Motivation for or Use Case**

JHipster Backend won't start anymore

##### **Reproduce the error**

Upgrade a existing JHipster App from 7.6.0 to 7.7.0

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

Please see example project in comments.

Stacktrace:

```
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'exampleService' defined in file [F:\Development\example\MVP\Backend\target\classes\tv\example\service\example\exampleService.class]: Unsatisfied dependency expressed through constructor parameter 5; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'exampleEntityRepository' defined in tv.example.repository.example.exampleEntityRepository defined in @EnableJpaRepositories declared on DatabaseConfiguration: Invocation of init method failed; nested exception is org.springframework.data.repository.query.QueryCreationException: Could not create query for public abstract java.util.Optional tv.example.repository.EntityRepositoryWithBagRelationships.fetchBagRelationships(java.util.Optional)! Reason: Failed to create query for method public abstract java.util.Optional tv.example.repository.EntityRepositoryWithBagRelationships.fetchBagRelationships(java.util.Optional)! No property fetchBagRelationships found for type Entity!; nested exception is java.lang.IllegalArgumentException: Failed to create query for method public abstract java.util.Optional tv.example.repository.EntityRepositoryWithBagRelationships.fetchBagRelationships(java.util.Optional)! No property fetchBagRelationships found for type Entity!
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:800)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:229)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1372)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1222)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:953)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:732)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:414)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:302)
	at tv.example.exampleApp.main(exampleApp.java:69)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'exampleEntityRepository' defined in tv.example.repository.example.exampleEntityRepository defined in @EnableJpaRepositories declared on DatabaseConfiguration: Invocation of init method failed; nested exception is org.springframework.data.repository.query.QueryCreationException: Could not create query for public abstract java.util.Optional tv.example.repository.EntityRepositoryWithBagRelationships.fetchBagRelationships(java.util.Optional)! Reason: Failed to create query for method public abstract java.util.Optional tv.example.repository.EntityRepositoryWithBagRelationships.fetchBagRelationships(java.util.Optional)! No property fetchBagRelationships found for type Entity!; nested exception is java.lang.IllegalArgumentException: Failed to create query for method public abstract java.util.Optional tv.example.repository.EntityRepositoryWithBagRelationships.fetchBagRelationships(java.util.Optional)! No property fetchBagRelationships found for type Entity!
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1804)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1389)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1309)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:887)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:791)
	... 22 common frames omitted
Caused by: org.springframework.data.repository.query.QueryCreationException: Could not create query for public abstract java.util.Optional tv.example.repository.EntityRepositoryWithBagRelationships.fetchBagRelationships(java.util.Optional)! Reason: Failed to create query for method public abstract java.util.Optional tv.example.repository.EntityRepositoryWithBagRelationships.fetchBagRelationships(java.util.Optional)! No property fetchBagRelationships found for type Entity!; nested exception is java.lang.IllegalArgumentException: Failed to create query for method public abstract java.util.Optional tv.example.repository.EntityRepositoryWithBagRelationships.fetchBagRelationships(java.util.Optional)! No property fetchBagRelationships found for type Entity!
	at org.springframework.data.repository.query.QueryCreationException.create(QueryCreationException.java:101)
	at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.lookupQuery(QueryExecutorMethodInterceptor.java:106)
	at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.lambda$mapMethodsToQuery$1(QueryExecutorMethodInterceptor.java:94)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Collections$UnmodifiableCollection$1.forEachRemaining(Collections.java:1054)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.mapMethodsToQuery(QueryExecutorMethodInterceptor.java:96)
	at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.lambda$new$0(QueryExecutorMethodInterceptor.java:86)
	at java.base/java.util.Optional.map(Optional.java:265)
	at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.<init>(QueryExecutorMethodInterceptor.java:86)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport.getRepository(RepositoryFactorySupport.java:364)
	at org.springframework.data.repository.core.support.RepositoryFactoryBeanSupport.lambda$afterPropertiesSet$5(RepositoryFactoryBeanSupport.java:322)
	at org.springframework.data.util.Lazy.getNullable(Lazy.java:230)
	at org.springframework.data.util.Lazy.get(Lazy.java:114)
	at org.springframework.data.repository.core.support.RepositoryFactoryBeanSupport.afterPropertiesSet(RepositoryFactoryBeanSupport.java:328)
	at org.springframework.data.jpa.repository.support.JpaRepositoryFactoryBean.afterPropertiesSet(JpaRepositoryFactoryBean.java:144)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1863)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800)
	... 33 common frames omitted
Caused by: java.lang.IllegalArgumentException: Failed to create query for method public abstract java.util.Optional tv.example.repository.EntityRepositoryWithBagRelationships.fetchBagRelationships(java.util.Optional)! No property fetchBagRelationships found for type Entity!
	at org.springframework.data.jpa.repository.query.PartTreeJpaQuery.<init>(PartTreeJpaQuery.java:96)
	at org.springframework.data.jpa.repository.query.JpaQueryLookupStrategy$CreateQueryLookupStrategy.resolveQuery(JpaQueryLookupStrategy.java:113)
	at org.springframework.data.jpa.repository.query.JpaQueryLookupStrategy$CreateIfNotFoundQueryLookupStrategy.resolveQuery(JpaQueryLookupStrategy.java:254)
	at org.springframework.data.jpa.repository.query.JpaQueryLookupStrategy$AbstractQueryLookupStrategy.resolveQuery(JpaQueryLookupStrategy.java:87)
	at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.lookupQuery(QueryExecutorMethodInterceptor.java:102)
	... 55 common frames omitted
Caused by: org.springframework.data.mapping.PropertyReferenceException: No property fetchBagRelationships found for type Entity!
	at org.springframework.data.mapping.PropertyPath.<init>(PropertyPath.java:90)
	at org.springframework.data.mapping.PropertyPath.create(PropertyPath.java:437)
	at org.springframework.data.mapping.PropertyPath.create(PropertyPath.java:413)
	at org.springframework.data.mapping.PropertyPath.lambda$from$0(PropertyPath.java:366)
	at java.base/java.util.concurrent.ConcurrentMap.computeIfAbsent(ConcurrentMap.java:330)
	at org.springframework.data.mapping.PropertyPath.from(PropertyPath.java:348)
	at org.springframework.data.mapping.PropertyPath.from(PropertyPath.java:331)
	at org.springframework.data.repository.query.parser.Part.<init>(Part.java:81)
	at org.springframework.data.repository.query.parser.PartTree$OrPart.lambda$new$0(PartTree.java:249)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at org.springframework.data.repository.query.parser.PartTree$OrPart.<init>(PartTree.java:250)
	at org.springframework.data.repository.query.parser.PartTree$Predicate.lambda$new$0(PartTree.java:383)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at org.springframework.data.repository.query.parser.PartTree$Predicate.<init>(PartTree.java:384)
	at org.springframework.data.repository.query.parser.PartTree.<init>(PartTree.java:92)
	at org.springframework.data.jpa.repository.query.PartTreeJpaQuery.<init>(PartTreeJpaQuery.java:89)
	... 59 common frames omitted


Process finished with exit code 0
```

**Comment by Tcharl** [comment] 2022-02-28 11:59
Hi,

Can you also post your .yo-rc file please?

**Comment by mshima** [comment] 2022-02-28 15:25
Still missing information to reproduce.
The `meta` entity is missing.
`"entities": ["Entity"],`

**Comment by tschig** [comment] 2022-02-28 18:59
Hi @Tcharl, @mshima ,

I've bundeled all needed files to reproduce this error into this zip:
[jhi-bug-template.zip](https://github.com/jhipster/generator-jhipster/files/8155907/jhi-bug-template.zip)

Steps to reproduce:
 1. Run `jhipster`
 2. Run `jhipster entity thing`
 3. Run `mvnw` to check if app is starting -> App should start
 4. Add `MyThingRepository.java` to `\src\main\java\com\mycompany\myapp\repository`
 5. Run `mvnw` -> App does not start -> Produces error


(The method findThingsWithMeta is irrelevant. Application startup fails also with this method removed)

MyThingRepository.java:


```
package com.mycompany.myapp.repository;


import com.mycompany.myapp.domain.Meta;
import com.mycompany.myapp.domain.Thing;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Optional;

@Repository
public interface MyThingRepository extends ThingRepository {


    @Query("select thing from Thing thing left join fetch thing.metas metas where :meta in(metas)")
    Optional<List<Thing>> findThingsWithMeta(@Param("meta") Meta meta);
}
````

**Comment by Weltraumschaf** [comment] 2022-02-28 20:12
I have a similar problem in the resource integration tests. We use a side-by-side approach to customize/extend the generated code. We have an extended repository crafted by hand:

```java
@Repository
public interface ExtendedBadgeRepository extends BadgeRepository {
    List<Badge> findAllByDimensionsIsNull();

    Page<Badge> findByIdIn(List<Long> badgeIds, Pageable pageable);
}
```

which extends the generated repository:

```java
@Repository
public interface BadgeRepository extends BadgeRepositoryWithBagRelationships, JpaRepository<Badge, Long>, JpaSpecificationExecutor<Badge> {
    default Optional<Badge> findOneWithEagerRelationships(Long id) {
        return this.fetchBagRelationships(this.findOneWithToOneRelationships(id));
    }

    default List<Badge> findAllWithEagerRelationships() {
        return this.fetchBagRelationships(this.findAllWithToOneRelationships());
    }

    default Page<Badge> findAllWithEagerRelationships(Pageable pageable) {
        return this.fetchBagRelationships(this.findAllWithToOneRelationships(pageable));
    }

    @Query(
        value = "select distinct badge from Badge badge left join fetch badge.image",
        countQuery = "select count(distinct badge) from Badge badge"
    )
    Page<Badge> findAllWithToOneRelationships(Pageable pageable);

    @Query("select distinct badge from Badge badge left join fetch badge.image")
    List<Badge> findAllWithToOneRelationships();

    @Query("select badge from Badge badge left join fetch badge.image where badge.id =:id")
    Optional<Badge> findOneWithToOneRelationships(@Param("id") Long id);
}
```

This fails with the same error when running the resource integration tests:

> Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'customAchievableSkillServiceImpl' defined in file [.../out/production/classes/com/company/app/service/impl/custom/CustomAchievableSkillServiceImpl.class]: Unsatisfied dependency expressed through constructor parameter 2; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'extendedBadgeRepository' defined in com.company.app.repository.custom.ExtendedBadgeRepository defined in @EnableJpaRepositories declared on DatabaseConfiguration: Invocation of init method failed; nested exception is org.springframework.data.repository.query.QueryCreationException: Could not create query for public abstract java.util.Optional com.company.app.repository.BadgeRepositoryWithBagRelationships.fetchBagRelationships(java.util.Optional)! Reason: Failed to create query for method public abstract java.util.Optional com.company.app.repository.BadgeRepositoryWithBagRelationships.fetchBagRelationships(java.util.Optional)! No property fetchBagRelationships found for type Badge!; nested exception is java.lang.IllegalArgumentException: Failed to create query for method public abstract java.util.Optional com.company.app.repository.BadgeRepositoryWithBagRelationships.fetchBagRelationships(java.util.Optional)! No property fetchBagRelationships found for type Badge!

**Comment by mshima** [comment] 2022-02-28 22:19
So the problem is not with the generated code, but extending it using side-by-side.
Is the original repository package still in the `@EnableJpaRepositories`?
https://github.com/jhipster/generator-jhipster/blob/74a0ec1050f9853ad5b370dc574f07e1c6078012/generators/server/templates/src/main/java/package/config/DatabaseConfiguration_sql.java.ejs#L90

**Comment by tschig** [comment] 2022-02-28 22:34
Yes, problem seems to be related to extending the repository.

Original Repository is still in ```@EnableJpaRepositories```
![image](https://user-images.githubusercontent.com/1055580/156069738-ec6729d2-a612-4f87-9502-7c95cfde90f5.png)

**Comment by mshima** [comment] 2022-02-28 23:33
Try making the extended repository extend the `WithBagRelationships` interface.

**Comment by tschig** [comment] 2022-03-01 09:25
> Try making the extended repository extend the `WithBagRelationships` interface.

This won't work I think. 
We need to extend `ThingRepository` so that we can use it as a `JPARepository` for saving entities etc.

**Comment by Weltraumschaf** [comment] 2022-03-01 11:33
I can confirm what @tschig writes: Extending `BadgeRepositoryWithBagRelationships` additionally from `ExtendedBadgeRepository` fixes the problem.

Is there somewhere documentation about this feature? I've never seen autogenerated JPA methods starting with `fetch`. I searched the web tonight and the only hint I found was this issue.

**Comment by Weltraumschaf** [comment] 2022-03-02 14:44
ah, I see. There is a link to a [blog post](https://vladmihalcea.com/hibernate-multiplebagfetchexception/). I found this post during my research, but I didn't realize that this `ENTITYRepositoryWithBagRelationshipsImpl` is more or less a workaround for the problem described in the post.

Would be nice to have a hint somewhere in the [JHipster doc](https://www.jhipster.tech/jdl/relationships) 🤗

**Comment by mraible** [comment] 2022-03-11 07:34
Can we close this @tschig?

**Comment by tschig** [comment] 2022-03-11 08:03
@mraible I think at least the JHipster Documentation should be adjusted. 

This page seems to be outdated with 7.7.0:
[Tips & Tricks](https://www.jhipster.tech/tips/035_tip_combine_generation_and_custom_code.html)
Another hint elsewhere would be very nice, as @Weltraumschaf pointed out.

**Closed** 2022-05-02 16:30 UTC
Labels: area: bug :bug:, theme: java, theme: relationships
