### ISSUE TITLE
A getAll request for an entity with pagination enabled will only return 20 results if paging parameters are not set

### ISSUE THREAD

**Issue by geraldhumphries** [jhipster/generator-jhipster#2251] opened 2015-10-30 18:01 UTC
##### Overview of the issue
Generating an entity with pagination (infinite scroll or full pagination, haven't tested simple pagination) will cause a `getAllEntities` request without parameters to return only 20 results.

Tests break for `getAllEntities` because the returned list of entities does not contain the entity added during `entityRepository.saveAndFlush(entity)`. This only happens when adding test data through liquibase:
```
Expected: a collection containing <509>
     but: was <2>, was <3>, was <4>, was <5>, was <6>, was <7>, was <8>, was <9>, was <10>, was <11>, was <12>, was <14>, was <16>, was <17>, was <18>, was <19>, was <20>, was <22>, was <25>, was <26>
java.lang.AssertionError: JSON path "$.[*].id"
```

##### Motivation for or Use Case
`getAllEntities` unit tests will fail if sample data (through liquibase) for the entity is more than 20 rows, and dropdowns that contain a list of that entity (in entity create/edit modals, for example) will only have the first 20 results.

##### JHipster Version
2.23.0

##### Reproduce the error
Create an entity with full pagination or infinite scrolling enabled, insert more than 20 rows, then send a request to the getAll method.

##### Suggest a Fix
Perhaps use the @PageableDefault annotation or add another method to the resource that does not use Pageable.

**Comment by cbornet** [comment] 2015-10-31 09:27
Why do you add test data with Liquibase ? For your own ITs ?
Although the standard JHipster tests assume an empty database, there has been improvements in the past to support pre-loaded data. So I guess this could also be done for pre-loaded database with pagination enabled.

**Comment by cbornet** [comment] 2015-10-31 10:14
Also note that if the data is not meant initially for tests but for your running dev/prod server, you can use liquibase context property in changeset to prevent loading if the context is test.

**Comment by geraldhumphries** [comment] 2015-11-01 07:10
The tests failing is just an observed effect - the main issue is the functionality. `getAllEntities()` does not actually get all entities by default, and this is noticeable in JHipster's generated entity managers where dropdowns only contain the first twenty results. I see that as a bug, unless this is intended behavior when pagination is used.

**Comment by deepu105** [comment] 2015-11-01 09:06
Ok the real issue here is that when the entity is shown in dropdowns for
one to many and many to many relationships it shows only default 20.

**Comment by cbornet** [comment] 2015-11-01 09:07
This is not a bug : this is pagination. When you query api/foos, you get one page of foos which by default is 20 items. You can query api/foos?size=2000 to get 2000 items.

**Comment by deepu105** [comment] 2015-11-01 09:09
I guess we should either add a non paged getAll or set some high values for paging when getting entities for drop downs. A new method might be cleaner

**Comment by cbornet** [comment] 2015-11-01 10:55
Yes the dropdown size is a problem. However shouldn't we keep some limitation on the size of the dropdown ? Imagine your entity table has 1M rows...

**Comment by cbornet** [comment] 2015-11-01 11:00
Same as for the unit test. IMO entities that have a lot of items should be set as pageable if you don't want to OOM and getAll should be called with a reasonable size limit

**Comment by deepu105** [comment] 2015-11-01 12:09
For dropdowns such cases should be implemented as an autocomplete kind of thing but thats out of our scope i guess, but normally it shouldn't be returning just 20 without option to fetch remaining

**Comment by jdubois** [comment] 2015-11-05 22:50
It's not really an issue, this is what pagination is all about, and this is on purpose (but I agree my purpose is not clearly documented!)
This can also be re-configured easily (as well as the Spring Data pagination, which is also limited).

For the drop-down list I understand the issue, but we can't send the whole entities in a drop down list if it's too big, anyway.

I don't really have a solution for this: we have pagination by default, which is good, and otherwise you need to reconfigure your code.

If anybody has a better idea I'm really opened for suggestions (especially for the drop down lists), but for the moment I'm closing this as it's not a bug. It might become a feature request if anyone has a good idea!

**Closed by jdubois** 2015-11-05 22:50 UTC
Labels: bug, enhancement

**Comment by naris** [comment] 2021-09-18 03:34
> It's not really an issue, this is what pagination is all about, and this is on purpose (but I agree my purpose is not clearly documented!)
> This can also be re-configured easily (as well as the Spring Data pagination, which is also limited).
> 
> For the drop-down list I understand the issue, but we can't send the whole entities in a drop down list if it's too big, anyway.
> 
> I don't really have a solution for this: we have pagination by default, which is good, and otherwise you need to reconfigure your code.
> 
> If anybody has a better idea I'm really opened for suggestions (especially for the drop down lists), but for the moment I'm closing this as it's not a bug. It might become a feature request if anyone has a good idea!

This issue has been closed for a while, but I am also working with a dropdown and it became clear that in order to have sorting, you have to have paging for some reason, then I ran into the size thing. I would suggest specifying a size of 0 should disable paging for that query, that way you don't have too have some random large number as a size to confuse people that maintain it later on.

**Comment by geraldhumphries** [comment] 2021-11-24 17:37
@naris Actually, you can have sorting without paging! A `PagingAndSortingRepository` has a `findAll(Sort sort)` method. You need to have an endpoint on your API that accepts a `Sort` rather than a `Pageable`, then pass that Sort object into the `findAll` method of the repository. You can also write your own repository methods that accept `Sort`. 

Here's a good example: https://stackoverflow.com/a/50984488/1977915
