### ISSUE TITLE
Required constraint in relationships and DTO option generate error in Angular

### ISSUE THREAD

**Issue by erickjvallejo** [jhipster/generator-jhipster#9844] opened 2019-06-02 16:25 UTC
##### **Overview of the issue**

I have imported my JDL file and notice that in Angular when I tried to update or create a record I have got an error of missing field and the value does not appear for textbox.

![error-in-angular](https://user-images.githubusercontent.com/21186106/58762810-37e5e280-8519-11e9-9b3b-98eddeaa0718.png)

##### **Motivation for or Use Case**

1. import-jdl
2. relationship ManyToOne  +  required
3. dto ENTITY with mapstruct
4. ERROR in the front

##### **Reproduce the error**

I imported a JDL file with below command:

- mvn clean & jhipster import-jdl Books.jdl --force --debug & mvnw

This is my JDL model:
```uml
entity Book {
	name String,
	isbn String
}
entity Author {
  name String required
}

relationship ManyToOne {
  Book{author(name) required} to Author
}

dto * with mapstruct


```

##### **Related issues**

These are very close:

- https://github.com/jhipster/generator-jhipster/issues/6835
- https://github.com/jhipster/generator-jhipster/issues/1760

##### **Suggest a Fix**

The problem is that Angular code does not prepare to manage the structure of rest service with and without DTO: 

Rest service without DTO:
![withoutDTO](https://user-images.githubusercontent.com/21186106/58763645-0d992280-8523-11e9-84ec-71ac3b9d67a5.png)

Rest service with DTO:
![withDTO](https://user-images.githubusercontent.com/21186106/58763647-11c54000-8523-11e9-8b19-4089c917ee0e.png)

- Solution in book-update-component.ts is add authorName in editForm, updateForm, createFormForm

```javascript
 editForm = this.fb.group({
    id: [],
    name: [],
    isbn: [],
    authorId: [null, Validators.required],
    authorName: []
  });

  updateForm(book: IBook) {
    this.editForm.patchValue({
      id: book.id,
      name: book.name,
      isbn: book.isbn,
      authorId: book.authorId,
      authorName: book.authorName
    });
  }

  private createFromForm(): IBook {
    const entity = {
      ...new Book(),
      id: this.editForm.get(['id']).value,
      name: this.editForm.get(['name']).value,
      isbn: this.editForm.get(['isbn']).value,
      authorId: this.editForm.get(['authorId']).value,
      authorName: this.editForm.get(['authorName']).value
    };
    return entity;
  }
```
- Solution in book-update.component.html is change author for authorName 
```html               
<div class="form-group">
    <label class="form-control-label" jhiTranslate="appApp.book.author" for="field_author">Author</label>
    <select class="form-control" id="field_author" name="authorName" formControlName="authorId">
        <option *ngIf="!editForm.get('authorName').value" [ngValue]="null" selected></option>
        <option [ngValue]="authorOption.id" *ngFor="let authorOption of authors; trackBy: trackAuthorById">{{authorOption.name}}</option>
    </select>
</div>
<div *ngIf="editForm.get('authorName').invalid && (editForm.get('authorName').dirty || editForm.get('authorName').touched)">
    <small class="form-text text-danger"
           *ngIf="editForm.get('authorName').errors.required" jhiTranslate="entity.validation.required">
        This field is required.
    </small>
</div>
```

##### **JHipster Version(s)**

- 6.0.1

##### **JHipster Version(s)**

```
app@0.0.0 C:\XXX\XXX\XXX\XX\jhipster\app
`-- generator-jhipster@6.0.1

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.demo",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "6.0.1",
    "applicationType": "monolith",
    "baseName": "app",
    "packageName": "com.demo",
    "packageFolder": "com/demo",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "[masked]",
    "clientFramework": "angularX",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "useSass": true,
    "clientPackageManager": "npm",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": ["en"]
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Book {
  name String,
  isbn String
}
entity Author {
  name String required
}
relationship ManyToOne {
  Book{author(name) required} to Author
}

dto Book, Author with mapstruct
service Book, Author with serviceClass

</pre>
</details>

##### **Environment and Tools**

java version "12.0.1" 2019-04-16
Java(TM) SE Runtime Environment (build 12.0.1+12)
Java HotSpot(TM) 64-Bit Server VM (build 12.0.1+12, mixed mode, sharing)

git version 2.21.0.windows.1

node: v10.15.3

npm: 6.4.1

yeoman: 2.0.6

yarn: 1.16.0

INFO! Congratulations, JHipster execution is complete!

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

-  Again
```uml
entity Book {
	name String,
	isbn String
}
entity Author {
  name String required
}

relationship ManyToOne {
  Book{author(name) required} to Author
}

dto * with mapstruct
```

##### **Browsers and Operating System**

- Google Chrome

- Windows 10

**Comment by DanielFran** [comment] 2019-06-02 20:22
I transferes it to this repo and reopen it.

**Comment by erickjvallejo** [comment] 2019-06-02 20:43
Thanks you! Regards.

**Comment by clement26695** [comment] 2019-06-03 08:09
I think it is the issue was solved in #9806 and #9768: applying the same fix (ie changing author to authorId in the editForm.get function, without changing anything else) solves the issue for me.

Can you tell me if it is also the case for you @erickjvallejo ?

**Comment by pascalgrimaud** [comment] 2019-06-03 11:01
I can confirm the issue with v6.0.1
And I can confirm too the issue is resolved with current master, so @clement26695 is right :)

I'm closing this, as it's a duplicated issue.

**Closed by pascalgrimaud** 2019-06-03 11:01 UTC
Labels: area: needs-reproduction, theme: JDL, theme: relationships

**Comment by erickjvallejo** [comment] 2019-06-03 15:44
Hi @clement26695 thank you for your PR, this will  resolve the issue. Many thanks!

Regards,
