### ISSUE TITLE
Can't  install other generators from the JHipster Marketplace + blank page for client project 

### ISSUE THREAD

**Issue by p4535992** [jhipster/generator-jhipster#5563] opened 2017-04-09 09:10 UTC
##### **Overview of the issue**

When i start to use `yo jhipster` and i decide to use the marketplace i get the following stacktrace exception, is strange because the first project i made has been built without a problem like in the video tuorial of the site, i put the image of the exception:

![jhipster_exception_use_add_generator](https://cloud.githubusercontent.com/assets/5201916/24836033/c56230ae-1d11-11e7-86fe-1c3ce050ce43.png)

if i choose to no use the marketplace the app is build fine but return on client (`mvnw` if maven on localhost:8080) a blank page wihtout  exception,  on server side (`yarn start` on localhost:9090) seems work fine instead

##### **Motivation for or Use Case**

Is a bug  (on my opinion) because is pure code "create a application" of jhipster i don't touch anything, is the default project i created with jhipster it's not working.

##### **Reproduce the error**

My steps on the creation of a application:

1. Install JHipster yarn global add generator-jhipster
2. Create a new directory and go into it mkdir myApp && cd myApp
3. Run JHipster and follow instructions on screen yo jhipster
4. Select Monolithic Application and enter
5. Select the name of my application and enter
6. Select  yes or no on the question "if  i like to install generators from the jhipster marketplace" and enter
   6.1 if i choose yes => **[ERROR]** Exception i showed in the image at the "Overview of issue" paragraph.
   6.2 if i choose no everything seems fine
7. Select other choice like database , version of angular i want to use , ecc.
..............
8. Start the application with mvnw (if maven)
9. **[ERROR]** blank page in all the browser 

I put a image with the all choices i made it for the project when i choose to no install some generator from the  marketplace:

![jhipster_exception_choice_propject](https://cloud.githubusercontent.com/assets/5201916/24836038/d3dd0b54-1d11-11e7-9819-2626ea00d073.png)

NOTE: I made a checkout to the database MySQL i'm using and seems all fine for confirmed that i put a image with the result of the run of the spring boot project with the ide intellijidea:
![jhipster_build_idea](https://cloud.githubusercontent.com/assets/5201916/24836116/c3676466-1d13-11e7-9d61-1798166f702c.jpg)

##### **Related issues**
For the exception launched to the select "yes i want to use the marketplace":

- can't find no one previuos issue related to this problem.

For the blanck page issue i found this reference (i read them but the solutions suggesteds not seems the case):

- https://github.com/jhipster/generator-jhipster/issues/4466  
- https://github.com/jhipster/generator-jhipster/issues/3540
- https://github.com/jhipster/generator-jhipster/issues/3385
- https://github.com/jhipster/generator-jhipster/issues/3527

##### **Suggest a Fix**

Sorry not sure what the problem is , i can just say the first project i maded work's fine at start but now is show just a blank page so maybe is some system setting  of my windows machine , but i haven't change none , i anyway delete all the npm_module and npm_module cache (local and global) reinstalled npm, yarn, yeoman and jhipster just to be sure i haven't corrupted some file when tested the first project.

##### **JHipster Version(s)**

4.2.0 (the current version if i'm not wrong)

##### **JHipster configuration**

**yo jhipster:info**
```
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

git version 2.9.3.windows.1

node: v6.9.1

npm: 4.4.4

bower: 1.8.0

gulp:
[11:03:22] CLI version 1.2.2

yeoman: 1.8.5

yarn: 0.21.3

Docker version 17.03.1-ce, build c6d412e

docker-compose version 1.11.2, build f963d76f`
```

**.yo-rc.json file**
```json
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.github.p4535992.jhipster03"
    },
    "jhipsterVersion": "4.2.0",
    "baseName": "jhipster04",
    "packageName": "com.github.p4535992.jhipster03",
    "packageFolder": "com/github/p4535992/jhipster03",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "rememberMeKey": "bbb80cb68615d0ab4b79f85a70de7a9d673e0df1",
    "clientFramework": "angular2",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

Not arrived at the point to need the import of some entities

##### **Browsers and Operating System**

- My SO is Windows 10
- The error is present in Firefox, Chrome e Mircrosoft Edge

- [ *] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment] 2017-04-09 10:00
I confirm: there is a problem when selecting the marketplace option

**Comment by pascalgrimaud** [comment] 2017-04-09 10:17
Found the problem:
- it comes from this line: https://github.com/jhipster/generator-jhipster/blob/a52b24d288a56b20eb5c1d37c2b2fd0581504dea/generators/app/prompts.js#L146
- [${modDef.package.author.name}] is null because there is one module wihout author name: generator-jhipster-db-helper

**Comment by deepu105** [comment] 2017-04-09 10:53
Then we should add a null check

**Comment by AdrienHorgnies** [comment] 2017-04-10 07:03
It seems fine now, can you confirm ?

Sorry about that, my colleague wanted to put both our names, hence the array. It was fixed with f4573c4f and I've published it.

**Comment by bastienmichaux** [comment] 2017-04-10 07:26
I'm the culprit here. When I started working on our JHipster module I put an array for the author property in our package.json (crediting me and AdrienHorgnies). I had NO idea this could happen. Sorry for that. We fixed it now. Still, this is quite surprising.

**Closed** 2017-04-10 08:44 UTC
Labels: bug

**Comment by p4535992** [comment] 2017-04-10 12:01
Sorry for  the delay, i confirm the marketplace configurations now it's work, i have still the problem of the blank page on the client application (localhost:8080) , try to figure out  by myself or open a new issue ticket with all the informations about it.
ty everyone for the help.

**Comment by pascalgrimaud** [comment] 2017-04-10 12:13
@p4535992 : if you have an issue with blank page, plz open a new ticket with full details so we can reproduce. But be sure:
- the front is build (typescript) with yarn run webpack:build
- to config your addblock in your browser

**Comment by yanweiqi** [comment] 2017-06-16 07:15
Welcome to the JHipster Generator v4.5.3
Documentation for creating an application: https://jhipster.github.io/creating-an-app/
Application files will be generated in folder: E:\er\jhipster\blog
? (1/16) Which *type* of application would you like to create? Monolithic application (recommended for simple projects)
? (2/16) What is the base name of your application? ywqblog
? (3/16) Would you like to install other generators from the JHipster Marketplace? Yes
undefined:1
Internal Server Error
^

SyntaxError: Unexpected token I in JSON at position 0
    at Object.parse (native)
    at generator.httpsGet (D:\deveolpTools\node\node_global\node_modules\generator-jhipster\generators\app\prompts.js:159:37)
    at IncomingMessage.res.on (D:\deveolpTools\node\node_global\node_modules\generator-jhipster\generators\generator-base.js:2097:17)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

**Comment by rnbsoft** [comment] 2017-06-16 08:35
Just following the "Getting started" guide in the homepage.
I am getting the same errors. 

? (1/16) Which *type* of application would you like to create? Microservice gat
eway
? (2/16) What is the base name of your application? licy
? (3/16) Would you like to install other generators from the JHipster Marketpla
ce? Yes
undefined:1
Internal Server Error
^

SyntaxError: Unexpected token I in JSON at position 0
    at Object.parse (native)
    at generator.httpsGet (C:\Users\User\AppData\Local\Yarn\config\global\node_m
odules\generator-jhipster\generators\app\prompts.js:159:37)
    at IncomingMessage.res.on (C:\Users\User\AppData\Local\Yarn\config\global\no
de_modules\generator-jhipster\generators\generator-base.js:2097:17)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

**Comment by ibrodjabi** [comment] 2017-06-16 11:43
Hello ! Sames probems with my case. I need help. Thanks !

**Comment by jdubois** [comment] 2017-06-16 11:47
Please don't comment on old issues, if you have a new issue please follow the guidelines

**Comment by deepu105** [comment] 2017-06-16 12:11
@ibrodjabi @rnbsoft its tarcked here https://github.com/jhipster/generator-jhipster/issues/5934
@jdubois I think this is a critical bug for people trying to use marketplace

**Comment by jdubois** [comment] 2017-06-16 12:53
Yes I'll try to do a release, but not easy at the moment
