### ISSUE TITLE
JDL generates bad json

### ISSUE THREAD

**Issue by drez769** [jhipster/generator-jhipster#9225] opened 2019-02-08 19:23 UTC
##### **Overview of the issue**

`jhipster import-jdl` command generates bad json and .java file for entities. This started happening after upgrading from JHipster ~v5.4.2 to 5.8+. 
The JDL I used is:
```
entity Mom {
	name String
}

entity Child {
	name String
}

relationship ManyToOne {
	Child{mom(name)} to Mom{children(name)}
}
```

**I noticed this isn't the same as what `jhipster info` shows below**

The resulting Child.json file has this block with incorrect otherEntityRelationshipName with parenthesis:

```json
...
"relationships": [
        {
            "relationshipType": "many-to-one",
            "relationshipName": "mom",
            "otherEntityName": "mom",
            "otherEntityField": "name",
------> "otherEntityRelationshipName": "children(name)"
        }
    ],
...
```

which also creates an incorrect part of the Child.java file:

```java
...
@ManyToOne
    @JsonIgnoreProperties("children(name)S")
    private Mom mom;
...
```

##### **Motivation for or Use Case**

This breaks JDL and creates incorrect files. The java entity has incorrect @JsonIgnoreProperties now

##### **Reproduce the error**

1. NPM install generator-jhipster and run the `jhipser` command, accept all defaults
2. create a JDL file as shown above
3. run `jhipster import-jdl` command for JDL file
4. Notice bad .json and .java files

##### **Related issues**

[9202](https://github.com/jhipster/generator-jhipster/issues/9202)
[9212](https://github.com/jhipster/generator-jhipster/issues/9212)

##### **Suggest a Fix**

Not sure, something wrong with an update to JDL parsing?

##### **JHipster Version(s)**

5.8.1

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

INFO! Using JHipster version installed locally in current project's node_modules
INFO! Executing jhipster:info
INFO! Options: from-cli: true
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
test@0.0.0 C:\dev\code\test
`-- generator-jhipster@5.8.1

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```
<details>
<summary>.yo-rc.json file</summary>
<pre>
{
    "generator-jhipster": {
        "promptValues": {
            "packageName": "com.mycompany.myapp",
            "nativeLanguage": "en"
        },
        "jhipsterVersion": "5.8.1",
        "applicationType": "monolith",
        "baseName": "test",
        "packageName": "com.mycompany.myapp",
        "packageFolder": "com/mycompany/myapp",
        "serverPort": "8080",
        "authenticationType": "jwt",
        "cacheProvider": "ehcache",
        "enableHibernateCache": true,
        "websocket": false,
        "databaseType": "sql",
        "devDatabaseType": "h2Disk",
        "prodDatabaseType": "mysql",
        "searchEngine": false,
        "messageBroker": false,
        "serviceDiscoveryType": false,
        "buildTool": "maven",
        "enableSwaggerCodegen": false,
        "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
        "clientFramework": "angularX",
        "useSass": true,
        "clientPackageManager": "npm",
        "testFrameworks": [],
        "jhiPrefix": "jhi",
        "entitySuffix": "",
        "dtoSuffix": "DTO",
        "otherModules": [],
        "enableTranslation": true,
        "nativeLanguage": "en",
        "languages": ["en"]
    }
}

</pre>
</details>


##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Mom {
  name String
}
entity Child {
  name String
}
relationship OneToMany {
  Mom{children} to Child{mom(name)}
}


</pre>
</details>


##### **Environment and Tools**

java version "1.8.0_191"
Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.191-b12, mixed mode)

git version 2.18.0.windows.1

node: v10.13.0

npm: 6.4.1

yarn: 1.10.1

INFO! Congratulations, JHipster execution is complete!
```

##### **Browsers and Operating System**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by MathieuAA** [comment] 2019-02-08 19:48
Hi, there are some fixes that have been implemented recently. I'm gonna check everything's good this week-end.Le 8 févr. 2019 20:23, drez769 <notifications@github.com> a écrit :For bug reports it is mandatory to run the command jhipster info in your project's root folder, and paste the result here.
Overview of the issue
jhipster import-jdl command generates bad json and .java file for entities. This started happening after upgrading from JHipster ~v5.4.2 to 5.8+. Please see the below JDL I am using. The resulting Child.json file has this block with incorrect otherEntityRelationshipName with parenthesis:
...
"relationships": [
        {
            "relationshipType": "many-to-one",
            "relationshipName": "mom",
            "otherEntityName": "mom",
            "otherEntityField": "name",
------> "otherEntityRelationshipName": "children(name)"
        }
    ],
...
which also creates an incorrect part of the Child.java file:
...
...
Motivation for or Use Case

Reproduce the error

NPM install generator-jhipster and run the jhipser command, accept all defaultscreate a JDL file as shown in the configs belowrun jhipster import-jdl commandNotice bad .json and .java files
Related issues

Suggest a Fix
Not sure, something wrong with an update to JDL parsing?
JHipster Version(s)
5.8.1
JHipster configuration

Entity configuration(s) entityName.json files generated in the .jhipster directory
INFO! Using JHipster version installed locally in current project's node_modules
INFO! Executing jhipster:info
INFO! Options: from-cli: true
Welcome to the JHipster Information Sub-Generator
JHipster Version(s)
test@0.0.0 C:\dev\code\test
`-- generator-jhipster@5.8.1


JHipster configuration, a .yo-rc.json file generated in the root folder
<details>
<summary>.yo-rc.json file</summary>
<pre>
{
    "generator-jhipster": {
        "promptValues": {
            "packageName": "com.mycompany.myapp",
            "nativeLanguage": "en"
        },
        "jhipsterVersion": "5.8.1",
        "applicationType": "monolith",
        "baseName": "test",
        "packageName": "com.mycompany.myapp",
        "packageFolder": "com/mycompany/myapp",
        "serverPort": "8080",
        "authenticationType": "jwt",
        "cacheProvider": "ehcache",
        "enableHibernateCache": true,
        "websocket": false,
        "databaseType": "sql",
        "devDatabaseType": "h2Disk",
        "prodDatabaseType": "mysql",
        "searchEngine": false,
        "messageBroker": false,
        "serviceDiscoveryType": false,
        "buildTool": "maven",
        "enableSwaggerCodegen": false,
        "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
        "clientFramework": "angularX",
        "useSass": true,
        "clientPackageManager": "npm",
        "testFrameworks": [],
        "jhiPrefix": "jhi",
        "entitySuffix": "",
        "dtoSuffix": "DTO",
        "otherModules": [],
        "enableTranslation": true,
        "nativeLanguage": "en",
        "languages": ["en"]
    }
}

</pre>
</details>


##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Mom {
  name String
}
entity Child {
  name String
}
relationship OneToMany {
  Mom{children} to Child{mom(name)}
}


</pre>
</details>


##### **Environment and Tools**

java version "1.8.0_191"
Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.191-b12, mixed mode)

git version 2.18.0.windows.1

node: v10.13.0

npm: 6.4.1

yarn: 1.10.1

INFO! Congratulations, JHipster execution is complete!

Browsers and Operating System

 Checking this box is mandatory (this is just to show you read everything)

**Comment by drez769** [comment] 2019-02-08 20:00
Thanks, I think I narrowed it down a bit more. It seems to be a bug with the **second set of parenthesis** in a relationship, ie the **problem** string in:
```
relationship OneToMany {
	A{b(name)} to B{a(problem)}
}
```

**Comment by MathieuAA** [comment] 2019-02-08 20:21
Indeed. I'm rewriting the JDL conversion right now for relationships to cover these cases that have been buggy latelyLe 8 févr. 2019 21:00, drez769 <notifications@github.com> a écrit :Thanks, I think I narrowed it down a bit more. It seems to be a bug with the second set of parenthesis in a relationship, ie the problem string in:
relationship OneToMany {
	A{b(name)} to B{a(problem)}
}

**Comment by MathieuAA** [comment] 2019-02-09 10:46
I'm gonna do a release to close this one.

**Closed** 2019-02-09 11:34 UTC
Labels: JDL
