### ISSUE TITLE
Cannot rollback transactional when deploy in weblogic

### ISSUE THREAD

**Issue by ThanhLD24** [jhipster/generator-jhipster#4697] opened 2016-12-16 08:11 UTC
##### **Overview of the issue**
I deploy project in weblogic. And I have one service method, has call to three repository method. When I call to service, one repository method has exception but two repository method remain still update normal. It can't rollback. In other case, I deploy project in tomcat, it running fine.

##### **JHipster Version(s)**
JHipster Version : 1.8.4

##### **Browsers and Operating System**
Windows 7 Ultimate

Sorry for my English not good.

**Comment by deepu105** [comment] 2016-12-16 08:15
Jhipster version 1.8 is too old and I dont understand your issue and you do not follow our bug template and guideline so closing it

**Closed by deepu105** 2016-12-16 08:15 UTC

**Comment by ThanhLD24** [comment] 2016-12-16 08:19
I has some mistake, Jhipster version is 3.10.0.

**Comment by deepu105** [comment] 2016-12-16 08:20
Still not enough info please follow our issue template guideline and
provide all details to reproduce

Thanks & regards,
Deepu

**Comment by jdubois** [comment] 2016-12-16 08:21
First contact WebLogic support (they are paid for it, unlike us), then
we'll have a look.

**Comment by ThanhLD24** [comment] 2016-12-16 08:37
I uncertain this issue cause by WebLogic or Jhipster, so I post question here hope some one encountered an error will help me solve it. :)

**Comment by gzsombor** [comment] 2016-12-16 08:40
I haven't used WebLogic for 7 years, but if I were you, I would check, if Spring could detect, what kind of transaction manager should it use. Because when your app is deployed to tomcat, spring should implement the whole thing, on his own, but in weblogic, it should integrate with Weblogic's transaction management. You should check, if JTA is used, etc ...
