### ISSUE TITLE
JDL generation does not take the elasticsearch filter in account

### ISSUE THREAD

**Issue by Tcharl** [jhipster/generator-jhipster#7317] opened 2018-03-18 14:26 UTC
##### **Overview of the issue**

All search repositories and tests are generated even if specifying a search filter in jdl.

##### **Motivation for or Use Case**

Sometimes the developper don't want to have all his entities indexed

##### **Reproduce the error**

2 entities in a jdl, with a yo with search, then using the elasticsearch 'except', or not using wildcard in the search query.

##### **Related issues**

N/A

##### **Suggest a Fix**

PR?
##### **JHipster Version(s)**

```
tmp@0.0.0 /Users/charliemordant/Code/Sources/jhipster/tmp
└── generator-jhipster@4.14.1 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp"
    },
    "jhipsterVersion": "4.14.1",
    "baseName": "tmp",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "session",
    "cacheProvider": "ehcache",
    "enableHibernateCache": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": false,
    "rememberMeKey": "replaced-by-jhipster-info",
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity ShallHaveSearchEnabled (shall_have_search_enabled) {
  name String
}
entity ShallNotHaveSearchEnabledBecauseNotInCandidate (shall_not_have_search_enabled_because_not_in_candidate) {
  name String
}
entity ShallNotHaveSearchEnabledBecauseExcluded (shall_not_have_search_enabled_because_excluded) {
  name String
}

search ShallHaveSearchEnabled with elasticsearch

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

git version 2.16.2

node: v9.7.1

npm: 5.7.1

yeoman: 1.8.5

yarn: 1.5.1

Docker version 18.02.0-ce, build fc4de44

docker-compose version 1.19.0, build 9e633ef

##### **Browsers and Operating System**

Any
- [x ] Checking this box is mandatory (this is just to show you read everything)

**Comment by MathieuAA** [comment] 2018-03-18 14:31
Please, next time, fill the template.
I'll work on reproducing this.

**Comment by MathieuAA** [comment] 2018-03-18 14:31
In the meantime, can you provide your JDL sample and your .yo-rc.json file? thanks.

**Comment by Tcharl** [comment] 2018-03-18 16:10
Sure, sorry, I was used to make my own PR, that's why my descriptions are succint.

I'll make a yo.rc as well as a jdl asap

**Comment by MathieuAA** [comment] 2018-03-18 18:01
Thanks! I'll check everything tomorrow, but this looks legit so I tried to reproduce. Didn't succeed.

**Comment by Tcharl** [comment] 2018-03-18 18:13
Damn, jhipster info do not parse jdl well as well: here's the original.

`entity ShallHaveSearchEnabled {
	id Long
	name String
}
entity ShallNotHaveSearchEnabledBecauseNotInCandidate {
	id Long
	name String
}
entity ShallNotHaveSearchEnabledBecauseExcluded {
	id Long
	name String
}

search ShallHaveSearchEnabled with elasticsearch except ShallNotHaveSearchEnabledBecauseExcluded
`

**Comment by MathieuAA** [comment] 2018-03-22 18:28
@Tcharl I've taken the liberty to create an issue over JCore's issue tracker for this issue (it doesn't concern the main generator at this point). 
Here's what I'm going to do:
  - close this issue and report work on the one (issue) created in JHipster Core issue tracker
  - if the issue is only in the JDL, then there's nothing to do here
  - if it's not, then I'll create an issue with more detailed from my investigation.

**Closed by MathieuAA** 2018-03-22 18:28 UTC
