### ISSUE TITLE
Use of spring-cloud-stream instead of kafka-clients

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/generator-jhipster#18385] opened 2022-04-15 09:00 UTC
##### **Overview of the issue**

We change the use of Kafka, by adding back spring-cloud-stream, which was removed 2 years ago.

Following this https://github.com/jhipster/generator-jhipster/pull/17685 by @Tcharl and my comment https://github.com/jhipster/generator-jhipster/pull/17685#issuecomment-1099953829

This change was not in the scope of this PR, so I don't understand.
And we introduce a possible breaking change here :-(

cc @jhipster/developers 

##### **Browsers and Operating System**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by Tcharl** [comment] 2022-04-16 11:28
Hi @pascalgrimaud ,

The rational behind here was:
 - To have reproducible tests: the previous version was not streaming messages and using polling which was really difficult to test.
 - To remove customized stuff preferring spring standards (i.e. the jhipster streaming properties)
 - To plan the introduction on `consumer` and `producer` in the entity generator, to complete the rest part (which topic would be configurable through spring configuration), and align the pattern.

**Comment by pascalgrimaud** [comment] 2022-04-16 14:38
Maybe, but we should discuss about it first, as this change broke all my apps when upgrading this to 7.8.1. 
So I use a fork with the revert of all Kafka changes.

**Comment by Tcharl** [comment] 2022-04-16 21:33
Yes, sorry, I'll try to create some tickets next time.
This testcontainer migration is impacting most of the backend codebase that's why it can have a bit of impact

**Comment by Tcharl** [comment] 2022-04-16 21:33
Yes, sorry, I'll try to create some tickets next time.
This testcontainer migration is impacting most of the backend codebase that's why it can have a bit of impact

**Comment by mshima** [comment] 2022-04-18 14:38
@pascalgrimaud I didn't realized the breaking change.
But since is done, I don't think reverting is the best option.
JHipster (official) is spring-boot based, so IMO we should prefer spring/spring-boot abstracted technologies.

I suggest to rename the spring `kafka` option to `spring-kafka`.

We have 2 options with `kafka` option:
1. Extract to a new generator inside `generator-jhipster` 
1. Extract to a blueprint.

Option 1:
Keep the kafka option at v7 and move to a blueprint at v8.

Options 2:
Throw an error if the blueprint is missing and recommend to install it

I prefer option 2.

**Comment by Tcharl** [comment] 2022-04-23 20:01
Can we close as it was merged?

**Comment by mraible** [comment] 2022-04-23 20:11
I noticed Spring Boot 2.7 RC1 has a Kafka-related feature. Not sure if that
helps or not.

https://spring.io/blog/2022/04/21/spring-boot-2-7-0-rc1-is-now-available

**Comment by pascalgrimaud** [comment] 2022-04-23 21:11
No, we introduce a breaking change here, so we need to do something and I still don't understand this change

**Comment by Tcharl** [comment] 2022-04-23 21:52
Hi Pascal,

Please take a deep look at how things were implemented [before](https://github.com/jhipster/generator-jhipster/blob/5c09c4e65693320b5f5dac92be4717da5567e98f/generators/server/templates/src/main/java/package/web/rest/KafkaResource.java.ejs#L117) vs [now](https://github.com/jhipster/generator-jhipster/blob/main/generators/server/templates/src/main/java/package/web/rest/KafkaResource.java.ejs)

1. Before
 - You had a kafka consumer created for each client connection, which doesn't make that much sense and not 12 factor (what if the service holding the connection crashed)?
 - You polled the queue in each sse connection every 5 seconds in a while(true){} loop that introduced a memory leak when the client closes its browser.
 - You sent a blank message every 5 seconds (why?)
 - It was a nightmare to test: we had to wait sse, + the polling and try to catch the right message (not the blank one), which for me failed at least 9 on 10 tries
 - The code seemed really hacky (custom jhipster kafka properties, the while loop, ...) and the test was even worse

2. Now

 - You only have one kafka channel that broadcasts to all subscribers
 - The contract is clear and held in spring standard properties
 - We can use the same pattern for rabbit, reducing the framework's maintenance
 - It's like reactive, not polled, no while(true)
 - The reactive counterpart [is even more simpler](https://github.com/jhipster/generator-jhipster/blob/main/generators/server/templates/src/main/java/package/web/rest/KafkaResource_reactive.java.ejs)
 - Tests are reproducible
 - Next, we'll implement a `consumer with kafka` and `producer with kafka` at the entity level which will use the exact same pattern, which will be very easy to implement and to maintain in time (thank to spring could stream) and make CQRS dream comes true for JHipster.

I suggest to draft a V8 of JH if breaking changes is the concern.

**Comment by pascalgrimaud** [comment] 2022-04-24 06:32
I agree the current Kafka support is not perfect, but it works perfectly since 2 years now for me.

So let's not debate what is better or not, let's go on.
The best fix here is suggested by @mshima :
- rename the kafka option to spring-kafka

So all users who whill upgrade their app won't have all conflict in properties, dependencies etc

**Closed** 2022-06-17 04:41 UTC
Labels: area: bug :bug:, theme: kafka
