### ISSUE TITLE
User management is not generated when I choose react 

### ISSUE THREAD

**Issue by marlonfa** [jhipster/generator-jhipster#18728] opened 2022-05-24 14:15 UTC
When I generate an application with Jhipster v7.8.1 using react as a front-end the user management is not generated automatically, but if I switch to angular the user management is created. Is there any way to generate user management automatically using react?

**Comment by emilpaw** [comment] 2022-06-07 13:35
Can't reproduce. 

Could you provide the information given by `jhipster info` as described in the issue template? 
Following is my `jhipster info` output. It did create the user management.

<details>
  <summary>My jhipster info output</summary>
  

INFO! Switching to JHipster installed locally in current project's node repository (node_modules)

Welcome to JHipster v7.8.1

Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
testsample@0.0.1-SNAPSHOT /home/user/jhipster/test-sample
└── generator-jhipster@7.8.1

```


##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**


<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "applicationType": "monolith",
    "authenticationType": "jwt",
    "baseName": "testsample",
    "blueprints": [],
    "buildTool": "maven",
    "cacheProvider": "no",
    "clientFramework": "react",
    "clientPackageManager": "npm",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "creationTimestamp": 1654608024015,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "devServerPort": 9060,
    "dtoSuffix": "DTO",
    "enableGradleEnterprise": false,
    "enableHibernateCache": false,
    "enableSwaggerCodegen": false,
    "enableTranslation": false,
    "entitySuffix": "",
    "jhiPrefix": "jhi",
    "jhipsterVersion": "7.8.1",
    "jwtSecretKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "languages": ["en", "fr"],
    "messageBroker": false,
    "nativeLanguage": "en",
    "otherModules": [],
    "packageName": "com.mycompany.myapp",
    "pages": [],
    "prodDatabaseType": "postgresql",
    "reactive": false,
    "searchEngine": false,
    "serverPort": "8080",
    "serverSideOptions": [],
    "serviceDiscoveryType": "no",
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "skipUserManagement": false,
    "testFrameworks": [],
    "websocket": false,
    "withAdminUi": true
  }
}

</pre>
</details>


##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>


##### **Environment and Tools**

openjdk version "17.0.2" 2022-01-18
OpenJDK Runtime Environment Temurin-17.0.2+8 (build 17.0.2+8)
OpenJDK 64-Bit Server VM Temurin-17.0.2+8 (build 17.0.2+8, mixed mode, sharing)

git version 2.35.1

node: v16.15.0

npm: 8.5.5

Docker version 20.10.12, build e91ed5707e

Docker Compose version 2.2.3


No change to package.json was detected. No package manager install will be executed.
Congratulations, JHipster execution is complete!
Sponsored with ❤️  by @oktadev.
</details>

**Comment by DanielFran** [comment] 2022-06-21 17:03
Closing since no more information have been provided

**Closed by DanielFran** 2022-06-21 17:03 UTC
Labels: area: waiting for information, theme: react, area: needs-reproduction, resolution: lack of interest
