### ISSUE TITLE
Epic: Enhance Gradle Support

### ISSUE THREAD

**Issue by oehme** [jhipster/generator-jhipster#6252] opened 2017-08-18 15:40 UTC
Following up on #5949, @atomfrede, @eriwen and I had a great chat this week on how to make JHipster's Gradle support awesome. I'd like to summarize our initial feedback here. We can break it down into smaller stories later on.

# High level observations

Let's start with a few things that can't be expressed in terms of "there's a problem at line 5" :)

## Verbose build scripts

The generator creates a lot of script content, which is probably overwhelming for the average user and also hard to evolve on JHipster upgrades. Most of the logic are conventions or defaults that should live inside a plugin (or small set of plugins) instead. A `jhipster` Gradle plugin could pre-configure the project with all your conventions and defaults and the user can still customize what they want. But mostly they won't have to and the build scripts will be reduced to a small fraction of their current size.

@atomfrede agreed to start writing a plugin and we will meet again in three weeks from now to talk about his experience and how to proceed.

I think it would make sense to break out plugins for each optional aspect (like gatling). That way the build script would mirror the generator config pretty much one for one. Here's what that would look like:

```
apply plugin: 'jhipster'
apply plugin: 'jhipster-gatling'
apply plugin: 'jhipster-mapstruct'

bootRepackage {
   mainClass = 'io.github.jhipster.application.JhipsterGradleSampleApplicationApp'
}
```

## Tasks are always out-of-date

Gradle has great incremental build support, but unfortunately the JHipster project doesn't benefit from it for several reasons:

- the Spring Boot build info put into the JAR contains a ms timestamp, making the JAR always out-of-date
- the Spring Boot `bootRepackage` task overwrites the WAR file, which makes the war task out-of-date (which then overwrites it again and so on...)
- the build script contains `processResources.dependsOn cleanResources`. Gradle is actually very good at detecting and cleaning stale output files, so this might be a historic artifact

The Spring team is aware of the issues and we will stay in touch with them to ensure they are resolved in the new version of the Boot plugin.

## Dependency resolution is slow

The Spring Dependency Management plugin re-parses BOMs on every build, a very costly operation, which adds about 500ms to every build. 

After hacking around the issues above I could reduce incremental build times from 5s to 200ms. @atomfrede said the build takes 43s on his machine. Getting a [build scan](https://scans.gradle.com) of that would be helpful.

Again, nothing much you can do here, but we are in touch with the Spring team. 

## Overuse of `-P` properties

The generated build hides a lot of features behind Gradle properties. This makes the build hard to understand, as the user either has to read a lot of documentation or the build code to find out what they can do. The replacement depends on the concrete case, but here are some examples:

### `-Pdev` vs. `-Pprod`

Instead of having two files with almost identical content, I'd recommend if-statements at the few places where it actually makes a difference. A typical pattern would be:

```
ext.ciBuild = hasProperty("ciBuild") || System.getEnv("BUILD_NUMBER") //or similar CI auto-detection
```

and then where needed:

```
if (ciBuild) {
  // do something different
}
```

A more sophisticated approach would be to create a separate task (or set of tasks) if there are two distinct workflows. E.g. something like `bootDebugRun`. The benefit of using tasks instead of `-P` is that the user can just type `gradle tasks` and see all their options.

### `-PnodeInstall`

The Node plugin has a really cool feature - automatically setting up the Javascript tools, so a backend developer doesn't have to worry about them. I don't know why this is deactivated by default. 

### `-Pgraphite` and similar

My knowledge is limited here, but this looks like it should either on or off, but not switchable. Maybe an option that the user picks at generation time?

# Specific Issues

## Large number of dependencies

Just checking, are these all top level dependencies or were you trying to work around some version conflicts by explicitly adding some of them?

Also, I assume most of these dependencies are mandatory for the basic "JHipster experience", so they could be part of the above mentioned `jhipster` plugin. That way, the user only needs to handle their additional dependencies.

## Large number of repositories

Every repository declaration slows down the build, because on missing or dynamic dependencies, Gradle has to look into each one of them in turn. I assume that may of these repos aren't actually necessary. For instance `mavenCentral` is fully contained in `jcenter()`.

## No way to run only the unit tests

The `test` task is only meant to run unit tests. For other tests, you should create a separate sourceSet and test task. This allows the user to only execute the test suite they care about.

There is a `check` task that is meant to depend on all tests, for when the user really wants to run everything.

Currently there are declarations saying that `test` is "finalized by" `cucumberTest`, making it impossible to run unit tests alone.

## Reimplemented some community plugins

There are plugins for many of the tools you are using, like [Docker](https://github.com/bmuschko/gradle-docker-plugin) or [Liquibase](https://github.com/liquibase/liquibase-gradle-plugin). It would make it easier for your users if you reused those plugins, because they are more feature rich and better tested. It also takes maintenance burden away from you.

## Gatling misuses task API

`gatling.gradle` creates Tasks at execution time and then calls `execute` on them. This was never intended to work and will be an error in future Gradle versions. Instead, this should be a dedicated task class with proper input and output declarations. It could use `Project.exec` inside the task action to launch the actual simulations.

The script also overwrites the configuration of `src/test/scala`, making it impossible to have normal Scala tests. Instead, it should create a dedicated sourceSet for Gatling simulations.

I'd recommend using the [Gradle Gatling](https://github.com/lkishalmi/gradle-gatling-plugin) plugin, which seems to solve these issues already.

# Future considerations

## Continuous re-deployment

We are currently creating a public deployment API that will allow plugins to redeploy applications on [continuous builds](https://docs.gradle.org/current/userguide/continuous_build.html). This means you'll no longer need another tool like yarn to redeploy and it will redeploy the whole app, not just the frontend code. Together with the much faster incremental builds that I talked about above (<200ms) ,this would make for a very smooth experience.

## Improvements to Gradle

This epic mostly mentioned things that you can improve on your end, but we are just as eager to improve Gradle to make life easier for you and your users. @eriwen, @bmuschko and I would be happy to hear your thoughts on what the biggest pain points are. Maybe you could collect them in a document for our next meeting?

We are super excited to help you provide a great experience to so many developers. Thanks for your enthusiasm for Gradle! 😃

**Comment by gmarziou** [comment] 2017-08-18 17:39
Thanks a lot for your help @oehme, it's great to see that also the Spring Boot team is working to improve Gradle's support.

**Comment by atomfrede** [comment] 2017-08-18 19:14
It is great to see that gradle cares about small community projects, thanks @oehme @eriwen for your time and input!

Regarding the 48s build, the build downloaed some dependencies. It takes 8s on subsequent builds with usage of the daemon, so thats fine. Nevertheless I will try the build scan. 

I plan to do (or at least start) the following things (starting next week):

* Try to fix the quick wins like up to date tasks etc.
* Replace liquibase or docker with one of the existing plugins
* The mentioned gatling plugin is working fine, but [doesn't support our current file layout](https://github.com/lkishalmi/gradle-gatling-plugin/issues/32). So here is the question, should we contribute that feature (as I planned) or do a fork and release a `jhipster-gatling' plugin
* A 'jhipster' plugin that maybe does nothing at the moment. As we are currently planning to use a [parent pom in the maven setup](https://github.com/jhipster/generator-jhipster/pull/6075/files) it would be cool if we could reuse the jhipster-dependencies pom. Does this make sense @oehme or should we do a different approach?

**Comment by oehme** [comment] 2017-08-18 19:35
The above all make sense to me.

Is the file layout going to stay like it is? Nesting gatling simulations under src/test/scala seems suboptimal to me, as that folder already has a different meaning. A PR to that plugin would be best. Should be a simple matter of adding setters and wrapping the usage of those properties in an afterEvaluate block (so the build script actually has a chance to change them).

**Comment by atomfrede** [comment] 2017-08-18 20:06
I would prefer to have the standard gatling layout, such that all gatling related stuff is grouped under `src/gatling`. @jdubois What do you think? I guess that's less problematic than putting integration test somewhere else? In fact I already prepared a PR, just need to decide to keep the autodetect feature for the layout or just make it configurable and using the default layput. Will try to do it over the weekend.

**Comment by oehme** [comment] 2017-08-18 20:26
Regarding integration tests: you can split them into their own task without putting them in a different folder. It's not ideal but a big usability improvement over the current single task.

**Comment by sendilkumarn** [comment] 2017-08-19 05:07
Thanks a lot @oehme This is interesting 👍

**Comment by atomfrede** [comment] 2017-08-21 12:55
I have replaced our custom docker file build with the gradle docker plugin, works fine. Will try to do a first PR during the week.

**Comment by jdubois** [comment] 2017-08-21 13:01
Great job here!!! All those are really non-trivial issues, and it looks like the Spring Boot Gradle plugin isn't very good. So I'm really happy that we have an explanation on our issues.

**Comment by atomfrede** [comment] 2017-09-01 17:54
@jhipster/developers We plan to shedule our next hangout on Sep. 6th 18.00 CEST. I think it would be cool if at least @deepu105 or @jdubois would join us. @oehme Is date and time still fine for you?

**Comment by jdubois** [comment] 2017-09-02 09:08
I'd love to participate, unfortunately I have no idea for which client I will work on Wednesday... Please send me the invitation, and I'll do my best!

**Comment by atomfrede** [comment] 2017-09-03 18:37
Here is the PR for the gatling plugin: https://github.com/lkishalmi/gradle-gatling-plugin/pull/42

**Comment by bescott1** [comment] 2017-10-03 15:12
I am using gradle on a project and I found a couple issues. Not sure if I should create my own PR with the quick fix, or add them to this PR:

1) gradle test doesn't run all the tests. The task includes:

```
test {
    include '**/*UnitTest*'
    include '**/*IntTest*'

    // uncomment if the tests reports are not generated
    // see https://github.com/jhipster/generator-jhipster/pull/2771 and https://github.com/jhipster/generator-jhipster/pull/4484
    // ignoreFailures true
    reports.html.enabled = false
}
```
However there are no tests with the format `*UnitTest*`

I fixed it by changing it to: 

```
test {
    exclude '**/CucumberTest*'


    // uncomment if the tests reports are not generated
    // see https://github.com/jhipster/generator-jhipster/pull/2771 and https://github.com/jhipster/generator-jhipster/pull/4484
    // ignoreFailures true
    reports.html.enabled = false
}
```

2) Default sonar configuration isn't adequate for code coverage:

Sonar by default will look for `jacoco.exec` and `jacoco-it.exec`

Jhipster produces: `test.exec` and `cucumberTest.exec`

As I couldn't figure out how to rename the files to the default sonar expectations I added to sonar.gradle:
```
sonarqube {
    properties {
        property "sonar.jacoco.itReportPath", "build/jacoco/cucumberTest.exec"
        property "sonar.jacoco.reportPath", "build/jacoco/test.exec"
    }
}
```
The solution above isn't the best as it depends on your sonar version, renaming to what sonar expects would be a better solution

**Comment by atomfrede** [comment] 2017-10-03 18:04
Thanks for the hint. Will apply these in the currently open pr for changing the test structure in gradle. Never tried sonar in fact.

**Comment by atomfrede** [comment] 2017-10-16 18:23
@bescott1 I tested with default settings and our sonar container. Doing a `gradle sonarqube` worked just fine and coverage was recorded fine, can you explain what you did exactly? [Renaming the jacoco report is quite easy (if required).](https://docs.gradle.org/current/userguide/jacoco_plugin.html#sec:jacoco_specific_task_configuration)

**Comment by bescott1** [comment] 2017-10-16 19:43
It might be an issue with Sonar version. I'm using the sonar installed at a company (6.0). In that version it doesn't pick it up automatically. When I use the dockerized sonar that comes with JHipster it picks it up.

**Comment by jdubois** [comment] 2017-12-05 12:49
@atomfrede are you still working on the Gradle plugin? We can try to find people to help

**Comment by atomfrede** [comment] 2017-12-05 16:47
Yes. Still working on it. Now as the bom stuff is merged I can try to
proceed. But having more people here would be great as I barely find time
currently to code something after work.

Am 05.12.2017 1:49 nachm. schrieb "Julien Dubois" <notifications@github.com

**Comment by Tcharl** [comment] 2018-01-20 10:45
Concerning the 
- No

 way to run only the unit tests stuff:

In maven, Integration tests are handled by the integration-test phase, so the maven-failsafe plugin. So that when user runs `mvn test`, it only executes unit tests, in opposite to running `mvn verify`, which runs both unit and integration tests.
I can implement it easily with Maven if you do the same for Gradle: WDYT?

**Comment by jdubois** [comment] 2018-03-13 17:11
I'm closing this as this is not moving forward - @atomfrede we can re-open it if you find more time. In the meantime, let's see what the new Spring Gradle plugin does, maybe the issue is solved there.

**Closed by jdubois** 2018-03-13 17:11 UTC
Labels: v5, work-in-progress
