### ISSUE TITLE
User class is not generated in Gateway but is referenced by an Entity via microservice

### ISSUE THREAD

**Issue by crowne** [jhipster/generator-jhipster#17008] opened 2021-11-14 12:59 UTC
##### **Overview of the issue**

The jdl below defines a Gateway app with no database and a microservice with 3 entities [Department, Employee, Roster].
Employee has a OneToOne relationship with User.
The microservice compiles correctly, however the Gateway compile fails because the pkg.domain.Employee class refers to User class which is not generated in the Gateway application.

##### **Motivation for or Use Case**

The code generated from the jdl should compile.

##### **Reproduce the error**

Generate the apps by importing the jdl below,
then compile the hr app,
then compile the portal app

```jdl
application {
  config {
    baseName portal
    applicationType gateway
    packageName com.jhipster.demo.portal
    authenticationType oauth2
    databaseType no
    devDatabaseType no
    prodDatabaseType no
    clientFramework vue
  }
  entities *
}

application {
  config {
    baseName hr
    applicationType microservice
    packageName com.jhipster.demo.hr
    authenticationType oauth2
    databaseType sql
    devDatabaseType h2Disk
    prodDatabaseType oracle
  }
  entities Department, Employee, Roster
}

enum ShiftType {
    EARLY_SHIFT, LATE_SHIFT
}

entity Department {
    name String required
}

entity Employee {
    code String required unique
    firstName String
    surname String
    startDate LocalDate
}

entity Roster {
    fromDate LocalDate
    thruDate LocalDate
    shiftType ShiftType
    changedAt Instant
}

relationship OneToOne {
    Employee{user(login)} to User
}

relationship ManyToOne {
    Employee{department(name) required} to Department
    Roster{department(name)} to Department
    Roster{changedBy(code)} to Employee
}

service * with serviceClass
paginate * with pagination

```

##### **Related issues**

Related, but different to #17001 which I reported 2 days ago

##### **Suggest a Fix**

Always generate the User class unless running with --skip-user-management

##### **JHipster Version(s)**

3.7.1

##### **JHipster configuration**

→ E:\mjh\jh\jh-user-rel-fix\portal [master]› jhipster info
INFO! Using JHipster version installed locally in current project's node_modules
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
portal@0.0.0 E:\mjh\jh\jh-user-rel-fix\portal
└── generator-jhipster@7.3.1

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "authenticationType": "oauth2",
    "clientFramework": "vue",
    "serverPort": "8080",
    "serviceDiscoveryType": "eureka",
    "skipUserManagement": true,
    "withAdminUi": true,
    "baseName": "portal",
    "buildTool": "maven",
    "databaseType": "no",
    "devDatabaseType": "no",
    "cacheProvider": "no",
    "enableHibernateCache": false,
    "enableSwaggerCodegen": false,
    "enableTranslation": true,
    "jhiPrefix": "jhi",
    "languages": ["en"],
    "messageBroker": false,
    "prodDatabaseType": "no",
    "searchEngine": false,
    "skipClient": false,
    "testFrameworks": [],
    "websocket": false,
    "enableGradleEnterprise": false,
    "gradleEnterpriseHost": "",
    "applicationType": "gateway",
    "packageName": "com.jhipster.demo.portal",
    "packageFolder": "com/jhipster/demo/portal",
    "jhipsterVersion": "7.3.1",
    "skipServer": false,
    "clientPackageManager": "npm",
    "dtoSuffix": "DTO",
    "entitySuffix": "",
    "reactive": true,
    "clientTheme": "none",
    "clientThemeVariant": "",
    "applicationIndex": 0,
    "skipCheckLengthOfIdentifier": true,
    "skipFakeData": false,
    "blueprints": [],
    "otherModules": [],
    "pages": [],
    "nativeLanguage": "en",
    "creationTimestamp": 1636891137184,
    "jwtSecretKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "devServerPort": 9060,
    "entities": ["Department", "Employee", "Roster"],
    "lastLiquibaseTimestamp": 1636891317000
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Department {
  name String required
}
entity Employee {
  code String required unique
  firstName String
  surname String
  startDate LocalDate
}
entity Roster {
  fromDate LocalDate
  thruDate LocalDate
  shiftType ShiftType
  changedAt Instant
}
enum ShiftType {
  EARLY_SHIFT,
  LATE_SHIFT
}

relationship OneToOne {
  Employee{user(login)} to User
}
relationship ManyToOne {
  Employee{department(name) required} to Department
  Roster{department(name)} to Department
  Roster{changedBy(code)} to Employee
}

service Department, Employee, Roster with serviceClass

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.10+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.10+9, mixed mode)

git version 2.31.1.windows.1

node: v14.18.0

npm: 8.0.0

Docker version 20.10.8, build 3967b7d

docker-compose version 1.29.2, build 5becea4c

No change to package.json was detected. No package manager install will be executed.
Congratulations, JHipster execution is complete!
Sponsored with ❤️  by @oktadev.

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

N/A see JDL above

##### **Browsers and Operating System**

Windows 10 Pro + chrome

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by Tcharl** [comment] 2021-12-30 14:44
Always buggy...

**Comment by mraible** [comment] 2022-04-23 23:59
Added bounty to try and get this fixed.

**Comment by mshima** [comment] 2022-08-20 00:57
I could not reproduce. Closing let me know if still persists.

**Closed by mshima** 2022-08-20 00:57 UTC
Labels: area: enhancement :wrench:, $100, theme: OIDC/OAuth2, $$ bug-bounty $$
