### ISSUE TITLE
Generated Entities Serializable Warnings

### ISSUE THREAD

**Issue by DeezCashews** [jhipster/generator-jhipster#1354] opened 2015-04-07 14:09 UTC
The generated entities have a warning because they are missing a `serialVersionUID` and implement `Serializeable`.

If the generator could at least add the a default:

```java
private static final long serialVersionUID = 1L;
```

I realize this can easily be generateed in an IDE but it would save time.

**Comment by jdubois** [comment] 2015-04-07 14:17
Duplicate of #682

**Closed by jdubois** 2015-04-07 14:17 UTC

**Comment by DeezCashews** [comment] 2015-04-07 14:53
So sorry.  I did search for it first and found nothing.  After getting this message I searched again and got 3 results.  Not sure what I did wrong the first time.

**Comment by jdubois** [comment] 2015-04-07 14:57
This is not your fault, GutHub's search is awful :-)
