### ISSUE TITLE
swagger-codegen 2.2.3 does not run

### ISSUE THREAD

**Issue by sinaghazi** [jhipster/generator-jhipster#6307] opened 2017-08-30 10:10 UTC
##### **Overview of the issue**
On a micro-service application version 4.7.0, once you run the project using `./mvnw spring-boot:run` with swagger-codegen-maven-plugin 2.2.3 an error is raised during run command. 

`org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.boot.autoconfigure.liquibase.LiquibaseAutoConfiguration$LiquibaseConfiguration': Invocation of init method failed; nested exception is java.lang.IllegalStateException: Cannot find changelog location: class path resource [db/changelog/db.changelog-master.yaml] (please add changelog or check your Liquibase configuration)`

##### **Reproduce the error**
In your pom.xml change your swagger-codegen to following:
<swagger-codegen-maven-plugin.version>2.2.3</swagger-codegen-maven-plugin.version>

##### **Suggest a Fix**
Version 2.2.2 works fine. 
<swagger-codegen-maven-plugin.version>2.2.2</swagger-codegen-maven-plugin.version>

##### **JHipster Version(s)**
4.7.0 

##### **JHipster configuration**

~~~
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.company",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "4.7.0",
    "baseName": "contract",
    "packageName": "com.company",
    "packageFolder": "com/company/contract",
    "serverPort": "8092",
    "authenticationType": "uaa",
    "uaaBaseName": "uaa",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": true,
    "jwtSecretKey": "3dda6385d1dc059a98228a59909956f49ff1176f",
    "enableTranslation": true,
    "applicationType": "microservice",
    "testFrameworks": [
      "cucumber"
    ],
    "jhiPrefix": "jhi",
    "skipClient": true,
    "skipUserManagement": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "fr",
      "de"
    ],
    "clientPackageManager": "yarn"
  }
}
~~~

##### **Browsers and Operating System**
Not applicable

**Comment by PierreBesson** [comment] 2017-08-30 15:42
This looks like the same stacktrace as https://github.com/jhipster/generator-jhipster/issues/6292

**Comment by sinaghazi** [comment] 2017-08-30 17:40
It is actually the same stacktrace as #6292 an error on liquibase. But when we changed the swagger-codegen to 2.2.2 the liquibase error disappeared

**Comment by PierreBesson** [comment] 2017-08-30 22:58
This is super strange, IMO the LiquibaseAutoconfigutation should not be triggered as we correctly define the SpringLiquibase bean here : https://github.com/jhipster/jhipster-sample-app/blob/master/src/main/java/io/github/jhipster/sample/config/DatabaseConfiguration.java

We should did into this deeper rather than downgrading anything. Unfortunately I won't be available for a few days, so if someone else can have a look that would be great. The /management/autoconfig endpoint will be useful to debug this. Also we should enable swagger-codegen in our Travis build so that it is able to catch the error.

**Comment by PierreBesson** [comment] 2017-09-06 15:24
@sinaghazi I recreated an application with your config (it was not easy since you use Registry+UAA+Mysql for dev+elasticsearch) and was not able to reproduce the issue. It seems dubious to me that downgrading the codegen plugin would fix the issue. Does the problem occur all the time or only sometimes ? Does it prevents from starting the application ?

**Comment by sinaghazi** [comment] 2017-09-08 09:28
@PierreBesson I tried it again today in a completely fresh environment and couldn't reproduce the issue. Will check it again on Monday with the team.

**Comment by jdubois** [comment] 2017-09-08 14:07
I'm closing this as it can't be reproduced, please re-open if you have more information

**Closed by jdubois** 2017-09-08 14:07 UTC

**Comment by bgagan911** [comment] 2017-11-16 13:00
I was able to reproduce the error.
Just imported the project and I see the error.

I'm using STS 3.9.1

> No marketplace entries found to handle swagger-codegen-maven-plugin:2.2.3:generate in Eclipse.  Please see Help for more information.

**Comment by tibistibi** [comment] 2018-01-10 10:49
same here:
![image](https://user-images.githubusercontent.com/1875634/34768868-5cd2d326-f5fc-11e7-9ccb-7f631465db30.png)

**Comment by tibistibi** [comment] 2018-01-10 10:56
when i changed the version from 2.2.3 to 2.2.2 it imported fine but i still see the error in the error tab:

Description	Resource	Path	Location	Type
Plugin execution not covered by lifecycle configuration: io.swagger:swagger-codegen-maven-plugin:2.2.2:generate (execution: default, phase: generate-sources)	pom.xml	/****	line 602	Maven Project Build Lifecycle Mapping Problem

**Comment by ThiagoPco** [comment] 2020-06-25 11:03
Hi there,
The same here.

OS: Windows 64-bit
IDE: Eclipse 2019-06 (4.12.0)
JDK: 12
Maven: 3.6.3

![image](https://user-images.githubusercontent.com/11446976/85708127-c6f10a00-b6db-11ea-9a93-5754b1d2a3a8.png)
