### ISSUE TITLE
checkstyleMain FAILED

### ISSUE THREAD

**Issue by vw98075** [jhipster/generator-jhipster#11402] opened 2020-02-28 05:33 UTC
##### **Overview of the issue**

with a test framework selected, I get an error on "checkstyleMain FAILED". I have this problem on  UAA, Gateway as well as microservices.

```

> Task :checkstyleMain FAILED
[ant:checkstyle] [ERROR] /.../uaa/src/main/java/com/example/microservices/uaa/config/CacheConfiguration.java:68:44: http:// URLs are not allowed but got 'http://docs.hazelcast.org/docs/management-center/3.9/manual/html/Deploying_and_Starting.html'. Use https:// instead. [NoHttp]

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':checkstyleMain'.
> Checkstyle rule violations were found. See the report at: file:///.../uaa/build/reports/checkstyle/main.html
  Checkstyle files with violations: 1
  Checkstyle violations by severity: [error:1]
```

##### **Motivation for or Use Case**

Need to make a build

##### **Reproduce the error**

Running the build comand "./gradlew build".

##### **JHipster Version(s)**

6.7.1

##### **JHipster configuration**

```
uaa@0.0.0 /home/oem/Workspace-dev/2020-spring-microservices-with-kubernetes/uaa
├── generator-jhipster@6.7.1 
└─┬ generator-jhipster-spring-cloud-stream@1.0.0
  └── generator-jhipster@6.7.1  deduped

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.example.microservices.uaa"
    },
    "jhipsterVersion": "6.7.1",
    "applicationType": "uaa",
    "baseName": "uaa",
    "packageName": "com.example.microservices.uaa",
    "packageFolder": "com/example/microservices/uaa",
    "serverPort": "9999",
    "authenticationType": "uaa",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "messageBroker": "kafka",
    "serviceDiscoveryType": false,
    "buildTool": "gradle",
    "enableSwaggerCodegen": false,
    "embeddableLaunchScript": false,
    "creationTimestamp": 1582847455109,
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [
      {
        "name": "generator-jhipster-vuejs2",
        "version": "1.1.12"
      },
      {
        "name": "generator-jhipster-spring-cloud-stream",
        "version": "1.0.0"
      }
    ],
    "enableTranslation": false,
    "clientPackageManager": "npm",
    "blueprints": [],
    "skipClient": true
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

openjdk version "1.8.0_242"
OpenJDK Runtime Environment (build 1.8.0_242-8u242-b08-0ubuntu3~16.04-b08)
OpenJDK 64-Bit Server VM (build 25.242-b08, mixed mode)

git version 2.7.4

node: v10.0.0

npm: 6.13.7

yeoman: 3.1.0

yarn: 1.9.4

Docker version 18.06.1-ce, build e68fc7a

docker-compose version 1.8.0, build unknown

##### **Browsers and Operating System**

-   [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by atomfrede** [comment] 2020-02-28 05:52
Looks like we forgot to replace some `http` with `https` in our templates (just documentation, so not critical), but the no http plugin is quite strict

**Comment by atomfrede** [comment] 2020-02-28 05:58
Are you sure you have used to generate the latest jhipster version? In our templates we have `https`. See https://github.com/jhipster/generator-jhipster/blob/cdb9ef09d7fb821402504ebc1c578c82a9026a93/generators/server/templates/src/main/java/package/config/CacheConfiguration.java.ejs#L333 Can you check your `CacheConfiguration` file? Did you do an update from an older version?

**Comment by vw98075** [comment] 2020-02-28 06:05
The error doesn't occur after changing from http to https on the line. The version of JHispter isn't newly installed, but upgrade from an older version.

**Comment by atomfrede** [comment] 2020-02-28 06:43
Did you choose to not override the cache configuration file? Will close this issue.

**Closed** 2020-02-28 06:44 UTC
Labels: area: triage, theme: undefined

**Comment by vw98075** [comment] 2020-02-28 16:42
The error occurs right out of the box. I need to modify the file to get rid of the error. I don't know that this one shall be closed without change JHipster code because it causes a compile problem for the end-users.

**Comment by atomfrede** [comment] 2020-02-28 16:52
When you do an update and keep the old file it will happen as we have integrated the no http plugin. For newly created project it should not happen. Can you reproduce the problem with a newly generated project?

**Comment by vw98075** [comment] 2020-02-28 18:45
I don't know whether there is some miscommunication or not. I upgraded the version with the command displayed when I started an older version of jhipster. The error was from projects generated with the latest version 6.7.1 last night.
     On Friday, February 28, 2020, 08:52:57 AM PST, Frederik Hahne <notifications@github.com> wrote:  
 
 
When you do an update and keep the old file it will happen as we have integrated the no http plugin. For newly created project it should not happen. Can you reproduce the problem with a newly generated project?
