### ISSUE TITLE
Cassandra Docker container enters invalid state after multiple successive IT executions

### ISSUE THREAD

**Issue by micobarac** [jhipster/generator-jhipster#10120] opened 2019-07-19 12:34 UTC
##### **Overview of the issue**

Sometimes, Cassandra Docker container enters invalid state after multiple successive IT executions. When it happens, Cassandra container becomes unavailable and all IT fail. 

I have to restart Docker process to make it work again.

```java
private static void startTestcontainer() throws TTransportException, IOException {
    CASSANDRA_CONTAINER =
        new GenericContainer("cassandra:3.11.4")
            .waitingFor(Wait.forListeningPort().withStartupTimeout(Duration.ofSeconds(60)))
            .withExposedPorts(CASSANDRA_TEST_PORT);

    CASSANDRA_CONTAINER.start();
}
```

This method fails. I also had timeout problem, then I increased default timeout from 30 to 60 seconds, and the problem happens rarely, but never goes away for good.

##### **Motivation for or Use Case**

Run multiple successive IT executions, without Cassandra Docker container being invalid and non-functional.

##### **Reproduce the error**

Generate a new JHipster Cassandra project:

`jhipster --skip-client --yarn`

Run building war file for production:

`mvn -Pprod,war clean verify`

##### **Suggest a Fix**

Make Cassandra Docker container functional and resilient and functional to running multiple successive IT executions.

##### **JHipster Version(s)**

`6.1.2`

##### **JHipster Version(s)**

```
openprovider@0.0.0 /Users/milan/Sites/jhipster
└── generator-jhipster@6.1.2

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.logate.openprovider"
    },
    "jhipsterVersion": "6.1.2",
    "applicationType": "monolith",
    "baseName": "openprovider",
    "packageName": "com.logate.openprovider",
    "packageFolder": "com/logate/openprovider",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": false,
    "websocket": false,
    "databaseType": "cassandra",
    "devDatabaseType": "cassandra",
    "prodDatabaseType": "cassandra",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": false,
    "clientPackageManager": "yarn",
    "skipClient": true
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_202"
Java(TM) SE Runtime Environment (build 1.8.0_202-b08)
Java HotSpot(TM) 64-Bit Server VM (build 25.202-b08, mixed mode)

git version 2.21.0

node: v10.15.3

npm: 6.9.0

yeoman: 3.0.0

yarn: 1.16.0

Docker version 18.09.2, build 6247962

docker-compose version 1.23.2, build 1110ad01

##### **Browsers and Operating System**

macOS Mojave
Version 10.14.5 (18F132)

**Comment by atomfrede** [comment] 2019-07-19 22:03
I was not able to reproduce it. Executed >10 times `verify` and each time it worked well. Testcontainers starts ryuk and one cassandra container which are stopped afterwards. Tried both with java 8 and 11. Most significant difference is the os. I am on a linux machine with docker `18.09.7-ce` but it should not be relevant that minor difference.

**Comment by micobarac** [comment] 2019-07-19 22:10
I have ~400 integration test methods, and using Swagger2Markup tests with separate application-s2m.yaml profile. Maybe, separate profile starts another container, and sometimes, the container enters invalid state.

**Comment by atomfrede** [comment] 2019-07-19 22:15
Can you check if the containers are stopped correctly in your case?

**Comment by micobarac** [comment] 2019-07-19 22:23
How? Do I run `docker ps`?

**Comment by atomfrede** [comment] 2019-07-20 06:50
I just do 'watch docker ps' during test execution

**Comment by atomfrede** [comment] 2019-07-30 07:03
@micobarac Any news from your site?

**Comment by micobarac** [comment] 2019-07-30 07:07
When I execute 'watch docker ps' during test execution, I get the error saying the watch doesn't exist.

In cases when Cassandra Docker container enters invalid state after multiple successive IT executions, I just restart the Docker service and it starts working again. I have found no other solution.

**Comment by pascalgrimaud** [comment] 2019-08-12 05:56
@micobarac : what you can try is to generate a default JHipster project with Cassandra with some entities, without any additional codes, like s2m profile. Then, could you try to reproduce plz ?

**Comment by pascalgrimaud** [comment] 2019-08-16 05:51
I'm closing this, as we didn't manage to reproduce.
Don't hesitate to generate + push a project on GitHub, so we can retry

**Closed by pascalgrimaud** 2019-08-16 05:51 UTC
Labels: area: needs-reproduction, theme: cassandra
