### ISSUE TITLE
Required relationships to the same entity are not supported

### ISSUE THREAD

**Issue by agoncal** [jhipster/generator-jhipster#11495] opened 2020-03-23 14:36 UTC
##### **Overview of the issue**

I need to model a reflexive relationship such as in https://www.jhipster.tech/jdl/relationships#reflexive-relationships : an invoice can have several child invoices, and a child invoice must refer to the parent. So, as explained in the guide, I have the following JDL:

```
relationship OneToMany {
    Invoice{parentInvoice(identifier) required} to Invoice{childInvoices(identifier)}
}
``` 

When I import the JDL I get:

```
Error: Can't add invalid relationship. Error: Required relationships to the same entity are not supported, for relationship from and to 'Invoice'.
Error while parsing applications and entities from the JDL Error: Can't add invalid relationship. Error: Required relationships to the same entity are not supported, for relationship from and to 'Invoice'.
```

It's just a matter of removing the `required` and it works (`Invoice{parentInvoice(identifier)}`. Which makes sense if you don't have a single required root invoice.

##### **Motivation for or Use Case**

I need my child invoice to have a `required` parent invoice (because I have a single root invoice). In the guide it's the example that is used, so it should work : 
https://www.jhipster.tech/jdl/relationships#reflexive-relationships.

So it's either a bug or the guide should be updated to remove the `required`.

##### **Reproduce the error**

Import the following JDL. With `required` it fails, without, it works:

```
application {
    config {
        applicationType monolith
        databaseType sql
        devDatabaseType postgresql
        prodDatabaseType postgresql
    }

    entities *
}

entity Invoice {
    invoiceDate LocalDate required,
    identifier String required maxlength(25) unique,
    vatRate Float required,
    vatAmount Float required,
    subtotal Float required,
    total Float required,
}

relationship OneToMany {
    Invoice{parentInvoice(identifier) required} to Invoice{childInvoices(identifier)}
}

service * with serviceClass
dto * with mapstruct
paginate * with pagination
filter *
```

##### **JHipster Version(s)**

```
jhipster@0.0.1-SNAPSHOT /Users/agoncal/Documents/Code/Temp/dummy
└── generator-jhipster@6.6.0 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "enableHibernateCache": true,
    "enableSwaggerCodegen": false,
    "enableTranslation": true,
    "jhiPrefix": "jhi",
    "languages": ["en", "fr"],
    "messageBroker": false,
    "nativeLanguage": "en",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "serviceDiscoveryType": false,
    "skipClient": false,
    "skipServer": false,
    "testFrameworks": [],
    "websocket": false,
    "applicationType": "monolith",
    "jhipsterVersion": "6.6.0",
    "baseName": "jhipster",
    "buildTool": "maven",
    "skipUserManagement": false,
    "clientPackageManager": "npm",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "clientFramework": "angularX",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "serverPort": "8080",
    "useSass": true,
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "embeddableLaunchScript": false,
    "creationTimestamp": 1584974011893,
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "blueprints": []
  },
  "entities": ["Invoice"]
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Invoice {
  invoiceDate LocalDate required,
  identifier String required maxlength(25) unique,
  vatRate Float required,
  vatAmount Float required,
  subtotal Float required,
  total Float required
}
relationship OneToMany {
  Invoice{parentInvoice} to Invoice{childInvoices(identifier)}
}

dto Invoice with mapstruct
paginate Invoice with pagination
service Invoice with serviceClass
filter Invoice

</pre>
</details>

##### **Environment and Tools**

java version "11.0.6" 2020-01-14 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.6+8-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.6+8-LTS, mixed mode)

git version 2.26.0

node: v13.11.0

npm: 6.13.7

yeoman: 3.1.1

yarn: 1.22.4

Docker version 19.03.8, build afacb8b

docker-compose version 1.25.4, build 8d51620a

##### **Browsers and Operating System**

-   [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by MathieuAA** [comment] 2020-03-23 20:56
Hi Antonio. Looking at the code, this was one one of the requirements to implement the required keyword for relationships.
It's clearly not a bug, but perhaps it should be supported, maybe (if there aren't any technical reasons).

Anyway, the doc should be fixed if such an example is present.

**Comment by cbornet** [comment] 2020-03-24 06:56
Wouldn't that create an infinite recursion ? ( an invoice must have a parent, which must have a parent, which...)

**Comment by MathieuAA** [comment] 2020-03-24 08:43
Yeah I guess so. Good point Christophe.

A simple way to do this kind of thing is to  have two entities: a "root" invoice and children ones. It makes dealing with the relationship easier.

**Comment by pascalgrimaud** [comment] 2020-03-24 18:00
good point @cbornet 
I think we should document it

**Comment by MathieuAA** [comment] 2020-05-16 10:54
Closing this as documentation has been added

**Closed by MathieuAA** 2020-05-16 10:54 UTC
Labels: area: documentation:books:, theme: JDL, theme: relationships

**Comment by tgeens** [comment] 2020-11-04 22:22
A note has been added, but the example on "Reflexive relationships" still has the `required` keyword. Shouldn't that be removed from the example ?

```
relationship ManyToMany {
  A{parent required} to A{child}
}
```

**Comment by MathieuAA** [comment] 2020-11-05 06:33
@tgeens true. Can you fix it in the doc repo?
