### ISSUE TITLE
Intellij & npm start wont allow login on port 9000

### ISSUE THREAD

**Issue by bigalnz** [jhipster/generator-jhipster#12209] opened 2020-08-06 07:21 UTC
Intellij Ultimate 2020.2 on Windows 10. I have followed the Intellij configuration instructions as per the Jhipster instructions page. Much information is below - please let me know if you need more.

Build tool is gradle. When I debug > bootRun the gradle task, it launches the project ok on port 8080 and I can login, but there is no live reload.

When I npm start it launches ok on port 9000 - and when I try to login (Chrome) I get the login modal and enter admin/admin  - the modal goes away, but I am not logged in. Browser inspection shows network tab message after trying to login:

{"type":"https://www.jhipster.tech/problem/problem-with-message","title":"Unauthorized","status":401,"detail":"Full authentication is required to access this resource","path":"/api/account","message":"error.http.401"}

jhipster info
INFO! Using JHipster version installed locally in current project's node_modules
INFO! Executing jhipster:info
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
deployment@0.0.1-SNAPSHOT C:\Users\Al Grant\IdeaProjects\Dep
`-- generator-jhipster@6.10.1

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "test.pot"
    },
    "jhipsterVersion": "6.10.1",
    "applicationType": "monolith",
    "baseName": "Deployment",
    "packageName": "test.pot",
    "packageFolder": "test.pot",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "gradle",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "embeddableLaunchScript": false,
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "angularX",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "creationTimestamp": 1596058503683,
    "testFrameworks": ["protractor"],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": false,
    "blueprints": [],
    "lastLiquibaseTimestamp": 1596059689000
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Plan {
  startDate LocalDate
}
entity Task {
  startDate Instant,
  endDate Instant,
  location String,
  narrative TextBlob,
  result TextBlob
}
entity District {
  name String
}
entity Area {
  name String
}
entity OffenceCode {
  name String,
  code Integer
}
entity TaskCode {
  name String,
  code String
}
relationship OneToMany {
  Plan{task} to Task{plan}
}

dto Plan, Task, District, Area, OffenceCode, TaskCode with mapstruct
paginate Plan, Task, Area, OffenceCode, TaskCode with infinite-scroll
service Plan, Task, District, Area, OffenceCode, TaskCode with serviceImpl
search Plan, Task, District, Area, OffenceCode, TaskCode with elasticsearch
filter Plan, Task, OffenceCode, TaskCode
readOnly District, Area, OffenceCode, TaskCode

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.6+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.6+10, mixed mode)

git version 2.22.0.windows.1

node: v12.16.2

npm: 6.14.4

yarn: 1.22.4

identical .jhipster\Area.json
identical .jhipster\District.json
identical .jhipster\OffenceCode.json
identical .jhipster\Plan.json
identical .jhipster\Task.json
identical .jhipster\TaskCode.json
INFO! Congratulations, JHipster execution is complete!

console output from npm start

```
npm start

> deployment@0.0.1-SNAPSHOT start C:\Users\Al Grant\IdeaProjects\Dep
> npm run webpack:dev


> deployment@0.0.1-SNAPSHOT webpack:dev C:\Users\Al Grant\IdeaProjects\Dep
> npm run webpack-dev-server -- --config webpack/webpack.dev.js --inline --hot --port=9060 --watch-content-base --env.stats=minimal


> deployment@0.0.1-SNAPSHOT webpack-dev-server C:\Users\Al Grant\IdeaProjects\Dep
> node --max_old_space_size=4096 node_modules/webpack-dev-server/bin/webpack-dev-server.js "--config" "webpack/webpack.dev.js" "--inline" "--hot" "--port=9060" "--watch-content-base" "--env.stats=minimal"

Webpack: Starting ...

  √ Compile modules
  > Build modules (0%)
    → 2 of 2 modules :: 
[HPM] Proxy created: [
  '/api',
  '/services',
  '/management',
  '/swagger-resources',
  '/v2/api-docs',
  '/h2-console',
  '/auth'
Webpack: Starting ...

  √ Compile modules
  √ Build modules
  √ Optimize modules
  √ Emit files

Webpack: Finished after 70.043 seconds.



 WARNING  Compiled with 1 warnings                                                                                                                                                                                            7:12:58 PM

Module Warning (from ./node_modules/eslint-loader/dist/cjs.js):

C:\Users\Al Grant\IdeaProjects\Dep\src\main\webapp\app\entities\plan\plan-task-detail.component.ts
   4:10  warning  'IPlan' is defined but never used            @typescript-eslint/no-unused-vars
  13:3   warning  Expected space or tab after '//' in comment  spaced-comment

✖ 2 problems (0 errors, 2 warnings)
  0 errors and 1 warning potentially fixable with the `--fix` option.


You may use special comments to disable some warnings.
Use // eslint-disable-next-line to ignore the next line.
Use /* eslint-disable */ to ignore all warnings in a file.
‼ ｢wdm｣:    539 modules

WARNING in ./src/main/webapp/app/entities/plan/plan-task-detail.component.ts
Module Warning (from ./node_modules/eslint-loader/dist/cjs.js):

C:\Users\Al Grant\IdeaProjects\Dep\src\main\webapp\app\entities\plan\plan-task-detail.component.ts
   4:10  warning  'IPlan' is defined but never used            @typescript-eslint/no-unused-vars
  13:3   warning  Expected space or tab after '//' in comment  spaced-comment

✖ 2 problems (0 errors, 2 warnings)
  0 errors and 1 warning potentially fixable with the `--fix` option.

i ｢wdm｣: Compiled with warnings.
[Browsersync] Proxying: http://localhost:9060
[Browsersync] Access URLs:
 ----------------------------------
       Local: http://localhost:9000
    External: http://10.8.0.26:9000
 ----------------------------------
          UI: http://localhost:3001
 UI External: http://localhost:3001
 ----------------------------------
```

**Comment by gmarziou** [comment] 2020-08-06 09:06
I edited your post to remove the .yo-rc.json you pasted manually because it contained your JWT secret and the sanitized  .yo-rc.json file is already included in `jhipster help`

**Comment by bigalnz** [comment] 2020-08-06 09:16
Nothing in backend - I do get this when I just tried in the Terminal tab from npm start:

`[HPM] Error occurred while trying to proxy request /management/info from localhost:9000 to http://localhost:8080 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)
[HPM] Error occurred while trying to proxy request /api/account from localhost:9000 to http://localhost:8080 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)
[HPM] Error occurred while trying to proxy request /api/account from localhost:9000 to http://localhost:8080 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)
[HPM] Error occurred while trying to proxy request /management/info from localhost:9000 to http://localhost:8080 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)
[HPM] Error occurred while trying to proxy request /api/account from localhost:9000 to http://localhost:8080 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)
[HPM] Error occurred while trying to proxy request /management/info from localhost:9000 to http://localhost:8080 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)
[HPM] Error occurred while trying to proxy request /management/info from localhost:9000 to http://localhost:8080 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)
[HPM] Error occurred while trying to proxy request /api/account from localhost:9000 to http://localhost:8080 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)
[HPM] Error occurred while trying to proxy request /api/authenticate from localhost:9000 to http://localhost:8080 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)
`

**Comment by bigalnz** [comment] 2020-08-06 09:17
Another clue which might be helpful is that the admin/admin username and password is cached and already filled out when I use the port 9000 - its not on the 8080.

**Comment by bigalnz** [comment] 2020-08-06 09:26
After trying to login on 9000 this is the backend log:

`2020-08-06 21:24:36.565  WARN 35396 --- [ XNIO-1 task-16] .m.m.a.ExceptionHandlerExceptionResolver : Resolved [org.springframework.security.authentication.InsufficientAuthenticationException: Full authentication is required to access this resource]
2020-08-06 21:25:02.537  INFO 35396 --- [ XNIO-1 task-19] govt.pol.security.jwt.TokenProvider      : Invalid JWT token.
2020-08-06 21:25:02.537  INFO 35396 --- [ XNIO-1 task-18] govt.pol.security.jwt.TokenProvider      : Invalid JWT token.
2020-08-06 21:25:02.547 DEBUG 35396 --- [ XNIO-1 task-18] g.p.r.CustomAuditEventRepository         : Enter: add() with argument[s] = [AuditEvent [timestamp=2020-08-06T09:25:02.547Z, principal=anonymousUser, type=AUTHORIZATION_FAILURE, data={details=org.springframework.security.web.authentication.WebAuthenticationDetails@957e: RemoteIpAddress: 127.0.0.1; SessionId: null, type=org.springframework.security.access.AccessDeniedException, message=Access is denied}]]
2020-08-06 21:25:02.548 DEBUG 35396 --- [ XNIO-1 task-18] g.p.r.CustomAuditEventRepository         : Exit: add() with result = null
2020-08-06 21:25:02.561  WARN 35396 --- [ XNIO-1 task-18] o.z.problem.spring.common.AdviceTraits   : Unauthorized: Full authentication is required to access this resource
2020-08-06 21:25:02.563  WARN 35396 --- [ XNIO-1 task-18] .m.m.a.ExceptionHandlerExceptionResolver : Resolved [org.springframework.security.authentication.InsufficientAuthenticationException: Full authentication is required to access this resource]
2020-08-06 21:25:11.001  INFO 35396 --- [ XNIO-1 task-20] govt.pol.security.jwt.TokenProvider      : Invalid JWT token.
2020-08-06 21:25:11.114 DEBUG 35396 --- [ XNIO-1 task-20] govt.pol.web.rest.UserJWTController      : Enter: authorize() with argument[s] = [LoginVM{username='admin', rememberMe=false}]
2020-08-06 21:25:11.336 DEBUG 35396 --- [ XNIO-1 task-20] g.pol.security.DomainUserDetailsService  : Authenticating admin
Hibernate: select user0_.id as id1_5_0_, authority2_.name as name1_2_1_, user0_.created_by as created_2_5_0_, user0_.created_date as created_3_5_0_, user0_.last_modified_by as last_mod4_5_0_, user0_.last_modified_date as last_mod5_5_0_, user0_.activated as activate6_5_0_, user0_.activation_key as activati7_5_0_, user0_.email as email8_5_0_, user0_.first_name as first_na9_5_0_, user0_.image_url as image_u10_5_0_, user0_.lang_key as lang_ke11_5_0_, user0_.last_name as last_na12_5_0_, user0_.login as login13_5_0_, user0_.password_hash as passwor14_5_0_, user0_.reset_date as reset_d15_5_0_, user0_.reset_key as reset_k16_5_0_, authoritie1_.user_id as user_id1_6_0__, authoritie1_.authority_name as authorit2_6_0__ from jhi_user user0_ left outer join jhi_user_authority authoritie1_ on user0_.id=authoritie1_.user_id left outer join jhi_authority authority2_ on authoritie1_.authority_name=authority2_.name where user0_.login=?
2020-08-06 21:25:13.583 DEBUG 35396 --- [ XNIO-1 task-20] g.p.r.CustomAuditEventRepository         : Enter: add() with argument[s] = [AuditEvent [timestamp=2020-08-06T09:25:13.582Z, principal=admin, type=AUTHENTICATION_SUCCESS, data={}]]
Hibernate: insert into jhi_persistent_audit_event (event_date, event_type, principal) values (?, ?, ?)
2020-08-06 21:25:13.941 DEBUG 35396 --- [ XNIO-1 task-20] g.p.r.CustomAuditEventRepository         : Exit: add() with result = null
2020-08-06 21:25:14.039 DEBUG 35396 --- [ XNIO-1 task-20] govt.pol.web.rest.UserJWTController      : Exit: authorize() with result = <200 OK OK,govt.pol.web.rest.UserJWTController$JWTToken@62c853e7,[Authorization:"Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImF1dGgiOiJST0xFX0FETUlOLFJPTEVfVVNFUiIsImV4cCI6MTU5Njc5MjMxNH0.6rKRuGSQMlGfBzwxPlv4RfgVET3GwIznNtj2VnK3JDh99uXgl33z0zNyqI8KEDSybRrd4_3dx9HRl-J_mG3Gjw"]>
2020-08-06 21:25:14.081  INFO 35396 --- [ XNIO-1 task-21] govt.pol.security.jwt.TokenProvider      : Invalid JWT token.
2020-08-06 21:25:14.088 DEBUG 35396 --- [ XNIO-1 task-21] g.p.r.CustomAuditEventRepository         : Enter: add() with argument[s] = [AuditEvent [timestamp=2020-08-06T09:25:14.087Z, principal=anonymousUser, type=AUTHORIZATION_FAILURE, data={details=org.springframework.security.web.authentication.WebAuthenticationDetails@957e: RemoteIpAddress: 127.0.0.1; SessionId: null, type=org.springframework.security.access.AccessDeniedException, message=Access is denied}]]
2020-08-06 21:25:14.088 DEBUG 35396 --- [ XNIO-1 task-21] g.p.r.CustomAuditEventRepository         : Exit: add() with result = null
2020-08-06 21:25:14.093  WARN 35396 --- [ XNIO-1 task-21] o.z.problem.spring.common.AdviceTraits   : Unauthorized: Full authentication is required to access this resource
2020-08-06 21:25:14.095  WARN 35396 --- [ XNIO-1 task-21] .m.m.a.ExceptionHandlerExceptionResolver : Resolved [org.springframework.security.authentication.InsufficientAuthenticationException: Full authentication is required to access this resource]
`

**Comment by atomfrede** [comment] 2020-08-06 10:00
Did you select remember me? Can you try a clean, private tab/window?

**Comment by bigalnz** [comment] 2020-08-06 15:21
> Did you select remember me? Can you try a clean, private tab/window?

I dont remember selecting remember me - but a private window has fixed it. I assume to fix it permenantly I need to clear out those stored credentials in Chrome?

**Comment by ruddell** [comment] 2020-08-06 20:32
Looks like a duplicate of https://github.com/jhipster/generator-jhipster/issues/12147, the wrong token is picked up.  I'm guessing you signed in with "remember me" and the token became invalid.  Signing in without "remember me" stores the token in sessionStorage, but that's loaded after the bad token in localStorage.

There's a good workaround/solution in the linked issue.

**Comment by atomfrede** [comment] 2020-08-07 12:14
Let's close it here, sounds you're assumption is correct @ruddell

**Closed by atomfrede** 2020-08-07 12:14 UTC
Labels: area: triage, theme: undefined
