### ISSUE TITLE
AWS - Database settings & table names

### ISSUE THREAD

**Issue by Vaelyr** [jhipster/generator-jhipster#1912] opened 2015-08-21 23:28 UTC
I tested my application on AWS. Deployment works fine, except that table names in MySQL are generated all in upper case due to the default parameter group setting `lower_case_table_names` which defaults to 0 and the schema default collation seems to be case sensitive. 

This results all the database queries to throw an invalid SQL exception from Hibernate. I had to change all table names to lower case manually and that seemed to work.

Is there any way you can pass in parameters during the RDS generation? Or is there anything I am missing, because locally my table names are always generated in lower case, not sure who is the victim here (Hibernate, Liquibase or MySQL settings).

Any suggestions or is it something that can be improved?

**Comment by deepu105** [comment] 2015-08-24 03:23
@wuethrich44 do you have any comment on this?

**Comment by wuethrich44** [comment] 2015-09-08 08:54
As you see in this [line](https://github.com/jhipster/generator-jhipster/blob/master/app/templates/src/main/resources/config/liquibase/changelog/_initial_schema.xml#L74) all table names are in upper case. Therefore I can't reproduce this issue with JHipster v2.20.0.

Which version of the JHipster generator do you use?

**Comment by Vaelyr** [comment] 2015-09-08 09:05
My Local MySQL creates table names in lower case regardless of what you have in liquibase, isn't that the case? Or are your local MySQL table names all upper case all the time? Mine are not, doesn't matter if I change them in entities and on liquibase. 

However RDS default settings prevent you from creating lower case table names due to the parameter (which can be manually configured by assigning custom parameter group for the instance).

I assume JPA entity names must be in the same case as the database table names, else there will be a conflict.

**Comment by wuethrich44** [comment] 2015-09-08 13:02
Yes on my local MySQL instance the table names are in lower case but the application works also on the RDS instance. So I don't understand really why you want lower case table names. If you want to change the parameter you can create a parameter group manually via AWS Managment Console and apply it to your RDS instance. Is that a acceptable workaround for you?

**Comment by Vaelyr** [comment] 2015-09-08 13:35
I just ran into a problem that caused Hibernate to throw exceptions because it expected table names to be lower case, while the RDS instance had made them all in upper. This isn't acceptable in my opinion and I was not sure what's the actual cause so I wanted to have some consistency here.

I can give another try where I change all entities and liquibase table names to uppercase and deploy fresh into clean RDS instance without changing anything. Currently only solution was to change the parameter manually.

**Comment by wuethrich44** [comment] 2015-09-09 08:56
I still don't understand why your table names are in lower case. Because the entity generator create them by default in upper case. Did you change all table names to lower case manually?

**Comment by deepu105** [comment] 2015-09-09 12:41
This seems to be not reproducable and also we cannot change the way we generate tables just for AWS so I dont think there is anything we can do here. @wuethrich44 im closing this, if you think this is an issue and it can be fixed on the subgen plz let me know ill re open this.
@vaelyr have you tried what wuethrich44 suggested?  Also please give more info and yo-rc config

**Closed by deepu105** 2015-09-09 12:41 UTC
Labels: aws, question

**Comment by safaahashim** [comment] 2015-10-04 22:32
I had similar issue when using MySql on Ubuntu. I resolved it by adding an MySql environment variable for "lower_case_table_names" in "/etc/mysql/my.cnf" and then restarting the server.

After I did that I dropped the old tables and regenerated the data schema which then was accessible, specially the authentication tables by spring with no issue.

Hope this helps.

**Comment by gmarziou** [comment] 2015-10-04 22:45
Duplicate of #2018
