### ISSUE TITLE
Error on generating UI entity in gateway

### ISSUE THREAD

**Issue by AnonymNoob** [jhipster/generator-jhipster#6901] opened 2017-12-21 01:21 UTC
##### **Overview of the issue**

I generated entity "prestations" in the related microservice  with command `jhipster entity prestations`
then when I wanted to generate the UI of the entity in gateway, I got the error 

ERROR! Microservice name for the entity is not found. Entity cannot be generated!

##### **Motivation for or Use Case**

I can't generate the related UI entity in gateway and I have read similar tickets but i did not get the point how I can solve this problem. I hope I could find a solution here

##### **JHipster Version(s)**

gateway@0.0.0 /home/scalpaine/careshop/gateway
└── generator-jhipster@4.10.2 
 (not a regression)

##### **JHipster configuration**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "fr"
    },
    "jhipsterVersion": "4.10.2",
    "baseName": "gateway",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "gateway",
    "testFrameworks": [
      "gatling",
      "cucumber",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "fr",
    "languages": [
      "fr",
      "en",
      "pt-br",
      "es"
    ]
  }
}
</pre>
</details>

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Browsers and Operating System**
OS: Ubuntu 17.10

**Comment by deepu105** [comment] 2017-12-21 07:39
How did you create the entity? You have not givem any entity config or
steps to reproduce here, we cant help you without these

**Comment by AnonymNoob** [comment] 2017-12-21 09:33
Thank you for replying.

Yes indeed, sorry for the lack of information.

**Reproduce the error:**

I have created the microservice prestations with the instruction `yo jhipster` and chose the microservice option, then I have generated the entity "prestations" within the microservice with the instruction `jhipster entity prestations`.

The Gateway was already created with the instruction `yo jhipster`, so I moved to the directory of the Gateway and lunched the instruction `jhipster entity prestations`.

The jhipster generator suggests if it's a generated entity from a microservice "Yes"
I typed the path "../services/prestations".

Then I got the message: "Prestations.json found and the entity will be automatically generated."
Then below the error:  

"ERROR! Microservice name for the entity is not found. Entity cannot be generated!"

**Comment by jdubois** [comment] 2017-12-21 09:40
I'm sorry but we need your full config to reproduce easily: the `.yo-rc.json` from both the microservice AND the gateway, as well as the `.jhipster/Prestations.json` from the microservice.
(and I know what can cause this issue, I just need to see what you have exactly)

**Comment by AnonymNoob** [comment] 2017-12-21 09:43
Yes no problem, I will copy/paste these files as soon as I get home, I'm at the office right now and don't have my laptop.

Thanks for being reactive.

**Comment by AnonymNoob** [comment] 2017-12-22 00:40
well here is the `.yo-rc.json` of the microservice prestations:
`{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "fr"
    },
    "jhipsterVersion": "4.11.1",
    "baseName": "prestations",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8083",
    "authenticationType": "jwt",
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "03df2d38d0b8ea922fc3d857ed840e1dee7492fe",
    "enableTranslation": true,
    "applicationType": "microservice",
    "testFrameworks": [
      "gatling",
      "cucumber"
    ],
    "jhiPrefix": "jhi",
    "nativeLanguage": "fr",
    "languages": [
      "fr",
      "en",
      "pt-br",
      "es"
    ],
    "clientPackageManager": "yarn",
    "skipClient": true,
    "skipUserManagement": true
  }
}`

here is the `.yo-rc.json` of the gateway:

` {
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "fr"
    },
    "jhipsterVersion": "4.10.2",
    "baseName": "gateway",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "c2d781e1fd8d90293d32ef1b95d86f2d74bfae81",
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "gateway",
    "testFrameworks": [
      "gatling",
      "cucumber",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "fr",
    "languages": [
      "fr",
      "en",
      "pt-br",
      "es"
    ]
  }
}`

and finally the `.jhipster/Prestations.json` from microservice:

`{
    "fluentMethods": true,
    "relationships": [],
    "fields": [
        {
            "fieldName": "nom",
            "fieldType": "String"
        }
    ],
    "changelogDate": "20171210161407",
    "dto": "no",
    "service": "no",
    "entityTableName": "prestations",
    "jpaMetamodelFiltering": false,
    "pagination": "pagination"
}`

I hope that I've pasted all the required files to resolve the problem

**Comment by jdubois** [comment] 2017-12-22 11:12
OK, this is because you don't have `"microserviceName": "prestations",` in your `.jhipster/Prestations.json`

-> I tested doing "jhipster entity Prestations" and it worked, how did you create your `.jhipster/Prestations.json`?

**Comment by AnonymNoob** [comment] 2017-12-22 11:41
Thanks for replying,

I have created the entity in the microservice with the instruction `jhipster entity prestations` (lowercase)
and added the filed name with the type string.

Then I moved to the gatewey and exected the same instruction.

So I have to add manually the name of the microservice in the `.jhipster/Prestations.json`?
If yes how please ?

**Comment by deepu105** [comment] 2017-12-22 11:57
There shoundt be anything manual to do, as Julien said he couldnt reproduce
your issue, so either you are doing something wrong or you are on some
weird edge case


Thanks & Regards,
Deepu

**Comment by AnonymNoob** [comment] 2017-12-22 12:06
Do you think the issue is the result of gettting the clone of the project and not creating it from scratch ?

**Comment by deepu105** [comment] 2017-12-22 12:11
what do you mean getting clone?
can you please clearly state the steps you did in bullet points


Thanks & Regards,
Deepu

**Comment by AnonymNoob** [comment] 2017-12-22 12:23
yes sure:

- I have cloned the project from remote repository `git clone <remote-repositroy-name>`
- I  moved to registry and run `mvn`
- I moved to microservice `prestations` and run `./mvnw`
- I moved to Gateway and run `./mvnw`
- I verified that the app is running in localhost:8080 and it was good
- I verified that the microservice `presations` was registered and it was good too
- I moved to microservice `prestations` and run `jhipster entity prestations` and the entity was created
- I moved to Gateway and run `jhipster entity prestations` and got the error 

Tell me if you need more steps

**Comment by jdubois** [comment] 2017-12-22 12:28
Oh sorry: I see you are using ` "jhipsterVersion": "4.11.1"`, maybe there was an issue in that release, I remember something like that -> this would explain why we can't reproduce, I was using the latest version, and this has been fixed.
Could you try with a newer version? I know upgrading can be painful.
Otherwise, the workaround is to add `"microserviceName": "prestations",`

**Comment by AnonymNoob** [comment] 2017-12-22 12:31
No problem, Thanks a lot for the solution I will try it.
Could you tell me please if it is possible to upgrade jhipster in an existing project and how ?
Or where I can find the documents related to upgrading ?

**Comment by jdubois** [comment] 2017-12-22 12:36
With each release notes we tell how to upgrade - so for you that would be http://www.jhipster.tech/2017/12/08/jhipster-release-4.12.0.html

**Comment by AnonymNoob** [comment] 2017-12-22 12:47
Ok great Julien! Thanks a lot  for your time guys. I'm gonna upgrade this tonight

**Comment by jdubois** [comment] 2017-12-22 12:49
Oh yes you can use 4.13.0, of course

**Comment by jdubois** [comment] 2017-12-22 12:50
I'm closing this as this looks solved, just add a comment if you still have an issue and I will reopen it

**Closed by jdubois** 2017-12-22 12:50 UTC
