### ISSUE TITLE
Tomcat: Broken Metrics page in 5.8.1

### ISSUE THREAD

**Issue by Dufgui** [jhipster/generator-jhipster#9195] opened 2019-02-05 14:25 UTC
##### **Overview of the issue**

Metrics page display nothing.

##### **Motivation for or Use Case**

Because it can be interesting to have metrics.

##### **Reproduce the error**
generate the app, change nothing. Launch it by eclipse or just in a tomcat
http://localhost:8080/#/admin/jhi-metrics

We see a stack in console:
org.springframework.http.converter.HttpMessageNotWritableException: Could not write JSON: Null key for a Map not allowed in JSON (use a converting NullKeySerializer?); nested exception is com.fasterxml.jackson.databind.JsonMappingException: Null key for a Map not allowed in JSON (use a converting NullKeySerializer?) (through reference chain: java.util.HashMap["cache"]->java.util.HashMap["null"])
	at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.writeInternal(AbstractJackson2HttpMessageConverter.java:294)
	at org.springframework.http.converter.AbstractGenericHttpMessageConverter.write(AbstractGenericHttpMessageConverter.java:102)
	at org.springframework.web.servlet.mvc.method.annotation.AbstractMessageConverterMethodProcessor.writeWithMessageConverters(AbstractMessageConverterMethodProcessor.java:272)
	at org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor.handleReturnValue(RequestResponseBodyMethodProcessor.java:180)
	at org.springframework.web.method.support.HandlerMethodReturnValueHandlerComposite.handleReturnValue(HandlerMethodReturnValueHandlerComposite.java:82)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:119)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:891)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
...
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Null key for a Map not allowed in JSON (use a converting NullKeySerializer?) (through reference chain: java.util.HashMap["cache"]->java.util.HashMap["null"])
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:285)
	at com.fasterxml.jackson.databind.SerializerProvider.mappingException(SerializerProvider.java:1251)
...
	at com.fasterxml.jackson.databind.ObjectWriter.writeValue(ObjectWriter.java:913)
	at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.writeInternal(AbstractJackson2HttpMessageConverter.java:285)
	... 101 common frames omitted

##### **Related issues**

No see, it's since jhipster migrate to micrometer

##### **Suggest a Fix**

the metric tomcat.cache.hit have no key because it have no tag name but have a name
So i suggest to change
JHipsterMetricsEndpoint.cacheMetrics() from:
```String name = counter.getId().getTag("name");```
to
```
String name = counter.getId().getTag("name");
if(name ==null) {
name = counter.getId().getName(); //maybe we can substring before the first dot found
}
```

##### **JHipster Version(s)**

5.8.1

##### **JHipster configuration**
 See above

##### **JHipster Version(s)**

```
reqhub@0.0.0 H:\git\mcp\com.trululu.mcp.requirement.product.server\plugins\com.trululu.mcp.server\com.trululu.metax.requirement.server.webapp
`-- generator-jhipster@5.8.1

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
    "generator-jhipster": {
        "promptValues": {
            "packageName": "com.trululu.metax.requirement.server.webapp",
            "nativeLanguage": "en"
        },
        "jhipsterVersion": "5.8.1",
        "applicationType": "monolith",
        "baseName": "reqhub",
        "packageName": "com.trululu.metax.requirement.server.webapp",
        "packageFolder": "com/trululu/metax/requirement/server/webapp",
        "serverPort": "8080",
        "authenticationType": "session",
        "cacheProvider": "ehcache",
        "enableHibernateCache": true,
        "websocket": false,
        "databaseType": "sql",
        "devDatabaseType": "h2Disk",
        "prodDatabaseType": "mariadb",
        "searchEngine": false,
        "messageBroker": false,
        "serviceDiscoveryType": false,
        "buildTool": "maven",
        "enableSwaggerCodegen": false,
        "rememberMeKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
        "clientFramework": "angularX",
        "useSass": false,
        "clientPackageManager": "npm",
        "testFrameworks": ["gatling", "protractor"],
        "jhiPrefix": "jhi",
        "otherModules": [],
        "enableTranslation": true,
        "nativeLanguage": "en",
        "languages": ["en"],
        "entitySuffix": "",
        "dtoSuffix": "DTO"
    }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

git version 2.19.0.windows.1

node: v8.12.0

npm: 6.7.0

yeoman: 2.0.5

INFO! Congratulations, JHipster execution is complete!

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

no entity

##### **Browsers and Operating System**

-   [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by Dufgui** [comment] 2019-02-05 14:40
another possible fix is to exclude tomcat cache, or to tag tomcat cache just like TomcatMetricsAutoConfiguration but add a tag:
```
        @Bean
	@ConditionalOnMissingBean
	public TomcatMetrics tomcatMetrics() {
		return new TomcatMetrics(
				(this.context != null) ? this.context.getManager() : null,
				Tag.of);
	}
```

**Comment by clement26695** [comment] 2019-02-05 15:54
Hi ! Thank you for reporting the issue !

Considering first option, I fear that the format of the response would be different as the one expected by the front end part.
```json
"cache" : {
    "usersByEmail" : {
      "cache.gets.miss" : 0.0,
      "cache.puts" : 0.0,
      "cache.gets.hit" : 0.0,
      "cache.removals" : 0.0,
      "cache.evictions" : 0.0
    },
    "com.trululu.metax.requirement.server.webapp.domain.PersistentToken" : {
      "cache.gets.miss" : 0.0,
      "cache.puts" : 0.0,
      "cache.gets.hit" : 0.0,
      "cache.removals" : 0.0,
      "cache.evictions" : 0.0
    }
    ...
}
```
But would be something like : 
```json
"cache" : {
    "cache.gets" : {
      "cache.gets.miss" : 0.0,
      "cache.gets.hit" : 0.0,
    },
    ...
}
```
It would also be less meaningful, IMO. So there is maybe a better way to do it.

Concerning the second option, some infos would be lost, so it is also something that bother me...

**Comment by clement26695** [comment] 2019-02-06 10:12
I missed something in your last comment ! Tagging tomcat cache could be the best option. WDYT @PierreBesson ?

**Comment by PierreBesson** [comment] 2019-02-06 10:15
@clement26695, sorry I don't understand the issue so I'm counting on you to reproduce and fix it...

**Comment by Dufgui** [comment] 2019-02-06 10:26
My first proposale is just like a seat belt. In case of missing tag name. it was orthogonal to my other proposale, so we can implement the first and tag the tomcat too.

**Comment by Dufgui** [comment] 2019-02-06 10:29
To be more clear, my json response is:
```
"cache" : {
    "usersByEmail" : {
      "cache.gets.miss" : 0.0,
      "cache.puts" : 0.0,
      "cache.gets.hit" : 0.0,
      "cache.removals" : 0.0,
      "cache.evictions" : 0.0
    },
    "com.trululu.metax.requirement.server.webapp.domain.PersistentToken" : {
      "cache.gets.miss" : 0.0,
      "cache.puts" : 0.0,
      "cache.gets.hit" : 0.0,
      "cache.removals" : 0.0,
      "cache.evictions" : 0.0
    },
    null : {
      "tomcat.gets.miss" : 0.0,
      "tomcat.cache.hit" : 0.0,
    },
...

```

**Comment by pascalgrimaud** [comment] 2019-02-06 10:36
Just tested this configuration, and I don't have this "tomcat.cache.hit".
I started the application, using `./mvnw`

**Comment by Dufgui** [comment] 2019-02-06 11:59
I have it when i launch from STS and run as Spring Boot Application
this one use tomcat instead of undertow

**Comment by pascalgrimaud** [comment] 2019-02-06 13:10
You said:
> Launch it by eclipse or maven

Because I tested with maven, there is no problem. So the issue comes from Eclipse, and I think it is not related to JHipster.

**Comment by Dufgui** [comment] 2019-02-06 13:37
yes it's a mistake, i update the description. But I test all fix list above and it's work. So it's a tomcat spring boot metric bug not an eclipse bug.

**Comment by clement26695** [comment] 2019-02-06 13:39
Yes, I manage to reproduce the bug when launching the app on tomcat. I didn't had the time to test your fixes yet

**Comment by pascalgrimaud** [comment] 2019-02-06 13:39
Ok guys, don't hesitate to apply the fix, if you have one!

**Comment by clement26695** [comment] 2019-02-06 13:44
Would you be ok to make a PR to apply the fix, @Dufgui ?

**Comment by Dufgui** [comment] 2019-02-06 13:44
So wich PR do you want ? 

- [ ] Tomcat init
- [ ] JHipsterMetricsEndpoint.cacheMetrics() get start of full name
- [ ] JHipsterMetricsEndpoint.cacheMetrics() log and ignore when tag name missing
- [ ] JHipsterMetricsEndpoint.cacheMetrics() get start of full name when tag name missing




 init ?

**Comment by clement26695** [comment] 2019-02-06 13:58
In retrospect, I would go with the 4th option, as we won't display these metrics correctly on the Metrics page anyway.

**Comment by Dufgui** [comment] 2019-02-06 13:59
ok for me, i no reply since this eavening, i will do my PR this night ;o)

**Comment by Dufgui** [comment] 2019-02-06 20:20
https://github.com/jhipster/jhipster/pull/170

**Comment by clement26695** [comment] 2019-02-07 11:26
Looks fine for me !

**Comment by DanielFran** [comment] 2019-02-09 00:57
@Dufgui @clement26695 PR in jhipster lib has been merged.
Please confirm if it can be closed?
Thanks

**Comment by Dufgui** [comment] 2019-02-09 06:58
yes it can

**Closed** 2019-02-09 08:04 UTC
Labels: bug :bug:, server-side libraries

**Comment by GiKyouGetsu** [comment] 2019-05-24 08:46
Hi @Dufgui @clement26695 @PierreBesson  , if i don't want to upgrade my project, how can I do to fix this issue?

**Comment by Dufgui** [comment] 2019-05-24 09:04
> @Bean
> 	@ConditionalOnMissingBean
> 	public TomcatMetrics tomcatMetrics() {
> 		return new TomcatMetrics(
> 				(this.context != null) ? this.context.getManager() : null,
> 				Arrays.asList(Tag.of("name","tomcat"));
> 	}


Cf my previous comment

**Comment by ernsyn** [comment] 2019-05-31 07:34
Is this released? I'm getting the same error in 5.8.2.

**Comment by clement26695** [comment] 2019-05-31 07:56
I think it was just included in the 6.0.0 version, unfortunately, but the fix provided by @Dufgui should work

**Comment by leonardomoralopez89** [comment] 2020-03-19 15:34
> > @bean
> > @ConditionalOnMissingBean
> > public TomcatMetrics tomcatMetrics() {
> > return new TomcatMetrics(
> > (this.context != null) ? this.context.getManager() : null,
> > Arrays.asList(Tag.of("name","tomcat"));
> > }
> 
> Cf my previous comment

How implement this solution, please be more specific, need help

**Comment by Dufgui** [comment] 2020-03-19 17:58
create a @Configuration wich expose this bean. 
The @Configuration class must be scanned by spring boot.

But It's an old bug, maybe it's another metrics wich block you today. You must debug to find which one, if my fix does n t work for you

**Comment by leonardomoralopez89** [comment] 2020-03-19 20:46
> create a @configuration wich expose this bean.
> The @configuration class must be scanned by spring boot.
> 
> But It's an old bug, maybe it's another metrics wich block you today. You must debug to find which one, if my fix does n t work for you

sorry for the inconvenience but what is the import of context
