### ISSUE TITLE
hibernate lazyinitialisation exception calling getAllEntity with dtos and services

### ISSUE THREAD

**Issue by NilsWild** [jhipster/generator-jhipster#3790] opened 2016-06-28 17:04 UTC
##### **Overview of the issue**

When you generate your entities with service and DTOs your calls to the findAll endpoints will fail as the dto is mapped after the transaction is closed. This will lead to a lazyinitialisationexception.

##### **Motivation for or Use Case** 

The findAll rest endpoint will return an hibernate lazyinitialisationeception as the transactin is closed before the fields are join fetched.

##### **JHipster Version(s)** 

3.4.2 as well as earlier versions

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 

[yo.rc.txt](https://github.com/jhipster/generator-jhipster/files/337587/yo.rc.txt)

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory** 

[Kita.txt](https://github.com/jhipster/generator-jhipster/files/337589/Kita.txt)
[Traeger.txt](https://github.com/jhipster/generator-jhipster/files/337590/Traeger.txt)

##### **Browsers and Operating System** 

Server related Problem

##### **Reproduce the error** 

create any entity with dto service and mapping and an lazy relationship and call the rest endpoint to get all entities of that type

##### **Related issues** 

-

##### **Suggest a Fix** 

Alternative
1. 

Add an @Transactional to the getAll endpoint as the Page information is needed to create the appropriate headers (don't know how this would affect performance or anything)

2.

create a custom "Page" object that is returned by the services findAll method that contains the content as well as the headers that is then applied to the response in the resource

**Comment by geraldhumphries** [comment] 2016-06-28 22:56
The resources did used to have the `@Transactional` annotation. Looks like it was removed following the discussion in #3175.

Might require a revert of that change.

**Comment by jdubois** [comment] 2016-06-29 06:25
Yes issue #3175 (ping @lordlothar99 ) is related - sorry I just didn't have enough time during the last few months

**Comment by lordlothar99** [comment] 2016-06-29 15:25
yes I think it's better with `@Transactional` in REST controllers (readonly if possible), so the hbn session will allow lazy loadings wihile converting entitites to DTO ; I know some guys may dislike this option, but it's the simplest one

**Comment by jdubois** [comment] 2016-06-29 15:30
You're right, I really dislike this option :-)

**Comment by srnm** [comment] 2016-07-06 04:37
Another issue is that for consistent DTOs you _need_ to do the transform from entity->DTO in the same transaction.

Using OpenSessionInView and/or eager fetching/transformation are far worse problems. By extending the transaction boundary up to the resource access you are having spring manage something similar to OpenSessionInView in a less ORM dependent way -- and gain consistent DTOs.

I remember reading an article that suggested adding @Transactional at the web resource level is becoming more of an accepted practice. Unfortunately I can't find the article...

Here's another write up on the issue that doesn't encourage, but doesn't condemn: http://stackoverflow.com/questions/23118789/why-we-shouldnt-make-a-spring-mvc-controller-transactional

**Comment by evelknievel** [comment] 2016-07-07 19:19
I like the idea of having a good architecture and seperation of concerns. The service layer should NOT handle mapping logic and or have anything to do with DTO's. So i'm very happy with issue #3175 . Actually, I made all these changes by hand in our current project. I think we have to avoid the resources to be transactional. I also ran into this same issue. The problem is we need the total count. 
This can be done by a seperate service call, which performs a countAllEntities(), or we can create a custom wrapper object which contains the List of Entities as well as a total count. I prefer the last option because we have to perform only one service call. Also, the service can work with the spring.data Page object to get the info needed. I don't think this count issue is a reason to make the resources transactional, we should try to avoid that as much as possible.

**Comment by deepu105** [comment] 2016-07-13 02:04
related to https://github.com/jhipster/generator-jhipster/issues/3175

**Comment by jdubois** [comment] 2016-08-05 14:19
This will be fixed with #3175

I just tested your use case (with the 2 provided entities) with the test branch for #3175 and I didn't get any lazy initialization error (which is normal, as now this is done in the service layer, which is transactional).

**Closed by jdubois** 2016-08-05 14:19 UTC
Labels: bug
