### ISSUE TITLE
[FEATURE] Entity and BaseEntity , EntityService and BaseEntityService, EntityResource & BaseEntityResource ...

### ISSUE THREAD

**Issue by unikzforce** [jhipster/generator-jhipster#3926] opened 2016-08-03 16:45 UTC
##### **Overview of the issue**

Everything Could have a Base class, for Example If you generate User, you could generate BaseUser, then UserService and BaseUserService and UserRepository and BaseUserRepository , UserFullDTO ( User dto with full extent) and BaseUserFullDTO,  UserResource and BaseUserResource ....

##### **Motivation for or Use Case**

suppose. you made your model .all your previous works and modifications are in "User.java" and then you changed your model a bit, and regenerated it again, all your modifications will be gone and you should track them from git or svn or .. . it could be really cumbersome but what if Every thing had a Base* , then you can override things in "User.java" and only Base* classes will be regenerated, and all your Modifications and new methods and etc will be untouched. It's much more easier to maintain.

**Comment by deepu105** [comment] 2016-08-03 17:09
Agree that its much more easier to maintain. we had thought about this and discussed it in few other issues, but the problem is this would be a major overhaul and a huge architecture change I dont think we have the bandwidth for that at the moment. So this could be something to consider for JHipster 5.0 or something
@jdubois what do you think?

**Comment by unikzforce** [comment] 2016-08-03 22:25
Okey,you're the boss around here. anyway in our company we're using such a generator, we design our model upon Hibernate standard "hbm.xml" files and generate our *Mgrs and *DAOs using those hbm files. then we create some "*.view.xml" and we generate Resources and DTOs and Angular crud/management modules and htmls upon them.  for ethical reasons i cannot use this generator for projects outside the company... so jhipster is my last hope,, i'll keep eye on it.. you're doing great.

**Comment by jdubois** [comment] 2016-08-04 08:21
Yes @deepu105 this is a discussion we've already had.
Many Java generators work this way, and it could be good option - we just don't have it as at the beginning I used as examples JavaScript generators, as well as RoR, and they are just scaffolding tools. So I'm quite happy with our current "scaffolding only" version, but that could be a good improvement, at least this is something we should try & consider.
It's obvious that we won't do this anytime soon, first we need to have AngularJS 2 support and that's going to take a few months.
As this would be a big work, we would need someone available to do this for an extended period of time (a few months, probably), and at the moment there is nobody with that time in the team: hopefully we will have a company sponsoring this, otherwise I'll see this the next time I have a trainee.
I'm closing this as we clearly won't be doing it anytime soon (and not by lack of interest, I'd love to have this going forward, at least as an experiment).

**Closed by jdubois** 2016-08-04 08:21 UTC
Labels: feature request, willdolater

**Comment by deepu105** [comment] 2016-08-04 08:33
May be as a starter we can layout an architecture as how we wanna do it and
propose it here so that if some body wants to pitch in they can start from
there.
This would mean that JHipster will become more of a framework rather than
just a scaffolding tool and the opportunities there would be endless.

If you would like I can try to propose a base structure for this but you
are the java guru here so it would be much better if you want to do that :)

Thanks & regards,
Deepu
