### ISSUE TITLE
[Enhancement] Static / Dynamic roles (authorities) in jHipster

### ISSUE THREAD

**Issue by ddewaele** [jhipster/generator-jhipster#3399] opened 2016-04-15 06:35 UTC
jHipster user mgmt allows for the creation of users with one or more roles. If we want to add custom roles they now need to be defined in 2 places. As roles are stored in the DB, they should only be defined in one place.

Currently they need to be defined in :

The DB :
```
insert into jhi_authority (name) VALUES ('ROLE_CUSTOM1');
insert into jhi_authority (name) VALUES ('ROLE_CUSTOM2');
```

In the UI : 

- user-management-dialog.controller.js
- user-management.controller.js

JHIpster hardcodes 2 roles:
```
vm.authorities = ['ROLE_USER', 'ROLE_ADMIN'];
```

##### **Motivation for or Use Case** 

If one wants to support additional roles they need to be added in 2 places.

##### **JHipster Version(s)** 

3.0

##### **Suggest a Fix** 

Would be better if the UI controllers were dynamic and used an Authority endpoint to fetch the roles dynamically.

**Comment by deepu105** [comment] 2016-04-15 07:09
duplicate of https://github.com/jhipster/generator-jhipster/issues/1995 @ddewaele I have a solution and Ill do a PR soon

**Closed by deepu105** 2016-04-15 07:09 UTC
