### ISSUE TITLE
one-directional one-to-many relationship generation

### ISSUE THREAD

**Issue by ValerioMC** [jhipster/generator-jhipster#1163] opened 2015-02-17 15:19 UTC
Hello, 

first of all congratulation @jdubois  for this beautiful project :+1: 

i've noticed that during one-to-many generation, jhipster asks if we want to add the relation also on the other entity (bidirectional relationship), if we say "No" attribute used in annotation for one-to-many will be "mappedBy=" that needs a bidirectional relationship.

In case we say 'No" do you think reasonable to map the relation with a join table (like many-to-many)? so bidirectional relationship is not needed 

Greetings,
Valerio

**Comment by jdubois** [comment] 2015-02-18 09:36
You are correct, we only support bi directional relationships.

We should indeed support uni directional relationships -> that wouldn't be a joint table, just a relationship on one side.

The issue is that we need to generate our mapping differently, and I didn't work on this yet.

I'm keeping this opened as I should indeed work on this.

**Comment by ValerioMC** [comment] 2015-02-18 11:49
Brilliant!

Just to clarify and explain better... i've taken as example a uni one-to-many (parent(one) -> childrens(many)) where the owner of the relationship is only the parent with no (java) reference on children-side.

In this particular case it's not possibile to have a uni-directional without a join table because in relational-database/one-to-many, the foreign key is on childrens.
so when this object oriented/relational database mismatch happens, there are usually two approaches, the first one is:

to change from:
one-to-many / uni / parent ownership
to:
many-to-one / uni / children ownership

and in this case we don't need join table.

But if we don't want to do this, bacause of our model, and we want to keep:

one-to-many / uni / parent ownership
we need a join table that's very similar to many-to-many

Currently, as you said, jhipster doesn't handle uni directional relationships, in addition it would be nice to handle also this particular case, to force one approach (es. many-to-one) or to give the possibility to the user to choose the desired approach with an join-table (similar to many-to-many)

Hope this was a better explanation :)

Greetings,
Valerio

**Comment by jdubois** [comment] 2015-03-06 10:37
OK, but the root of the problem is still that we don't generate uni-directional relationships -> I'm eventually closing this, as this is on my roadmap, and not truly a bug (it's documented that we only support bi directional relationships)

**Closed by jdubois** 2015-03-06 10:37 UTC

**Comment by naymesh** [comment] 2015-09-18 03:46
Great project @jdubois 

I am using jhipster version 2.21.0. I need to have a uni directional `OneToMany` between my two entities with a `@JoinTable`. Is this feature available yet (there is a tag link to 2.5.2 here)? Am I missing something?
