### ISSUE TITLE
Error when I execute mvn liquibase:diff

### ISSUE THREAD

**Issue by adetrie** [jhipster/generator-jhipster#1355] opened 2015-04-07 19:21 UTC
Hi,

First of all, thank you for this beautiful tools !

So, I have created my project with jHipster. I'm using Postgres (local and prod) with cache with OAuth2 authentication. It's a JAVA8 project.

Here my config :
Apache Maven 3.2.3 (33f8c3e1027c3ddde99d3cdebad2656a31e8fdf4; 2014-08-11T22:58:10+02:00)
Maven home: /Users/tripless/Applications/apache-maven-3.2.3
Java version: 1.8.0_40, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_40.jdk/Contents/Home/jre
Default locale: fr_FR, platform encoding: UTF-8
OS name: "mac os x", version: "10.10.2", arch: "x86_64", family: "mac"

Here my liquibase config :
[DEBUG] Configuring mojo 'org.liquibase:liquibase-maven-plugin:3.3.2:diff' with basic configurator -->
[DEBUG]   (f) changeLogFile = src/main/resources/config/liquibase/master.xml
[DEBUG]   (f) clearCheckSums = false
[DEBUG]   (f) diffChangeLogFile = src/main/resources/config/liquibase/changelog/20150407191323_changelog.xml
[DEBUG]   (f) diffExcludeObjects = oauth_access_token, oauth_approvals, oauth_client_details, oauth_client_token, oauth_code, oauth_refresh_token
[DEBUG]   (f) driver = org.postgresql.Driver
[DEBUG]   (f) emptyPassword = false
[DEBUG]   (f) includeArtifact = true
[DEBUG]   (f) includeTestOutputDirectory = true
[DEBUG]   (f) logging = debug
[DEBUG]   (f) password = mypassword
[DEBUG]   (f) project = MavenProject: net.tripless.passenger.server:passenger:0.0.1-SNAPSHOT @ /Users/tripless/AndroidStudioProjects/Passenger/jhipster/pom.xml
[DEBUG]   (f) promptOnNonLocalDatabase = true
[DEBUG]   (f) propertyFileWillOverride = false
[DEBUG]   (f) referenceUrl = hibernate:spring:net.tripless.passenger.server.domain?dialect=org.hibernate.dialect.PostgreSQL82Dialect
[DEBUG]   (f) url = jdbc:postgresql://localhost:5432/passenger
[DEBUG]   (f) username = postgres
[DEBUG]   (f) verbose = true

Here the error generated by maven :
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.089 s
[INFO] Finished at: 2015-04-07T21:13:26+02:00
[INFO] Final Memory: 26M/279M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.liquibase:liquibase-maven-plugin:3.3.2:diff (default-cli) on project passenger: Error setting up or running Liquibase: liquibase.command.CommandExecutionException: java.lang.NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.liquibase:liquibase-maven-plugin:3.3.2:diff (default-cli) on project passenger: Error setting up or running Liquibase: liquibase.command.CommandExecutionException: java.lang.NullPointerException
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:347)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:154)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:582)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:214)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:158)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Error setting up or running Liquibase: liquibase.command.CommandExecutionException: java.lang.NullPointerException
	at org.liquibase.maven.plugins.AbstractLiquibaseMojo.execute(AbstractLiquibaseMojo.java:373)
	at org.liquibase.maven.plugins.LiquibaseDatabaseDiff.execute(LiquibaseDatabaseDiff.java:145)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 19 more
Caused by: liquibase.exception.LiquibaseException: liquibase.command.CommandExecutionException: java.lang.NullPointerException
	at liquibase.integration.commandline.CommandLineUtils.doDiffToChangeLog(CommandLineUtils.java:123)
	at liquibase.integration.commandline.CommandLineUtils.doDiffToChangeLog(CommandLineUtils.java:100)
	at org.liquibase.maven.plugins.LiquibaseDatabaseDiff.performLiquibaseTask(LiquibaseDatabaseDiff.java:176)
	at org.liquibase.maven.plugins.AbstractLiquibaseMojo.execute(AbstractLiquibaseMojo.java:369)
	... 22 more
Caused by: liquibase.command.CommandExecutionException: java.lang.NullPointerException
	at liquibase.command.AbstractCommand.execute(AbstractCommand.java:13)
	at liquibase.integration.commandline.CommandLineUtils.doDiffToChangeLog(CommandLineUtils.java:121)
	... 25 more
Caused by: java.lang.NullPointerException
	at java.util.regex.Matcher.getTextLength(Matcher.java:1283)
	at java.util.regex.Matcher.reset(Matcher.java:309)
	at java.util.regex.Matcher.<init>(Matcher.java:229)
	at java.util.regex.Pattern.matcher(Pattern.java:1093)
	at liquibase.diff.output.StandardObjectChangeFilter$Filter.matches(StandardObjectChangeFilter.java:104)
	at liquibase.diff.output.StandardObjectChangeFilter.include(StandardObjectChangeFilter.java:70)
	at liquibase.diff.output.StandardObjectChangeFilter.includeMissing(StandardObjectChangeFilter.java:51)
	at liquibase.diff.output.changelog.ChangeGeneratorChain.fixMissing(ChangeGeneratorChain.java:28)
	at liquibase.diff.output.changelog.ChangeGeneratorFactory.fixMissing(ChangeGeneratorFactory.java:99)
	at liquibase.diff.output.changelog.DiffToChangeLog.generateChangeSets(DiffToChangeLog.java:145)
	at liquibase.diff.output.changelog.DiffToChangeLog.print(DiffToChangeLog.java:125)
	at liquibase.diff.output.changelog.DiffToChangeLog.print(DiffToChangeLog.java:76)
	at liquibase.diff.output.changelog.DiffToChangeLog.print(DiffToChangeLog.java:64)
	at liquibase.command.DiffToChangeLogCommand.run(DiffToChangeLogCommand.java:61)
	at liquibase.command.AbstractCommand.execute(AbstractCommand.java:8)
	... 26 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

Do you have any idea about this error ?
I can copy the entire trace if needed.

Thanks a lot.

Alexis

**Comment by flythebluesky** [comment] 2015-04-07 20:02
Looks like a duplicate of
https://github.com/jhipster/generator-jhipster/issues/754

**Comment by adetrie** [comment] 2015-04-07 21:14
@flythebluesky 
thanks for your answer.

I have already read this topic, I have the last version of liquibase and liquibase-hibernate but the error is still here. More over, the error isn't the same :)

**Comment by jdubois** [comment] 2015-04-08 07:03
This is likely a Liquibase issue -> could you post your issue on the Liquibase Github project, and link it here?

**Comment by adetrie** [comment] 2015-04-08 07:39
Issue is available on https://github.com/liquibase/liquibase-hibernate/issues/79

**Comment by atomfrede** [comment] 2015-04-08 19:25
For me ``liquibase:diff`` works well with java8 and oauth (As my postgres is version 9.3 I had to change the driver).

**Comment by adetrie** [comment] 2015-04-08 20:21
I have updated my PostgreSQL version to 9.3->9.4.
Everything is ok now.

**Comment by jdubois** [comment] 2015-04-09 09:09
OK, so this is an issue with Liquibase support of PostgreSQL -> I'm closing this as this not a JHipster issue, but of course that's annoying.
The weird thing is that I'm using 9.3...

**Closed by jdubois** 2015-04-09 09:09 UTC

**Comment by atomfrede** [comment] 2015-04-09 09:15
Another strange thing, the hibernate driver is by default postgres 8

**Comment by jdubois** [comment] 2015-04-09 09:27
@atomfrede good to know! As long as it works I'm reluctant to change it, but that's very strange indeed.
