### ISSUE TITLE
Access Info such as login from current user on the front end Javascript side (JHIPSTER)

### ISSUE THREAD

**Issue by kante12** [jhipster/generator-jhipster#2744] opened 2016-01-31 15:22 UTC
Hi, 
This may be the easiest thing for you all, but it is bothering me that I cannot retrieved the simplest things from the current user in my application.

Simply put let's say for instance a user signs in in the app, and you want to retrieve the user's first name to display welcome back "{{User.firstName}}" or the current user is sending a message to another user and you want to get his/her login as the "sender attribute" for your message entity HOW DO YOU DO THAT?

I am aware of the loadAll() method which return all users, but I still am not able to pick the current user from all those users.   @jdubois, @deepu105

**Comment by jdubois** [comment] 2016-01-31 18:13
This is the ticket system -> can you post this to StackOverflow?
I'm closing this as this is not a bug.

**Closed by jdubois** 2016-01-31 18:13 UTC

**Comment by kante12** [comment] 2016-01-31 23:26
Sure. Thank you and sorry for the inconvenience.

**Comment by deepu105** [comment] 2016-02-01 00:32
Take a look at the principal service, it will give you the current user,
check the login module or home page where it is used

**Comment by jdubois** [comment] 2016-02-01 06:47
Yes, but let's answer this on Stackoverflow

**Comment by kante12** [comment] 2016-02-01 13:32
Thank you very much @deepu105
