### ISSUE TITLE
 workbox-sw is needed by the service worker and could not be copied over to your new site.

### ISSUE THREAD

**Issue by xiaoxie** [jhipster/generator-jhipster#6945] opened 2018-01-05 09:37 UTC
i just run command ```yarn build```,more error info as follow:

...
601ms additional asset processing
2ms chunk asset optimization
 94% asset optimizationMergetJsonsWebpackPlugin compilation started...
MergetJsonsWebpackPlugin compilation completed...                                                                  58ms asset optimization 95% emittingMergetJsonsWebpackPlugin emit starts...
MergetJsonsWebpackPlugin emit completed...
MergetJsonsWebpackPlugin emit starts...
MergetJsonsWebpackPlugin emit completed...
MergetJsonsWebpackPlugin emit starts...
MergetJsonsWebpackPlugin emit completed...
Error: workbox-sw is needed by the service worker and could not be copied over to your new site. Error: EPERM: operation not permitted, open 'D:\source\gitspace\orders\build\www\workbox-sw.prod.v2.1.2.js.map'
    at Promise.all.then.catch (D:\source\gitspace\orders\node_modules\workbox-build\build\lib\utils\copy-workbox-sw.js:17:13)
    at <anonymous>
error Command failed with exit code 1.
error Command failed with exit code 1.
error Command failed with exit code 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

thanks!

**Comment by xiaoxie** [comment] 2018-01-05 09:39
and my jhister version is  v4.13.2

**Comment by glautervl** [comment] 2018-01-05 13:23
When try to deploy a gateway application on heroku I get the same error.
...
[INFO] yarn run v1.3.2
[INFO] $ yarn run cleanup && yarn run webpack:prod:main && yarn run clean-www
[INFO] $ rimraf target/{aot,www}
[INFO] $ yarn run webpack -- --config webpack/webpack.prod.js --progress --profile
[ERROR] warning From Yarn 1.0 onwards, scripts don't require "--" for options to be forwarded. In a future version, any explicit "--" will be forwarded as-is to the scripts.
[INFO] $ node --max_old_space_size=4096 node_modules/webpack/bin/webpack.js --config webpack/webpack.prod.js --progress --profile
[ERROR] 35989ms building modules                                                                
[ERROR] 70ms sealing
[ERROR] 1ms optimizing 
[ERROR] 0ms basic module optimization 
[ERROR] 64ms module optimization
[ERROR] 0ms advanced module optimization 
[ERROR] 16ms basic chunk optimization       
[ERROR] 0ms chunk optimization 
[ERROR] 2ms advanced chunk optimization 
[ERROR] 2931ms building modules                                                                
[ERROR] 0ms module and chunk tree optimization 
[ERROR] 1ms chunk modules optimization 
[ERROR] 0ms advanced chunk modules optimization 
[ERROR] 9ms module reviving 
[ERROR] 0ms module order optimization 
[ERROR] 4ms module id optimization 
[ERROR] 4ms chunk reviving 
[ERROR] 0ms chunk order optimization 
[ERROR] 20ms chunk id optimization
[ERROR] 393ms hashing
[ERROR] 1ms module assets processing 
[ERROR] 463ms chunk assets processing
[ERROR] 6ms additional chunk assets processing 
[ERROR] 1ms recording 
[ERROR] 17178ms additional asset processing
[ERROR] 1ms chunk asset optimization 
[INFO] MergetJsonsWebpackPlugin compilation started...
[INFO] MergetJsonsWebpackPlugin compilation completed...
[ERROR] 504ms asset optimization
[INFO] MergetJsonsWebpackPlugin emit starts...
[INFO] MergetJsonsWebpackPlugin emit completed...
[INFO] MergetJsonsWebpackPlugin emit starts...
[INFO] MergetJsonsWebpackPlugin emit completed...
[INFO] MergetJsonsWebpackPlugin emit starts...
[INFO] MergetJsonsWebpackPlugin emit completed...
[ERROR]  95% emittingError: workbox-sw is needed by the service worker and could not be copied over to your new site. Error: ENOENT: no such file or directory, unlink '/Users/glauterlemos/Dropbox/DESENVOLVIMENTO/JAVA/indoorchannel/IDCGateway/target/www/workbox-sw.prod.v2.1.2.js'
[ERROR]     at Promise.all.then.catch (/Users/glauterlemos/Dropbox/DESENVOLVIMENTO/JAVA/indoorchannel/IDCGateway/node_modules/workbox-build/build/lib/utils/copy-workbox-sw.js:17:13)
[ERROR]     at <anonymous>
[ERROR] error Command failed with exit code 1.
[INFO] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[ERROR] error Command failed with exit code 1.
[INFO] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[ERROR] error Command failed with exit code 1.
[INFO] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:16 min
[INFO] Finished at: 2018-01-05T10:21:07-03:00
[INFO] Final Memory: 48M/422M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.6:yarn (webpack build prod) on project idc-gateway: Failed to run task: 'yarn run webpack:prod' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1) -> [Help 1]

**Comment by kaidohallik** [comment] 2018-01-05 14:23
Fix in my case is described here: https://github.com/jhipster/generator-jhipster/pull/6716#issuecomment-352351247

**Comment by gmarziou** [comment] 2018-01-05 17:18
I confirm that this is failing also all time on Ubuntu with 4.13.2 and maven, I'm going to try upgrading workbox-webpack-plugin to version 3.0.0-alpha.3 as suggested by @kaidohallik

**Comment by gmarziou** [comment] 2018-01-05 18:04
Tested successfully on Ubuntu 17.10 and Windows 10 with JHipster 4.13.2 using maven where it was failing systematically.

**Comment by pascalgrimaud** [comment] 2018-01-05 19:43
@gmarziou : do you have input to reproduce the error ? I tried but never got locally the error. And for Travis, it failed rarely...

**Comment by gmarziou** [comment] 2018-01-05 20:11
I have no idea what triggers the error, I suspect a race condition during file access. I have sen several similar errors in various node modules and most of the time they ended up re-coding some parts dealing with files.

**Comment by jdubois** [comment] 2018-01-05 22:04
I'm doing this all the time and never had the error - I'm closing this as we can't reproduce, but indeed maybe we should better fix the dependencies versions... Next time, could you do a "diff" on your package-lock.json or yarn-lock.json before and after the error is fixed? So we can pinpoint what causes the issue

**Closed by jdubois** 2018-01-05 22:04 UTC

**Comment by nutrimax1987** [comment] 2018-01-08 19:18
Windows 10 . same error .
[ERROR]  95% emittingError: workbox-sw is needed by the service worker and could not be copied over to your new site. Error: EPERM: operation not permitted, open '...target\www\workbox-sw.prod.v2.1.2.js.map''

**Comment by jdubois** [comment] 2018-01-08 19:23
yes, from my understanding this will be fixed in the next release

**Comment by gmarziou** [comment] 2018-01-08 21:23
@nutrimax1987 before the release, you can fix it in your package.json, see commit.

**Comment by xiaoxie** [comment] 2018-01-11 02:54
That is great!

**Comment by knavadiya** [comment] 2018-02-20 07:12
ok
