### ISSUE TITLE
Securing url resources from unauthorized users doesn't work for token based approach

### ISSUE THREAD

**Issue by thiloh** [jhipster/generator-jhipster#1998] opened 2015-09-11 13:36 UTC
A logged in user (without admin privileges) is able to access resources which should only be accessible by the admin.

This can be reproduced be creating a new project with folowing configuration (Release 2.20.0): 

```javascript
{
  "generator-jhipster": {
    "baseName": "sampleToken",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "authenticationType": "xauth",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "mysql",
    "searchEngine": "no",
    "useSass": false,
    "buildTool": "maven",
    "frontendBuilder": "grunt",
    "javaVersion": "8",
    "enableTranslation": true,
    "rememberMeKey": "6cb68672d37b28f2a9efcfa165e3f70c144e6dab"
  }
}
```

After login with the the default 'user', go to 
  http://127.0.0.1:8080/#/metrics
  
This page is shown although it should be secured by the WebSecurityConfigurerAdapter for admins only
    .antMatchers("/metrics/**").hasAuthority(AuthoritiesConstants.ADMIN)

However this seems to work in the sample app from github:
  https://github.com/jhipster/jhipster-sample-app-token

**Comment by jdubois** [comment] 2015-09-11 13:49
I just tried with the sample application:

- You can't access the page, you are redirected to an error page (this is correct)
- I also checked the API call, you are also redirected to an error page

So everything is correct, and the error messages are also correct.

Sorry but I can't reproduce your issue -> what you say about the sample app isn't clear to me, is it working or not?

I'm closing this as I can't reproduce, of course if you send something that I can reproduce I'll be happy to test it.

**Closed by jdubois** 2015-09-11 13:49 UTC

**Comment by thiloh** [comment] 2015-09-11 15:40
It is all working fine with the sample app from github:
  https://github.com/jhipster/jhipster-sample-app-token

The problems described above occur in a new project created with the current generator (2.20.0) and the settings from above (I tried to match the same settings from the 'jhipster-sample-app-token').
