### ISSUE TITLE
Many to one relationship between entities gives error: TypeError: Cannot read property 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by anshulcoolans880** [jhipster/generator-jhipster#11568] opened 2020-04-10 08:44 UTC
I have created First Entity with name "FirstEntity" with a field "name" of type String and ManyToOne Relationship with User entity. It was created successfully. When I tried creating second entity with name "SecondEntity" with a field "name" of type String and ManyToOne Relationship with "FirstEntity", its failing with this error:

`Everything is configured, generating the entity...

~~~
events.js:288
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'toLowerCase' of undefined
    at Function.plural (C:\Users\anshu\OneDrive\Desktop\tcs work from home\jhipster poc\node_modules\pluralize\pluralize.js:133:24)
    at pluralize (C:\Users\anshu\OneDrive\Desktop\tcs work from home\jhipster poc\node_modules\pluralize\pluralize.js:174:46)
    at C:\Users\anshu\OneDrive\Desktop\tcs work from home\jhipster poc\node_modules\generator-jhipster\generators\entity\index.js:928:74
    at Array.forEach (<anonymous>)
    at EntityGenerator.loadInMemoryData (C:\Users\anshu\OneDrive\Desktop\tcs work from home\jhipster poc\node_modules\generator-jhipster\generators\entity\index.js:877:39)
    at Object.<anonymous> (C:\Users\anshu\OneDrive\Desktop\tcs work from home\jhipster poc\node_modules\yeoman-generator\lib\index.js:546:23)
    at C:\Users\anshu\OneDrive\Desktop\tcs work from home\jhipster poc\node_modules\run-async\index.js:47:25
    at new Promise (<anonymous>)
    at C:\Users\anshu\OneDrive\Desktop\tcs work from home\jhipster poc\node_modules\run-async\index.js:24:19
    at C:\Users\anshu\OneDrive\Desktop\tcs work from home\jhipster poc\node_modules\yeoman-generator\lib\index.js:547:9
Emitted 'error' event on EntityGenerator instance at:
    at Immediate.<anonymous> (C:\Users\anshu\OneDrive\Desktop\tcs work from home\jhipster poc\node_modules\yeoman-generator\lib\index.js:559:18)
    at processImmediate (internal/timers.js:456:21)
    at process.topLevelDomainCallback (domain.js:137:15)`
~~~

I added a console.log on line 928 of node_modules/generator-jhipster/generators/entity/index.js
and following was printed:

~~~
{
  relationshipName: 'firstEntity',
  otherEntityName: 'firstEntity',
  relationshipType: 'many-to-one',
  relationshipValidateRules: undefined,
  otherEntityField: 'id',
  ownerSide: undefined,
  useJPADerivedIdentifier: undefined,
  otherEntityRelationshipName: undefined
}
~~~

I can guess `otherEntityRelationshipName` is undefined because of which it is throwing error. 

##### **JHipster Version(s)**

Jhipster version: 6.7.1

##### **JHipster configuration**
<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp"
    },
    "jhipsterVersion": "6.7.1",
    "applicationType": "monolith",
    "baseName": "jhipster",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "session",
    "cacheProvider": "caffeine",
    "enableHibernateCache": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,

    "embeddableLaunchScript": false,
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "angularX",
    "clientTheme": "cerulean",
    "clientThemeVariant": "primary",
    "creationTimestamp": 1586358157593,
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": false,
    "blueprints": []
  }
}

</pre>
##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

Using command line

##### **Browsers and Operating System**

Windows 10 OS

  [how to check? ] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment] 2020-04-10 12:26
I think it’s fixed on master.

**Comment by anshulcoolans880** [comment] 2020-04-10 12:33
It was not working on 6.8 version either... which is the right version to use?

**Comment by mshima** [comment] 2020-04-10 12:46
You should try `npm install jhipster/generator-jhipster#master` to fix this bug.

After generating the project you probably can downgrade if you want;
```
npm install generator-jhipster@6.8.0
jhipster —with-entities
```

**Comment by mshima** [comment] 2020-04-11 12:59
Closing.
@anshulcoolans880 if you manage to reproduce usint

**Closed** 2020-04-11 12:59 UTC
Labels: area: needs-reproduction, area: waiting for information, theme: relationships

**Comment by MathieuAA** [comment] 2020-04-11 13:50
On a side note, there are `undefined` values in what was logged.
@anshulcoolans880 please follow the issue template, otherwise we won't be able to reproduce the issue and fix it.

**Comment by mshima** [comment] 2020-04-11 14:10
Probably duplicate of https://github.com/jhipster/generator-jhipster/issues/11520

**Comment by MathieuAA** [comment] 2020-04-11 14:34
Yup
