### ISSUE TITLE
Missing dependencies  (spring-tx) when generating microservice without database 

### ISSUE THREAD

**Issue by funder7** [jhipster/generator-jhipster#12916] opened 2020-10-31 10:43 UTC
##### **Overview of the issue**

Generated a microservice without database from JDL.
The `ExceptionTranslator` class has a little part of code which depends on  `org.springframework.dao.DataAccessException` which cannot be found. 

(I'm using Java 14, but that shouldn't affect this in any way. )

##### **Motivation for or Use Case**

I was expecting no errors when disabling the db.

##### **Reproduce the error**

Execute `import-jdl` to generate an application(microservice) having `databaseType no`  option.

##### **Related issues**

None. 

##### **Suggest a Fix**

- Remove
```java
import org.springframework.dao.DataAccessException;
```
- Remove 
```java
            if (throwable instanceof DataAccessException) {
                return Problem.builder()
                    .withType(type)
                    .withTitle(status.getReasonPhrase())
                    .withStatus(status)
                    .withDetail("Failure during data access")
                    .withCause(Optional.ofNullable(throwable.getCause())
                        .filter(cause -> isCausalChainsEnabled())
                        .map(this::toProblem)
                        .orElse(null));
            }
```

- Check Spring autoconfiguration (Datasource classes exclusion)

##### **JHipster Version(s)**

`6.10.4` 

##### **JHipster configuration**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "authenticationType": "oauth2",
    "cacheProvider": "no",
    "serverPort": "8083",
    "serviceDiscoveryType": "eureka",
    "skipUserManagement": true,
    "baseName": "communication",
    "buildTool": "maven",
    "databaseType": "no",
    "devDatabaseType": "no",
    "enableHibernateCache": false,
    "enableSwaggerCodegen": true,
    "enableTranslation": true,
    "jhiPrefix": "pot",
    "languages": ["it", "en", "fr", "de", "pt-pt", "es"],
    "messageBroker": "kafka",
    "nativeLanguage": "it",
    "prodDatabaseType": "no",
    "searchEngine": false,
    "skipClient": true,
    "testFrameworks": ["gatling"],
    "websocket": false,
    "applicationType": "microservice",
    "dtoSuffix": "DTO",
    "packageName": "it.italdev.potpot",
    "packageFolder": "it/italdev/potpot",
    "jhipsterVersion": "6.10.4",
    "creationTimestamp": 1604087280182,
    "clientPackageManager": "npm",
    "embeddableLaunchScript": false,
    "entitySuffix": "",
    "otherModules": [],
    "blueprints": []
  },
  "entities": []
}

</pre>
</details>

##### **Environment and Tools**

java version "14.0.2" 2020-07-14
Java(TM) SE Runtime Environment (build 14.0.2+12-46)
Java HotSpot(TM) 64-Bit Server VM (build 14.0.2+12-46, mixed mode, sharing)

git version 2.17.1

node: v12.18.2

npm: 6.14.8

yeoman: 3.1.1

yarn: 0.32

Docker version 19.03.13, build 4484c46d9d

docker-compose version 1.25.4, build 8d51620a

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

No folder present. 

##### **Browsers and Operating System**

`Linux xxxxxxxxx 5.3.0-53-generic #47~18.04.1-Ubuntu SMP Thu May 7 13:10:50 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by funder7** [comment] 2020-10-31 13:01
I must add that after fixing:
- The application starts correctly if booted from main class, or maven
- It fails to run if booted as docker image returning the following error:

<pre>
2020-10-31 12:32:40.259  WARN 1 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.context.ApplicationContextException: Unable to start web server; nested exception is java.lang.RuntimeException: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'servletEndpointRegistrar' defined in class path resource [org/springframework/boot/actuate/autoconfigure/endpoint/web/ServletEndpointManagementContextConfiguration$WebMvcServletEndpointManagementContextConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.actuate.endpoint.web.ServletEndpointRegistrar]: Factory method 'servletEndpointRegistrar' threw exception; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'healthEndpoint' defined in class path resource [org/springframework/boot/actuate/autoconfigure/health/HealthEndpointConfiguration.class]: Unsatisfied dependency expressed through method 'healthEndpoint' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'healthContributorRegistry' defined in class path resource [org/springframework/boot/actuate/autoconfigure/health/HealthEndpointConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.actuate.health.HealthContributorRegistry]: Factory method 'healthContributorRegistry' threw exception; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.springframework.boot.actuate.autoconfigure.jdbc.DataSourceHealthContributorAutoConfiguration': Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSource' defined in class path resource [org/springframework/boot/autoconfigure/jdbc/DataSourceConfiguration$Hikari.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.zaxxer.hikari.HikariDataSource]: Factory method 'dataSource' threw exception; nested exception is org.springframework.boot.autoconfigure.jdbc.DataSourceProperties$DataSourceBeanCreationException: Failed to determine a suitable driver class
2020-10-31 12:32:40.276 ERROR 1 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   : 

***************************
APPLICATION FAILED TO START
***************************

Description:

Failed to configure a DataSource: 'url' attribute is not specified and no embedded datasource could be configured.

Reason: Failed to determine a suitable driver class


Action:

Consider the following:
	If you want an embedded database (H2, HSQL or Derby), please put it on the classpath.
	If you have database settings to be loaded from a particular profile you may need to activate it (the profiles prod,swagger are currently active).
</pre>

I tried to change the configuration by excluding all autoconfiguration classes that may be related to datasource or HealthEndpointConfiguration, but it didn't work. 
What I don't understand is that it presents only when running from docker image. 

But except for that I would tell that something must be excluded from maven, or the generated pom would contain dependencies making think to spring that it must configure the app with a datasource. 
It's an assumption, I never had an application configured this way, for the moment I will add a db an keep it empty.

**Comment by ruddell** [comment] 2020-10-31 15:07
Duplicate of https://github.com/jhipster/generator-jhipster/issues/12827

Fixed in https://github.com/jhipster/generator-jhipster/pull/12829

**Closed by ruddell** 2020-10-31 15:07 UTC
Labels: area: triage, theme: undefined
