### ISSUE TITLE
When creating an entity that ends in s, two ss are created

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#1895] opened 2015-08-19 05:20 UTC
I created a couple entities with plural names. For example: points and preferences. All the endpoints, some templates and other variables were named pointss and preferencess. This was difficult to fix all over the place. It'd be great if JHipster somehow detected plurals and didn't use two 's'.

On a related note, I have WebSockets in my project and I noticed the following requests being made:

````
GET http://localhost:3000/api/points/new?cacheBuster=1439961344639 400 (Bad Request)
````

When I click to add a new record on my list screen, I see a notification with the following error message:

    Failed to convert value of type 'java.lang.String' to required type 'java.lang.Long'; nested exception 
    is java.lang.NumberFormatException: For input string: "new"

I can see why this is happening - the method mapped to this expects a long.

````java
    /**
     * GET  /points/:id -> get the "id" points.
     */
    @RequestMapping(value = "/points/{id}",
            method = RequestMethod.GET,
            produces = MediaType.APPLICATION_JSON_VALUE)
    @Timed
    public ResponseEntity<Points> get(@PathVariable Long id) {
````

Any ideas how to fix this?

**Comment by gmarziou** [comment] 2015-08-19 12:27
Plural in which language? ;)

**Comment by deepu105** [comment] 2015-08-19 15:02
Ya its a tough issue unless we add some specific library to handle that.
Another case is when you use names like country it creates countrys :P i
guess there are many such variations

**Comment by mraible** [comment] 2015-08-19 15:08
In AppFuse, we use a StringUtils class that gets the plural for the word:

https://github.com/appfuse/appfuse/blob/master/plugins/appfuse-maven-plugin/src/main/java/org/appfuse/tool/StringUtils.java

Any idea how to get past /points/new creating an alert? This seems like a bug.

**Comment by gzsombor** [comment] 2015-08-19 15:13
In the javascript router config, you should put '/something/{id:int}'  instead of '/something/:id'.

The problem is that sometimes ui-router first picks /something/:id, when it doesn't know that id should be a number.

**Comment by mraible** [comment] 2015-08-19 15:21
That worked @gzsombor! Thanks for the tip.

**Comment by Vaelyr** [comment] 2015-08-21 23:14
https://www.npmjs.com/package/pluralize

This one works, would require to add a variable into template I assume and replace entity name usage locations where it is required.

**Comment by gmarziou** [comment] 2015-08-22 11:58
I suppose it does work only for English.

**Comment by Vaelyr** [comment] 2015-08-22 11:59
I personally consider API-s or code written in any other language than English very rigid.

**Comment by gmarziou** [comment] 2015-08-22 12:08
Customer decides.

**Comment by Vaelyr** [comment] 2015-08-22 12:09
Developer shouldn't agree and should say no ;)

**Comment by gmarziou** [comment] 2015-08-22 13:26
:smile:

**Comment by deepu105** [comment] 2015-08-22 15:16
Ok never knew you could actually write code in non latin?

**Comment by mraible** [comment] 2015-08-22 19:29
I discovered another bug related to this today. The double 's' does not cause a problem in functionality, but it does cause an issue with variable names in the list screen controller. In particular, the "list" of entities is named the plural version, as is the entity that gets passed to the edit dialog. There's some variable name collision that takes place when editing, but it rears its ugly head more when deleting. To fix this, I added a "List" suffix to my variables in controllers. For example, `$scope.pointsList` and $scope.preferencesList`. I also renamed the variable in `ng-repeat` in the HTML template.

**Comment by jdubois** [comment] 2015-09-06 16:46
OK I understand this related issue -> I need to test this but to me that's even more annoying than the first issue.

For pluralization we already use https://github.com/SlexAxton/messageformat.js/ so my idea is to do something similar to what Rails has, and handle pluralization in several languages.

Then that's a lot of work, and I'm not sure it's worth all the effort, when we only have one REST endpoint with an "s" per entity, and that it's really easy to rename it manually.

**Comment by deepu105** [comment] 2015-09-07 00:28
Guys I still dont understand why it needs to be handled in several
languages wouldn't English alone suffice as that is accepted as the
universal programming language?  And as far as I know jhipster, spring and
angular doesn't support coding in any other language? ?  Atleast I havent
seen it

**Comment by gzsombor** [comment] 2015-09-07 13:39
No, please, no more English specific band aid. There is 2 very simple solution for this:
 1, Always use the non-plural name, in the table, in the stage names, etc, so no grammar nazis would fight over the problem with the plurals of 'news', 'octopus', 'jeans', 'trousers', etc ...
 2, Ask the user about the plural form, so any irregularities (and the 6 billion people who not speak a single word of English) could be handled correctly.

**Comment by deepu105** [comment] 2015-09-07 14:48
Ha ha Zsombor, Im not evangelizing english, its not my mother tongue
either  :) but since we are stuck with english for almost everything
related to programming I suggested that. Anyways your idea seems good +1

**Comment by jdubois** [comment] 2015-09-20 07:25
- As @gzsombor wrote, yes we should always the non-plural form in table names, etc.
- I did a little digging, and the plural form appears 46 times in the application, mostly on the client side (but also on tests, etc).
- As long as we use it internally, we could do like @mraible and add a suffix -> for "Foo" we would use something like "Foo-List". I would add a "-" as with "List" we could have the same issue as we have today with an "s" -> but for the REST endpoint, I'm sure people will want to have the plural form, and that will end up being annoying
- I wanted to do like Rails, have a look at inflections.rb where they do pluralization... It's a bit like what @mraible did for AppFuse. And in JavaScript, we already use [MessageFormat.js](https://github.com/SlexAxton/messageformat.js/) which would do this job (note to self: why the hell do we already use it???)

My proposal is:
- Let's have a try with MessageFormat.js -> it would solve a lot of hassle
- If not, let's ask for the plural format as @gzsombor said -> that would make one more question, which I really don't like (I feel it's already far too complex), but at least it would work

Anyway, this plural form should be stored in the .jhipster file, and so should be able to be modified easily afterwards -> just change the config file and re-run the sub-generator

**Comment by deepu105** [comment] 2016-01-18 05:10
@jhipster/developers why dont we just use https://www.npmjs.com/package/pluralize in the generator and generate correct forms during entity creation??

**Comment by jdubois** [comment] 2016-01-18 09:37
Thanks @deepu105 , yes this has been opened for too long:

- I still have no idea what we do with MessageFormat.js , I didn't have the time to check
- It's clear that Pluralize will do the trick, and it's very popular, so let's use it
- And we need to store the plural form in our .json conf file, so it can be modified if needed -> in the future, we could also provide this as an "advanced" option in the generators questions, then I see everyone using this kind of thing with RoR and everybody seems happy with it, so let's do this later or we will never have finished with this ticket

**Comment by deepu105** [comment] 2016-01-18 09:52
I think message format is used in angular js side for i18n are we using the
npm module anywhere?

Thanks & Regards,
Deepu

**Comment by deepu105** [comment] 2016-01-28 10:30
let me see if i can do this

**Comment by tapas4java** [comment] 2016-01-28 11:39
I also observed if the entity name is 'Category' it is pluralising as
'Categorys'. This will be also fixed once we fix this issue.

**Closed** 2016-01-28 22:13 UTC
Labels: enhancement
