### ISSUE TITLE
TypeError: Cannot read property 'name' of undefined at moduleResponse.results.forEach

### ISSUE THREAD

**Issue by egorlitvinenko** [jhipster/generator-jhipster#5560] opened 2017-04-08 09:49 UTC
##### **Overview of the issue**

```
? (3/15) Would you like to install other generators from the JHipster Marketplace? Yes
/home/jhipster/generator-jhipster/generators/app/prompts.js:146
                name: `(${modDef.package.name}-${modDef.package.version}) ${modDef.package.description} [${modDef.package.author.name}]`
                                                                                                                                ^
TypeError: Cannot read property 'name' of undefined
    at moduleResponse.results.forEach (/home/jhipster/generator-jhipster/generators/app/prompts.js:146:129)
    at Array.forEach (native)
    at generator.httpsGet (/home/jhipster/generator-jhipster/generators/app/prompts.js:143:32)
    at IncomingMessage.res.on (/home/jhipster/generator-jhipster/generators/generator-base.js:1994:17)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

##### **Motivation for or Use Case**

It doesn't work...

##### **Reproduce the error**

It's docker image, I ran it with command:

> docker run --name jhipster -v ~/app:/home/jhipster/app -v ~/.m2:/home/jhipster/.m2 -p 8081:8082 -p 9001:9000 -p 3002:3001 -d -t jhipster/jhipster

The same error for both types of applications: monolithic and microservice.

##### **Related issues**

I didn't find any.

##### **JHipster Version(s)**

```
yo jhipster:info
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
/home/jhipster/app
`-- (empty)

```

cat: no such file or directory: .yo-rc.json

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml

```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

ls: no such file or directory: .jhipster/*.json

##### **Browsers and Operating System**

~~~
openjdk version "1.8.0_121"
OpenJDK Runtime Environment (build 1.8.0_121-8u121-b13-0ubuntu1.16.04.2-b13)
OpenJDK 64-Bit Server VM (build 25.121-b13, mixed mode)

git version 2.7.4

node: v6.10.2

npm: 4.4.4

bower: 1.8.0

gulp:
[09:44:14] CLI version 1.2.2

yeoman: 1.8.5

yarn: 0.21.3

jhipster@7dbea7878c0a:~/app$ 

~~~

##### **JHipster configuration**

I don't have this file, because it happens before application generation.

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

I don't have entities.
I don't have this file, because it happens before application generation.

##### **Browsers and Operating System**

I use your docker image. The question about browser is not appropriate, because it happens before application generation.
Docker version 1.12.2, build bb80604, host OS - Ubuntu 14.04

- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by gmarziou** [comment] 2017-04-08 11:09
Looks like a connectivity issue while fetching module list from npm registry.

**Comment by egorlitvinenko** [comment] 2017-04-08 11:15
It happens stably on this. I skipped this step and application was generated successfully.

**Comment by gmarziou** [comment] 2017-04-08 13:21
Well, I don't exepct their REST API to be served by same hosts than the node modules.

**Comment by jdubois** [comment] 2017-04-08 13:31
It depends on your JHipster version, I remember correcting this some time ago.
As you don't give your version number I'm closing this.

**Closed by jdubois** 2017-04-08 13:31 UTC

**Comment by gmarziou** [comment] 2017-04-09 11:11
Duplicate of #5563

**Comment by egorlitvinenko** [comment] 2017-04-12 14:13
@jdubois 4.2.0
