### ISSUE TITLE
Unable to start jhipster project on digitalocean cloud.

### ISSUE THREAD

**Issue by ivanursul** [jhipster/generator-jhipster#1425] opened 2015-04-30 14:09 UTC
When I try to deploy my application using 
mvn spring-boot:run 
I got
[DEBUG] com.kb.config.WebConfigurer - Registering Metrics Servlet
[INFO] com.kb.config.WebConfigurer - Web application fully configured

It's the last row that I can receive, and after that, process stucks.
Who knows what can be the problem ?

**Comment by johnyUA** [comment] 2015-04-30 14:15
My assumption is that this is -Djava.security.egd paremeter fault.

**Comment by johnyUA** [comment] 2015-04-30 14:17
Could someone tell me how to pass parameters to embedded tomcat ?

**Comment by drissamri** [comment] 2015-04-30 16:13
You can do this by passing it on the commandline with --parameter.property=value

http://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html#boot-features-external-config-command-line-args

**Comment by johnyUA** [comment] 2015-04-30 17:13
I found the solution - you need to pass /dev/urandom as a value 

Djava.security.egd=file:/dev/./urandom


            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <jvmArguments>-Djava.rmi.server.hostname=localhost -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5005 -Djava.security.egd=file:/dev/./urandom</jvmArguments>
                    <arguments>
                        <argument>--spring.profiles.active=dev</argument>
                    </arguments>
                </configuration>
            </plugin>

**Comment by jdubois** [comment] 2015-05-03 15:09
This looks quite specific to DigitalOcean, do you think we should have a documentation page for this?
I'm closing this as the issue is solved, but if you want to contribute something like http://jhipster.github.io/cloudfoundry.html you could propose a PR [here](https://github.com/jhipster/jhipster.github.io)

**Closed by jdubois** 2015-05-03 15:09 UTC

**Comment by ivanursul** [comment] 2015-05-04 00:39
I think, that you should add this additional parameter to spring-boot-maven-plugin.
This will avoid this issue on digitalocean.
Or just write a documentation for this, or, I can handle this.
Thanks.

**Comment by maxleiko** [comment] 2016-10-27 12:54
Sorry for the revival, but it's the same for ScaleWay C1 (arm arch) with a Debian Jessie.  
The solution for the application not to hang, was to specify `-Djava.security.egd=file:/dev/urandom`

**Comment by ivanursul** [comment] 2016-10-27 12:56
I know, thanks.

**Comment by m2ger** [comment] 2016-11-12 11:48
Thanks, the same helped in vultr with Debian Jessie as well.
It had worked though in the same server without this parameter for the last 10+ months.

**Comment by MilanMaric** [comment] 2018-01-05 23:23
I know this issue is closed for a long time now, but I had a similar issue on Digital Ocean, and the google led me to this issue.

The -Djava.security.egd value wasn't helpful. in this case.

In my case the liquibase has locked the database to start with async migrations, and set the 'LOCKED' value in DATABASECHANGELOG. Since application has stopped for some irrelevant reasons before it has finished, database was locked.

After setting it to 0 manually everything worked fine.

```
DATABASECHANGELOGLOCK` SET `LOCKED`='0' WHERE `ID`='1';
```

**Comment by datnguyen293** [comment] 2022-07-26 07:13
> 

It's worth a million thanks. JHipster should show some message to tell the liquibase is locking the database.
