### ISSUE TITLE
EntityResourceIntTest Failures with Required Relationships

### ISSUE THREAD

**Issue by ruddell** [jhipster/generator-jhipster#3769] opened 2016-06-24 20:21 UTC
##### **Overview of the issue**
There are out-of-the-box test failures when generating entities with required relationships.

##### **Motivation for or Use Case** 
Tests should not fail on a fresh generated project.

##### **JHipster Version(s)** 
Master, 3.2.0+ (required relationships added)

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 
```
{
  "generator-jhipster": {
    "jhipsterVersion": "3.4.2",
    "baseName": "test",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": "no",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "rememberMeKey": "8c073c30fd56d34230694bc40fb1ec253d47c7d7",
    "useSass": false,
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ]
  }
}
```
##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory** 
Foo
```
{
    "relationships": [
        {
            "relationshipName": "foo",
            "otherEntityName": "foo",
            "relationshipType": "one-to-many",
            "otherEntityRelationshipName": "bar"
        }
    ],
    "fields": [
        {
            "fieldName": "name",
            "fieldType": "String"
        }
    ],
    "changelogDate": "20160624065546",
    "dto": "mapstruct",
    "service": "serviceClass",
    "entityTableName": "bar",
    "pagination": "pagination"
}
```
Bar
```
{
    "relationships": [
        {
            "relationshipName": "bar",
            "otherEntityName": "bar",
            "relationshipType": "many-to-one",
            "relationshipValidateRules": [
                "required"
            ],
            "otherEntityField": "name"
        }
    ],
    "fields": [
        {
            "fieldName": "name",
            "fieldType": "String"
        }
    ],
    "changelogDate": "20160624065503",
    "dto": "mapstruct",
    "service": "serviceClass",
    "entityTableName": "foo",
    "pagination": "pagination"
}
```

##### **Reproduce the error** 
Generate the above entities (or any with a required relationship) and run `mvn test`
##### **Related issues** 
#1843 - talks about string length and regex validation.  There is a note about validation failing is documented in the Validation section https://jhipster.github.io/creating-an-entity/:

> JHipster generates unit tests that work for generic entities, without knowing your validation rules: it is possible that the generated tests do not pass the validation rules. In that case, you will need to update the sample values used in your unit tests, so that they pass the validation rules.

##### **Suggest a Fix** 
Since a `Bar` entity is required to create/update a `Foo` entity, I was able to get FooResouceIntTest.java working by creating a `Bar` in `setup()`, then adding it to the `initTest()` and `updateFoo()` tests.  I also needed to inject `BarMapper` and `BarService`.

The other option would be to close this issue and point at the documentation, though fixing the tests requires more work than just updating the sample values.

**Comment by cbornet** [comment] 2016-06-25 12:16
It would be easy to fix for one level of dependency bit what if entity A requires B, B requires C, C requires D, ... ?

**Comment by deepu105** [comment] 2016-06-26 02:35
Ya damn thata gonna be difficult. May be we can try to do for one level and add documentation to ask user to correct if there are nested validations

**Comment by cbornet** [comment] 2016-06-26 14:53
The solution could be to use liquibase to create an instance of each entity with a defined ID. What do you think ?

**Comment by deepu105** [comment] 2016-06-26 16:18
Ya we could try that

Thanks & regards,
Deepu

**Comment by evelknievel** [comment] 2016-07-07 15:05
I think it would be nice to have a tool which can setup your database before each integration test. For example DB Unit is an option?

**Comment by jdubois** [comment] 2016-08-05 15:47
You need to have managed entities, so creating them with Liquibase won't help a lot.

Those are like "normal" properties, they should be provided when the object is created. They should be created a the beginning of the test, and they need to be flushed to the database: you need to inject the relationship's repository.

So that's quite a lot of changes, but that should be doable in pure Java.

**Comment by evelknievel** [comment] 2016-08-05 16:13
The problem is you need to build the whole tree of entities. When a relationship is required, and that relationship has another relationship that is required, you need to inject a lot of repositories. DB unit or liquibase can help with this. Then you only have to perform one find on the main entity to load it into the entitymanager.

**Comment by jdubois** [comment] 2016-08-08 09:11
You are right @evelknievel - I'll have another look now

**Comment by jdubois** [comment] 2016-08-08 14:30
This is in fact quite hard: using Liquibase doesn't really solve the graph issue, and then the IDs are supposed to be generated by Hibernate, so this needs another trick.

I think I can solve this in Java, and it wouldn't be too bad, I'm trying this now.

**Comment by jdubois** [comment] 2016-08-08 16:02
I'm not totally satisfied with it, and it requires a lot of testing (I just did a simple relationship for the moment), but I've pushed my idea in this commit: https://github.com/jhipster/generator-jhipster/commit/14e9b339eaa34b1435fa725183f01b0a8851ebae

**Comment by cbornet** [comment] 2016-08-08 17:21
Won't liquibase use hibernate ?

**Comment by jdubois** [comment] 2016-08-08 19:15
I don't think it does, for generating the PK from a CSV file.
The issue, anyway, is that the PKs are auto-generated, so it's annoying, as
you need to know the PKs.

Le 8 août 2016 7:21 PM, "Christophe Bornet" <notifications@github.com> a
écrit :

**Comment by cbornet** [comment] 2016-08-08 19:37
Indeed...

**Comment by cbornet** [comment] 2016-08-08 19:41
Is it an issue for hibernate if rows from different table have the same known id ?

**Comment by evelknievel** [comment] 2016-08-08 19:49
You dont have to let hibernate generate the id. You can insert it manually and then use it in other tables.

**Comment by jdubois** [comment] 2016-08-09 09:14
Yes you can insert it manually, but then you need to be careful that it won't be used by Hibernate afterwards... I usually take a very high number.

I've done more tests with my commit, and it works really well. I also like that it's quite simple, and doesn't change much on what currently works.

For the record, I tested a many-to-many and many-to-one required relationship, as well as a graph of two required relationships.

I'm going to clean it up, and merge it.

**Comment by cbornet** [comment] 2016-08-09 10:16
I think the hibernate sequence starts at 1000 so you can use ids lower than that. Eg. 100.

**Comment by jdubois** [comment] 2016-08-09 11:15
@cbornet it's starting with 1 -> we use the "new" hi/lo generator, and I'm guessing you're familiar with the old one (and with our config, the old one would have started at 100 if my memory is good)

**Comment by jdubois** [comment] 2016-08-09 11:59
Closing as I merged my commits

**Closed by jdubois** 2016-08-09 11:59 UTC
Labels: bug
