### ISSUE TITLE
$state is not defined. Error on entity page generated by jhipster version 4

### ISSUE THREAD

**Issue by hjgomez1975** [jhipster/generator-jhipster#5284] opened 2017-02-22 14:07 UTC
When I try to change page using pagination bar in an entity generated by Jhipster, get the following **javascript error**: **$state is not defined**

Can you solve this issue for the next release?

##### **Reproduce the error**

I am evaluating the JHipster version 4.0.5 framework with angularJS version 1 to clientFramework. All entities were generated through the command jhipster:entity entity-name using pagination option.

The problem is on the entitycontroller.js generated 'state' variable is missing on the controller injection. e.g.

` EntityController.$inject = ['Entity', 'ParseLinks', 'AlertService', 'paginationConstants','$state']`

##### **Suggest a Fix**

You have to modify **_entity-management.controller.js**

This file is located on the directory: ../node_modules/generator-jhipster/generators/entity/templates/client/angularjs/src/main/webapp/app/entities/_entity-management.controller.js

You need to add $state variable on the $inject and function code. Here you have, the changed code for jhipster 4.0.5 release:

```

(function() {
    'use strict';

    angular
        .module('<%=angularAppName%>')
        .controller('<%= entityAngularName %>Controller', <%= entityAngularName %>Controller);

    <%= entityAngularName %>Controller.$inject = [<% if (fieldsContainBlob) { %>'DataUtils', <% } %>'<%= entityClass %>'<% if (searchEngine == 'elasticsearch') { %>, '<%= entityClass %>Search'<% } %><% if (pagination != 'no') { %>, 'ParseLinks', 'AlertService', 'paginationConstants', '$state'<% } %> <%_ if (pagination == 'pager' || pagination == 'pagination'){ %>, 'pagingParams'<% } %>];

    function <%= entityAngularName %>Controller(<% if (fieldsContainBlob) { %>DataUtils, <% } %><%= entityClass %><% if (searchEngine == 'elasticsearch') { %>, <%= entityClass %>Search<% } %><% if (pagination != 'no') { %>, ParseLinks, AlertService, paginationConstants, $state<% } %> <%_ if (pagination == 'pager' || pagination == 'pagination'){ %>, pagingParams<% } %>) {

        var vm = this;

        <%_ if (pagination == 'pagination' || pagination == 'pager') { _%>
<%- include('pagination-template'); -%>
        <%_ } else if (pagination == 'infinite-scroll') { _%>
<%- include('infinite-scroll-template'); -%>
        <%_ } else { _%>
<%- include('no-pagination-template'); -%>
        <%_ } _%>
    }
})();

```
##### **JHipster Version(s)** 
```
{
  "generator-jhipster": {
    "jhipsterVersion": "4.0.5",
    "baseName": "test",
    "packageName": "com.test",
    "packageFolder": "com/test",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "jwtSecretKey": "f06bf47624fbee1bfaa264ddcf50f7c9145d3edc",
    "clientFramework": "angular1",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "es",
    "languages": [
      "es",
      "gl"
    ]
  }
}

```

**Comment by jdubois** [comment] 2017-02-23 10:19
I'm sorry but I can't reproduce if you don't give me your entities....

**Comment by jdubois** [comment] 2017-02-23 10:19
This ticket has been closed as the guidelines are not followed.

Tickets must follow our [Guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#submitting-an-issue), as mentioned in:

1. our [Readme file on the front page of the project](https://github.com/jhipster/generator-jhipster/blob/master/README.md), 
2. the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) and
3. our [Help page](http://jhipster.github.io/help/)

We have also created a template on the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) to help you follow those guidelines.

**Closed by jdubois** 2017-02-23 10:19 UTC
