### ISSUE TITLE
entity post hook is not getting triggered with import-jdl jhipster command

### ISSUE THREAD

**Issue by CarreraPHP** [jhipster/generator-jhipster#6475] opened 2017-10-05 12:32 UTC
##### **Overview of the issue**

I have create a JHipster module generator by choosing the entity post hook option. The hook is working fine when i execute ```jhipster entity ENTITY_NAME``` but its not getting triggered when i do a ```jhipster import-jdl PATH_TO_JDL_FILE```

##### **Motivation for or Use Case**

To develop a JHipster Module, that consists of Modified Template files for Angular Entity Client code. This will provide additional functionality on top of the basic CRUD currently supported. The JHipster Module should run whenever ```jhipster entity``` or ```jhipster import-jdl``` is called.

##### **Reproduce the error**

- generate an JHipster module using ```generator-jhipster-module```, enable Entity Post Hook in options.
- run ```yarn link```
- generate an Project using JHipster.
- run ```yarn link generator-jhipster-modulename```
- run ```jhipster entity ENTITY_NAME```, the entity hook is triggered and the default ```dummy.txt``` file is created in the project folder.
- run ```jhipster import-jdl PATH_TO_JDL_FILE```, the entity hook is not triggered.

##### **Related issues**

NA

##### **Suggest a Fix**

Yet to Analysis on a workaround.

##### **JHipster Version(s)**

```
mock-project-2@0.0.0 D:\Yogesh\workspace\JHipster\MockProject2
+-- generator-jhipster@4.9.0  -> D:\Yogesh\git\generator-jhipster
`-- UNMET PEER DEPENDENCY popper.js@^1.11.0

```

##### **JHipster configuration**

```
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "4.9.0",
    "baseName": "MockProject2",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": true,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "hi",
      "es",
      "ta"
    ]
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

```
entity Country (m_country) {
  ctryCd String maxlength(10) minlength(2),
  ctryName String maxlength(10) minlength(2),
  createdBy String required,
  createdDate ZonedDateTime required,
  approvedBy String,
  approvedDate ZonedDateTime
}
entity State (state) {
  stateCd String
}

dto Country with mapstruct
paginate Country with pagination
service Country with serviceImpl

```

##### **Browsers and Operating System**

Windows 10 64bit operating system, All Browsers
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

git version 2.14.2.windows.1

node: v6.11.3

npm: 3.10.10

yeoman: 2.0.0

yarn: 1.1.0

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by deepu105** [comment] 2017-10-11 15:08
can you run the command with`--debug` flag and see if there is any useful debug info?

**Comment by deepu105** [comment] 2017-10-28 16:29
@CarreraPHP were you able to run with `--debug` flag?

**Comment by deepu105** [comment] 2017-10-28 17:19
I'm unable to reproduce this. Make sure you had change in entities when you regenerated otherwise entity generator will not run anyway. I'm closing as I couldnt reproduce. If you have more info from running debug please ask to reopen.

**Closed by deepu105** 2017-10-28 17:19 UTC
Labels: module, waiting for information
