### ISSUE TITLE
Hazelcast.cluster.impl warning when deploy on Tomcat8

### ISSUE THREAD

**Issue by fontanellif** [jhipster/generator-jhipster#1361] opened 2015-04-09 12:31 UTC
Hi, i'm trying set up the continuous integration architecture, but when jenkins deploy a simple jhipster project 

```json 
{
  "generator-jhipster": {
    "baseName": "awhy_server",
    "packageName": "it.xxx.xxx_server",
    "packageFolder": "it.xxx.xxx_server",
    "authenticationType": "oauth2",
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": "hazelcast",
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "mysql",
    "useCompass": false,
    "buildTool": "maven",
    "frontendBuilder": "grunt",
    "javaVersion": "8",
    "rememberMeKey": "a1b1b3b94e08955ba80b20f32501370618591e27"
  }
}
```

on tomcat 8, in the catalina.out log i get this warning:

```
09-Apr-2015 12:27:32.770 INFO [hz._hzInstance_1_dev.MulticastThread] org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading Illegal access: this web application instance has been stopped already. Could not load [com.hazelcast.cluster.impl.JoinRequest]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
 java.lang.IllegalStateException: Illegal access: this web application instance has been stopped already. Could not load [com.hazelcast.cluster.impl.JoinRequest]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
	at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading(WebappClassLoaderBase.java:1327)
	at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForClassLoading(WebappClassLoaderBase.java:1313)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1196)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1157)
	at com.hazelcast.nio.ClassLoaderUtil.tryLoadClass(ClassLoaderUtil.java:124)
	at com.hazelcast.nio.ClassLoaderUtil.loadClass(ClassLoaderUtil.java:97)
	at com.hazelcast.nio.ClassLoaderUtil.newInstance(ClassLoaderUtil.java:66)
	at com.hazelcast.nio.serialization.DataSerializer.read(DataSerializer.java:109)
	at com.hazelcast.nio.serialization.DataSerializer.read(DataSerializer.java:39)
	at com.hazelcast.nio.serialization.StreamSerializerAdapter.read(StreamSerializerAdapter.java:44)
	at com.hazelcast.nio.serialization.SerializationServiceImpl.readObject(SerializationServiceImpl.java:309)
	at com.hazelcast.nio.serialization.ByteArrayObjectDataInput.readObject(ByteArrayObjectDataInput.java:439)
	at com.hazelcast.cluster.impl.MulticastService.receive(MulticastService.java:155)
	at com.hazelcast.cluster.impl.MulticastService.run(MulticastService.java:113)
	at java.lang.Thread.run(Thread.java:745)

09-Apr-2015 12:28:15.137 INFO [hz._hzInstance_1_dev.cached.thread-3] org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading Illegal access: this web application instance has been stopped already. Could not load [com.hazelcast.cluster.impl.MulticastJoiner$1]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
 java.lang.IllegalStateException: Illegal access: this web application instance has been stopped already. Could not load [com.hazelcast.cluster.impl.MulticastJoiner$1]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
	at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading(WebappClassLoaderBase.java:1327)
	at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForClassLoading(WebappClassLoaderBase.java:1313)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1196)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1157)
	at com.hazelcast.cluster.impl.MulticastJoiner.searchForOtherClusters(MulticastJoiner.java:101)
	at com.hazelcast.cluster.impl.SplitBrainHandler.searchForOtherClusters(SplitBrainHandler.java:48)
	at com.hazelcast.cluster.impl.SplitBrainHandler.run(SplitBrainHandler.java:38)
	at com.hazelcast.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:209)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:92)

Exception in thread "hz._hzInstance_1_dev.cached.thread-3" java.lang.IllegalStateException: Can't overwrite cause with java.lang.IllegalStateException: Illegal access: this web application instance has been stopped already. Could not load [com.hazelcast.cluster.impl.MulticastJoiner$1]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
	at java.lang.Throwable.initCause(Throwable.java:457)
	at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForClassLoading(WebappClassLoaderBase.java:1316)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1196)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1157)
	at com.hazelcast.cluster.impl.MulticastJoiner.searchForOtherClusters(MulticastJoiner.java:101)
	at com.hazelcast.cluster.impl.SplitBrainHandler.searchForOtherClusters(SplitBrainHandler.java:48)
	at com.hazelcast.cluster.impl.SplitBrainHandler.run(SplitBrainHandler.java:38)
	at com.hazelcast.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:209)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:92)
Caused by: java.lang.ClassNotFoundException
	at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForClassLoading(WebappClassLoaderBase.java:1315)
	... 11 more
09-Apr-2015 12:28:34.537 INFO [hz._hzInstance_1_dev.scheduled] org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading Illegal access: this web application instance has been stopped already. Could not load [com.hazelcast.util.executor.CachedExecutorServiceDelegate$1]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
 java.lang.IllegalStateException: Illegal access: this web application instance has been stopped already. Could not load [com.hazelcast.util.executor.CachedExecutorServiceDelegate$1]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
	at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading(WebappClassLoaderBase.java:1327)
	at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForClassLoading(WebappClassLoaderBase.java:1313)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1196)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1157)
	at com.hazelcast.util.executor.CachedExecutorServiceDelegate$Worker.<init>(CachedExecutorServiceDelegate.java:200)
	at com.hazelcast.util.executor.CachedExecutorServiceDelegate.addNewWorkerIfRequired(CachedExecutorServiceDelegate.java:136)
	at com.hazelcast.util.executor.CachedExecutorServiceDelegate.execute(CachedExecutorServiceDelegate.java:106)
	at com.hazelcast.spi.impl.ExecutionServiceImpl$ScheduledTaskRunner.run(ExecutionServiceImpl.java:548)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:92)
```

**Comment by jdubois** [comment] 2015-04-09 13:37
Looks like an error when the server is killed, how do you stop your server?
Did you ask this question to Hazelcast? We just wrap it, but if it fails we are not the right project to fix it.

**Comment by jdubois** [comment] 2015-05-07 13:38
I'm closing this as I can't reproduce the issue.

You should check with Hazelcast support, it looks like an issue on their side.

**Closed by jdubois** 2015-05-07 13:38 UTC

**Comment by RoshanGerard** [comment] 2021-02-18 17:25
You have to shutdown the hazelcast instances prior to servlet context destroyed

public class HazelCastContextListener  implements ServletContextListener {

    public void contextInitialized(ServletContextEvent servletContextEvent) { }
	
	public void contextDestroyed(ServletContextEvent servletContextEvent) {
	   myHazelcastInstance.getLifecycleService().shutdown();
	}
}

define this listener in web.xml file
<listener>
    <listener-class>com.srg.common.ContextListener</listener-class>
</listener>

**Comment by RoshanGerard** [comment] 2021-02-18 17:30
You have to shutdown the hazelcast instances prior to servlet context destroyed

public class HazelCastContextListener  implements ServletContextListener {

	@Override
	public void contextInitialized(ServletContextEvent servletContextEvent) { }
	
	@Override
	public void contextDestroyed(ServletContextEvent servletContextEvent) {
		myHazelcastInstance.getLifecycleService().shutdown();
	}
}

<listener>
    <listener-class>com.srg.common.ContextListener</listener-class>
</listener>
