### ISSUE TITLE
Account Management should be optional if selecting OIDC Authentication

### ISSUE THREAD

**Issue by alexander-redmann-teaching** [jhipster/generator-jhipster#8359] opened 2018-09-18 07:01 UTC
##### **Overview of the feature request**

If selecting an application with OIDC authentication support, the user should be ask if he want that the user and accountmanagement stuff should be generated.

##### **Motivation for or Use Case**

The big advantage of the OIDC protocoll is that the whole user information is stored inside the token and their is no need to store this information local inside an database. Also is the whole user management stuff already in your identity and access managament provider like Okta or Keycloak.

For me it is very easy to activate full Keycloak support inside the generated code, but it is very hard to remove the user management stuff, especially if the client side code generation is activated

Greetings,
Alex

**Comment by mraible** [comment] 2018-09-18 10:36
If you select OAuth 2.0 / OIDC as your authentication mechanism, user management is skipped. Are you saying you'd like it added back in? I'm not sure what the issue is here. Are you reporting a bug? If so, what is it?

**Comment by alexander-redmann-teaching** [comment] 2018-09-18 11:01
If i generate a monolithic or gateway app with jhipster with OIDC a domain object User and Authority and all belonging classes and services to manage these are generated. I think this should be optional if you decide to manage the user in your own provider and not inside the application.

**Comment by mraible** [comment] 2018-09-18 12:15
This is because we have a User synchronization feature that copies the user’s data to the database when you first login. This allows you to create relationships with the User entity. The user is read only and there’s no UI to modify it.

How would you propose we refactor things and retain the ability to create relationships with a User?

**Comment by alexander-redmann-teaching** [comment] 2018-09-18 12:31
Ask on creation of the project if the creator is interested on the user entities or not. I think some projects doesn't need this feature.

**Comment by mraible** [comment] 2018-09-18 12:58
This is JHipster's issue tracker and we prefer to use it to report bugs, not handle requests for enhancements. The best way to continue is to:

1. Edit this issue and provide the reasons why this is a bug for you (and your project's information).
2. Close this issue, make the changes required to implement this feature, and create a pull request. 

If you decide to implement this feature, I'd recommend adding something to the entity generator so it fails when you try to create a relationship with `User`. Before the user synching feature existed, entities would generate without errors, but compilation would fail.

**Closed** 2018-09-19 10:55 UTC
