### ISSUE TITLE
Npm install errors microfrontend sample

### ISSUE THREAD

**Issue by amirensit** [jhipster/generator-jhipster#23073] opened 2023-08-06 09:21 UTC
##### **Overview of the issue**
I am following this blog example [micro-frontends-for-java-microservices](https://auth0.com/blog/micro-frontends-for-java-microservices/) windows terminal**, npm install finishes with errors for microfrontend example. **Using intellij ultimate,** it works

##### **Reproduce the error**
I installed current last version of jhipster, downloaded the jdl file, then run ` jhipster jdl reactive-mf.jdl --client-framework angularX --monorepository --workspaces
--client-framework angular`
From root folder, running npm install returns this error:
```
npm ERR! code ERR_SOCKET_TIMEOUT
npm ERR! network Socket timeout
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\amire\AppData\Local\npm-cache\_logs\2023-08-06T09_01_28_086Z-debug-0.log
ERROR! ERROR! Command failed with exit code 1: npm install
Error: Command failed with exit code 1: npm install
    at makeError (file:///C:/Users/amire/AppData/Roaming/npm/node_modules/generator-jhipster/node_modules/execa/lib/error.js:59:11)
    at handlePromise (file:///C:/Users/amire/AppData/Roaming/npm/node_modules/generator-jhipster/node_modules/execa/index.js:124:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async execPackageManager (file:///C:/Users/amire/AppData/Roaming/npm/node_modules/generator-jhipster/node_modules/yeoman-environment/dist/package-manager.js:68:9)
    at async queueTask.once (file:///C:/Users/amire/AppData/Roaming/npm/node_modules/generator-jhipster/node_modules/yeoman-environment/dist/environment-base.js:601:13)
    at async runLoop.add.once (file:///C:/Users/amire/AppData/Roaming/npm/node_modules/generator-jhipster/node_modules/yeoman-environment/dist/environment-base.js:383:17) {
  shortMessage: 'Command failed with exit code 1: npm install',
  command: 'npm install',
  escapedCommand: 'npm install',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: undefined,
  stderr: undefined,
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
```

##### **JHipster Version(s)**
8.0.0-beta.2

##### **JHipster configuration**
[mf-jdl-file](https://github.com/jhipster/jdl-samples/blob/v8/reactive-mf.jdl)

##### **Browsers and Operating System**

- [ v] Checking this box is mandatory (this is just to show you read everything)

**Comment by amirensit** [comment] 2023-08-06 11:18
now I get this error with `./gradlew`
```
\gateway\src\main\webapp\main.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
```

**Comment by mshima** [comment] 2023-08-09 17:01
The first error is a network error.

I could not reproduce the second error at current main.
```
jhipster jdl reactive-mf.jdl --monorepository --workspaces --client-framework angular
cd gateway
./gradlew
```

Build successfully
```
Webpack: Starting ...

  ✔ Compile modules
  ✔ Build modules
  ✔ Optimize modules
  ✔ Emit files

Finished after 1.225 seconds.

85 assets
713 modules
webpack 5.88.2 compiled successfully in 4474 ms
```

Closing for now if you manage to reproduce using main, please let me know.

**Closed by mshima** 2023-08-09 17:01 UTC
Labels: area: triage, theme: undefined
