### ISSUE TITLE
wiredep doesn't get bower files injected after app is generated for first time

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#1710] opened 2015-07-11 10:48 UTC
Isnt this suppose to be triggered after app generation, doesnt seems to work atleast in windows.

Need to take a closer look

**Comment by jdubois** [comment] 2015-07-11 12:06
That would be a big issue, yes please post updates on your findings!

**Comment by deepu105** [comment] 2015-07-12 07:47
can someone confirm if this works in linux/mac ?

**Comment by gmarziou** [comment] 2015-07-12 08:52
Works on linux  ubuntu with both gulp and grunt

**Comment by deepu105** [comment] 2015-07-12 08:54
@gmarziou then this might be another windows only issue :(

**Comment by deepu105** [comment] 2015-07-12 09:05
this is weird it seems to be working now. I can vouch that it didnt work last few times i tried.

**Comment by atomfrede** [comment] 2015-07-12 09:23
@deepu105 When I was testing my windows machine I've seen it too. After generating the app, all bower files where missing from ``index.html``. After doing ``grunt serve`` everything was fine, but I didn't dig any deeper.

**Comment by gmarziou** [comment] 2015-07-12 09:34
There are often beginners (not your case of course) who post issues about seeing only footer, most of the times they did not follow the doc or had an error duirng installation that they did not notice.

We could avoid these issues if the index.html contained a help section that would show only if angular app did not successfully intialize.

**Comment by atomfrede** [comment] 2015-07-12 09:59
@gmarziou Sounds like a reasonable idea. Will check if I can reproduce it on windows next week (as you said it works on linux, same for me here)

**Comment by jdubois** [comment] 2015-07-12 10:40
@deepu105 @atomfrede @gmarziou you can have Windows 10 preview for free on a VirtualBox machine, and the rumors is that it will stay free after the preview...

**Comment by deepu105** [comment] 2015-07-12 12:34
Since i had windows 8 im getting 10 for free on 29th july anyways

**Comment by gmarziou** [comment] 2015-07-12 12:38
So finally Armageddon is for July 29th ;)

**Comment by deepu105** [comment] 2015-07-21 01:58
Im reopening this issue, coz this seems to be appearing on and off, I still dont know how to reproduce, but randomly this happens.
May be this is only in windows but given the unstable nature i doubt. This is a very bad thing for new comers and should be fixed

**Comment by deepu105** [comment] 2015-07-21 02:00
I guess a sure shot way is to bind the these two tasks into the mavan or gradle build so that it is not missed

**Comment by andidev** [comment] 2015-07-21 05:38
Grunt build is run from at least maven and it should inject the files.

**Comment by atomfrede** [comment] 2015-07-21 06:33
I've created two projects just now on windows 8 (one with maven, one with gradle) and both times wiredep injected all files.

**Comment by deepu105** [comment] 2015-07-21 09:38
@atomfrede for me its working on and off and i dont know whats causing this behavior im on windows 8 as well. had an embarrassing moment coz of this when i was doing the JH demo to Singapore spring user group earlier

**Comment by atomfrede** [comment] 2015-08-04 13:38
anybody able to reproduce it?

**Comment by jdubois** [comment] 2015-08-18 09:54
it looks like nobody is able to reproduce this, so I'm closing it.

**Closed by jdubois** 2015-08-18 09:54 UTC
Labels: bug

**Comment by mallim** [comment] 2015-09-11 01:16
if somebody got the same error in windows and google to this page like me, I got it solve by first performing:

* download and install python https://www.python.org/downloads/
* download and install build tool http://www.visualstudio.com/downloads/download-visual-studio-vs#d-build-tools
* setup search path, so that node-gyp can find python

Then perform the installation steps:
* npm install -g yo
* npm install -g bower
* npm install -g generator-jhipster

and the wiredep works again for:
* yo jhipster

**Comment by deepu105** [comment] 2015-09-11 02:47
Thats interesting

**Comment by gmarziou** [comment] 2015-09-11 13:19
@mallim Your instructions should mention that it's Python 2.7.x that you must install not Python 3.x

**Comment by mallim** [comment] 2015-09-11 13:29
@gmarziou In fact, I installed Python 3.X, my environment as follows:

* Windows 8.1
* npm 2.11.3
* node 0.12.7

**Comment by gmarziou** [comment] 2015-09-11 13:33
Well I think you should re-consider it, I recently had to downgrade Python on a co-worker's PC.

There's this well known and [very old gyp issue](https://code.google.com/p/gyp/issues/detail?id=36) and as a consequence [node-gyp](https://github.com/nodejs/node-gyp) does not support Python 3 either, even [NodeJS requires gyp to build](https://github.com/nodejs/node/issues/133).
