### ISSUE TITLE
UAA without service discovery

### ISSUE THREAD

**Issue by lmbai** [jhipster/generator-jhipster#9176] opened 2019-02-02 10:48 UTC
##### **Overview of the feature request**

Can we run the service without a service registry server?

##### **Motivation for or Use Case**
 without `No service discovery`
    - when we generate the UAA server, we can choose the `No service discovery`.
    - when we generte the gateway/service, we can choose the `No service discovery` + `UAA`
    - but it won't work later.

this is a not critical issue, but i would to understand more:
-  if we would like to keep the UAA under the `service discovery`
    - can we add some document for this, to emphisis this ?
    - can we add some constraint for the generator, when user generate the UAA, they should not choose the `No service discovery`, when user generate the gateway/service, if they choose `No service discovery`, they can't choose the `UAA`

- if we don't limit the UAA under the `No service discovery` , technically it is possible to do that. i did some trial with it:
    - we need to use the `vanillaRestTemplate` without the loadbalance. 
    - user should config the right UAA server address. 
    - we need to change the frontend UAA call endpoint. 
        - the gateway should provide the account related endpoint 
        - frontend should call gateway to get account. change password ..... 

##### **Related issues or PR**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by ruddell** [comment] 2019-02-02 18:09
Duplicate of https://github.com/jhipster/generator-jhipster/issues/9027, could you please add your comments there?

**Closed by ruddell** 2019-02-02 18:09 UTC
Labels: uaa
