### ISSUE TITLE
Option to deploy on Aws without RDS

### ISSUE THREAD

**Issue by alchemistgo87** [jhipster/generator-jhipster#1945] opened 2015-08-28 16:22 UTC
I want to deploy to Aws without generator asking for RDS option. There should be option of none if we dont want to run an RDS instance.

**Comment by deepu105** [comment] 2015-08-29 03:53
:+1: do you want to propose a PR?

**Comment by jdubois** [comment] 2015-08-29 06:26
As written in the doc we can't improve this generator ourselves, as we don't have an AWS account (AWS is a paying service, we just work for free here, so we're just not going to spend our own personal money to solve someone else's issue).

**Comment by jdubois** [comment] 2015-09-01 16:14
I'm closing this as I don't think anybody will spend money on AWS for implementing this.

**Comment by mraible** [comment] 2015-09-01 16:19
My company might be interested in sponsoring an AWS instance. Should only be a few dollars for a month, correct?

**Comment by jdubois** [comment] 2015-09-01 16:34
Oh yes, by the way someone already proposed that (my bad, I didn't follow up...).

The issue is that I don't know how this can work in practice. For example, could you pay an instance and give me the "keys" to that instance?

**Comment by mraible** [comment] 2015-09-01 16:40
Yes, it looks like you can create groups and assign users with AWS Identity and Access Management (IAM). 

http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/UsingIAM.html

It's super easy to setup a server with Java installed. You could shut it down when you're done using it, and it'd likely cost under $1 per day. The most I've paid is $15 USD for a month.

**Comment by jdubois** [comment] 2015-09-01 19:50
OK, then that could be a good solution indeed.

I forgot to ask @wuethrich44 about this -> @wuethrich44 we have several AWS issues opened, would you be interested in working on them? If you are ready to work on this, I will start a vote to add you to the project team, see http://jhipster.github.io/team.html

And Matt, I'd love to work on this myself, but my current gig takes me full time during the day, so I don't have enough free time to commit working on this.

BTW, I'm reopening the issue, of course.

**Comment by jdubois** [comment] 2015-09-02 19:27
I've had a quick look and our first job should be to support other databases with RDS (like Postgresql).

I'm just out of a 3-hour meeting with AWS (for my "real" job) and it looks to me we should push RDS usage if people are using AWS. That's where they add the biggest value.

**Comment by deepu105** [comment] 2015-09-03 00:46
RDS supports mysql, posgres, oracle and so on, current aws sub supports
only mysql, its not very hard to add remaining. I originally wanted to add
a PR for that, but testing the PR will take some time. And im too busy till
end of September. So if anyone wants to take this up plz do else if anyone
can offer help to test i can put the required changes in a branch in my
fork

**Comment by wuethrich44** [comment] 2015-09-04 19:49
Today I returned from my holidays and I see there are a lot of issues open. I'm glad that the subgenerator is still in beta state. First of all I fix the serious bugs and after that I have enough time to work on new features (add more databases, grab the newest tomcat version...). Therefore you can assign all AWS related issues too me. @deepu105 can review my work and merge my PRs. 

Currently I still have an account with a free tier available but if the free tier expire a sponsored account would be very helpful. In one of our projects our customer has root access to AWS Management Console (User Management, Bill) and I can only access the technical stuff like RDS. I believe there is also an option to control the cost of an account. @mraible Maybe you could provide such an account for jhipster?

@alchemistgo87 Why do you want to deploy a jhipster application without RDS? Could you explain me your exact use case (Database from other provider, DynamoDB)?

**Comment by deepu105** [comment] 2015-09-05 02:37
@wuethrich44 one of the use case i often have is using aws for a demo,
where i would use an in memory DB as i dont want any persistent db.

And sometimes you wanna do the DB part manually for some reasons as well.

**Comment by alchemistgo87** [comment] 2015-09-05 06:31
@wuethrich44 I am using mongodb and elasticcache (with redis). So I don't need RDS. I have to deploy mongo db to another ec2 instance as a database tier.

**Comment by wuethrich44** [comment] 2015-09-05 07:55
Ah oke now I understand your problem. This feature made definitely sense. Should the RDS option be checked by default or not?

**Comment by seghers** [comment] 2015-09-05 21:42
If the aws generator uses a file (like  .yo-rc.json) it would only ask the questions one time.

**Comment by wuethrich44** [comment] 2015-09-09 08:57
Ok thanks for the input. I will implement this feature as soon as possible.

**Comment by jdubois** [comment] 2015-12-09 19:59
As nobody has worked on this for 3 months, and we have also several bugs opened for AWS (which are more important, of course), should we close this?

**Comment by deepu105** [comment] 2015-12-10 15:18
@wuethrich44 do you wanna work on this else lets close this

**Comment by wuethrich44** [comment] 2015-12-10 17:16
I don't have time so we can close this :+1:

**Comment by deepu105** [comment] 2016-01-12 06:21
no one is working on this so closing it

**Closed by deepu105** 2016-01-12 06:21 UTC
Labels: aws, feature request
