### ISSUE TITLE
after browser reload the login dialog will show up.

### ISSUE THREAD

**Issue by Alwan** [jhipster/generator-jhipster#5579] opened 2017-04-11 11:42 UTC
greetings, 

##### **Overview of the issue**

 If you login then reload a page that require authorization the login dialog will show up even though you already logged in.

##### **Motivation for or Use Case**

the user already logged in no need to ask him for credentials. 

##### **Reproduce the error**

1. Generate a monolithic project with Angular 4+.
2. Start the project.
3. login using the admin user.
4. open a page that require  authorization  for example http://localhost:8080/#/user-management
5. In your browser refresh the page. the login dialog will show up which is not required because the user already logged in  

##### **Related issues**
--

##### **Suggest a Fix**

--

##### **JHipster Version(s)**
4.2.0

##### **JHipster configuration**

`
##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.tw"
    },
    "jhipsterVersion": "4.2.0",
    "baseName": "tw",
    "packageName": "com.tw",
    "packageFolder": "com/tw",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "no",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "rememberMeKey": "39eeb94a298b04293cdf7eeec1d9d768164567bb",
    "clientFramework": "angular2",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

ls: no such file or directory: .jhipster/*.json

##### **Browsers and Operating System**

java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

git version 2.12.2.windows.2

node: v6.10.2

npm: 4.4.4

gulp:
[14:32:43] CLI version 3.9.1

yeoman: 1.8.5

yarn: 0.22.0`

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

no entity.

##### **Browsers and Operating System**
- Windows 10 
- Chrome

- [* ] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment] 2017-04-11 12:19
I'm sorry but I can't reproduce... I'm with the master branch, but I doubt there is a difference

**Comment by jdubois** [comment] 2017-04-11 14:53
I tried again using your `.yo-rc.json`, I still cannot reproduce.

I'm closing this as I can't reproduce, but please provide more information if you can, and I will try again.

**Closed by jdubois** 2017-04-11 14:53 UTC

**Comment by suhendra-arianto** [comment] 2017-05-06 08:11
I face the same issue in JHipster 4.2.0 monolithic, using HTTP Session Authentication as the authentication type and ehcache (not sure if this is relevant).
Each time the page is reloaded/refreshed, user has to login again. Even when user opens a link in a new tab, user has to login again in that new tab, which is unexpected.

**Comment by Alwan** [comment] 2017-05-06 08:20
@suhendra-arianto  upgrade to 4.3 it will resolve the issue.

**Comment by suhendra-arianto** [comment] 2017-05-06 11:16
Thanks @Alwan , 4.3.0 is confirmed resolving this issue.
