### ISSUE TITLE
make jar not executable (<executable>true</executable>)

### ISSUE THREAD

**Issue by svennela** [jhipster/generator-jhipster#10715] opened 2019-10-31 20:37 UTC
##### **Overview of the feature request**

I am using CNB's(https://buildpacks.io/) to build image for jhipster app, using https://github.com/buildpack/pack cli. Ran into invalid zip file error. As I am deploying to CF using CNB, there’s no benefit to the jar being fully-executable as it won’t use the launch script that’s prepended anyway.

[builder]   zip: not a valid zip file
[builder] ERROR: failed to build: exit status 103
ERROR: build failed: failed with status code: 7

##### **Motivation for or Use Case**

As of now as a workaround, I am passing false and proceeding further. As more automation or tools emerge to run the jar files, make it executable won't help as it won’t use the launch script that’s prepended anyway.

##### **Related issues or PR**

-   [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by ruddell** [comment] 2019-10-31 20:45
Duplicate of https://github.com/jhipster/generator-jhipster/issues/10255

This should be fixed as of v6.3.0, in #10282 it was changed to use non-executable JAR by default

**Closed by ruddell** 2019-10-31 20:45 UTC

**Comment by svennela** [comment] 2019-11-01 00:44
Thank you.
