### ISSUE TITLE
Minor bug in LoggingAspect

### ISSUE THREAD

**Issue by vivekmore** [jhipster/generator-jhipster#2262] opened 2015-11-01 04:01 UTC
**Overview of the issue**
In the generated LoggingAspect class, the following method has a minor bug

    @AfterThrowing(pointcut = "loggingPointcut()", throwing = "e")
    public void logAfterThrowing(JoinPoint joinPoint, Throwable e) {
        if (env.acceptsProfiles(Constants.SPRING_PROFILE_DEVELOPMENT)) {
            log.error("Exception in {}.{}() with cause = {}", joinPoint.getSignature().getDeclaringTypeName(),
                joinPoint.getSignature().getName(), e.getCause(), e);
        } else {
            log.error("Exception in {}.{}() with cause = {}", joinPoint.getSignature().getDeclaringTypeName(),
                joinPoint.getSignature().getName(), e.getCause());
        }
    }

The *log.error()* method accepts 4 arguments in the if condition block but has only 3 {} placeholders in the format.

On a slightly related note:
The log field on this class could be made static final

    private static final Logger LOG = LoggerFactory.getLogger(LoggingAspect.class);

instead of 

    private final Logger log = LoggerFactory.getLogger(this.getClass());

**Jhipster version**
2.23.0

**Reproduce the error**
Create a jhipster project normally.
I don't think there is a special scenario when this code is generated this way.

**Comment by deepu105** [comment] 2015-11-09 02:14
This is not a bug, the logback error method can accept a throwable hence exception is passed and it will be logged, but only in dev mode, in production only the cause is logged. this is perfectly normal

**Comment by vivekmore** [comment] 2015-11-09 14:49
The error method 

    error(String msg, Throwable t)

on the Logger accepts a **Throwable** only when the total number of arguments are 2. The bug is about the mismatch in number of arguments (2nd argument onwards) passed to the number of placeholders in the format (1st argument) as mentioned in the bug description. The actual error method getting called in the generated code is

	error(String format, Object... arguments)

Please feel free to verify the api [javadoc](http://www.slf4j.org/api/org/slf4j/Logger.html#error(java.lang.String, java.lang.Throwable))

I am still certain that this is a bug. I can provide a code snippet if you still need more clarity around the said issue.

**Comment by gzsombor** [comment] 2015-11-09 15:01
Yes, it's a bug

**Comment by deepu105** [comment] 2015-11-09 15:55
Oops sorry my bad I didnt look close enough

**Comment by deepu105** [comment] 2015-11-09 16:00
Closed via https://github.com/jhipster/generator-jhipster/commit/f8cb326e1c52fffb17e543e0400d796092076efe

**Comment by deepu105** [comment] 2015-11-09 16:00
Corrected

**Closed by deepu105** 2015-11-09 16:00 UTC
Labels: bug

**Comment by vivekmore** [comment] 2015-11-12 15:17
Thank you.
Any thoughts on making the LOG static final ?
It is definitely a better practice in my opinion.

**Comment by jdubois** [comment] 2015-11-12 15:20
It's a Spring bean -> it wouldn't do anything, except wasting some characters.

**Comment by vivekmore** [comment] 2015-11-12 17:27
The suggestion was more for all places (not just for this class)
It does not make a difference for beans in singleton scope (which I agree - most of the beans will be in) but it certainly helps to make sure you have a single logger for all types of objects (say beans in request or prototype scope) of any given class.

The extra characters, IMHO, are definitely worth the benefits in those cases. 
In addition to that it'll make the logger definition across the generated app consistent (i.e. in prototyped-scoped, request-scoped and singleton-scoped beans alike).
I don't see value in each object of the same class having it's own instance of a logger, unless I'm missing something.

Here are few discussions that might supplement my suggestion:
- [Should be logger always final and static?](http://stackoverflow.com/questions/7324386/should-be-logger-always-final-and-static)
- [Why do we declare Loggers static final?](http://stackoverflow.com/questions/6653520/why-do-we-declare-loggers-static-final)

**Comment by jdubois** [comment] 2015-11-12 17:49
@vivekmore then that's another issue, please our guidelines say we should have only one issue per ticket

- this has already been discussed in the past
- I find it more logical not to put them static as they don't need to be (waste of characters, and might put people under the false assumption the Spring bean isn't a singleton)
- it's not even recommended by tools like SLF4J ( http://www.slf4j.org/faq.html#declared_static )
- we don't use non-singleton scopes in the project (and in which case, it would indeed make sense, and they would just show that the users understand what they actually do instead of blindly copy/pasting code all over the place, see my first point)
- and that's a personal preference of mine, but if you put them static final, then you would need to write them in upper case, which looks like you're shouting all over the place, and brings the eye on the logging statements, which are probably the less important stuff in the code

**Comment by vivekmore** [comment] 2015-11-12 21:06
Fair enough.
Apologies for mixing multiple issues in one ticket.
I was just trying to understand the rationale behind it and provide my 2 cents on the matter.

**Comment by deepu105** [comment] 2015-11-13 00:43
@vivekmore suggestions are always welcome

**Comment by jdubois** [comment] 2015-11-13 06:05
Yes, I read myself again, sorry if it sound a bit harsh, it wasn't my intention

**Comment by vivekmore** [comment] 2015-11-13 15:35
Thank you @deepu105 and @jdubois - No offense taken.
Once I brush up on my git skills I plan to contribute to this project in any way I can.

**Comment by deepu105** [comment] 2015-11-13 16:11
You are welcome
