### ISSUE TITLE
Error when generation App from module

### ISSUE THREAD

**Issue by Tonterias** [jhipster/generator-jhipster#7854] opened 2018-06-25 09:51 UTC
##### **Overview of the issue**

ERROR in ./src/main/webapp/app/entities/post/post-update.component.ts
Module not found: Error: Can't resolve 'app/entities/blog' in 'D:\BasuraTemporal\Borrar\BOOTSRAP\JHispter\Packtpub\newstest501\src\main\webapp\app\entities\post'
 @ ./src/main/webapp/app/entities/post/post-update.component.ts 10:13-41
 @ ./src/main/webapp/app/entities/post/index.ts
 @ ./src/main/webapp/app/entities/post/post.module.ts
 @ ./src/main/webapp/app/entities/entity.module.ts
 @ ./src/main/webapp/app/app.module.ts
 @ ./src/main/webapp/app/app.main.ts

ERROR in ./src/main/webapp/app/entities/post/post-update.component.ts
Module not found: Error: Can't resolve 'app/entities/tag' in 'D:\BasuraTemporal\Borrar\BOOTSRAP\JHispter\Packtpub\newstest501\src\main\webapp\app\entities\post'
 @ ./src/main/webapp/app/entities/post/post-update.component.ts 11:12-39
 @ ./src/main/webapp/app/entities/post/index.ts
 @ ./src/main/webapp/app/entities/post/post.module.ts
 @ ./src/main/webapp/app/entities/entity.module.ts
 @ ./src/main/webapp/app/app.module.ts
 @ ./src/main/webapp/app/app.main.ts

ERROR in ./src/main/webapp/app/entities/post/post-update.component.ts
Module not found: Error: Can't resolve 'app/entities/topic' in 'D:\BasuraTemporal\Borrar\BOOTSRAP\JHispter\Packtpub\newstest501\src\main\webapp\app\entities\post'
 @ ./src/main/webapp/app/entities/post/post-update.component.ts 12:14-43
 @ ./src/main/webapp/app/entities/post/index.ts
 @ ./src/main/webapp/app/entities/post/post.module.ts
 @ ./src/main/webapp/app/entities/entity.module.ts
 @ ./src/main/webapp/app/app.module.ts
 @ ./src/main/webapp/app/app.main.ts

ERROR in D:/BasuraTemporal/Borrar/BOOTSRAP/JHispter/Packtpub/newstest501/src/main/webapp/app/entities/post/post-update.component.ts
(11,23): Cannot find module 'app/shared/model/blog.model'.

ERROR in D:/BasuraTemporal/Borrar/BOOTSRAP/JHispter/Packtpub/newstest501/src/main/webapp/app/entities/post/post-update.component.ts
(12,29): Cannot find module 'app/entities/blog'.

ERROR in D:/BasuraTemporal/Borrar/BOOTSRAP/JHispter/Packtpub/newstest501/src/main/webapp/app/entities/post/post-update.component.ts
(13,22): Cannot find module 'app/shared/model/tag.model'.

ERROR in D:/BasuraTemporal/Borrar/BOOTSRAP/JHispter/Packtpub/newstest501/src/main/webapp/app/entities/post/post-update.component.ts
(14,28): Cannot find module 'app/entities/tag'.

ERROR in D:/BasuraTemporal/Borrar/BOOTSRAP/JHispter/Packtpub/newstest501/src/main/webapp/app/entities/post/post-update.component.ts
(15,24): Cannot find module 'app/shared/model/topic.model'.

ERROR in D:/BasuraTemporal/Borrar/BOOTSRAP/JHispter/Packtpub/newstest501/src/main/webapp/app/entities/post/post-update.component.ts
(16,30): Cannot find module 'app/entities/topic'.

ERROR in D:/BasuraTemporal/Borrar/BOOTSRAP/JHispter/Packtpub/newstest501/src/main/webapp/app/shared/model/post.model.ts
(3,23): Cannot find module 'app/shared/model//blog.model'.

ERROR in D:/BasuraTemporal/Borrar/BOOTSRAP/JHispter/Packtpub/newstest501/src/main/webapp/app/shared/model/post.model.ts
(4,22): Cannot find module 'app/shared/model//tag.model'.

ERROR in D:/BasuraTemporal/Borrar/BOOTSRAP/JHispter/Packtpub/newstest501/src/main/webapp/app/shared/model/post.model.ts
(5,24): Cannot find module 'app/shared/model//topic.model'.
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Entity Post generated successfully.
Entity Comment generated successfully.
##### **Motivation for or Use Case**

I can not generate the App from the model.
##### **Reproduce the error**

yo jhipster:import-jdl ./src/main/scripts/raro.jh

##### **JHipster Version(s)**

v5.0.1
##### **JHipster configuration**

D:\BasuraTemporal\Borrar\BOOTSRAP\JHispter\Packtpub\newstest501>jhipster info
Using JHipster version installed locally in current project's node_modules
Executing jhipster:info
Options:
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
newstest-501@0.0.0 D:\BasuraTemporal\Borrar\BOOTSRAP\JHispter\Packtpub\newstest501
`-- generator-jhipster@5.0.1

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.web.newstest501"
    },
    "jhipsterVersion": "5.0.1",
    "applicationType": "monolith",
    "baseName": "newstest501",
    "packageName": "com.web.newstest501",
    "packageFolder": "com/web/newstest501",
    "serverPort": "8080",
    "authenticationType": "session",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "gradle",
    "enableSwaggerCodegen": false,
    "rememberMeKey": "replaced-by-jhipster-info",
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "yarn",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Blog (blog) {
  creationDate Instant required,
  title String minlength(2) maxlength(100) required,
  image ImageBlob
}
entity Post (post) {
  creationDate Instant required,
  publicationDate Instant,
  headline String minlength(2) maxlength(100) required,
  lead String minlength(2) maxlength(1000),
  bodytext TextBlob,
  quote String minlength(2) maxlength(1000),
  conclusion String minlength(2) maxlength(2000),
  image ImageBlob
}
entity Comment (comment) {
  creationDate Instant required,
  commentText TextBlob,
  isOffensive Boolean
}
entity Frontpageconfig (frontpageconfig) {
  creationDate Instant required,
  topNews1 Long,
  topNews2 Long,
  topNews3 Long,
  topNews4 Long,
  topNews5 Long,
  latestNews1 Long,
  latestNews2 Long,
  latestNews3 Long,
  latestNews4 Long,
  latestNews5 Long,
  breakingNews1 Long,
  recentPosts1 Long,
  recentPosts2 Long,
  recentPosts3 Long,
  recentPosts4 Long,
  featuredArticles1 Long,
  featuredArticles2 Long,
  featuredArticles3 Long,
  featuredArticles4 Long,
  featuredArticles5 Long,
  featuredArticles6 Long,
  featuredArticles7 Long,
  featuredArticles8 Long,
  featuredArticles9 Long,
  featuredArticles10 Long,
  popularNews1 Long,
  popularNews2 Long,
  popularNews3 Long,
  popularNews4 Long,
  popularNews5 Long,
  popularNews6 Long,
  popularNews7 Long,
  popularNews8 Long,
  weeklyNews1 Long,
  weeklyNews2 Long,
  weeklyNews3 Long,
  weeklyNews4 Long,
  newsFeeds1 Long,
  newsFeeds2 Long,
  newsFeeds3 Long,
  newsFeeds4 Long,
  newsFeeds5 Long,
  newsFeeds6 Long,
  usefulLinks1 Long,
  usefulLinks2 Long,
  usefulLinks3 Long,
  usefulLinks4 Long,
  usefulLinks5 Long,
  usefulLinks6 Long,
  recentVideos1 Long,
  recentVideos2 Long,
  recentVideos3 Long,
  recentVideos4 Long,
  recentVideos5 Long,
  recentVideos6 Long
}
entity Topic (topic) {
  topicName String minlength(2) maxlength(40) required
}
entity Tag (tag) {
  tagName String minlength(2) maxlength(40) required
}
entity Urllink (urllink) {
  linkText String required,
  linkURL String required
}
relationship OneToOne {
  Blog{user required} to User
}
relationship OneToMany {
  Blog{post} to Post{blog(title) required},
  Post{comment} to Comment{post(headline) required}
}
relationship ManyToMany {
  Topic{post(headline)} to Post{topic},
  Tag{post(headline)} to Post{tag}
}

paginate Blog, Post, Comment, Frontpageconfig, Topic, Tag, Urllink with pagination

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)

git version 2.16.2.windows.1

node: v8.11.1

npm: 5.6.0

yeoman: 2.0.2

yarn: 1.7.0

Docker version 18.03.0-ce, build 0520e24302

docker-compose version 1.20.1, build 5d8c71b2

Congratulations, JHipster execution is complete!
##### **Browsers and Operating System**

Windows10
- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment] 2018-06-26 09:31
I'm sorry but I can't reproduce...
Only difference is that I ran `jhispter import-jdl ./src/main/scripts/raro.jh` which is our newer command. Also, I'm on the master branch, but I don't think anything as changed on this part since 5.0.1 (which is very new).

Did you run `yarn install` correctly before? Did you have any error when generating your application initially?

I'm closing this as I can't reproduce, but if you have more information I would happily test again.

**Closed by jdubois** 2018-06-26 09:31 UTC

**Comment by Tonterias** [comment] 2018-06-27 18:59
So do I. I just can't reproduce it. Good.

- Regarding Import: It doesn't work (for me) if I do not use....yo jhipster:import-jdl ./src/main/scripts/raro.jh

Do I have to upgrade anything?

Thanks

**Comment by ruddell** [comment] 2018-06-27 19:12
I would just use `jhipster` without the `yo`.  Yeoman is probably picking up an older version, maybe you installed with both npm and yarn (usually fixable by removing it from both and installing with the one of your choice).

**Comment by QauseenMZ** [comment] 2019-11-04 20:24
Same issue for me! After importing entities from JDL file, it throws this error on npm run webpack:build
