### ISSUE TITLE
Jhipster - error with creating field 

### ISSUE THREAD

**Issue by saahon** [jhipster/generator-jhipster#2406] opened 2015-11-27 11:24 UTC
The problem: when I created new entity with jhipster on the terminal ubuntu, after creating field no asked of type for field. Instead, move to the next stage. How to fix this error?
screenshot:  http://i.stack.imgur.com/Y4lFr.png

**Comment by jdubois** [comment] 2015-11-27 11:29
You don't even have a question asking you for the type of your field??

I'm closing this, according to our guidelines, as:
- You don't provide your JHipster version
- You don't provide your JHipster configuration

So it's really impossible for us to reproduce.

**Closed by jdubois** 2015-11-27 11:29 UTC

**Comment by saahon** [comment] 2015-11-27 11:47
I edited the question

**Comment by deepu105** [comment] 2015-11-27 12:08
What is your .yo-rc.json file configuration only then we can reproduce

**Comment by saahon** [comment] 2015-11-27 12:19
```{```
```  "generator-jhipster": {```
 ```   "baseName": "epos_monitor",```
```    "packageName": "com.epos_monitor",```
  ```  "packageFolder": "com/epos_monitor",```
```    "authenticationType": "session",```
  ```  "hibernateCache": "ehcache",```
```    "clusteredHttpSession": "no",```
```    "websocket": "no",```
```    "databaseType": "sql",```
 ```   "devDatabaseType": "postgresql",```
 ```   "prodDatabaseType": "postgresql",```
```    "searchEngine": "no",```
```    "useSass": true,```
```    "buildTool": "maven",```
 ```   "frontendBuilder": "grunt",```
```    "enableTranslation": true,```
```    "enableSocialSignIn": false,```
  ```  "rememberMeKey": "1245454asdf45asdf54asdf45a4fd454adf",```
```    "testFrameworks": [ ```
  ```  "gatling" ```
 ```   ]  ```
```  }  ```
``` }  ```

**Comment by jdubois** [comment] 2015-11-27 12:59
Did you try with a correct package name? We don't check this (maybe we should!), but your package name is wrong

**Comment by saahon** [comment] 2015-11-30 04:03
how the correct the package name?

**Comment by pascalgrimaud** [comment] 2015-11-30 04:50
Can't reproduce your problem.

Can you :
* show your `package.json` in this project
* start a new project instead of the project from bitbucket, and try to reproduce your error

**Comment by saahon** [comment] 2015-11-30 05:16
My error there is for different versions of the node. I deleted and re-copy the folder node_modules and an error was corrected. Thank you for all the aid and advice
