### ISSUE TITLE
Npm build failing with Docker

### ISSUE THREAD

**Issue by rodrigorodrigues** [jhipster/generator-jhipster#10933] opened 2019-12-13 15:32 UTC
##### **Overview of the issue**

I'm trying to build a react front-end web app with Docker but it's failing when run command `npm run webpack:build`, following docker output:

	ERROR in /usr/src/app/src/main/webapp/app/routes.tsx
	ERROR in /usr/src/app/src/main/webapp/app/routes.tsx(39,35):
	TS2322: Type 'typeof LoadableComponent' is not assignable to type 'ComponentClass<any, any> | FunctionComponent<any> | ComponentClass<RouteComponentProps<any, StaticContext, any>, any> | FunctionComponent<RouteComponentProps<any, StaticContext, any>>'.
	  Type 'typeof LoadableComponent' is not assignable to type 'FunctionComponent<any>'.
	    Type 'LoadableComponent' is missing the following properties from type 'ReactElement<any, string | ((props: any) => ReactElement<any, string | ... | (new (props: any) => Component<any, any, any>)>) | (new (props: any) => Component<any, any, any>)>': type, props, key

	ERROR in /usr/src/app/src/main/webapp/app/routes.tsx
	ERROR in /usr/src/app/src/main/webapp/app/routes.tsx(40,37):
	TS2322: Type 'typeof LoadableComponent' is not assignable to type 'ComponentClass<any, any> | FunctionComponent<any> | ComponentClass<RouteComponentProps<any, StaticContext, any>, any> | FunctionComponent<RouteComponentProps<any, StaticContext, any>>'.
	  Type 'typeof LoadableComponent' is not assignable to type 'FunctionComponent<any>'.

	ERROR in /usr/src/app/src/test/javascript/spec/enzyme-setup.ts
	ERROR in /usr/src/app/src/test/javascript/spec/enzyme-setup.ts(5,22):
	TS2350: Only a void function can be called with the 'new' keyword.
	npm ERR! code ELIFECYCLE
	npm ERR! errno 2
	npm ERR! spendingbetter@0.0.0 webpack: `node --max_old_space_size=4096 node_modules/webpack/bin/webpack.js "--config" "webpack/webpack.dev.js" "--env.stats=minimal"`
	npm ERR! Exit status 2
	npm ERR! 
	npm ERR! Failed at the spendingbetter@0.0.0 webpack script.
	npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

	npm ERR! A complete log of this run can be found in:
	npm ERR!     /root/.npm/_logs/2019-12-12T08_31_57_422Z-debug.log
	npm ERR! code ELIFECYCLE
	npm ERR! errno 2
	npm ERR! spendingbetter@0.0.0 webpack:build:main: `npm run webpack -- --config webpack/webpack.dev.js --env.stats=minimal`
	npm ERR! Exit status 2
	npm ERR! 
	npm ERR! Failed at the spendingbetter@0.0.0 webpack:build:main script.
	npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

	npm ERR! A complete log of this run can be found in:
	npm ERR!     /root/.npm/_logs/2019-12-12T08_31_57_438Z-debug.log
	npm ERR! code ELIFECYCLE
	npm ERR! errno 2
	npm ERR! spendingbetter@0.0.0 webpack:build: `npm run cleanup && npm run webpack:build:main`
	npm ERR! Exit status 2
	npm ERR! 
	npm ERR! Failed at the spendingbetter@0.0.0 webpack:build script.
	npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

##### **Motivation for or Use Case**

Use case is to ship a react front-end app using docker

##### **Reproduce the error**

To reproduce this issue you can run the following docker command
`docker build --quiet --build-arg PORT=$REACT_WEBAPP_PORT -t eu.gcr.io/${GCP_PROJECT_ID}/${DOCKER_IMAGE}:$TRAVIS_COMMIT .`

Dockerfile

	FROM node:10.15.3-slim as builder
	ARG PORT

	# Create app directory
	WORKDIR /usr/src/app

	ENV PATH /usr/src/app/node_modules/.bin:$PATH

	# Install app dependencies
	# A wildcard is used to ensure both package.json AND package-lock.json are copied
	# where available (npm@5+)
	COPY package*.json ./

	COPY node_modules/ ./

	RUN apt-get update && apt-get install netcat-openbsd -y

	RUN npm install --silent --only=production

	# Bundle app source
	COPY . .

	RUN npm run webpack:build

	### STAGE 2: Production Environment ###
	FROM nginx:1.13.12-alpine
	ARG PORT

	ENV PORT=$PORT

	COPY --from=builder /usr/src/app/build /usr/share/nginx/html
	COPY --from=builder /usr/src/app/nginx.conf /etc/nginx/conf.d/default.conf

	RUN echo "PORT = $PORT"

	RUN sed -i 's/PORT/'"$PORT"'/g' /etc/nginx/conf.d/default.conf

	RUN echo "daemon off;" >> /etc/nginx/nginx.conf

	EXPOSE $PORT

	ENV JAVA_CMD="nginx"
	CMD ["nginx"]

##### **JHipster Version(s)**

v6.3.1

##### **JHipster configuration**

	{
	  "generator-jhipster": {
	    "promptValues": {
	      "nativeLanguage": "en"
	    },
	    "jhipsterVersion": "6.3.1",
	    "applicationType": "monolith",
	    "baseName": "spendingbetter",
	    "useSass": true,
	    "clientPackageManager": "npm",
	    "clientFramework": "react",
	    "clientTheme": "none",
	    "clientThemeVariant": "",
	    "authenticationType": "jwt",
	    "cacheProvider": "no",
	    "databaseType": "mongodb",
	    "devDatabaseType": "mongodb",
	    "prodDatabaseType": "mongodb",
	    "testFrameworks": [],
	    "jhiPrefix": "jhi",
	    "entitySuffix": "",
	    "dtoSuffix": "DTO",
	    "otherModules": [],
	    "enableTranslation": true,
	    "nativeLanguage": "en",
	    "languages": [
	      "en",
	      "pt-br"
	    ],
	    "skipServer": true,
	    "blueprints": []
	  }
	}

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**
	entity Person {
		id String required
	    fullName String required
	    dateOfBirth LocalDate
	    createdByUser String
	    createdDate Instant
	    lastModifiedByUser String
	    lastModifiedDate Instant
	}
	skipServer Person

	/**
	entity Child {
	id String required
		name String required
	    dateOfBirth LocalDate required
	}
	skipServer Child
	skipClient Child

	// an ignored comment
	entity Address {
		id String required
		address String required
		postalCode String required
		city String required
		stateOrProvince String required
	    country String required
	}
	skipServer Address
	skipClient Address

	relationship OneToOne {
		Person{address} to Address
	    Address{person} to Person
	}

	// defining multiple OneToMany relationships with comments
	relationship OneToMany {
		Person{children} to Child,
	}
	*/

	// Set pagination options
	paginate all with infinite-scroll

##### **Browsers and Operating System**

Docker version 19.03.5, build 633a0ea838
docker-compose version 1.23.1, build b02f1306

##### **Source Code**

https://github.com/rodrigorodrigues/microservices-design-patterns/tree/fixed-jhipster-app - branch `fixed-jhipster-app`

-   [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by ruddell** [comment] 2019-12-13 17:42
I could not reproduce this on v6.3.1 or master.  

Can you please fill out the rest of the issue template?  That will enable us to use the same config you do, the issue could relate to your prompt choices.

**Comment by rodrigorodrigues** [comment] 2019-12-13 19:24
Thanks for your reply @ruddell have added more information about it.

**Comment by ruddell** [comment] 2019-12-14 03:01
Thank you for providing all that information.

It has something to do with how you copy the `node_modules` folder then install only the production dependencies.

One possible fix is to remove the `COPY node_modules .` line and remove the `--only=production` flag from your `npm install` command.  Adding a `.dockerignore` for `node_modules` will drastically speed up your build, you're currently copying them twice (also in `COPY . .`)

Since this is not reproducible in a regular JHipster setup and relates to your custom Dockerfile, I'm closing the issue.  Let me know if the above fix works for you.

**Closed by ruddell** 2019-12-14 03:01 UTC
Labels: area: waiting for information, theme: react

**Comment by rodrigorodrigues** [comment] 2019-12-14 14:58
Thanks for your help @ruddell you are absolute right just removed `COPY node_modules` line and it worked.
