### ISSUE TITLE
TimeZone is not correct for non GMT

### ISSUE THREAD

**Issue by ratonlarvor** [jhipster/generator-jhipster#1196] opened 2015-03-01 19:33 UTC
Hi,

I follow the demo [youtube](https://www.youtube.com/watch?v=g-3tfSh_4g8). 
But when I tried to create a nez Customer with a birthdate 01.01.1970 the date registered was 31.12.1969. Then I edit the customer and save, the date was 30.12.1969.

The problem might come that I'm in CET and not in GMT I guess

Anyway congratulation for your work!

**Comment by gomesp** [comment] 2015-03-03 11:14
I had the same issue. I'm in the NZDT timezone. The solution for me was to change the line 20 in the CustomDateTimeSerializer.java file to the following pattern: "yyyy-MM-dd'T'HH:mm:ssZ".

@jdubois Have you seen this bug before?

**Comment by gomesp** [comment] 2015-03-03 11:25
hmmm, that solution I proposed had worked in my app running version 2.0.0. I had tried now with 2.5.1 and I have the same issue as you @ratonlarvor

**Comment by gomesp** [comment] 2015-03-03 11:28
Just realised the last part of my workaround. I also am using DateTime instead of LocalDate. I can't make it work with LocalDate too.

**Comment by ratonlarvor** [comment] 2015-03-03 13:03
Thanks for your reply! I will ccheck by my own if a fix is possible

**Comment by jdubois** [comment] 2015-03-05 20:44
I guys, I'm using a DateTime, and I'm not in GMT, but it's working for me....

Can you explain me your fix? I'm not sure of what I should do here, as I can't reproduce it, and it probably depends on your time zone and OS, I guess

**Comment by jdubois** [comment] 2015-03-06 10:35
As I can't reproduce I'm closing this, if you have more input I will of course have a look

**Comment by ratonlarvor** [comment] 2015-03-06 16:54
@jdubois sorry, I reply late. I will investigate more on my issue this weekend and let you know about. Thanks

**Comment by gomesp** [comment] 2015-03-09 08:44
@jdubois I created a sample app where I could reproduce it with a LocalDate. Please check this [repo](https://github.com/gomesp/jhipster-date-bug). 

On the [README.md](https://github.com/gomesp/jhipster-date-bug/blob/master/README.md) file I explain my steps to reproduce the error.

**Comment by jdubois** [comment] 2015-03-09 09:26
OK I'm reopening this.
Maybe this is because of this line:
https://github.com/gomesp/jhipster-date-bug/blob/master/src/main/webapp/scripts/app/entities/testEntity/testEntitys.html#L31

Can you check removing this 'UTC' option?

**Comment by gomesp** [comment] 2015-03-09 21:04
Thanks for the hint, I'll check that. I had only tried changing the serializer classes in the back-end.

**Comment by gomesp** [comment] 2015-03-09 22:03
Removing UTC from that line will break the "DateTime" component too (and it does not fix the LocalDate). :(

**Comment by red0point** [comment] 2015-03-16 22:17
When I update an entity with a property LocalDate to a date, the day before the LocaleDate appears in the database and in all subsequent queries.

For example when I set a date '25.02.2015', the date '24.02.2015' appears afterwards. I tracked this down to the issue that the angular $resource parses the JSON dates according to UTC time, but the new Date object has been created according to the Local Timezone.

I fixed it with a request transformer in angular (this is a snippet out of an entity.service.js file)

        'update': {
                method: 'PUT',
                transformRequest: function (data) {
                    var newDatum = new Date();
                    newDatum.setUTCDate(data.datum.getDate());
                    newDatum.setUTCMonth(data.datum.getMonth());
                    newDatum.setUTCFullYear(data.datum.getFullYear());
                    data.datum = newDatum;
                    return angular.toJson(data);
                }
            },

Maybe you know a more elegant way to solving this problem?

**Comment by ivdmeer** [comment] 2015-05-17 14:19
Hi,

I'm new to angular and jhipster, but I'm having the same issue as stated above. I'm from The Netherlands so my timezone differs (non GMT). At my entity I have 3 fields with type LocalDate. 

The code from red0point inspired me to create a fix more generic so it would effect all 3 fields with type LocalDate.

            'update': {
                method: 'PUT',
                transformRequest: function (data) {
                	angular.forEach(data, function(v,k) {
                		// Fixup for localDate values
	                    if (angular.isDate(v)) {
	                		var newDate = new Date();
		                    newDate.setUTCDate(data[k].getDate());
		                    newDate.setUTCMonth(data[k].getMonth());
		                    newDate.setUTCFullYear(data[k].getFullYear());
		                    data[k] = newDate;
                		}
                	});
                    return angular.toJson(data);
                }
            },

I hope this helps investigating this issue.

**Comment by jdubois** [comment] 2015-05-18 08:38
Hi, thanks for your help, as I'm still stucked with this issue (and I lack time, of course...).

I'll give it a try -> if anyone following this issue, in a non-GMT timezone, can test this, that would be a huge help!

Oh, and @ivdmeer don't hesitate to do a PR, so that you are credited for your work

**Comment by ivdmeer** [comment] 2015-05-18 11:10
Hi,

I think this is more like a quickfix, but not solving the root cause. I also noticed that the output of a LocalDate field on the view and edite page of an entity displays a different date. On the edit page the LocalDate value is displayed in the HTML datepicker (<input type="date" ...>), but  the view page displays the LocalDate in string format (<input type="text" ...>). On each page a different date is displayed despite of the different format that is used.

I'm still investigating on this and will post updates on this matter at this ticket if that's ok with you?

**Comment by ivdmeer** [comment] 2015-05-18 20:16
Hi,

After a bit of digging I've created a custom directive that converts a LocalDate string to a javascript Date obj. 
This directive makes all of the LocalDate reformatting code that was added to the ../entities/member.serivce.js file obsolete.

P.S. In my example, I have an entity called member with a few attributes that are of type LocalDate.

```javascript
angular.module('myApp')
    .directive('formatDate', function(){
        return {
	        require: 'ngModel',
	        link: function(scope, elem, attr, ngModelCtrl) {
	            ngModelCtrl.$formatters.push(function(modelValue){
	            	if(modelValue) {
	                    return new Date(modelValue);
	                }
	            });
	        }
        };
    });
```

A small change to the view is required for the input field tag, from:

```html
<input type="date" ng-model="member.birth_date" > 
```
To:

```html
<input type="date" ng-model="member.birth_date" format-date> 
```


My member.service.js file was looking like this:
````javascript
'use strict';

angular.module('myApp')
    .factory('Member', function ($resource) {
        return $resource('api/members/:id', {}, {
            'query': { method: 'GET', isArray: true},
            'get': {
                method: 'GET',
                transformResponse: function (data) {
                    data = angular.fromJson(data);
                    if (data.birth_date != null){
                        var birth_dateFrom = data.birth_date.split("-");
                        data.birth_date = new Date(new Date(birth_dateFrom[0], birth_dateFrom[1] - 1, birth_dateFrom[2]));
                    }
                    if (data.member_since != null){
                        var member_sinceFrom = data.member_since.split("-");
                        data.member_since = new Date(new Date(member_sinceFrom[0], member_sinceFrom[1] - 1, member_sinceFrom[2]));
                    }
                    if (data.removed_since != null){
                        var removed_sinceFrom = data.removed_since.split("-");
                        data.removed_since = new Date(new Date(removed_sinceFrom[0], removed_sinceFrom[1] - 1, removed_sinceFrom[2]));
                    }
                    return data;
                }
            },
            'update': {
                method: 'PUT',
                transformRequest: function (data) {
                	angular.forEach(data, function(v,k) {
                	   // Fixup for localDate values
	                    if (angular.isDate(v)) {
	                	   var newDate = new Date();
		                    newDate.setUTCDate(data[k].getDate());
		                    newDate.setUTCMonth(data[k].getMonth());
		                    newDate.setUTCFullYear(data[k].getFullYear());
		                    data[k] = newDate;
                		}
                	});
                    return angular.toJson(data);
                }
            },

        });
    });
```


I could refactor it to this:

```javascript
'use strict';

angular.module('clubmembersApp')
    .factory('Member', function ($resource) {
        return $resource('api/members/:id', {}, {
            'query': { method: 'GET', isArray: true},
            'get': {
                method: 'GET',
            },
            'update': {
                method: 'PUT',
            }
        });
    });
```

I will need some more testing with this and make a PR to the JHipster project.

**Comment by jdubois** [comment] 2015-05-19 16:26
Yes the issue is just for LocalDate
@ivdmeer I tried your fix and it works -> I'm going to commit it as this has been opened for too long

However my code should clearly be refactored in a directive, if you have time to have a look at it and improve it, I would appreciate it

**Closed** 2015-05-19 16:38 UTC

**Comment by ivdmeer** [comment] 2015-05-19 17:20
@jdubois thanks for testing my code. I will do my best to refactor this quickfix and create a PR.
