### ISSUE TITLE
Error running generator app: Error: Cannot find module 'yeoman-environment/transform'

### ISSUE THREAD

**Issue by crowne** [jhipster/generator-jhipster#17007] opened 2021-11-14 10:32 UTC
##### **Overview of the issue**

I am using a fork of JHipster which is up to date with main.
When I try to run jhipster I get an error, stacktrace shown below.
If I switch to tag v7.3.1 then the error does not occur.

```
INFO! Using JHipster version installed globally
INFO! Executing import-jdl model.jdl
INFO! The JDL is being parsed.
warn: An Entity name 'User' was used: 'User' is an entity created by default by JHipster. All relationships toward it will be kept but any attributes and relationships from it will be disregarded.
INFO! Found entities: Department, Employee, Roster.
INFO! The JDL has been successfully parsed
INFO! Generating 1 application.
Error running generator app: Error: Cannot find module 'yeoman-environment/transform'
Require stack:
- E:\jhipster\generator-jhipster\generators\bootstrap\index.js
- E:\jhipster\generator-jhipster\node_modules\yeoman-environment\lib\util\esm.js
- E:\jhipster\generator-jhipster\node_modules\yeoman-environment\lib\store.js
- E:\jhipster\generator-jhipster\node_modules\yeoman-environment\lib\environment.js
- E:\jhipster\generator-jhipster\cli\environment-builder.js
- E:\jhipster\generator-jhipster\cli\program.js
- E:\jhipster\generator-jhipster\cli\cli.js
- E:\jhipster\generator-jhipster\cli\jhipster.js
Error: Cannot find module 'yeoman-environment/transform'
Require stack:
- E:\jhipster\generator-jhipster\generators\bootstrap\index.js
- E:\jhipster\generator-jhipster\node_modules\yeoman-environment\lib\util\esm.js
- E:\jhipster\generator-jhipster\node_modules\yeoman-environment\lib\store.js
- E:\jhipster\generator-jhipster\node_modules\yeoman-environment\lib\environment.js
- E:\jhipster\generator-jhipster\cli\environment-builder.js
- E:\jhipster\generator-jhipster\cli\program.js
- E:\jhipster\generator-jhipster\cli\cli.js
- E:\jhipster\generator-jhipster\cli\jhipster.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (E:\jhipster\generator-jhipster\generators\bootstrap\index.js:28:5)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at requireOrImport (E:\jhipster\generator-jhipster\node_modules\yeoman-environment\lib\util\esm.js:14:14)
    at Object.get [as jhipster:bootstrap] (E:\jhipster\generator-jhipster\node_modules\yeoman-environment\lib\store.js:49:16)
    at Store.get (E:\jhipster\generator-jhipster\node_modules\yeoman-environment\lib\store.js:72:44)
    at Environment.composability.getByNamespace (E:\jhipster\generator-jhipster\node_modules\yeoman-environment\lib\namespace-composability.js:21:37)
    at Environment.get (E:\jhipster\generator-jhipster\node_modules\yeoman-environment\lib\environment.js:621:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'E:\\jhipster\\generator-jhipster\\generators\\bootstrap\\index.js',
    'E:\\jhipster\\generator-jhipster\\node_modules\\yeoman-environment\\lib\\util\\esm.js',
    'E:\\jhipster\\generator-jhipster\\node_modules\\yeoman-environment\\lib\\store.js',
    'E:\\jhipster\\generator-jhipster\\node_modules\\yeoman-environment\\lib\\environment.js',
    'E:\\jhipster\\generator-jhipster\\cli\\environment-builder.js',
    'E:\\jhipster\\generator-jhipster\\cli\\program.js',
    'E:\\jhipster\\generator-jhipster\\cli\\cli.js',
    'E:\\jhipster\\generator-jhipster\\cli\\jhipster.js'
  ]
}
ERROR! Cannot find module 'yeoman-environment/transform'
Require stack:
- E:\jhipster\generator-jhipster\generators\bootstrap\index.js
- E:\jhipster\generator-jhipster\node_modules\yeoman-environment\lib\util\esm.js
- E:\jhipster\generator-jhipster\node_modules\yeoman-environment\lib\store.js
- E:\jhipster\generator-jhipster\node_modules\yeoman-environment\lib\environment.js
- E:\jhipster\generator-jhipster\cli\environment-builder.js
- E:\jhipster\generator-jhipster\cli\program.js
- E:\jhipster\generator-jhipster\cli\cli.js
- E:\jhipster\generator-jhipster\cli\jhipster.js
Error: Cannot find module 'yeoman-environment/transform'
Require stack:
- E:\jhipster\generator-jhipster\generators\bootstrap\index.js
- E:\jhipster\generator-jhipster\node_modules\yeoman-environment\lib\util\esm.js
- E:\jhipster\generator-jhipster\node_modules\yeoman-environment\lib\store.js
- E:\jhipster\generator-jhipster\node_modules\yeoman-environment\lib\environment.js
- E:\jhipster\generator-jhipster\cli\environment-builder.js
- E:\jhipster\generator-jhipster\cli\program.js
- E:\jhipster\generator-jhipster\cli\cli.js
- E:\jhipster\generator-jhipster\cli\jhipster.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (E:\jhipster\generator-jhipster\generators\bootstrap\index.js:28:5)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at requireOrImport (E:\jhipster\generator-jhipster\node_modules\yeoman-environment\lib\util\esm.js:14:14)
    at Object.get [as jhipster:bootstrap] (E:\jhipster\generator-jhipster\node_modules\yeoman-environment\lib\store.js:49:16)
    at Store.get (E:\jhipster\generator-jhipster\node_modules\yeoman-environment\lib\store.js:72:44)
    at Environment.composability.getByNamespace (E:\jhipster\generator-jhipster\node_modules\yeoman-environment\lib\namespace-composability.js:21:37)
    at Environment.get (E:\jhipster\generator-jhipster\node_modules\yeoman-environment\lib\environment.js:621:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'E:\\jhipster\\generator-jhipster\\generators\\bootstrap\\index.js',
    'E:\\jhipster\\generator-jhipster\\node_modules\\yeoman-environment\\lib\\util\\esm.js',
    'E:\\jhipster\\generator-jhipster\\node_modules\\yeoman-environment\\lib\\store.js',
    'E:\\jhipster\\generator-jhipster\\node_modules\\yeoman-environment\\lib\\environment.js',
    'E:\\jhipster\\generator-jhipster\\cli\\environment-builder.js',
    'E:\\jhipster\\generator-jhipster\\cli\\program.js',
    'E:\\jhipster\\generator-jhipster\\cli\\cli.js',
    'E:\\jhipster\\generator-jhipster\\cli\\jhipster.js'
  ]
}
```

##### **Motivation for or Use Case**

I can't use jhipster, this will need to be solved for the next version.

##### **Reproduce the error**

clone jhipster
npm link
try to run jhipster in a new project dir

##### **Related issues**

None found

##### **Suggest a Fix**

Please solve the missing dependency

##### **JHipster Version(s)**

> 3.7.1 ... Fork of main at commit ea922e7

##### **JHipster configuration**

It doesn't run, it crashes

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

None, just trying to run jhipster on command line 

##### **Browsers and Operating System**

Windows 10 Prod + chrome

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment] 2021-11-14 14:45
@crowne what node version are you using?

**Comment by crowne** [comment] 2021-11-14 16:22
v14.18.0

**Comment by mshima** [comment] 2021-11-14 20:16
Subpath exports is supported since v12.7.0 https://nodejs.org/api/packages.html#subpath-exports.
So this is not a bug.

Probably you are using the generator-jhipster from git, updated the repository, but forgot to run `npm ci` to update dependencies.
Closing as invalid for now.

**Closed by mshima** 2021-11-14 20:16 UTC
Labels: area: bug :bug:, theme: jhipster-internals

**Comment by crowne** [comment] 2021-11-15 07:15
Thanks @mshima
`npm ci` fixed the issue.

Do you think we should update
https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md#setup

to add the step of running `npm link` and then running `npm ci` ?

**Comment by mshima** [comment] 2021-11-15 10:28
@crowne that would be great. Could you provide the PR please?

**Comment by crowne** [comment] 2021-11-15 14:29
I will do so.
New problem for me, jhipster is crashing with "ERROR! Callback called multiple times",
this is apparently a known issue for node versions > 14 according to #16744

**Comment by mshima** [comment] 2021-11-15 14:45
@crowne update to main if you are using git.
Downgrade node if you are using release.

**Comment by pascalgrimaud** [comment] 2021-11-15 15:10
@mshima : should I do a release to fix that ? As I'm pretty sure a lot of users already upgraded Node version to use LTS

**Comment by mshima** [comment] 2021-11-15 20:18
@pascalgrimaud yes, sure. Would be great to have https://github.com/jhipster/generator-jhipster/pull/16991, https://github.com/jhipster/generator-jhipster/pull/16990 and maybe https://github.com/jhipster/generator-jhipster/pull/16880 merged.

**Comment by pascalgrimaud** [comment] 2021-11-15 20:20
If you feel confident, go ahead and merge these PRs. I'm trusting you and the daily builds, to know if it's ready for a release or not

**Comment by mshima** [comment] 2021-11-18 20:30
@pascalgrimaud you probably should release now.

**Comment by pascalgrimaud** [comment] 2021-11-18 20:32
@mshima : ok, I'll prepare it for tomorrow and will ask in the mailing list. Thanks !

**Comment by mshima** [comment] 2021-11-18 21:07
@pascalgrimaud 👍 thanks.

**Comment by mshima** [comment] 2021-11-19 00:12
@pascalgrimaud npm test is broken but not failing.
I will try to fix.
