### ISSUE TITLE
Elasticsearch tests are not that well configured

### ISSUE THREAD

**Issue by Tcharl** [jhipster/generator-jhipster#11912] opened 2020-06-06 18:32 UTC
##### **Overview of the issue**

Looking at the actual tests with elasticsearch configured is pretty messy:

* src/test/resources/application.yml reference path.home: it configures an embedded elastic
* src/test/java/<package>/config/ElasticsearchConfiguration overrides that properties setting a temporary folder instead of the fixed folder referenced in the configuration
* SearchRepositoryMocks are generated in src/test/java/<package>/repository/search/<Entity>SearchRepositoryMock
* Mocks are used in tests, meaning that the two first bullets are useless

##### **Motivation for or Use Case**

Improving the code, avoiding useless properties and behaviors.

##### **Reproduce the error**

Generate a platform with elastic

##### **Suggest a Fix**

So we have multiple choices here:

1) Using mock and disabling embedded start: spring boot 2.3 compliant, but with more code (the stub/mock) and potential misbehavior (if the user wants to mock some more method for example)
2) Using embedded Elastic (thus removing mocks), however, from what I know it's part of Vanroy/JestElastic so will be removed with S.B 2.3. Also, starting elastic before each tests class leads to some strange tests behaviors and sometimes heapdumps see !https://github.com/jhipster/generator-jhipster/pull/11903
3) Using test containers to start embedded elastic: better behavior, but the end user must have docker installed...

I suggest a vote on this ticket, before a PR

##### **JHipster Version(s)**

6.9.1

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by murdos** [comment] 2020-06-06 21:26
> Looking at the actual tests with elasticsearch configured is pretty messy:
> 
>     * src/test/resources/application.yml reference path.home: it configures an embedded elastic
> 
>     * src/test/java//config/ElasticsearchConfiguration overrides that properties setting a temporary folder instead of the fixed folder referenced in the configuration
> 
>     * SearchRepositoryMocks are generated in src/test/java//repository/search/SearchRepositoryMock
> 
>     * Mocks are used in tests, meaning that the two first bullets are useless

The two first bullets have already been cleaned in https://github.com/jhipster/generator-jhipster/pull/11683 and thus are fixed in the `spring-boot-2.3` branch.

>     3. Using test containers to start embedded elastic: better behavior, but the end user must have docker installed...

I don't think the issue is for end user (docker is already required for development), but rather for CI.
But since that's already the case for Couchbase, Neo4j, Cassandra, Redis, and don't think it's blocking.

**Closed** 2020-06-07 09:36 UTC
Labels: area: triage, theme: elasticsearch
