### ISSUE TITLE
webpack:build failed with jhipster --skip-server

### ISSUE THREAD

**Issue by danielbrutti** [jhipster/generator-jhipster#7746] opened 2018-06-08 18:11 UTC
##### **Overview of the issue**

I got the following error when generating a jhipster client side.

`jhipster --skip-server --auth UAA --uaa-base-name uaa --db mysql --protactor --websocket`

```
[at-loader] Checking finished with 3 errors
285ms asset optimization
Hash: 8691065468b05c4adbb9
Version: webpack 3.10.0
Time: 19754ms
 14 assets
[./node_modules/css-loader/index.js!./node_modules/postcss-loader/lib/index.js!./node_modules/sass-loader/lib/loader.js!./src/main/webapp/content/scss/global.scss] ./node_modules/css-loader!./node_modules/postcss-loader/lib!./node_modules/sass-loader/lib/loader.js!./src/main/webapp/content/scss/global.scss 5.22 kB {3} [built]
       [] -> factory:4ms building:9201ms dependencies:122ms = 9327ms
[./src/main/webapp/app/app.main.ts] ./src/main/webapp/app/app.main.ts 591 bytes {2} [built]
        factory:570ms building:4330ms = 4900ms
[./src/main/webapp/app/app.module.ts] ./src/main/webapp/app/app.module.ts 4.07 kB {2} [built]
       [] -> factory:36ms building:118ms = 154ms
[./src/main/webapp/app/blocks/config/prod.config.ts] ./src/main/webapp/app/blocks/config/prod.config.ts 391 bytes {2} [built]
       [] -> factory:43ms building:136ms dependencies:596ms = 775ms
[./src/main/webapp/app/blocks/config/uib-pagination.config.ts] ./src/main/webapp/app/blocks/config/uib-pagination.config.ts 1.57 kB {2} [built]
       [] -> factory:44ms building:257ms dependencies:334ms = 635ms
[./src/main/webapp/app/blocks/interceptor/auth-expired.interceptor.ts] ./src/main/webapp/app/blocks/interceptor/auth-expired.interceptor.ts 364 bytes {2} [built]
       [] -> factory:45ms building:304ms dependencies:345ms = 694ms
[./src/main/webapp/app/blocks/interceptor/errorhandler.interceptor.ts] ./src/main/webapp/app/blocks/interceptor/errorhandler.interceptor.ts 1.04 kB {2} [built]
       [] -> factory:46ms building:355ms dependencies:748ms = 1149ms
[./src/main/webapp/app/blocks/interceptor/notification.interceptor.ts] ./src/main/webapp/app/blocks/interceptor/notification.interceptor.ts 1.78 kB {2} [built]
       [] -> factory:46ms building:406ms dependencies:697ms = 1149ms
[./src/main/webapp/app/entities/entity.module.ts] ./src/main/webapp/app/entities/entity.module.ts 1.3 kB {2} [built]
       [] -> factory:48ms building:513ms dependencies:60ms = 621ms
[./src/main/webapp/app/home/home.module.ts] ./src/main/webapp/app/home/home.module.ts 1.48 kB {2} [built]
       [] -> factory:47ms building:427ms dependencies:973ms = 1447ms
[./src/main/webapp/app/layouts/index.ts] ./src/main/webapp/app/layouts/index.ts 670 bytes {2} [built]
       [] -> factory:601ms building:89ms = 690ms
[./src/main/webapp/app/polyfills.ts] ./src/main/webapp/app/polyfills.ts 2.66 kB {1} [built]
        factory:300ms building:4523ms = 4823ms
[./src/main/webapp/app/shared/index.ts] ./src/main/webapp/app/shared/index.ts 1.3 kB {2} [built]
       [] -> factory:599ms building:79ms dependencies:5479ms = 6157ms
[./src/main/webapp/content/scss/global.scss] ./src/main/webapp/content/scss/global.scss 1.38 kB {3} [built]
        factory:572ms building:31ms = 603ms
[./src/main/webapp/manifest.webapp] ./src/main/webapp/manifest.webapp 61 bytes {1} [built]
       [] -> factory:455ms dependencies:5575ms building:6009ms = 12039ms
    + 667 hidden modules

ERROR in [at-loader] ./src/main/webapp/app/blocks/interceptor/auth-expired.interceptor.ts:6:14 
    TS2420: Class 'AuthExpiredInterceptor' incorrectly implements interface 'HttpInterceptor'.
  Property 'intercept' is missing in type 'AuthExpiredInterceptor'.

ERROR in [at-loader] ./src/main/webapp/app/shared/login/login.service.ts:12:37 
    TS2304: Cannot find name 'AuthServerProvider'.

ERROR in [at-loader] ./src/main/webapp/app/shared/shared.module.ts:8:5 
    TS2305: Module '"/home/daniel/workspace/budderfly/hello.world/developer.web/src/main/webapp/app/shared/index"' has no exported member 'AuthServerProvider'.
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
If you find JHipster useful consider supporting our collective https://opencollective.com/generator-jhipster
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: ERROR! webpack:build failed.
    at Environment.error (/home/daniel/.config/yarn/global/node_modules/yeoman-environment/lib/environment.js:157:40)
    at module.exports.error (/home/daniel/.config/yarn/global/node_modules/generator-jhipster/generators/generator-base.js:2064:18)
    at module.exports.end (/home/daniel/.config/yarn/global/node_modules/generator-jhipster/generators/client/index.js:410:18)
    at Object.<anonymous> (/home/daniel/.config/yarn/global/node_modules/generator-jhipster/node_modules/yeoman-generator/lib/index.js:399:25)
    at /home/daniel/.config/yarn/global/node_modules/run-async/index.js:25:25
    at new Promise (<anonymous>)
    at /home/daniel/.config/yarn/global/node_modules/run-async/index.js:24:19
    at self.env.runLoop.add.completed (/home/daniel/.config/yarn/global/node_modules/generator-jhipster/node_modules/yeoman-generator/lib/index.js:400:11)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
```

##### **Motivation for or Use Case**

I want to generate an angular 5 client side project.

##### **Reproduce the error**

Just create an empty directory, run the command
`jhipster --skip-server --auth UAA --uaa-base-name uaa --db mysql --protactor --websocket`
Answer the questions and it will fail during creation.

##### **Related issues**

https://github.com/jhipster/generator-jhipster/issues/7592

##### **Suggest a Fix**

No suggestion.

##### **JHipster Version(s)**

v4.14.4

##### **JHipster configuration**

```
Using JHipster version installed locally in current project's node_modules
Executing jhipster:info
Options: 
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
developerweb@0.0.0 /home/daniel/workspace/budderfly/hello.world/developer.web
└── generator-jhipster@4.14.4 

```


##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**


<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "4.14.4",
    "baseName": "developerweb",
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "yarn",
    "authenticationType": "UAA",
    "cacheProvider": "no",
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "applicationType": "monolith",
    "testFrameworks": [
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ],
    "skipServer": true
  }
}
</pre>
</details>


##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>




</pre>
</details>


##### **Environment and Tools**

java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)

git version 2.7.4

node: v8.11.2

npm: 6.1.0

bower: 1.8.2

gulp:
[15:10:03] CLI version 1.2.2

yeoman: 2.0.2

yarn: 1.7.0

Docker version 17.05.0-ce, build 89658be

docker-compose version 1.11.0-rc1, build 0ea24e7

Congratulations, JHipster execution is complete!
```

##### **Browsers and Operating System**

Chrome, Firefox
Elementary based on UBuntu 16.04

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by danielbrutti** [comment] 2018-06-08 18:11
Btw, i tried using different parameters and values on the --skip-server command without success. The command throws an error as soon as I run it because params are incorrect, or I got this error when generating the app.

**Comment by danielbrutti** [comment] 2018-06-08 18:17
This is the .yo-rc file
```
{
  "generator-jhipster": {
    "promptValues": {
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "4.14.4",
    "baseName": "developerweb",
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "yarn",
    "authenticationType": "UAA",
    "cacheProvider": "no",
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "applicationType": "monolith",
    "testFrameworks": [
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ],
    "skipServer": true
  }
}
```

**Comment by pascalgrimaud** [comment] 2018-06-08 19:48
The problem is: you can't have an application with `authenticationType=UAA` with an `applicationType=monolith`. That's why it failed.

For all users who want to use `--skip-server` or `--skip-client`, it's for very advanced configuration and we can't guarantee it can work, as there are a lot of other configuration we didn't test.

What I can advice to you, is to generate an application, using `jhipster`.
You have to select `gateway` with `uaa`, according to your command line.
Then you delete what you don't need step by step, using git, so you can revert when something is wrong.

I let this ticket opened for now but not sure we can't fix this.

**Comment by deepu105** [comment] 2018-06-09 10:38
Yes, this is not a supported config. Uaa is only for microservice options and hence we cant guarantee it would work for any config. I'm closing this ticket as I don't think we will do anything to support this. Either try with application type gateway or use jwt auth. Else follow the advice from Pascal. These flags are for advanced users and the assumption is that there might be quirks and edge cases but an advanced user would be able to fix it themselves.

Ofcourse if a small fix can avoid the issue, you are welcome to PR it. You can also just fix the webpack compilation error is your code

**Closed by deepu105** 2018-06-09 10:38 UTC
