### ISSUE TITLE
 Liquibase: foreign column is of type bigint but expression is of type character varying

### ISSUE THREAD

**Issue by kirill-kobzev** [jhipster/generator-jhipster#10121] opened 2019-07-20 00:30 UTC
##### **Overview of the issue**

An error occurs when trying to add a foreign key from CSV file.

~~~
2019-07-20 02:43:55.483 ERROR 26088 --- [  restartedMain] liquibase.changelog.ChangeSet            : Change Set config/liquibase/changelog/20190719225630_added_entity_Money.xml::20190719225630-1-data::jhipster failed.  Error: java.sql.BatchUpdateException: Batch entry 0 INSERT INTO public.money(id, count, name, purse_id) VALUES(1, 37454, 'Directives application Home Loan Account', '1') was aborted: ERROR: column "purse_id" is of type bigint but expression is of type character varying
  Подсказка: You will need to rewrite or cast the expression.
  Позиция: 72  Call getNextException to see other errors in the batch.
2019-07-20 02:43:55.486  WARN 26088 --- [  restartedMain] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'liquibase' defined in class path resource [com/home/liquibasetest/config/LiquibaseConfiguration.class]: Invocation of init method failed; nested exception is liquibase.exception.MigrationFailedException: Migration failed for change set config/liquibase/changelog/20190719225630_added_entity_Money.xml::20190719225630-1-data::jhipster:
     Reason: liquibase.exception.DatabaseException: java.sql.BatchUpdateException: Batch entry 0 INSERT INTO public.money(id, count, name, purse_id) VALUES(1, 37454, 'Directives application Home Loan Account', '1') was aborted: ERROR: column "purse_id" is of type bigint but expression is of type character varying
  Подсказка: You will need to rewrite or cast the expression.
  Позиция: 72  Call getNextException to see other errors in the batch.
2019-07-20 02:43:55.519 ERROR 26088 --- [  restartedMain] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'liquibase' defined in class path resource [com/home/liquibasetest/config/LiquibaseConfiguration.class]: Invocation of init method failed; nested exception is liquibase.exception.MigrationFailedException: Migration failed for change set config/liquibase/changelog/20190719225630_added_entity_Money.xml::20190719225630-1-data::jhipster:
     Reason: liquibase.exception.DatabaseException: java.sql.BatchUpdateException: Batch entry 0 INSERT INTO public.money(id, count, name, purse_id) VALUES(1, 37454, 'Directives application Home Loan Account', '1') was aborted: ERROR: column "purse_id" is of type bigint but expression is of type character varying
  Подсказка: You will need to rewrite or cast the expression.
  Позиция: 72  Call getNextException to see other errors in the batch.
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1778)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:593)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:307)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1105)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:142)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316)
	at com.home.liquibasetest.LiquibasetestApp.main(LiquibasetestApp.java:65)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49)
Caused by: liquibase.exception.MigrationFailedException: Migration failed for change set config/liquibase/changelog/20190719225630_added_entity_Money.xml::20190719225630-1-data::jhipster:
     Reason: liquibase.exception.DatabaseException: java.sql.BatchUpdateException: Batch entry 0 INSERT INTO public.money(id, count, name, purse_id) VALUES(1, 37454, 'Directives application Home Loan Account', '1') was aborted: ERROR: column "purse_id" is of type bigint but expression is of type character varying
  Подсказка: You will need to rewrite or cast the expression.
  Позиция: 72  Call getNextException to see other errors in the batch.
	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:637)
	at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:53)
	at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:83)
	at liquibase.Liquibase.update(Liquibase.java:202)
	at liquibase.Liquibase.update(Liquibase.java:179)
	at liquibase.integration.spring.SpringLiquibase.performUpdate(SpringLiquibase.java:353)
	at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:305)
	at io.github.jhipster.config.liquibase.AsyncSpringLiquibase.initDb(AsyncSpringLiquibase.java:100)
	at io.github.jhipster.config.liquibase.AsyncSpringLiquibase.afterPropertiesSet(AsyncSpringLiquibase.java:90)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1837)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1774)
	... 21 common frames omitted
Caused by: liquibase.exception.DatabaseException: java.sql.BatchUpdateException: Batch entry 0 INSERT INTO public.money(id, count, name, purse_id) VALUES(1, 37454, 'Directives application Home Loan Account', '1') was aborted: ERROR: column "purse_id" is of type bigint but expression is of type character varying
  Подсказка: You will need to rewrite or cast the expression.
  Позиция: 72  Call getNextException to see other errors in the batch.
	at liquibase.statement.ExecutablePreparedStatementBase.execute(ExecutablePreparedStatementBase.java:86)
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:115)
	at liquibase.database.AbstractJdbcDatabase.execute(AbstractJdbcDatabase.java:1229)
	at liquibase.database.AbstractJdbcDatabase.executeStatements(AbstractJdbcDatabase.java:1211)
	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:600)
	... 31 common frames omitted
Caused by: java.sql.BatchUpdateException: Batch entry 0 INSERT INTO public.money(id, count, name, purse_id) VALUES(1, 37454, 'Directives application Home Loan Account', '1') was aborted: ERROR: column "purse_id" is of type bigint but expression is of type character varying
  Подсказка: You will need to rewrite or cast the expression.
  Позиция: 72  Call getNextException to see other errors in the batch.
	at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:148)
	at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:824)
	at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1538)
	at com.zaxxer.hikari.pool.ProxyStatement.executeBatch(ProxyStatement.java:128)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeBatch(HikariProxyPreparedStatement.java)
	at liquibase.statement.BatchDmlExecutablePreparedStatement.executePreparedStatement(BatchDmlExecutablePreparedStatement.java:65)
	at liquibase.statement.ExecutablePreparedStatementBase.execute(ExecutablePreparedStatementBase.java:84)
	... 35 common frames omitted
Caused by: org.postgresql.util.PSQLException: ERROR: column "purse_id" is of type bigint but expression is of type character varying
  Подсказка: You will need to rewrite or cast the expression.
  Позиция: 72
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308)
	at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:821)
	... 40 common frames omitted
~~~

##### **Motivation for or Use Case**

The error is critical, as for the need to migrate directories in the database

##### **Reproduce the error**

1. Add a foreign key to the CSV file

~~~csv
id;count;name;purse_id
1;37454;Directives application Home Loan Account;1
2;15601;Computer Practical Fresh Pants;2
3;60111;alarm;3
4;2058;Producer;4
~~~

2) run the application

##### **Related issues**

NO

##### **Suggest a Fix**

File entity_money.xml

    <changeSet id="20190719225630-1-data" author="jhipster" context="faker">
     ...................
            <column name="name" type="string"/>
   ...............................

add to line   

column name="purse_id" type="numeric"

##### **JHipster Version(s)**

jhipster@6.0.1 

##### **JHipster configuration**

INFO! Using JHipster version installed locally in current project's node_modules
INFO! Executing jhipster:info
INFO! Options: from-cli: true
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
liquibasetest@0.0.0 /home/kirill/liquibasetest
└── generator-jhipster@6.0.1 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.home.liquibasetest"
    },
    "jhipsterVersion": "6.0.1",
    "applicationType": "microservice",
    "baseName": "liquibasetest",
    "packageName": "com.home.liquibasetest",
    "packageFolder": "com/home/liquibasetest",
    "serverPort": "8081",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": "consul",
    "buildTool": "gradle",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": false,
    "clientPackageManager": "npm",
    "skipClient": true,
    "skipUserManagement": true
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Money {
  count Integer,
  name String
}
entity Purse {
  name String
}
relationship OneToMany {
  Purse{money} to Money{purse}
}

microservice Money, Purse with liquibasetest
clientRootFolder Money, Purse with liquibasetest

</pre>
</details>

##### **Environment and Tools**

java version "11.0.2" 2019-01-15 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.2+9-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.2+9-LTS, mixed mode)

git version 2.17.1

node: v8.10.0

npm: 3.5.2

yeoman: 2.0.6

Docker version 18.09.8, build 0dd43dd87f

docker-compose version 1.24.0, build 0aa59064

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

~~~json

{
    "name": "Money",
    "fields": [
        {
            "fieldName": "count",
            "fieldType": "Integer"
        },
        {
            "fieldName": "name",
            "fieldType": "String"
        }
    ],
    "relationships": [
        {
            "relationshipName": "purse",
            "otherEntityName": "purse",
            "relationshipType": "many-to-one",
            "otherEntityField": "id"
        }
    ],
    "changelogDate": "20190719225630",
    "entityTableName": "money",
    "dto": "no",
    "pagination": "no",
    "service": "no",
    "jpaMetamodelFiltering": false,
    "fluentMethods": true,
    "clientRootFolder": "liquibasetest",
    "applications": "*",
    "microserviceName": "liquibasetest"
}
~~~

~~~json
{
    "name": "Purse",
    "fields": [
        {
            "fieldName": "name",
            "fieldType": "String"
        }
    ],
    "relationships": [
        {
            "relationshipType": "one-to-many",
            "otherEntityName": "money",
            "otherEntityRelationshipName": "purse",
            "relationshipName": "money"
        }
    ],
    "changelogDate": "20190719225631",
    "entityTableName": "purse",
    "dto": "no",
    "pagination": "no",
    "service": "no",
    "jpaMetamodelFiltering": false,
    "fluentMethods": true,
    "clientRootFolder": "liquibasetest",
    "applications": "*",
    "microserviceName": "liquibasetest"
}
~~~

##### **Browsers and Operating System**

Ubuntu 18.06

-   [+]

 Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment] 2019-07-20 10:47
As you're using JHipster v6.0.1, I suggest you to upgrade to v6.1.2 as some issues related to faker.js have been fixed.

Then, about your issue, I tried to generate a project with JHipster 6.1.2
- without modification : no issue
- using your modification: it failed and it's normal

You tried to insert money data before purse data. And by adding the relationship, purse doesn't exist and that's why it failed. You should try to change the order in your master.xml config

So I'm closing this because:
- no issue with your config with the default generated code
- it should go to stackoverflow instead

**Comment by kirill-kobzev** [comment] 2019-07-20 11:44
Update version did not help.
Default data in SCV file is unrelated
When you create the entity.xml file in the / src / main / resources / config / liquibase / changelog folder
There is no numeric foreign key type in loadData

If you add a foreign key to the CSV file
Then, when starting the application, a type mismatch error occurs

**Comment by kirill-kobzev** [comment] 2019-07-20 11:49
change this code   
 <changeSet id="20190720111656-1-data" author="jhipster" context="faker">
        <loadData
                  file="config/liquibase/data/money.csv"
                  separator=";"
                  tableName="money"
                  context="dev">
            <column name="id" type="numeric"/>
            <column name="count" type="numeric"/>
            <column name="name" type="string"/>
        </loadData>
    </changeSet>

on this
    <changeSet id="20190720111656-1-data" author="jhipster" context="faker">
        <loadData
                  file="config/liquibase/data/money.csv"
                  separator=";"
                  tableName="money"
                  context="dev">
            <column name="id" type="numeric"/>
            <column name="count" type="numeric"/>
            <column name="name" type="string"/>
            <column name="purse_id" type="numeric"/>
        </loadData>
    </changeSet>

and the type mismatch error will disappear

**Comment by gmarziou** [comment] 2019-07-20 13:26
> When you create the entity.xml file in the / src / main / resources / config / liquibase / changelog folder
> There is no numeric foreign key type in loadData

Yes because relationship is not marked as required in your JDL.

> If you add a foreign key to the CSV file
> Then, when starting the application, a type mismatch error occurs

I suppose,you mean adding `required` to relationship  and then re-importing JDL.

~~~
entity Money {
  count Integer,
  name String
}
entity Purse {
  name String
}
relationship OneToMany {
  Purse{money} to Money{purse required} 
}
~~~

I did it with JHipster 6.1.2 and it worked well 

20190720131402_added_entity_Money.xml

~~~xml
    <changeSet id="20190720131402-1-data" author="jhipster" context="faker">
        <loadData
                  file="config/liquibase/data/money.csv"
                  separator=";"
                  tableName="money">
            <column name="id" type="numeric"/>
            <column name="count" type="numeric"/>
            <column name="name" type="string"/>
            <column name="purse_id" type="numeric"/>
            <!-- jhipster-needle-liquibase-add-loadcolumn - JHipster (and/or extensions) can add load columns here, do not remove-->
        </loadData>
    </changeSet>
~~~

and money.csv

~~~csv
id;count;name;purse_id
1;37454;Directives application Home Loan Account;2
~~~

Have you verified that you did not reference old entity files, I had 2 version of `*_added_entity_Money.xml` in my folder: the old one and the new one, and `master.xml` was referencing the 2 versions. This is the real problem and a major one for me.  I was expecting that the  migrations would have been replaced and not duplicated. @pascalgrimaud is it the expected behavior?

**Comment by gmarziou** [comment] 2019-07-20 14:02
Here is a simpler way to reproduce.

1. Generate an app
2. Write a JDL file `one.jdl` that defines a single entity

~~~
entity Money {
  name String
}
~~~


3. Import it twice with `jhipster import-jdl one.jdl` => you get 2 migrations for same entity and they are both referenced in master.xml: `20190720135340_added_entity_Money.xml`    and `20190720135358_added_entity_Money.xml `

**Comment by pascalgrimaud** [comment] 2019-07-20 14:26
@gmarziou :
- about the duplicated diff, it should be resolved. See the ticket https://github.com/jhipster/generator-jhipster/issues/9996
- about the required, I think it's mentionned in this ticket https://github.com/jhipster/generator-jhipster/issues/9579

**Comment by pascalgrimaud** [comment] 2019-07-20 14:29
You can look at the master.xml file of the generated project: 
https://github.com/pascalgrimaud/jhipster-sample-application190720/pull/1/files

Money is before Purse, so you can't insert data Money with FK Purse, as it won't exist

**Comment by gmarziou** [comment] 2019-07-20 15:20
I tried to test with master on generator-jhipster and jhipster-core, I npm linked both but I got same behavior with duplicated migrations. So maybe it's my way of doing, I admit I have never worked with jhipster-core on master and its [contributing guide](https://github.com/jhipster/jhipster-core/blob/master/CONTRIBUTING.md) does not cover this part.

Beside that I did not get the message about no change in entity when re-importing same file, in 5.8.2  it was working, with current master it does not.

In 5.8.2
~~~
INFO! The JDL is being parsed.
INFO! No change in entity configurations, no entities were updated.                                                     INFO! The JDL has been successfully parsed 
~~~

**Comment by MathieuAA** [comment] 2019-07-21 08:14
I'll test this out

**Comment by pascalgrimaud** [comment] 2019-08-12 06:01
For me, there is no issue as there were some modifications in the generated code. The modifications are not correct and don't respect the correct order.

If someone can generate a project + entities without modification, I can have a look

**Comment by pascalgrimaud** [comment] 2019-08-16 05:41
As previously, I'm closing this because there is no issue with the orignal config with the default generated code

**Closed by pascalgrimaud** 2019-08-16 05:41 UTC
Labels: area: waiting for information, theme: faker.js, theme: relationships
