### ISSUE TITLE
upgrade force option does not work on jhipster modules

### ISSUE THREAD

**Issue by alireza-hanifi** [jhipster/generator-jhipster#3665] opened 2016-05-30 12:27 UTC
##### **Overview of the issue**
when we upgrade application, the process hangs at module overwrite questions.
my modules: basic-auth, entity-audit

##### **Motivation for or Use Case** 
yo jhipster:upgrade --force

##### **JHipster Version(s)** 
3.4.0

##### **Browsers and Operating System** 

ubuntu

**Comment by deepu105** [comment] 2016-05-30 16:10
Does it work on an app without any modules?  Ideally this shouldn't affect
modules or vice versa. Do you see any error trace?

**Comment by deepu105** [comment] 2016-05-30 16:10
Also please provide your app s yo-rc file etc

**Comment by alireza-hanifi** [comment] 2016-05-31 06:03
{
  "generator-jhipster": {
    "jhipsterVersion": "3.1.0",
    "baseName": "gunsnheroes",
    "packageName": "com.arvand.gunsnheroes",
    "packageFolder": "com/arvand/gunsnheroes",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": "no",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "rememberMeKey": "9321fe3cf0249ca9459ea846950932b4451b92d4",
    "useSass": false,
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling"
    ],
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ],
    "jhiPrefix": "jhi"
  },
  "generator-jhipster-entity-audit": {
    "auditFramework": "custom"
  }
}

**Comment by alireza-hanifi** [comment] 2016-05-31 06:14
yes it upgrades when i removed modules from project.
no, it hasn't error. just it pauses on overwrite questions. and i can't enter Y or n.

**Comment by cbornet** [comment] 2016-05-31 06:20
Does it ask question if you do yo jhipster-basic-auth --force ?

**Comment by alireza-hanifi** [comment] 2016-05-31 08:48
no, it doesn't ask. the problem is on jhipster upgrade with basic-auth.

**Comment by deepu105** [comment] 2016-06-04 12:50
could you try to pinpoint the exact issue combination as you have both entity audit module and basic auth. can you try on a fresh app with either one of the module and see which module is causing the issue so that we can investigate

**Comment by deepu105** [comment] 2016-06-08 10:58
@alireza-hanifi we will close this ticket if further info is not provided, so please provide info asked above if you want us to investigate

**Comment by alireza-hanifi** [comment] 2016-06-08 20:42
@deepu105 The main issue is that when I use either of these modules and upgrade the program, it askes for confirmation using the terminal when overwriting files and since it's running on another process I'm unable to confirm, even when I use force option, it's still held up behind the confirmation requests.

**Comment by deepu105** [comment] 2016-06-09 02:37
Ok understood ill take a look

**Comment by deepu105** [comment] 2016-06-09 05:14
could you check with the current master branch if it works now for you?

**Closed** 2016-06-09 05:14 UTC
Labels: bug

**Comment by pascalgrimaud** [comment] 2016-06-09 06:30
Maybe it's not related to module, the sub generator doesn't work for me (or maybe I'm doing something wrong). My steps:
1) create folder, and git init: `mkdir test && cd test`
2) generate a fresh project, all default option: `yo jhipster`
3) create a simple "hello.txt" file: `echo "hello" > hello.txt`
4) commit: `git add . && git commit -m "Initial commit"`
5) then, launch: `yo jhipster:upgrade --force`
6) the file "hello.txt" has been deleted

I think the problem comes from: starting in a new branch, with only .yo-rc.json and .git (all history), after generation, I got:
```
diff --git a/hello.txt b/hello.txt
deleted file mode 100644
index ce01362..0000000
--- a/hello.txt
+++ /dev/null
@@ -1 +0,0 @@
-hello
```

**Comment by deepu105** [comment] 2016-06-09 06:38
@pascalgrimaud I understand I guess the problem is since we delete all files before generation when we commit the generated code which woul have a newer time stamp it would be considered as a override when merging back and hence deleting stuff in the original branch which was custom files.

I think we should find a way to regenerate without deleting files which are not generated by JHipster. Can you open a new issue for this.
