### ISSUE TITLE
missing end of sentence

### ISSUE THREAD

**Issue by mattboll** [jhipster/generator-jhipster#5717] opened 2017-05-05 13:51 UTC
In _activate.json there is this message :
"success": "<strong>Your user account has been activated.</strong> Please ",

It misses the end of the sentance which should be something such as "Please login"

**Comment by jdubois** [comment] 2017-05-05 13:52
This ticket has been closed as the guidelines are not followed.

Tickets must follow our [Guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#submitting-an-issue), as mentioned in:

1. our [Readme file on the front page of the project](https://github.com/jhipster/generator-jhipster/blob/master/README.md), 
2. the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) and
3. our [Help page](http://jhipster.github.io/help/)

We have also created a template on the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) to help you follow those guidelines.

**Comment by jdubois** [comment] 2017-05-05 13:53
I'm pretty sure I've already seen this error, but if you don't follow the guidelines it's impossible for anyone to work on this

**Closed by jdubois** 2017-05-05 13:52 UTC

**Comment by jdubois** [comment] 2017-05-05 13:54
Could you write this again, following the guidelines?

**Comment by deepu105** [comment] 2017-05-05 16:21
Its on purpose as the login text is a link and ng2 translate cant do interpolations on these

**Comment by tezcane** [comment] 2017-05-05 16:30
I had reported this before but was told here it is expected behavior.  I thought I had broken the code somehow and didn't investigate further.  However, I believe it is a bug since it is showing up for other people too.  The issue is not just in the translation file (I think this is what is assumed right now), it actually shows up when the server is running... "Please" is how the sentenced ends, their is no link afterwards.

**Comment by deepu105** [comment] 2017-05-07 10:20
Are you guys talking about content in the json or are yih talking about the displayed text on the ui page? If its in the json its intentional but if its in the rendered ui then its an issue

**Comment by tezcane** [comment] 2017-05-07 15:52
Displayed text on the UI page.
