### ISSUE TITLE
Jhipster swagger-ui not showing documentation in gateway

### ISSUE THREAD

**Issue by jkoorts** [jhipster/generator-jhipster#9999] opened 2019-06-27 10:45 UTC
##### **Overview of the issue**

I follow https://www.baeldung.com/jhipster-uaa-secured-micro-service which means I have a registry, uaa, gateway and microservice. 
I login admin/admin
I click Administration, I click API
I see the dev ribbon, a swagger.io hyperlink. A dropdown box that is EMPTY and a textbox which is also empty.

Where is the API's in Swagger UI format?

When I go Administration - Gateway I see the uaa and my diagnostics url
When I go http://10.0.75.1:8081/v2/api-docs (which is the diagnostics microservice) i see the API in json format.

##### **Motivation for or Use Case**

JHipster docs said it would work

##### **Reproduce the error**

Follow https://www.baeldung.com/jhipster-uaa-secured-micro-service

##### **Related issues**

Someone else had the same issue in 2018 was never resolved

##### **Suggest a Fix**

I'm stumped what the issue is, but I might add that the UI in Admin -> API with empty fields already looks unintuitive to me. I mean why is the swagger in hyperlink? Why no labels on the combobox and textbox?

##### **JHipster Version(s)**

Latest

##### **JHipster configuration**

INFO! Using JHipster version installed locally in current project's node_modules
INFO! Executing jhipster:info
INFO! Options: from-cli: true
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
gateway@0.0.0 C:\dev\java\myproject\gateway
`-- generator-jhipster@6.1.1

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.hex"
    },
    "jhipsterVersion": "6.1.1",
    "applicationType": "gateway",
    "baseName": "gateway",
    "packageName": "com.hex",
    "packageFolder": "com/hex",
    "serverPort": "8080",
    "authenticationType": "uaa",
    "uaaBaseName": "uaa",
    "cacheProvider": "ehcache",
    "enableHibernateCache": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "angularX",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": false
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Diagnostics {
  model String required unique,
  created ZonedDateTime required
}
dto Diagnostics with mapstruct
paginate Diagnostics with pagination
service Diagnostics with serviceImpl
microservice Diagnostics with diagnostics
filter Diagnostics
clientRootFolder Diagnostics with diagnostics

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_211"
Java(TM) SE Runtime Environment (build 1.8.0_211-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.211-b12, mixed mode)

git version 2.21.0.windows.1

node: v10.15.3

npm: 6.4.1

yeoman: 2.0.6

yarn: 1.16.0

Docker version 18.09.2, build 6247962

docker-compose version 1.23.2, build 1110ad01

INFO! Congratulations, JHipster execution is complete!

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

{
    "name": "Diagnostics",
    "fields": [
        {
            "fieldName": "model",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "unique"
            ]
        },
        {
            "fieldName": "created",
            "fieldType": "ZonedDateTime",
            "fieldValidateRules": [
                "required"
            ]
        }
    ],
    "relationships": [],
    "changelogDate": "20190627070749",
    "entityTableName": "diagnostics",
    "dto": "mapstruct",
    "pagination": "pagination",
    "service": "serviceImpl",
    "jpaMetamodelFiltering": true,
    "fluentMethods": true,
    "clientRootFolder": "diagnostics",
    "applications": "*",
    "microserviceName": "diagnostics"
}

##### **Browsers and Operating System**

Windows 10

-   [x ] Checking this box is mandatory (this is just to show you read everything) 
<img width="185" alt="pic2" src="https://user-images.githubusercontent.com/10402021/60260297-7fbe1680-98d9-11e9-8ef9-c025bf7327a6.png">

<img width="735" alt="pic1" src="https://user-images.githubusercontent.com/10402021/60260453-f0653300-98d9-11e9-9e35-17f18742544e.png">

**Comment by mraible** [comment] 2019-06-27 12:44
Can you try it with JHipster 5? Since the Baeldung tutorial was last updated "February 24, 2019", I'm guessing it uses JHipster 5.

**Comment by pascalgrimaud** [comment] 2019-06-28 09:59
Just tried to reproduce with JHipster 6.1.2 and it works fine.
I can see Swagger API without problem.
Can you provide more information / exact steps to reproduce ? Or try JHipster 6 ?

**Comment by jkoorts** [comment] 2019-06-28 10:23
Let me check

**Comment by jkoorts** [comment] 2019-06-28 12:05
Right, I had another go at it. I followed it step by step, and I think now the problem lies with jhispter import-jdl. 

It does not create my liquidbase/dto/service/entities:

From baeldung:

entity Quote {
  symbol String required unique,
  price BigDecimal required,
  lastTrade ZonedDateTime required
}
dto Quote with mapstruct
paginate Quote with pagination
service Quote with serviceImpl
microservice Quote with quotes
filter Quote
clientRootFolder Quote with quotes

Then I run:

C:\dev\java\demo\oemgateway>jhipster import-jdl quotes.jh

I get:

INFO! Using JHipster version installed globally
INFO! Executing import-jdl quotes.jh
INFO! Options: from-cli: true
INFO! Found .yo-rc.json on path. This is an existing app
INFO! The JDL is being parsed.
info: JPAMetaModelFiltering has been detected for Quote, the 'serviceClass' value for the 'service' is gonna be set for this entity if no other value has been set.
info: The DTO option has been detected to be set for Quote, the 'serviceClass' value for the 'service' is gonna be set for this entity if no other value has been set.
INFO! No change in entity configurations, no entities were updated.
INFO! The JDL has been successfully parsed

<img width="492" alt="Untitled" src="https://user-images.githubusercontent.com/10402021/60341056-8cac3a00-99ad-11e9-9655-6e71934a231e.png">


Here some extra info:

{
  "name": "oemgateway",
  "version": "0.0.0",
  "description": "Description for oemgateway",
  "private": true,
  "license": "UNLICENSED",
  "cacheDirectories": [
    "node_modules"
  ],
  "devDependencies": {
    "generator-jhipster": "6.1.2"
  },
  "engines": {
    "node": ">=8.9.0"
  }
}


{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.hex"
    },
    "jhipsterVersion": "6.1.2",
    "applicationType": "microservice",
    "baseName": "oemgateway",
    "packageName": "com.hex",
    "packageFolder": "com/hex",
    "serverPort": "8081",
    "authenticationType": "uaa",
    "uaaBaseName": "uaa",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "NjA0NDcwYTU1YTE5YmY0ZDg5YTYwYTYwYWY0MGU1N2RjYTdjY2NmMzBlNzZhYjA4MmFmMTc1ZGNjZjdhOTQ2YTVjYWRlZDdiZjA3ZWFlNzEyMjQyZTI0ZWM2ZmQ0Mzg4ODg4YTY2MDBiZjZlMTY4ZjA5NmJiOWM5MDU5ZDAxNGI=",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": false,
    "clientPackageManager": "npm",
    "skipClient": true,
    "skipUserManagement": true
  }
}

btw I'm using mysql

**Comment by jkoorts** [comment] 2019-06-28 12:18
Ok created the entity via "jhipster entity" since the "jhipster import-jdl" seems broken.

Started the microservice up, and the result is the same as in my initial bug report. 

Here screenshots:

<img width="772" alt="Untitled" src="https://user-images.githubusercontent.com/10402021/60341643-77d0a600-99af-11e9-90a7-b6c1f7bae643.png">
<img width="161" alt="Untitled1" src="https://user-images.githubusercontent.com/10402021/60341656-8a4adf80-99af-11e9-9702-23f55325b9dd.png">

What else can I do to help? I can zip and email everything - its just a copy of the baeldung samples

**Comment by jkoorts** [comment] 2019-06-28 12:19
Just a note I did not "7.2. Adding the Quotes UI" part of the UI. Not needed to see Swagger UI

**Comment by clement26695** [comment] 2019-07-11 15:09
For me, everything looks fine. I created 3 folders:

1. Microservice folder (/m1) with:

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.hex"
    },
    "jhipsterVersion": "6.1.2",
    "applicationType": "microservice",
    "baseName": "oemgateway",
    "packageName": "com.hex",
    "packageFolder": "com/hex",
    "serverPort": "8081",
    "authenticationType": "uaa",
    "uaaBaseName": "uaa",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": false,
    "clientPackageManager": "npm",
    "skipClient": true,
    "skipUserManagement": true,
    "blueprints": []
  }
}
</pre>
</details>

2. Gateway folder (/gateway) with:

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "io.github.jhipster.registry",
      "nativeLanguage": "en",
      "microservicePath": "../m1"
    },
    "jhipsterVersion": "6.1.2",
    "applicationType": "gateway",
    "baseName": "gateway",
    "packageName": "io.github.jhipster.registry",
    "packageFolder": "io/github/jhipster/registry",
    "serverPort": "8080",
    "authenticationType": "uaa",
    "uaaBaseName": "uaa",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "angularX",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": ["en"],
    "blueprints": []
  }
}

</pre>
</details>

3. UAA folder (/uaa) with:

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "io.github.jhipster.registry",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "6.1.2",
    "applicationType": "uaa",
    "baseName": "uaa",
    "packageName": "io.github.jhipster.registry",
    "packageFolder": "io/github/jhipster/registry",
    "serverPort": "9999",
    "authenticationType": "uaa",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": true,
    "clientPackageManager": "npm",
    "nativeLanguage": "en",
    "languages": [
      "en"
    ],
    "blueprints": [],
    "skipClient": true
  }
}
</pre>
</details>

You can run `jhipster` in each 3 folder to generate each app.

You can then create an entity in your microservice. Create the JDL file (entities.jdl):
<details>
<summary>JDL entity definitions</summary>

<pre>
entity Post {
  name String
}
entity Quote {
  symbol String required unique,
  price BigDecimal required,
  lastTrade ZonedDateTime required
}
microservice Post, Quote with oemgateway
clientRootFolder Post, Quote with oemgateway
dto Quote with mapstruct
paginate Quote with pagination
service Quote with serviceImpl
filter Quote

</pre>
</details>

And then run the command: `jhipster import-jdl entities.jdl`

You can then run the 3 application, after starting a mysql server for your microservice, and a jhipster-registry, by running (inside your microservice folder):

`docker-compose -f src/main/docker/jhipster-registry.yml up -d`
`docker-compose -f src/main/docker/mysql.yml up -d`

Once connected to my app (http://localhost:8080/admin/docs), I was able to see the resources I created:
![image](https://user-images.githubusercontent.com/25530077/61062453-8f238080-a3fe-11e9-9fb5-ae8509ecef13.png)

**Comment by clement26695** [comment] 2019-07-11 15:12
Note that I had to change the JDL file given by baeldung by replacing "quotes" by your application name:

```
entity Quote {
    symbol String required unique,
    price BigDecimal required,
    lastTrade ZonedDateTime required
}
dto Quote with mapstruct
paginate Quote with pagination
service Quote with serviceImpl
microservice Quote with quotes
filter Quote
clientRootFolder Quote with quotes
```

to 

```
entity Quote {
    symbol String required unique,
    price BigDecimal required,
    lastTrade ZonedDateTime required
}
dto Quote with mapstruct
paginate Quote with pagination
service Quote with serviceImpl
microservice Quote with oemgateway
filter Quote
clientRootFolder Quote with oemgateway
```

**Comment by clement26695** [comment] 2019-08-02 08:20
@jkoorts Do you have any update on this? If you don't face the issue anymore, I think we can close this issue

**Comment by jkoorts** [comment] 2019-08-02 08:32
I will have another go at it. I think I first have to figure out how to create a node environment used just for jhipster so that other software don't try to upgrade parts of it - creating I think this issue. 

Give me until monday please.

**Comment by jkoorts** [comment] 2019-08-07 15:10
With a fresh environment it works now thanks. I'll reopen once I have pin point the issue.

cheers

**Comment by pascalgrimaud** [comment] 2019-08-11 06:47
As it works fine, I think we can close this now.
Don't hesitate to comment and provide all information + steps if you think there is still an issue

**Closed by pascalgrimaud** 2019-08-11 06:47 UTC
Labels: area: waiting for information, theme: uaa
