### ISSUE TITLE
MS SQL Server (etc.) support

### ISSUE THREAD

**Issue by piprog** [jhipster/generator-jhipster#1185] opened 2015-02-25 09:47 UTC
What would it take to implement support for MS SQL Server (or other RDBMSes)? We are right now working on a project with a client req on the above and wonder how would one go about adding generator support...

**Comment by jdubois** [comment] 2015-02-25 10:06
It probably wouldn't be very difficult, but I will not do it myself as this is a proprietary database on Windows, and I have no money to buy those (and I don't have much interest or need to work on SQL Server anyway).

What would need to be done:

- Configure the datasource
- Change the Hibernate dialect
- Modify and test the Liquibase changelog

If you want to do it, it could be merged in the main generator, with 2 conditions:

- I can't test or support it, so it will be marked with some kind of warning (I normally test everything)
- It needs to work with 100% Open Source librairies, but I think the SQL Server driver is Open Source, so that would be OK (that's the issue we have with Oracle -> we can't have a Maven dependency to their driver)

**Comment by piprog** [comment] 2015-02-25 11:21
Thanks Julien for the quick reply. I was expecting something along the those lines... :) At the moment I hope that someone will turn up with more experience with jhipster, if not then we may give it a shot. Are you aware of any such 3rd party RDBMS integration that is OSS for a template?

**Comment by jdubois** [comment] 2015-02-26 16:52
Hi @piprog no I don't know any OSS project doing this. It would be very surprising.

**Closed by jdubois** 2015-02-26 16:52 UTC

**Comment by Grant-Lay** [comment] 2015-06-30 07:17
FYI since adding oracle support in 2.16, each liquibase added_entity script has the following added to it:

<property name="now" value="now()" dbms="mysql,h2"/>
<property name="now" value="current_timestamp" dbms="postgresql"/>
<property name="now" value="sysdate" dbms="oracle"/>

<property name="autoIncrement" value="true" dbms="mysql,h2,postgresql"/>
<property name="autoIncrement" value="false" dbms="oracle"/>

Which means that we need to modify each script if using mssql to be : 

<property name="now" value="now()" dbms="mysql,h2"/>
<property name="now" value="current_timestamp" dbms="postgresql"/>
<property name="now" value="sysdate" dbms="oracle"/>
<property name="now" value="GETDATE()" dbms="mssql"/>

<property name="autoIncrement" value="true" dbms="mysql,h2,postgresql,mssql"/>
<property name="autoIncrement" value="false" dbms="oracle"/>

I understand the unwillingness to not have to support every propriety database, but now that JHipster provides support to Oracle, does it not make sense to support sql server as well?

**Comment by jdubois** [comment] 2015-07-03 16:06
@Grant-Lay the MS SQL Server support is only in the tips section: http://jhipster.github.io/tips/004_tip_using_ms_sql_server.html

-> normally that should work out for you, otherwise don't hesitate to improve the tip!

Yes Oracle is now included in the generator, but this is only because it was submitted this way. I can't support any of those databases, as I don't have the licences, so it depends of what people propose.

Oracle support should also be better as:
- more people use it
- I should be able to test it using VirtualBox (it doesn't work on Mac OS X, which I use)

**Comment by deepu105** [comment] 2015-07-04 04:48
@grant-lay ms sql was a tip coz the changes you need to do are minimal and one time if im not wrong, for oracle its more complicated and would require changes in each entity liquibase file as well as name length and stuff thats why i submitted it as a generator option rather than a tip, else i also agree with jdubois that we shouldn't be doing non oss stuff

**Comment by gpulluri** [comment] 2015-09-25 01:27
I would vote for mssql support to be included. As far as licenses are concerned SQL server express 2014 and SQL server management studio are free. So testing should not be a problem. 

The most important reason however is the incredible amount of free credits that Microsoft offers to startups. The only viable option to use the credits is to use Azure SQL (the 3rd party mysql offering "cleardb" is extremely horrible). 

I just started experimenting with MSSQL and I am trying to fix the issues that I encounter. I think its worthwhile to support it. Please let me know what you guys think.

**Comment by deepu105** [comment] 2015-09-25 01:43
Have you looked at the tips, it has a page on how to add ms sql support,
its quite straight forward unlike oracle

**Comment by gpulluri** [comment] 2015-09-25 02:07
Yes. The server starts up fine. However, there is an error when writing to the audit table, 

Code:
====
@Override
@Transactional(propagation = Propagation.REQUIRES_NEW)
public void add(AuditEvent event) {
	....
	....
	persistenceAuditEventRepository.save(persistentAuditEvent);
}


Error:
====
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Cannot insert the value NULL into column 'event_id', table 'filmext.dbo.JHI_PERSISTENT_AUDIT_EVENT'; column does not allow nulls. INSERT fails.

This I guess is because of the auto increment not working (not sure). 
I tried changing the auto increment property to include mssql like below but then I was getting an error saying identity insert is set to off. I am trying to figure things out but this is the first time I am playing with sql server. 

<property name="autoIncrement" value="true" dbms="mysql,mssql,h2,postgresql"/>

**Comment by jdubois** [comment] 2015-09-25 07:39
@gpulluri  I'm not sure we have same idea of what a "free" licence is...

**Comment by putssander** [comment] 2016-01-20 15:36
@gpulluri Today I got JHipster v2.27.0 running with MSSQL

I followed the tutorial https://jhipster.github.io/tips/004_tip_using_ms_sql_server.html and got the same error message "Cannot insert the value NULL into column 'event_id'.

The error is caused by copying the snippet 00000000000000_initial_schema.xml of the tutorial which overwrites autoIncrement (mssql has to be added).
<property name="autoIncrement" value="true" dbms="mysql,h2,postgresql,oracle,mssql"/> 

After this change, the 'event_id' was generated and events inserted, but .cvs files with users and roles where not loaded.

After correcting the databaseChangeLog and updating to the latest maven dependency for https://github.com/sabomichal/liquibase-mssql (version 1.5) this worked as well.

<databaseChangeLog
    xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
    xmlns:ext="http://www.liquibase.org/xml/ns/dbchangelog-ext"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.4.xsd
    http://www.liquibase.org/xml/ns/dbchangelog-ext http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-ext.xsd">


<dependency>
    <groupId>com.github.sabomichal</groupId>
    <artifactId>liquibase-mssql</artifactId>
    <version>1.5</version>
</dependency>

**Comment by deepu105** [comment] 2016-01-21 00:44
Would you like to do a PR to update the tip?

**Comment by cbornet** [comment] 2016-01-21 09:14
Or maybe create a module ?

**Comment by putssander** [comment] 2016-01-25 11:52
I will make a PR for the tip this week and will try to make a module later (was dedicated to get jhipster running on mssql for work, won't use mssql in personal projects).

**Comment by buminda** [comment] 2016-04-07 00:08
Yes, as commented putssander , adding the following line to initial_schema.xml will solve the issue, 

<property name="autoIncrement" value="true" dbms="mysql,h2,postgresql,oracle,mssql"/>

"Cannot insert the value NULL into column 'event_id'. for mssql server.

**Comment by edwardbeckett** [comment] 2017-01-20 01:43
FWIW ~  I manually scripted both `dbo.jhi_persistent_audit_evt_data` and `dbo.jhi_persistent_audit_event` to a new query window in SQL Server Management Studio. Then modified dbo.jhi_persistent_audit_evt_data.event_id to add `IDENTITY(1,1)` 

After dropping them and then adding `IDENTITY` the app seems too be working okay now... ( ymmv )

[Modification Script](https://gist.github.com/edwardbeckett/ee67d0b9fc7252365617fa8fb33b27dd)

> USE [Foo]
> GO
> SET ANSI_NULLS ON
> GO
> 
> SET QUOTED_IDENTIFIER ON
> GO
> 
> CREATE TABLE [dbo].[jhi_persistent_audit_event](
> 	[event_id] [bigint] IDENTITY(1,1) NOT NULL,
> 	[principal] [varchar](50) NOT NULL,
> 	[event_date] [datetime] NULL,
> 	[event_type] [varchar](255) NULL,
>  CONSTRAINT [PK_JHI_PERSISTENT_AUDIT_EVENT] PRIMARY KEY CLUSTERED 
> (
> 	[event_id] ASC
> )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
> ) ON [PRIMARY]
> 
> GO
> 
> CREATE TABLE [dbo].[jhi_persistent_audit_evt_data](
> 	[event_id] [bigint] NOT NULL,
> 	[name] [varchar](150) NOT NULL,
> 	[value] [varchar](255) NULL,
> PRIMARY KEY CLUSTERED 
> (
> 	[event_id] ASC,
> 	[name] ASC
> )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
> ) ON [PRIMARY]
> 
> GO
> 
> ALTER TABLE [dbo].[jhi_persistent_audit_evt_data]  WITH CHECK ADD  CONSTRAINT [fk_evt_pers_audit_evt_data] FOREIGN KEY([event_id])
> REFERENCES [dbo].[jhi_persistent_audit_event] ([event_id])
> GO
> 
> ALTER TABLE [dbo].[jhi_persistent_audit_evt_data] CHECK CONSTRAINT [fk_evt_pers_audit_evt_data]
> GO
