### ISSUE TITLE
Unable to start jhipster project on CloudFoundry

### ISSUE THREAD

**Issue by dancancro** [jhipster/generator-jhipster#1439] opened 2015-05-04 09:38 UTC
Hi everyone,

I'm following the bookstore example from the [tutorial](http://jhipster.github.io/video_tutorial.html) (great job on that, btw!).

The app ran fine in development mode locally, but not when deployed to CloudFoundry.  In that case, I just get a 404 and nothing useful in the logs.

Here is the [log](https://gist.github.com/dancancro/0a4eb5aa8b785f411f79).

Also, could anyone explain how to serve the frontend locally in production mode?  I ran `mvn -Pprod spring-boot:run` to get the production API going. `gulp build` creates the production frontend, but doesn't serve it.  `gulp serve` serves the frontend development files.

One other thing, to get the app to work locally, I also needed to do a couple things that were not mentioned in the instructions.  

I needed to edit application-dev.yml by entering the database username and password. I also got an error about an address already being in use.  So I changed the port in application_dev.yml and gulpfile.js from 8080 to 8181. I also got the error "Unsupported major.minor version 51.0". To fix that, I deleted the app and regenerated it without using Java 8.  I'd love to help people avoid these hurdles.  Should (can) I add something to the docs?

Thank you!

**Comment by jdubois** [comment] 2015-05-04 11:43
From your log, the app looks to be running. Do you have a 404 when going to the root of your app? No index.html file ready there? Can you anything when you do a "cf logs"? This should show you the HTTP requests

As I use Grunt, here is how it is supposed to work with Grunt (and Gulp should work the same, or that's an error):
- In dev mode you can use "grunt serve" to serve the dev files
- In prod mode you go directly to your Tomcat instance, using "grunt serve" wouldn't do anything as you don't reload anything anymore (everything is minified) -> so what you ask for shouldn't work, or at least shouldn't do anything meaningful
- Doing a "mvn spring-boot:run -Pprod" should indeed make everything work, just go to your localhost:8080 and you should be in prod mode (the "dev" banner should have disappeared)

As this looks like a Gulp error, I'm putting the Gulp flag here

**Comment by dancancro** [comment] 2015-05-04 13:57
Yes, I got the 404 when trying to go to the root of my [app](http://sophiesbookstore.cfapps.io/) running on CloudFoundry.  The `cf logs` output from that is just
```
2015-05-04T14:54:49.89+0200 [RTR/2]      OUT sophiesbookstore.cfapps.io - [04/05/2015:12:54:49 +0000] "GET / HTTP/1.1" 404 4063 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.90 Safari/537.36" 10.10.2.122:29540 x_forwarded_for:"95.90.233.181" vcap_request_id:fc99f768-28d6-4672-7a49-b7831524817b response_time:0.032367845 app_id:82cf6eca-b854-4383-87d1-ac89f986f4c0
2015-05-04T14:54:50.09+0200 [RTR/2]      OUT sophiesbookstore.cfapps.io - [04/05/2015:12:54:50 +0000] "GET /favicon.ico HTTP/1.1" 200 5430 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.90 Safari/537.36" 10.10.2.122:64024 x_forwarded_for:"95.90.233.181" vcap_request_id:fc82a4f1-1994-4ba9-7a28-d24dc11bb18e response_time:0.012417918 app_id:82cf6eca-b854-4383-87d1-ac89f986f4c0```
```

I tried running `mvn spring-boot:run -Pprod` locally then going to http://127.0.0.1:8181, but got the same results with that.  So perhaps the problem doesn't have to do with CloudFoundry.

I made [this](https://gist.github.com/dancancro/6dafab69e08305e5cf2c) gist of my "target" directory contents.  Maybe it has some clues.

Also, it looks like I installed the PHP PgAdmin tool which is occupying port 8080.  I'm not sure how to shut this down or uninstall it from my Mac.  But I can deal with that later.

**Comment by gmarziou** [comment] 2015-05-05 08:57
Something in your log is weird, you're running with both dev and prod profiles

000+00:00 [App/0] OUT [INFO] com.mycompany.myapp.Application - Running with Spring profile(s) : [dev, prod, cloud]
2015-05-04T08:16:08.

**Comment by dancancro** [comment] 2015-05-05 12:44
That does look strange.  Do you know how to fix it?  

In production mode (running `mvn spring-boot:run -Pprod`) locally, I do at least get a favicon.ico file.  But it's the green leaf, not the jhipster dude.  I'm not sure exactly which files should be served in production mode locally.  There was no index.html in my target/bookstore-0.0.1-SNAPSHOT/dist folder so I tried putting one there, but it wasn't served.  There is an index.html in target/bookstore-0.0.1-SNAPSHOT/ but that doesn't seem to be getting served either.

**Comment by gmarziou** [comment] 2015-05-05 12:51
Well profiles can be set from different places, you should have a look at the pom.xml and maybe application-*.yml

When in production, as you said most client files (index.html, css files, ...) are supposed to be versioned by the build process and served from dist folder. I had the case once where main.css was not generated in dist folder and this was due to a merging conflict (my team si still using SVN) on build server. So I just removed the generated file from repository and added it to the ignore list.  Maybe you got soemthing similar.

**Comment by cah-JimShingler** [comment] 2015-05-07 04:45
I am not sure it is the same issue, ... but i discovered a similar sounding issue when trying to deploy to docker.  I've tracked it down to something being wrong with the executable jar  NOTE: jar not war.  

I created a new JHipster project and attempted to run the jar.  when I hit the site I am getting 404.

Thoughts?

Jim

**Comment by gmarziou** [comment] 2015-05-07 13:57
Yes I had same problem too, I unzipped the jar file and found that it was missing all dist files. I switched maven artifact type to war and this solved the issue for me too.

**Comment by jdubois** [comment] 2015-05-07 14:04
@dancancro sorry I didn't reply on your other comments:

- for database username and password, it's already in the documentation, here: http://jhipster.github.io/creating_an_app.html
- for the 8080 port, no you can't have two applications on the same port. Changing the port is a standard Spring Boot property, documented by Spring Boot: I agree it might not be easy to understand at the beginning, but when it's a Spring Boot feature we don't document it, as we forward people to the Spring Boot documentation. In the end, it solves a lot of issues for us, as Spring Boot is also evolving quite quickly.
- If you use JDK7, you can't generate your application with Java 8. It just can't work, as we use new Java 8 structures that are not available with JDK7. We should remove JDK7 support soon anyway, as it's now EOL, and we see a drop of people using it.

**Comment by jdubois** [comment] 2015-05-07 14:10
@dancancro for your cloudfoundry issue the most logical thing is that the Gulp build didn't work correctly. I use Grunt personally, and Gulp.js is done by @amr 

-> I'm going to give it a try
-> can you try using Grunt instead?

**Comment by jdubois** [comment] 2015-05-07 14:24
I just tried it out and had no problem at all.

-> I'm removing the gulp.js tag as this isn't a Gulp.js issue

**Comment by jdubois** [comment] 2015-05-07 14:30
I have tried it and deployed correctly to CloudFoundry, without any issue.
I also used MySQL, to have exactly the same setup.

I'm sorry but I can't reproduce your issue.

**Comment by jdubois** [comment] 2015-05-07 14:31
Do you have something in your src/webapp/dist folder? That's the only thing that could give you a 404 (excepted from the "dev" profile issue, but that was already pointed out)

**Comment by dancancro** [comment] 2015-05-07 19:13
@jdubois 

>  for database username and password, it's already in the documentation, here: http://jhipster.github.io/creating_an_app.html

You are correct.  I didn't read closely enough.

> for the 8080 port, no you can't have two applications on the same port. Changing the port is a standard Spring Boot property, documented by Spring Boot: I agree it might not be easy to understand at the beginning, but when it's a Spring Boot feature we don't document it, as we forward people to the Spring Boot documentation. In the end, it solves a lot of issues for us, as Spring Boot is also evolving quite quickly.

That's fine.  I don't know the first thing about Spring Boot, but it seems to have been enough to change 8080 to 8181 in the application-dev.yml and application-prod.yml files.

> If you use JDK7, you can't generate your application with Java 8. It just can't work, as we use new Java 8 structures that are not available with JDK7. We should remove JDK7 support soon anyway, as it's now EOL, and we see a drop of people using it.

This is fine.  I misdiagnosed the problem.  It was related to a bad JAVA_HOME value.  For anyone's reference.  If you get
`Exception in thread "main" java.lang.UnsupportedClassVersionError: org/apache/maven/cli/MavenCli : Unsupported major.minor version 51.0`
then it might help you to run
`export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_05.jdk/Contents/Home`

> -> can you try using Grunt instead?

I made a Grunt app and a Gulp app.  Running `mvn spring-boot:run -Pprod` only worked with the Grunt version, so it would seem the problem was indeed related to Gulp.

> Do you have something in your src/webapp/dist folder? 

My good Grunt app has this in that folder:
assets/
scripts/
index.html

My not-working Gulp app has this in that folder:
assets/
i18n/
scripts/

One other thing.  I got this error a couple times:
`permission denied for relation databasechangeloglock`
To fix it, I gave the PostgreSQL user superuser rights.

My app was successfully deployed to Cloudfoundry.  YAY!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Thank you!

**Comment by dancancro** [comment] 2015-05-08 13:29
A couple of things after the first day...

1) After a while, authentication from the login page stops working.  I enter admin/admin or user/user and it tells me "Authentication failed! Please check your credentials and try again.".  If I refresh the page and try again, it works.  That doesn't seem like a desired behavior.  I'm using Chrome and "authenticationType": "session".

2) Registration seems to be working, but since it requires an email confirmation to activate accounts, I'll need to get email to work.  Does anyone have any tips for doing that?  I found SendMail among the CloudFoundry 3rd party services.  I added it and was given some credentials.  It seems like maybe I just need to enter them somewhere in the jhipster code.  I found a place for them in application.yml, just where I expected to find it (nice!), but I'm wondering whether I should instead put them into application-prod.yml.  It would be nice to have it work in both dev and prod which will have different settings.

3) I'm confused about when to run `mvn spring-boot:run` and when to run `grunt serve`.  It seems that the former calls the latter, so I never need to run `grunt serve`.

One other thing.  I really like the jhipster docs.  Great job!

**Comment by jdubois** [comment] 2015-05-11 12:16
Hi Dan,

As you succeeded in deploying I'm closing this ticket, still let me answer your other issues in order:

1) I agree this is not a normal behavior. I don't know what's causing this, so if you have any more information (like a Chrome console error) it's most welcome -> if you have this, can you open up another ticket?
2) Yes you need an SMTP server to send emails. You found the right configuration, indeed. Yes you can have different settings in dev and prod, each file is there for this very reason.
3) No, "mvn spring-boot:run" does not run "grunt serve". You have access to the same page, so it looks the same, but the difference is that "grunt serve" uses BrowserSync, so your page will be automatically reloaded, etc.

**Closed by jdubois** 2015-05-11 12:16 UTC
