### ISSUE TITLE
React gateways fail to compile after PR #8525

### ISSUE THREAD

**Issue by jsm174** [jhipster/generator-jhipster#8577] opened 2018-10-15 12:52 UTC
##### **Overview of the issue**

I went to test PR #8560, and started getting compile errors for react gateways:

I believe it is the result of PR #8525.

For jwt gateways: 

```
ERROR in /Users/jsm174/git/jhipster/react-test-9/gateway/src/main/webapp/app/modules/login/login.tsx
ERROR in /Users/jsm174/git/jhipster/react-test-9/gateway/src/main/webapp/app/modules/login/login.tsx(6,10):
TS2305: Module '"/Users/jsm174/git/jhipster/react-test-9/gateway/src/main/webapp/app/shared/reducers/authentication"' has no exported member 'login'.

ERROR in /Users/jsm174/git/jhipster/react-test-9/gateway/src/main/webapp/app/shared/reducers/authentication.ts
ERROR in /Users/jsm174/git/jhipster/react-test-9/gateway/src/main/webapp/app/shared/reducers/authentication.ts(105,29):
TS2339: Property 'session' does not exist on type '{ new (): Storage; prototype: Storage; }'.

ERROR in /Users/jsm174/git/jhipster/react-test-9/gateway/src/test/javascript/spec/app/shared/reducers/authentication.spec.ts
ERROR in /Users/jsm174/git/jhipster/react-test-9/gateway/src/test/javascript/spec/app/shared/reducers/authentication.spec.ts(8,52):
TS2305: Module '"/Users/jsm174/git/jhipster/react-test-9/gateway/src/main/webapp/app/shared/reducers/authentication"' has no exported member 'login'.
```

For oauth2 gateways:  

```
ERROR in /Users/jsm174/git/jhipster/react-test-10/gateway/src/main/webapp/app/shared/reducers/authentication.ts
ERROR in /Users/jsm174/git/jhipster/react-test-10/gateway/src/main/webapp/app/shared/reducers/authentication.ts(81,29):
TS2339: Property 'session' does not exist on type '{ new (): Storage; prototype: Storage; }'.

ERROR in /Users/jsm174/git/jhipster/react-test-10/gateway/src/test/javascript/spec/app/shared/reducers/authentication.spec.ts
ERROR in /Users/jsm174/git/jhipster/react-test-10/gateway/src/test/javascript/spec/app/shared/reducers/authentication.spec.ts(118,17):
TS2304: Cannot find name 'localeActionTypes'.
```

##### **Reproduce the error**

jwt jdl:

```
application {
  config {
    baseName gateway,
    applicationType gateway,
    authenticationType JWT,
    packageName com.example.gateway,
    prodDatabaseType postgresql,
    clientFramework react,
    buildTool gradle
  }
  entities A, B, C, D
}

application {
  config {
    baseName microservicea,
    applicationType microservice,
    authenticationType JWT,
    packageName com.example.microservicea,
    prodDatabaseType postgresql,
    buildTool gradle
  }
  entities A, B
}

application {
  config {
    baseName microserviceb,
    applicationType microservice,
    authenticationType JWT,
    packageName com.example.microserviceb,
    prodDatabaseType postgresql,
    buildTool gradle
  }
  entities C, D
}

entity A {
    data String
}

entity B {
    data String
}

entity C {
    data String
}

entity D {
    data String
}

dto * with mapstruct
service * with serviceClass

microservice A, B with microservicea
microservice C, D with microserviceb
```

oauth2 jdl:

```
application {
  config {
    baseName gateway,
    applicationType gateway,
    authenticationType oauth2,
    packageName com.example.gateway,
    prodDatabaseType postgresql,
    clientFramework react,
    buildTool gradle
  }
  entities A, B, C, D
}

application {
  config {
    baseName microservicea,
    applicationType microservice,
    authenticationType oauth2,
    packageName com.example.microservicea,
    prodDatabaseType postgresql,
    buildTool gradle
  }
  entities A, B
}

application {
  config {
    baseName microserviceb,
    applicationType microservice,
    authenticationType oauth2,
    packageName com.example.microserviceb,
    prodDatabaseType postgresql,
    buildTool gradle
  }
  entities C, D
}

entity A {
    data String
}

entity B {
    data String
}

entity C {
    data String
}

entity D {
    data String
}

dto * with mapstruct
service * with serviceClass

microservice A, B with microservicea
microservice C, D with microserviceb
```

##### **JHipster Version(s)**

```
gateway@0.0.0 /Users/jsm174/git/jhipster/react-test-10/gateway
└── generator-jhipster@5.4.2

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "enableHibernateCache": true,
    "enableSwaggerCodegen": false,
    "enableTranslation": true,
    "jhiPrefix": "jhi",
    "languages": [
      "en",
      "fr"
    ],
    "messageBroker": false,
    "nativeLanguage": "en",
    "packageName": "com.example.gateway",
    "packageFolder": "com/example/gateway",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "serviceDiscoveryType": "eureka",
    "skipClient": false,
    "skipServer": false,
    "testFrameworks": [],
    "websocket": false,
    "baseName": "gateway",
    "applicationType": "gateway",
    "authenticationType": "oauth2",
    "clientFramework": "react",
    "buildTool": "gradle",
    "jhipsterVersion": "5.4.2",
    "skipUserManagement": true,
    "clientPackageManager": "npm",
    "cacheProvider": "hazelcast",
    "serverPort": "8080",
    "useSass": true
  },
  "entities": [
    "A",
    "B",
    "C",
    "D"
  ]
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity A {
  data String
}
entity B {
  data String
}
entity C {
  data String
}
entity D {
  data String
}
dto A, B, C, D with mapstruct
service A, B, C, D with serviceClass
microservice A, B with microservicea
microservice C, D with microserviceb

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

git version 2.17.1 (Apple Git-112)

node: v8.12.0

npm: 6.4.1

yarn: 1.10.1

Docker version 18.06.1-ce, build e68fc7a

docker-compose version 1.22.0, build f46880f

-   [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by jsm174** [comment] 2018-10-15 13:34
Sorry about that. Forgot I wasn't in the gateway directory. Updated jhipster info in the initial comment.

**Comment by lmbai** [comment] 2018-10-15 14:01
@jsm174 confirmed it is a issue. will fix in another PR

**Comment by lmbai** [comment] 2018-10-15 15:07
@jsm174 , i can't reproduce the issue for JWT. when it is JWT. defnitely the `Storage` will be imported. and the `login` will be there.

Acturally there is issue for the monolithic app using session.  . but not with the JWT. can you try again? or you can post the yo-rc.json here

**Comment by jsm174** [comment] 2018-10-15 15:10
Let me check again for JWT. I was using head of jhipster-core testing out some other fixes.

**Comment by jsm174** [comment] 2018-10-15 15:22
Yeh, I am definitely getting the error:

```
ERROR in /Users/jmillard/git/jhipster/react-test-9/gateway/src/main/webapp/app/modules/login/login.tsx
ERROR in /Users/jmillard/git/jhipster/react-test-9/gateway/src/main/webapp/app/modules/login/login.tsx(6,10):
TS2305: Module '"/Users/jmillard/git/jhipster/react-test-9/gateway/src/main/webapp/app/shared/reducers/authentication"' has no exported member 'login'.

ERROR in /Users/jmillard/git/jhipster/react-test-9/gateway/src/main/webapp/app/shared/reducers/authentication.ts
ERROR in /Users/jmillard/git/jhipster/react-test-9/gateway/src/main/webapp/app/shared/reducers/authentication.ts(105,29):
TS2339: Property 'session' does not exist on type '{ new (): Storage; prototype: Storage; }'.

ERROR in /Users/jmillard/git/jhipster/react-test-9/gateway/src/test/javascript/spec/app/shared/reducers/authentication.spec.ts
ERROR in /Users/jmillard/git/jhipster/react-test-9/gateway/src/test/javascript/spec/app/shared/reducers/authentication.spec.ts(8,52):
TS2305: Module '"/Users/jmillard/git/jhipster/react-test-9/gateway/src/main/webapp/app/shared/reducers/authentication"' has no exported member 'login'.
```

Full disclosure, I'm using master's for generator and core:

```
git clone https://github.com/jhipster/generator-jhipster.git
cd generator-jhipster
vi package.json --> "jhipster-core": "git+https://github.com/jhipster/jhipster-core"
yarn global add file:/Users/jsm174/generator-jhipster
```

Here is the yo-rc.json:

```

{
  "generator-jhipster": {
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "enableHibernateCache": true,
    "enableSwaggerCodegen": false,
    "enableTranslation": true,
    "jhiPrefix": "jhi",
    "languages": [
      "en",
      "fr"
    ],
    "messageBroker": false,
    "nativeLanguage": "en",
    "packageName": "com.example.gateway",
    "packageFolder": "com/example/gateway",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "serviceDiscoveryType": "eureka",
    "skipClient": false,
    "skipServer": false,
    "testFrameworks": [],
    "websocket": false,
    "baseName": "gateway",
    "applicationType": "gateway",
    "authenticationType": "JWT",
    "clientFramework": "react",
    "buildTool": "gradle",
    "jhipsterVersion": "5.4.2",
    "skipUserManagement": false,
    "clientPackageManager": "npm",
    "cacheProvider": "hazelcast",
    "serverPort": "8080",
    "useSass": true
  },
  "entities": [
    "A",
    "B",
    "C",
    "D"
  ]
}
```

**Comment by lmbai** [comment] 2018-10-15 15:33
@jsm174 hey, i think you should use `"authenticationType": "jwt"` . haha

**Comment by jsm174** [comment] 2018-10-15 15:41
Wow, I feel like an idiot. :)  That worked!

In my defense, I would have expected `jhipster import-jdl` to catch that. :) 

I just tried the following:

```
application {
  config {
    baseName gateway,
    applicationType gateway,
    authenticationType xyz,
    packageName com.example.gateway,
    prodDatabaseType postgresql,
    clientFramework react,
    buildTool gradle
  }
  entities A, B, C, D
}
.
.
.
```

And that didn't get flagged either.

**Comment by lmbai** [comment] 2018-10-15 15:44
@jsm174 you a welcome. thanks for point out the issue with oAuth2

**Comment by jdubois** [comment] 2018-10-15 20:30
Closing as #8579 is merged, thanks @lmbai !

**Closed by jdubois** 2018-10-15 20:30 UTC

**Comment by afshimono** [comment] 2019-07-12 17:19
Hi everyone, this is my first post here, so please be a little patient if I do not follow protocol and advise where I can improve. I am having similar issues while deploying a simple test gateway + 2 microservices app on jhipster.  This is my jdl file:

`application {
	config {
		baseName gateway,
		packageName br.com.altimus.gateway,
		applicationType gateway,
		authenticationType oauth2,
		devDatabaseType mysql, 
		prodDatabaseType mysql,
		clientFramework react,
		buildTool gradle,
		dtoSuffix DTO,
		nativeLanguage pt-br,
		languages [en, es],
		searchEngine elasticsearch, 
		serviceDiscoveryType eureka, 
		testFrameworks [cucumber] 
	}
	entities Veiculo, Cliente, Venda, Loja, Vendedor
}

application {
	config {
		baseName revendas,
		packageName br.com.altimus.revendas,
		applicationType microservice,
		authenticationType oauth2,
		devDatabaseType mysql,
		prodDatabaseType mysql,
		buildTool gradle,
		enableHibernateCache false,
		searchEngine elasticsearch,
		serverPort 8081,
		serviceDiscoveryType eureka
	}
	entities Veiculo, Cliente, Venda, Loja, Vendedor

}

application {
	config {
		baseName mercado,
		packageName br.com.altimus.mercado,
		applicationType microservice,
		authenticationType oauth2,
		databaseType mongodb,
		devDatabaseType mongodb,
		prodDatabaseType mongodb,
		buildTool gradle,
		searchEngine elasticsearch,
		serverPort 8082,
		serviceDiscoveryType eureka
	}
}

entity Veiculo {
	placa String required minlength(3),
}

entity Cliente {
	nome String required,
	telefone String,
	email String 
}

entity Venda {
	valor BigDecimal required min(0),
	data LocalDate required
}

entity Loja {
	nome String required,
	cnpj String required
}

entity Vendedor {
	nome String required,
	cpf String required
}

relationship OneToOne{
	Veiculo{venda} to Venda{veiculo},
	Cliente{compra} to Venda{cliente}
}

relationship ManyToOne {
	Veiculo{loja(veiculos)} to Loja,
	Vendedor{loja(vendedores)} to Loja,
	Venda{vendedor(vendas)} to Vendedor,
}


paginate Veiculo, Cliente with infinite-scroll
paginate Venda with pagination

microservice Veiculo, Vendedor, Venda, Loja, Cliente with revendas
`

I am currently using OAuth2 okta for login in jhipster-registry and for all applications, and was trying to compile only the gateway using the proccess described on https://www.jhipster.tech/docker-compose/ : 

> ./gradlew -Pprod bootJar jibDockerBuild --offline

However, I keep getting the error:

`ERROR in C:/jHipster/gateway/src/main/webapp/app/entities/revendas/veiculo/veiculo-detail.tsx
ERROR in C:/jHipster/gateway/src/main/webapp/app/entities/revendas/veiculo/veiculo-detail.tsx(44,58):
TS2339: Property 'veiculos' does not exist on type 'ILoja'.

ERROR in C:/jHipster/gateway/src/main/webapp/app/entities/revendas/veiculo/veiculo-update.tsx
ERROR in C:/jHipster/gateway/src/main/webapp/app/entities/revendas/veiculo/veiculo-update.tsx(139,42):
TS2339: Property 'veiculos' does not exist on type 'ILoja'.

ERROR in C:/jHipster/gateway/src/main/webapp/app/entities/revendas/veiculo/veiculo.tsx
ERROR in C:/jHipster/gateway/src/main/webapp/app/entities/revendas/veiculo/veiculo.tsx(166,94):
TS2339: Property 'veiculos' does not exist on type 'ILoja'.

ERROR in C:/jHipster/gateway/src/main/webapp/app/entities/revendas/venda/venda-detail.tsx
ERROR in C:/jHipster/gateway/src/main/webapp/app/entities/revendas/venda/venda-detail.tsx(48,62):
TS2339: Property 'vendas' does not exist on type 'IVendedor'.

ERROR in C:/jHipster/gateway/src/main/webapp/app/entities/revendas/venda/venda-update.tsx
ERROR in C:/jHipster/gateway/src/main/webapp/app/entities/revendas/venda/venda-update.tsx(146,42):
TS2339: Property 'vendas' does not exist on type 'IVendedor'.

ERROR in C:/jHipster/gateway/src/main/webapp/app/entities/revendas/venda/venda.tsx
ERROR in C:/jHipster/gateway/src/main/webapp/app/entities/revendas/venda/venda.tsx(153,102):
TS2339: Property 'vendas' does not exist on type 'IVendedor'.

ERROR in C:/jHipster/gateway/src/main/webapp/app/entities/revendas/vendedor/vendedor-detail.tsx
ERROR in C:/jHipster/gateway/src/main/webapp/app/entities/revendas/vendedor/vendedor-detail.tsx(46,60):
TS2339: Property 'vendedores' does not exist on type 'ILoja'.

ERROR in C:/jHipster/gateway/src/main/webapp/app/entities/revendas/vendedor/vendedor-update.tsx
ERROR in C:/jHipster/gateway/src/main/webapp/app/entities/revendas/vendedor/vendedor-update.tsx(133,42):
TS2339: Property 'vendedores' does not exist on type 'ILoja'.

ERROR in C:/jHipster/gateway/src/main/webapp/app/entities/revendas/vendedor/vendedor.tsx
ERROR in C:/jHipster/gateway/src/main/webapp/app/entities/revendas/vendedor/vendedor.tsx(110,95):
TS2339: Property 'vendedores' does not exist on type 'ILoja'.`

Thanks so much in advance.
