### ISSUE TITLE
Inconsistent relationship to User for OAuth2

### ISSUE THREAD

**Issue by gflohr** [jhipster/generator-jhipster#8460] opened 2018-10-04 15:08 UTC
##### **Overview of the issue**

I  have a OneToOne relationship from `Customer` to `User` for a microservice using OAuth2 and MariaDB.

The `user` table is generated with a primary key `id varchar(100)`. The referring column in `customer` is `user_id bigint(20)`.  When liquibase creates the foreign key constraint, an exception is thrown:

```
classpath:config/liquibase/master.xml: config/liquibase/changelog/20181004142453_added_entity_constraints_Customer.xml::20181004142453-2::jhipster: Change Set config/liquibase/changelog/20181004142453_added_entity_constraints_Customer.xml::20181004142453-2::jhipster failed.  Error: (conn=759) Can't create table `junk`.`#sql-1_2f7` (errno: 150 "Foreign key constraint is incorrectly formed") [Failed SQL: ALTER TABLE junk.customer ADD CONSTRAINT fk_customer_user_id FOREIGN KEY (user_id) REFERENCES junk.jhi_user (id)]
```

The error message "Foreign key constraint is incorrectly formed" means in this case that the two columns involved are not equivalent.

##### **Motivation for or Use Case**

The two columns should have identical definitions. See for example https://stackoverflow.com/questions/8434518/mysql-foreign-key-constraint-is-incorrectly-formed-error

##### **Reproduce the error**

Generated the project using the `.yo-rc.json` below, then imported `domain.jh`, also included below. Then started the server with `./gradlew bootRun`.

##### **Related issues**

Maybe related to #7065.

##### **Suggest a Fix**

Enforce that the referring column is of same type as the referred column.

##### **JHipster Version(s)**

Tested with 5.3.4 and 5.4.0.

##### **JHipster configuration**

Using JHipster version installed locally in current project's node_modules
Executing jhipster:info
Options: from-cli: true
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
junk@0.0.0 /private/tmp/junk
└── generator-jhipster@5.3.4 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.cantanea.storage",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "5.3.4",
    "applicationType": "microservice",
    "baseName": "junk",
    "packageName": "com.cantanea.storage",
    "packageFolder": "com/cantanea/storage",
    "serverPort": "8081",
    "authenticationType": "oauth2",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "mariadb",
    "prodDatabaseType": "mariadb",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "gradle",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "enableTranslation": true,
    "languages": [
      "en"
    ],
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "clientPackageManager": "npm",
    "nativeLanguage": "en",
    "skipClient": true,
    "skipUserManagement": true
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Customer
relationship OneToOne {
  Customer{user} to User
}

microservice Customer with junk
clientRootFolder Customer with junk

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_172"
Java(TM) SE Runtime Environment (build 1.8.0_172-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.172-b11, mixed mode)

git version 2.19.0

node: v8.12.0

npm: 5.10.0

yeoman: 2.0.5

yarn: 1.10.1

Docker version 18.06.1-ce, build e68fc7a

docker-compose version 1.22.0, build f46880f

Congratulations, JHipster execution is complete!

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

`domain.jh`:

Imported `domain.jh`:

```
entity Customer {}
relationship OneToOne {Customer to User}
```

Resulting `.jhipster/Customer.json`:

```json
{
    "name": "Customer",
    "fields": [],
    "relationships": [
        {
            "relationshipType": "one-to-one",
            "relationshipName": "user",
            "otherEntityName": "user",
            "otherEntityField": "id",
            "ownerSide": true,
            "otherEntityRelationshipName": "customer"
        }
    ],
    "changelogDate": "20181004142453",
    "entityTableName": "customer",
    "dto": "no",
    "pagination": "no",
    "service": "no",
    "jpaMetamodelFiltering": false,
    "fluentMethods": true,
    "clientRootFolder": "junk",
    "applications": "*",
    "microserviceName": "junk"
}
```

##### **Browsers and Operating System**

No frontend.

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by mraible** [comment] 2018-10-04 15:10
Duplicate of https://github.com/jhipster/generator-jhipster/issues/8454

**Comment by jdubois** [comment] 2018-10-04 15:11
I'm currently testing a few things, a patch release will be published either tonight or tomorrow morning

**Closed by mraible** 2018-10-04 15:10 UTC

**Comment by gflohr** [comment] 2018-10-04 15:21
Sorry for the duplicate. I've searched 68 issues containing "foreign key" but have overlooked #8454. My bad.

**Comment by jdubois** [comment] 2018-10-04 15:28
No problem @gflohr - thanks for the bug report!!
