### ISSUE TITLE
Write/Read blueprint custom keyword for entities

### ISSUE THREAD

**Issue by danielpetisme** [jhipster/generator-jhipster#11577] opened 2020-04-12 13:53 UTC
##### **Overview of the feature request**

Provide hooks for Entity#writeEntityJson
https://github.com/jhipster/generator-jhipster/blob/master/generators/entity/index.js#L634
and
Generator-base#LoadEntityJson
https://github.com/jhipster/generator-jhipster/blob/master/generators/generator-base.js#L1218

##### **Motivation for or Use Case**

When developing a blueprint, it would be interesting to introduce new feature to the entity (ie. Quakus promote active record pattern over repository.
This information could be stored in the entity JSON file generated by JHipster.

Without this feature, a blueprint developer has to copy/paster main-generator code (load Json) or hack the phases (writeJson) in order to cover a new entity keyword.

##### **Related issues or PR**

I didn't look to request asking to introduce custom keywords in the JDL, but I guess at some point if we consider to extend this feature to the entity definition, JHipster entity serialization with custom properties will be a a point to cover.

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment] 2020-04-12 14:37
I don't think this is necessary: 
```
get initializing() {
  return {
    ...super._initializing(),
    loadCustomProperties() {
      this.context.quarkusPattern = this.context.fileData.quarkusPattern;
    }
  }
}

get configuring() {
  return {
    saveCustomProperties() {
      this.storageData = this.storageData || {};
      this.storageData.quarkusPattern = this.context.quarkusPattern;
    },
    ...super.configuring()
  }
}
```

JDL custom app config support is tracked by https://github.com/jhipster/jhipster-core/issues/448
About entity config I don't know if its supported or a bug (probably a bug) but I think this works:
```
@quarkusPattern(foo)
entity A
```

**Comment by MathieuAA** [comment] 2020-04-14 07:48
>  About entity config I don't know if its supported or a bug (probably a bug) but I think this works:

Not a bug :)

**Comment by danielpetisme** [comment] 2020-04-14 16:01
@mshima I end up with a similar solution but.... I struggle way too much with this one (My not a js nor a yeoman expert) ...
I think phase steps ordering is worth a not in the blueprint documentation.

I'll start something, would you mind if I name you as reviewer?

**Comment by danielpetisme** [comment] 2020-04-16 20:51
Close with 
https://github.com/jhipster/jhipster.github.io/pull/937

**Comment by mshima** [comment] 2020-04-20 23:14
Reopening, I think we can improve this.

**Comment by mshima** [comment] 2020-07-28 14:56
Fixed by https://github.com/jhipster/generator-jhipster/pull/12132

**Closed by mshima** 2020-07-28 14:56 UTC
Labels: area: feature request :bulb:, theme: blueprint :paw_prints:
