### ISSUE TITLE
No mapping found for [_score] in order to sort on

### ISSUE THREAD

**Issue by manisi** [jhipster/generator-jhipster#7908] opened 2018-07-01 18:57 UTC
##### **Motivation for or Use Case**

when table data is null and if enter any character in search panel,this error rise:
Caused by: org.elasticsearch.index.query.QueryShardException: No mapping found for [_score] in order to sort on

##### **Reproduce the error**
<img width="1365" alt="screen shot 2018-07-01 at 23 17 03" src="https://user-images.githubusercontent.com/3120328/42137656-8d0e4f14-7d85-11e8-9a88-f400d35a6062.png">

Caused by: org.elasticsearch.index.query.QueryShardException: No mapping found for [_score] in order to sort on
	at org.elasticsearch.search.sort.FieldSortBuilder.build(FieldSortBuilder.java:262)
	at org.elasticsearch.search.sort.SortBuilder.buildSort(SortBuilder.java:156)
	at org.elasticsearch.search.SearchService.parseSource(SearchService.java:634)
	at org.elasticsearch.search.SearchService.createContext(SearchService.java:485)
	at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:461)
	at org.elasticsearch.search.SearchService.executeDfsPhase(SearchService.java:226)
	at org.elasticsearch.action.search.SearchTransportService$5.messageReceived(SearchTransportService.java:332)
	at org.elasticsearch.action.search.SearchTransportService$5.messageReceived(SearchTransportService.java:329)
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:69)
	at org.elasticsearch.transport.TransportService$7.doRun(TransportService.java:654)
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:638)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
##### **Suggest a Fix**
add    defaultSort: 'id,asc' 
<img width="359" alt="screen shot 2018-07-01 at 23 24 53" src="https://user-images.githubusercontent.com/3120328/42137675-1883bbce-7d86-11e8-9359-a963288f6a96.png">

##### **JHipster Version(s)**
jhipster 5.0.1

##### **JHipster configuration**

```
sample-5@0.0.0 /Users/developer/Desktop/sample5
└── (empty)

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "5.0.0",
    "applicationType": "monolith",
    "baseName": "sample5",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "yarn",
    "testFrameworks": [
      "gatling",
      "cucumber"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "fa"
    ]
  }
}
</pre>
</details>

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

```
entity City{
cityCode Integer,
cityName String required,
active Boolean
}

entity Ostan{
ostanCode Integer,
ostanName String required,
active Boolean
}

relationship ManyToOne {
City{ostan} to Ostan
}
relationship OneToOne {
Personel{user} to User
}

paginate City, Ostan with infinite-scroll

paginate Personel with pagination
service all with serviceImpl
```

##### **Browsers and Operating System**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by ruddell** [comment] 2018-07-01 19:29
I can't reproduce with an entity both with and without pagination.  Please post your entity configuration so I don't waste more time.

Looks similar to https://github.com/jhipster/generator-jhipster/issues/5908

**Comment by manisi** [comment] 2018-07-01 19:48
@ruddell  urwelcome ruddell  :)
entity config : 

entity City{
cityCode Integer,
cityName String required,
active Boolean
}

entity Ostan{
ostanCode Integer,
ostanName String required,
active Boolean 
}

relationship ManyToOne {
  City{ostan} to Ostan
}
relationship OneToOne {
  Personel{user} to User
}

paginate  City, Ostan  with infinite-scroll

paginate Personel with pagination
service all with serviceImpl

**Comment by ruddell** [comment] 2018-07-01 23:48
This is the same issue I linked above.  Setting a default sort doesn't fix the issue, it just changes the error message to reference that field instead of `_score` which is set in the entity.component.ts

Closing based on the same reasons/discussion in the original ticket https://github.com/jhipster/generator-jhipster/issues/5908#issuecomment-315439102, if you have a solution please comment

**Closed by ruddell** 2018-07-01 23:48 UTC
