### ISSUE TITLE
Getting java.lang.IllegalStateException: handshake failed, mismatched cluster name Exception while running embedded Elasticsearch instance

### ISSUE THREAD

**Issue by maheshjadhav007** [jhipster/generator-jhipster#11641] opened 2020-04-25 21:17 UTC
I have created UAA service, Gateway and OtpService microservice using Jhipster. but when I ran Gateway and Otpservice , I am getting below exception related to Elastic search cluster. I am using embedded Elasticsearch instance. after throwing below exception services getting registered to Eureka server. I am expecting to run services without exception.
 
2020-04-26 02:25:11.623  WARN 3372 --- [_connect]][T#6]] o.e.discovery.zen.UnicastZenPing         : [1] failed send ping to {127.0.0.1:9300}{JgxF0kBVR-iIrOf73cnwVg}{127.0.0.1}{127.0.0.1:9300}

java.lang.IllegalStateException: handshake failed, mismatched cluster name [Cluster [internal-test-cluster-name146d2dde-6933-4fc3-abea-4e548dce1c15]] - {127.0.0.1:9300}{JgxF0kBVR-iIrOf73cnwVg}{127.0.0.1}{127.0.0.1:9300}
        at org.elasticsearch.transport.TransportService.handshake(TransportService.java:404)
        at org.elasticsearch.transport.TransportService.handshake(TransportService.java:367)
        at org.elasticsearch.discovery.zen.UnicastZenPing$PingingRound.getOrConnect(UnicastZenPing.java:366)
        at org.elasticsearch.discovery.zen.UnicastZenPing$3.doRun(UnicastZenPing.java:471)
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:723)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

2020-04-26 02:25:11.623  WARN 3372 --- [_connect]][T#3]] o.e.discovery.zen.UnicastZenPing         : [1] failed send ping to {[::1]:9300}{QX-g01bdRo2aIjad08AccQ}{0:0:0:0:0:0:0:1}{[::1]:9300}

**************************************************************************************
Jhipster info
***************************************************************************************
INFO! Using JHipster version installed locally in current project's node_modules
INFO! Executing jhipster:info
INFO! Options: from-cli: true
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
gatewayservice@0.0.0 D:\jhipster2\gateway
`-- generator-jhipster@6.2.0

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.tennabo.gatewayservice"
    },
    "jhipsterVersion": "6.2.0",
    "applicationType": "gateway",
    "baseName": "gatewayservice",
    "packageName": "com.tennabo.gatewayservice",
    "packageFolder": "com/tennabo/gatewayservice",
    "serverPort": "8085",
    "authenticationType": "uaa",
    "uaaBaseName": "authservice",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "useSass": true,
    "clientPackageManager": "npm",
    "skipClient": true,
    "testFrameworks": [
      "cucumber"
    ],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": false,
    "blueprints": []
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_221"
Java(TM) SE Runtime Environment (build 1.8.0_221-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.221-b11, mixed mode)

git version 2.23.0.windows.1

node: v10.16.0

npm: 6.14.4

**Comment by mraible** [comment] 2020-04-25 21:57
Embedded elasticsearch is used by default in the `dev` profile:

https://github.com/jhipster/generator-jhipster/blob/master/generators/server/templates/src/main/resources/config/application-dev.yml.ejs#L176

localhost:9200 is used when running with the `prod` profile:

https://github.com/jhipster/generator-jhipster/blob/master/generators/server/templates/src/main/resources/config/application-prod.yml.ejs#L150

I'm confused because it looks like it's failing to call 9300, yet you say you're running in embedded mode. Did you make any changes to your app after generating it? Embedded elasticsearch + cluster doesn't make sense to me. Can you clarify?

**Comment by maheshjadhav007** [comment] 2020-04-26 06:13
Hi mraible,

Thanks for responding. 

I haven't done any changes in application-dev.yml. Even It confused me. I am attaching my application-dev.yml for your reference. 

I am running following application in my laptop locally.

1)Eureka Server   -> Ran perfectly
2)UAA                  -> Ran Perfectly
3)Gateway           -> throws below error. but connect to eureka
4)OTP Service      -> throws below error. but connect to eureka

Can you please point out, what should I do next to resolve?

*************************************************************************
application-dev.yml
************************************************************************* 

# ===================================================================
# Spring Boot configuration for the "dev" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

logging:
  level:
    ROOT: DEBUG
    io.github.jhipster: DEBUG
    com.tennabo.authservice: DEBUG

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/

management:
  health:
    elasticsearch:
      enabled: false

spring:
  profiles:
    active: dev
    include:
      - swagger
      # Uncomment to activate TLS for the dev profile
      #- tls
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: false # we use Webpack dev server + BrowserSync for livereload
  jackson:
    serialization:
      indent-output: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/authservice?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: 
    hikari:
      poolName: Hikari
      auto-commit: false
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: MYSQL
    show-sql: true
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
  data:
    elasticsearch:
      properties:
        path:
          home: target/elasticsearch
  liquibase:
    # Remove 'faker' if you do not want the sample data to be loaded automatically
    contexts: dev, faker
  mail:
    host: localhost
    port: 25
    username:
    password:
  messages:
    cache-duration: PT1S # 1 second, see the ISO 8601 standard
  thymeleaf:
    cache: false
  sleuth:
    sampler:
      probability: 1 # report 100% of traces
  zipkin: # Use the "zipkin" Maven profile to have the Spring Cloud Zipkin dependencies
    base-url: http://localhost:9411
    enabled: false
    locator:
      discovery:
        enabled: true

server:
  port: 9999

# ===================================================================
# JHipster specific properties
#
# Full reference is available at: https://www.jhipster.tech/common-application-properties/
# ===================================================================

jhipster:
  cache: # Cache configuration
    hazelcast: # Hazelcast distributed cache
      time-to-live-seconds: 3600
      backup-count: 1
      management-center: # Full reference is available at: http://docs.hazelcast.org/docs/management-center/3.9/manual/html/Deploying_and_Starting.html
        enabled: false
        update-interval: 3
        url: http://localhost:8180/mancenter
  # CORS is only enabled by default with the "dev" profile, so BrowserSync can access the API
  cors:
    allowed-origins: '*'
    allowed-methods: '*'
    allowed-headers: '*'
    exposed-headers: 'Authorization,Link,X-Total-Count'
    allow-credentials: true
    max-age: 1800
  security:
    client-authorization:
      client-id: internal
      client-secret: internal
  mail: # specific JHipster mail property, for standard properties see MailProperties
    base-url: http://127.0.0.1:9000
  metrics:
    logs: # Reports metrics in the logs
      enabled: false
      report-frequency: 60 # in seconds
  logging:
    use-json-format: false # By default, logs are not in Json format
    logstash: # Forward logs to logstash over a socket, used by LoggingConfiguration
      enabled: false
      host: localhost
      port: 5000
      queue-size: 512
uaa:
  key-store:
    name: config/tls/keystore.p12
    password: password
    alias: selfsigned
  web-client-configuration:
    # Access Token is valid for 5 mins
    access-token-validity-in-seconds: 300
    # Refresh Token is valid for 7 days
    refresh-token-validity-in-seconds-for-remember-me: 604800
    client-id: web_app
    secret: changeit
# ===================================================================
# Application specific properties
# Add your own application properties here, see the ApplicationProperties class
# to have type-safe configuration, like in the JHipsterProperties above
#
# More documentation is available at:
# https://www.jhipster.tech/common-application-properties/
# ===================================================================

# application:

**Comment by mraible** [comment] 2020-04-26 13:28
Can you please wrap the YAML in your previous comment in a markdown code block so it's easier to read? 

What's an OTP Service? Is that an app you created with JHipster?

**Comment by maheshjadhav007** [comment] 2020-04-26 13:50
Hi mraible,

Extremely sorry for inconvenience. I am attaching application-dev file as txt file. Can you please look into it.  OTP service application is created with Jhipster.

In my all 3 jhipster application, I am using embedded elastic instance. and I am trying to run on my laptop. Is it fine to run jhipster application with embedded elastic instance on same machine?

**Comment by mraible** [comment] 2020-04-26 14:34
Embedded ES to me means that you're writing to the file system rather than talking to it in a Docker container (or real instance). Do you have the same definition?

I'm trying to understand why you call it embedded rather than just saying you're using JHipster with Elasticsearch.

**Comment by maheshjadhav007** [comment] 2020-04-26 14:52
Yes matt. Embedded ES writes data in followning location for each microservice.
D:\uaa\target\elasticsearch\data\
D:\gateway\target\elasticsearch\data\
D:\otpservice\target\elasticsearch\data\
 
I am using JHipster with Elasticsearch. I am trying to run microservices for dev environment.

**Comment by mraible** [comment] 2020-04-26 15:04
I haven't experienced this issue, but I have experienced problems when running ES embedded. The problem I experienced is ES fails to restart after it's started once because it thinks the index is corrupted.

If you change your dev ES settings to use the prod settings and start ES in a Docker container, does it solve the problem?

The reason I ask is we might make that the default in JHipster 7.

**Comment by maheshjadhav007** [comment] 2020-04-26 18:11
Hi matt,

If I start ES in docker with prod setting, It will work.
but I am more interested in generating application with jhipster and without modifying any setting,
it should run without any exception.

For re-production of same issue, please find below microservices ( changed db password to 'root')
AuthServer -> https://github.com/maheshjadhav007/authserver.git
Gateway -> https://github.com/maheshjadhav007/gateway.git
OTPService -> https://github.com/maheshjadhav007/otpservice.git

To avoid this exception for time being I am disabling elastic search engine property in .yo-rc.json file as following
"searchEngine": "elasticsearch"
to this:
"searchEngine": false

I wanted to use ES in dev environment without any exception.

Thanks,
Mahesh

**Comment by mraible** [comment] 2020-04-26 18:13
> but I am more interested in generating application with jhipster and without modifying any setting, it should run without any exception.

I agree. It should run without any exceptions. However, this might not be possible. You might've found a bug and we're unable to fix it unless we use Docker in dev mode too. I don't know how to fix your problem. If you figure out a solution, please create a PR.

**Comment by maheshjadhav007** [comment] 2020-04-26 18:31
If possible, Can you please check with repositories which I have shared whether you are getting same exception or not. I just wanted to confirm from expert.

**Comment by mraible** [comment] 2020-05-05 04:35
@maheshjadhav007 Can you give step-by-step instructions to reproduce the problem? I'm sorry, I've never used UAA so I'm not sure how to run everything. Instructions should be something like:

```
git clone git@github.com:maheshjadhav007/authserver.git
cd authserver
// Docker Compose commands
// start command

git clone git@github.com:maheshjadhav007/gateway.git
cd gateway
// Docker Compose commands
// start command

git clone git@github.com:maheshjadhav007/otpservice.git
cd otpserver
// Docker Compose commands
// start command
```

Then steps to reproduce your issue, for example, running `npm run e2e` in the Gateway project.

**Comment by pascalgrimaud** [comment] 2020-05-05 10:02
It's not the first time someone report a problem with embedded Elasticsearch.
Maybe it's time to switch definitively to the docker-compose Elasticsearch in dev too.

**Comment by maheshjadhav007** [comment] 2020-05-06 13:19
Hi @mraible ,

Thanks for your reply.

Please find the below steps to reproduce the issue.
There is no need to run docker coomand. You can run below application locally. 
1. Start Eureka Server. Use **mvnw** command from eureka directory if you are using windows OS, else use "./mvnw"
you can download Eureka Server from below github link
https://github.com/jhipster/jhipster-registry

2. Start AuthServer. Use **mvn spring-boot:run -DskipTests** command to run the app without test cases
3. Start Gateway. Use  **mvn spring-boot:run -DskipTests** command
4. Start OtpServer. Use **mvn spring-boot:run -DskipTests** command

All other services will get Register on Eureka Server Registry. So you have to run Eureka Server first.
After that you should run AuthServer because other microservices required Oauth Token. after that you can run run Gateway Service or OtpService. There is no specific order to run Gateway service or OtpServer.

Thanks in advance.

Mahesh Jadhav.

**Comment by mraible** [comment] 2020-05-07 16:18
I'm sorry, but this is a UAA issue and I'm not a supporter of UAA. I recommend developers use OIDC. 😊

Tagging @xetys, who is our UAA stream lead.

**Comment by maheshjadhav007** [comment] 2020-05-07 16:49
Hi @mraible ,

I am not getting any issue in UAA. I am getting the **IllegalStateException: handshake failed, mismatched cluster name** only when I am running more than one microservice.

If I run only Eureka, Gateway Service and UAA Service , I don't get any exception. but when I tried to run otpservice or any other microservice I encounter above mentioned exception.

So the point is here, one microservice ES is trying to find other microservice ES. but there cluster name is mismatched. Hence it throws **IllegalStateException: handshake failed, mismatched cluster name**.

Thanks matt for your reply.

I am still looking for solution, :)

**Comment by pascalgrimaud** [comment] 2020-06-19 13:57
@maheshjadhav007 : just gave a try to your issue, and I can confirm it. Anyway, the explication is really simple:
- your gateway started an embedded Elasticsearch
- your microservice tried to start another embedded Elasticsearch and it failed

You would have the exact problem if your gateway use postgresql (with port 5432) and another microservice with postgresql (with same port 5432), so only one can work.

What I can suggest is :
- change the config in dev for your gateway and your microservice: use the similar config in prod
- start only once the docker-compose yaml file, related to Elasticsearch
- start both applications -> it will work as it will connect to the same Elasticsearch

Then, as there is more an issue related to how to use microservice, there is nothing we can do on our side.
Anyway, we'll probably migrate to docker-compose Elasticsearch in dev for v7, it's far better.

For now, let's close this.

**Closed by pascalgrimaud** 2020-06-19 13:57 UTC
Labels: area: needs-reproduction, theme: elasticsearch, theme: uaa
