### ISSUE TITLE
When restarting mvnw with elasticsearch / logstash enabled mvnw throws a elasticsearch index already exists error

### ISSUE THREAD

**Issue by BLKingLLC** [jhipster/generator-jhipster#10199] opened 2019-08-08 21:18 UTC
##### **Overview of the issue**
When restarting ./mvnw with logstash enabled I receive an index already exists exception.  The index exists in target/elasticsearch/data/nodes/0/indices.  If I manually delete the index and start ./mvnw it starts correctly and logstash/elasicsearch works fine.  The error is ::
~~~
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'userService' defined in file [/home/cuzimbob/eclipse-offerLetter/offerLetter/target/classes/com/odysseysystems/service/UserService.class]: Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'userSearchRepository': Invocation of init method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.data.elasticsearch.repository.support.SimpleElasticsearchRepository]: Constructor threw exception; nested exception is com.github.vanroy.springdata.jest.exception.JestElasticsearchException: Cannot execute jest action , response code : 400 , error : {"root_cause":[{"type":"resource_already_exists_exception","reason":"index [user/rGcNzfu5RICiJMgqUzgIpA] already exists","index_uuid":"rGcNzfu5RICiJMgqUzgIpA","index":"user"}],"type":"resource_already_exists_exception","reason":"index [user/rGcNzfu5RICiJMgqUzgIpA] already exists","index_uuid":"rGcNzfu5RICiJMgqUzgIpA","index":"user"} , message : null
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:769)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:218)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1341)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1187)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:845)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:877)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:742)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:389)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:311)
	at com.odysseysystems.OfferLetterApp.main(OfferLetterApp.java:65)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'userSearchRepository': Invocation of init method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.data.elasticsearch.repository.support.SimpleElasticsearchRepository]: Constructor threw exception; nested exception is com.github.vanroy.springdata.jest.exception.JestElasticsearchException: Cannot execute jest action , response code : 400 , error : {"root_cause":[{"type":"resource_already_exists_exception","reason":"index [user/rGcNzfu5RICiJMgqUzgIpA] already exists","index_uuid":"rGcNzfu5RICiJMgqUzgIpA","index":"user"}],"type":"resource_already_exists_exception","reason":"index [user/rGcNzfu5RICiJMgqUzgIpA] already exists","index_uuid":"rGcNzfu5RICiJMgqUzgIpA","index":"user"} , message : null
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1778)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:593)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:277)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1251)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1171)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:857)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:760)
	... 22 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.data.elasticsearch.repository.support.SimpleElasticsearchRepository]: Constructor threw exception; nested exception is com.github.vanroy.springdata.jest.exception.JestElasticsearchException: Cannot execute jest action , response code : 400 , error : {"root_cause":[{"type":"resource_already_exists_exception","reason":"index [user/rGcNzfu5RICiJMgqUzgIpA] already exists","index_uuid":"rGcNzfu5RICiJMgqUzgIpA","index":"user"}],"type":"resource_already_exists_exception","reason":"index [user/rGcNzfu5RICiJMgqUzgIpA] already exists","index_uuid":"rGcNzfu5RICiJMgqUzgIpA","index":"user"} , message : null
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:184)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport.lambda$getTargetRepositoryViaReflection$3(RepositoryFactorySupport.java:513)
	at java.util.Optional.map(Optional.java:215)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport.getTargetRepositoryViaReflection(RepositoryFactorySupport.java:513)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport.getTargetRepositoryViaReflection(RepositoryFactorySupport.java:498)
	at org.springframework.data.elasticsearch.repository.support.ElasticsearchRepositoryFactory.getTargetRepository(ElasticsearchRepositoryFactory.java:74)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport.getRepository(RepositoryFactorySupport.java:305)
	at org.springframework.data.repository.core.support.RepositoryFactoryBeanSupport.lambda$afterPropertiesSet$5(RepositoryFactoryBeanSupport.java:297)
	at org.springframework.data.util.Lazy.getNullable(Lazy.java:211)
	at org.springframework.data.util.Lazy.get(Lazy.java:94)
	at org.springframework.data.repository.core.support.RepositoryFactoryBeanSupport.afterPropertiesSet(RepositoryFactoryBeanSupport.java:300)
	at org.springframework.data.elasticsearch.repository.support.ElasticsearchRepositoryFactoryBean.afterPropertiesSet(ElasticsearchRepositoryFactoryBean.java:67)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1837)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1774)
	... 33 common frames omitted
Caused by: com.github.vanroy.springdata.jest.exception.JestElasticsearchException: Cannot execute jest action , response code : 400 , error : {"root_cause":[{"type":"resource_already_exists_exception","reason":"index [user/rGcNzfu5RICiJMgqUzgIpA] already exists","index_uuid":"rGcNzfu5RICiJMgqUzgIpA","index":"user"}],"type":"resource_already_exists_exception","reason":"index [user/rGcNzfu5RICiJMgqUzgIpA] already exists","index_uuid":"rGcNzfu5RICiJMgqUzgIpA","index":"user"} , message : null
	at com.github.vanroy.springdata.jest.mapper.DefaultErrorMapper.mapError(DefaultErrorMapper.java:30)
	at com.github.vanroy.springdata.jest.JestElasticsearchTemplate.execute(JestElasticsearchTemplate.java:1126)
	at com.github.vanroy.springdata.jest.JestElasticsearchTemplate.executeWithAcknowledge(JestElasticsearchTemplate.java:1136)
	at com.github.vanroy.springdata.jest.JestElasticsearchTemplate.createIndex(JestElasticsearchTemplate.java:197)
	at com.github.vanroy.springdata.jest.JestElasticsearchTemplate.createIndexWithSettings(JestElasticsearchTemplate.java:1345)
	at com.github.vanroy.springdata.jest.JestElasticsearchTemplate.createIndexIfNotCreated(JestElasticsearchTemplate.java:1330)
	at com.github.vanroy.springdata.jest.JestElasticsearchTemplate.createIndex(JestElasticsearchTemplate.java:178)
	at org.springframework.data.elasticsearch.repository.support.AbstractElasticsearchRepository.createIndex(AbstractElasticsearchRepository.java:96)
	at org.springframework.data.elasticsearch.repository.support.AbstractElasticsearchRepository.<init>(AbstractElasticsearchRepository.java:87)
	at org.springframework.data.elasticsearch.repository.support.SimpleElasticsearchRepository.<init>(SimpleElasticsearchRepository.java:36)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:172)
	... 46 common frames omitted
~~~

##### **Motivation for or Use Case**

This bug prevents ./mvnw from compiling and running the localhost:8080 server.

##### **Reproduce the error**
1.) Enable LogStash in application-dev.yml.  Set use-json-format to true and logstash.enabled to true.
2.) Spin up the JHipster Console using the instructions provided on the monitoring page of the Jhipster Docs.
3.) Run ./.mvnw
4.) Verify that logs are being sent to localhost:5601/app/logtrail
5.) Ctrl+C on the ./mvnw window
6.) Run ./mvnw again.
Another way to reproduce is:
1. Run ./mvnw and have the localhost up and running normally.
2.) Change some java code in eclipse
3.) Observe ./mvnw auto-reload and fail with the same stack trace as above.

##### **Related issues**

https://github.com/jhipster/generator-jhipster/issues/3958 is a similar issue that was closed due to missing content in the issue description.

##### **Suggest a Fix**

Workaround:  Delete the index before running ./mvnw
Suggested Fix: Replace the existing index with a new index during ./mvnw startup or remove the existing index in ./mvnw shutdown.

##### **JHipster Version(s)**

Running JHipster 6.20.  Existing in 6.1.1 as well.

##### **JHipster Version(s)**

```
offer-letter@0.0.0 /home/cuzimbob/eclipse-offerLetter/offerLetter
├── generator-jhipster@6.2.0 
└─┬ generator-jhipster-social-login-api@0.0.1
  └── generator-jhipster@6.2.0  deduped

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com."
    },
    "jhipsterVersion": "6.2.0",
    "applicationType": "monolith",
    "baseName": "offerLetter",
    "packageName": "com.",
    "packageFolder": "com/",
    "serverPort": "8080",
    "authenticationType": "oauth2",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSwaggerCodegen": true,
    "jwtSecretKey":
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "angularX",
    "clientTheme": "cyborg",
    "clientThemeVariant": "primary",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [
      {
        "name": "generator-jhipster-social-login-api",
        "version": "0.0.1"
      }
    ],
    "enableTranslation": false,
    "blueprints": []
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Company {
  companyName String,
  companyDescription String
}
entity Candidate {
  salutation String,
  firstName String,
  lastName String,
  email String,
  address1 String,
  address2 String,
  city String,
  state String
}
entity Offer {
  positionID String,
  offerName String,
  uniqueLinkID String,
  startingDate LocalDate,
  expirationDate LocalDate,
  description String
}
entity Approval {
  ready Boolean,
  compliance Boolean,
  finalreview Boolean
}
entity OfferSignature {
  dateSigned LocalDate,
  fullName String,
  signature ImageBlob
}
entity CompiledOffer {
  finishedOffer AnyBlob
}
entity OfferContent {
  offerDate LocalDate,
  startingDate LocalDate,
  dutyLocation String,
  programOffice String,
  includeProgramOffice Boolean,
  weeklyHours String,
  wages Long,
  flsaCategory String,
  minClearance String,
  includeMinClearance Boolean,
  positionTitle String,
  reportsTo String,
  description String
}
entity DefaultOfferContent {
  subject String,
  companyName String,
  footer TextBlob,
  header TextBlob,
  logo ImageBlob,
  description String
}
entity Attachments {
  description String,
  attachment AnyBlob
}
entity Paragraph {
  paragraphText TextBlob,
  paragraphName String
}
entity ParagraphPlacement {
  order Long
}
entity SpecialConditions {
  conditionDescription String,
  condition TextBlob
}
entity EmailSystemConfig {
  secretKey AnyBlob,
  serviceAccountID String,
  serviceAccountUser String
}
entity EmailConfiguration {
  type String,
  content String
}
entity Recipient {
  type String,
  address String
}
entity CompanyContact {
  firstName String,
  lastName String,
  department String,
  phoneNumber String,
  email String,
  office String,
  title String,
  type String
}
relationship OneToOne {
  Company{emailSystemConfig} to EmailSystemConfig{company},
  Offer{approval} to Approval{offer},
  Offer{offerSignature} to OfferSignature{offer},
  Offer{compiledOffer} to CompiledOffer{offer},
  Offer{offerContent} to OfferContent{offer}
}
relationship OneToMany {
  DefaultOfferContent{company} to Company{defaultOfferContent},
  Company{candidate} to Candidate{company},
  Candidate{offer} to Offer{candidate},
  ParagraphPlacement{paragraph} to Paragraph{paragraphPlacement}
}
relationship ManyToMany {
  Company{emailConfiguration} to EmailConfiguration{company},
  Company{companyContact} to CompanyContact{company},
  OfferContent{specialConditions} to SpecialConditions{offerContent},
  OfferContent{attachments} to Attachments{offerContent},
  OfferContent{paragraph} to Paragraph{offerContent},
  EmailConfiguration{recipient} to Recipient{emailConfiguration}
}

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.4" 2019-07-16
OpenJDK Runtime Environment (build 11.0.4+11-post-Ubuntu-1ubuntu218.04.3)
OpenJDK 64-Bit Server VM (build 11.0.4+11-post-Ubuntu-1ubuntu218.04.3, mixed mode, sharing)

git version 2.17.1

node: v12.7.0

npm: 6.10.3

yeoman: 3.1.0

Docker version 18.09.7, build 2d0083d

docker-compose version 1.17.1, build unknown

##### **Browsers and Operating System**

Ubuntu 18.04 LTS and Chrome Latest

-   [ x] Checking this box is mandatory (this is just to show you read everything)

**Comment by gmarziou** [comment] 2019-08-09 08:04
@BLKingLLC could you past the stack trace, not only the cause? Because I don't see the relation between getting a Jest exception and logstash logging. Logstash appender does not connect directly to Elasticsearch, it connects to logstash on port 5000 in jhipster-console, so it does not use Jest at all.

**Comment by BLKingLLC** [comment] 2019-08-09 15:58
@gmarziou I've updated the ticket with the full stack trace.  It's possible that I'm wrong about it being logstash, but it's definitely the index created in target/elasticsearch/data/nodes/0/indices

**Comment by BLKingLLC** [comment] 2019-08-15 15:36
In CacheConfiguration.java I added cache.clear() and cache.close() and now when I run ./mvnw again I don't get the error.  But, I still get the error when mvnw does an automatic rebuild after it detects changed code.

**Comment by pascalgrimaud** [comment] 2019-08-16 13:02
After spending a couple of minutes to generate the correct project with your configuration (because your `.yo-rc.json` is not valid and you edited it), I didn't manage to reproduce.
I can stop / start without any problem

The problem you encountered, seems to be related to Elasticsearch, not logstash.

Feel free to push a project on GitHub with the problem and I'll try to reproduce. But for now, as the issue couldn't be reproduced, I'm closing this.

**Closed by pascalgrimaud** 2019-08-16 13:02 UTC
Labels: area: needs-reproduction, theme: java

**Comment by BLKingLLC** [comment] 2019-08-16 18:15
@pascalgrimaud I can add you to my private repo and let you check that out and take it for a spin.  The bug is really a PITA. Let me know if you want to give that a shot.

**Comment by pascalgrimaud** [comment] 2019-08-16 18:17
@BLKingLLC : I'd prefer you to create a fresh JHipster project, and push it publicly, so everyone can have a look, and check if there is a real issue or not
Because, with a fresh project, there is no additional code

**Comment by gmarziou** [comment] 2019-08-16 19:53
Also your project is a bit complex for easy reproduction requiring to start several containers: mysql in dev vs h2, use of Eureka, use of jhipster-console. I'm pretty sure these external dependencies have nothing to do with the problem, I would rather bet on application context refresh scope issue when devtools restart the app. You should be able to nail it by running under debugger with a breakpoint in  SimpleElasticsearchRepository constructor.

**Comment by BLKingLLC** [comment] 2019-08-19 19:02
I couldn't reproduce it with a fresh jhipster project but I did find that it seems to be time dependent.  If I give maven a minute between builds then it starts with no issue.  It's like the file is still locked or something.

**Comment by nury-garryyev** [comment] 2019-10-28 11:12
I have the same problem. I have asked a question for the same problem on StackOverflow.
https://stackoverflow.com/questions/58553331/elasticsearch-error-when-re-running-jhipster-project-error-creating-bean-with-n?noredirect=1#comment103441536_58553331

Please find the GitHub repository to reproduce the error.
https://github.com/nury-garryyev/jhipster

Please help me with this issue. Let me know if you need additional information.

**Comment by tmdonalds** [comment] 2019-11-09 22:45
I am receiving this exact error. Can someone help me please?

**Comment by pascalgrimaud** [comment] 2019-11-10 10:45
@tmdonalds : have a look at other ticket and my suggestion https://github.com/jhipster/generator-jhipster/issues/10702#issuecomment-548257419

**Comment by tmdonalds** [comment] 2019-11-10 13:11
thanks @pascalgrimaud . I am using ubuntu. That worked. I just ended up blowing away my target/elasticsearch dir before every build. That worked as well. Such a strange error.

**Comment by wattazoum** [comment] 2020-05-16 17:26
Hi,

I have been having the same error. I tried different tests and realize something that might cause this issue:

## The issue

> Happens only when using the `dev` profile 

When the application starts, it will try to find if the ES indices exist for my repositories. If they don't exist,  it will create them. 

How does it proceed for that? Jest makes a call to ES the server and if it receives a 404 it will launch a call to create the index. 
What happens it that the ES server becomes ready between those 2 moments. (This explains why some might not be able to reproduce it. It depends on the power of your laptop, or the component initialization order in your project (triggers the workaround 3) ). 

## Workarounds (mentionned by others above)

1. Use an external ES server
2. Remove the internal ES data folder between each start (doesn't solve the fact that ES will be ready between the 2 moments but the second call will not fail because the index doesn't exist)
3. Find a way for ES to be ready before the first call from Jest: On my laptop this happens when I start the server in debug mode (from my IDE)

**Comment by fitdeveloper** [comment] 2020-12-28 22:11
@wattazoum you are a genius thanks buddy !!!
