### ISSUE TITLE
MSSQL Setting gateway cant startup 

### ISSUE THREAD

**Issue by taohannan** [jhipster/generator-jhipster#4612] opened 2016-12-06 04:05 UTC
```

```yaml
{
  "generator-jhipster": {
    "jhipsterVersion": "3.11.0",
    "baseName": "IASGateway",
    "packageName": "com.mbb.ias",
    "packageFolder": "com/mbb/ias",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": "kafka",
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "jwtSecretKey": "b2bfde017b580423fad9f0bc49457e4c273ae27d",
    "useSass": false,
    "applicationType": "gateway",
    "testFrameworks": [
      "gatling"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}


##### **Entity configuration(s) `entityName.json` files generated

ls: no such file or directory: .jhipster/*.json
##### **Browsers and Operating System**

java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)

git version 2.10.2.windows.1

node: v7.2.0

npm: 3.10.9

bower: 1.8.0

gulp:
[11:38:39] CLI version 1.2.2
[11:38:39] Local version 3.9.1

yeoman: 1.8.5

```

##### **Overview of the issue**
Hi,
Im trying to create Jhipster Microservices Backend Applications using MSSQL  setup provided at tips an trick.  i configure everything as per advise and run mvn command to start the project and its throw this error:

```
```2016-12-06` 11:41:41.118  WARN 18016 --- [  restartedMain] ationConfigEmbeddedWebApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'liquibase' defined in class path resource [com/mbb/ias/config/DatabaseConfiguration.class]: Unsatisfied dependency expressed through method 'liquibase' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSource' defined in class path resource [org/springframework/boot/autoconfigure/jdbc/DataSourceConfiguration$Tomcat.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.apache.tomcat.jdbc.pool.DataSource]: Factory method 'dataSource' threw exception; nested exception is org.springframework.boot.autoconfigure.jdbc.DataSourceProperties$DataSourceBeanCreationException: Cannot determine embedded database driver class for database type NONE. If you want an embedded database please put a supported one on the classpath. If you have database settings to be loaded from a particular profile you may need to active it (the profiles "swagger,dev" are currently active).
2016-12-06 11:41:41.118  WARN 18016 --- [  restartedMain] o.s.boot.SpringApplication               : Error handling failed (Error creating bean with name 'delegatingApplicationListener' defined in class path resource [org/springframework/security/config/annotation/web/configuration/WebSecurityConfiguration.class]: BeanPostProcessor before instantiation of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.cache.config.internalCacheAdvisor' defined in class path resource [org/springframework/cache/annotation/ProxyCachingConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.cache.interceptor.BeanFactoryCacheOperationSourceAdvisor]: Factory method 'cacheAdvisor' threw exception; nested exception is java.lang.NullPointerException)
2016-12-06 11:41:41.118 ERROR 18016 --- [  restartedMain] o.s.b.d.LoggingFailureAnalysisReporter   :

***************************
APPLICATION FAILED TO START
***************************

Description:

Cannot determine embedded database driver class for database type NONE

Action:

If you want an embedded database please put a supported one on the classpath. If you have database settings to be loaded from a particular profile you may need to active it (the profiles "swagger,dev" are currently active).```
```

this is my dev-profile :
```
spring:
    profiles:
        active: dev
        include: swagger
    autoconfigure:
        exclude: org.springframework.boot.autoconfigure.cassandra.CassandraAutoConfiguration
    devtools:
        restart:
            enabled: true
        livereload:
            enabled: false # we use gulp + BrowserSync for livereload
    jackson:
        serialization.indent_output: true
    cloud:
        stream:
            kafka:
                binder:
                    brokers: localhost
                    zk-nodes: localhost
            bindings:
                output:
                    destination: topic-jhipster
                    
datasource:
        driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDataSource
        url: jdbc:sqlserver://localhost:1433
        databaseName: IASDB
        serverName: localhost
        user: devuser  
        password: CIAtopSecret
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
jpa:
        database-platform: org.hibernate.dialect.SQLServerDialect
        database: SQL_SERVER
        openInView: false
        show_sql: true
        generate-ddl: false
        properties:
            hibernate.cache.use_second_level_cache: true
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: true
            hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory
```
my pom snippet:
```
			<groupId>com.github.sabomichal</groupId>
			<artifactId>liquibase-mssql</artifactId>
			<version>1.4</version>
		</dependency>
		<!-- jhipster-needle-maven-add-dependency -->
		<!-- Microsoft JDBC -->
		<dependency>
			<groupId>com.microsoft.sqlserver</groupId>
			<artifactId>sqljdbc41</artifactId>
			<version>4.1</version>
		</dependency>
```
i did tried with driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver also but its throw the same error.

##### **Motivation for or Use Case**
My microservices setup didnt throw db error but also cant start due to :

```
`2016-12-05 19:58:17.788  INFO 14068 --- [  restartedMain] com.mbb.ias.IasBackendApp                : Started IasBackendApp in 1.579 seconds (JVM running for 20.086)
2016-12-05 19:58:18.871  WARN 14068 --- [0:0:0:0:1:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.ConnectException: Connection refused: no further information
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
        at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
        at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)

2016-12-05 19:58:19.975  WARN 14068 --- [127.0.0.1:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.ConnectException: Connection refused: no further information
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
        at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
        at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)

2016-12-05 19:58:22.077  WARN 14068 --- [0:0:0:0:1:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.ConnectException: Connection refused: no further information
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
        at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
        at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)

2016-12-05 19:58:23.198  WARN 14068 --- [127.0.0.1:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.ConnectException: Connection refused: no further information
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
        at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
        at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)

2016-12-05 19:58:25.299  WARN 14068 --- [0:0:0:0:1:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.ConnectException: Connection refused: no further information
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
        at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
        at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)

2016-12-05 19:58:26.400  WARN 14068 --- [127.0.0.1:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.ConnectException: Connection refused: no further information
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
        at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
        at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)`
```

so my assumption for my microservices app didnt start is because of my gateway is not up yet? thats why i tried to bring up my gateway and i encountered this error.
Im using windows 7 pro 64bit.

Please advise

**Comment by ruddell** [comment] 2016-12-06 05:19
We just merged MSSQL as an option in #4589.  It will be officially available in the next release.  

The tip is slightly outdated for our latest database config.  Here's what you will need (remove `driver-class-name`):
```
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:sqlserver://localhost:1433;database=msqltest
        username: SA
        password: yourStrong(!)Password
        hikari:
                  .........
    jpa:
        database-platform: org.hibernate.dialect.SQLServer2012Dialect
        database: SQL_SERVER
                  .........        
```
Also the official driver is now in mvn central:
```
 <dependency>
     <groupId>com.microsoft.sqlserver</groupId>
     <artifactId>mssql-jdbc</artifactId>
     <version>6.1.0.jre8</version>   
</dependency>
```

About your second problem, it looks like an issue with Kafka/Zookeeper.  Check to make sure they are running, you can start them locally with docker: `docker-compose src/main/docker/kafka.yml up -d`

**Comment by taohannan** [comment] 2016-12-06 06:00
Hi @ruddell 
How about the liquibase mssql extension? do i still need it since i just intended to setup microservices and the gateway.  Planned to regenerate the apps =)

**Comment by ruddell** [comment] 2016-12-06 06:29
That's still needed as well

**Comment by jdubois** [comment] 2016-12-06 07:05
Yes it will be supported in the next versions, so at the moment this isn't a bug, as it's just a tip.
Then in your stacktrace you have a Zookeeper stacktrace, so that's probably not caused by MS SQL.
@taohannan @ruddell if you find issues in the tip, don't hesitate to do a PR and change it, the source is [here](https://github.com/jhipster/jhipster.github.io/tree/master/tips)

**Closed by jdubois** 2016-12-06 07:05 UTC

**Comment by maektwain** [comment] 2018-01-10 11:20
About your second problem, it looks like an issue with Kafka/Zookeeper. Check to make sure they are running, you can start them locally with docker: docker-compose -f  src/main/docker/kafka.yml up -d
