### ISSUE TITLE
Karma Coverage Report shows always 100% coverage of nothing

### ISSUE THREAD

**Issue by kheckelmann** [jhipster/generator-jhipster#5271] opened 2017-02-21 12:26 UTC
- Please follow the issue template below for bug reports and feature requests.
- Tickets opened without any of these informations will be **closed** without any explanation.

##### **Overview of the issue**

After generating a jhipster gateway with Angular 2 frontend and starting the Karma Unit-Tests the coverage report shows 100% of everything and no files. That can't be right, because initially there is only one Karma-Unit-Test present.

##### **Motivation for or Use Case**

Coverage report is not very useful this way.

##### **Reproduce the error**

Generate a Gateway with Angular 2.

##### **JHipster Version(s)**

At least 4.0.3 and 4.0.5

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "jhipsterVersion": "4.0.3",
    "baseName": "person",
    "packageName": "com.diamos.person",
    "packageFolder": "com/diamos/person",
    "serverPort": "51286",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "gradle",
    "enableSocialSignIn": false,
    "jwtSecretKey": "14b70ac02ed21d1be0d0f7608754c21cdfd9be21",
    "useSass": true,
    "clientPackageManager": "npm",
    "applicationType": "gateway",
    "clientFramework": "angular2",
    "testFrameworks": [
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "de",
    "languages": [
      "de",
      "en"
    ]
  }
}
```
##### **Browsers and Operating System**

java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

git version 1.8.4.msysgit.0

node: v6.9.5

npm: 3.10.10

yeoman: 1.8.5

yarn: 0.19.1

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment] 2017-02-21 12:27
Duplicate of #5243 - our directory is not correct

**Comment by kaidohallik** [comment] 2017-02-21 17:59
@jdubois Both coverage reports are empty:
* in `build/test-results/coverage`
* in `src/test/javascript/coverage`

Seems that coverage configuration needs update to resolve both this issue and #5243

**Comment by jdubois** [comment] 2017-02-21 19:33
OK, re-opening!

**Comment by jdubois** [comment] 2017-03-09 15:42
I do have correctly the report in `target/test-results/coverage` (I'm using Maven, so it's in `target`)

Then there was a second, false report in `src/test/javascript/coverage`, and that was a report on the compiled JavaScript - no idea why we had this, and it's just wrong. I'll do a PR to remove it and close this.

**Comment by kheckelmann** [comment] 2017-03-10 14:16
Removing the coverage reporter prevents the second report to be written, but my coverage report in the build folder is still empty. Maybe the problem occurs only with gradle? Does anybody have the same problem?

**Comment by jdubois** [comment] 2017-03-10 14:21
@kheckelmann oh yes I only tested with Maven, so there might a difference with Gradle. Shouldn't be a big issue, but still I'm reopening this.

**Comment by jdubois** [comment] 2017-03-11 08:44
Tested with Maven + Gradle, both work! Not sure what's your exact issue @kheckelmann but now this should all be solved!

**Closed by jdubois** 2017-03-11 08:44 UTC

**Comment by kaidohallik** [comment] 2017-03-20 15:59
It can be Windows issue, in my tests:
* in Ubuntu correct coverage report is generated
* in Windows empty coverage report is generated

**Comment by kaidohallik** [comment] 2017-04-25 19:08
FYI. I discovered additional case when coverage is always 100%: if project path contains substring `test`. It's probably caused by this line https://github.com/jhipster/generator-jhipster/blob/master/generators/client/templates/angular/src/test/javascript/_karma.conf.js#L87

**Comment by thecolas** [comment] 2017-04-25 19:38
@kaidohallik Thank you a lot. I got a problem since 2 days and can't solve it.

I test all my project in GitLab CI but I got 100% 0/0 during the coverage step.

I try to reproduce this issue in **local** with the same docker has CI but the coverage was OK.

My project's name was **test-jhipster** so during the CI it's was cloning it in **test-jhipster/** directory and coverage don't pass.
In local I mount myself the project in **/home/jhipster/app** so there was no **test** in the path and the coverage pass.

I rename my gitlab project and now the coverage is OK.
