### ISSUE TITLE
Can't run .war.original on Tomcat 9.0 because of wrong Content-Type header

### ISSUE THREAD

**Issue by anthony-o** [jhipster/generator-jhipster#8890] opened 2018-11-27 16:27 UTC
##### **Overview of the issue**

When trying to run the `.war.original` war of my application on Tomcat 9.0 and trying to access it via http://localhost:8080/ I've got the following error in the console:
```
0.14e73ee94b13c0699bd4.chunk.js:1 Uncaught SyntaxError: Invalid regular expression: /[^ 

	áš€á Žâ€€-â€Š  â€¯âŸã€€﻿]/: Range out of order in character class
    at new RegExp (<anonymous>)
    at Object.<anonymous> (0.14e73ee94b13c0699bd4.chunk.js:1)
    at r (main.14e73ee94b13c0699bd4.bundle.js:1)
    at Object.<anonymous> (0.14e73ee94b13c0699bd4.chunk.js:1)
    at Object.<anonymous> (0.14e73ee94b13c0699bd4.chunk.js:1)
    at r (main.14e73ee94b13c0699bd4.bundle.js:1)
    at Module.384 (main.14e73ee94b13c0699bd4.bundle.js:1)
    at r (main.14e73ee94b13c0699bd4.bundle.js:1)
    at u (main.14e73ee94b13c0699bd4.bundle.js:1)
    at main.14e73ee94b13c0699bd4.bundle.js:1
```

This is due to the fact that when my browser asks for the root `/` page, Tomcat sends the following wrong response header: `Content-Type: text/html;charset=ISO-8859-1`

When I run it with classical `./target/test-app-0.0.1-SNAPSHOT.war`, the header sent for the `/` page is `Content-Type: text/html;charset=utf-8` and the application is correctly running.

##### **Motivation for or Use Case**

I want to run my JHipster application on Tomcat 9.0.

##### **Reproduce the error**

```bash
mkdir test-app
cd test-app

cat > test-app.jdl <<EOF
application {
  config {
    applicationType monolith
    authenticationType oauth2
    baseName TestApp
    buildTool maven
    cacheProvider hazelcast
    clientPackageManager yarn
    devDatabaseType postgresql
    enableSwaggerCodegen false
    enableTranslation false
    languages [fr]
    nativeLanguage fr
    packageName fr.mycompany.testapp
    prodDatabaseType postgresql
    testFrameworks [cucumber, gatling]
    useSass true
  }

  entities *
}
EOF

docker run -it --rm --name jhipster -v "$(pwd):/home/jhipster/app" -v ~/.m2:/home/jhipster/.m2 -v ~/.cache/yarn:/home/jhipster/.cache/yarn -v "$HOME/.gitconfig:/home/jhipster/.gitconfig:ro" jhipster/jhipster:v5.7.0 jhipster import-jdl ./test-app.jdl --force

./mvnw -Pprod package

cat > src/main/docker/app-tomcat.yml <<EOF
version: '2'
services:
    testapp-app:
        image: tomcat:9.0-jre8-slim
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://testapp-postgresql:5432/TestApp
            - SECURITY_OAUTH2_CLIENT_ACCESS_TOKEN_URI=http://keycloak:9080/auth/realms/jhipster/protocol/openid-connect/token
            - SECURITY_OAUTH2_CLIENT_USER_AUTHORIZATION_URI=http://keycloak:9080/auth/realms/jhipster/protocol/openid-connect/auth
            - SECURITY_OAUTH2_CLIENT_CLIENT_ID=web_app
            - SECURITY_OAUTH2_CLIENT_CLIENT_SECRET=web_app
            - SECURITY_OAUTH2_CLIENT_SCOPE=openid profile email
            - SECURITY_OAUTH2_RESOURCE_USER_INFO_URI=http://keycloak:9080/auth/realms/jhipster/protocol/openid-connect/userinfo
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
        volumes:
          - ../../../target/test-app-0.0.1-SNAPSHOT.war.original:/usr/local/tomcat/webapps/ROOT.war
        command: bash -c "rm -rf webapps/ROOT && catalina.sh run"
    testapp-postgresql:
        extends:
            file: postgresql.yml
            service: testapp-postgresql
    keycloak:
        extends:
            file: keycloak.yml
            service: keycloak
EOF

docker-compose -f src/main/docker/app-tomcat.yml up
```
Here when I access to http://localhost:8080/ I have the error I described in the overview of the issue.
Nevertheless, if I access to http://localhost:8080/index.html , the sent header is `Content-Type: text/html` and I can correctly access it using Firefox, but failing with the same issue as the overview using Chromium.

Now if I run:
```bash
docker-compose -f src/main/docker/app-tomcat.yml down --volumes

docker-compose -f src/main/docker/app.yml up testapp-postgresql keycloak &

./target/test-app-0.0.1-SNAPSHOT.war
```
I can correctly access my application at the `/` url or the `/index.html`, the sent header is the correct `Content-Type: text/html;charset=utf-8`.

##### **JHipster Version(s)**

```
test-app@0.0.0 /home/jhipster/app
`-- generator-jhipster@5.7.0 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "enableHibernateCache": true,
    "enableSwaggerCodegen": false,
    "enableTranslation": false,
    "jhiPrefix": "jhi",
    "languages": [
      "fr"
    ],
    "messageBroker": false,
    "nativeLanguage": "fr",
    "packageName": "fr.mycompany.testapp",
    "packageFolder": "fr/mycompany/testapp",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "serviceDiscoveryType": false,
    "skipClient": false,
    "skipServer": false,
    "testFrameworks": [
      "cucumber",
      "gatling"
    ],
    "websocket": false,
    "applicationType": "monolith",
    "authenticationType": "oauth2",
    "baseName": "TestApp",
    "buildTool": "maven",
    "cacheProvider": "hazelcast",
    "clientPackageManager": "yarn",
    "useSass": true,
    "jhipsterVersion": "5.7.0",
    "skipUserManagement": true,
    "clientFramework": "angularX",
    "serverPort": "8080",
    "otherModules": []
  },
  "entities": []
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

openjdk version "1.8.0_181"
OpenJDK Runtime Environment (build 1.8.0_181-8u181-b13-1ubuntu0.18.04.1-b13)
OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)

git version 2.17.1

node: v10.13.0

npm: 6.4.1

yeoman: 2.0.5

yarn: 1.12.3

##### **Browsers and Operating System**

Firefox 63.0 & Chromium 70.0.3538.77 on Ubuntu 16.04 LTS

-   [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by ruddell** [comment] 2018-11-27 17:56
Duplicate of https://github.com/jhipster/generator-jhipster/issues/8586

The fix was merged 2 days ago and will be in the next release.  If you don't care about running your app in docker, the only change needed to fix is:

https://github.com/jhipster/jhipster-sample-app/blob/master/webpack/webpack.prod.js#L27

        -path: utils.root('target/classes/public'),
        +path: utils.root('target/www'),

**Closed by ruddell** 2018-11-27 17:56 UTC

**Comment by anthony-o** [comment] 2018-11-28 13:14
@ruddell great thank you it solved this problem actually.
