### ISSUE TITLE
Spring Native support in JHipster 7

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#14289] opened 2021-03-12 13:40 UTC
JHipster 7 is based on Spring Boot 2.4.3, and thus should work fine with Spring Native Beta using https://docs.spring.io/spring-native/docs/current/reference/htmlsingle/#_build_the_native_application

-> Here is a sample application, generated today from the `main` branch, using the default options: https://github.com/jdubois/experimental-jhipster7-native

- Here is what I configured for Spring Native to work: https://github.com/jdubois/experimental-jhipster7-native/commit/1333f4bed3ad6146f6659d8491a4e12d2fd51b4d (this works on a simplified project)
- To build it, you need to use the "prod" profile: `mvn spring-boot:build-image -Pprod`
- To run it, as you'll need the database, you need to go to `src/main/docker` and do `docker-compose -f app.yml up`

As discussed with @sdeleuze I'm creating an issue for this on https://github.com/spring-projects-experimental/spring-native and will link it here -> work should happen on that other ticket, probably.

I'm adding a [$500 bug bounty](https://www.jhipster.tech/bug-bounties/) on this ticket, as this is super important.

**Comment by mshima** [comment] 2021-03-12 13:42
Duplicate of https://github.com/jhipster/generator-jhipster/issues/13733?

**Comment by jdubois** [comment] 2021-03-12 13:45
Oh yes, you're right @mshima !!!
Let's close this one, and migrate my comment and bounty there

**Comment by pascalgrimaud** [comment] 2021-03-12 13:45
Yes, it's duplicated. There are already some discussions in the other ticket :)

**Comment by jdubois** [comment] 2021-03-12 13:48
And I'm the one complaining that people don't read existing opened tickets !
Who's managing this thing??? 🤣

**Closed** 2021-03-12 13:49 UTC
Labels: area: feature request :bulb:, theme: docker :whale:
