### ISSUE TITLE
JHipster Database dummy data

### ISSUE THREAD

**Issue by iDisturb** [jhipster/generator-jhipster#10013] opened 2019-07-01 08:57 UTC
##### **Overview of the issue**

I would like to disable the generation of dummy data on my database when running my JHipster application, there's probably a setting to disable this but I just can't find it.

##### **Motivation for or Use Case**

Because I don't want my project to be filled with information that is not mine.

##### **Reproduce the error**

Running the project will cause this.

##### **Related issues**

Only started happening with new JHipster versions.

**Comment by clement26695** [comment] 2019-07-01 09:10
You can look into the src/main/resources/config/application-dev.yml file and remove "faker" in spring.liquibase.contexts

**Comment by jdubois** [comment] 2019-07-01 09:14
Closing as this is not a bug, and @clement26695 is correct (also have a look at the documentation, but I know it's complex when you start)

**Closed by jdubois** 2019-07-01 09:14 UTC

**Comment by murdos** [comment] 2019-07-01 09:31
@jdubois I don't think there's any documentation on fake-data.

**Comment by deepu105** [comment] 2019-07-01 09:38
@jdubois since many people have been opening similar issue, maybe we can disable the fake data profile by default and people can enable it if required. WDYT? I also personally would like fake data not loaded by default in dev

**Comment by jdubois** [comment] 2019-07-01 09:44
Yes I see many people disliking it, but it's always the same thing, the happy people never talk 😀
If we disable it by default, we might as well totally remove it, as I know people will forget about it, so it won't be used, and so there'll be tons of bugs. Please note that the idea is also you can edit the files with a spreadsheet, so you can put your own data there -> WDYT about removing faker, and just keeping the empty files?

**Comment by deepu105** [comment] 2019-07-01 09:57
Ya may be lets keep the mechanism and disable faker data by default and may
be we can enable faker data injection while generation with a flag

Thanks & Regards,
Deepu

**Comment by iDisturb** [comment] 2019-07-01 13:20
Yes it would be great if you guys make it optional because it was confusing to me at first, I didn't know it was linked to a profile and there's no information to explain it in JHipster's website, thank you everyone, keep up the good work with this generator.

**Comment by gmarziou** [comment] 2019-07-01 16:17
One thing that also confuses some users about fake data is that when they add their own data to generated CSV file they get a Liquibase checksum error. I think that calling loadData from *_added_entity_*.xml migration adds confusion, I would rather call it from a dedicated migration.
