### ISSUE TITLE
Metrics not working in AWS

### ISSUE THREAD

**Issue by carpanese** [jhipster/generator-jhipster#5371] opened 2017-03-06 02:24 UTC
##### **Overview of the issue**

When deploying to production on AWS, I encountered problems viewing the application metrics. I noticed that the problem has to do with getting the value of the garbage from the JVM

`TypeError: Cannot read property 'value' of undefined
    at View_JhiMetricsMonitoringComponent1.detectChangesInternal (/GetrangoAdminModule/JhiMetricsMonitoringComponent/component.ngfactory.js:820)
    at View_JhiMetricsMonitoringComponent1.AppView.detectChanges (vendor.dll.js:97514)
    at View_JhiMetricsMonitoringComponent1.DebugAppView.detectChanges (vendor.dll.js:97709)
    at ViewContainer.detectChangesInNestedViews (vendor.dll.js:97847)
    at CompiledTemplate.proxyViewClass.View_JhiMetricsMonitoringComponent0.detectChangesInternal (/GetrangoAdminModule/JhiMetricsMonitoringComponent/component.ngfactory.js:3582)
    at CompiledTemplate.proxyViewClass.AppView.detectChanges (vendor.dll.js:97514)
    at CompiledTemplate.proxyViewClass.DebugAppView.detectChanges (vendor.dll.js:97709)
    at CompiledTemplate.proxyViewClass.AppView.internalDetectChanges (vendor.dll.js:97499)
    at CompiledTemplate.proxyViewClass.View_JhiMetricsMonitoringComponent_Host0.detectChangesInternal (/GetrangoAdminModule/JhiMetricsMonitoringComponent/host.ngfactory.js:29)
    at CompiledTemplate.proxyViewClass.AppView.detectChanges (vendor.dll.js:97514)
    at CompiledTemplate.proxyViewClass.DebugAppView.detectChanges (vendor.dll.js:97709)
    at ViewContainer.detectChangesInNestedViews (vendor.dll.js:97847)
    at CompiledTemplate.proxyViewClass.View_JhiMainComponent0.detectChangesInternal (/GetrangoAppModule/JhiMainComponent/component.ngfactory.js:112)
    at CompiledTemplate.proxyViewClass.AppView.detectChanges (vendor.dll.js:97514)
    at CompiledTemplate.proxyViewClass.DebugAppView.detectChanges (vendor.dll.js:97709)`

The line of error

`var currVal_206 = jit_inlineInterpolate19(1,'',self.parentView.context.metrics.gauges['jvm.garbage.PS-MarkSweep.count'].value,'');`

##### **Motivation for or Use Case**

This is a bug because it does not allow the visualization of the metrics. The same is true for deploying packages in web containers (Tomcat).

##### **Reproduce the error**

I used the production commands:

**yo jhipster:aws** and also, running straight into a Virtual Machine (EC2) I got the same problem. **./mvnw -Pprod**

##### **Related issues**

I did not find anything related to this problem.

##### **Suggest a Fix**

I have not found a solution to the problem yet.

##### **JHipster Version(s)**

4.0.7 - Angular 2 - Application Monolithic

##### **JHipster configuration**

Newly created application without any modification.

{
  "generator-jhipster": {
    "jhipsterVersion": "4.0.7",
    "baseName": "getrango",
    "packageName": "br.com.getrango",
    "packageFolder": "br/com/getrango",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": true,
    "jwtSecretKey": "-",
    "clientFramework": "angular2",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "pt-br",
    "languages": [
      "pt-br"
    ],
    "aws": {
      "applicationName": "getrango",
      "environmentName": "getrango-tst",
      "bucketName": "getrango",
      "instanceType": "t2.micro",
      "awsRegion": "sa-east-1",
      "dbName": "getrangotst",
      "dbInstanceClass": "db.t2.micro"
    }
  }
}

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

No entities

##### **Browsers and Operating System**

All navigators.

**Comment by jdubois** [comment] 2017-03-06 07:17
Are you sure this is linked to AWS? It looks like our prod build doesn't work well for the monitoring page, that's all -> if correct, can you update the title of the ticket?
And please note you are using Angular 2, and it is still in beta, so that's normal (the prod build isn't perfect yet, I keep telling it all the time, we need help here)

**Comment by carpanese** [comment] 2017-03-06 12:04
Hi, I updated the title.

My application is not in production yet, however, I'm already doing Angular 2 tests.

**Comment by jdubois** [comment] 2017-03-06 15:55
I just tested a very similar application, with `./mvnw -Pprod` and couldn't reproduce the issue.... This isn't linked to AWS, for me this comes from the "prod" build.

**Comment by jdubois** [comment] 2017-03-06 15:57
Oh sorry, you are deploying in Tomcat? Could you try running the executable JAR, like a normal JHipster build, so we can see if that makes a difference?
Maybe also an issue with your JVM? Which JVM are you using? Could you try running your application in the JHipster Devbox, so we are sure you are in the same conditions?
Otherwise I will close this, as I can't reproduce.

**Comment by carpanese** [comment] 2017-03-06 17:35
Hello,

I thought it might be a little bit related to openjdk however, I have now installed an Oracle JDK. The error continues.

`java version "1.8.0_112"
Java(TM) SE Runtime Environment (build 1.8.0_112-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.112-b15, mixed mode)
`

**Check URL** 
[http://52.67.68.96:8080](http://52.67.68.96:8080)

**I tried running the war via ./app.war and the problem occurred too.**

**Comment by carpanese** [comment] 2017-03-06 18:09
In Cloud Foundry works fine. 

I commented lines of garbage collector in html, its works. 

The problem is related to **jvm.garbage** in aws

Suggestions?

**Comment by jdubois** [comment] 2017-03-06 21:40
This is probably linked to the jvm and its options, but I need some time to investigate.

**Comment by jdubois** [comment] 2017-03-06 21:41
An easy solution would be to add a switch and ignore the error, but I'd like to understand it.

**Comment by jdubois** [comment] 2017-03-06 22:32
The "jvm.garbage" data comes from Dropwizard Metrics, more specifically this class: https://github.com/dropwizard/metrics/blob/3.2-development/metrics-jvm/src/main/java/com/codahale/metrics/jvm/GarbageCollectorMetricSet.java

Maybe you could try to debug it? Or this if you have a stacktrace there?

**Comment by jdubois** [comment] 2017-03-07 10:22
So I guess this depends on the JVM - I don't really understand why, but if we don't have the metrics, then let's just not display them.

**Closed** 2017-03-07 10:33 UTC
Labels: aws

**Comment by carpanese** [comment] 2017-03-07 12:00
Nice @jdubois !
