### ISSUE TITLE
"relationship name is not synchronized" is broken

### ISSUE THREAD

**Issue by gzsombor** [jhipster/generator-jhipster#13885] opened 2021-02-08 09:09 UTC
##### **Overview of the issue**

There is a check for relationship names, which is incorrect, and prevents perfectly valid JDL setups to be generated
And even worse, the error message is very confusing - as very low level - which doesn't help to solve the issue.

##### **Motivation for or Use Case**

I have multiple relations between entities, but I can't generate the entities with this check in place.

##### **Reproduce the error**
JDL:
```

entity Node {
}

entity OtherEntity {
}
relationship ManyToOne {
     OtherEntity{node} to Node{others}
     Node{mainOther} to OtherEntity
 }
```

If I add a `Node{mainOther} to OtherEntity{reverseMains}` - then it will generate the entities, however, that will add a     `Set<Node> reverseMains` to OtherEntity, which I would like to avoid, as doesn't make too much sense, and could accidentally trigger unwanted db queries, etc

##### **Suggest a Fix**

I think, this check needs to be removed - or reduce to 'warning' level

##### **JHipster Version(s)**

Latest main branch

##### **Browsers and Operating System**

- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment] 2021-02-10 02:34
This bug should be fixed by https://github.com/jhipster/generator-jhipster/pull/13900.

But the back reference will be added, currently jdl always generates back references.
Back reference problem is related to https://github.com/jhipster/generator-jhipster/issues/13305

**Comment by DanielFran** [comment] 2021-02-10 12:03
Closed by #13900

**Closed by DanielFran** 2021-02-10 12:03 UTC
Labels: area: bug :bug:, theme: JDL, theme: entities

**Comment by ndjordjevic** [comment] 2021-03-24 16:15
I'm getting the following error during the project upgrade to JHipster 7.0.0. Any idea what's wrong?

```
Error: Error at entity Firma: relationship name is not synchronized {
    "relationshipType": "one-to-one",
    "otherEntityName": "radnik",
    "otherEntityRelationshipName": "firma",
    "relationshipName": "direktor",
    "otherEntityField": "id",
    "ownerSide": true,
    "otherEntity": "[Radnik Entity]",
    "collection": false,
    "otherSideReferenceExists": false,
    "otherEntityIsEmbedded": false
} with {
    "relationshipType": "many-to-one",
    "otherEntityName": "firma",
    "otherEntityRelationshipName": "radnik",
    "relationshipName": "firma",
    "otherEntityField": "id",
    "otherEntity": "[Firma Entity]"
}
    at prepareRelationshipForTemplates (/Users/ndjordjevic/IdeaProjects/isb/node_modules/generator-jhipster/utils/relationship.js:64:15
```
I have 1-1 rel between firm and worker (1 firm has one director (worker)) and many to one between workers and firm... Many workers work for one firm.
No problems generating that model from a JDL file with a 6.10.5 version

**Comment by gmarziou** [comment] 2021-03-24 18:37
@ndjordjevic as this was supposed to be fixed, I suggest you open a new issue and you include the JDL file. Does it happen only during upgrade or can you reproduce it with a fresh project in 7.0?

**Comment by mshima** [comment] 2021-03-24 18:57
JDL always generate bi-lateral relationships.
```
entity Firm {
}
entity Worker {
}
relationship OneToOne {
  Firm{director} to Worker
}
relationship OneToMany {
  Firm{workers} to Worker
}
```
implies:
```
entity Firm {
}
entity Worker {
}
relationship OneToOne {
  Firm{director} to Worker{firm}
}
relationship OneToMany {
  Firm{workers} to Worker{firm}
}
```

Having 2 relationships from Worker with firm name can cause this error.

**Comment by ndjordjevic** [comment] 2021-03-24 19:36
JDL I have regarding those two entities looks like this:

relationship OneToOne {
    Firm{director} to Worker
}

relationship ManyToOne {
    Worker{firm} to Firm,
}

**Comment by ndjordjevic** [comment] 2021-03-25 14:20
Also it's not just when Im upgrading the app, it's the same with a newly created one.. So I think this should be re-opened

**Comment by mshima** [comment] 2021-03-25 16:29
@ndjordjevic for now you need to add a back name to fix the conflict:
```
relationship OneToOne {
  Firm{director} to Worker{firmDirector}
}

relationship ManyToOne {
  Worker{firm} to Firm,
}
```

**Comment by robinrjoe** [comment] 2021-04-27 08:54
What should be the work around for this issue? Is this fixed?
I get the same issue even after upgrading the latest version of Jhipster 7.0.1. Issue appears when I try to upgrade the existing application from 6.7.0 to 7.0.1 or when I try to import new entity using import-jdl command.
ERROR! Error at entity Ticket: relationship name is not synchronized

**Comment by azeerman** [comment] 2021-08-15 13:09
same error in 7.1.0

**Comment by gmarziou** [comment] 2021-08-15 15:59
@azeerman why don't you open a new issue with full details?

**Comment by karlivory** [comment] 2022-04-18 11:20
I don't see why this issue is closed. The problem still remains, jhipster 7.0.0+ does not work with unidirectional while 6.10.5 works perfectly fine. This prevents me from upgrading my jhipster version since I don't want to add completely unnecessary back-references to my entities.

**Comment by miy4mori** [comment] 2022-05-03 23:41
same error in 7.8.1 fresh generation

**Comment by JeSuisAlrick** [comment] 2023-11-28 23:02
Please note that the back reference name is important for this to work. For example:
```
entity RecurringPayment {
    amount BigDecimal
}
entity Account {
    accountNumber String
}

relationship OneToOne {
	RecurringPayment{sourceAccount} to Account{recurringPaymentSource}
	RecurringPayment{destinationAccount} to Account{recurringPaymentBeneficiary}
}
```

The back references `recurringPaymentSource` and `recurringPaymentBeneficiary` on Account are what you should take note of.
