### ISSUE TITLE
Error using "jhipster import-jdl <jdl-samples-master/online-shop.jh>"

### ISSUE THREAD

**Issue by alexsintoni** [jhipster/generator-jhipster#6129] opened 2017-07-16 14:28 UTC
##### **Overview of the issue**

I just created a Monolithic application with jhipster command line.
After I run the "jhipster import-jdl ../../dl-samples-master/online-shop.jh" in order to create some entities as example and I got this error:
```
ERROR in ./src/main/webapp/app/entities/category/category-dialog.component.ts
Module parse failed: /home/alex/Development/workspace/jhipster/jhi-primeng/node_modules/angular2-template-loader/index.js!/home/alex/Development/workspace/jhipster/jhi-primeng/node_modules/awesome-typescript-loader/dist/entry.js!/home/alex/Development/workspace/jhipster/jhi-primeng/node_modules/tslint-loader/index.js!/home/alex/Development/workspace/jhipster/jhi-primeng/src/main/webapp/app/entities/category/category-dialog.component.ts Argument name clash (20:81)
You may need an appropriate loader to handle this file type.
| var product_1 = require("../product");
| var CategoryDialogComponent = (function () {
|     function CategoryDialogComponent(activeModal, alertService, categoryService, categoryService, productService, eventManager) {
|         this.activeModal = activeModal;
|         this.alertService = alertService;
 @ ./src/main/webapp/app/entities/category/index.ts 9:9-47
 @ ./src/main/webapp/app/entities/category/category.module.ts
 @ ./src/main/webapp/app/entities/entity.module.ts
 @ ./src/main/webapp/app/app.module.ts
 @ ./src/main/webapp/app/app.main.ts

ERROR in [at-loader] ./src/main/webapp/app/entities/category/category-dialog.component.ts:9:10 
    TS2300: Duplicate identifier 'Category'.

ERROR in [at-loader] ./src/main/webapp/app/entities/category/category-dialog.component.ts:11:10 
    TS2300: Duplicate identifier 'CategoryService'.

ERROR in [at-loader] ./src/main/webapp/app/entities/category/category-dialog.component.ts:12:10 
    TS2300: Duplicate identifier 'Category'.

ERROR in [at-loader] ./src/main/webapp/app/entities/category/category-dialog.component.ts:12:20 
    TS2300: Duplicate identifier 'CategoryService'.

ERROR in [at-loader] ./src/main/webapp/app/entities/category/category-dialog.component.ts:35:17 
    TS2300: Duplicate identifier 'categoryService'.

ERROR in [at-loader] ./src/main/webapp/app/entities/category/category-dialog.component.ts:36:17 
    TS2300: Duplicate identifier 'categoryService'.
Child html-webpack-plugin for "index.html":
    [./node_modules/html-webpack-plugin/lib/loader.js!./src/main/webapp/index.html] ./node_modules/html-webpack-plugin/lib/loader.js!./src/main/webapp/index.html 1.23 kB {0} [built]
            factory:257ms building:2284ms = 2541ms
error Command failed with exit code 2.
error Command failed with exit code 1.
error Command failed with exit code 1.
```
It did not happen with version 4.5.6

##### **Motivation for or Use Case**

I am executing different tests with JHipster to get knowledge about it with different configurations

##### **Reproduce the error**

Just follow previous explanation

##### **Related issues**

Maybe but this version is pretty new so I doubt it.

##### **JHipster configuration**

jhipster info
Executing jhipster:info
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
jhiprimeng@0.0.0 /home/alex/Development/workspace/jhipster/jhi-primeng
└── generator-jhipster@4.6.1 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.jhiprimeng",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "4.6.1",
    "baseName": "jhiprimeng",
    "packageName": "com.mycompany.jhiprimeng",
    "packageFolder": "com/mycompany/jhiprimeng",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": true,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "fr",
      "de",
      "it"
    ]
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Category (category) {
  linky String required,
  description String required,
  sortOrder Integer,
  dateAdded LocalDate,
  dateModified LocalDate,
  status CategoryStatus
}
entity Product (product) {
  title String required,
  keywords String,
  description String,
  rating Integer,
  dateAdded LocalDate,
  dateModified LocalDate
}
entity Customer (customer) {
  firstName String,
  lastName String,
  email String,
  telephone String
}
entity Address (address) {
  address1 String,
  address2 String,
  city String,
  postcode String required maxlength(10),
  country String required maxlength(2)
}
entity Wishlist (wishlist) {
  title String required,
  restricted Boolean
}

enum CategoryStatus {
  AVAILABLE,
  RESTRICTED,
  DISABLED
}

relationship OneToMany {
  Wishlist{product} to Product{wishlist},
  Customer{address} to Address{customer},
  Customer{whislist} to Wishlist{customer}
}
relationship ManyToOne {
  Category{parent} to Category
}
relationship ManyToMany {
  Category{product(title)} to Product{category}
}

paginate Category with pagination
service Category with serviceClass
paginate Product with infinite-scroll
paginate Customer with pagination
paginate Address with pager

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

git version 2.7.4

node: v8.0.0

npm: 5.0.4

bower: 1.8.0

gulp:
[16:19:54] CLI version 1.3.0

yeoman: 2.0.0

yarn: 0.27.5

Execution complete

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

I have run "jhipster import-jdl ../jdl-samples-master/" with the public examples from Jhipster

**Comment by deepu105** [comment] 2017-07-16 14:47
duplicate of #6063

**Closed by deepu105** 2017-07-16 14:47 UTC

**Comment by alexsintoni** [comment] 2017-07-16 15:19
Wow, this is a very fast feedback. One of the best support ever ;)
I have also found an issue with the registration using Facebook and I have found a working solution.
Shall I report it or you have it already?

**Comment by jdubois** [comment] 2017-07-16 15:59
thanks @alexsintoni -> yes if you have another issue, don't hesitate to open a ticket, and even better do a PR if you have the solution!

**Comment by deepu105** [comment] 2017-07-16 16:33
And an even faster fix is coming in :smiling_imp:
