### ISSUE TITLE
Unable to bring up the application using gradle and gulp combination

### ISSUE THREAD

**Issue by mreddimasi** [jhipster/generator-jhipster#3028] opened 2016-02-29 08:04 UTC
##### **Overview of the issue**

Unable to bring up the application using gradle and gulp combination

##### **Motivation for or Use Case** 

Unable to bring up the application using gradle and gulp combination, works fine with gradle and grunt combination, but the index.html has only the section of footer

##### **JHipster Version(s)** 

2.27.1

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 

{
  "generator-jhipster": {
    "baseName": "Unpickle",
    "packageName": "com.unpickle",
    "packageFolder": "com/unpickle",
    "authenticationType": "session",
    "hibernateCache": "no",
    "clusteredHttpSession": "no",
    "websocket": "spring-websocket",
    "databaseType": "mongodb",
    "devDatabaseType": "mongodb",
    "prodDatabaseType": "mongodb",
    "searchEngine": "no",
    "useSass": false,
    "buildTool": "gradle",
    "frontendBuilder": "gulp",
    "enableTranslation": true,
    "enableSocialSignIn": false,
    "rememberMeKey": "a28dda7866a2e54026cdf4aa6a6798b451f65ec0",
    "testFrameworks": [
      "protractor"
    ]
  }
}

##### **Browsers and Operating System** 

Windows all browsers

##### **Reproduce the error** 

1. yo jhipster
2. select gradle and gulp combination
3. Once installation is done, run
gradlew bootRun
λ gradlew bootRun
Starting the Unit and Integration test
:bower
:nodeSetup SKIPPED
:npmSetup SKIPPED
:npmInstall
module.js:341
    throw err;
    ^

Error: Cannot find module 'E:\Projects\Dev\Unpickle\node_modules\npm\bin\npm-cli.js'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:141:18)
    at node.js:933:3
module.js:341
    throw err;
    ^

Error: Cannot find module 'E:\Projects\Dev\Unpickle\node_modules\npm\bin\npm-cli.js'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:141:18)
    at node.js:933:3
:npmInstall FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':npmInstall'.
> Process 'command 'cmd'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 10.134 secs

##### **Related issues** 

https://github.com/jhipster/generator-jhipster/issues/1059

**Comment by mreddimasi** [comment] 2016-02-29 08:07
node - v5.7.0
npm - 3.7.5
npm view  gulp version - 3.9.1

**Comment by gmarziou** [comment] 2016-02-29 10:23
Have you tried running an LTS version of node? It's more stable.

**Comment by mreddimasi** [comment] 2016-02-29 10:54
@gmarziou No I've not tried the same.
just an fyi, I tried building with a combination of maven + gulp and gradle + grunt both work fine.

Will try with LTS version as suggested

**Comment by mreddimasi** [comment] 2016-02-29 11:18
@gmarziou Tried with the LTS version, the result is the same.

**Comment by atomfrede** [comment] 2016-02-29 11:37
Have zou tried to run npm install manually? Looks like node_modules folder is missing

**Comment by mreddimasi** [comment] 2016-02-29 11:55
@atomfrede no, not tried running the npm install manually, trying that right now.

But node_modules folder is not there since all the modules have been installed with -g option.

**Comment by gmarziou** [comment] 2016-02-29 12:31
Not sure I understand, modules are not supposed to be installed globally (with -g option). You're supposed to install globally only comand line tools like gulp, bower, ...

**Comment by mreddimasi** [comment] 2016-02-29 12:37
@gmarziou gulp, bower, yo, grunt have been installed with -g option before executing yo jhipster.
Once yo jhipster is complete I don't see a node_modules directory.

Are we supposed to see the node_modules in the directory?

**Comment by gmarziou** [comment] 2016-02-29 12:53
Yes, when you generated the app, jhipster did run `npm install` for you to fill the `node_modules` directory.
Sometimes it could fail and you have to re-run it manually, same thing for `bower install`.

This can also happen, when you share your project with someone else by git as node_modules is ignored by .gitignore.

Please read our documentation.

**Comment by jdubois** [comment] 2016-02-29 14:20
I just did it with the latest v2 version:

- Worked without any issue (and I tried it before the release, so I was pretty confident)
- I do have a "node_modules" folder -> I don't understand what you did with the `-g` option, so I guess that's what causing the issue

You can also try doing it on the "devbox" to see if you can reproduce.

I'm closing this as I can't reproduce the ticket.

**Closed by jdubois** 2016-02-29 14:20 UTC
