### ISSUE TITLE
Field validate rules into entity.json

### ISSUE THREAD

**Issue by houcine8** [jhipster/generator-jhipster#1264] opened 2015-03-16 11:32 UTC
What should I put in field Validation Rules if I want to add a regular expression for email validation.
```
"fieldValidate":true,
"fieldValidateRules":[?]
```
Thank you.

**Comment by jdubois** [comment] 2015-03-16 12:35
You have to input a regular expression that validates the email. On the Java side, I would advise that you remove the @Pattern and put an @Email annotation instead.

I'm closing this as this is not a bug.

**Closed by jdubois** 2015-03-16 12:35 UTC

**Comment by jshingler** [comment] 2015-04-10 18:32
Hi,  I understand why you are saying to use @Email instead of @Pattern.  The core issue is that Regular Expression escaping is not working correctly.  email is a good example.  

From:https://jhipster.github.io/creating_an_entity.html
"Regular Expression patterns don't work the same in JavaScript and in Java, so if you configure one, you might need to tweak one of the generated patterns"  

It is because:

"fieldValidateRulesPattern": "^\\\\.com$"  works properly for java, it doesn't for javascript
and if you make it work for javascript, ... it fails in java

So I won't make the argument that it is a bug, ... but as a users of jhipster, I believe having this work better would be valuable.
