### ISSUE TITLE
pureFilter:filter not working in logs.components.html

### ISSUE THREAD

**Issue by vwiencek** [jhipster/generator-jhipster#10348] opened 2019-09-04 09:39 UTC
##### **Overview of the issue**

The `logs.components.html` page doest not properly display the logs list. Logs are correctly injected within the component, but the html page seems to have difficulties displaying loggers because `pureFilter:filter:'name'` does not work properly.

I don't really see where it needs to be injected / imported to be used within the view.

##### **Browsers and Operating System**

-   [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by vishal423** [comment] 2019-09-04 09:49
possible duplicate of #9982

**Comment by vwiencek** [comment] 2019-09-04 12:06
it works with ng-jhipster 11.0 but not 11.1 ....

**Comment by kaidohallik** [comment] 2019-09-04 12:11
To use ng-jhipster 0.11.1 we must merge #10069, will continue conversation there.

**Comment by vishal423** [comment] 2019-09-04 13:25
I am closing this as current master code is on `v0.11` that contains the fix.

https://github.com/jhipster/generator-jhipster/blob/3213aa38ec51216ebf345e8c18cfd34b24923241/generators/client/templates/angular/package.json.ejs#L49

**Closed by vishal423** 2019-09-04 13:25 UTC
