### ISSUE TITLE
gateway fails to start with UAA

### ISSUE THREAD

**Issue by xetys** [jhipster/generator-jhipster#4882] opened 2017-01-16 18:27 UTC
##### **Overview of the issue**

This is a issue for my self. Our current gateway fails to start, when configured using UAA.

Failing cause is:

```
Failed to instantiate [javax.servlet.Filter]: Factory method 'springSecurityFilterChain' threw exception; nested exception is java.lang.NoSuchMethodError: org.springframework.security.core.userdetails.User.withUsername(Ljava/lang/String;)Lorg/springframework/security/core/userdetails/User$UserBuilder;
```

##### **Reproduce the error**

just generate an uaa gateway and try to start

##### **Suggest a Fix**

I don't know exactly, which new component requires the userDetailsBean, and if it is needed on gateway when auth is uaa, and user management is no longer happening there.

Depending of what is the case, either we need a UserDetailsService bean using load balanced RestTemplate / FeignClient, or just remove that component which requires that bean, if it is not necessary.

Hope, maybe someone has an idea about this. I will fix it as soon I find the time to find the cause 

##### **JHipster Version(s)**

current master

**Comment by pascalgrimaud** [comment] 2017-01-16 18:39
@xetys : it's strange because Travis build for uaa is green... did you have a look to the logs of our Travis build?

**Comment by jdubois** [comment] 2017-01-23 14:48
@xetys do you confirm the issue? We will soon be in code freeze mode, for JHipster 4 -> will you be able to fix this in the next couple of days? Otherwise this will go for the next release

**Comment by xetys** [comment] 2017-01-23 16:37
I will take a look ASAP

**Comment by ruddell** [comment] 2017-01-23 18:31
I couldn't reproduce this locally using NG1 (gateway NG2 webpack fails, seems unrelated)

**Comment by pascalgrimaud** [comment] 2017-01-23 22:13
@xetys : same, I couldn't reproduce... maybe a problem with your spring security lib? Pierre got a problem when downloading spring security here https://github.com/jhipster/generator-jhipster/issues/4813

**Comment by jdubois** [comment] 2017-01-23 23:31
Closing as your PR is merged

**Comment by pascalgrimaud** [comment] 2017-01-23 23:33
@jdubois : what is the PR you're talking about ? I don't see any PR related to this ticket

**Comment by pascalgrimaud** [comment] 2017-01-23 23:42
oh probably https://github.com/jhipster/generator-jhipster/pull/4937 but it's not related to UAA. It's related to ng2+gateway which failed

**Comment by jdubois** [comment] 2017-01-23 23:45
Oh sorry it's late :-)
Re-opening....

**Comment by jdubois** [comment] 2017-01-26 14:15
Closing this as the issue is now #4975

**Closed by jdubois** 2017-01-26 14:15 UTC
