### ISSUE TITLE
angular unittest  user.service.spec.ts expect not work

### ISSUE THREAD

**Issue by ufwtlsb** [jhipster/generator-jhipster#9503] opened 2019-03-29 09:39 UTC
##### **Overview of the issue**
 user.service.spec.ts change 
            it('should return User', () => {
                service.find('user').subscribe(received => {
                    expect(received.body.login).toEqual('user');
                });

                const req = httpMock.expectOne({ method: 'GET' });
                req.flush(new User(1, 'user'));
            });
expect(received.body.login).toEqual('user'); change expect(received.body.login).toEqual('user1');
npm test is pass

##### **Suggest a Fix**

   maybe add async()
##### **JHipster Version(s)**
5.8.2 

##### **Browsers and Operating System**

-   [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment] 2019-03-29 09:43
I'm sorry but we need your configuration here, with the default setup I'm sure that this passes, as we have unit tests running all the time for those

**Comment by vishal423** [comment] 2019-03-29 10:26
it's duplicate of #9463

**Comment by jdubois** [comment] 2019-03-29 10:28
Thanks @vishal423 - closing as duplicate

**Closed by jdubois** 2019-03-29 10:28 UTC
