### ISSUE TITLE
add a new field to jhi_user jhipster

### ISSUE THREAD

**Issue by Hafyane** [jhipster/generator-jhipster#1607] opened 2015-06-14 14:25 UTC
gave me the different steps to add a new field to table(jhi_user)

**Comment by jdubois** [comment] 2015-06-14 15:47
This is not a bug or a feature request, so I'm closing this. Did you read our [help page](http://jhipster.github.io/help.html)?
If you want to learn about Java, Spring and Hibernate, you can start with [this spring.io guide](http://spring.io/guides/gs/accessing-data-jpa/)

**Closed by jdubois** 2015-06-14 15:47 UTC
