### ISSUE TITLE
Issue with options "server"

### ISSUE THREAD

**Issue by sdharmadhikari** [jhipster/generator-jhipster#7593] opened 2018-05-09 23:32 UTC
I am trying create separate UI and server applications for deployment purpose. When use command "jhipster server", it skips main question whether you want to create monolithic, gateway and microservice. But if I try to use "jhipster --skip-client" command, it correctly asks me those questions. 

> $ jhipster server

Using JHipster version installed globally
Executing jhipster:server
Options: 
? What is the base name of your application? vPortalServer
? What is your default Java package name? (com.verient.vendorportal)

> jhipster --skip-client 
Using JHipster version installed globally
Running default command
Executing jhipster:app
Options: skipClient: true, skip-client: true
<Removed Image>
                            http://www.jhipster.tech

Welcome to the JHipster Generator v4.14.1

  JHipster update available: 4.14.3 (current: 4.14.1)

  Run yarn global upgrade generator-jhipster to update.

 ______________________________________________________________________________

? Which *type* of application would you like to create? Microservice gateway (correctly asks the question here)

**Comment by deepu105** [comment] 2018-05-10 06:17
Its intentional. The correct way to use is by using the skip client flag and that's what we have documented. If you use the server sub gen directly then you need to pass relevant flags. Run 'jhipster server --help'  to see all flags.
Closing this as its not a bug

**Closed by deepu105** 2018-05-10 06:17 UTC
