### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by loydjayme25** [jhipster/generator-jhipster#7738] opened 2018-06-06 12:04 UTC
Good Day !
i love to work with your project, can i submit my logo design for it ?

**Comment by PierreBesson** [comment] 2018-06-06 12:35
That would be awesome !

You can post your logo proposals as PRs to : https://github.com/jhipster/jhipster.github.io/tree/master/images/logo
However it will mean that you agree that your logo be put under the Apache 2 license and distributed as part of the project, the same way than a code contribution would. And yes Apache 2 allows commercial use so make sure that you are OK with that.

**Comment by loydjayme25** [comment] 2018-06-06 12:37
i am fine with that sir @PierreBesson  , i will send the logo as soon as i can finish it.

**Comment by loydjayme25** [comment] 2018-06-06 12:42
i can only make the start up icon that will be place on every devices , and also the Read Me Banner for github.

**Comment by deepu105** [comment] 2018-06-06 12:46
Also please note that the logo is subject to the team's approval :)

Thanks & Regards,
Deepu

**Comment by jdubois** [comment] 2018-06-06 12:58
Yes, we have a well-known logo, and I'm happy with it, so I wouldn't want to change this easily.

We need more help on other related things like wallpapers, or on having some cool t-shirts for example.

**Comment by pascalgrimaud** [comment] 2018-06-06 18:14
I think posting here before submitting PR would be better
So we can discuss about it

**Comment by PierreBesson** [comment] 2018-06-06 18:22
Let's see what @loydjayme25 has to propose, it can always be nice to have even if doesn't end up replacing the official logo.

**Comment by loydjayme25** [comment] 2018-06-07 11:39
hello everyone ..

young and cool , any suggestions ?
![jhipster](https://user-images.githubusercontent.com/37318022/41097446-825b7b68-6a8a-11e8-873e-fd5df6a231b6.png)

**Comment by agoncal** [comment] 2018-06-07 12:55
Where are the tatoos ? Where is the earring ? Where's the hype ?

;o)

**Comment by PierreBesson** [comment] 2018-06-07 12:59
And the bow tie ! :smile:

**Comment by loydjayme25** [comment] 2018-06-07 13:19
i can add if you wanted me to do so :D

**Comment by loydjayme25** [comment] 2018-06-07 13:19
but how did you find my design ? is it okay ?

**Comment by deepu105** [comment] 2018-06-07 13:48
@loydjayme25 First of all good work, its nice.
Now just make sure to match it closer to the[ original Hipster guy](https://www.jhipster.tech/images/logo/logo-jhipster.svg), as we wouldn't want a completely new logo as original logo is quite famous already so try to improve the original one. Or add stuff like the original logo drinking coffee with more swag, or original log wind surfing, or original logo <add your action> sort of stuff

We could definitely use yours for swag, stickers etc.

**Comment by jdubois** [comment] 2018-06-07 13:53
Yes the logo is awesome, then we already have a logo, and it's very complex to change it (it's also part of the "brand"). It could be an alternate logo, I don't really know... I'm sorry but I have tons of work with JHipster Conf and JHipster 5 (and my "normal" job), so I don't really have time for the moment. For t-shirts or wallpapers that could be great, indeed, like an alternate, "cooler" logo.

**Comment by loydjayme25** [comment] 2018-06-07 14:00
![jhipster](https://user-images.githubusercontent.com/37318022/41104539-2fceec68-6a9e-11e8-994b-05d7ccde6e07.png)

**Comment by loydjayme25** [comment] 2018-06-07 14:03
![jhipster](https://user-images.githubusercontent.com/37318022/41104736-a56d8dbc-6a9e-11e8-8320-979af1828071.png)

**Comment by loydjayme25** [comment] 2018-06-08 06:30
you can use my design for the future updates/project. if you wanted me to PR, i am willing to do it. Many thanks for your response !

**Comment by cbornet** [comment] 2018-06-08 07:40
What would be nice would be to have logo/avatar variants like the github octopus

**Comment by jdubois** [comment] 2018-06-08 08:02
Oh yes +1 @cbornet 
@loydjayme25 I think everybody loves your logo, it's really cool, but it's really complex for us to change the "official" one

**Comment by loydjayme25** [comment] 2018-06-08 08:32
i understand that @jdubois  , i'll make a PR if you need my logo. I respect your decision on not changing the offical logo.

**Comment by jdubois** [comment] 2018-06-08 08:33
Yes but your logo could be used on shirts, wallpapers, etc... Like the Octocat, in fact.
It's really cool, really
Give me some time, the JHipster Conf is in 2 weeks, I'll do this afterwards

**Comment by loydjayme25** [comment] 2018-06-08 08:37
Thank you sir, so overwhelming. just beep me, and i can send you my design.
here's my email : @loydjayme1996@gmail.com

**Comment by jdubois** [comment] 2018-06-08 08:41
Oh thanks, but you can directly put your artwork at https://github.com/jhipster/jhipster.github.io/tree/master/images/artwork with a PR, that's where we store our files so we don't lose them

**Comment by loydjayme25** [comment] 2018-06-08 11:58
do you have any required size needed ? at least 3 sizes.

**Comment by loydjayme25** [comment] 2018-06-08 12:36
maybe 1024 px or higher

**Comment by jdubois** [comment] 2018-06-08 13:05
SVG is best

**Comment by loydjayme25** [comment] 2018-06-08 13:12
I will include svg :)

**Comment by mraible** [comment] 2018-06-08 13:54
I can get some stickers made up for JHipster Conf. Should they say anything on them?

**Comment by atomfrede** [comment] 2018-06-08 14:00
I can also do some stickers and I wanted to get some new tshirts for me and my son, maybe I can use the logo already :)

**Comment by sendilkumarn** [comment] 2018-06-08 23:15
@loydjayme25 great work. absolutely love it ❤️

**Comment by erikkemperman** [comment] 2018-06-09 08:20
That’s awesome!

**Comment by loydjayme25** [comment] 2018-06-09 13:34
@deepu105  could you please give an example about how i name the size and the svg file. pls ? thanks !

**Comment by deepu105** [comment] 2018-06-19 09:06
closing as the PR is merged

**Closed by deepu105** 2018-06-19 09:06 UTC

**Comment by agoncal** [comment] 2018-06-21 07:13
@loydjayme25 and what about creating a diverse group of several hipsters ? The JHipster logo will remain, but with your new logo we could create a kid of mascot. We could have a younger Hipster, an older one, a tatoed female Hipster, an asian still of Hipster....

We could then have several stickers and each one of us would recognize him/herself in such or such caracter.

WDYT ?

**Comment by agoncal** [comment] 2018-06-21 07:31
@atomfrede exactly ;o)

**Comment by sendilkumarn** [comment] 2018-06-21 11:03
@agoncal love it :

**Comment by deepu105** [comment] 2018-06-21 20:21
Yes please

**Comment by jdubois** [comment] 2018-06-22 09:17
Yes let's do this - and maybe even change the "official" logo, as the majority of people at JHipster Conf yesterday seemed to like this one more.

Here's my plan:

- Create a specific repo for the logo
- Have the logo fully OSS, so people can modify it without any issue (the current logo was given away, but legally I'm not 100% sure we can modify it without the agreement of the original author)
- Start with something like 10-20 "diverse" logos, a bit like the GitHub Octodex
- I know Sharat Chander (can't find his GitHub handle, but I will notify him on Twitter) was ready to sponsorize this -> we could do something specific on https://opencollective.com/generator-jhipster so people who create those logos have some financial rewards, so we have even more logos
- We would need some kind of "board" who can validate that those logos are OK to be used (Are they inclusive enough? Will they hurt some people for some reason? Those questions are not always easy). I'll ask a few people I know who would be good fit for that.

If that's fine with you (or not!), please 👍 or 👎 on this comment.

**Comment by agoncal** [comment] 2018-06-22 10:12
"Will they hurt some people for some reason?" Careful with that. There are [3.2 billion people connected to the internet](https://en.wikipedia.org/wiki/Global_Internet_usage) and it's difficult to find something that will not hurt at least one of these 3.2 billion people (except the sky is blue I suppose). So I don't mind being part of this board if we know that, no matter what we do, how careful we are, someone, somewhere on this planet, will be hurt.

**Comment by jdubois** [comment] 2018-07-07 08:38
2 weeks later, let me do a quick summary of what happened (or not!):

- We had 10 👍 and 0 👎 so I think everybody agrees here
- I had no news from Sharat Chander, I'm going to try to reach him again through Twitter
- @loydjayme25 as you are the main author here, are you OK with all of this?
- I'm going to reach for a few people to do our "board"

Then concerning all the discussions about the logo not being inclusive enough, I just hope people will be happy that we take a specific effort here. We are a bunch of people doing this for free (I'm writing this on a Saturday morning, and I have 3 kids, so obviously a lot of other stuff to do), so I'm not going to do anything more than trying to organize this to have a new logo. And if that fails, then we'll keep the old logo.

And if that is not enough for people, why don't they go after some other OSS projects with far more people and money than us (like https://jenkins.io/ or https://www.oracle.com/java/duke.html ), or even famous brands with tons of money like https://en.wikipedia.org/wiki/Pringles or https://en.wikipedia.org/wiki/KFC .

Oh, and I don't think that https://en.wikipedia.org/wiki/Herm%C3%A8s displaying a man has ever been seen "not inclusive enough" and has refrained women from buying their stuff (I've just visited their Paris shop and I was the only man). If women do not participate in JHipster as much as men, and which is a real problem, I do not think that comes from the logo. So I'd rather spend time trying to help women contribute to JHipster (like I already did a few times) than spend time on the logo.

**Comment by jdubois** [comment] 2018-08-13 10:10
So one more month has passed:

- The awesome @aneveu agreed to be on our board to validate the different logos. Thanks a lot Audrey!
- I still have no news from @loydjayme25 (and I also tried by email)

So at the moment we are stuck: as long as our logo isn't with the correct Creative Commons license, we have the same issue as the older logo from @ggaulard , we cannot modify it. So there's no way we can do different logos.

I think the best solution at the moment would be that I buy a logo, using our OpenCollective money. In that way, I would own the logo, and then I would be able to give it the correct Creative Commons license, or even change it to another better license in the future.

**Comment by ggaulard** [comment] 2018-08-13 10:25
This new version is way more modern that what I did. Great job 👍 
I didn't know about the license issues, for me it was all yours :) 
I always wanted to make a declination of the logo to illustrate the microservice features.
My idea was to do something with the rowing sport.

**Comment by PierreBesson** [comment] 2018-08-13 14:27
For me there is no licence issue. Everything in our project is licenced under Apache2 and that includes documentation, images and logos. So people are free to modify them as long as they give proper attribution. And we can totally change the licence to créative commons if you prefer and if @ggaulard and @loydjames25 approve.

**Comment by jdubois** [comment] 2018-08-13 15:33
@ggaulard what I can tell you for sure is that children love your logo, and that's a big part of the project's success because our stickers get used everywhere :-)
As this is a "work of art", for me we have the right to use the logo, but not modify it. To be able to modify it, we need a specific Creative Commons license, and the Apache 2 license is not enough here.
@ggaulard would you be OK to publish your logo as https://creativecommons.org/licenses/by/4.0/ ? We would publish it on https://github.com/jhipster/jhipster-artwork and put there the specific files needed by the license: name of the creator (you), copyright notice (the ones from JHipster), license notice, etc.

**Comment by ggaulard** [comment] 2018-08-14 09:00
@jdubois I'm completely ok to publish it on creative commons. I'm very happy that the logo is appreciated so much. Thanks for the beer :) I keep it preciously

**Comment by jdubois** [comment] 2018-08-14 09:03
@ggaulard oh I was wondering if you got the JHipster beer :-)
If you are available for eating today, we can meet together (it's the JHipster day at Ippon) near the Argentine metro station - I'll invite you using our https://opencollective.com/generator-jhipster money, and we can set up the repository together.

**Comment by jdubois** [comment] 2018-09-10 08:41
Hi everyone, the "diversity issue" is coming again, and we still have this logo. Now there is someone on Twitter (sorry I can't mention him, I don't have his GitHub handle), who proposed just to have no person at all. Which would solve all the problems, so I'm all for it.

I have just one very personal thing here: I see many kids, including my own kids, who love the current logo. I've seen it in people's house, even on a young kid's scooter. So I would still like to have something "cute", so that kids can continue to use our stickers everywhere and be happy about it.

That's why I would like to have a baby animal, of course with an indefinite sex (no mustache or anything). Like the Linux penguin. And I would like this to be a turtle:

- My younger daughter, who is 1 year old, loves the current logo and loves turtles. I'm sure she'll be happy to see turtles everywhere.
- I do not know any famous project with a turtle as a logo.
- It's really hard to guess a turtle's sex.
- I guess you all know Jean de la Fontaine's poem about the turtle and the rabbit. Our project is like that, we do a lot of continuous effort, and we arrive at the end faster than our competitors.
- The "Turtle" is in fact the first thing I ever programmed in my whole life, when I was probably 7 or 8 years old. See https://en.wikipedia.org/wiki/Logo_(programming_language) for some background.

What do you all think about this? And as it's really hard to find an artist who would do this for us, let's spend some OpenCollective money to pay for it, and have the full rights on the logo. So no more copyright issue, also.

Please vote 👍 or 👎 or comment if you think something's wrong here.

**Comment by PierreBesson** [comment] 2018-09-10 08:58
I like the symbol of the turtle (slow pace but winning in the end) and the relation to programming. I'm fine with the change as long as the turtle character looks hipster enough 😉.
And +1 for appealing to kids, maybe children can be involved in the logo selection.

**Comment by mraible** [comment] 2018-09-10 09:15
-1 on the turtle. Turtles are slow, not hip!

**Comment by deepu105** [comment] 2018-09-10 09:37
@jdubois while diversity is really important (not coz some arrogant guy said so), I don't think its necessary to change the logo altogether. A lot of projects do have a gendered logo(Jenkins, Yeoman and so on)
IMO its sufficient if we add some variations as well(If no one is doing it I can try to do it). Changing the logo altogether also will affect the brand

**Comment by cbornet** [comment] 2018-09-10 13:30
> -1 on the turtle. Turtles are slow, not hip!

Even Ninja ones ?

**Comment by atomfrede** [comment] 2018-09-10 14:39
So as first starting point lets move everything we have regarding artworks to the repository to make it more visible (I can do that). Afterwards lets try to find volunteers creating more logos like github as with the octodex. 

Regarding the turtle (animal), I like the idea, but also seen the jhipster in the wild last weekend in a coffee shop in paderborn (sadly no time to talk to the owner), but it was quite cool to see it, so we quite a strong branding I guess. And there is already snap (https://github.com/intelsdi-x/snap) which as a turtle as a logo.

**Comment by deepu105** [comment] 2018-09-10 16:06
I'll ask the UX team at my office if they can help with creating artwork,
also I can try to brush up my Photoshop skills(might be a bit rusty since I
haven't done it for a while)
Either way, we need to make sure that we have full rights for any new logo
we create(including the source), unlike the existing ones.

Thanks & Regards,
Deepu

**Comment by deepu105** [comment] 2018-09-10 16:28
So one of my colleagues has agreed to help and I guess another one might be
interested as well :) will update you guys after discussion with them

Thanks & Regards,
Deepu

**Comment by mraible** [comment] 2018-09-10 16:30
I held a [logo contest for AppFuse](https://raibledesigns.com/rd/entry/appfuse_logo_contest) way back in 2004 that was quite successful. I think the key was offering a prize. Maybe we could do something similar and offer $100 to each of the logos we select?

**Comment by deepu105** [comment] 2018-09-10 17:06
Actually that's a good idea as well, the more the merrier

**Comment by aneveu** [comment] 2018-09-13 10:11
Logo was my first programming language too but both as a developer and a woman I prefer the JHipster logo to stay the same and being enriched with variations. 

It's a vital part of the brand and replacing it by a turtle would seems to me like getting round the problem of diversity instead of facing it, whereas the hipster theme offers a lot of possibility to decline the logo in very nice ways.

So 👍 for the contest with a prize for every logo we select.

**Comment by jdubois** [comment] 2018-09-13 10:27
Thanks so much @aneveu ! You are right, and also please note we have tons of money in the bank at the moment, so doing that contest is totally possible.

- There is a little thing to check on the logo license, as I was asked yesterday by a big company about the logo copyright. For me it is Apache, and that's what I put at https://commons.wikimedia.org/w/index.php?title=File:JHipster-logo.png but I hope it's correct. I will do that part, as I'm probably the best person for this in the team.
- Now for organizing the contest: I have currently a lot of personal stuff to do (all good news), and also we have like 45 opened bugs, so I'll be a bottleneck. Who would like to take the lead on this?

**Comment by deepu105** [comment] 2018-09-13 19:46
I'm planning some twitter discussion on topic of diversity to get some ideas for improvement. @aneveu let me know if you can organise the logo competition. I'll be happy to assist. We can discuss on the requirements as well

**Comment by aneveu** [comment] 2018-09-18 12:19
@deepu105 I won't have a lot of free time until the end of year so not sure I should take the lead on that, but I'll be happy to help if possible.

**Comment by agoncal** [comment] 2018-11-26 21:48
I know this issue is closed, but I would like to keep this Tweet for posterity:

https://twitter.com/doanduyhai/status/1067095315763904513

I hope one day we will understand that, being 7 billion different people on earth, we are all diverse (and unique) by design. Just embrace human kind and you will naturally embrace diversity.
