### ISSUE TITLE
Gitlab-CI found error with generated .gitlab-ci.yml  cache issue

### ISSUE THREAD

**Issue by Rathor6** [jhipster/generator-jhipster#22129] opened 2023-05-15 12:54 UTC
Overview of the issue
Pipeline just started, and then found FATAL: file does not exist. And don't have any clues about the file was referred.

FATAL: file does not exist                         
Failed to extract cache
Executing "step_script" stage of the job script

**Comment by atomfrede** [comment] 2023-05-15 12:58
Do you have a Link to your gitlab repo?

**Comment by Rathor6** [comment] 2023-05-15 13:02
cache:
    key: ${CI_RUNNER_S3_CACHE}
    untracked: true
    paths:
      - node_modules/
    policy: pull
  except:
    variables:
      - $CI_DISABLE_NPM_TESTS == "true"

npm:lint:
  extends: .npm-test
  allow_failure: false
  script:
    - npm run lint


above is the configuration in .yml file

**Comment by atomfrede** [comment] 2023-05-15 13:18
Where does the key variable come from? Nothing jhipster generates. The problem is that variable is not defined in your gitlab ci configuration.

**Comment by atomfrede** [comment] 2023-05-15 15:09
Can you try

```
cache:
    key: "$CI_RUNNER_S3_CACHE"
```

Side note, why are you creating a new variable instead of using `$CI_COMMIT_REF_SLUG` directly?

**Comment by atomfrede** [comment] 2023-05-31 20:43
As I don't think there is an issue in the generated I will close this. If you still think this is a jhipster bug please reopen it.

**Closed by atomfrede** 2023-05-31 20:43 UTC
Labels: area: invalid, area: question :question:
