### ISSUE TITLE
Error double notification

### ISSUE THREAD

**Issue by mtdx** [jhipster/generator-jhipster#5858] opened 2017-05-30 11:45 UTC
##### **Overview of the issue**

https://gyazo.com/61dd0762032221da5c277a73f8679f45
https://gyazo.com/1a2f3005425e1d6cabaacd8052aa877f

There are 2 small issues in those gifs, first when you're in a popup and some error happens, it also shows in the back (behind the popup), in this case the problem is the image being to big, but is not the first time I see it.

Also the "Field Image cannot be empty" isn't that descriptive for a max bytes restriction. 

##### **Reproduce the error**

Generate a simple entity, with an image field, with a max bytes size restriction and try to upload a bigger size image.

##### **JHipster Version(s)**

freshly generated app, JHipster 4.5.2

##### **JHipster configuration**

java version "1.8.0_131"
node: v6.10.3
npm: 4.2.0
yeoman: 1.8.5
yarn: 0.24.6

##### **Browsers and Operating System**

macOS, Chrome browser

**Comment by JulienMrgrd** [comment] 2017-05-30 12:53
I can take this issue

**Comment by deepu105** [comment] 2017-05-30 13:49
You are still not following the guidelines. We need your yo-rc.json and entity.json. can you plz run jhipster info on your app and post the results

**Comment by mtdx** [comment] 2017-05-30 20:52
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.xxx.xxx",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "4.5.2",
    "baseName": "xxx",
    "packageName": "com.xxx.xxx",
    "packageFolder": "com/xxx/xxx",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": true,
    "rememberMeKey": "506073c2654996412640f902f76e6c270b46a403",
    "clientFramework": "angular2",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "de"
    ]
  }
}


{
    "fluentMethods": true,
    "relationships": [],
    "fields": [
        {
            "fieldName": "name",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": 20
        },
        {
            "fieldName": "image",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "image",
            "fieldValidateRules": [
                "required",
                "maxbytes"
            ],
            "fieldValidateRulesMaxbytes": "80000"
        }
    ],
    "changelogDate": "20170530185220",
    "dto": "no",
    "service": "serviceClass",
    "entityTableName": "avatar",
    "pagination": "infinite-scroll"
}

you will see if you try to upload a 100kb image

**Comment by jdubois** [comment] 2017-05-31 13:19
Can you put a more descriptive title? I'm sorry but "small issue" doesn't mean anything

**Comment by mtdx** [comment] 2017-06-01 12:22
Probably related to the same issue, when you try to delete an entity in a required relationship with another entity and assigned you get a Server Error notification in the popup while behind the popup you get success notification "A ... is deleted with identifier..."

https://gyazo.com/8dac4ebb2b3a4c9db48331b34601b625

**Comment by pascalgrimaud** [comment] 2017-06-01 12:58
Recently, I work on the alert systemn here: https://github.com/jhipster/generator-jhipster/pull/5829 specially for creating / updating / deleting entities.
Not sure if it is related to my work, so don't hesitate to ping me if you need help @JulienMrgrd

**Comment by JulienMrgrd** [comment] 2017-06-01 14:11
After taking a look on this, there are some bugs to fix :

- [x] The double notification :arrow_up:  

- [ ] When you delete an image, the filename remains displayed. http://imgur.com/a/8sTvI

- [ ] Do not display the same error several times when clicking the save button (without having modified anything). http://imgur.com/a/cz0zH

- [ ] The dialog title : "Create or edit a XXXXX". Replace the article "a" by "an" if the entity name begins with a consonant. (exemple : "Create or edit an Avatar").

- [ ] The "Server Error notification" :arrow_up:

**Comment by deepu105** [comment] 2017-06-01 15:15
I wouldnt worry about the 4th item in the list as its difficult to do for
all languages. hence if you want you can do it for English but I would
leave it to end users to change as they see fit


Thanks & Regards,
Deepu

**Comment by JulienMrgrd** [comment] 2017-06-01 15:31
One more, not really related with this issue, but related to the @mtdx's entity :

- [ ] With an Image field, there is no "imageContentType" attribute in the `avatar.model`, but it's much used in html templates.

![capture d ecran de 2017-06-01 17-30-22](https://cloud.githubusercontent.com/assets/11616517/26687463/0af4a702-46f0-11e7-8c79-26dcf7f473be.png)
.

**Comment by JulienMrgrd** [comment] 2017-06-02 15:30
I'll do the PR after the @mtdx response (about the "Server Error" notification).

About this bug :

> - [ ] Do not display the same error several times when clicking the save button (without having modified anything). http://imgur.com/a/cz0zH

I'm actually trying to find a "pretty" solution to correct this.

**Comment by mtdx** [comment] 2017-06-02 15:39
@JulienMrgrd I'm sorry I don't have that app anymore, it was a test one, basically you create 2 entities, a one to one relationship  then add entries and assign 1 entity to another then you try to delete the assigned entity, you get a server error, in the debug log the actual error is a foreign key constraint error, so probably is a postgresql only error.

update or delete on table "some_table" violates foreign key constraint "fk_some_table_id" on table "some_table2"

Is not a big issue, the improvement would be here, a more descriptive error message.

Thanks

**Comment by JulienMrgrd** [comment] 2017-06-02 15:41
Ok thanks, I'll take a look.

**Comment by pascalgrimaud** [comment] 2017-06-15 06:26
@JulienMrgrd : is it fixed?

**Comment by thiagosoares-mobile** [comment] 2017-06-17 21:17
In the version 4.5.4 this issue persist. 
Apparently, the `ErrorHandlerInterceptor.responseIntercept` is called two times and the `this.eventManager.broadcast( {name: 'jhipsterApp.httpError', content: error})` add two error events. 

Unfortunately, I could not solve this problem. If someone already knows the solution, please share.

Grateful.

**Comment by deepu105** [comment] 2017-06-18 09:27
@thiagosoares-mobile I think this is a different issue. Could you please open a new issue with your configuration yo-rc file

**Comment by thiagosoares** [comment] 2017-06-19 12:07
OK @deepu105.

**Comment by nicoraynaud** [comment] 2017-06-20 04:56
The issue on multiple error being displayed looks a lot like [#5918](https://github.com/jhipster/generator-jhipster/issues/5918).

I was able to reproduce it as well. The interceptors are being called twice.

**Comment by deepu105** [comment] 2017-06-23 08:34
@JulienMrgrd are you still working on this or shall we close it?
@mtdx can you check if the issue is solved in current master?

**Comment by JulienMrgrd** [comment] 2017-06-23 09:29
Unfortunately I do not have the time currently to work on this.
But the main corrections have been made and merged.
I keep the minor issue of @mtdx in mind, if it's still relevant.

**Comment by deepu105** [comment] 2017-06-28 16:36
I'm closing this as there is no information for last few days

**Closed by deepu105** 2017-06-28 16:36 UTC
Labels: waiting for information
