### ISSUE TITLE
Microservice APIs returning empty response (master)

### ISSUE THREAD

**Issue by ruddell** [jhipster/generator-jhipster#9261] opened 2019-02-14 06:49 UTC
##### **Overview of the issue**
Microservice APIs return empty responses (generated with `master` branch).  I'm guessing it affects all Zuul routes since getting the account from the UAA is also broken.

##### **Motivation for or Use Case**
Generate a working microservice architecture

##### **Reproduce the error**
Generate a gateway
Generate a microservice
Generate an entity on the microservice (then on gateway)
Start registry, gateway, microservice
Attempt to access entity page

In browser developer tools, you can see on the network tab the response is null.  You can also see errors logged to the console, such as `core.js?09c9:15713 ERROR TypeError: Cannot read property 'length' of null at JhiParseLinks.parse (ng-jhipster.js?8ee9:1971)`

##### **Related issues**
Don't think so

##### **Suggest a Fix**
Unsure, maybe related to SB2.1?  Only affects master

##### **JHipster Version(s)**

Master, v5.8.2 works fine.

##### **JHipster configuration**
<details>
<summary>Gateway .yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "en",
      "microservicePath": "../msmaster"
    },
    "jhipsterVersion": "5.8.1",
    "applicationType": "gateway",
    "baseName": "gway",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "npm",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ],
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": []
  }
}
</pre>
</details>

<details>
<summary>Microservice .yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "5.8.1",
    "applicationType": "microservice",
    "baseName": "ms",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8081",
    "authenticationType": "jwt",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "enableTranslation": true,
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "clientPackageManager": "npm",
    "nativeLanguage": "en",
    "languages": [
      "en"
    ],
    "skipClient": true,
    "skipUserManagement": true,
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": []
  }
}
</pre>
</details>

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**
<details>
<summary>JDL entity definitions</summary>

<pre>
entity Foo {
  name String
}
dto Foo with mapstruct
paginate Foo with pagination
service Foo with serviceClass
microservice Foo with ms
filter Foo
clientRootFolder Foo with ms

</pre>
</details>

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment] 2019-02-14 07:02
@ruddell : maybe not related, but for your information, the last important changes in master are:
- Move client app to classpath:/public -> https://github.com/jhipster/generator-jhipster/pull/9154
- Change the packaging to jar and configure a war profile -> https://github.com/jhipster/generator-jhipster/pull/9034

As I didn't finish yet the Travis/Azure builds with multi applications, we didn't detect this problem.

**Comment by ruddell** [comment] 2019-02-14 07:19
I can do a `git bisect` tomorrow to find out what caused it if no one knows

**Comment by pascalgrimaud** [comment] 2019-02-14 07:20
If someone can check with dev / prod profile, because I saw different behavior yesterday when testing UAA (but it seems to affect all microservices):
- it's broken with dev profile
- it works for prod profile

**Comment by ruddell** [comment] 2019-02-14 19:57
`prod` works, but in `dev` the request never reaches the microservice.

I had trouble using `git bisect` since most commits on the SB 2.1 branch require a special build of `jhipster-dependencies`, but the merge of SB 2.1 is where the issue started c3803e580d442796ff1d00c0fe0924bb77ff1f56. Things work as expected as of the commit just before that ddea0311cd0669546c562c79788008a813b1295c

**Comment by pascalgrimaud** [comment] 2019-02-15 08:14
Finally got it !
The problem comes from this file: https://github.com/jhipster/generator-jhipster/blob/master/generators/server/templates/src/main/java/package/config/lazy/LazyInitBeanFactoryPostProcessor.java.ejs

If I disable it for `dev`, it works.
Ping @jdubois as you coded this file. Can you help us on this ticket ?

**Comment by jdubois** [comment] 2019-02-15 09:17
Thanks a lot @pascalgrimaud !!
This bean is "trick" to improve startup performance by lazy-loading all beans. I know this isn't really clean, that's why this is only in `dev` mode.

I'm guessing there's one bean that doesn't like this. It's possible with this technique to force a bean to be loaded, I'm going to look into that.

I know it's an unsafe way to start the application, then it really gives a big performance boost at startup, so it should be worth it.

**Comment by pascalgrimaud** [comment] 2019-02-15 09:41
I think there are some different beans for microservices, and indeed we need to analyze them to know the root cause.
I agree, let's try to keep this file as it will increase the performance at startup, so improve the dev experience!

**Comment by jdubois** [comment] 2019-02-15 10:21
I'm sorry I can't reproduce.... I did this with JWT as you have JWT in the `.yo-rc.json` in the original comment, but then you are speaking of UAA -> is it only with UAA?

By the way, now that Faker.js support is merged, you'll automatically have 10 values in dev mode, so it should definitely not be empty.

**Comment by pascalgrimaud** [comment] 2019-02-15 10:32
My gateway:

```
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "io.github.pascalgrimaud",
      "nativeLanguage": "en",
      "microservicePath": "../micro"
    },
    "jhipsterVersion": "5.8.1",
    "applicationType": "gateway",
    "baseName": "gateway",
    "packageName": "io.github.pascalgrimaud",
    "packageFolder": "io/github/pascalgrimaud",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "MzI5NTQ4NWY4Y2ZjMmM0Nzk4ODI0NTk0NWJkYTBlYWM3NWY3ZTUzYTQyMmU4YmIxMzUxYjgyMWIxZDc1OWM1ZWRkY2Y5M2VkZmI0NjU4NTA3MWQyYjNjYTdjZjU2YzNkNTg1YjQ1MDU3Mjg3N2UxNWIzZDljMzMzMTY0ZjdkYjQ=",
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "npm",
    "testFrameworks": ["protractor"],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": ["en"]
  }
}
```

My microservice:
```
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "io.github.pascalgrimaud",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "5.8.1",
    "applicationType": "microservice",
    "baseName": "micro",
    "packageName": "io.github.pascalgrimaud",
    "packageFolder": "io/github/pascalgrimaud",
    "serverPort": "8081",
    "authenticationType": "jwt",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": false,
    "websocket": false,
    "databaseType": "mongodb",
    "devDatabaseType": "mongodb",
    "prodDatabaseType": "mongodb",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "MmZlZjczNDM0MWQyOGI2MDY0ZDNkMDQ4MDc4ZWFiZWEwMWIwNzczOTdjYWEzMDg2YTk4NDIwNDdjNDEzYjdlOGFiZjNhYmRjY2Y0NjdmZTMzZDhmMGE4MDM5MGNiOTViZGY1MGU5NTY0MWI2OTdhMzVhMzlhOTQ3NzUyMWRkY2Q=",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": true,
    "clientPackageManager": "npm",
    "nativeLanguage": "en",
    "languages": [
      "en"
    ],
    "skipClient": true,
    "skipUserManagement": true
  }
}
```

Entities for my micro:

```
{
    "fluentMethods": true,
    "clientRootFolder": "micro",
    "relationships": [],
    "fields": [
        {
            "fieldName": "name",
            "fieldType": "String"
        }
    ],
    "dto": "no",
    "searchEngine": false,
    "service": "no",
    "entityTableName": "toto",
    "databaseType": "mongodb",
    "jpaMetamodelFiltering": false,
    "pagination": "no",
    "microserviceName": "micro"
}
```

**Comment by pascalgrimaud** [comment] 2019-02-15 10:38
I followed @ruddell's comment:

- Generate a gateway
- Generate a microservice
- (not needed -> Generate an entity on the microservice (then on gateway))
- Start registry, gateway, microservice
- Attempt to access to Swagger API of microservice

**Comment by ruddell** [comment] 2019-02-16 04:33
The bean name and definition that we need to exclude is: 

```
zuulFilterInitializer
Root bean: 
    class [null]; 
    scope=;
    abstract=false;
    lazyInit=false; 
    autowireMode=3; 
    dependencyCheck=0;
    autowireCandidate=true; 
    primary=false;
    factoryBeanName=org.springframework.cloud.netflix.zuul.ZuulServerAutoConfiguration$ZuulFilterConfiguration; 
    factoryMethodName=zuulFilterInitializer;
    initMethodName=null;
    destroyMethodName=(inferred); 
    defined in class path resource [org/springframework/cloud/netflix/zuul/ZuulServerAutoConfiguration$ZuulFilterConfiguration.class]
```

**Comment by PierreBesson** [comment] 2019-03-11 09:03
So it seems we just need to add `private Class<?>[] exclusionList = {ZuulFilterInitializer.class};` for gateway apps.
As solved here: https://github.com/mraible/jhipster-ms-oidc-improved/pull/1

**Closed** 2019-03-25 08:35 UTC
Labels: bug :bug:, microservice
