### ISSUE TITLE
jar v war suffix for spring-boot archive fail

### ISSUE THREAD

**Issue by tony-kerz** [jhipster/generator-jhipster#7379] opened 2018-03-29 23:20 UTC
##### **Overview of the issue**

followed [typical pattern](https://spring.io/guides/gs/spring-boot-docker/) to containerize spring-boot app which happens to change the archive suffix to `jar` (in the below example to `app.jar`):

```
FROM openjdk:8-jdk-alpine
VOLUME /tmp
ARG JAR_FILE
ADD ${JAR_FILE} app.jar
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]
```

jhipster seems to load perfectly as far as logging indicates, with something like:

```
:: JHipster 🤓  :: Running Spring Boot 1.5.10.RELEASE ::
:: http://www.jhipster.tech ::

2018-03-29 19:05:19.172  INFO 42985 --- [           main] com.aetna.nba.DemoApp                    : Starting DemoApp on MA716948A-HFD-OEM.local with PID 42985 (/Users/tony/git/pkgdiff/foo.war started by a716948 in /Users/tony/git/pkgdiff)
2018-03-29 19:05:19.175  INFO 42985 --- [           main] com.aetna.nba.DemoApp                    : The following profiles are active: prod
2018-03-29 19:05:21.876  INFO 42985 --- [           main] com.aetna.nba.config.WebConfigurer       : Web application configuration, using profiles: prod
2018-03-29 19:05:21.884  INFO 42985 --- [           main] com.aetna.nba.config.WebConfigurer       : Web application fully configured
2018-03-29 19:05:31.594  INFO 42985 --- [           main] com.aetna.nba.DemoApp                    : Started DemoApp in 13.136 seconds (JVM running for 13.63)
2018-03-29 19:05:31.596  INFO 42985 --- [           main] com.aetna.nba.DemoApp                    :
----------------------------------------------------------
	Application 'demo' is running! Access URLs:
	Local: 		http://localhost:8080
	External: 	http://192.168.86.75:8080
	Profile(s): 	[prod]
----------------------------------------------------------
```

but hitting the app from a browser yields:

<img width="553" alt="screen shot 2018-03-29 at 7 04 49 pm" src="https://user-images.githubusercontent.com/1223231/38117764-df9c3372-3384-11e8-98e3-0c7bc26633cd.png">

i flailed around troubleshooting for longer than i care to admit until i stumbled on the fact that renaming with a `war` suffix made the issue go away (apparently the prefix doesn't matter).

##### **Motivation for or Use Case**

issue discovered attempting to containerize

##### **Reproduce the error**

rename jhipster jar with `jar` suffix

##### **Suggest a Fix**

either:
1. make jhipster suffix agnostic, or
1. call out the suffix thing somewhere in the doc to improve awareness of behavior

##### **JHipster info**

Using JHipster version installed globally
Executing jhipster:info
Options:
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
demo@0.0.0 /Users/tony/git/Test-Jhipster
└── generator-jhipster@4.14.1

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.aetna.nba"
    },
    "jhipsterVersion": "4.14.1",
    "baseName": "demo",
    "packageName": "com.aetna.nba",
    "packageFolder": "com/aetna/nba",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "no",
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_162"
Java(TM) SE Runtime Environment (build 1.8.0_162-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.162-b12, mixed mode)

git version 2.13.0

node: v9.8.0

npm: 5.6.0

yarn: 1.5.1

Docker version 17.12.0-ce, build c97c6d6

docker-compose version 1.18.0, build 8dd22a9

Congratulations, JHipster execution is complete!

**Comment by jdubois** [comment] 2018-03-30 05:39
It's documented everywhere that we do a WAR file, this is for people using an app server.
There have been discussions to use JAR instead for JHipster v5 as app servers are dead, and I was in favor of using JAR, but this hasn't happened - I guess it just wasn't done... That's normal with OSS, people come and go and stuff is sometimes forgotten. 
Anyway,  we provide a working Dockerfile, with the correct file extension, and which has been tuned by many people. If you want to do your own that's of course perfectly fine, but then you're on your own and that's not a bug,  which is why I'm closing this ticket.

**Closed by jdubois** 2018-03-30 05:39 UTC

**Comment by tony-kerz** [comment] 2018-03-30 05:54
thanks julien, 

i didn't really consider it a bug, but i don't think the behavior follows the "principle of least surprise". 

i just think it might be a reasonable enhancement to throw-an-error/log-a-message if possible when an unsupported file suffix is used instead of log messages that imply that everything is going smoothly.

**Comment by deepu105** [comment] 2018-03-30 06:35
Did you build your front end when you build your file, how did you build
the jar? This seems like the front end missing.

**Comment by jdubois** [comment] 2018-03-30 06:41
Yes reading your ticket again you seem to have changed a lot of things...
so who knows what you broke... We can only support our code, it's already
hard enough.

**Comment by tony-kerz** [comment] 2018-03-30 13:33
sorry, i wasn't entirely clear. 

simply changing the suffix from `jar` to `war` got rid of the issue.

i'd be happy to attempt a p/r to add a log message or such if anyone can point me in the right direction code wise (i'm not sure how the code would be aware of the suffix beyond the `-jar` parameter)...

**Comment by jdubois** [comment] 2018-03-30 14:20
The good solution to me is that we migrate to a JAR - give me some time for this, and that will solve everything. For JHipster 5 I think it's much better, as reactive code won't work well in an app server.
