### ISSUE TITLE
Running reactive-ms fails on Windows after migration to webpack V5 

### ISSUE THREAD

**Issue by slade13** [jhipster/generator-jhipster#13996] opened 2021-02-18 13:35 UTC
##### **Overview of the issue**

After running `jhipster jdl reactive-ms` there is a problem with an access to the gateway on http://localhost:8080/ :

![image](https://user-images.githubusercontent.com/7571921/108360051-fe737000-71f0-11eb-87bc-79ae87d4f1f8.png)

logs:
```
----------------------------------------------------------
        Application 'gateway' is running! Access URLs:
        Local:          http://localhost:8080/
        External:       http://192.168.50.158:8080/
        Profile(s):     [dev, api-docs]
----------------------------------------------------------
2021-02-18 13:52:07.939  INFO 19720 --- [  restartedMain] com.okta.developer.gateway.GatewayApp    :
----------------------------------------------------------
        Config Server:  Connected to the JHipster Registry running in Docker
----------------------------------------------------------
2021-02-18 13:52:15.585  WARN 19720 --- [oundedElastic-1] o.z.problem.spring.common.AdviceTraits   : Not Found: 404 NOT_FOUND
2021-02-18 13:52:16.798  INFO 19720 --- [freshExecutor-0] com.netflix.discovery.DiscoveryClient    : Disable delta property : false
2021-02-18 13:52:16.798  INFO 19720 --- [freshExecutor-0] com.netflix.discovery.DiscoveryClient    : Single vip registry refresh property : null
2021-02-18 13:52:16.798  INFO 19720 --- [freshExecutor-0] com.netflix.discovery.DiscoveryClient    : Force full registry fetch : false
2021-02-18 13:52:16.798  INFO 19720 --- [freshExecutor-0] com.netflix.discovery.DiscoveryClient    : Application is null : false
2021-02-18 13:52:16.798  INFO 19720 --- [freshExecutor-0] com.netflix.discovery.DiscoveryClient    : Registered Applications size is zero : true
2021-02-18 13:52:16.798  INFO 19720 --- [freshExecutor-0] com.netflix.discovery.DiscoveryClient    : Application version is -1: false
2021-02-18 13:52:16.798  INFO 19720 --- [freshExecutor-0] com.netflix.discovery.DiscoveryClient    : Getting all instance registry info from the eureka server
2021-02-18 13:52:16.817  INFO 19720 --- [freshExecutor-0] com.netflix.discovery.DiscoveryClient    : The response status is 200
2021-02-18 13:52:16.942  INFO 19720 --- [nfoReplicator-0] com.netflix.discovery.DiscoveryClient    : Saw local status change event StatusChangeEvent [timestamp=1613652736942, current=UP, previous=DOWN]
2021-02-18 13:52:16.942  INFO 19720 --- [nfoReplicator-0] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_GATEWAY/gateway:ddfcfbb2e29361b8572dd360a7324100: registering service...
2021-02-18 13:52:16.960  INFO 19720 --- [nfoReplicator-0] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_GATEWAY/gateway:ddfcfbb2e29361b8572dd360a7324100 - registration status: 204
2021-02-18 13:52:26.830  INFO 19720 --- [freshExecutor-0] com.netflix.discovery.DiscoveryClient    : Disable delta property : false
2021-02-18 13:52:26.830  INFO 19720 --- [freshExecutor-0] com.netflix.discovery.DiscoveryClient    : Single vip registry refresh property : null
2021-02-18 13:52:26.830  INFO 19720 --- [freshExecutor-0] com.netflix.discovery.DiscoveryClient    : Force full registry fetch : false
2021-02-18 13:52:26.830  INFO 19720 --- [freshExecutor-0] com.netflix.discovery.DiscoveryClient    : Application is null : false
2021-02-18 13:52:26.830  INFO 19720 --- [freshExecutor-0] com.netflix.discovery.DiscoveryClient    : Registered Applications size is zero : true
2021-02-18 13:52:26.830  INFO 19720 --- [freshExecutor-0] com.netflix.discovery.DiscoveryClient    : Application version is -1: false
2021-02-18 13:52:26.830  INFO 19720 --- [freshExecutor-0] com.netflix.discovery.DiscoveryClient    : Getting all instance registry info from the eureka server
2021-02-18 13:52:26.849  INFO 19720 --- [freshExecutor-0] com.netflix.discovery.DiscoveryClient    : The response status is 200
2021-02-18 13:52:36.859  INFO 19720 --- [freshExecutor-0] com.netflix.discovery.DiscoveryClient    : Disable delta property : false
2021-02-18 13:52:36.859  INFO 19720 --- [freshExecutor-0] com.netflix.discovery.DiscoveryClient    : Single vip registry refresh property : null
2021-02-18 13:52:36.859  INFO 19720 --- [freshExecutor-0] com.netflix.discovery.DiscoveryClient    : Force full registry fetch : false
2021-02-18 13:52:36.859  INFO 19720 --- [freshExecutor-0] com.netflix.discovery.DiscoveryClient    : Application is null : false
2021-02-18 13:52:36.859  INFO 19720 --- [freshExecutor-0] com.netflix.discovery.DiscoveryClient    : Registered Applications size is zero : true
2021-02-18 13:52:36.859  INFO 19720 --- [freshExecutor-0] com.netflix.discovery.DiscoveryClient    : Application version is -1: false
2021-02-18 13:52:36.859  INFO 19720 --- [freshExecutor-0] com.netflix.discovery.DiscoveryClient    : Getting all instance registry info from the eureka server
2021-02-18 13:52:36.889  INFO 19720 --- [freshExecutor-0] com.netflix.discovery.DiscoveryClient    : The response status is 200
2021-02-18 13:52:42.056  WARN 19720 --- [oundedElastic-1] o.z.problem.spring.common.AdviceTraits   : Not Found: 404 NOT_FOUND
```
Each time I visit the page the `[oundedElastic-1] o.z.problem.spring.common.AdviceTraits   : Not Found: 404 NOT_FOUND` is populated.

After running gateway in production mode, build fails:
```
C:\Users\mateu\OneDrive\Documents\work\jhipster-contribution\reproduce#13862_newV\gateway>gradlew -Pprod

> Task :webapp

> gateway@0.0.0 webapp:prod
> npm run clean-www && npm run webapp:build:prod


> gateway@0.0.0 clean-www
> rimraf build/resources/main/static/app/{src,build/}


> gateway@0.0.0 webapp:build:prod
> npm run webpack -- --config webpack/webpack.prod.js --progress=profile --env stats=minimal


> gateway@0.0.0 webpack
> node --max_old_space_size=4096 node_modules/webpack/bin/webpack.js "--config" "webpack/webpack.prod.js" "--progress=profile" "--env" "stats=minimal"

<s> [webpack.Progress] 0%

<s> [webpack.Progress] 1% setup initialize
<s> [webpack.Progress] 1% setup initialize HtmlWebpackPlugin
<s> [webpack.Progress] 1% setup initialize
<s> [webpack.Progress] 2% setup before run
<s> [webpack.Progress] 2% setup before run NodeEnvironmentPlugin
<s> [webpack.Progress] 2% setup before run
<s> [webpack.Progress] 3% setup run
<s> [webpack.Progress] 3% setup run webpack-cli
<s> [webpack.Progress] 3% setup run ForkTsCheckerWebpackPlugin
<s> [webpack.Progress] 3% setup run
<s> [webpack.Progress] 4% setup normal module factory
<s> [webpack.Progress] 4% setup normal module factory
<s> [webpack.Progress] 5% setup context module factory
<s> [webpack.Progress] 5% setup context module factory
<s> [webpack.Progress] 6% setup before compile
<s> [webpack.Progress] 6% setup before compile ProgressPlugin
<s> [webpack.Progress] 6% setup before compile
<s> [webpack.Progress] 7% setup compile
<s> [webpack.Progress] 7% setup compile ExternalsPlugin
<s> [webpack.Progress] 7% setup compile
<s> [webpack.Progress] 8% setup compilation
<s> [webpack.Progress] 8% setup compilation CopyPlugin
<s> [webpack.Progress] 8% setup compilation mini-css-extract-plugin
<s> [webpack.Progress] 8% setup compilation GenerateSW
<s> [webpack.Progress] 8% setup compilation ArrayPushCallbackChunkFormatPlugin
<s> [webpack.Progress] 8% setup compilation JsonpChunkLoadingPlugin
<s> [webpack.Progress] 8% setup compilation StartupChunkDependenciesPlugin
<s> [webpack.Progress] 8% setup compilation ImportScriptsChunkLoadingPlugin
<s> [webpack.Progress] 8% setup compilation FetchCompileWasmPlugin
<s> [webpack.Progress] 8% setup compilation FetchCompileAsyncWasmPlugin
<s> [webpack.Progress] 8% setup compilation WorkerPlugin
<s> [webpack.Progress] 8% setup compilation SplitChunksPlugin
<s> [webpack.Progress] 8% setup compilation ResolverCachePlugin
<s> [webpack.Progress] 8% setup compilation HtmlWebpackPlugin
<s> [webpack.Progress] 8% setup compilation
<s> [webpack.Progress] 9% setup compilation
<s> [webpack.Progress] 9% setup compilation ProgressPlugin
<s> [webpack.Progress] 9% setup compilation vue-loader-plugin
<s> [webpack.Progress] 9% setup compilation DefinePlugin
<s> [webpack.Progress] 9% setup compilation TerserPlugin
<s> [webpack.Progress] 9% setup compilation OptimizeCssAssetsWebpackPlugin
<s> [webpack.Progress] 9% setup compilation ForkTsCheckerWebpackPlugin
<s> [webpack.Progress] 9% setup compilation ChunkPrefetchPreloadPlugin
<s> [webpack.Progress] 9% setup compilation SourceMapDevToolPlugin
<s> [webpack.Progress] 9% setup compilation JavascriptModulesPlugin
<s> [webpack.Progress] 9% setup compilation JsonModulesPlugin
<s> [webpack.Progress] 9% setup compilation AssetModulesPlugin
<s> [webpack.Progress] 9% setup compilation EntryPlugin
<s> [webpack.Progress] 9% setup compilation EntryPlugin
<s> [webpack.Progress] 9% setup compilation EntryPlugin
<s> [webpack.Progress] 9% setup compilation RuntimePlugin
<s> [webpack.Progress] 9% setup compilation InferAsyncModulesPlugin
<s> [webpack.Progress] 9% setup compilation DataUriPlugin
<s> [webpack.Progress] 9% setup compilation FileUriPlugin
<s> [webpack.Progress] 9% setup compilation CompatibilityPlugin
<s> [webpack.Progress] 9% setup compilation HarmonyModulesPlugin
<s> [webpack.Progress] 9% setup compilation AMDPlugin
<s> [webpack.Progress] 9% setup compilation RequireJsStuffPlugin
<s> [webpack.Progress] 9% setup compilation CommonJsPlugin
<s> [webpack.Progress] 9% setup compilation LoaderPlugin
<s> [webpack.Progress] 9% setup compilation LoaderPlugin
<s> [webpack.Progress] 9% setup compilation NodeStuffPlugin
<s> [webpack.Progress] 9% setup compilation APIPlugin
<s> [webpack.Progress] 9% setup compilation ExportsInfoApiPlugin
<s> [webpack.Progress] 9% setup compilation WebpackIsIncludedPlugin
<s> [webpack.Progress] 9% setup compilation ConstPlugin
<s> [webpack.Progress] 9% setup compilation UseStrictPlugin
<s> [webpack.Progress] 9% setup compilation RequireIncludePlugin
<s> [webpack.Progress] 9% setup compilation RequireEnsurePlugin
<s> [webpack.Progress] 9% setup compilation RequireContextPlugin
<s> [webpack.Progress] 9% setup compilation ImportPlugin
<s> [webpack.Progress] 9% setup compilation SystemPlugin
<s> [webpack.Progress] 9% setup compilation ImportMetaPlugin
<s> [webpack.Progress] 9% setup compilation URLPlugin
<s> [webpack.Progress] 9% setup compilation DefaultStatsFactoryPlugin
<s> [webpack.Progress] 9% setup compilation DefaultStatsPresetPlugin
<s> [webpack.Progress] 9% setup compilation DefaultStatsPrinterPlugin
<s> [webpack.Progress] 9% setup compilation JavascriptMetaInfoPlugin
<s> [webpack.Progress] 9% setup compilation EnsureChunkConditionsPlugin
<s> [webpack.Progress] 9% setup compilation RemoveEmptyChunksPlugin
<s> [webpack.Progress] 9% setup compilation MergeDuplicateChunksPlugin
<s> [webpack.Progress] 9% setup compilation FlagIncludedChunksPlugin
<s> [webpack.Progress] 9% setup compilation SideEffectsFlagPlugin
<s> [webpack.Progress] 9% setup compilation FlagDependencyExportsPlugin
<s> [webpack.Progress] 9% setup compilation FlagDependencyUsagePlugin
<s> [webpack.Progress] 9% setup compilation InnerGraphPlugin
<s> [webpack.Progress] 9% setup compilation MangleExportsPlugin
<s> [webpack.Progress] 9% setup compilation ModuleConcatenationPlugin
<s> [webpack.Progress] 9% setup compilation NoEmitOnErrorsPlugin
<s> [webpack.Progress] 9% setup compilation RealContentHashPlugin
<s> [webpack.Progress] 9% setup compilation WasmFinalizeExportsPlugin
<s> [webpack.Progress] 9% setup compilation DeterministicModuleIdsPlugin
<s> [webpack.Progress] 9% setup compilation DeterministicChunkIdsPlugin
<s> [webpack.Progress] 9% setup compilation DefinePlugin
<s> [webpack.Progress] 9% setup compilation TerserPlugin
<s> [webpack.Progress] 9% setup compilation TemplatedPathPlugin
<s> [webpack.Progress] 9% setup compilation RecordIdsPlugin
<s> [webpack.Progress] 9% setup compilation WarnCaseSensitiveModulesPlugin
<s> [webpack.Progress] 9% setup compilation
<i> [webpack.Progress]  | 14 ms setup > compilation
<i> [webpack.Progress] 23 ms setup
<s> [webpack.Progress] 10% building
<s> [webpack.Progress] 10% building 0/1 entries 0/0 dependencies 0/0 modules
(node:196) [DEP_WEBPACK_COMPILATION_OPTIMIZE_CHUNK_ASSETS] DeprecationWarning: optimizeChunkAssets is deprecated (use Compilation.hook.processAssets instead and use one of Compilation.PROCESS_ASSETS_STAGE_* as stage option)
(Use `node --trace-deprecation ...` to show where the warning was created)
<i> [webpack.Progress]  | 107 ms building > entries dependencies modules
<s> [webpack.Progress] 10% building import loader ../../reproduce#13862_newV/gateway/node_modules/ts-loader/index.js
<s> [webpack.Progress] 28% building import loader ../../reproduce#13862_newV/gateway/node_modules/ts-loader/index.js
<s> [webpack.Progress] 46% building import loader ../../reproduce#13862_newV/gateway/node_modules/ts-loader/index.js
<s> [webpack.Progress] 46% building import loader ../../reproduce#13862_newV/gateway/node_modules/mini-css-extract-plugin/dist/loader.js
<s> [webpack.Progress] 65% building import loader ../../reproduce#13862_newV/gateway/node_modules/mini-css-extract-plugin/dist/loader.js
<s> [webpack.Progress] 65% building
<s> [webpack.Progress] 69% building finish
<s> [webpack.Progress] 69% building finish
<i> [webpack.Progress] 108 ms building
<s> [webpack.Progress] 70% sealing finish module graph
<s> [webpack.Progress] 70% sealing finish module graph ResolverCachePlugin
<s> [webpack.Progress] 70% sealing finish module graph InferAsyncModulesPlugin
<s> [webpack.Progress] 70% sealing finish module graph FlagDependencyExportsPlugin
<s> [webpack.Progress] 70% sealing finish module graph InnerGraphPlugin
<s> [webpack.Progress] 70% sealing finish module graph WasmFinalizeExportsPlugin
<s> [webpack.Progress] 70% sealing finish module graph
<s> [webpack.Progress] 70% sealing plugins
<s> [webpack.Progress] 70% sealing plugins WarnCaseSensitiveModulesPlugin
<s> [webpack.Progress] 70% sealing plugins
<s> [webpack.Progress] 71% sealing dependencies optimization
<s> [webpack.Progress] 71% sealing dependencies optimization SideEffectsFlagPlugin
<s> [webpack.Progress] 71% sealing dependencies optimization FlagDependencyUsagePlugin
<s> [webpack.Progress] 71% sealing dependencies optimization
<s> [webpack.Progress] 71% sealing after dependencies optimization
<s> [webpack.Progress] 71% sealing after dependencies optimization
<s> [webpack.Progress] 72% sealing chunk graph
<s> [webpack.Progress] 72% sealing chunk graph
<s> [webpack.Progress] 73% sealing after chunk graph
<s> [webpack.Progress] 73% sealing after chunk graph
<s> [webpack.Progress] 73% sealing optimizing
<s> [webpack.Progress] 73% sealing optimizing
<s> [webpack.Progress] 74% sealing module optimization
<s> [webpack.Progress] 74% sealing module optimization
<s> [webpack.Progress] 75% sealing after module optimization
<s> [webpack.Progress] 75% sealing after module optimization
<s> [webpack.Progress] 75% sealing chunk optimization
<s> [webpack.Progress] 75% sealing chunk optimization EnsureChunkConditionsPlugin
<s> [webpack.Progress] 75% sealing chunk optimization RemoveEmptyChunksPlugin
<s> [webpack.Progress] 75% sealing chunk optimization MergeDuplicateChunksPlugin
<s> [webpack.Progress] 75% sealing chunk optimization SplitChunksPlugin
<s> [webpack.Progress] 75% sealing chunk optimization RemoveEmptyChunksPlugin
<s> [webpack.Progress] 75% sealing chunk optimization
<s> [webpack.Progress] 76% sealing after chunk optimization
<s> [webpack.Progress] 76% sealing after chunk optimization
<s> [webpack.Progress] 77% sealing module and chunk tree optimization
<s> [webpack.Progress] 77% sealing module and chunk tree optimization PersistentChildCompilerSingletonPlugin
<s> [webpack.Progress] 77% sealing module and chunk tree optimization
<s> [webpack.Progress] 77% sealing after module and chunk tree optimization
<s> [webpack.Progress] 77% sealing after module and chunk tree optimization
<s> [webpack.Progress] 78% sealing chunk modules optimization
<s> [webpack.Progress] 78% sealing chunk modules optimization ModuleConcatenationPlugin
<s> [webpack.Progress] 78% sealing chunk modules optimization
<s> [webpack.Progress] 78% sealing after chunk modules optimization
<s> [webpack.Progress] 78% sealing after chunk modules optimization
<s> [webpack.Progress] 79% sealing module reviving
<s> [webpack.Progress] 79% sealing module reviving RecordIdsPlugin
<s> [webpack.Progress] 79% sealing module reviving
<s> [webpack.Progress] 80% sealing before module ids
<s> [webpack.Progress] 80% sealing before module ids
<s> [webpack.Progress] 80% sealing module ids
<s> [webpack.Progress] 80% sealing module ids DeterministicModuleIdsPlugin
<s> [webpack.Progress] 80% sealing module ids
<s> [webpack.Progress] 81% sealing module id optimization
<s> [webpack.Progress] 81% sealing module id optimization
<s> [webpack.Progress] 82% sealing module id optimization
<s> [webpack.Progress] 82% sealing module id optimization
<s> [webpack.Progress] 82% sealing chunk reviving
<s> [webpack.Progress] 82% sealing chunk reviving RecordIdsPlugin
<s> [webpack.Progress] 82% sealing chunk reviving
<s> [webpack.Progress] 83% sealing before chunk ids
<s> [webpack.Progress] 83% sealing before chunk ids
<s> [webpack.Progress] 84% sealing chunk ids
<s> [webpack.Progress] 84% sealing chunk ids DeterministicChunkIdsPlugin
<s> [webpack.Progress] 84% sealing chunk ids
<s> [webpack.Progress] 84% sealing chunk id optimization
<s> [webpack.Progress] 84% sealing chunk id optimization FlagIncludedChunksPlugin
<s> [webpack.Progress] 84% sealing chunk id optimization
<s> [webpack.Progress] 85% sealing after chunk id optimization
<s> [webpack.Progress] 85% sealing after chunk id optimization
<s> [webpack.Progress] 87% sealing module hashing
<s> [webpack.Progress] 87% sealing module hashing
internal/crypto/hash.js:84
    throw new ERR_INVALID_ARG_TYPE(
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
    at Hash.update (internal/crypto/hash.js:84:11)
    at BulkUpdateDecorator.update (C:\Users\mateu\OneDrive\Documents\work\jhipster-contribution\reproduce#13862_newV\gateway\node_modules\webpack\lib\util\createHash.js:51:14)
    at NormalModule.updateHash (C:\Users\mateu\OneDrive\Documents\work\jhipster-contribution\reproduce#13862_newV\gateway\node_modules\webpack\lib\NormalModule.js:1129:8)
    at Compilation._createModuleHash (C:\Users\mateu\OneDrive\Documents\work\jhipster-contribution\reproduce#13862_newV\gateway\node_modules\webpack\lib\Compilation.js:3085:10)
    at Compilation.createModuleHashes (C:\Users\mateu\OneDrive\Documents\work\jhipster-contribution\reproduce#13862_newV\gateway\node_modules\webpack\lib\Compilation.js:3057:10)
    at C:\Users\mateu\OneDrive\Documents\work\jhipster-contribution\reproduce#13862_newV\gateway\node_modules\webpack\lib\Compilation.js:2334:11
    at eval (eval at create (C:\Users\mateu\OneDrive\Documents\work\jhipster-contribution\reproduce#13862_newV\gateway\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:23:1)
    at C:\Users\mateu\OneDrive\Documents\work\jhipster-contribution\reproduce#13862_newV\gateway\node_modules\webpack\lib\optimize\ModuleConcatenationPlugin.js:449:32
    at processTicksAndRejections (internal/process/task_queues.js:75:11) {
  code: 'ERR_INVALID_ARG_TYPE'
}
npm ERR! code 1
npm ERR! path C:\Users\mateu\OneDrive\Documents\work\jhipster-contribution\reproduce#13862_newV\gateway
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node --max_old_space_size=4096 node_modules/webpack/bin/webpack.js --config webpack/webpack.prod.js --progress=profile --env stats=minimal

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\mateu\AppData\Local\npm-cache\_logs\2021-02-18T13_29_24_835Z-debug.log
npm ERR! code 1
npm ERR! path C:\Users\mateu\OneDrive\Documents\work\jhipster-contribution\reproduce#13862_newV\gateway
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c npm run webpack -- --config webpack/webpack.prod.js --progress=profile --env stats=minimal

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\mateu\AppData\Local\npm-cache\_logs\2021-02-18T13_29_24_854Z-debug.log
npm ERR! code 1
npm ERR! path C:\Users\mateu\OneDrive\Documents\work\jhipster-contribution\reproduce#13862_newV\gateway
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c npm run clean-www && npm run webapp:build:prod

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\mateu\AppData\Local\npm-cache\_logs\2021-02-18T13_29_24_876Z-debug.log

> Task :webapp FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':webapp'.
> Process 'command 'npm.cmd'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s
3 actionable tasks: 2 executed, 1 up-to-date

C:\Users\mateu\OneDrive\Documents\work\jhipster-contribution\reproduce#13862_newV\gateway>
```

##### **Motivation for or Use Case**

Behavior of the application should be the same or at least operational for both Windows and macOS/Linux systems.

As I know everything works just fine on the macOS.

##### **Reproduce the error**

To reproduce this error follow the procedures below:

```
jhipster jdl reactive-ms

cd gateway
docker-compose -f src/main/docker/keycloak.yml up -d
docker-compose -f src/main/docker/postgresql.yml up -d
docker-compose -f src/main/docker/jhipster-registry.yml up -d
gradlew

# open a new terminal
cd blog
docker-compose -f src/main/docker/neo4j.yml up -d
gradlew

# open a new terminal
cd store
docker-compose -f src/main/docker/mongodb.yml up -d
gradlew
```

##### **Related issues**

Problem happened when I tried to reproduce this issue: #13862 

##### **Suggest a Fix**

Static resources are not copied to **gateway\build\resources\main\static**

Reverting commit 525b1b223b327399c907d501d8faa06f05f2a344 fixes this problem.

##### **JHipster Version(s)**

Current **main** branch from **18.02.2021**

##### **Browsers and Operating System**

Tested on Chrome, Edge and Firefox - behavior is the same, so it's not the case
Windows 10.0.19041

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment] 2021-02-19 21:09
Can you post your information with `jhipster info` plz? So we'll know your node, npm version etc

It's to compare with our daily builds for Windows: https://github.com/hipster-labs/jhipster-daily-builds/actions/runs/580874212

**Comment by slade13** [comment] 2021-02-19 22:49
Sure, here is the full output:
```
INFO! Using JHipster version installed locally in current project's node_modules
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
gateway@0.0.0 C:\Users\mateu\OneDrive\Documents\work\jhipster-contribution\reproduce#13862_newV\gateway
`-- generator-jhipster@7.0.0-beta.1

```


##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**


<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "authenticationType": "oauth2",
    "cacheProvider": "no",
    "clientFramework": "vue",
    "serverPort": "8080",
    "serviceDiscoveryType": "eureka",
    "skipUserManagement": true,
    "withAdminUi": true,
    "baseName": "gateway",
    "buildTool": "gradle",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "enableHibernateCache": false,
    "enableSwaggerCodegen": false,
    "enableTranslation": true,
    "jhiPrefix": "jhi",
    "languages": [
      "en"
    ],
    "messageBroker": false,
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "skipClient": false,
    "testFrameworks": [
      "protractor"
    ],
    "websocket": false,
    "reactive": true,
    "packageName": "com.okta.developer.gateway",
    "packageFolder": "com/okta/developer/gateway",
    "applicationType": "gateway",
    "jhipsterVersion": "7.0.0-beta.1",
    "skipServer": false,
    "clientPackageManager": "npm",
    "dtoSuffix": "DTO",
    "entitySuffix": "",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "blueprints": [],
    "otherModules": [],
    "pages": [],
    "nativeLanguage": "en",
    "creationTimestamp": 1613652422899,
    "lastLiquibaseTimestamp": 1613652662000,
    "entities": [
      "Blog",
      "Post",
      "Product",
      "Tag"
    ],
    "appFolder": "gateway"
  }
}

</pre>
</details>


##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Blog {
  name String required minlength(3)
  handle String required minlength(2)
}
entity Post {
  title String required
  content TextBlob required
  date Instant required
}
entity Product {
  title String required
  price BigDecimal required min(0)
  image ImageBlob
}
entity Tag {
  name String required minlength(2)
}
relationship ManyToOne {
  Blog{user(login)} to User
  Post{blog(name)} to Blog
}
relationship ManyToMany {
  Post{tag(name)} to Tag{post}
}

microservice Blog, Post, Tag with blog
microservice Product with store
clientRootFolder Blog, Post, Tag with blog
clientRootFolder Product with store
paginate Post, Tag with infinite-scroll
paginate Product with pagination

</pre>
</details>


##### **Environment and Tools**

java version "11.0.10" 2021-01-19 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.10+8-LTS-162)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.10+8-LTS-162, mixed mode)

git version 2.30.0.windows.1

node: v14.15.4

npm: 7.5.4

Docker version 20.10.2, build 2291f61

docker-compose version 1.27.4, build 40524192

INFO! Congratulations, JHipster execution is complete!
```

**Comment by pascalgrimaud** [comment] 2021-03-04 22:17
ping @jhipster/developers : is there someone with Windows who can test this one plz ?

**Comment by mraible** [comment] 2021-03-11 04:53
Adding a bounty to encourage folks to test on Windows.

**Comment by murdos** [comment] 2021-03-11 23:18
Here's what I've tested on my Windows machine:

```
jhipster jdl reactive-ms

cd gateway
docker-compose -f src/main/docker/keycloak.yml up -d
docker-compose -f src/main/docker/postgresql.yml up -d
docker-compose -f src/main/docker/jhipster-registry.yml up -d
gradlew

# open a new terminal
cd blog
docker-compose -f src/main/docker/neo4j.yml up -d
gradlew

# open a new terminal
cd store
docker-compose -f src/main/docker/mongodb.yml up -d
gradlew
```

I've been able to: 
- access gateway on http://localhost:8080, 
- authenticate with admin
- create a new blog
- create a new product
However (but I think this is unrelated to this ticket), I can't create a new tag a new blog post.

Then I've stopped gateway, and - in the gateway folder - relaunched it prod profile:
`./gradlew -Pprod`
Nothing particular here, I'm still been able to access gateway on http://localhost:8080, authenticate with admin.

So, it seems I can't reproduce the issue described here.
For the record:
```
##### **Environment and Tools**

java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)

git version 2.29.2.windows.2

node: v14.15.1

npm: 6.14.8

Docker version 20.10.2, build 2291f61

docker-compose version 1.27.4, build 40524192
```

**Comment by mshima** [comment] 2021-03-12 09:52
I’ve created daily builds for react and vue.
https://github.com/hipster-labs/jhipster-daily-builds/actions/runs/645610146.

IMO this was a webpack plugin problem that was fixed upstream.
@slade13 can you still reproduce the problem?

**Comment by ecostanzi** [comment] 2021-03-12 13:16
I also tried to reproduce on windows. Everything seems to work fine.

**Comment by vishal423** [comment] 2021-03-12 14:35
I do see the difference in the `npm` version. Daily builds use `6.14.6`, whereas the issue is raised with `7.5.4`

**Comment by deepu105** [comment] 2021-03-12 17:25
We only support the LTS versions of node/npm

**Comment by vishal423** [comment] 2021-03-12 17:39
https://github.com/jhipster/generator-jhipster/blob/fa96b1348199f2822ba6f1ba0552646735aa2a78/generators/generator-constants.js#L28

**Comment by deepu105** [comment] 2021-03-12 17:44
Ah ok

**Comment by mshima** [comment] 2021-03-19 19:48
Closing since 2 core developer were unable to reproduce and CI is passing.

**Closed by mshima** 2021-03-19 19:48 UTC
Labels: $$ bug-bounty $$, $200, area: needs-reproduction, theme: front, theme: windows
