### ISSUE TITLE
Search functionality

### ISSUE THREAD

**Issue by pnreddysvu** [jhipster/generator-jhipster#1317] opened 2015-03-31 06:43 UTC
JBoss Developer Studio Forge supports search functionality out of the box for a generated entity.
JBoss forge also generate AngularJS code. I think JBoss forge  templates can be reused to implement search in Jhipster project also.
Please have a look at the below sample application

http://www.jboss.org/ticket-monster/adminhtml5/

Below is forge code

https://github.com/forge

https://github.com/forge/angularjs-scaffoldx-plugin

https://github.com/forge/angularjs-addon

Another good thing about Forge is you can generate separate front end and back end code

**Comment by jdubois** [comment] 2015-03-31 08:03
Do you know how it works with Forge? If that's just a "%" in the SQL code, then that would be too basic for us.

I'd like us to have an ElasticSearch "hook", but that's a bit complex to add, so at the moment it's out of scope -> let's discuss this here first, and have a look at forge, then I will create a specific ticket for this.

**Comment by pnreddysvu** [comment] 2015-03-31 08:49
Ok if you are looking for ElasticSearch then that will be good. Forge has simple search.

**Comment by jdubois** [comment] 2015-03-31 08:52
You mean they only do a "%" in SQL? That wouldn't surprise me...

**Comment by pnreddysvu** [comment] 2015-03-31 09:10
I haven't checked the code. Will scaffold some entities and check it.

**Comment by verrol** [comment] 2015-04-01 04:26
What about Solr? From the entity, we can build a solr-schema to index that entity. The 'entity' sub-generator would ask two other questions on the field. Should the field be indexed and/or stored. When a entity is created or updated, a record is sent to Solr for indexing. later it can be searched. Spring Data might have support for Solr. Data will be both indexed in Solr and stored in SQL/NoSQL. Probably after it is persisted so the "id" field can be used in solr to find it in the DB.

**Comment by rblazquez** [comment] 2015-04-03 02:34
+1 For searching capabilities

ElasticSearch seems like a good idea ... however if too complex a simpler solution may be interesting also. Searching is basic functionality most webapps need.

Maybe "%" looks like too basic but now there is nothing.

**Comment by jdubois** [comment] 2015-04-03 09:28
- "%" is just a bad practice, and we don't support bad practices :-)
- Solr vs ElasticSearch: I always prefer to use Apache projects over projects owned by a company, but in this case it's clear that ElasticSearch has won the "hype" war, so I'd rather use it
- Maybe we could also propose a "bare Lucene" option, using Hibernate Search. I've already used it, it's an excellent solution, and very easy to use. But that means you need to store your Lucene index on your local hard drive, which is against our "cloud ready" principles (we want to do a "12 Factor" app): so that could only be a non-default option, and not a standard option

**Comment by jdubois** [comment] 2015-04-15 16:20
I'm going to merge an ElasticSearch option, that was made with @dadoonet this week.

This is some big rework, so don't expect a result until the end of next week!

**Comment by dadoonet** [comment] 2015-04-15 16:27
\o/ Tell me if you need a code review. I'll be happy to help

**Comment by jdubois** [comment] 2015-04-15 16:31
@dadoonet yes I will definitely need one, thanks!

**Comment by pnreddysvu** [comment] 2015-04-16 02:00
thanks @dadoonet  and @jdubois . You made my work easier.

**Comment by jdubois** [comment] 2015-04-16 16:02
After having a look at it, I might use Spring Data ElasticSearch instead of the code from @dadoonet -> it should work the same, but with a lot less code.
At least I will try both options, and then choose after testing which has the best code.

About our architecture: I'm worried as we should have some kind of search repositories, along our JPA repositories. My current idea is to put them in the *.repository.search package -> it would be a subpackage of the JPA repositories, as I think they complete the JPA repositories. Any comments on this?

**Comment by pnreddysvu** [comment] 2015-04-17 02:16
Yes I also prefer to have separate search repositories.

**Comment by jdubois** [comment] 2015-04-23 22:22
Closed, as ElasticSearch has just been merged in master

**Closed by jdubois** 2015-04-23 22:22 UTC

**Comment by pnreddysvu** [comment] 2015-04-24 06:40
Seems only exact search is implemented right?
I quickly tried and found one issue.

I created an entity with many-to-one relationship with user. I choose 'login' as display field.
After search user field is coming empty.

**Comment by jdubois** [comment] 2015-04-24 07:10
- It's done with ElasticSearch, but without a specific configuration, so yes it's "exact search". Then you need to customize ElasticSearch
- Search is on the current entity, not related entities. That could be improved, indeed, but at the moment we have first the basic features.
- If you remove your search query, then you have a "findAll" -> you seem to have an issue here, but I can't reproduce it

**Comment by krishna383** [comment] 2015-05-15 05:03
Have been trying to make the related entities work. Any pointers would be helpful
