### ISSUE TITLE
After upgrading to 3.5.1 I had to add to my test/application.yml a new configuration for hibernate second level cache

### ISSUE THREAD

**Issue by marcelinobadin** [jhipster/generator-jhipster#3932] opened 2016-08-04 21:07 UTC
After I did upgrade to version 3.5.1 and ran my tests, I got an error telling me to add 

 hibernate.cache.region.factory_class: hibernate.cache.region.factory_class: com.hazelcast.hibernate.HazelcastCacheRegionFactory

on my test/application.yml.

Is that right? Because after that, all tests passed.

**Comment by jdubois** [comment] 2016-08-04 21:36
There shouldn't be this `test/application.yml` file, so you've probably found a bug. However I need more info to reproduce, like your .yo-rc.json to answer you, as well as what you did with your entities.

**Comment by jdubois** [comment] 2016-08-04 21:37
This ticket has been closed as the guidelines are not followed.

Tickets must follow our [Guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#submitting-an-issue), as mentioned in:

1. our [Readme file on the front page of the project](https://github.com/jhipster/generator-jhipster/blob/master/README.md), 
2. the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) and
3. our [Help page](http://jhipster.github.io/help/)

We have also created a template on the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) to help you follow those guidelines.

**Comment by marcelinobadin** [comment] 2016-08-04 21:40
ok.. test/resources/config/application.yml... but anyway... I will come back with more detailed issue to help us all investigate this.

**Comment by jdubois** [comment] 2016-08-04 21:46
Oh OK, indeed this file is needed, then!
Can you post your `.yo-rc.json` file, so I can try to reproduce?

**Comment by marcelinobadin** [comment] 2016-08-04 21:48
yes, sure.

```json
{
  "generator-jhipster": {
    "jhipsterVersion": "3.5.1",
    "baseName": "newton",
    "packageName": "com.example.app",
    "packageFolder": "com/example/app",
    "serverPort": "8081",
    "authenticationType": "jwt",
    "hibernateCache": "hazelcast",
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": "elasticsearch",
    "buildTool": "maven",
    "jwtSecretKey": "blablabla",
    "enableTranslation": true,
    "applicationType": "microservice",
    "testFrameworks": [
      "gatling"
    ],
    "skipClient": true,
    "skipUserManagement": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "pt-br"
    ],
    "clusteredHttpSession": "no",
    "websocket": "no",
    "enableSocialSignIn": false,
    "jhiPrefix": "jhi"
  },
  "generator-jhipster-entity-audit": {
    "auditFramework": "custom"
  }
}
```

**Comment by jdubois** [comment] 2016-08-04 21:59
Thanks, I'm re-opening this and I'll have a look tomorrow

**Comment by jdubois** [comment] 2016-08-05 10:01
- I created an app with your `.yo-rc.json` file
- I created an entity, as you need one if you want to test the cache

-> I didn't have any issue, and I didn't get that warning.

I'm closing this as I can't reproduce, but that's weird.

**Closed by jdubois** 2016-08-05 10:01 UTC

**Comment by marcelinobadin** [comment] 2016-08-05 10:57
Well, if I find something I tell you. Thanks!
