### ISSUE TITLE
Directories with space are not working (upgrade sub-generator)

### ISSUE THREAD

**Issue by MBurchard** [jhipster/generator-jhipster#6864] opened 2017-12-14 11:13 UTC
During the upgrade process to 4.13.0 under Windows 10 an error is show.

The first step `yarn global upgrade generator-jhipster` was done.

The second step...

    c:\Users\Martin Burchard\Entwicklung\2018\el-vis>jhipster upgrade
    ...
    √ Installed generator-jhipster@4.12.0
    Regenerating application with JHipster 4.12.0...
    c:\Users\Martin Burchard\Entwicklung\2018\el-vis\node_modules\.bin
         info c:\Users\Martin Burchard\Entwicklung\2018\el-vis\node_modules\.bin/jhipster --with-entities --force --skip-install
    Der Befehl "c:\Users\Martin" ist entweder falsch geschrieben oder
    konnte nicht gefunden werden.
    events.js:183
          throw er; // Unhandled 'error' event
          ^

    Error: ERROR! Something went wrong while generating project! Der Befehl "c:\Users\Martin" ist entweder falsch geschrieben oder
    konnte nicht gefunden werden.

        at Environment.error (C:\Users\Martin Burchard\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\yeoman-environment\lib\environment.js:157:40)
        at module.exports.error (C:\Users\Martin Burchard\AppData\Roaming\npm\node_modules\generator-jhipster\generators\generator-base.js:1974:18)
        at shelljs.exec (C:\Users\Martin Burchard\AppData\Roaming\npm\node_modules\generator-jhipster\generators\upgrade\index.js:87:23)
        at C:\Users\Martin Burchard\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\shelljs\src\exec.js:204:9
        at ChildProcess.exithandler (child_process.js:282:5)
        at emitTwo (events.js:126:13)
        at ChildProcess.emit (events.js:214:7)
        at maybeClose (internal/child_process.js:925:16)
        at Socket.stream.socket.on (internal/child_process.js:346:11)
        at emitOne (events.js:116:13)

Besides the error I also wonder, we it says:

    √ Installed generator-jhipster@4.12.0
    Regenerating application with JHipster 4.12.0...

**Comment by PierreBesson** [comment] 2017-12-14 13:11
Looks like the problem is here : https://github.com/jhipster/generator-jhipster/blob/master/generators/upgrade/index.js#L81, the generatorCommand variable should be wrapped with quotes like this : 
```
generatorCommand = `"${generatorDir.replace('\n', '')}/jhipster"`;
```

This would work on linux but I'm not sure if it would solve the problem on windows. Do you mind trying it out and submitting a PR ?

**Comment by jdubois** [comment] 2017-12-14 13:12
Thanks @PierreBesson ! The problem is that we don't have any Windows license to test - see my thread at https://twitter.com/java_hipster/status/940510248644866049

**Comment by MBurchard** [comment] 2017-12-14 13:50
Steps I did:

- downgrade to jhipster 4.12.0
- create new application
- upgrade to jhipster 4.13.0
- run `jhipster upgrade` to make sure this problem occurs with e new project
- revert all changes and get previous version from git
- changed C:\Users\Martin Burchard\Entwicklung\2018\el-vis-4.12\node_modules\generator-jhipster\generators\upgrade\index.js like advised above
- run `jhipster upgrade` again
- error still occures. Reason: It looks like my changes in node_modules get replaced during jhipster upgrade command.

How can I test if your suggestion works?

**Comment by antarus** [comment] 2017-12-14 14:09
I confirm the issue and I also confirm that the @PierreBesson  solution works on windows.

The problem is that, since older versions do not have the double quote, the upgrade will not work.
To test the solution of Pierre, I generate the application with a clone of the generator, modify the version in the .yo-rc and then upgrade with my version edit locally.

The simplest solution for versions not containing this patch is to launch the upgrade in a folder without space.

I can do a PR tonight if you want.

**Comment by PierreBesson** [comment] 2017-12-14 14:11
@antarus Well done ! And yes sadly this won't fix the problem for 4.12 but future releases will not have the bug.

**Comment by antarus** [comment] 2017-12-14 14:14
I can't test  under linux though..

**Comment by MBurchard** [comment] 2017-12-14 15:03
Great... yes, already did the update in another folder and moved it back where it was before...
Thank you...

**Closed** 2017-12-15 07:11 UTC

**Comment by PierreBesson** [comment] 2017-12-15 14:30
@antarus Even without testing, I'm confident that it will work on linux.
