### ISSUE TITLE
Front : Loading resources problem

### ISSUE THREAD

**Issue by 7170** [jhipster/generator-jhipster#1702] opened 2015-07-08 12:48 UTC
First of all, this project is amazing and gave me the power to save a lot of time in starting a new project !

Since I use JHipster I have a big issue with front loading, I tried lot of thing to avoid this problem but couldn't solve it by myself...

I use JHipster with default choices and jdk 7  on a mac os X Yosemite, Postgres 9.4 and a tomcat 8.0.22 installed.

The fact is when I start tomcat it's fine and all works well ! 

![issue_working](https://cloud.githubusercontent.com/assets/7570981/8570218/3c95e08a-257f-11e5-935d-7ac953f1455e.png)

After few time using and loading resources from clients, the front displays only "This is your footer" And nothing appears in logs or JVM memory or anywhere else.... I've reproduced this with another OS by connecting to the remote database (on the mac), but with another postgres, on different machine, I have no problem.
Another test was to connect to another postgres and to stop it. In this case no front appears at all, just a grey banner at the top with no error showed (it seems to be infinitely loading)...

![issue_no_front](https://cloud.githubusercontent.com/assets/7570981/8570205/2b397e6e-257f-11e5-8fe1-613d90d6d046.png)

So please help me to identify my problem and see if it is a JHipster issue or something wrong from me :)

Thank you in advance for the time you'll give me !

**Comment by gmarziou** [comment] 2015-07-08 13:39
Have you looked at browser console?

**Comment by 7170** [comment] 2015-07-08 13:45
> Have you looked at browser console?

In my description I said :
> And nothing appears in logs or JVM memory or anywhere else....

**Comment by jdubois** [comment] 2015-07-08 19:19
Do you have an ad blocker? We've had several people who had a similar error because of that.
Otherwise, did you try to force refresh your browser? In Chrome, open up the dev console, then click for a long time on the "reload" button, you will get 3 choices, one of them being "clean cache and force reload"

**Comment by 7170** [comment] 2015-07-09 07:13
It was a possibility but it's not the problem here, We tried with various browsers and OS and the result was the same.

**Comment by 7170** [comment] 2015-07-09 14:17
Resources are not loaded and js seems to be disabled by a script somewhere in the project...

Some console.log("toto"); doesn't work and print that javascript was deactivated by a script on the page...

**Comment by gmarziou** [comment] 2015-07-09 15:04
It really looks like an ad blocker or a corporate firewall

**Comment by jdubois** [comment] 2015-07-09 20:31
If you can reproduce this issue, then I will have a look at it, but at the moment I have no way to understand or test anything, so I just can't help you -> this is why I'm closing this
It really looks like browser issue, like an ad blocker - we've already had this reported before.

**Closed by jdubois** 2015-07-09 20:31 UTC

**Comment by deepu105** [comment] 2015-07-10 09:06
Just a sanity check, do a grunt build and and see if its still the same. @jdubois after the yeoman upgrade there were some instances when the bower dependency were not updated to index.html by wiredap, i din look deeper into it

**Comment by 7170** [comment] 2015-07-10 15:21
I have succeeded to reproduce it many times by deploying the ".war.original" file (as war) into an installed tomcat and started in prod profile.

On basic jhipster project with postgres, tomcat 7 or 8, with java 7, basic auth and all default answers to generate the project :

I have reproduced on mac os X Yosemite & raspbian & Ubuntu 15.04"

To reproduce, you need load pages several times (navigating and reloading), after some (random) time the front is no more served and "This is your footer" is the only message displayed.

I searched in databases, js, tomcat and nothing appeared to me... In fact, when you have various apps on your tomcat, when one bugs, all are bugged... So I think this is related with shared resources in the same JVM but I cannot tell where, where and how it crashes...

**Comment by deepu105** [comment] 2015-07-11 07:22
I have apps running in tomcat 8 in aws for months and never had this issue

**Comment by 7170** [comment] 2015-07-15 08:18
@deepu105 with which OS ?
I made a mistake with Ubuntu, I can't reproduce on it.

And by using local access (127.0.0.1) I have the same issue with mac OS X, so it's impossible that it is a firewall issue.

**Comment by deepu105** [comment] 2015-07-15 09:52
Im on windows but i dont that makes a difference

**Comment by deepu105** [comment] 2015-07-15 09:53
And the one running in aws is linux

**Comment by 7170** [comment] 2015-07-15 12:34
@deepu105 Resources sharing is not the same on all OSes, this could the reason why on windows you never seen that before.

@jdubois I've identified a bug with the context of the deployed application in prod profile :
 - when you try to load tomcat_url/app/dist from installed tomcat you get the page I mentioned before with "This is your footer"
 - when you get the same url from embedded tomcat (java -jar...) you obtain an empty page
 - when you get this by mvn spring-boot:run you can't access the page (and it's the normal way !)other urls should have issues app/assets and /app/assets/anything..

I don't understand why the context changes when the app is running, it may be from spring context or something shared between apps in the same tomcat.

I can't reproduce it from an embedded tomcat, so if you tried before like this, it may be normal you couldn't identify this issue before

**Comment by deepu105** [comment] 2015-07-15 12:52
@7170 what Jhispter version are you using, we had some issues with deploying to a context in prod profile which was fixed in 2.17 i guess, but that too was not same as what you have. Moreover there are lot of people using this and no one else have this problem regardless of the OS so unless you provide the exact config in .`yo-rc.json` on the project root we wont be able to help.

Also from ur screenshot seems like you are running in prod profile can you try in dev profile and see if it works?

also in prod profile you dont have to access `tomcat_url/app/dist` even if you do it wont work you should set the spring profile to prod and access normal url as in dev

I really dont think this has anything to do with resource sharing

**Comment by 7170** [comment] 2015-07-15 13:09
@deepu105 I'm using 2.17
 my .yo-rc.json : 
{
  "generator-jhipster": {
    "baseName": "jhipster",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "authenticationType": "session", 
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": "no",
    "useCompass": false,
    "buildTool": "maven",
    "frontendBuilder": "grunt",
    "javaVersion": "7",
    "enableTranslation": true,
    "rememberMeKey": "89e6fdbfbfa92302eb5204b84d26f65066b4b5e8"
  }
}

The url I gave you was just to tell you what happens, it's abnormal to get a result with these links, it proves that there is an issue concerning context.
