### ISSUE TITLE
Support BrowserRouter in React

### ISSUE THREAD

**Issue by vivaldus** [jhipster/generator-jhipster#8998] opened 2018-12-30 22:35 UTC
##### **Overview of the feature request**

JHipster generates react projects with hashrouter. Having hashes in URLs is a poor UX. Switching over to BrowserRouter manually is quite involved. It would be much nicer if BrowserRouter could be selected as an option when generating react projects.

##### **Motivation for or Use Case**

I, for one, refuse to build web apps with hashrouting for reasons described. I, for one, will not want to use JHipster with reract projects until either this is supported out of the box, or documentation is given for how to transform to browserrouter.

##### **Related issues or PR**

Related: more generally it would be great if there were more documentation on manipulating a react project (beyond using JDL). I wasn't even able to add a simple react page component at a `/test` route (note without hash #), which was very discouraging as someone who sees JHipster as having a lot of promise.

-   [X] Checking this box is mandatory (this is just to show you read everything)

👉  https://opencollective.com/generator-jhipster/donate -->

**Comment by deepu105** [comment] 2018-12-31 08:05
There was a ticket for this, could you please check if its open, I'm on phone now. This is a good feature but someone has to work on it and no one was interested even with a bounty on it

**Comment by jdubois** [comment] 2018-12-31 10:07
Yes, duplicate of #8462

@vivaldus there's a bug bounty on it, if you are interested.

**Closed by jdubois** 2018-12-31 10:07 UTC
