### ISSUE TITLE
Your request cannot be processed when access gateway

### ISSUE THREAD

**Issue by alialrabi** [jhipster/generator-jhipster#5762] opened 2017-05-14 08:23 UTC
##### **Overview of the issue**

get this error ,Your request cannot be processed when access gateway by localhost:8080

##### **Reproduce the error**
import jhipster registry 2.6 from github and deploy with maven build
import gateway and microservices project and deploy with gradle
eclipse console shows all servers run correctly

##### **JHipster Version(s)**

jhipster 4.4.1
jhipster registry 2.6.0
node v6.10.3
npm 3.10.10
yarn 0.24.4

##### **Browsers and Operating System**
OS  : ubuntu 16.0.4
Browser : last version chrome and firefox

**Comment by gmarziou** [comment] 2017-05-14 11:09
We can't help you if you don't provide details. 
What about logs from server or browser's console?

**Comment by alialrabi** [comment] 2017-05-14 11:57
Do you see I have used compatible versions?


This is server console in eclipse
  
`Working Directory: /home/ali/git/gateway
Gradle User Home: /home/ali/.gradle
Gradle Distribution: Gradle wrapper from target build
Gradle Version: 3.5
Java Home: /usr/lib/jvm/java-8-openjdk-amd64
JVM Arguments: None
Program Arguments: None
Gradle Tasks: bootRun

:cleanResources
:bootBuildInfo
:nodeSetup SKIPPED
:yarnSetup UP-TO-DATE
:webpackBuildDev SKIPPED
:processResources
:compileJava[Fatal Error] shrinkwrap-bom-1.2.3.pom:2:95: XML document structures must start and end within the same entity.
[Fatal Error] shrinkwrap-resolver-bom-2.2.0.pom:2:95: XML document structures must start and end within the same entity.
[Fatal Error] shrinkwrap-descriptors-bom-2.0.0-alpha-8.pom:2:95: XML document structures must start and end within the same entity.
[Fatal Error] shrinkwrap-bom-1.2.3.pom:2:95: XML document structures must start and end within the same entity.
[Fatal Error] shrinkwrap-resolver-bom-2.2.0.pom:2:95: XML document structures must start and end within the same entity.
[Fatal Error] shrinkwrap-descriptors-bom-2.0.0-alpha-8.pom:2:95: XML document structures must start and end within the same entity.
 UP-TO-DATE
:compileScala NO-SOURCE
:classes
:findMainClass
:bootRunIgnoring Class-Path entry lib/snakeyaml-1.13.jar found in/home/ali/.gradle/caches/modules-2/files-2.1/org.liquibase/liquibase-core/3.5.3/f346404c3876c5bd0e07a7e10b7565bdcd35dbab/liquibase-core-3.5.3.jar as /home/ali/.gradle/caches/modules-2/files-2.1/org.liquibase/liquibase-core/3.5.3/f346404c3876c5bd0e07a7e10b7565bdcd35dbab/lib/snakeyaml-1.13.jar does not exist

13:46:47.616 [main] DEBUG org.springframework.boot.devtools.settings.DevToolsSettings - Included patterns for restart : []
13:46:47.621 [main] DEBUG org.springframework.boot.devtools.settings.DevToolsSettings - Excluded patterns for restart : [/spring-boot-starter/target/classes/, /spring-boot-autoconfigure/target/classes/, /spring-boot-starter-[\w-]+/, /spring-boot/target/classes/, /spring-boot-actuator/target/classes/, /spring-boot-devtools/target/classes/]
13:46:47.622 [main] DEBUG org.springframework.boot.devtools.restart.ChangeableUrls - Matching URLs for reloading : [file:/home/ali/git/gateway/build/classes/main/, file:/home/ali/git/gateway/build/resources/main/]
2017-05-14 13:46:51.820 DEBUG 7791 --- [kground-preinit] org.jboss.logging                        : Logging Provider: org.jboss.logging.Slf4jLoggerProvider found via system property

        ██╗ ██╗   ██╗ ████████╗ ███████╗   ██████╗ ████████╗ ████████╗ ███████╗
        ██║ ██║   ██║ ╚══██╔══╝ ██╔═══██╗ ██╔════╝ ╚══██╔══╝ ██╔═════╝ ██╔═══██╗
        ██║ ████████║    ██║    ███████╔╝ ╚█████╗     ██║    ██████╗   ███████╔╝
  ██╗   ██║ ██╔═══██║    ██║    ██╔════╝   ╚═══██╗    ██║    ██╔═══╝   ██╔══██║
  ╚██████╔╝ ██║   ██║ ████████╗ ██║       ██████╔╝    ██║    ████████╗ ██║  ╚██╗
   ╚═════╝  ╚═╝   ╚═╝ ╚═══════╝ ╚═╝       ╚═════╝     ╚═╝    ╚═══════╝ ╚═╝   ╚═╝

:: JHipster 🤓  :: Running Spring Boot 1.5.3.RELEASE ::
:: http://jhipster.github.io ::

2017-05-14 13:46:54.412  INFO 7791 --- [  restartedMain] com.innvo.GatewayApp                     : The following profiles are active: swagger,dev
2017-05-14 13:46:59.021 DEBUG 7791 --- [  restartedMain] com.innvo.config.AsyncConfiguration      : Creating Async Task Executor
2017-05-14 13:47:00.587 DEBUG 7791 --- [  restartedMain] com.innvo.config.MetricsConfiguration    : Registering JVM gauges
2017-05-14 13:47:00.674 DEBUG 7791 --- [  restartedMain] com.innvo.config.MetricsConfiguration    : Monitoring the datasource
2017-05-14 13:47:00.675 DEBUG 7791 --- [  restartedMain] com.innvo.config.MetricsConfiguration    : Initializing Metrics JMX reporting
2017-05-14 13:47:07.131 DEBUG 7791 --- [  restartedMain] com.innvo.config.CacheConfiguration      : Configuring Hazelcast
2017-05-14 13:47:07.266 DEBUG 7791 --- [  restartedMain] com.innvo.config.CacheConfiguration      : Configuring Hazelcast clustering for instanceId: gateway
2017-05-14 13:47:07.266 DEBUG 7791 --- [  restartedMain] com.innvo.config.CacheConfiguration      : Application is running with the "dev" profile, Hazelcast cluster will only work with localhost instances
2017-05-14 13:47:07.547  INFO 7791 --- [  restartedMain] com.netflix.discovery.DiscoveryClient    : Initializing Eureka in region us-east-1
2017-05-14 13:47:07.960  INFO 7791 --- [  restartedMain] c.n.d.provider.DiscoveryJerseyProvider   : Using JSON encoding codec LegacyJacksonJson
2017-05-14 13:47:07.962  INFO 7791 --- [  restartedMain] c.n.d.provider.DiscoveryJerseyProvider   : Using JSON decoding codec LegacyJacksonJson
2017-05-14 13:47:08.178  INFO 7791 --- [  restartedMain] c.n.d.provider.DiscoveryJerseyProvider   : Using XML encoding codec XStreamXml
2017-05-14 13:47:08.180  INFO 7791 --- [  restartedMain] c.n.d.provider.DiscoveryJerseyProvider   : Using XML decoding codec XStreamXml
2017-05-14 13:47:08.640  INFO 7791 --- [  restartedMain] c.n.d.s.r.aws.ConfigClusterResolver      : Resolving eureka endpoints via configuration
2017-05-14 13:47:08.677  INFO 7791 --- [  restartedMain] com.netflix.discovery.DiscoveryClient    : Disable delta property : false
2017-05-14 13:47:08.677  INFO 7791 --- [  restartedMain] com.netflix.discovery.DiscoveryClient    : Single vip registry refresh property : null
2017-05-14 13:47:08.678  INFO 7791 --- [  restartedMain] com.netflix.discovery.DiscoveryClient    : Force full registry fetch : false
2017-05-14 13:47:08.678  INFO 7791 --- [  restartedMain] com.netflix.discovery.DiscoveryClient    : Application is null : false
2017-05-14 13:47:08.678  INFO 7791 --- [  restartedMain] com.netflix.discovery.DiscoveryClient    : Registered Applications size is zero : true
2017-05-14 13:47:08.678  INFO 7791 --- [  restartedMain] com.netflix.discovery.DiscoveryClient    : Application version is -1: true
2017-05-14 13:47:08.678  INFO 7791 --- [  restartedMain] com.netflix.discovery.DiscoveryClient    : Getting all instance registry info from the eureka server
2017-05-14 13:47:10.265  INFO 7791 --- [  restartedMain] com.netflix.discovery.DiscoveryClient    : The response status is 200
2017-05-14 13:47:10.270  INFO 7791 --- [  restartedMain] com.netflix.discovery.DiscoveryClient    : Starting heartbeat executor: renew interval is: 5
2017-05-14 13:47:10.285  INFO 7791 --- [  restartedMain] c.n.discovery.InstanceInfoReplicator     : InstanceInfoReplicator onDemand update allowed rate per min is 12
2017-05-14 13:47:10.292  INFO 7791 --- [  restartedMain] com.netflix.discovery.DiscoveryClient    : Discovery Client initialized at timestamp 1494762430292 with initial instances count: 0
2017-05-14 13:47:10.625  INFO 7791 --- [  restartedMain] c.h.instance.DefaultAddressPicker        : [LOCAL] [dev] [3.7.7] Picked [127.0.0.1]:13800, using socket ServerSocket[addr=/0:0:0:0:0:0:0:0,localport=13800], bind any local is true
2017-05-14 13:47:10.651  INFO 7791 --- [  restartedMain] com.hazelcast.system                     : [127.0.0.1]:13800 [dev] [3.7.7] Hazelcast 3.7.7 (20170404 - e3c56ea) starting at [127.0.0.1]:13800
2017-05-14 13:47:10.652  INFO 7791 --- [  restartedMain] com.hazelcast.system                     : [127.0.0.1]:13800 [dev] [3.7.7] Copyright (c) 2008-2016, Hazelcast, Inc. All Rights Reserved.
2017-05-14 13:47:10.652  INFO 7791 --- [  restartedMain] com.hazelcast.system                     : [127.0.0.1]:13800 [dev] [3.7.7] Configured Hazelcast Serialization version : 1
2017-05-14 13:47:10.969  INFO 7791 --- [  restartedMain] c.h.s.i.o.impl.BackpressureRegulator     : [127.0.0.1]:13800 [dev] [3.7.7] Backpressure is disabled
2017-05-14 13:47:11.443 DEBUG 7791 --- [  restartedMain] c.h.internal.cluster.ClusterService      : [127.0.0.1]:13800 [dev] [3.7.7] Updating members [Member [127.0.0.1]:13800 - d6a995c9-f7f4-4eb0-bc8c-94dff527d245 this]
2017-05-14 13:47:11.443 DEBUG 7791 --- [  restartedMain] c.h.i.p.InternalPartitionService         : [127.0.0.1]:13800 [dev] [3.7.7] Adding Member [127.0.0.1]:13800 - d6a995c9-f7f4-4eb0-bc8c-94dff527d245 this
2017-05-14 13:47:11.460  INFO 7791 --- [  restartedMain] com.hazelcast.instance.Node              : [127.0.0.1]:13800 [dev] [3.7.7] Creating TcpIpJoiner
2017-05-14 13:47:11.629  INFO 7791 --- [  restartedMain] c.h.s.i.o.impl.OperationExecutorImpl     : [127.0.0.1]:13800 [dev] [3.7.7] Starting 4 partition threads
2017-05-14 13:47:11.632  INFO 7791 --- [  restartedMain] c.h.s.i.o.impl.OperationExecutorImpl     : [127.0.0.1]:13800 [dev] [3.7.7] Starting 3 generic threads (1 dedicated for priority tasks)
2017-05-14 13:47:11.641  INFO 7791 --- [  restartedMain] com.hazelcast.core.LifecycleService      : [127.0.0.1]:13800 [dev] [3.7.7] [127.0.0.1]:13800 is STARTING
2017-05-14 13:47:11.641 DEBUG 7791 --- [  restartedMain] c.h.i.p.InternalPartitionService         : [127.0.0.1]:13800 [dev] [3.7.7] Adding Member [127.0.0.1]:13800 - d6a995c9-f7f4-4eb0-bc8c-94dff527d245 this
2017-05-14 13:47:11.643  INFO 7791 --- [  restartedMain] c.h.n.t.n.NonBlockingIOThreadingModel    : [127.0.0.1]:13800 [dev] [3.7.7] TcpIpConnectionManager configured with Non Blocking IO-threading model: 3 input threads and 3 output threads
2017-05-14 13:47:11.644 DEBUG 7791 --- [  restartedMain] c.h.n.t.n.NonBlockingIOThreadingModel    : [127.0.0.1]:13800 [dev] [3.7.7] IO threads selector mode is SELECT
2017-05-14 13:47:11.658 DEBUG 7791 --- [  restartedMain] com.hazelcast.cluster.impl.TcpIpJoiner   : [127.0.0.1]:13800 [dev] [3.7.7] This node will assume master role since no possible member where connected to.
2017-05-14 13:47:11.659 DEBUG 7791 --- [  restartedMain] com.hazelcast.cluster.impl.TcpIpJoiner   : [127.0.0.1]:13800 [dev] [3.7.7] PostJoin master: [127.0.0.1]:13800, isMaster: true
2017-05-14 13:47:11.659  INFO 7791 --- [  restartedMain] com.hazelcast.cluster.impl.TcpIpJoiner   : [127.0.0.1]:13800 [dev] [3.7.7] 


Members [1] {
	Member [127.0.0.1]:13800 - d6a995c9-f7f4-4eb0-bc8c-94dff527d245 this
}

2017-05-14 13:47:11.691  INFO 7791 --- [  restartedMain] com.hazelcast.core.LifecycleService      : [127.0.0.1]:13800 [dev] [3.7.7] [127.0.0.1]:13800 is STARTED
2017-05-14 13:47:13.150 DEBUG 7791 --- [  restartedMain] com.innvo.config.WebConfigurer           : Registering CORS filter
2017-05-14 13:47:13.397  WARN 7791 --- [  restartedMain] c.n.c.sources.URLConfigurationSource     : No URLs will be polled as dynamic configuration sources.
2017-05-14 13:47:13.922  INFO 7791 --- [  restartedMain] com.innvo.config.WebConfigurer           : Web application configuration, using profiles: swagger
2017-05-14 13:47:13.924 DEBUG 7791 --- [  restartedMain] com.innvo.config.WebConfigurer           : Initializing Metrics registries
2017-05-14 13:47:13.928 DEBUG 7791 --- [  restartedMain] com.innvo.config.WebConfigurer           : Registering Metrics Filter
2017-05-14 13:47:13.929 DEBUG 7791 --- [  restartedMain] com.innvo.config.WebConfigurer           : Registering Metrics Servlet
2017-05-14 13:47:13.940  INFO 7791 --- [  restartedMain] com.innvo.config.WebConfigurer           : Web application fully configured
2017-05-14 13:47:14.479 DEBUG 7791 --- [  restartedMain] com.innvo.config.DatabaseConfiguration   : Configuring Liquibase
2017-05-14 13:47:14.494  WARN 7791 --- [eway-Executor-1] i.g.j.c.liquibase.AsyncSpringLiquibase   : Starting Liquibase asynchronously, your database might not be ready at startup!
2017-05-14 13:47:15.337  INFO 7791 --- [tbeatExecutor-0] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_GATEWAY/gateway:29ec804b7ad443e2cafe7e9cc4f5c989 - Re-registering apps/GATEWAY
2017-05-14 13:47:15.338  INFO 7791 --- [tbeatExecutor-0] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_GATEWAY/gateway:29ec804b7ad443e2cafe7e9cc4f5c989: registering service...
2017-05-14 13:47:15.555  INFO 7791 --- [tbeatExecutor-0] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_GATEWAY/gateway:29ec804b7ad443e2cafe7e9cc4f5c989 - registration status: 204
2017-05-14 13:47:18.440 DEBUG 7791 --- [eway-Executor-1] i.g.j.c.liquibase.AsyncSpringLiquibase   : Liquibase has updated your database in 3941 ms
2017-05-14 13:47:18.538  INFO 7791 --- [  restartedMain] c.h.h.HazelcastCacheRegionFactory        : Starting up HazelcastCacheRegionFactory
2017-05-14 13:47:18.543  INFO 7791 --- [  restartedMain] c.h.h.instance.HazelcastInstanceFactory  : Using existing HazelcastInstance [gateway].
2017-05-14 13:47:20.274  INFO 7791 --- [freshExecutor-0] com.netflix.discovery.DiscoveryClient    : Disable delta property : false
2017-05-14 13:47:20.275  INFO 7791 --- [freshExecutor-0] com.netflix.discovery.DiscoveryClient    : Single vip registry refresh property : null
2017-05-14 13:47:20.276  INFO 7791 --- [freshExecutor-0] com.netflix.discovery.DiscoveryClient    : Force full registry fetch : false
2017-05-14 13:47:20.284  INFO 7791 --- [freshExecutor-0] com.netflix.discovery.DiscoveryClient    : Application is null : false
2017-05-14 13:47:20.289  INFO 7791 --- [freshExecutor-0] com.netflix.discovery.DiscoveryClient    : Registered Applications size is zero : true
2017-05-14 13:47:20.289  INFO 7791 --- [freshExecutor-0] com.netflix.discovery.DiscoveryClient    : Application version is -1: false
2017-05-14 13:47:20.289  INFO 7791 --- [freshExecutor-0] com.netflix.discovery.DiscoveryClient    : Getting all instance registry info from the eureka server
2017-05-14 13:47:20.307  INFO 7791 --- [freshExecutor-0] com.netflix.discovery.DiscoveryClient    : The response status is 200
2017-05-14 13:47:25.982 DEBUG 7791 --- [  restartedMain] com.innvo.config.CacheConfiguration      : Starting HazelcastCacheManager
2017-05-14 13:47:28.547 DEBUG 7791 --- [  restartedMain] i.g.j.c.apidoc.SwaggerConfiguration      : Starting Swagger
2017-05-14 13:47:28.564 DEBUG 7791 --- [  restartedMain] i.g.j.c.apidoc.SwaggerConfiguration      : Started Swagger in 16 ms
2017-05-14 13:47:29.050 DEBUG 7791 --- [  restartedMain] c.datastax.driver.core.SystemProperties  : com.datastax.driver.NEW_NODE_DELAY_SECONDS is undefined, using default value 1
2017-05-14 13:47:29.069 DEBUG 7791 --- [  restartedMain] c.datastax.driver.core.SystemProperties  : com.datastax.driver.NOTIF_LOCK_TIMEOUT_SECONDS is undefined, using default value 60
2017-05-14 13:47:29.124 DEBUG 7791 --- [  restartedMain] c.datastax.driver.core.SystemProperties  : com.datastax.driver.USE_NATIVE_CLOCK is undefined, using default value true
2017-05-14 13:47:29.556  INFO 7791 --- [  restartedMain] com.datastax.driver.core.ClockFactory    : Using native clock to generate timestamps.
2017-05-14 13:47:29.578 DEBUG 7791 --- [  restartedMain] c.datastax.driver.core.SystemProperties  : com.datastax.driver.NON_BLOCKING_EXECUTOR_SIZE is undefined, using default value 4
2017-05-14 13:47:31.085  WARN 7791 --- [  restartedMain] c.n.c.sources.URLConfigurationSource     : No URLs will be polled as dynamic configuration sources.
2017-05-14 13:47:31.448  WARN 7791 --- [  restartedMain] o.s.j.e.a.AnnotationMBeanExporter        : Bean with key 'zuulEndpoint' has been registered as an MBean but has no exposed attributes or operations
2017-05-14 13:47:32.204  INFO 7791 --- [  restartedMain] com.netflix.discovery.DiscoveryClient    : Saw local status change event StatusChangeEvent [timestamp=1494762452203, current=UP, previous=STARTING]
2017-05-14 13:47:32.298  INFO 7791 --- [freshExecutor-0] com.netflix.discovery.DiscoveryClient    : Disable delta property : false
2017-05-14 13:47:32.298  INFO 7791 --- [freshExecutor-0] com.netflix.discovery.DiscoveryClient    : Single vip registry refresh property : null
2017-05-14 13:47:32.298  INFO 7791 --- [freshExecutor-0] com.netflix.discovery.DiscoveryClient    : Force full registry fetch : false
2017-05-14 13:47:32.298  INFO 7791 --- [freshExecutor-0] com.netflix.discovery.DiscoveryClient    : Application is null : false
2017-05-14 13:47:32.298  INFO 7791 --- [freshExecutor-0] com.netflix.discovery.DiscoveryClient    : Registered Applications size is zero : true
2017-05-14 13:47:32.298  INFO 7791 --- [freshExecutor-0] com.netflix.discovery.DiscoveryClient    : Application version is -1: false
2017-05-14 13:47:32.298  INFO 7791 --- [freshExecutor-0] com.netflix.discovery.DiscoveryClient    : Getting all instance registry info from the eureka server
2017-05-14 13:47:32.353  INFO 7791 --- [freshExecutor-0] com.netflix.discovery.DiscoveryClient    : The response status is 200
2017-05-14 13:47:32.679  INFO 7791 --- [nfoReplicator-0] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_GATEWAY/gateway:29ec804b7ad443e2cafe7e9cc4f5c989: registering service...
2017-05-14 13:47:32.696  INFO 7791 --- [nfoReplicator-0] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_GATEWAY/gateway:29ec804b7ad443e2cafe7e9cc4f5c989 - registration status: 204
2017-05-14 13:47:33.838  INFO 7791 --- [  restartedMain] com.innvo.GatewayApp                     : Started GatewayApp in 46.184 seconds (JVM running for 47.439)
2017-05-14 13:47:33.847  INFO 7791 --- [  restartedMain] com.innvo.GatewayApp                     : 
----------------------------------------------------------
	Application 'gateway' is running! Access URLs:
	Local: 		http://localhost:8099
	External: 	http://127.0.1.1:8099
	Profile(s): 	[swagger, dev]
----------------------------------------------------------
2017-05-14 13:47:33.848  INFO 7791 --- [  restartedMain] com.innvo.GatewayApp                     : 
----------------------------------------------------------
	Config Server: 	Connected to the JHipster Registry config server!
----------------------------------------------------------
2017-05-14 13:47:41.670  WARN 7791 --- [  XNIO-2 task-1] o.s.c.n.zuul.web.ZuulHandlerMapping      : No routes found from RouteLocator
2017-05-14 13:47:43.329  WARN 7791 --- [  XNIO-2 task-2] o.s.c.n.zuul.web.ZuulHandlerMapping      : No routes found from RouteLocator
2017-05-14 13:48:07.942  WARN 7791 --- [  XNIO-2 task-3] o.s.c.n.zuul.web.ZuulHandlerMapping      : No routes found from RouteLocator
2017-05-14 13:48:15.800  WARN 7791 --- [  XNIO-2 task-5] o.s.c.n.zuul.web.ZuulHandlerMapping      : No routes found from RouteLocator
2017-05-14 13:49:13.306  WARN 7791 --- [  XNIO-2 task-6] o.s.c.n.zuul.web.ZuulHandlerMapping      : No routes found from RouteLocator
2017-05-14 13:49:23.882  WARN 7791 --- [  XNIO-2 task-7] o.s.c.n.zuul.web.ZuulHandlerMapping      : No routes found from RouteLocator
2017-05-14 13:50:20.433  WARN 7791 --- [ XNIO-2 task-10] o.s.c.n.zuul.web.ZuulHandlerMapping      : No routes found from RouteLocator
2017-05-14 13:50:22.895  WARN 7791 --- [ XNIO-2 task-11] o.s.c.n.zuul.web.ZuulHandlerMapping      : No routes found from RouteLocator
`

   Browser screenshot with console and network 
 
![screenshot from 2017-05-14 13-49-59](https://cloud.githubusercontent.com/assets/7685208/26033446/dfcacc88-38ac-11e7-8133-e673601b543a.png)
![screenshot from 2017-05-14 13-50-48](https://cloud.githubusercontent.com/assets/7685208/26033448/e620b5a2-38ac-11e7-835b-568f2cc7531f.png)

**Comment by deepu105** [comment] 2017-05-14 12:16
Did you run yarn start or yarn build on the apps?

**Comment by alialrabi** [comment] 2017-05-14 12:25
No ,I have never run jhipster with yarn..

**Comment by alialrabi** [comment] 2017-05-14 20:18
type yo jhipster  fix the problem,Do you have any idea what was the problem?

**Comment by jdubois** [comment] 2017-05-15 08:58
The problem is that you needed to run Yarn, have a look at the documentation.

Anyway, I'm closing this as this is not following the guidelines

**Comment by jdubois** [comment] 2017-05-15 08:58
This ticket has been closed as the guidelines are not followed.

Tickets must follow our [Guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#submitting-an-issue), as mentioned in:

1. our [Readme file on the front page of the project](https://github.com/jhipster/generator-jhipster/blob/master/README.md), 
2. the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) and
3. our [Help page](http://jhipster.github.io/help/)

We have also created a template on the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) to help you follow those guidelines.

**Closed by jdubois** 2017-05-15 08:58 UTC

**Comment by oraclemohammadi** [comment] 2018-01-18 17:49
I have the same issue after cloning "JHipster Registry 3.2.4" , running yarn install before running ./mvnw fixed the issue

**Comment by gmarziou** [comment] 2018-01-18 18:12
Yes this is what is explained in the README.md
