### ISSUE TITLE
gateway package is missing with latest jhispster generator 

### ISSUE THREAD

**Issue by kdhanrajgoud** [jhipster/generator-jhipster#23276] opened 2023-08-24 05:12 UTC
##### **Overview of the issue**

Gateway application does not include gateway package ( Rate limiting, access control, responserewriting) 

##### **Motivation for or Use Case**

Im trying to upgrade Jhipster from 6.X to 8.X which uses latest Spring boot.

##### **Reproduce the error**

Create a gateway application from https://start.jhipster.tech/generate-application, the generation application is missing gateway package which has functionalities like Rate Limiting on Ip address, Access control, Swagger Response writing.

##### **JHipster Version(s)**

8.0.0-beta.2

**Comment by mshima** [comment] 2023-08-24 14:08
- Rate limit is not implemented at jhipster. Probably never implemented at reactive gateway.
- I don’t know what you mean about access control.
- Swagger response writing was replaced with client side lookup.

It’s not a bug. If you want to open a feature request, please open specific feature request.

**Comment by mshima** [comment] 2023-09-01 17:29
There is no bug here, if there is interest in some feature request please open new issues. Closing.

**Closed by mshima** 2023-09-01 17:29 UTC
Labels: area: triage, theme: undefined
