### ISSUE TITLE
Searching with elasticsearch does not work for entities that use pagination

### ISSUE THREAD

**Issue by nevadyzm** [jhipster/generator-jhipster#11111] opened 2020-01-13 12:20 UTC
##### **Overview of the issue**

Filtering using elasticsearch does not work correctly for entities with pagination enabled:
- for paginate with pagination nothing happens when you try to search 
- for paginate with infinite-scroll the search executes but does not find any entities

##### **Motivation for or Use Case**

According to the documentation this functionality should work out-of-the-box:
https://www.jhipster.tech/using-elasticsearch/

##### **Reproduce the error**
1. Generate new jhipster project using configuration pasted below.
2. Run jhipster import-jdl for the attached file
3. Create empty database on your local PostgreSQL instance.
4. Update application-dev.yml - provide name of the database, username and password
5. Run the application.
6. Log in to the application.
7. Create some entities of each type.
8. Try searching for each entity type.

##### **JHipster configuration**
INFO! Using JHipster version installed locally in current project's node_modules
INFO! Executing jhipster:info
INFO! Options: from-cli: true
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
jhpstertest@0.0.1-SNAPSHOT C:\git-repo\jhpstertest
`-- generator-jhipster@6.6.0

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.my.test",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "6.6.0",
    "applicationType": "monolith",
    "baseName": "jhpstertest",
    "packageName": "com.my.test",
    "packageFolder": "com/my/test",
    "serverPort": "8080",
[jhipster-jdl.txt](https://github.com/jhipster/generator-jhipster/files/4053459/jhipster-jdl.txt)

    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": ""
    "embeddableLaunchScript": false,
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "react",
    "clientTheme": "cerulean",
    "clientThemeVariant": "primary",
    "creationTimestamp": 1578908163109,
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": ["en", "pl"],
    "blueprints": []
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity EntityWithPaging {
  name String
}
entity EntityWithScroll {
  name String
}
entity EntityWithNeither {
  name String
}
paginate EntityWithPaging with pagination
paginate EntityWithScroll with infinite-scroll
service EntityWithPaging, EntityWithScroll, EntityWithNeither with serviceImpl
filter EntityWithPaging, EntityWithScroll, EntityWithNeither

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_231"
Java(TM) SE Runtime Environment (build 1.8.0_231-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.231-b11, mixed mode)

node: v12.14.0

npm: 6.13.4

##### **Browsers and Operating System**

Microsoft Windows 10 Pro Version 1607

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by SudharakaP** [comment] 2020-02-27 18:27
This has been reproduced and tracked at #11321. I am currently trying to find the root cause and fix it. Since this is already tracked I am closing this issue. 😄

**Closed by SudharakaP** 2020-02-27 18:27 UTC
Labels: area: duplicate, theme: elasticsearch
