### ISSUE TITLE
app.constants.js was not created with OAuth2 selected

### ISSUE THREAD

**Issue by tom-010** [jhipster/generator-jhipster#2896] opened 2016-02-16 14:11 UTC
I've created an project with OAuth2 selected. The **app.constant.js** was not generated. This is not the case when I create the Project with HTTP Session Authentication (stateful, default Spring Security mechanism) as authentication type.

Because the app.constants.js ist not defined, the webapp shows only "This is your footer" and as log-output I get:

```
2016-02-16 15:00:52.282 DEBUG 7552 --- [nio-8080-exec-9] c.skytala.job.aop.logging.LoggingAspect  : Enter: org.springframework.boot.actuate.audit.AuditEventRepository.add() with argument[s] = [AuditEvent [timestamp=Tue Feb 16 15:00:52 CET 2016, principal=anonymousUser, type=AUTHORIZATION_FAILURE, data={type=org.springframework.security.access.AccessDeniedException, message=Access is denied}]]
2016-02-16 15:00:52.282 DEBUG 7552 --- [nio-8080-exec-9] c.skytala.job.aop.logging.LoggingAspect  : Exit: org.springframework.boot.actuate.audit.AuditEventRepository.add() with result = null
2016-02-16 15:00:52.283 DEBUG 7552 --- [nio-8080-exec-9] c.s.j.s.Http401UnauthorizedEntryPoint    : Pre-authenticated entry point called. Rejecting access
2016-02-16 15:02:08.791 DEBUG 7552 --- [nio-8080-exec-4] c.skytala.job.aop.logging.LoggingAspect  : Enter: org.springframework.boot.actuate.audit.AuditEventRepository.add() with argument[s] = [AuditEvent [timestamp=Tue Feb 16 15:02:08 CET 2016, principal=anonymousUser, type=AUTHORIZATION_FAILURE, data={type=org.springframework.security.access.AccessDeniedException, message=Access is denied}]]
```

The solution is to create the app.constants.js manually:
```javascript
"use strict";
// DO NOT EDIT THIS FILE, EDIT THE GRUNT TASK NGCONSTANT SETTINGS INSTEAD WHICH GENERATES THIS FILE
angular.module('jobApp')

.constant('ENV', 'dev')

.constant('VERSION', '0.0.1-SNAPSHOT')

;
```

Tom

**Comment by gmarziou** [comment] 2016-02-16 14:14
Which version?
The app.constant.js is generated by the frontend build: grunt or gulp.
Did you run it?

**Comment by gmarziou** [comment] 2016-02-16 14:17
Please provide your .yo-rc.json file

**Comment by tom-010** [comment] 2016-02-16 14:18
I have coosen grunt. The grunt version(s) are:
grunt-cli v0.1.13
grunt v0.4.5

After jhipster installation i've ran grunt wiredep

.yo-rc.json
```
{
  "generator-jhipster": {
    "baseName": "Job",
    "packageName": "com.skytala.job",
    "packageFolder": "com/skytala/job",
    "authenticationType": "xauth",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": "no",
    "useSass": false,
    "buildTool": "gradle",
    "frontendBuilder": "grunt",
    "enableTranslation": true,
    "enableSocialSignIn": false,
    "rememberMeKey": "f3b5e6861950ddb94666235884073c5b83a55f88",
    "testFrameworks": [
      "gatling"
    ]
  }
}
```

**Comment by gmarziou** [comment] 2016-02-16 21:08
I mea

**Comment by gmarziou** [comment] 2016-02-16 21:50
`grunt wiredep` could not help here, you  should have run `grunt serve` .

I have successfully tested your config against JHipster 2.27 and current master (JHipster 3.0 to come).

So I don't know what went wrong for you but I can't reproduce it, so I'm closing the issue.

BTW, you may want to switch to gulp, as we will drop grunt in 3.0

**Closed by gmarziou** 2016-02-16 21:50 UTC
