### ISSUE TITLE
Ehcache warning for User.authorities caching

### ISSUE THREAD

**Issue by pkraeutli** [jhipster/generator-jhipster#1090] opened 2015-02-04 15:24 UTC
The @Cache annotation in 

https://github.com/jhipster/generator-jhipster/blob/master/app/templates/src/main/java/package/domain/_User.java#L79 

causes Ehcache to print this warning:

```
[WARN ] n.s.e.p.s.ObjectGraphWalker - The configured limit of 1'000 object references was reached while attempting to calculate the size of the object graph. Severe performance degradation could occur if the sizing operation continues. This can be avoided by setting the CacheManger or Cache <sizeOfPolicy> elements maxDepthExceededBehavior to "abort" or adding stop points with @IgnoreSizeOf annotations. If performance degradation is NOT an issue at the configured limit, raise the limit value using the CacheManager or Cache <sizeOfPolicy> elements maxDepth attribute. For more information, see the Ehcache configuration documentation.
```

Has anybody an idea why this happens? The Authority entity only has id and name and I have only two entries (ROLE_ADMIN and ROLE_USER).

**Comment by jdubois** [comment] 2015-02-04 15:31
This is because you have other objects in the cache, and in total you have more than 1,000 objects.

It might indeed be a bit small, but that's just for development. Have a look at the ehcache config file -> can you keep us updated on this? Maybe the limit should be be upper.

**Comment by pkraeutli** [comment] 2015-02-04 15:38
The strange thing is that the message disappears when I remove the @Cache annotation from User.authorities. When I remove it only form User or Authority, for instance, the message remains.

My whole database has only ~100 entries so I wonder where the 1000 objects are coming from. Maybe some circular graph thing?

**Comment by jdubois** [comment] 2015-02-04 15:42
you need to count the number of authorities per user, the number of users, etc... Have a look at the JMX console, you can see how many objects are stored.

This is just for dev, in prod your defaults should be higher.

I'm closing this as this is not a bug.

**Closed by jdubois** 2015-02-04 15:42 UTC

**Comment by vitornobrega** [comment] 2016-01-29 00:06
I am getting the same warning and my service is very slow. Where i can increase the limitation of 1000 objects?

**Comment by lifei1102** [comment] 2017-05-15 13:11
i am getting this problem too,i have changed the maxDepth = 1000 and maxDepthExceededBehavior = "abort",it seems no this warning,but my service is still very slow,please tell me how to make my service normal
PS: i found only some service is slow,and the other is normal

**Comment by lifei1102** [comment] 2017-05-15 13:11
@jdubois @vitornobrega

**Comment by jdubois** [comment] 2017-05-15 13:18
I'm sorry, why are you spamming me @lifei1102 ? This doesn't look like a bug on our side, and even it is was:

- you need to follow the guidelines and give your full configuration
- don't spam me. I have a daily work, I can't help people in real time like that, and we have official channels to help you as best as we can
