### ISSUE TITLE
Error using entity names that match SQL reserved words

### ISSUE THREAD

**Issue by rblazquez** [jhipster/generator-jhipster#1335] opened 2015-04-03 12:40 UTC
Note this simple example ... following documentation on Entity relationships i created a "client" who has a one-to-many relationship to an "order"

Passing tests just after generator get error:

Caused by: java.lang.IllegalArgumentException: org.hibernate.hql.internal.ast.QuerySyntaxException: unexpected token: order near line 1, column 82 [select order from com.blacarapps.hipsterspike.domain.Order order left join fetch order.items where order.id =:id]

**Comment by jdubois** [comment] 2015-04-03 12:43
Duplicate of #1278

**Closed by jdubois** 2015-04-03 12:43 UTC

**Comment by rblazquez** [comment] 2015-04-03 13:03
I was looking at that issue and decided to create a new one instead since it is not the same case.

In that issue the problem is that there are fields in the entity that has reserved words. In this case the problem is not fields named as reserved words but entity name as reserved word.

I supposed that the actions to solve those problems will be different so there may be a specific issue to this particular case.

If this will be also covered by #1278  then, maybe i should put a comment there?

**Comment by jdubois** [comment] 2015-04-03 13:06
Yes, we are going to make a list of all reserved words (also in Java....), and add a validation rule forbidding all of them, for entity names and fields.
It's annoying, I know, but that's the only way to be sure we don't have this kind of issue.

**Comment by rblazquez** [comment] 2015-04-03 13:48
Ok, thanks.

**Comment by ricardojlrufino** [comment] 2016-12-03 23:11
On database, an alternative to allow would be to enable the "quote" of the reserved words

spring.jpa.properties.hibernate.globally_quoted_identifiers=true
