### ISSUE TITLE
foreignKeyConstraint naming logic produces duplicate names

### ISSUE THREAD

**Issue by systemsplanet** [jhipster/generator-jhipster#3839] opened 2016-07-13 22:16 UTC
##### **Overview of the issue**

Thie code that generates constraint names is brittle. 
For example, add two tables TrackerCategories and TrackerIssues.
The first three chars are the same for both tables and the constraint names will be the same

 generator-jhipster\generators\entity\templates\src\main\resources\config\liquibase\changelog\_added_entity_constraints.xml
     if(prodDatabaseType === 'oracle' && constraintName.length > 30) {
                    constraintName = 'fk_' + getTableName(name.toLowerCase().substri**ng(0, 3))** + '_' +
                        getTableName(relationshipName.toLowerCase().substring**(0, 3))** + '_id';
                        

##### **Motivation for or Use Case** 

    Build Error was something like....
      liquibase.exception.DatabaseException: Constraint "FK_REL_REL_ID" already exists; SQL statement:
        ALTER TABLE PUBLIC.ReleaseNoteImport  ADD CONSTRAINT fk_rel_rel_id FOREIGN KEY (release_note_import_id) REFERENCES PUBLIC.release_note_issue (id) [90045-191] [Failed SQL: ALTER TABLE PUBLIC.release_note_import ADD CONSTRAINT fk_rel_rel_id FOREIGN KEY (release_note_issue) REFERENCES PUBLIC.release_note_import (id)]
##### **JHipster Version(s)** 

3.4.2
##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 
{
  "generator-jhipster": {
    "jhipsterVersion": "3.4.2",
    "baseName": "ASDLC",
    "packageName": "com.theice.asdlc",
    "packageFolder": "com/theice/asdlc",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "no",
    "clusteredHttpSession": "no",
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "oracle",
    "searchEngine": "no",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "rememberMeKey": "",
    "useSass": true,
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "zh-cn",
      "hi",
      "pt-br"
    ]
  } 

Note you can test Oracle SQL using H2...
  jdbc:h2:file:./.h2/asdlc;AUTO_SERVER=TRUE;DB_CLOSE_DELAY=-1;**MODE=Oracle;**

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory** 
It was close to this...

entity ReleaseNoteImport {
  jiraProject String required,
  content ImageBlob
}
entity ReleaseNoteIssue {
  jiraId String required
}

relationship OneToMany {
  ReleaseNoteImport{releaseNoteIssue} to  ReleaseNoteIssue{releaseNoteImport}
}

I believe the foreign keys will have the same names for both tables because the both start with REL

##### **Browsers and Operating System** 

Win7
##### **Reproduce the error** 
 jhipster-uml 
mvn
##### **Related issues** 

n

##### **Suggest a Fix** 

I would just genereate a name
    FK_[randomnumber]

update a message property for easy translation to a log message
dbError["FK_xxxxxx"+'log']=Entity 0000 (Table AAA) Property 1111 (Column BBB)  Refrences Entity 2222 (Table CCC) Property 3333 (Column DDD).

**Comment by deepu105** [comment] 2016-07-14 01:29
You are welcome to PR if you have a clean solution for this

Thanks & regards,
Deepu

**Comment by HemanthD** [comment] 2016-07-14 10:44
You are right, I had made a similar observation. It is not possible to guarantee uniqueness if we are picking the first few char of the entitiy names and if the entity name differs only towards the end. I did not include it in my earlier PR as this might have needed some discussion based on the naming conventions.

My suggestion is to use unique prefix as fk1_ and fk2_ instead of a common fk_. This would be simpler than using a random no. We will have only 2 FK for the join table and this should suffice.

**Comment by jdubois** [comment] 2016-07-20 09:46
This is because of that annoying char limitation in Oracle :-(

2 solutions for me:

- Use indeed a unique number, but then we'll need to store it somewhere which can be annoying (in `.yo-rc.json` probably), if people create some other tables without using JHipster then this number would be a bit strange
- In RoR they name of the association with the suffix `_id` added (and this could be overriden with a `foreign_key` option). We could do the same, but we would then need to limit the associations names to 27 (only for Oracle, maybe??), and be sure people don't use the same association name twice.

**Comment by jdubois** [comment] 2016-07-20 10:10
Isn't this a duplicate from #3809 ?

**Comment by jdubois** [comment] 2016-07-20 10:11
This is a duplicate from #3809 but as this ticket is better, I'm keeping this one and closing the other one.

**Comment by deepu105** [comment] 2016-07-20 14:02
It could happen for mySql as well but it has a 65 char limit I guess

Thanks & regards,
Deepu

**Comment by jdubois** [comment] 2016-08-09 13:01
As I don't have Oracle I can't test this, but looking at the code:

- We have a lot of duplicates for this part
- Some cases look wrong to me, I need to check
- Anyway, we have a lot of spaces left here, for example when we do `getTableName(name.substring(0, 5)) + '_' + getTableName(relationshipName.substring(0, 5)) + '_MAPPING'`this takes 19 characters -> we could do instead `getTableName(name.substring(0, 15)) + '_' + getTableName(relationshipName.substring(0, 10)) + '_MAP'`. Your issue could still occur, but that would be in more specific cases, and that could be OK.

**Comment by jdubois** [comment] 2016-08-09 13:17
Sorry, I was speaking of joint table names, but that's the same issue as we FK. JHipster generates them, but there are limitations both with Oracle and MySQL.

I think there is an even easier idea: let's use the "normal" generated name (both for joint tables and FK), and then do a substring. It should be big enough to be unique for most people.

Only people who would have issues are people with 15+ characters in their table names on Oracle, but: they would need to have 2 tables beginning with the same name, joining the same first table. That's a pretty weird combination.

@deepu105 as you coded this, I hope that's fine for you.

**Comment by jdubois** [comment] 2016-08-09 13:42
OK so I've now done substrings of the "normal" joint table name and FK name. That allows us to have the longest possible name allowed by the underlying database.

The only issue would be for Oracle, anyway, but I'd rather have a consistent naming for all JHipster applications, than to have something specific (like a random String) for one database. I don't think that's such a big issue, as 30 characters is still long enough, and most people working with JHipster don't use Oracle anyway (and instead of sending their $$$ to Oracle, they should better help JHipster!).

Last solution, which I haven't do at the moment, is to have the FK as an option, which would be stored in our .json configuration file. I don't want to have too options here, as this adds more maintenance burden, if we don't need to.

**Comment by jdubois** [comment] 2016-08-09 13:42
@deepu105 as you coded this part, can you have a look? And of course I can't test this, so if @systemsplanet you can this, it would be most welcome

**Comment by jdubois** [comment] 2016-08-09 20:44
I'm reopening this as @deepu105 has added some comments & code

- @deepu105 made a function to generate those codes: of course that's much better, so let's do it
- For the "join table" name we still have some discussion. I've just had a look at the JPA spec 2.1, and it says `The concatenated names of the two associated primary entity tables (owning side first), separated by an underscore.`, which is what we currently try to do. So for me, according to our [Policy 1](https://jhipster.github.io/policies/), we should try to use that as much as possible. With my proposal, we only have the issue with Oracle, for people with very long table names (and do remember that Oracle is a big part of the JPA spec! That's insane, right...). In that case, the end of the name gets cut off, which should be OK most of the time -> you would need 2 associations of the same table with 2 different tables which start with the same name. That sounds OK to me, but we should discuss this here @deepu105

**Comment by systemsplanet** [comment] 2016-08-10 06:17
I think it's a mistake to partially fix this. The ability to generate valid unique names is a fundamental requirement for solid code generation.

I would go with the limitations of the smallest common denominator.  That way it's easy to generate a site for MySql that can be switch to Oracle and it just works.

At least then you can say it just works.
An intelligent naming solution that is dynamic and changes as the underlying db changes is  probably too much work and will be too complex.

**Comment by jdubois** [comment] 2016-08-10 07:53
Good point @systemsplanet but then I'm worried we don't follow the JPA spec, just because there is an issue with Oracle.

I'm not too worried about being able to switch databases: nobody ever does this, and if you need to, then you will probably have other issues to solve (like PK generation, etc), so you'll need a little work here anyway.

What I would love to know, is how people using Weblogic + Oracle solve this. They are on a the full Oracle stack, so they must have some solution, probably non-standard. I'm going to look for this, but if anybody knows, please add some comment.

**Comment by jdubois** [comment] 2016-08-10 08:41
- I have no idea how people using Weblogic + Oracle handle this. I couldn't find anything :-(
- I've looked at our stats, and that's 0,84% of our users who use Oracle in production. I don't want to do something too specific for such a small share of our users.

I think my current "solution" should handle a lot more cases than the previous one, as we now take as many characters as possible. Then, if that's not enough, we can add two things:

- A big warning message during generation when this situation occurs -> I'm doing this right now
- Some documentation on the Oracle page about this

Then, if we want something really clean, the best solution would be to add a new question:

- When there is a table name of fk length issue, ask the user a specific question: "The generated table name is too long (you have reached the 30 character limit on Oracle), please enter a table name manually:"
- Then we need to store this in our .json files
- And of course use it everywhere

But that means a lot of work and maintenance, and for 0,84% of our users I am not going to do this now. As this is for people with lots of $$$, maybe some of those users would be ready to contribute this themselves? Or "sponsor" the feature?

**Comment by jdubois** [comment] 2016-08-10 09:39
I added the warning and the documentation.

The "truncate" option will solve most issues, as we now have much bigger FK and join tables than we used to have.

It's also the option with the less maintenance for us, and we don't modify anything for people using MySQL & Postgresql, which are our top users.

Of course the solution with a new question would be better, but that's more maintenance for us, and I don't have the time to code this -> if anyone wants to do it, a PR will be most welcome, but at the moment I'm closing this

**Closed by jdubois** 2016-08-10 09:39 UTC
Labels: bug

**Comment by deepu105** [comment] 2016-08-10 16:43
@jdubois lets not go the new question way, thats too much maintenance, the warning and documentation is sufficient.

I have only one concern with the new solution, as I explained earlier it would at times produce meaningless table names, and sometimes names would end with an `_` which is not very neat. by trimming of the name we are not following JPA spec anyway so why not ensure that there is no dangling `_` and just truncate each name so that the result is still somewhat meaningfull, the below would reduce the chance of duplicate cases even further, I have removed the `_MP` suffix as well. what do you think?
```
 Generator.prototype.getJoinTableName = function (entityName, relationshipName, prodDatabaseType) {
    var joinTableName = this.getTableName(entityName) + '_'+ this.getTableName(relationshipName);
    var limit = 0;
    if (prodDatabaseType === 'oracle' && joinTableName.length > 30) {
        this.log(chalk.red('WARNING!') + ' The generated join table \"' + joinTableName + '\" is ' +
            'too long for Oracle (which has a 30 characters limit). It will be truncated!');

        limit = 30;
    }
    if (prodDatabaseType === 'mysql' && joinTableName.length > 64) {
        this.log(chalk.red('WARNING!') + ' The generated join table \"' + joinTableName + '\" is ' +
            'too long for MySQL (which has a 64 characters limit). It will be truncated!');

        limit = 64;
    }
    if (limit > 0) {
        var halfLimit = Math.floor(limit/2),
        entityTable = getTableName(entityName.substring(0, halfLimit)),
        relationTable = getTableName(relationshipName.substring(0, halfLimit-1));
        return `${entityTable}_${relationTable}`;
    }
    return joinTableName;
};
```

**Comment by deepu105** [comment] 2016-08-10 16:56
Btw @jdubois I have used Oracle many times as my client has Oracle as the enterprise primary DB, I have also done weblogic + Oracle (Non JH apps)  and Jboss + Oracle (JH app) but in both cases we manually made sure the Table names are within the limit :smile:  And ofcourse we didnt follow the JPA convention there as it was plain stupid given the limitation :smiling_imp:

**Comment by systemsplanet** [comment] 2016-08-10 17:58
Bottom line: complexity kills projects

Least Common Denominator
There is nothing simpler than supporting  the least common denominator.
Once you've mastered that, then provide a path upstream by providing paid
services to support the best of the best... In this case, it may be too
late to force all constraints to the smallest ..as it would break backward
compatibility.

Generator Knowledge base
If not minimum, then bite the bullet and create a persisting dynamic
knowledge base (tables of constraints for all generated tech, eg Databases,
Caches, etc) that the generator consults  to generate any artifact.  The
windows registry is an example, but using yml or and embedded database for
persistence.

mike lawrence    404 841 7800

**Comment by deepu105** [comment] 2016-08-10 18:17
@systemsplanet I agree with you but lets talk real world scenario here. If you are creating a real world app with JHipster that uses oracle, you are gonna do a lot of changes to the generated project anyway and the chances that you get a duplicate join table name are low but still present. But it would be still easy to just change in the generated liquibase file as you are gonna make modification anyway. I know not a great argument but isnt that the reality? so do we really have to complicate stuff so much to address the scenario completely? IMO current solutions are good enough

**Comment by systemsplanet** [comment] 2016-08-10 18:26
How about requiring a 2-5 character short name annotation for each entity?
When a generated name (sequence, trigger, constraint)  is too large, use the short name. Guaranteed to fit.
@JHShortName ("USER")

**Comment by systemsplanet** [comment] 2016-08-10 18:30
I'm not editing the liquibase (or anything else)  if I can avoid it.
The less you change the easier your upgrade will be.
I'd like to see a maven module added for extendeding the generated project.
Every change to generated code is more work / risk for the user.

**Comment by deepu105** [comment] 2016-08-10 18:31
Again I dont like to add more questions which is useful only to few users,
we already have a command line key to specify the table name and I guess
that would be a good choice if you want to have a shorter table name for a
long entity name


Thanks & Regards,
Deepu

**Comment by deepu105** [comment] 2016-08-10 18:33
we are thinking about a new architecture to make upgrading easier, but that
would be for JHipster 5.0 or more


Thanks & Regards,
Deepu

**Comment by systemsplanet** [comment] 2016-08-10 18:34
How about defaulting the short name 

I just don't think generation should ever fail 

When it does, you probably just lost a potential contributor.

**Comment by deepu105** [comment] 2016-08-10 18:38
@systemsplanet the problem is that if we start doing more than we can bite then the project is gonna become too big to maintain for us, unless some big company is gonna sponsor. We cannot do everything so we compromise when required. you could very well use the `--table-name` flag to pass a shorter name for tables as a workaround already

**Comment by jdubois** [comment] 2016-08-11 07:25
Yes I like this idea with the --table-name : so in fact it works with this
option? For me this is good: we an easy solution for 99,9% of people, and
otherwise there is an advanced settings.

Le 10 août 2016 8:38 PM, "Deepu K Sasidharan" <notifications@github.com> a
écrit :

**Comment by systemsplanet** [comment] 2016-08-12 06:36
The user experience is
Run generator
Answer questions
Long build process
Run app
Database error.


Maybe we should do some basic validation as the user enters Entity and Property names.  Warn them after each entry that names over N characters may result in generation errors.

We could warn anytime any if these reserve words are used: 

https://github.com/mybatis/generator/blob/master/core/mybatis-generator-core/src/main/java/org/mybatis/generator/internal/db/SqlReservedWords.java


If we start by asking "JDBC database URL? 
(Optionally, used to improve generation quality)

**Comment by jdubois** [comment] 2016-08-12 07:06
- Yes more warning is good. We could also add the tip there, for the --table-name option, when the table name is too long. Or maybe even add a new question for the table name, if the entity name is too long? This would make everybody happy, I think -> if you agree with that, let's reopen this
- We already have a "reserved keyword" dictionary -> maybe we miss some keywords, but I haven't seen any issue there for a long time
- The database introspector would be good, but here you come to one of the big JHipster limitation: it's a NodeJS project, we can't use any of those Java/JDBC classes.

**Comment by systemsplanet** [comment] 2016-08-12 07:26
Sounds good to me.

Why not start  generator from a maven module so it can extract the
database  metadata to a property file, install a local nodejs if needed,
then kick off generator?

Maybe one day Oracle will invest in their JS Engine, so it competes with
Google,  and makes JS to Java integration seamless.

mike lawrence    404 841 7800

On Aug 12, 2016 3:06 AM, "Julien Dubois" <notifications@github.com> wrote:


   - Yes more warning is good. We could also add the tip there, for the
   --table-name option, when the table name is too long. Or maybe even add a
   new question for the table name, if the entity name is too long? This would
   make everybody happy, I think -> if you agree with that, let's reopen this
   - We already have a "reserved keyword" dictionary -> maybe we miss some
   keywords, but I haven't seen any issue there for a long time
   - The database introspector would be good, but here you come to one of
   the big JHipster limitation: it's a NodeJS project, we can't use any of
   those Java/JDBC classes.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/jhipster/generator-jhipster/issues/3839#issuecomment-239376087>,
or mute the thread

**Comment by jdubois** [comment] 2016-08-12 07:42
- For the table name, I'll open up a specific issue for that
- For Maven: the issue is that Maven itself is installed by JHipster... The only solution I have at the moment would be to access the database from NodeJS
